checkstyle/checkstyle

- src/xdocs/beginning_development.xml
just based on multiple questions in  gitter on how to build our project.
> doc: extend beginning development with step to build in terminal before IDE

- config/checkstyle_non_main_files_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOther.java
> Issue #10625: Fixed InputMissingOverrideBadOverrideFromOther.java and removed it form line length suppression

- config/checkstyle_non_main_files_suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSkipIfLastAndSharedWithCase.java
> Issue #10625: Fixed an Input file and removed it from line length suppression

- config/checkstyle_non_main_files_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
> Issue #10625: Fixed two input files and removed them from line length suppression

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElementTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/XpathUtilTest.java
Issue #9142
Not as many as the other so this was manually done.
> Issue #9142: resolve Assertions.assertNotEquals

- wercker.yml
reactivate no-exception-checkstyle-sevntu after updating projects file at https://github.com/checkstyle/contribution/pull/589
> infra: reactivate no-exception-checkstyle-sevntu

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java
> Issue #9142: resolve Assertions.assertSame

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java
> Issue #9142: resolve Assertions.assertNotSame

- config/checkstyle_non_main_files_suppressions.xml
> Issue #10625: Removed the old suppression related text

- config/spotbugs-exclude.xml
Issue #11140
Testing CI as I got no failures locally.
> Issue #11140: resolve FCBL_FIELD_COULD_BE_LOCAL

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressionsThree.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckPatterns.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/overloadmethodsdeclarationorder/InputOverloadMethodsDeclarationOrder.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingTrue2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEquality.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java
Issue #6320
This is for coding package only.
> Issue #6320: added test cases from regression for missing mutation

- config/checkstyle_checks.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
> Issue #9889: Prevent usage of 'getFileContents()' method in code

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
Issue #6320
Identified at #11157 .
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/IllegalTypeCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@56791346_450
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/IllegalTypeCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@56791346_521
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/IllegalTypeCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@56791346_670
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/IllegalTypeCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@56791346_8 …
> Issue #6320: resolution for IllegalTypeCheck

- config/spotbugs-exclude.xml
Issue #11140
No violations locally.
> Issue #11140: resolve WOC_WRITE_ONLY_COLLECTION_FIELD

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
Issue #6320
Identified at #11157 .
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/MagicNumberCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@6bbc669_489
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/MagicNumberCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@6bbc669_570
> Issue #6320: resolution for MagicNumberCheck

- config/spotbugs-exclude.xml
Issue #11140
No violations locally.
> Issue #11140: resolve OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

- config/checkstyle_checks.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageLexer.g4
- src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4
- src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocLexer.g4
- src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocParser.g4
Identified at https://github.com/checkstyle/checkstyle/issues/11203#issuecomment-1013910863
> infra: adds headers to all grammars and enforced by checkstyle

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionVariableDeclarationUsageDistanceTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/variabledeclarationusagedistance/SuppressionXpathRegressionVariableDeclarationUsageDistance1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/variabledeclarationusagedistance/SuppressionXpathRegressionVariableDeclarationUsageDistance2.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationNoNpe.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodExtendAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorHeader.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorImports.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleTypeVariables.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments2.java
Identified at https://github.com/checkstyle/checkstyle/issues/11203#issuecomment-1013910992
> minor: remove unnecessary headers from input files

- .github/workflows/bump_license_year.yml
From https://github.com/checkstyle/checkstyle/pull/11204#issuecomment-1013921598
minor: Add required permissions to bump_license_year.yml
> minor: Add required permissions to bump_license_year.yml

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForArrayDeclarator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForEllipsis.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestDot.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestMethodRef.java
> Issue #11091: Fail test execution when input file hasn't specified violation messages

- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
> minor: fix mistype in TreeWalkerTest

- .ci/jsoref-spellchecker/whitelist.words
- .ci/validation.sh
- .travis.yml
Opened at the request of @romani ; see https://github.com/jqno/equalsverifier/issues/586
> Updates EqualsVerifier pom version variable

- .ci/travis.sh
- .travis.yml
https://github.com/checkstyle/checkstyle/pull/11247 showcases the issue and the fix.
> infra: resolves issue with travis ensuring no git differences

- .semaphore/semaphore.yml
Part of #9146 
Cherry-picked to diagnose the Semaphore CI issue.
> infra: disable NonDex due to incompatibility with Java11

- .ci/no-exception-test.sh
> Issue #11281: Removed extra checkstyle build in no-exception-test.sh

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java
- src/xdocs/config_coding.xml
Fixes #7657 
**$ cat config.xml**
```
<module name="ReturnCount">
<property name="max" value="3"/>
</module>
</module>
</module>
```
**$ cat MyClass.java**
```
public int sign(int x) {
if (x < 0)
return -1;
if (x == 0)
return 1;
return 0;
} // OK
public int badSign(int x) {
if (x < -2)
return -2;
if (x == 0)
return 0;
if (x > 2)
return 2;
return 1;
} // violation, more than three return statements
}
```
```
PS C:\Users\Dell\Desktop\Checkstyle\Test> javac MyClass.java
PS C:\Users\Dell\Desktop\Checkstyle\Test> java -jar checkstyle-9.2-all.jar -c config.xml …
```
> Issue #7657: Update doc for ReturnCount

- pom.xml
From https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=7637&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=609
> config: bump sonar plugin to 3.9.1.2184

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterVarargs.java
- src/xdocs/config_whitespace.xml
Resolves #11116
Final Report (Clean) : https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7e745f8_2022191620/reports/diff/index.html
> Issue #11116: Added ELLIPSIS support to WhitespaceAfterCheck

- .ci/validation.sh
- config/suppressions.xml
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterSwitchStatements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLambdaExpressions.java
- src/xdocs/config_whitespace.xml
Resolves #11298 
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/97410d450226ecfe8c45df4f2693cd61c25c3765/my_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Vyom-Yadav/273327b9c6cd6963b7dade792bc2c9c2/raw/a2715eb5a51a57dec2e34472a9797abf85f267db/patch_config.xml
---
PMD PR - https://github.com/pmd/pmd/pull/3767
Orekit PR - https://github.com/CS-SI/Orekit/pull/29
> Issue #11298: Added switch statements and lambda support to WhitespaceAfter

- src/xdocs/index.xml.vm
Issue #9146
Update documentation for backport.
> Issue #9146: update backport section for changes for jdk11

- pom.xml
permanent failre - https://github.com/checkstyle/checkstyle/runs/5259529581?check_suite_focus=true
```
<td><i><a class="externalLink" href="https://travis-ci.com/">https://travis-ci.com/</a>: 403 Forbidden</i></td></tr></table></td></tr>
Ex
```
> config: remove travis from line check

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRedundantImportTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/redundantimport/SuppressionXpathRegressionRedundantImport1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/redundantimport/SuppressionXpathRegressionRedundantImport2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/redundantimport/SuppressionXpathRegressionRedundantImport3.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partial for Issue: #6207
Add xpath regression test for RedundantImport
> Issue #6207: Add Xpath Regression Test for RedundantImport

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/modifier/RedundantModifierCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedClassInPublicInterfaceRedundantModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedDef.java
- src/xdocs/config_modifier.xml
Resolves #11268
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/2984d7a7e418099c61e407c3dd56748ba5cada87/my_checks.xml
---
Diff Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e6cae19_2022205859/reports/diff/index.html
Website: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e6cae19_2022054921/config_modifier.html#RedundantModifier
> Issue #11268: Fix false negative in RedundantModifierCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
- src/xdocs/config_misc.xml
Fixes #7588
\> type config.xml
```
<module name="FinalParameters">
</module>
</module>
</module>
```
\> type Point.java
```
public class Point {
public Point() { } // ok
public Point(final int m) { } // ok
public Point(final int m,int n) { } // violation, n should be final
public void methodOne(final int x) { } // ok
public void methodTwo(int x) { } // violation, x should be final
public static void main(String[] args) { } // violation, args should be final
}
```
```
C:\Users\DELL\Desktop\tests>java -jar checkstyle-9.2.1-all.jar -c config.xml Point.java
[ERROR] …
```
> Update doc for FinalParameters #7588

- src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
- src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Follow up of #9146 
Minor refactoring suggested by IDEA.
> minor: use java-11 api

- .ci/pitest.sh
- pom.xml
Issue https://github.com/checkstyle/checkstyle/issues/6320
Added new mutator and starting list.
>  Issue #6320: add remove conditionals mutator for coding package 

- src/xdocs/releasenotes.xml
I noticed that I forgot to set my username to my real name in my local git setup.
> minor: change "nmancus1" to "Nick Mancuso" in release notes

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalTokenTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltoken/SuppressionXpathRegressionIllegalToken1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltoken/SuppressionXpathRegressionIllegalToken2.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partial for Issue: #6207
Add xpath regression test for IllegalToken
> Issue #6207: Add Xpath Regression Test for IllegalToken

- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObject.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOther.java
Issue #11166, fix for MissingOverrideCheck
Report (clean) https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/9a93e0a_2022174334/reports/diff/index.html
Diff Regression config: https://gist.githubusercontent.com/strkkk/4dbcf7e137f836e68638c2422e540082/raw/6b187ffa6c09f6b659e013a7510b4d669b427cd6/config2.xml
> Issue #11166: remove getFileContents from missing override

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullSuperClass.java
Issue #11214 Specified violation message in EqualsAvoidNullCheck
> Issue #11214: Specified violation message in EqualsAvoidNullCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterSwitchStatements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterBraces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterCountUnicodeCorrectly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterDefaultConfig.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterDoWhile.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterFor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLambdaExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralDo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralElse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralFor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralIf.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralWhile.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterMultilineCast.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterTypeCast.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterVarargs.java
> Issue #11214: specified violation message in WhiteSpaceAfterCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountInterfaceMemberScopeIsPublic.java
Issue #11214 Specified violation message in MethodCountCheck
> Issue #11214: Specified violation message in MethodCountCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceAtStartOfTheLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceMethodRef2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceNested.java
Issue #11214  Specified violation message in GenericWhitespaceCheck
> Issue #11214: Specified violation message in GenericWhitespaceCheck

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java
Same check is in multiple places, so extract common method
Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/54d6f5aa9f33b6f47a305772c469d872239049eb/config_single.xml
> Pull #11133: refactor check for override annotation - add util method

- .drone.yml
> config: make container name to be explicit as each step is independend in pipeline

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplevariabledeclarations/InputMultipleVariableDeclarations.java
Issue #11214: Specified violation message in MultipleVariableDeclarationsCheck
> Issue #11214: Specified violation message in MultipleVariableDeclarationsCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAround2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAfterEmoji.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyTypesAndNonEmptyClasses.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyTypesAndNonEmptyClasses2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundArrayInitialization.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundBraces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundBraces2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundDoWhile.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundDoubleBraceInitialization.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundKeywordsAndOperators.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSimple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundStartOfTheLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundVarargs.java
Issue #11214: specified violation message in WhitespaceAroundCheck
> Issue #11214: specified violation message in WhitespaceAroundCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileCrlf.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileNoNewline.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileNoNewline2.java
Issue #11214: Specified violation message in NewlineAtEndOfFileCheck
> Issue #11214: Specified violation message in NewlineAtEndOfFileCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/modifier/RedundantModifierCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierRecords.java
- src/xdocs/config_modifier.xml
Resolves #11259 
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/2984d7a7e418099c61e407c3dd56748ba5cada87/my_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/2984d7a7e418099c61e407c3dd56748ba5cada87/my_checks.xml
> Issue #11259: Add record support to RedundantModifier

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocHtmlFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineForbidden.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriodAtEnd.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/inputs/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/package-info.java
Resolves #11030: Enhance logging approach of SummaryJavadocCheck
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/9dd91cdba86d998f8fee9d271c0368258aa3deb6/my_checks.xml
Report final - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/f07d6a3_2022150937/reports/diff/index.html
> Issue #11030: Enhanced logging approach of SummaryJavadocCheck and used AST-based approach to get content of inline tag.

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockWithEmoji.java
Issue #10924: Updated `EmptyBlockCheck` to use code point.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/a223cbe737a095b9020b0380039581dd/raw/ccc15a31b10b75efda1f6dec6d228aca8b96cc9d/config.xml
First commit is under review
> Issue #10924: Updated EmptyBlockCheck to use code point.

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCheckWithEmoji.java
> minor: Updated Inputs for CommentsIndentationCheck

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnArrInitWithEmoji.java
> minor: Updated Inputs for AnnotationArrayInitHandler

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationArrayInitIndentWithEmoji.java
> minor: Updated Inputs for ArrayInitHandler

- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithEmoji.java
> minor: Updated Inputs for EmptyLineSeparatorCheck

- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java
Minor fixes pulled from https://github.com/checkstyle/checkstyle/pull/11280
> minor: small fixes and improvements for various test assertions

- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyWithEmoji.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyWithEmojiNl.java
> minor: Updated Inputs for LeftCurlyCheck

- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodIgnoreThrows.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperNoCodeInFileCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperSummaryJavadocCheck.java
Issue https://github.com/checkstyle/checkstyle/issues/4845
Targeted DetailAST and DetailNode and switch them to String.
> Issue #4845: removed usage of DetailAST/Node from inputs

- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/InputEmptyLineSeparator.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputEmptyLineSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowStaticMember.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportExcludes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportWithChecker.java
Issue https://github.com/checkstyle/checkstyle/issues/4845
Targeted Checker and ones next to them. The import inputs seem like copy/pastes.
> Issue #4845: removed usage of Checker and similar from inputs

- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapBad.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapBad2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapGood.java
Issue https://github.com/checkstyle/checkstyle/issues/4845
Targeted TreeWalker.
> Issue #4845: removed usage of TreeWalker from inputs

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPadWithEmoji.java
Issue #10924: Updated EmptyForInitializerPadCheck to use code points.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/d0d6599dd257421f2e97c2237a7e9d8d/raw/50a659961e7cd57d052ac01c14dff0fcba07852e/config.xml
> Issue #10924: Update EmptyForInitializerPadCheck to use code points.

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterWithEmoji.java
Issue #10924: Updated WhitespaceAfterCheck to use code point.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/b0e2f949855c6f9625f3287f4cca6670/raw/78de9bc3b0f904016fc250036d66b130b41ffe29/config.xml
> Issue #10924: Update WhitespaceAfterCheck to use code points

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckWithEmoji.java
Issue #10924: Updated MethodParamPadCheck to use code points
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/32669c2249de13c50e3932982d828928/raw/90afd2693a5e8d65d846da75d433a5ad170edc18/config.xml
> Issue #10924: Update MethodParamPadCheck to use code points

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPadWithEmoji.java
Issue #10924: Updated EmptyForIteratorPadCheck to use code points
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/a5ed25df531799658d100b0e643c2942/raw/ff2499c0432bd8c5e152b3847489284f1a51e094/config.xml
> Issue #10924: Update EmptyForIteratorPadCheck to use code points

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationFirstLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/package-info.java
Issue #11214: Specified violation message in JavadocContentLocationCheck
> Issue #11214: Specified violation message in JavadocContentLocationCheck

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterByCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterByCheckAndId.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterByCheckAndMessage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterByCheckAndNonMatchingId.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterByIdAndMessage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterCheckC.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterCheckCpp.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterInfluenceFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterUsingNonMatchingVariableMessage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterUsingTagMessageRegexp.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterUsingVariableCheckOnNextLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterUsingVariableCheckOnPreviousLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterUsingVariableMessage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterVariableCheckOnVariableNumberOfLines.java
> Issue #10737: Migrate to inline config parser for SuppressWithNearbyCommentFilter

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswarningsfilter/InputSuppressWarningsFilterById.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswarningsfilter/InputSuppressWarningsFilterWithoutFilter.java
> Issue #10737: Migrate to inline config parser for SuppressWarningsFilterTest

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceWithEmoji.java
Issue #10924: Updated GenericWhitespaceCheck to use code points
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/29772ece533f2a32313bd9baf085809d/raw/69aa032d1ed30f9996663b15a531729b6e4d35f9/config.xml
> Issue #10924: Update GenericWhitespaceCheck to use code points

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapGuardedPatterns.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapArrayAssign.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapEol.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapNl.java
Issue #11214: Specified violation message in OperatorWrapCheck
> Issue #11214: Specified violation message in OperatorWrapCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughWithEmoji.java
Issue #10924: Updated FallThroughCheck to use code points
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/cb3ffe158a0eb42df8ab37b07e8f6401/raw/1418b03a040cb0727788758b26f4fbcfbb67d862/config.xml
> Issue #10924: Update FallThroughCheck to use code points

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterWithCustomOnAndOffComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterWithDefaultCfg.java
> Issue #10737: Migrate to inline config parser in SuppressWithPlainTextCommentFilterTest

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilterTest.java
Resolves #10737 
To reviewers - Only the last commit is under consideration
> Issue #10737: Migrate to inline config parser for SuppressionSingleFilterTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
just one exclude from Issue #10390
> Issue #10390: resolve forbiddenapi exclude for LineLengthCheckTest

- config/checkstyle_checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/LineLengthCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthIgnoringImportStatements.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthIgnoringPackageStatements.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongPackageStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongImportStatements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthUnicodeChars.java
- src/xdocs/config_sizes.xml
Resolves #10907
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/43b60083c738ca023812deccdfe888c32f1de126/my_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/43b60083c738ca023812deccdfe888c32f1de126/my_checks.xml
---
Report (clean): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7e5e027_2022123723/reports/diff/index.html
> Issue #10907: Modify LineLengthCheck to support validating import and package statements

- config/pmd.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
> Issue #11201: Moved methods common in UnusedLocalVariableCheck and FinalClassCheck to util

- config/checkstyle_input_suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
Removed closed issues that are still referenced in files
> minor: Remove closed issues that are still referenced in files

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalImportTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegalimport/SuppressionXpathRegressionIllegalImportOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegalimport/SuppressionXpathRegressionIllegalImportTwo.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partially Fixes Issue #6207 Add Xpath Regression Test for IllegalImport
> Issue #6207: Add Xpath Regression Test for IllegalImport

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllSinglelineCommentsTest.java
Resolves update for AllSinglelineCommentsTest in #11446.
This PR will serve as example for associated issue
> Issue #11446: Update AllSinglelineCommentsTest to use verifyWithInlineConfigParser

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorCommentsWithEmoji.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorWithEmoji.java
Issue #10924: Updated SingleSpaceSeparatorCheck to use code points
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/d9d164ab79b55379349d030e1a283951/raw/dd8a4741763c00448c7d45c3bf0d1fd4372e1364/config.xml
> Issue #10924: Update SingleSpaceSeparatorCheck to use code points

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterAcceptOnNullFile.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterAcceptOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterAcceptTwo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterAcceptWithOptionalTrue.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeChar.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeChar.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeString.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeString.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterIdAndQuery.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterNonExistentFileWithTrueOptional.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterReject.java
> Issue #11438: Converted test for SuppressionXpathFilterTest to use inlined config in Input files

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalTypeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltype/SuppressionXpathRegressionIllegalTypeOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltype/SuppressionXpathRegressionIllegalTypeTwo.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath Regression Test for IllegalType

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOperatorWrapTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/operatorwrap/SuppressionXpathRegressionOperatorWrapNewLine.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/operatorwrap/SuppressionXpathRegressionOperatorWrapPreviousLine.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207: Add Xpath Regression Test for OperatorWrap
> Issue #6207: Add Xpath Regression Test for OperatorWrap

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineForbidden.java
Resolves #11213 
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/9dd91cdba86d998f8fee9d271c0368258aa3deb6/my_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/0f5845d0050e1b515298271e63c59a829d1d5aae/projects-to-test-on.properties
Final Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a906e6a_2022072602/reports/diff/index.html
> Issue #11213: Fixed false positive in SummaryJavadocCheck

- pom.xml
Update hardcoded version to property
> minor: change java version for modernizer plugin

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMethodNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodname/SuppressionXpathRegressionMethodName1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodname/SuppressionXpathRegressionMethodName2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodname/SuppressionXpathRegressionMethodName3.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207: Add Xpath Regression Test for MethodName
> Issue #6207: Add Xpath Regression Test for MethodName

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMemberNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/membername/SuppressionXpathRegressionMemberName1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/membername/SuppressionXpathRegressionMemberName2.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207: Add Xpath Regression Test for MemberName
> Issue #6207: Add Xpath Regression Test for MemberName

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionTypeNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/typename/SuppressionXpathRegressionTypeName1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/typename/SuppressionXpathRegressionTypeName2.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207: Add Xpath Regression Test for TypeName
> Issue #6207: Add Xpath Regression Test for TypeName

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImport_UnnamedPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportCheckClearState.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportWithChecker.java
Issue #11214: specified violation message in RedundantImport
> Issue #11214: specified violation message in RedundantImport

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughDefault.java
Issue: #11214 (FallThroughCheck)
> Issue #11214: Specified violation message in FallThroughCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
> Issue #11214: Moved UniquePropertiesCheck from SUPPRESSED_CHECKS to PERMANENT_SUPPRESSED_CHECKS collection

- .ci/jsoref-spellchecker/whitelist.words
- config/version-number-rules.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractGuiTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/MainTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/TreeTableTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/gui/main/InputMain.java
- src/test/resources/com/puppycrawl/tools/checkstyle/gui/mainframe/InputMainFrame.java
- src/test/resources/com/puppycrawl/tools/checkstyle/gui/treetable/InputTreeTable.java
Issue #11475 
Tests for `Main`, `MainFrame` and `TreeTable`.
> Issue #11475: unit tests for gui

- appveyor.yml
Detected at https://github.com/checkstyle/checkstyle/pull/11477#issuecomment-1086667161
> config: update maven to 3.8.5 as 3.8.4 is not downloadable

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralTry.java
- src/xdocs/config_whitespace.xml
Resolves #11489 
Diff Regression config: https://gist.githubusercontent.com/Rahulkhinchi03/27b23af58be50c8ac5be9e3d44db6742/raw/288d528568ed0f9959360736b0abb63ff9df14a8/config.xml
Diff Regression patch config: https://gist.githubusercontent.com/Rahulkhinchi03/f6f4d6939dd8ac952b9fce093d33ea60/raw/47b475a36fadd791c6c3fe49972771829b7feaea/patch_config.xml
> Issue #11489: Add LITERAL_TRY token support to WhitespaceAfter

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/InputSuppressWithNearbyCommentFilterByCheckAndInfluence.java
Resolves update for SuppressionWithNearbyCommentFilterTest in https://github.com/checkstyle/checkstyle/issues/11446.
> Issue #11446: Update SuppressionWithNearbyCommentFilterTest to use verifyWithInlineConfigParser

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralFinally.java
- src/xdocs/config_whitespace.xml
Resolves #11493 
Diff Regression config: https://gist.githubusercontent.com/Rahulkhinchi03/27b23af58be50c8ac5be9e3d44db6742/raw/288d528568ed0f9959360736b0abb63ff9df14a8/config.xml
Diff Regression patch config: https://gist.githubusercontent.com/Rahulkhinchi03/f6f4d6939dd8ac952b9fce093d33ea60/raw/47b475a36fadd791c6c3fe49972771829b7feaea/patch_config.xml
> Issue #11493: Add LITERAL_FINALLY token support to WhitespaceAfter

- .ci/openjdk17-excluded.files
Found at https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/514d736_2022085653/reports/diff/openjdk17/index.html#A3
> minor: remove duplicate exclusion in openjdk17-excluded.files 

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder5.java
> minor: changed the input file path in test file

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralCatch.java
- src/xdocs/config_whitespace.xml
Resolves #11498 
Diff Regression config: https://gist.githubusercontent.com/Binita-tech/76be87d6c361ab5305863361aef3de15/raw/b207f4d59a809e58e13b45863e94479b7b3226e2/config.xml
Diff Regression patch config: https://gist.githubusercontent.com/Binita-tech/6fbe5f120efde70be0ad345079f86acc/raw/ef0b6c9270a7f0c03d82c67ce4ef9f2ed19be38f/patch_config.xml
> Issue #11498: Added LITERAL_CATCH token support to WhitespaceAfter

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionThrowsCountTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/throwscount/SuppressionXpathRegressionThrowsCount1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/throwscount/SuppressionXpathRegressionThrowsCount2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/throwscount/SuppressionXpathRegressionThrowsCount3.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath Regression Test for ThrowsCount

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionStringLiteralEqualityTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/stringliteralequality/SuppressionXpathRegressionStringLiteralEquality.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/stringliteralequality/SuppressionXpathRegressionStringLiteralEquality1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/stringliteralequality/SuppressionXpathRegressionStringLiteralEquality2.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath Regression Test for StringLiteralEquality

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUpperEllTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/upperell/SuppressionXpathRegressionUpperEllFirst.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/upperell/SuppressionXpathRegressionUpperEllSecond.java
Resolves `XpathRegressionUpperEllTest` in https://github.com/checkstyle/checkstyle/issues/8151
> Issue #8151: Update XpathRegressionUpperEllTest to have atleast 2 tests

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestSwitchExpressions.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestSwitchExpressionsNewLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefaultTestNl.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefaultTestNlow.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnumsOptFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnumsOptTrue.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyMethodTestNewLine2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestCoverageIncrease.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefaultLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefaultWithAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestEolSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestLineBreakAfter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestMissingBraces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNewLine3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNewLineOptionWithLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlWithAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlowSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlowWithAnnotations.java
> Issue #11214: Specified violation message in LeftCurlyCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2Statement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2Text.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticText.java
Issue #11214 
Specified violation message in EmptyBlockCheck.
> Issue #11214: Specified violation message in EmptyBlockCheck

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralReturn.java
- src/xdocs/config_whitespace.xml
Resolves #11536 
Diff Regression config: https://gist.githubusercontent.com/Rahulkhinchi03/27b23af58be50c8ac5be9e3d44db6742/raw/288d528568ed0f9959360736b0abb63ff9df14a8/config.xml
Diff Regression patch config: https://gist.githubusercontent.com/Rahulkhinchi03/f6f4d6939dd8ac952b9fce093d33ea60/raw/47b475a36fadd791c6c3fe49972771829b7feaea/patch_config.xml
> Issue #11536: Added support for LITERAL_RETURN token in WhitespaceAfter

- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
Noticed at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/567406582 and https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/567482195, we have somehow damaged master build with this commit: 1d29e97c030935ce2e7ce13a5e7014a9944b0f7e
Link to Travis build that must pass in this PR: https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/567487468
> minor: fix failing master build (related to #11536)

- .ci/jsoref-spellchecker/whitelist.words
- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
Issue #11528 
The rationale is explained [here](https://github.com/checkstyle/checkstyle/issues/11427#issuecomment-1102539871).
Does not resolve the complete issue.
> Issue #11528: Kill surviving mutation in EqualsAvoidNullCheck

- config/intellij-idea-inspections.xml
- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableCellRenderer.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
> Resolve IDEA violations from Teamcity 2022.04

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
> Issue #11214: Moved TranslationCheck from SUPPRESSED_CHECKS to PERMANENT_SUPPRESSED_CHECKS collection

- .drone.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/check-pr-description.yml
- config/intellij-idea-inspection-scope.xml
- config/intellij-idea-inspections.properties
Issue #11566
Scope:
THIS IS FALSE POSITIVE, there is no such properties
.circleci/config.yml (1)
Schema validation: Missing required properties 'body', 'description', 'name'
https://docs.drone.io/pipeline/configuration/, FiXED
.drone.yml (6)
Schema validation: One of the following property sets is required: property 'type' or property 'type'
Schema validation: One of the following property sets is required: property 'type' or property 'type'
Schema validation: One of the following property sets is required: property 'type' or property 'type'
Schema validation: One of the following property sets is required: property 'type' or property 'type'
Schema validation: One of the following property sets is required: property 'type' or property 'type'
Schema validation: One of the following …
> Issue #11566: fix insection violations 'Validation by JSON Shema'

- config/intellij-idea-inspection-scope.xml
- config/intellij-idea-inspections.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTags.java
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
> Temp disable of inspections

- config/intellij-idea-inspections.xml
> Issue #11566: temporal disablement of grammar inspection

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheck.java
- src/xdocs/config_coding.xml
Fixes Issue https://github.com/checkstyle/checkstyle/issues/7662
> Issue #7662: Update doc for SuperFinalize 

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
> Issue #11214: Specified violation message in RegexpOnFilenameCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountSwitches.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountSwitches2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountVoid.java
> Issue #11214: specified violation message in ReturnCount

- .ci/pitest.sh
- config/spotbugs-exclude.xml
- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControl.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/ParserUtil.java
Part of #11140 
In fact, this is nano optimization with zero impact. But this forces us to add more variables to the code. This makes the code readable and easy to debug.
There is a false-positive for `Checker` and `TreeWalker`. See https://github.com/mebigfatguy/fb-contrib/issues/329 for the details.
> Issue #11140: solve PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableTernaryAndExpressions.java
Closes #11588.
Diff Regression config: https://gist.githubusercontent.com/nick-mancuso/858f3ef5e63e12540b71a3e514acdf52/raw/b9e3d229bb0e226cfb11b98e5e3c26895c26faa7/config.xml
> Issue #11588: Resolve SimplifiableIfStatement inspection violations

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
> Issue #11214: Specified violation message in EqualsHashCodeCheck

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisCatchVariables.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExtendedMethod.java
#11528 
https://github.com/checkstyle/checkstyle/blob/78ef41d24560f880052f02a049da80e560580996/.ci/pitest.sh#L212
---
```xml
<module name="RequireThis"/>
```
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/cbab1ad_2022060550/reports/diff/index.html
---
```xml
<module name="RequireThis">
<property name="validateOnlyOverlapping" value="false"/>
</module>
```
WithoutOpenJDK - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/db6616b_2022050743/reports/diff/index.html
Report for open JDK - https://vyom-yadav.github.io/DiffReport/diffRequireThisOpenJDK/index.html
> Issue #11528: Kill surviving mutation in RequireThisCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl12.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl13.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl14.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl15.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl16.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl162.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl163.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl17.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl19.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl21.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl22.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlDisallowClassOfAllowPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl_Blacklist.java
Issue #11214: Specify violation messages for ImportControlCheck
> Issue #11214: Specify violation messages for ImportControlCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralYield.java
- src/xdocs/config_whitespace.xml
Resolves #11508 
Diff Regression config: https://gist.githubusercontent.com/Binita-tech/76be87d6c361ab5305863361aef3de15/raw/b207f4d59a809e58e13b45863e94479b7b3226e2/config.xml
Diff Regression patch config: https://gist.githubusercontent.com/Binita-tech/6fbe5f120efde70be0ad345079f86acc/raw/ef0b6c9270a7f0c03d82c67ce4ef9f2ed19be38f/patch_config.xml
> Issue #11508: Added LITERAL_YIELD token support to WhitespaceAfter

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
- src/xdocs/config_whitespace.xml
Issue #7617: Update doc for EmptyForInitializerPad
> Issue #7617: Update doc for EmptyForInitializerPad

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/NoWhitespaceAfterCheck.xml
- src/xdocs/config_whitespace.xml
Fixes issue for NoWhitespaceAfterCheck #7624
> Issue #7624: Updated doc for NoWhitespaceAfterCheck

- config/checkstyle_resources_suppressions.xml
- config/suppressions.xml
As title suggests. Identified through https://github.com/rnveach/checkstyle/tree/suppression_splitter .
> minor: remove unnecessary suppressions

- pom.xml
detected in azure 
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=9169&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=577
> config: bump maven-compiler-plugin to 3.10.1

- config/checkstyle_resources_suppressions.xml
- config/sevntu_suppressions.xml
- src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java
- src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurly2.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile2.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOther.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOther2.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/Configuration.java
> Issue #7546: adds support to it to load multiple configs at once

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughCharacterSwitch.java
Hi,
This is a small update for adding a new test case for the character switch case in FallThroughCheck. Followed the contribution document, and changes are passed by command `mvn clean verify`. Thank you for your review and consideration.
> minor: add new character switch test case in FallThroughCheck

- .ci/bump-license-year-in-all-projects.sh
- .ci/bump-license-year.sh
- .ci/checkchmod.sh
- .ci/common.sh
- .ci/copy-site-to-sourceforge.sh
- .ci/eclipse-compiler-javac.sh
- .ci/fast-forward-merge.sh
- .ci/idea_inspection.sh
- .ci/no-exception-test.sh
- .ci/no_old_refs.sh
- .ci/pitest.sh
- .ci/pr-description.sh
- .ci/releasenotes-gen.sh
- .ci/run-link-check-plugin.sh
- .ci/travis.sh
- .ci/util.sh
- .ci/validation.sh
- .shellcheckrc
Resolves: `SC2086`  #11637
`SC2086: Double quote to prevent globbing and word splitting.`  (https://github.com/koalaman/shellcheck/wiki/Sc2086)
> Issue #11637: Used Shellcheck to resolve SC2086 in Shell Script

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAfterCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralCase2.java
- src/xdocs/config_whitespace.xml
#11666 
Added LITERAL_CASE support for WhitespaceAfter check
> Issue #11666: Added LITERAL_CASE support for WhitespaceAfter check

- config/spotbugs-exclude.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
Part of #11140
Usually the number of elements is known already. It makes sense to create an array/list of the right size in advance.
But sometimes (for recursive code) it will be problematic. Two such cases are suppressed.
> Issue #11140: solve PSC_PRESIZE_COLLECTIONS

- config/spotbugs-exclude.xml
Part of #11140
Suppression for unsolvable items.
> Issue #11140: suppress false positives

- config/assembly-bin.xml
- config/assembly-src.xml
Removed internal/obsolete files.
> minor: removed internal and obsolete files from distributions

- pom.xml
> Issue #11681: adds maven-source-plugin for test sources

- .ci/travis.sh
- .ci/validation.sh
- .travis.yml
- azure-pipelines.yml
> Issue #11554: Added 'git diff' validation after execution of verify phase to Azure

- .ci/common.sh
- .ci/idea_inspection.sh
- .ci/validation.sh
- .github/workflows/diff_report.yml
- .github/workflows/site.yml
- .shellcheckrc
- .travis.yml
- release.sh
Resolves `SC2006` : https://github.com/checkstyle/checkstyle/issues/11637
SC2006: (style): Use $(...) notation instead of legacy backticks `...`.
> Issue #11637: Use Shellcheck to resolve SC2006 in Shell Script

- .ci/pitest.sh
- config/checkstyle_non_main_files_suppressions.xml
Noticed at https://github.com/checkstyle/checkstyle/runs/6850292559?check_suite_focus=true
> minor: remove closed issue references

- src/xdocs/index.xml.vm
> Issue #11735: move backport section after jre section

- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
Does not close #11277, but adds comments for WeakerAccess, ThreadLocalNotStaticFinal, NoopMethodInAbstractClass
> Issue #11277: update code base to have javadoc tag to explain noinspection content(WeakerAccess, ThreadLocalNotStaticFinal, NoopMethodInAbstractClass)

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEmptyBlockTest.java
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultConfigurationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
Issue #11566
based on feedback - https://youtrack.jetbrains.com/issue/IDEA-293684
> Issue #11566: resolve suppression of DeprecatedIsStillUsed

- src/xdocs/writingchecks.xml
> Issue #11698: reorganizes checkstyle limitations and add bom

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/xdocs/config_blocks.xml
Issue: #7582, Adds examples for option 'nlow'
> Issue #7582: Adds examples to doc for LeftCurly

- config/intellij-idea-inspections.xml
- src/main/java/com/puppycrawl/tools/checkstyle/FileStatefulCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/GlobalStatefulCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/StatelessCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/XdocsPropertyType.java
> Issue #11710: Disable IDEA Inspection for AnnotationClass

- src/test/java/com/puppycrawl/tools/checkstyle/DefaultConfigurationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
from https://github.com/checkstyle/checkstyle/pull/11639#issuecomment-1166314576
> minor: extension of test doc to explain deprecation reason

- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
Noticed during work on https://github.com/checkstyle/checkstyle/pull/11691, it is better to fix a simple violation like this, than to put a comment on it and let it live in the code base.
> minor: remove multiple return points

- .ci/validation.sh
- .circleci/config.yml
- .drone.yml
- .semaphore/semaphore.yml
from https://github.com/checkstyle/checkstyle/pull/11806
update to catch unstaged files
> infra: validate git status after commands

- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Includes: ProhibitedExceptionThrown, ChainOfInstanceofChecks, FieldNotUsedInToString, SuspiciousArrayCast, ClassWithTooManyDependencies. Part of #11277 .
> Issue #11277: update code base to have javadoc tag to explain noinspection content

- .ci/drone-io.sh
- .ci/jsoref-spellchecker/whitelist.words
https://github.com/checkstyle/checkstyle/issues/11817
> infra: speedup cache.tar download (dropbox)

- .ci/prepare-settings.sh
- .ci/releasenotes-gen-xdoc-push.sh
- .ci/tweet-releasenotes.sh
https://github.com/checkstyle/checkstyle/issues/11784
testing:
```
$ ./.ci/tweet-releasenotes.sh 
Error: Define TWITTER_CONSUMER_SECRET environment variable
✘-1 ~/java/github/romani/checkstyle [infra-fix-v L|✔] 
$ unset TWITTER_CONSUMER_KEY
✔ ~/java/github/romani/checkstyle [infra-fix-v L|✔] 
$ ./.ci/tweet-releasenotes.sh 
Error: Define TWITTER_CONSUMER_KEY environment variable
✘-1 ~/java/github/romani/checkstyle [infra-fix-v L|✔] 
$ TWITTER_CONSUMER_KEY="test"
✔ ~/java/github/romani/checkstyle [infra-fix-v L|✔] 
$ ./.ci/tweet-releasenotes.sh 
Error: Define TWITTER_CONSUMER_KEY environment variable
```
> #11784: fix bash scripts to detect not set variable properly

- .ci/StarterRuleSet-AllRulesByCategory.groovy.txt
- .ci/codenarc.groovy
- .ci/pitest-survival-check-xml.groovy
- .github/workflows/codenarc-analysis.yml
- .github/workflows/pitest.yml
Resolves #11823 
Codenarc failing (proof of working): https://github.com/checkstyle/checkstyle/runs/7180285139?check_suite_focus=true
Pitest failing (due to a mutation commented out, https://github.com/checkstyle/checkstyle/pull/11829/commits/09b98f8bd085816577846913bf9ef0b9af03cc4d): https://github.com/checkstyle/checkstyle/runs/7181418305?check_suite_focus=true
> Issue #11823: Use groovy version provided by apt

- .ci/prepare-settings.sh
> Issue #11783: prepare-settings.sh fails to create settings.xml

- src/main/resources/com/puppycrawl/tools/checkstyle/checks/design/messages_zh.properties
> Increase readability of Chinese exception messages.

- .ci/releasenotes-gen-xdoc-push.sh
Resolves #11782 
Child issue: https://github.com/checkstyle/contribution/pull/618
> Issue #11782: releasenotes script generated empty commit

- .semaphore/semaphore.yml
- .travis.yml
Mostly addresses frequent travis failures in master and PRs by moving all no error executions to semaphore. 
Example of failure: https://github.com/checkstyle/checkstyle/runs/7263811781
Link to semaphore build: https://checkstyle.semaphoreci.com/workflows/e02d483e-91c1-4b22-b693-b5c2e3fd1b4d?pipeline_id=6b0ee82e-e5e2-4d5b-ae6b-59c173ac4661
> infra: move no error executions to semaphore.yml

- .ci/releasenotes-gen.sh
due to checkstyle/contribution#617
detected at https://cloud.drone.io/checkstyle/checkstyle/11271/4/3
> config: remove publishXdoc from releasenotes-gen

- .ci/pitest-suppressions/pitest-coding-2-suppressions.xml
- .ci/pitest-survival-check-html.sh
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTryWithResources.java
#11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#OneStatementPerLine
Only the last commit is under consideration.
Not Required, no logic was modified. 
Logic was analyzed to come up with the test case.
>  Issue #11720: Kill surviving mutation in OneStatementPerLineCheck related to try-with-resource block

- .ci/pitest-suppressions/pitest-common-suppressions.xml
- .ci/pitest-survival-check-html.sh
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
https://github.com/checkstyle/checkstyle/issues/11720
N/A
The missing test case was added.
> Issue #11720: Kill surviving mutation in Checker

- .ci/pitest-suppressions/pitest-common-suppressions.xml
- .ci/pitest-survival-check-html.sh
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
#11720 
N/A
The missing test case was added.
> Issue #11720: Kill surviving mutation in DefaultLogger related to event's severity level

- .ci/pitest-suppressions/pitest-coding-2-suppressions.xml
- .ci/pitest-survival-check-html.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationNameSimilarToStandardClasses.java
https://github.com/checkstyle/checkstyle/issues/11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#IllegalInstantiation
Not required, no change in the check logic was made
- The logic was analyzed to develop the test case
> Issue #11720: Kill surviving mutation in IllegalInstantiationCheck

- .ci/pitest-suppressions/pitest-imports-suppressions.xml
- .ci/pitest-survival-check-html.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlWithoutRegexAndWithStrategyOnMismatch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlWithoutRegexAndWithStrategyOnMismatch.xml
Resolves #6658
**Check Documentation:** https://checkstyle.sourceforge.io/config_imports.html#ImportControl
N/A
- Logic was analyzed to develop the test case.
> Issue #6658: Kill surviving mutation in PkgImportControl related to regex

- .ci/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
#11720 
N/A
The missing test case was added.
> Issue #11720: Kill surviving mutation in DefaultLogger related to closing streams

- .ci/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
#11720
N/A
Missing Test Case Was Added
> Issue #11720: Kill surviving mutation in PackageObjectFactory

- .ci/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlWithRegex.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlWithRegex.xml
#6658
**Check Documentation:** https://checkstyle.sourceforge.io/config_imports.html#ImportControl
N/A
- Logic was analyzed to develop the test case.
> Issue #6658: Kill surviving mutation in PkgImportControl in matchesExactly

- .ci/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParentheses15Extensions.java
#11720
N/A
- Logic was analyzed and test case was developed
> Issue #11720: Kill surviving mutation in UnnecessaryParenthesesCheck in leaveToken

- .github/workflows/bump_license_year.yml
> Issue #11970: Updated GitHub Action for bump-license-year.sh

- .ci/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceDefault2.java
#11720
- Not required, no changes to the check were made
- Logic was analyzed to develop the test case
> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in isChild

- .ci/jsoref-spellchecker/whitelist.words
- .circleci/config.yml
- .github/workflows/shellcheck.yml
- .travis.yml
Attempting to fix failure noted at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/577739286 and https://github.com/checkstyle/checkstyle/pull/11990/checks?check_run_id=7513176563
> infra: move jobs out of travis

- pom.xml
minor: Modify pitest mutators for `pitest-java-ast-visitor`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-java-ast-visitor/index.html
> minor: Modify pitest mutators for pitest-java-ast-visitor

- .ci/pitest-survival-check-xml.groovy
Enhanced error messages in `pitest-survival-check-xml.groovy`
> minor: Enhanced error messages in pitest-survival-check-xml.groovy

- .ci/pitest-suppressions/pitest-api-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
> Issue #12017: Kill surviving mutations in AbstractFileSetCheck related to initializing members

- .ci/prepare-settings.sh
- .ci/releasenotes-gen-xdoc-push.sh
- .ci/tweet-releasenotes.sh
- .ci/util.sh
> Issue #11758: Adding CheckForVariable function to util.sh

- SECURITY.md
> Issue #11865: Resolve incorrect table formatting idea violations

- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
> Issue #11865: Resolve multiple occurrences idea violations

- .ci/no_old_refs.sh
- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/GlobalStatefulCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
- src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
#11865 
`no_old_refs.sh` was also modified to support anchor tags.
> Issue #11865: Resolve link specefied as plain text idea violations 

- src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnConstructor.java
Resolves #11605
---
Diff Regression config: https://gist.githubusercontent.com/stoyanK7/b3ab8c5d2245108a5366c5263e7079dc/raw/2b7519866985771115f2c6b31fad5070a1fb38b1/config.xml
> Issue #11605: Fix false positive for generic constructor without access modifier in InvalidJavadocPosition

- .ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisTryWithResources.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisTryWithResourcesOnlyOverlappingFalse.java
Resolves #11821
---
Diff Regression config: https://gist.githubusercontent.com/stoyanK7/915bf3abd0e42ae89e6e6dc1051fbe02/raw/de67d93f46a866635e725941b296a799ac3c1fc3/config.xml
> Issue #11821: RequireThisCheck now handles try-with resources

- src/it/java/com/google/checkstyle/test/chapter5naming/rule523methodnames/MethodNameTest.java
- src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
- src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java
- src/main/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/PackageNameCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/packagename/InputPackageNameSimple.java
- src/xdocs/config_naming.xml
> Issue #11865: Resolve RegExp idea violations

- .ci/maven-prepare.sh
- .github/workflows/maven_prepare.yml
Fixes #12078 
Final Testing: https://github.com/Rahulkhinchi03/checkstyle-test/actions/runs/2928941890
> Issue #12078: Github action Release prepare

- .ci/update-github.sh
- .github/workflows/update_github.yml
> Issue #12080: Github action Update Github milestone and upload '-all'  jar

- .ci/releasenotes-gen-xdoc-push.sh
- .ci/update-releasenotesxml.sh
- .github/workflows/update_sources.yml
> Issue #12077: Github action to update sources with release notes

- .ci/jsoref-spellchecker/whitelist.words
- .ci/publish-releasenotes-githubpage.sh
- .github/workflows/publish_releasenotes_outside.yml
> Issue #12082: Github action Publish release notes outside

- .ci/jsoref-spellchecker/whitelist.words
- .github/workflows/bump-version-and-update-milestone.yml
- .github/workflows/maven_prepare.yml
- .github/workflows/publish_releasenotes_for_twitter.yml
- .github/workflows/publish_releasenotes_outside.yml
- .github/workflows/update_github.yml
- .github/workflows/update_sources.yml
> Issue #12114: rename all release action to have 'R:' prefix in name

- .github/workflows/update_sources.yml
> Issue #12120: rename update-sources.sh

- pom.xml
- src/xdocs/beginning_development.xml
> Issue #12111: upgrades maven version for contributors

- .ci/publish-releasenotes-githubpage.sh
- .ci/tweet-releasenotes.sh
- .github/workflows/publish_releasenotes_outside.yml
Fixes https://github.com/checkstyle/checkstyle/issues/12124
> Issue #12124: Minor changes in in shell scripts

- .ci/update-github-io.sh
- .github/workflows/update_github_io.yml
> Issue #12115: Github Action Update github.io

- .ci/pitest-survival-check-xml.groovy
> Issue #12133: Fix 'IllegalArgumentException: character to be escaped is missing' exception

- .github/ISSUE_TEMPLATE/feature_request.md
Noticed in https://github.com/checkstyle/checkstyle/issues/12157, we are not consistent in our issue template.
> doc: add 'I have read check documentation...' to feature_request.md

- .ci/validation.sh
- .circleci/config.yml
- .github/workflows/no-exception-workflow.yml
- .semaphore/semaphore.yml
> Issue #12129: build checkstyle SNAPSHOT before execution other projects validaiton

- release.sh
Issue #11912
see prove that it is ok in issue - https://github.com/checkstyle/checkstyle/issues/11912#issuecomment-1229538320
so we will not have reports in website that nobody care to look and action.
But we will significantly reduce execution time of this release phase.
1 min - without validation
8 min - with validatiion
> Issue #11912: remove all validations during web site build during release

- .github/workflows/update_github_io.yml
> Issue #12160: execution of 'R: Update github.io' with '10.3.3' faililng

- .github/workflows/bump-version-and-update-milestone.yml
- .github/workflows/bump_license_year.yml
- .github/workflows/maven_prepare.yml
- .github/workflows/new-milestone-and-issue-in-other-repo.yml
- .github/workflows/publish_releasenotes_for_twitter.yml
- .github/workflows/publish_releasenotes_outside.yml
- .github/workflows/update_github_io.yml
- .github/workflows/update_sources.yml
- .github/workflows/upload-all-jar.yml
> Issue #12165: updates in Github actions

- .ci/error-prone-check.groovy
```
Caught: java.io.IOException: Cannot run program "mvn": CreateProcess error=2, The system cannot find the file specified
java.io.IOException: Cannot run program "mvn": CreateProcess error=2, The system cannot find the file specified
at error-prone-check.getErrorProneErrors(error-prone-check.groovy:87)
at error-prone-check.checkErrorProneReport(error-prone-check.groovy:63)
at error-prone-check.parseArgumentAndExecute(error-prone-check.groovy:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at error-prone-check.run(error-prone-check.groovy:19)
at …
```
> Pull #12154: Use OS specific command and correct errorExtractingPattern

- .github/workflows/bump_license_year.yml
- .github/workflows/codeql-analysis.yml
> Issue #12175: Disable execution of GitHub actions with cron in fork repositories

- .ci/StarterRuleSet-AllRulesByCategory.groovy.txt
- .ci/checker-framework-suppressions/checker-framework-formatter-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-index-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-lock-tainting-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-methods-resource-fenum-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-purity-value-returns-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-regex-property-key-compiler-message-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-signature-gui-units-init-suppressions.xml
- .ci/checker-framework.groovy
- .ci/jsoref-spellchecker/exclude.pl
- .ci/jsoref-spellchecker/whitelist.words
- .github/workflows/checker-framework.yml
- config/checkstyle_non_main_files_suppressions.xml
- pom.xml
> Issue #12164: Enable Checker Framework

- README.md
Added badge for:
- Pitest
- Error Prone
- Checker Framework
- Codenarc
> Pull #12218: Add badges for new GitHub actions

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses3.java
Issue https://github.com/checkstyle/checkstyle/issues/11920
---
Diff Regression config: https://gist.githubusercontent.com/ZuevKirill95/343499fde086f3aa9b3994112f4f2f6c/raw/835a28fc3fc529cccd5b9daa476e2aeb3e3fa4b7/config.xml
> Issue #11920: fix false positive: UnusedLocalVariableCheck

- .ci/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapEol.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapWithTrimOptionProperty.java
Issue #12266: Resolve Pitest suppression for OperatorWrapCheck
> Issue #12266: Resolve Pitest suppression for OperatorWrapCheck

- .ci/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadSetOptionTrim.java
Issue #12264: Resolve Pitest suppression for MethodParamPadCheck
> Issue #12264: Resolve Pitest suppression for MethodParamPadCheck

- .ci/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPadSetOptionTrim.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPadWithEmoji.java
Issue #12265: Resolve Pitest suppression for EmptyForInitializerPadCheck
> Issue #12265: Resolve Pitest suppression for EmptyForInitializerPadCheck

- .ci/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestDot.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapSetOptionTrim.java
Issue #12267: Resolve Pitest suppression for SeperatorWrapCheck
> Issue #12267: Resolve Pitest suppression for SeperatorWrapCheck

- README.md
to test https://github.com/checkstyle/checkstyle/issues/12087#issuecomment-1272669800
> doc: remove teamcity badge but keep links in case we will restore it

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java
- src/xdocs/config_filters.xml
from https://github.com/checkstyle/checkstyle/pull/12268
all points from https://github.com/checkstyle/checkstyle/pull/12268#issuecomment-1271511500 are checked, all good.
> doc: Update SuppressionXpathSingleFilter example (related to #3095)

- .travis.yml
All jobs were commented out and confirmed moved somewhere else.
> infra: remove outdated jobs from travis

- .ci/checker-framework-suppressions/checker-framework-index-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-lock-tainting-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-methods-resource-fenum-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-purity-value-returns-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-regex-property-key-compiler-message-suppressions.xml
- .ci/checker-framework-suppressions/checker-framework-signature-gui-units-init-suppressions.xml
- .ci/checker-framework.groovy
- .github/workflows/checker-framework.yml
#12243 
idea is taken from https://github.com/checkstyle/checkstyle/pull/11617/commits/0d149b5db810c2f04da20329d30e49436a96624a
```
groovy ./.ci/checker-framework.groovy --list
WARNING: A.........
............All illegal access operations will be denied in a future release
Supported profiles:
checker-framework-nullness-optional-interning
checker-framework-signature-gui-units-init
checker-framework-formatter
checker-framework-methods-resource-fenum
checker-framework-lock-tainting
checker-framework-index
checker-framework-regex-property-key-compiler-message
checker-framework-purity-value-returns
```
-----
example of diff if I damaged suppression file manually:
```
$ git diff
diff --git a/.ci/checker-framework-suppressions/checker-framework-lock-tainting-suppressions.xml …
```
> I12243 checker

- .ci/validation.sh
- .travis.yml
> Issue #9984: restore verify-no-exception-configs

- .github/workflows/checker-framework.yml
extra fix after:
https://github.com/checkstyle/checkstyle/commit/dbd312a6ee808708cf35f1b24ef4ed41987f1ecc
> infra: enable printing diff to monitor what is going on in Checker

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/UnusedImportsCheck.xml
- src/xdocs/config_imports.xml
> Issue #12224: document limitation regarding same-name imports

- .ci/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/InputNewlineAtEndOfFileTestTrimProperty.java
Issue #12314: Resolve Pitest suppression for misc profile
> Issue #12314: Resolve Pitest suppression for misc profile

- .ci/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationFirstLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationTrimOptionProperty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheckOptionLowercaseProperty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTestTrimProperty.java
Issue #12315: Resolve Pitest suppression for Javadoc profile
> Issue #12315: Resolve Pitest suppression for Javadoc profile

- .github/workflows/checker-framework.yml
loooks stable after https://github.com/checkstyle/checkstyle/pull/12313 and other changes in for Checker
> infra: enable Checker in CI

- .github/workflows/pitest.yml
Identified at https://github.com/checkstyle/checkstyle/pull/12324#issuecomment-1287809764 for https://github.com/checkstyle/checkstyle/issues/12229
> config: make pitest names more compact to show profile

- .ci/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForEnum.java
Issue #12327: Resolve Switch case mutation for ParenPad
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e206f8b15b0d8c04e1d6b1fbded90dbe/raw/287387889a74449dab21e1da7b07c3167e3397d1/config.xml
> Issue #12327: Resolve Switch case mutation for ParenPad

- config/ant-phase-verify.xml
- config/checkstyle_input_checks.xml
- config/checkstyle_non_main_files_checks.xml
- config/checkstyle_resources_checks.xml
- config/checkstyle_sevntu_checks.xml
- pom.xml
Minor found at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/916
> minor: cleanups for ant-phase-verify

- .ci/validation.sh
Identified when preparing to merge https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/916
Sevntu's checkstyle skip is changing.
This PR should wait on sevntu merge and should re-run to confirm.
> supplemental: ant switch in sevntu-checkstyle/sevntu.checkstyle#915

- .ci/validation.sh
- .circleci/config.yml
Closes #12259 
Example of failure: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/15744/workflows/0ecc8155-71c4-426c-85ab-70fba55b46e4/jobs/189949
> Issue #12259: Create CI task to fail PR if merge commit exists

- .ci/validation.sh
- .circleci/config.yml
Closes #12319 
~~First commit is not under review.~~
Example of failure (on commit https://github.com/checkstyle/checkstyle/pull/12344/commits/0bf87981c766048276a61e9d1e5f9458f0781ec4): https://app.circleci.com/pipelines/github/checkstyle/checkstyle/15747/workflows/45589939-13ca-4595-b983-796e6cb95b01/jobs/190021
> Issue #12319: validate PR number when commit is for PR

- appveyor.yml
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/45193904/job/3gw74la4l739kxvd
````
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:3 char:3
+   (new-object System.Net.WebClient).DownloadFile(
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : WebException
````
> config: upgrade appveyor maven to 3.8.6

- pom.xml
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11909&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=631
> config: bump versions.plugin.version to 2.13.0

- .ci/checker-framework-suppressions/checker-index-suppressions.xml
- pom.xml
Version bump
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11909&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=608
> config: checkerframework.version 3.27.0

- src/xdocs/property_types.xml
Created for https://github.com/checkstyle/checkstyle/issues/12355#issuecomment-1298701324 and not connected to the issue since this is just for documenting what was seen as missing, imo.
> doc: expanded documentation on severities

- .circleci/config.yml
Reorganizes circleci config, functionality is the same. Also, I added a cache in a second commit to help CI to be more stable and speed up builds.
> infra: reorg circleci to have one parameterized job for validation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/NewlineAtEndOfFileCheck.xml
- src/xdocs/config_misc.xml
> Issue #12370: Removed the unwanted text for NewLineCheck

- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorBlockCommentUnderPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorClassDefinitionAndCommentNotSeparatedFromPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorEmptyLineAfterPackageForPackageAst.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorHeader.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorModifierUnderPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorNewMethodDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPostFixCornerCases.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPreviousLineEmptiness.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorRecursive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleCommentUnderPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleLineCommentAfterPackage.java
Fixes Issue for https://github.com/checkstyle/checkstyle/issues/11214
> Issue #11214: Update for EmptyLineSeparator

- .github/workflows/bump-version-and-update-milestone.yml
> Issue #12351: Fix action 'Bump version/Update Milestone' failing to update milestones

- .ci/close-create-milestone.sh
- .ci/creation-of-issue-in-other-repos.sh
- .ci/drone-io.sh
- .ci/no_old_refs.sh
- .ci/pr-description.sh
- .ci/releasenotes-gen-xdoc-push.sh
- .ci/run-link-check-plugin.sh
- .ci/sonar.sh
- .ci/travis.sh
- .ci/tweet-releasenotes.sh
- .ci/update-github-milestone.sh
- .ci/update-github-page.sh
- .ci/upload-all-jar.sh
- .ci/validation.sh
- config/checkstyle_non_main_files_checks.xml
- config/checkstyle_non_main_files_suppressions.xml
- release.sh
> Issue #12389: enforced fail-with-body in curl commands

- .ci/releasenotes-gen.sh
As requested in https://github.com/checkstyle/contribution/pull/670#issuecomment-1285754978
> Pull #12316: add release number validation

- .ci/validation.sh
- .circleci/config.yml
migrate drone jobs to circleci
> infra: migrate drone jobs to circleci

- .ci/jsoref-spellchecker/whitelist.words
- .ci/travis.sh
Prevent build failures on other PRs.
> minor: prevent find running for quarterly cleanup if it doesn't exist

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl8.java
Subtask of #11446  : Update The ImportControlCheckTest
> Issue #11446: Replace verify method in ImportControlCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
- src/xdocs/config_design.xml
Fixes : #7613, Add Code Example For MutableException
- Outputs: 
- 1 :  
- 2 : 
- 3 :
> Issue #7613: Update doc for MutableException

- pom.xml
http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.43.0
> config: bump sevntu to 1.43.0

- pom.xml
http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.43.0
by step from release process - https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle
> config: bump maven.sevntu-checkstyle-check.checkstyle.version to 10.4

- .ci/pitest-suppressions/pitest-annotation-suppressions.xml
- .ci/pitest-suppressions/pitest-blocks-suppressions.xml
- .ci/pitest-suppressions/pitest-coding-1-suppressions.xml
- .ci/pitest-suppressions/pitest-coding-2-suppressions.xml
- .ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml
- .ci/pitest-suppressions/pitest-common-suppressions.xml
- .ci/pitest-suppressions/pitest-metrics-suppressions.xml
- .ci/pitest-suppressions/pitest-misc-suppressions.xml
- .ci/pitest-suppressions/pitest-utils-suppressions.xml
- .ci/pitest-suppressions/pitest-whitespace-suppressions.xml
- .ci/pitest-suppressions/pitest-xpath-suppressions.xml
- pom.xml
Supersedes https://github.com/checkstyle/checkstyle/pull/12376
> config: bump pitest to 1.9.9

- .ci/validation.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyCommentBeforeLeftCurly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyCommentBeforeLeftCurly2.java
Issue #11410: False Negative: LeftCurlyCheck
-----------------------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/2f8c33a742f0b14868f7c263333d0589/raw/4a431ad8819bae6b86d3a70d07f3a22662fc1b76/Mycheck.xml
> Issue #11410: False Negative: LeftCurlyCheck

- config/checkstyle_resources_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleNoJavadoc1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleNoJavadoc2.java
In relation to #11163: Enforce File Size On Inputs 
- Removed FileSize Suppression From InputJavadocStyleNoJavadoc
> Issue #11163: Reduced Size Of InputJavadocStyleNoJavadoc

- .ci/generate-website.sh
- .ci/push-website-to-github-io.sh
- .github/workflows/update_github_io.yml
Resolves #12168 
https://github.com/stoyanK7/checkstyle/actions/runs/3448827113
> Issue #12168: failure of update github.io to clone checkstyle.github.io

- .ci/pitest-suppressions/pitest-javadoc-suppressions.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagDoubleTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEmptyTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagIgnore.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagIncomplete.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMissingFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagSeverity.java
Related to https://github.com/checkstyle/checkstyle/issues/11446.
Here I have made some changes. I am getting the following errors in maven:
```
[ERROR] Tests run: 15, Failures: 9, Errors: 0, Skipped: 0, Time elapsed: 0.159 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.checks.javadoc.WriteTagCheckTest
[ERROR] testSeverity  Time elapsed: 0.061 s  <<< FAILURE!
com.google.common.truth.ComparisonFailureWithFacts:
error message 0
expected: ?agSeverity.java:15: Javadoc tag @author=Daniel Grenner  // violation
but was : ?agSeverity.java:15: Type Javadoc tag @author must match pattern 'S'.
at com.puppycrawl.tools.checkstyle.checks.javadoc.WriteTagCheckTest.verify(WriteTagCheckTest.java:209)
at com.puppycrawl.tools.checkstyle.checks.javadoc.WriteTagCheckTest.testSeverity(WriteTagCheckTest.jav …
```
> Issue #11446: Update WriteTagCheckTest to use verifyWithInlineConfigParser

- config/checkstyle_non_main_files_suppressions.xml
- release.sh
problem detected during release
> infra: diable new curl option as it absent in CI and my local

- .ci/releasenotes-gen.sh
> Issue #12468: releasenotes-builder does not update releasenotes.xml 

- src/xdocs/releasenotes.xml
https://github.com/checkstyle/checkstyle/issues/12479#issuecomment-1333048227
> Revert "doc: release notes for 10.5.1"

- .ci/releasenotes-gen-xdoc-push.sh
Resolves #12488 
Action: https://github.com/stoyanK7/checkstyle/actions/runs/3604870995/jobs/6074684061#step:4:241
> Issue #12488: 'R: Push Release Notes' makes xml section version as snapshot

- .ci/validation.sh
https://checkstyle.semaphoreci.com/jobs/b5111b2e-81b7-4a62-b1f3-acb6a9ce47ef#L661
> Unable to create Root Module: config {[https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.5.1-SNAPSHOT/config/checkstyle_non_main_files_checks.xml}](https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.5.1-SNAPSHOT/config/checkstyle_non_main_files_checks.xml%7D)
> config: update sevntu regression based on changes in sevntu

- .circleci/config.yml
- .github/dependabot.yml
- .github/workflows/check-pr-description.yml
- .github/workflows/checker-framework.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/diff_report.yml
- .github/workflows/error-prone.yml
- .github/workflows/no-exception-workflow.yml
- .github/workflows/no_old_refs.yml
- .github/workflows/pitest.yml
- .github/workflows/publish_releasenotes_for_twitter.yml
- .github/workflows/rebase.yml
- .github/workflows/site.yml
- .travis.yml
- azure-pipelines.yml
- codeship-steps.yml
- config/jsoref-spellchecker/whitelist.words
- config/yamllint.yaml
- pom.xml
> Issue #12435: Create YAML linting CI task

- .ci/validation.cmd
- .ci/validation.sh
- .travis.yml
- appveyor.yml
- config/ant-phase-verify-sevntu.xml
- config/ant-phase-verify.xml
- config/checkstyle_sevntu_checks.xml
- config/jsoref-spellchecker/whitelist.words
- pom.xml
Issue #5385
New profile is needed, see note.
> Issue #5385: convert maven-checkstyle-plugin to ant

- .ci/no-exception-test.sh
- .travis.yml
Identified at https://github.com/checkstyle/checkstyle/pull/12392#issuecomment-1348692764 .
> config: add regression on checkstyle-samples ant

- config/jsoref-spellchecker/whitelist.words
- src/xdocs/index.xml.vm
- src/xdocs/writingchecks.xml
https://github.com/checkstyle/checkstyle/actions/runs/3783054939/jobs/6431291434#step:3:2453
https://wheregoes.com/trace/20226050213/
> minor: fix links for sonarqube (linkcheck plugin)

- .github/workflows/actionlint.yml
- .github/workflows/bump_license_year.yml
- .github/workflows/copy_site_to_sourceforge.yml
- .github/workflows/diff_report.yml
- .github/workflows/no_old_refs.yml
- .github/workflows/site.yml
- config/jsoref-spellchecker/whitelist.words
closes #12501
Diff Regression config: https://gist.githubusercontent.com/nrmancuso/858f3ef5e63e12540b71a3e514acdf52/raw/b9e3d229bb0e226cfb11b98e5e3c26895c26faa7/config.xml
> Issue #12501: Create CI task to lint github actions

- config/suppressions.xml
- src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractGuiTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java
- src/test/resources/simplelogger.properties
> Issue #12100: Review usages of BeforeAll in tests 

- config/pitest-suppressions/pitest-metrics-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSSResolveMutation.java
Issue #12333: Resolve pitest for profile metrics
part of https://github.com/checkstyle/checkstyle/issues/12341
> Issue #12333: Resolve pitest for profile metrics

- .github/workflows/actionlint.yml
- .github/workflows/no-exception-workflow.yml
- .github/workflows/shellcheck.yml
> Issue #12568: Fix lint GitHub Actions workflows executed twice

- .github/workflows/bump_license_year.yml
allow to run bump year manually
> config: allow to run bump year manually

- .ci/pitest.sh
- .github/workflows/pitest.yml
> Issue #12557: Restore pitest.sh to ease operation on local

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-ant-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
- src/xdocs/anttask.xml.vm
> Issue #12338: removes CheckstyleAntTask's classpath

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitialization.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitializationOnlyObjectReference.java
Issue #12331: Test case added to kill mutation
> Issue #12331: Test case added to kill mutation

- config/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadTryWithResourcesAndSuppression.java
Issue #12601
Edit by @nrmancuso to help find example in the future: Mutation killed by combination of XPath suppression and check
> Issue #12601: adds test for whitespace mutation 

- config/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
> Issue #12601: removes code for EmptyLineSeparatorCheck

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-whitespace-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
> Issue #12601: removes code for SingleSpaceSeparator

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/InputJavadocPackageBadCls.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/InputJavadocPackageBadCls2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/InputJavadocPackageBadTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/InputJavadocPackageNoJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/InputJavadocPackageNotJava.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/bothfiles/InputJavadocPackageBothIgnored.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/noparentfile/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/pkghtml/InputJavadocPackageHtmlIgnored.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/pkghtml/InputJavadocPackageHtmlIgnored2.java
Issue #11214: Specified violation messages for JavadocPackageCheck
> Issue #11214: Specified violation messages for JavadocPackageCheck

- config/pitest-suppressions/pitest-whitespace-suppressions.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleLines3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleLines2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorStaticImport.java
> Issue #12601: adds tests for whitespace mutations

- config/pitest-suppressions/pitest-blocks-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestItWithAllowsOn.java
> Issue #12615: adds test for need braces

- config/pitest-suppressions/pitest-blocks-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
> Issue #12615: removes unnecessary code for EmptyBlock

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- config/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
Identified when working on pitest-require-this .
> Corrects classes scanned for pitest to include sub-classes

- config/jsoref-spellchecker/whitelist.words
- src/xdocs/index.xml.vm
> doc: explanation on versioning of checkstyle

- config/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
Issue #12626
Regression and comments to come.
> Issue #12626: removes code in RequireThis sub-classes

- config/intellij-idea-inspections.xml
- config/pmd-test.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
> Issue #11446: Update SuppressionFilterTest to use execute

- config/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThis15Extensions.java
Issue #12626
No regression needed.
> Issue #12626: adds tests for mutations in RequireThis sub-classes

- config/pitest-suppressions/pitest-design-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionIgnoredAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableExceptionNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCount4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierAnnotated.java
Issue #12641
No regression needed.
> Issue #12641: adds tests for design profile

- config/projects-to-test/openjdk19-excluded.files
Related to #12515, we forgot to remove comment above associated file filters.
> minor: remove 'until...' comment (checkstyle#12515)

- .ci/validation.sh
> Issue #7815: removes retired apex-core

- .ci/validation.sh
- .circleci/config.yml
- .github/workflows/actionlint.yml
- .github/workflows/bump-version-and-update-milestone.yml
- .github/workflows/bump_license_year.yml
- .github/workflows/check-pr-description.yml
- .github/workflows/checker-framework.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/copy_site_to_sourceforge.yml
- .github/workflows/diff_report.yml
- .github/workflows/error-prone.yml
- .github/workflows/maven_prepare.yml
- .github/workflows/new-milestone-and-issue-in-other-repo.yml
- .github/workflows/no-exception-workflow.yml
- .github/workflows/no_old_refs.yml
- .github/workflows/pitest.yml
- .github/workflows/publish_releasenotes_for_twitter.yml
- .github/workflows/publish_releasenotes_outside.yml
- .github/workflows/rebase.yml
- .github/workflows/releasenotes-gen.yml
- .github/workflows/run_link_check.yml
- .github/workflows/shellcheck.yml
- .github/workflows/site.yml
- .github/workflows/update_github_io.yml
- .github/workflows/update_sources.yml
- .github/workflows/upload-all-jar.yml
- config/jsoref-spellchecker/whitelist.words
Closes #12645
Example of failure: https://circleci.com/gh/checkstyle/checkstyle/234145
> Issue #12645: All GitHub CI workflows should have concurrency of 1

- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
>  Issue #11589: adds descriptions for ResultOfMethodCallIgnored

- src/xdocs/cmdline.xml.vm
- src/xdocs/releasenotes_old_1-0_5-9.xml
- src/xdocs/writingjavadocchecks.xml.vm
> Issue #11572: corrects wrong links in xdocs

- .ci/copy-site-to-sourceforge.sh
- .github/workflows/copy_site_to_sourceforge.yml
Resolves #12574
---
[Successful job run](https://github.com/stoyanK7/checkstyle/actions/runs/4074017115/jobs/7018643442)
> Issue #12574: Github action to copy to sourceforge does not work

- pom.xml
Missed from https://github.com/checkstyle/checkstyle/pull/12710 as I needed to run `versions:display-plugin-updates` to see these.
> Multiple plugins bump

- config/pitest-suppressions/pitest-annotation-suppressions.xml
- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- config/pitest-suppressions/pitest-common-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- pom.xml
Bump pitest https://github.com/hcoles/pitest/releases/tag/1.11.0 .
> dependency: bump pitest-maven to 1.11.0

- src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
> Issue #12717: Remove admins from white list on commit validation

- .shellcheckrc
> Issue #11637: Resolve shellcheck SC1004

- .ci/travis.sh
- .shellcheckrc
Part of #11637 
Refrence :- https://www.shellcheck.net/wiki/SC2088
> Issue #11637: Resolve shellcheck SC2088

- .ci/pitest-survival-check-xml.groovy
- .ci/pitest.sh
- .github/workflows/pitest.yml
Resolves #12613
Resolves #12153
> Issue #12613: `pitest-survival-check-xml.groovy` should automatically update list of suppressions

- .ci/bump-version.sh
> Issue #12608: Validation for next version in GitHub action

- README.md
Part of #12716 
In https://github.com/checkstyle/checkstyle/pull/12727 we forgot to edit those 4 lines. I realised while working on https://github.com/checkstyle/checkstyle/pull/12739#discussion_r1106182620.
> Issue #12716: Fix forgotten links

- .ci/bump-version.sh
- .ci/close-create-milestone.sh
- .ci/maven-prepare.sh
- .ci/maven-release-perform.sh
- .ci/update-releasenotesxml.sh
- .ci/util.sh
- .github/workflows/maven-prepare.yml
- .github/workflows/new-milestone-and-issue-in-other-repo.yml
- .github/workflows/shellcheck.yml
- .github/workflows/update-sources.yml
- release.sh
Resolves #12726 
---
Small test:
```
stoyan @  zenbook:  ~/open-source/checkstyle                                                                                                        issue/12726-replace-usages-xmlstarlet
$ ./.ci/bump-version.sh 11.0.0                                                                                                                                                     11:30:32 am
NEW_VERSION=11.0.0
CURRENT_VERSION=10.7.1
bump version in pom.xml
```
> Issue #12726: Replace all usages of xmlstarlet with getCheckstylePomVersion from util.sh

- config/checker-framework-suppressions/checker-signature-gui-units-init-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableModelAdapter.java
- src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java
supplemental: make private class final with default constructor
part of :- https://github.com/checkstyle/checkstyle/pull/12737
> supplemental: make private class final with default constructor

- src/main/java/com/puppycrawl/tools/checkstyle/LocalizedMessage.java
> minor: extention of doc to address #7488

- .ci/maven-release-perform.sh
- .ci/prepare-settings.sh
- .github/workflows/maven-release-perform.yml
- config/jsoref-spellchecker/whitelist.words
- pom.xml
Part of #12720 
---
The maven-release-perform workflow was not tested as an action. Now that I understand better what is happening, a few things needed to be changed to make it work.
Proof that it works: https://github.com/stoyanK7/checkstyle/actions/runs/4183171423/jobs/7247190315
> Issue #12720: Fix issues with maven-release-perform workflow

- .ci/validation.sh
- config/ant-phase-verify.xml
- config/checkstyle_non_main_files_checks.xml
From https://github.com/checkstyle/checkstyle/pull/12755#discussion_r1112055478
>So before mergin this PR we need 1 PR for checkstyle repo to make it as a variable and 1 PR for sevnu to define this variable.
> Pull #12761: Define variable for non-main-files-suppressions file

- README.md
- codeship-services.yml
- codeship-steps.yml
- config/jsoref-spellchecker/exclude.pl
- config/jsoref-spellchecker/whitelist.words
- pom.xml
> Issue #12758: remove codeship CI

- .ci/validation.sh
- .shellcheckrc
Related to #11637 
https://www.shellcheck.net/wiki/SC2026
> Issue #11637: Resolve shellcheck SC2026

- .ci/util.sh
- .shellcheckrc
> Issue #11637: Resolve shellcheck SC2005

- .shellcheckrc
> Issue #11637: Resolve shellcheck SC2126

- .ci/validation.sh
https://checkstyle.semaphoreci.com/jobs/e7538968-34c5-4297-863f-19c224238660#L642
```
Unable to create Root Module: config {../../../config/checkstyle_checks.xml}.
cannot initialize module RegexpHeader - unable to load header file https://raw.githubusercontent.com/checkstyle/checkstyle/master/config/java-regexp.header
```
> minor: rename forgotten file from sevntu to kebab-case

- src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
> Issue #12766: CommitValidationTest fails on revert commits

- .github/workflows/copy-site-to-sourceforge.yml
- .github/workflows/maven-prepare.yml
- .github/workflows/maven-release-perform.yml
- .github/workflows/new-milestone-and-issue-in-other-repo.yml
- .github/workflows/publish-releasenotes-for-twitter.yml
- .github/workflows/publish-releasenotes-outside.yml
- .github/workflows/release.yml
- .github/workflows/update-github-io.yml
- .github/workflows/update-sources.yml
Resolves #12720
Continues from https://github.com/checkstyle/checkstyle/pull/12733. I can not reopen PR since it was from my `master` branch and I force-pushed. Probably there is a way to fix that but it is faster to open this one.
The first two commits are just for my convenience. We will remove them before merging. Look at commit `Issue #12720: Make action to trigger all release steps` to see the relevant changes to the issue.
Success run: https://github.com/stoyanK7/checkstyle/actions/runs/4177134639
Tags at my repo: https://github.com/stoyanK7/checkstyle/tags
Milestones: https://github.com/stoyanK7/checkstyle/milestones?state=closed
Commits: https://github.com/stoyanK7/checkstyle/commits/master
Sourceforge: https://stoyank7-checkstyle.sourceforge.io/
> Issue #12720: Make action to trigger all release steps

- .github/workflows/copy-site-to-sourceforge.yml
- .github/workflows/maven-prepare.yml
- .github/workflows/maven-release-perform.yml
- .github/workflows/new-milestone-and-issue-in-other-repo.yml
- .github/workflows/publish-releasenotes-for-twitter.yml
- .github/workflows/publish-releasenotes-outside.yml
- .github/workflows/release.yml
- .github/workflows/update-github-io.yml
- .github/workflows/update-sources.yml
Resolves #12785 
---
https://github.com/stoyanK7/checkstyle/actions
https://github.com/stoyanK7/checkstyle/actions/runs/4317341249
> Issue #12785: Use dynamic names for release workflow runs

- .ci/set-milestone-on-referenced-issue.sh
- .github/workflows/set-milestone-on-referenced-issue.yml
- config/checkstyle-non-main-files-suppressions.xml
Resolves #12497
Test issue: https://github.com/stoyanK7/checkstyle/issues/36
Merged PR: https://github.com/stoyanK7/checkstyle/pull/39
Action that kicked off: https://github.com/stoyanK7/checkstyle/actions/runs/4286289128/jobs/7465657911
Test PR: https://github.com/stoyanK7/checkstyle/pull/46
Action that kicked off: https://github.com/stoyanK7/checkstyle/actions/runs/4293756147/jobs/7481853864
> Issue #12497: Create GitHub action to put current milestone on issue of closed PR

- .github/workflows/release.yml
- .github/workflows/upload-all-jar.yml
Requires https://github.com/checkstyle/checkstyle/pull/12793 to be merged first.
Success upload run:
https://github.com/stoyanK7/checkstyle/actions/runs/4326378052
Proof of upload:
https://github.com/stoyanK7/checkstyle/releases/tag/checkstyle-10.8.1
> Pull #12792: Execute upload of -all jar separately

- config/sevntu-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java
> Issue #4930: adds sourceClass to Violation compareTo method

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordAsTopLevel.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordDefault.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingFalseLeaves.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLambdaParameters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLocalVars.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAnonymousEmpty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisCatchVariables.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExtendedMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFinalInstanceVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisMethodReferences.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisSimple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisTryWithResourcesOnlyOverlappingFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingTrue.java
Issue #11214 
I have specified violation messages of all input files that use RequireThisCheck.
Based on test file `src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java`.
Please check, thanks.
> Issue #11214: Specified violation messages in RequireThisCheck

- pom.xml
may be it will resolve 
https://github.com/checkstyle/checkstyle/actions/runs/4396049302/jobs/7698238711#step:4:2371
```
$ cd target/site/
✔ ~/java/github/romani/checkstyle/target/site [master|✔] 
$ ag --hidden "pitest.org"
plugin-management.html
196:<td><a class="externalLink" href="http://pitest.org">pitest-maven</a></td>
```
> dependency: bump pitest to 1.11.4

- .github/workflows/release-upload-all-jar.yml
After https://github.com/checkstyle/checkstyle/pull/12793 got merged, this comment is no longer valid.
> minor: remove stamtement that is no longer true

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierNoViolationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierRecords.java
Closes #11569
Diff Regression config: https://gist.githubusercontent.com/strkkk/238b6c97492ff6ffdb3be1603deca8fc/raw/b813fdd41472f62f3b0952b53a5670f6b61a7e11/config_single_2.xml
> Issue #11569: fix ClassMemberImpliedModifierCheck for nested record

- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierNoViolationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierRecords.java
Fixes failure noted at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/17752/workflows/b1d510a4-798d-4146-b302-3f8134d40afc/jobs/260784
> minor: bump language level in test input

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceCheckSwitchExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistance.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceAnonymous.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceIfStatements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceRegExp.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceScopes.java
Solve issue #11214. And to 'unsupress' unit test of VariableDeclarationUsageDistanceCheck. (Issue: #11968, PR: #12822)
Documentation [link](https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance)
> Issue #11214: Specified violation messages in VariableDeclarationUsageDistanceCheck

- pom.xml
fixed at https://github.com/hcoles/pitest/releases/tag/1.11.5
> dependency: bump pitest to avoid bad link generation in our website

- .ci/bump-license-year.sh
- .shellcheckrc
Related to #11637 
Doc link: https://www.shellcheck.net/wiki/SC2061
> Issue #11637: Resolve shellcheck SC2061

- config/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
- src/xdocs/config_filters.xml
> Issue #12827: Update doc for SuppressionCommentFilter

- config/pitest-suppressions/pitest-api-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java
Related to #12879 
@romani 
Surviving mutation has been killed.
> Issue #12879: Resolve pitest suppression for FilterSet

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEqualsAvoidNullTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/equalsavoidnull/SuppressionXpathRegressionEqualsAvoidNull.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/equalsavoidnull/SuppressionXpathRegressionEqualsAvoidNullIgnoreCase.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207
Add two XPath regression tests for EqualsAvoidNull check.
Documentation：https://checkstyle.sourceforge.io/config_coding.html#EqualsAvoidNull
> Issue #6207: Add xpath regression test for EqualsAvoidNull

- src/test/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilterSetTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java
Bug identified at https://github.com/checkstyle/checkstyle/pull/12888#issuecomment-1481561762
Code change should fix the bug.
https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&sinceLeakPeriod=true&id=org.checkstyle%3Acheckstyle
> minor: fixing bug of leaked violation into master

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/xdocs/config_coding.xml
Issue #12898
I changed the type of PI from int to double in the [documentation](https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance).
> Issue #12898: changed type of PI from int to double

- .ci/idea-inspection.sh
Improves output of IDEA inspections in CI
Link to inspections workflow: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/17868/workflows/bad7f959-2fad-4a94-a632-6ec27c2c1d61/jobs/265571
Output:
```
...
[INFO] Total time:  19.023 s
[INFO] Finished at: 2023-03-23T04:36:29Z
####################################################################################################
Intellij Idea validation is about to start
Progress output will be flushed at end. Validation is in progress ...
Checking results ...
ATTENTION GITHUB …
```
> minor: improve output of inspections in CI

- .github/workflows/bump-license-year.yml
- .github/workflows/bump-version-and-update-milestone.yml
- .github/workflows/diff-report.yml
- .github/workflows/error-prone.yml
- .github/workflows/no-old-refs.yml
- .github/workflows/pitest.yml
- .github/workflows/rebase.yml
- .github/workflows/release-maven-perform.yml
- .github/workflows/release-maven-prepare.yml
- .github/workflows/release-new-milestone-and-issues-in-other-repos.yml
- .github/workflows/release-publish-releasenotes-twitter.yml
- .github/workflows/release-update-github-io.yml
- .github/workflows/release-update-github-page.yml
- .github/workflows/release-update-xdoc-with-releasenotes.yml
- .github/workflows/releasenotes-gen.yml
- .github/workflows/run-link-check.yml
- .github/workflows/site.yml
- config/checkstyle-non-main-files-checks.xml
- config/checkstyle-non-main-files-suppressions.xml
Resolves #12851 
---
Errors before fixing them:
```
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/checkstyle/.github/workflows/bump-license-year.yml:26: Workflow job steps should have empty lines between each other [workflowStepSpacing]
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/checkstyle/.github/workflows/bump-license-year.yml:29: Workflow job steps should have empty lines between each other [workflowStepSpacing]
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/checkstyle/.github/workflows/bump-license-year.yml:32: Workflow job steps should have empty lines between each other [workflowStepSpacing]
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/checkstyle/.github/workflows/bump-version-and-update-milestone.yml:31: Workflow job steps should have empty lines …
```
> Issue #12851: Keep spacing between job steps consistent

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_12.java
Issue #12687: False positive about MagicNumber
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/6c454ec1c672a21710fc0cda01ceaf5b/raw/3fc36498aa1511c61c41cefb46ff02cdf8a1d2bb/magic.xml
> Issue #12687: False positive about MagicNumber

- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/xdocs/config_misc.xml
Issue #7587 
Examples added.
``` mvn clean verify``` passed.
CLI outputs:
https://gist.github.com/coderdeadpool/a1d9913669bdd123ab6d83c494d82499
> Issue #7587: Updated doc for DescendantToken

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectory.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtParent.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtSubpackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationNoPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationNoPackage.java
Issue #11214
Specified violation message in PackageDeclarationCheck.
`mvn clean verify` Passed.
> Issue #11214: Specified violation message in PackageDeclarationCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedAbovePackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadDeprecated.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedSpecialCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/package-info.java
Issue #11214 
Specified violation message in MissingDeprecatedCheck.
> Issue #11214: Specified violation message in MissingDeprecatedCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorRecordsAndCompactCtorsNoEmptyLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorJavadocCommentAfterPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleImportEmptyClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorNonPackageInfoWithJavadocBeforePackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPrePreviousLineIsEmpty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPreviousLineEmptiness.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/packageinfo/test3/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/packageinfo/test4/package-info.java
Issue #11214 
Specified violation messages in EmptyLineSeparatorCheck.
`mvn clean verify` passed.
> Issue #11214: Specified violation messages in EmptyLineSeparatorCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealed.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderAnnotationDeclaration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderIt.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderTypeAnnotations.java
Issue #11214
Specified violation message in ModifierOrderCheck.
> Issue #11214: Specified violation message in ModifierOrderCheck

- config/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
- src/xdocs/config_design.xml
Issue: https://github.com/checkstyle/checkstyle/issues/7616
https://checkstyle.org/config_design.html#VisibilityModifier
This PR adds a code example to the documentation of the VisibilityModifier check.
> Issue #7616: Add code example for VisibilityModifier check

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodDefaultAccessModifier.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodEnum.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodExtraThrows.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodGenerics.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodIgnoreThrows.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodInheritDoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodMissingJavadocTagsDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodNoJavadocDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodNoJavadocOnlyPrivateScope.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodNoJavadocProtectedScope.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodParamsTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodProtectedScopeJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodPublicOnly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodThrowsDetection.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodTypeParamsTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodsNotSkipWritten.java
Related to #11214
Diff Regression config: {{https://gist.githubusercontent.com/strkkk/121653f4a334be38b9e77e4245e144e2/raw/691fe6e90ff40473707ce77518b7a0b058bd0955/config.xml}}
GitHub, generate report
> Issue #11214: minor: Specified violation messages in JavadocMethodCheck

- .ci/append-to-github-output.sh
- .github/workflows/diff-report.yml
- .github/workflows/site.yml
Resolves #12954
Test on local fork: https://github.com/stoyanK7/checkstyle/pull/62#issuecomment-1496137559
> Issue #12954: Create script for appending text to $GITHUB_OUTPUT

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionReturnCountTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/returncount/SuppressionXpathRegressionReturnCount1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/returncount/SuppressionXpathRegressionReturnCount2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/returncount/SuppressionXpathRegressionReturnCount3.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/returncount/SuppressionXpathRegressionReturnCount4.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Addresses #6207
Adds 4 regression tests for ReturnCount check
Successfully ran mvn clean verify
ReturnCount check: https://checkstyle.org/config_coding.html#ReturnCount
> Issue #6207: Added Xpath IT regression test for ReturnCount

- .ci/append-to-github-output.sh
- .github/workflows/actionlint.yml
- .github/workflows/diff-report.yml
> Issue #12696: Use Environment Files instead of set-output in GitHub Actions

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/RightCurlyCheck.xml
Issue: #12968
Javadoc of RightCurlyCheck is broken
> minor: Javadoc of RightCurlyCheck is broken

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral3.java
issue: #12976.
I added test cases of inner class, annoymous class, extends, implements, constructor methods, lambda expressions.
> Issue #12976: added test cases of inner class, anonymous class, extends and implements

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
Related to #12671 #12341
Diff Regression config: https://gist.githubusercontent.com/coderdeadpool/96fa62c511add1eb980efe8de851256d/raw/57420e4b601c7ed073340dd039e5c4af7a0d1ccd/gistfile1.txt
> Issue #12671: Resolve pitest suppression for FinalLocalVariableCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagDoubleTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEmptyTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEnumsAndAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagExpressionError.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagIncomplete.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMissingFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMissingTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagNoJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagSeverity.java
Issue #11214 : Specified violation message in WriteTagCheck
> Issue #11214: Specified violation message in WriteTagCheck

- .ci/diff-report.sh
Items from https://github.com/checkstyle/checkstyle/pull/13017#pullrequestreview-1395980148
> minor: clean up validate_url function

- .ci/validation.sh
- config/checkstyle-checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperator2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperator3.java
- src/xdocs/config_coding.xml
Issue #11109: False Negative: UnnecessaryParenthesesCheck2
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/d7bafc525a9bbbd310d26fc1450d8c73/raw/f08834a6a50b6d149d81930a3ce5894a729d3c65/upara.xml
> Issue #11109: False Negative: UnnecessaryParenthesesCheck2

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceTryResources.java
Issue: #11968 
- I used some code from Pull Request: #12543.
- I removed unnecessary suppressed mutation 
```
<sourceFile>VariableDeclarationUsageDistanceCheck.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck</mutatedClass>
<mutatedMethod>getFirstNodeInsideTryCatchFinallyBlocks</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.NakedReceiverMutator</mutator>
<description>replaced call to com/puppycrawl/tools/checkstyle/api/DetailAST::getLastChild with receiver</description>
<lineContent>final DetailAST finalBlock = currentNode.getLastChild();</lineContent>
</mutation>
```
- This PR solved Issue: #11968 as follows:
```
less config.xml
```
```
<?xml …
```
> Issue #11968: corrected false positive in VariableDeclarationUsageDistanceCheck

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastDefaultMethodsInInterface2.java
Issue: #12889
The suppressed mutation can be removed.
Diff Regression config: https://gist.githubusercontent.com/jxr98/2f9093b28e91baa6f3bf425bdfb54cb7/raw/d939ffe15d9d8ca975b8ea05d5c79cf290454b92/DefaultComesLast.xml
> Issue #12889: killed survivng mutation in DefaultComesLastCheck

- src/xdocs/index.xml.vm
latest:
without "when maintainers wants"
all
> doc: new release cycle

- pom.xml
minor: update Pitest to latest version
> minor: update Pitest to latest version

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistance3.java
Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 2
Covering 
https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L147-L154
and 
https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L156-L163
and 
https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L165-L172
> Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 2

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistance1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceScope2.java
Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 1
covering https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L120-L127
and 
https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L138-L145
> Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 1

- src/xdocs-test/java/com/puppycrawl/tools/checkstyle/checks/.gitkeep
- src/xdocs-test/resources-noncompatible/com/puppycrawl/tools/checkstyle/checks/.gitkeep
- src/xdocs-test/resources/com/puppycrawl/tools/checkstyle/checks/.gitkeep
Resolves https://github.com/checkstyle/checkstyle/issues/13100#issuecomment-1567422929
> Pull #13105: Create initial xdocs-test folder structure

- .github/workflows/release.yml
Related to  #13094
summer is starting .... I doubt I have time to investigate why it is failing. we will come back to it later on.
> infra: disable twitter posts until #13094

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 6
covering 
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L111-L118
> Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 6

- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Minor fix for https://github.com/checkstyle/checkstyle/pull/13201 .
> minor: fixed new eclipse violations in MainTest

- pom.xml
Extracted from https://github.com/checkstyle/checkstyle/pull/13207
I am transferring other examples and face the same issues so I need it merged as soon as possible.
> config: exclude Example files from forbiddenapis check

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/Example2.java
https://checkstyle.sourceforge.io/config_whitespace.html#NoWhitespaceAfter
> Issue #13100: Create tests from NoWhitespaceAfter xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/Example2.java
https://checkstyle.sourceforge.io/config_whitespace.html#MethodParamPad
> Issue #13100: Create tests from MethodParamPad xdoc examples

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable3.java
Issue #12671: Kill mutation for finalLocalVariable-3
-------
https://checkstyle.org/config_coding.html#FinalLocalVariable
-------
https://github.com/checkstyle/checkstyle/blob/398035a2cc135f86523f1942b468b2b06b717919/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L30-L37
----
> Issue #12671: Kill mutation for finalLocalVariable-3

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/Example2.java
https://checkstyle.sourceforge.io/config_whitespace.html#EmptyForInitializerPad
> Issue #13100: Create tests from EmptyForInitializerPad xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/Example5.java
https://checkstyle.sourceforge.io/config_whitespace.html#EmptyLineSeparator
> Issue #13100: Create tests from EmptyLineSeparator xdoc examples

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeAbstractClassNameFormat.java
Issue #13109: Kill mutation for IllegalTypeCheck
--------
https://checkstyle.org/config_coding.html#IllegalType
------
https://github.com/checkstyle/checkstyle/blob/eaed451ba71f543d7a98675d521ca8bb428f79d5/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L75-L91
----
Test added :)
> Issue #13109: Kill mutation for IllegalTypeCheck

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckTest.java
Issue #13109: Kill mutation for PackageDeclarationCheck
-------------
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L48-L55
> Issue #13109: Kill mutation for PackageDeclarationCheck

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/Example7.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/SuperClass.java
Part of #13100
https://checkstyle.sourceforge.io/config_naming.html#AbbreviationAsWordInName
> Issue #13100: Create tests from AbbreviationAsWordInName xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/Example4.java
Part of #13100
https://checkstyle.sourceforge.io/config_whitespace.html#NoWhitespaceBefore_Examples
> Issue #13100: Create tests from NoWhitespaceBefore xdoc examples

- pom.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/Example4.xml
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/Example5.html
> Issue #13100: Create tests from FileTabCharacter xdoc examples 

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/Example2.java
https://checkstyle.sourceforge.io/config_whitespace.html#OperatorWrap_Examples
> Issue #13100: Create tests from OperatorWrap xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/Example3.java
Part of #13100
https://checkstyle.sourceforge.io/config_whitespace.html#SeparatorWrap
> Issue #13100: Create tests from SeparatorWrap xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCaseDefaultColonExamplesTest.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java
Part of #13100
https://checkstyle.sourceforge.io/config_whitespace.html#NoWhitespaceBeforeCaseDefaultColon_Examples
> Issue #13100: Create tests from NoWhitespaceBeforeCaseDefaultColon xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/Example2.java
Part of #13100
https://checkstyle.sourceforge.io/config_sizes.html#LambdaBodyLength_Examples
> Issue #13100: Create tests from LambdaBodyLength xdoc examples

- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/Example1.java
I saw that it is version 14 from https://rules.sonarsource.com/java/RSPEC-6208
> In Java 14 there is a new way to write cases in Switch Statement and Expression when the same action should be performed for different cases.
> minor: add java compilation version comment and fix example

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepthDefault.java
Issue #13109: Kill mutation for NestedForDepthCheck-2
--------
https://checkstyle.org/config_coding.html#NestedForDepth
----------
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L84-L91
----------
Test added
> Issue #13109: Kill mutation for NestedForDepthCheck-2

- config/checkstyle-input-suppressions.xml
- config/checkstyle-resources-suppressions.xml
- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportWithoutPackage.java
Issue #13109: Kill mutation for RedundantImportCheck
------
https://checkstyle.org/config_imports.html#RedundantImport
-------
https://github.com/checkstyle/checkstyle/blob/461944ca99db34ee419bb0a9030952621aaf93e4/config/pitest-suppressions/pitest-imports-suppressions.xml#L147-L154
------
Test cases added
> Issue #13109: Kill mutation for RedundantImportCheck

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/Example5.java
Part of #13100
https://checkstyle.sourceforge.io/config_whitespace.html#NoLineWrap
> Issue #13100: Create tests from NoLineWrap xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/Example2.java
https://checkstyle.sourceforge.io/config_whitespace.html#TypecastParenPad
> Issue #13100: Create tests from TypecastParenPad xdoc examples

- src/main/resources/google_checks.xml
- src/main/resources/sun_checks.xml
- src/site/site.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config.xml
- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml
- src/xdocs/filefilters/index.xml
> Issue #13097: Split filefilters xdocs into separate pages

- src/site/resources/css/site.css
> Issue #13195: Mobile page rendering requires extra font difference for properties

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example2.java
Part of #13100
https://checkstyle.org/config_whitespace.html#SingleSpaceSeparator
> Issue #13100: Create tests from SingleSpaceSeparator xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/Example2.java
Part of #13100
https://checkstyle.sourceforge.io/config_whitespace.html#ParenPad
> Issue #13100: Create tests from ParenPad xdoc examples

- config/checkstyle-examples-checks.xml
- config/checkstyle-examples-suppressions.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/Example1.java
> Issue #13244: Extend checkstyle-examples-checks

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example10.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example7.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example8.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example9.java
https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAround
> Issue #13100: Create tests from WhitespaceAround xdoc examples

- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example10.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example7.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example8.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/Example9.java
minor: Fix Indentation
related to failures in master: https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=15057&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069&t=a9b761e6-b8d5-50cf-467a-54967189cab2
Looks like we leaked failures into master branch from PR branch not having latest checkstyle config.
> minor: Fix Indentation

- src/site/site.xml
> Issue #13283: Move Filters and File Filters to be a sibling of Checks in site menu

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplevariabledeclarations/InputMultipleVariableDeclarations2.java
Issue #13109: Kill mutation for MultipleVariableDeclarationsCheck
--------
https://checkstyle.org/config_coding.html#MultipleVariableDeclarations
--------
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L66-L82
-------
Test added
---------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/47e3287_2023184215/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/47e3287_2023211141/reports/diff/index.html
------------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/201dae231798cb048eca902b7b21d6ea/raw/6655ab3c5cff01a88fcbc704e671b6be0c441a98/MultipleVariableDeclarationsCheck.xml …
> Issue #13109: Kill mutation for MultipleVariableDeclarationsCheck

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- config/jsoref-spellchecker/whitelist.words
> Issue #13310: Update issue template after split of website to use individual page for module

- config/checkstyle-examples-suppressions.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterExamplesTest.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/Example2.java
https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAfter
> Issue #13100: Create tests from WhitespaceAfter xdoc examples

- config/checkstyle-resources-suppressions.xml
- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationBeginTree1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationBeginTree2.java
Issue #13328: Kill mutation for IllegalInstantiationCheck
-----
Check :
https://checkstyle.org/config_coding.html#IllegalInstantiation
-----
https://github.com/checkstyle/checkstyle/blob/6324a9d693324eb755c2cdfdbd90c2300d3c7f02/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L30-L37
-----
Tests Added
-------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/3bd236a24ed8eacd760e6b12b47f7455/raw/97d7a64aa97fc35488a6db5d7345ee23ae9b9507/olc.xml
> Issue #13328: Kill mutation for IllegalInstantiationCheck

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
Resolves #13301 
Adds a test to ensure that every module xdoc has a link in the menu.
> Issue #13301: Write a test to ensure checks are present in menu

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
Issue #13328: Kill mutation UnusedImport
-----------
https://checkstyle.org/checks/imports/unusedimports.html#UnusedImports
-----------
https://github.com/checkstyle/checkstyle/blob/61eb1ae8fb640763d7b3f260c8f7860adef5fdd3/config/pitest-suppressions/pitest-imports-suppressions.xml#L111-L118
----------
Test added
> Issue #13328: Kill mutation UnusedImport

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough3.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough4.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughFallThroughLotsOfComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughFallThroughLotsOfComment2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughLastLineCommentCheck.java
minor: Test setup for FallThroughCheck
For https://github.com/checkstyle/checkstyle/pull/12966
> minor: Test setup for FallThroughCheck

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
supplemental: Remove Pitest-coding-1 suppression file
> supplemental: Remove Pitest-coding-1 suppression file

- config/pitest-suppressions/pitest-api-suppressions.xml
- config/sevntu-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/api/fullident/InputFullIdent.java
Issue #13109: Kill mutation for FullIdent.java-2
---
https://github.com/checkstyle/checkstyle/blob/b8753a7a025f706d41e6e7b1de302d94da3b8c0f/config/pitest-suppressions/pitest-api-suppressions.xml#L48-L55
> Issue #13109: Kill mutation for FullIdent.java-2

- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainBeginTree2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainRecords2.java
Issue #13321: Kill mutation for UncommentedMainCheck-1
---------
https://checkstyle.org/checks/misc/uncommentedmain.html
---------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L192-L199
---------
Test added
> Issue #13321: Kill mutation for UncommentedMainCheck-1

- config/checkstyle-examples-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example10.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example11.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example12.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example7.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example8.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/Example9.java
- src/xdocs/checks/design/visibilitymodifier.xml
> Issue #13100: Create tests from VisibilityModifier xdoc examples

- config/pitest-suppressions/pitest-regexp-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic8.java
Issue #13321: Kill mutation for RegexpCheck
-------
https://checkstyle.org/checks/regexp/regexpsinglelinejava.html#RegexpSinglelineJava
https://checkstyle.org/checks/regexp/regexpsingleline.html#RegexpSingleline
-------
https://github.com/checkstyle/checkstyle/blob/4b7a2dfd9d98e8fdd59a220e45e365aa6a6507b3/config/pitest-suppressions/pitest-regexp-suppressions.xml#L75-L82
https://github.com/checkstyle/checkstyle/blob/4b7a2dfd9d98e8fdd59a220e45e365aa6a6507b3/config/pitest-suppressions/pitest-regexp-suppressions.xml#L57-L64
--------
Test added
> Issue #13321: Kill mutation for RegexpCheck

- config/checkstyle-resources-suppressions.xml
- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainBeginTreePackage1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainBeginTreePackage2.java
Issue #13321: Kill mutation for UncommentedMainCheck-2
---------
https://checkstyle.org/checks/misc/uncommentedmain.html
---------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L210-L226
---------
Test added
> Issue #13321: Kill mutation for UncommentedMainCheck-2

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierAnnotatedSameTypeName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableSameTypeName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableSameTypeName2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableStarImport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierIsStarImport.java
Issue: #4845
Modified inputs for files in VisibilityModifer. 
Updated VisibilityModifierCheckTest to keep the original purpose
Updated checkstyle_input_supressions.xml to reflect changes
> Issue #4845: Removed checkstyle dependencies from VisibilityModifer inputs

- config/pitest-suppressions/pitest-regexp-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
Issue #13321: Kill mutation for RegexpCheck-2
----------
https://checkstyle.org/checks/regexp/regexpsinglelinejava.html#RegexpSinglelineJava
https://checkstyle.org/checks/regexp/regexpsingleline.html#RegexpSingleline
---------
https://github.com/checkstyle/checkstyle/blob/4b7a2dfd9d98e8fdd59a220e45e365aa6a6507b3/config/pitest-suppressions/pitest-regexp-suppressions.xml#L66-L73
https://github.com/checkstyle/checkstyle/blob/4b7a2dfd9d98e8fdd59a220e45e365aa6a6507b3/config/pitest-suppressions/pitest-regexp-suppressions.xml#L84-L91
> Issue #13321: Kill mutation for RegexpCheck-2

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefaultPackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderEclipseDefaultPositive.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderNoPackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderNoPackage2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderNoPackage3.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSamePackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSamePackage2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSamePackageDepth25.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSamePackageDepth252.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSamePackageDepth253.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderThirdPartyAndSpecial.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderThirdPartyAndSpecial2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderViolationsSameLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderCompareImports.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderEmptyRule.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderFindBetterPatternMatch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderImportsContainingJava.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderPossibleIndexOutOfBoundsException.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpanMultipleLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_MultiplePatternMultipleImport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_NoSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_OverlappingPatterns.java
Issue #11214: Specified violation messages for CustomImportOrderCheck in all the input test files in accordance with message.properties
> Issue #11214: Specified violation messages for CustomImportOrderCheck

- config/jsoref-spellchecker/whitelist.words
- config/pitest-suppressions/pitest-utils-suppressions.xml
- config/sevntu-suppressions.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/annotationutil/InputAnnotationUtil1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/annotationutil/InputAnnotationUtil2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil3.java
Issue #13321: Kill mutation for pitest-utils profile
> Issue #13321: Kill mutation for pitest-utils profile

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/xdocs/checks/coding/fallthrough.xml
Issue #12974: Updated Fall through docs such that user can try all the fall through checks on a single common code
> Issue #12974: Updated Fall through docs

- src/main/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/misc/index.html
> Issue #13421: Add since in javadoc of each property setter for misc checks

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/Example2.txt
Part of #13100
https://checkstyle.org/checks/annotation/annotationonsameline.html#Examples
> Issue #13100: Create tests from AnnotationOnSameLine xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/Example4.txt
https://checkstyle.org/checks/annotation/annotationusestyle.html#Examples
> Issue #13100: Create tests from AnnotationUseStyle xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/Example2.txt
https://checkstyle.org/checks/annotation/missingdeprecated.html#Examples
> Issue #13100: Create tests from MissingDeprecated xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/Example2.txt
https://checkstyle.org/checks/annotation/missingoverride.html#Examples
> Issue #13100: Create tests from MissingOverride xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/Example2.txt
Part of #13100
https://checkstyle.org/checks/annotation/suppresswarnings.html#Examples
> Issue #13100: Create tests from SuppressWarnings xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/Example2.txt
Part of #13100
https://checkstyle.org/checks/blocks/avoidnestedblocks.html
> Issue #13100: Create tests from AvoidNestedBlocks xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example3.txt
https://checkstyle.org/checks/blocks/emptyblock.html#Examples
> Issue #13100: Create tests from EmptyBlock xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example4.txt
https://checkstyle.org/checks/blocks/emptycatchblock.html#Examples
> Issue #13100: Create tests from EmptyCatchBlock xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/Example4.txt
https://checkstyle.org/checks/blocks/leftcurly.html#Examples
> Issue #13100: Create tests from LeftCurly xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example4.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example5.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example6.txt
https://checkstyle.org/checks/blocks/needbraces.html#Examples
> Issue #13100: Create tests from NeedBraces xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example4.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example5.txt
https://checkstyle.org/checks/blocks/rightcurly.html#Examples
> Issue #13100: Create tests from RightCurly xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/Example4.txt
https://checkstyle.org/checks/design/designforextension.html#Examples
> Issue #13100: Create tests from DesignForExtension xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/Example1.txt
https://checkstyle.org/checks/design/finalclass.html#Examples
> Issue #13100: Create tests from FinalClass xdoc examples

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/Example1.txt
https://checkstyle.org/checks/design/hideutilityclassconstructor.html#Examples
> Issue #13100: Create tests from HideUtilityClassConstructor xdoc examples

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-xpath-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/iterators/DescendantIterator.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/iterators/FollowingIterator.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/iterators/PrecedingIterator.java
Issue #13321: Kill mutation for Xpath profile
------
https://github.com/checkstyle/checkstyle/blob/89e3ffcf7c2a7f764c5e76d52af25d8283b3d3b3/config/pitest-suppressions/pitest-xpath-suppressions.xml#L57-L73
and 
https://github.com/checkstyle/checkstyle/blob/89e3ffcf7c2a7f764c5e76d52af25d8283b3d3b3/config/pitest-suppressions/pitest-xpath-suppressions.xml#L84-L91
---------
All are default value and they are in constructor
> Issue #13321: Kill mutation for Xpath profile

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/Example1.txt
- src/xdocs/checks/design/innertypelast.xml.template
https://checkstyle.org/checks/design/innertypelast.html#Examples
> Issue #13100: Create tests from InnerTypeLast xdoc examples

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil5.java
Issue #13321: Kill mutation for CheckUtil-5
-----
https://github.com/checkstyle/checkstyle/blob/f4a33f90bf8eda8ef2cdf7f66fd60878d2aa1736/config/pitest-suppressions/pitest-utils-suppressions.xml#L30-L46
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/df2ff7a8f9969bb2c68d7251a97ffa8b/raw/6a4e81a624fa36483f23b0adcf1fc513ca6df350/JavadocMethod.xml
> Issue #13321: Kill mutation for CheckUtil-5

- src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java
just to keep checker in same method
> minor: refactoring to ease reading

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/Example4.txt
Part of #13100
https://checkstyle.sourceforge.io/checks/annotation/annotationlocation.html#AnnotationLocation
> Issue #13100: Create tests from AnnotationLocation xdoc examples

- config/checkstyle-checks.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
Closes #13421 
---
DO NOT MERGE until all other PRs referencing #13421 are merged
> Issue #13421: Add check to ensure all module setters have since in javadoc

- config/projects-to-test/openjdk20-excluded.files
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclarationNullAst.java
Issue #13411: Fix NPE in UnnecessarySemicolonAfterTypeMemberDeclarationCheck
Diff Regression config: https://gist.githubusercontent.com/relentless-pursuit/95180658ff45ac1bab444f2c35ac301d/raw/d53eda164c7ccd456cb6a1def8bb4e4f0de9c39c/gistfile1.txt
> Issue #13411: Fix NPE in UnnecessarySemicolonAfterTypeMemberDeclarationCheck

- config/pitest-suppressions/pitest-regexp-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTree1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTree2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTreeLastVariableResourcesStatementEnd1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTreeLastVariableResourcesStatementEnd2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckB1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckB2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckB3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckB4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckEmptyLine2.java
Issue #13501: Kill mutation for RegexpCheck-3
-------
https://checkstyle.org/checks/regexp/regexp.html#Regexp
-------
https://github.com/checkstyle/checkstyle/blob/4b7a2dfd9d98e8fdd59a220e45e365aa6a6507b3/config/pitest-suppressions/pitest-regexp-suppressions.xml#L21-L55
-------
Test added
> Issue #13501: Kill mutation for RegexpCheck-3

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
Issue #13321: Kill mutation for CommonUtil
------
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L237-L245
------
No usage in the whole codebase
> Issue #13321: Kill mutation for CommonUtil

- config/checkstyle-resources-suppressions.xml
- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlBeginTree.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlBeginTree1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlBeginTree2.java
Issue #13501: Kill mutation for ImportControlCheck
-------
https://checkstyle.org/checks/imports/importcontrol.html#ImportControl
------
https://github.com/checkstyle/checkstyle/blob/5eedd6cf806c85da84291ddb9fcafee122a0539c/config/pitest-suppressions/pitest-imports-suppressions.xml#L21-L28
--------
Test expansion
> Issue #13501: Kill mutation for ImportControlCheck

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/whitespace/whitespaceafter.xml
- src/xdocs/checks/whitespace/whitespaceafter.xml.template
Resolves #13428 
---
PR is in draft so I can show failing CI
> Issue #13428: Add a test to ensure examples have a paragraph with an id before them

- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
Fixes leaked failure in master
Link to inspection build: https://circleci.com/gh/checkstyle/checkstyle/352365
> minor: suppress IDEA inspections violation

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck1.java
Issue #13501: Kill mutation for HtmlTag
-------
https://github.com/checkstyle/checkstyle/blob/7e879f3eedd9302623a6b2ac383b22af1cbe99f0/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L75-L82
---------
Test added
> Issue #13501: Kill mutation for HtmlTag

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/EmptyLineSeparatorCheck.xml
- src/xdocs/checks/whitespace/emptylineseparator.xml
> Issue #13506: Remove outdated XPath suppression warning from EmptyLineSeparator

- src/xdocs/checks/design/designforextension.xml.template
- src/xdocs/checks/design/finalclass.xml.template
- src/xdocs/checks/design/hideutilityclassconstructor.xml.template
- src/xdocs/checks/design/interfaceistype.xml.template
- src/xdocs/checks/design/mutableexception.xml.template
- src/xdocs/checks/design/onetoplevelclass.xml.template
- src/xdocs/checks/design/throwscount.xml.template
- src/xdocs/checks/design/visibilitymodifier.xml.template
Part of #13498
---
Copied the `design` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from design checks xdocs

- src/xdocs/checks/misc/arraytypestyle.xml.template
- src/xdocs/checks/misc/avoidescapedunicodecharacters.xml.template
- src/xdocs/checks/misc/commentsindentation.xml.template
- src/xdocs/checks/misc/descendanttoken.xml.template
- src/xdocs/checks/misc/finalparameters.xml.template
- src/xdocs/checks/misc/indentation.xml.template
- src/xdocs/checks/misc/newlineatendoffile.xml.template
- src/xdocs/checks/misc/nocodeinfile.xml.template
- src/xdocs/checks/misc/orderedproperties.xml.template
- src/xdocs/checks/misc/outertypefilename.xml
- src/xdocs/checks/misc/outertypefilename.xml.template
- src/xdocs/checks/misc/todocomment.xml.template
- src/xdocs/checks/misc/trailingcomment.xml.template
- src/xdocs/checks/misc/translation.xml.template
- src/xdocs/checks/misc/uncommentedmain.xml.template
- src/xdocs/checks/misc/uniqueproperties.xml.template
- src/xdocs/checks/misc/upperell.xml.template
Part of #13498
---
Copied the `misc` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from misc checks xdocs

- src/xdocs/filters/severitymatchfilter.xml.template
- src/xdocs/filters/suppressioncommentfilter.xml.template
- src/xdocs/filters/suppressionfilter.xml.template
- src/xdocs/filters/suppressionsinglefilter.xml.template
- src/xdocs/filters/suppressionxpathfilter.xml.template
- src/xdocs/filters/suppressionxpathsinglefilter.xml.template
- src/xdocs/filters/suppresswarningsfilter.xml.template
- src/xdocs/filters/suppresswithnearbycommentfilter.xml.template
- src/xdocs/filters/suppresswithnearbytextfilter.xml.template
- src/xdocs/filters/suppresswithplaintextcommentfilter.xml.template
Part of #13498
---
Copied the `filters` xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from filters xdocs

- .ci/travis.sh
- .travis.yml
- config/jsoref-spellchecker/whitelist.words
after doing : https://github.com/checkstyle/checkstyle/pull/13510
and loooking at logs
https://app.travis-ci.com/github/checkstyle/checkstyle/builds/265020910#L330
so finally jdk installer fixed problem with javahome.
> infra: fix Travis problem with JAVA_HOME

- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitCyclesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitSuperClassTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
> minor: skip ArchUnit Testing until #13544

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil7.java
Issue #13321: Kill mutation for CheckUtil-4
-----
https://github.com/checkstyle/checkstyle/blob/f4a33f90bf8eda8ef2cdf7f66fd60878d2aa1736/config/pitest-suppressions/pitest-utils-suppressions.xml#L48-L55
-----
Test added
> Issue #13321: Kill mutation for CheckUtil-4

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/Example3.java
Issue #12974: Added test cases for fallthrough doc examples.
> Issue #12974: Added test cases for fallthrough doc examples

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocType1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocType2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocType3.java
Issue #13501: Kill mutation for JavadocTypeCheck1
----
https://checkstyle.org/checks/javadoc/javadoctype.html#JavadocType
-------
Test added
> Issue #13501: Kill mutation for JavadocTypeCheck1

- .github/workflows/site.yml
Issue #13567
this is the only difference from other yml file I can spot.
looks like idea parser is not stable on parsing and we have only problems in site.yml file.
> Issue #13567: upadte site.yml to fix idea inspection violations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/Example2.txt
- src/xdocs/checks/modifier/classmemberimpliedmodifier.xml
- src/xdocs/checks/modifier/classmemberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/interfacememberimpliedmodifier.xml
- src/xdocs/checks/modifier/interfacememberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/modifierorder.xml
- src/xdocs/checks/modifier/modifierorder.xml.template
- src/xdocs/checks/modifier/redundantmodifier.xml
- src/xdocs/checks/modifier/redundantmodifier.xml.template
Part of #13100
https://checkstyle.org/checks/modifier/index.html
> Issue #13100: Create tests from modifiers category checks xdoc examples

- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocType4.java
> minor: remove //ok Comment

- src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filefilters/beforeexecutionexclusionfilefilter/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filefilters/beforeexecutionexclusionfilefilter/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filefilters/beforeexecutionexclusionfilefilter/Example3.txt
- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml
- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml.template
Part of #13100
https://checkstyle.org/filefilters/index.html
> Issue #13100: Create tests from filefilters  xdoc examples

- src/xdocs/checks/design/designforextension.xml.template
- src/xdocs/checks/design/finalclass.xml.template
- src/xdocs/checks/design/hideutilityclassconstructor.xml.template
- src/xdocs/checks/design/innertypelast.xml.template
- src/xdocs/checks/design/interfaceistype.xml.template
- src/xdocs/checks/design/mutableexception.xml.template
- src/xdocs/checks/design/onetoplevelclass.xml.template
- src/xdocs/checks/design/throwscount.xml.template
- src/xdocs/checks/design/visibilitymodifier.xml.template
> Issue #13610: Use parent module macro in design templates

- src/xdocs/checks/imports/avoidstarimport.xml.template
- src/xdocs/checks/imports/avoidstaticimport.xml.template
- src/xdocs/checks/imports/customimportorder.xml.template
- src/xdocs/checks/imports/illegalimport.xml.template
- src/xdocs/checks/imports/importcontrol.xml.template
- src/xdocs/checks/imports/importorder.xml.template
- src/xdocs/checks/imports/redundantimport.xml.template
- src/xdocs/checks/imports/unusedimports.xml.template
> Issue #13610: Use parent module macro in imports templates

- src/xdocs/checks/misc/arraytypestyle.xml.template
- src/xdocs/checks/misc/avoidescapedunicodecharacters.xml.template
- src/xdocs/checks/misc/commentsindentation.xml.template
- src/xdocs/checks/misc/descendanttoken.xml.template
- src/xdocs/checks/misc/finalparameters.xml.template
- src/xdocs/checks/misc/indentation.xml.template
- src/xdocs/checks/misc/newlineatendoffile.xml.template
- src/xdocs/checks/misc/nocodeinfile.xml.template
- src/xdocs/checks/misc/orderedproperties.xml.template
- src/xdocs/checks/misc/outertypefilename.xml.template
- src/xdocs/checks/misc/todocomment.xml.template
- src/xdocs/checks/misc/trailingcomment.xml.template
- src/xdocs/checks/misc/translation.xml.template
- src/xdocs/checks/misc/uncommentedmain.xml.template
- src/xdocs/checks/misc/uniqueproperties.xml.template
- src/xdocs/checks/misc/upperell.xml.template
> Issue #13610: Use parent module macro in misc templates

- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/filters/severitymatchfilter.xml
- src/xdocs/filters/severitymatchfilter.xml.template
- src/xdocs/filters/suppressioncommentfilter.xml
- src/xdocs/filters/suppressioncommentfilter.xml.template
- src/xdocs/filters/suppressionfilter.xml
- src/xdocs/filters/suppressionfilter.xml.template
- src/xdocs/filters/suppressionsinglefilter.xml
- src/xdocs/filters/suppressionsinglefilter.xml.template
- src/xdocs/filters/suppressionxpathfilter.xml
- src/xdocs/filters/suppressionxpathfilter.xml.template
- src/xdocs/filters/suppressionxpathsinglefilter.xml
- src/xdocs/filters/suppressionxpathsinglefilter.xml.template
- src/xdocs/filters/suppresswarningsfilter.xml
- src/xdocs/filters/suppresswarningsfilter.xml.template
- src/xdocs/filters/suppresswithnearbycommentfilter.xml
- src/xdocs/filters/suppresswithnearbycommentfilter.xml.template
- src/xdocs/filters/suppresswithnearbytextfilter.xml
- src/xdocs/filters/suppresswithnearbytextfilter.xml.template
- src/xdocs/filters/suppresswithplaintextcommentfilter.xml
- src/xdocs/filters/suppresswithplaintextcommentfilter.xml.template
> Issue #13610: Use parent module macro in filters templates

- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml
- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml.template
> Issue #13610: Use parent module macro in filefilters templates

- src/xdocs/checks/annotation/annotationlocation.xml
- src/xdocs/checks/annotation/annotationlocation.xml.template
- src/xdocs/checks/annotation/annotationonsameline.xml
- src/xdocs/checks/annotation/annotationonsameline.xml.template
- src/xdocs/checks/annotation/annotationusestyle.xml
- src/xdocs/checks/annotation/annotationusestyle.xml.template
- src/xdocs/checks/annotation/missingdeprecated.xml
- src/xdocs/checks/annotation/missingdeprecated.xml.template
- src/xdocs/checks/annotation/missingoverride.xml
- src/xdocs/checks/annotation/missingoverride.xml.template
- src/xdocs/checks/annotation/packageannotation.xml
- src/xdocs/checks/annotation/packageannotation.xml.template
- src/xdocs/checks/annotation/suppresswarnings.xml
- src/xdocs/checks/annotation/suppresswarnings.xml.template
> Issue #13627: Use violation messages macro in annotation templates

- src/xdocs/checks/blocks/avoidnestedblocks.xml
- src/xdocs/checks/blocks/avoidnestedblocks.xml.template
- src/xdocs/checks/blocks/emptyblock.xml
- src/xdocs/checks/blocks/emptyblock.xml.template
- src/xdocs/checks/blocks/emptycatchblock.xml
- src/xdocs/checks/blocks/emptycatchblock.xml.template
- src/xdocs/checks/blocks/leftcurly.xml
- src/xdocs/checks/blocks/leftcurly.xml.template
- src/xdocs/checks/blocks/needbraces.xml
- src/xdocs/checks/blocks/needbraces.xml.template
- src/xdocs/checks/blocks/rightcurly.xml
- src/xdocs/checks/blocks/rightcurly.xml.template
> Issue #13627: Use violation messages macro in block templates

- src/xdocs/checks/design/designforextension.xml
- src/xdocs/checks/design/designforextension.xml.template
- src/xdocs/checks/design/finalclass.xml
- src/xdocs/checks/design/finalclass.xml.template
- src/xdocs/checks/design/hideutilityclassconstructor.xml
- src/xdocs/checks/design/hideutilityclassconstructor.xml.template
- src/xdocs/checks/design/innertypelast.xml
- src/xdocs/checks/design/innertypelast.xml.template
- src/xdocs/checks/design/interfaceistype.xml
- src/xdocs/checks/design/interfaceistype.xml.template
- src/xdocs/checks/design/mutableexception.xml
- src/xdocs/checks/design/mutableexception.xml.template
- src/xdocs/checks/design/onetoplevelclass.xml
- src/xdocs/checks/design/onetoplevelclass.xml.template
- src/xdocs/checks/design/throwscount.xml
- src/xdocs/checks/design/throwscount.xml.template
- src/xdocs/checks/design/visibilitymodifier.xml
- src/xdocs/checks/design/visibilitymodifier.xml.template
> Issue #13627: Use violation messages macro in design templates

- src/xdocs/checks/imports/avoidstarimport.xml
- src/xdocs/checks/imports/avoidstarimport.xml.template
- src/xdocs/checks/imports/avoidstaticimport.xml
- src/xdocs/checks/imports/avoidstaticimport.xml.template
- src/xdocs/checks/imports/customimportorder.xml
- src/xdocs/checks/imports/customimportorder.xml.template
- src/xdocs/checks/imports/illegalimport.xml
- src/xdocs/checks/imports/illegalimport.xml.template
- src/xdocs/checks/imports/importcontrol.xml
- src/xdocs/checks/imports/importcontrol.xml.template
- src/xdocs/checks/imports/importorder.xml
- src/xdocs/checks/imports/importorder.xml.template
- src/xdocs/checks/imports/redundantimport.xml
- src/xdocs/checks/imports/redundantimport.xml.template
- src/xdocs/checks/imports/unusedimports.xml
- src/xdocs/checks/imports/unusedimports.xml.template
> Issue #13627: Use violation messages macro in imports templates

- src/xdocs/checks/metrics/booleanexpressioncomplexity.xml
- src/xdocs/checks/metrics/booleanexpressioncomplexity.xml.template
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml.template
- src/xdocs/checks/metrics/classfanoutcomplexity.xml
- src/xdocs/checks/metrics/classfanoutcomplexity.xml.template
- src/xdocs/checks/metrics/cyclomaticcomplexity.xml
- src/xdocs/checks/metrics/cyclomaticcomplexity.xml.template
- src/xdocs/checks/metrics/javancss.xml
- src/xdocs/checks/metrics/javancss.xml.template
- src/xdocs/checks/metrics/npathcomplexity.xml
- src/xdocs/checks/metrics/npathcomplexity.xml.template
> Issue #13627: Use violation messages macro in metrics templates

- src/xdocs/checks/modifier/classmemberimpliedmodifier.xml
- src/xdocs/checks/modifier/classmemberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/interfacememberimpliedmodifier.xml
- src/xdocs/checks/modifier/interfacememberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/modifierorder.xml
- src/xdocs/checks/modifier/modifierorder.xml.template
- src/xdocs/checks/modifier/redundantmodifier.xml
- src/xdocs/checks/modifier/redundantmodifier.xml.template
> Issue #13627: Use violation messages macro in modifiers templates

- src/xdocs/checks/regexp/regexp.xml
- src/xdocs/checks/regexp/regexp.xml.template
- src/xdocs/checks/regexp/regexpmultiline.xml
- src/xdocs/checks/regexp/regexpmultiline.xml.template
- src/xdocs/checks/regexp/regexponfilename.xml
- src/xdocs/checks/regexp/regexponfilename.xml.template
- src/xdocs/checks/regexp/regexpsingleline.xml
- src/xdocs/checks/regexp/regexpsingleline.xml.template
- src/xdocs/checks/regexp/regexpsinglelinejava.xml
- src/xdocs/checks/regexp/regexpsinglelinejava.xml.template
> Issue #13627: Use violation messages macro in regexp templates

- src/xdocs/checks/sizes/anoninnerlength.xml
- src/xdocs/checks/sizes/anoninnerlength.xml.template
- src/xdocs/checks/sizes/executablestatementcount.xml
- src/xdocs/checks/sizes/executablestatementcount.xml.template
- src/xdocs/checks/sizes/filelength.xml
- src/xdocs/checks/sizes/filelength.xml.template
- src/xdocs/checks/sizes/lambdabodylength.xml
- src/xdocs/checks/sizes/lambdabodylength.xml.template
- src/xdocs/checks/sizes/linelength.xml
- src/xdocs/checks/sizes/linelength.xml.template
- src/xdocs/checks/sizes/methodcount.xml
- src/xdocs/checks/sizes/methodcount.xml.template
- src/xdocs/checks/sizes/methodlength.xml
- src/xdocs/checks/sizes/methodlength.xml.template
- src/xdocs/checks/sizes/outertypenumber.xml
- src/xdocs/checks/sizes/outertypenumber.xml.template
- src/xdocs/checks/sizes/parameternumber.xml
- src/xdocs/checks/sizes/parameternumber.xml.template
- src/xdocs/checks/sizes/recordcomponentnumber.xml
- src/xdocs/checks/sizes/recordcomponentnumber.xml.template
> Issue #13627: Use violation messages macro in sizes templates

- src/xdocs/checks/whitespace/emptyforinitializerpad.xml
- src/xdocs/checks/whitespace/emptyforinitializerpad.xml.template
- src/xdocs/checks/whitespace/emptyforiteratorpad.xml
- src/xdocs/checks/whitespace/emptyforiteratorpad.xml.template
- src/xdocs/checks/whitespace/emptylineseparator.xml
- src/xdocs/checks/whitespace/emptylineseparator.xml.template
- src/xdocs/checks/whitespace/filetabcharacter.xml
- src/xdocs/checks/whitespace/filetabcharacter.xml.template
- src/xdocs/checks/whitespace/genericwhitespace.xml
- src/xdocs/checks/whitespace/genericwhitespace.xml.template
- src/xdocs/checks/whitespace/methodparampad.xml
- src/xdocs/checks/whitespace/methodparampad.xml.template
- src/xdocs/checks/whitespace/nolinewrap.xml
- src/xdocs/checks/whitespace/nolinewrap.xml.template
- src/xdocs/checks/whitespace/nowhitespaceafter.xml
- src/xdocs/checks/whitespace/nowhitespaceafter.xml.template
- src/xdocs/checks/whitespace/nowhitespacebefore.xml
- src/xdocs/checks/whitespace/nowhitespacebefore.xml.template
- src/xdocs/checks/whitespace/operatorwrap.xml
- src/xdocs/checks/whitespace/operatorwrap.xml.template
- src/xdocs/checks/whitespace/parenpad.xml
- src/xdocs/checks/whitespace/parenpad.xml.template
- src/xdocs/checks/whitespace/separatorwrap.xml
- src/xdocs/checks/whitespace/separatorwrap.xml.template
- src/xdocs/checks/whitespace/singlespaceseparator.xml
- src/xdocs/checks/whitespace/singlespaceseparator.xml.template
- src/xdocs/checks/whitespace/typecastparenpad.xml
- src/xdocs/checks/whitespace/typecastparenpad.xml.template
- src/xdocs/checks/whitespace/whitespacearound.xml
- src/xdocs/checks/whitespace/whitespacearound.xml.template
> Issue #13627: Use violation messages macro in whitespace templates

- src/xdocs/checks/header/header.xml
- src/xdocs/checks/header/header.xml.template
- src/xdocs/checks/header/regexpheader.xml
- src/xdocs/checks/header/regexpheader.xml.template
> Issue #13627: Use violation messages macro in header templates

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodBasic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodSetterGetter3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodSetterGetter4.java
Resolves #13596
---
---
report 1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/729c1ee_2023092722/reports/diff/index.html
---
Diff Regression config: https://gist.githubusercontent.com/relentless-pursuit/c6b58ae47d9f0419460753a8d5199535/raw/5cb0276c3f8ff2e86ac1b1942ebfc6493f7fc31c/my_checks.xml
> Moved utility methods from CheckUtil to MissingJavadocMethodCheck

- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/Example2.txt
- src/xdocs/checks/javadoc/nonemptyatclausedescription.xml
> Issue #13660: restore examples for nonemptyatclausedescription

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MatchXpathCheck.xml
- src/xdocs/checks/coding/matchxpath.xml
- src/xdocs/checks/coding/matchxpath.xml.template
detected at https://github.com/checkstyle/checkstyle/actions/runs/6049431100/job/16416700367#step:4:2391
> minor: fix url detected by link check plugin

- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #13672: Kill mutation in TreeWalker-1
---------
https://github.com/checkstyle/checkstyle/blob/ca7d6d66d191747919b6ea30710dab3d539985f6/config/pitest-suppressions/pitest-tree-walker-suppressions.xml#L111-L136
---------
Test update
> Issue #13672: Kill mutation in TreeWalker-1

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/DeclarationOrderCheck.xml
- src/xdocs/checks/coding/arraytrailingcomma.xml
- src/xdocs/checks/coding/arraytrailingcomma.xml.template
- src/xdocs/checks/coding/declarationorder.xml
- src/xdocs/checks/coding/declarationorder.xml.template
- src/xdocs/checks/coding/defaultcomeslast.xml
- src/xdocs/checks/coding/defaultcomeslast.xml.template
Issue #13693
codign package files from top util defaultcomeslast
> Issue #13693: use property macros in few coding modules

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpath5.java
Issue #13328
Attempt to improve this PR: https://github.com/checkstyle/checkstyle/pull/13242
> Issue #13328: kill mutations in MatchXpathCheck

- .ci/pitest-survival-check-xml.groovy
- config/pitest-suppressions/pitest-xpath-suppressions.xml
From https://github.com/checkstyle/checkstyle/pull/13398#discussion_r1265538825
> Pull #13492: Fix Pitest script to recognize unstable mutations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalThrowsCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/VariableDeclarationUsageDistanceCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/coding/illegalthrows.xml
- src/xdocs/checks/coding/illegalthrows.xml.template
- src/xdocs/checks/coding/variabledeclarationusagedistance.xml
- src/xdocs/checks/coding/variabledeclarationusagedistance.xml.template
Issue #13668
same as #13717 but without changing of first char of description to upper case.
> Issue #13668: order properties in xdoc and javadoc for coding package

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/Example4.txt
- src/xdocs/checks/annotation/annotationlocation.xml
- src/xdocs/checks/annotation/annotationlocation.xml.template
- src/xdocs/checks/annotation/missingdeprecated.xml
- src/xdocs/checks/annotation/missingdeprecated.xml.template
- src/xdocs/checks/blocks/avoidnestedblocks.xml
- src/xdocs/checks/blocks/avoidnestedblocks.xml.template
- src/xdocs/checks/blocks/emptyblock.xml
- src/xdocs/checks/blocks/emptyblock.xml.template
- src/xdocs/checks/blocks/emptycatchblock.xml
- src/xdocs/checks/blocks/emptycatchblock.xml.template
- src/xdocs/checks/blocks/needbraces.xml
- src/xdocs/checks/blocks/needbraces.xml.template
- src/xdocs/checks/blocks/rightcurly.xml
- src/xdocs/checks/blocks/rightcurly.xml.template
- src/xdocs/checks/design/designforextension.xml
- src/xdocs/checks/design/designforextension.xml.template
- src/xdocs/checks/design/finalclass.xml
- src/xdocs/checks/design/finalclass.xml.template
- src/xdocs/checks/design/hideutilityclassconstructor.xml
- src/xdocs/checks/design/hideutilityclassconstructor.xml.template
> Issue #13732: Add Examples Macro Support to All Checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocTagContinuationIndentationCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/MissingJavadocMethodCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/ClassFanOutComplexityCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/LocalVariableNameCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/javadoc/javadoctagcontinuationindentation.xml
- src/xdocs/checks/javadoc/javadoctagcontinuationindentation.xml.template
- src/xdocs/checks/javadoc/missingjavadocmethod.xml
- src/xdocs/checks/javadoc/missingjavadocmethod.xml.template
- src/xdocs/checks/metrics/classfanoutcomplexity.xml
- src/xdocs/checks/metrics/classfanoutcomplexity.xml.template
- src/xdocs/checks/naming/localvariablename.xml
- src/xdocs/checks/naming/localvariablename.xml.template
> Issue #13666: fix ordering of properties in few modules

- config/pitest-suppressions/pitest-common-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
> Issue #11902: kill mutation in PackageObjectFactory

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/LeftCurlyCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocParagraphCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocStyleCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/AbbreviationAsWordInNameCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/EmptyLineSeparatorCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/blocks/leftcurly.xml
- src/xdocs/checks/blocks/leftcurly.xml.template
- src/xdocs/checks/javadoc/javadocparagraph.xml
- src/xdocs/checks/javadoc/javadocparagraph.xml.template
- src/xdocs/checks/javadoc/javadocstyle.xml
- src/xdocs/checks/javadoc/javadocstyle.xml.template
- src/xdocs/checks/naming/abbreviationaswordinname.xml
- src/xdocs/checks/naming/abbreviationaswordinname.xml.template
- src/xdocs/checks/whitespace/emptylineseparator.xml
- src/xdocs/checks/whitespace/emptylineseparator.xml.template
> Issue #13666: reorder propertties in few modules

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/MethodCountCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/regexp/regexp.xml
- src/xdocs/checks/regexp/regexp.xml.template
- src/xdocs/checks/sizes/methodcount.xml
- src/xdocs/checks/sizes/methodcount.xml.template
> Issue #13666: order properties in Regexp and MethodCount

- config/import-control.xml
- config/pitest-suppressions/pitest-xpath-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractElementNode.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter5.xml
Issue #13672: Kill mutation for Xpath
------------
https://github.com/checkstyle/checkstyle/blob/c525c6732e2c1f15bd3f85f943770c649f1ab775/config/pitest-suppressions/pitest-xpath-suppressions.xml#L30-L46
and
https://github.com/checkstyle/checkstyle/blob/c525c6732e2c1f15bd3f85f943770c649f1ab775/config/pitest-suppressions/pitest-xpath-suppressions.xml#L3-L10
----------
Test added
> Issue #13672: Kill mutation for Xpath

- config/pitest-suppressions/pitest-xpath-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter6.xml
Issue #13672: Kill mutation for Xpath-2
-----------
Test
> Issue #13672: Kill mutation for Xpath-2

- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/TranslationCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/indentation/IndentationCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/AtclauseOrderCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/MethodNameCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/javadoc/atclauseorder.xml
- src/xdocs/checks/javadoc/atclauseorder.xml.template
- src/xdocs/checks/misc/indentation.xml
- src/xdocs/checks/misc/indentation.xml.template
- src/xdocs/checks/misc/translation.xml
- src/xdocs/checks/misc/translation.xml.template
- src/xdocs/checks/naming/methodname.xml
- src/xdocs/checks/naming/methodname.xml.template
- src/xdocs/config.xml
> Issue #13666: fix property order for few modules

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/AvoidStarImportCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/MemberNameCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressWithNearbyTextFilter.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressWithPlainTextCommentFilter.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/imports/avoidstarimport.xml
- src/xdocs/checks/imports/avoidstarimport.xml.template
- src/xdocs/checks/naming/membername.xml
- src/xdocs/checks/naming/membername.xml.template
- src/xdocs/filters/suppresswithnearbytextfilter.xml
- src/xdocs/filters/suppresswithnearbytextfilter.xml.template
- src/xdocs/filters/suppresswithplaintextcommentfilter.xml
- src/xdocs/filters/suppresswithplaintextcommentfilter.xml.template
> Issue #13666: order properties in few modules

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongImportStatements.java
> Issue #4845: Removed checkstyle dependencies from lineLength

- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/AvoidEscapedUnicodeCharactersCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/ReturnCountCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/StaticVariableNameCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/ParameterNumberCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/RecordComponentNumberCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/coding/returncount.xml
- src/xdocs/checks/coding/returncount.xml.template
- src/xdocs/checks/misc/avoidescapedunicodecharacters.xml
- src/xdocs/checks/misc/avoidescapedunicodecharacters.xml.template
- src/xdocs/checks/naming/staticvariablename.xml
- src/xdocs/checks/naming/staticvariablename.xml.template
- src/xdocs/checks/sizes/parameternumber.xml
- src/xdocs/checks/sizes/parameternumber.xml.template
- src/xdocs/checks/sizes/recordcomponentnumber.xml
- src/xdocs/checks/sizes/recordcomponentnumber.xml.template
> Issue #13666: fix ordering in sevral modules

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/UnmodifiableCollectionUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionfilter/InputSuppressionFilter7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionfilter/InputSuppressionFilter7.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionfilter/InputSuppressionFilter8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter7.xml
Issue #13672: Kill mutation for Filter
----------
SuppressionFIlter :- https://checkstyle.sourceforge.io/filters/suppressionfilter.html#SuppressionFilter
SuppressionXpathFilter :- https://checkstyle.sourceforge.io/filters/suppressionxpathfilter.html#SuppressionXpathFilter
----------
https://github.com/checkstyle/checkstyle/blob/d73d90511ce01b9dcebd8486c332480a48369080/config/pitest-suppressions/pitest-filters-suppressions.xml#L309-L316
and 
https://github.com/checkstyle/checkstyle/blob/d73d90511ce01b9dcebd8486c332480a48369080/config/pitest-suppressions/pitest-filters-suppressions.xml#L327-L343
-----------
Test and Expanition of util method
> Issue #13672: Kill mutation for Filter

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlTestException.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlTestException.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlTestRegexpInFile.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlTestRegexpInFile.xml
Issue #13672: Kill mutation for ImportControlLoader
-----
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/config/pitest-suppressions/pitest-imports-suppressions.xml#L21-L37
-----
Test
> Issue #13672: Kill mutation for ImportControlLoader

- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/DescendantTokenCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/NewlineAtEndOfFileCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SingleLineJavadocCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpOnFilenameCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpSinglelineCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpSinglelineJavaCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/javadoc/singlelinejavadoc.xml
- src/xdocs/checks/javadoc/singlelinejavadoc.xml.template
- src/xdocs/checks/misc/descendanttoken.xml
- src/xdocs/checks/misc/descendanttoken.xml.template
- src/xdocs/checks/misc/newlineatendoffile.xml
- src/xdocs/checks/misc/newlineatendoffile.xml.template
- src/xdocs/checks/regexp/regexponfilename.xml
- src/xdocs/checks/regexp/regexponfilename.xml.template
- src/xdocs/checks/regexp/regexpsingleline.xml
- src/xdocs/checks/regexp/regexpsingleline.xml.template
- src/xdocs/checks/regexp/regexpsinglelinejava.xml
- src/xdocs/checks/regexp/regexpsinglelinejava.xml.template
> Issue #13666: final fix for ordering of properties in modules

- config/pitest-suppressions/pitest-common-suppressions.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checker/InputCheckerTestCharset.java
Issue #13672: Kill mutation in Common Profile
Test
> Issue #13672: Kill mutation in Common Profile

- config/pitest-suppressions/pitest-api-suppressions.xml
- config/pitest-suppressions/pitest-common-2-suppressions.xml
- config/pitest-suppressions/pitest-common-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/LocalizedMessage.java
- src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/UnmodifiableCollectionUtil.java
Issue #13672: Kill mutation using utility class
> Issue #13672: Kill mutation using utility class

- config/pitest-suppressions/pitest-api-suppressions.xml
- pom.xml
Issue #13809: Kill mutation in pitest-api profile
Just test added.
> Issue #13809: Kill mutation in pitest-api profile

- config/checkstyle-examples-checks.xml
> Issue #13797: Create a Checkstyle module to enforce comment formatting for input files

- src/xdocs/property_types.xml
Issue #13650: Minor doc fix in file `property_type.xml`
> Issue #13650: Update Docs

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/upperell/Example1.java
- src/xdocs/checks/misc/upperell.xml
- src/xdocs/checks/misc/upperell.xml.template
Part of https://github.com/checkstyle/checkstyle/issues/13345
> Issue #13345: Enable examples tests for upperell

- src/xdocs/checks/annotation/annotationusestyle.xml
- src/xdocs/checks/annotation/annotationusestyle.xml.template
Issue #13693
no updates in javadoc until #13626
this is RP to agree on, if all good, other PR, will be batched with 5-7 modules.
> Issue #13693: use marco property in module templates

- .github/workflows/diff-report.yml
- .github/workflows/site.yml
- config/jsoref-spellchecker/whitelist.words
Related: https://github.com/checkstyle/checkstyle/issues/13045
> Issue #13045: Node.js 12 actions deprecated

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/annotation/annotationonsameline.xml
- src/xdocs/checks/annotation/annotationonsameline.xml.template
> Issue #13693: use property macro at AnnotationOnSameLineCheck

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/coding/unnecessarysemicolonafteroutertypedeclaration.xml
- src/xdocs/checks/coding/unnecessarysemicolonafteroutertypedeclaration.xml.template
- src/xdocs/checks/coding/unnecessarysemicolonaftertypememberdeclaration.xml
- src/xdocs/checks/coding/unnecessarysemicolonaftertypememberdeclaration.xml.template
> Issue #13829: final migration to parent macro

- .gitignore
Related: https://github.com/checkstyle/checkstyle/issues/13834
> Issue #13834: Add .vscodefoler in .gitignore

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/annotation/missingoverride.xml
- src/xdocs/checks/annotation/missingoverride.xml.template
- src/xdocs/checks/annotation/suppresswarnings.xml
- src/xdocs/checks/annotation/suppresswarnings.xml.template
> Issue #13693: migrate to properties macros few modules

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/Example5.java
- src/xdocs/checks/naming/parametername.xml
- src/xdocs/checks/naming/parametername.xml.template
> Issue #13345: Enable test case for parameternameChecktest

- .github/dependabot.yml
Related:  https://github.com/checkstyle/checkstyle/issues/12984
> Issue #12984: Add schedular to update github-actions

- .github/workflows/actionlint.yml
Related: https://github.com/checkstyle/checkstyle/issues/13765
> Issue #13765: Add proper naming format

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml.template
- src/xdocs/filters/severitymatchfilter.xml
- src/xdocs/filters/severitymatchfilter.xml.template
- src/xdocs/filters/suppressioncommentfilter.xml
- src/xdocs/filters/suppressioncommentfilter.xml.template
- src/xdocs/filters/suppressionfilter.xml
- src/xdocs/filters/suppressionfilter.xml.template
- src/xdocs/filters/suppressionsinglefilter.xml
- src/xdocs/filters/suppressionsinglefilter.xml.template
- src/xdocs/filters/suppressionxpathfilter.xml
- src/xdocs/filters/suppressionxpathfilter.xml.template
- src/xdocs/filters/suppressionxpathsinglefilter.xml
- src/xdocs/filters/suppressionxpathsinglefilter.xml.template
- src/xdocs/filters/suppresswithnearbycommentfilter.xml
- src/xdocs/filters/suppresswithnearbycommentfilter.xml.template
- src/xdocs/filters/suppresswithnearbytextfilter.xml
- src/xdocs/filters/suppresswithnearbytextfilter.xml.template
- src/xdocs/filters/suppresswithplaintextcommentfilter.xml.template
> Issue #13693: migrate filter xdoc termplates to property macros

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadoc2.java
Related: https://github.com/checkstyle/checkstyle/issues/13347
Diff Regression config: https://gist.githubusercontent.com/AayushSaini101/2db49b2556a5ed7f2df81b3624661c38/raw/d9e6dac89729ca2436edd6506fe76dcbe3feb0cd/gistfile1.txt
> Issue #13347: False Positive and Negative in SummaryJavaDocCheck

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/Example2.java
- src/xdocs/checks/imports/avoidstaticimport.xml.template
> Issue #13345: Enable AvoidStaticImportCheckExampleTest

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/Example1.java
- src/xdocs/checks/coding/parameterassignment.xml
- src/xdocs/checks/coding/parameterassignment.xml.template
Related: https://github.com/checkstyle/checkstyle/issues/13345
> Issue #13345: Enable example test for parameterassignment

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example3.java
- src/xdocs/checks/blocks/emptyblock.xml
- src/xdocs/checks/blocks/emptyblock.xml.template
> Issue #13345: Enable Empty Block Check

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
Issue #13809: Kill mutation ConfigurationLoader
Test
> Issue #13809: Kill mutation ConfigurationLoader

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault5.java
> Issue #4845: Removed dependencies from AvoidStaticImportCheck

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/xdocs/checks/coding/illegaltokentext.xml
- src/xdocs/checks/coding/illegaltokentext.xml.template
> Issue #13859: Migrate to property macros IllegalTokenText

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/AbstractParenPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/checks/whitespace/typecastparenpad.xml.template
> Issue #13867: Resolve MacroExecutionException in TypecastParenPadCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/indentation/IndentationCheck.xml
- src/xdocs/checks/misc/indentation.xml
- src/xdocs/checks/misc/indentation.xml.template
Issue #13783 
This PR fixes the typo in IndentationCheck file
> Issue #13783:  Fixed typo in IndentationCheck for initialization

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/Example2.java
- src/xdocs/checks/imports/unusedimports.xml
- src/xdocs/checks/imports/unusedimports.xml.template
> Issue #13345: Enable UnusedImportCheckExamplesTest

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
Issue #13809: Kill mutation in Checker-3
--------
Mutation 
https://github.com/checkstyle/checkstyle/blob/8c8bc0c6102823206ca3a562b01b26882fc242fa/config/pitest-suppressions/pitest-common-suppressions.xml#L21-L28
> Issue #13809: Kill mutation in Checker-3

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/xdocs/checks/coding/illegaltoken.xml
- src/xdocs/checks/coding/illegaltoken.xml.template
> Issue #13860: Migrate IllegalToken to properties macros

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowStaticMember.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportExcludes.java
> Issue #4845: removed checkstyle dependencies from avoidstarimport inputs

- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/xdocs/checks/coding/finallocalvariable.xml
- src/xdocs/checks/coding/finallocalvariable.xml.template
Related:  https://github.com/checkstyle/checkstyle/issues/13853
Old PR: https://github.com/checkstyle/checkstyle/pull/13878
> Issue #13853: migrate FinalLocalVariable xdoc to use property macro

- config/checkstyle-non-main-files-suppressions.xml
Fixes failure leaked to master, see https://github.com/checkstyle/checkstyle/actions/runs/6641236933/job/18043297467
> minor: remove leaked suppression

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_Wildcard.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_WildcardUnspecified.java
> Issue #4845: Removed checkstyle dependencies from importOrder inputs

- .ci/validation.cmd
- appveyor.yml
- config/jsoref-spellchecker/whitelist.words
Issue #11816: Added cmd script for git-diff validation for windows environment
> Issue #11816: Added windows cmd script for git-diff validation

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example1.java
- src/xdocs/checks/coding/innerassignment.xml
- src/xdocs/checks/coding/innerassignment.xml.template
> Issue #13345: Enable InnerAssignmentCheckExamplesTest

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestStarImports.java
> Issue #4845: Removed checkstyle dependencies for illegaltype

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionInnerAssignmentTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/innerassignment/SuppressionXpathRegressionInnerAssignment1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/innerassignment/SuppressionXpathRegressionInnerAssignment2.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath IT Regression Testing for InnerAssignment

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic12.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic13.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment9.java
> Issue #11214: Specify violation messages for RegexpCheck Input Files

- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
Issue #13809: Kill mutation in Tree-walker
> Issue #13809: Kill mutation in Tree-walker

- config/checkstyle-non-main-files-suppressions.xml
- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/xdocs/checks/misc/descendanttoken.xml
- src/xdocs/checks/misc/descendanttoken.xml.template
> Issue #13885: Migrate DescendantToken to properties macros

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/coding/multiplestringliterals.xml
- src/xdocs/checks/coding/multiplestringliterals.xml.template
> Issue #13933: Migrate multiplestringliterals.xml.template to use properties

- pom.xml
https://github.com/hcoles/pitest/releases
> dependency: bump pitest to 1.15.3

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionFinalLocalVariableTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable3.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable4.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable5.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable6.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable7.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable8.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable9.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207 
Link to Check's Documentation - https://checkstyle.org/checks/coding/finallocalvariable.html#FinalLocalVariable
> Issue #6207: Add Xpath IT Regression Testing for FinalLocalVariable

- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/treewalker/InputTreeWalker2.java
Issue #13809: Kill mutation in Tree-Walker-2
> Issue #13809: Kill mutation in Tree-Walker-2

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/metrics/booleanexpressioncomplexity.xml
- src/xdocs/checks/metrics/booleanexpressioncomplexity.xml.template
- src/xdocs/checks/metrics/cyclomaticcomplexity.xml
- src/xdocs/checks/metrics/cyclomaticcomplexity.xml.template
> Issue #13693: mirgate few metrics modules to properties macros

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java
Issue #13672: Kill mutation for SuppressionXpathSingleFilter
> Issue #13672: Kill mutation for SuppressionXpathSingleFilter

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnonymousClassInMethodCurlyOnNewLine.java
> Issue #4845: Remove checkstyle dependencies for indentation test inputs

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMagicNumberTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/magicnumber/SuppressionXpathRegressionMagicNumberAnotherVariable.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/magicnumber/SuppressionXpathRegressionMagicNumberMethodDef.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/magicnumber/SuppressionXpathRegressionMagicNumberVariable.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #6207 
Documentation : [MagicNumber](https://checkstyle.org/checks/coding/magicnumber.html)
> Issue #6207: Added Xpath IT regression test for MagicNumber

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/design/designforextension.xml
- src/xdocs/checks/design/designforextension.xml.template
- src/xdocs/checks/design/interfaceistype.xml
- src/xdocs/checks/design/interfaceistype.xml.template
- src/xdocs/checks/design/mutableexception.xml.template
- src/xdocs/checks/design/throwscount.xml.template
- src/xdocs/checks/design/visibilitymodifier.xml
- src/xdocs/checks/design/visibilitymodifier.xml.template
> Issue #13693: migrate design xdoc template to use property macro

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/xdocs/checks/sizes/methodcount.xml
- src/xdocs/checks/sizes/methodcount.xml.template
- src/xdocs/checks/sizes/methodlength.xml
- src/xdocs/checks/sizes/methodlength.xml.template
- src/xdocs/checks/sizes/outertypenumber.xml.template
- src/xdocs/checks/sizes/parameternumber.xml
- src/xdocs/checks/sizes/parameternumber.xml.template
- src/xdocs/checks/sizes/recordcomponentnumber.xml
- src/xdocs/checks/sizes/recordcomponentnumber.xml.template
> Issue #13693: migrate sizes xdoc templates to use property macro

- README.md
looks like gitter is almost completely removed, we need new link that works
> minor: fix chat link in README.md

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/SuppressWarningsHolder.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/annotation/suppresswarningsholder.xml
- src/xdocs/checks/annotation/suppresswarningsholder.xml.template
> Issue #13839: migrate SuppressWarningsHolder to use property macro

- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitSuperClassTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
Issue #13544
cycles will be covered at https://github.com/checkstyle/checkstyle/issues/14053
> Issue #13544: Re-enable ArchUnit Testing (except of cycle validation)

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSuperCloneTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/superclone/SuppressionXpathRegressionSuperCloneInnerClone.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/superclone/SuppressionXpathRegressionSuperCloneNoSuperClone.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/superclone/SuppressionXpathRegressionSuperClonePlainAndSubclasses.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
part of #6207 
Documentation : [SuperClone](https://checkstyle.sourceforge.io/checks/coding/superclone.html#SuperClone)
> Issue #6207: Added Xpath IT regression test for SuperClone

- pom.xml
just notices https://github.com/TNG/ArchUnit
> dependency: update archunit to 1.2.0

- config/jsoref-spellchecker/whitelist.words
- pom.xml
Noticed while browsing maven central, I need to update my username.
> minor: fix username

- config/checkstyle-input-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports2.java
> Issue #4845: Removed Checkstyle Dependency From UnusedImports

- .circleci/config.yml
#13970
https://github.com/checkstyle/contribution/pull/810
> Issue #13970: Update CI to have Maven Version 3.8.8

- config/checkstyle-input-suppressions.xml
> Issue #4845: Removed Checkstyle Dependency From ReduntantImport

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/api/abstractcheck/InputAbstractCheckTestFileContents.java
> Issue #11446: Update AbstractCheckTest to use verifyWithInlineConfigParser

- .semaphore/semaphore.yml
Issue #14086 and #12705
layout is not good, as it is not intended to be a pipeline, but OK, lets keep it like this 
https://checkstyle.semaphoreci.com/workflows/65ba10a4-7259-4388-b305-d1cbddce09de?pipeline_id=a9dc30f1-cad4-4574-986a-a8ad0e4a51c5
> infra: disable no-exception-samples-ant until #14086

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
Issue #14084
https://stackoverflow.com/a/35875417
> Issue #14084: fix Checker violation for nullable return

- .semaphore/semaphore.yml
from https://checkstyle.semaphoreci.com/jobs/eb66d84d-15f8-4679-8918-eeb6468d214b#L462
```
/home/semaphore/.m2/repository/R-4.27-202303020300/ is not found, downloading ... 00:13
--2023-12-06 19:10:34--  http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/eclipse/downloads/drops4/R-4.27-202303020300/ 00:13
Resolving ftp-stud.fht-esslingen.de (ftp-stud.fht-esslingen.de)... 129.143.116.10, 2001:7c0:700::10 00:13
Connecting to ftp-stud.fht-esslingen.de (ftp-stud.fht-esslingen.de)|129.143.116.10|:80... connected. 00:13
HTTP request sent, awaiting response... 404 Not Found 00:13
2023-12-06 19:10:34 ERROR 404: Not Found. 00:13
[ERROR] Command execution failed. 00:13
org.apache.commons.exec.ExecuteException: Process exited with an error: 8 (Exit value: 8)
``` …
> infra: update eclipse version as old version is not available any more

- .cirrus.yml
- pom.xml
- src/xdocs/beginning_development.xml
> dependency: Updated Maven version to 3.6.3

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileSetCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/api/fileset/InputFileSetIllegalTokens.java
> Issue #11446: Update Filesetchecktest to use verifyWithInlineConfigParser method

- .ci/validation.sh
- azure-pipelines.yml
- config/jsoref-spellchecker/whitelist.words
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/LocalizedMessageTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
related to https://github.com/checkstyle/checkstyle/pull/11529
> infra: set English locale for tests

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionStaticVariableNameTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/staticvariablename/SuppressionXpathRegressionStaticVariableName2.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/staticvariablename/SuppressionXpathRegressionStaticVariableName3.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/staticvariablename/SuppressionXpathRegressionStaticVariableName1.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Related: https://github.com/checkstyle/checkstyle/issues/6207
Diff Regression config: https://gist.githubusercontent.com/aayushRedHat/849313f94f6df07629e364070d5ed19a/raw/3fc325f6c384a7ca918dc4a5875fa26cc1444679/gistfile1.txt
Diff Regression projects: https://gist.githubusercontent.com/aayushRedHat/085b2f4c08f7e2859c92e0d2cb2144c9/raw/358a901648397fd9f66978d4ce51636694546177/gistfile1.txt
> Issue #6207: Added Xpath IT regression test for StaticVariableName

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java
Resolves #3132
Indent-strict: https://gist.githubusercontent.com/romani/82a313d3a8de5becbf7fb54767d434ef/raw/b297c3de497f6f63458ef2e198fab2f879e25f2b/pull-9758.xml
Diff Regression config: https://gist.githubusercontent.com/romani/82a313d3a8de5becbf7fb54767d434ef/raw/de70b01eb659ee0513387b003a1968ada966ece6/pull-9758-indent2.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/db8ebee721f2a387e1d4b81a55f2d5f1/raw/8e4a96fdad2654d55808851ae59553b58f5e782f/pull-9758-only-guava.properties
only jdk: https://gist.githubusercontent.com/romani/c539071f4b33eb8e2f451c14a0d4480b/raw/b6e9c3c275d0a941e7c10f558ba52c2e4f55a58f/pull-9758.properties
projects old: https://gist.githubusercontent.com/suniti0804/1d7bd7fbc50bf6c93896fbe2bbbf2c4a/raw/f71611ef97d0737b6d8bb1c1253cab18b9342429/pro …
> Issue #3132: fixed not checked split line new array

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/checks/sizes/anoninnerlength.xml.template
- src/xdocs/checks/sizes/executablestatementcount.xml
- src/xdocs/checks/sizes/executablestatementcount.xml.template
- src/xdocs/checks/sizes/filelength.xml.template
- src/xdocs/checks/sizes/lambdabodylength.xml.template
> Issue #13693: migrate size  modules to property marco

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldInnerRecordsImplicitlyStatic.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldRecordsImplicitlyStaticClassComparison.java
Issue #14028: HiddenField false positive on inner records
--------------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e922f9f79f4b5245caba9b44cd2d1f0d/raw/50a61d0d72c5a09bd74a383907fe0021d28f1763/hidden.xml
Report label: Report-2.2
> Issue #14028: HiddenField false positive on inner records

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
> Issue #11446: Update DetailAstImplTest to use execute

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpOnFilenameCheck.xml
- src/xdocs/checks/regexp/regexp.xml
- src/xdocs/checks/regexp/regexp.xml.template
- src/xdocs/checks/regexp/regexpmultiline.xml
- src/xdocs/checks/regexp/regexpmultiline.xml.template
- src/xdocs/checks/regexp/regexponfilename.xml
- src/xdocs/checks/regexp/regexponfilename.xml.template
- src/xdocs/checks/regexp/regexpsingleline.xml
- src/xdocs/checks/regexp/regexpsingleline.xml.template
- src/xdocs/checks/regexp/regexpsinglelinejava.xml
- src/xdocs/checks/regexp/regexpsinglelinejava.xml.template
> Issue #13693: migrate regexp checks to property macro

- src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
> Issue #12238: Unable to persist cache file if target directory is a symbolic link

- pom.xml
> Issue #11446: Remove exclude statement from pom.xml file

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/OrderedPropertiesCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/TranslationCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/UniquePropertiesCheck.xml
- src/xdocs/checks/misc/orderedproperties.xml
- src/xdocs/checks/misc/orderedproperties.xml.template
- src/xdocs/checks/misc/todocomment.xml.template
- src/xdocs/checks/misc/trailingcomment.xml
- src/xdocs/checks/misc/trailingcomment.xml.template
- src/xdocs/checks/misc/translation.xml
- src/xdocs/checks/misc/translation.xml.template
- src/xdocs/checks/misc/uncommentedmain.xml
- src/xdocs/checks/misc/uncommentedmain.xml.template
- src/xdocs/checks/misc/uniqueproperties.xml
- src/xdocs/checks/misc/uniqueproperties.xml.template
> Issue #13693: migrate misc modules to property macros

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionFinalParametersTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finalparameters/SuppressionXpathRegressionFinalParameters1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finalparameters/SuppressionXpathRegressionFinalParameters2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finalparameters/SuppressionXpathRegressionFinalParameters3.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partial for issue #6207 Add xpath regression test for FinalParameters.
Link to the documentation: https://checkstyle.sourceforge.io/checks/misc/finalparameters.html
> Issue #6207: Add Xpath Regression Test for FinalParameters

- pom.xml
Issue #14137.
Based on the answers in #14229, I will update this PR accordingly.
> Issue #14137: Enable `AmbiguousJsonCreator` check

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavaNCSSTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javancss/SuppressionXpathRegressionJavaNCSSOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javancss/SuppressionXpathRegressionJavaNCSSThree.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javancss/SuppressionXpathRegressionJavaNCSSTwo.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue: #6207 
Doc Link: https://checkstyle.sourceforge.io/checks/metrics/javancss.html
> Issue #6207: Add Xpath Regression Test for JavaNCSS

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java
> Issue #11446: update AllBlockCommentsTest to use execute method

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckExamplesTest.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/Example3.java
- src/xdocs/checks/coding/illegaltokentext.xml
> minor: placeTheCommentBeforeThePackageLine

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPackageNameTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packagename/SuppressionXpathRegressionPackageName.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/packagename/SuppressionXpathRegressionPackageNameOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/packagename/SuppressionXpathRegressionPackageNameTwo.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath Regression Test for PackageName

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionInnerTypeLastTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/innertypelast/SuppressionXpathRegressionInnerTypeLastOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/innertypelast/SuppressionXpathRegressionInnerTypeLastThree.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/innertypelast/SuppressionXpathRegressionInnerTypeLastTwo.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath Regression Test for InnerTypeLastTest

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclarationRecords.java
Removed '//ok' comments from InputMagicNumberIgnoreFieldDeclarationRecords.java
> Issue #13213: Removed //ok from magicNumber

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTagsVisitCountOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTagsVisitCountTwo.java
Enforced file size on InputAbstractJavadocHtmlTagsVisitCount.java file.
> Issue #11163: Enforced filesize HtmlTagsVisitCount

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderLotsOfRecords1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderLotsOfRecords2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderLotsOfRecords3.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderLotsOfRecords4.java
Removed //ok comments from atclauseorder module.
> Issue #13213: Removed //ok atclauseorder

- config/checkstyle-input-suppressions.xml
- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCorrectParagraphOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCorrectParagraphTwo.java
Enforced file size on InputAbstractJavadocCorrectParagraph file.
> Issue #11163: Enforced filesize CorrectParagraph

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectory2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtParent2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtSubpackage2.java
Removed '//ok' comments from packagedeclaration module.
> Issue #13213: Removed //ok packageDeclaration

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocks.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckPatterns.java
Issue #13213
Removed //ok from illegaltokentext
> Issue #13213: Removed //ok from illegaltokentext

- config/checkstyle-input-suppressions.xml
- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthModifierOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthModifierTwo.java
Enforced file size limit of 120 lines on InputMethodLengthModifier.java file.
Part of #13213
Removed '//ok' comment from the fiile.
> Issue #11163: Enforced filesize MethodLengthModifier

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount1One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount1Two.java
Enforced file size on InputMethodCount1 check
> Issue #11163: Enforced file size MethodCount1

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentDemoBug1195047Comment3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentMethod.java
> Issue #11163: Enforce file size on InnerAssignment

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSS2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSS3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSSResolveMutation.java
Part of #13213
Removed `//ok` comments from **InputJavaNCSS2.java**, **InputJavaNCSS3.java** and **InputJavaNCSSResolveMutation.java**
> Issue #13213: Removed //ok from javancss

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/IsInstanceLambdaUsage/ check.
> Issue #14137: Enable `IsInstanceLambdaUsage` check

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/MockitoMockClassReference/ check.
> Issue #14137: Enable `MockitoMockClassReference` check

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode2One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode2Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode3One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode3Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCodeOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCodeTwo.java
Issue #11163:
force file size on inputs on InputCommentIndentationSurroundingCode, InputCommentIndentationSurroundingCode2, InputCommentIndentationSurroundingCode3
> Issue #11163: Enforced file size inputs on InputCommentIndentationSurroundingCode

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalTokenTextTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltokentext/SuppressionXpathRegressionIllegalTokenText1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltokentext/SuppressionXpathRegressionIllegalTokenText2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/illegaltokentext/SuppressionXpathRegressionIllegalTokenText3.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207;
Traveling from HK to USA these days.
Three tests for the class, method and interface level
> Issue #6207: Enable XpathRegressionTest for ilegalTokenText

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassEmpty.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/package-info.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierPackageClassName.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexityRecordLeaves.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSSRecordsAndCompactCtors.java
Removed '//ok' comments from all the files of following modules :
noncompilable/metrics
noncompilable/design
> Issue #13213: removed //ok metrics,design

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect2One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect2Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect3One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect3Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrectOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrectTwo.java
issue #11163:
force file size on inputs on InputAnnotationLocationIncorrect,
InputAnnotationLocationIncorrect2, InputAnnotationLocationIncorrect3
now we can mark the AnnotationLocation module as done
> Issue #11163: Enforced file size inputs on annotation location

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCatchParameterNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameAnonymous.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameEnum.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameInterface.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameLambda.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameNested.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameSimple.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/SuppressionXpathRegressionCatchParameterNameStaticInit.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #6207 ([Documentation](https://checkstyle.org/checks/naming/catchparametername.html))
> Issue #6207: Add XPath IT Regression test for CatchParameterName

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEqualsHashCodeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/equalshashcode/SuppressionXpathRegressionEqualsHashCode1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/equalshashcode/SuppressionXpathRegressionEqualsHashCode2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/equalshashcode/SuppressionXpathRegressionEqualsHashCodeNestedCase.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207,
1 test for equals, 1 for hashcode, 1 for nested case
> Issue #6207: Enable XpathRegressionTestforEqualsHashCode

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapGood.java
Part of #13213
Removed `//ok` comments from **InputNoLineWrapGood.java**
> Issue #13213: Removed //ok from nolinewrap

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrder2.java
Part of #13213
Removed `//ok` comments from **InputDeclarationOrder2.java**
> Issue #13213: Removed //ok from declarationorder

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc1One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc1Two.java
Enforced filesize for InputMissingJavadocTypeNoJavadoc1
> Issue #11163: Enforced filesize TypeNoJavadoc1

- src/xdocs/releasenotes.xml
`mvn clean verify` is failing in master: https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=19138&view=logs&j=e663805c-ee13-5a24-f979-d725e0346c8e&t=40ff6e43-c5d7-5753-f947-23012624b0c6
```
[INFO] --- maven-antrun-plugin:3.1.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle-checks.xml): 28/01/2024 02:53:39 PM
[INFO] [checkstyle] Running Checkstyle  on 2119 files
[ERROR] [checkstyle] [ERROR] /home/vsts/work/1/s/src/xdocs/releasenotes.xml:50: Line should not be longer than 100 symbols [lineLengthXml]
[ERROR] [checkstyle] [ERROR] /home/vsts/work/1/s/src/xdocs/releasenotes.xml:55: Line should not be longer than 100 symbols [lineLengthXml]
[INFO]      [echo] Checkstyle finished (checkstyle-checks.xml) : …
```
> doc: fix releasenotes.xml line length violation

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/checker-framework-suppressions/checker-methods-resource-fenum-suppressions.xml
- pom.xml
> Issue #14346: Bump maximum heap size for checker framework execution

- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
detected at https://github.com/checkstyle/checkstyle/pull/13991#discussion_r1456759351
to be merged after https://github.com/checkstyle/checkstyle/pull/13991
> minor: remove token from ignore list that are present in google config

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldReceiver.java
For issue - #13213 
Removed //ok comments from the following files :
- `InputHiddenField8.java`
- `InputHiddenFieldReceiver.java`
> Issue #13213: Removed //ok from hiddenfield

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionParameterNumberTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameternumber/SuppressionXpathRegressionParameterNumberDefault.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameternumber/SuppressionXpathRegressionParameterNumberIgnoreOverriddenMethods.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameternumber/SuppressionXpathRegressionParameterNumberMethods.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
issue #6207 [(Documentation)](https://checkstyle.org/checks/sizes/parameternumber.html#ParameterNumber)
1 test for default config, 1 for methods check, 1 for ignore override
> Issue #6207: Add XPath IT Regression test for ParameterNumberCheck

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineMultilineForDeclarations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineMultilineInLoopsAndTryWithResources.java
issue #11163:
force file size on InputOneStatementPerLineMultiline
OneStatementPerLine module is done
> Issue #11163: Enforced filesize InputOneStatementPerLineMultiline

- config/checkstyle-examples-suppressions.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example5.java
- src/xdocs/checks/misc/outertypefilename.xml
- src/xdocs/checks/misc/outertypefilename.xml.template
Part of #13345 
Enabled OuterTypeFilenameCheckExamplesTest
> Issue #13345: Enabled OuterTypeFilenameCheckExamplesTest

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMethodLengthTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodlength/SuppressionXpathRegressionMethodLengthNoEmptyLines.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodlength/SuppressionXpathRegressionMethodLengthSimple.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodlength/SuppressionXpathRegressionMethodLengthSingleToken.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Enable XpathRegressiontest for MethodLength

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingleadingasterisk/Example1.java
- src/xdocs/checks/javadoc/javadocmissingleadingasterisk.xml
- src/xdocs/checks/javadoc/javadocmissingleadingasterisk.xml.template
Part of #13345 
Enabled JavadocMissingLeadingAsteriskCheckExamplesTest
> Issue #13345: Enabled JavadocMissingLeadingAsteriskCheckExamplesTest

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSimplifyBooleanExpressionTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/simplifybooleanexpression/SuppressionXpathRegressionSimplifyBooleanExpressionAnonymous.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/simplifybooleanexpression/SuppressionXpathRegressionSimplifyBooleanExpressionInterface.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/simplifybooleanexpression/SuppressionXpathRegressionSimplifyBooleanExpressionSimple.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
part of issue #6207:
[(doc)](https://checkstyle.org/checks/coding/simplifybooleanexpression.html#SimplifyBooleanExpression)
> Issue #6207: Add XPath IT Regression test for SimplifyBooleanExpression

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentReceiver.java
Part of #13213
Removed `//ok` comments from **InputParameterAssignmentReceiver.java**
> Issue #13213: Removed //ok from parameterassignment

- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checker/InputCheckerTabCharacter.txt
> Issue #11446: Update TestTabViolation Method Of Checkertest

- .ci/no-exception-test.sh
- .circleci/config.yml
> Issue #12558: Execute all checkstyle samples in each PR execution (gradle)

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentLambdaExpressions.java
removed UnnecessaryOkComment suppressions related to inputinnerassignment module
> Issue #13213: removed suppressions related to inputinnerassignment

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckBlockCommentBegin.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckBlockCommentEnd.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckCommentsContent.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckDefaultTokenLabel.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckSingleLineComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckSwitchAndPostIncDec.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckTokenNative.java
Part of #14436 
Enforced naming convention on illegaltoken module
> Issue #14436: Enforced naming convention for illegaltoken

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsIgnoreMethodNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsIgnoreOverriddenMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestClassNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestIllegalClassNames.java
Issue: #13213
Removed // ok comments from files in illegalthrows and the suppressions
> Issue #13213: Remove '//ok' comments from illegalthrows

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextDefaultFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable.java
> Issue #13213: Remove '//ok' comments from Input files (illegaltokentext)

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java
Issue #14019: 
https://github.com/checkstyle/checkstyle/blob/a4411aa08c3a9744139067dc38ced282adbf9fcc/config/pitest-suppressions/pitest-utils-suppressions.xml#L3-L10
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/471fd9cd53eb2c56da8a5748f832a3987c9235ff/check.xml
Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/649bd1dced8e2cde1d5b5aa148ab93a1/raw/db4ff628cf5ecdf578729cd4811f880de1fca868/projects-to-test-on.properties
> Issue #14019: Kill mutation in ModuleReflectionUtil

- src/xdocs/index.xml.vm
from https://github.com/checkstyle/checkstyle/actions/runs/8059216426/job/22013243199#step:4:2401
`+<a class="externalLink" href="https://netbeans.apache.org/">https://netbeans.apache.org/</a>: 301 Moved Permanently`
https://wheregoes.com/trace/20241081435/
> minor: fix link to avoid redirection (link-check-plugin)

- .ci/codenarc.groovy
Closes #14556 
Extension of Issue https://github.com/checkstyle/contribution/issues/757 and response to https://github.com/checkstyle/contribution/issues/757#issuecomment-1965744852
CodeNarc release used : `v2.2.0`
Link to page : https://github.com/CodeNarc/CodeNarc/releases
Verified changes on local : 
```
[INFO] Total time:  01:56 h
[INFO] Finished at: 2024-02-27T12:17:22+05:30
```
> Issue #14556: Bump Codenarc version to highest compatible release v2.2.0

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/pkghtml/InputJavadocPackageHtmlIgnored2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCorrect.java
Issue #13213 
Removed   //  ok  from InputJavadocPackageHtmlIgnored2.java   and   InputJavadocParagraphCorrect.java with its  suppressions
> Issue #13213: Remove '//ok' comments 

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionExecutableStatementCountTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/executablestatementcount/SuppressionXpathRegressionExecutableStatementCountCustomMax.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/executablestatementcount/SuppressionXpathRegressionExecutableStatementCountDefault.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/executablestatementcount/SuppressionXpathRegressionExecutableStatementCountLambdas.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #6207 
[Documentation](https://checkstyle.org/checks/sizes/executablestatementcount.html#ExecutableStatementCount)
Three files for : 
1. Default config
2. Added max property
3. Added token property
> Issue #6207: Add XPath IT Regression test for ExecutableStatementCountCheck

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtorEmptyClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtorNestedClasses.java
> Issue #14436: Enforced naming convention for MissingCtor

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeNoJavadocOnInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariableInner2.java
Issue #13213 
Removed // ok from InputJavadocPackageHtmlIgnored2.java and  InputJavadocTypeNoJavadocOnInterface.java and InputJavadocVariableInner2.java with its suppressions
> Issue #13213: Remove unnecessary comments

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThis15Extensions.java
Issue #13213: Removed '//ok' from InputRequireThis15Extensions along with its suppressions
> Issue #13213: Removed '//ok' from InputRequireThis15Extensions along with its suppressions

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextCheckCaseInSensitive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextCheckCommentToken.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextCheckCustomMessageInStringLiteral.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextCheckDefaultCaseSensitive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextCheckNullMessageInStringLiteral.java
Part of Issue no. #14436 
Enforced naming convention on illegalTokenTextCheckTest
> Issue #14436: Enforced naming convention for illegalTokenTextCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
**Updated:**
**Old:**
**Test.java code used**
```
/**
* Some java doc.
*
* @return true if file exists
* @param fileExists file exists
*/
public boolean fileVerify(boolean fileExists) {
return fileExists;
}
}
```
**Run command**
`java -jar checkstyle-10.14.0-all.jar -J Test.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'`
**Output**
```
|--IDENT -&gt; Test
|--METHOD_DEF -&gt; METHOD_DEF
|   |--MODIFIERS -&gt; MODIFIERS
|   |   |--BLOCK_COMMENT_BEGIN -&gt; /*
|   |   |   |--COMMENT_CONTENT -&gt; *\r\n     * Some java doc.\r\n     *\r\n     * …
```
> Issue #14631: Updated RETURN_LITERAL of JavadocTokenTypes.java to new format of AST print

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
**Updated**
**Old**
Issue: #14631 
**Test.java code used**
```
/**
* Javadoc.
*
* @param value The parameter of method.
* @see <a href="https://docs.oracle.com/en/java/">Java Dcoumentation</a>
*/
public void testFunction(String value) {
}
}
```
**Command to run**
`java -jar checkstyle-10.14.0-all.jar -J Test.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'`
**Output**
```
|--IDENT -&gt; Test
|--METHOD_DEF -&gt; METHOD_DEF
|   |--MODIFIERS -&gt; MODIFIERS
|   |   |--BLOCK_COMMENT_BEGIN -&gt; /*
|   |   |   |--COMMENT_CONTENT -&gt; *\r\n     * …
```
> Issue #14631: Updated PARAM_LITERAL of JavadocTokenTypes.java to new format of AST print

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/checks/imports/customimportorder.xml
- src/xdocs/checks/imports/customimportorder.xml.template
closes #13693
https://checkstyle.org/checks/imports/customimportorder.html#Properties
nuance with not easy property default value is postponed until https://github.com/checkstyle/checkstyle/issues/14178 all explanation why we need override is here.
> Issue 13693 - CustomImportOrderCheck

- .ci/validation.sh
- .circleci/config.yml
related to  #14211
placing in CI what I tested at https://github.com/checkstyle/checkstyle/issues/14211#issuecomment-2002201042
> infra: add spotbugs to CI to prevent transitive dependency problems for gradle users #14211

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/Example1.java
- src/xdocs/checks/design/hideutilityclassconstructor.xml
- src/xdocs/checks/design/hideutilityclassconstructor.xml.template
Part of Issue #13345.
Preparing for Issue #14424
> Issue #13345: Enable example tests for HideUtilityClassConstructorCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631  
```
|--METHOD_DEF -> METHOD_DEF [8:2]
|   |--MODIFIERS -> MODIFIERS [8:2]
|   |   |--ANNOTATION -> ANNOTATION [8:2]
|   |   |   |--BLOCK_COMMENT_BEGIN -> /* [2:1]
|   |   |   |   |--COMMENT_CONTENT -> *\n   * Some Java doc.\n   *\n   * @param p1 The first number\n   * @serialData Two values of Integer type\n    [2:3]
|   |   |   |   |   `--JAVADOC -> JAVADOC [2:4]
|   |   |   |   |       |--NEWLINE -> \n [2:4]
|   |   |   |   |       |--LEADING_ASTERISK ->    * [3:0]
|   |   |   |   |       |--TEXT ->  Some Java doc. [3:4]
| …
```
> Issue #14631: Update SINCE_LITERAL to new AST fromet

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughSwitchRules.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughLabeledBreak.java
Resolves: #11230
This PR aims to fix FallThroughCheck for labeled statements. 
Diff regression config: https://gist.githubusercontent.com/relentless-pursuit/5f484c60cf4933dcc3cadc564e7e574f/raw/70d35777b174a9d980d09644bb45d1c4fc483365/config_fallThroughCheck.xml
> Issue #11230: fix FallThroughCheck for labeled statements

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/AuditEventTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilterSetTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ChainedPropertyUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java
Issue #11343: Wrap assertThrows with getExpectedThrowable method
> Issue #11343: Wrap assertThrows with getExpectedThrowable method

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
We leaked failures into master during rebase at #14717
> minor: fix failing build in master

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidDoubleBraceInitializationTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidEscapedUnicodeCharactersTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidInlineConditionalsTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidNestedBlocksTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoiddoublebraceinitialization/InputXpathAvoidDoubleBraceInitializationClassFields.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoiddoublebraceinitialization/InputXpathAvoidDoubleBraceInitializationMethodDef.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidescapedunicodecharacters/InputXpathAvoidEscapedUnicodeCharactersAllEscaped.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidescapedunicodecharacters/InputXpathAvoidEscapedUnicodeCharactersControlCharacters.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidescapedunicodecharacters/InputXpathAvoidEscapedUnicodeCharactersDefault.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidescapedunicodecharacters/InputXpathAvoidEscapedUnicodeCharactersNonPrintable.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidescapedunicodecharacters/InputXpathAvoidEscapedUnicodeCharactersTailComment.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/InputXpathAvoidInlineConditionalsAssert.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/InputXpathAvoidInlineConditionalsAssign.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/InputXpathAvoidInlineConditionalsVariableDef.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/InputXpathAvoidNestedBlocksAllowedInSwitchCase.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/InputXpathAvoidNestedBlocksBreakOutside.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/InputXpathAvoidNestedBlocksEmpty.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/InputXpathAvoidNestedBlocksNotAllowedInSwitchCase.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/InputXpathAvoidNestedBlocksVariable.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #14715 
@rnveach , there are exactly 20 files :)
> Issue #14715: Enforced new naming convention in IT area - Part Two
