checkstyle/checkstyle

- .github/workflows/check-pr-description.yml
- .github/workflows/checker-framework.yml
- .github/workflows/diff-report.yml
- .github/workflows/site.yml
Upgrades `actions/checkout` to v3
https://github.com/checkstyle/checkstyle/pull/12959#discussion_r1158548369
Upgrading to `v3` of action upgrades to node v16 runtime: https://stackoverflow.com/a/73474103/9553927. v2 uses node v12 which is out of support since April 2022 - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> minor: upgrade actions/checkout to v3

- pom.xml
I do not know why only this page is problematic
https://github.com/checkstyle/checkstyle/actions/runs/4621172724/jobs/8172260574#step:4:2383
```
<td><i><a class="externalLink" 
href="https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.28">
https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.28</a>
: 500 Internal Server Error</i></td></tr></table></td></tr>
<td><i><a class="externalLink" 
href="https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.28">
https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.28</a>
: 500 Internal Server Error</i></td></tr></table></td></tr>
```
it is not single usage of this jdk docs
``` …
```
> minor: exclude annoying link that results in 500 http code frequently

- config/pitest-suppressions/pitest-api-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableTestWarningSeverity.java
Resolves #12876 
@romani @nrmancuso 
Surviving mutation has been killed. 
Note that pure JUnit test has been used to kill the mutation. Reason for this is mentioned as a multiline comment above the test suite in ``AbstractViolationReportertest.java``.
> Issue #12876: Resolve pitest suppression for AbstractViolationReporter

- .ci/diff-report.sh
- .github/workflows/diff-report.yml
Noticed at https://github.com/checkstyle/checkstyle/pull/12979#issuecomment-1509958270 and elsewhere, it looks like we are failing to download files for report generation. Example from logs:
```
...
2023-04-15T20:33:26.0038234Z   PATCH_CONFIG_LINK: 
2023-04-15T20:33:26.0038722Z   LINK_FROM_PR: https://gist.githubusercontent.com/0xbakry/7853843aa3d69aee301d7a8d62d08ebb/raw/65a7d6bee0ad8ad789c17f778ce7d8b0056ae28b/my_projects
2023-04-15T20:33:26.0039194Z ##[endgroup]
2023-04-15T20:33:26.1529944Z ##[error]Process completed with exit code 8.
...
```
exit code 8 from wget typically denotes a error response from the server, read more at https://stackoverflow.com/questions/65677320/what-does-server-issued-an-error-responseexit-status-8-mean-in-wget#:~:text=The%20man%20page%20of%20wget,types%20of% …
> infra: update diff report file download to use GitHub token and curl

- .github/workflows/diff-report.yml
Noticed at https://github.com/checkstyle/checkstyle/actions/runs/4723225716/jobs/8379544362, we need to bump checkout step so that repo exists in ci:
```
/home/runner/work/_temp/d39f4dfa-b81f-44f2-a2d5-aa97b4886bac.sh: line 1: ./.ci/diff-report.sh: No such file or directory
Error: Process completed with exit code 127.
```
> infra: bump checkout step to first step

- .github/workflows/diff-report.yml
closes #12995
-----------
Ok, here is the real issue: https://github.com/checkstyle-ci-tester/checkstyle/actions/runs/4739501477/jobs/8414388078#step:5:25
```
./text: ASCII text, with CRLF, LF line terminators
```
GitHub uses windows line endings in comments/descriptions, and when we get the text from the event it has windows line endings. Here is the line endings shown in a [tool](https://www.soscisurvey.de/tools/view-chars.php) that I found online:
The problem is that when we grep and sed these lines from the text, we leave a single carriage return at the end of each line. Example:
```
curl --fail-with-body -X GET $'https://gist.githubusercontent.com/0xbakry/a1fcb13eef42f29de8ff500892f34166/raw/1b0af8d2da606b273e8ef9aaed6278020f876202/config_check.xml/r' -H 'Accept: …
```
> Issue #12995: Fix windows line endings in GitHub event text

- .github/workflows/bump-version-and-update-milestone.yml
- .github/workflows/checker-framework.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/diff-report.yml
- .github/workflows/error-prone.yml
- .github/workflows/pitest.yml
- .github/workflows/release-maven-perform.yml
- .github/workflows/release-maven-prepare.yml
- .github/workflows/release-new-milestone-and-issues-in-other-repos.yml
- .github/workflows/release-publish-releasenotes-twitter.yml
- .github/workflows/release-update-github-io.yml
- .github/workflows/release-update-github-page.yml
- .github/workflows/release-update-xdoc-with-releasenotes.yml
- .github/workflows/release-upload-all-jar.yml
- .github/workflows/releasenotes-gen.yml
- .github/workflows/run-link-check.yml
- .github/workflows/site.yml
Solves https://github.com/checkstyle/checkstyle/issues/12978
Upgradeing `actions/cache` to v3 upgrades `Node.js` to v16:
https://github.com/marketplace/actions/cache
> Issue #12978: Upgrade actions/cache to v3

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
Related to #12997 #12671 
Mutation killed:
https://github.com/checkstyle/checkstyle/blob/5768a5e30a00ad8c2ae80da5fb67961219acf7b6/.ci/pitest-suppressions/pitest-coding-2-suppressions.xml#L48-L55
Diff Regression config: https://gist.githubusercontent.com/coderdeadpool/96fa62c511add1eb980efe8de851256d/raw/57420e4b601c7ed073340dd039e5c4af7a0d1ccd/gistfile1.txt
> Issue #12997: Resolve pitest suppression for FinalLocalVariableCheck

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
Related to #12671 #12341 
Mutation Killed:
https://github.com/checkstyle/checkstyle/blob/b9cd0cb3553a21795d27a0238625c96ed8f8a33d/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L12-L19
Diff Regression config: https://gist.githubusercontent.com/coderdeadpool/96fa62c511add1eb980efe8de851256d/raw/57420e4b601c7ed073340dd039e5c4af7a0d1ccd/gistfile1.txt
> Issue #12671: Resolve pitest for FinalLocalVariableCheck

- .ci/diff-report.sh
- .github/workflows/diff-report.yml
Part of #12991
We want to fail fast and provide feedback about bad parameter/URL. Right now, a bad URL will still make it to the make-report job, where we just fail with a cryptic curl error. This wastes time and resources to re-clone the repo, etc. 
All of the issues that I see with report parameters are checked for in the `validate_url` function, namely:
1. newlines after `:` instead of single space
2. link to gist that is not a raw link
3. bad url in general
> Issue #12991: Improvements to diff report generation - parsing PR description and validation of URLs

- .github/workflows/diff-report.yml
- .github/workflows/site.yml
Solves https://github.com/checkstyle/checkstyle/issues/13031
Upgrading `aws-actions/configure-aws-credentials` to v2 upgrades `Node.js` to v16:
[aws-actions](https://github.com/aws-actions/configure-aws-credentials#:~:text=We%27ve%20recently%20released%20a%20v2%20of%20this%20action%20that%20uses%20the%20Node%2016%20runtime%20by%20default.%20You%20should%20update%20your%20action%20references%20to%20v2.%20We%20intend%20v2%20to%20be%20the%20new%20default%20for%20this%20action%20and%20will%20no%20longer%20be%20providing%20updates%20to%20the%20v1%20tag.)
> Issue #13031: Upgrade aws-actions to v2

- .ci/generate-extra-site-links.sh
Resolves #13054 
Before
```
$ ./.ci/generate-extra-site-links.sh 13042 https://checkstyle.org
PR_NUMBER=13042
AWS_FOLDER_LINK=https://checkstyle.org
CHANGED_XDOCS_PATHS=src/xdocs/index.xml.vm
EARLIEST_CHANGE_LINE_NUMBER=91
CURRENT_XDOC_NAME=index.vm
$ cat .ci-temp/message 
https://checkstyle.org/index.vm.html#
```
After
```
$ ./.ci/generate-extra-site-links.sh 13042 https://checkstyle.org 
PR_NUMBER=13042
AWS_FOLDER_LINK=https://checkstyle.org
CHANGED_XDOCS_PATHS=src/xdocs/index.xml.vm
EARLIEST_CHANGE_LINE_NUMBER=91
CURRENT_XDOC_NAME=index
$ cat .ci-temp/message 
https://checkstyle.org/index.html#
```
> Issue #13054: Site Action generate bad link to index page

- .ci/pitest.sh
Issue #13063 
Fix tested on Mac, Fedora and Ubuntu as follows:
Mac
```
/var/tmp/checkstyle[issue-13063 L|✔] [20:56:18]% uname -v
Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
/var/tmp/checkstyle[issue-13063 L|✔] [20:56:24]% ./.ci/pitest.sh --list
Supported profiles:
pitest-annotation
pitest-ant
pitest-api
pitest-blocks
pitest-coding-1
pitest-coding-2
pitest-coding-require-this-check
pitest-common
pitest-common-2
pitest-design
pitest-filters
pitest-gui
pitest-header
pitest-imports
pitest-indentation
pitest-java-ast-visitor
pitest-javadoc
pitest-main
pitest-metrics
pitest-misc
pitest-modifier
pitest-naming
pitest-packagenamesloader
pitest-regexp
pitest-sizes
pitest-tree-walker
pitest-utils
pitest-whitespace
pitest-xpath
```
Fedora
``` …
```
> Issue #13063: fix listing pitest profiles on Mac

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java
Solves issue #11214 for MethodParamPadCheck
- Build successful with `mvn clean verify`
- Removed MethodParamPadCheck from suppression list
- Added violation messages for InputMethodParamPadRecords
> Issue #11214: Specify violation messages for MethodParamPadCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/UnusedImportsCheck.xml
- src/xdocs/config_imports.xml
Issue #13007 : Update doc for UnusedImports
Site after changes: 
Default
```
/var/tmp $ javac MyClass.java
/var/tmp $ cat config.xml
<module name = "TreeWalker">
<module name="UnusedImports"/>
</module>
</module>
/var/tmp $ cat MyClass.java
// limitation as it match field name in code
import java.awt.Component; //OK
// no ability to recognize what import is not used
import static java.util.Map.copyOf; //OK
import static java.util.Arrays.copyOf; //OK
import java.lang.String; // violation
import java.util.Stack;  // OK
import java.util.Map;   // violation
import java.util.List; // OK
/**
* @link List
*/
class …
```
> Issue #13007: Update doc for UnusedImports

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/gui/BaseCellEditorTest.java
Solves issue #11514 Improve code coverage for GUI classes - BaseCellEditor
* Added test file and new test cases for BaseCellEditor
* Improved method coverage by 44% and line coverage by 69%
* Built successfully with `mvn clean verify`
> Issue #11514: add test case for base cell editor

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTableModelTest.java
Solves issue #11514 Improve code coverage for GUI classes
- Built successfully with `mvn clean verify`
- Added a new ParseTreeTableModelTest
- Increased the code coverage of ParseTreeTableModel class
```
$ java -jar checkstyle-10.9.2-all.jar -T InputParseTreeTablePresentation.java 
|--PACKAGE_DEF -> package [1:0]
|   |--ANNOTATIONS -> ANNOTATIONS [1:43]
|   |--DOT -> . [1:43]
|   |   |--DOT -> . [1:39]
|   |   |   |--DOT -> . [1:28]
|   |   |   |   |--DOT -> . [1:22]
|   |   |   |   |   |--DOT -> . [1:11]
|   |   |   |   |   |   |--IDENT -> com [1:8]
|   |   |   |   |   |   `--IDENT -> puppycrawl [1:12]
|   |   |   |   |   `--IDENT -> tools [1:23]
|   |   |   |   `--IDENT -> checkstyle [1:29]
|   |   |   `--IDENT -> gui [1:40]
|   |   `--IDENT -> …
```
> Issue #11514: Improve code coverage by adding a new ParseTreeTableModelTest

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrder2.java
Issue #13102: kill mutation for DeclarationOrderCheck
covering 
https://github.com/checkstyle/checkstyle/blob/d7f62fc0f643eb54c3b20d9e9243ec72faea637f/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L21-L28
> Issue #13102: kill mutation for DeclarationOrderCheck

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
**1**  Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 3
**2** Link to Check Documentation :-
https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance
**3** covering 
https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L129-L136
**4** Logic behind mutation removal
I don't find any test case which can kill this mutation.
https://github.com/Kevin222004/checkstyle/blob/d60bae5293a4221f4e5b28da1300441a90be5d44/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L569-L571
whenever the token type is off `TokenTypes.VARIABLE_DEF` then `resultDist++;` will increment by 1.
In default case …
> Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 3

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
Issue #13109: Kill mutation for EqualsAvoidNullCheck
**1 check** :- https://checkstyle.org/config_coding.html#EqualsAvoidNull
**2covering** :- 
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L12-L19
**3 Explaination**
`getObjectFrame()` method will provide the nearest parent frame of class, enum.
if we remove getObjectFramefrom the `FieldFrame frame = getObjectFrame(currentFrame);` and `frame = getObjectFrame(frame.getParent());` they will go through all the frame instead of directly going to frame which are class or enum.
and as per the condition in loop `className.equals(frame.getFrameName())` 
frameName would always be of class enum as per …
> Issue #13109: Kill mutation for EqualsAvoidNullCheck

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
Issue #13109: Kill mutation for EqualsAvoidNullCheck 2
**1 check** :- https://checkstyle.org/config_coding.html#EqualsAvoidNull
**2covering** :- 
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L21-L28
**3 Explaination**
`getObjectFrame()` method will provide the nearest parent frame of class, enum.
if we remove getObjectFramefrom the `FieldFrame frame = getObjectFrame(currentFrame);` and `frame = getObjectFrame(frame.getParent());` they will go through all the frame instead of directly going to frame which are class or enum.
and as per the condition in loop `className.equals(frame.getFrameName())` 
frameName would always be of class enum as per …
> Issue #13109: Kill mutation for EqualsAvoidNullCheck 2

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java
NullChecking is missing to avoid an error when reading a ternary operator that contain unnecessary parenthesis, these can of course be removed but this is another checkstyle rule and should not throw any exception while reading this line
Diff Regression config: https://gist.githubusercontent.com/SebHeuze/2925a42bb90d851892522cb4c2d1c9dc/raw/23982ee5bf8813df8776f14854aac4064649310c/my_check.xml
> Issue #13140: Fix NullPointerException

- src/xdocs/releasenotes.xml
Detected while doing local runs with linkcheck
> minor: fix broken link in releasenotes

- config/pitest-suppressions/pitest-api-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
Issue #13109: Kill mutation for FileContents
---------------------
https://github.com/checkstyle/checkstyle/blob/82b6ac46193fafdfbcfc5dacbb848004c36a82e4/config/pitest-suppressions/pitest-api-suppressions.xml#L3-L19
--------------------
Test cases expanded.
If we see `return Collections.unmodifiableMap(cppComments);` is mutated to `return cppComments;`. basically  Collections. unmodifiable will not allow us to make any updates to the map. if we try to update it it will throw `UnsupportedOperationException`. so in this test case if we try to remove data from the comment so it will throw the exception
> Issue #13109: Kill mutation for FileContents

- config/pitest-suppressions/pitest-api-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java
Issue #13109: Kill mutation for FileText
--------------------
https://github.com/checkstyle/checkstyle/blob/82b6ac46193fafdfbcfc5dacbb848004c36a82e4/config/pitest-suppressions/pitest-api-suppressions.xml#L21-L28
-----------------------
Test cases added
> Issue #13109: Kill mutation for FileText

- config/archunit-store/slices-should-be-free-of-cycles-suppressions
- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-api-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
Issue #13109: Kill mutation for FileText 2
--------------
https://github.com/checkstyle/checkstyle/blob/82b6ac46193fafdfbcfc5dacbb848004c36a82e4/config/pitest-suppressions/pitest-api-suppressions.xml#L75-L82
--------------
Our code is
```
public FileText(FileText fileText) {
file = fileText.file;
charset = fileText.charset;
fullText = fileText.fullText;
lines = fileText.lines.clone();
if (fileText.lineBreaks == null) {
lineBreaks = null;
}
else {
lineBreaks = fileText.lineBreaks.clone();
}
}
```
Here the part of code  
```
if (fileText.lineBreaks == null) {
lineBreaks = null;
}
```
is mutated as 
```
if (fileText.lineBreaks == null) {
}
```
Here the condition in if statment is 
something like 
```
fileText.lineBreaks == null
```
know if we see logically their is 2 possiblity 
either …
> Issue #13109: Kill mutation for FileText 2

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
Issue #13109: Kill mutation for UnnecessaryParenthesesCheck 2
----------------
https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L66-L73
------------
ast.gettext() is not require because we are not showing it.
https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties#L60
> Issue #13109: Kill mutation for UnnecessaryParenthesesCheck 2

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
Issue #13102: kill mutation for DeclarationOrderCheck 2
check :- https://checkstyle.org/config_coding.html#DeclarationOrder
covering :- 
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L3-L10
Explanation:- 
if we look at else part the if condition will execute when state.`currentScopeState` is greater than `STATE_STATIC_VARIABLE_DEF`
As per https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java#L228
the value of `STATE_STATIC_VARIABLE_DEF` is 1 
know if will only execute when state.current scope if either 2, 3, 4 means greater than 1 not even 1.
so if their the value of …
>  Issue #13102: kill mutation for DeclarationOrderCheck 2

- config/ant-phase-verify-sevntu.xml
https://github.com/checkstyle/checkstyle/pull/13135 and https://github.com/checkstyle/checkstyle/pull/13143 fail on sevntu check. We have to exclude resources from this
> minor: exclude xdocs-examples resources from sevntu checks

- pom.xml
Addresses CVE-2020-8908 and CVE-2023-2976
Last update of version: https://github.com/checkstyle/checkstyle/commit/29bdef1e516b7cfe72f13d8a15553f59359df71b
> dependency: bump guava from 31.1-jre to 32.0.1-jre

- config/pitest-suppressions/pitest-api-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java
Issue #13109: Kill mutation for FullIdent.java
--------------
https://github.com/checkstyle/checkstyle/blob/b8753a7a025f706d41e6e7b1de302d94da3b8c0f/config/pitest-suppressions/pitest-api-suppressions.xml#L57-L73
---------------
So we have code :- 
https://github.com/checkstyle/checkstyle/blob/b8753a7a025f706d41e6e7b1de302d94da3b8c0f/src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java#L119-L128
in which 
https://github.com/checkstyle/checkstyle/blob/b8753a7a025f706d41e6e7b1de302d94da3b8c0f/src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java#L120
is mutated as 
`DetailAST expression = arrayDeclarator`
Here expression is assigned as `arrayDeclarator.getFirstChild` 
when the loop is going to start it will check whether the expression is null or not know if we remove …
> Issue #13109: Kill mutation for FullIdent.java

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
Issue #13109: Kill mutation for UnusedLocalVariableCheck 6
---------
https://checkstyle.org/config_coding.html#UnusedLocalVariable
--------
https://github.com/checkstyle/checkstyle/blob/958051594a64ea5a228359919ed7426e69a242d7/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L309-L316
--------
hence it is not possible to create a such test that kills mutation. instead of starting the loop with `literalNewAst.getParent()` if we start from `literalnewAst` at the end of the first iteration in the loop it will become literalNewAst.getParent. loops run one time more then it was running previously.
hence while as per my changes currentAST go in loop it never be in array of CONTAINERS_FOR_ANON_INNERS https://github.com/checkstyle/checkstyle/blob/958051594a64ea5a228359919ed7426e69a242d7 …
> Issue #13109: Kill mutation for UnusedLocalVariableCheck 6

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
Issue #13109: Kill mutation for ReturnCountCheck
-------------------
https://checkstyle.org/config_coding.html#ReturnCount
----------------------
https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L39-L55
-----------------------
**1) Test cases**
Here in this check, we have an acceptable token
https://github.com/checkstyle/checkstyle/blob/655196ed840b1cb443607a9e6f330a562bfcb2c4/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java#L332-L338
and in visitToken and Leave Token all the acceptable tokens have their own case.
so without pure unit testing not possible to create such kind of scenario to cover default.
**2) Removal of code**
Here in this check, we have an …
> Issue #13109: Kill mutation for ReturnCountCheck

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
1 Issue https://github.com/checkstyle/checkstyle/issues/13095: kill mutation for VariableDeclarationUsageDistanceCheck 5
------------
https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance
-----------
https://github.com/checkstyle/checkstyle/blob/6f451fbb49afc21b0e04b46c0576c7a984419a88/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L111-L118
---------
ok so the whole loop will start if 
https://github.com/checkstyle/checkstyle/blob/c5566a6ea8c336ddedde446648b03ef56a73b7ba/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L613
currentScopeAst != null;
then 
https://github.com/checkstyle/checkstyle/blob/c5566a6ea8c336ddedde446648b03ef56a73b7ba/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/Var …
> Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 5

- .ci/eclipse-compiler-javac.sh
Noticed at https://checkstyle.semaphoreci.com/jobs/a2f1d5ba-6547-45a8-a9b1-fc00c7f7c49c, we need to update jdk for this job to 17 (major ver. 61)
> infra: update jdk for eclipse static analysis

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpecialImportsRegExp.java
Issue #13109: Kill mutation for CustomImportOrderCheck
--------
Check :- 
https://checkstyle.org/config_imports.html#CustomImportOrder
-----
https://github.com/checkstyle/checkstyle/blob/3f77dd11d7e7ac8e23ecc817a1caeeea7d1a489d/config/pitest-suppressions/pitest-imports-suppressions.xml#L2-L19
-----------
Test cases added
> Issue #13109: Kill mutation for CustomImportOrderCheck

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
Issue #13109: Kill mutation for UnnecessaryParenthesesCheck
-------------
https://checkstyle.org/config_coding.html#UnnecessaryParentheses
---------
https://github.com/checkstyle/checkstyle/blob/c5566a6ea8c336ddedde446648b03ef56a73b7ba/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L48-L55
---------
The only reason i can see to removal of this will not make issue is the checkExpression method is used only in leaveToken 
```
if (type == TokenTypes.EXPR) {
checkExpression(ast);
}
```
so the changes of ParentToSkip will not really make any effect in code because token will be leaved if the is statment is been executed, it will never be used after it.
------
Regression :- 
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/13cdd33_2023060542/reports/diff/index.html …
> Issue #13109: Kill mutation for UnnecessaryParenthesesCheck

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextDefaultFormat.java
Issue #13109: Kill mutation for IllegalTokenTextCheck
-------
https://checkstyle.org/config_coding.html#IllegalTokenText
----------
https://github.com/checkstyle/checkstyle/blob/eaed451ba71f543d7a98675d521ca8bb428f79d5/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L57-L73
-----------
Test cases added
----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/13ca2532a9d40774066ac08c558f4111/raw/e41a49826864eac40ca16a3d2865cfb993255e98/IllegalTokenText.xml
Report label: Report-2
> Issue #13109: Kill mutation for IllegalTokenTextCheck

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
Issue #12671: Kill mutation for finalLocalVariable-2
----------
https://checkstyle.org/config_coding.html#FinalLocalVariable
--------
https://github.com/checkstyle/checkstyle/blob/c5566a6ea8c336ddedde446648b03ef56a73b7ba/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L21-L28
--------
ok so the `&& isSameVariables(storedVariable, variable)` condition in if will check wether the StoredVariable and variable is same or not.
Know if Storedvariable is null then the condition will not execute and if it is not then `storedVariable = candidate.variableIdent;` and `final FinalVariableCandidate candidate = scopeData.scope.get(variable.getText());` 
know as per the initalization of candidate it will always get data scope which is variable 
and stored variable is also assigned as ` …
> Issue #12671: Kill mutation for finalLocalVariable-2

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
Issue #13109: Kill mutation for MagicNumber
--------
https://checkstyle.org/config_coding.html#MagicNumber
---------
https://github.com/checkstyle/checkstyle/blob/eaed451ba71f543d7a98675d521ca8bb428f79d5/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L93-L100
------------
if we remove .getParent no issue will their because in loop it will be update by `currentAST = currentAST.getParent();` so the loops run one timr more.
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/6c454ec1c672a21710fc0cda01ceaf5b/raw/3fc36498aa1511c61c41cefb46ff02cdf8a1d2bb/magic.xml
Report label: …
> Issue #13109: Kill mutation for MagicNumber

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
This is needed for examples that will go in `resources-noncompilable` folder.
`getResourceLocation` is specified in each examples test:
https://github.com/checkstyle/checkstyle/blob/81cb6f1ee7d6fb729df255681c4c7cd7340ebb67/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckExamplesTest.java#L33-L35
> minor: construct non-compilable path based on resource location

- .ci/validation.sh
We need to make sure that resources in the non-compilable folder are verified by javac*
We also need to add a check that any example resource in this folder has a comment with compilation details.
> infra: add compilation of non-compilable examples

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports3.java
Issue #13109: Kill mutation for UnusedImportCheck-2
---------
Check : 
https://checkstyle.org/config_imports.html#UnusedImports
----------
https://github.com/checkstyle/checkstyle/blob/c7f3688f4380144bb712bee7ad6808cd075b327c/config/pitest-suppressions/pitest-imports-suppressions.xml#L174-L181
--------
Test added
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/27bfdb307fbeb7459ca132bcc5104c5b/raw/0d6a50d1d09d825a0947355e7ba1af3f80d94d74/UnusedImport.xml
Report label: R2
> Issue #13109: Kill mutation for UnusedImportCheck-2

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
Issue #13109: Kill mutation for CustomImportOrderCheck 4
----
https://checkstyle.org/config_imports.html#CustomImportOrder
------
https://github.com/checkstyle/checkstyle/blob/79d3c5536760d2645b0676c5a7f31da3bb0eed72/config/pitest-suppressions/pitest-imports-suppressions.xml#L30-L37
----------
This is setter for  https://github.com/checkstyle/checkstyle/blob/79d3c5536760d2645b0676c5a7f31da3bb0eed72/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L726
which is https://github.com/checkstyle/checkstyle/blob/79d3c5536760d2645b0676c5a7f31da3bb0eed72/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L809-L817 
we are not directly using this property hence all the rule will be first stored in …
> Issue #13109: Kill mutation for CustomImportOrderCheck 4

- pom.xml
Noticed at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/19045/workflows/82da432e-cfa8-49ad-b077-b122122ba35d/jobs/313477?invite=true#step-103-2437
```
1a2
> <td><i><a class="externalLink" href="http://www.mojohaus.org/xml-maven-plugin/">http://www.mojohaus.org/xml-maven-plugin/</a>: 301 Moved Permanently</i></td></tr></table></td></tr>
Exit code:1
Exited with code exit status 1
```
> minor: exclude mojohaus 301 link from linkcheck

- .ci/run-link-check-plugin.sh
Noticed at https://github.com/checkstyle/checkstyle/pull/13255#issuecomment-1596653952 (and other PRs)
Linkcheck script constantly has problems with items that are at the end of a table
```
501c501
< <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr>
---
> <td><i><a href="apidocs/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.html#%3Cinit%3E()">#%3Cinit%3E()</a>: doesn't exist.</i></td></tr></table></td></tr>
```
The difference here is just `</table></td></tr>` - the link is still the same
The link gets moved around and happens to be at the end of the table. Therefore, we get a …
> minor: trim table,tr and td tags in linkcheck

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/blocks/index.xml
- src/xdocs/checks/whitespace/index.xml
Identified at https://github.com/checkstyle/checkstyle/pull/13258#discussion_r1236976318
The tables in `index.xml` in each category(`blocks`, `naming`,etc..) are an exact copy of `checks.xml`. It turned out that the script doesn't extract them correctly, hence we need this check.
Test run found 3 issues merged. Here is one
```
The summary for check WhitespaceAfter in the file "src/xdocs/checks/whitespace/index.xml" should match the summary for this check in the file "src/xdocs/checks.xml"
expected: Checks that a token is followed by whitespace, with the exception that it does not check for whitespace after the semicolon of an empty for iterator.
but was : Checks that there is at least one whitespace after the leading asterisk.
```
> Pull #13285: Ensure category index page tables are in sync with checks.xml page table

- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example2.java
Noticed in https://github.com/checkstyle/checkstyle/pull/13286#issuecomment-1603676583
The checks for examples got merged yesterday and 3 trailing whitespace slipped into master.
```
[INFO] [checkstyle] Running Checkstyle  on 54 files
[ERROR] [checkstyle] [ERROR] /home/kevin/Desktop/check_style/checkstyle/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example1.java:14: Trailing whitespace is not allowed [noTrailingWhitespace]
[ERROR] [checkstyle] [ERROR] /home/kevin/Desktop/check_style/checkstyle/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/Example1.java:15: Trailing whitespace is not allowed [noTrailingWhitespace]
[ERROR] [checkstyle] [ERROR] …
```
> minor: fix trailing whitespace violations

- .ci/validation.sh
just tried to use latest commit from this repo.
https://github.com/pgjdbc/pgjdbc/commits/master
https://checkstyle.semaphoreci.com/jobs/c5552a3b-390a-4773-96d6-ea140a06ce78
```
> Task :buildSrc:jar 02:46
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins 02:46
> Task :buildSrc:assemble 02:46
> Task :buildSrc:compileTestKotlin NO-SOURCE 02:46
> Task :buildSrc:pluginUnderTestMetadata 02:46
> Task :buildSrc:compileTestJava NO-SOURCE 02:46
> Task :buildSrc:compileTestGroovy NO-SOURCE 02:46
> Task :buildSrc:testClasses UP-TO-DATE 02:46
> Task :buildSrc:test NO-SOURCE 02:46
> Task :buildSrc:validatePlugins 02:46
> Task :buildSrc:check 02:46
> Task :buildSrc:build 02:46
03:18
FAILURE: Build failed with an exception. 03:18
* What went wrong: 03:18
A problem occurred …
```
> infra: fix for validaton.sh pgjdbc failure

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheck.java
Issue #13109: Kill mutation for NestedTryDepthCheck
--------
https://checkstyle.org/config_coding.html#NestedTryDepth
----------
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L111-L118
----------
All the values will increase by visit token and decrement by leave Token so I don't see we should require to reset the value using beginTree because at the end it will be reset by leaveToken 
but lets see Regression
---------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dac5a8c_2023201111/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dac5a8c_2023225538/reports/diff/index.html
-------- …
> Issue #13109: Kill mutation for NestedTryDepthCheck

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java
Issue #13109: Kill mutation for NestedForDepthCheck
--------
https://checkstyle.org/config_coding.html#NestedForDepth
----------
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L93-L100
----------
All the values will increase by visit token and decrement by leave Token so I don't see we should require to reset the value using beginTree because at the end it will be reset by leaveToken 
but lets see Regression
---------
Report 1:- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1f65036_2023200854/reports/diff/index.html
Report-2:- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1f65036_2023230138/reports/diff/index.html
--------- …
> Issue #13109: Kill mutation for NestedForDepthCheck

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
Issue #13109: Kill mutation for UnusedImportCheck
---------
Check : 
https://checkstyle.org/config_imports.html#UnusedImports
----------
https://github.com/checkstyle/checkstyle/blob/c7f3688f4380144bb712bee7ad6808cd075b327c/config/pitest-suppressions/pitest-imports-suppressions.xml#L183-L190
--------
The trim function is basically used to remove the space from the starting and end of the string.
over here  `{@link JavadocTag}` space needs to be removed before and after arg JavadocTag.
I have tried many ways to put space before and after but there I no case available where this function usage is coming it is already trimmed.
Regression also finds nothing
---------
Report-1 :-  https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/895e49c_2023101010/reports/diff/index.html
Report-2 :- …
> Issue #13109: Kill mutation for UnusedImportCheck

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
Issue #13109: Kill mutation for CustomImport
---------
https://checkstyle.org/config_imports.html#CustomImportOrder
--------
https://github.com/checkstyle/checkstyle/blob/c7f3688f4380144bb712bee7ad6808cd075b327c/config/pitest-suppressions/pitest-imports-suppressions.xml#L3-L19
---------
ok so there are 4 places where `samePackageMatchingDepth` is used let's talk about first in method `addRulesToList`
https://github.com/checkstyle/checkstyle/blob/c7f3688f4380144bb712bee7ad6808cd075b327c/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L1225-L1234
know it will actually call by only a setter method which is `setCustomImportOrderRules` 
https://github.com/checkstyle/checkstyle/blob/c7f3688f4380144bb712bee7ad6808cd075b327c/src/main/java/com/puppycrawl/too …
> Issue #13109: Kill mutation for CustomImport

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
Issue #13109: Kill mutation for OneStatmentPerLineCheck-3
-----
https://checkstyle.org/config_coding.html#OneStatementPerLine
------
https://github.com/checkstyle/checkstyle/blob/e0d3066777834ba62c489d86bd3edc9727aa79e3/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L147-L172
-----
This all are getting their origin value at the time of init while leaving token. so no need to reset 
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/3bd236a24ed8eacd760e6b12b47f7455/raw/97d7a64aa97fc35488a6db5d7345ee23ae9b9507/olc.xml
> Issue #13109: Kill mutation for OneStatmentPerLineCheck-3

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
Issue #13109: Kill mutation for UnusedLocalVariableCheck 2
------------
https://checkstyle.org/config_coding.html#UnusedLocalVariable
-------------
https://github.com/checkstyle/checkstyle/blob/958051594a64ea5a228359919ed7426e69a242d7/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L273-L308
-------------
This might not be a good changes but still,
Here in the method 
https://github.com/checkstyle/checkstyle/blob/958051594a64ea5a228359919ed7426e69a242d7/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L509-L518
the code 
```
final VariableDesc desc = new VariableDesc(ident.getTe(),
varDefAst.findFirstToken(TokenTypes.TYPE), findScopeOfVariable(varDefAst));
```
is mutated as 
```
final VariableDesc desc = new …
```
> Issue #13109: Kill mutation for UnusedLocalVariableCheck 2

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheck.java
Issue #13109: Kill mutation for NestedIfDepthCheck
--------
https://checkstyle.org/config_coding.html#NestedIfDepth 
----------
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L102-L109
----------
All the values will increase by visit token and decrement by leave Token so I don't see we should require to reset the value using beginTree because at the end it will be reset by leaveToken 
but lets see Regression
---------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/033e5f2_2023175528/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/033e5f2_2023190546/reports/diff/index.html
---------- …
> Issue #13109: Kill mutation for NestedIfDepthCheck

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
Issue #13109: Kill mutation for OneStatementPerLineCheck-2
-----------
https://checkstyle.org/config_coding.html#OneStatementPerLine
----------
https://github.com/checkstyle/checkstyle/blob/c5566a6ea8c336ddedde446648b03ef56a73b7ba/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L183-L217
---------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/88d109b_2023082948/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2907cd7_2023142213/reports/diff/index.html
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/3bd236a24ed8eacd760e6b12b47f7455/raw/97d7a64aa97fc35488a6db5d7345ee23ae9b9507/olc.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb …
> Issue #13109: Kill mutation for OneStatementPerLineCheck-2

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
Issue #13109: Kill mutation for MultipleStringLiteralCheck
----------
https://checkstyle.org/config_coding.html#MultipleStringLiterals
----------
https://github.com/checkstyle/checkstyle/blob/3f25c37d731544f47d13020b47bfbec2a1bf57b6/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L57-L64
---------
The loops run one time more.
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/7d3bd1d1b0d117d9b3d1a23fb9a7ae26/raw/d1f8aec7b4247bda070e645445515de2b8421c7a/MultipleStringLiterals.xml
Report label: R1
> Issue #13109: Kill mutation for MultipleStringLiteralCheck

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/.gitkeep
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/.gitkeep
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/.gitkeep
We no longer need those `gitkeep`s since the directories have other files in them.
> minor: remove gitkeeps that are no longer needed

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocEmptyPeriod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocTestForbiddenFragments2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocTestForbiddenFragments3.java
Issue #13321: Kill mutation for SummaryJavaDocCheck-10
-----
-----
https://github.com/checkstyle/checkstyle/blob/aed4d3835de0da5e12c41e677e9a10be77b8a372/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L975-L1000
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/61eaa69fe98585b6ee1882ca082362bc/raw/316ca02ce9fd290119d9bfc560f2b11e84a1b685/Summary.xml
> Issue #13321: Kill mutation for SummaryJavaDocCheck-10

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect3.java
Issue #13321: Kill mutation for SummaryJavaDocCheck-9
-----
-----
https://github.com/checkstyle/checkstyle/blob/c3c7ab8f444509ccbd9e85add37f875bc8951b46/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L943-L959
-----
Test added
-----
> Issue #13321: Kill mutation for SummaryJavaDocCheck-9

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineReturn2.java
Issue #13321: Kill mutation for SummaryJavaDocCheck-12
-----
-----
https://github.com/checkstyle/checkstyle/blob/82589c1736430393bb3a04ebb575839952445c04/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L970-L977
-----
Test added
> Issue #13321: Kill mutation for SummaryJavaDocCheck-12

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTree1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTree2.java
Issue #13328: Kill mutation for OneStatementPerLineCheck
-------------
https://checkstyle.org/config_coding.html#OneStatementPerLine
-----------
https://github.com/checkstyle/checkstyle/blob/6324a9d693324eb755c2cdfdbd90c2300d3c7f02/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L174-L181
> Issue #13328: Kill mutation for OneStatementPerLineCheck

- src/site/resources/css/site.css
- src/site/resources/js/checkstyle.js
Resolves #13304 
This PR makes the menu stretch based on content width.
Some names are too large to fit in the navigation.
>  Issue #13304: Rendering issues with website 

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 4
https://checkstyle.org/config_coding.html#VariableDeclarationUsageDistance
https://github.com/checkstyle/checkstyle/blob/81448ea434cda883b748d3d2c77b2f58a8b22bbe/config/pitest-suppressions/pitest-coding-1-suppressions.xml#L102-L109
4) Explanation:-
My thinking is that instead of removing the condition, we can continue if the token is SEMI and set the result to true. Now this won't have any problem as other branches can alter the result in the subsequent iterations and result is by default true.
A single dangling ; would be EMPTY_STAT and not SEMI. Please run regression on this method.
5)  Regression 
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2e4b5ad_2023084207/reports/diff/index.html …
> Issue #13095: kill mutation for VariableDeclarationUsageDistanceCheck 4

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadoc1.java
Issue #13321: Kill mutation for SummaryJavaDocCheck-1
-----
-----
https://github.com/checkstyle/checkstyle/blob/3d8ed42ab60c0399550b3e7d54ca9dd767583101/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L858-L865
-----
The removal of trim will effect the programme it will increase the number of times in loop.
There are total 3 usage of the `containsForbiddenFragment`
1) In `validateUntaggedSummary` method at 
https://github.com/checkstyle/checkstyle/blob/6073cd4194af4e673a5805fcfc6a2cddb0e4547d/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java#L343-L345
Note:-  If this `condition` execute then violation thrown and violation message doesn't contains any relation with the …
> Issue #13321: Kill mutation for SummaryJavaDocCheck-1

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethod1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethod2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethod3.java
Issue #13321: Kill mutation for JavadocMethod-2
-----
https://checkstyle.org/checks/javadoc/javadocmethod.html#JavadocMethod
-----
https://github.com/checkstyle/checkstyle/blob/73ec12d6960f417c5f84c079773702724af7430a/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L102-L109
and 
https://github.com/checkstyle/checkstyle/blob/73ec12d6960f417c5f84c079773702724af7430a/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L138-L145
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/df2ff7a8f9969bb2c68d7251a97ffa8b/raw/6a4e81a624fa36483f23b0adcf1fc513ca6df350/JavadocMethod.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/test- …
> Issue #13321: Kill mutation for JavadocMethod-2

- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameBeginTree1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameBeginTree2.java
Issue #13321: Kill mutation for OuterTypeFile-2
-----
https://checkstyle.org/checks/misc/outertypefilename.html#OuterTypeFilename
-----
https://github.com/checkstyle/checkstyle/blob/20a52f70548476a4ca3bb0f56e4d8fcd9cd775b7/config/pitest-suppressions/pitest-misc-suppressions.xml#L84-L109
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/19becb64b46958e038d7cc25e7ee2653/raw/8a01e220b6dda4d1bca26cb1916437d230ab8fa4/out.xml
> Issue #13321: Kill mutation for OuterTypeFile-2

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityCheck.java
Issue #13328: Kill mutation for StringLiteralEqualityCheck
-------
Check :- 
https://checkstyle.org/config_coding.html#StringLiteralEquality
--------
https://github.com/checkstyle/checkstyle/blob/ca00dfad4c00df56eacc6174e379cdd8a2b38784/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L192-L199
------
Reomval of this will not make any issue
the ast https://github.com/checkstyle/checkstyle/blob/ca00dfad4c00df56eacc6174e379cdd8a2b38784/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java#L132
is always either `==` or `!=` 
so while entering in the while loop ast is never going to be null so it will alwyas execute.
know lets suppose we have code like 
```
if (s == "a") {}
```
so the ast look like 
```
|       |--LITERAL_IF -> if [14:8]
| …
```
> Issue #13328: Kill mutation for StringLiteralEqualityCheck

- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
Issue #13321: Kill mutation for NewLineAtEnd
-------
https://checkstyle.org/checks/misc/newlineatendoffile.html#NewlineAtEndOfFile
-------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L21-L37
--------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages.properties#L9
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages.properties#L22 
we are not showing any filepath
> Issue #13321: Kill mutation for NewLineAtEnd

- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/InputTodoCommentDefault.java
Issue #13321: Kill mutation for TODOCommentCheck-1
---------
https://checkstyle.org/checks/misc/todocomment.html#TodoComment
---------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L156-L172
---------
Test added
> Issue #13321: Kill mutation for TODOCommentCheck-1

- config/pitest-suppressions/pitest-misc-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
Issue #13321: Kill mutation for TranslationCheck-1
---------
https://checkstyle.org/checks/misc/translation.html#Translation
---------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L174-L190
---------
To Kill the mutation unmodifiableCollectionUtil I have used avoid call to for out class created to wrap that method in util by default avoidcall to is applied to https://pitest.org/quickstart/maven/#:~:text=If%20a%20list%20is%20not%20explicitly%20supplied%20then%20PIT%20will%20default%20to%20a%20list%20of%20common%20logging%20packages%20as%20follows 
so add log method to avoid the error at https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/src/main/java/com/pupp …
> Issue #13321: Kill mutation for TranslationCheck-1

- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder2.java
Issue #13321: Kill mutation for SuppressWarningHolderCheck-1
----------
https://checkstyle.org/checks/annotation/suppresswarningsholder.html#SuppressWarningsHolder
----------
https://github.com/checkstyle/checkstyle/blob/0169b0891563cd7e12d39aa42acc6e6b2cb0ee38/config/pitest-suppressions/pitest-misc-suppressions.xml#L93-L127
---------
Test added
> Issue #13321: Kill mutation for SuppressWarningHolderCheck-1

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
Issue #13321: Kill mutation for UncommentedMainCheck-3
---------
https://checkstyle.org/checks/misc/uncommentedmain.html
---------
https://github.com/checkstyle/checkstyle/blob/2be5780673b9ba5397526aadab981be68f874172/config/pitest-suppressions/pitest-misc-suppressions.xml#L201-L208
---------
In visitToken when Token is classDEF or RecordDef it call visitClassOrRecordDef where if classDepth == 0 then only currentClass will update know every time when new file come sequentially they alwyas have a class and that time the classDepth is always 0. and classdepth is reset to 0 in begintree. 
-------
------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/92e6545d9dda7c3febcd4ad8f8a91443/raw/5b88dc50b3b7828cca1bce0d4d6aa47209d25647/UMC.xml …
> Issue #13321: Kill mutation for UncommentedMainCheck-3

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XdocUtil.java
- src/xdocs/index.xml.vm
- src/xdocs/writingjavadocchecks.xml.vm
> Issue #13389: Extend `getXdocsFilePaths` to gather `.xml.vm` files

- src/xdocs/index.xml.vm
From https://github.com/checkstyle/checkstyle/actions/runs/5560007224/jobs/10156644820#step:4:2338:
```
0a1,2
> <td><i><a class="externalLink" href="https://stickler-ci.com/">https://stickler-ci.com/</a>: org.apache.commons.httpclient.ConnectTimeoutException : The host did not accept the connection within timeout of 6000 ms</i></td></tr>
> <td><i><a class="externalLink" href="https://stickler-ci.com/docs#java">https://stickler-ci.com/docs#java</a>: org.apache.commons.httpclient.ConnectTimeoutException : The host did not accept the connection within timeout of 6000 ms</i></td></tr>
```
Looks like stickler ci is not active anymore, I am removing it from "Active Tools" section. See …
> minor: remove stickler-ci from active tools

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
Issue #13321: Kill mutation for OrderedPropertiesCheck-1
---------
https://checkstyle.org/checks/misc/orderedproperties.html#OrderedProperties
-----------
https://github.com/checkstyle/checkstyle/blob/20a52f70548476a4ca3bb0f56e4d8fcd9cd775b7/config/pitest-suppressions/pitest-misc-suppressions.xml#L57-L82
----------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/c3213434af8523d918594b88ce5554f7/raw/3565cfcd975e228af515bb34ce22c83afce0a7c7/opc.xml
> Issue #13321: Kill mutation for OrderedPropertiesCheck-1

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleDefault4.java
Issue #13321: Kill mutation for TagParser
--------
https://github.com/checkstyle/checkstyle/blob/8b7dac5792b450386651647e2c8a5fa84e1d7f97/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L1026-L1042
---------
Test added
> Issue #13321: Kill mutation for TagParser

- .ci/run-link-check-plugin.sh
- .circleci/config.yml
We should only check for internal links in PRs.
Linkcheck run should pass in this PR even though we have a bad external link (stickler-ci) in master: https://circleci.com/gh/checkstyle/checkstyle/335960
Link to failure in master: https://github.com/checkstyle/checkstyle/actions/runs/5546064017/jobs/10125837894
----------------
Proof that `--check-external` works: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/19614/workflows/2475ba7b-ee8e-4d65-96b3-fbc06dd143ab/jobs/336405
Proof that default works (internal only): https://circleci.com/gh/checkstyle/checkstyle/336829
> Pull #13397: update link check to only check internal links in PRs

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/whitespace/index.html
> Issue #13421: Add since in javadoc of each property setter for whitespace checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/blocks/index.html
> Issue #13421: Add since in javadoc of each property setter for block checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/design/index.html
> Issue #13421: Add since in javadoc of each property setter for design checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/coding/index.html
> Issue #13421: Add since in javadoc of each property setter for coding checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/header/index.html
> Issue #13421: Add since in javadoc of each property setter for header checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/annotation/index.html
> Issue #13421: Add since in javadoc of each property setter for annotation checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/imports/index.html
> Issue #13421: Add since in javadoc of each property setter for imports checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/modifier/index.html
> Issue #13421: Add since in javadoc of each property setter for modifier checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/metrics/index.html
> Issue #13421: Add since in javadoc of each property setter for metrics checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/sizes/index.html
> Issue #13421: Add since in javadoc of each property setter for sizes checks

- src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java
---
Taken from https://checkstyle.sourceforge.io/filefilters/index.html
> Issue #13421: Add since in javadoc of each property setter for filefilters

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
---
Taken from https://checkstyle.sourceforge.io/checks/regexp/index.html
> Issue #13421: Add since in javadoc of each property setter for regexp checks

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java
---
Taken from https://checkstyle.sourceforge.io/filters/index.html
> Issue #13421: Add since in javadoc of each property setter for filters

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/AbstractExamplesModuleTestSupport.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckExamplesTest.java
Resolves #13484 
---
Adds new class `AbstractExamplesModuleTestSupport` and fixes the 14 tests with switched `getResourceLocation` and `getPackageLocation`
> Issue #13484: Fix package/resource location in example tests

- src/site/resources/css/site.css
- src/site/resources/js/anchors.js
Resolves #13205
---
Adds anchors to paragraphs that have an ID starting with `Example`. For now, this applies to `WhitespaceAfter`'s paragraphs because only they have such IDs. But as we transfer more xdocs to templates, others will get IDs too.
> Issue #13205: Add links to examples' paragraphs

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/UnmodifiableCollectionUtil.java
Issue #13321: Kill mutation for DetailAstImpl
--------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L66-L82
and 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L93-L109
Expanded unmodifiableCollectionUtil class
> Issue #13321: Kill mutation for DetailAstImpl

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
Issue #13328: Kill mutation for HiddenField
--------
https://checkstyle.org/checks/coding/hiddenfield.html#HiddenField
--------
https://github.com/checkstyle/checkstyle/blob/f4a33f90bf8eda8ef2cdf7f66fd60878d2aa1736/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L21-L28
--------
Tried various ways but no test cases were found. 
--------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/76d0b0f_2023195339/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/76d0b0f_2023170225/reports/diff/index.html
------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e922f9f79f4b5245caba9b44cd2d1f0d/raw/50a61d0d72c5a09bd74a383907fe0021d28f1763/hidden.xml …
> Issue #13328: Kill mutation for HiddenField

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderBeginTree.java
Issue #13328: Kill mutation ImportOrderCheck  
--------------
https://checkstyle.org/checks/imports/importorder.html#ImportOrder
------------
https://github.com/checkstyle/checkstyle/blob/b8915dab95432f57df7218f4f16ef7306e049e54/config/pitest-suppressions/pitest-imports-suppressions.xml#L57-L64
--------------
begin tree always reset data. for `lastImportStatic = false` so we need to create two input somehow lastImportStatic become true while the sequentially second file will be come in process and that is easy we only have to set last import of first file as true.
lets start from visitToken
In visit token the parameter `isStatic` will check wether the current import is static or not.
https://github.com/checkstyle/checkstyle/blob/b8915dab95432f57df7218f4f16ef7306e049e54/src/main/java/com/pu …
> Issue #13328: Kill mutation ImportOrderCheck  

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #13321: Kill mutation for DetailAstImpl-2
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L48-L64
--------
here the code in method to addPreviousSibiling is 
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L116-L135
in which line no 121 and 133 is mutated and the reasonto removal is same for both
here as per the condition `if (previousSibilingNode != null` it shows that we already have previousSibilingNode
lets suppose an example we have 2 node connected y and …
> Issue #13321: Kill mutation for DetailAstImpl-2

- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/ViolationMessagesMacro.java
As suggested in https://github.com/checkstyle/checkstyle/pull/13423#discussion_r1281289602
>  please restore copy pasta and add a comment about why we use treeset
In https://github.com/checkstyle/checkstyle/pull/13423#discussion_r1275385868 there is a thread about a chunk of code that is a direct copy of those two:
https://github.com/checkstyle/checkstyle/blob/ec5cd7e2ffd7c5c3a1b2cd4e28e4d3c37bb723fc/src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java#L211-L213
https://github.com/checkstyle/checkstyle/blob/0c2ab5338db569b4699d5d20121d1bd508394eb9/src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java#L1381-L1389
There was some uncertainty as to why `TreeSet` is used, but @rnveach explained that in …
> Pull #13505: Restore usage of TreeSet

- .travis.yml
https://app.travis-ci.com/github/checkstyle/checkstyle/builds/264912656
```
$ ./.ci/travis.sh init-m2-repo
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
The command "./.ci/travis.sh init-m2-repo" exited with 1.
0.02s$ ./.ci/travis.sh run-command "$CMD"
eval of CMD is starting
CMD=mvn -e --no-transfer-progress clean integration-test failsafe:verify -DargLine='-Xms1024m -Xmx2048m'
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this
```
support was contacted, no reply.
> infra: disable tavis until issue with JAVA_PATH is resolved

- .ci/validation.sh
Noticed at https://checkstyle.semaphoreci.com/jobs/b360caba-c32a-48f7-8405-eab7c233924c and elsewhere, nondex has become unstable for this test.
```
java.util.concurrent.ExecutionException: java.lang.Error: Error was thrown while processing /home/semaphore/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorNoStackoverflowError.java13:23
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)13:23
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)13:23
at com.puppycrawl.tools.checkstyle.internal.utils.TestUtil.getResultWithLimitedResources(TestUtil.java:258)13:23
at com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport.verifyWithLimitedResources(AbstractModuleTestSupport.java:3 …
```
> minor: avoid flaky test in nondex execution

- config/checkstyle-checks.xml
- config/checkstyle-non-main-files-suppressions.xml
- config/suppressions.xml
Required for https://github.com/checkstyle/checkstyle/issues/13498
---
Excludes regular `.xml` Xdoc files from line-length validation and adds templates `.xml.template` to line-length validation. The problem is that the parser escapes lots of characters(`"`, for example) and some lines inside code blocks become longer than 100 chars after generation.
---
Proof of suppression work: https://regexr.com/7hvad
> Pull #13499: Exclude xdocs from line length validation and validate templates instead

- src/xdocs/checks/annotation/annotationlocation.xml.template
- src/xdocs/checks/annotation/annotationonsameline.xml.template
- src/xdocs/checks/annotation/annotationusestyle.xml.template
- src/xdocs/checks/annotation/missingdeprecated.xml.template
- src/xdocs/checks/annotation/missingoverride.xml.template
- src/xdocs/checks/annotation/packageannotation.xml.template
- src/xdocs/checks/annotation/suppresswarnings.xml.template
- src/xdocs/checks/annotation/suppresswarningsholder.xml.template
Part of #13498
---
Copied the `annotation` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from annotation checks xdocs

- src/xdocs/checks/blocks/avoidnestedblocks.xml.template
- src/xdocs/checks/blocks/emptyblock.xml.template
- src/xdocs/checks/blocks/emptycatchblock.xml.template
- src/xdocs/checks/blocks/leftcurly.xml.template
- src/xdocs/checks/blocks/needbraces.xml.template
- src/xdocs/checks/blocks/rightcurly.xml.template
Part of #13498
---
Copied the `blocks` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from block checks xdocs

- src/xdocs/checks/imports/avoidstarimport.xml.template
- src/xdocs/checks/imports/avoidstaticimport.xml.template
- src/xdocs/checks/imports/customimportorder.xml.template
- src/xdocs/checks/imports/illegalimport.xml.template
- src/xdocs/checks/imports/importcontrol.xml.template
- src/xdocs/checks/imports/importorder.xml.template
- src/xdocs/checks/imports/redundantimport.xml.template
- src/xdocs/checks/imports/unusedimports.xml.template
Part of #13498
---
Copied the `imports` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from imports checks xdocs

- src/xdocs/checks/coding/arraytrailingcomma.xml.template
- src/xdocs/checks/coding/avoiddoublebraceinitialization.xml.template
- src/xdocs/checks/coding/avoidinlineconditionals.xml.template
- src/xdocs/checks/coding/avoidnoargumentsuperconstructorcall.xml.template
- src/xdocs/checks/coding/covariantequals.xml.template
- src/xdocs/checks/coding/declarationorder.xml.template
- src/xdocs/checks/coding/defaultcomeslast.xml.template
- src/xdocs/checks/coding/emptystatement.xml
- src/xdocs/checks/coding/emptystatement.xml.template
- src/xdocs/checks/coding/equalsavoidnull.xml.template
- src/xdocs/checks/coding/equalshashcode.xml.template
- src/xdocs/checks/coding/explicitinitialization.xml.template
- src/xdocs/checks/coding/fallthrough.xml.template
- src/xdocs/checks/coding/finallocalvariable.xml.template
- src/xdocs/checks/coding/hiddenfield.xml.template
- src/xdocs/checks/coding/illegalcatch.xml.template
- src/xdocs/checks/coding/illegalinstantiation.xml.template
- src/xdocs/checks/coding/illegalthrows.xml.template
- src/xdocs/checks/coding/illegaltoken.xml.template
- src/xdocs/checks/coding/illegaltokentext.xml.template
- src/xdocs/checks/coding/illegaltype.xml.template
Part of #13498
---
This is the first half of the coding checks. The category is very big so I split it in 2
Copied the `coding` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from coding-1 checks xdocs

- src/xdocs/checks/modifier/classmemberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/interfacememberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/modifierorder.xml.template
- src/xdocs/checks/modifier/redundantmodifier.xml.template
Part of #13498
---
Copied the `modifier` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from modifier checks xdocs

- src/xdocs/filefilters/beforeexecutionexclusionfilefilter.xml.template
Part of #13498
---
Copied the `filefilters` xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from filefilters xdocs

- src/xdocs/checks/header/header.xml.template
- src/xdocs/checks/header/regexpheader.xml.template
Part of #13498
---
Copied the `header` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from header checks xdocs

- src/xdocs/checks/javadoc/atclauseorder.xml.template
- src/xdocs/checks/javadoc/invalidjavadocposition.xml.template
- src/xdocs/checks/javadoc/javadocblocktaglocation.xml.template
- src/xdocs/checks/javadoc/javadoccontentlocation.xml.template
- src/xdocs/checks/javadoc/javadocmethod.xml.template
- src/xdocs/checks/javadoc/javadocmissingleadingasterisk.xml
- src/xdocs/checks/javadoc/javadocmissingleadingasterisk.xml.template
- src/xdocs/checks/javadoc/javadocmissingwhitespaceafterasterisk.xml.template
- src/xdocs/checks/javadoc/javadocpackage.xml.template
- src/xdocs/checks/javadoc/javadocparagraph.xml.template
- src/xdocs/checks/javadoc/javadocstyle.xml.template
- src/xdocs/checks/javadoc/javadoctagcontinuationindentation.xml
- src/xdocs/checks/javadoc/javadoctagcontinuationindentation.xml.template
- src/xdocs/checks/javadoc/javadoctype.xml.template
- src/xdocs/checks/javadoc/javadocvariable.xml.template
- src/xdocs/checks/javadoc/missingjavadocmethod.xml.template
- src/xdocs/checks/javadoc/missingjavadocpackage.xml.template
- src/xdocs/checks/javadoc/missingjavadoctype.xml.template
- src/xdocs/checks/javadoc/nonemptyatclausedescription.xml.template
- src/xdocs/checks/javadoc/requireemptylinebeforeblocktaggroup.xml
- src/xdocs/checks/javadoc/requireemptylinebeforeblocktaggroup.xml.template
- src/xdocs/checks/javadoc/singlelinejavadoc.xml.template
- src/xdocs/checks/javadoc/summaryjavadoc.xml.template
- src/xdocs/checks/javadoc/writetag.xml.template
Part of #13498
---
Copied the `javadoc` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from javadoc checks xdocs

- src/xdocs/checks/naming/abbreviationaswordinname.xml.template
- src/xdocs/checks/naming/abstractclassname.xml.template
- src/xdocs/checks/naming/catchparametername.xml.template
- src/xdocs/checks/naming/classtypeparametername.xml
- src/xdocs/checks/naming/classtypeparametername.xml.template
- src/xdocs/checks/naming/constantname.xml.template
- src/xdocs/checks/naming/illegalidentifiername.xml.template
- src/xdocs/checks/naming/interfacetypeparametername.xml
- src/xdocs/checks/naming/interfacetypeparametername.xml.template
- src/xdocs/checks/naming/lambdaparametername.xml
- src/xdocs/checks/naming/lambdaparametername.xml.template
- src/xdocs/checks/naming/localfinalvariablename.xml.template
- src/xdocs/checks/naming/localvariablename.xml.template
- src/xdocs/checks/naming/membername.xml
- src/xdocs/checks/naming/membername.xml.template
- src/xdocs/checks/naming/methodname.xml.template
- src/xdocs/checks/naming/methodtypeparametername.xml.template
- src/xdocs/checks/naming/packagename.xml.template
- src/xdocs/checks/naming/parametername.xml.template
- src/xdocs/checks/naming/patternvariablename.xml
- src/xdocs/checks/naming/patternvariablename.xml.template
- src/xdocs/checks/naming/recordcomponentname.xml.template
- src/xdocs/checks/naming/recordtypeparametername.xml
- src/xdocs/checks/naming/recordtypeparametername.xml.template
- src/xdocs/checks/naming/staticvariablename.xml.template
- src/xdocs/checks/naming/typename.xml
- src/xdocs/checks/naming/typename.xml.template
Part of #13498
---
Copied the `naming` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from naming checks xdocs

- src/xdocs/checks/sizes/anoninnerlength.xml
- src/xdocs/checks/sizes/anoninnerlength.xml.template
- src/xdocs/checks/sizes/executablestatementcount.xml.template
- src/xdocs/checks/sizes/filelength.xml
- src/xdocs/checks/sizes/filelength.xml.template
- src/xdocs/checks/sizes/lambdabodylength.xml.template
- src/xdocs/checks/sizes/linelength.xml.template
- src/xdocs/checks/sizes/methodcount.xml.template
- src/xdocs/checks/sizes/methodlength.xml.template
- src/xdocs/checks/sizes/outertypenumber.xml.template
- src/xdocs/checks/sizes/parameternumber.xml.template
- src/xdocs/checks/sizes/recordcomponentnumber.xml.template
Part of #13498
---
Copied the `sizes` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from sizes checks xdocs

- src/xdocs/checks/metrics/booleanexpressioncomplexity.xml.template
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml.template
- src/xdocs/checks/metrics/classfanoutcomplexity.xml.template
- src/xdocs/checks/metrics/cyclomaticcomplexity.xml.template
- src/xdocs/checks/metrics/javancss.xml.template
- src/xdocs/checks/metrics/npathcomplexity.xml.template
Part of #13498
---
Copied the `metrics` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from metrics checks xdocs

- src/xdocs/checks/regexp/regexp.xml.template
- src/xdocs/checks/regexp/regexpmultiline.xml.template
- src/xdocs/checks/regexp/regexponfilename.xml.template
- src/xdocs/checks/regexp/regexpsingleline.xml.template
- src/xdocs/checks/regexp/regexpsinglelinejava.xml.template
Part of #13498
---
Copied the `regexp` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from regexp checks xdocs

- src/xdocs/checks/whitespace/emptyforinitializerpad.xml.template
- src/xdocs/checks/whitespace/emptyforiteratorpad.xml
- src/xdocs/checks/whitespace/emptyforiteratorpad.xml.template
- src/xdocs/checks/whitespace/emptylineseparator.xml.template
- src/xdocs/checks/whitespace/filetabcharacter.xml.template
- src/xdocs/checks/whitespace/genericwhitespace.xml.template
- src/xdocs/checks/whitespace/methodparampad.xml.template
- src/xdocs/checks/whitespace/nolinewrap.xml.template
- src/xdocs/checks/whitespace/nowhitespaceafter.xml.template
- src/xdocs/checks/whitespace/nowhitespacebefore.xml.template
- src/xdocs/checks/whitespace/nowhitespacebeforecasedefaultcolon.xml.template
- src/xdocs/checks/whitespace/operatorwrap.xml.template
- src/xdocs/checks/whitespace/parenpad.xml.template
- src/xdocs/checks/whitespace/separatorwrap.xml.template
- src/xdocs/checks/whitespace/singlespaceseparator.xml.template
- src/xdocs/checks/whitespace/typecastparenpad.xml
- src/xdocs/checks/whitespace/typecastparenpad.xml.template
- src/xdocs/checks/whitespace/whitespacearound.xml.template
Part of #13498
---
Copied the `whitespace` checks xdocs and named them as `xx.xml.template`.
> Issue #13498: Create templates from whitespace checks xdocs

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
Issue #13501: Kill mutation for UnusedLocalVariableCheck 9  
------
https://checkstyle.org/checks/coding/unusedlocalvariable.html#UnusedLocalVariable
--------
https://github.com/checkstyle/checkstyle/blob/554a87ea9b5ae27f9519e8dbca15a116bcc108a4/config/pitest-suppressions/pitest-coding-2-suppressions.xml#L66-L73
-----------
TokenUtil.isTypeDeclaration check if the ast is of type 
class, enum, record or interface.
know in this all type of the last child is alwyas objBlock token. so the parent of SList never going to be 
from isTypeDeclaration so either of checking currentASt Parent if the loops run 1 time more and currentast would be change then ultimately in 
`result = currentAst.getType() == TokenTypes.SLIST;` it will make affect but result will not change.
----------
Report-1 ; …
> Issue #13501: Kill mutation for UnusedLocalVariableCheck 9  

- config/pitest-suppressions/pitest-misc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/orderedproperties/InputOrderedProperties2.properties
Issue #13321: Kill mutation for OrderedPropertiesCheck-2
---------
https://checkstyle.org/checks/misc/orderedproperties.html#OrderedProperties
-----------
https://github.com/checkstyle/checkstyle/blob/20a52f70548476a4ca3bb0f56e4d8fcd9cd775b7/config/pitest-suppressions/pitest-misc-suppressions.xml#L39-L55
----------
Test added
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/c3213434af8523d918594b88ce5554f7/raw/3565cfcd975e228af515bb34ce22c83afce0a7c7/opc.xml
> Issue #13321: Kill mutation for OrderedPropertiesCheck-2

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-regexp-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic10.java
Issue #13321: Kill mutation for DetectorOption
-----
https://github.com/checkstyle/checkstyle/blob/2335abaea101774a23d0bdaf55f19e4f0cad0d37/config/pitest-suppressions/pitest-regexp-suppressions.xml#L3-L10
-----
It is some inner class, and all fields already not initialized, so with such update we do implementation consistent.
All the time whenever we use this message field in check we use the build method and the build method is 
https://github.com/checkstyle/checkstyle/blob/2335abaea101774a23d0bdaf55f19e4f0cad0d37/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java#L246-L250
message is set like `message = Optional.ofNullable(message).orElse("");` so if the message is null then it will be `""` empty string so removal will not make issue
-----
-----
Diff …
> Issue #13321: Kill mutation for DetectorOption

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
Issue #13501: Kill mutation for CommonUtil-2
------
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L246-L262
------
This method is used in https://github.com/checkstyle/checkstyle/blob/f9df51921515e7ee48f2a0fc3bd35a4c36ad2ed0/src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java#L173-L175
This method is used to set the property excludedPackages lets suppose if it is set empty then in filter commonUtil.isName never be call so the string never be empty it always true
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/ccd588c72cd541ff98736f08dc687e43/raw/28c14aa0fdf848a5191761ffe4cbbea8c860a0a9/gist.xml …
> Issue #13501: Kill mutation for CommonUtil-2

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocation.java
Issue #13501: Kill mutation for JavadocContentLocationCheck
-------
https://checkstyle.org/checks/javadoc/javadoccontentlocation.html#JavadocContentLocation
--------
https://github.com/checkstyle/checkstyle/blob/7e879f3eedd9302623a6b2ac383b22af1cbe99f0/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L84-L91
--------
https://github.com/checkstyle/checkstyle/blob/7e879f3eedd9302623a6b2ac383b22af1cbe99f0/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java#L170
This line of code is mutated as 
`private JavadocContentLocationOption location;`
know this changes will not affect the check functionality becuase the current logic here in visitToken 
https://github.com/checkstyle/checkstyle/blob/7e879f3eedd9302623a6b2ac383b22af1cbe99f0/src/main/jav …
> Issue #13501: Kill mutation for JavadocContentLocationCheck

- config/pitest-suppressions/pitest-utils-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
Issue #13321: Kill mutation for CheckUtil-7
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#PARAMETER_DEF
AST:
```
|--PARAMETERS -> PARAMETERS
|   |--PARAMETER_DEF -> PARAMETER_DEF
|   |   |--MODIFIERS -> MODIFIERS
|   |   |--TYPE -> TYPE
|   |   |   `--LITERAL_INT -> int
|   |   `--IDENT -> firstParameter
```
-----
https://github.com/checkstyle/checkstyle/blob/f4a33f90bf8eda8ef2cdf7f66fd60878d2aa1736/config/pitest-suppressions/pitest-utils-suppressions.xml#L120-L127
-----
https://github.com/checkstyle/checkstyle/blob/a174e6e47fdc1e6e11f7c5a9688a481a5274df6c/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java#L388-L391
when `this` is reciever parameter https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.1 …
> Issue #13321: Kill mutation for CheckUtil-7

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethod1.java
Issue #13501: Kill mutation for MissingJavadocMethodCheck
----------
https://checkstyle.org/checks/javadoc/missingjavadocmethod.html#MissingJavadocMethod
-----
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L651-L658
-----
Test added
> Issue #13501: Kill mutation for MissingJavadocMethodCheck

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocType4.java
Issue #13501: Kill mutation for JavadocTypeCheck2
----
https://checkstyle.org/checks/javadoc/javadoctype.html#JavadocType
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L597-L613
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e591a1cf82070108242c5569a7236a01/raw/9b17bf12fa20506af727bb7cae5c18b5b6dfe4ec/JavadocTypeCheck.xml
> Issue #13501: Kill mutation for JavadocTypeCheck2

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentation1.java
Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck
----
https://checkstyle.org/checks/javadoc/javadoctagcontinuationindentation.html#JavadocTagContinuationIndentation
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L507-L514
-----
Test added
> Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck2.java
Issue #13501: Kill mutation for JavadocStyleCheck1
----
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L390-L406
-----
Test added
> Issue #13501: Kill mutation for JavadocStyleCheck1

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck2.java
Issue #13501: Kill mutation for JavadocStyleCheck4
----
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L381-L388
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0b07ecc7d3ca0ca403454d504707156d/raw/8c76ea8db01b4bcb565d1af9301130f7c67c3c1d/JavadocStyleCheck.xml
> Issue #13501: Kill mutation for JavadocStyleCheck4

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck2.java
Issue #13501: Kill mutation for JavadocStyleCheck5
----
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L372-L379
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0b07ecc7d3ca0ca403454d504707156d/raw/8c76ea8db01b4bcb565d1af9301130f7c67c3c1d/JavadocStyleCheck.xml
> Issue #13501: Kill mutation for JavadocStyleCheck5

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/intellij-idea-inspections.xml
- config/jsoref-spellchecker/whitelist.words
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
Issue #13321: Kill mutation for CheckUtil-2
-----
https://github.com/checkstyle/checkstyle/blob/f4a33f90bf8eda8ef2cdf7f66fd60878d2aa1736/config/pitest-suppressions/pitest-utils-suppressions.xml#L165-L172
-----
0 will not make any issue while converting octal to decimal
-----
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6e8fbb4_2023210658/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7e63cf9_2023061818/reports/diff/index.html
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/22c763808f0888ecec916bbd916d9893/raw/1e441345ad27f5e0e07214cfd84b8c7c9d8f3d84/parseDouble.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7 …
> Issue #13321: Kill mutation for CheckUtil-2

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationCheck1.java
Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck2
----
https://checkstyle.org/checks/javadoc/javadoctagcontinuationindentation.html#JavadocTagContinuationIndentation
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L516-L541
-----
loop run 1 time more
---------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b09decb_2023223713/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6e50bb5_2023174529/reports/diff/index.html
--------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/ec7b8b74e9e64a8a9f9c0014860b2016/raw/e392cb5c586eacde87601e6ef62098f95b8eba8f/JavadocTagContinuationInd …
> Issue #13501: Kill mutation for JavadocTagContinuationIndentationCheck2

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocType3.java
Issue #13501: Kill mutation for JavadocTypeCheck3
----
https://checkstyle.org/checks/javadoc/javadoctype.html#JavadocType
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L579-L586
We filter only params at https://github.com/checkstyle/checkstyle/blob/0fa8d8b3e951ddee26785a2af50c7ff7c159f7c3/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java#L619 so it is double check, not required.
-----
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6d4c16b_2023215123/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6d4c16b_2023234000/reports/diff/index.html
----- …
> Issue #13501: Kill mutation for JavadocTypeCheck3

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck2.java
Issue #13501: Kill mutation for JavadocStyleCheck7
----
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L420-L451
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0b07ecc7d3ca0ca403454d504707156d/raw/8c76ea8db01b4bcb565d1af9301130f7c67c3c1d/JavadocStyleCheck.xml
> Issue #13501: Kill mutation for JavadocStyleCheck7

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck3.java
Issue #13501: Kill mutation for JavadocStyleCheck6
----
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L408-L415
-----
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0b07ecc7d3ca0ca403454d504707156d/raw/8c76ea8db01b4bcb565d1af9301130f7c67c3c1d/JavadocStyleCheck.xml
> Issue #13501: Kill mutation for JavadocStyleCheck6

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil9.java
Issue #13501: Kill mutation for CheckUtil8
-----
https://github.com/checkstyle/checkstyle/blob/79e760900c400c0ebac121a67517235529012eb3/config/pitest-suppressions/pitest-utils-suppressions.xml#L102-L118
-----
**Usage**
MissingJavadocMethodCheck :- https://checkstyle.org/checks/javadoc/missingjavadocmethod.html#MissingJavadocMethod
https://github.com/checkstyle/checkstyle/blob/79e760900c400c0ebac121a67517235529012eb3/src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java#L354-L357
the condition `slist.getChildCount() == GETTER_BODY_SIZE` replace this with true as a suggestion of pit.
know the `getterMethod = expr.getType() == TokenTypes.LITERAL_RETURN;` this is only possible when the child count is 2.
becuase expr here is
`final DetailAST expr = slist.getFirstChild();` 
example …
> Issue #13501: Kill mutation for CheckUtil8

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCheck1.java
Issue #13501: Kill mutation for JavadocParagraph2
----
https://checkstyle.org/checks/javadoc/javadocparagraph.html#JavadocParagraph
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L327-L361
-----
Test added
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/131e059942a4ef61d37aef621fe27777/raw/eb52f0fe0b9810e3fe6192ece69350da2ca40115/JavadocParagraph.xml
> Issue #13501: Kill mutation for JavadocParagraph2

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
Issue #13501: Kill mutation for JavadocParagraph
----
https://checkstyle.org/checks/javadoc/javadocparagraph.html#JavadocParagraph
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L372-L379
-----
Regression will find nothing. 
loops run 1 time more. our node always be newline. so always while will execute and value will update which is done at `        DetailNode tag = JavadocUtil.getNextSibling(node);
`
-----
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/131e059942a4ef61d37aef621fe27777/raw/eb52f0fe0b9810e3fe6192ece69350da2ca40115/JavadocParagraph.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005 …
> Issue #13501: Kill mutation for JavadocParagraph1

- src/xdocs/checks/header/header.xml.template
- src/xdocs/checks/header/regexpheader.xml.template
> Issue #13610: Use parent module macro in headers templates

- src/xdocs/checks/metrics/booleanexpressioncomplexity.xml.template
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml.template
- src/xdocs/checks/metrics/classfanoutcomplexity.xml.template
- src/xdocs/checks/metrics/cyclomaticcomplexity.xml.template
- src/xdocs/checks/metrics/javancss.xml.template
- src/xdocs/checks/metrics/npathcomplexity.xml.template
> Issue #13610: Use parent module macro in metrics templates

- src/xdocs/checks/modifier/classmemberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/interfacememberimpliedmodifier.xml.template
- src/xdocs/checks/modifier/modifierorder.xml.template
- src/xdocs/checks/modifier/redundantmodifier.xml.template
> Issue #13610: Use parent module macro in modifiers templates

- src/xdocs/checks/regexp/regexp.xml.template
- src/xdocs/checks/regexp/regexpmultiline.xml.template
- src/xdocs/checks/regexp/regexponfilename.xml.template
- src/xdocs/checks/regexp/regexpsingleline.xml.template
- src/xdocs/checks/regexp/regexpsinglelinejava.xml.template
> Issue #13610: Use parent module macro in regexp templates

- src/xdocs/checks/sizes/anoninnerlength.xml.template
- src/xdocs/checks/sizes/executablestatementcount.xml.template
- src/xdocs/checks/sizes/filelength.xml.template
- src/xdocs/checks/sizes/lambdabodylength.xml.template
- src/xdocs/checks/sizes/linelength.xml.template
- src/xdocs/checks/sizes/methodcount.xml.template
- src/xdocs/checks/sizes/methodlength.xml.template
- src/xdocs/checks/sizes/outertypenumber.xml.template
- src/xdocs/checks/sizes/parameternumber.xml.template
- src/xdocs/checks/sizes/recordcomponentnumber.xml.template
> Issue #13610: Use parent module macro in sizes templates

- src/xdocs/checks/whitespace/emptyforinitializerpad.xml.template
- src/xdocs/checks/whitespace/emptyforiteratorpad.xml.template
- src/xdocs/checks/whitespace/emptylineseparator.xml.template
- src/xdocs/checks/whitespace/filetabcharacter.xml.template
- src/xdocs/checks/whitespace/genericwhitespace.xml.template
- src/xdocs/checks/whitespace/methodparampad.xml.template
- src/xdocs/checks/whitespace/nolinewrap.xml.template
- src/xdocs/checks/whitespace/nowhitespaceafter.xml.template
- src/xdocs/checks/whitespace/nowhitespacebefore.xml.template
- src/xdocs/checks/whitespace/nowhitespacebeforecasedefaultcolon.xml.template
- src/xdocs/checks/whitespace/operatorwrap.xml.template
- src/xdocs/checks/whitespace/parenpad.xml.template
- src/xdocs/checks/whitespace/separatorwrap.xml.template
- src/xdocs/checks/whitespace/singlespaceseparator.xml.template
- src/xdocs/checks/whitespace/typecastparenpad.xml.template
- src/xdocs/checks/whitespace/whitespacearound.xml.template
> Issue #13610: Use parent module macro in whitespace templates

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleCheck5.java
Issue #13501: Kill mutation for JavadocStyleCheck2
----
-------
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L372-L379
-----
Trim is not required becuase we are trimming at https://github.com/checkstyle/checkstyle/blob/17ace5521807a9696bd03b96ddd5e998745737b5/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L509
-----
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d3e54b4_2023204347/reports/diff/index.html
-----
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0b07ecc7d3ca0ca403454d504707156d/raw/8c76ea8db01b4bcb565d1af9301130f7c67c3c1d/Javado …
> Issue #13501: Kill mutation for JavadocStyleCheck2

- src/main/java/com/puppycrawl/tools/checkstyle/site/ParentModuleMacro.java
Noticed in https://github.com/checkstyle/checkstyle/pull/13653
Enforces forward slashes in relative links to the parent module. Links to the parent module are generated by the `ParentModuleMacro` which constructs the link based on the location of the current Xdoc file and `src/xdocs/config.xml`. When that link is constructed, the system delimiter is used. On Ubuntu(`/`) that worked fine but on Windows the pathing delimiter is `\`.
> Pull #13656: Ensure only forward slashes are in relative link to parent module

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
Issue #13501: Kill mutation for CommonUtil
-------
https://github.com/Kevin222004/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/config/pitest-suppressions/pitest-utils-suppressions.xml#L228-L235
-----
Regression will find nothing.
Reason 
```
public static String baseClassName(String type) {
final String className;
final int index = type.lastIndexOf('.');
if (index == -1) {
className = type;
}
else {
className = type.substring(index + 1);
}
return className;
}
```
lets suppose if type means the name of class is only `SomeClassName` here index will become -1. know 
if we remove the if condition then in else className is equal to `type.substring(index+1)` it means starting point of substring is 0 and index also start from 0. and in if condition className = type. so both are doing …
> Issue #13501: Kill mutation for CommonUtil

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserHiddenComments4.java
Issue #13501: Kill mutation for JavaParser
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L93-L100
------------
Test added
> Issue #13501: Kill mutation for JavaParser

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #13501: Kill mutation for DetailAstImpl-7
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L66-L73
------------
Test added
> Issue #13501: Kill mutation for DetailAstImpl-7

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #13501: Kill mutation for DetailAstImpl-6
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L75-L91
------------
Test added
> Issue #13501: Kill mutation for DetailAstImpl-6

- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughLastLineCommentCheck.java
Resolves https://github.com/checkstyle/checkstyle/issues/12948
partial for Issue #11166: remove getFileContent() usage from FallThroughCheck
--------------------
final report :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b242e7a_2023192425/reports/diff/index.html
final report 2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b242e7a_2023213303/reports/diff/index.html
-----------------------------------------------------------------------------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/ebc8a446892fe0a9aaf746b1b1b43c05/raw/4e77df9181e2cbd8dd9e227169310190e2eb8f5b/fall.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/9600f179b602d4c971bdb0a050099005/raw/360a95ed7bb60d7a0956e531199d484c4d6f6617/test-projects …
> Issue #11166: remove getFileContent() usage from FallThroughCheck

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java
Issue #13501: Kill mutation for CodePointUtil
Mutation introduction at https://github.com/checkstyle/checkstyle/commit/b8628532f12f46ab18e61372a997a4ca73e33d2a
@nrmancuso  is mandatory reviewer, as we allowed this code in PR year ago.
------
https://github.com/checkstyle/checkstyle/blob/bb64c20cbcf6e543b297b6e809f379bd8746b5e7/config/pitest-suppressions/pitest-utils-suppressions.xml#L174-L226
-----
Both the method 
https://github.com/checkstyle/checkstyle/blob/79e760900c400c0ebac121a67517235529012eb3/src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java#L64-L70
and
https://github.com/checkstyle/checkstyle/blob/79e760900c400c0ebac121a67517235529012eb3/src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java#L78-L86
are same only logic has written differently. …
> Issue #13501: Kill mutation for CodePointUtil

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
Issue #13501: Kill mutation for DetailAstImpl-5
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L3-L10
------------
https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L50
This line is mutated. 
The reason of removal is whenever any node is created and set it as parent, child, nextSibling, previousSibling. every time the method is called https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/De …
> Issue #13501: Kill mutation for DetailAstImpl-5

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
Issue #13501: Kill mutation for JavaParser2
https://github.com/Kevin222004/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
-------
https://github.com/checkstyle/checkstyle/blob/7007bef1f43a621757ae0b885818cf8baa0e6ef1/config/pitest-suppressions/pitest-common-2-suppressions.xml#L102-L109
------------
https://github.com/Kevin222004/checkstyle/blob/7007bef1f43a621757ae0b885818cf8baa0e6ef1/src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java#L140
The code is mutated as to remove `file.getAbsoluteFile()` --> `file` getAbsoluteFile this method will give the absolute path of file.
As per my research, the file from the parameter is already an absolute file path. I also don't think that test case is even possible because if we provide only filename …
> Issue #13501: Kill mutation for JavaParser2

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/AnnotationUseStyleCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/annotation/annotationusestyle.xml
- src/xdocs/checks/annotation/annotationusestyle.xml.template
Resolves #13666 
- Adds extra check in `XdocsPagesTest` to assert that the properties are ordered alphabetically with `javadocTokens` and `tokens` being last
- Adds a suppression list of all modules whose properties are not ordered
- Orders the properties of `AnnotationUseStyle`
> Issue #13666: Assert that properties are ordered alphabetically in xdoc

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/AnnotationLocationCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/annotation/annotationlocation.xml
- src/xdocs/checks/annotation/annotationlocation.xml.template
Part of #13668
Orders properties in annotation checks alphabetically - `AnnotationLocationCheck`
> Issue #13668: Order properties alphabetically in annotation checks

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodAnnotationField.java
Issue #13501: Kill mutation for MissingJavadocMethodCheck2
----------
https://checkstyle.org/checks/javadoc/missingjavadocmethod.html#MissingJavadocMethod
-----
https://github.com/checkstyle/checkstyle/blob/d2c985ecdb5deb34ce5e535034060826d2f9bff4/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L660-L694
-----
https://github.com/checkstyle/checkstyle/blob/d832cae442e754f6d76729ff4794cb6c6302a971/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java#L432-L438
In this all the `ast.getType == .. ` are use less because they are the only tokens which is accepted so any token is going to be one of them because this method is called by https://github.com/checkstyle/checkstyle/blob/d832cae442e754f6d76729ff4794cb6c6302a971/src/main/java/com/puppycraw …
> Issue #13501: Kill mutation for MissingJavadocMethodCheck2

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceEndsTheLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceInnerClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceList.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceMethodRef1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceWithEmoji.java
Part of https://github.com/checkstyle/checkstyle/issues/13213
Link to check documentation: https://checkstyle.org/checks/whitespace/genericwhitespace.html
```
➜  checkstyle git:(master) grep genericwhitespace config/checkstyle-input-suppressions.xml
files="checks[\\/]whitespace[\\/]genericwhitespace[\\/]InputGenericWhitespaceEndsTheLine.java"/>
files="checks[\\/]whitespace[\\/]genericwhitespace[\\/]InputGenericWhitespaceInnerClass.java"/>
files="checks[\\/]whitespace[\\/]genericwhitespace[\\/]InputGenericWhitespaceList.java"/>
files="checks[\\/]whitespace[\\/]genericwhitespace[\\/]InputGenericWhitespaceMethodRef1.java"/>
files="checks[\\/]whitespace[\\/]genericwhitespace[\\/]InputGenericWhitespaceWithEmoji.java"/>
➜  checkstyle git:(master) echo $? …
```
> Issue #13213: Remove '//ok' comments from Input files (InputGenericWhitespace)

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/ClassAndPropertiesSettersJavadocScraper.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/checks/coding/matchxpath.xml.template
Resolves #13680 
---
- Simplifies `isSetterMethod()` to only check if the method name starts with `set`
- Ensures that we do not get `NullPointerException` if a Javadoc is missing but a better message
> Issue #13680: Simplify requirement for what we consider a setter method in ClassAndPropertiesSettersJavadocScraper

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleNestedGenerics.java
part of #13213 
Link to check documentation : [Click Here](https://checkstyle.sourceforge.io/checks/misc/arraytypestyle.html#ArrayTypeStyle)
proof that all supressions for this check are removed : 
```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep arraytypestyle config/checkstyle-input-suppressions.xml
files="checks[\\/]arraytypestyle[\\/]InputArrayTypeStyleNestedGenerics.java"/>
files="checks[\\/]arraytypestyle[\\/]InputArrayTypeStyleNestedGenerics.java"/>
files="checks[\\/]arraytypestyle[\\/]InputArrayTypeStyleNestedGenerics.java"/>
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ git checkout issue-13213-arraytypestyle
Switched to branch 'issue-13213-arraytypestyle'
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-arraytypestyle)
$ grep arraytypestyle …
```
> Issue #13213: Remove '//ok' comments from arraytypestyle package

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportNestedClass.java
part of https://github.com/checkstyle/checkstyle/issues/13213
link to check documentation: https://checkstyle.org/checks/imports/avoidstaticimport.html
```
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'avoidstaticimport'
<suppress id="UnnecessaryOkComment"
files="checks[\\/]imports[\\/]avoidstaticimport[\\/]InputAvoidStaticImportNestedClass.java"/>
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'avoidstaticimport'| sed '/^--$/d' | grep -c 'UnnecessaryOkComment'
1
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'avoidstaticimport'
% grep -A 1 'UnnecessaryOkComment' checkstyle-input-suppressions.xml | grep -B 1 'avoidstaticimport'| sed '/^--$/d' | grep -c 'UnnecessaryOkComment'
0
```
> Issue #13213: Remove '//ok' comments from Input files (AvoidStaticImport)

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #13501: Kill mutation for DetailAstImpl-4
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L12-L28
------------
https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L169 
This line is mutated. 
The similar reason https://github.com/checkstyle/checkstyle/pull/13391 and https://github.com/checkstyle/checkstyle/pull/13390#issue-1800473514
https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/ …
> Issue #13501: Kill mutation for DetailAstImpl-4

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/ExplicitInitializationCheck.xml
- src/xdocs/checks/coding/equalsavoidnull.xml
- src/xdocs/checks/coding/equalsavoidnull.xml.template
- src/xdocs/checks/coding/explicitinitialization.xml
- src/xdocs/checks/coding/explicitinitialization.xml.template
- src/xdocs/checks/coding/fallthrough.xml
- src/xdocs/checks/coding/fallthrough.xml.template
Issue #13693
FinalLocalVariable i not possible to migrate until we fix ordering in junit:
```
ailures: 
[ERROR]   XdocsPagesTest.testAllCheckSections:650->validateCheckSection:733->validatePropertySection:875
->validatePropertySectionPropertiesOrder:922 finallocalvariable.xml 
section 'FinalLocalVariable' should have properties in the requested order
contents match, but order was wrong
expected: [validateEnhancedForLoopVariable, tokens]
but was : [tokens, validateEnhancedForLoopVariable]
[INFO] 
```
> Issue #13693: use property macros in few coding modules

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheck.java
Issue #13672: Kill mutation for JavadocMissingLeadingAsteriskCheck
---------
https://checkstyle.org/checks/javadoc/javadocmissingleadingasterisk.html
----------
https://github.com/checkstyle/checkstyle/blob/08814f209de43368cf9078a56e9175bf1f91f7a9/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L264-L271
-----------
I have tried various ways but whenever the asterisk is missing means the line is blank then that token is always a JavadocTokenTypes.TEXT
----------
Report-1 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/aaa4542_2023215322/reports/diff/index.html
Report-2 :- https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/aaa4542_2023082849/reports/diff/index.html
------------ …
> Issue #13672: Kill mutation for JavadocMissingLeadingAsteriskCheck

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInheritDoc.java
Issue #13672: Kill mutation for SummaryJavaDocCheck-11
-----
-----
https://github.com/checkstyle/checkstyle/blob/3d8ed42ab60c0399550b3e7d54ca9dd767583101/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L912-L919
-----
The mutation is `for (int i = 0; !found; i++) {` to change !found == true which has been into for each loop and after making this changes The coverage of code will be missing as https://github.com/checkstyle/checkstyle/pull/13329#issuecomment-1616684730 looks like https://github.com/checkstyle/checkstyle/pull/13329#discussion_r1288190352. 
basically the extra code that has been changed is for the pattern like 
```
/** <h1> Some header </h1> {@inheritDoc} {@code bar1} text*/
void bar2() {}
``` …
> Issue #13672: Kill mutation for SummaryJavaDocCheck-11

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #13672: Kill mutation for DetailAstImpl-3
-------
https://github.com/checkstyle/checkstyle/blob/88486f7ca9795f613d28fa6c2a53beccef521dfc/config/pitest-suppressions/pitest-common-2-suppressions.xml#L30-L46
------------
To add Next sibiling. The code is 
https://github.com/checkstyle/checkstyle/blob/0dba32b6c8c29977d74af675078501fa8052c10f/src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java#L140-L156
Line 150 and 153 is mutated 
This explaination is almost similar to https://github.com/checkstyle/checkstyle/pull/13390#issue-1800473514
lets suppose `if (sibling != null) {` if this statment execute then 
`astImpl.setNextSibling(sibling);` while calling …
> Issue #13672: Kill mutation for DetailAstImpl-3

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck3.java
part of #13213 
Link to check the documentation : [ClickHere](https://checkstyle.sourceforge.io/checks/annotation/annotationonsameline.html#AnnotationOnSameLine)
Proof that all suppressions have removed : 
```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep annotationonsameline config/checkstyle-input-suppressions.xml
files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineRecordsAndCompactCtors.java"/>
files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck.java"/>
files="checks[\\/]annotation[\\/]annotationonsameline[\\/]InputAnnotationOnSameLineCheck.java"/> …
```
> Issue #13213: Remove '//ok' comments from annotationonsameline

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedGood.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedSingleComment.java
part of #13213 
Link to check documentation : [ClickHere](https://checkstyle.sourceforge.io/checks/annotation/missingdeprecated.html#MissingDeprecated)
```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep missingdeprecated config/checkstyle-input-suppressions.xml
files="checks[\\/]annotation[\\/]missingdeprecated[\\/]InputMissingDeprecatedGood.java"/>
files="checks[\\/]annotation[\\/]missingdeprecated[\\/]InputMissingDeprecatedSingleComment.java"/>
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ git checkout issue-13213-missingdeprecated
Switched to branch 'issue-13213-missingdeprecated'
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (issue-13213-missingdeprecated)
$ grep missingdeprecated config/checkstyle-input-suppressions.xml
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle …
```
> Issue #13213: Remove '//ok' comments from missingdeprecated

- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder6.java
Issue #13501: Kill mutation for ImportOrderCheck-2
---------
Check : 
https://checkstyle.org/config_imports.html#ImportOrder
https://checkstyle.org/checks/imports/importorder.html#ImportOrder
----------
https://github.com/checkstyle/checkstyle/blob/58fdccf566a46b2ad4eea3987be3157d323bb3a8/config/pitest-suppressions/pitest-imports-suppressions.xml#L57-L73
--------
https://pitest.org/quickstart/mutators/#non-void-method-call-mutator-non_void_method_calls
test was added.
---------
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/64068f25e12fc53287e29c691b44b0cd/raw/3f08e73e3946ef9ef59bd119028bb67eff99b15b/ImportOrder.xml
Diff Regression projects: https://gist.githubusercontent.com/Kevin222004/21e3934e85f802e2fbd48af06d122364/raw/604256badd733d8568064f371d55657c04b00dfd/t …
> Issue #13501: Kill mutation for ImportOrderCheck-2

- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/Example1.txt
- src/xdocs/checks/javadoc/invalidjavadocposition.xml
Issue #13735:  Fixed typos in files `invalidjavadocposition.xml` and `Example1.txt`
> Issue #13735: Fixed typos

- config/pitest-suppressions/pitest-api-suppressions.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescriptionDifferentCharset.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthUnmappableCharacters.java
Issue #13672: Kill mutation related to Charset in FileText
originally discussed at https://github.com/checkstyle/checkstyle/pull/13181#discussion_r1308725119
---
https://github.com/checkstyle/checkstyle/blob/958051594a64ea5a228359919ed7426e69a242d7/config/pitest-suppressions/pitest-api-suppressions.xml#L12-L28
> Issue #13672: Kill mutation related to Charset in FileText

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
The basic difference is that the comment did not include the term `malformed` input characters. This test particularly tests for malformed input sequences for a particular charset.
> minor: Fix wording of Javadoc comment for malformed input

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenTestLimitedToken.java
part of #13213 
Link to check documentation :  [clickHere](https://checkstyle.sourceforge.io/checks/misc/descendanttoken.html#DescendantToken)
Proof that all suppressions has removed : 
```
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ grep descendanttoken config/checkstyle-input-suppressions.xml
files="checks[\\/]descendanttoken[\\/]InputDescendantTokenIllegalTokens.java"/>
files="checks[\\/]descendanttoken[\\/]InputDescendantTokenIllegalTokens5.java"/>
files="checks[\\/]descendanttoken[\\/]InputDescendantTokenIllegalTokens6.java"/>
files="checks[\\/]descendanttoken[\\/]InputDescendantTokenReturnFromFinally2.java"/>
files="checks[\\/]descendanttoken[\\/]InputDescendantTokenTestLimitedToken.java"/>
rajro@DESKTOP-HSV42DL MINGW64 ~/checkstyle (master)
$ git checkout …
```
> Issue #13213: Remove ok comments from descendanttoken package

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
Issue #13672: Kill mutation for Filter2
----------
https://checkstyle.sourceforge.io/filters/suppressionfilter.html#SuppressionFilter
----------
https://github.com/checkstyle/checkstyle/blob/d73d90511ce01b9dcebd8486c332480a48369080/config/pitest-suppressions/pitest-filters-suppressions.xml#L318-L325
-----------
https://github.com/checkstyle/checkstyle/blob/d73d90511ce01b9dcebd8486c332480a48369080/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java#L182-L184 
The removal will not make affect becuase lets suppose the optional is true and the file does not exist then it is already initialized at https://github.com/checkstyle/checkstyle/blob/d73d90511ce01b9dcebd8486c332480a48369080/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java#L145 so …
> Issue #13672: Kill mutation for Filter2

- config/pitest-suppressions/pitest-xpath-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
> Issue #13809: kill mutation for RootNode getColumnNumber

- config/checkstyle-non-main-files-suppressions.xml
- src/xdocs/checks/javadoc/javadocmissingwhitespaceafterasterisk.xml
- src/xdocs/checks/javadoc/javadocmissingwhitespaceafterasterisk.xml.template
- src/xdocs/checks/javadoc/javadoctagcontinuationindentation.xml
- src/xdocs/checks/javadoc/javadoctagcontinuationindentation.xml.template
- src/xdocs/checks/javadoc/requireemptylinebeforeblocktaggroup.xml
- src/xdocs/checks/javadoc/requireemptylinebeforeblocktaggroup.xml.template
Part of https://github.com/checkstyle/checkstyle/issues/13627
> Issue #13627: Enable macros to fix missing 'javadoc.unclosedHtml'

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-imports-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/FileImportControl.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlTestRegexpInFile2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlTestRegexpInFile2.xml
Issue #13672: Kill mutation for FileImportControl
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/config/pitest-suppressions/pitest-imports-suppressions.xml#L12-L19
This constructor
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/FileImportControl.java#L44-L49
is used called only at line 185
https://github.com/checkstyle/checkstyle/blob/ccc12eb6d7f6c8e0876077e7883cf8f59a541a37/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java#L181-L186
so this elseif statment will execute in case 
```
<file name="InputImportControl.*" regex="true">
<disallow class="java.awt.Image"/>
</file>
```
where we have file know encloseInGroup …
> Issue #13672: Kill mutation for FileImportControl

- config/pitest-suppressions/pitest-xpath-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractRootNode.java
Issue #13809: kill mutation for AbstarctRootNode
https://github.com/checkstyle/checkstyle/blob/d316b893da935d33736e90321b909f9b72d835d8/config/pitest-suppressions/pitest-xpath-suppressions.xml#L3-L10
Attributes are not allowed by design:
https://github.com/checkstyle/checkstyle/blob/a7fa83a3de92486dd7033b45bc5364ca3eae9725/src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractRootNode.java#L73-L75
> Issue #13809: kill mutation for AbstarctRootNode

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/pitest-suppressions/pitest-common-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatter.java
- src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java
Issue #13809: kill mutation for AuditEventDefaultFormatter
I didn't find any test case for this and the reason may be in StringBuilder even after we assign the capacity if the character or string goes beyond the limit of assigned capacity. it will automatically expands the necessary memory to accommodate character to string builder.
> Issue #13809: kill mutation for AuditEventDefaultFormatter

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/javadocpropertiesgenerator/InputJavadocPropertiesGeneratorGetFirstJavadocSentence.java
Issue #13809: kill mutation for JavadocPropertiesGenerator
https://github.com/checkstyle/checkstyle/blob/a7fa83a3de92486dd7033b45bc5364ca3eae9725/config/pitest-suppressions/pitest-common-2-suppressions.xml#L111-L118
Test
> Issue #13809: kill mutation for JavadocPropertiesGenerator

- config/pitest-suppressions/pitest-common-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
Issue #13809: kill mutation for JavadocPropertiesGenerator-2
https://github.com/checkstyle/checkstyle/blob/649b669336ebdb914936b65e582eb00a5a9ed17f/config/pitest-suppressions/pitest-common-2-suppressions.xml#L13-L20
we don't need help when we run cmd from the config
> Issue #13809: kill mutation for JavadocPropertiesGenerator-2

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsRecords.java
Issue #13213 
Proof that all suppressions for this check are removed:
```
suniti@CJHFFWQW9J checkstyle % grep methodparampad config/checkstyle-input-suppressions.xml                        
suniti@CJHFFWQW9J checkstyle % files="checks[\\/]coding[\\/]covariantequals[\\/]InputCovariantEqualsRecords.java"  
suniti@CJHFFWQW9J checkstyle % git checkout remove-ok-covariantequals                                              
Switched to branch 'remove-ok-covariantequals'
Your branch is up to date with 'origin/remove-ok-covariantequals'.
suniti@CJHFFWQW9J checkstyle % grep methodparampad config/checkstyle-input-suppressions.xml
suniti@CJHFFWQW9J checkstyle % echo $?
1
```
> Issue #13213: Remove //ok comments for supress id: covariantequals

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSwitchExpressionsSkipIfLast.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastDefaultMethodsInInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastDefaultMethodsInInterface2.java
Issue #13213 
Proof that all suppressions for this check are removed:
```
suniti@CJHFFWQW9J checkstyle % grep methodparampad config/checkstyle-input-suppressions.xml   
suniti@CJHFFWQW9J checkstyle % files="checks[\\/]coding[\\/]defaultcomeslast[\\/]InputDefaultComesLastSwitchExpressionsSkipIfLast.java"
suniti@CJHFFWQW9J checkstyle % files="checks[\\/]coding[\\/]defaultcomeslast[\\/]InputDefaultComesLastSwitchExpressionsSkipIfLast.java"
suniti@CJHFFWQW9J checkstyle % git checkout remove-ok-defaultcomeslast                                                                 
Switched to branch 'remove-ok-defaultcomeslast'
Your branch is up to date with 'origin/remove-ok-defaultcomeslast'.
suniti@CJHFFWQW9J checkstyle % grep methodparampad config/checkstyle-input-suppressions.xml …
```
> Issue #13213: Remove //ok comments for suppress id=defaultcomeslast

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
Issue #12671
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/6e271c2ae713051c0a30111211de5627/raw/9f34341ce6c7feabbda4bc3d59fa62df427d775d/FinalLocal.xml
Report label: Regression-Oct-03
Attempt to improve [this PR](https://github.com/checkstyle/checkstyle/pull/13184) and kill mutation without affecting performance issues mentioned in the comments.
We don't need a separate stack for `prevScopeUninitializedVariables`. We can track those variables within `ScopeData` and rely on the current check's logic to `pop` from `scopeStack`.
> Issue #12671: kill pitest mutations in FinalLocalVariableCheck

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-common-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
Issue #13809: Kill mutation in Checker
class :- https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
------------
https://github.com/checkstyle/checkstyle/blob/8dffc49e46490cbd472548cfd6cccccd5ecedc4f/config/pitest-suppressions/pitest-common-suppressions.xml#L3-L10
and 
https://github.com/checkstyle/checkstyle/blob/8dffc49e46490cbd472548cfd6cccccd5ecedc4f/config/pitest-suppressions/pitest-common-suppressions.xml#L48-L55
---------
we initialize fileExtensions to null if extensions are null at 
https://github.com/checkstyle/checkstyle/blob/8dffc49e46490cbd472548cfd6cccccd5ecedc4f/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L549-L552
so if we remove it and remove the empty initialization at …
> Issue #13809: Kill mutation in Checker

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
Issue #13809: Kill mutation in Checker-4
-----------
https://github.com/checkstyle/checkstyle/blob/8c8bc0c6102823206ca3a562b01b26882fc242fa/config/pitest-suppressions/pitest-common-suppressions.xml#L30-L38
----------
Test added
> Issue #13809: Kill mutation in Checker-4

- .github/workflows/site.yml
Noticed at https://github.com/checkstyle/checkstyle/pull/13861#issuecomment-1755265092, skipped runs count towards concurrency. Updating the `cancel-in-progress` configuration to be `false` will protect in-progress actions from being cancelled.
> infra: do not allow in-progress site action to be cancelled by skipped run

- README.md
- Members' chat link was broken, don't know if it still exists. (404)
- Matrix brought gitter or something like that, so this is the updated room link.
> minor: Fix broken link to matrix(gitter) chat

- config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/XdocsTemplateSink.java
For Issue #13770: PR #13774 has a bug, to resolve that we are overriding the `write` func of PrinterWriter as well to make it concrete.
Proof of Validity - https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/48355264
> Issue #13770: Override write func to enforce unix-style newline

- config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElementTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElementTest.java
Issue #13809: Kill mutation in Filters
this is typical extra data storage that pitest catch as not critical for execution.
I think it is fine to remove it here as cost of taking String value of regexp from Pattern object is cheap, as it is stored as is (String) in Patter class (it is single getter to get String on Pattern class).
https://github.com/openjdk/jdk/blob/ecd25e7d6f9d69f9dbdbff0a4a9b9d6b19288593/src/java.base/share/classes/java/util/regex/Pattern.java#L1138-L1144
> Issue #13809: Kill mutation in Filters

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
Issue #11214 
This PR removes the `SummaryJavaDocCheck` from the suppression list in `InlineConfigParser.java` class as all the checks using this have the violation message specified.
> Issue #11214: Remove SummaryJavaDocCheck from Suppression List

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
Issue #13809: Kill mutation in TokenUtil
https://github.com/checkstyle/checkstyle/blob/0322ba1be8489d1df373013efc9078de4d209eb4/src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java#L80 
we are passing object as a param so I think it will not make a difference either we pass only name or whole field
> Issue #13809: Kill mutation in TokenUtil

- config/checker-framework-suppressions/checker-methods-resource-fenum-suppressions.xml
- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/UnmodifiableCollectionUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java
Issue #13809: Kill mutation in XpathUtil
https://github.com/checkstyle/checkstyle/blob/0322ba1be8489d1df373013efc9078de4d209eb4/config/pitest-suppressions/pitest-utils-suppressions.xml#L354-L361
> Issue #13809: Kill mutation in XpathUtil

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPad2.java
> Issue #11214: Specify violation messages for EmptyForInitializerPadCheck Input Files

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleDefaultSettingsFour.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleDefaultSettingsOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleDefaultSettingsThree.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleDefaultSettingsTwo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleExcludeScope1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleExcludeScope2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleExcludeScope4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleHtml1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleHtml2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleHtml3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleHtml4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleScopePackage1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleScopePackage3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleScopeProtected1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleScopeProtected3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleScopePublic1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleScopePublic3.java
Issue #13969 
This PR aims to improve the clarity of our codebase's documentation by removing the term `// violation` from within Javadoc comments. Leveraging our support for annotations like `// violation X lines above/below`, these violation references will be relocated above the relevant Javadoc, enhancing readability.
> Issue #13969: Update JavaDocStyleChecks and it's input files

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
Issue #13809: Kill mutation in PackageObjectFactory
if the string contains packageSeparator then the instance will be null. Probably no test case is possible.
> Issue #13809: Kill mutation in PackageObjectFactory

- config/checkstyle-input-suppressions.xml
- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/packageobjectfactory/abc/FooCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/packageobjectfactory/zoo/FooCheck.java
Issue #13809: Kill mutation in PackageObjectFactory-2
Test added
> Issue #13809: Kill mutation in PackageObjectFactory-2

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/configurationloader/InputConfigurationLoaderDefaultProperty.xml
- src/xdocs/config.xml
Issue #13809: Kill mutation ConfigurationLoader2
Test
> Issue #13809: Kill mutation ConfigurationLoader2

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilterSuppressById6.java
Issue #13809: Kill mutation in SuppressionCommentFilter
----------
https://checkstyle.sourceforge.io/filters/suppressioncommentfilter.html#SuppressionCommentFilter
----------
https://github.com/checkstyle/checkstyle/blob/00f1780694eefe400bd08c37d255772da82e1279/config/pitest-suppressions/pitest-filters-suppressions.xml#L282-L289
----------
test added.
Modified test prooves that exception is happening:
```
✔ ~/java/github/romani/checkstyle [Kevin222004/SuppressionCommentFilter L|✚ 2…1⚑ 1] 
$ git diff
diff --git a/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java b/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
index 5a82d0c..0a99106 100644
--- a/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilt …
```
> Issue #13809: Kill mutation in SuppressionCommentFilter

- config/checkstyle-non-main-files-suppressions.xml
Issue #13893 
This issue has been marked completed but is still having the reference in `checkstyle-non-main-files-suppressions.xml` file. This PR removes the reference so that in future PRs it doesn't gives error as - 
```
Following lines are referencing closed issues.
Such lines should be removed or the issue should be examined:
https://github.com/suniti0804/checkstyle/blob/xpathfinallocalvariable/config/checkstyle-non-main-files-suppressions.xml#L256
> Issue #13893: Remove issue reference from checkstyle-non-main-files-suppressions.xml

- config/pitest-suppressions/pitest-common-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
Issue #13809: Kill mutation in CommonUtil
regression is taken from https://github.com/checkstyle/checkstyle/pull/13284
gist: https://gist.github.com/romani/f15f3afabac0f9ad1e63f429b62d445f
Diff Regression config: https://gist.githubusercontent.com/romani/f15f3afabac0f9ad1e63f429b62d445f/raw/40dfb3e50dc3e5606844f00d074f572be4682079/Config.xml
Report label: Regression-with-path-for-basedir
> Issue #13809: Kill mutation in CommonUtil

- config/jsoref-spellchecker/whitelist.words
- src/xdocs/index.xml.vm
Added reference to the [Checkstyle extension for bld](https://github.com/rife2/bld-checkstyle) in the ` Active Tools` table (#13995)
From https://rife2.com/bld:
>[bld](https://github.com/rife2/bld) is a new build system that allows you to write your build logic in pure Java.
> doc: Added reference to the Checkstyle extension for bld

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
Issue #13999 
Changes in the AbstractJavadocCheck class for the mutated method are covered by the existing test cases.
> Issue #13999: Resolve pitest suppression for AbstractJavadocCheck validateDefaultJavadocTokens() method

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
Issue #13999 
Changes in the `AbstractJavadocCheck` class for the mutated method are covered by the existing test cases.
> Issue  #13999: Cover pitest survival for init() method of AbstractJavaDocCheck

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/xdocs/checks/coding/returncount.xml
> Issue #13934: Version updated from 3.2 to 3.4

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnClass.java
Issue #13321: Kill mutation for BlockCommentPosition 2
------
https://github.com/checkstyle/checkstyle/blob/8804126fd3a4f58d5116712aaba939bcd2269b52/config/pitest-suppressions/pitest-utils-suppressions.xml#L21-L28
-----
dependency tree on this method
```
BlockCommentPosition.isOnPlainClassMember
+--isOnMethod
+--ClassAndPropertiesSettersJavadocScraper
+--BlockCommentPosition.isOnMember
+--JavadocUtil.isCorrectJavadocPosition
+--InvalidJavadocPositionCheck
+--JavadocUtil.isJavadocComment
+--AstTreeStringPrinter
+--JavadocPropertiesGenerator
+--DesignForExtensionCheck
+--AbstractJavadocCheck
+-- all ast based javadoc checks
+--JavadocContentLocationCheck
+--MissingJavadocPackageCheck
+--isOnField
+-- isCorrectJavadocPosition ... same as above
+--isOnConstructor
+-- isCorrectJavadocPosition …
```
> Issue #13321: Kill mutation for BlockCommentPosition 2

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/SimplifyBooleanReturnCheck.xml
- src/xdocs/checks/coding/simplifybooleanreturn.xml
- src/xdocs/checks/coding/simplifybooleanreturn.xml.template
Noticed at https://checkstyle.org/checks/coding/simplifybooleanreturn.html#SimplifyBooleanReturn, I expected a direct link to this PMD rule.
> doc: add direct link to check

- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitCyclesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitSuperClassTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
As the [Issue #13544](https://github.com/checkstyle/checkstyle/issues/13544) has been marked closed so we need to remove it's reference from the files to avoid build failures.
Build failure discovered in - https://github.com/checkstyle/checkstyle/actions/runs/6941703823/job/18883087013?pr=13951
> minor: Remove closed issue reference

- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
Issue #14019 
In this PR, I've made a change to the `getDeclaredScopeFromMods` method in the `ScopeUtil` class. I removed the `result == null` condition from the for loop. This change was based on a mutation test, which suggested that we could remove this condition without affecting the functionality of the code.
After making this change, I ran our suite of unit and integration tests. I'm happy to report that all tests passed successfully, indicating that this change did not introduce any regressions or break any existing functionality.
Based on my analysis, the impact of this change appears to be minimal. The `result == null` condition was not contributing to the functionality of the method, and its removal has not negatively affected any other parts of our code.
In conclusion, it seems …
> Issue #14019: Resolve pitest suppressions for ScopeUtil 2

- pom.xml
The previous identifier has been replaced by a more readable one at some point in the past.
* https://spdx.org/licenses/
* https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1%2B.xml
> infra: use valid SPDX license identifier

- azure-pipelines.yml
trying to understand https://github.com/checkstyle/checkstyle/pull/13887
and what will be required for https://github.com/checkstyle/checkstyle/pull/14012
fact that maven opts are not printing mvn version, but print jdk version:
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=17918&view=logs&j=c902ebb4-c9f8-5f09-4e17-ff78fbbc842e&t=9ca98c81-ff64-58f0-9d03-a23ac1c4a111&l=14
```
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/bb44b446-8cfc-40a0-a0a6-02d141cff2bd.sh
ON_CRON_ONLY:$(onCronOnly)
BUILD_REASON:PullRequest
cmd: ./.ci/validation.sh test
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed …
```
> minor: print mvn version; MAVEN_OPTS --show-version is not working

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
Issue #13999 
The mutation involves replacing the `JavadocUtil.getPreviousSibling(node)` method call with the `node` itself. The mutated line of code is as follows:
`DetailNode newLine = node;`
In the mutated code, instead of getting the previous sibling of the node, we directly assign the node to the `newLine`.
The overall purpose of the `getNearestEmptyLine` method is to find and return the nearest empty line in Javadoc. The mutation changes the starting point of the search from the previous sibling to the current node itself. The change in the code does not alter the logic or the context of the application. The `getNearestEmptyLine` method does not rely on the hierarchical relationship between the nodes. Therefore, starting the search from the current node instead of its previous …
> Issue #13999: Resolve pitest suppression for JavadocParagraphCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment11.java
Resolves #14064
covers task of Issue #11446
> Issue #14064: Regexp: violation pointing to line 0 while other Checks count first line as 1

- config/checkstyle-non-main-files-suppressions.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/header/HeaderCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/header/header.xml
- src/xdocs/checks/header/header.xml.template
- src/xdocs/checks/header/regexpheader.xml
- src/xdocs/checks/header/regexpheader.xml.template
Issue #13693
all extra refactoring was enforced by our verify validation.
setCharset
https://github.com/checkstyle/checkstyle/commit/326e3ae67b8cc2a1dcbcf2356b30fd9a4afa964a#diff-fa56dd39f138d19b44a0aa110150c621c7ba641aead7a198d35db46fdbc767a2R71
setHeaderFile
https://github.com/checkstyle/checkstyle/commit/6f1f7bd3fdcca84404e97964b3e48de6db5024ec#diff-fa56dd39f138d19b44a0aa110150c621c7ba641aead7a198d35db46fdbc767a2R69
setHeader
https://github.com/checkstyle/checkstyle/commit/6f1f7bd3fdcca84404e97964b3e48de6db5024ec#diff-fa56dd39f138d19b44a0aa110150c621c7ba641aead7a198d35db46fdbc767a2R81
> Issue #13693: migrate header modules to use property macro

- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedClassInInt.java
Fixes #14129.
For context see the ticket.
> Issue #14129: Make long class and interface names shorter

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-utils-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
Issue #14019 
Mutation - 
https://github.com/checkstyle/checkstyle/blob/11e2b4baee11523db5c15602380775e95fb437ba/config/pitest-suppressions/pitest-utils-suppressions.xml#L39-L46
```
Method
getScopeFromMods(DetailAST)
Usages or usages of base method in Project Files
Unclassified
checkstyle
com.puppycrawl.tools.checkstyle.checks.coding
DeclarationOrderCheck
processModifiersSubState(DetailAST, ScopeState, boolean)
final Scope access = ScopeUtil.getScopeFromMods(modifiersAst);
```
1. `DeclarationOrderCheck`
Diff Regression config: https://gist.githubusercontent.com/suniti0804/35fc6bb1108b1e7ddb7c5f13471510b8/raw/fffe9dbf99d906a8e1855e38dcbf64c57fca430d/pull-14061-regerssion-config
Diff Regression projects: https://gist.githubusercontent.com/suniti0804/1d7bd7fbc50bf6c93896fbe2bbbf2c4a/raw/f7161 …
> Issue #14019: Resolve pitest utils suppressions for ScopeUtil#getScopeFromMods

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/ClassFanOutComplexityCheck.xml
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml
- src/xdocs/checks/metrics/classdataabstractioncoupling.xml.template
- src/xdocs/checks/metrics/classfanoutcomplexity.xml
- src/xdocs/checks/metrics/classfanoutcomplexity.xml.template
Issue #13693
setMax: https://github.com/checkstyle/checkstyle/commit/c044038c3b932586c0d384b614254cc2d1838838#diff-d554a793e3a3cbe81e95a9dd9b699444150c22c39a4c35ee7696fbdd04805d14R109 ( Jan 2, 2004)
https://sourceforge.net/projects/checkstyle/files/OldFiles/
setExcludedClass: (Dec 2, 2013) , it is 5.7
https://github.com/checkstyle/checkstyle/commit/cd7d040b4d2c4a80e87ef9b5be9bbd964f19e97d#diff-d554a793e3a3cbe81e95a9dd9b699444150c22c39a4c35ee7696fbdd04805d14R109
dates are weird a bit for few releases of 5.X:
setExcludeClassesRegexps:
https://github.com/checkstyle/checkstyle/commit/7b95603c0e5036f397365a05b68483d0da690c63#diff-ae3adc6efccc0a0cca1c89bf35cb69fd68ae8d0ce40c52176814218bd4e144a7R133
tags are weird ..... it isnot 4.4
https://github.com/checkstyle/checkstyle/issues/3234, it is 7.7 …
> Issue #13693: migrate few metric modules to property macro

- config/checkstyle-non-main-files-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/StaticVariableNameCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/TypeNameCheck.xml
- src/xdocs/checks/naming/staticvariablename.xml
- src/xdocs/checks/naming/staticvariablename.xml.template
- src/xdocs/checks/naming/typename.xml
- src/xdocs/checks/naming/typename.xml.template
Issue #13693
exception will looks like:
```
Caused by: org.apache.maven.doxia.macro.MacroExecutionException: 
Failed to find '@since' version for 'format' property in 'TypeNameCheck' and all parent classes of it
at com.puppycrawl.tools.checkstyle.site.SiteUtil.getSinceVersion(SiteUtil.java:724)
at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writePropertySinceVersionCell
(PropertiesMacro.java:546)
at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writePropertyRow(PropertiesMacro.java:268)
at com.puppycrawl.tools.checkstyle.site.PropertiesMacro.writeTablePropertiesRows(PropertiesMacro.java:214)
... 73 more
```
Verifier.java from checkstyle 2.4:
[Verifier.java.txt](https://github.com/checkstyle/checkstyle/files/13464497/Verifier.java.txt) …
> Issue #13693: migrate to module macros few naming modules

- pom.xml
This PR is based on a suggestion by @romani in: https://github.com/checkstyle/checkstyle/issues/14129. The idea is to add Error Prone Support to Checkstyle in this PR and after that discuss which checks we want to enable.
I added Error Prone Support as part of the already existing Maven profile that runs Error Prone. The reason for this is that Error Prone Support is an extension and "just adds some checks". Configuration wise, this is the simplest. The only difference the user could notice is that the documentation URL from the Error Prone Support checks are slightly different. See an example below.
Error from an Error Prone check from Google:
> Error:  /home/runner/work/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java:[183,51] …
> Issue #14137: Introduce Error Prone Support

- pom.xml
fixes Issue number: #14123 by excluding the dependency below doxia-core
before:
```
[INFO] --- dependency:3.6.1:tree (default-cli) @ checkstyle ---
[INFO] com.puppycrawl.tools:checkstyle:jar:10.12.7-SNAPSHOT
(...)
[INFO] +- org.apache.maven.doxia:doxia-core:jar:1.12.0:compile
[INFO] |  +- org.apache.maven.doxia:doxia-sink-api:jar:1.12.0:compile
[INFO] |  +- org.apache.maven.doxia:doxia-logging-api:jar:1.12.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.3.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-container-default:jar:2.1.0:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:compile
[INFO] |  |  +- org.apache.xbean:xbean-reflect:jar:3.7:compile
[INFO] |  |  \- com.google.collections:google-collections:jar:1.0:compile
[INFO] |  +- …
```
> Issue #14123: Remove transitive google-collections dependency

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTags2.java
Fixes #13307
VIOLATIONS_ABOVE_PATTERN_WITH_MESSAGES was MULTIPLE_VIOLATIONS_ABOVE_PATTERN_WITH_MESSAGES but PMD complained on length, it kind of right, so I removed MULTIPLE_.
> Issue #13307: support for 'X violations above:'

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
Issue #13999 
```
JavadocStyleCheck.checkHtmlTags(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkComment(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.visitToken(DetailAST)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
TestUtil.isStatefulFieldClearedDuringBeginTree(AbstractCheck, DetailAST, String, Predicate<Object>)  (com.puppycrawl.tools.checkstyle.internal.utils)
TreeWalker.notifyVisit(DetailAST, AstState)  (com.puppycrawl.tools.checkstyle)
```
1. JavadocStyleCheck
Diff Regression config: https://gist.githubusercontent.com/suniti0804/466108cc17f588f2311aa2d4f40b60bb/raw/f1a067202e11a4639696c0779f36574e4a81000d/pull-14033-regerssion-config …
> Issue #13999: Resolve pitest suppression for parseTags() method of TagParser

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
Issue #13999 
```
TagParser.TagParser(String[], int)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkHtmlTags(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkComment(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.visitToken(DetailAST)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
TreeWalker.notifyVisit(DetailAST, AstState)  (com.puppycrawl.tools.checkstyle)
TestUtil.isStatefulFieldClearedDuringBeginTree(AbstractCheck, DetailAST, String, Predicate<Object>)  (com.puppycrawl.tools.checkstyle.internal.utils)
```
1. JavadocStyleCheck
Diff Regression config: https://gist.githubusercontent.com/suniti0804/466108cc17f588f2311aa2d4f40b60bb/raw/f1a067202e11a4639696c0779f36574e4a81000 …
> Issue #13999: Resolve pitest suppression for skipHTMLComment() method of TagParser

- pom.xml
Related issue https://github.com/checkstyle/checkstyle/issues/14137.
This PR disables a few checks from Error Prone Support. Additionally, the goal of this PR is to agree on how we are going to configure the rest of the checks in the `pom.xml`. If we, at some point, decide to either disable or enable more checks from Error Prone itself that have severity `WARN` or `INFO` we can do that in the same configuration section (see [docs](https://errorprone.info/bugpatterns)).
At Picnic we have the convention to add a comment for every rule explaining why we disable it. If we would like the same here, I need your help to write the correct reasoning :). We can also decide to leave it like this. For now, I disabled two extra rules that are that will cause more noise than improvements.
[In the …
> Issue #14137: Disable Error Prone Support checks

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
Issue #13999 
```
TagParser.TagParser(String[], int)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkHtmlTags(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkComment(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.visitToken(DetailAST)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
TestUtil.isStatefulFieldClearedDuringBeginTree(AbstractCheck, DetailAST, String, Predicate<Object>)  (com.puppycrawl.tools.checkstyle.internal.utils)
TreeWalker.notifyVisit(DetailAST, AstState)  (com.puppycrawl.tools.checkstyle)
```
1. JavadocStyleCheck
Diff Regression config: https://gist.githubusercontent.com/suniti0804/466108cc17f588f2311aa2d4f40b60bb/raw/f1a067202e11a4639696c0779f36574e4a81000 …
> Issue #13999: Resolve pitest suppression for parseTag() method of TagParser

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
Issue #13999 
```
TagParser.parseTags(String[], int)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
TagParser.TagParser(String[], int)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkHtmlTags(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.checkComment(DetailAST, TextBlock)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
JavadocStyleCheck.visitToken(DetailAST)  (com.puppycrawl.tools.checkstyle.checks.javadoc)
TreeWalker.notifyVisit(DetailAST, AstState)  (com.puppycrawl.tools.checkstyle)
TestUtil.isStatefulFieldClearedDuringBeginTree(AbstractCheck, DetailAST, String, Predicate<Object>)  (com.puppycrawl.tools.checkstyle.internal.utils)
```
1. JavadocStyleCheck …
> Issue #13999: Resolve pitest suppression for getTagId() method of TagParser

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullEnhancedInstanceof.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java
> Issue #13213: Remove //ok comments for equalavoidsnull module

- pom.xml
Part of #14120 
Added `Automatic-Module-Name` to `MANIFEST.MF`.
When using Checkstyle as a dependency (e.g. when implementing own checks), this will fix the warnings issued by the Java compiler and by Maven about an unstable automatic module name that is derived from the file name.
With this change, Checkstyle is still treated as an automatic module (as before) but with a stable name.
> Issue: #14120 Automatic Module

- config/jsoref-spellchecker/whitelist.words
- pom.xml
Issue #14137.
This PR enables the `AssertJIsNull` check, see https://error-prone.picnic.tech/bugpatterns/AssertJIsNull/.
> Issue #14137: Enable `AsertJIsNull` check

- pom.xml
Issue #14137.
This PR enables the following check: https://error-prone.picnic.tech/bugpatterns/AutowiredConstructor/.
> Issue #14137: Enable `AutowiredConstructor` check

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/CanonicalAnnotationSyntax/ check.
> Issue #14137: Enable `CanonicalAnnotationSyntax` check

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/DirectReturn/ check.
> Issue #14137: Enable `DirectReturn` check

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckExamplesTest.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/Example4.java
- src/xdocs/checks/coding/illegaltokentext.xml
- src/xdocs/checks/coding/illegaltokentext.xml.template
Issue: #13345 
Sorry for deleting the branch causing the last PR to close.
1. In example2, the program failed to detect violation message with explanation, problem may be in src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
2. In example3, text block will cause compile error in source10 environment, I turned it to another pattern and thus, test disabled
> Issue#13345: Enable ilegalTokenTextExamplesTest

- config/checkstyle-input-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/CustomImportOrderCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderListRules.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderListRulesWhitespace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLineList.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example10.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example12.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example15.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example2.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example3.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example4.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example5.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example6.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example7.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example8.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/Example9.txt
- src/xdocs/checks/imports/customimportorder.xml
- src/xdocs/checks/imports/customimportorder.xml.template
Resolves #14216, if we decide to approve.
We can add a note about still supporting `###` delimited string if we want to, I don't think it's necessary. I have left UT configs alone to show that we don't have a regression.
> Issue #14216: CustomImportOrder property 'customImportOrderRules' should be String[]

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNull.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullIgnoreCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullSuperClass.java
Part of Issue #13213 
Removing '//ok' comments from input files equalsavoidnull module.
I have run the code on my local system using mvn verify
Status : Build successful.
Proof of work :
> Issue #13213: Removed '//ok' from equalsavoidnull

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
Issue: #13999 
https://github.com/checkstyle/checkstyle/blob/5cd55fbd79d93f3a336c36319438450f51f133bd/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L201-L208
`findTextStart(String line)` method is used to find the index of the first non-whitespace character ignoring the javadoc comment's start and end strings as well as `*`.
The mutated code was `index += 2;` which was incrementing the index by 2 whenever it encountered `/**`.  Now based on the changes I made, the index gets incremented by 1 only instead of 2 and the functionality of the method `findTextStart()` does not changes. The method checks that if the current character is a whitespace or `/**` or `*/` or `*`. When we encounters the `/**`, index gets incremented by 1 so the next character is `*` which gets ignored. 
So …
> Issue #13999: Resolve pitest suppression for index += 2; of JavadocStyleCheck

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/EmptyMethod/ check.
> Issue #14137: Enable `EmptyMethod` check

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTagsOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTagsTwo.java
Part of #11163
Enforced file size for InputAbstractJavadocHtmlTags.java
The decided file size limit was 120 lines and I have implemented the same.
> Issue #11163: Enforced file size on NonTightHtmlTags

- .circleci/config.yml
until https://github.com/checkstyle/checkstyle/issues/13209
to fix `The version of Java (11.0.20.1) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
As a temporary measure, you can set the property 'sonar.scanner.force-deprecated-java-version' to 'true' to continue using Java 11.0.20.1
This workaround will only be effective until January 28, 2024. After this date, all scans using the deprecated Java 11 will fail.`
from https://app.circleci.com/pipelines/github/checkstyle/checkstyle/22927/workflows/a8517d08-b7c7-44f4-8b07-1ec4b10ffab6/jobs/476750
> infra: disable sonar until we migrate to jdk17

- config/checkstyle-input-suppressions.xml
- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTagsNoViolationOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTagsNoViolationTwo.java
Enforced file size on InputAbstractJavadocHtmlTagsNoViolation.java
Came across unnecessary '//ok' comments while working on the file InputAbstractJavadocHtmlTagsNoViolation.java , also removed those as part of the same commit.
> Issue #11163: Enforced fileSize HTMLTagsNoViolation

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsConstants.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsValuePair.java
Part of https://github.com/checkstyle/checkstyle/issues/13213
Link to check documentation:
https://checkstyle.org/checks/annotation/suppresswarnings#SuppressWarnings
Proof that all suppressions for this check are removed:
```
(master)$ grep suppresswarnings config/checkstyle-input-suppressions.xml
files="checks[\\/]annotation[\\/]suppresswarnings[\\/]InputSuppressWarningsConstants.java"/>
files="checks[\\/]annotation[\\/]suppresswarnings[\\/]InputSuppressWarningsConstants.java"/>
files="checks[\\/]annotation[\\/]suppresswarnings[\\/]InputSuppressWarningsValuePair.java"/>
(issue-13213-suppresswarnings)$ grep suppresswarnings config/checkstyle-input-suppressions.xml
(issue-13213-suppresswarnings)$ echo $?
1
```
> Issue #13213: Remove '//ok' comments from Input files (SuppressWarningsCheck)

- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/OverloadMethodsDeclarationOrderTest.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadMethodsDeclarationOrderPrivateAndStaticMethods.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/overloadmethodsdeclarationorder/InputOverloadMethodsDeclarationOrderPrivateAndStaticMethods.java
Issue: #14273 
> Thanks a lot for testing modifiers, please send PR to contribute Junit test coverage to make sure it will always be like this:).
Added JUnit Test coverage for private and static methods as a part of `OverloadMethodsDeclarationOrder` check.
Created a new input file called `InputOverloadMethodsDeclarationOrderPrivateAndStaticMethods.java` and wrote the test method for it.
> supplemental: Issue#14273 Add JUnit test coverage for overloaded private and static methods for OverloadMethodsDeclarationOrder

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCorrectParagraphTwo.java
Removed '//ok' comments from InputAbstractJavadocCorrectParagraphTwo.java file.
> Issue #13213: Removed //ok from CorrectParagraph

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/ExplicitEnumOrdering/ check.
> Issue #14137: Enable `ExplicitEnumOrdering` check

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthSimpleOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthSimpleTwo.java
Enforced file size on InputMethodLengthSimple file.
There was only one violation in the file before splitting, so I set the **_expected_** of first file to
expected = CommonUtil.EMPTY_STRING_ARRAY;
and mentioned the violation in second file.
> Issue #11163: Enforced filesize MethodLengthSimple

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldClassNestedInRecord.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationLang2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerFallThrough.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityCheckTextBlocks.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckPatterns.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclarationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableWithoutPackageStatement.java
Part of #13213
Removed all the '//ok' comments from multiple checks belonging to the test/resources-noncompilable/coding module
like **_suggested_**.
Hope this is fine..
Also resolved the conflicts that occurred previously
> Issue #13213: Removed '//ok' noncompilable/coding

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassAnnotation.java
Issue #13213: Removed '//ok' from InputOneTopLevelClass and InputOneTopLevelClassAnnotation
> Issue #13213: Removed '//ok' from InputOneTopLevelClass and InputOneTopLevelClassAnnotation

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderDefaultMethods.java
Part of #13213
Removed `//ok` comments from **InputModifierOrderDefaultMethods.java**
> Issue #13213: Removed //ok from modifierorder

- config/checkstyle-input-suppressions.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/package-info.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersReceiver.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationNoNpe.java
Removed '//ok' comments from leftout files of /noncompilable.
Also, noticed that there were few unnecessary suppress tags in checkstyle-input-suppressions.xml
The reason was due to the files changed in the recent PR [#14308](https://github.com/checkstyle/checkstyle/pull/14308).
I noticed that the comments were removed as part of enforcing file size but the respective suppress tags have not been removed.
The PR however was merged and thus the unnecessary suppress tags, which I have removed now.
> Issue #13213: Removed //ok leftout checks

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
issue: #13999 
https://github.com/checkstyle/checkstyle/blob/6d83d86d162c25071a280d5b19c1dbc9daa40cb1/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L111-L119
The `isInIgnoreBlock()` modified in this PR is used to check whether there is `throw` keyword is used in a block that should be ignored. Blocks that should be ignored are try block with catch, local classes, anonymous class & lambda expressions.  
The `DetailAST throwAst` parameter used in this method is a DetailAst node representing the `throw` keyword used in the current block. Pitest was complaining about the `getParent()` method used on this parameter ( throwAst.getParent() ). The getParent() is used to get the parent token of the current token which in our case is `throw` keyword. 
We're using the parent token to …
> Issue#13999: Resolve pitest suppression for throwAst.getParent() of JavadocMethod

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount6.java
Part of #13213
Removed `//ok` comments from **InputMethodCount.java**, **InputMethodCount4.java** and **InputMethodCount6.java**
> Issue #13213: Removed //ok from methodcount

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/MockitoStubbing/ check.
> Issue #14137: Enable `MockitoStubbing` check

- pom.xml
Issue https://github.com/checkstyle/checkstyle/issues/14137.
This PR enables the [error-prone.picnic.tech/bugpatterns/TimeZoneUsage](https://error-prone.picnic.tech/bugpatterns/TimeZoneUsage/) check.
> Issue #14137: Enable `TimeZoneUsage` check

- config/error-prone-suppressions/test-compile-phase-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
As of 0bb9038582406af853dd064d9c699ddc93c0994d the code under test no longer uses `ByteStreams.toByteArray`.
> minor: Simplify `PropertyCacheFileTest#testNonExistentResource`

- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
Part of #11446 
Updated test from CheckerTest to discard usage of verify( )
Tested on local : Build Successful
> Issue #11446: Update CheckerTest test to discard verify()

- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
Part of #11446 
Updated few test methods of CheckerTest to discard usage of verify( ).
> Issue #11446: Updated CheckerTest tests to stop verify() usage

- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
Part of #11446 
Updated few test methods of CheckerTest to discard usage of verify()
> Issue #11446: Update CheckerTest checks to use execute

- config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/PrimitiveComparison/ check.
I'll be off for a week or so, so there will be a small break in the PRs. I will resume with creating PRs afterwards 😄.
> Issue #14137: Enable `PrimitiveComparison` check

- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
issue #11446:
continues: #14417
partial migration for TreeWalkerTest to discard verify usage
> Issue #11446: update TreeWalkerTest to remove verify usage

- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
We leaked failed build to master in https://github.com/checkstyle/checkstyle/commit/a56788765442cefc98cfbc0771439c92d19278fa from not rebasing before merge.
> minor: fix compilation

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/treewalker/InputTreeWalkerSuppressionXpathFilterAbsolute.java
- src/test/resources/com/puppycrawl/tools/checkstyle/treewalker/InputTreeWalkerWithCacheWithNoViolation.java
Issue #11446:
final migration of TreeWalketTest to discard verify usage and use inline configuration parser
> Issue #11446: update TreeWalkerTest to use inline config parser

- src/main/java/com/puppycrawl/tools/checkstyle/checks/NoCodeInFileCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/NoCodeInFileCheck.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/ExpectedJavadocMetadataScraperNoCodeInFileCheck.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperNoCodeInFileCheck.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/NoCodeInFileCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/Example2.java
- src/xdocs/checks/misc/nocodeinfile.xml
- src/xdocs/checks/misc/nocodeinfile.xml.template
Part of #13345 
Enabled NoCodeInFileCheckExamplesTest
Based on findings in this PR #14395  and Response to  https://github.com/checkstyle/checkstyle/pull/14395#discussion_r1483020974 ,
Updated the `NoCodeInFileCheck` description in all related files.
**_Previously :_** 
`Checks whether file contains code. Files which are considered to have no code:`
**_After update :_** 
```
* Checks whether file contains code.
* Java compiler is not raising errors on files with no code or all commented out.
* Files which are considered to have no code:
```
> Issue #13345: Enabled NoCodeInFileCheckExamplesTest

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalInstantiationTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalinstantiation/SuppressionXpathRegressionIllegalInstantiationAnonymous.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalinstantiation/SuppressionXpathRegressionIllegalInstantiationInterface.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalinstantiation/SuppressionXpathRegressionIllegalInstantiationSimple.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
part of #6207 [doc](https://checkstyle.org/checks/coding/illegalinstantiation.html#IllegalInstantiation)
add xPath regression test for   IllegalInstantiationCheck
1 test for normal case, 1 for anonymous class, 1 for interface
the input files aren't compiled by IntelliJ because there is a deprecation warning for the Boolean(boolean) and Integer constructors
> Issue #6207: Add XPath IT Regression test for IllegalInstantiationCheck

- config/signatures-test.txt
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
Resolves #14220: 
This PR attempts to resolve issues related `File.createTempDirectory `with `@TempDir`
> Issue #14220: Forbid Files.createTempDirectory in Checkstyle and replace with @TempDir

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
Part of #13999 
([Check Documentation](https://checkstyle.org/checks/javadoc/javadocmethod.html))
**Mutation:**
https://github.com/checkstyle/checkstyle/blob/943576fc0da0f0e00b15b7d77f15b16dc8823416/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L111-L118
<hr>
1. **and-expression**:-
```java
ancestor.getType() == TokenTypes.LITERAL_TRY
&& ancestor.findFirstToken(TokenTypes.LITERAL_CATCH) != null	
```
2. **first-operand**: `ancestor.getType() == TokenTypes.LITERAL_TRY`
3. **second-operand**: `ancestor.findFirstToken(TokenTypes.LITERAL_CATCH) != null`
4. **mutant**: replacing **first-operand** with `true`.
<hr>
- **mutant** does not alters the result of **and-expression** because `LITERAL_CATCH` cannot exist without being the child of `LITERAL_TRY`. 
- This makes evaluating …
> Issue #13999: Resolve Pitest suppression for `ancestor.getType() == TokenTypes.LITERAL_TRY` of JavadocMethod

- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckInterfaceAndEnum.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckPrivateAndDeprecatedVar.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckPublicMethodAndVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckTokensOnMethodAndVar.java
Part of #14436 
Renamed input files and test methods of annotationonsameline module to follow naming convention.
The following files test accordingly : 
-  InputAnnotationOnSameLineCheckTokensOnMethodAndVar - 
tests for validity of multiple tokens on method and var declarations
- InputAnnotationOnSameLineCheckInterfaceAndEnum - 
tests for validity of annotations on interface and enum declarations
- InputAnnotationOnSameLineCheckPrivateAndDeprecatedVar - 
tests for validity of annotations on private var declarations and deprecations ( example : @SuppressWarnings )
- InputAnnotationOnSameLineCheckPublicMethodAndVariable - 
tests for validity of annotations on public method and var declarations
> Issue #14436: Enforced naming convention for annotaiononsameline

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescriptionOne.java
removed unnecessary //ok suppressions from nonemptyatclausedescription
This PR is for testing purposes, can be merged.
> Issue #13213: removed unnecessary //ok suppressions

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
issue #13999:
https://github.com/checkstyle/checkstyle/blob/8e76057c776b00ba718a3df6669e4e05f15f1399/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L255-L262
`javadocStyleCheck`
`.trim()` is redundant here the spaces at the end of the tag `<b      >` got trimmed already by the loop below. the spaces is not considered as  `JavaIdentifierPart` so the loops breaks when encounter a space
```
while (position < text.length()
&& Character.isJavaIdentifierPart(text.charAt(position))) {
position++;
}
```
and if there is a space at the start of the tag `<        b>` it is not considered as valid HTML tag and didn't even get passed to the TagParser 
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/83da30fe55de9d9465940675441ec003/raw/c939775415328f2bf39289ab7f6fc97717c …
> Issue #13999: Kill mutation in TagParser

- pom.xml
Issue #14485
Configure maven compiler level in a single place by using the default user property. Remove all duplicate properties. Use release instead of source and target, since that includes the API compatibility check.
> Issue #14485: should use release 11 for compilation

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckDefaultTokens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckMultipleExceptions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckSuperclassException.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckSuperclassThrowable.java
Part of #14436 
Renamed input files and test methods of annotationonsameline module to follow naming convention.
The following files test accordingly : 
-  InputIllegalCatchCheckDefaultTokens- 
tests for violations of default tokens in catch()
- InputIllegalCatchCheckMultipleExceptions- 
tests for violations in catch() holding multiple exceptions
- InputIllegalCatchCheckSuperclassThrowable- 
tests for violations related to usage of Superclass Throwable in catch()
- InputIllegalCatchCheckSuperclassException- 
tests for violations related to usage of Superclass Exception in catch()
> Issue #14436: Enforced naming convention for illegalcatch

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidinlineconditionals/InputAvoidInlineConditionals.java
Issue #13213 
Removed // ok comments from InputAvoidInlineConditionals.java and its suppressions
> Issue #13213: Remove '//ok' comments from Input files (avoidinlineconditionals)

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves  #14317:
update Javadoc example for `EMBEDDED_EXPRESSION*` tokens to  show how ` " ` are rendered in tree
> Issue #14317: update javadoc example for EMBEDDED_EXPRESSION* tokens

- .ci/checker-framework.groovy
- pom.xml
Resolve #14396
This PR enhances the GitHub Actions workflow for the Checker Framework by ensuring execution fails upon detecting errors during report generation.
> Issue #14396: checker-framework.yml should fail execution if report generation fails

- pom.xml
#14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/FormatStringConcatenation/ check.
> Issue #14137: Enable `FormatStringConcatenation` check

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ImmutabilityTest.java
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/RedundantStringConversion/ check.
> Issue #14137: Enable `RedundantStringConversion` check

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/StringJoin/ check.
> Issue #14137: Enable `StringJoin` check

- pom.xml
Issue #14137.
This PR enables the https://error-prone.picnic.tech/bugpatterns/Slf4jLogStatement/ check.
> Issue #14137: Enable `Slf4jLogStatement` check

- pom.xml
Closes  #14376 
@romani  , @nrmancuso 
In order to remove the parent pom usage, we needed to apply the parent pom's plugin config. See https://github.com/sonatype/oss-parents/blob/master/codehaus-parent/pom.xml for this configuration.
Without updating this configuration, we get the following error:
```
[ERROR] Project does not define required minimum version of Maven.
[ERROR] Update the pom.xml to contain maven-enforcer-plugin to
[ERROR] force the Maven version which is needed to build this project.
```
We also had failures in the [release-dry-run workflow](https://app.circleci.com/pipelines/github/checkstyle/checkstyle/23415/workflows/1abd9b3b-bf74-424b-afd6-cf50631e7dd2/jobs/497715?invite=true#step-103-22861_57):
```
launch (Launcher.java:226)
at …
```
> Issue #14376: Removed Parent POM & Updated maven-release-plugin Config to fix Broken mvn-Enforcer Config

- src/xdocs/releasenotes.xml
the latest releasenotes has line length violation
```
[INFO] [checkstyle] Running Checkstyle  on 2122 files
[ERROR] [checkstyle] [ERROR] /home/circleci/project/src/xdocs/releasenotes.xml:36: Line should not be longer than 100 symbols [lineLengthXml]
[INFO]      [echo] Checkstyle finished (checkstyle-checks.xml) : 28/02/2024 04:26:27 PM
[INFO]      [echo] Checkstyle started (checkstyle-non-main-files-checks.xml): 28/02/2024 04:25:09 PM
[INFO] [checkstyle] Running Checkstyle  on 4368 files
[ERROR] [checkstyle] [ERROR] /home/circleci/project/src/xdocs/releasenotes.xml:36: Line should not be longer than 100 symbols [lineLength]
```
> doc: fix line length violation in releasenotes.xml

- config/pitest-suppressions/pitest-coding-1-suppressions.xml
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/VariableDeclarationUsageDistanceTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/InputVariableDeclarationUsageDistanceCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceCloseToBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceLabels.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceScopes.java
Resolves #3502:
- updated VariableDeclarationUsageDistance to do violation to move variables closer to the block
- updated corresponding tests to match the new functionality of the check
I will generate 2 reports difference is expected for report-2
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/ce878f7db10dd474a7f6aa53ada50c7c/raw/68d7ec7bcef08b49d6deaa712d2e18cf8c328dcd/check1.xml
Report label: report-2
I generated two report
- [report-1](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/17c1f8f_2024173315/reports/diff/index.html) (no diff) with this [config](https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/e82a7576e6372a18bb4794217b6713b475f0e4f9/check.xml) to check that the check behavior didn't change when …
> Issue #3502: update VariableDeclarationUsageDistance to do violation to move variables closer to block

- config/intellij-idea-inspections.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionExecutableStatementCountTest.java
We leaked an inspections failure from being too comfortable with failing inspections. This PR fixes inspection's complaint and disables the inspection that keeps failing.
Leaked in PR: https://github.com/checkstyle/checkstyle/pull/14578
Link to build: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/24261/workflows/30c63bd9-0623-4723-814f-1afb0c072212/jobs/534230/artifacts
```
<problems is_local_tool="true">
<problem>
<file>file://$PROJECT_DIR$/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionExecutableStatementCountTest.java</file>
<line>125</line>
<module>project</module>
<package>org.checkstyle.suppressionxpathfilter</package>
<entry_point TYPE="method" FQNAME="org.checkstyle.suppressionxpathfilter.XpathRegressionExecutableStatementCountTest void …
```
> minor: fix inspections violation

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue: #14516 
Parameters.java used for conversion
```
public class Parameters {
public void function(int start, int end) {
}
}
```
Converted to AST using:
`java -jar checkstyle-10.13.0-all.jar -t Parameters.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'`
Output:
```
|--IDENT -&gt; Parameters
|--METHOD_DEF -&gt; METHOD_DEF
|   |--MODIFIERS -&gt; MODIFIERS
|   |   `--LITERAL_PUBLIC -&gt; public
|   |--TYPE -&gt; TYPE
|   |   `--LITERAL_VOID -&gt; void
|   |--IDENT -&gt; function
|   |--LPAREN -&gt; (
|   |--PARAMETERS -&gt; PARAMETERS
|   |   |--PARAMETER_DEF -&gt; PARAMETER_DEF
| …
```
> Issue #14516: Update TokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue: #14516 
**SingleLineComment.java** used for conversion
```
public class SingleLineComment {
//
}
```
Converted to AST using: 
`java -jar checkstyle-10.13.0-all.jar -T SingleLineComment.java | sed 's/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g'`
Output:
```
|--IDENT -&gt; SingleLineComment
|--SINGLE_LINE_COMMENT -&gt; //
|   `--COMMENT_CONTENT -&gt; \r\n
`--RCURLY -&gt; }
```
> Issue #14516: Updated single line comment in TokenTypes.java to AST

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/xdocs/writingchecks.xml
Aims to close #14516
EDIT : Changed link to TokenTypes of our docs to be more specific
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html
Updated Inputs based on suggestions from review :
```
E:\MANISH\Workspace>cat Test.java
import java.util.List;
List<String> l = new ArrayList<String>();
}
```
```
E:\MANISH\Workspace>cat Test.java
String[] strings = new String[3];
}
```
```
E:\MANISH\Workspace>cat Test.java
public abstract class Supplier<Integer> {
public abstract Integer get();
}
Supplier<Integer> s = new Supplier<>() {
@Override
public Integer get() {
return 42;
}
};
}
```
// Outdated Inputs used previously : 
```
float[] test = new …
```
> Issue #14516: Updated LITERAL_NEW outdated examples and AST of TokenTypes.java to new format of AST print

- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountCustomMaxCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountMaxAllowZero.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountNotIgnorePrivateMethods.java
Part of Issue #14436 
This PR is for testing resolved issues with failing CI of circleci workflow `no-error-xwiki`
We've had a failing CI of workflow related to `xwiki`
Investigation of the issue led me to the following error :
Before merge of  PR https://github.com/xwiki/xwiki-platform/pull/2934 : 
```
[INFO] Starting audit...
[ERROR] /home/circleci/project/.ci-temp/xwiki-platform/xwiki-platform-core/xwiki-platform-notifications/xwiki-platform-notifications-rest/src/main/java/org/xwiki/notifications/rest/NotificationsResource.java:131: Line is longer than 120 characters (found 123). [LineLength] Audit done.
[INFO] There is 1 error reported by Checkstyle 10.14.0-SNAPSHOT with checkstyle.xml ruleset. [ERROR] src/main/java/org/xwiki/notifications/rest/NotificationsResource.java:[131] …
```
> Issue #14436: Rename ThrowsCount test input files and test methods to specify Test functionality

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionParameterAssignmentTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameterassignment/SuppressionXpathRegressionParameterAssignmentCtor.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameterassignment/SuppressionXpathRegressionParameterAssignmentLambdas.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameterassignment/SuppressionXpathRegressionParameterAssignmentMethods.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #6207 
Added new Xpath IT Regression test for ParameterAssignmentCheck
The check doesn't involve usage of config properties. So, created two files for different scenarios
`Update` : Created one more file to show violations in _**Ctor**_ parameter assignment.
> Issue #6207: Added Xpath IT Regression test for ParameterAssignmentCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeRecordParamDescriptionWithAngularTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeParamDescriptionWithAngularTags.java
Resolves https://github.com/checkstyle/checkstyle/issues/13309
<hr>
**Regression:** ([Report](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/0fbf9da_2024125210/reports/diff/index.html)) No Differences Found
Expected to have some differences(specifically removed violations) as we have fixed a false positive,
but we do not see any due the very specific scope of this false positive. ([Reference](https://github.com/checkstyle/checkstyle/issues/13309#issuecomment-1971651949))
The fix is working as intended and can be verified using the added test inputs, which previously would have produced a false violation.
Diff Regression config: https://gist.githubusercontent.com/sktpy/44a31ea4e946a0755fa3e331fd65de98/raw/df79e294a1b3f1fc37a6fdc971273c2dd746cea2/check.xml
> Issue #13309: False positive error from JavadocType with record

- pom.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/FilterUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/XpathUtilTest.java
Resolves: #14465
This PR aims to get rid of `Files.createTempFile` methods.
> Issue #14465: Refactor to exclude createTempFile methods

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Begins #14631 
```
E:\MANISH\Workspace>cat Test.java
/**
* Some Java doc.
*
* @param p1 The first number
* @deprecated It is deprecated method
*/
@Deprecated
private int boo(int p1) {
return p1;
}
}
E:\MANISH\Workspace>java -jar checkstyle-10.13.0-all.jar -J Test.java | sed "s/->/-\&gt;/g; s/\[[0-9]\+:[0-9]\+\]//g"
|--IDENT -&gt; Test
|--METHOD_DEF -&gt; METHOD_DEF
|   |--MODIFIERS -&gt; MODIFIERS
|   |   |--ANNOTATION -&gt; ANNOTATION
|   |   |   |--BLOCK_COMMENT_BEGIN -&gt; /*
|   |   |   |   |--COMMENT_CONTENT -&gt; *\n   * Some Java doc.\n   *\n   * @param p1 …
```
> Issue #14631: Updated DEPRECATED_LITERAL of JavadocTokenTypes to new AST format

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepthCheckCustomMaxLevelFour.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepthCheckCustomMaxLevelTwo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepthCheckDefaultMaxLevel.java
> Issue #14436: Enforced naming convention for  `NestedForDepthCheckTest`

- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_ru.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_zh.properties
Part of #3110 
All hardcoded messages in finishLocalSetup  method of Checker.java have been removed and replaced with keys pointing to respective messages.properties files to support non-locale translations.
I have used Google translate to extract translations of the messages.
PS : Simplified Chinese has been used for messages_zh.properties
> Issue #3110: BugFix in Checker.java removed hardcoded exception messages of finishLocalSetup method

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTreeLastVariableResourcesStatementEnd1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTreeLastVariableResourcesStatementEnd2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineBeginTreeTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTryWithResources.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTryWithResourcesIgnore.java
Part of Issue: #13213
1. Remove "// ok" comments from 6 classes under onestatementperline.
2. Remove corresponding suppress statements in config/checkstyle-input-suppressions.xml
> Issue #13213: Remove "// ok" from onestatementperline

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestAloneOrSinglelineTryCatchBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTryWithResourceAloneSingle.java
Resolves #12020:  
tryBlock at single line was raising a violation in `ALONE_OR_SINGLELINE`  option
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/b3282ceb40c5ca4a56ede9f6c5194a3f/raw/bb787f9f9d73023e38b43faae582a6e4f9d6d20d/rightcurly.xml
[report](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/9179d1b_2024114344/reports/diff/index.html) expected difference. violation has been removed for all single line try-catch blocks when `ALONE_OR_SINGLELINE`  option
> Issue #12020: False positive in RightCurly with 'alone_or_singleline'

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionVisibilityModifierTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/SuppressionXpathRegressionVisibilityModifierAnnotation.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/SuppressionXpathRegressionVisibilityModifierAnonymous.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/SuppressionXpathRegressionVisibilityModifierDefault.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/SuppressionXpathRegressionVisibilityModifierInner.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of Issue #6207. Add XPath Regression Test for VisibilityModifier
Documentation of VisibilityModifier: https://checkstyle.sourceforge.io/checks/design/visibilitymodifier.html
Hi, I am not sure whether these tests are sufficient enough to cover VisibilityModifier, could you please have a look.
Currently, there are tests for
1. field with default modifier
2. field with the annotation
3. field inside an anonymous class
4. field inside an inner class
> Issue #6207: Add XPath IT Regression for VisibilityModifier

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocStyleCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleDefaultSettingsFive.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/Example1.txt
- src/xdocs/checks/javadoc/javadocstyle.xml
- src/xdocs/checks/javadoc/javadocstyle.xml.template
Solves https://github.com/checkstyle/checkstyle/issues/12600
Since inline `@return` tag is the only inline tag that automatically inserts a period after the text, we can modify check method to determine if the first sentence was `{@return something}`
CLI:
```
<module name="JavadocStyle"/>
</module>
</module>
class Test {
/**
* {@return a string}
*/
String foo() {
return "Hello, world";
}
}
$ java -jar checkstyle-10.10.1-SNAPSHOT-all.jar -c config.xml Test.java
Audit done.
``` …
> Issue #12600: Modify javadocstyle check to work with inline return

- config/pitest-suppressions/pitest-common-suppressions.xml
- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checker/InputCheckerTestSeverity.java
Issue #14019 Kill mutation for setSeverity in checker
created a test case to kill the mutation
> Issue #14019: Kill mutation for setSeverity in Checker

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Part of Issue #14631 
```
E:\MANISH\Workspace>cat Test.java
/**
* Some Java doc.
*
* @param p1 The first number
* @deprecated It is deprecated method
*/
@Deprecated
private int boo(int p1) {
return p1;
}
}
E:\MANISH\Workspace>java -jar checkstyle-10.13.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--LCURLY -> {
|--METHOD_DEF -> METHOD_DEF
|   |--MODIFIERS -> MODIFIERS
|   |   |--ANNOTATION -> ANNOTATION
|   |   |   |--BLOCK_COMMENT_BEGIN -> /*
|   |   |   |   |--COMMENT_CONTENT -> *\n   * Some Java doc.\n   *\n   * @param p1 The first number\n   * @deprecated It is …
```
> Issue #14631: Updated DEPRECATED_LITERAL of JavadocTokenTypes to new AST format (->)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/GenericWhitespaceCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeRecordHeader.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/Example1.txt
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/Example2.txt
- src/xdocs/checks/whitespace/genericwhitespace.xml
- src/xdocs/checks/whitespace/genericwhitespace.xml.template
Resolves #14502 
Reasoning for the changes are mentioned in the comments.
Old Doc([site](https://checkstyle.org/checks/whitespace/genericwhitespace.html)), New Doc([site](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/05dd30d_2024155912/checks/whitespace/genericwhitespace.html#Description))
<hr>
Differences found (expected)
- **Added Violations (4)**: Example (rest occurrences are similar) ([link](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e3fa404_2024081446/reports/diff/checkstyle/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/checkstyle/src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordtypeparametername/SuppressionXpathRegressionRecordTypeParameterName1.java.html#L7))
This is intended …
> Issue #14502: Handling of whitespace between generic and record header (GenericWhitespaceCheck)

- config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
part of #13999 
Explanation - All the Overridden implementation of the method `getRequiredJavadocTokens()` are of length more than 0.
Diff Regression config: https://gist.githubusercontent.com/TanayMorakhia/431cb93bf15c238967db9914a3d164ec/raw/575ff26646e5f029e9f9053a8878f27859bb186b/AbstractJavaDocCheck.xml
Diff Regression projects: https://gist.githubusercontent.com/TanayMorakhia/f3a248e4d705e5b3e0defe44c8bc8452/raw/6a2871822b807d93bcb58a449f79d94a55702f35/project.properties
> Issue #13999: Resolve pitest suppression for validateDefaultJavadocTokens method of AbstractJavadocCheck

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionLocalFinalVariableNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/localfinalvariablename/SuppressionXpathRegressionLocalFinalVariableNameInner.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/localfinalvariablename/SuppressionXpathRegressionLocalFinalVariableNameResource.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/localfinalvariablename/SuppressionXpathRegressionLocalFinalVariableNameVar.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath regression test for LocalFinalVariableName

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameExamplesTest.java
Refactor for Issue #14653.
Updates:
1. Directly use configuration parsed from XML headers
2. Change `testInputConfiguration.createConfiguration()` to `testInputConfiguration.getConfiguration()`
Todo:
Delete `handleXmlConfig()` since it is not used anymore.
I have marked this PR as a draft. Please check it to see whether I am on the right track @romani
> Issue #14653: support XML configs without detalization

- pom.xml
Fixes Issues #14123 and #14211 by also excluding google-collections from doxia-module-xdoc.
A previous fix (#14140) removed google-collections from doxia-core, but doxia-module-xdoc also contains google-collections as a transitive dependency.
> Issue #14123: Exclude google-collections from doxia-module-xdoc

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskValid.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskValidWithTab.java
Part of Issue: https://github.com/checkstyle/checkstyle/issues/13213
Remove "// ok" comments from 4 classes under javadocmissingwhitespaceafterasterisk.
Remove corresponding suppress statements in config/checkstyle-input-suppressions.xml
> Issue #13213: Remove "// ok"  from javadocmissingwhitespaceafterasterisk

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_ru.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/messages_zh.properties
Part of #3110 
The following methods required message keys : 
- processFiles (Exception msg)
- setupChild
- setCharset
Checker.java file now has only two more hardcoded strings left to completely be compatible with non-locale translations : 
1. destroy
2. processFiles (Error msg)
For maximum code optimization, I've designed a new method  `getLocalizedMessage` that takes in a String arg `messageKey` and returns another String `localizedMessage` that is extracted from _.properties_ files instead of returning _LocalizedMessage_ object, to make things even more simpler.
Thanks a lot @rdiachenko, for pointing this out coz, reused and optimized code is obviously the best !!
> Issue #3110: Bugfix in Checker.java removed English hardcoded msgs & Added new method to extract non-locale translations

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java
Part of issue #14084.
Remove violation suppression for `XpathQueryGenerator` by adding `@Nullable`
> Issue #14084: fix Checker violation with nullness

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionParameterNumberTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/parameternumber/SuppressionXpathRegressionParameterNumberIgnoreAnnotatedBy.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/ParameterNumberCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberIgnoreAnnotatedBy.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberIgnoreAnnotatedByFullyQualifiedClassName.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/Example4.txt
- src/xdocs/checks/sizes/parameternumber.xml
- src/xdocs/checks/sizes/parameternumber.xml.template
Resolves #11340 
Old Doc([site](https://checkstyle.org/checks/sizes/parameternumber.html)), New Doc([site](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/4cc9297_2024153913/checks/sizes/parameternumber.html#Properties))
<hr>
**Differences Found** (expected):
`Deprecated` is used as the value for the `ignoreAnnotatedBy`(selected for the purpose that it would produce some differences being a commonly used annotation)
**Removed violations** (**22**): Example ([link](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a62d9ca_2024194155/reports/diff/guava/xref/home/runner/work/checkstyle/checkstyle/.ci-temp/contribution/checkstyle-tester/repositories/guava/android/guava/src/com/google/common/collect/ImmutableSortedMapFauxverideShim.java.html#L107)), rest of the occurrences …
> Issue #11340: Add ignoreAnnotatedBy property to ParameterNumberCheck

- .cirrus.yml
https://github.com/cirruslabs/cirrus-ci-docs/discussions/1269#discussioncomment-8841674
From CI:
>No tasks were found for the build. Either only_if expressions excluded all of the tasks and/or Starlark script did not generate any tasks.
> infra: Update .cirrus.yml to skip execution on PR

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
issue #13999:
https://github.com/checkstyle/checkstyle/blob/d43ccb86e7b3dd82aee759851b184aa4f899317a/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L30-L37
All checks that are a subclass of  `AbstractJavadocCheck`
this condition reported by Pitest is ok to remove and won't affect the function behavior. we traverse the tree to look for interested nodes for the checks we get the child of the node first if the child is null we enter this loop to search for the sibling instead of the child and then update the curr node  with the sibling
```
while (curNode != null && toVisit == null) {
if (waitsForProcessing) {
leaveJavadocToken(curNode);
}
toVisit = JavadocUtil.getNextSibling(curNode);
curNode = curNode.getParent();
if (curNode != null) {
waitsForProcessing = …
```
> Issue #13999: Kill mutation in AbstractJavadocCheck

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptyIsFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptySmallSize.java
Issue #13213
Removed "//ok" comments from 
"InputMethodLengthCountEmptyIsFalse.java" and "InputMethodLengthCountEmptySmallSize.java" files
and also removed respective suppressions
> Issue #13213: Remove '//ok' comments from methodlength

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLengthDefault.java
Part of Issue https://github.com/checkstyle/checkstyle/issues/13213
Updates
Removed filelength suppresion rules from checkstyle-input-suppressions.xml
Removed unnecessary // ok from all previously suppressed java files accordingly
> Issue #13213: Remove "// ok" from filelength 

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMethodTypeParameterNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodtypeparametername/SuppressionXpathRegressionMethodTypeParameterName1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodtypeparametername/SuppressionXpathRegressionMethodTypeParameterName2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodtypeparametername/SuppressionXpathRegressionMethodTypeParameterName3.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #6207: Add Xpath regression test for MethodTypeParameterName

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionVisibilityModifierTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/InputXpathVisibilityModifierAnnotation.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/InputXpathVisibilityModifierAnonymous.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/InputXpathVisibilityModifierDefault.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/visibilitymodifier/InputXpathVisibilityModifierInner.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #14715 
Enforced new naming convention on visibilitymodifier in IT area
> Issue #14715: Enforced new naming convention on visibilitymodifier in IT area

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java
Supplemental for #6723 
Refactored misaligned leading asterisks in javadoc comments.
> supplemental: refactor misaligned leading asterisks in javadoc comments

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMethodTypeParameterNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodtypeparametername/InputXpathMethodTypeParameterNameDefault.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodtypeparametername/InputXpathMethodTypeParameterNameInner.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodtypeparametername/InputXpathMethodTypeParameterNameLowercase.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #14715 
rename xpath it regression input files in MethodTypeParameterName module
> Issue #14715: Enforce new naming convention on methodtypeparametername in IT area

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthMax.java
Issue #13213
Removed "//ok" comments from "InputLambdaBodyLengthMax.java" file 
and also removed respective suppressions
> Issue #13213: Remove '//ok' comments from lambdabodylength

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordTypeParameterNameTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordtypeparametername/InputXpathRecordTypeParameterNameTypeDeclared.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordtypeparametername/InputXpathRecordTypeParameterNameTypeDefault.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
> Issue #14715: Enforce new naming convention on RecordTypeParameterName in IT area

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/UnusedImportsCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromStaticMethodRef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromStaticMethodRefExtended.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromStaticMethodRefInDocsOnly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromStaticMethodRefJavadocDisabled.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/Example2.java
- src/xdocs/checks/imports/unusedimports.xml
- src/xdocs/checks/imports/unusedimports.xml.template
Issue #12923:  
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/9516feffda197f31ee9b3da072e72161/raw/dc487895b45335b66942657e474a592d115ba3b8/imports.xml
> Issue #12923: static imports with method reference reported as unused

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses7.java
Fix for Issue #14092
```Java
int a = 12;
void foo() {
int a = 12; // this is unused, no violation
int ab = 12; // this is unused, violation thrown
class asd {
Test a = new Test() {
void asd() {
System.out.println(a);
}
};
}
}
}
```
Update:
modify `addLocalVariables()` to also push a variable that has a grandparent of type `TokenTypes.CLASS_DEF` into the variable stack.
Cause of the problem: 
For `Test a = new Test()`, `a` is not pushed into the stack, because `isInstanceVarInAnonymousInnerClass` condition is not met. However, `a` in this case should meet this condition and be pushed to the stack. Because of that, when the visitor goes through `System.out.println(a);`, it marks the wrong variable `a` as used. …
> Issue #14092: fix UnusedLocalVariableCheck to support local classes

- .circleci/config.yml
- src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/SinglelineDetector.java
- src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java
Aims to close https://github.com/checkstyle/checkstyle/issues/14448
Follow-up of  #14604 and https://github.com/checkstyle/contribution/pull/837
Based on observations from https://github.com/checkstyle/checkstyle/pull/14604#discussion_r1530584190 and further discussions.
The latest IDEA release that we have used for update (2023.3.4) had issues with scopes.
A bit of research on different versions landed me on `v2022.3.3` being stable and good with scopes.
Link to docker image (personal) for testing update : 
https://hub.docker.com/layers/manishkk07/manish-k-07-checkstyle/jdk11-idea2022.3.3/images/sha256-3a659714655f8e033e648d894ac20eb110a0aa557f0f19821366cb54e4089305?context=repo
To pull image : `docker pull manishkk07/manish-k-07-checkstyle:jdk11-idea2022.3.3`
> Issue #14448: Migrated IDEA to highest true scopes release v2022.3.3

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/checkstyle-checks.xml
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCasesBlocks.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/RightCurlyCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchExpressionAlone.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchExpressionAloneOrSingleline.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchRuleAlone.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchRuleAloneOrSingleline.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksInSwitchStatementAlone.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksInSwitchStatementAlone2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksInSwitchStatementAloneOrSingleline.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksInSwitchStatementAloneOrSingleline2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksInSwitchStatementSame.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksInSwitchStatementSame2.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/Example5.java
- src/xdocs/checks/blocks/rightcurly.xml
- src/xdocs/checks/blocks/rightcurly.xml.template
Resolves #14620 :
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/c82dbc1b4a05567e245729eccfc6cf62/raw/c4958b5ee00ded9c8f89d3af0a50fa871b352205/rcurlybase.xml
Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/fb26eda6b5a3264c0c42351e612cc4f6/raw/daf318509889f654cd61d58c9e039c9ba1505716/rcurlypatch.xml
- alone option ([link](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ddf54a1_2024014514/reports/diff/index.html))
- alone_or_singleline option ([link](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ddf54a1_2024024511/reports/diff/index.html  ))
- same option ([link](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ddf54a1_2024001633/reports/diff/index.html))
> Issue #14620:  `LITERAL_CASE` token support in RightCurlyCheck

- config/intellij-idea-inspections.xml
#14448 has been closed via #14696 
We had disabled `YAMLSchemaValidation` and was referenced to old issue.
https://github.com/checkstyle/checkstyle/blob/0707dd5ac38b2f0fd4af9941070ea2615c17f335/config/intellij-idea-inspections.xml#L4109-L4111
This PR updates linked issue to #14806
> minor: fix failing CI check_issues by referencing new issue link

- src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
Part of #14625 
Deals with one problem of **OptionalGetWithoutIsPresent** inspection.
```
<problem>
<file>file://$PROJECT_DIR$/src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java</file>
<line>114</line>
<module>project</module>
<package>com.puppycrawl.tools.checkstyle</package>
<entry_point TYPE="method" FQNAME="com.puppycrawl.tools.checkstyle.JavaParserTest void testAppendHiddenSingleLineCommentNodes()"/>
<problem_class id="OptionalGetWithoutIsPresent" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Optional.get() is called without isPresent() check</problem_class>
<description><code>Optional.get()</code> without 'isPresent()' check</description>
<highlighted_element>get</highlighted_element>
<language>JAVA</language>
<offset>52</offset>
<length>3</length>
</problem> …
```
> Issue #14625: fix inspection violation OptionalGetWithoutIsPresent JavaParserTest testSingleLineComment

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclarationWithAnnotation.java
Fix for Issue #14788
What analyzed in https://github.com/checkstyle/sonar-checkstyle/issues/519#issuecomment-2051912553 is correct.
Diff Regression config: https://gist.githubusercontent.com/Lmh-java/86f88c7301a73bd5b6d9a5edc54d2683/raw/fcd872371461b8cc978230d1e03395add2d51027/magic-number-config-2.xml
> Issue #14788: fix NPE for MagicNumberCheck

- src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
Part of #14625 
Fixes all inspection violations related to **OptionalGetWithoutIsPresent**.
https://output.circle-artifacts.com/output/job/e65c9574-61a6-4a48-8d9a-3b8206e5ad29/artifacts/0/home/circleci/project/target/inspection-results/OptionalGetWithoutIsPresent.xml
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/1/workflows/0968f80e-db8e-401a-ad87-8c409072ba31/jobs/574793/artifacts
> Issue #14625: fix inspection violations OptionalGetWithoutIsPresent

- src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
Part of #14625 
Deals with **MismatchedJavadocCode** inspection.
```
<problems is_local_tool="true">
<problem>
<file>file://$PROJECT_DIR$/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java</file>
<line>450</line>
<module>project</module>
<package>com.puppycrawl.tools.checkstyle.ant</package>
<entry_point TYPE="method" FQNAME="com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask com.puppycrawl.tools.checkstyle.api.AuditListener[] getListeners()"/>
<problem_class id="MismatchedJavadocCode" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Mismatch between Javadoc and code</problem_class>
<description>Method is specified to return list but the return type is array</description>
<highlighted_element>list</highlighted_element>
<language>JAVA</language> …
```
> Issue #14625: fixed inspections violations MismatchedJavadocCode

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
This removes an if condition, and moves the if condition inside the method call to the outside. Nothing else was changed besides indentation.
The conditions we removed/moved before this change basically amounts to:
> TokenUtil.isTypeDeclaration && isNonLocalTypeDeclaration
[`isNonLocalTypeDeclaration`](https://github.com/checkstyle/checkstyle/blob/55f5c966bfa61b387110db6c4780f259a21676c8/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java#L389) is basically:
> TokenUtil.isTypeDeclaration && !slist
So basically we are calling `TokenUtil.isTypeDeclaration` twice, and my changes remove the extra call.
Also, this code is in the `visitToken` and this change [aligns us with the `leaveToken` which has the same if condition …
> minor: removes extra method call from UnusedLocalVariableCheck

- .ci/check-performance-regression.sh
- .github/workflows/check-performance-regression.yml
- config/benchmark-config.xml
> Issue #14599: Create performance regression test CI

- .github/workflows/check-performance-regression.yml
https://github.com/checkstyle/checkstyle/actions/runs/8934444831/job/24541391465?pr=14779#step:6:9
```
0s
Run cd checkstyle
cd checkstyle
bash ./.ci/check-performance-regression.sh
shell: /usr/bin/bash -e {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.22-7/x64
JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.22-7/x64
bash: ./.ci/check-performance-regression.sh: No such file or directory
```
> infra: update check-performance-regression.yml to have no extra folder

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
```$ cat Test.java
/**
* This class represents a Test object.
*
* @version 1.3
*/
}
$ java -jar checkstyle-10.15.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * This class represents a Test object.\r\n *\r\n * @version 1.3\r\n
|   |   |       |--TEXT ->  This class represents a Test object.
|   |   | …
```
> Issue #14631: Updated Version literal to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
**Command used:**` java -jar checkstyle-10.14.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Output:**
```
|   |   |--COMMENT_CONTENT -> *\r\n * Some javadoc\r\n *\r\n * @since 3.4 RELEASE\r\n
|   |   |       |--TEXT ->  Some javadoc
|   |   |       |   |--SINCE_LITERAL -> @since
|   | …
```
> Issue #14631: update SINCE_LITERAL in JavadocTokenTypes.java to new format of AST print #14631

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
`java -jar checkstyle-10.16.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* @author Baratali Izmailov
*/
}
```
```
SteLeo@DESKTOP-11C7U5R MINGW64 ~/author_literal AST
$ java -jar checkstyle-10.16.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * @author Baratali Izmailov\r\n
|   |   |       |   |--AUTHOR_LITERAL -> @author
|   |   | …
```
> Issue #14631: Updated author_literal in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
```
SteLeo@DESKTOP-11C7U5R MINGW64 ~/exception_literal test
* @exception SQLException if query is not correct
SteLeo@DESKTOP-11C7U5R MINGW64 ~/exception_literal test
$ java -jar checkstyle-10.16.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--LEADING_ASTERISK -> *
|--WS ->
|--JAVADOC_TAG -> JAVADOC_TAG
|   |--EXCEPTION_LITERAL -> @exception
|   |--WS ->
|   |--CLASS_NAME -> SQLException
|   |--WS ->
|   `--DESCRIPTION -> DESCRIPTION
|       `--TEXT -> if query is not correct
`--EOF -> <EOF>
SteLeo@DESKTOP-11C7U5R MINGW64 ~/exception_literal test
$
```
> Issue #14631: Updated exception_literal to new AST format

- .ci/validation.sh
do it like just
```
✔ ~/java/github/romani/checkstyle
$ ./.ci/validation.sh --list
Supported tasks:
all-sevntu-checks
assembly-run-all-jar
check-missing-pitests
check-since-version
checkstyle-and-sevntu
check-wildcards-on-pitest-target-classes
ci-temp-check
eclipse-static-analysis
git-check-pull-number
git-diff
git-no-merge-commits
jacoco
javac11
javac14
javac15
javac16
javac17
javac19
javac20
javac21
--list
markdownlint
no-error-checkstyles-sevntu
no-error-contribution
no-error-equalsverifier
no-error-hibernate-search
no-error-htmlunit
no-error-methods-distance
no-error-orekit
no-error-pgjdbc
no-error-pmd
no-error-sevntu-checks
no-error-spotbugs
no-error-spring-cloud-gcp
no-error-spring-integration
no-error-strata
no-error-test-sbe
no-error-xwiki
no-exception-alot-of-projects …
```
> infra: make --list for validation.sh

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
First step for #12586:   
this is not the final fix I just want to make sure that I am on the right direction also I faced some errors want to discuss them. IMO once this optimization is completed and reaches its final form, it will provide significant benefits. specifically aims to improve the process of ` mvn test` and `mvn clean verify.`
> Issue #12586: Optimize testing methods to run check one time over a file

- .github/workflows/check-performance-regression.yml
> Issue #14852: Fix performance test

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
```prath@LAPTOP-5K4C7SC4 /cygdrive/c/Users/prath/Downloads
/**
* Javadoc.
*
*@see org.apache.utils.Lists.Comparator#compare(Object)
*/
public void testFunction() {}
}
prath@LAPTOP-5K4C7SC4 /cygdrive/c/Users/prath/Downloads
$ java -jar checkstyle-10.15.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--LCURLY -> {
|--METHOD_DEF -> METHOD_DEF
|   |--MODIFIERS -> MODIFIERS
|   |   |--BLOCK_COMMENT_BEGIN -> /*
|   |   |   |--COMMENT_CONTENT -> *\r\n     * Javadoc.\r\n     *\r\n     *@see org.apache.utils.Lists.Comparator#compare(Object)\r\n
|   |   | …
```
> Issue #14631: Updated See literal to new AST format

- config/jsoref-spellchecker/whitelist.words
- src/xdocs/beginning_development.xml
Added link to the playlist of my video tutorials
> doc: Added link to the video instructions on beginning development page

- config/pmd-main.xml
- config/pmd-test.xml
- config/pmd.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
```
[INFO] BUILD FAILURE
[INFO] Total time:  01:34 min
[INFO] Finished at: 2024-05-04T02:56:07+02:00
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.22.0:pmd (pmd) on project checkstyle: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.22.0:pmd failed: org.apache.maven.reporting.MavenReportException: The ruleset could not be loaded: Cannot load ruleset config/pmd.xml: An XML validation error occurred -> [Help 1]  
[ERROR]
```
I assumed that this is because we using [rules that were removed](https://docs.pmd-code.org/latest/pmd_release_notes_pmd7.html#removed-rules) in the latest pmd …
> dependency: bump pmd.version to 7.1.0 and maven-pmd-plugin to 3.22.0

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckExamplesTest.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java
- src/xdocs/checks/coding/innerassignment.xml
- src/xdocs/checks/coding/innerassignment.xml.template
Resolves #13086 :
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/70e0fb4b76668949fd9e0fd3744deddd/raw/0b035184445fee1009e49543af7b1daa6b52f79f/innerass.xml
Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/297d7353d2d0bcec178e1b098109cd9e/raw/546dcdbdff363110fa265ea80d70e36f079c6ee8/projects-to-test-on.properties
> Issue #13086: fix InnerAssignmentCheck In SwitchRuleAndExpression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableSwitchExpression.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableSwitchStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableSwitchStatement2.java
Issue #14506: False positive for UnusedLocalVariable
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/0dbdfb487f8e9a050ed0e6356f1a35b4/raw/31f7927f400e11e4285e86fd086b373095227848/unusedLocal.xml
> Issue #14506: False positive for UnusedLocalVariable

- config/signatures.txt
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/configurationloader/æ£µ¥/InputConfigurationLoaderDefaultProperty.xml
Closes #13012
Attempt number 3 to fix this issue
> Issue #13012: fix loading with non-ascii symbols in path

- .ci/test-spelling-unknown-words.sh
Added additional details to the message to clarify for the beginners what they need to do exactly and ensure they won't confuse the command with the rest of the report.
> spelling: added detailed message to spelling test script

- config/checkstyle-resources-suppressions.xml
- config/jsoref-spellchecker/whitelist.words
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/NeedBracesTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/InputNeedBraces.java
- src/xdocs/google_style.xml
Issue #14908 
Renamed section `4.1.1` from ` Braces are used where optional` to `Use of optional braces` and referenced it to the new cached page.
Created test cases for lambdas to ensure that if we ever update config of this rule, we will be ignoring `lambdas` as per the newly paragraph added here:
https://github.com/checkstyle/checkstyle/pull/14901/files#diff-3f79fa1ed75e6db042f0bb87505b89c47280f86dc510d90ed8d039c77869ce33R264
> Issue #14908: Renamed section 4.1.1 and created test cases for lambdas

- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/ConstructorsDeclarationGroupingTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/OverloadMethodsDeclarationOrderTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputConstructorsDeclarationGroupingRecords.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputConstructorsDeclarationGrouping.java
- src/main/resources/google_checks.xml
- src/xdocs/checks/coding/constructorsdeclarationgrouping.xml
- src/xdocs/checks/coding/constructorsdeclarationgrouping.xml.template
- src/xdocs/google_style.xml
Issue #14907 
This PR contains following:
- Added [ConstructorsDeclarationGrouping](https://checkstyle.org/checks/coding/constructorsdeclarationgrouping.html#ConstructorsDeclarationGrouping) module in google_checks.xml.
- Created test cases for it.
- Updated the coverage page, added new config & test links and updated the style guide reference to the new cached page.
> Issue #14907: Add support to check grouping of constructors in google style guide implementation

- config/jsoref-spellchecker/whitelist.words
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/MissingSwitchDefaultTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/InputMissingSwitchDefault.java
- src/xdocs/google_style.xml
Issue #14909 
Renamed section `4.8.4.3` of google style guide implementation from `The default case is present` to `Presence of the default label` and referenced to the new cached page.
Renamed test folder from `rule4843defaultcasepresent` to `rule4843defaultlabelpresence` also.
> Issue #14909: Renamed section 4.8.4.3 of google style guide implementation

- src/xdocs/google_style.xml
Issue #14938 
Updated google style coverage page, removed the `JSNI could not be detected` message in section `4.4 Column Limit: 100` and added a new message indicating that it will be not supported by us with the issue link which contains all the discussion.
> Issue #14938: Updated the google style coverage page regarding JSNI method

- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/SingleLineJavadocTest.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocCheck.java
- src/xdocs/google_style.xml
issue #14947 
updated google documentation for section 7.1.1, removed ok_blue.png and added ok_green.png and updated the test case for `@return` in single line javadoc comment
> Issue #14947: updated documentation and test case for section 7.1.1

- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/SummaryJavadocTest.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputIncorrectSummaryJavaDocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SummaryJavadocCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocForbiddenFragmentRelativeToPeriod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocJapanesePeriod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriodAtEnd.java
- src/xdocs/checks/javadoc/summaryjavadoc.xml
- Resolves: #14689
- Resolves: #14750
- Resolves: #14751
Handle cases where first sentence of Javadoc is on its own line.
Handle cases where first sentence of Javadoc includes a period character without whitespace after it.
original-Diff Regression config: https://gist.githubusercontent.com/patchwork01/d62651d8467212daf75aff8100e813c1/raw/ac03b5b7fbcbee95f7508e40462ce97d72dfc550/my_check.xml
jp-period-Diff Regression config: https://gist.githubusercontent.com/romani/3a9b1b47b71ad0a9f5583a738ff4710c/raw/862494acad8497fb3129d7893dd1438ebf48c7b8/my_check-pr-14690.xml
jp-period-Diff Regression projects: https://gist.githubusercontent.com/romani/edc0f152b7dd10118e6bc395bb1e62af/raw/c8cc30b749d4c27b94fa219b701120f1bca4a435/pull-14690-projects.properties
Prev-Diff Regression config: …
> Issue #14689: Prevent false positives when first sentence of Javadoc is on its own line

- config/jsoref-spellchecker/whitelist.words
- config/sevntu-suppressions.xml
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ClassAnnotationsTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/InputClassAnnotations.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/google_style.xml
Issue #14910 
~~Draft PR~~ because I had some doubts regarding failing xdoc tests.
I was adding a new section `4.8.5.2` to the google style guide implementation, to add support for this section, I required to combine 2 different modules ( AnnotationLocation & InvalidJavadocPosition ) in single test case. 
The test case is working fine but the problem is with Xdoc tests. I added 2 new configs and 1 test case in the coverage page, something like this:
Here, 2 `config` are for AnnotationLocation module and InvalidJavadocPosition module. The single `test` is the test file which uses these 2 configs internally to ensure we're following the rule.
But the `XdocPagesTest` is failing, it requires all the `config` to be paired with their individual `test` which is not the case here. In this case, …
> Issue #14910: Add new section 4.8.5.2 in google style guide implementation

- config/checkstyle-checks.xml
closes #12653: 
The regex is ugly but I think this is the best possible solution. Suppression by file and lines is not flexible if the line number is changed and will be huge. `WriteTagCheck` isn't applicable here because it always will requires the tag to be present
---
test commit : e8344a207bf8c50eeabd9225f78f404df55ebaa3
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/25884/workflows/ef4b7987-40cf-4d8a-a696-89bce3b46140/jobs/605288
```
[ERROR] [checkstyle] [ERROR] /home/circleci/project/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6690: @since tag must follow the X.Y.Z version format after version 10.5.0. [sinceVersionNumber]
[ERROR] [checkstyle] [ERROR] /home/circleci/project/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java:6741: …
```
> Issue #12653: Add regexp config to violate since version number

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTypeCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeWithRecordPattern.java
- src/xdocs/checks/coding/illegaltype.xml
closes #14946 :
added `RECORD_PATTERN_DEF` token to `IllegalTypeCheck`
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/d09e02f562fa0cd9e71eebcc4f9ab6fd09a4fd36/check.xml
Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/efa32547d82e4b966268643d284182774d68bfdd/check_patch.xml
Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/8ca3493f88bc1003db86b40015a4c2101ab7bc94/projects-to-test-on.properties
> Issue #14946: False negative in IllegalTypeCheck on record pattern

- .ci/validation.sh
- azure-pipelines.yml
from https://github.com/checkstyle/checkstyle/pull/15001#issuecomment-2175063950
it becomes a pain to restart.
```
##[error]This is a scheduled macOS-11 brownout. The macOS-11 environment 
is deprecated and will be removed on June 28th, 2024.
,##[error]The remote provider was unable to process the request.
Started: Yesterday at 10:53 AM
Duration: 20h 8m 52s
Job preparation parameters
9 queue time variables used
```
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=21757&view=logs&j=d72e04f6-d294-5bfe-b3cd-ffcb523f40f9
> infra: update azure to macOS-12 to avoid deprecation warning

- pom.xml
Issue #14137.
This enables the `ImmutablesSortedSetComparator` check, see docs here: https://error-prone.picnic.tech/bugpatterns/ImmutablesSortedSetComparator/.
Sorry for the delay on the last PRs of #14137. I'm back to file the last two PRs and get it merged!
> Issue #14137: Enable `ImmutablesSortedSetComparator` check

- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainCustomSeverityForGoogleConfig.java
- src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainCustomSeverityForGoogleConfig.properties
- src/xdocs/google_style.xml
issue #15053 
Made google style guide severity property define-able by system variable. Added a new `Overrides` section in google coverage page about this and wrote test case for it
> Issue #15053: Made google style guide severity property define-able by  variable

- src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java
- src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/FileNameTest.java
- src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/WhitespaceCharactersTest.java
- src/it/java/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/SpecialEscapeSequencesTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule32packagestatement/PackageStatementTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/NoWildcardImportsTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/OverloadsNeverSplitTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/SourceFileStructureTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/toolongpackagetotestcoveragegooglesjavastylerule/PackageStatementTest.java
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/EmptyBlocksMayBeConciseTest.java
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ClassAnnotationsTest.java
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/MethodsAndConstructorsAnnotationsTest.java
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/FieldAnnotationsTest.java
- src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/InputClassAnnotations.java
issue #15026 
created a new method: `verifyWithWholeGoogleConfig()` which helps us to check the input file against whole google configuration. We just require to pass the file path to the method and everything else will work like a magic 🔮🪄
> Issue #15026: Added support to check input file against whole google configuration for google IT tests

- config/error-prone-suppressions/compile-phase-suppressions.xml
- pom.xml
Issue #14137.
This enables the `IdentityConversion` check, see docs here: https://error-prone.picnic.tech/bugpatterns/IdentityConversion/.
This is the last PR of #14137! 
https://github.com/checkstyle/checkstyle/blob/a2ba2b27bc7d59f9619d96663881f000260a913f/src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java#L140-L148
> Issue #14137: Enable `IdentityConversion` check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
Finished #14090 which renamed the static variable for UnusedLocalVar check
> minor: renamed static variable in UnusedLocalVarCheck

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
Closes #14937 
Removed the `PER_MODULE_TESTS_RULES_LIST` used in migration of sections to chapter wise testing
> Issue #14937: Removed PER_MODULE_TESTS_RULES_LIST from XdocsPagesTest

- src/xdocs/checks/naming/abbreviationaswordinname.xml
- src/xdocs/checks/naming/abbreviationaswordinname.xml.template
- src/xdocs/checks/naming/classtypeparametername.xml
- src/xdocs/checks/naming/classtypeparametername.xml.template
problem detected at https://github.com/checkstyle/checkstyle/actions/runs/9913652978/job/27391115727#step:4:2422
```
--- .ci-temp/linkcheck-suppressions-sorted.txt	2024-07-12 20:21:26.341087606 +0000
+++ .ci-temp/linkcheck-errors-sorted.txt	2024-07-12 20:21:26.341087606 +0000
@@ -1,3 +1,7 @@
+<a class="externalLink" href="https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s4.8.6.1-block-comment-style">https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s4.8.6.1-block-comment-style</a>: 404 Not Found
+<a class="externalLink" href="https://checkstyle.org/styleguides/google-java-style-20220203/javaguide.html#s5.2.8-type-variable-names">https://checkstyle.org/styleguides/google-java-st …
```
> infra: fix links to google style to be relative

- .ci/check-performance-regression.sh
closes #15241 
new baseline comes from the average execution time after string template removal  https://github.com/checkstyle/checkstyle/pull/15212#issuecomment-2221074819
> Issue #15241: Reduce baseline execution time value

- src/xdocs/config_system_properties.xml
taken from https://github.com/checkstyle/checkstyle/pull/15102
just noticed, that content is irrelevan for system properties.
https://checkstyle.org/config.html#Custom_messages
https://checkstyle.org/checks/naming/abbreviationaswordinname.html#Violation_Messages
last list very clearly shows where are translations.
> doc: remove Localization section from system properties web page

- config/projects-to-test/openjdk17-excluded.files
- config/projects-to-test/openjdk19-excluded.files
- config/projects-to-test/openjdk20-excluded.files
- config/projects-to-test/openjdk21-excluded.files
NPE on non-compile able file from `MissingNullCaseInSwitch` Report:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/adcd467_2024031159/reports/diff/openjdk21/index.html#A968
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/adcd467_2024031159/reports/diff/openjdk21/index.html#A976
PR: https://github.com/checkstyle/checkstyle/pull/15113
report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/adcd467_2024031159/reports/diff/index.html
> minor : Extend exclude list for openjdk projects

- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java
#15218 
https://checkstyle.org/google_style.html#a7.1.1
>[SingleLineJavadoc](https://checkstyle.org/checks/javadoc/singlelinejavadoc.html#SingleLineJavadoc) Recent update for guide that clarify requirements will be addressed at[ #4052](https://github.com/checkstyle/checkstyle/issues/4052)
InvalidJavadocPosition
https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s7.1.1-javadoc-multi-line
>The basic form is always acceptable. The single-line form may be substituted when the entirety of the Javadoc block (including comment markers) can fit on a single-line. Note that this only applies when there are no block tags such as `@return`. 
attention; InvalidJavadocPosition is in use , but old version of syle guide is not released yet.
but this check is in covergate …
> Issue #15218: formatted input file for section 7.1.1 General form to follow google style guide rules

- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputGenericWhitespace.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputGenericWhitespaceEndsTheLine.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputMethodParamPad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeAnnotations.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeCaseDefaultColon.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeColonOfLabel.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeEmptyForLoop.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputParenPad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundBasic.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundEmptyTypesAndCycles.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundGenerics.java
#15218 
coverage page: https://checkstyle.org/google_style.html#a4.6.2
modules:
[WhitespaceAround](https://checkstyle.org/checks/whitespace/whitespacearound.html#WhitespaceAround)
[GenericWhitespace](https://checkstyle.org/checks/whitespace/genericwhitespace.html#GenericWhitespace)
[MethodParamPad](https://checkstyle.org/checks/whitespace/methodparampad.html#MethodParamPad)
[ParenPad](https://checkstyle.org/checks/whitespace/parenpad.html#ParenPad)
[WhitespaceAfter](https://checkstyle.org/checks/whitespace/whitespaceafter.html#WhitespaceAfter)
[NoWhitespaceBefore](https://checkstyle.org/checks/whitespace/nowhitespacebefore.html#NoWhitespaceBefore)
[NoWhitespaceBeforeCaseDefaultColon](https://checkstyle.org/checks/whitespace/nowhitespacebeforecasedefaultcolon.html#NoWhitespaceBeforeCaseDefa …
> Issue #15218: formatted input files for section 4.6.2 Horizontal Whitespace to follow google style guide rules

- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule32packagestatement/PackageStatementTest.java
- src/it/java/com/google/checkstyle/test/chapter3filestructure/toolongpackagetotestcoveragegooglesjavastylerule/PackageStatementTest.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule32packagestatement/InputPackageStatement.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/toolongpackagetotestcoveragegooglesjavastylerule/InputPackageStatementLongName.java
#15214 
https://checkstyle.org/google_style.html#a3.2
>3.2 Package statement | LineLength                                                                                                                    NoLineWrap
[3.2 Package statement](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s3.2-package-statement) 	[LineLength](https://checkstyle.org/checks/sizes/linelength.html#LineLength)
[NoLineWrap](https://checkstyle.org/checks/whitespace/nolinewrap.html#NoLineWrap)
> Issue #15214: Migrated section 3.2 Package statement to whole config testing

- src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/FileNameTest.java
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName1.java
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName3.java
#15214 
> 2.1 File name | OuterTypeFilename
[2.1 File name](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s2.1-file-name) 	[OuterTypeFilename](https://checkstyle.org/checks/misc/outertypefilename.html#OuterTypeFilename)
expected violation `type.file.mismatch=The name of the outer type and the file do not match.`
> Issue #15214: Migrated section 2.1 File Name to whole config testing

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/UseOfOptionalBracesTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/InputUseOfOptionalBraces.java
#15214 
https://checkstyle.org/google_style.html#a4.1.1
> 4.1.1 Braces are used where optional 	NeedBraces
>needBraces=''{0}'' construct must use '''{}'''s.
> Issue #15214: migrated section 4.1.1 Use of optional braces to whole config testing

- .github/workflows/regression-report.yml
Resolves: #15234 
doc how to use: https://github.com/checkstyle/test-configs/tree/main/AbbreviationAsWordInName/Example1#example1-configs
for later: 
https://github.com/checkstyle/test-configs/issues/131
https://github.com/checkstyle/test-configs/issues/139
https://github.com/checkstyle/test-configs/issues/140
example of usage: https://github.com/checkstyle-gsoc/checkstyle/pull/7
https://github.com/checkstyle-gsoc/checkstyle/pull/16
or bunch of any other PR: https://github.com/checkstyle-gsoc/checkstyle/pulls
`also done:`
The code changes also included the rocket symbol not working. This has been fixed and tested. 
Link to the PR testing: https://github.com/checkstyle-gsoc/checkstyle/pull/7
`also done:`
We need one PR at a time. 
As you can see with changes in workflow to option c, i can …
> New Github workflow that provide links to test-configs but reuse contribution repo for report generation

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/NonemptyBlocksKrStyleTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputLeftCurlyAnnotations.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputLeftCurlyMethod.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputNonemptyBlocksLeftRightCurly.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurly.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile2.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOther.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCase.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCasesBlocks.java
#15214 
  | 4.1.2 Nonempty blocks: K & R style | LeftCurly                                                                                                 RightCurly
-- | -- | --
4.1.2 Nonempty blocks: K & R style 	[LeftCurly](https://checkstyle.org/checks/blocks/leftcurly.html#LeftCurly)
[RightCurly](https://checkstyle.org/checks/blocks/rightcurly.html#RightCurly)
> Issue #15214: migrated section 4.1.2 non empty blocks K & R style to whole config testing

- src/xdocs/google_style.xml
#15252
Updated google style guide coverage page and added usage of [EmptyCatchBlock](https://checkstyle.sourceforge.io/checks/blocks/emptycatchblock.html) module. There were already test cases for this module so no need to update them.
> Issue #15252: added usage of EmptyCatchBlock for section 6.2 in google style coverage page

- src/it/resources/com/google/checkstyle/test/chapter5naming/rule523methodnames/InputMethodName.java
Detected at: https://github.com/checkstyle/checkstyle/pull/14901/files/4bcfed8ef4a4446fbda32e24fd067abd933030ce#r1679695992
Added test case for JUnit test methods. The test works same even if I remove the `@Test` annotation. I'm not sure if we should be concerned about this or not.
> supplemental: added test cases for JUnit test method names in google style guide section 5.2.3 method names

- src/xdocs/google_style.xml
#15329 
Updated coverage table for section 4.4 Column Limit: 100, added a message indicating how to use suppression for long identifiers.
> Issue #15329: Updated coverage table of google style guide implementation for section 4.4 Column Limit

- src/xdocs/google_style.xml
Issue #15329 
Updated coverage table for section [7.3.1 Exception: self-explanatory methods](https://checkstyle.sourceforge.io/styleguides/google-java-style-20180523/javaguide.html#s7.3.1-javadoc-exception-self-explanatory), referenced 2 issues: https://github.com/checkstyle/checkstyle/issues/15414 https://github.com/checkstyle/checkstyle/issues/15434
> Issue #15329: updated coverage table for section 7.3.1 Exception: self-explanatory members

- src/xdocs/google_style.xml
#15329
#15416 
Added new section "Type-use annotations" and explained the reason behind why we cannot follow rules of this section with a red mark.
> Issue #15329 added a new section 4.8.5.1 Type-Use annotations and a message explaining reason for not following its rules

- src/xdocs/google_style.xml
#15329
Linked: #15338 
Updated coverage table for section 4.6.2 Horizontal whitespace, added blue tick for WhitespaceAround module and a message explaining the reason behind blue tick and also reference link of the issue.
> Issue #15329: updated coverage table for section 4.6.2, added blue tick for WhitespaceAround module and a message referencing to the issue

- src/xdocs/google_style.xml
#15329
Linked #15324 
Updated coverage table of google style guide implementation for section [4.1.2 Nonempty blocks: K & R style](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.1.2-blocks-k-r-style), added blue tick for "LeftCurly" module and a message referencing the issue.
> Issue #15329: updated coverage table for section 4.1.2, added blue tick for LeftCurly module and a message explaining the reason

- .ci/google-java-format.sh
- .github/workflows/google-java-format.yml
- config/jsoref-spellchecker/whitelist.words
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequences.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule32packagestatement/InputPackageStatement.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule523methodnames/InputMethodName.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesSimple.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputLambdaParameterName.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterName.java
- src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/InputNoFinalizeExtend.java
- src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/InputNoFinalizer.java
Issue #15236
Exact list of Inputs to validate is separate conversation.
In this PR we just need to merge CI validation with empty list of Inputs or any single Input. 
example of work: https://github.com/checkstyle/checkstyle/actions/runs/9909177598/job/27376661314?pr=15237
Looks like Goolge formatter enforce `{` to be on new line after `case`, we will investigate separately to follow or not this formatting. It is unrelated to FallThrough so I am ok to merge such changes. 
but update for comment location is good catch from it.
```
$ git diff
diff --git a/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java b/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
index eda4f11..88f3130 …
```
> Issue #15236: format some ITs Google Inputs by formatter

- src/xdocs/google_style.xml
#15442
removed explanation message for issue #6707 from section [4.6.2 Horizontal whitespace](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b4c7950_2024151443/styleguides/google-java-style-20220203/javaguide.html#s4.6.2-horizontal-whitespace)
> Issue #15329: removed explanation message for issue #6707 from section 4.6.2 in google style guide

- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
Assist for https://github.com/checkstyle/checkstyle/pull/15376#discussion_r1706279547 ,
`PROPERTIES_ALLOWED_GET_TYPES_FROM_METHOD` allows us to use the setter's type ONLY if the field cannot be found. If we make the field invisible to use that override, we lose the default value of the field.
This updates PROPERTIES_ALLOWED_GET_TYPES_FROM_METHOD logic so it uses the setter even if the field exists. This override is only used by 4 other checks, so it should be minimal impact.
> Pull #15466: grab setter types even if field exists for override

- .ci/google-java-format.sh
#15449
excluded `rule72thesummaryfragment` from the script, formatting its inputs does not make tests fails. Checkstyle and google-java-format both works fine for this rule
> Issue #15449: excluded rule72thesummaryfragment from google-java-format.sh

- .ci/google-java-format.sh
> Issue #15449: excluded rule51identifiernames from google-java-format.sh

- .ci/google-java-format.sh
#15449
7.3 Where Javadoc is used
https://checkstyle.org/google_style.html#a7.3
> Issue #15449: excluded rule73 from google-java-format.sh

- .ci/google-java-format.sh
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacingNoImports.java
#15449
Only InputOrderingAndSpacingNoImports .java is excluded other than that all of the inputs needed to be grepped cuz they're based on unused imports and formatter will remove those during formatting process.
> Issue #15449: partially excluded rule333orderingandspacing from google-java-format.sh

- .ci/google-java-format.sh
#15449
Doc:- [7.1.3 Block tags](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s7.1.3-javadoc-at-clauses)
grepped InputJavaDocTagContinuationIndentation.java because it is indentation based input which contains violations. Formatter will correct the violations and test will start to fail
> Issue #15449: partially excluded rule713atclauses from google-java-format.sh

- .ci/google-java-format.sh
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectIfAndParameter.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/InputPresenceOfDefaultLabel.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule488numericliterals/InputNumericLiterals.java
#15449 
the grepped list became large in this PR. There were only few section under rule48 in which our config and formatter did not conflict. 
Most of the tests started failing after formatting the input files of them. 
Grepped sections:
[4.8.7 Modifiers](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.7-modifiers)
[4.8.2.1 One variable per declaration](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.2.1-variables-per-declaration)
[4.8.2.2 Declared when needed](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.2.2-variables-limited-scope)
[4.8.4.1 Indentation](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.4.1-switch-indentation) ( only …
> Issue #15449: partially excluded rule48 from google-java-format.sh

- .ci/google-java-format.sh
- config/jsoref-spellchecker/whitelist.words
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentContinuationLinesAtLeast4SpacesTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectIfAndParameter.java
- src/xdocs/google_style.xml
#15449
Affected sections:
[4.5.2 Indent continuation lines at least +4 spaces](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.5.2-line-wrapping-indent)
[4.5.1 Where to break](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.5.1-line-wrapping-where-to-break)
all inputs of 4.5.1 started failing after formatting so had to grep it entirely
> Issue #15449: partially excluded rule45 from google-java-format.sh

- .ci/google-java-format.sh
#15449 
Affected sections:
[4.1.1 Use of optional braces](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2d35464_2024232909/styleguides/google-java-style-20220203/javaguide.html#s4.1.1-braces-always-used) ( grepped entirely )
[4.1.2 Nonempty blocks: K & R style](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2d35464_2024232909/styleguides/google-java-style-20220203/javaguide.html#s4.1.2-blocks-k-r-style) ( partially grepped )
[4.1.3 Empty blocks: may be concise](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2d35464_2024232909/styleguides/google-java-style-20220203/javaguide.html#s4.1.3-braces-empty-blocks) ( partially grepped)
> Issue #15449: partially excluded rule41 from google-java-format.sh

- .ci/google-java-format.sh
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadsNeverSplitRecords.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadsNeverSplit.java
#15449 
[3.4.2.1 Overloads: never split](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s3.4.2.1-overloads-never-split)
> Issue #15449: partially excluded rule3421overloadsplit from google-java-format.sh

- src/xdocs/google_style.xml
#15217 
Added missing sections `2.3 Special characters` & `4.8.5.5 Parameter and local variable annotations` to coverage table.
> Issue #15217: added missing sections in google style guide coverage table

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ClassAnnotationsTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/InputFormattedClassAnnotations.java
#15340 
Had to exclude following cases from the new input file:
```java
@SomeAnnotation1
@SomeAnnotation2
/** Inner class 2. */
class Inner2 {}
```
Formatter wasn't able to correct javadoc position so our config was complaining for it
> Issue #15340: Created InputFormatted file for section 4.8.5.2 Class Annotations

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/FieldAnnotationsTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/InputFormattedFieldAnnotations.java
#15340 
Had to exclude following cases from the new input file:
```java
@SomeAnnotation1
@SomeAnnotation3(x = 14)
/** testing. */
List<String> list = new ArrayList<>();
@SuppressWarnings("bla")
@SomeAnnotation1
/** testing. */
InputFormattedFieldAnnotations obj = new InputFormattedFieldAnnotations();
```
Formatter wasn't able to correct javadoc position so our config was complaining for it
> Issue #15340: created InputFormatted file for section 4.8.5.4 Field Annotations

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/MethodsAndConstructorsAnnotationsTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputFormattedMethodsAndConstructorsAnnotations.java
#15340 
Had to exclude following cases from the new input file:
```java
@SomeAnnotation1
@SomeAnnotation2
/** testing. */
void test4() {}
@SomeAnnotation1
@SomeAnnotation2
/** testing. */
InputFormattedMethodsAndConstructorsAnnotations(double d) {}
```
Formatter wasn't able to correct javadoc position so our config was complaining for it
> Issue #15340: created InputFormatted file for section 4.8.5.3 Methods And Constructors Annotations

- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputLambdaBodyWrap.java
Closes #4006
I moved marker comments out of lambdas to make code close to real  (no comment in the middle of lambda)
> Issue #4006: testing of line break after lambda arrow

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/ColumnLimit100Test.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputFormattedColumnLimit.java
#15340 
[4.4 Column limit: 100](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.4-column-limit)
Had to exclude some examples because they were unwrap-able
```java
// Long line
// ----------------------------------------------------------------------------------------------------
```
```java
// Very long url with valid href: href    =
// "www.google.com/search?hl=en&q=java+style+guide+checkstyle+check+href+length+limit&btnG=Google+Search"
int validHrefWithWhiteSpaces = 54;
// Very long url with invalid href:
// href="www.google.com/search?hl=en&q=java+style+guide+checkstyle+check+href+length+limit&btnG=Google+Search
int invalidHref = 88;
```
> Issue #15340: created InputFormatted file for section 4.4 Column Limit: 100

- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/InputDeclaredWhenNeeded.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule523methodnames/InputMethodName.java
- src/main/resources/google_checks.xml
#15429 
Added [SuppressionXpathSingleFilter](https://checkstyle.sourceforge.io/filters/suppressionxpathsinglefilter.html) suppression in google_checks.xml and updated regex at MethodName module to allow test methods to have `_` in their name for section [5.2.3 Method Names](https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/bcdd4d1_2024123825/google_style.html#a5.2.3), for other methods, module will give violation if `_` is used in method name
> Issue #15429: Added SuppressionXpathSingleFilter suppression ignore Test Methods for section 5.2.3 Method Names

- .github/workflows/google-java-format.yml
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
Issue #15236
Example how this CI job catch user mistake https://github.com/checkstyle/checkstyle/pull/15478#discussion_r1711799289
reminder: please  review PR https://github.com/checkstyle/checkstyle/pull/15237 as it was merged unintentionally.
we should see some diff due to reported problem https://github.com/checkstyle/checkstyle/pull/15237#issuecomment-2253766008 is fixed
> Issue #15236: use latest formatter as they fixed some defects that we noticed

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/HorizontalWhitespaceTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundWhen.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedGenericWhitespace.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedGenericWhitespaceEndsTheLine.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedMethodParamPad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeAnnotations.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeCaseDefaultColon.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeColonOfLabel.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeEmptyForLoop.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedParenPad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAfterBad.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAfterGood.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundBasic.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundEmptyTypesAndCycles.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundGenerics.java
#15340 
there were multiple inputs for [4.6.2 Horizontal whitespace](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.6.2-horizontal-whitespace), so had to create extra classes. Reason explained at: https://github.com/checkstyle/checkstyle/pull/15535
> Issue #15340: created InputFormatted file for section 4.6.2 Horizontal whitespace

- config/checkstyle-resources-suppressions.xml
- src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/WhitespaceCharactersTest.java
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule231filetab/InputFormattedWhitespaceCharacters.java
#15340
original input file: [InputWhitespaceCharacters.java](https://github.com/checkstyle/checkstyle/blob/master/src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule231filetab/InputWhitespaceCharacters.java) contained violations only about tabs usage. Formatter just removed the tabs and used spaces instead though it wasn't able to remove tabs from certain places so had to add violation comments for it
> Issue #15340: created InputFormatted file for section 2.3.1 whitespace characters

- .circleci/config.yml
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/27670/workflows/f0ba2fb2-5a67-4c61-91aa-e06efccf88ad/jobs/679943
```
Starting a Gradle Daemon (subsequent builds will be faster)
Executing Gradle on JVM versions 16 and lower has been deprecated. 
This will fail with an error in Gradle 9.0. Use JVM 17 or greater to execute Gradle. 
Projects can continue to use older JVM versions via toolchains. 
Consult the upgrading guide for further information: 
https://docs.gradle.org/8.10/userguide/upgrading_version_8.html#minimum_daemon_jvm_version
at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor
.execute(RootBuildLifecycleBuildActionExecutor.java:50)
```
> infra: update sbe project to use jdk17 to fix build problem

- .ci/google-java-format.sh
- config/checkstyle-non-main-files-suppressions.xml
Detected at: https://github.com/checkstyle/checkstyle/actions/runs/10683811066/job/29612742864?pr=15558
> Create InputFormattedCommentsIndentation.java for InputCommentsIndentation.java
the grepped file was like:
```
| grep -v "rule4861blockcommentstyle/InputCommentsIndentation.*.java" \
```
`.*` was causing CI failure so had to remove it. Removed all occurrence of `.*` from the file, some line was crossing linelength limit so had to add suppression for it.
> supplemental: removed regex usage from google-java-format.sh

- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedSingleLineJavadocAndInvalidJavadocPosition.java
#15340
```diff
$ diff -u src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedSingleLineJavadocAndInvalidJavadocPosition.java
--- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java 2024-08-31 15:32:12.072778300 +0530
+++ src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedSingleLineJavadocAndInvalidJavadocPosition.java        2024-08-31 15:54:48.865630200 +0530
@@ -1,12 +1,14 @@
package // violation 'package statement should not be line-wrapped.'
-    /** invalid javadoc. */ // violation 'Javadoc …
```
> Issue #15340: created InputFormatted file for section 7.1.1 General Form

- .ci/google-java-format.sh
Closes #15340
output:
```
✘-1 ~/java/github/romani/checkstyle [i15449-sync-Inputs L|✚ 1⚑ 2] 
$ ./.ci/google-java-format.sh .ci-temp/google-java-format-1.23.0-all-deps.jar
Checking that all excluded java files in this script have matching InputFormatted* file:
Create InputFormattedSingleLineJavadocAndInvalidJavadocPosition.java for InputSingleLineJavadocAndInvalidJavadocPosition.java
Create InputFormattedInvalidJavadocPosition.java for InputInvalidJavadocPosition.java
Create InputFormattedCamelCaseDefined.java for InputCamelCaseDefined.java
Create InputFormattedClassNames.java for InputClassNames.java
Create InputFormattedUseOfOptionalBraces.java for InputUseOfOptionalBraces.java
Create InputFormattedEmptyBlocksAndCatchBlocks.java for InputEmptyBlocksAndCatchBlocks.java
Create …
```
> Issue #15340: validation that all excluded from formatting google Input files have InputFormatted

- config/checkstyle-non-main-files-suppressions.xml
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputColumnLimit.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputFormattedColumnLimit.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/filters/suppresswithnearbytextfilter.xml
- src/xdocs/filters/suppresswithnearbytextfilter.xml.template
- src/xdocs/google_style.xml
#15233 
Added test cases with `@SuppressWarnings({"LineLength"})` for long identifiers for section 4.4 input file. Updated section on the coverage table to show how to avoid violation for such long identifiers with suppression.
> Issue #15233:  4.4 input usage of suppression for long identifiers

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeEqualsParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_Wildcard.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagDoubleTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagIncomplete.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMissingFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagSeverity.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineMultilineSupport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineMultilineSupport2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorNoViolationOnEmptyLineBeforeComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleLineCommentAfterPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/packageinfo/test4/package-info.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/Example2.java
- src/xdocs/checks/misc/nocodeinfile.xml
Issue: #15256
Updated bdd/InlineConfigParser.java to match violation comments
Removed extra comments from this InputEqualsHashCodeEqualsParameter file.
Added additional matcher that matches the following pattern: `//.*violation.*`
> Issue #15256: Fixed location of violation comments

- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/severitymatchfilter/Example1.java
- src/xdocs/filters/severitymatchfilter.xml
- src/xdocs/filters/severitymatchfilter.xml.template
Issue: #13345
Enabled the example tests for SeverityMatch filter.
> Issue #13345: Enabled SeverityMatch example tests

- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/InputDeclaredWhenNeeded.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule731selfexplanatory/InputJavadocMethodAndMissingJavadocMethod.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule732exceptionoverrides/InputJavadocMethodAndMissingJavadocMethod.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputJavadocMethodAndMissingJavadocMethod.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeCorrect.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeIncorrect.java
- src/main/resources/google_checks.xml
- src/xdocs/google_style.xml
#15434 
From style guide: 
> At the minimum, Javadoc is present for every public class, and every public or protected member of such a class, with a few exceptions noted below.
We're required to give warning for every public/protected members of a public class but as per changes made in google_checls.xml in this PR, we're giving warning for all public/protected members of a public class as well as for all public/protected members of a protected class too, which we doesn't want.
I'm not sure how we can solve this problem. @romani looking for your help here
Diff Regression config: https://gist.githubusercontent.com/Zopsss/eef363a452104d034a9ce7be532f647d/raw/01ec2b9c4cd7afd4fb508acccf1605b57767edc0/master_google_checks.xml
Diff Regression patch config: …
> Issue #15434: fixed MissingJavadocMethod module in google_checks.xml to give warning for missing javadoc for protected methods

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckInterfaceAndEnum.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckPrivateAndDeprecatedVar.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckPublicMethodAndVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckTokensOnMethodAndVar.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/Example2.java
- src/xdocs/checks/annotation/annotationonsameline.xml
Issue #15456 
Attention: 
is given a .DS_Store as filePath input.
Since, it is OS specific and I guess it would never happen on CI, though I'm questioning whether an improvement should be considered.
For now I added a check - !file.isHidden() - here as a workaround.
For more details read https://github.com/checkstyle/checkstyle/issues/15456#issuecomment-2350937837
--------
Attention: CI can not detect this problem, as CI never open file browser to navigate on folders, browsing folder in UI creates such folders.
> Issue #15456: Specify violation messages for AnnotationOnSameLineCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
``` java
/**
* @serial include
*/
/**
* Some Java doc.
*
* @serial serialized company name.
*/
private String companyName;
}
```
``` console
target % java -jar checkstyle-10.18.2-SNAPSHOT-all.jar -J ../Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
COMPILATION_UNIT -> COMPILATION_UNIT [4:0]
`--CLASS_DEF -> CLASS_DEF [4:0]
|--MODIFIERS -> MODIFIERS [4:0]
|   |--BLOCK_COMMENT_BEGIN -> /* [1:0]
|   |   |--COMMENT_CONTENT -> *\n * @serial include\n  [1:2]
|   |   |   `--JAVADOC -> JAVADOC [1:3]
|   |   |       |--NEWLINE -> \n [1:3]
|   |   |       |--LEADING_ASTERISK ->  * [2:0]
|   |   |       |--WS ->   [2:2]
|   |   |       |--JAVADOC_TAG -> JAVADOC_TAG [2:3]
|   |   |       |   |--SERIAL_LITERAL -> @serial [2:3]
|   |   |       |   |--WS ->   [2:10]
|   |   | …
```
> Issue #14631: Update serial literal to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/ImportOrderCheck.xml
- src/xdocs/checks/imports/importorder.xml
fixes #15626
The documentation currently explains what happens when an import does not match any group, but it doesn't explain what happens if it matches two or more groups.
> Issue #15626: Explain what happens when an import matches two or more groups

- pom.xml
https://github.com/mojohaus/jdepend-maven-plugin/issues/2
https://github.com/checkstyle/checkstyle/actions/runs/11084772897/job/30800440141#step:4:2626
```
--- .ci-temp/linkcheck-suppressions-sorted.txt	2024-09-28 14:48:12.325455794 +0000
+++ .ci-temp/linkcheck-errors-sorted.txt	2024-09-28 14:48:12.323455782 +0000
@@ -1,3 +1,4 @@
+<a class="externalLink" href="https://www.mojohaus.org/jdepend-maven-plugin/jdepend-maven-plugin">https://www.mojohaus.org/jdepend-maven-plugin/jdepend-maven-plugin</a>: 404 Not Found
```
> infra: fix link in exclude for jdepend-maven-plugin to fix run of maven-linkcheck-plugin

- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedIncorrectJavadocParagraph.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
- src/main/resources/google_checks.xml
fixes #15716
set `allowNewlineParagraph` property of `JavadocParagraph` to `false`
now we're able to achieve the following expected behavior in google_checks.xml:
```
/**
* Some Summary.
*
* <p>
* Some test.
*/
}
$ java -jar checkstyle-10.18.1-all.jar -c /google_checks.xml  Test.java 
[WARN] /var/tmp/Test.java:4: <p> tag should be placed immediately before the first word
, with no space after. [JavadocParagraph]
Audit done.
```
didnt needed to change inputs that much, only added the extra violation message, no new cases were added
---
Diff Regression config: https://gist.githubusercontent.com/Zopsss/eef363a452104d034a9ce7be532f647d/raw/12b3995567589f3477ff9d8b46b129dff3c0eafa/master_google_checks.xml
Diff Regression patch config: …
> Issue #15716: set allowNewlineParagraph to false in google_checks.xml

- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectJavadocParagraph.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedCorrectJavadocParagraph.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedIncorrectJavadocParagraph.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ru.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocParagraphCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect5.java
- src/xdocs/checks/javadoc/javadocparagraph.xml
fixes #15503 
added support to check and violate block-tag if they're followed by p tag.
created a new violation message for it.
wrote new test cases.
took the HTML tags list from: https://checkstyle.sourceforge.io/checks/javadoc/javadocstyle.html#JavadocStyle
`Check for allowed HTML tags. The list of allowed HTML tags is "a", "abbr", "acronym", "address", "area", "b", "bdo", "big", "blockquote", "br", "caption", "cite", "code", "colgroup", "dd", "del", "dfn", "div", "dl", "dt", "em", "fieldset", "font", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "img", "ins", "kbd", "li", "ol", "p", "pre", "q", "samp", "small", "span", "strong", "sub", "sup", "table", "tbody", "td", "tfoot", "th", "thead", "tr", "tt", "u", "ul", "var".`
and filtered out block-level tags. 
--- …
> Issue #15503: Added support for violation of p tag if it precedes a block tag

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionInterfaceTypeParameterNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfacetypeparametername/InputXpathInterfaceTypeParameterNameInsideClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfacetypeparametername/InputXpathInterfaceTypeParameterNameInsideInnerClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfacetypeparametername/InputXpathInterfaceTypeParameterNameTopLevelPublic.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Part of #6207 
Added XPath IT Regression Tests for [InterfaceTypeParameterName](https://checkstyle.org/checks/naming/interfacetypeparametername.html#InterfaceTypeParameterName)
> Issue #6207: Added XPath IT Regression Tests for InterfaceTypeParameterName

- .ci/diff-report.sh
- .github/workflows/diff-report.yml
Replaces `project.properties` with `projects.properties` and add support for `yml` in `diff-report.sh`
> infra: replace project.properties with projects.properties

- .github/workflows/regression-report.yml
Adds the new official releases for extractor and diff-java-tool and a new regression-report.sh to keep the operations and changes for diff-report.yml and regression-report.yml as separate for now. 
This PR will test on the following scenarios:
1. InputJavaFile generating projects in yml format (as we have made the default projects format as yml)
2. PR configurations with .properites file and generating the regression-report in .properties file
3. PR configurations with .yml file and generating the regression-report in .yml file
4. Using the existing config bundle commands Github, generate report for <CheckName/all-in-one-examples> using the default projects list
5. Using the existing config bundle commands Github, generate report for <CheckName/all-in-one-examples> using the custom …
> infra: fix regression-report.yml and add a new regression-report.sh

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocParagraphCheck.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/Example4.java
- src/xdocs/checks/javadoc/javadocparagraph.xml
- src/xdocs/checks/javadoc/javadocparagraph.xml.template
closes #15734 
updated doc and added example for new violation previously added.
2 new examples were added, one with default `allowNewlineParagraph` and other with `allowNewlineParagraph = false`
> Issue #15734: updated JavadocParagraphCheck documentation and added examples for P tag should not precede block-tag

- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundWhen.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedRightCurlySwitchCasesBlocks.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCasesBlocks.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationInSwitchBlock.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputFormattedCommentsIndentationInSwitchBlock.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
part of #15324 
Suggestions taken from: https://github.com/checkstyle/checkstyle/issues/15324#issuecomment-2375361863
Added support to check for preceding line break before `{` for switch-case-default ( [4.1.2 Nonempty blocks: K & R style](https://checkstyle.org/google_style.html#a4.1.2) )
Some new tests were added to:
https://github.com/checkstyle/checkstyle/compare/master...Zopsss:15324-switch-case-lcurly?expand=1#diff-aff628179d81aea067e835af1af5587bc7f1a1a797f41835546d40ea0f3997e4
https://github.com/checkstyle/checkstyle/compare/master...Zopsss:15324-switch-case-lcurly?expand=1#diff-8e4bfd0f5535171a324423e3cc959fc50f3c7759555973e6084110dae5f1fd20
I didn't needed to change input files that much because they already contained the required cases.
I had to make changes to some other …
> Issue #15324: added support to check for preceding line break of `{` for switch-case-default blocks

- .ci/validation.sh
- config/checkstyle-checks.xml
- config/jsoref-spellchecker/whitelist.words
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocParagraphCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCheck1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag3.java
- src/xdocs/checks/javadoc/javadocparagraph.xml
- src/xdocs/checks/javadoc/javadocparagraph.xml.template
fixes #15685 https://github.com/checkstyle/checkstyle/issues/15732
tried fixing the implementation of JavadocParagraph ~might have introduced new false-negatives :p~
I tried to make the Check work same way when the paragraph tag's corresponding closing tag is also present.
when I tried to run build command locally, I got so many errors for different files like checks, filters, etc for `<p>` tag. Most of them were for:
```
<p> tag should be placed immediately before the first word, with no space after.
```
@romani need your help here
---
Diff Regression config: https://gist.githubusercontent.com/Zopsss/013f379d4c821f2d624be56212a64575/raw/5f17ec9186d4421396429ab38cbac3e4663bf4eb/javadocparagraph_config.xml …
> Issue #15685: fixed JavadocParagraph to detect paragraph tag when they have their corresponding closing tag

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java
Part of #14019 
Removed suppression
https://github.com/checkstyle/checkstyle/blob/954a9f121861cd71ddd8838fa2233384e62ded12/config/pitest-suppressions/pitest-filters-suppressions.xml#L165-L172
Followed https://github.com/checkstyle/checkstyle/pull/13794 as they are similar
This steps are better described [here](https://github.com/checkstyle/checkstyle/wiki/How-to-Generate-and-Analyze-Pitest-Reports),
- Removed suppression from `pitest-filters-suppressions.xml`
- Listed pitest profiles with `groovy .ci/pitest-survival-check-xml.groovy --list` using java 11 and groovy 2.4.5
- Picked up `pitest-filters` as active profile
- Generated report locally using `mvn -e --no-transfer-progress -P"$PITEST_PROFILE" clean test-compile org.pitest:pitest-maven:mutationCoverage`  
<details>
<summary> …
> Issue #14019: Kill this.checks = null mutation on SuppressionXpathSingleFilter

- .ci/validation.sh
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/28331/workflows/d8073709-edf6-4e99-b636-1e8d089b43bd/jobs/707482?invite=true#step-103-944586_87
caused by https://github.com/xwiki/xwiki-platform/commit/f696d5e2c519346a2e78c3d55f48c51f8921dce7
```
[INFO] --- maven-checkstyle-plugin:3.5.0:check (default) @ xwiki-platform-websocket ---
[INFO] Starting audit...
[ERROR] /home/circleci/project/.ci-temp/xwiki-platform/xwiki-platform-core/
xwiki-platform-websocket/src/main/java/org/xwiki/websocket/script/WebSocketScriptService.java:86:52:
The String "/" appears 2 times in the file. [MultipleStringLiterals]
Audit done.
[INFO] There is 1 error reported by Checkstyle 10.19.0-SNAPSHOT with checkstyle.xml ruleset.
[ERROR] src/main/java/org/xwiki/websocket/script/WebSocketScriptService.ja …
```
> infra: set certain sha for xwiki-platform to avoid CI failure in our PRs

- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurly.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputTryCatchIfElse2.java
- src/main/resources/google_checks.xml
part of #15664 
moved LITERAL_FINALLY to RightCurlyAlone, didnt needed to modify suppression, all tests were passing by default.
> Issue #15664: moved LITERAL_FINALLY to RightCurlyAlone in google_checks.xml

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
Part of #13999 
Removed suppression https://github.com/checkstyle/checkstyle/blob/42621ebbd4f3b61a8dec15c2f939562530c0a8b3/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L39-L46
Also, the following suppressions were removed as a side effect of refactoring
https://github.com/checkstyle/checkstyle/blob/42621ebbd4f3b61a8dec15c2f939562530c0a8b3/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L48-L55
https://github.com/checkstyle/checkstyle/blob/42621ebbd4f3b61a8dec15c2f939562530c0a8b3/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L84-L100 
- Removed suppression from [pitest-javadoc-suppressions.xml](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-javadoc-suppressions.xml)
- Selected `pitest-javadoc` as active profile
- …
> Issue #13999: Kill NonVoidMethodCallMutator on .getColumnNo());

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCache3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCache4.java
Part of Issue #13999
[AbstractJavadocCheck Documentation](https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.html)
Mutation - 1
https://github.com/checkstyle/checkstyle/blob/42f3c4f33790050b75341b6ad1c5afe0083e762c/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L3-L10
Caching by column was removed , see reason at https://github.com/checkstyle/checkstyle/pull/15798#issuecomment-2429262257 and [why it works ](https://github.com/checkstyle/checkstyle/pull/15798#discussion_r1814893199)
> Issue #13999: Resolve Pitest AbstractJavadocCheck mutation-1 suppression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecordsAndCompactCtors.java
Unrelated to https://github.com/checkstyle/checkstyle/issues/15683 but noticed when looking at it and the code.
We set required tokens in this Check which aren't needed. With them removed, we are able to remove a bit of code which was blocking violations on those tokens.
Tokens to remove from acceptable:
TokenTypes.CLASS_DEF,
TokenTypes.ENUM_DEF,
TokenTypes.INTERFACE_DEF,
TokenTypes.RECORD_DEF
Regression: https://rveach.no-ip.org/checkstyle/regression/4/
No differences.
**Migration note:**
Remove above tokens from config if used.
> JavadocMethodCheck: removed unnecessary tokens from acceptable

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631: Updated THROWS_LITERAL of JavadocTokenTypes to new AST format
```
/** some text.
* @throws SQLException if query is not correct
* */
}
$ java -jar checkstyle-10.19.0-SNAPSHOT-all.jar -J Test.java 
COMPILATION_UNIT -> COMPILATION_UNIT [4:0]
`--CLASS_DEF -> CLASS_DEF [4:0]
|--MODIFIERS -> MODIFIERS [4:0]
|   |--BLOCK_COMMENT_BEGIN -> /* [1:0]
|   |   |--COMMENT_CONTENT -> * some text.\n * @throws SQLException if query is not correct\n *  [1:2]
|   |   |   `--JAVADOC -> JAVADOC [1:3]
|   |   |       |--TEXT ->  some text. [1:3]
|   |   |       |--NEWLINE -> \n [1:14]
|   |   |       |--LEADING_ASTERISK ->  * [2:0]
|   |   |       |--WS ->   [2:2]
|   |   |       |--JAVADOC_TAG -> JAVADOC_TAG [2:3]
|   |   |       |   |--THROWS_LITERAL -> …
```
> Issue #14631: Updated THROWS_LITERAL of JavadocTokenTypes to new AST format

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameRecord.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameRecordMethodRecordDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename1a.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameNoPublic.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/Example5.java
- src/xdocs/checks/misc/outertypefilename.xml
**### Key Changes**
- **Added Violation Messages**: Custom violation messages have been implemented for OuterTypeFilenameCheck to improve readability and usability.
- **Updated Suppression Lis**t: The OuterTypeFilenameCheck has been removed from the suppression list.
> Issue #15456: Specify violation messages for OuterTypeFilenameCheck

- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundWhen.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundWhen.java
- src/main/resources/google_checks.xml
Closes #15831 
Enabled `allowEmptySwitchBlockStatements`, added test cases and updated `InputFormattedXxxxx` file
> Issue #15831: enabled allowEmptySwitchBlockStatements property of WhitespaceAround in google_checks.xml

- .github/CONTRIBUTING.md
- .github/GSOC.md
- README.md
- config/jsoref-spellchecker/whitelist.words
- src/xdocs/contributing.xml
Improves the CONTRIBUTING.md file, README.md file, and creates the GSOC.md file for GSoC participants. Make sure to "View File" on each to see rendered markdown content.
GH Views:
https://github.com/nrmancuso/checkstyle/blob/contributing/.github/CONTRIBUTING.md
https://github.com/nrmancuso/checkstyle/blob/contributing/.github/GSOC.md
https://github.com/nrmancuso/checkstyle/blob/contributing/README.md
> doc: improve CONTRIBUTING.md

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631: Updated custom_name to to new format of AST format
```
kushagra@Kushagra projects % cat Test.java
/** 
* @myJavadocTag some magic
* */
kushagra@Kushagra projects % java -jar checkstyle-10.20.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--TEXT -> /**  [0:0]
|--NEWLINE -> \n [0:4]
|--LEADING_ASTERISK ->  * [1:0]
|--WS ->   [1:2]
|--JAVADOC_TAG -> JAVADOC_TAG [1:3]
|   |--CUSTOM_NAME -> @myJavadocTag [1:3]
|   |--WS ->   [1:16]
|   `--DESCRIPTION -> DESCRIPTION [1:17]
|       |--TEXT -> some magic [1:17]
|       |--NEWLINE -> \n [1:27]
|       |--LEADING_ASTERISK ->  * [2:0]
|       |--TEXT ->  */ [2:2]
|       `--NEWLINE -> \n [2:5]
`--EOF -> <EOF> [3:0]
> Issue #14631: Updated custom_name to to new format of AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue : #14631
```java
$ cat Test.java                                                                     
{@code Comparable&lt;E&gt;}
$  java -jar checkstyle-10.20.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [0:0]
|   |--JAVADOC_INLINE_TAG_START -> { [0:0]
|   |--CODE_LITERAL -> @code [0:1]
|   |--WS ->   [0:6]
|   |--TEXT -> Comparable&lt;E&gt; [0:7]
|   `--JAVADOC_INLINE_TAG_END -> } [0:27]
|--NEWLINE -> \n [0:28]
|--NEWLINE -> \n [1:0]
`--EOF -> <EOF> [2:0]
> Issue #14631 : Updated JAVADOC_INLINE_TAG_START of JavadocTokenTypes to new AST format 

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631: Updated JAVADOC_INLINE_TAG_END to to new format of AST format
```java
$ cat Test.java                                                                                              
{@code Comparable&lt;E&gt;}%                                                                                          
$ java -jar checkstyle-10.20.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"                         
|--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [0:0]
|   |--JAVADOC_INLINE_TAG_START -> { [0:0]
|   |--CODE_LITERAL -> @code [0:1]
|   |--WS ->   [0:6]
|   |--TEXT -> Comparable&lt;E&gt; [0:7]
|   `--JAVADOC_INLINE_TAG_END -> } [0:27]
`--EOF -> <EOF> [0:28]
> Issue #14631: Updated JAVADOC_INLINE_TAG_END to to new format of AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 : Updated VALUE_LITERAL of JavadocTokenTypes to new AST format
```
$  cat Test.java
{@value Integer#MAX_VALUE}%     
$ java -jar checkstyle-10.20.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG [0:0]
|--JAVADOC_INLINE_TAG_START -> { [0:0]
|--VALUE_LITERAL -> @value [0:1]
|--WS ->   [0:7]
|--REFERENCE -> REFERENCE [0:8]
|   |--PACKAGE_CLASS -> Integer [0:8]
|   |--HASH -> # [0:15]
|   `--MEMBER -> MAX_VALUE [0:16]
`--JAVADOC_INLINE_TAG_END -> } [0:25]
> Issue #14631 : Updated VALUE_LITERAL to to new format of AST format

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeBadTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTypeParamsTags_1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeUnusedParamInJavadocForClass.java
Closes #14573
Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/cf451b3aa6366addc027a08423786d455bc79aa7/config_single.xml
> Issue #14573: fix javadoc type check for empty tags

- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/Example1.java
- src/xdocs/checks/coding/simplifybooleanreturn.xml
- src/xdocs/checks/coding/simplifybooleanreturn.xml.template
**Summary**
This pull request aims to enable example tests for the ** SimplifyBooleanReturnCheck** in the project. The implementation focuses on ensuring that the SimplifyBooleanReturn checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.
> Issue #13345: Enable examples tests for SimplifyBooleanReturnCheck

- src/main/resources/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocParser.g4
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescriptionTwo.java
Solves https://github.com/checkstyle/checkstyle/issues/13061
**CLI:**
_config.xml_
```
<module name="NonEmptyAtclauseDescription"/>
</module>
</module>
```
_@param tag:_
```
/**
* @param
*/
public int method(String str)
{
return 1;
}
}
$ java -jar checkstyle-10.15.1-SNAPSHOT-all.jar -c config.xml Test.java
[ERROR] D:\checkproject\parser\Test.java:4: At-clause should have a non-empty description. [NonEmptyAtclauseDescription]
Audit done.
``` …
> Issue #13061: Update grammar for @exception, @throws, and @param tags

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java
For #14019 
Removed suppression
```
<sourceFile>SuppressionXpathSingleFilter.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.filters.SuppressionXpathSingleFilter</mutatedClass>
<mutatedMethod>setMessage</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.MemberVariableMutator</mutator>
<description>Removed assignment to member variable message</description>
<lineContent>this.message = null;</lineContent>
</mutation>
```
**Steps followed to kill mutation**
-  Removed suppression from` pitest-filters-suppressions.xml`
- Listed pitest profiles with `groovy .ci/pitest-survival-check-xml.groovy --list` using java 11 and groovy 2.4.5
- Picked up `pitest-filters` as active profile
- Generated report locally using `mvn …
> Issue #14019: Kill mutation on SuppressionXpathSingleFilter

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSuperFinalizeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/superfinalize/InputXpathSuperFinalizeAnonymousClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/superfinalize/InputXpathSuperFinalizeInnerClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/superfinalize/InputXpathSuperFinalizeNoFinalize.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
**Xpath Regresssion test for Superfinalize**
* [`src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSuperFinalizeTest.java`](diffhunk://#diff-5502589ccdf2d7cd1bc12c8ce8b31eb64d9528809bd77e155768c41b1c29d73dR1-R76)
* [`src/it/resources/org/checkstyle/suppressionxpathfilter/superfinalize/InputXpathSuperFinalizeMethodReference.java`](diffhunk://#diff-046c742554230f7c88efe927b402ffa6299f56cc8205ca899cb6e8bb1eaccf64R1-R16)
* [`src/it/resources/org/checkstyle/suppressionxpathfilter/superfinalize/InputXpathSuperFinalizeNoFinalize.java`](diffhunk://#diff-51e8c7c7c44a6adac410f5c33072477603faee7f7a4222e8a4084e31f125b0a8R1-R7)
* Removal of `SuperFinalize` from Regression Test
> Issue #6207: Xpath Regresssion test for Superfinalize

- config/signatures-test.txt
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XdocGenerator.java
additional fix in scope of Issue #14220
detected at https://github.com/checkstyle/checkstyle/pull/15935#issuecomment-2481334319
example of violation after config change:
```
[INFO] --- forbiddenapis:3.8:testCheck (forbiddenapis-test) @ checkstyle ---
[INFO] Scanning for classes to check...
[INFO] Reading bundled API signatures: jdk-unsafe-11
[INFO] Reading bundled API signatures: jdk-deprecated-11
[INFO] Reading bundled API signatures: jdk-system-out
[INFO] Reading bundled API signatures: jdk-non-portable
[INFO] Reading API signatures: ....../checkstyle/config/signatures-test.txt
[INFO] Loading classes to check...
[INFO] Scanning classes for violations...
[ERROR] Forbidden method invocation: java.io.File#createTempFile(java.lang.String,java.lang.String) 
[Use of this method is forbidden, …
```
> Issue #14220: extra fix for File#createTempFile(java.lang.String,javalang.String)

- .github/workflows/google-java-format.yml
https://github.com/google/google-java-format/releases/tag/v1.25.0
> infra: Update google-java-format to 1.25.0

- config/checkstyle-examples-suppressions.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/Example2.java
- src/xdocs/checks/coding/packagedeclaration.xml
- src/xdocs/checks/coding/packagedeclaration.xml.template
**Summary**
This pull request aims to enable example tests for the ** PackageDeclarationCheck** in the project. The implementation focuses on ensuring that  PackageDeclaration checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.
- Adding suppression in config for PackageDeclaration check
> Issue #13345: Enable examples tests for PackageDeclarationCheck

- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName1.java
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName2.java
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName3.java
- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/InputNonAsciiCharacters.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedNonemptyBlocksLeftRightCurly.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedTryCatchIfElse.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByComment.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByVariableName.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyFinallyBlocks.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputFormattedSeparatorWrap.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputFormattedSeparatorWrapComma.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrap.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapComma.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputFormattedVerticalWhitespace.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputVerticalWhitespace.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeAnnotations.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4832nocstylearray/InputNoCstyleArrays.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule521packagenames/InputPackageNameGood.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesBasic.java
- src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/InputEmptyFinallyBlock.java
Issue #13213: Removed redundant `// ok` comments from input files
This PR removes unnecessary `// ok` comments from several input files to improve clarity and maintain consistency across test resources. The changes are aimed at reducing noise in the input files while ensuring they still serve their purpose effectively in testing.
Changes made:
1. Removed redundant `// ok` comments across multiple input files.
2. Verified that the updated input files continue to fulfill their role in testing.
> Pull #13213: Remove // ok comments from input files

- .github/workflows/google-java-format.yml
https://github.com/google/google-java-format/releases/tag/v1.25.1
> config: Update google-java-format.yml to new formatter

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
part of #14881 : remove null usage from `visitJavaDocToken`
> Issue #14881: remove null from visitJavaDocToken in SummaryJavadocCheck

- src/site/resources/js/checkstyle.js
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks/index.xml
- src/xdocs/config_annotation.xml
- src/xdocs/config_blocks.xml
- src/xdocs/config_coding.xml
- src/xdocs/config_design.xml
- src/xdocs/config_filefilters.xml
- src/xdocs/config_filters.xml
- src/xdocs/config_headers.xml
- src/xdocs/config_imports.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/config_metrics.xml
- src/xdocs/config_misc.xml
- src/xdocs/config_modifier.xml
- src/xdocs/config_naming.xml
- src/xdocs/config_regexp.xml
- src/xdocs/config_sizes.xml
- src/xdocs/config_whitespace.xml
Fixes: #13494 
added `index.xml` under `.../xdocs/checks` directory, after running `mvn clean site -Pno-validations` locally, I was able to generate `index.html` file under `.../xdocs/checks` directory. Path of that index.html file: `http://localhost:63342/checkstyle/target/site/checks/index.html`
Created `index.xml` instead of `index.html` because `index.html` gets ignored while generating the site using `mvn clean site -Pno-validations` so it does not appears in the final generated html files. Generating html files through xml files also supports `../checks.html` format.
> Issue #13494: fixed https://checkstyle.org/checks/ & config_xxxx URLs giving 404 error

- .github/workflows/run-checkstyle.yml
#15955
Jar is not downloading without it.
https://github.com/checkstyle/checkstyle/actions/runs/12283085850/job/34275752229#step:6:11
```
un ls -la
ls -la
JAR_NAME=$(find . -name "*-all.jar")
java -jar "$JAR_NAME" -c config.xml Test.java
shell: /usr/bin/bash -e {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
total 16
drwxr-xr-x [2](https://github.com/checkstyle/checkstyle/actions/runs/12283085850/job/34275752229#step:6:2) runner docker 4096 Dec 11 19:14 .
drwxr-xr-x [3](https://github.com/checkstyle/checkstyle/actions/runs/12283085850/job/34275752229#step:6:3) runner docker 4096 Dec 11 19:14 ..
-rw-r--r-- 1 runner docker 1320 Dec 11 …
```
> Issue #15955:  run-checkstyle.yml use filename for download

- .github/workflows/google-java-format.yml
https://github.com/google/google-java-format/releases/tag/v1.25.2
> dependency: Update google-java-format.yml to 1.25.2

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
**Test.java**
```
/**
*/
}
```
**Command:**
`java -jar checkstyle-10.20.2-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g`
**Output:**
```
.../LeftBrace> java -jar checkstyle-10.20.2-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--TEXT -> /**
|--NEWLINE -> \r\n
|--LEADING_ASTERISK ->  *
|--WS ->
|--JAVADOC_TAG -> JAVADOC_TAG
|   |--SEE_LITERAL -> @see
|   |--WS ->
|   |--REFERENCE -> REFERENCE
|   |   |--HASH -> #
|   |   |--MEMBER -> method
|   |   `--PARAMETERS -> PARAMETERS
|   |       |--LEFT_BRACE -> (
|   |       |--ARGUMENT -> Processor
|   |       |--COMMA -> ,
|   |       |--WS ->
|   |       |--ARGUMENT -> String
|   |       `--RIGHT_BRACE -> )
|   |--NEWLINE -> \r\n
| …
```
> Issue #14631: Updated LEFT_BRACE of JavadocTokenTypes to new AST format

- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
part of #13999:
mutation in question:
https://github.com/checkstyle/checkstyle/blob/24eedce6a64145442db5b478c7a39ce0763dad8c/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L57-L64
**Rationale:**
`surroundingAccessModifier ` is one of the deciding factor if  we want to process the method/construction or not. the case `surroundingAccessModifier == null` is when we come on a overriden method. For example : 
```
final Runnable r = new Runnable() {
public void run() {};
};
```
this condition might have been placed there because: 
- it's better not to send surroundingAccessModifier down in camparsions because with null there is always risk of NullPointerException error. 
- this simple checking saves us making unnecessary camparisons.
**Removal is OK**  because …
> Issue #13999: kill mutation for JavadocMethodCheck

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentsAfterMethodCall.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationWithInMethodCallWithSameIndent.java
Worked on Issue #13213: removed //ok from "commentsindentation" module and replaced them with proper comment messages.
> Issue #13213: remove //ok from commentsindentation

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Test.java
```
/**
*/
}
```
Command:
` java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g" `
Output:
```
|   |   |--COMMENT_CONTENT -> *\n * @see #method(Processor, String)\n  
|   |   |       |--WS ->   
|   |   |       |--JAVADOC_TAG -> JAVADOC_TAG 
|   |   |       |   |--SEE_LITERAL -> @see 
|   |   |       |   |--REFERENCE -> REFERENCE 
|   |   |       |   |   |--HASH -> # 
|   |   |       |   |   |--MEMBER -> method 
|   | …
```
> Issue #14631: Updated Right_Brace to new AST format

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/javadoc/package-info.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/package-info.java
- src/xdocs/checks/javadoc/missingjavadocpackage.xml
- src/xdocs/checks/javadoc/missingjavadocpackage.xml.template
**Summary**
This pull request aims to enable example tests for the **  MissingJavadocPackageCheck** in the project. The implementation focuses on ensuring that   MissingJavadocPackage are correctly validated through comprehensive test cases, improving overall code reliability and quality.
> Issue #13345: Enable examples tests for MissingJavadocPackageCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue :#14631
**Command Used:**
java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
```
/**
*  @Code Comparable&lt;E&gt;
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\r\n *  @Code Comparable&lt;E&gt;\r\n
|   |   |       |   |--CUSTOM_NAME -> @Code
|   |   |       |   `--DESCRIPTION -> DESCRIPTION
|   |   |       |       |--TEXT -> Comparable&lt;E&gt;
|   |   |       |       |--NEWLINE -> \r\n
|   | …
```
> Issue #14631: Updated code_literal in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
part of #14881 : remove null usage from methods : `untaggedSummary`, `findSentenceEndingOrNull` , `getFirstSentenceOrNull`
> Issue #14881: remove null from ValidateUntaggedSummary in SummaryJavadocCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
**Command:** 
`
**Test.java**
```
/**
* @see org.apache.utils.Lists.Comparator#compare(Object)
*/
}
```
```
KIIT0001@BT01290 MINGW64 /c/git-repositories/package_class AST
|   |   |--COMMENT_CONTENT -> *\r\n * @see org.apache.utils.Lists.Comparator#compare(Object)\r\n …
```
> Issue #14631: Updated PACKAGE_CLASS to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631:  ARGUMENT
**Command:**
```
$ java -jar checkstyle-10.13.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
```
**Test.java**
```
```
**Output:**
```
elina@fedora:~/IdeaProjects/sandbox/java17
$ java -jar checkstyle-10.13.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--LEADING_ASTERISK -> *
|--WS ->
|--JAVADOC_TAG -> JAVADOC_TAG
|   |--SEE_LITERAL -> @see
|   |--WS ->
|   |--REFERENCE -> REFERENCE
|   |   |--HASH -> #
|   |   |--MEMBER -> method
|   |   `--PARAMETERS -> PARAMETERS
|   |       |--LEFT_BRACE -> (
|   |       |--ARGUMENT -> Processor
|   |       |--COMMA -> ,
|   |       |--WS ->
|   |       |--ARGUMENT -> String
|   |       `--RIGHT_BRACE -> )
|   `--NEWLINE -> \n
`--EOF -> …
```
> Issue #14631: Update ARGUMENT to new AST format in Javadoc

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631: FIELD_TYPE
**Command:**
```
$ java -jar checkstyle-10.13.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
```
**Test.java**
```
@serialField counter Integer objects counter
```
**Output:**
```
elina@fedora:~/IdeaProjects/sandbox/jdk17
$ java -jar checkstyle-10.13.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--JAVADOC_TAG -> JAVADOC_TAG
|   |--SERIAL_FIELD_LITERAL -> @serialField
|   |--WS ->
|   |--FIELD_NAME -> counter
|   |--WS ->
|   |--FIELD_TYPE -> Integer
|   |--WS ->
|   `--DESCRIPTION -> DESCRIPTION
|       |--TEXT -> objects counter
|       `--NEWLINE -> \n
`--EOF -> <EOF>
```
> Issue #14631: Update FIELD_TYPE to new AST format in Javadoc

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
Updated COMMA to new AST format
**Command**: 
`
**Test.java**
```
/**
*/
}
```
```
KIIT0001@BT01290 MINGW64 /c/git-repositories/Comma_AST
|   |   |--COMMENT_CONTENT -> *\r\n * @see #method(Processor, String)\r\n
|   |   |       |   |--SEE_LITERAL -> @see
| …
```
> Issue #14631: Updated COMMA to new AST format

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineMultilineForDeclarations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineMultilineInLoopsAndTryWithResources.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineSingleLineInLoops.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineSingleLineSmallTalkStyle.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTryWithResources.java
Issue #15456: Specify violation messages for OneStatementPerLineCheck
Regarding [InputOneStatementPerLine.java](https://github.com/checkstyle/checkstyle/compare/master...ElinaZoldnere:checkstyle:15456-specify-violation-messages/OneStatementPerLine?expand=1#diff-32263841b4aa69afe876dff943de41941f57264f790c20047fda39b0ee824a30) - I didn't find the matching violation pattern for comment
```// X violations below 'Some message here.'```
Only a pattern without a message.
```
/** A pattern to find the string: "// X violations below". */
private static final Pattern MULTIPLE_VIOLATIONS_BELOW_PATTERN = Pattern
.compile(".*//\\s*(\\d+) violations below$");
```
So I utilized this:
```
/**
* <div>
* Multiple violations for line. Violations are Y lines below, messages are X lines below.
* {@code
* …
```
> Issue #15456: Specify violation messages for OneStatementPerLineCheck

- config/jsoref-spellchecker/whitelist.words
- src/site/resources/css/site.css
- src/site/resources/js/checkstyle.js
Resolves #8244
Added a hamburger for the mobile/tablet view. User can toggle the menu's visibility using that.
The hamburger is added in the `breadcrumbs` bar and I have made it stick to the top for mobile view. 
Currently, if the user makes the menu visible, he isn't automatically scrolled to the top to see the menu, he will still need to manually scroll up. @rnveach @nrmancuso @romani, do you want to automatically scroll user to the top when he makes the menu visible?
Also, I haven't changed anything in Menu's styling for mobile view, if any maintainer requests for that, I will gladly do it :)
> Issue #8244: Added expandable menu for mobile/tablet devices

- pom.xml
from:
https://github.com/checkstyle/checkstyle/actions/runs/12587684935/job/35084028290#step:4:2642
```
--- .ci-temp/linkcheck-suppressions-sorted.txt	2025-01-02 19:31:24.433823367 +0000
+++ .ci-temp/linkcheck-errors-sorted.txt	2025-01-02 19:31:24.429823366 +0000
@@ -1,3 +1,4 @@
+<a class="externalLink" href="https://codeclimate.com/">https://codeclimate.com/</a>: 403 Forbidden
```
> minor: codeclimate.com is skipped from link validation; permanent 403

- .ci/check-performance-regression.sh
- .ci/validation.sh
from https://github.com/checkstyle/checkstyle/actions/runs/12589564511/job/35089604527?pr=16078#step:4:8
```
In ./.ci/check-performance-regression.sh line 106:
exit $?
^-----^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
In ./.ci/validation.sh line 408:
if [ ${a} != ${b} ]
^--^ SC208[6](https://github.com/checkstyle/checkstyle/actions/runs/12589564511/job/35089604527?pr=16078#step:4:7) (info): Double quote to prevent globbing and word splitting.
^--^ SC2086 (info): Double quote to prevent globbing and word splitting.
Did you mean: 
if [ "${a}" != "${b}" ]
For more information:
https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
https://www.shellcheck.net/wiki/SC231[7](https://github.com/checkstyle/checkstyle/act …
```
> minor: fix bash spelling SC2086 and SC2317

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationPlain.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationWithCommentOnly.java
Issue: #13213 
This PR addresses the removal of //ok comments from the file InputPackageDeclarationPlain
> Issue #13213: remove ok from InputPackageDeclarationPlain

- .ci/generate-extra-site-links.sh
extra update for initial update of Issue #16077
detected at:
https://github.com/checkstyle/checkstyle/pull/16105#issuecomment-2569731597
```
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/bebb18d_2025194407/index.html
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/bebb18d_2025194407/src/site/xdoc/checks/header/header.xml.html#Description
```
link to Check is broken, as xdoc location is changed.
> Issue #16077: fix extra links for site workflow

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
**Command:**
`
**Test.java**
```
/**
* @see "Spring Framework"
*/
}
```
```
KIIT0001@BT01290 MINGW64 /c/git-repositories/string_AST
|   |   |--COMMENT_CONTENT -> *\r\n * @see "Spring Framework"\r\n
|   |   |       |   |--SEE_LITERAL -> @see …
```
> Issue #14631: Updated STRING to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Test
```
/**
* @throws SQLException if query is not correct
*/
void foo() {}
}
:/var/tmp$ java -jar checkstyle-10.20.2-all.jar -J Test.java
|--METHOD_DEF -> METHOD_DEF [5:2]
|   |--MODIFIERS -> MODIFIERS [5:2]
|   |--TYPE -> TYPE [5:2]
|   |   |--BLOCK_COMMENT_BEGIN -> /* [2:0]
|   |   |   |--COMMENT_CONTENT -> *\n * @throws SQLException if query is not correct\n [2:2]
|   |   |   |   `--JAVADOC -> JAVADOC [2:3]
|   |   |   |       |--NEWLINE -> \n [2:3]
|   |   |   | …
```
> Pull #14631: Updated THROWS_LITERAL of JavadocTokenTypes to new AST

- README.md
- config/jsoref-spellchecker/whitelist.words
https://support.cci.drexel.edu/getting-connected/discord/create-invite-links/#:~:text=How%20to%20Customize%20a%20Discord,long%20the%20link%20will%20last.
We deprecating Element chat.
> minor: Update README.md with never expiring invite link

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
**Command Used:**
`java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* @serialField counter Integer objects counter
*/
}
```
```
Arnab@LAPTOP-4M502KT5 MINGW64 ~/Desktop/FIELD_NAME AST
|   |   |--COMMENT_CONTENT -> *\r\n * @serialField counter Integer objects counter\r\n
|   |   |       |   |--SERIAL_FIELD_LITERAL -> …
```
> Issue #14631: Updated FIELD_NAME of JavadocTokenTypes to new AST format

- src/site/xdoc/checks/misc/orderedproperties.xml
- src/site/xdoc/checks/misc/orderedproperties.xml.template
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/orderedproperties/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/orderedproperties/Example1.properties
Issue https://github.com/checkstyle/checkstyle/issues/13345
Enable examples tests for `OrderedPropertiesCheck`
- .txt converted to .java + .properties
- xml updated
- enabled example tests
- used new method in `AbstractModuleTestSupport`
https://checkstyle.org/checks/misc/orderedproperties.html#Examples
> Issue #13345: Enable example test for OrderedPropertiesCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javadoc.html#serial
` java -jar checkstyle-10.21.1-all.jar -J Test.java | gsed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* @serial exclude
*/
}
```
```
devanggupta@Devangs-MacBook-Pro Literal Exclude Ast % java -jar checkstyle-10.21.1-all.jar -J Test.java | gsed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\n * @serial exclude\n  
|   |   |       |--WS ->   
|   |   |       |--JAVADOC_TAG -> JAVADOC_TAG  …
```
> Issue #14631: Updated literal_exclude in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
**comment used**
`java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
*@serial include
*/
}
```
```
AHIL@DESKTOP-17M5Q0M MINGW64 ~/IdeaProjects/literal_include AST
|   |   |--COMMENT_CONTENT -> *\r\n *@serial include\r\n
|   |   |       |   |--SERIAL_LITERAL -> @serial
|   |   |       |   |--LITERAL_INCLUDE -> include …
```
> Issue #14631: Updated LITERAL_INCLUDE in JavadocTokenTypes.java in new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
**Command:**
```
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
```
**Test.java**
```
/**
* @param T The bar.
*/
}
```
**Output:**
```
Harsh@LAPTOP-G8FFVU8Q MINGW64 /d/contribute/PARAMETER_NAME AST
|   |   |--COMMENT_CONTENT -> *\r\n * @param T The bar.\r\n
|   |   |       |   |--PARAM_LITERAL -> @param
|   | …
```
> Issue #14631: Update PARAMETER_NAME in javadocTokenType to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
``` 
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g" 
```
```java
/**
* @see org.apache.utils.Lists.Comparator#compare(Object)
*/
public class Test{    
} 
```
```
|--BLOCK_COMMENT_BEGIN -> /* 
|   |--COMMENT_CONTENT -> *\n * @see org.apache.utils.Lists.Comparator#compare(Object)\n  
|   |   `--JAVADOC -> JAVADOC 
|   |       |--NEWLINE -> \n 
|   |       |--LEADING_ASTERISK ->  * 
|   |       |--WS ->   
|   |       |--JAVADOC_TAG -> JAVADOC_TAG 
|   |       |   |--SEE_LITERAL -> @see 
|   |       |   |--WS ->   
|   |       |   |--REFERENCE -> REFERENCE 
|   |       |   | …
```
> Issue #14631: Updated MEMBER in javadocTokenTypes.java to new AST format

- src/site/resources/css/site.css
part of #16077 
made `code` text wrappable.
> Issue #16077: made non-formatted text wrappable

- src/site/resources/css/site.css
- src/site/resources/js/anchors.js
part of #16077 
> click on name of section use to update link in browser location to have full link with anchor. Kill feature for maintainers to share link to exact place in doc. Now it is generating `#undefined`
I have fixed undefined links for h1 & h2 links. Is there any other tags like h3,h4,h5,h6 which gives `#undefined` links?
> Issue #16077: fixed #undefined links for h1 & h2 sections

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
java -jar checkstyle-10.16.0-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
@see org.apache.utils.Lists.Comparator#compare(Object)
```
|--TEXT -> /** [0:0]
|--NEWLINE -> \r\n [0:3]
|--LEADING_ASTERISK ->  * [1:0]
|--WS ->   [1:2]
|--JAVADOC_TAG -> JAVADOC_TAG [1:3]
|   |--SEE_LITERAL -> @see [1:3]
|   |--WS ->   [1:7]
|   |--REFERENCE -> REFERENCE [1:8]
|   |   |--PACKAGE_CLASS -> org.apache.utils.Lists.Comparator [1:8]
|   |   |--HASH -> # [1:41]
|   |   |--MEMBER -> compare [1:42]
|   |   `--PARAMETERS -> PARAMETERS [1:49]
|   |       |--LEFT_BRACE -> ( [1:49]
|   |       |--ARGUMENT -> Object [1:50]
|   |       `--RIGHT_BRACE -> ) [1:56]
|   |--NEWLINE -> \r\n [1:57]
|   `--DESCRIPTION -> DESCRIPTION [2:0]
| …
```
> Issue #14631: Updated Hash_literal in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
Command used:
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
Test.java
```text before break <br> text after break```
```
|   |   |--COMMENT_CONTENT -> *\r\n * text before break <br> text after break\r\n
|   |   |       |--TEXT ->  text before break
|   |   |       |       `--BR_TAG -> BR_TAG
|   |   |       |           |--START -> <
|   |   |       |           |--BR_HTML_TAG_NAME -> br …
```
> Issue #14631: Updated BR_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

- src/site/resources/css/site.css
part of #16077
> no link images as first column
problem: the anchor image was too small
> Issue #16077: Fixed anchor image size

- config/jsoref-spellchecker/whitelist.words
- src/site/resources/css/site.css
part of #16077 
> all table headers column text should be adjusted to left. Not a middle of cell.
> Issue #16077: changed alignment of table header text to left and added background color

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
Command used:
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
Test.java
```<tr></tr>```
```
|   |   |--COMMENT_CONTENT -> *\r\n * <tr></tr>\r\n
|   |   |       |   `--TR -> TR
|   |   |       |       |--TR_TAG_START -> TR_TAG_START
|   |   |       |       |   |--START -> <
|   |   |       |       |   |--TR_HTML_TAG_NAME -> tr
|   |   |       |       |   `--END -> >
|   |   |       |       `--TR_TAG_END -> TR_TAG_END …
```
> Issue #14631: Updated TR_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
#14631 
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
```
/**
* @exception SQLException if query is not correct
*/
}
```
```
prave@DESKTOP-ONMIJ3B MINGW64 /e/Projects/TestProject
|   |   |--COMMENT_CONTENT -> *\r\n * @exception SQLException if query is not correct\r\n
|   |   |       |   |--EXCEPTION_LITERAL -> …
```
> Issue #14631: Updated exception_literal in JavadocTokenTypes.java to new format of AST

- src/site/resources/css/site.css
added missing `}` in site.css
it was removed at commit: https://github.com/checkstyle/checkstyle/commit/45fca03deaff04c202469ff2c3192ba4c573ec57#diff-864a902184d44aa82cfc0242b94b8fec71ff45299594744e94ca51d95e5da822R93-R104
> minor: added missing closing curly bracket for img[src=images/anchor.png]

- src/site/resources/css/site.css
part of #16077 
> mobile web site should have tables to be single column.
all tables had `tableBody` class in previous theme. Currently it is replaced with two classes: `table table-striped`.
In this PR, I removed all the `tableBody` references and replaced them with the tag name `table`, I think there should not be any problems with this change. I checked the website locally and it was looking fine to me.
> Issue #16077: made tables single column for mobile devices and removed .bodyTable class reference

- src/site/resources/css/site.css
part of #16077
> remove text links under banner images in left panel, just image/banner is enough.
> Issue #16077: Removed text under banner images in menu

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
#14631 
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed -E "s/[[0-9]+:[0-9]+]//g"
**Test.java**
```
/**
* {@link String}
*/
}
```
**Output**
```
java -jar checkstyle-10.21.1-all.jar Test.java -J | sed -E "s/\[[0-9]+:[0-9]+\]//g"
|   |   |--COMMENT_CONTENT -> *\n * {@link String}\n  
|   |   |       |--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG 
|   |   |       |   |--JAVADOC_INLINE_TAG_START -> { 
|   |   |       |   |--LINK_LITERAL -> @link 
|   |   | …
```
> Issue #14631: Update JAVADOC_INLINE_TAG in JavadocTokenTypes

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclaration4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclaration5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclaration6.java
This PR fixes Issue #16101:  where MagicNumberCheck was incorrectly flagging magic numbers in field declarations containing arithmetic operations even when ignoreFieldDeclaration=true.
The fix moves the field declaration check to the start of the visitToken method to ensure all field declarations are properly ignored when the option is enabled.
> Issue #16101: Fixed MagicNumber Check Bug

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java
resolves #15939 
main point:
>Whitespaces on the end line of the text block are not part of the string and there is nothing visible before the end of the text block. It should be indented by this check because it is code and it starts the line.
```xml
$ cat testconfig.xml 
<property name="severity" value="${org.checkstyle.google.severity}" default="warning"/>
<property name="fileExtensions" value="java, properties, xml"/>
<module name="SuppressWarningsFilter"/>
<module name="SuppressWarningsHolder"/>
<module name="Indentation">
<property …
```
> Issue #15939: false-positive for text-block-literal at indentation fix

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631 
**Command Used:**
`
**Test.java**
```
/**
* @param T The bar.
*/
}
```
```
Smita Prajapati@Smita-5ESU2EG5 MINGW64 ~/RULE_javadocTag
|   |   |--COMMENT_CONTENT -> *\r\n * @param T The bar.\r\n
|   |   |       |   |--PARAM_LITERAL -> @param …
```
> Issue #14631: Updated JAVADOC_TAG in javadocTokenType to new AST format

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationMultilineCodeBlock.java
Issue: #13213 
Remove '// ok' comments from  javadocblocktaglocation
> Issue #13213: remove OK comments from javadocblocktaglocation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/FileTabCharacterCheck.xml
- src/site/xdoc/checks/whitespace/filetabcharacter.xml
- src/site/xdoc/checks/whitespace/filetabcharacter.xml.template
Issue #16225 
This PR adds an explicit Note about checks default behaviour:
When the `FileTabCharacter` check is used with the default configuration,
only the first instance of a tab character is reported.
> Issue #16225: Update FileTabCharacter documentation with default config behaviour in case of suppressions

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc2One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc2Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc3One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc3Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly1One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly1Two.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly2One.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly2Two.java
Issue #11163
Resolves the file size under MissingJavadocType from exceeding 120 lines and removed related suppressions
> Issue #11163: Enforce file size under MissingJavadocType

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationYieldForceStrict.java
> Issue #15967: fix yield fails indentation in switch with forceStrictCondition

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
** Test.java **
```
* {@link org.apache.utils.Lists.Comparator#compare(Object)}
*/
}
```
```
java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\n * {@link org.apache.utils.Lists.Comparator#compare(Object)}\n  
|   |   |       |--JAVADOC_INLINE_TAG -> JAVADOC_INLINE_TAG 
|   |   |       |   |--JAVADOC_INLINE_TAG_START -> { 
|   |   |       |   |--LINK_LITERAL -> @link  …
```
> Issue #14631 : Updated Link_Literal in JavadocTokenTypes to new AST format

- src/site/resources/css/site.css
This pull request solves the issue #16243 by removing the unnecessary space between top image and the gray bar. It was done by setting the .banner class height to 97px to ensure proper alignment.
Issue Link:
Fixes: #16243
> Issue #16243: Remove extra spacing between top image and gray bar in header

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
```
maximpaxim@maximpaxim-OMEN-by-HP-Laptop-15-dc0xxx:~/Desktop/javadoc test$ cat Test.java
/**
* @param T The bar.
*/
}
maximpaxim@maximpaxim-OMEN-by-HP-Laptop-15-dc0xxx:~/Desktop/javadoc test$ java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\n * @param T The bar.\n  
|   |   |       |--WS ->   
|   |   |       |--JAVADOC_TAG -> JAVADOC_TAG 
|   |   |       |   |--PARAM_LITERAL -> @param  …
```
> Issue #14631: Updated JAVADOC of JavadocTokenTypes.java to to new AST format

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
Issue #15983 
Added validation to default in InlineConfigParser
```
diff --git a/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsCompactNonConstant1.java b/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsCompactNonConstant1.java
index 14c16e7c96b..7cbb8610eeb 100644
--- a/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsCompactNonConstant1.java
+++ b/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsCompactNonConstant1.java
@@ -1,6 +1,6 @@
/*
SuppressWarnings
-format = (default)^\s*+$
+format = …
```
> Issue #15983 :added validation to default

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: https://github.com/checkstyle/checkstyle/issues/14631
Command used:
`java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
`
Input:
Test.java
```
/**
*  Type here: <input type="text" id="id" name="name">
*/
class Test {
}
```
Output:
```
|--BLOCK_COMMENT_BEGIN -> /*
|   |--COMMENT_CONTENT -> *\r\n *  Type here: <input type="text" id="id" name="name">\r\n
|   |   `--JAVADOC -> JAVADOC
|   |       |--NEWLINE -> \r\n
|   |       |--LEADING_ASTERISK ->  *
|   |       |--TEXT ->   Type here:
|   |       |--HTML_ELEMENT -> HTML_ELEMENT
|   |       |   `--SINGLETON_ELEMENT -> SINGLETON_ELEMENT
|   |       |       `--INPUT_TAG -> INPUT_TAG
|   |       |           |--START -> < …
```
> Issue #14631: Updated INPUT_TAG in JavadocTokenTypes.java to new AST format

- src/site/resources/css/site.css
Fixed the left column alignment issue that caused text to misalign due to improper width handling with minimal changes. It was previously using width: fit-content which led to inconsistent wrapping, especially for long words.
Before:
After:
Issue Link: 
Fixes: #16291
> Issue #16291: Fixed UI overlap issue in documentation sidebar

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerSpecialName.xml
Issue #14019  
using command  
` mvn -e --no-transfer-progress -Ppitest-common clean test-compile org.pitest:pitest-maven:mutationCoverage
`
Kill mutation for removing the call to the encoding method
Kill mutation for removing the call to the `writer.println` in writeFileClosingTag Method
> Issue #14019: Resolve pitest suppressions for XMLLogger  FileOpeningTag

- src/site/resources/css/site.css
Fixed the gap between the left column and the top bar. Adjusted positioning to move the left column up without messing with the breadcrumb padding.
Before: 
After: 
Part of: #16243
> Issue #16243: Fixed left column alignment

- src/site/resources/css/site.css
Issue #16243
Too much top/bottom spacing was present on code snippets then remove the spacing on code snippets.
This is not overlapping with https://github.com/checkstyle/checkstyle/pull/16250 as it fixes different kind of code blocks.
> Issue #16243: remove top/bottom spacing on code snippets

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
The change improves the documentation for the area html tag. The test comment included the area tag with one attribute (shape = "rect").
**Test file**
```
/**
* <area shape="rect">
*/
}
}
```
**Command**
`java -jar checkstyle-10.21.2-all.jar -J Test.java | sed -E "s/\[[0-9]+:[0-9]+\]//g"`
**Full output**
```
|   |   |--COMMENT_CONTENT -> *\n * <area shape="rect">\n   …
```
> Issue #14631: Updated area html tag documentation

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
This change improves the `area_tag` documentation. It reuses the documentation from `area_html_tag_name`.
The test comment included the area tag with one attribute (`shape = "rect"`).
**Test file**
```
/**
* <area shape="rect">
*/
}
}
```
**Command**
`java -jar checkstyle-10.21.2-all.jar -J Test.java | sed -E "s/\[[0-9]+:[0-9]+\]//g"`
**Full output**
```
|   |   |--COMMENT_CONTENT -> *\n * <area shape="rect">\n  
|   |   |       |--HTML_ELEMENT -> …
```
> Issue #14631: Improved area tag documentation

- src/site/xdoc/checks/coding/missingswitchdefault.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/Example1.java
Issue: #16262 
- **Removed the Default Clause:** In the switch statement (see Example3.java), I've removed the default clause.
- **Added a Comment:** I've added an inline comment on the switch to indicate that it now intentionally violates the MissingSwitchDefault rule.
- **Updated Tests:** The tests (in MissingSwitchDefaultCheckExamplesTest.java) have been adjusted to reflect this change, so they now expect the violation accordingly.
> Issue #16262: update MissingSwitchDefault doc

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleErrorColumn0.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleErrorColumn1.sarif
Issue #14019
Kill mutation for `ArgumentPropagationMutator on .replace(MESSAGE_PLACEHOLDER, escape(event.getMessage()))` under `SarifLogger`
**Reason for mutation:**
The reason is related with `escape` method on `SarifLogger.java` , In `addError` method we are using `escape` method to modify some selected characters of string `event.getMessage()` ( `violation` from `event class` ) but all test cases available has not any character that need to modify and falls to default switch condition of `escape` method then the `return` string of `escape` method is similar with `parameter` string of `escape` method.
**Solution:**
Added the test case which will have the character `\n` that must need to be modify by `escape` method then mutation kill and even not creating any new mutation.
> Issue #14019: kill mutation for SarifLogger under addError method 

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberEmptyInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberSimple1.java
ISSUE : https://github.com/checkstyle/checkstyle/issues/13213
Removed //ok from outerTypeNumber module from Input files.
**PROOF:**
```
$ grep outertypenumber config/checkstyle-input-suppressions.xml
files="checks[\\/]sizes[\\/]outertypenumber[\\/]InputOuterTypeNumberEmptyInner.java"/>
files="checks[\\/]sizes[\\/]outertypenumber[\\/]InputOuterTypeNumberSimple1.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (removeOk)
$ grep outertypenumber config/checkstyle-input-suppressions.xml
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (removeOk)
$ echo $?
1
```
> Issue #13213: Remove '//ok' comments from Input files(outertypenumber)

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/annotationutil/InputAnnotationUtil2.java
Removed //ok from annotationutil module from Input files.
**PROOF:**
```
$ grep annotationutil config/checkstyle-input-suppressions.xml
files="utils[\\/]annotationutil[\\/]InputAnnotationUtil2.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (annotationUtil)
$ grep annotationutil config/checkstyle-input-suppressions.xml
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (annotationUtil)
$ echo $?
1
```
> Issue #13213: Remove '//ok' comments from Input files(annotationutil)

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple3.java
Removed //ok from parameternumber module from Input files.
**PROOF:**
```
$ grep parameternumber config/checkstyle-input-suppressions.xml
files="checks[\\/]sizes[\\/]parameternumber[\\/]InputParameterNumberSimple3.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (parameterNumber)
$ grep parameternumber config/checkstyle-input-suppressions.xml
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (parameterNumber)
$ echo $?
1
```
> Issue #13213: Remove '//ok' from Input Files(parameternumber)

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForInvalidOption.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestTrailingWhitespace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapWithEmoji.java
Removed //ok from separatorwrap module from Input files.
**PROOF**:
```
$ grep separatorwrap config/checkstyle-input-suppressions.xml
files="checks[\\/]whitespace[\\/]separatorwrap[\\/]InputSeparatorWrapForInvalidOption.java"/>
files="checks[\\/]whitespace[\\/]separatorwrap[\\/]InputSeparatorWrapForTestTrailingWhitespace.java"/>
files="checks[\\/]whitespace[\\/]separatorwrap[\\/]InputSeparatorWrapForTestTrailingWhitespace.java"/>
files="checks[\\/]whitespace[\\/]separatorwrap[\\/]InputSeparatorWrapWithEmoji.java"/>
files="checks[\\/]whitespace[\\/]separatorwrap[\\/]InputSeparatorWrapWithEmoji.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (separatorWrap)
$ grep …
```
> Issue #13213: Remove '//ok' from Input Files(separatorwrap)

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
This change improves the li documentation.
**Test file**
```java
/**
* <li>Test</li>
*/
}
```
**Command**
```sh
mvn exec:java -q -Dexec.mainClass="com.puppycrawl.tools.checkstyle.Main" -Dexec.args="-J Test.java" | sed -E "s/\[[0-9]\+:[0-9]\+\]//g"
```
**Output**
```
|   |   |--COMMENT_CONTENT -> *\n * <li>Test</li>\n  
|   |   |       |   `--LI -> LI 
|   |   |       |       |--LI_TAG_START -> LI_TAG_START 
|   |   |       |       |   |--START …
```
> Issue checkstyle#14631: Updated LI to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
**Command used**
`java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* <p></p>
*/
}
```
```
MohamedMetwalli@DESKTOP-I42140D MINGW64 ~/Desktop
$ java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * <p></p>\r\n
|   |   |       |   `--PARAGRAPH -> PARAGRAPH
|   |   |       |       |--P_TAG_START -> P_TAG_START …
```
> Issue #14631: Updated PARAGRAPH in JavadocTokenTypes.java to new AST format

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckB3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckB4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckEmptyLine2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckStopEarly.java
Issue #13213
Removed `//ok` comments from:
- InputRegexpCheckB3.java
- InputRegexpCheckB4.java
- InputRegexpCheckEmptyLine2.java
- InputRegexpCheckStopEarly.java
and Updated _checkstyle-input-suppressions.xml_ to handle the affected checks appropriately.
> Issue #13213: removed //ok from InputRegexpCheck

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclarationNullAst.java
Removed //ok from unnecessarysemicolonaftertypememberdeclaration module from Input files.
-> 1 //ok from 1 file
**PROOF:**
```
$ grep unnecessarysemicolonaftertypememberdeclaration config/checkstyle-input-suppressions.xml
files="checks[\\/]coding[\\/]unnecessarysemicolonaftertypememberdeclaration[\\/]InputUnnecessarySemicolonAfterTypeMemberDeclarationNullAst.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (unnecessarySemicolon)
$ grep unnecessarysemicolonaftertypememberdeclaration config/checkstyle-input-suppressions.xml
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (unnecessarySemicolon)
$ echo $?
1
```
> Issue #13213: Remove '//ok' from Input Files(unnecessarysemicolon)

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtil7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/package-info.java
Removed //ok from checkutil module from Input files
PROOF:
```
$  grep checkutil config/checkstyle-input-suppressions.xml
files="utils[\\/]checkutil[\\/]InputCheckUtil4.java"/>
files="utils[\\/]checkutil[\\/]InputCheckUtilPackage.java"/>
files="utils[\\/]checkutil[\\/]package-info.java"/>
files="utils[\\/]checkutil[\\/]InputCheckUtil7.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (checkUtil)
$  grep checkutil config/checkstyle-input-suppressions.xml
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (checkUtil)
$ echo $?
1
```
> Issue #13213: Remove '//ok' From Input File(checkutil)

- config/checkstyle-input-suppressions.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilterNullViolation.java
Removed //ok from suppressionxpathsinglefilter  module from Input files
PROOF:
```
$ grep suppressionxpathsinglefilter config/checkstyle-input-suppressions.xml
files="filters[\\/]suppressionxpathsinglefilter[\\/]InputSuppressionXpathSingleFilterNullViolation.java"/>
```
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (suppresionXPathSingleFilter)
$ grep suppressionxpathsinglefilter config/checkstyle-input-suppressions.xml
DELL@DESKTOP-KL8FGN8 MINGW64 ~/checkstyle (suppresionXPathSingleFilter)
$ echo $?
1
```
> Issue #13213: Remove '//ok'from(suppressionxpathsinlefilter)

- config/pitest-suppressions/pitest-filters-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterTest.java
#14019 
https://github.com/checkstyle/checkstyle/blob/dcc81520f445d456dbaafc4447071fb4ef74b9fe/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilter.java#L194-L200
this optimization is for make sure that `getFileText` and  `collectSuppressions` is called ones on a file, performance optimization, functioanlly and behavior that user see  all stays the same, that is why pitest see it un necessary code. 
we can try to remove target file while between  execution of `accept`, so this will throw exception.
[getFileText](https://github.com/checkstyle/checkstyle/blob/dcc81520f445d456dbaafc4447071fb4ef74b9fe/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilter.java#L228-L233)
> Issue #14019: Kill mutation in SuppressWithNearbyTextFilter

- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag.java
Removing closed issue reference from :
https://github.com/Anmol202005/checkstyle/blob/AnnotationLine/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag.java#L49
removed until comment.
> minor: removing closed issues reference

- config/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
- src/site/xdoc/index.xml.vm
- src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerAbsoluteLinuxPath.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerAbsoluteWindowsPath.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleError.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerLineOnly.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerRelativeLinuxPath.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerRelativeWindowsPath.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleError.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleWarning.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSpaceInPath.sarif
Issue #16127
I am not sure this covers all cases that the URIs will always be valid, but I didn't find a Java method that doesn't change relative paths to absolute paths automatically. I have already spent most of the day on this, because the test tooling for this project is quite slow.
> Issue #16127: Correctly handle windows file paths in SARIF and add a doc link to nvim-lint.

- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java
Issue #14019
The call to `file.getAbsoluteFile()` is unnecessary because the `File` class can handle both relative and absolute paths when reading files. Since we only need to read the file, there is no requirement to explicitly convert it to an absolute path. Additionally, calling `getAbsoluteFile()` creates a new `File` instance that points to the same file, making it redundant and adding unnecessary overhead. 
This is also done in CLI options with the `printFileAst` method, which handles files in the same structure without using getAbsoluteFile().
https://github.com/checkstyle/checkstyle/blob/20284e326cdff304f569b4ff0ebca3a4ddf511de/src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java#L137
> Issue #14019: Resolve pitest suppressions for  SuppressionsStringPrinter

- src/site/xdoc/checks/coding/illegaltype.xml
- src/site/xdoc/checks/coding/illegaltype.xml.template
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/Example8.java
Fixes Issue #14775
Adds a new example that allows the addition of a new type in addition to the Checkstyle defaults to the `IllegalType` check. Here, it uses `var` as an example of a restricted type.
> Issue #14775: Add additional example for IllegalType

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Begins https://github.com/checkstyle/checkstyle/issues/14631
cat Test.java
/**
* <body>
* This is inside the body tag.
* </body>
*/
public class TestBodyTag {
}
(base) youyun@youyundeMacBook-Air checkstyle % java -jar target/checkstyle-10.21.4-SNAPSHOT-all.jar -j Test.java | sed -E "s/\[[0-9]+:[0-9]+\]//g"
JAVADOC -> JAVADOC 
|--TEXT -> /** 
|--NEWLINE -> \n 
|--LEADING_ASTERISK ->  * 
|--TEXT ->   
|--HTML_ELEMENT -> HTML_ELEMENT 
|   `--BODY -> BODY 
|       |--BODY_TAG_START -> BODY_TAG_START 
|       |   |--START -> < 
|       |   |--BODY_HTML_TAG_NAME -> body 
|       |   `--END -> > 
|       |--NEWLINE -> \n 
|       |--LEADING_ASTERISK ->  * 
|       |--TEXT ->  This is inside the body tag. 
|       |--NEWLINE -> \n 
|       |--LEADING_ASTERISK ->  * 
|       |--TEXT ->   
| …
> Issue #14631: Updated BODY_TAG_START BODY_TAG_END  of JavadocTokenTypes

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
This change improves the colgroup documentation.
test file
```
/**
* <colgroup>
*  <col />
*  <col span="2" class="batman" />
* </colgroup>
*/
}
```
command
```
⚡bishoy ❯❯ java -jar checkstyle-10.21.3-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\n * <colgroup>\n *  <col />\n *  <col span="2" class="batman" />\n * </colgroup>\n  
|   |   |       |   `--COLGROUP -> COLGROUP  …
```
> Issue #14631: Updated COLGROUP  of JavadocTokenTypes

- config/checkstyle-examples-suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalIdentifierNameTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalidentifiername/InputXpathIllegalIdentifierNameOne.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalidentifiername/InputXpathIllegalIdentifierNameTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/IllegalIdentifierNameCheck.xml
- src/site/xdoc/checks.xml
- src/site/xdoc/checks/naming/illegalidentifiername.xml
- src/site/xdoc/checks/naming/illegalidentifiername.xml.template
- src/site/xdoc/checks/naming/index.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierName.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameLambda.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameParameterReceiver.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameRecordPattern.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameUnnamedVariables.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheckExamplesTest.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/Example1.java
- src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/Example2.java
Issue: #15499  
https://checkstyle.org/checks/naming/illegalidentifiername.html#IllegalIdentifierName
Changed default value to the newer regex that checks for "var" and $ components in the variable names
Will resolve rest of the CI errors later
> Issue #15499: Changed default for IllegalIdentifierName

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: https://github.com/checkstyle/checkstyle/issues/14631
```bash
java -jar checkstyle-10.21.3-all.jar -j Test.java | ForEach-Object {$_ -replace "\[\d+:\d+\]", ""}
```
```bash
PS C:\Users\ThinkPad\IdeaProjects\checkstyle> Get-Content Test.java   
/** <table><tbody></tbody></table>
PS C:\Users\ThinkPad\IdeaProjects\checkstyle> java -jar checkstyle-10.21.3-all.jar -j Test.java | ForEach-Object {$_ -replace "\[\d+:\d+\]", ""}
JAVADOC -> JAVADOC 
|--TEXT -> /**
|--HTML_ELEMENT -> HTML_ELEMENT
|   `--HTML_TAG -> HTML_TAG
|       |--HTML_ELEMENT_START -> HTML_ELEMENT_START
|       |   |--START -> <
|       |   |--HTML_TAG_NAME -> table
|       |   `--END -> >
|       |--HTML_ELEMENT -> HTML_ELEMENT
|       |   `--TBODY -> TBODY
|       |       |--TBODY_TAG_START -> TBODY_TAG_START
|       | …
```
> Issue #14631: Updated TBODY Token to new AST format

- pom.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidDoubleBraceInitializationTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionConstructorsDeclarationGroupingTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEmptyCatchBlockTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEqualsAvoidNullTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMissingSwitchDefaultTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionModifiedControlVariableTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionModifierOrderTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOverloadMethodsDeclarationOrderTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUncommentedMainTest.java
solves -#16447  : dependency bump  bump pmd.version from 7.10.0 to 7.11.0
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=26513&view=logs&j=7c725a47-0ff7-59ff-90e3-3cd594a39550&t=8f072c98-5edb-5957-d66c-9e7f0eebe900&l=1869
```
[INFO] --- pmd:3.26.0:check (default) @ checkstyle ---
[WARNING] PMD Failure: org.checkstyle.suppressionxpathfilter.XpathRegressionAvoidDoubleBraceInitializationTest:33 Rule:FinalFieldCouldBeStatic Priority:3 This final field could be made static.
[WARNING] PMD Failure: org.checkstyle.suppressionxpathfilter.XpathRegressionConstructorsDeclarationGroupingTest:33 Rule:FinalFieldCouldBeStatic Priority:3 This final field could be made static.
[WARNING] PMD Failure: org.checkstyle.suppressionxpathfilter.XpathRegressionEmptyCatchBlockTest:33 …
```
> dependency: bump pmd.version from 7.10.0 to 7.11.0

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
Issue #14019
Kill mutation for `SarifLogger` `NonVoidMethodCallMutator on final String version = SarifLogger.class.getPackage().getImplementationVersion();`
**Reason for Mutation:**
On `readResource` method under `SarifLogger.java`, we are writing the `buffer` on `result` variable in some `n iterations of while loop` but by the mutation it makes the `initial assignment` of `length` variable as `0` and this will not affect the `result` variable so all test cases passed.
**Kill mutation:**
Makes the `initial assignment` of `length` variable as `0` by own. By this, all logic remains as usual, and it can't change because it will affect the `result` variable, and test cases will fail.
> Issue #14019: kill mutation of SarifLogger readResource Method

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
**Test.java File:** 
```
/**
* <tag_name attr_name="attr_value">Content</tag_name>
*/
// Method implementation
}
```
`java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g
`
**Command output:**
```
icon@LAPTOP-2D9VIFHD MINGW64 /v/Open-Source-Contributions/Check-Style-Project/attr_value AST
|   |   |--COMMENT_CONTENT -> *\r\n * <tag_name attr_name="attr_value">Content</tag_name>\r\n
|   |   | …
```
> Issue #14631: Update ATTR_VALUE of JavadocTokenTypes.java to new AST

- config/jsoref-spellchecker/whitelist.words
- src/site/resources/css/site.css
- src/site/resources/js/copy-clipboard.js
- src/site/site.xml
#16072 
#16300
- Dynamically injecting a copy-to-clipboard icon button into every <source> block.
- Automatically prepends a XML header for XML snippets wherever missing.
> Issue #16072: Copy to clipboard image button for all sources

- src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
Issue #16359 : Update RegexpHeaderCheckTest to use verifyWithInlineConfigParser
Updates use of verify method to verifyWithInlineConfigParser from RegexpHeaderCheckTest
> Issue #16359 : Update RegexpHeaderCheckTest to use verifyXXXX

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Command used : $ java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
```
/**
* <td></td>
*/
}
```
```
Sushanth Rai@LAPTOP-BNHH6IM9 MINGW64 /d/GSOC/td_tag AST
|   |   |--COMMENT_CONTENT -> *\r\n * <td></td>\r\n
|   |   |       |   `--TD -> TD
|   |   |       |       |--TD_TAG_START -> TD_TAG_START …
```
> Issue #14631 : Updated <td> HTML tag in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
```
/**
* <p>Paragraph Tag.</p>}
*/
}
```
```
1501s@Dell_G15 MINGW64 /D/Sambhav/opensource/checkstyle/checkstyle_debugging
|   |   |--COMMENT_CONTENT -> *\r\n * <p>Paragraph Tag.</p>}\r\n
|   |   |       |   `--PARAGRAPH -> PARAGRAPH …
```
> Issue #14631: Updated  P_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

- .github/workflows/remainder-bot.yml
- config/jsoref-spellchecker/whitelist.words
Fixes Issue: #15770 
https://github.com/actions/stale
we can handle PRs with different settings , or skip them at all: https://github.com/actions/stale?tab=readme-ov-file#days-before-close
This workflow implements an automated remainder using GitHub Actions.
Workflow Name: `feedback-reminder-bot`
Trigger: Runs automatically every day at midnight UTC using a cron schedule
Permissions: Has read access to repository contents and write access to issues
The workflow uses the official GitHub `actions/stale@v9` action to manage inactive issues. 
Functionality:  
Target issues labelled with `awaiting-response`
After 7 days of inactivity, add a friendly reminder message requesting feedback
If there is no response within another 7 days, close the issue with a no-response label
so it can close: …
> Issue 15770: Github Remainder Bot

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
**Command used**
**Test.java**
```
Prarthana@Prarthana MINGW64 ~/OneDrive/desktop/hr_tag
/**
* text before horizontal rule <hr> text after horizontal rule
*/
}
```
```
Prarthana@Prarthana MINGW64 ~/OneDrive/desktop/attr_value
|   |   |--COMMENT_CONTENT -> *\r\n * text before horizontal rule <hr> text after horizontal rule\r\n
|   |   | …
```
> Issue #14631: Updated HR_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
**Issue**: #14631 
**Command**: 
`java -jar checkstyle-10.21.4-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* <ol>
*   <li>banana</li>
* </ol>
*/
}
```
```
noman@ANIS MINGW64 /d/zaid/zaid/codes/checkstyle/LI_HTML_TAG_NAME AST
$ java -jar checkstyle-10.21.4-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--TEXT -> /**
|--NEWLINE -> \r\n
|--LEADING_ASTERISK ->  *
|--TEXT ->
|--HTML_ELEMENT -> HTML_ELEMENT
|   `--HTML_TAG -> HTML_TAG
|       |--HTML_ELEMENT_START -> HTML_ELEMENT_START
|       |   |--START -> <
|       |   |--HTML_TAG_NAME -> ol
|       |   `--END -> >
|       |--NEWLINE -> \r\n
|       |--LEADING_ASTERISK ->  *
|       |--TEXT ->
|       |--HTML_ELEMENT -> HTML_ELEMENT
|       |   `--LI -> LI
| …
```
> Issue #14631: Updated LI_HTML_TAG_NAME to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
```
/**
* @serialField counter Integer objects counter
*/
}
```
```
1501s@Dell_G15 MINGW64 /d/sambhav/opensource/checkstyle/checkstyle_debugging
|   |   |--COMMENT_CONTENT -> *\r\n * @serialField counter Integer objects counter\r\n …
```
> Issue #14631: Updated FIELD_TYPE in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
**Command Used :**
java -jar checkstyle-10.21.4-all.jar -J Test.java | sed -E 's/[[0-9]+:[0-9]+]//g'
```
Test.java
/**
* <p class="highlight">Sample text</p>
*/
}
```
Terminal Output:
```
|   |   |--COMMENT_CONTENT -> *\n * <p class="highlight">Sample text</p>\n  
|   |   |       |   `--PARAGRAPH -> PARAGRAPH 
|   |   |       |       |--P_TAG_START -> P_TAG_START 
|   |   |       |       |   |--START -> <  …
```
> Issue #14631: Updated Attribute to new AST value

- src/site/xdoc/checks/naming/methodname.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameRecordInInterfaceBody.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameEqualClassName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameEqualClassName2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameEqualClassName3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameOverriddenMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNamePrivateMethodsInInterfaces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNamePublicMethodsInInterfaces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameSimpleTwo.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/Example5.java
This PR addresses **issue** #15456
**Example preview of changes made:**
```
// 2 violations 3 lines below:
//        'Method Name 'InputMethodNameEqualClassName' must not equal the enclosing class name.'
//        'Name 'InputMethodNameEqualClassName' must match pattern.'
public int InputMethodNameEqualClassName() {
return 0;
}
```
> Issue #15456: Defined violation message for MethodName in InlineConfigParser.java

- config/checkstyle-non-main-files-checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleError.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/InputSarifLoggerSingleError.java
Issue #16361 
- created a method `verifyWithInlineConfigParserAndLogger`  in `AbstractModuleTestSupport` for loggers with one output stream. One test case in `SarifLoggerTest` is converted to the new approach as an example.
> Issue 16361: Update SarifLoggerTest.java to use verifyWithInlineConfigParserAndLogger

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptyIsFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptyIsFalseThree.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptyIsFalseTwo.java
this PR addresses issue #11163 
preview of changes made:
1.` MethodLength/InputMethodLengthCountEmptyIsFalse.java`  file was split into 3 files ensuring  _file length < 120_   for all inputs
2. test methods were introduced in `Sizes/InputMethodLengthCheckTest.java` to ensure the new files were thoroughly tested 
3. Removed suppressions for file length for `InputMethodLengthCountEmptyIsFalse.java`
> Issue #11163: Enforced file size on MethodName check inputs

- config/pitest-suppressions/pitest-ant-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
part of #14019
**Explaination :** 
Since no function was there that returns maxErrors variable directly, I thought of adding getter method for that. But Then I realised that there is no actual dependency on maxErrors field because it was never populated using setter function. It was just for testing purpose. Even in production code processFiles() func. It was useless to have the logic that I removed because maxErrors is always 0 ( default value ). Not sure whether removing the fields and logic is a good practise or not. 
cc @romani 
**Targeted Mutation:** 
https://github.com/checkstyle/checkstyle/blob/afba154a6a5be1ec41accd829170140332759950/config/pitest-suppressions/pitest-ant-suppressions.xml#L183-L190
Diff Regression config: https://gist.githubusercontent.com/Rohanraj123/b4b513e27c22e9 …
> Issue #14019: Remove suppression for pitest-ant profile

- src/site/xdoc/checks/naming/localfinalvariablename.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableName1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameTryResources.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/Example3.java
Issue: https://github.com/checkstyle/checkstyle/issues/15456
**com.puppycrawl.tools.checkstyle.checks.coding.LocalFinalVariableNameCheck**
**Some info** 
Needed to add suppressions to ignore line length violations in test inputs, as these lines contain message required for validation
> Issue #15456: Define violation message for LocalFinalVariableNameCheck

- config/pitest-suppressions/pitest-common-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerEncodedMessage.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/InputXMLLoggerEncodedMessage.java
Issue #14019: Kill mutation for XMLLogger ArgumentPropagationMutator on + encode(event.getMessage())
Reason for Mutation: In the writeFileError method of XMLLogger.java, we normally encode the error message to escape special XML characters (like <, >, and &). However, the mutation replaces the call to encode(event.getMessage()) with event.getMessage(), so special characters aren’t escaped. As a result, the XML output may be malformed, yet all test cases pass.
Kill mutation: Simulate the mutation by directly using event.getMessage() in place of encode(event.getMessage()). This change exposes the missing encoding of special characters, causing tests that expect correctly escaped XML to fail
@romani waiting for your review
> Issue #14019: kill mutation of encode(event.getMessage()) in XMLLogger

- .github/workflows/check-performance-regression.yml
- config/jsoref-spellchecker/whitelist.words
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
> This is the fastest prediction mode, and provides correct results for many grammars
```Java
public enum PredictionMode {
/**
* The SLL(*) prediction mode. This prediction mode ignores the current
* parser context when making predictions. This is the fastest prediction
* mode, and provides correct results for many grammars. This prediction
* mode is more powerful than the prediction mode provided by ANTLR 3, but
* may result in syntax errors for grammar and input combinations which are
* not SLL.
*
* <p>
* When using this prediction mode, the parser will either return a correct
* parse tree (i.e. the same parse tree that would be returned with the
* {@link #LL} prediction mode), or it will report a syntax error. If a
* syntax error is encountered when using the {@link #SLL} prediction …
```
> Pull #16628: Try SLL prediction mode for fast javadoc parsing

- .ci/validation.sh
- config/jsoref-spellchecker/whitelist.words
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputJavaDocTagContinuationIndentation.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationCheckHtml.java
Fixes Issue #16385 and https://github.com/checkstyle/checkstyle/issues/16385
resolved JavadocTagContinuationIndentation Ignore indentation check when HTML tag break line
attention:
Block tags: Represented by JAVADOC_TAG
Inline tags: Represented by JAVADOC_INLINE_TAG
> Issue #16385: resolved JavadocTagContinuationIndentation bug

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
Related Issue #11166
Remove `getFileContents()` Usage in `EmptyLineSeparatorCheck.java`
Diff Regression config: https://gist.githubusercontent.com/roulpriya/c794c73b3ae7ddfcb29cc8cf1ac1a5e2/raw/72e1a308d64df0bb072552d2b6fccc677886c832/check.xml
> Remove Usage of getFileContents()

- config/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
**Test.java**
```
/**
* <link rel="stylesheet" href="Style.css">
*/
}
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/LINK_HTML_TAG_NAME
|   |   |--COMMENT_CONTENT -> *\r\n * <link rel="stylesheet" href="Style.css">\r\n …
```
> Issue #14631: Updated LINK_HTML_TAG_NAME to AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
issue #14631 
Command Used
java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
Test.java
```
/**
* @param T The bar.
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\r\n * @param T The bar.\r\n
|   |   |       |   |--PARAM_LITERAL -> @param
|   |   |       |   |--PARAMETER_NAME -> T …
```
> Issue #14631: Updated PARAM_TYPE in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
issue #14631 
Command Used
java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
Test.java
```
/**
* @serial include
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\r\n * @serial include\r\n
|   |   |       |   |--SERIAL_LITERAL -> @serial
|   |   |       |   |--LITERAL_INCLUDE -> include
|   |   |       |   |--NEWLINE -> \r\n
|   |   | …
```
> Issue #14631: Updated LITERAL_INCLUDE in JavadocTokenTypes.java to new AST format

- .github/workflows/google-java-format.yml
https://github.com/google/google-java-format/releases/tag/v1.26.0
> infra: update google-java-format.yml to 1.26.0 formatter

- src/site/xdoc/sun_style.xml
> Issue #16666: Updated Broken Link - Javadoc OpenJDK 8 Report in website, 404 Error

- config/checker-framework-suppressions/checker-index-suppressions.xml
- config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTag.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithLinkAndMethodTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithLinkAndMethodTagSuperClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithLinkTag.java
#14697 
The issue was  `@link` tag being considered valid. The root cause lies in the **`BLOCK_TAG_PATTERN`**, which retrieves all regex expressions containing `@` within Javadoc comments. This pattern incorrectly identifies `@link` as an valid reference for imports.
https://github.com/checkstyle/checkstyle/blob/1fa0377d6892f12e544e7c56acec4cf38c23d15e/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtil.java#L41
To resolve this, we filter patterns with `@link` since they are considered invalid references for imports.
---
Another issue arises with `{@link Set::add}`, which is an invalid link. correct one `{@link ClassName#methodName}`
The probelm was in extraction of  INLINE_TAG_PATTERN regex  
https://github.com/checkstyle/checkstyle/blob/1fa0377d6892f12e544e7c5 …
> Issue #14697: Resolved False negative in UnusedImportCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
issue #14631 
Command Used
```java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"```
Test.java
```
/**
* text before break < br > text after break
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\r\n * text before break < br > text after break\r\n
|   |   |       |--TEXT ->  text before break < br > text after break
|   |   |       `--EOF -> <EOF>
|   | …
```
> Issue #14631: Updated BASEFONT_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Command Used
```
java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
```
Test.java
```
/**
* <meta charset="UTF-8">
*/
}
```
```
$ java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * <meta charset="UTF-8">\r\n
|   |   |       |       `--META_TAG -> META_TAG
|   |   |       |           |--START -> < …
```
> Issue #14631: Updated META_TAG to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
**Command**
**Test.java**
```
/**
* <dd></dd>
*/
}
```
```
--HTML_ELEMENT -> HTML_ELEMENT
`--DD -> DD
|--DD_TAG_START -> DD_TAG_START
|   |--START -> <
|   |--DD_HTML_TAG_NAME -> dd
|   `--END -> >
|--TEXT -> "Description content"
`--DD_TAG_END -> DD_TAG_END
|--START -> <
|--SLASH -> /
|--DD_HTML_TAG_NAME -> dd
`--END -> >
```
> Issue #14631: Updated DD  in JavadocTokenTypes.java to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocMethodCheck.xml
- src/site/xdoc/checks/javadoc/javadocmethod.xml
- src/site/xdoc/checks/javadoc/javadocmethod.xml.template
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodAllowInlineReturn.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodDoNotAllowInlineReturn.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/Example8.java
Aims to close #9745 
Added new `allowInlineReturn` property in JavadocMethodCheck to control whether to allow inline return tags in javadoc.
Default. value is `false` to not break compatibility
> Issue #9745: Added JavadocMethod inline return tag support

- src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
Fixed Issue #16155 
Removed the `File` API usage in favour of nio `Path` API.
> Issue #16155: use nio api in XpathFileGeneratorAuditListener

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Command Used
```
java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
```
Test.java
```
/**
* text above line<hr> test after line
*/
}
```
```
$ java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * text above line<hr> test after line\r\n
|   |   |       |--TEXT ->  text above line
|   |   |       |       `--HR_TAG -> HR_TAG
| …
```
> Issue #14631: Updated HR_TAG to new AST format

- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerErrorZeroColumn.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/InputXMLLoggerErrorOnZeroColumn.java
Fixes Issue https://github.com/checkstyle/checkstyle/issues/16360
Change the `XMLLoggerTest.testAddErrorOnZeroColumns` method to use `verifyWithInlineConfigParserAndXmlLogger`.
> Issue #16360: Migrate XMLLoggerTest.testAddErrorOnZeroColumns to use inlineConfigParser

- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerAddError.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/InputXMLLoggerAddError.java
Fixes Issue #16360
Change `testAddError` method to use `verifyWithInlineConfigParserAndXmlLogger`.
> Issue 16360: Migrate XMLLoggerTest to use inlineConfigParser

- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java
Issue: #14019
**Killed Mutations**
```
<sourceFile>DetailNodeTreeStringPrinter.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter</mutatedClass>
<mutatedMethod>parseFile</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
<description>removed call to java/nio/charset/Charset::name</description>
<lineContent>System.getProperty(&quot;file.encoding&quot;, StandardCharsets.UTF_8.name()));</lineContent>
</mutation>
<sourceFile>DetailNodeTreeStringPrinter.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter</mutatedClass>
<mutatedMethod>parseFile</mutatedMethod> …
```
> Issue #14019: Cover pitest survivals with tests in DetailNodeTreeStringPrinter

- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java
Issue: #14019
**Mutations killed**
```
<sourceFile>SuppressionsStringPrinter.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.SuppressionsStringPrinter</mutatedClass>
<mutatedMethod>printSuppressions</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
<description>removed call to java/nio/charset/Charset::name</description>
<lineContent>System.getProperty(&quot;file.encoding&quot;, StandardCharsets.UTF_8.name()));</lineContent>
</mutation>
<sourceFile>SuppressionsStringPrinter.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.SuppressionsStringPrinter</mutatedClass>
<mutatedMethod>printSuppressions</mutatedMethod> …
```
> Issue #14019: Cover pitest survivals in SuppressionStringPrinter

- config/pitest-suppressions/pitest-ant-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue #14019 
Build stats:
test runs after changes
```mvn test```
```mvn clean verify```
> Issue #14019: Kill Mutation For CheckstyleAntTask

- config/pitest-suppressions/pitest-ant-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Fixes Issue #14019 
Kills mutation: 
- ArgumentPropagationMutator on `throw new BuildException(String.format(Locale.ROOT, &quot;Unable to create listeners:`
- ArgumentPropagationMutator on `throw new BuildException(String.format(Locale.ROOT, &quot; Unable to create Root Module`
> Issue #14019: Kill argument propogation mutation in CheckstyleAntTask

- config/error-prone-suppressions/compile-phase-suppressions.xml
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImplTest.java
Issue: #13999 
Resolved Pitest Suppression in [JavadocNodeImpl.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java)
**Mutation** - `toString : removed call to java/util/Objects::hashCode → SURVIVED`
- Objects.hashCode(children) returns the array's identity hash code, not a content-based hash. In assertions, this leads to incorrect evaluations since the actual contents of the array are ignored.
- Static analysis tools flag this under the ArrayHashCode bug pattern when used in logical contexts like assert. The same call in toString() is not flagged, as it's treated as non-functional and purely informational.
- Despite this, using Objects.hashCode() limits functionality even in toString(), as it doesn't …
> Issue #13999: Resolved Pitest Suppression in JavadocNodeImpl

- config/jsoref-spellchecker/whitelist.words
- pom.xml
- src/site/xdoc/sponsoring.xml
Fixes : #16759 
Closes: #16767 
Build status:
> Issue #16759: Removed Broken Flattr Link and Image on Sponsoring Page

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameMemberExtended.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameSimple1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameSimple2.java
Issue #15456
```
/**
* This is a test class for demonstrating Checkstyle violations.
*/
public static final int badConstant = 2;
private static final int BAD__NAME = 3;
String data = "zxzc";
public int mPublic = 0;
int mProtected = 0;
int mPackage = 0;
int mPrivate = 0;
public int _public = 0;
int _protected = 0;
int _package = 0;
int _private = 0;
}
```
```
<module name="ConstantName">
<property name="format" value="^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"/>
</module>
<module name="MemberName">
<property name="format" value="^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"/>
</module>
</module> …
```
> Issue #15456: Defined violation message for ConstantNameCheck in InlineConfigParser.java

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue: #14631
**Command**
**Test.java**
```
/**
* <dt></dt>
*/
}
```
```
--HTML_ELEMENT -> HTML_ELEMENT
`--DT -> DT
|--DT_TAG_START -> DT_TAG_START
|   |--START -> <
|   |--DT_HTML_TAG_NAME -> dt
|   `--END -> >
|--TEXT -> "Description term"
`--DT_TAG_END -> DT_TAG_END
|--START -> <
|--SLASH -> /
|--DT_HTML_TAG_NAME -> dt
`--END -> >
```
> Issue #14631: Updated DT in JavadocTokenTypes.java to new AST format

- config/pitest-suppressions/pitest-ant-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
issue #14019 
removed call to com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask::getLocation
```xml
<sourceFile>CheckstyleAntTask.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask</mutatedClass>
<mutatedMethod>processFiles</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
<description>removed call to com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask::getLocation</description>
<lineContent>throw new BuildException(failureMsg, getLocation());</lineContent>
</mutation>
```
> Issue #14019: Kill Mutation For CheckstyleAntTask: processFiles()

- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
Issue: #11166
**Usage of getFileContents() removed for lline:**
` if (fileContents.lineIsBlank(line - 1))`
**Suppression removed:**
` <suppress id="noUsageOfGetFileContentsMethod" files="EmptyLineSeparatorCheck.java"/>`
**Updated Block**
```
private boolean hasEmptyLine(int startLine, int endLine) {
// Initial value is false - blank line not found
boolean result = false;
for (int line = startLine; line <= endLine; line++) {
// Check, if the line is blank. Lines are numbered from 0, so subtract 1
if (CommonUtil.isBlank(getLine(line - 1))) {
result = true;
break;
}
}
return result;
}
```
Diff Regression config: 
https://github.com/Atharv3221/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
Diff Regression patch config: …
> Issue #11166: Removed usage of getFileContents() in EmptyLineSeparatorCheck

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/packagename/InputPackageNameSimple1.java
Issue #15456
```
package com.puppycrawl.tools.checkstyle.checks.naming.packagename;
/**
* This is a test class for demonstrating Checkstyle violations.
*/
}
```
```
<module name="PackageName">
<property name="format" value="[A-Z]+"/>
</module>
</module>
</module>
```
```
$ java -jar checkstyle-10.23.0-all.jar -c config_check.xml com/puppycrawl/tools/checkstyle/checks/naming/packagename/Test.java
[ERROR] F:\GitHub\headhtmltagname\com\puppycrawl\tools\checkstyle\checks\naming\packagename\Test.java:1:9: Name …
```
> Issue #15456: Defined violation message for PackageNameCheck in InlineConfigParser.java

- config/checkstyle-resources-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidMethodIndent1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidMethodIndent2.java
Issue #11163
Enforce file size for `InputIndentationInvalidMethodIndent.java` splits into 2 class i.e `InputIndentationInvalidMethodIndent1.java` and `InputIndentationInvalidMethodIndent2.java`, both file size are below 120 lines of code.
> Issue #11163: Enforce file size for IndentationInvalidMethodIndent

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Command Used
```
java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
```
Test.java
```
/**
* <embed src="URL" type="MIME_type">
*/
}
```
```
$ java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * <embed src="URL" type="MIME_type">\r\n
|   |   |       |       `--EMBED_TAG -> EMBED_TAG
|   |   | …
```
> Issue #14631: Updated EMBED_TAG to new AST format

- config/checkstyle-examples-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/site/xdoc/checks/annotation/suppresswarningsholder.xml
- src/site/xdoc/checks/annotation/suppresswarningsholder.xml.template
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias7.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsHolderExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarningsholder/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarningsholder/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarningsholder/Example4.java
Issue #11641 
Allow SuppressWarningsHolder to use simple name of checks in aliasList
simple name of checks like CheckNameCheck and CheckName will now also allow in aliasList.
Added the test cases:
- with the suppressed check NOT having "Check' appended to the end of the name, ex: https://github.com/checkstyle/checkstyle/issues/11641#issuecomment-1127006448
- a case with two modules of the same check, with different configs, and show that we filter out unique violations for each
> Issue #11641: allow usage of simple name of checks in aliasList by SuppressWarningsHolder

- src/site/xdoc/writinglisteners.xml.vm
Fixes #1241 
Now https://checkstyle.org/writinglisteners.html
As mentioned in issue description to add Content section in two files but Content section was already there in config.xml. So we just need to add it to writinglisteners.xml.vm.
Here you can see content section of config.xml
Build status ```mvn clean verify```
> Issue #1241: Add table of contents macro to writinglisteners.xml.vm

- config/jsoref-spellchecker/whitelist.words
- pom.xml
- src/site/xdoc/sponsoring.xml
Fixes #16753  
Closes #16819 
I have removed freedomsponsors completely as i don't see it's replacement - till replacement we can safely remove it from site once we get it we can update it again.
> minor #16753: remove references to freedomsponsors from pom.xml, sponsoring.xml, and whitelist.words

- .ci/validation.sh
- config/jsoref-spellchecker/whitelist.words
This PR reverts the fork usage on no-error-pmd cli validations.
> minor: Revert fork usage in ci validations on no-error-pmd

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/VariableDeclarationUsageDistanceCheck.xml
- src/site/xdoc/checks/coding/variabledeclarationusagedistance.xml
- src/site/xdoc/checks/coding/variabledeclarationusagedistance.xml.template
related fix #16680
Pull #16811: fix whitespace typo in `Note : ` -> `Note: `
> Pull #16811: fix whitespace typo in `Note : ` -> `Note: `

- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Pull #16559: fix `OSX build` when `.DS_Store` is present
ref: https://github.com/checkstyle/checkstyle/issues/16801
https://en.m.wikipedia.org/wiki/.DS_Store#:~:text=DS_Store%20is%20a%20file%20that,positions%2C%20and%20other%20visual%20information.
this a file created while walking in file manager.
> Pull #16559: fix `OSX build` when `.DS_Store` is present

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
**Test.java**
```
/**
* <br> line breaks<br/>
*/
}
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/BR_TAG (hide)
|   |   |--COMMENT_CONTENT -> *\r\n * <br> line breaks<br/>\r\n …
```
> Issue #14631: Updated BR_TAG to new AST format

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
Command Used
```
java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
```
Test.java
```
/**
* <isindex prompt="search">
*/
}
```
```
$ java -jar checkstyle-10.22.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * <isindex prompt="search">\r\n
|   |   |       |       `--ISINDEX_TAG -> ISINDEX_TAG …
```
> Issue #14631: Updated ISINDEX_TAG to new AST format

- config/spotbugs-exclude.xml
Issue: #16882 
**Suppression removed**
```
<Match>
<Class name="com.puppycrawl.tools.checkstyle.checks.metrics.NPathComplexityCheck"/>
<Bug pattern="AT_STALE_THREAD_WRITE_OF_PRIMITIVE"/>
</Match>
```
> Issue #16882: Removed suppression in spotbugs-exclude

- config/pitest-suppressions/pitest-ant-suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue: #14019 
**Suppression removed**
```
<sourceFile>CheckstyleAntTask.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask</mutatedClass>
<mutatedMethod>&lt;init&gt;</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.MemberVariableMutator</mutator>
<description>Removed assignment to member variable maxWarnings</description>
<lineContent>private int maxWarnings = Integer.MAX_VALUE;</lineContent>
</mutation>
```
> Issue #14019: Covered pitest survivals with tests for CheckstyleAntTask

- config/spotbugs-exclude.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheck.java
Issue: #16882
**Suppression removed**
```
<Match>
<Class name="com.puppycrawl.tools.checkstyle.checks.sizes.RecordComponentNumberCheck"/>
<Bug pattern="AT_STALE_THREAD_WRITE_OF_PRIMITIVE"/>
</Match>
```
**Method updated**
```
private static int countComponents(DetailAST recordComponents) {
return recordComponents.getChildCount(TokenTypes.RECORD_COMPONENT_DEF);
}
```
> Issue #16882: Removed usage of AtomicInteger from RecordComponentNumberCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
Issue: #16882 
**Removed usage of AtomicInteger for UniquePropertiesCheck**
```
PS C:\Users\athar\OneDrive\Desktop\checkstyle> mvn clean verify
.
.
.
[INFO] Total time:  17:27 min
[INFO] Finished at: 2025-04-20T01:33:42+05:30
```
> Issue #16882: Removed usage of AtomicInteger for UniquePropertiesCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelCounter.java
Issue: #16882 
**Removed usage of AtomicInteger for SeverityLevelCounter**
```
PS C:\Users\athar\OneDrive\Desktop\checkstyle> mvn clean verify
.
.
.
INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:51 min
[INFO] Finished at: 2025-04-20T00:56:14+05:30
```
> Issue #16882: Removed usage of AtomicInteger for SeverityLevelCounter

- src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
Issue: #16882
**Removed usage of ConcurrentLinkedQueue**
```
final Queue<DetailAstImpl> descendantList = binOpList.parallelStream()
.map(this::getInnerBopAst)
.collect(Collectors.toCollection(ArrayDeque::new));
```
**Used ArrayDeque instead of ConcurrentLinkedQueue**
```
PS C:\Users\athar\OneDrive\Desktop\checkstyle> mvn clean verify                                                                             
.
.
.
[INFO] Total time:  18:31 min
[INFO] Finished at: 2025-04-20T06:21:06+05:30
```
> Issue #16882: Removed usage of ConcurrentLinkedQueue in JavaAstVisitor

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java
Issue: #16882 
**Removed usage of ConcurrentHashMap**
```
/** The directories checked. */
private final Set<File> directoriesChecked = new HashSet<>();
```
**Used HashSet instead of ConcurrentHashMap**
```
PS C:\Users\athar\OneDrive\Desktop\checkstyle> mvn clean verify
.
.
.
[INFO] Total time:  20:45 min
[INFO] Finished at: 2025-04-20T08:27:58+05:30
```
> Issue #16882: Removed usage of ConcurrentHashMap in JavadocPackageCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
Issue: #16882
**Removed usage of ConcurrentHashMap**
`final Set<ResourceBundle> resourceBundles = new HashSet<>();`
**Using HashSet instead of  ConcurrentHashMap.newKeySet()**
```
PS C:\Users\athar\OneDrive\Desktop\checkstyle> mvn clean verify
.
.
.
[INFO] Total time:  16:32 min
[INFO] Finished at: 2025-04-20T07:51:26+05:30
```
> Issue #16882: Removed usage of ConcurrentHashMap in TranslationCheck

- src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
Issue: #16882 
**Removed usage of ConcurrentHashMap**
```
/** Holds all messages for the given file. */
private final Map<String, FileMessages> fileMessages =
new HashMap<>();
```
**Used HashMap instead of ConcurrentHashMap**
```
PS C:\Users\athar\OneDrive\Desktop\checkstyle> mvn clean verify                                                                      
.
.
.
[INFO] Total time:  19:09 min
[INFO] Finished at: 2025-04-20T07:16:13+05:30
```
> Issue #16882: Removed usage of ConcurrentHashMap in XMLLogger

- src/site/xdoc/config.xml
- src/site/xdoc/config_system_properties.xml
#14879 
Anchors are generated when we have an id attribute , therefore for such files [https://checkstyle.org/config.html#](https://checkstyle.org/config.html#TreeWalker_Examples) id attribute is added so that anchor.js generates linking href.
Output:
Now We can hover and create a link to it!
> Issue #14879 : Configuration website does not allow linking to Examples

- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedIncorrectJavadocParagraph.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCheck1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphNested.java
Fixes: https://github.com/checkstyle/checkstyle/issues/16630
Fixed false-positive and some already existing tests.
The check was built on the assumption that a nested `<p>` tag means it is nested inside another `<p>` tag.
Now, no violation will be produced if a `<p>` tag is nested inside any other tag.
This PR reintroduces the changes from the original PR (https://github.com/checkstyle/checkstyle/pull/16687), which was closed due to a required refork of the repository.
> Issue #16630: fp when <p> is nested

- src/site/xdoc/writingchecks.xml
Issue #13538 
Extends the documentation on no lombok support inside [Limitations](https://checkstyle.org/writingchecks.html#Limitations).
Added separate sub-section for it.
> Issue #13538: Added documenation on no lombok support

- config/import-control.xml
Issue #16903: disallow import of `java.util.concurrent.atomic.AtomicInteger` yet, it is still used in `api\SeverityLevelCounter.java` and `checks\UniquePropertiesCheck.java`
> Issue #16903: disallow import of `java.util.concurrent.atomic.AtomicInteger`

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
- config/pitest-suppressions/pitest-ant-suppressions.xml
- config/pitest-suppressions/pitest-coding-2-suppressions.xml
- config/pitest-suppressions/pitest-filters-suppressions.xml
- config/pitest-suppressions/pitest-header-suppressions.xml
- config/pitest-suppressions/pitest-imports-suppressions.xml
- config/pitest-suppressions/pitest-javadoc-suppressions.xml
- config/pitest-suppressions/pitest-packagenamesloader-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java
Fixes #16937 
Revert PR - Issue #14019
Reference #16938 
Closes #16938 , #16945 
Build status 
```
mvn -e --no-transfer-progress -P"pitest-tree-walker" clean test-compile org.pitest:pitest-maven:mutationCoverage
```
Report
> Issue #14019: update SuppressFilterElement constructor and remove unused methods

- src/site/xdoc/filters/suppressioncommentfilter.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example7.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/Example8.java
Update `SuppressionCommentFilterExamplesTest` to use `verifyFilterWithInlineConfigParser`
Issue: https://github.com/checkstyle/checkstyle/issues/16738
> Issue #16738: Update SuppressionCommentFilterExamplesTest to use verifyFilterWithInlineConfigParser

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
Fix #16880 
Updated `testMethodPrecedeByAnnotationsWithParameterOnSeparateLine()` to use `verifyWarns()`.
> Issue #16880: Update IndentationCheckTest.testMethodPrecedeByAnnotationsWithParameterOnSeparateLine to use verifyWarns

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnotationIncorrect.java
Fix #16880
Updated `testAnnotationIncorrect()` to use `verifyWarns()`.
> Issue #16880: Update IndentationCheckTest.testAnnotationIncorrect to use verifyWarns

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSeparatedStatementWithSpaces.java
Fix #16880 
Updated `testSeparatedLineWithJustSpaces()` to use `verifyWarns()`.
> Issue #16880: Update IndentationCheckTest.testSeparatedLineWithJustSpaces to use verifyWarns

- .circleci/config.yml
- config/jsoref-spellchecker/whitelist.words
- config/spotbugs-exclude.xml
Earlier Disabled : https://github.com/checkstyle/checkstyle/pull/14863
Due to SpotBug Issue Mentioned in :https://github.com/spotbugs/spotbugs-maven-plugin/issues/806
Local Results on : mvn clean test-compile spotbugs
**For Example Lets Take This High-Confidence Error Flagges by SpotBug :**
**This is the part of the code where Error is Flagged :**  
Ans:The error RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE occurs because Spotbugs detects a redundant null check on a variable (stream in your code) that is guaranteed to be non-null due to prior dereferencing. In this case, this is likely a false positive caused by Spotbugs analyzing the bytecode generated for the try-with-resources block.
-Files.find(...) returns a Stream<Path>, which will never be null (it throws IOException on failure). …
> infra: Enabling Spot-Bug in CircleCI

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
Fix #16880
Updated `testTextBlockLiteral()` to use `verifyWarns()` method.
> Issue #16880: Update IndentationCheckTest.testTextBlockLiteral to use verifyWarns

- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
Issue: #16155 
Removed usage of File.io in CheckUtil, CheckUtilTest, MissingJavadocMethodCheckTest
```
public static boolean isPackageInfo(String filePath) {
final Path path = Path.of(filePath);
final Path filename = path.getFileName();
return filename != null && "package-info.java".equals(filename.toString());
}
```
Explanation:
As .toString() can cause NullPointerException, so `filename != null` was needed, as no existing test tested for `filename != null`
added new test to trigger if `filename == null` killing the possible mutations.
```
@Test
public void testPackageInfo() {
final boolean result = CheckUtil.isPackageInfo("/");
assertWithMessage("Expected isPackageInfo() to return false for ('/')")
.that(result)
.isFalse();
}
```
> Issue #16155: Used nio api in CheckUtil

- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerIgnored.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/InputXMLLoggerIgnored.java
Part of #16360 
Replace the `verifyXml()` call with `verifyWithInlineConfigParserAndXmlLogger()` in the `XMLLoggerTest.testAddIgnored`.
> Issue #16360: Migrate XMLLoggerTest.testAddIgnored to use inlineConfigParser

- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerErrorModuleId.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/InputXMLLoggerErrorModuleId.java
Part of #16360 
Replace the `verifyXml()` call with `verifyWithInlineConfigParserAndXmlLogger()` in the `XMLLoggerTest.testErrorModuleId` method.
> Issue #16360: Migrate XMLLoggerTest.testErrorModuleId to use inlineConfigParser

- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XdocUtil.java
References issue #13132 
The build was locally successful and no anomalies were detected after the changes were made. 
lets see with CI/CD
---
the issue was based on the comment's 
👉 https://github.com/checkstyle/checkstyle/pull/13103#discussion_r1213522514
👉 https://github.com/checkstyle/checkstyle/issues/13097#issuecomment-1566508439
from my perspective comments' indicates that earlier  a task was carried out to split  xdoc modules into separate pages , and the new files were decided to have this `xdoc/checks/<category>/<check> - xdoc/checks/naming/abstractclassname.xml ` structure , and dropping the earlier where `config_` prefix was used .
and all the conditions where we checked for that prefix were not needed and hence needed to be removed.
@Zopsss review requested
> Issue #13132: Removed config_ prefix condition

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidArrayInitIndentWithoutTrailingComments.java
Issue: #16880 
All tests in IndentationCheckTest.java updated to use verifyWarns() in place of verify()
additionally added comment pattern-> "`//below indent:4 exp:8 warn`"
**Reason**
1) for `'InputIndentationTextBlock.java'` which use `"""`, adding indentation comment results in the following error->
> InputIndentationTextBlock.java:89: error: illegal text block open delimiter sequence, missing line terminator
>         if ("""                                               //indent:8 exp:8
>                                                               ^
This occurs because, according to the Java Language Specification (JLS §3.10.6), the opening delimiter of a text block (""") must be immediately followed by a line terminator — that is, a newline character.
2) for …
> Issue #16880 IndentationCheckTest updated to use verifyWarns

- .ci/validation.sh
simple bump of version does not work https://github.com/checkstyle/checkstyle/pull/16996
we will do it sepate activity https://github.com/checkstyle/checkstyle/issues/17001
for now we need to unblock all PRs
> infra: use last commit of pgjdbc before they migrated to jdk21

- src/site/xdoc/beginning_development.xml
- src/site/xdoc/cmdline.xml.vm
- src/site/xdoc/report_issue.xml
- src/site/xdoc/writingchecks.xml
- src/site/xdoc/writingjavadocchecks.xml.vm
- src/site/xdoc/writinglisteners.xml.vm
> Issue #16790: Incorrect language class assigned to code blocks in documentation (e.g., logs getting language-xml, Java code getting language-xml) 

- src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleErrorColumn1.sarif
- src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/InputSarifLoggerSingleErrorColumn1.java
Part of #16361 
updated `testAddErrorAtColumn1()` method to use `verifyWithInlineConfigParserAndLogger()`.
> Issue #16361: Update SarifLoggerTest.testAddErrorAtColumn1 to use verifyWithInlineConfigParserAndLogger

- config/jsoref-spellchecker/whitelist.words
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSingleSwitchStatementWithoutCurly.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSingleSwitchStatementWithoutCurlyCorrect.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchWrappingIndentation.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchWrappingIndentationCorrect.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchRuleHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSingleSwitchStatementsWithoutCurly.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationPatternMatchingForSwitch.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchExpressionWrappingIndentation.java
fixes: #15098 , #16762
This PR reintroduces the changes from the original PR ([#16647](https://github.com/checkstyle/checkstyle/pull/16647)), which was closed due to a required refork of the repository.
New module config: https://gist.githubusercontent.com/mohitsatr/937e10572dd412961b61c77577619dff/raw/7a47240f8793e7335adbd81c2806b375f0394815/google_checks_indentation.xml
---Diff-- Regression config: https://gist.githubusercontent.com/mohitsatr/937e10572dd412961b61c77577619dff/raw/7a47240f8793e7335adbd81c2806b375f0394815/google_checks_indentation.xml
Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/9ba8e4fb324e1daf589874c6992f2aa87b03079a/list-of-projects.properties
> Issue #15098: Indentation of switch block when no braces is now validated

- .github/workflows/google-java-format.yml
https://github.com/google/google-java-format/releases/tag/v1.27.0
> infra: Update google-java-format.yml with 1.27.0 formatter

- config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
Issue #8807
`SuppressWithPlainTextCommentFilter` was slow on files with multiple errors
Reuse the `suppressions` for the file and use it again if the file name is the same as the last file name we used.
> Issue #8807: reuse suppressions on SuppressWithPlainTextCommentFilter

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
**Test.java**
```
/**
* <frame src="frame_a.html"> 
*/
}
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/FRAME_HTML_TAG_NAME (master)
|   |   |--COMMENT_CONTENT -> *\r\n * <frame src="frame_a.html"> - Test for FRAME_HTML_TAG_NAME\r\n …
```
> Issue #14631: Update Javadoc for FRAME_HTML_TAG_NAME with AST example

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
` java -jar checkstyle-10.13.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* Example using {@link String#length()} to test LINK_TAG.
*/
public class Test { }
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/LINK_TAG (master)
$ java -jar checkstyle-10.13.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * Example using {@link String#length()} to test LINK_TAG.\r\n
|   |   |       |--TEXT ->  Example using
|   |   |       |--JAVADOC_INLINE_TAG -> …
```
> Issue #14631: Add example and AST for LINK_TAG in JavadocTokenTypes.java

- .ci/checkchmod.sh
- .ci/generate-website.sh
- .gitignore
- .mvn/wrapper/maven-wrapper.properties
- appveyor.yml
- config/ant-phase-verify.xml
- config/jsoref-spellchecker/whitelist.words
- mvnw
- mvnw.cmd
Issue #16850 
Closes #16747 
Reference #16851
Phase 1:
This PR contains all files related to maven wrapper setup and use case.
Phase 2.
Updated ```.ci/generate-website.sh``` to use maven wrapper rather maven.
Commands Used:
All goes Build Successful
In Git Bash:
1.  `./mvnw validate`\
2.  `./mvnw compile`\
3. `./mvnw test`
4.  `./mvnw clean verify -U`
5.  `./mvnw dependency:analyze`
6.  `./mvnw clean verify`
in CMD:
All goes Build Successful
`mvnw.cmd validate`
`mvnw.cmd compile`
`mvnw.cmd test`
`mvnw.cmd clean verify -U`
`mvnw.cmd dependency:analyze`
`mvnw.cmd clean verify`
And 
`mvnw validate`
`mvnw compile`
`mvnw test`
`mvnw clean verify -U`
`mvnw dependency:analyze`
`mvnw clean verify`
> Issue #16850: Add Maven Wrapper support with configuration files and Updated .ci/generate-website.sh  to use maven wrapper.

- src/site/xdoc/checks/coding/matchxpath.xml
- src/site/xdoc/checks/coding/matchxpath.xml.template
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/Example5.java
Issue: #17059
```
<module name="MatchXpath">
<property name="query"
value="//CLASS_DEF[count(./OBJBLOCK/CTOR_DEF) > 1]"/>
<message key="matchxpath.match"
value="Classes with more than 1 constructor are not allowed"/>
</module>
</module>
</module>
```
```
public class Example5 {
public Example5() { }
class Inner { // violation
public Inner(int a) { }
public Inner() { }
}
}
```
```
C:\Users\athar\OneDrive\Desktop\test2>java -jar checkstyle-10.23.1-all.jar -c config.xml Example5.java
[ERROR] C:\Users\athar\OneDrive\Desktop\test2\Example5.java:3:5: Classes …
```
> Issue #17059: Add example to MatchXpath for Constructor Count

- src/site/xdoc/beginning_development.xml
- src/site/xdoc/config_system_properties.xml
- src/site/xdoc/contributing.xml
minor words fixed to capitals across website.
> minor: capitalize section titles for consistency

- config/pmd.xml
Pull #16962: include PMD `GuardLogStatement`
- Obsolet as bug causing code pattern is gone.
- Could use live mode to increase coverage.
- #16961
> Pull #16962: include PMD `GuardLogStatement`

- config/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
` java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* Example for empty tag.
*
* <justsometag />
*/
public class Test { }
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/EMPTY_TAG (master)
|   |   |--COMMENT_CONTENT -> *\r\n * Example for empty tag.\r\n *\r\n * <justsometag />\r\n
|   |   |       |--TEXT ->  Example for empty tag.
|   |   | …
```
> Issue #14631: Add example and AST tree for EMPTY_TAG in JavadocTokenTypes.java

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersReceiver.java
fixes #16378 
updated InlineConfigParser.java to validate that all properties are specified in Input file. if all properties are default, all properties should be mentioned in Input file and all has prefix (default).
> Issue #16378: Validate that all Inputs mentioned all default properties

- .github/GSOC.md
Based on https://github.com/checkstyle/checkstyle/pull/16625#issuecomment-2868000748
This PR updates the GSoC participant guide (`.github/GSOC.md`) with a new tip encouraging contributors to understand the broader context of software development. It includes a link to an article on developer sentiment in code reviews to help new contributors appreciate the human aspect of collaboration.
* Added a new tip to the GSoC participant guide.
* Linked to an article on developer sentiment in code reviews as a suggested resource.
* Simplified the tip’s wording for clarity and approachability.
[Video showing how the link works](https://github.com/user-attachments/assets/6a3dd5ff-e324-4287-8d48-3bae564e00b7)
> Add GSoC guide tip on learning beyond code, link article on coding review

- config/ant-phase-verify-sevntu.xml
- config/ant-phase-verify.xml
this the only one avoiding the common pattern:
> Pull #17110: fix log typo

- config/checkstyle-resources-suppressions.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorCompactNoPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorClassPackageSeparation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorOneLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithJavadoc2.java
Issue: #16564  
here is AST for the input:
```
COMPILATION_UNIT -> COMPILATION_UNIT [13:0]
|--BLOCK_COMMENT_BEGIN -> /* [1:0]
|   |--COMMENT_CONTENT -> xml\r\n<module name="Checker">\r\n  <module name="TreeWalker">\r\n    <module name="EmptyLineSeparator">\r\n      <property name="allowNoEmptyLineBetweenFields" value="true"/
>\r\n      <property name="allowMultipleEmptyLines" value="false"/>\r\n      <property name="allowMultipleEmptyLinesInsideClassMembers" value="false"/>\r\n    </module>\r\n  </module>\r\n</module>\r\n
[1:2]
|   `--BLOCK_COMMENT_END -> */ [11:0]
|--PACKAGE_DEF -> package [13:0]
|   |--ANNOTATIONS -> ANNOTATIONS [13:57]
|   |--DOT -> . [13:57]
|   |   |--DOT -> . [13:46]
|   |   |   |--DOT -> . [13:39]
|   |   |   |   |--DOT -> . [13:28]
|   |   |   |   |   |--DOT -> . …
```
> Issue #16564: Fixed EmptyLineSeparator validation with Javadoc

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocVariableCheck.xml
- src/site/xdoc/checks/javadoc/javadocvariable.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariableNoJavadoc2.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/Example2.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/Example4.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/Example5.java
Extends change in https://github.com/checkstyle/checkstyle/pull/16049, in the case of an enum constant, it's accessibility will be derived based on the enclosing enum (which could be `private`) rather than being assumed to be implicitly public.
Test(s) added to validate.
Fixes: https://github.com/checkstyle/checkstyle/issues/16786
Closes: https://github.com/checkstyle/checkstyle/pull/16787
This is _alternative_ implementation of https://github.com/checkstyle/checkstyle/pull/16787, but affecting _only_ `JavadocVariableCheck` to address [concerns](https://github.com/checkstyle/checkstyle/pull/16787/files#r2073671898).
> Issue #16786: Ensure enum constants accessibility is properly evaluated (addressing `JavadocVariableCheck` _only_)

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631
` java -jar checkstyle-10.13.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* <rp>Fallback</rp>
*/
public class Test {}
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/RP_HTML_TAG_NAME
$ java -jar checkstyle-10.13.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * <rp>Fallback</rp>\r\n
|   |   |       |   `--RP -> RP
|   |   |       |       |--RP_TAG_START -> RP_TAG_START …
```
> Issue #14631: Update Javadoc for RP_HTML_TAG_NAME in JavadocTokenTypes.java

- config/jsoref-spellchecker/whitelist.words
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsCategoryIndexTest.java
Issue #17125
This PR introduces a new JUnit test, `XdocsCategoryIndexTest`, to ensure the integrity and accuracy of our check documentation listings in category `index.xml` files. Previously, there was no automated verification for this, potentially leading to outdated or missing entries for checks.
**How the test works**
The `XdocsCategoryIndexTest` systematically verifies check documentation as follows:
1.  **Discover Check XDoc Files:** It first scans the `src/site/xdoc/checks/` directory to find all individual XML files that document a specific check (e.g., `MyCheck.xml`), excluding general files like `index.xml` or `property_types.xml`.
2.  **Extract Check Details from XDoc:** For each discovered check XDoc file:
*   It determines the **main check name** (e.g., "MyCheck") by parsing …
> Issue #17125: Add JUnit Validation to Ensure New Checks Are Listed in index.xml Categories

- .cirrus.yml
Closes #17139
https://cirrus-ci.com/task/6735355057012736
```
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 0 NEQ 0 exit /b 0 
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call ant -version 
Apache Ant(TM) version 1.10.15 compiled on August 25 2024
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 0 NEQ 0 exit /b 0 
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call java --version 
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 0 NEQ 0 exit /b 0 
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call mvn --version 
Apache Maven …
```
> Issue #17139: build set JAVA_HOME and update PATH for OpenJDK installation

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilter.java
Issue: #16155
```
private static FileText getFileText(String fileName) {
final File file = new File(fileName);
FileText result = null;
// some violations can be on a directory, instead of a file
if (!file.isDirectory()) {
try {
result = new FileText(file, StandardCharsets.UTF_8.name());
}
```
Updated to:
```
private static FileText getFileText(String fileName) {
final Path path = Paths.get(fileName);
FileText result = null;
// some violations can be on a directory, instead of a file
if (!Files.isDirectory(path)) {
try {
result = new FileText(path.toFile(), StandardCharsets.UTF_8.name());
}
```
> Issue #16155: Used nio api in SuppressWithNearbyTextFilter

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 :
`java -jar checkstyle-10.25.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
*<option value="yes">Yes</option>
*/
}
```
```
Saloni@Sunflower MINGW64 ~/option_html_tag_name AST
$ java -jar checkstyle-10.25.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n *<option value="yes">Yes</option>\r\n
|   |   |       |   `--OPTION -> OPTION
|   |   |       |       |--OPTION_TAG_START -> …
```
> Issue #14631: Added Javadoc for OPTION_HTML_TAG_NAME in JavadocTokenType.java

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
Issue: #17225
https://github.com/checkstyle/checkstyle/blob/97fae48600dc7650b69e0c5088ea25c6be791713/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java#L36
Example AST tree of MissingDeprecated check's module javadoc
```
|--NEWLINE -> \r\n [0:0]
|--NEWLINE -> \r\n [1:0]
|--NEWLINE -> \r\n [2:0]
|--NEWLINE -> \r\n [3:0]
|--NEWLINE -> \r\n [4:0]
|--NEWLINE -> \r\n [5:0]
|--NEWLINE -> \r\n [6:0]
|--NEWLINE -> \r\n [7:0]
|--NEWLINE -> \r\n [8:0]
|--NEWLINE -> \r\n [9:0]
|--NEWLINE -> \r\n [10:0]
|--NEWLINE -> \r\n [11:0]
|--NEWLINE -> \r\n [12:0]
|--NEWLINE -> \r\n [13:0]
|--NEWLINE -> \r\n [14:0]
|--NEWLINE -> \r\n [15:0]
|--NEWLINE -> \r\n [16:0]
|--NEWLINE -> \r\n [17:0]
|--NEWLINE -> \r\n [18:0]
|--NEWLINE -> \r\n [19:0] …
```
> Issue #17225: Added new data to javadoc of module to extract true version of its properties

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
> Issue #17225: Extend "Since version" javadoc marking implementation

- src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
- src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
part of : #17168
From comment : https://github.com/checkstyle/checkstyle/pull/17259#issuecomment-3019192404
Need for this changes : Inspection error :
[home/circleci/project/target/inspection-results/MethodOnlyUsedFromInnerClass.xml](https://output.circle-artifacts.com/output/job/355610cc-e057-4d11-a6ae-6c9ec5da37cd/artifacts/0/home/circleci/project/target/inspection-results/MethodOnlyUsedFromInnerClass.xml)
```
<problems is_local_tool="true">
<problem>
<file>file://$PROJECT_DIR$/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java</file>
<line>346</line>
<module>project</module>
<package>com.puppycrawl.tools.checkstyle</package>
<entry_point TYPE="method" FQNAME="com.puppycrawl.tools.checkstyle.ConfigurationLoader java.lang.String replaceProperties(java.lang.String …
```
> Issue #17168: Fix inspection for private methods used from inner class

- .circleci/config.yml
part of : #17168
Redundant Job, since anchor image is already update to jdk 17 and we already have a package site validation for jdk17.
> Issue #17168: Remove Jdk11 Site Validation Job

- .ci/travis.sh
- .travis.yml
Issue: #17320 
Removed:
```
deploy-snapshot)
SKIP_DEPLOY=false
if [ "$(git log -1 | grep -E "\[maven-release-plugin\] prepare release" | cat | wc -l)" -lt 1 ];
then
SKIP_DEPLOY=false;
else
SKIP_DEPLOY=true;
fi;
if [[ $TRAVIS_REPO_SLUG == 'checkstyle/checkstyle'
&& $TRAVIS_BRANCH == 'master'
&& $TRAVIS_PULL_REQUEST == 'false'
&& $DEPLOY == 'true'
&& $RUN_JOB == 1
&& $SKIP_DEPLOY == 'false'
]];
then
./mvnw -e --no-transfer-progress -s config/deploy-settings.xml -Pno-validations deploy;
echo "deploy to maven snapshot repository is finished";
fi
;;
```
> Issue #17320: Removed from Travis CI snapshot deploy

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/InvalidJavadocPositionCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocBlockTagLocationCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocContentLocationCheck.xml
- src/site/xdoc/checks/javadoc/invalidjavadocposition.xml
- src/site/xdoc/checks/javadoc/javadocblocktaglocation.xml
- src/site/xdoc/checks/javadoc/javadocblocktaglocation.xml.template
- src/site/xdoc/checks/javadoc/javadoccontentlocation.xml
- src/site/xdoc/checks/javadoc/javadoccontentlocation.xml.template
https://github.com/checkstyle/checkstyle/actions/runs/16238202146/job/45851065652
```
--- .ci-temp/linkcheck-suppressions-sorted.txt	2025-07-12 12:56:37.554866043 +0000
+++ .ci-temp/linkcheck-errors-sorted.txt	2025-07-12 12:56:37.552866051 +0000
@@ -1,3 +1,21 @@
+<a class="externalLink" href="https://docs.oracle.com/en/java/javase/17/docs/specs/doc-comment-spec.html">https://docs.oracle.com/en/java/javase/17/docs/specs/doc-comment-spec.html</a>: 404 Not Found
```
> Updated url flagged by linkcheck

- src/site/xdoc/filters/suppresswithnearbytextfilter.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbytextfilter/Example5.properties
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbytextfilter/Example6.properties
part of #16738 
There was no method named `verifyFilterWithInlineConfigParserSeparateConfigAndTarget()` to update `Example5` and `Example6`.
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyTextFilterExamplesTest.java
I created the `verifyFilterWithInlineConfigParserSeparateConfigAndTarget()` method, as well as a `getFilteredViolation()` method to retrieve filtered violations for verification.
I then updated `Example5` and `Example6` in `SuppressWithNearbyTextFilterExamplesTest.java` to use this new method. 
The main reason for doing this is that some examples in `SuppressWithPlainTextCommentFilterExamplesTest.java` also uses `.properties` as a target files.
This update will help in modifying those …
> Issue #16738: Update SuppressWithNearbyTextFilterExamplesTest to use verifyFilterWithInlineConfigParserSeparateConfigAndTarget

- .github/workflows/google-java-format.yml
from https://github.com/google/google-java-format/releases/tag/v1.28.0?notification_referrer_id=NT_kwDOAAxnuLIxNzQ5MzkzNjUwMTo4MTI5ODQ
> infra: Update google-java-format.yml

- config/checkstyle-examples-suppressions.xml
- src/site/xdoc/filters/suppresswithplaintextcommentfilter.xml
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example1.properties
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example2.properties
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example3.properties
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example4.xml
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example6.xml
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example7.xml
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example8.sql
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example9.java
part of #16738 
updated `SuppressWithPlainTextCommentFilterExamplesTest.java` method's to use `verifyFilterWithInlineConfigParserSeparateConfigAndTarget()`.
`Example9.java` does not use any target file, so it has been updated wih `verifyFilterWithInlineConfigParser()`.
> Issue #16738: Update SuppressWithPlainTextCommentFilterExamplesTest to use verifyFilter

- config/pitest-suppressions/pitest-api-suppressions.xml
- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/site/xdoc/checks/javadoc/writetag.xml
- src/site/xdoc/filters/severitymatchfilter.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableTestWarningSeverity.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEmptyTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEnumsAndAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagRegularExpression.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckExamplesTest.java
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/severitymatchfilter/Example1.java
Fixes #16738 
- Updated `SeverityMatchFilter.java` to use `verifyFilterWithInlineConfigParsar()`.
- Modified `getActualViolations()` in `AbstractModuleTestSupport.java`: removed `errorCount` logic and added a new logic which passes all the test cases.
- `getActualViolations()` no longer depends on the severity level, meaning it now allows violations with any severity level.
- After adding the new logic, multiple test cases that were previously failing are now working properly.
Please verify issue #12980 as well; I believe this issue is now resolved by this PR.
> Issue #16738: Update SeverityMatchFilter to use verifyFilterWithInlineConfigParser

- config/checkstyle-non-main-files-suppressions.xml
- config/jsoref-spellchecker/whitelist.words
- src/site/xdoc/filters/suppressionfilter.xml
- src/site/xdoc/filters/suppressionfilter.xml.template
- src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterExamplesTest.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionfilter/Example1.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionfilter/suppressionexample1.xml
Issue #17401 
Added new files `SuppressionFilterExamplesTest.java`, `Example1.java`,  `suppressionexample1.xml` and `suppressionexample1.txt`
The reason of adding `suppressionexample1.txt` to parse within the `XdocsPagesTest.java`
> Issue #17401: Enabled example macros for suppressionfilter.xml.template

- .ci/google-java-format.sh
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/HorizontalWhitespaceTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceBeforeLeftCurlyOfEmptyBlock.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceBeforeLeftCurlyOfEmptyBlock.java
> supplemental: IT for 4.6.2 whitespace before '{' of empty blocks

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #17362 
second part of the html escape character usage correction PR.
> Issue #17362: Corrected the usage of HTML entities in javadoc

- config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
- config/pitest-suppressions/pitest-tree-walker-suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
For #14019 
```xml
<sourceFile>JavadocDetailNodeParser.java</sourceFile>
<mutatedClass>com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser</mutatedClass>
<mutatedMethod>getMissedHtmlTag</mutatedMethod>
<mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>
<description>removed call to java/util/Deque::pop</description>
<lineContent>htmlTagNameStart = stack.pop();</lineContent>
</mutation>
```
- `JavadocDetailNodeParser`
- First, I hardcoded the mutation
- I ran `mvn clean verify` and all tests passed
- I generated the pitest report and there were no new surviving mutations
- I generated the diff report for `JavadocChecks` and there were no diff
- After hardcoding the mutation, I analyzed its behaviour and the impact on …
> Issue #14019: Kill mutation for getMissedHtmlTag

- .ci/validation.sh
- .github/workflows/no-error-trino.yml
- config/jsoref-spellchecker/whitelist.words
Issue: #17240 
```
no-error-trino)
echo "Building checkstyle..."
./mvnw -e --no-transfer-progress clean install -Pno-validations -DskipTests
echo "Resolving Checkstyle version from pom.xml..."
CS_POM_VERSION="$(getCheckstylePomVersion)"
echo "CS_version: ${CS_POM_VERSION}"
echo "Cloning Trino sources..."
checkout_from https://github.com/trinodb/trino.git
cd .ci-temp/trino
echo "Running Checkstyle ${CS_POM_VERSION} on Trino..."
./mvnw -e --no-transfer-progress checkstyle:check -Dcheckstyle.version="${CS_POM_VERSION}"
cd ../
echo "Cleaning up cloned Trino repo..."
removeFolderWithProtectedFiles trino
;;
```
Trino CI failure for checkstyle violations
https://github.com/trinodb/trino/actions/runs/16391578147/job/46318251496?pr=26242
> Issue #17240: Added Trino to no error testing in CI

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
```
if (ModuleReflectionUtil.isCheckstyleTreeWalkerCheck(moduleClass)
|| ModuleReflectionUtil.isTreeWalkerFilterModule(moduleClass)) {
final Configuration config = createTreeWalkerConfig(moduleConfig);
checker.configure(config);
}
else {
final Configuration config = createRootConfig(moduleConfig);
checker.configure(config);
}
```
changed to 
```
final Configuration config;
if (ModuleReflectionUtil.isCheckstyleTreeWalkerCheck(moduleClass)
|| ModuleReflectionUtil.isTreeWalkerFilterModule(moduleClass)) {
config = createTreeWalkerConfig(moduleConfig);
}
else {
config = createRootConfig(moduleConfig);
}
checker.configure(config);
```
> minor: Refactor to avoid duplicate checker.configure() call

- config/google-java-format/excluded/compilable-input-paths.txt
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/WhereToBreakTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputFormattedNoWrappingAfterRecordName.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputFormattedNoWrappingAfterRecordName2.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputNoWrappingAfterRecordName.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputNoWrappingAfterRecordName2.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputNoWrappingAfterRecordNameCorrect.java
From: https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break
> A method, constructor, or record-class name stays attached to the open parenthesis (() that follows it.
record-class name is newly added to this section.
```
$ cat WrappedRecord.java
/** some javadoc. */
public class WrappedRecord {
record Multi (String string, Record rec) { // OK 
private boolean inRecord (Object obj) { // OK
int value = 0;
if (obj instanceof Integer i) {
value = i;
}
return value > 10;
}
}
record Multi2 () { // OK
Multi2 (String s1, String s2, String s3) { // OK
this();
}
}
record Multi3 (Integer i, Node node) { // OK  
public static void main (String... args) { // OK
System.out.println("works!");
}
}
record Multi4 () {  // OK
void foo(){} 
}
record Multi5() {
static Multi obj …
```
> supplemental: adding inputs for 4.5.1 where to break for record-class

- .gitattributes
- config/checkstyle-resources-suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeWithBlockComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeWithNative.java
Issue: #17332
Fixed logic for determining valid block comment 
```
if (comment.getStartLineNo() == comment.getEndLineNo()) {
final String line = line(comment.getStartLineNo() - 1).trim();
lineHasOnlyBlockComment = line.startsWith("/*") && line.endsWith("*/");
}
```
is updated to
```
final String startLine = line(comment.getStartLineNo() - 1).trim();
if (!startLine.startsWith("/*")) {
lineHasOnlyBlockComment = false;
}
final String endLine = line(comment.getEndLineNo() - 1).trim();
if (!endLine.endsWith("*/")) {
lineHasOnlyBlockComment = false;
}
```
> Issue #17332: Fixed False positive for JavadocType:Unused @param tag

- src/site/xdoc/filters/suppresswithnearbycommentfilter.xml
- src/site/xdoc/filters/suppresswithplaintextcommentfilter.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputViolation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbytextfilter/InputSuppressWithNearbyTextFilterNearbyTextPattern.css.txt
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterCustomMessageFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById5.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsinglefilter/Example3.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsinglefilter/Example9.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithnearbycommentfilter/Example6.java
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/Example9.java
Issue https://github.com/checkstyle/checkstyle/issues/17031
previous violations or filtered violations comment when lines are equal:
`// violation 'some message'` or `// filtered violation 'some message'`
now
`// violation 'num: some message'` or `// filtered violation 'num: some message'` where `num` refers to the violation that comes first, denoted by the smallest integer. We can also use the column number instead. However, it doesn't matter what we use — the `num` is only added to help with sorting, first by line number, then by message.
Previously, the `compareTo()` method sorted in reverse chronological order when the line numbers were equal. Now, it sorts in chronological order.
> Issue #17031: Fix compareTo method for TestInputViolation.java

- src/site/xdoc/google_style.xml
from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2234079569 and #17563
> supplemental: Coverage gap for '6.2 Caught exceptions'

- config/google-java-format/excluded/compilable-input-paths.txt
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/NonemptyBlocksKrStyleTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedKrStyleExceptionLocalVariables.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputKrStyleExceptionLocalVariables.java
- src/site/xdoc/google_style.xml
from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2233986700 and https://github.com/checkstyle/checkstyle/issues/17569
> supplemental: IT and Table update for '4.1.2 Nonempty blocks: K & R style'

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/AnnotationLocationCheck.xml
- src/site/xdoc/checks/annotation/annotationlocation.xml
- src/site/xdoc/checks/annotation/annotationlocation.xml.template
Issue https://github.com/checkstyle/checkstyle/issues/17571
Clarified the documentation in `AnnotationLocationCheck.java` to indicate that the check does not enforce annotations to appear immediately after Javadocs, and points users to `InvalidJavadocPosition` for that purpose.
Appreciate the guidance provided in this issue.
> Issue #17571: Update the documentation of AnnotationLocation

- .ci/eclipse-compiler-javac.sh
- .ci/validation.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLambdaParameterShouldBeUnnamedCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/WhenShouldBeUsedCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordPattern.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckPatterns.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesWhenExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedInsideAnonClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedWithResourceAndFinally.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlambdaparametershouldbeunnamed/InputUnusedLambdaParameterShouldBeUnnamedMultipleParameters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlambdaparametershouldbeunnamed/InputUnusedLambdaParameterShouldBeUnnamedNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlambdaparametershouldbeunnamed/InputUnusedLambdaParameterShouldBeUnnamedSingleLambdaParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableWithAllowUnnamed.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableWithAllowUnnamedFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistancePatternVariables.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/whenshouldbeused/InputWhenShouldBeUsedNonPatternsSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/whenshouldbeused/InputWhenShouldBeUsedSwitchExpression.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/whenshouldbeused/InputWhenShouldBeUsedSwitchRule.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/whenshouldbeused/InputWhenShouldBeUsedSwitchStatements.java
part of : #17429
https://en.m.wikipedia.org/wiki/Java_version_history
https://docs.oracle.com/en/java/javase/24/migrate/significant-changes-jdk-21.html
Reason to enable preview features of jdk in checkstyle:
- Checkstyle vis always behind in jdk usage by 1 or 2 lat releases.
- Preview features are appearing and removed, good example is "String templates" in jdk21. It is very awaited feature by users, so user immediately would use it, but it challenging in consistent behavior, so it was removed few releases later. If checkstyle started to use such feature, it will be pain to refactor to stop using it. We removed support of string templates, as it was big  problem for us to support too.
- checkstyle has its own parser of java, so even jdk preview feature is in , and we enable them, on first …
> Issue #17429: Relocate inputs to compilable path for Coding Module1

- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableRecordDecomposition.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersRecordForLoopPatternVariables.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapGuardedPatterns.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputGenericRecordDeconstructionPattern.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19BindingWithModifiers.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19BindingsWithLotsOfOperators.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19GuardsWithExtraParenthesis.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19PatternsAnnotationsOnBinding.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19PatternsInNullSwitch1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19PatternsInNullSwitch2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19PatternsInSwitchLabels.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19PatternsTrickyWhenUsage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputJava19RecordDecompositionWithConditionInLoops.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputRecordPatternsPreview.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java19/InputRecordPatternsPreviewNestedDecomposition.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java20/InputJava20RecordDecompositionEnhancedForLoop.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java20/InputJava20RecordDecompositionEnhancedForLoopTricky.java
part of : #17429
All these changes were supported before jdk21
Report of changes :
1. Parenthesized Patterns Removed
Java 19 preview (JEP 405) allowed extra parentheses around record patterns for flexibility, e.g.:
`case (Box<Box<String>>(Box<String>(String s) box)) -> ...`
Java 21 (JEP 441) removed parenthesized patterns:
> “Remove parenthesized patterns, since they did not have sufficient value.”
✅ Java 21 requires:
`case Box<Box<String>>(Box<String>(String s) box) -> ...`
2. Guards (when clauses) Simplified
Java 19 preview allowed overly nested/casted expressions in guards:
`
case Box(Box(String s) box) when (boolean)"test".equals(s) -> 1;`
Java 21 (JEP 441) requires plain boolean conditions without unnecessary casts/extra parentheses.
✅ Legal in Java 21:
`case Box(Box(String s) box) …
> Issue #17429: Changing Comment for module compilable before jdk21

- src/site/xdoc/checks/sizes/linelength.xml
- src/site/xdoc/checks/sizes/linelength.xml.template
- src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/Example6.java
> supplemental: Documentation to disable LineLength Check on Text-blocks

- src/test/java/com/puppycrawl/tools/checkstyle/IndentationTrailingCommentsVerticalAlignmentTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLineWrappedRecordDeclaration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationValidBlockIndent1.java
Part of Issue #17128
- Ignored import lines during alignment checking (as per [comment](https://github.com/checkstyle/checkstyle/pull/17409#issuecomment-3146724011)).
- Fixed alignment in two input files:
- [`InputIndentationLineWrappedRecordDeclaration.java`](src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLineWrappedRecordDeclaration.java)
- [`InputIndentationValidBlockIndent1.java`](src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationValidBlockIndent1.java)
> Issue #17128: ignore import lines during check, fix alignment in more input files

- config/jsoref-spellchecker/whitelist.words
- pom.xml
fixes #17642
based on https://stackoverflow.com/a/71785465
https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#doclint
https://docs.oracle.com/en/java/javase/17/docs/specs/man/javadoc.html#additional-options-provided-by-the-standard-doclet
>missing: Checks for missing documentation comments or tags (for example, a missing comment or class, or a missing `@return` tag or similar tag on a method).
it is not ideal fix, but we enable warning and disable specific validations, we disabling a bit more than required, but it is limitation of javadoc tool
> Issue #17642: enable javadoc warning but disable missing

- .ci/error-prone-check.groovy
detected during investigatioon of https://github.com/checkstyle/checkstyle/actions/runs/17534091743/job/49794859272?pr=17675#logs
there is no print of actual mvn command, so contributors were confused on how to reproduce this on local.
> minor: log cmd for error-prone

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #14631 
**Test.java**
```
/**
* <p>Paragraph Tag.</p>
*/
}
```
**Command**
```
$ java -jar checkstyle-11.0.1-all.jar -j Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
```
**AST**
```
|   |   |--COMMENT_CONTENT -> *\r\n * <p>Paragraph Tag.</p>\r\n
|   |   |       |   `--PARAGRAPH -> PARAGRAPH
|   |   |       |       |--P_TAG_START -> P_TAG_START
|   |   |       |       |   |--START -> <
|   |   |       |       |   |--P_HTML_TAG_NAME -> p …
```
> issue #14631: Update Javadoc for SLASH token

- pom.xml
Fixes: #16543
Fixes: #17487
- https://docs.openrewrite.org/changelog/8-51-0-Release
[tech.picnic.errorprone.refasterrules.StreamRulesRecipes$StreamMapFirstRecipe](https://docs.openrewrite.org/recipes/tech/picnic/errorprone/refasterrules/streamrulesrecipesusdstreammapfirstrecipe): Where possible, clarify that a mapping operation will be applied only to a single stream element.
```
[WARNING] Changes have been made to src/main/java/com/puppycrawl/tools/checkstyle/site/ModuleJavadocParsingUtil.java by:
[WARNING]     tech.picnic.errorprone.refasterrules.StreamRulesRecipes
[WARNING]         tech.picnic.errorprone.refasterrules.StreamRulesRecipes$StreamMapFirstRecipe
```
> Issue #17487: Add `errorprone.refasterrules`

- src/site/xdoc/cmdline.xml.vm
Fixes #17834
**Updated**
```
&lt;!DOCTYPE suppressions PUBLIC
"-//Checkstyle//DTD Checkstyle Configuration 1.2//EN"
"https://checkstyle.org/dtds/suppressions_1_2.dtd"&gt;
```
> Issue #17834: Fix DTD in suppressions.xml example

- config/google-java-format/excluded/compilable-input-paths.txt
- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputCorrectJavadocLeadingAsteriskAlignment.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedCorrectJavadocLeadingAsteriskAlignment.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedIncorrectJavadocLeadingAsteriskAlignment.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputIncorrectJavadocLeadingAsteriskAlignment.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPositionRecord.java
- src/main/resources/google_checks.xml
- src/site/xdoc/checks/javadoc/javadocleadingasteriskalign.xml
- src/site/xdoc/checks/javadoc/javadocleadingasteriskalign.xml.template
- src/site/xdoc/google_style.xml
Issue: #17778 
Added [JavadocLeadingAsteriskAlign](https://checkstyle.org/checks/javadoc/javadocleadingasteriskalign.html#JavadocLeadingAsteriskAlign) in google_checks.xml to ensure javadoc's leading asterisks alignment based on rule [7.1.1 General Form](https://google.github.io/styleguide/javaguide.html#s7.1.1-javadoc-multi-line).
The input files are directly copied from Check's input files:  https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocleadingasteriskalign
I didn't copied the [InputJavadocLeadingAsteriskAlignTabs.java](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocleadingasteriskalign/InputJavadocLeadingAsteriskAlignTabs.java) …
> Issue #17778: Added JavadocLeadingAsteriskAlign Check in google_checks.xml for Rule: 7.1.1 General Form

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Fixes #14631
`java -jar checkstyle-11.0.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* <p>Paragraph Tag.</p>
*/
}
```
```
Windows@Windows MINGW64 ~/ASt (master)
$ java -jar checkstyle-11.0.1-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   |   |--COMMENT_CONTENT -> *\r\n * <p>Paragraph Tag.</p>\r\n
|   |   |       |   `--PARAGRAPH -> PARAGRAPH
|   |   |       |       |--P_TAG_START -> P_TAG_START
|   |   | …
```
> Fixes #14631  Updates SLASH token documentation to match new AST format.

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ClassAnnotationsTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/example1/package-info.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/package-info.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/Name.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ParentPackage.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/SizePackage.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/example1/package-info.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/example2/package-info.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/example3/package-info.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/example4/package-info.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/example5/package-info.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/package-info.java
- src/main/resources/google_checks.xml
- src/site/xdoc/google_style.xml
resolves #17540
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/f3d0e6d4aa5b6e25a9d3a6b9d5425972/raw/82af3a37f61201b3c95b3094391da73115bc3809/master_annotationlocation.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/b53a185be531c4ac11653a45b478e2a1/raw/5751b1e4812eb9e659b4c19cc49da1a109942f73/patch_annotationlocation.xml
> Issue #17540: Enforce Annotation location rule in package-info.java
