pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/coding/InputEqualsAvoidNull.java

Behaviour of the Check has not changed. Checkstyle reports before and after my commit are identical: http://baratali.github.io/equals_avoid/index.html (report under Guava+HBase)

Issue #1293: Refactoring of EqualsAvoidNullCheck. More UTs.

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/whitespace/InputEmptyLineSeparatorMultipleImportEmptyClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/whitespace/InputPrePreviousLineEmptiness.java

Reports for Guava and Hibernate projects before check's refactoring and after are identical: http://rdiachenko.github.io/

Issue #1289: 'EmptyLineSeparatorCheck' refactored, UT coverage improved

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/InputWhitespace.java

Reports for Guava, Hibernate, Spring, pmd, findbugs projects before check's refactoring and after are identical: http://rdiachenko.github.io/

Issue #1289: 'NoWhitespaceAfterCheck' refactored, UT coverage improved

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java

Checkstyle reports: http://baratali.github.io/modified_control/index.html **Reports are identical**

Issue #1293: Improved coverage for ModifiedControlVariableCheck

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java

Done without checks's code modification

Coverage has been increased to 100% in SinglelineDetector. Issue #1010

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/InputTypeParamsTags.java
src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputLoadErrors.java
src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputMissingJavadocTags.java
src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputSetterGetter.java
src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/TestGenerics.java

Reports over about 10,000 files are the same:
```
diff 6.8/checkstyle-result.xml 6.9/checkstyle-result.xml -U 0
--- 6.8/checkstyle-result.xml
+++ 6.9/checkstyle-result.xml
@@ -2 +2 @@
-<checkstyle version="6.8.1">
+<checkstyle version="6.9-SNAPSHOT">
```

Add tests and refactor JavadocMethod check. #1308

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/filters/InputSuppressWithNearbyCommentFilter.java

Test coverage improved to 100%.

Issue #1296: 'SuppressWithNearbyCommentFilter' refactored, UT coverage improved

---

pom.xml

This commit should fix majority of violations in `pom.xml`: http://nemo.sonarqube.org/issues/search#resolved=false|projectUuids=93eb9164-80ec-4136-9c42-d4d23deed1db|fileUuids=c0e3f6be-c841-440c-8f1a-69445f10ba8f

Fix SonarQube violations in pom.xml. #46

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/suppressions_id.xml
src/test/resources/com/puppycrawl/tools/checkstyle/suppressions_invalid_file.xml
src/test/resources/com/puppycrawl/tools/checkstyle/suppressions_no_check_and_id.xml

Test coverage improved to 100%.

Issue #1296: 'SuppressionsLoader' refactored, UT coverage improved

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java

1) Done refactoring of `validate` method to make it static.
2) Added if/else at `visitToken` to save performance since an array which is returned by getLines() is used inside validate only when `shouldStartLine = true` .
[REPORTS](http://mezk.github.io/index.html)
diff result:

Refactoring of RightCurlyCheck, issue #1511.

---

src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/JTreeTable.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeInfoPanel.java

Inner classes were moved to the end of outer classes.

Issue #1566: 'Fields and methods should be before inner classes' violations fixed

---

src/main/java/com/puppycrawl/tools/checkstyle/gui/FileDrop.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeInfoPanel.java

Violations fixed:
- DeclarationOrder Constructor definition in wrong order.

Issue #1566: Constructor definition in wrong order fixed

---

src/main/java/com/puppycrawl/tools/checkstyle/gui/JTreeTable.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeInfoPanel.java

Violations fixed:
- Indentation 'X' child have incorrect indentation level Y, expected level should be Z.

Issue #1566: incorrect indentation fixed

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/CommentSuppressor.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java

Reports are identical:
http://sabaka.github.io/CommentSuppressor/master/checkstyle.html
http://sabaka.github.io/CommentSuppressor/checkstyle.html

Coverage has been increased to 100% in CommentSuppressor. Issue #1010

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/CheckUtilsTest.java

without changes in CheckUtils.

Coverage has been increased to 100% in CheckUtils. Issue #1290

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/AbstractCellEditor.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/AbstractTreeTableModel.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ListToTreeSelectionModelWrapper.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/Main.java

Violations fixed partially:
- JavadocMethod: Missing a Javadoc comment.
- JavadocVariable: Missing a Javadoc comment.

Issue #1566: 'missing javadoc comment' violations partial fix

---

config/checkstyle_checks.xml

Issue #1566: New Checks added to checkstyle_checks config

---

config/checkstyle_checks.xml
config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/api/Comment.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractOptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/ClassResolver.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/AbstractParenPadCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java

Fixed violations:
- MultipleStringLiterals ```The String "XXX" appears X times in the file.```

Issue #1566: MultipleStringLiterals violations fixed

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java

NoWhitespaceBeforeCheck has been refactored

Issue #1566: Fixed CyclomaticComplexityCheck violation (partial)

---

src/main/java/com/puppycrawl/tools/checkstyle/api/Check.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java

Fix for:
- JavadocMethod ```Missing a Javadoc comment.```

Issue #1566: 'missing javadoc comment' violations fixed for Check, JavadocNodeImpl

---

config/checkstyle_checks.xml
config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/gui/FileDrop.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeInfoPanel.java

Fix for ```WriteTag``` violations.

Issue #1566: WriteTag violations fixed

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java

Nested if, for, while, switch and try statements is a key ingredient for making what's known as "Spaghetti code". Such code is hard to read, refactor and therefore maintain.

Issue #46. Statements shouldn't be nested too deep.

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java

Without changes in check's code

Issue #1290: Coverage has been increased to 100% in NewLineAtTheEndOfFileCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputTags.java

Provides a fix for #2141 and updates test cases.

Issue #2141: Allow @return tags from annotation types

---

src/xdocs/config_misc.xml

Now it should be clearer what for this check is from the first example.

Doc: examles order for DescedantTokenCheck has been changed.

---

src/it/java/com/google/checkstyle/test/base/BriefLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java

[Compatibility problem](https://groups.google.com/forum/#!topic/checkstyle-devel/3jJ4cCQ3sM0) was resolved.

Issue #67: Added support of logging severity for all audit events

---

pom.xml

SLF4J Simple Binding is enough for test purposes and does not require any configuration.

Issue #2129: Remove some non-maven output from test launches

---

src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java

https://travis-ci.org/checkstyle/checkstyle/jobs/80743904#L607-L608

Issue #2195: Remove errors from Maven output in TokenTypesDocletTest

---

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java

- the test was stabilized by overcoming the problem with Assume.assumeTrue due to https://github.com/jayway/powermock/issues/428
- alternate github location was added in case sourceforge is unavailable

Issue #2191: SuppressionsLoaderTest UT was stabilized

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/InputSuppressWarningsHolder3.java
src/test/resources/com/puppycrawl/tools/checkstyle/InputSuppressWarningsHolder4.java

Reports are identical
before changes: http://sabaka.github.io/SuppressWarningHolder/master/checkstyle.html
after changes: http://sabaka.github.io/SuppressWarningHolder/checkstyle.html

Issue #1290: Coverage has been increased to 100% in SuppressWarningsHolder.

---

src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputCovariant.java

@romani Fix for failing master

minor: fixed failing master

---

pom.xml
src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java
src/it/java/com/google/checkstyle/test/base/IndentationConfigurationBuilder.java
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/AllChecksPresentOnAvailableChecksPageTest.java
src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java

- 'forbiddenapis' maven plugin was added and configured
- violations were fixed, input resources were marked as excluded

Issue #1217: adding 'forbiddenapis' verification tool into Checkstyle

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputDeclarationOrder.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputEmptyStatement.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputEqualsHashCodeCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputWhitespace.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputDeclarationOrder.java

Issue #2161: unify test input locations for coding package

---

config/suppressions.xml

Once this is merged, I feel we are done with this issue.
No violations found.
Removed "Generated[a-zA-Z]*\.java" suppression since those files are not in the "src" directory, so there should be no conflict.

Issue #2421: removed unneeded suppressions

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java
src/xdocs/config_imports.xml

removed documentation of samePackageMatchingDepth and override in unit test.

Issue #2453: removed xdoc of CustomImportOrder.samePackageMatchingDepth

---

src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java
src/xdocs/config_annotation.xml
src/xdocs/config_blocks.xml
src/xdocs/config_coding.xml
src/xdocs/config_design.xml
src/xdocs/config_filters.xml
src/xdocs/config_header.xml
src/xdocs/config_imports.xml
src/xdocs/config_javadoc.xml
src/xdocs/config_metrics.xml
src/xdocs/config_misc.xml
src/xdocs/config_modifier.xml
src/xdocs/config_naming.xml
src/xdocs/config_regexp.xml
src/xdocs/config_sizes.xml
src/xdocs/config_whitespace.xml

Removed some duplicates in regexp.
**New Requirements:**
Removed xml restriction in usage section, now section can only contain certain words.
Added URL validation for links in usage section.

Issue 2517 2519

---

src/xdocs/google_style.xml

Issue #2519: removed xdoc google style links to master

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/CustomImportOrderTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/LineLengthTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/MethodParamPadTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/OperatorWrapTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/SeparatorWrapTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/MultipleVariableDeclarationsTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/FallThroughTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder1.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder3.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderValid.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/toolongpackagetotestcoveragegooglesjavastylerule/InputLineLength.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputLineLength.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputMethodParamPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrapAssign.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/MultipleVariableDeclarationsInput.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/FallThroughInput.java

As suggested:
> please rename "rule333orderingandsoacing" to ".......spacing"
> "toolongpackagetotestcoveragegooglesjavastylerool" --> ".....rule"
I also went through all the folder names and fixed any other spelling errors i saw.
Let me know if you see one I missed.

Issue #2540: fix spelling errors in it packages

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentaion/InputFastMatcher.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentaion/InputIndentationCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputFastMatcher.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFastMatcher.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrect.java

the last of the putting 'Input' in front of the input file names

Issue #2540: unify it input file names for chapter4formatting

---

config/checkstyle_sevntu_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/Comment.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java

@romani 
The last check from issue https://github.com/checkstyle/checkstyle/issues/2661.

Issue #2661: Enforce AvoidConditionInversionCheck of sevntu-checkstyle over Checkstyle source code

---

.gitignore

https://en.wikipedia.org/wiki/.DS_Store

minor: DS_Store file has been added to .gitignore

---

config/findbugs-exclude.xml
config/pmd.xml
config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputDeclarationOrderForwardReference.java
src/xdocs/config_coding.xml

@romani 
OOM exception happened during Travis CI execution.

Issue #924: Fix enforcement of declaration order which leads to illegal forward reference

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
src/xdocs/google_style.xml

Issue #2975 
Added row anchors to all rows in style's TOC.
Added test to verify anchors are correctly named.

Issue #2975: added anchors to all google_style's TOC rows

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java

Issue #1487 
to get 100% coverage

Issue #1487: workaround for cobertura at CheckstyleAntTask.java 

---

config/checkstyle_sevntu_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java

https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/429

Pull #3042: reenable two sevntu checks

---

pom.xml

It contains fix for vertical text

config: dsm-maven-plugin has been updated

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java

@romani requested:
1) IsBlank method need to be created
2) we should not use deprecated guava methodshttp://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Objects.html#firstNonNull(T,%20T)

Issue #2428: Remaining cleanup

---

src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/MethodReferencesTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammars/java8/InputMethodReferences7.java

Issue #2968 
Here are the new examples I found. I still have to test travis for 2 others before declaring this is all I can find or create.
It seems the current grammar will accept them, so I added the test for them.

Issue #2968: adding more method references examples

---

src/site/site.xml
src/xdocs/sponsoring.xml

Issue #3057: Fund raising pages for checkstyle

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/xdocs/config_misc.xml

Issue #2969: Add the ability to validate language codes by TranslationCheck

---

config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java

https://github.com/checkstyle/checkstyle/pull/3092

Pull #3093: Use DatatypeConverter#printHexBinary to convert byte array to hex String in PropertyCacheFile

---

distelli-manifest.yml

#2825 
Launches checkstyle-tester with only Javadoc Checks against guava and spring sources.
Please merge checkstyle/contribution pull request before this one: https://github.com/checkstyle/contribution/pull/81

Issue #2825: distelliCI manifest file added

---

src/xdocs/writingjavadocchecks.xml.vm

#410 
How it looks like: http://baratali.github.io/site/writingjavadocchecks.html

Issue #410: Wiki-page .'Tools To See Javadoc Tree Structure' part

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java

Issue #2271:  Fix issues for Java found by Codacy static analysis tool

---

src/xdocs/writingjavadocchecks.xml.vm

#410
http://baratali.github.io/site/writingjavadocchecks.html

Issue #410: Wiki-page. Some more info.

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCommentsIndentationCommentIsAtTheEndOfBlock.java

Issue #2998 
Report: http://vladlis.github.io/reports/2998_2/index.html

Issue #2998: Fix CommentsIndentation Check false-positive at the end of a block

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: Wiki-page. What is Javdoc comment.

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/DoWhileHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidDoWhileIndent.java

Issue #3136
Added indentation check of `while` in `do .. while`.
It is required to be on the same indentation as `while` if it starts the line.
Added minor change to IndentAudit to also verify the line number.

Issue #3136: added indentation check of while in do..while

---

pom.xml
src/xdocs/writingchecks.xml

Issue #2966: Upgrade maven-site-plugin to 3.5.1

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtils.java

requested from PR #3146 
Regression of  all checks that call the changed method: http://rnveach.github.io/checkstyle/minor_3146/
No differences reported.

minor: fixed ScopeUtils.isClassFieldDef checking for variables

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410. Wiki page

---

src/xdocs/writingjavadocchecks.xml.vm

#410 
How the page looks like: http://baratali.github.io/site/writingjavadocchecks.html

Issue #410: WritingJavadocChecks wiki-page changes.

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: WritingJavadocChecks wiki-page. Link to issue.

---

src/xdocs/writingjavadocchecks.xml.vm

WritingJavadocChecks wiki-page changes

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: WritingJavadocChecks wiki-page. Some amendments.

---

.gitignore

And some formatting etc. changes for better readability
Signed-off-by: Michael Vorburger <mike@vorburger.ch>

Improve .gitignore by adding .pmd etc. by m2e-code-quality

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

Issue #3168 fix
Based on conversations in PR #3195
Reason for this fix: https://github.com/checkstyle/checkstyle/pull/3195#issuecomment-220686877

Issue #3168: allow new line on end of commit

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: More examples to WritingJavadocChecks wiki-page

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCommentsIndentationInEmptyBlock.java

Issue #3127
Report shows no regression: https://vladlis.github.io/reports/3127/
Tested projects: checkstyle, sevntu-checkstyle, openjdk7, guava, findbugs, pmd, lombok-ast, spring, hibernate, elasticsearch, java-design-patterns, MaterialDesignLibrary, Hbase, Orekit, apache-ant, apache-jsecurity, android-launcher, infinisoan, protonpack, jOOL, RxJava

Issue #3127: fix CommentsIndentation false-positive in empty array declarations

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

Issue #3266
Rewrote test to also show which rule was broken on validation.
Some important changes:
* `#\\d*` was changed to `#\\d+` since we require the issue/pull number.
* when the commit message is displayed during a failure, it shows the hidden characters `\r, \n, \t` for easier debugging

Issue #3266: refactored commit message validation to allow new lines

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCommentsIndentationInMultiblockStructures.java

Issue #3220 
Report shows no regression: https://vladlis.github.io/reports/3220/
Tested projects: checkstyle, sevntu-checkstyle, openjdk7, guava, findbugs, pmd, lombok-ast, spring, hibernate, elasticsearch, java-design-patterns, MaterialDesignLibrary, Hbase, Orekit, apache-ant, apache-jsecurity, android-launcher, infinispan, protonpack, jOOL, RxJava

Issue #3220: CommentsIndentation: allow upper comments for following block at multi-block structures

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: Info about 'Not supported in HTML5' tags

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: More info about HTML5 tags

---

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4

minor: formatting in antlr4 grammar

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: Table describing new HTML standard update in Javadoc grammar

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #410: Various amendments in wiki-page

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java

#3361
Few minor preparations for https://github.com/checkstyle/checkstyle/issues/3074.

minor: fix hardcoded messages in UTs and spelling mistakes in FinalLocalVariable

---

config/sevntu_suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java

Issue #3317: Fix build failure on German machine

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/xdocs/cmdline.xml.vm

Issue #3287
Issue is not yet approved.

Issue #3287: added exclude directory option

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputChainedMethods.java

@rnveach @romani Fixes for #3208.  Please review.

Issue #3208: Add better support for chained methods

---

.gitignore
.travis.yml
pom.xml

Issue #3378: Added NonDex to pom.xml, .travis.yml, and .gitignore

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputEqualsHashCodeNoEquals.java
src/xdocs/config_coding.xml

Issue #3308 
Added new violation, was a minor logic change.

Issue #3308: EqualsHashCode violation for hashCode without equals

---

src/xdocs/config_filters.xml

Issue #977: Extend xdocs for SuppressCommentFilter and SuppressWithNearbyCommentFilter

---

config/sevntu_suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/gui/JTreeTable.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTableModel.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePModel.java

Issue #408: Update Checkstyle GUI in order to display Javadoc tokens

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule487modifiers/ModifierOrderTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputModifierOrder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/InputModifier.java
src/xdocs/config_modifier.xml

Issue #3471 
Fix expected order of modifiers and update documentation of ModifierOrder

Issue #3471: Fix order of "default" method modifier

---

src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/api/InputClearDetailAstLazyLoadCache.java

Issue #3466: Clear cache in DetailAST before changing its structure 

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #3507: Link to issue which can change DetailNode tree

---

config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpInPkgTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlTest.java

Issue #3514
@romani since you already told me this change was OK,
I didn't wait for the issue to be labeled as 'approved' to make this PR.
I didn't know this would make the build fail.

Issue #3514: Rename PkgControl to ImportControl

---

pom.xml

minor: added rnveach as developer

---

pom.xml

config: bump maven compiler version

---

config/pmd.xml
config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/api/RootModule.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/test/java/com/puppycrawl/tools/checkstyle/TestRootModuleChecker.java
src/test/resources/com/puppycrawl/tools/checkstyle/config-custom-root-module.xml
src/xdocs/cmdline.xml.vm

Issue #3515.
Named the new interface `InitialModule`.

Issue #3515: allowed cli to override and swap checker

---

config/checkstyle_checks.xml
src/xdocs/cmdline.xml.vm
src/xdocs/index.xml.vm
src/xdocs/writingjavadocchecks.xml.vm

added validation for VM files located in xdocs

minor: added vm files to be checked by checkstyle

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java

Issue #3255
Removed unnecessary String fields, inlined their values into the Pattern, and renamed pattern to be same name as setter (which is what the string field was).

Issue #3255: removed unnecessary string fields for patterns

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java

Issue #3536
With this change, the proxy stopped showing connections for this DTD to the server.

Issue #3536: added import control dtd 1.2 to loader

---

src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAroundTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/ParameterNameTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundBasic.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterNameSimplePriv.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterNameSimplePub.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/InputEmptyBlockCatch.java
src/main/resources/google_checks.xml
src/xdocs/google_style.xml

Issue #3381 
I had to extend BaseCheckTestSupport to allow test of config files containing multiple instances of the same check (`ParameterName`). Please let me know if belongs here of if it should be moved to another Issue/RP.

Issue #3381: Update Google style coverage to state of 12 July 2016

---

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java

Issue #3536
Changed assume to if.

Issue #3536: changed assume into if because of powermock interference

---

config/checkstyle_sevntu_checks.xml

config: added notice about hardcoded cache file

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/InputFinalInEnumMethods.java
src/xdocs/config_modifier.xml

Issue #2068
Updated documentation and added test to show.

Issue #2068: updated RedundantModifier documentation for final in enums

---

config/findbugs-exclude.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/FileContentsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/FileContentsHolderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/FileSetCheckLifecycleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java

Issue #2992: ThreadLocal usage in single-threaded checkstyle

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
src/xdocs/config_filters.xml
src/xdocs/config_javadoc.xml

Issue #3575 
Severity level converter.

Issue #3575: changed module setters for severity level

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlTest.java

Issue #3498 
inPkg renamed to packageName because package is keyword.

Issue #3498: ImportCheckControl refactored

---

config/intellij-idea-inspections.xml
config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
src/xdocs/config_javadoc.xml
src/xdocs/config_naming.xml

Issue #3575: changed module setters for scope

---

.travis.yml

infra: Use launch.groovy for 'NoException' testing (Travis)

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
src/xdocs/config_header.xml
src/xdocs/config_imports.xml
src/xdocs/property_types.xml

Issue #3575
HeaderCheck and ImportControl were affected by this change. Changes in test are based on where the exception was being thrown from.
I changed `ImportControl.setUrl` to just call `ImportControl.setFile` since they are eventually doing the same thing.

Issue #3575: changed module setters for uri

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableMultiCatch.java

Issue #3617: make FinalLocalVariable not check multi-catch vars

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePModel.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePModelTest.java

This PR is for Issue #3606 
Made some edits for bugs found during testing. The class now has 100% UT coverage

Issue #3606: Test coverage boost for ParseTreeTablePModel.java 

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePModelTest.java

Issue #3606: additioanl UTs for coverage 100%

---

.ci/README.md
.ci/travis/travis.sh
.ci/travis/xtr_releasenotes-gen.sh
.travis.yml

Issue #3632: releasenotes generation was moved to separate shell file

---

.ci/travis/travis.sh
.ci/travis/xtr_pr-description.sh
.ci/travis/xtr_releasenotes-gen.sh
.travis.yml

Issue #3632: pr description validation is moved to shell script

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/MethodParamPadTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/ParenPadTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputMethodParamPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputParenPad.java
src/main/resources/google_checks.xml
src/xdocs/config_whitespace.xml
src/xdocs/google_style.xml

Issue #2809
Added method param pad check and paren pad check to google style 4.6.2.

Issue #2809: added new checks for google style 4.6.2

---

.ci/travis/travis.sh
.travis.yml

Issue #3632 bunch of configs

---

config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/xdocs/config.xml

Issue #3184: Make hardcoded map with all module names that in checkstyle

---

.ci/travis/checkchmod.sh
.ci/travis/travis.sh
.travis.yml

Issue #3683: add to CI test permissions on all files

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyDoWhile.java

Issue #3681: fixed NPE in RightCurly when do has no curlies

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java

Issue #3582
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/169/
No differences. This is probably a rare case.

Issue #3582: marked enum field's final method as redundant

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFallThrough.java

Issue #3509
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/173/
Again, no differences.

Issue #3509: fixed try with resource on FallThroughCheck

---

config/checkstyle_sevntu_checks.xml

Issue #3064: removed waiting comment that was already implemented

---

wercker.yml

Issue #3670: add pgjdbc project at NoErrorTest group of tests

---

config/suppressions.xml

config: Suppress MethodCount check in tests

---

pom.xml

Issue #3708
Just happened to notice this when looking at the other issue.
Couldn't have started with an easier fix than this. :)

Issue #3708: increased mutation for naming package to 100%

---

config/checkstyle_checks.xml
config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/xdocs/config_imports.xml

Issue #3462: Implement 'path' property for ImportControlCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/InputUnusedImportFromJavaLang.java

#3741
Diff reports:
http://mezk.github.io/i3741-UnusedImports/diff/index.html

Issue #3741: Fix false negative when import is from java.lang package

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #3740
Just added the test and the overrides.
Split the test from the previous issue into a common method so both configs can use it.

Issue #3740: verify all tokens are used in google config

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputJavadocReceiverParameter.java

Issue #3732: fix NPE for Java 8's 'receiver parameter'

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java

Issue #3764: removed garbage placed in RightCurlyCheck's rcurly

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #3753: updated reason for no NeedBracesCheck on lambda

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputRequireThis3.java

Issue #3041
Diff reports: https://vladlis.github.io/3041/index.html

Issue #3041: RequireThisCheck doesn't see outer classes for anonymous classes

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java

Issue #3771: fixed in NPE in cache for HeaderCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyTryResource.java
wercker.yml

Issue #3776: fixed try-resource in RightCurlyCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java

Issue #3778: show exception when failed to instantiate class

---

.ci/travis/travis.sh
circle.yml
wercker.yml

#3782
Must be merged only after https://github.com/checkstyle/contribution/pull/164

infra: Update CIs configs to use cli options names of launch.groovy

---

.ci/travis/travis.sh

infra: fix launch.groovy script parameters

---

wercker.yml

Issue #3790: Add the Hibernate Search project to the Checkstyle CI

---

.ci/travis/travis.sh
circle.yml
wercker.yml

#3801
Should be merged after https://github.com/checkstyle/contribution/pull/170

infra: fix cli arg names for launch.groovy

---

src/xdocs/config_javadoc.xml

Issue #3800: Typo in website documentation for JavadocMethod

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/xdocs/config_metrics.xml

Issue #3797: fix default and acceptable tokens for NPathComplexityCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputWhitespace.java
src/xdocs/config_whitespace.xml

Issue https://github.com/checkstyle/checkstyle/issues/3718

Issue #3718: Add varargs support for NoWhitespaceBefore

---

wercker.yml

testing moving commit to latest fix

infra: update orekit commit

---

src/xdocs/config_imports.xml

As discussed in #3736.
Please tell me if this example should be extended or if wording should be changed.

doc: Add notes on import control config for inner classes

---

config/import-control.xml

Issue #3736: Clean up import control configuration

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputAnnotationClosingParenthesisEndsInSameIndentationAsOpening.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputAnnotationScopeIndentationCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCommentsIndentationAfterAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCorrectMultipleAnnotationsWithWrappedLines.java

Issue #3733
checkAnnotationIndentation has been modified to check one annotation at a time, and recurse to handle additional annotations.

Issue #3733: Modify indent check to handle multiple, stacked annotations

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidIfIndent.java

Issue #3803: added new case for if and or operator for IndentationCheck

---

config/checkstyle_checks.xml

Issue #3751
Just adding the token

Issue #3751: added assert literal to checkstyle illegal token

---

config/checkstyle_checks.xml
config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ListToTreeSelectionModelWrapper.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #3735
Are we sure we are ok with `allowSingleLineStatement`? This means no braces when it is a single line. We still require braces for if statements even if it is small.

Issue #3735: added lambdas to NeedBraces for checkstyle config

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #3748: updated reason for google's EmptyBlockCheck config

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/xdocs/config_coding.xml

 Issue #3729: Reevaluate tokens in IllegalTokenText

---

src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_2.dtd

Issue #2935 
Only the DTD change for now. The documenting I will do soon.
Is it possible to have multiple PRs for one issue (for correct changelog generation)? If not, I will add the other changes to this PR as well.

Issue #2935: Correct naming in import control DTD

---

.ci/travis/travis.sh
.travis.yml

Issue #3843
Added check for missing classes in Cobertura coverage report

Issue #3843: Add check for missing classes in Cobertura coverage report

---

src/xdocs/config_misc.xml

spelling: Fix typo in documentation

---

circle.yml

Issue #3869: Provide ability to skip CI executions base on commit files in CircleCI

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputWhitespaceMultilineCast.java

Issue #3850 
Diff: https://soon-checkstyle-diffs.github.io/

Issue #3850: Fixed "'typecast' is not followed by whitespace" for multiline cast.

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

Issue #3910: CommitValidationTest: add character limit to line

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputParenPadLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputParenPadLambdaOnly.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputParenPadLambdaOnlyWithSpace.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputParenPadLambdaWithSpace.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputParenPadWithDisabledLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputParenPadWithSpaceAndDisabledLambda.java
src/xdocs/config_whitespace.xml

Issue #3329 
Diff: https://soon-checkstyle-diffs.github.io/issue-3329

Issue #3329: Added lambda to ParenPad

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterAround.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterBraces.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterDefaultConfig.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterDoWhile.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterFor.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterGenerics.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralDo.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralElse.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralFor.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralIf.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralWhile.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterMultilineCast.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterTypeCast.java

https://github.com/checkstyle/checkstyle/issues/3897

Issue #3897: Splitted input test files for WhitespaceAfterCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap.java

Issue #3929: Modified OperatorWrapCheckTest.java and moved its input files to operatorwrap subdirectory

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java

Issue #3685: Refactoring for RightCurlyCheck.java

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadWhitespaceAround.java

Issue #3954 Split and orginise inputs by MethodParamPad Test.

Issue #3954: MethodParamPadCheck input files split

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength.java

Issue #3999: Split and Organize Checkstyle inputs by Test for FileLength

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPad.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPadDefaultConfig.java

Resolved Issue #3970. This pull request is for splitting the input tests for EmptyForInitializerPadTest

Issue #3970: Split Inputs test for EmptyInitializerPadTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount3.java

https://github.com/checkstyle/checkstyle/issues/4014

Issue #4014: Split and Organize Checkstyle inputs by Test for MethodCount

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputEmptyLineSeparatorFormerException.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputPrePreviousLineEmptiness.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorFormerException.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorHeader.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLines.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleFieldsInClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleImportEmptyClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPrePreviousLineEmptiness.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/package-info/test1/package-info.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/package-info/test2/package-info.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/package-info/test3/package-info.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/package-info/test4/package-info.java

I fixed the issue #3985. It passed the mvn clean verify.

Issue #3985: Moved all input files to new folder emptylineseparator

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/anoninnerlength/InputAnonInnerLength.java

This pull request is for splitting and organizing the test inputs for AnonInnerLength for fixing Issue #3986

Issue #3986: Splitting inputs by Test for AnonInnerLength

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/NoLineWrapTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapBad.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapGood.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputNoLineWrapBad.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputNoLineWrapGood.java
src/xdocs/config_whitespace.xml

Issue #3892: Added TokenTypes.STATIC_IMPORT in NoLineWrapCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java

Issue #3491: DetailAst class unclear logic in addChild method

Issue #3491: DetailAst class unclear logic in addChild method 

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java

Issue #4055: Perform refactoring of AnnotationLocationCheck to increase code readability

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableFalsePositives.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableLeavingSlistToken.java

#3172 
Diff reports:
http://www.luolc.com/checkstyle-diff-report/issue3172/
~~No diff on regression.~~
BTW, there are two UTs for false positives but why?
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java#L122
https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java#L226

Issue #3172: Regression false-positive FinalLocalVariable

---

README.md

Issue #4093: fix broken link in README.md

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputCorrectSummaryJavaDoc.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputIncorrectSummaryJavaDoc.java
src/xdocs/config_javadoc.xml

Issue #3908: SummaryJavadoc need special processing of inheritDoc tag

---

.github/PULL_REQUEST_TEMPLATE.md

Issue #4098: Grammar mistakes in PULL_REQUEST_TEMPLATE.md

---

README.md

Double-checked to make sure that all links work over HTTPS.

minor: Use HTTPS links and the SVG Travis badge

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingComma.java

Issue #3891 Move test resource of ArrayTrailingCommaCheckTest to new location

Issue #3891: Split and Organize Checkstyle inputs by Test for ArrayTrailingComma

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
src/xdocs/config_metrics.xml

https://github.com/checkstyle/checkstyle/issues/3234

Issue #3234: ClassDataAbstractionCoupling : Add a regex attribut

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameFormerFalsePositive.java

Issue #4106: organized Checkstyle inputs by Test for AbstractClassName

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java

Issue #3616: Fix/suppress TC "Deprecated member is still used" errors

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyOption.java
src/xdocs/property_types.xml

Issue #4085: Extend documentation for RightCurlyOption.SAME

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidinlineconditionals/InputAvoidInlineConditionals.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidinlineconditionals/InputWhitespace.java

Issue #3891 Move test resource of AvoidInlineConditionals to new location

Issue #3891: Split and Organize Checkstyle inputs by Test for AvoidInlineConditionals

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneOrSingleline.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyTryResource.java

#4091 
Report: https://vladlis.github.io/4091/

Issue #4091: False negative on multiblock tokens with ALONE_OR_SINGLINE option

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputEmptyCase.java
src/xdocs/checks.xml
src/xdocs/config_blocks.xml

Issue #3839 : Added special checks in EmptyBlockCheck.java for LITERAL_CASE to detect related empty blocks.

Issue #3839 : EmptyBlock: can't get violation from case token

---

.github/CONTRIBUTING.md
config/checkstyle_non_main_files_checks.xml
config/checkstyle_non_main_files_suppressions.xml
pom.xml

Issue #3072: Add NewlineAtEndOfFile config for test and it inputs

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameInnerClass.java

//I did every step again to make sure that I followed the requirements in Issue #3891 and PR rules
this is in response of the Issue #4144
changes including:
1. move the test files of LocalFinalVariableName to subdir and rename them.
2. change code in LocalFinalVariableNameCheckest to adapt the path.
Results:
1. All unit tests passed.
2. the result of `mvn clean verify` -> `Tests run: 103, Failures: 0, Errors: 0, Skipped: 0`
I'm sorry for my closing of PR #4146 and #4147
For the first, I found my mistake and wanted to reduce your work, so I cloesd my pull request.
But for the second, I found that I named my branch incorrectly then I deleted it, but my request was closed automatically. 
I'm terriablly sorry for my violation of the PR rules and please forgive me.

Issue #4144: Modified LocalFinalVariableNameCheckest.java and move its tests to subdir

---

src/site/resources/css/site.css
src/xdocs/beginning_development.xml
src/xdocs/cmdline.xml.vm
src/xdocs/writingchecks.xml
src/xdocs/writingjavadocchecks.xml.vm

Issue #3902: Formatting of code chunks in html documentation (linewrap or scrolling)

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrder.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderAvoidDuplicatesInStaticFinalFields.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderForwardReference.java

Issue #4165 Move test resource of DeclarationOrderCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for DeclarationOrderCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/emptystatement/InputEmptyStatement.java

Issue #4165 Move test resource of EmptyStatementCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for EmptyStatementCheckTest

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java

Issue #3616: Fix TC violation - Field may be 'final'

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java

Issue #3616: Fix TC violation - Redundant suppression

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java

Issue #3616: Fix TC violation - Simplify stream API call chains

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLast.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastDefaultMethodsInInterface.java

Issue #4165 Move test resource of DefaultComesLastCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for DefaultComesLastCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEquals.java

Issue #4165 Move test resource of CovariantEqualsCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for CovariantEqualsCheckTest

---

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java

Issue #2899: Explanations now present to differentiate between try-with-resources tokens in Javadoc

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitialization.java

Issue #4165 Move test resource of ExplicitInitializationCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for ExplicitInitializationCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough2.java

Issue #4165 Move test resource of FallThroughCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for FallThroughCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCode.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeEqualsParameter.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeNoEquals.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeSemantic.java

Issue #4165 Move test resource of EqualsHashCodeCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for EqualsHashCodeCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNull.java

Issue #4165 Move test resource of EqualsAvoidNullCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for EqualsAvoidNullCheckTest

---

config/checkstyle_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #4119
No new issues created yet.
Do we need issues for our config?
I will update CS 8 wiki for these google issues

Issue #4119: fixed verifying tokens being referenced in configs

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputSkipIfLastAndSharedWithCase.java
src/xdocs/config_coding.xml

Issue #4078: DefaultComesLast only if doesnt share case

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java

Fixed styling issue after 2 separate PRs were merged together.

minor: fixed styling issue on brace

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputAllowEmptyTypesAndNonEmptyClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputBraces.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputGenerics.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAround.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyLambdaExpressions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundArrayInitialization.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundCatch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundDoWhile.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundDoubleBraceInitialization.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundEmptyTypesAndCycles.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundKeywordsAndOperators.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSimple.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitch.java

This pull request related to issue #3898

Issue #3898: Split and Organize Checkstyle inputs by Test for WhitespaceAround

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAssignedInsideAndOutsideSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAssignedMultipleTimes.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableEnhancedForLoopVariable.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFalsePositive.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFalsePositives.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableLeavingSlistToken.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableMultiCatch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableMultipleAndNestedConditions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameShadowing.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNativeMethods.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldLambdas.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldReceiver.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldReorder.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldStaticVisibility.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch2.java

Issue #4165 Move test resource of FinalLocalVariableCheckTest, HiddenFieldCheckTest, IllegalCatchCheckTest to new location

Issue #4165: Split and Organize Checkstyle inputs by Test for FinalLocalVariableCheckTest HiddenFieldCheckTest IllegalCatchCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java

Issue #3650: Expand missing testing for PropertyCacheFile tests

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputNoWhiteSpaceAfterFormerNpe.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfter.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterFormerNpe.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterMethodRef.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterSynchronized.java

This pull request solves the issue #3931 
Moved appropriate classes into new package. Maven clean verify completed successfully.

Issue #3931: Split and Organize Checkstyle inputs by Test for NoWhitespaceAfter

---

config/checkstyle_checks.xml
config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneOrSinglelineLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlySameLambda.java
src/xdocs/config_blocks.xml

Issue #3546: add lambda in a rightcurlycheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/staticvariablename/InputStaticVariableName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/staticvariablename/InputStaticVariableName1.java

PR for Issue #4208 -
InputStaticVariableName.java was moved to staticvariablename

Issue #4208: Split and Organize Checkstyle inputs by Test for StaticVariableName

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapBad.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapGood.java

Issue #3933: Split and Organize Checkstyle inputs by Test for NoLineWrap

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeVariations.java

Related to issue #4165 
Class: SuperFinalizeCheck

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: SuperFinalize

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountSwitches.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountVoid.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: ReturnCount

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThis15Extensions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLocalVars.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAnonymousEmpty.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisBraceAlone.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisMetodReferences.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisReceiver.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisSimple.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisStatic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingFalse.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingTrue.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: RequireThis

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentReceiver.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentWithUnchecked.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: ParameterAssignment

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneInnerAndWithArguments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperClonePlainAndSubclasses.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: SuperClone

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEquality.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: StringLiteralEquality

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/InputSimplifyBooleanReturn.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: SimplifyBooleanReturn

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: SimplifyBooleanExpression

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistance.java

This PR related to issue #4165
Split and organized tests for class VariableDeclarationUsageDistanceCheck

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: VariableDeclarationUsageDistanceCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParentheses15Extensions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java

This PR related to issue #4165

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: UnnecessaryParentheses

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/overloadmethoddeclaration/InputOverloadMethodsDeclarationOrder.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: OverloadMethodsDeclarationOrder

---

src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/Input15Extensions.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputComplexityOverflow.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputComplexitySwitchBlocks.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputJavaNCSS.java

Issue #56 
for Pull #4234 
Split input files location for MainTest and check.metrics.* tests.
CI on Pull #4234 fails because MainTest shows violation on input files for metrics that has more that 170 lines.

Issue #56: fix MainTest input files

---

config/checkstyle_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeMethodRef.java
src/xdocs/config_whitespace.xml

This PR related to issue #3949 
What was done:
1) added new tokens into config
2) added new test class into /nowhitespacebefore package
3) added new test method in NoWhitespaceBeforeCheckTest.java to test correct behavior.

Issue #3949: NoWhitespaceBefore: add support for method reference operator

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineMultiline.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineSingleLine.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: OneStatementPerLine

---

config/checkstyle_checks.xml
config/suppressions.xml
src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java
src/it/java/com/google/checkstyle/test/base/BaseIndentationCheckSupport.java
src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractDeclarationCollector.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java

ReturnCount: enforce max=1 over checkstyle code (part 1)

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerFallThrough.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerHasFinalizer.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: NoFinalizer

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingComma.java
src/xdocs/config_coding.xml

#1509
Reports look good: https://vladlis.github.io/1509/

Issue #1509:  Extra comma is required in multi-line array value

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
src/xdocs/config_misc.xml

Issue #4250: Fix new TeamCity violations (part1)

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedifdepth/InputNestedIfDepth.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: NestedIfDepth

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedtrydepth/InputNestedTryDepth.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: NestedTryDepth

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableBothForLoops.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: ModifiedControlVariable

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepth.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: NestedForDepth

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplevariabledeclarations/InputMultipleVariableDeclarations.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: MultipleVariableDeclarations

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtor.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: MissingCtor

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputIntMethodAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: MagicNumber

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: MissingSwitchDefault

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: MultipleStringLiterals

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XmlUtil.java

ReturnCount: enforce max=1 over checkstyle code (part 2)

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalType.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeAbstractClassNames.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeGregorianCalendar.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeMemberModifiers.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeStarImports.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeStaticImports.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: IllegalType

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noclone/InputNoClone.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: NoClone

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentLambdaExpressions.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: InnerAssignment

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceErrors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorNoErrors.java

Issue #4080: Split and Organize Checkstyle inputs by Test for SingleSpaceSeparator

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens.java

Issue #4165: Moved resource class to new package /illegaltokentext

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterNameSimple.java

Issue #4136: Split and Organize Checkstyle inputs by Test for CatchParameterName

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/InputClassTypeParameterName.java

Issue #4137: Split and Organize Checkstyle inputs by Test for ClassTypeParameterName

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBraces.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesConditional.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesEmptyDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesNoBodyLoops.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineStatements.java

Issue #4220: Split and Organize Checkstyle inputs by Test in the blocks package: NeedBraces

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2.java

Issue #4220: Split and Organize Checkstyle inputs by Test in the blocks package: EmptyBlock

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AuditEvent.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FilterSet.java
src/main/java/com/puppycrawl/tools/checkstyle/api/LineColumn.java
src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/CsvFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressElement.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java

#3496 
Reports for MissingDeprecatedCheck and SuppressWarningsCheck show no regression:
https://vladlis.github.io/3496/part5/1/index.html

Issue #3496: Enforce ReturnCount max=1 (part 5)

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputComplexity.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputComplexityOverflow.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputNPathComplexity.java
src/xdocs/config_metrics.xml

Issue #56 .
Continuation of Pull #3785.

Issue #56: fix NPathComplexityCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername/InputInterfaceTypeParameterName.java

Issue #4142: Split and Organize Checkstyle inputs by Test for InterfaceTypeParameterName

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckTest.java
src/xdocs/config_coding.xml

Issue #2399: New option 'onlyObjectReferences' for ExplicitInitializationCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameEqualClassName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameExtra.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameOverridenMethods.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameSimple.java

Issue #4158: Split and Organize Checkstyle inputs by Test for MethodName

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameExtended.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameInner.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameSimple.java

Issue #4151: Split and Organize Checkstyle inputs by Test for MemberName

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/packagename/InputPackageNameSimple.java

Issue #4172: Split and Organize Checkstyle inputs by Test for PackageName

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java

minor: Refactored getDetails method of RightCurlyCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: IllegalToken

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrows.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsIgnoreOverriddenMethods.java

Issue #4165: Split and Organize Checkstyle inputs by Test for checks in coding package: IllegalThrows

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassClassWithPrivateCtorWithNestedExtendingClass.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassClassWithPrivateCtorWithNestedExtendingClassWithoutPackage.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: FinalClass

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/package-info.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputOneTopLevelEnum.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputOneTopLevelInterface.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassClone.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassDeclarationOrder.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassNoPublic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelEnum.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelEnum2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelInterface.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelInterface2.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: OneTopLevelClass

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCount.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: ThrowsCount

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableException.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableExceptionClassExtendsGenericClass.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: MutableException

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClass.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: InnerTypeLast

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/interfaceistype/InputInterfaceIsType.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: InterfaceIsType

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObject.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOther.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverride.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideFromObject.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideFromOther.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideNotOverride.java

Issue #4313: Split and Organize Checkstyle inputs by Test for checks in annotation package: MissingOverride

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/package-info.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation2.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/package-info.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/InputPackageAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation.java

Issue #4313: Split and Organize Checkstyle inputs by Test for checks in annotation package: PackageAnnotation

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtension.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionIgnoredAnnotations.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionMultipleAnnotations.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionNativeMethods.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionOverridableMethods.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionsLocalAnnotations.java

Issue #4314: Split and Organize Checkstyle inputs by Test for checks in design package: DesignForExtension

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsCompact.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsConstants.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsExpanded.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsHolder.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsSingle.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsValuePair.java

Issue #4313: Split and Organize Checkstyle inputs by Test for checks in annotation package: SuppressWarnings

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyle.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleCustomAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleParams.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingComma.java

Issue #4313: Split and Organize Checkstyle inputs by Test for checks in annotation package: AnnotationUseStyle

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameTryResources.java
src/xdocs/config_naming.xml

Issue: #3348 fixed
Also, since I needed to add extra test cases for LocalFinalVariableNameCheck. Diff report: https://nimfadora.github.io/

Issue #3348: add validation of try with resources to the LocalFinalVariableName check

---

config/checkstyle_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterBadMethodRef.java
src/xdocs/config_whitespace.xml

Issue #3950: NoWhitespaceAfter: add support for method reference operator

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/InputAnnotationLocation1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationCorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationCustomAnnotationsDeclared.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationDeprecatedAndCustom.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationEmpty.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationWithoutAnnotations.java

#4313 
While running receiving the same issue as here:
https://github.com/policeman-tools/forbidden-apis/issues/108
@MEZk 
How can I fix this in this case?
Thanks

Issue #4313: Split and Organize Checkstyle inputs by Test for checks in annotation package: AnnotationLocation

---

src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties

I got this error in some code and felt the need to fix the grammar :)

minor: Significantly improve grammar of variable.declaration.usage.distance.extend property

---

.travis.yml

#4316 
Base on knowledge of https://github.com/travis-ci/travis-ci/issues/4042

infra: attempt to resolve #4316 by jdk upgrade

---

.travis.yml

Issue #4316: disable ConfigurationLoaderTest as experiment

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/InputImportControl_Blacklist.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_blacklist.xml
src/xdocs/config_imports.xml

https://github.com/checkstyle/checkstyle/issues/3451

Issue #3451: ImportControl: blacklist mode

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java

Issue #4165: Made refactoring of OneStatementPerLine tests to meet the requirements

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLambdaParameters.java

Issue #4207 : Fixed false positives from RequireThis for lambdas

Issue #4207: False positive for lambda parameters from RequireThis

---

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4
src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParseTreeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/ParseTreeBuilder.java
src/test/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/javadocTags/InputLinkToPackage.txt

#4349: Digits shall be allowed in Package names

Issue #4349: Digits shall be allowed in Package names

---

config/catalog.xml
config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/MismatchStrategy.java
src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_3.dtd
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_strategy-on-mismatch_four.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_strategy-on-mismatch_one.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_strategy-on-mismatch_three.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_strategy-on-mismatch_two.xml
src/xdocs/config_imports.xml

https://github.com/checkstyle/checkstyle/issues/4274

Issue #4274: ImportControl: strategyOnMismatch property

---

pom.xml
wercker.yml

Issue #4387 
When I tested this locally I didn't get any exception and I'm not sure why. Wercker is the same.

Issue #4387: added sevntu no error test

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java

Issue #4437
This PR moves all inputs of IllegalImportCheckTest of the imports package to a new subdirectory 'illegalimport'.

Issue #4437: Modified IllegalImportCheckTest.java and moved its input files to the illegalimport subdirectory

---

config/checkstyle_sevntu_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java
src/test/resources/com/puppycrawl/tools/checkstyle/packageobjectfactory/bar/FooCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/packageobjectfactory/foo/FooCheck.java

Issue #4414: Simple name conflict of Checks from thirdparty ch..

---

pom.xml

Issue #4414: remove allowance of PackageObjectFactory coverage to be non 100%

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutils/InputCheckUtilsTest.java

Issue #4395 
increased mutation threshold for pitest-checkstyle-utils by 18%
threshold: 67%
execution time: 01:54 min
[pitest report before changes for class](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle.utils/CheckUtils.java.html)
[pitest report before changes for package](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle.utils/index.html)

Issue #4395: increase coverage of pitest-checkstyle-utils profile to 67%

---

config/ant-phase-verify.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/config-non-existing-classname-ignore.xml
src/xdocs/anttask.xml.vm
src/xdocs/cmdline.xml.vm

Issue #3566: adding and turning off omitIgnoredModules

---

pom.xml

Test to fix Issue #4316 
Sources for fix:
https://github.com/travis-ci/travis-ci/issues/5631#issuecomment-188812771
https://github.com/travis-ci/travis-ci/issues/6330#issuecomment-234985707
https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi
https://issues.apache.org/jira/browse/STORM-1436

config: added heap size to surefire to fix travis failures

---

config/pmd-main.xml
config/pmd-test.xml
config/pmd.xml
pom.xml

Issue #877 
enable test checks in pmd;
create separate profiles for production and test code;
suppress all violations for test code for now;

Issue #877: enable test checks for pmd, create separate configs and suppress all violations

---

config/pmd-test.xml
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/ScopeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ClassImportRuleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportRuleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

Issue #4497 
fixed all violations of rule specified
[pmd report](https://nimfadora.github.io/pmd-pr/pmd4497.html)

Issue #4497: fix pmd violations for CheckstyleCustomShortVariable

---

config/pmd-test.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

Issue #4492 
fixed all violations of rule specified
[pmd report](https://nimfadora.github.io/pmd-pr/pmd4492.html)

Issue #4492: fix pmd violations for CommentDefaultAccessModifier

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java

Issue #4353: refactoring: remove 'final' modifier from all arguments of method/c-tor at ImportControlCheck and around

---

config/pmd-test.xml
src/test/java/com/puppycrawl/tools/checkstyle/BriefUtLogger.java

Issue #4488 
fixed all violations of rule specified
[pmd report](https://nimfadora.github.io/pmd-pr/pmd4488.html)

Issue #4488: fix pmd violations for UselessOverridingMethod

---

src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/FileSetCheckLifecycleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java

Issue #4516
fix second bunch of pmd violations for JUnitAssertionsShouldIncludeMessage

Issue #4516: fix second bunch of pmd violations for JUnitAssertionsShouldIncludeMessage

---

config/pmd-main.xml
config/pmd-test.xml
config/pmd.xml
src/it/java/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/NonEmptyAtclauseDescriptionTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJava14LexerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

Issue #4500
fix first part of tentative pmd violations

Issue #4500: fix first part of tentative pmd violations

---

src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java

Issue #3110 
The hardcoded messages in DefaultLogger have been removed and i18n support for those messages have been added.
EDIT: More PRs to be added for other files.

Issue #3110: Modified DefaultLogger to remove hardcoded messages and to support i18n for the messages

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ClassDefHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/PrimordialHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCustomAnnotation.java

Issue #3134: Add AnnotationDefHandler for custom annotations

---

.travis.yml

Issue #4316: remove excludes from localized tests as they become stable

---

src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/InputImportControlOne.xml
src/test/resources/com/puppycrawl/tools/checkstyle/InputImportControlOneRegExp.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportNestedClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderBug.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_WildcardUnspecified.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports.java

Issue #4437 
This PR arranges the remaining files in the 'imports' directory because they are used in different files. The rearrangement also caused a few changes to made to certain input and test files.

Issue #4437: Arranged the remaining files from 'imports' directory and modified the test and input files based on the rearrangement

---

pom.xml

Issue #4342 
```
[INFO] Building checkstyle 8.0-SNAPSHOT
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (default-cli) @ checkstyle ---
Downloading: https://oss.sonatype.org/content/repositories/codehaus-snapshots/net/sourceforge/pmd/pmd-java/5.7.0/pmd-java-5.7.0.pom
Downloading: http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2/net/sourceforge/pmd/pmd-java/5.7.0/pmd-java-5.7.0.pom
Downloading: http://repo.maven.apache.org/maven2/net/sourceforge/pmd/pmd-java/5.7.0/pmd-java-5.7.0.pom
Downloaded: http://repo.maven.apache.org/maven2/net/sourceforge/pmd/pmd-java/5.7.0/pmd-java-5.7.0.pom (7 KB at 18.1 KB/sec)
Downloading: …
```

Issue #4342: fix pmd dependencies which prevented it from using the latest version

---

config/pmd-main.xml
config/pmd-test.xml
config/suppressions.xml
pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java

Issue #4500
Almost all violations were fixed, 7 cases left. These tests need to be rewritten as I don't see how can I check something here. 
[report on checks left](https://nimfadora.github.io/pmd-pr/pmd877.html)

Issue #4500: fix second part of JUnitTestsShouldIncludeAssert violations

---

config/pmd-test.xml
config/suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java

Issue #877: fix third part of JUnitTestsShouldIncludeAssert violations

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config.xml
src/xdocs/config_annotation.xml
src/xdocs/config_blocks.xml
src/xdocs/config_coding.xml
src/xdocs/config_design.xml
src/xdocs/config_filefilters.xml
src/xdocs/config_filters.xml
src/xdocs/config_header.xml
src/xdocs/config_imports.xml
src/xdocs/config_javadoc.xml
src/xdocs/config_metrics.xml
src/xdocs/config_misc.xml
src/xdocs/config_modifier.xml
src/xdocs/config_naming.xml
src/xdocs/config_regexp.xml
src/xdocs/config_sizes.xml
src/xdocs/config_whitespace.xml

Issue #4475
This is the final PR for the issue.

Issue #4475: added since version to all module descriptions

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java

Issue #3110: fix localization for TranslationCheckTest and IllegalInstantiationCheckTest

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/packageobjectfactory/bar/FooCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/packageobjectfactory/foo/FooCheck.java
wercker.yml

Issue #605
`AbstractCheckTest.java` required one of it's tests to change.

Issue #605: made get acceptable and required tokens abstract

---

wercker.yml

Issue #4582: restored wercker checkstyle's sevntu

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexity.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexityNPE.java

Issue #4575 
This PR moves all inputs of BooleanExpressionComplexityCheckTest of the metrics package to a new subdirectory 'booleanexpressioncomplexity'.

Issue #4575: Modified BooleanExpressionComplexityCheckTest.java and moved its input files to the 'booleanexpressioncomplexity' subdirectory

---

wercker.yml

Issue #4582: restored wercker hibernate search

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/CheckerStub.java
src/test/java/com/puppycrawl/tools/checkstyle/TestRootModuleChecker.java
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java
src/test/resources/com/puppycrawl/tools/checkstyle/config-custom-checker-root-module.xml
src/test/resources/com/puppycrawl/tools/checkstyle/config-custom-root-module.xml
src/test/resources/com/puppycrawl/tools/checkstyle/config-multi-thread-mode.xml

Issue #4400
[pitest report before changes](https://nimfadora.github.io/issue4400.html)
increased mutation threshold for pitest-checkstyle-common profile by 3%
current threshold: 95%
execution time: 13:01 min

Issue #4400: increase coverage of pitest-checkstyle-common profile to 95%

---

config/pmd-test.xml
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java

Issue #877: fix TreeWalkerTest JUnitTestsShouldIncludeAssert violations

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSS.java

Issue #4575
This PR moves all inputs of JavaNCSSCheckTest of the metrics package to a new subdirectory 'javancss'.

Issue #4575: Modified JavaNCSSCheckTest.java and moved its input files to the javancss subdirectory

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexity.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexitySwitchBlocks.java

Issue #4575
This PR moves all inputs of CyclomaticComplexityCheckTest of the metrics package to a new subdirectory 'cyclomaticcomplexity'.

Issue #4575: Modified CyclomaticComplexityCheckTest.java and moved its input files to the cyclomaticcomplexity subdirectory

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/descendanttoken/InputDescendantTokenEmptyStatement.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/descendanttoken/InputDescendantTokenIllegalTokens.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/descendanttoken/InputDescendantTokenMissingSwitchDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/descendanttoken/InputDescendantTokenReturnFromCatch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/descendanttoken/InputDescendantTokenReturnFromFinally.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/descendanttoken/InputDescendantTokenStringLiteralEquality.java

Issue #4587: Moved resources for descendant token check test

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/FileSetCheckLifecycleTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/fileset/InputFileSetIllegalTokens.java

Issue #4587: Moved resources for FileSet check test

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexity.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityOverflow.java

Issue #4575
This PR moves all inputs of NPathComplexityCheckTest of the metrics package to a new subdirectory 'npathcomplexity'.

Issue #4575: Modified NPathComplexityCheckTest.java and moved its input files to the npathcomplexity subdirectory

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java

Issue #3574: moved DetailAST log to AbstractCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/finalparameters/InputFinalParameters.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/finalparameters/InputFinalParametersPrimitiveTypes.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/finalparameters/InputFinalParametersReceiver.java

Issue #4587: Moved resources for FinalParameters check test

---

config/suppressions.xml
pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java

Issue #4400
increased mutation threshold for pitest-checkstyle-common by 3%
threshold: 98%
execution time: 08:41 min
[pitest report before changes for package](https://nimfadora.github.io/issue4400.html)

Issue #4400: increase coverage of pitest-checkstyle-common profile to 98%

---

src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileSetCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/FileSetCheckLifecycleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

https://github.com/checkstyle/checkstyle/issues/3034

Issue #3034: FileText should not extends AbstractList

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/todocomment/InputTodoCommentSimple.java

Issue #4587: Moved all necessary resource files for TodoComment

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/uncommentedmain/InputUncommentedMain.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/uncommentedmain/InputUncommentedMain2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/uncommentedmain/InputUncommentedMain3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/uncommentedmain/InputUncommentedMain4.java

Issue #4587: Moved all resources for UncommentedMain check

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/upperell/InputUpperEllSemantic.java

Issue #4587: Moved all resources for UpperEll check

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/trailingcomment/InputTrailingComment.java

Issue #4587: Moved all resources for TrailingComment check

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java

Issue #4400
increased mutation threshold for pitest-checkstyle-common by 2%
threshold: 100%

Issue #4400: increase coverage of pitest-checkstyle-common profile to 100%

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java

Issue #4395
increased mutation threshold for pitest-checkstyle-common by 1%
threshold: 100%
execution time: 02:40 min

Issue #4395: increase coverage of pitest-checkstyle-utils profile to 100%

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstracttypeaware/InputAbstractTypeAwareLoadErrors.java

#4586 
I will delete all useless files at the end

Issue #4586: Moved resources for AbstractTypeAware check test

---

src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java

Issue #3110
The hardcoded messages in Main have been removed and i18n support for those messages have been added.

Issue #3110: Modified Main to remove hardcoded messages and to support i18n for the messages

---

.ci/travis/travis.sh
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java

Issue #4664
Fixed test and removed nondex exclude.

Issue #4664: removed constructor search in ConfigurationLoaderTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationGuavaFalsePositive.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationOffset3.java

Issue #4586: Moved all resources for JavadocTagContinuationIndentationCheckTest

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/xdocs/config_imports.xml

Issue #3578: Removed 'url' property from ImportControl

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescription.java

Issue #4586: Moved all resources for NonEmptyAtclauseDescription

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/singlelinejavadoc/InputSingleLineJavadoc.java

Issue #4586: Moved all resources for SingleLineJavadocChecktest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag2.java

Issue #4586: Moved all resources for WriteTagCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocCorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocNoPeriod.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriod.java

Issue #4586: Moved all resources for SummaryJavadocCheckTest

---

src/test/resources/com/puppycrawl/tools/checkstyle/config-custom-root-module.xml
src/test/resources/com/puppycrawl/tools/checkstyle/package-info.java

#4588 
As I've mentioned in #4588 I've removed unused resource files

Issue #4588: Removed unused resource files from root package

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java

Issue #4694: UniquePropertiesCheck.getLineNumber should be private

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/InputDefaultConfig.java
src/test/resources/com/puppycrawl/tools/checkstyle/internal/InputAllChecksDefaultConfig.java
src/test/resources/com/puppycrawl/tools/checkstyle/internal/InputAllChecksImport-control_complete.xml

Issue #4588: Moved resources for AllChecksTest

---

config/intellij-idea-inspections.xml
src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/FileTabCharacterTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/ParameterNameTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #4711: fixed code style idea violations

---

config/intellij-idea-inspections.xml

Issue #3301: update suppress comment

---

config/intellij-idea-inspections.xml
src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/MethodTypeParameterNameTest.java
src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/FileContentsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java

Issue #4708
fixed part of [idea violations](https://nimfadora.github.io/idea/suppressed_2_part.html)
added some violations to myAllowedSuppressions:
```
<option value="AssignmentToStaticFieldFromInstanceMethod" />
<option value="DeprecatedIsStillUsed" />
<option value="NoopMethodInAbstractClass" />
<option value="UseOfSystemOutOrSystemErr" />
```
they should be commented somehow

Issue #4708: fixed part of idea violations

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java

Issue #4726 
violation fixes included:
```
CollectionsMustHaveInitialCapacity
ConstantConditions
DuplicatePropertyInspection
HardcodedFileSeparators
HardcodedLineSeparators
LengthOneStringsInConcatenation
MagicConstant
NullableProblems
ObjectAllocationInLoop
ObjectEquality
ReturnNull
SuspiciousArrayCast
```

Issue #4726: fixed easy cases of the fifth part of idea violations

---

src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java

Issue #4394
last mutation is fixed, task is done

Issue #4394: fix last mutation

---

config/intellij-idea-inspections.xml

Issue #4713
suppress violations:
```
AbstractClassExtendsConcreteClass
BooleanMethodIsAlwaysInverted
BooleanVariableAlwaysNegated
BreakStatement
ContinueStatement
CyclicClassDependency
CyclicPackageDependency
DuplicateStringLiteralInspection
EmptyMethod
ErrorRethrown
HardCodedStringLiteral
IfMayBeConditional
LawOfDemeter
MagicCharacter
NonThreadSafeLazyInitialization
PublicInnerClass
SameParameterValue
SameReturnValue
SingleClassImport
StaticImport
StringConcatenation
```

Issue #4713: add suppressions

---

config/intellij-idea-inspections.xml

Issue #4724 
add suppressions on violations:
```
AutoCloseableResource
ClassHasNoToStringMethod
CloneableClassInSecureContext
DeserializableClassInSecureContext
DesignForExtension
JUnitTestNG
LongLine
NonStaticInnerClassInSecureContext
ParameterHidingMemberVariable
SerializableClassInSecureContext
SpellCheckingInspection
```

Issue #4724: add suppressions

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount6.java

Issue #4556
This is temporary fix. Full fix can be seen at https://github.com/rnveach/checkstyle/commits/issue_4539 .

Issue #4556: fixed MethodCountCheck exception for partial tokens

---

wercker.yml

Issue #4363: add vavr library to our regression testing

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java

Issue #4722
fix SimplifiableIfStatement and MissingPackageInfo  violation

Issue #4722: fix SimplifiableIfStatement, MissingPackageInfo  violations

---

wercker.yml

config: restore sevntu on wercker

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment.java

Issue #4585: Moved resources for RegexpSinglelineJavaCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic.java

Issue #4585: Moved resources for RexepMultiline

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic.java

Issue #4585: Moved resources for RegexpSingleline

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractIllegalCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractIllegalMethodCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractNestedDepthCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractComplexityCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/grammars/CommentListener.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJavaTokenTypesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParseTreeTest.java

Issue #4723: fix all cases from the fourth part of idea violations

---

config/intellij-idea-inspections.xml
src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java
src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
src/main/java/com/puppycrawl/tools/checkstyle/api/CheckstyleException.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/FileContentsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/FileSetCheckLifecycleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

Issue #4713
fixed violations remained:
NestedTryStatement
ProtectedField
ProtectedInnerClass
AssignmentToForLoopParameter
ForLoopWithMissingComponent
CheckedExceptionClass
ExtendsConcreteCollection
StaticVariableInitialization
StaticVariableUninitializedUse

Issue #4713: fix all violations from the third part of idea violations

---

config/intellij-idea-inspections.xml

Issue #4707
fixed violations:
```
FeatureEnvy
InstanceofInterfaces
ParameterOfConcreteClass
PublicMethodNotExposedInInterface
TypeMayBeWeakened
```

Issue #4707: remained violations for the ninth part of idea violations

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/AuditEventFormatter.java
src/main/java/com/puppycrawl/tools/checkstyle/ModuleFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyResolver.java
src/main/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/api/Configurable.java
src/main/java/com/puppycrawl/tools/checkstyle/api/Contextualizable.java
src/main/java/com/puppycrawl/tools/checkstyle/api/ExternalResourceHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/api/Filter.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/MatchSuppressor.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/IntFilter.java

Issue #3435
add @FunctionalInterface annotations to interfaces:
AuditEventFormatter
BeforeExecutionFileFilter
Configurable
Contextualizable
ExternalResourceHolder
Filter
IntFilter
MatchSuppressor
ModuleFactory
PropertyResolver

Issue #3435: introduce InterfaceMayBeFunctional violation, add annotations

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java

Issue #4401 
[pitest report before changes](https://nimfadora.github.io/issue4401.html)

Issue #4401: increase coverage of pitest-checks-header profile to 100%

---

config/intellij-idea-inspections.xml

Issue #4801: add suppressions on the eleventh part of IDEA violations

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java

Issue #4722
fixed EqualsReplaceableByObjectsCall idea violation

Issue #4722: fix EqualsReplaceableByObjectsCall idea violation

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java

Issue #4726: fix MethodMayBeStatic idea violations

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java

Issue #4722
fix all HtmlTagCanBeJavadocTag idea violations except those on TokenTypes, which will be addressed in #4805

Issue #4722: fix HtmlTagCanBeJavadocTag idea violation

---

config/intellij-idea-inspections.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtils.java
src/site/resources/js/anchors.js
src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java

Issue #4725
fix includes:
```
GjsLint
JSHint
JSLint
TsLint
Eslint
Jscs
InnerHTMLJS
Duplicates
```

Issue #4725: fix all violations from the tenth part of idea violations

---

.ci/check-only-javadoc-error.sh

Build time is risen to 10 minutes 41 seconds which is still less then on Travis.

config: add more projects to Distelli CI

---

config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java

https://github.com/checkstyle/checkstyle/issues/4419

Issue #4419: Add token type to LocalizedMessage

---

config/pmd-main.xml
config/suppressions.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/DefinitionsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilityTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilsTest.java

Issue #4399
[report before changes](https://nimfadora.github.io/issue4399.html)
increased coverage of pitest-checkstyle-main by 7%
95/95 mutations are killed
execution time: 05:01

Issue #4399: increase coverage of pitest-checkstyle main profile to 100%

---

src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpInPkgTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/FilterSetTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJava14LexerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java

Issue #4808: fix second 200 AssertsWithoutMessages violations

---

src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/ScopeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportRuleTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java

Issue #4808: fix 300 more AssertsWithoutMessages violations

---

src/test/java/com/puppycrawl/tools/checkstyle/BaseFileSetCheckTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/AllBlockCommentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/AllSinglelineCommentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentationTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java

Issue #4592
This PR extends the tests (that are left to be changed) from AbstractModuleTestSupport and AbstractPathTestSupport.

Issue #4592: Added more tests which extend AbstractPathTestSupport and AbstractModuleTestSupport

---

wercker.yml

Issue #4829: add NoErrorTest for sevntu project to wercker

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinter.java
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/AbstractTreeTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java

Issue #4707: fix BooleanParameter idea violations

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount7.java
src/xdocs/checks.xml
src/xdocs/config_sizes.xml

Issue #4539: fixed MethodCount from counting methods in wrong definition

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAnonymousClass.java
wercker.yml

Issue #4727: fixed FinalLocalVariable scanning anonymous classes

---

pom.xml

@romani we forgot to restore sevntu after PR #4755 .

config: remove skipping sevntu checks

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationValidTryResourcesIndent.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputTryResourcesNotStrict.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputTryWithResourcesStrict.java

Issue #3131: Add support for try with resources

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisCaseGroup.java

Issue #4777: fixed RequireThisCheck with NPE on case group

---

config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

https://github.com/checkstyle/checkstyle/issues/4843

Issue #4843: TreeWalkerFilter needs to be added to ModuleReflectionUtils

---

config/intellij-idea-inspections.xml
src/test/java/com/puppycrawl/tools/checkstyle/AbstractTreeTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #4592
This PR extends the last few remaining tests from AbstractModuleTestSupport.

Issue #4592: Added the last few tests which extend AbstractModuleTestSupport

---

wercker.yml

Issue #3573: remove patch workaround for wercker

---

config/checkstyle_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
src/xdocs/config_blocks.xml

Issue #3671
I will make required changes in 3rd parties when wercker fails.

Issue #3671: removed maxLineLength in LeftCurlyCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java

Issue #4857: hot fix for BooleanParameter idea violation

---

config/import-control.xml
config/pmd.xml
config/suppressions.xml
pom.xml
shippable.yml
src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/package-info.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/InputXpathAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/InputXpathEnum.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/InputXpathInterface.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/InputXpathMapperAst.java

https://github.com/checkstyle/checkstyle/issues/4369

Issue #4369: Investigate how to map XPath expressions onto AST nodes

---

src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java

Issue #4709: fix avoid boolean parameters for public methods

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

Issue #4801
PR not for merge
violations included:
```
UnusedReturnValue
unused
TooBroadCatch
UncheckedExceptionClass
UnusedProperty
TodoComment
ThisEscapedInConstructor
StringTokenizer
VarargParameter
SystemExit
UseOfPropertiesAsHashtable
UnnecessaryFinalOnLocalVariableOrParameter
XmlPathReference
```

Issue #4801: fix some violations from the eleventh part of idea violations

---

src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifier.java

Issue #4801: partial resolve of WeakerAccess violations

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesLambdas.java
src/xdocs/config_coding.xml

Issue #4639: added suppport for lambdas in UnnecessaryParentheses

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java

Issue #4801: fix for violations from WeakerAccess inspection

---

config/intellij-idea-inspections.xml

Issue #4940: add suppressions on the twelfth part of idea violations

---

config/intellij-idea-inspections.xml
src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule521packagenames/PackageNameTest.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java

Issue #4940
All violations from the issue are fixed, except MultipleReturnPointsPerMethod, which will be addressed separately.

Issue #4940: fix twelfth part idea violations

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

Issue #4742
Identified AuditListeners and blocked classes from being picked up that don't have a default constructor.

Issue #4742: add 3rd party AuditListener and require default constructor

---

src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java

Issue #4931: removed powermock tests for AuditEventDefaultFormatter

---

src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java

Issue #4857: fix BooleanParameter idea violation for it package

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ArrayInitHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java

Issue #4940
some of the cases looks weird or complicated, please comment what we should do with equals methods, and comment those hard cases that left unfixed.

Issue #4940: fix MultipleReturnPointsPerMethod idea violation

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpInPkgTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlRegExpTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlTest.java

Issue #4863: fix ThisEscapedInConstructor idea violation for ImportControl class

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java

Issue #4966: Update `AnnotationUseStyleCheck` documentation to match actual defaults

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java
src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java

Issue #4805: fix HtmlTagCanBeJavadocTag in TokenTypes

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #4384: Remove strong, wildcard suppressions in configuration

---

config/import-control.xml
config/pmd-test.xml
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalkerAuditEvent.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/filters/xpathfilter/InputSuppressByXpath.java

https://github.com/checkstyle/checkstyle/issues/4422

Issue #4422: Implement XpathFilter

---

src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/package-info.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGenerator.java

https://github.com/checkstyle/checkstyle/issues/4901

Issue #4901: Implement xpath query generator

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPrePreviousLineIsEmpty.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPreviousLineEmptiness.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceAtStartOfTheLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceNested.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeAtStartOfTheLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadStartOfTheLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundStartOfTheLine.java

Issue #5003
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.whitespace/index.html)
coverage of pitest-checks-whitespace was increased by 3%
current threshold: 98

Issue #5003: increased coverage of pitest-checks-whitespace to 98%

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSimilarClassName.java

Issue #4947
I expect mutation to fail as I haven't added any new tests.
I will run regression for differences too.

Issue #4947: split illegalClassNames for IllegalType for short names

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/xdocs/config_javadoc.xml

Issue [https://github.com/checkstyle/checkstyle/issues/4987](https://github.com/checkstyle/checkstyle/issues/4987)

Issue #4987: fixed Javadoc for minLineCount property and xdocs

---

config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java

Issue #5027: remove use of javax.xml.bind.DatatypeConverter

---

pom.xml
shippable.yml
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClassRootClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableExceptionMultipleInputs.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountMwthodWithAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierIsStarImport.java

Issue #5007
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.design/index.html)
coverage of pitest-checks-design was increased by 2%
current threshold: 100

Issue #5007: increase coverage of pitest-checks-design to 100%

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #4384: fix JavadocParagraph violation in JavadocTokenTypes

---

pom.xml
shippable.yml

Issue #4394: exclude missed method to enforce check_survived

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations.java

Issue [https://github.com/checkstyle/checkstyle/issues/4557](https://github.com/checkstyle/checkstyle/issues/4557)
Fixed NPE and added tests.

Issue #4557: fixed NPE in NoWhitespaceAfterCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough.java

Issue #5037: handle synchronized blocks in FallThroughCheck

---

shippable.yml

Issue #4402: enforce check_survived on pitest-checks-annotation

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelCounterTest.java

Issue #4394: kill last mutation in pitest-checkstyle-api profile

---

src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/doclets/tokentypesdoclet/InputTokenTypesDocletCorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/doclets/tokentypesdoclet/InputTokenTypesDocletEmptyJavadoc.java
src/test/resources/com/puppycrawl/tools/checkstyle/doclets/tokentypesdoclet/InputTokenTypesDocletJavadocParseError.java
src/test/resources/com/puppycrawl/tools/checkstyle/doclets/tokentypesdoclet/InputTokenTypesDocletNotConstants.java

Issue #3891 
No inputs in main directory. https://github.com/rnveach/checkstyle/tree/issue_3891_2/src/test/resources/com/puppycrawl/tools/checkstyle/doclets
Simple package change.

Issue #3891: reorganized doclet package inputs

---

src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java

Issue #3891
Simple change for the utils package. I didn't see anything else wrong.

Issue #3891: added test support for CheckUtilsTest

---

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4

Issue #5040: Rename JavadocLexer rule to a more meaningful name

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java

https://github.com/checkstyle/checkstyle/issues/4998

Issue #4998: Add columnCharIndex field to LocalizedMessage

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/NoWhitespaceBeforeTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeEmptyForLoop.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeEmptyForLoop.java
src/xdocs/config_whitespace.xml
src/xdocs/google_style.xml

Issue #5058: handle empty for loop conditions in NoWhitespaceBefore

Issue #5058: handle empty for loop conditions in NoWhitespaceBefore

---

shippable.yml

Issue #3708: introduction of check_survived for coding, blocks, imports, whitespace profiles to avoid extra leaks

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations3.java
src/xdocs/config_whitespace.xml

Issue #3300: fixed ERROR whitespace after annotation

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundVarargs.java
src/xdocs/config_whitespace.xml

Fixed [https://github.com/checkstyle/checkstyle/issues/4157](https://github.com/checkstyle/checkstyle/issues/4157)

Issue #4157: added support for varargs.

---

config/checkstyle_checks.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfter.java
src/xdocs/config_whitespace.xml

Issue https://github.com/checkstyle/checkstyle/issues/4410. I continue [PR](https://github.com/checkstyle/checkstyle/issues/4412)

Issue #4410: whitespace after @

---

src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/DefinitionsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilityTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilsTest.java

Split off of https://github.com/checkstyle/checkstyle/pull/5112 .
Move assertions from util method to actual test methods.

minor: change constructor assertion to check

---

config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTabWidth.java

https://github.com/checkstyle/checkstyle/issues/4999

Issue #4999: XpathQueryGenerator should consider tabWith parameter

---

pom.xml
shippable.yml
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslationCheckFireErrors.properties
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslationCheckFireErrors_de.properties
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslation_de.txt
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/OutputTranslationCheckLinux.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/OutputTranslationCheckMacOS.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/OutputTranslationCheckWindows.xml

Issue #4675
coverage of pitest-checks-misc profile was increased by 4%
[report before changes](https://nimfadora.github.io/issue4675.html)
[regression report](https://nimfadora.github.io/diff4675/index.html)
current threshold: 100

Issue #4675: increase coverage of pitest-checks-misc to 100%

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupSeperated.java
src/xdocs/config_imports.xml

Issue #5065: No violation before or after changes for static import list

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileName.java
src/xdocs/config_coding.xml

Fixed [issue](https://github.com/checkstyle/checkstyle/issues/4425)

Issue #4425: fixed multidimensional array types

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java

Issue #4917
Wrapped `messageCollector` field with `ThreadLocal` so that it could be used from the separate threads

Issue #4917: Remove thread-unsafe context from the AbstractFileSetCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullNested.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullOnTheSameLine.java

Issue #5008
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.coding/index.html)
current threshold: 96%

Issue #5008: kill EqualsAvoidNull mutations

---

.ci/eclipse-compiler-javac.sh
config/intellij-idea-inspections.xml
pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertiesExpanderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelCounterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

Issue #5116: enabled eclipse compiler check in test code

---

config/pmd-test.xml
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/FilterUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/FilterUtilsTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsloader/InputSuppressionsLoaderXpathCorrect.xml
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsloader/InputSuppressionsLoaderXpathId.xml
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsloader/InputSuppressionsLoaderXpathInvalidFile.xml
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsloader/InputSuppressionsLoaderXpathNoCheckAndId.xml
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilter.java
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterIdAndQuery.xml
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterInvalidFile.xml
src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterNone.xml
src/test/resources/com/puppycrawl/tools/checkstyle/treewalker/InputTreeWalkerSuppressionXpathFilter.xml

https://github.com/checkstyle/checkstyle/issues/4421

Issue #4421: Support suppression-xpath element in SuppressionLoader

---

pom.xml
shippable.yml
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java

Issue #4675: reverting some coverage to make build stable

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java

Issue #4581 
This PR reorganizes the token methods in `GenericWhitespaceCheck`. After this PR is approved, similar changes will be made for other checks as well.

Issue #4581: Reorganize token methods in GenericWhitespaceCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java

Issue #5162: fixed sanitizing ampersand in xml file

---

README.md
appveyor.yml

Fixed issue #3870
Test commit will be removed after review.

Issue #3870: Added skip_commits section to appveyor.yml

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java

Issue #5114: Removed extra numeric offset

---

config/pmd-test.xml
config/suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypesTest.java

Issue #5186: Added a test to disallow changes in values of fields in 'JavadocTokenTypes'

Added tests in JavadocTokenTypesTest

---

src/xdocs/config_filters.xml

minor: Fix typo in SuppressionCommentFilter xdoc

---

wercker.yml

Issue #4714 , identified at https://github.com/checkstyle/checkstyle/pull/5194#issuecomment-338483328

Issue #4714: remove patch from wercker.yml for hibernate-search

---

src/xdocs/property_types.xml

Issue #5188: fix left curly nlow documentation

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityMultiDimensionalArray.java

Issue #5134: Could not reproduce. Added test to cover the case.

Issue #5134: Added test case for the issue

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java

Issue #5228
Moved configurations from class fields to local variables.

Issue #5228: moved class field configurations to local variables

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java

Issue #5228
Removed all temporary variables that are used to assign a property it's value.

Issue #5228: removed temporary variables property values

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
src/xdocs/config_design.xml

Issue #5249: Fix plural agreement in docs

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java

Issue #5263: clear fileset messages after process for multi-file run

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules/TestFileSetCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java

Issue #5264: clear filesets on checker destroy

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule51identifiernames/CatchParameterNameTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule521packagenames/PackageNameTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/MemberNameTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/ParameterNameTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/LocalVariableNameTest.java

Issue #5228
This fixes all violations found in IT. No suppressions were needed.

Issue #5228: fixed violations in it for test makeup

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java

Issue #5124
@romani I removed the cases out of https://github.com/checkstyle/checkstyle/pull/5267 that had no effect on regression to merge easier.
I also fixed the shippable error.

Issue #5124: removed usages of branchContains

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/FilterUtils.java

Issue #5283: resolve problem with covbertura on appveyor

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/FilterUtils.java

Issue #5283: resolve problem with pitest caused by previous commit

---

shippable.yml
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderEclipseStaticCaseSensitive.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderEclipseStaticRepetition.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderGetGroupNumber.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderNoGapBetweenStaticImports.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderRepetiton.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderSortStaticImportsAlphabetically.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticRepetition.java
src/xdocs/config_imports.xml

Issue #5176: adjacent static import groups ones became impossible in 8.3

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexponfilename/package-info.java

Issue #5278: fix NullPointerException when relative path is used to run CLI

---

src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java

Issue #5228 
Suppressing the final violation from the check in sevntu. See https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/306900583#L987 .

Issue #5228: suppressed dynamic message property in suppression test

---

src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java

Issue #4916 
Added ability to old style force loading of checks using forceLoad flag in Checker.

Issue #4916: Adding ability to force load

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceAnonymous.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceLabels.java

Issue #5124 
I split VariableDeclarationUsageDistanceCheck off from https://github.com/checkstyle/checkstyle/pull/5267 for easier review.
Fixed and added regression tests found at https://github.com/checkstyle/checkstyle/pull/5267#issuecomment-344800546 .
New regression to come.

Issue #5124: removed usages of branchContains for Variable Distance

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodTags.java

Issue #4701
No error for a misplaced javadoc tag
Regression test https://pbludov.github.io/issue-4701/JavadocMethod/

Issue #4701: No error for a misplaced javadoc tag

---

.ci/travis/travis.sh
.travis.yml
config/version-number-rules.xml
pom.xml

Issue #5208: use maven version plugin to report new versions for update

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocPosition.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocPositionWithSinglelineComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnAnnotationField.java
src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnMethod.java
src/xdocs/writingjavadocchecks.xml.vm

Issue #4169
Javadoc on annotation fields support

Issue #4169: Javadoc on annotation fields support

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config_javadoc.xml

Issue #5002
See question in issue at https://github.com/checkstyle/checkstyle/issues/5002#issuecomment-349429748

Issue #5002: added documentation for violateExecutionOnNonTightHtml

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalType.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepth.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineSingleLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentWithUnchecked.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java

Issue #5008
Increased coverage to 98%. Will generate regression for one check that was changed drastically.

Issue #5008: increased pitest of coding package

---

src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtility.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilityTest.java

Issue #5327
I will create regression and look for a more detailed UT for this change.

Issue #5327: fixed finding annotation name with comment embedded

---

shippable.yml

Issue #5008
Requested change from https://github.com/checkstyle/checkstyle/pull/5331#issuecomment-350275655

Issue #5008: removed checks at 100% mutation for coding package

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexity.java

Issue #5005
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/10/com.puppycrawl.tools.checkstyle.checks.metrics/index.html
198/202 (2 points shy of 99%, 4 of 100%)
I can't do any of the others. See main issue.

Issue #5005: increased pitest coverage for metrics package

---

pom.xml
shippable.yml
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityPackageName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityDefault.java

Issue #5005: increased pitest coverage for metrics package to 100%

---

pom.xml
shippable.yml
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfter.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations2.java

Issue #5003
Some proof of changes at https://github.com/checkstyle/checkstyle/issues/5003#issuecomment-350560290 .

Issue #5003: increased pitest coverage for whitespace package to 100%

---

config/intellij-idea-inspections.xml
config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java

Issue #4716
Turned on intellij rule and made class abstract.

Issue #4716: enabled intellij AbstractClassExtendsConcreteClass

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilsTest.java

Issue #4605
Went from 91% line coverage to 96%.
Went from 88% mutation to 94%.

Issue #4605: increased pitest coverage for utils package

---

config/version-number-rules.xml

base on https://travis-ci.org/checkstyle/checkstyle/jobs/316030201#L3120

config: add artifactId and new rule to version-number-rules.xml

---

pom.xml

base on https://travis-ci.org/checkstyle/checkstyle/jobs/316030201#L3106

config: bump maven-javadoc-plugin to 3.0.0

---

.ci/travis/travis.sh
pom.xml

base on https://travis-ci.org/checkstyle/checkstyle/jobs/316030201#L3294

config: bump antlr4 to 4.7.1 with minor output extension for travis

---

pom.xml

Issue #4605: minimized utils profile

---

pom.xml

reason https://travis-ci.org/checkstyle/checkstyle/jobs/319315351#L3262

config: bump sonar-maven-plugin version to 3.4.0.905

---

pom.xml

reason - https://travis-ci.org/checkstyle/checkstyle/jobs/319315351#L3275

config: bump pitest to 1.2.5

---

pom.xml

reason - https://travis-ci.org/checkstyle/checkstyle/jobs/319315351#L3249

config: bump version jgit to 4.9.2.201712150930-r

---

pom.xml

reason - https://travis-ci.org/checkstyle/checkstyle/jobs/319315351#L3231

config: bump Saxon-HE to 9.8.0-7

---

wercker.yml

Issue #5286: remove compile phase to make it same as pgjdbc travis 

---

pom.xml

reason : https://travis-ci.org/checkstyle/checkstyle/jobs/322284841#L3240

config: bump pitest to 1.3.1

---

src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerErrorModuleId.xml
src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerException2.xml
src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerException3.xml

Issue #5057
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/15/
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/16/
100% mutation for translation check and 100% for XML logger.

Issue #5057: fixed xml violations/exceptions with file started/finished

---

config/intellij-idea-inspections.xml
config/pmd-test.xml
config/suppressions-xpath.xml
config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config.xml
src/xdocs/config_annotation.xml
src/xdocs/config_blocks.xml
src/xdocs/config_coding.xml
src/xdocs/config_design.xml
src/xdocs/config_filters.xml
src/xdocs/config_header.xml
src/xdocs/config_imports.xml
src/xdocs/config_javadoc.xml
src/xdocs/config_metrics.xml
src/xdocs/config_misc.xml
src/xdocs/config_naming.xml
src/xdocs/config_regexp.xml
src/xdocs/config_sizes.xml
src/xdocs/config_whitespace.xml
src/xdocs/property_types.xml

Issue #3254
Some field names were changed to align with their setter names.
Some field types were changed to align with their uses.
All xdoc updates are result of new validation.

Issue #3254: UT to verify all property types and values in XDocs

---

src/main/resources/google_checks.xml

Minor: Use correct indention in google_checks.xml

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java

Issue #4581
This PR reorganizes the token methods in remaining checks.

Issue #4581: Reorganize token methods in remaining checks

---

src/xdocs/config_filters.xml

https://github.com/checkstyle/checkstyle/issues/5400

Issue #5400: Incorrect documentation for SuppressionXpathFilter

---

src/xdocs/anttask.xml.vm
src/xdocs/checks.xml
src/xdocs/cmdline.xml.vm
src/xdocs/config.xml
src/xdocs/config_annotation.xml
src/xdocs/config_coding.xml
src/xdocs/config_design.xml
src/xdocs/config_filters.xml
src/xdocs/config_imports.xml
src/xdocs/config_javadoc.xml
src/xdocs/config_metrics.xml
src/xdocs/config_regexp.xml
src/xdocs/config_sizes.xml
src/xdocs/config_whitespace.xml
src/xdocs/eclipse.xml
src/xdocs/google_style.xml
src/xdocs/idea.xml
src/xdocs/index.xml.vm
src/xdocs/netbeans.xml
src/xdocs/property_types.xml
src/xdocs/releasenotes.xml
src/xdocs/report_issue.xml
src/xdocs/sponsoring.xml
src/xdocs/writingchecks.xml
src/xdocs/writingjavadocchecks.xml.vm

Issue #5291: fixed long xdoc lines of 107 characters or more

---

pom.xml

reason: https://travis-ci.org/checkstyle/checkstyle/jobs/327357856#L3238

config: bump checkstyle maven plugin to 3.0.0

---

pom.xml

reason: https://travis-ci.org/checkstyle/checkstyle/jobs/327357856#L3225

config: bump jacoco to 0.8.0

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java

spelling: Fix typo

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java

spelling: fix typo in tests

---

appveyor.yml

Issue #5474: fix appveyor build failure with cygwin

---

src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java

Issue #5409
Fixes all Unsafe lazy initialization of 'static' field inspection 2 errors.
I was going to use double locking instead of synchronizing on the method, but PMD complained about that too. This article explains why: https://www.javaworld.com/article/2074979/java-concurrency/double-checked-locking--clever--but-broken.html
So I had to remove the lazy init.

Issue #5409: fixed remaining intellij 2017.3 violations

---

src/xdocs/writingjavadocchecks.xml.vm

Issue #3311: Updated Documentation

Issue #3311: Updated Documentation

---

.ci/wercker.sh

wercker failure

---

src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/api/fullident/InputFullIdentTestArrayType.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeArrays.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypePlainAndArrays.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileName.java

Issue #4429
Continuation of Pull #5073 
Issue solved in another way. Created some additional tests.

Issue #4429: IllegalType: support arrays as types

---

src/xdocs/config_regexp.xml

Updated config_regexp.xml regarding #5489

Issue #5489: Fixed indentation in config_regexp.xml

---

src/xdocs/config_filters.xml

minor: fix typo in SuppressionXpathFilter xdoc

---

src/xdocs/config.xml

Issue #5489: Fixed indentation in config.xml

---

src/xdocs/config_annotation.xml

Fixed indentation in config_annotation.xml for #5489

Issue #5489: Fixed indentation in config_annotation.xml

---

src/xdocs/config_blocks.xml

Updated indentation in config_blocks.xml for #5489. Updated the indentation for all switch statements under source blocks

Issue #5489: Fixed indentation in config_blocks.xml

---

src/xdocs/config_coding.xml

Fixed indentation in config_coding.xml related to #5489

Issue #5489: Fixed indentation in config_coding.xml

---

pom.xml

base on https://travis-ci.org/checkstyle/checkstyle/jobs/341570516

config: bump guava to 24.0-jre

---

pom.xml

based on https://travis-ci.org/checkstyle/checkstyle/jobs/341570516

config: bump pitest to 1.3.2

---

src/xdocs/config_design.xml

Issue #5489: Fixed indentation in config_design.xml

---

src/xdocs/config_imports.xml

Updated Indentation in config_imports.xml for #5489

Issue #5489: Fixed indentation in config_imports.xml

---

src/xdocs/config_javadoc.xml

Updated config_javadoc.xml #5489

Issue #5489: Fixed indentation in config_javadoc.xml

---

.ci/shippable.sh
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java

Issue #5008: increase coverage of pitest-checks-coding

---

src/xdocs/config_metrics.xml

Updated commits in config_metrics.xml #5489

Issue #5489: Fixed indentation in config_metrics.xml

---

.ci/shippable.sh
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtils.java

Issue #4605 
just removed negation(and continue) in condition.
This issue looks like a bug in pitest.

Issue #4605: cover all lines of of utils package in pitest run

---

.ci/shippable.sh
pom.xml

Issue #3708: cover all lines for pitest run over api

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolver.java

Issue #5546
Workaround for Jacoco limitations (1 of 4).

Issue #5546: Explicitly throw ClassNotFoundException from ClassResolver

---

src/xdocs/config_misc.xml

Updated indentation in config_misc.xml #5489

Issue #5489: Fixed indentation in config_misc.xml

---

.travis.yml

Testless build with oraclejdk9.

config: Travis JDK9 build

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtils.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilsTest.java

Issue #5555
Workaround for Jacoco limitations (part 4).
Also, solves a bit of #3433

Issue #5555: Refactoring of JavadocUtils static init

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java

Issue #5551
Workaround for Jacoco limitations (part 2).

Issue #5551: PackageNamesLoaderTest refactoring

---

src/xdocs/index.xml.vm

Fix some typos and grammar on the main web page.

doc: typos and grammar fixes on website main page

---

src/xdocs/report_issue.xml
src/xdocs/writingchecks.xml

Updated indentation in report_issue.xml & writingcheckss.xml #5489

Issue #5489: Fixed indentation in report_issue.xml & writingcheckss.xml

---

.ci/shippable.sh
src/test/java/com/puppycrawl/tools/checkstyle/DefaultConfigurationTest.java

Issue #5591 
This is related to #5592. I'm going to extract some classes to a dedicated profile, but the Pitest complains on missing coverage for some classes.

Issue #5591: 100% Coverage for DefaultConfiguration

---

src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java

Issue #5604 
Violation:
https://sonarcloud.io/project/issues?id=com.puppycrawl.tools%3Acheckstyle&open=AV0GeNYnI1Qj-tYTbFkx&resolved=false&types=CODE_SMELL

Issue #5604: resolve sonar violation 'Remove this unused private ctor ...'

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java

Issue #5553
Workaround for Jacoco limitations (part 3).

Issue #5553: Jacoco workaround for MainTest

---

.ci/run-link-check-plugin.sh
.ci/travis/travis.sh
.ci/wercker.sh
.travis.yml
appveyor.yml
pom.xml
release.sh
src/xdocs/contributing.xml

Issue #5586
- cobertura replaced with jacoco where possible
- Jacoco check extracted from it's profile
- JDK9 build with tests
- Sonarqube coverage

Issue #5586: Drop Cobertura

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java

based on discussions at https://github.com/checkstyle/checkstyle/issues/5615

doc: fixed improper private method documentation

---

.github/PULL_REQUEST_TEMPLATE.md

minor: update PULL_REQUEST_TEMPLATE.md

---

README.md
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectJavadocParagraphCheck.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraphCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocCorrectParagraph.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect.java

Fixes for GWT and Guava links in docs

Fixes for GWT and Guava links in docs

---

pom.xml

based on https://travis-ci.org/checkstyle/checkstyle/jobs/359510383

config: bump jacoco to 0.8.1

---

.ci/travis/travis.sh
.ci/wercker.sh

#5452
depends on https://github.com/checkstyle/contribution/pull/277

Issue #5452: Avoid Wercker failures in not updated PRs after release

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControl.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlDisallowClassOfAllowPackage.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlDisallowClassOfAllowPackage.xml
src/xdocs/config_imports.xml

Issue #5642: matched order of ImportControl rules to XML file

---

config/pmd-test.xml
config/pmd.xml
config/version-number-rules.xml
pom.xml

Issue #5603
There are many warnings about deprecated rules, they should be fixed in separated PRs.

Issue #5603: Migrate to PMD6

---

src/xdocs/config_misc.xml

Found while working on CI support

spelling: McConnell

---

src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexponfilename/InputRegexpOnFilenameSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/upperell/InputUpperEllSemantic.java

I'm not sure about this change.
I'm mostly making this PR to test the function of the newly added spell checking test.

spelling: commenting

---

.circleci/config.yml

originally was introduced at #5684

infra: update circleCI to utilize 'checkstyleVersion' option of launch.groovy

---

.ci/test-spelling-unknown-words.sh

Issue #5693: Exclude two resources directories

---

.ci/test-spelling-unknown-words.sh

Issue #5701: Hide details from spell checker word family output

---

config/pmd-test.xml
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java

Issue #5677: Refactor PackageObjectFactoryTest.testCreateModuleWithNonExistName

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/365264327#L3370

config: bump saxon to 9.8.0-11

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/365264327#L3383

config: bump maven-dependency-plugin to 3.1.0

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/365264327#L3409

config: bump forbiddenapis to 2.5

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/365264327#L3396

Jar and Shade plugin version bumps

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/365264327#L3421

Surefire and failsafe to 2.21.0

---

src/xdocs/config_misc.xml

Issue #5718: UpperEll rule description gives bogus reason

---

config/import-control.xml
src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java
src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java

Issue #5638
All `File{Input,Output}Stream` replaced with `Files.new{Input,Output}Stream`.

Issue #5638: Replace File{Input,Output}Stream with Files.new{Input,Output}Stream

---

config/import-control.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinterTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/suppressionsstringprinter/InputSuppressionsStringPrinter.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainSuppressionsStringPrinter.java
src/test/resources/com/puppycrawl/tools/checkstyle/suppressionsstringprinter/InputSuppressionsStringPrinter.java
src/xdocs/cmdline.xml.vm

https://github.com/checkstyle/checkstyle/issues/4530

Issue #4530: Add the new option for Checkstyle CLI to generate the basic suppression xpath

---

.ci/test-spelling-unknown-words.sh

Issue #5732: let spellchecker tolerate case jitter

---

config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java

https://github.com/checkstyle/checkstyle/issues/5571

Issue #5571: Xpath Mapper : UnsupportedOperationException when several queries are combined

---

src/xdocs/config_filters.xml

https://github.com/checkstyle/checkstyle/issues/5513

Issue #5513: Create xdoc page to explain the new Xpath-based suppression model

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java

Issue #5412 
From pull #5768 
Changed lambda parameters names.

Issue #5412: change lambda parameter names

---

config/checkstyle_checks.xml
config/pmd-test.xml
config/sevntu_suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for AbbreviationAsWordInNameCheck

---

config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java
src/main/java/com/puppycrawl/tools/checkstyle/DefaultContext.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelector.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java

Issue #3484
Removed first batch of guava.

Issue #3484: removed instances of guava immutables

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/376970775#L1177

config: bump system-rules to 1.17.2

---

pom.xml

https://travis-ci.org/checkstyle/checkstyle/jobs/376970775#L1191

config: bump saxon to 9.8.0-12

---

pom.xml

minor: disable maven site.xml validation till #5785

---

.travis.yml

Attempt to force travis CI to always run for specific sections.
Please verify my new bash command is fine.

minor: force specific travis CI sections to run always

---

.ci/jsoref-spellchecker/whitelist.words
.ci/wercker.sh

continuation of https://github.com/OpenGamma/Strata/pull/1688
https://groups.google.com/d/msg/checkstyle/KYF-9EEzsbs/-5QsQ01BAwAJ

config: add strata project to wercker

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/checks.xml
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for CatchParameterName

---

config/checkstyle_non_main_files_checks.xml
config/checkstyle_non_main_files_suppressions.xml
src/xdocs/cmdline.xml.vm

Issue #5791: update format to skip imports and http, resolve some cases

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java
src/xdocs/config_filters.xml

Issue #5757
There should be no more easy cases after this.

Issue #5757: switched simple log line/column to log ast

---

config/checkstyle_non_main_files_checks.xml
config/checkstyle_non_main_files_suppressions.xml
pom.xml

Issue #5791: wrap lines in pom.xml

---

config/checkstyle_non_main_files_suppressions.xml
config/pmd-main.xml
config/pmd-test.xml
config/pmd.xml
config/spotbugs-exclude.xml

Issue #5791: wrap lines in pmd and spotbugs

---

.ci/circleci.sh
.ci/eclipse-compiler-javac.sh
.ci/run-link-check-plugin.sh
.ci/shippable.sh
.ci/sonar.sh
.ci/test-spelling-unknown-words.sh
.ci/wercker.sh
.circleci/config.yml
config/checkstyle_non_main_files_suppressions.xml
distelli-manifest.yml

Issue #5791: wrap lines in ci folder

---

config/build.xml
config/checkstyle_checks.xml
config/checkstyle_non_main_files_checks.xml
config/checkstyle_non_main_files_suppressions.xml
config/checkstyle_sevntu_checks.xml
config/suppressions.xml
src/xdocs/writingchecks.xml
src/xdocs/writingjavadocchecks.xml.vm

Issue #5791: wrap checkstle configs

---

appveyor.yml

Issue #5791: line wrap for appveyor

---

.ci/eclipse-compiler-javac.sh
config/checkstyle_checks.xml
config/intellij-idea-inspections.xml
config/org.eclipse.jdt.core.prefs
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java

Issue #5752 
Force use of `try-with-resources`

issue #5752: Activate checks related to java.io.Closeable

---

config/checkstyle_non_main_files_suppressions.xml
config/intellij-idea-inspection-scope.xml
config/intellij-idea-inspections.properties
config/intellij-idea-inspections.xml

Issue #5791
This is final commit for this issue.
Attention to https://github.com/checkstyle/checkstyle/issues/5791#issuecomment-390361171 to explain not wrapping changes.

Issue #5791: wrap IntelliJ configs

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #5791: fix xdoc and restore disabled UT

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for ClassTypeParameterNameCheck

---

config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for ConstantNameCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for InterfaceTypeParameterNameCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for LocalFinalVariableNameCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue 5750 local variable name check

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for MemberNameCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: aligned javadoc/xdoc for MethodNameCheck

---

config/checkstyle_non_main_files_suppressions.xml

config: suppress linelength validation in pom.xml till MRELEASE-1008

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_naming.xml

Issue #5750: last of naming checks

---

.ci/jsoref-spellchecker/whitelist.words
release.sh
src/xdocs/index.xml.vm

config: make previous releases documentation accessible from web (#5601)

---

.ci/jsoref-spellchecker/whitelist.words
src/xdocs/sponsoring.xml

Issue #5256: place opencollective badge on sponsoring page

---

pom.xml
release.sh
src/xdocs/cmdline.xml.vm

Issue #5601: stop publishing binaries to sourceforge

---

src/xdocs/sponsoring.xml

Identified at https://github.com/checkstyle/checkstyle/pull/5869#issuecomment-395794850

minor: fix empty tag in sponsoring.xml

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config.xml

Issue identified at https://github.com/checkstyle/checkstyle/pull/5913#pullrequestreview-127942797 .

minor: fixed xdoc not validating required sub-sections

---

config/checkstyle_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config.xml

Issue #2726
continuation of #5913

Issue #2726: add explanation of metadata tag in checkstyle config

---

src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java

Issue #5916: resolve 'Access restriction' warning from Eclipse

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingComma.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingComma.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java

Issue #5916: simplify inputs to resolve eclipse errror

---

config/ant-phase-verify.xml
config/checkstyle_resources_checks.xml

Issue #4100: enable PackageDeclarationCheck on resources

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config_coding.xml
src/xdocs/config_imports.xml
src/xdocs/config_javadoc.xml
src/xdocs/config_misc.xml
src/xdocs/config_regexp.xml
src/xdocs/config_sizes.xml

Issue #5949: fix 'Begin or end anchor in unexpected position' violations

---

.ci/jsoref-spellchecker/whitelist.words
.circleci/config.yml
.travis.yml
Jenkinsfile
appveyor.yml
distelli-manifest.yml
shippable.yml
wercker.yml

Issue #5953: add the initial Jenkinsfile for the project

Issue #5953: Add the initial Jenkinsfile for the project

---

.ci/travis/xtr_releasenotes-gen.sh

Required update for https://github.com/checkstyle/contribution/pull/310

config: add remoteRepoPath to releasenotes-builder

---

.ci/jsoref-spellchecker/whitelist.words
config/import-control.xml
config/suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtil.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainConfig-empty.xml
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainConfig-xpath-suppressions.xml
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainGenerateXpathSuppressions.java
src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainGenerateXpathSuppressionsTabWidth.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpathfilegeneratorauditlistener/InputXpathFileGeneratorAuditListener.java
src/xdocs/cmdline.xml.vm

https://github.com/checkstyle/checkstyle/issues/102

Issue #102: Generate a suppressions.xml file from the errors list

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsAbove.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsBottom.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsInflow.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsNegative.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsTop.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsUnordered.java
src/xdocs/config_imports.xml

Issue #5724
https://pbludov.github.io/issue-5724/

Issue #5724: Groups for static imports

---

.ci/jsoref-spellchecker/whitelist.words
Jenkinsfile

Issue #5953: Setup 'mvn compile' and 'mvn package' builds in Jenkins

Issue #5953: Setup 'mvn compile' and 'mvn package' builds in Jenkins

---

pom.xml
src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathRegressionTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRequireThisTest.java

Issue #5996 
Fixing POM to confirm issue with IT tests.

Issue #5996: expanded it tests to include checkstyle

---

src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java

Issue #6001: print no version if it is null

---

src/site/resources/files/suppressions_none.xml
src/xdocs/config.xml
src/xdocs/config_filters.xml

Issue #6003
new section to explain what is ID.
"Suppressions XML Document" is part of certain filter, not a whole checkstyle

Issue #6003: update documentation of SuppressionFilter with links to latest DTDs

---

config/import-control.xml
config/pmd.xml
src/main/java/com/puppycrawl/tools/checkstyle/GlobalStatefulCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java

Issue #4870
continuation of #5165

Issue #4870: Mark TranslationCheck and JavadocPackageCheck with GlobalStatefulCheck annotation

---

.ci/test-spelling-unknown-words.sh
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

Issue #4870: added UT to ensure multithread annotations on modules

---

.ci/travis/travis.sh

based on problem https://github.com/checkstyle/checkstyle/pull/6016#issuecomment-403696636

config: run check goal for jacoco coverage verification

---

src/xdocs/config.xml

Issue #6011: redo XML_Structure documentation section

---

src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilter.java
src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java

https://github.com/checkstyle/checkstyle/issues/5979

Issue #5979: XpathFileGeneratorAstFilter: EVENTS and QUERIES as single map

---

.ci/jsoref-spellchecker/whitelist.words
config/ant-phase-verify.xml
pom.xml
src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java
src/it/java/org/checkstyle/checks/imports/ImportOrderTest.java
src/it/resources-noncompilable/org/checkstyle/checks/imports/importorder/InputFromAndroid.java
src/it/resources-noncompilable/org/checkstyle/checks/imports/importorder/InputFromSpotify.java
src/it/resources-noncompilable/org/checkstyle/checks/imports/importorder/InputFromTwitter.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsBottomSeparated.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsTopSeparated.java
src/xdocs/config_imports.xml
src/xdocs/property_types.xml

Issue #5279 
Regression tests https://pbludov.github.io/issue-5279/

Issue #5279: static imports can be separated by local groups

---

src/xdocs/config_filters.xml

https://github.com/checkstyle/checkstyle/issues/5980

doc: reference in SuppressionXpathFilter doc about ability to generate suppressions by CLI

---

.ci/wercker.sh
wercker.yml

Issue #6018 
CI for import order checks  for `guava(v25)` and `java design patterns`

Issue #6018: Add to CI import order validation

---

src/site/resources/css/site.css
src/site/resources/js/anchors.js
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/config.xml
src/xdocs/config_annotation.xml
src/xdocs/config_blocks.xml
src/xdocs/config_coding.xml
src/xdocs/config_design.xml
src/xdocs/config_filefilters.xml
src/xdocs/config_filters.xml
src/xdocs/config_header.xml
src/xdocs/config_imports.xml
src/xdocs/config_javadoc.xml
src/xdocs/config_metrics.xml
src/xdocs/config_misc.xml
src/xdocs/config_modifier.xml
src/xdocs/config_naming.xml
src/xdocs/config_regexp.xml
src/xdocs/config_sizes.xml
src/xdocs/config_whitespace.xml
src/xdocs/google_style.xml
src/xdocs/sun_style.xml

Issue #6014: added subsection anchors to xdoc

---

src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java

https://github.com/checkstyle/checkstyle/issues/5984

Issue #5984: XpathSuppression generation should support module id

---

config/intellij-idea-inspections.xml
src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java
src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java

Issue #6037: fix inspection violations, suppress 2 inspections

---

config/checkstyle_checks.xml
src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCyclomaticComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionDeclarationOrderTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionDefaultComesLastTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionExplicitInitializationTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionFallThroughTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionHiddenFieldTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalThrowsTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionImportControlTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavadocVariableTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionLeftCurlyTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMethodParamPadTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMultipleVariableDeclarationsTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNPathComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNestedForDepthTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNestedIfDepthTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNestedTryDepthTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOneStatementPerLineTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOuterTypeNumberTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRequireThisTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRightCurlyTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathTestSupport.java

Issue #6037: resolve inspection violation 'Abstract class without abstract method

---

src/xdocs/google_style.xml
src/xdocs/sun_style.xml

Issue #6043: update links to html reports for guava and sun

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyEolSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyNlSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyNlowSwitch.java
src/xdocs/config_blocks.xml

Issue #5207
Regression report https://pbludov.github.io/issue-5207/

Issue #5207: LITERAL_CASE and LITERAL_DEFAULT in LeftCurlyCheck

---

.ci/test-spelling-unknown-words.sh

#6046
This doesn't fix issue, it is just workaround.

Issue #6046: fix link to linux.words file

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameLambda.java
src/xdocs/config_naming.xml

Issue #5894
Remove processing of lambda from ParameterNameCheck, tests added.

Issue #5894: Remove lambda parameters processing

---

src/site/resources/css/site.css

based off of changes in https://github.com/checkstyle/contribution/pull/323

minor: added date formatting for release notes

---

.travis.yml

Issue #6055: fix Travis CI build on OSX

---

.ci/jsoref-spellchecker/whitelist.words
src/xdocs/contributing.xml

Some information for volunteers. I don't really know what's supposed to be there. Suggestions and comments are welcome.

doc: note about bounty

---

.ci/test-spelling-unknown-words.sh

Issue #6046
Grep for the file name to get most recent version.

Issue #6046: Spell check failing to get words file

---

src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java
src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java
src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/BlockOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AccessResult.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/MismatchStrategy.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/PadOption.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WrapOption.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

Discussed in sevntu-checkstyle/sevntu.checkstyle#709
Related to issue 3161

Issue #3161: Format for trailing comma check in enums

---

.circleci/config.yml

Issue #6093: fix problem with circle-ci ability to restore cache

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/xdocs/config_javadoc.xml

Issue 5750 atclauseorder

---

pom.xml

Issue #6098: downgrade spotbugs library to previous version

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java
src/xdocs/config_naming.xml

Issue #5832: Add javadoc and xdoc Example for AbstractClassName

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheck.java
src/xdocs/config_naming.xml

Issue #5832: Add javadoc and xdoc Example for ClassTypeParameterName
