src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidNoArgumentSuperConstructorCallTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidStarImportTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidStaticImportTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionBooleanExpressionComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCatchParameterNameTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnoargumentsuperconstructorcall/InputXpathAvoidNoArgumentSuperConstructorCallDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnoargumentsuperconstructorcall/InputXpathAvoidNoArgumentSuperConstructorCallInnerClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnoargumentsuperconstructorcall/SuppressionXpathRegressionAvoidNoArgumentSuperConstructorCall.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstarimport/InputXpathAvoidStarImportOne.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstarimport/InputXpathAvoidStarImportTwo.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstaticimport/InputXpathAvoidStaticImportOne.java
src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstaticimport/InputXpathAvoidStaticImportTwo.java
src/it/resources/org/checkstyle/suppressionxpathfilter/booleanexpressioncomplexity/InputXpathBooleanExpressionComplexityCatchBlock.java
src/it/resources/org/checkstyle/suppressionxpathfilter/booleanexpressioncomplexity/InputXpathBooleanExpressionComplexityClassFields.java
src/it/resources/org/checkstyle/suppressionxpathfilter/booleanexpressioncomplexity/InputXpathBooleanExpressionComplexityConditionals.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameAnonymous.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameEnum.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameLambda.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameNested.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameSimple.java
src/it/resources/org/checkstyle/suppressionxpathfilter/catchparametername/InputXpathCatchParameterNameStaticInit.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #14715: Enforced new naming convention in IT area - Part Eight

---

src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControl.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java

Resolves Checkstyle failures that arise when fixing the following issue:
- https://github.com/checkstyle/checkstyle/issues/14750
Split from the PR that fixes it:
- https://github.com/checkstyle/checkstyle/pull/14690

doc: Fix periods in Javadoc summary

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Begin #14631 
Example:
```
PS C:\Users\Hp\Desktop\4th year> cat Test.java
/**
* Some Java doc.
* @serialField counter Integer objects counter
*/
private void boo();
}
```
Tree:
```
PS C:\Users\Hp\Desktop\4th year> java -jar checkstyle-10.14.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|--LCURLY -> {
|--METHOD_DEF -> METHOD_DEF
|   |--MODIFIERS -> MODIFIERS
|   |   |--BLOCK_COMMENT_BEGIN -> /*
|   |   |   |--COMMENT_CONTENT -> *\r\n   * Some Java doc.\r\n   * @serialField counter Integer objects counter\r\n
|   |   |   |   `--JAVADOC -> JAVADOC
|   |   |   |       |--NEWLINE …
```

Issue #14631: Updated SERIAL_FIELD_LITERAL of JavadocTokenTypes to new AST format

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCustomImportOrderTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCyclomaticComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionFinalLocalVariableTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/InputXpathCustomImportOrderFive.java
src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/InputXpathCustomImportOrderFour.java
src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/InputXpathCustomImportOrderOne.java
src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/InputXpathCustomImportOrderSix.java
src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/InputXpathCustomImportOrderThree.java
src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/InputXpathCustomImportOrderTwo.java
src/it/resources/org/checkstyle/suppressionxpathfilter/cyclomaticcomplexity/InputXpathCyclomaticComplexityConditionals.java
src/it/resources/org/checkstyle/suppressionxpathfilter/cyclomaticcomplexity/InputXpathCyclomaticComplexitySwitchBlock.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableConditionals.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableCtor.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableEnhancedFor.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableForLoop.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableInnerClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableMethodDef.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableParameterDef.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableSwitchCase.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/InputXpathFinalLocalVariableTryBlock.java
src/it/resources/org/checkstyle/suppressionxpathfilter/finallocalvariable/SuppressionXpathRegressionFinalLocalVariable7.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #14715: Enforced new naming convention in IT area 15

---

config/projects-to-test/openjdk21-excluded.files
src/test/java/com/puppycrawl/tools/checkstyle/JavaAstVisitorTest.java

Linked to explanation of suppression and expanded comment.

minor: update comment on suppression

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalIdentifierNameTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalInstantiationTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPackageAnnotationTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPackageDeclarationTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPatternVariableNameTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordComponentNameTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordComponentNumberTest.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalidentifiername/InputXpathIllegalIdentifierNameOne.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalidentifiername/InputXpathIllegalIdentifierNameTwo.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalinstantiation/InputXpathIllegalInstantiationAnonymous.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalinstantiation/InputXpathIllegalInstantiationInterface.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalinstantiation/InputXpathIllegalInstantiationSimple.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packageannotation/InputXpathPackageAnnotationOne.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packageannotation/InputXpathPackageAnnotationTwo.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packagedeclaration/InputXpathMissingPackage.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packagedeclaration/InputXpathWrongPackage.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/InputXpathPatternVariableNameFour.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/InputXpathPatternVariableNameOne.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/InputXpathPatternVariableNameThree.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/InputXpathPatternVariableNameTwo.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentname/InputXpathRecordComponentNameDefault.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentname/InputXpathRecordComponentNameFormat.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentnumber/InputXpathRecordComponentNumberCustomMax.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentnumber/InputXpathRecordComponentNumberDefault.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Resolves #14715 
Suppression list and conditional that checks suppressions are removed.

Issue #14715: Enforced new naming convention in IT area 24

---

src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/SinglelineDetector.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java

Part of #14625 
`TailRecursion` inspection problems need to be dealt with on a case by case basis.
These have been moved to new separate issue for discussions....

Issue #14625: move TailRecursion inspection problems to separate issue

---

.circleci/config.yml

enablement based on request at https://github.com/spotbugs/spotbugs/issues/2819#issuecomment-2095294403
UPDATE: disablement is staying, reason is changing.

infra: change reason of spotbugs disablement in circleci

---

.github/CONTRIBUTING.md

**PR Summary**:
PR #8055 moved the issue template to a new location. This PR adjusts sources to changes.

doc: update issue template reference

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/WhitespaceAroundCheck.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchExpressions.java
src/xdocs/checks/whitespace/whitespacearound.xml
src/xdocs/checks/whitespace/whitespacearound.xml.template

Closes #14825
Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/3dfd508a98b976b267532ea4d4c0986d7b78c11c/config_single.xml

Issue #14825: fix false positive for WhitespaceAroundCheck

---

src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundSwitchExpressions.java

minor: add non-compiled comment

---

.ci/validation.sh
.circleci/config.yml
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassNestedStaticClassInsideInnerClass.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionNewLine.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeRecordParamDescriptionWithAngularTags.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethod1.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealed.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealedNoViolation.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierRecords.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainBeginTree2.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainRecords2.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionJava15FinalLocalRecord.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionJava16LocalEnumAndInterface.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionUncommon.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionUncommon3.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java15/InputAstRegressionSealedAndPermits.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java15/InputTopLevelNonSealed.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java16/InputPatternVariableWithModifiers.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java
src/test/resources/com/puppycrawl/tools/checkstyle/grammar/antlr4/ExpectedAntlr4AstRegressionJava15FinalLocalRecord.txt
src/test/resources/com/puppycrawl/tools/checkstyle/grammar/antlr4/ExpectedAntlr4AstRegressionUncommon.txt
src/test/resources/com/puppycrawl/tools/checkstyle/grammar/antlr4/ExpectedAntlr4AstRegressionUncommon3.txt

Issue #14877: drop unsupported java version builds from CI

---

config/pitest-suppressions/pitest-coding-2-suppressions.xml
config/spotbugs-exclude.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLocalClasses.java

Issue #13167: Fix NPE in UnusedLocalVariable check

---

.ci/validation.sh

Issue #818: Aims to see if the shallowClone feature works fine

test: shallowClone in checkstyle-tester with SHA checkout

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/MethodParamPadCheck.xml
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckConstructors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadWhitespaceAround.java
src/xdocs/checks/whitespace/methodparampad.xml

Closes #13675 
Diff Regression config: https://gist.githubusercontent.com/strkkk/238b6c97492ff6ffdb3be1603deca8fc/raw/f60ac5a16eb2fc4516ed203c4cf31e45c3e94ca6/config_single_2.xml

Issue #13675: add constructor call token to MethodParamPadCheck

---

src/xdocs/google_style.xml

Issue #14930: fixed inconsistent spacing between checks in google style documentation

---

.ci/validation.sh

content from https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations
is copied to code to let all use it as if we have `just` tool.

minor: move wiki content of useful commands to code

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/LineLengthTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputLineLength.java
src/main/resources/google_checks.xml

issue #14955 
updated the linelength module based on https://github.com/checkstyle/checkstyle/pull/14943#discussion_r1631183000 https://github.com/checkstyle/checkstyle/pull/14943#discussion_r1631179645 and created new test cases for it

Issue #14955: updated LineLength ignorePattern property in google config

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/ConstructorsDeclarationGroupingTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/ClassAnnotationsTest.java
src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputConstructorsDeclarationGroupingRecords.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputConstructorsDeclarationGrouping.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/InputClassAnnotations.java
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java

issue #14929 
added support for violations messages including above, below, etc in AbstractItModuleTestSupport for google IT tests

Issue #14929: added support for violation messages for google tests

---

src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/Example6.txt
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/Example7.txt
src/xdocs/checks/regexp/regexpsingleline.xml

Issue #14996: fix wrong comment

---

config/jsoref-spellchecker/whitelist.words
config/sevntu-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/MethodsAndConstructorsAnnotationsTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputMethodsAndConstructorsAnnotations.java
src/xdocs/google_style.xml

issue #14911 
added a new section `4.8.5.3 Methods And Constructors Annotations` in google style guide coverage page and wrote test cases for it

Issue #14911: Added a new section 4.8.5.3 in google style guide implementation

---

config/jsoref-spellchecker/whitelist.words
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/FieldAnnotationsTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/InputFieldAnnotations.java
src/xdocs/google_style.xml

issue #14914 
added a new section `4.8.5.4 Field Annotations` in google style guide coverage page and wrote test cases for it

Issue #14914: Added a new section 4.8.5.4 Field Annotations in google style guide implementation

---

src/xdocs/google_style.xml

issue #14899
discussed at https://github.com/checkstyle/checkstyle/pull/14901#discussion_r1622428372
updated coverage page and added message addressing to the new issue for section 7.1.2 Paragraphs

Issue #14899: Updated google coverage page regarding section 7.1.2 Paragraphs

---

config/checkstyle-resources-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/FileNameTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName1.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName2.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName3.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 2.1 File name to follow chapter wise testing

---

config/checkstyle-resources-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/WhitespaceCharactersTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule231filetab/InputWhitespaceCharacters.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 2.3.1 Whitespace Characters to follow Chapter Wise Testing

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Related #14631 
```
rohanjha@rohanjha-IdeaPad-3-15IIL05-Ua:~/Desktop$ cat Test.java
/**
* A simple method that uses {@inheritDoc} inline tag.
*
* <p>This method demonstrates the use of {@inheritDoc} tag.</p>
*
* {@inheritDoc}
*
* @param p1 The first number
* @return The input number
*/
public int exampleMethod(int p1) {
return p1;
}
}
rohanjha@rohanjha-IdeaPad-3-15IIL05-Ua:~/Desktop$ java -jar checkstyle-10.17.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
|   `--LITERAL_PUBLIC -> public 
|--LITERAL_CLASS -> class 
|--IDENT -> Test 
`--OBJBLOCK -> OBJBLOCK 
|--LCURLY -> { 
|--METHOD_DEF -> METHOD_DEF 
|   |--MODIFIERS -> MODIFIERS 
|   |   |--BLOCK_COMMENT_BEGIN -> /* …
```

Issue #14631: Updated LINK_LITERAL to new AST format

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/NoWildcardImportsTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/InputNoWildcardImports.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 3.3.1 No wildcard imports to follow chapter wise testing approach

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Related #14631 
```
rohanjha@rohanjha-IdeaPad-3-15IIL05-Ua:~/Desktop$ cat Test.java
/**
* A simple method that uses {@linkplain org.apache.utils.Lists.Comparator#compare(Object) compare} inline tag.
*
* <p>This method demonstrates the use of {@linkplain org.apache.utils.Lists.Comparator#compare(Object) compare} tag.</p>
*
* {@linkplain org.apache.utils.Lists.Comparator#compare(Object) compare}
*
* @param p1 The first number
* @return The input number
*/
public int exampleMethod(int p1) {
return p1;
}
}
rohanjha@rohanjha-IdeaPad-3-15IIL05-Ua:~/Desktop$ java -jar checkstyle-10.17.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g" …
```

Issue #14631: Updated LINKPLAIN_LITERAL to new AST format

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 4.3 One statement per line to Chapter wise testing

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/SourceFileStructureTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/InputSourceFileStructure.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 3 Source File Structure to Chapter Wise Testing

---

src/it/java/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/NonAsciiCharactersTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/InputNonAsciiCharacters.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 2.3.3 Non-ASCII characters to follow chapter wise testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/FallThroughCommentedTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 4.8.4.2 Fall-through Commented to chapter wise testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/DeclaredWhenNeededTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822variabledistance/InputDeclaredWhenNeeded.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 4.2.2 Declared When Needed to chapter wise testing

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckNullCaseLabel.java

closes #15123 
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/fd6bb80bfe66feb1d7bf946caf87c0a7be981f6c/check.xml
Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/8ca3493f88bc1003db86b40015a4c2101ab7bc94/projects-to-test-on.properties

Issue #15123: False Positive when case null in switch statements group

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule521packagenames/PackageNamesTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521$packagenames/InputPackageBadName3.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521_packagenames/InputBadPackageName2.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521packageNamesCamelCase/InputPackageNameBad.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 5.2.1 Package names to chapter wise testing

---

src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadDeprecated.java

Issue #15144: trims back violation message

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/PresenceOfTheDefaultLabelTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/InputPresenceOfDefaultLabel.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 4.8.4.3 Presence of the default label to chapter wise testing

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurly.java

Detected at: https://github.com/checkstyle/checkstyle/pull/15116#discussion_r1655465265

minor: Restored formatting for InputRightCurly.java

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/VerticalWhitespaceTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputVerticalWhitespace.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 4.6.1 vertical whitespace to chapter wise testing

---

src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequences.java

Issue #13213: Remove '//ok' comments from InputSpecialEscapeSequences

Issue #13213: Remove '//ok' comments from InputSpecialEscapeSequences

---

src/it/java/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/CaughtExceptionsNotIgnoredTest.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/InputEmptyFinallyBlock.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 6.2 Caught Exceptions Not Ignored to chapter wise testing

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputLeftCurlyMethod.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOther.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCase.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputMethodParamPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapArrayDeclarator.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapEllipsis.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputModifierOrder.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule522typenames/InputClassNames.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputLocalVariableNameOneCharVarName.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck1.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck2.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeCheck.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeCheckNoViolations.java

Issue: #13213 
Finished #14325 by removing //ok comments from all the files that were preserved to this day.

Issue #13213: Removed //ok comments from src/it

---

config/jsoref-spellchecker/whitelist.words
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/OperatorWrapCheck.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperator.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperatorEndOfLine.java
src/xdocs/checks/whitespace/operatorwrap.xml
src/xdocs/checks/whitespace/operatorwrap.xml.template

Issue #15007: Add input file for instanceof operator in OperatorWrap

---

config/checkstyle-non-main-files-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/ColumnLimit100Test.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputColumnLimit.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 4.4 Column Limit: 100 to chapter wise testing

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/MethodParamPadCheck.xml
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckRecordPattern.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckRecordPattern2.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckConstructors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckWithEmoji.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadSetOptionTrim.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadWhitespaceAround.java
src/xdocs/checks.xml
src/xdocs/checks/whitespace/index.xml
src/xdocs/checks/whitespace/methodparampad.xml
src/xdocs/checks/whitespace/methodparampad.xml.template

closes #14966 :
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/b2b2571b42b8fa0f5e95ea546e9fa16e98948980/check.xml
Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/761163c3fb766f95d7303e07c60ef178013be96e/check_patch.xml
Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/a3424ad9b6f722e5de1a927e3d85e383101b2b93/projects-to-test-on.properties

Issue #14966: Update MethodParmPad to support record patterns

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableRecords.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableWithoutPackageStatement.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariable2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableAnonInnerClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableDepthOfClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableEnum.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableGenericAnonInnerClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLambdaExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableLocalClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableSwitchStatement2.java

We will introduce a new message in #15187. So we need to update all existing files to specify the message. Specifying the message is obligatory when we have more than one.

supplemental: Add violation message in unusedLocalVariable input files

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/NonRequiredJavadocTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPosition.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 7.3.4 Non-required javadoc to chapter wise testing

---

config/jsoref-spellchecker/whitelist.words
src/it/java/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/BlockIndentation2SpacesTest.java
src/it/java/com/google/checkstyle/test/chapter4formatting/rule452continuationlines/IndentContinuationLinesAtLeast4SpacesTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated Indentation sections 4.2, 4.5.2, 4.8.4.1 to chapter wise testing

---

config/jsoref-spellchecker/whitelist.words
src/it/java/com/google/checkstyle/test/chapter7javadoc/rule732exceptionoverrides/ExceptionOverridesTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule732exceptionoverrides/InputJavadocMethodAndMissingJavadocMethod.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

Issue #14937: Migrated section 7.3.2 Exception: Overrides to chapter wise testing

---

src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java

detected at: https://github.com/checkstyle/checkstyle/issues/14937#issuecomment-2218431551

minor: updated until comment for verifyWithConfigParser method

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/OverloadsNeverSplitTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadsNeverSplitRecords.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3421overloadsplit/InputOverloadsNeverSplit.java

Issue #15214: Migrated section 3.4.2.1 Overloads: never split to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/OrderingAndSpacingTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing1.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing3.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing4.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing5.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacingNoImports.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacingValid.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacingValid2.java

Issue #15214: migrated section 3.3.3 Ordering and spacing to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/FallThroughCommentedTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java

Issue #15214: Migrated section 4.8.4.2 Fall through commented to whole config testing

---

src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequences.java

Issue #15218: Formatted the input file for section 2.3.2 Special Escape Sequences to follow google java style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter5naming/rule53camelcase/InputCamelCaseDefined.java

Issue #15218: Formatted input file of section 5.3 Camel case: defined to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName1.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName2.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule21filename/InputFileName3.java

Issue #15218: Formatted input files for section 2.1 File Name to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/InputNoFinalizeExtend.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/InputNoFinalizer.java

Issue #15218: Formatted input files of section 6.4 Finalizers to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter5naming/rule523methodnames/InputMethodName.java

Issue #15218: Formatted input file of section 5.2.3 Method Name to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/InputOneVariablePerDeclaration.java

Issue #1518: Formatted the input file for section 4.8.2.1 One variable per line to follow google style guide rules

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadCheckWhenExpression.java

Issue #14980: Add new input file for when expression syntax in ParenPad

---

src/xdocs/checks/coding/declarationorder.xml
src/xdocs/checks/coding/declarationorder.xml.template
src/xdocs/index.xml.vm

Issue #14875
related to https://github.com/checkstyle/checkstyle/pull/15253

Issue #14875: fix links to be relative for styleguides

---

src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/InputEmptyFinallyBlock.java

Issue #15218: Formatted input file of section 6.2 Caught Exceptions: not ignored to follow google style guide rules

---

src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checker/InputCheckerTestCharset.java

Issue: #11446
Finishing #14821 which updated verify method in testUnmappableCharacters()

Issue #11446: Updated testUnmappableCharacters in CheckerTest

---

.ci/diff-report.sh
.github/workflows/diff-report.yml

Rename variables in diff-report.sh to support new workflow

---

src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputPatternVariableNameEnhancedInstanceofTestDefault.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputLocalVariableNameOneCharVarName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputLocalVariableNameSimple.java

Issue #15218: Formatted input files of section 5.2.7 Local Variable Names to follow google style guide rules

---

src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputRecordTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputClassTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputInterfaceTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputMethodTypeParameterName.java

Issue #15218: Formatted input files of section 5.2.8 Type variable names to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/InputNonAsciiCharacters.java

Issue #15218: Formatted input file of section 2.3.3 Non Ascii Characters to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassBad1.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassBad2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassBasic.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassGood.java

Issue #15218: Formatted input files for section 3.4.1 Exactly one top-level class declaration to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule488numericliterals/InputNumericLiterals.java

Issue #15218: formatted input file for section 4.8.8 numeric literals to follow google style guide rules

---

src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputRecordComponentName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputCatchParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputLambdaParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterName.java

Issue #15218: formatted input files for section 5.2.6 parameter names to follow google style guide rules

---

src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java

Issue #15218: formatted input files for section 4.3 one statement per line to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4832nocstylearray/InputNoCStyleArrays.java

Issue #15218: formatted input file for section 4.8.3.2 No C style array to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/InputPresenceOfDefaultLabel.java

Issue #15218: formatted input file for section 4.8.4.3 presence of default label to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/InputSourceFileStructure.java

Issue #15218: formatted input file for section 3 source file to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter5naming/rule521$packagenames/InputPackageBadName3.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521_packagenames/InputBadPackageName2.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521packageNamesCamelCase/InputPackageNameBad.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521packagenames/InputPackageNameGood.java

Issue #15218: formatted input files for section 5.2.1 package names to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/InputUseOfOptionalBraces.java

Issue #15218: formatted input file for section 4.1.1 use of optional braces to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule32packagestatement/InputPackageStatement.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/toolongpackagetotestcoveragegooglesjavastylerule/InputPackageStatementLongName.java

Issue #15218: formatted input file for section 3.2 package statement to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapping.java

Issue #15218: formatted input file for section 3.3.2 no line wrapping to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputModifierOrder.java

Issue #15218: formatted input file for section 4.8.7 modifiers to follow google style guide rules

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpressionWithWhen.java

Issue #15039: Add new input file for when expressions in SimplifyBooleanExpression

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck1.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck2.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck3.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputIncorrectAtClauseOrderCheck1.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputIncorrectAtClauseOrderCheck2.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputIncorrectAtClauseOrderCheck3.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputJavaDocTagContinuationIndentation.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputNonEmptyAtclauseDescription.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputNonEmptyAtclauseDescriptionSpaceSeq.java

Issue #15218: formatted input files for section 7.1.3 Block tags to follow google style guide rules

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/ParenPadCheck.xml
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForRecordPattern.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForRecordPatternWithSpaceOption.java
src/xdocs/checks/whitespace/parenpad.xml

closes #14948:
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/9046d995c208dc72ae20f27578851dfbd6057d50/check.xml
Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/9c0a6290200a700c8a363411f8fb577680f70f79/check_patch.xml
Diff Regression projects: https://gist.githubusercontent.com/mahfouz72/a3d0af030c8f5efd0d8a39f2c14750bc/raw/a3424ad9b6f722e5de1a927e3d85e383101b2b93/projects-to-test-on.properties

Issue #14948: Add support for record pattern syntax in ParenPadCheck

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationCommentIsAtTheEndOfBlock.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationInEmptyBlock.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationInSwitchBlock.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationSurroundingCode.java

Issue #15218: formatted input files for section 4.8.6.1 block comments style to follow google style guide rules

---

config/jsoref-spellchecker/whitelist.words
src/xdocs/beginning_development.xml
src/xdocs/config_system_properties.xml
src/xdocs/contributing.xml
src/xdocs/index.xml.vm
src/xdocs/writingchecks.xml
src/xdocs/writingjavadocchecks.xml.vm

Finished Pull Request #14730 which worked on improving grammar, spelling, and punctuation.

doc: improved grammar, spelling, and punctuation

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPosition.java

Issue #15218: Formatted input file for section 7.3.4 Non Required Javadoc to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputCorrectSummaryFragment.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputIncorrectSummaryFragment.java

Issue #15218: formatted input files for section 7.2 the summary fragment to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectJavadocParagraph.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectRequireEmptyLineBeforeBlockTagGroup.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectRequireEmptyLineBeforeBlockTagGroup.java

Issue #15218: formatted input files for section 7.1.2 paragraphs to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputMethodParamPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapArrayDeclarator.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapComma.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapEllipsis.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapMethodRef.java

Issue #15218: formatted input files for section 4.5.1 Where to break to follow google java style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/InputFieldAnnotations.java

Issue #15218: Formatted input file for section 4.8.5.4 Field Annotations to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputMethodsAndConstructorsAnnotations.java

Issue #15218: formatted input file for section 4.8.5.3 methods and constructors annotations to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule732exceptionoverrides/InputJavadocMethodAndMissingJavadocMethod.java

#15218 
https://checkstyle.org/google_style.html#a7.3.2

Issue #15218: Formatted input file for section 7.3.2 Exception Overrides to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule731selfexplanatory/InputJavadocMethodAndMissingJavadocMethod.java

#15218
https://checkstyle.org/google_style.html#a7.3.1

Issue #15218: formatted input file for section 7.3.1 self explanatory members to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputJavadocMethodAndMissingJavadocMethod.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeCorrect.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeIncorrect.java

#15218
https://checkstyle.org/google_style.html#a7.3

Issue #15218: formatted input files for section 7.3 Where javadoc is used to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputVerticalWhitespace.java

#15218
https://checkstyle.org/google_style.html#a4.6.1

Issue #15218: formatted input file for section 4.6.1 vertical whitespace to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule231filetab/InputWhitespaceCharacters.java

#15218
https://checkstyle.org/google_style.html#a2.3.1

Issue #15218: formatted input file for section 2.3.1 file tab to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputLeftCurlyAnnotations.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputLeftCurlyMethod.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputNonemptyBlocksLeftRightCurly.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurly.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile2.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOther.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCase.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCasesBlocks.java

#15218
https://checkstyle.org/google_style.html#a4.1.2

Issue #15218: formatted input files for section 4.1.2 Non Empty Blocks k & R Style to follow google style guide rules

---

src/xdocs/contributing.xml
src/xdocs/writingjavadocchecks.xml.vm

followup on https://github.com/checkstyle/checkstyle/pull/15146

doc: fixes for links

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputColumnLimit.java

Issue #15218: formatted input file for section 4.4 Column Limit to follow google style guide rules

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/InputUseOfOptionalBraces.java

Detected at: https://github.com/checkstyle/checkstyle/pull/15289#discussion_r1685473438

supplemental: added if (k != null) k = ss; example to InputUseOfOptionalBraces.java

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/FieldAnnotationsTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4854fieldannotations/InputFieldAnnotations.java

Issue #15214 Migrated section 4.8.5.4 Field Annotations to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule488numericliterals/NumericLiteralsTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule488numericliterals/InputNumericLiterals.java

Issue #15214: Migrated section 4.8.8 Numeric Literals to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/NonAsciiCharactersTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/InputNonAsciiCharacters.java

Issue #15214: Migrated section 2.3.3 Non Ascii Characters to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/ExactlyOneTopLevelClassDeclarationTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassBad2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassBasic.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/InputOneTopLevelClassGood.java

Issue #15214: Migrated section 3.4.1 Exactly One Top Level Class Declaration to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/MethodsAndConstructorsAnnotationsTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4853methodsandconstructorsannotations/InputMethodsAndConstructorsAnnotations.java

Issue #15214: Migrated section 4.8.5.3 Methods and constructors annotations to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/SpecialEscapeSequencesTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequences.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule233nonascii/InputNonAsciiCharacters.java

Issue #15214: Migrated section 2.3.3 Special Escape Sequences to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/NoWildcardImportsTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/InputNoWildcardImports.java

Issue #15214: Migrated section 3.3.1 No Wildcard Imports to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter2filebasic/rule231filetab/WhitespaceCharactersTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule231filetab/InputWhitespaceCharacters.java

Issue #15214: migrated section 2.3.1 Whitespace Characters to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/VerticalWhitespaceTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputVerticalWhitespace.java

Issue #15214: Migrated section 4.6.1 vertical whitespace to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule487modifiers/ModifiersTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputModifierOrder.java

Issue #15214: Migrated section 4.8.7 Modifiers to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4832nocstylearray/NoCstyleArrayDeclarationsTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4832nocstylearray/InputNoCstyleArrays.java

Issue #15214: Migrated section 4.8.3.2 No C Style Array Declarations to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java

#15214 
https://checkstyle.org/google_style.html#a4.3
>OneStatementPerLine
https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fcoding+path%3A**%2Fmessages*.properties+repo%3Acheckstyle%2Fcheckstyle+%22multiple.statements.line%22&type=code

Issue #15214: Migrated section 4.3 One statement per line to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/NoLineWrappingTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputNoLineWrapping.java

Issue #15214: Migrated section 3.3.2 No line wrapping to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/DeclaredWhenNeededTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/InputDeclaredWhenNeeded.java

#15214 
https://checkstyle.org/google_style.html#a4.8.2.2
>4.8.2.2 Declared when needed 	VariableDeclarationUsageDistance

Issue #15214: Migrated section 4.8.2.2 Declared when needed to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/PresenceOfTheDefaultLabelTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4843defaultlabelpresence/InputPresenceOfDefaultLabel.java

Issue #15214: migrated section 4.8.4.3 presence of the default label to whole config testing

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/nestedifdepth/InputNestedIfDepthInsideCaseBody.java

closes #15036
IMO, very unneeded input

Issue #15036: Add new input for nestedIfDepth

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/ColumnLimit100Test.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputColumnLimit.java

Issue #15214: Migrated section 4.4 Column Limit: 100 to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/WhereToBreakTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputMethodParamPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapComma.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapEllipsis.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapMethodRef.java

Issue #15214: migrated section 4.5.1 where to break to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/OneVariablePerDeclarationTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/InputOneVariablePerDeclaration.java

Issue #15214: Migrated section 4.8.2.1 one variable per declaration to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule521packagenames/PackageNamesTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521$packagenames/InputPackageBadName3.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521_packagenames/InputBadPackageName2.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule521packageNamesCamelCase/InputPackageNameBad.java

Issue #15214: migrated section 5.2.1 package names to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule522classnames/ClassNamesTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule522classnames/InputClassNames.java

Issue #15214: migrated section 5.2.2 class names to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule523methodnames/MethodNamesTest.java

issue #15214: migrated section 5.2.3 method names to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/NonConstantFieldNamesTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesBasic.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesSimple.java

issue #15214: migrated section 5.2.5 Non-constant field names to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/ParameterNamesTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputRecordComponentName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputCatchParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputLambdaParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterName.java

issue #15214: migrated section 5.2.6 parameter names to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/LocalVariableNamesTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputPatternVariableNameEnhancedInstanceofTestDefault.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputLocalVariableNameOneCharVarName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputLocalVariableNameSimple.java

Issue #15214: migrated section 5.2.7 local variable names to whole config testing

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/LocalFinalVariableNameCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/LocalVariableNameCheck.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/naming/PatternVariableNameCheckExamplesTest.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/patternvariablename/Example4.java
src/xdocs/checks/naming/localfinalvariablename.xml
src/xdocs/checks/naming/localfinalvariablename.xml.template
src/xdocs/checks/naming/localvariablename.xml
src/xdocs/checks/naming/localvariablename.xml.template
src/xdocs/checks/naming/patternvariablename.xml
src/xdocs/checks/naming/patternvariablename.xml.template

Issue #10971: Add example to show how to configure the check with different format for final and non-final pattern variables

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/TypeVariableNamesTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputRecordTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputClassTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputInterfaceTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputMethodTypeParameterName.java

Issue #15214: migrated section 5.2.8 type variable names to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule53camelcase/CamelCaseDefinedTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule53camelcase/InputCamelCaseDefined.java

Issue #15214: migrated section 5.3 camel case to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/CaughtExceptionsNotIgnoredTest.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/InputEmptyFinallyBlock.java

Issue #15214: migrated section 6.2 Caught exceptions not ignored to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/FinalizersNotUsedTest.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/InputNoFinalizeExtend.java

Issue #15214: migrated section 6.4 finalizers not used to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/BlockTagsTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck1.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck2.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputCorrectAtClauseOrderCheck3.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputIncorrectAtClauseOrderCheck1.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputIncorrectAtClauseOrderCheck2.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputIncorrectAtClauseOrderCheck3.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputJavaDocTagContinuationIndentation.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputNonEmptyAtclauseDescription.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule713atclauses/InputNonEmptyAtclauseDescriptionSpaceSeq.java

Issue #15214: migrated section 7.1.3 block tags to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/ParagraphsTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectRequireEmptyLineBeforeBlockTagGroup.java

Issue #15214: migrated section 7.1.2 paragraphs to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/WhereJavadocIsUsedTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputJavadocMethodAndMissingJavadocMethod.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeIncorrect.java

Issue #15214: migrated section 7.3 where javadoc is used to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule732exceptionoverrides/ExceptionOverridesTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule732exceptionoverrides/InputJavadocMethodAndMissingJavadocMethod.java

Issue #15214: migrated section 7.3.2 exception overrides to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule731selfexplanatory/ExceptionSelfExplanatoryMembersTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule731selfexplanatory/InputJavadocMethodAndMissingJavadocMethod.java

Issue #15214: migrated section 7.3.1 self explanatory members to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/TheSummaryFragmentTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputCorrectSummaryFragment.java

Issue #15214: migrated section 7.2 the summary fragment to whole config testing

---

.github/workflows/regression-report.yml

Issues #15394: Refactor new Github Workflow: regression-report.yml

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocAndInvalidJavadocPosition.java

Issue #15214: migrated section 7.1.1 general form to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/NonRequiredJavadocTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPosition.java

Issue #15214: migrated section 7.3.4 non required javadoc to whole config testing

---

.github/workflows/regression-report.yml

Remove condition for triggering new workflow on active PR

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/BlockCommentStyleTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationCommentIsAtTheEndOfBlock.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationInEmptyBlock.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationInSwitchBlock.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationSurroundingCode.java

Issue #15214: migrated section 4.8.6.1 block comment style to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/HorizontalWhitespaceTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputGenericWhitespace.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputGenericWhitespaceEndsTheLine.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputMethodParamPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeAnnotations.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeCaseDefaultColon.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeColonOfLabel.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeEmptyForLoop.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputParenPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundBasic.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundGenerics.java

#15214 
https://checkstyle.org/google_style.html#a4.6.2
>[WhitespaceAround](https://checkstyle.org/checks/whitespace/whitespacearound.html#WhitespaceAround)
[GenericWhitespace](https://checkstyle.org/checks/whitespace/genericwhitespace.html#GenericWhitespace)
[MethodParamPad](https://checkstyle.org/checks/whitespace/methodparampad.html#MethodParamPad)
[ParenPad](https://checkstyle.org/checks/whitespace/parenpad.html#ParenPad)
[WhitespaceAfter](https://checkstyle.org/checks/whitespace/whitespaceafter.html#WhitespaceAfter)
[NoWhitespaceBefore](https://checkstyle.org/checks/whitespace/nowhitespacebefore.html#NoWhitespaceBefore)
[NoWhitespaceBeforeCaseDefaultColon](https://checkstyle.org/checks/whitespace/nowhitespacebeforecasedefaultcolon.html#NoWhitespaceBeforeCaseDefaultColon)

Issue #15214: migrated section 4.6.2 horizontal whitespace to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/BlockIndentation2SpacesTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/ClassWithChainedMethods.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/ClassWithChainedMethodsCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputFastMatcher.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectAnnotationArrayInit.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectClass.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectFieldAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectForAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectIfAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectNewChildren.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectReturnAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectWhileDoWhileAndParameter.java

#15214
  | 4.2 Block indentation: +2 spaces | Indentation
-- | -- | --
4.2 Block indentation: +2 spaces 	[Indentation](https://checkstyle.org/checks/misc/indentation.html#Indentation)

Issue #15214: migrated indentation sections to follow whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule452continuationlines/IndentContinuationLinesAtLeast4SpacesTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/ClassWithChainedMethods.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/ClassWithChainedMethodsCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputFastMatcher.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectAnnotationArrayInit.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectClass.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectFieldAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectForAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectIfAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectNewChildren.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectReturnAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/InputIndentationCorrectWhileDoWhileAndParameter.java

#15214
[4.5.2 Indent continuation lines at least +4 spaces](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.5.2-line-wrapping-indent)

Issue #15214: migrated section 4.5.2 Indent Continuation Lines At Least +4 Spaces to whole config testing

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethodsCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFastMatcher.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectAnnotationArrayInit.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectClass.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectFieldAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectForAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectIfAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectNewChildren.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectReturnAndParameter.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectWhileDoWhileAndParameter.java

#15214
[4.8.4.1 Indentation](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.4.1-switch-indentation)

Issue #15214: migrated section 4.8.4.1 Indentation to follow whole config testing

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocksNoViolations.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByComment.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByVariableName.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyFinallyBlocks.java

#15218 
https://checkstyle.org/google_style.html#a4.1.3
>[EmptyBlock](https://checkstyle.org/checks/blocks/emptyblock.html#EmptyBlock)
[EmptyCatchBlock](https://checkstyle.org/checks/blocks/emptycatchblock.html#EmptyCatchBlock)

Issue #15218: formatted input files for section 4.1.3 empty blocks may be concise to follow google style guide rules

---

.github/workflows/regression-report.yml

New workflow shall run only active PRs

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeInPermitsList.java

Issue #15010: Add new input for sealed classes in IllegalTypeCheck

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/EmptyBlocksMayBeConciseTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocksNoViolations.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByComment.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByVariableName.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyFinallyBlocks.java

Issue #15213: migrated section 4.1.3 empty blocks may be concise to whole config testing

---

.github/workflows/regression-report.yml

Refactor egression-report.yml workflow shall run only active PRs before reacting and change emoji reaction if job fails

---

src/xdocs/google_style.xml

Issue #15329: update coverage table for 5.2.3 Method Name

---

src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequences.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule32packagestatement/InputPackageStatement.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule523methodnames/InputMethodName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule525nonconstantfieldnames/InputNonConstantNamesSimple.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputLambdaParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterName.java

Issue - 15218 more formatting

---

.github/workflows/regression-report.yml

Fix openPull issue

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundUnnamedPattern.java

Issue #15225: Add new input for unnamed pattern in whitespaceAroundCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterUnnamedPattern.java

Issue #15057: Add new input for unnamed pattern in whitespaceAfterCheck

---

src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule51identifiernames/RulesCommonToAllIdentifiersTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule51identifiernames/InputCatchParameterName.java
src/xdocs/google_style.xml

Fixes #15214 
It is final fix.
migrated section 5.1 to whole config testing additionally, updated it on coverage table: https://checkstyle.org/google_style.html#a5.1
removed the message, added module usage in place of it.

Issue #15214: migrated section 5.1 to whole config testing and updated it on coverage table

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/SuppressWarningsCheck.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsPatternVariables.java
src/xdocs/checks/annotation/suppresswarnings.xml

closes #15062 
Diff Regression config: https://gist.githubusercontent.com/mahfouz72/afd57aa6e51ca161b7927acd959e5211/raw/3eefa151f23d9c0754bcb6ed1c2c2ef73f45db9b/check.xml
Diff Regression patch config: https://gist.githubusercontent.com/mahfouz72/33967bf86e4a29cafa429771b0e95808/raw/8c95593d4d6db416055445b4e4dc43104c375aa9/check_patch.xml

Issue #15062: Add support for pattern variables in SuppressWarningCheck

---

.ci/google-java-format.sh
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputClassTypeParameterName.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputMethodTypeParameterName.java

#15449 
5.2.8 Type variable names
https://checkstyle.org/google_style.html#a5.2.8

Issue #15449: excluded rule528 from google-java-format.sh

---

.ci/google-java-format.sh

#15449
Test file: https://github.com/checkstyle/checkstyle/blob/master/src/it/java/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/ParagraphsTest.java

Issue #15449: partially excluded rule712paragraphs from google-java-format.sh

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/SimplifyBooleanReturnCheck.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/InputSimplifyBooleanReturnWithYield.java
src/xdocs/checks.xml
src/xdocs/checks/coding/index.xml
src/xdocs/checks/coding/simplifybooleanreturn.xml
src/xdocs/checks/coding/simplifybooleanreturn.xml.template

Issue #15040: Add support for yield in SimplifyBooleanReturnCheck

---

.ci/google-java-format.sh

#15449
https://checkstyle.org/google_style.html#a6.4

Issue #15449: excluded rule64 from google-java-format.sh

---

.ci/google-java-format.sh
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectIfAndParameter.java

#15449 
https://checkstyle.org/google_style.html#a4.2

Issue #15449: partially excluded rule42 from google-java-format.sh

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSealedClasses.java

Issue #15108: Add new input file for sealed classes in indentation check

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/WhereToBreakTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputLambdaBodyWrap.java

Issue #4006
Extend inputs for [4.5.1 Where to break](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.5.1-line-wrapping-where-to-break) section with lambda cases.

Issue #4006: add inputs with lambda cases

---

.ci/google-java-format.sh

#15449 
Partially excluded rule462 from google-java-format.sh

Issue #15449: exlcuded rule462 from google-java-format.sh

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/VerticalWhitespaceTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule461verticalwhitespace/InputFormattedVerticalWhitespace.java

#15340
https://checkstyle.org/google_style.html#a4.6.1

Issue #15340: created InputFormatted file for section 4.6.1 Vertical Whitespace

---

src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules/CheckWhichThrowsError.java
src/test/resources/com/puppycrawl/tools/checkstyle/checker/InputChecker.java

Issue #11446: Updated testHaltOnExceptionOff in CheckerTest

---

src/main/resources/google_checks.xml
src/xdocs/filters/suppressionxpathfilter.xml
src/xdocs/filters/suppressionxpathfilter.xml.template

detected at: https://github.com/checkstyle/checkstyle/issues/15429#issuecomment-2293967608
corrected example queries

doc: updated documentation for suppressionxpathfilter

---

.ci/google-java-format.sh

#15449
removed whole folder names from grep list and used individual file names instead.

Issue #15449: removed whole folder reference and added individual file names to be grepped in google-java-format.sh

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule487modifiers/ModifiersTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputFormattedModifierOrder.java

#15340 
[4.8.7 Modifiers](https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html#s4.8.7-modifiers)

Issue #15340: created InputFormatted file for section 4.8.7 Modifiers

---

src/xdocs/index.xml.vm

Issue #13293: Add supported Java Language Level to website

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/SourceFileStructureTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/InputFormattedSourceFileStructure.java

Issue #15340: created InputFormatted file for section 3 Source File

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/ParagraphsTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedCorrectJavadocParagraph.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedCorrectRequireEmptyLineBeforeBlockTagGroup.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedIncorrectJavadocParagraph.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedIncorrectRequireEmptyLineBeforeBlockTagGroup.java

Issue #15340: created InputFormatted file for section 7.1.2 Paragraphs

---

config/checkstyle-non-main-files-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/NoLineWrappingTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputFormattedNoLineWrapping.java

#15340 
this section's input file did not had much code and most of the imports were unused to formatter removed them in InputFormatted file

Issue #15340: created InputFormatted file for section 3.3.2 No Line Wrapping

---

.ci/diff-report.sh
.github/workflows/regression-report.yml
config/jsoref-spellchecker/whitelist.words

Update the new workflow to add regression testing for input java files and configs in PR description

---

.github/workflows/regression-report.yml

Fix the error of the new workflow

---

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/OrderingAndSpacingTest.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacing1.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacing2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacing3.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacing4.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacing5.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacingNoImports.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacingValid.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputFormattedOrderingAndSpacingValid2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing1.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing2.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacing3.java
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputOrderingAndSpacingValid2.java

Issue #15340: created InputFormatted files for section 3.3.3 Ordering And Spacing

---

.github/workflows/regression-report.yml

Fix the new workflow and Optimise it

---

.github/workflows/regression-report.yml

Fix the error message

---

.github/workflows/regression-report.yml

Failure of make_report in new workflow does not produce comment in PR

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule53camelcase/CamelCaseDefinedTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule53camelcase/InputFormattedCamelCaseDefined.java

Issue #15340: created InputFormatted file for section 5.3 Camel Case Defined

---

config/checkstyle-resources-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter5naming/rule522classnames/ClassNamesTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule522classnames/InputFormattedClassNames.java

Issue #15340: created InputFile for section 5.2.2 Class Names

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/NonRequiredJavadocTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputFormattedInvalidJavadocPosition.java

Issue #15340: created InputFormatted file for section 7.3.4 non required javadoc

---

.github/workflows/regression-report.yml

Restoring label feature in new workflow regression-report.yml

---

.circleci/config.yml

 Issue #15475: Re-enable no-error-pmd validation

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/OneVariablePerDeclarationTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4821onevariableperline/InputFormattedOneVariablePerDeclaration.java

Issue #15340: created inputFormatted file for section 4.8.2.1 One variable per declaration

---

.ci/google-java-format.sh
src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/InputNoWildcardImports.java

~~#15340~~ #15449 
~~added extra code so formatter does not remove unused imports~~
excluded rule331nowildcard from google-java-format.sh

Issue #15340: created inputformatted file for section 3.3.1 No wild card imports

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/spotbugs-exclude.xml
src/main/java/com/puppycrawl/tools/checkstyle/gui/ListToTreeSelectionModelWrapper.java

continuation of https://github.com/checkstyle/checkstyle/pull/15574

minor: workaround spotbugs violation MC_OVERRIDABLE_METHOD_CALL_IN_CONSTRUCTOR

---

.ci/google-java-format.sh
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java

Issue #15340
alternative to https://github.com/checkstyle/checkstyle/pull/15591
issue is created on formatter - https://github.com/google/google-java-format/issues/1155

Issue #15340: created InputForamtted file for section 4.8.4.2 Fall through commented

---

.ci/google-java-format.sh
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/InputDeclaredWhenNeeded.java

Issue #15340: created inputformatted file for section 4.8.2.2 declared when needed

---

.ci/google-java-format.sh
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule411optionalbracesusage/InputUseOfOptionalBraces.java

~~#15340~~ #15449 
~~the formatted file contains many new violations regarding indentation~~
excluded section 4.1.1 from google-java-format.sh

Issue #15449: excluded rule411optionalbracesusage from google-java-format.sh

---

config/jsoref-spellchecker/whitelist.words
docs/NEW_LANGUAGE_FEATURE_INTEGRATION_PROCESS.md

closes #14923: 
GH view: https://github.com/mahfouz72/checkstyle/blob/doc-improvements/docs/NEW_LANGUAGE_FEATURE_INTEGRATION_PROCESS.md

Issue #14923: Improvements for language feature integration documents

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example2.java
src/xdocs/checks/misc/todocomment.xml

update TodoComment to show how to use ignore case in format property

---

.ci/google-java-format.sh
src/it/java/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/EmptyBlocksMayBeConciseTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyFinallyBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputFormattedEmptyBlocksAndCatchBlocks.java

Issue #15340: created InputFormatted file for section 4.1.3 Empty blocks may be concise

---

.ci/google-java-format.sh
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputClassWithChainedMethods.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputClassWithChainedMethodsCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedClassWithChainedMethods.java

#15340
PR is very large due to large amount of input files, I'm waiting for approval on this PR and after that I will send 2 other PRs for remaining indentation section as they also have same input files.
PS: the original and formatted files might be very similar to each other as all the original files didn't contained violations expect ClassWithChainedMethods.java

Issue #15340: created inputFormatted file for section 4.8.4.1 Indentation

---

.github/workflows/regression-report.yml

Create a cache cleanup in regression-report.yml

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/emptystatement/InputEmptyStatement.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/emptystatement/Example1.java
src/xdocs/checks/coding/emptystatement.xml

Issue #15456: Specify violation messages for EmptyStatementCheck

Issue #15456: Specify violation messages for EmptyStatementCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassConstructorInRecord.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassNestedInRecord.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassNestedStaticClassInsideInnerClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassAnonymousInnerClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassEnum.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassInnerAndNestedClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassInterface.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassNestedInEnumWithAnonInnerClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassNestedInInterfaceWithAnonInnerClass.java

Issue #15456 : Specify violation messages for FinalClassCheck

Issue #15456: Specify violation messages for FinalClassCheck

---

.github/workflows/regression-report.yml

regression-report.yml can not find Input path

---

.github/workflows/regression-report.yml

regression-report.yml should generate label at handle_generated_config section

---

src/xdocs/checks/misc/todocomment.xml
src/xdocs/checks/misc/todocomment.xml.template

Issue #15605: update description of TODO Check

---

config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/FallThroughCheck.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough8.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughInlineSingleCase.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughLastLineCommentCheck.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughMultipleReliefPatterns.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughWithoutReliefPattern.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/Example1.java
src/xdocs/checks/coding/fallthrough.xml
src/xdocs/checks/coding/fallthrough.xml.template

Issue: #13553
Finishing #14734 and [this review](https://github.com/checkstyle/checkstyle/pull/14734#discussion_r1597719839) by restoring the original wording and adding some about putting any other comment on the same line.

Issue #13553: Finished false positive in FallThroughCheck on last case

---

src/xdocs/cmdline.xml.vm
src/xdocs/config_system_properties.xml

I15089 windows system properties

---

.github/workflows/regression-report.yml

regression-report.yml should generate label at handle_existing_config_bundle

---

.github/workflows/regression-report.yml

regression-report.yml patch config issue

---

pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java

Fixes https://github.com/checkstyle/checkstyle/issues/15636
~~Depends on https://github.com/checkstyle/checkstyle/issues/15637~~

Issue #15636: Update CheckerTest.java to use @TempDir instead of java.io.File#createTempFile

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs/google_style.xml

#14968 
Updated coverage table to follow new rules/style. Updated its test in XdocsPagesTest to work accordingly new changes, it is still WIP. 
~~Draft PR to let the maintainers first review the website look, after that, will proceed further~~
PS: I have also fixed some inconsistent line breaks in `Checkstyle Configs` column.

Issue #14968: Updated coverage table to follow new rules and updated its validation test

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/newlineatendoffile/Example4.cpp
src/xdocs/checks/misc/newlineatendoffile.xml
src/xdocs/checks/misc/newlineatendoffile.xml.template

convert example4.py into example4.cpp #15651

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoiddoublebraceinitialization/InputAvoidDoubleBraceInitialization.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoiddoublebraceinitialization/Example1.java
src/xdocs/checks/coding/avoiddoublebraceinitialization.xml

Issue #15456: Specify violation messages for AvoidDoubleBraceInitialization

---

src/it/resources/com/google/checkstyle/test/chapter5naming/rule523methodnames/InputMethodName.java
src/main/resources/google_checks.xml

https://github.com/checkstyle/checkstyle/issues/15609

Issue #15609: Fix overly-lenient google_checks MethodName SuppressionXpathSingleFilter

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputFormattedEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputParenPad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4852classannotations/InputClassAnnotations.java
src/main/resources/google_checks.xml
src/xdocs/checks/regexp/regexpsinglelinejava.xml
src/xdocs/checks/regexp/regexpsinglelinejava.xml.template
src/xdocs/google_style.xml

#15642 
Diff Regression config: https://gist.githubusercontent.com/Zopsss/eef363a452104d034a9ce7be532f647d/raw/1b640e394ffa67af6e2cf1fa56d08a63b6d252d1/master_google_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Zopsss/95df70ba9ccdb5cf49758dba527582d8/raw/99fbd0c9dbb80f6431fc6a49c96a1878ddbdc0cf/suppressed_false_positives_google_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/Zopsss/9960953f88e763d31eea3a14447b861f/raw/edfd96ea7a5757cea2e08856be98776cbb21a171/guava-project.properties

Issue #15642: suppressed false-positive curly braces violations in google_checks.xml

---

.github/workflows/regression-report.yml
config/jsoref-spellchecker/whitelist.words

Part #15665
Moved to follow up PR:
Update for comments action 
Defect on new module mode

regression-report.yml should be independent of checkstyle/contribution and diff.groovy

---

.github/workflows/regression-report.yml

Remove the existing comment option in regression-report

---

.github/workflows/regression-report.yml

Incorporate the place for new_module_config.xml missing new module config

---

.github/workflows/regression-report.yml

Investigate step Setup local maven cache in regression-report.yml

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectJavadocParagraph.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java

#15503
added test cases for issue 15503

supplemental: tests for #15503

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/Example2.java
src/xdocs/checks/javadoc/javadocparagraph.xml
src/xdocs/checks/javadoc/javadocparagraph.xml.template

Issue #13345: enable JavadocParagraphCheckExamplesTest

---

.github/workflows/regression-report.yml

Add new argument --diffToolJarPath to DiffTool command for regression-report.yml

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionModifiedControlVariableTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifiedcontrolvariable/InputXpathModifiedControlVariableNestedSkipEnhancedForLoop.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifiedcontrolvariable/InputXpathModifiedControlVariableNestedWithFor.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifiedcontrolvariable/InputXpathModifiedControlVariableNestedWithForeach.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifiedcontrolvariable/InputXpathModifiedControlVariableSkipEnhancedForLoop.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifiedcontrolvariable/InputXpathModifiedControlVariableWithFor.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifiedcontrolvariable/InputXpathModifiedControlVariableWithForeach.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #6207: Add XPath IT Regression Test for ModifiedControlVariable

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/InputAvoidNestedBlocksAllowInSwitchCase.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/InputAvoidNestedBlocksDefault.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/Example2.java
src/xdocs/checks/blocks/avoidnestedblocks.xml

Issue #15456: Specify violation message for Nested Block

Issue #15456: Specify violation message for Nested Block  

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionClassDataAbstractionCouplingTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classdataabstractioncoupling/InputXpathClassDataAbstractionCouplingClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classdataabstractioncoupling/InputXpathClassDataAbstractionCouplingEnum.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classdataabstractioncoupling/InputXpathClassDataAbstractionCouplingInterface.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #6207: add class data abstraction coupling xpath regression tests

---

config/checkstyle-resources-suppressions.xml
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputFormattedIncorrectJavadocParagraph.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCheck1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect3.java

Issue #15713: updated JavadocParagraph's input files based on issue description

---

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilter.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressionSingleFilter.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressionXpathSingleFilter.xml
src/xdocs/filters/suppressionsinglefilter.xml
src/xdocs/filters/suppressionsinglefilter.xml.template
src/xdocs/filters/suppressionxpathsinglefilter.xml
src/xdocs/filters/suppressionxpathsinglefilter.xml.template

Hi,
while reading documentation for [SuppressionFilter](https://checkstyle.org/filters/suppressionfilter.html) and [SuppressionXpathSingleFilter](https://checkstyle.org/filters/suppressionxpathsinglefilter.html) I found several sentences difficult to read due to grammatical errors.
Here is my attempt to fix it.

doc: Fix wording in SuppressionSingleFilter and SuppressionXpathSingleFilter

---

src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectJavadocParagraph.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect2.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckExamplesTest.java

Issue #15733: Added support for column number in JavadocParagraph's violation messages

---

.ci/checker-framework.groovy
src/main/resources/google_checks.xml

spelling: suppresion -> suppression

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSuppressWarningsTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsAnnotationDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsAnnotationFieldDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsClassDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsEnumConstantDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsEnumDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsInterfaceDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsMethodDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsParameterDefinition.java
src/it/resources/org/checkstyle/suppressionxpathfilter/suppresswarnings/InputXpathSuppressWarningsVariableDefinition.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Part of #6207 
Added XPath IT Regression Tests for [SuppressWarnings](https://checkstyle.org/checks/annotation/suppresswarnings.html#SuppressWarnings)

Issue #6207: Added XPath IT Regression Tests for SuppressWarnings

---

.github/workflows/regression-report.yml

not for merge.
https://github.com/checkstyle/checkstyle/pull/15704

infra: attempt to use action caches

---

.ci/diff-report.sh
.github/workflows/regression-report.yml

Yml regreport-regresson.yml should use yml files for list of projects

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/CliOptionsXdocsSyncTest.java
src/xdocs/cmdline.xml.vm

Closes #14759 
Reused code from #14799, and added anchor image  (as per https://github.com/checkstyle/checkstyle/pull/14799#issuecomment-2356627003)

Issue #14759: Updated Command Line Options in table format

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/UpperEllCheck.xml
src/xdocs/checks/misc/upperell.xml
src/xdocs/checks/misc/upperell.xml.template

Issue #15763: fixed UpperEll's paragraphs

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCasesBlocks.java

fix for https://github.com/checkstyle/checkstyle/actions/runs/11293075217/job/31410402810

minor: fixed until #xxxx issue number in InputRightCurlySwitchCasesBlocks.java

---

.github/workflows/README.md
config/jsoref-spellchecker/whitelist.words

related to https://github.com/checkstyle/checkstyle/issues/15380
We can not use folders due to https://github.com/orgs/community/discussions/18055

minor: Update workflows/README.md to let it work for all workflows

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidinlineconditionals/InputAvoidInlineConditionals.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidinlineconditionals/Example1.txt
src/xdocs/checks/coding/avoidinlineconditionals.xml

Issue #15456: Specify violation messages for AvoidInlineConditionals

---

.ci/google-java-format.sh
src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/NonemptyBlocksKrStyleTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedTryCatchIfElse.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedTryCatchIfElse2.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputTryCatchIfElse.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputTryCatchIfElse2.java

supplemental for PR: https://github.com/checkstyle/checkstyle/pull/15779
part of issue #15664

supplemental: Issue #15664 - Added test cases for NonemptyBlocksKrStyleTest

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/interfaceistype/InputInterfaceIsType.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/interfaceistype/InputInterfaceIsTypeAllowMarker.java

Issue #15456: Specify violation messages for interfaceistype

---

pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java

Issue #15541: Add new isOfType that accepts List of Integers as parameter

---

.ci/google-java-format.sh
src/it/java/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/BlockIndentation2SpacesTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputFormattedIndentationCodeBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCodeBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4822declaredwhenneeded/InputDeclaredWhenNeeded.java
src/main/resources/google_checks.xml
src/xdocs/google_style.xml

part of #15769
- added suppression
- updated documentation
- added test cases for separate code blocks
---
Diff Regression config: https://gist.githubusercontent.com/Zopsss/eef363a452104d034a9ce7be532f647d/raw/3a36ba1cad81f3dff628f24c1c9b1591a2c5ef78/master_google_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Zopsss/4d1852aea0ab161ad746e43f9ee3362d/raw/eec7d9700e3b3b78fff0954566d392be6f937846/block_code_indentation_google_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/015aff9c00dd09b2b9db3f72951bc61f/raw/9891630875ee62e6f8a2975721841e8d80536d4d/Projects.properties
Too big:
https://gist.githubusercontent.com/Zopsss/22adadb570e4deb95296917244c580b3/raw/144d72ee70de11891eabe4a342cbb0da37153a20/projects-to-test-on-for-github-action. …

Issue #15769: added suppression for separate code blocks and updated documentation

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/NonemptyBlocksKrStyleTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedTryCatchIfElse.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedTryCatchIfElse2.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputTryCatchIfElse.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputTryCatchIfElse2.java

part of #15664 
added some more test cases & updated formatted files

supplemental: Issue #15664 - Added some more test cases

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/Example3.java
src/xdocs/checks/coding/declarationorder.xml
src/xdocs/checks/coding/declarationorder.xml.template

Issue #13345: Enabled DeclarationOrderCheckExamplesTest

---

.github/workflows/google-java-format.yml
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4842fallthrough/InputFallThrough.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputFormattedCommentsIndentationInSwitchBlock.java

https://github.com/google/google-java-format/releases/tag/v1.24.0

dependency: update google formatter to 1.24.0

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMutableExceptionTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/mutableexception/InputXpathMutableExceptionClassName.java
src/it/resources/org/checkstyle/suppressionxpathfilter/mutableexception/InputXpathMutableExceptionDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/mutableexception/InputXpathMutableExceptionExtendedClassName.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

For #6207 
Added tests for [Mutable Exception](https://checkstyle.org/checks/design/mutableexception.html#MutableException)

Issue #6207: Added XPath regression test for MutableException

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionLocalVariableNameTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/localvariablename/InputXpathLocalVariableNameInnerClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/localvariablename/InputXpathLocalVariableNameIteration.java
src/it/resources/org/checkstyle/suppressionxpathfilter/localvariablename/InputXpathLocalVariableNameMethod.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue: #6207  
[LocalVariableName check documentation](https://checkstyle.org/checks/naming/localvariablename.html#LocalVariableName)

Issue #6207: Expanded regression testing for LocalVariableName

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFileInUnnamedPackage.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsRecordsAndCompactCtors.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsSingleWordPackage.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsArrayRef.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsCheckClearState.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromJavaLang.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsJavadocQualifiedName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsShadowed.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/Example2.java
src/xdocs/checks/imports/unusedimports.xml

Issue #15456: Specify violation messages for UnusedImportsCheck

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCasesBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
src/xdocs/google_style.xml

minor: added refernce of issues 15791 & 15792 in google style coverage table for section 4.1.2 KR blocks

---

config/jsoref-spellchecker/whitelist.words
src/main/resources/google_checks.xml

Mauryan Kansara - My real name
Zops - alias name which I use for all of my social medias and GitHub

minor: added my name in google_checks.xml

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/EmptyBlockCheck.xml
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckExamplesTest.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/Example3.java
src/xdocs/checks/blocks/emptyblock.xml
src/xdocs/checks/blocks/emptyblock.xml.template

continuation of https://github.com/checkstyle/checkstyle/pull/15366

doc: update doc for EmptyBlock and extend example

---

src/site/resources/css/site.css

Issue #15809: make div font to be same as p

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainBeginTreePackage2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/Example1.txt
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/Example2.txt
src/xdocs/checks/misc/uncommentedmain.xml

Issue #15456: Specify violation messages for UncommentedMain

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/Example2.java
src/xdocs/checks/coding/arraytrailingcomma.xml

Issue #15456 
- Added Violation Messages: Custom violation messages have been implemented for ArrayTrailingComma to improve readability and usability.
- Updated Suppression List: The ArrayTrailingCommaCheck has been removed from the suppression list.

Issue #15456: Specify violation messages for ArrayTrailingComma

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionClassTypeParameterNameTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classtypeparametername/InputXpathClassTypeParameterNameClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classtypeparametername/InputXpathClassTypeParameterNameInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classtypeparametername/InputXpathClassTypeParameterNameMethod.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #6207: Added XPath regression test for ClassTypeParameterName

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/ConstructorsDeclarationGroupingCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/constructorsdeclarationgrouping/Example2.java
src/xdocs/checks/coding/constructorsdeclarationgrouping.xml

Issue #15829: Added test class for ConstructorsDeclarationGrouping

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/Example2.java
src/xdocs/checks/coding/explicitinitialization.xml
src/xdocs/checks/coding/explicitinitialization.xml.template

**Summary**
This pull request aims to enable example tests for the ExplicitInitializationCheck in the project. The implementation focuses on ensuring that the ExplicitInitializationCheck checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

Issue #13345: Enable examples tests for ExplicitInitializationCheck

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java

Part of #14814 : ```findMatch``` method in RegexpCheck.java

Issue #14814: refactor recursive findmatch method into iterative method

---

config/checker-framework-suppressions/checker-index-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/SinglelineDetector.java

Part of #14814 : ```checkLine``` method in SinglelineDetector.java

Issue #14814: refactor recursive checkline into iterative method

---

src/xdocs/releasenotes.xml

LineWrapping for few lines in releasenotes.xml

minor : LineWrapping for few lines in releasenotes.xml

---

docs/BEGINNING_DEVELOPMENT.md

Creates a "beginning development" document in github, loosely based on https://checkstyle.org/beginning_development.html.  
https://github.com/nrmancuso/checkstyle/blob/beginning-development/docs/BEGINNING_DEVELOPMENT.md

doc: BEGINNING_DEVELOPMENT.md

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java

part of #14814 : containsStaticField in HiddenFieldCheck

Issue #14814: refactor containsStaticField into iterative method

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/Example1.java
src/xdocs/checks/coding/missingctor.xml
src/xdocs/checks/coding/missingctor.xml.template

**Summary**
This pull request aims to enable example tests for the **MissingCtorCheck** in the project. The implementation focuses on ensuring that the covariant equals checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

Issue #13345: Enable examples tests for MissingCtorCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyle.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleNestedGenerics.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleOff.java

Issue: https://github.com/checkstyle/checkstyle/issues/15456
Specify violation messages for ArrayTypeStyleCheck

Issue checkstyle#15456: Specify violation messages for ArrayTypeStyleCheck

---

.github/GSOC.md

Issue #15845
all that I can understand from https://github.com/checkstyle/checkstyle/pull/14514#discussion_r1503050685 and all below

Issue #15845: impove wording based on PR comments

---

src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java

minor: Removed tail recursion

---

config/intellij-idea-inspections.xml
config/jsoref-spellchecker/whitelist.words
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

Resolves #14625 
Similar to how pmd handles this method , mentioned at https://github.com/checkstyle/checkstyle/pull/14812#discussion_r1573117201
Tested on: 
```
Version: 2022.3.3
Build: 223.8836.41
Released: 8 March 2023
```
Which is the latest idea  docker image version inside CircleCI's --> https://github.com/checkstyle/checkstyle/blob/master/.circleci/config.yml

Issue #14625: fix noinspectionreason for TestMethodWithoutAssertion

---

src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundWhen.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundWhen.java
src/main/resources/google_checks.xml

Issue #15851
Diff Regression config: https://raw.githubusercontent.com/checkstyle/checkstyle/refs/heads/master/src/main/resources/google_checks.xml
Diff Regression patch config: https://raw.githubusercontent.com/checkstyle/checkstyle/2b51ddc169412cdbdd347746a860629f74dac55e/src/main/resources/google_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/43e3ccdd18eea023a3d0e405b64a5414/raw/345cb17301fe37544e56d659306395ca1a4e9a8f/guava-project.properties

Issue #15851: suppress LeftCurlyNl for switch expressions

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSeparatorWrapTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/separatorwrap/InputXpathSeparatorWrapClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/separatorwrap/InputXpathSeparatorWrapInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/separatorwrap/InputXpathSeparatorWrapMethod.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #6207: Added XPath regression test for SeparatorWrap

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java

part of #14814 : removed tail-recursion from `walkConditional`

Issue #14814: refactor walkConditional into iterative method

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/NeedBracesCheck.xml
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example4.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example5.java
src/xdocs/checks/blocks/needbraces.xml
src/xdocs/checks/blocks/needbraces.xml.template

Fixes: #3619
Continuation of #14133

Issue #3619: NeedBraces need clear description of allowSingleLineStatement

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckDefaultTokens.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckMultipleExceptions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckSuperclassException.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatchCheckSuperclassThrowable.java

Issue #15456: Specify violation messages for IllegalCatch

Issue #15456: Specify violation messages for IllegalCatch

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes2.java

Issue #15456: Specify violation messages for FinalParametersCheck

Issue #15456: Specify violation messages for FinalParametersCheck

---

.ci/print-diff-as-patch.sh
.github/workflows/checker-framework.yml
.github/workflows/pitest.yml

Issue #15837: print diff as patch

---

config/jsoref-spellchecker/whitelist.words
src/xdocs/index.xml.vm

from https://github.com/checkstyle/checkstyle/issues/9118#issuecomment-1258422174

doc: add check-tfij-style project to 'Additional Checks'

---

src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/api/fullident/InputFullIdentLiteralNewCondition.java

part of #14814 
- converted extractFullIdent into iterative method
- added test case for 100% branch coverage 
diffs: https://github.com/checkstyle/checkstyle/pull/15904#issuecomment-2469701116

Issue #14814: refactor extractFullIdent into iterative method

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocParagraphCheck.xml
src/xdocs/checks/javadoc/javadocparagraph.xml
src/xdocs/checks/javadoc/javadocparagraph.xml.template

Issue #15865: list block-tags for JavadocParagraphCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/InputSealedShouldHavePermitsListInnerClass.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/InputSealedShouldHavePermitsListInnerInterface.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/InputSealedShouldHavePermitsListJepExample.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/InputSealedShouldHavePermitsListTopLevelSealedClass.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/InputSealedShouldHavePermitsListTopLevelSealedInterface.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/sealedshouldhavepermitslist/Example1.java
src/xdocs/checks/design/sealedshouldhavepermitslist.xml

Issue #15456: Specify violation messages for SealedShouldHavePermitsListCheck

Issue #15456: Specify violation messages for SealedShouldHavePermitsListCheck

---

src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/Example2.java
src/xdocs/checks/metrics/npathcomplexity.xml
src/xdocs/checks/metrics/npathcomplexity.xml.template

**Summary**
This pull request aims to enable example tests for the **NPathComplexityCheck** in the project. The implementation focuses on ensuring that NPathComplexity checks are correctly validated through comprehensive test cases, improving overall code reliability and quality.

Issue #13345: Enable examples tests for NPathComplexityCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation2.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckExamplesTest.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/Example1.java
src/xdocs/checks/annotation/packageannotation.xml

Issue #15456 
Violation messages for PackageAnnotationCheck

Issue #15456: Define violation messages for PackageAnnotationCheck

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionHideUtilityClassConstructorTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/hideutilityclassconstructor/InputXpathHideUtilityClassConstructorDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/hideutilityclassconstructor/InputXpathHideUtilityClassConstructorPublic.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #6207 
Add XPath IT Regression Testing for HideUtilityClassConstructor

Issue #6207: Expand XPath IT Regression Testing for HideUtilityClassConstructor

---

src/site/site.xml
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

resolves #14840 : added test to ensure Group, check and filter names are in alphabetical order

Issue #14840: test to ensure alphabetical order on the website

---

.github/workflows/run-checkstyle.yml

Issue #15955: run checkstyle by github action

---

.github/workflows/run-checkstyle.yml

Issue #15955: improve output of run-checkstyle.yml

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionClassFanOutComplexityTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classfanoutcomplexity/InputXpathClassFanOutComplexityClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classfanoutcomplexity/InputXpathClassFanOutComplexityEnum.java
src/it/resources/org/checkstyle/suppressionxpathfilter/classfanoutcomplexity/InputXpathClassFanOutComplexityInterface.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

For Issue #6207 
ClassFanOutComplexityCheck: https://checkstyle.sourceforge.io/checks/metrics/classfanoutcomplexity.html

Issue #6207: Add XPath Regression Testing For ClassFanOutComplexityCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableAnonInnerClasses2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableAnonInnerClasses3.java

Aims to close #11374
Based on abandoned #12795

Issue #11374: Fix false positive related to anon inner classes in UnusedLocalVariableCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noarraytrailingcomma/InputNoArrayTrailingComma.java

Issue #15456 : Define violation messages for NoArrayTrailingCommaCheck

Issue #15456: Define violation messages for NoArrayTrailingCommaCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclarationRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclaration.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/Example2.java
src/xdocs/checks/coding/unnecessarysemicolonafteroutertypedeclaration.xml

Issue #15456,
Specify violation message for UnnecessarySemicolonAfterOuterTypeDeclaration

Issue #15456: Specify violation message for UnnecessarySemicolonAfterOuterTypeDeclaration

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noclone/InputNoClone.java

Issue #15456 : Specify violation messages for NoCloneCheck

Issue #15456: Specify violation messages for NoCloneCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingCommaOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingCommaThree.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingCommaTwo.java

Issue #15456 : Specify violation messages for NoEnumTrailingCommaCheck

Issue #15456: Specify violation messages for NoEnumTrailingCommaCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicoloninenumeration/InputUnnecessarySemicolonInEnumeration.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicoloninenumeration/Example1.java
src/xdocs/checks/coding/unnecessarysemicoloninenumeration.xml

Issue: #15456
Specify violation message for UnnecessarySemicolonInEnumeration

Issue #15456: Specify violation message for UnnecessarySemicolonInEnumeration

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue: #14631 
**Command**:
`
**Test.java**
```
/**
* @throws IOException connection problems
*/
}
```
```
KIIT0001@BT01290 MINGW64 /c/git-repositories/class_Name_AST
|   |   |--COMMENT_CONTENT -> *\r\n * @throws IOException connection problems\r\n
|   |   |       |   |--THROWS_LITERAL -> @throws
|   | …
```

Issue #14631: Updated CLASS_NAME to new AST format

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefault2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefaultLF.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example4.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/Example5.java
src/xdocs/checks/blocks/emptycatchblock.xml

Issue: #15456 
Specify violation message for EmptyCatchBlock

Issue #15456: Specify violation message for EmptyCatchBlock

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerHasFinalizer.java

Issue #15456: Specify violation messages for NoFinalizerCheck

Issue #15456: Specify violation messages for NoFinalizerCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue: #14631
` java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
**Test.java**
```
/**
* @throws IOException if <b>connection</b> problems occur
*/
}
```
```
Souvik@souviks MINGW64 ~/Desktop/checkStylee/HTML Element AST
|   |   |--COMMENT_CONTENT -> *\r\n * @throws IOException if <b>connection</b> problems occur\r\n …
```

Issue #14631: Updated HTML_ELEMENT in JavadocTokenTypes.java  to new AST format

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java

Issue #15456
Message update for noncompilable resource file InputOneStatementPerLine.java
Related to PR #16104

Issue #15456: Update violation message for OneStatementPerLine

---

src/site/xdoc/checks.xml
src/site/xdoc/filters/index.xml
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

Issue #16013: test to ensure alphabetical order at summary pages

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters4One.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters4Two.java

Resolves update for InputAvoidEscapedUnicodeCharacters4 #11163

Issue #11163: Enforce file size on InputAvoidEscapedUnicodeCharacters4

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionDesignForExtensionTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/designforextension/InputXpathDesignForExtensionClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/designforextension/InputXpathDesignForExtensionWithEnum.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

For Issue https://github.com/checkstyle/checkstyle/issues/6207
DesignForExtensionCheck : https://checkstyle.org/checks/design/designforextension.html

Issue #6207: Add Xpath Regression Testing for DesignForExtensionCheck

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRedundantModifierTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/redundantmodifier/InputXpathRedundantModifierClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/redundantmodifier/InputXpathRedundantModifierInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/redundantmodifier/InputXpathRedundantModifierWithEnum.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

For Issue #6207
RedundantModifierCheck : https://checkstyle.org/checks/modifier/redundantmodifier.html

Issue #6207: Add Xpath Regression Testing for RedundantModifierCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java

clarification for https://github.com/checkstyle/checkstyle/pull/16130#issuecomment-2581610660

minor: clarify output of test for debug mode

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/import-control.xml
src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java
src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java
src/main/java/com/puppycrawl/tools/checkstyle/site/ParentModuleMacro.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java
src/test/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParserTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CliOptionsXdocsSyncTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsUrlTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XdocUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFor.java

Issue #16155: migration to nio jdk api

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/InputSimplifyBooleanReturnWithYield.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/InputSimplifyBooleanReturn.java

Issue https://github.com/checkstyle/checkstyle/issues/15456: Specify violation messages for InputSimplifyBooleanReturnCheck

Issue #15456: Specify violation messages for InputSimplifyBooleanReturnCheck

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodThrowsDetectionOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodThrowsDetectionTwo.java

Resolves update for InputJavadocMethodThrowsDetection in #11163 
Also removed  "//ok"  from InputJavaDocThrowsDetection

Issue #11163: Enforce file size on InputJavadocMethodThrowsDetection

---

config/checkstyle-resources-suppressions.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/InputJavadocPackageClass.java

Issue #11163 
Resolves the file size from exceeding 120 lines and removed related suppressions

Issue #11163: Enforce file size on InputJavadocPackageNoJavadoc

---

src/site/resources/css/site.css

part of #16077
made code blocks scroll-able. Changes are noticeable in smaller devices.

Issue #16077: made code blocks scroll-able

---

src/site/resources/js/checkstyle.js

Issue #16178: added target=_blank to open external links in new tab

---

.github/workflows/site.yml

Rockets action does not work for long
https://github.com/checkstyle/checkstyle/pull/16184#issuecomment-2597331204

infra: Update site.yml to remove steps that are not doing anything

---

.github/workflows/site.yml

works https://github.com/checkstyle/checkstyle/actions/runs/12845109212
now we can debug this action in PR branch, without merges.

infra: trigger action site.yml manually

---

src/site/xdoc/checks/coding/illegalthrows.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsIgnoreMethodNames.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsNotIgnoreOverriddenMethod.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestClassNames.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestIllegalClassNames.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/Example4.java

Issue: #15456 
Specify Violation messages for IllegalThrowsCheck

Issue #15456: Specify Violation messages for IllegalThrowsCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

#14631 
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed -E "s/[[0-9]+:[0-9]+]//g"
**Test.java**
```
/**
*/
}
```
**Output**
```
java -jar checkstyle-10.21.1-all.jar Test.java -J | sed -E "s/\[[0-9]+:[0-9]+\]//g"
|   |   |--COMMENT_CONTENT -> *\n * @see #method(Processor, String)\n  
|   |   |       |--WS ->   
|   |   |       |--JAVADOC_TAG -> JAVADOC_TAG 
|   |   |       |   |--SEE_LITERAL -> @see 
|   |   |       |   |--REFERENCE -> REFERENCE …
```

Issue #14631 : Update parameters in JavadocTokenTypes

---

src/site/xdoc/config.xml

improvement based on https://github.com/checkstyle/checkstyle/issues/15820#issuecomment-2602791333

minor: clarify that severity ignore is for all loggers/formatters

---

src/site/xdoc/checks/coding/innerassignment.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentSwitchAndSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentDemoBug1195047Comment3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentMethod.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentNotInLoopContext.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/Example1.java

Issue: #15456
Specify violation messages for coding.InnerAssignmentCheck

Issue #15456: Specify violation messages for inner assignments

---

src/site/resources/css/site.css
src/site/site.xml

Reverts checkstyle/checkstyle#16213

Revert "Issue #16077: Removed text under banner images in menu"

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

#14631 
java -jar checkstyle-10.21.1-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
**Test.java**
```
/**
* @serial serialized company name
*/
}
```
```
prave@DESKTOP-ONMIJ3B MINGW64 /e/Projects/TestProject
|   |   |--COMMENT_CONTENT -> *\r\n * @serial serialized company name\r\n
|   |   |       |   |--SERIAL_LITERAL -> @serial
|   |   | …
```

Issue #14631: Updated SERIAL_LITERAL in JavadocTokenTypes.java to new format of AST

---

config/jsoref-spellchecker/whitelist.words
src/site/resources/css/site.css

#16077 
The newer theme had small fonts, made the font size a bit bigger and changed the font family to the old site's font family.

minor: made website font size bigger

---

azure-pipelines.yml

supplemental: disable locale runs until #16233

---

src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCasts1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCasts2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCasts3.java

supplemental #14872: test cases

---

src/site/resources/css/site.css
src/site/resources/js/checkstyle.js

#16077 
fixed followings:
> not clear why some text under section has different indentation from left
and 
> in mobile mode reduce left and right margin, to increase space for text as much as possible.
---
Both of these issues were related to padding and margin so fixed them both in one PR.

Issue #16077: fixed large margins and paddings

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtorEmptyClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtorNestedClasses.java

Issue: #15456: Specify violation messages for MissingCtorcheck

Issue #15456: Missing Ctor check

---

config/checkstyle-examples-suppressions.xml
src/site/xdoc/checks/imports/avoidstarimport.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowStaticMember.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportExcludes.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/Example4.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/Example5.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/Example6.java

Issue #15456 
Added violation messages for avoidStarImportCheck violation

Issue #15456 Specify violation message for AvoidStarImportCheck

---

src/site/xdoc/checks/imports/avoidstaticimport.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault5.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/Example2.java

Added violation message for AvoidStaticImportCheck.

Issue #15456: Specify violation message for AvoidStaticImportCheck

---

config/pitest-suppressions/pitest-javadoc-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java

part of #13999 
WIP
https://github.com/checkstyle/checkstyle/blob/977c425e633414fec09952bb3bb887a937ce8157/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L39-L55
https://github.com/checkstyle/checkstyle/blob/977c425e633414fec09952bb3bb887a937ce8157/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L21-L28

Issue #13999: kill mutation for javadocMethodCheck-2

---

src/site/resources/css/site.css
src/site/resources/js/anchors.js
src/site/site.xml

This pull request solves the issue #16243, where the header image was larger than intended and also the red line was not touching the top of the page. The changes include:
Fixing the size of header image.
Adjusting the CSS to ensure the red line aligns properly with the top of the page.
Thank you.
Issue Link: 
Fixes: #16243

Fix header image size and red line alignment 

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameSimpleOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameSimpleThree.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameSimpleTwo.java

Issue https://github.com/checkstyle/checkstyle/issues/11163
Resolves the file size from exceeding 120 lines and removed related suppressions.

Issue #11163: Enforce file size on MemberNameCheck

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionDescendantTokenTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/descendanttoken/InputXpathDescendantTokenNestedSwitch.java
src/it/resources/org/checkstyle/suppressionxpathfilter/descendanttoken/InputXpathDescendantTokenSwitchNoDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/descendanttoken/InputXpathDescendantTokenSwitchTooManyCases.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java

Issue #6207: Add Xpath Regression Testing for DescendantTokenCheck
https://checkstyle.org/checks/misc/descendanttoken.html#DescendantToken

Issue #6207: Add Xpath Regression Testing for DescendantTokenCheck

---

src/site/xdoc/checks.xml

Rules:
1) The issue you are trying to fix/resolve has to have the "approved" label.
2) Put in the description of Pull Request the reference to an issue if it exists.
Example: "Issue: #XXXXXX"
3) Commit message should adhere to the following rules:
a) MUST match one of the following patterns:
^Issue #\\d+: .*$
^Pull #\\d+: .*$
^(minor|config|infra|doc|spelling|dependency): .*$
b) MUST contain only one line of text
c) MUST NOT end with a period, space, or tab
d) MUST be less than or equal to 200 characters
To avoid multiple iterations of fixes and CIs failures, please read
https://checkstyle.org/contributing.html
ATTENTION: We are not merging Pull Requests that are not passing our CIs,
but we will help to resolve issues.
Thanks for reading, remove whole this message and type what you need.

Removed duplicate

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue: #14631 
**Test.java**
```java
/**
* @throws IOException if <b>connection</b> problems occur
*/
}
```
**command used**
```bash
java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
```
**command output**
```bash
|   |   |--COMMENT_CONTENT -> *\n * @throws IOException if <b>connection</b> problems occur\n
|   |   |       |--NEWLINE -> \n
|   |   |       |   |--THROWS_LITERAL -> @throws
|   |   |       |   |--CLASS_NAME -> IOException
|   |   | …
```

Issue #14631: update DESCRIPTION to new AST format

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable2One.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable2Two.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAnonymousClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAssignedInsideAndOutsideSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAssignedMultipleTimes.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableBreak.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableEnhancedForLoopVariable.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableEnhancedForLoopVariable2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFalsePositives.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFive.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFour.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameShadowing.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableThree.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableTwo.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation messages for `FinalLocalVariableCheck`

Issue #15456: Define violation message for FinalLocalVariableCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterName2.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation messages for `CatchParameterNameCheck`

Issue #15456: Specify violation message for CatchParameterNameCheck

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/InputTodoCommentSimpleOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/InputTodoCommentSimpleTwo.java

Part of Issue #11163 
- Enforced file size on TodoComment

Issue #11163: Enforce file size on TodoComment

---

.github/workflows/run-checkstyle.yml

https://github.com/checkstyle/checkstyle/actions/runs/13264902278

infra: use javac in run-checkstyle.yml

---

.github/workflows/run-checkstyle-ast-print.yml

same as https://github.com/checkstyle/checkstyle/pull/16305
run with compile error: https://github.com/checkstyle/checkstyle/actions/runs/13286532466
Passed: https://github.com/checkstyle/checkstyle/actions/runs/13290220284/job/37108884650

infra: add option to do javac on file before ast print

---

config/jsoref-spellchecker/whitelist.words
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckBlockCommentBegin.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckBlockCommentEnd.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckCommentsContent.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckDefaultTokenLabel.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckSingleLineComment.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckSwitchAndPostIncDec.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokensCheckTokenNative.java

Issue checkstyle#15456: illegal token check

---

src/site/xdoc/checks/blocks/needbraces.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitchAllowSingleLine.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSwitchExpressionAndLambda.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSwitchExpressionAndLambdaAllowSingleLine.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSwitchExpression.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSwitchExpressionNoSingleLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesLoopBodyFalse.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesLoopBodyTrue.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineStatements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestCaseDefaultNoSingleLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestConditions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestIt.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestItWithAllowsOn.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestNotAllowSingleLineLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSingleLineCaseDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSingleLineLambda.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/Example6.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation message for `NeedBracesCheck`

Issue #15456: Define violation message for NeedBracesCheck

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderItOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderItTwo.java

Issue #11163
Resolves the file size from exceeding 120 lines and removed related suppressions.

Issue #11163: Enforce file size on ModifierOrderCheck

---

src/site/resources/css/site.css

detected at: https://github.com/checkstyle/checkstyle/pull/16301#issuecomment-2650722041

minor: removed extra margin-left of codeblocks

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderTypeAnnotationsOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderTypeAnnotationsTwo.java

Issue https://github.com/checkstyle/checkstyle/issues/11163
Resolves the file size from exceeding 120 lines and removed related suppressions.

Issue #11163: Enforce file size on Annon ModifierOrderCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountCustomMaxCount.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountMethodWithAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountNotIgnorePrivateMethods.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation message for `ThrowsCountCheck`

Issue #15456: Define violation message for ThrowsCountCheck

---

config/jsoref-spellchecker/whitelist.words
src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue: https://github.com/checkstyle/checkstyle/issues/14631
**Test.java**
```
/**
* <p>Paragraph Tag.</p>
*/
public void testFunction(String value) {
}
}
```
`java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
`
**Output:**
```
DELL@DESKTOP-KL8FGN8 MINGW64 ~/SLASH_TOKEN
$ java -jar checkstyle-10.21.2-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
|--METHOD_DEF -> METHOD_DEF [5:4]
|   |--MODIFIERS -> MODIFIERS [5:4]
|   |   |--BLOCK_COMMENT_BEGIN -> /* [2:4]
|   |   | …
```

Issue #14631: Updated P_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format 

---

config/pitest-suppressions/pitest-common-suppressions.xml
config/pmd-main.xml
src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java

Issue #15821: remove usage of synchronized block

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressions.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressionsTwo.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation message for `MissingSwitchDefaultCheck`

Issue #15456: Violation message for MissingSwitchDefaultCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/nestedifdepth/InputNestedIfDepthInsideCaseBody.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedifdepth/InputNestedIfDepthDefault.java

Issue #15456: violation message for NestedIfDepthCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecords.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecords2.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecords3.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecordsAndCompactCtors.java

Issue #15683: resolved false positive on compact constructors for nested record classes

Issue #15683: Resolved JavadocMethod Issue

---

config/checkstyle-input-suppressions.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorCommentsWithEmoji.java

Issue #13213 
@romani , I've opened this PR as per your request in [this review comment](https://github.com/checkstyle/checkstyle/pull/16374#pullrequestreview-2629806718).

Issue #13213: unresolved '//ok' comments for singlespaceseparator module

---

src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphCheck1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrectOpenClosedTag2.java

Issue #15762 :
added a check for children node indentation validation

Issue #15762: resolved javadoc issue

---

config/checkstyle-input-suppressions.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPad2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPadToCheckTrimFunctionInOptionProperty.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPadToCheckUppercaseFunctionInOptionProperty.java

Issue #13213: Remove '//ok' comments for emptyforiteratorpad module

---

config/checkstyle-input-suppressions.xml

Issue #13213: Remove suppressions for javadoctype module

---

config/checkstyle-input-suppressions.xml
src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexponfilename/InputRegexpOnFilenameSemantic.java

Issue #13213: Remove '//ok' comments for regexponfilename module

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/InputNoCodeInFile3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/InputNoCodeInFile5.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/Example2.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation message for `NoCodeInFileCheck`

Issue #15456: Violation message for NoCodeInFileCheck

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierItOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierItTwo.java

Issue https://github.com/checkstyle/checkstyle/issues/11163
Resolves the file size from exceeding 120 lines and removed related suppressions.

Issue #11163: Enforce file size on RedundantModifierCheck

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthSimpleTwo.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation message for `MethodLengthCheck`

Issue #15456: Violation message for MethodLengthCheck

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexitySwitchBlocks6.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexityWhenSwitchAsSinglePoint.java

Issue #16165: fix CyclomaticComplexity's switchBlockAsSingleDecisionPoint to properly handle switch blocks

---

.github/workflows/set-milestone-on-referenced-issue.yml

Issue #16414: make github wirkflow to be triggered manually

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableInterface.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameLambda.java

Issue #16081: Resolved FinalLocalVariable bug ,
- Fixed the issue where PARAMETER_DEF in FinalLocalVariable check was not working as expected in interfaces.
- Updated logic to correctly handle parameters inside interface methods.
- Added necessary test cases to verify correct behavior.

Issue #16081: Resolved FinalLocalVariable Bug

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/Example2.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Define violation message for `FileLengthCheck`

Issue #15456: Violation message for FileLengthCheck

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSkipIfLastAndSharedWithCaseOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSkipIfLastAndSharedWithCaseTwo.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastTwo.java

Issue #11163 
Enforced 120 lines on two files 1.InputDefaultComesLast  2.InputDefaultComesLastSkipIfLastAndSharedWithCase by splitting them into two files and updated the test cases.

Issue #11163: Enforce file size on DefaultComesLastCheck

---

.ci/validation.sh
config/jsoref-spellchecker/whitelist.words

reverted changes in validation.sh as discussed in :
https://github.com/checkstyle/checkstyle/pull/16319#issuecomment-2688019646

 reverted changes in validation.sh

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLine.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckInterfaceAndEnum.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckPublicMethodAndVariable.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckTokensOnMethodAndVar.java

Issue #15161:
resolved FalseNegative when the annotation is on the same line of the modifer of the target class.

Issue #15161: Resolved False Negative at AnnotationOnSameLine

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneInnerAndWithArguments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperClonePlainAndSubclasses.java

Issue https://github.com/checkstyle/checkstyle/issues/15456 : Violation message for `SuperCloneCheck`

Issue #15456: Violation message for SuperCloneCheck

---

config/pitest-suppressions/pitest-main-suppressions.xml
pom.xml

Issue #14019: Kill mutation for getVersionString()

---

config/pitest-suppressions/pitest-javadoc-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfoTest.java

Issue #13999
Kill mutation for `JavadocTagInfo$11`.

Issue #13999: kill mutation for JavadocTagInfo$11

---

config/pitest-suppressions/pitest-javadoc-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfoTest.java

Reverts checkstyle/checkstyle#16434

Revert "Issue #13999: kill mutation for JavadocTagInfo$11"

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressionsOne.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressionsTwo.java

Issue https://github.com/checkstyle/checkstyle/issues/11163

Issue #11163: Enforce file size on EmptyBlocks

---

config/pitest-suppressions/pitest-javadoc-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfoTest.java

Reverts checkstyle/checkstyle#16471

Revert "Revert "Issue #13999: kill mutation for JavadocTagInfo$11""

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
pom.xml

dependency: bump checkerframework.version from 3.48.4 to 3.49.1

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersFinal.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersPrivateFinal.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersPublicProtectedStatic.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestEnhancedInstanceof.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeArrays.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeEmptyStringMemberModifiers.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeNewArrayStructure.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileNameFalsePositive.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestAbstractClassNamesTrue.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestClearDataBetweenFiles.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestDefaults.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestExtendsImplements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestFormat.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestGenerics.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestIgnoreMethodNames.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestLegalAbstractClassNames.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestMemberModifiers.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestPlainAndArraysTypes.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestSameFileNameGeneral.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestStarImports.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestStaticImports.java

Issue #15456: Specified violation messages for IllegalTypeCheckTest

Issue #15456: Specified violation messages for IllegalTypeCheckTest

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault7.java

Issue #15456: violation messages for IllegalImportCheck

Issue #15456: violation messages for IllegalImportCheck

---

src/site/xdoc/checks/naming/classtypeparametername.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/InputClassTypeParameterName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/InputClassTypeParameterName1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/Example3.java

Issue: #15456
**src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java**
`"com.puppycrawl.tools.checkstyle.checks.naming.ClassTypeParameterNameCheck"`
**Tests passed**
```
public class ClassTypeParameterNameCheckExamplesTest extends AbstractExamplesModuleTestSupport {
@Override
protected String getPackageLocation() {
return "com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername";
}
@Test
public void testExample1() throws Exception {
final String pattern = "^[A-Z]$";
final String[] expected = {
"14:18: " + getCheckMessage(MSG_ILLEGAL_ABSTRACT_CLASS_NAME, "t", pattern),
"15:18: " + getCheckMessage(MSG_ILLEGAL_ABSTRACT_CLASS_NAME, "abc", pattern),
"16:18: " + getCheckMessage(MSG_ILLEGAL_ABSTRACT_CLASS_NAME, "LISTENER", pattern),
"17:18: " + …
```

Issue #15456: Defined violation message for ClassTypeParameterName in InlineConfigParser.java

---

pom.xml

Issue #16396: Use bom artifact for junit version management

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #14631 
**Command used  check if rendering is good**
`mvn clean site -Pno-validations`
**Screenshot of successful rendering**

Issue #14631: Updated escaping to non-escaping in JavadocTokenTypes.java to new AST.

---

config/pitest-suppressions/pitest-common-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java

Issue #14019: Kill mutation for getSourceName in writeFileError

---

src/site/xdoc/index.xml.vm

Adding missing remarks in the "Additional Checks" table in the documentation.
Issue: #16149 
-> Added remarks for Checkstyle Addons, SevNTU Checkstyle, and Check-TFIJ-Style in 'index.xml.vm'.
-> No functional changes are made, only documentation updates.
-> Ensured correct formatting.

Fix: Add missing remarks in Additional Checks table

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/pitest-suppressions/pitest-main-suppressions.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/Main.java

Issue #14019: Kill mutation for getImplementationVersion in runCli

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java

Issue #16358: Update HeaderCheckTest to use verifyWithInlineConfigParser method

Issue #16358: Update HeaderCheckTest to use verifyWithInlineConfigParser method

---

azure-pipelines.yml
src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java

Solves : #16233
Reverted https://github.com/checkstyle/checkstyle/pull/16234 to verify

Issue #16233: test execution is failing on non EN locales

---

config/jsoref-spellchecker/whitelist.words
src/site/resources/css/site.css
src/site/resources/js/checkstyle.js
src/site/site.xml

Updated PR that solves the issue where syntax highlighting is performed at runtime using JavaScript.
Fixes: #16300

Issue #16300: Updated Move Syntax Highlighting to Site Generation Phase

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

issue: #14631
**Test.java**
```
/**
* <table><tbody></tbody></table>
*/
}
```
```
noman@ANIS MINGW64 /d/zaid/zaid/codes/checkstyle/TBODY AST
|   |   |--COMMENT_CONTENT -> *\r\n * <table><tbody></tbody></table>\r\n
|   |   |       |   `--HTML_TAG -> HTML_TAG …
```

Issue #14631: Updated TBODY in JavadocTokenTypes.java to new AST format

---

src/site/xdoc/checks/naming/typename.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeNameRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName6.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/Example3.java

**Issue**: #15456
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
"**com.puppycrawl.tools.checkstyle.checks.naming.TypeNameCheck**"

Defined violation message for TypeNameCheck in InlineConfigParser.java Type

---

src/site/xdoc/checks/naming/interfacetypeparametername.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername/InputInterfaceTypeParameterName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername/InputInterfaceTypeParameterName1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername/Example2.java

Issue: [#15456](https://github.com/checkstyle/checkstyle/issues/15456) 
**src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java**
`"com.puppycrawl.tools.checkstyle.checks.naming.InterfaceTypeParameterNameCheck"`
**Tests passed**
```
public class InterfaceTypeParameterNameCheckExamplesTest extends AbstractExamplesModuleTestSupport {
@Override
protected String getPackageLocation() {
return "com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername";
}
@Test
public void testExample1() throws Exception {
final String[] expected = {
"14:29: " + getCheckMessage(MSG_INVALID_PATTERN, "t", "^[A-Z]$"),
};
verifyWithInlineConfigParser(getPath("Example1.java"), expected);
}
@Test
public void testExample2() throws Exception {
final String[] expected = {
"17:28: " + …
```

Issue #15456: Defined violation message for InterfaceTypeParameterName in InlineConfigParser

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue : #14631
**Test.java**
```
/**
* 
*/
}
```
**Terminal output**
```
(base) kapishyadavbanda@Kapishs-MacBook-Pro BodyTag % java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
COMPILATION_UNIT -> COMPILATION_UNIT [7:0]
`--CLASS_DEF -> CLASS_DEF [7:0]
|--MODIFIERS -> MODIFIERS [7:0]
|   |--BLOCK_COMMENT_BEGIN -> /* [1:0]
|   |   |--COMMENT_CONTENT -> *\n * \n  [1:2]
|   |   |   `--JAVADOC -> JAVADOC [1:3]
|   |   |       |--NEWLINE -> \n [1:3]
|   |   |       |--LEADING_ASTERISK ->  * [2:0]
|   |   |       |--TEXT ->   [2:2]
|   |   |       |--HTML_COMMENT -> HTML_COMMENT [2:3]
|   |   |           |--HTML_COMMENT_START ->  [5:3]
|   | …
```

Issue #14631: Updated HTML_COMMENT_START and HTML_COMMENT_END of JavadocTokenTypes to new AST Format

---

config/pitest-suppressions/pitest-common-suppressions.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java

Issue #14019: Kill mutation for getImplementationVersion in XMLLogger

---

src/site/xdoc/checks/naming/membername.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberName7.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameExtended.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameInner.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameSimpleOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/InputMemberNameSimpleThree.java
src/test/resources/com/puppycrawl/tools/checkstyle/grammar/InputGrammar.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/naming/membername/Example3.java

Issue #15456: Defined violation message for MemberNameCheck

Issue #15456 Defined violation message for MemberNameCheck

---

config/pitest-suppressions/pitest-javadoc-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocLeaveToken.java

part of #13999
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/f5a524a06294d907c84b9fc5b68661dc/raw/604872961df92db35e66c26218dc74c61bb10097/config.xml
https://github.com/checkstyle/checkstyle/blob/e1dc3abaa59f522ffafb200aa7ae4c2ced7a64c0/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L3-L10
https://github.com/checkstyle/checkstyle/blob/e1dc3abaa59f522ffafb200aa7ae4c2ced7a64c0/config/pitest-suppressions/pitest-javadoc-suppressions.xml#L12-L19

Issue #13999: Kill mutation for AbstractJavadocCheck

---

.github/workflows/remainder-bot.yml

Fixes Issue #15770 
This PR adds checkstyle repository condition in the remainder bot workflow.

Reaminder Bot: Adding repository checkstyle condition

---

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java

supplemental for Issue #16385 
As suggested in:
https://github.com/checkstyle/checkstyle/pull/16518/files/b5c5d220672fcee1fa648a46a9508fae3c48f3a7#r1991745459

supplemental: Issue #16385 -resolved JavadocTag bug

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableName1one.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableName1two.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableName2one.java

Issue #11163: Enforce file size on LocalVariableName

Issue #11163: Enforce file size on LocalVariableName

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

prerequisite for: https://github.com/checkstyle/checkstyle/pull/16435

Pull #16560: improve logging

---

src/site/xdoc/google_style.xml

English is not my first language either, but hopefully this helps a bit.

minor: wording fixes in Google guidelines documentation

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpressionWithWhen.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java

Issue: #15456 
I've updated the code to make the violations more specific wherever they were already mentioned. However, there are still places where violations could be added but were not explicitly marked. Please review and let me know if further updates are needed.

Issue #15456: Specify violation messages for SimplifyBooleanExpressionCheck

---

config/pitest-suppressions/pitest-ant-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java

Part of #14019 
**Target Mutation**
https://github.com/checkstyle/checkstyle/blob/e0481fee2cc6f50f29d488c345419f64bb7449d5/config/pitest-suppressions/pitest-ant-suppressions.xml#L192-L199

Issue #14019: Remove suppresion for pitest-ant profile.

---

src/site/xdoc/checks/misc/upperell.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/upperell/InputUpperEllSemantic.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/upperell/Example1.java

**Issue #15456: fix Upper Ell Check**

Issue #15456: fix Upper Ell Check

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias3.java

Issue: #6637  
Determined the problem is in isSuppressed() method.

Issue #6637: Fixed SuppressWarningsHolder aliasList

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue : #14631
**Test.java**
```
/**
* <colgroup><col span="2"></colgroup>
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\n * <colgroup><col span="2"></colgroup>\n  
|   |   |       |   `--COLGROUP -> COLGROUP 
|   |   |       |       |--COLGROUP_TAG_START -> COLGROUP_TAG_START 
|   |   |       |       |   |--START -> <  …
```

Issue #14631: Update COLGROUP_HTML_TAG_NAME to new AST format

---

config/pitest-suppressions/pitest-ant-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java

part of #14019 
**Target Mutation :** 
https://github.com/checkstyle/checkstyle/blob/5495106a50a0fdb3a4f9bee1280c14b4a5417dea/config/pitest-suppressions/pitest-ant-suppressions.xml#L93-L109

Issue #14019: Remove suppression for pitest-ant profile : execute()

---

src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsJavadocAboveComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodAboveComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleAboveComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeAboveComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariableAboveComment.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodAboveComments.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeAboveComments.java

closes #43
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/f5a524a06294d907c84b9fc5b68661dc/raw/604872961df92db35e66c26218dc74c61bb10097/config.xml

Issue #43: Javadoc should be detected above block comment

---

src/site/xdoc/index.xml.vm

Issue #16157: Populated Empty Cells in Active tool

---

.ci/no-exception-test.sh
.ci/validation.sh
.travis.yml

Pull #16608: align xmx args

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/upperell/InputUpperEllSemantic.java

**Issue #11163** 
Refactored InputUpperEllSemantic.java file into some files to reduce it's size

Issue #11163: Enforce upper ell file size

---

config/pitest-suppressions/pitest-utils-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java

Issue #14019 
Diff Regression config: https://gist.githubusercontent.com/Abdelrhmansersawy/a260374764de47cf113461589afb63fb/raw/d85d2b2a5fff191ac8a6a4eda54f28e108aa5888/config.xml

Issue 14019: Kill Mutation For ScopeUtil

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #14631
**Test.java**
```
/**
* <table>
*     <tr>Table Row</tr>
* </table>
*/
```
```
v@SIMRAN MINGW64 ~/TR_HTML_TAG_NAME
|   |   |--COMMENT_CONTENT -> *\r\n * <table>\r\n *     <tr>Table Row</tr>\r\n * </table>\r\n
|   |   |       |   `--HTML_TAG -> HTML_TAG …
```

Issue #14631: Updated TR_HTML_TAG_NAME to new AST format

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #14631 
**Test.java**
```
/**
* <tr>
*     <td>Cell 1</td>
* </tr>
*/
}
```
```
v@SIMRAN MINGW64 ~/TD_HTML_TAG_NAME
|   |   |--COMMENT_CONTENT -> *\r\n * <tr>\r\n *     <td>Cell 1</td>\r\n * </tr>\r\n
|   |   |       |   `--TR -> TR …
```

Issue #14631: Updated TD_HTML_TAG_NAME to new AST format

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SummaryJavadocCheck.xml
src/site/xdoc/checks/javadoc/summaryjavadoc.xml
src/site/xdoc/checks/javadoc/summaryjavadoc.xml.template

Added the additional clarification about the Javadoc summary use.

doc: Clarified the description of SummaryJavadoc check

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #14631 
`java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
`
**Test.java**
```
/**
* <dl>
*     <dt>Java</dt>
*     <dd>A high-level programming language.</dd>
* </dl>
*/
}
```
```
v@SIMRAN MINGW64 ~/DD_HTML_TAG_NAME
|   |   |--COMMENT_CONTENT -> *\r\n * <dl>\r\n *     <dt>Java</dt>\r\n *     <dd>A high-level programming language.</dd>\r\n * </dl>\r\n
| …
```

Issue #14631: Updated DD_HTML_TAG_NAME to new AST format

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

minor: fix checkstyle violation leaked by prev commit

---

README.md

Issue #12742: Added Missing Badges in the README file

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

issue #14631
Command Used
```java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"```
Test.java
```
/**
* <td>Cell Content</td>
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\r\n * <td>Cell Content</td>\r\n
|   |   |       |   `--TD -> TD
|   |   |       |       |--TD_TAG_START -> TD_TAG_START
|   |   |       |       |   |--START -> < …
```

Issue #14631: Updated TR_TAG_END in JavadocTokenTypes.java to new AST format

---

.ci/generate-extra-site-links.sh
config/jsoref-spellchecker/whitelist.words
src/site/resources/js/anchors.js

Issue #14857: Github generate site fails to generate links with anchors

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue#14631
java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
**Test.java**
```
/**
* <input name="Name" type="text" placeholder="Enter your name"/>
*/
}
```
```
yukti@LAPTOP-P8NBSFE2 MINGW64 ~/INPUT_HTML_TAG_NAME
|   |   |--COMMENT_CONTENT -> *\r\n * <input name="Name" type="text" placeholder="Enter your name"/>\r\n
|   |   |       |--HTML_ELEMENT -> …
```

Issue #14631: Updated INPUT_HTML_TAG_NAME to new AST format

---

.ci/validation.sh

This PR references Issue #16671

Issue #16671: Reverted changes made to no-error-xwiki

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #14631
`java -jar checkstyle-10.21.4-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"
`
**Test.java**
```
/**
* <dl>
*     <dt>Java</dt>
* </dl>
*/
}
```
```
v@SIMRAN MINGW64 ~/DT_HTML_TAG_NAME
|   |   |--COMMENT_CONTENT -> *\r\n * <dl>\r\n *     <dt>Java</dt>\r\n * </dl>\r\n
|   |   |       |   `--HTML_TAG -> HTML_TAG …
```

Issue #14631: Updated DT_HTML_TAG_NAME to new AST format

---

src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleErrorColumn0.sarif
src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/InputSarifLoggerErrorColumn0.java

Part of Issue #16361 
Update `testAddErrorAtColumn0` test case in `SarifLoggerTest` to use verifyWithInlineConfigParserAndLogger

Issue #16361: Update SarifLoggerTest.java to use verifyWithInlineConfigParserAndLogger

---

docs/GRAMMAR_UPDATES.md

very small piece of change in sentence structure for better clarity.

minor: correction in GRAMMAR_UPDATES.md

---

azure-pipelines.yml

fixes https://github.com/checkstyle/checkstyle/issues/16793

infra: Update azure-pipelines.yml to use ubuntu-24.04

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

Issue #14631
`java -jar checkstyle-10.23.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"`
```
/**
* <head>
*   <title>Page Title</title>
*   <meta charset="UTF-8">
* </head>
*/
}
```
```
$ java -jar checkstyle-10.23.0-all.jar -J Test.java | sed "s/\[[0-9]\+:[0-9]\+\]//g"COMPILATION_UNIT -> COMPILATION_UNIT
|   |   |--COMMENT_CONTENT -> *\r\n * <head>\r\n *   <title>Page Title</title>\r\n *   <meta charset="UTF-8">\r\n * </head>\r\n
|   |   |       |   `--HEAD -> HEAD …
```

Issue #14631: Updated HEAD_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

---

config/suppressions.xml

references issue #11166 
reason of PR:
this suppression was unnecessarily residing there.

config: removed unnecessary suppression for GetFileContents Method in suppression.xml

---

.semaphore/semaphore.yml

https://checkstyle.semaphoreci.com/jobs/1b3e1222-0968-4ff8-ade0-925659f6adbf
so it is periodically stuck in execution, might be related to CI , not a nondex

Infra disable nondex

---

config/checker-framework-suppressions/checker-formatter-suppressions.xml
pom.xml

part of #14084  
Disabling the Formatter Checker as discussed at  #16690

Issue #14084: Disable Formatter checker

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/VariableDeclarationUsageDistanceCheck.xml
src/site/xdoc/checks/coding/variabledeclarationusagedistance.xml
src/site/xdoc/checks/coding/variabledeclarationusagedistance.xml.template

doc: improve variableDeclarationUsageDistanceChec's docs to avoid confusion

---

.github/workflows/check-pr-description.yml
.github/workflows/no-old-refs.yml
.github/workflows/release-new-milestone-and-issues-in-other-repos.yml
.github/workflows/release-publish-releasenotes-twitter.yml
.github/workflows/release-update-github-page.yml
.github/workflows/release-upload-all-jar.yml
.github/workflows/releasenotes-gen.yml
.github/workflows/run-link-check.yml
.github/workflows/set-milestone-on-referenced-issue.yml
azure-pipelines.yml

Pull #16829: align ubuntu image version `ubuntu-22.04` -> `ubuntu-24.04`
10 
vs.
15

Pull #16829: align ubuntu image version `ubuntu-22.04` -> `ubuntu-24.04`

---

azure-pipelines.yml

fixes: https://github.com/checkstyle/checkstyle/pull/16829#discussion_r2040661339
`no need to move to Travis , let is sit in semaphore.`

Pull #16841: infra: verify-no-exception-configs is in semaphore ci

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava4.java

Issue #11163 
Reduced file size for `InputIndentationFromGuava2.java` and `InputIndentationFromGuava.java`. All files in `Indentation` folder are now under 120 lines of code.

Issue #11163: Enforce file size for InputIndentationFromGuava

---

README.md
config/jsoref-spellchecker/whitelist.words

doc: remove SonarCloud badge from README.md

---

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java

issue #14631 
Command Used
```
java -jar checkstyle-10.21.0-all.jar -J Test.java | sed "s/[[0-9]+:[0-9]+]//g"
```
Test.java
```
/**
* <body>
*     <p>Body Content</p>
* </body>
*/
}
```
```
|   |   |--COMMENT_CONTENT -> *\r\n * <body>\r\n *     <p>Body Content</p>\r\n * </body>\r\n
|   |   |       |   `--BODY -> BODY
|   |   |       |       |--BODY_TAG_START -> BODY_TAG_START
|   | …
```

Issue #14631: Updated BODY_HTML_TAG_NAME in JavadocTokenTypes.java to new AST format

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java

Issue #16882
Change AtomicInteger to int according to given issue.
Here is the "mvn clean verify" results below:

Issue #16882: update atomic variable to non-atomic int

---

src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputPatternVariableNameEnhancedInstanceofTestDefault.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks1.java

fixes #15769 
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/d55485b980e5c7ae9c883ba8f79dcbd6/raw/c824102d90368dbd060f41a1f6bda249cdcf0a5b/master_google_style.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/60d8725143067033c0ee8c8b8c6902c0/raw/e585f76bf1fe45a3eab04329b4f3ae01766aa394/google_checks_codeblock.xml
Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/f9c7774ca78df1f48f34bf30799bd3952abd9e2a/list-of-projects.properties

Issue #15769: fix false-positive indentation violations for block codes

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
config/pitest-suppressions/pitest-filters-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java

Issue: #14019
**Killing mutation with removing redundant code**
**Changes** 
```
/**
* Constructs a {@code SuppressFilterElement} using regular expressions
* as {@code String}s. These are internally compiled into {@code Pattern}
* objects and passed to the main constructor.
*
* @param files   regular expression for names of filtered files.
* @param checks  regular expression for filtered check classes.
* @param message regular expression for messages.
* @param modId   the id
* @param lines   lines CSV values and ranges for line number filtering.
* @param columns columns CSV values and ranges for column number filtering.
*/
public SuppressFilterElement(String files, String checks, String message,
String modId, String lines, String columns) {
this(toPattern(files), toPattern(checks), …
```

Issue #14019: Covered pitest survivals for SuppressFilterElement

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidArrayInitIndent.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidArrayInitIndent1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidArrayInitIndentWithoutTrailingComments.java

Fix #16869 
Added Missing test for `InputIndentationInvalidArrayInitIndent.java` with `forceStrictCondition=false`

Issue #16869: Added missing test for InputIndentationInvalidArrayInitIndent.java

---

src/site/xdoc/checks/coding/covariantequals.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsTwo.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/Example1.java

Issue #15456: Specify violation messages for CovariantEqualsCheck 

---

src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java

Fixed Issue https://github.com/checkstyle/checkstyle/issues/16155
Removed the File API usage in Properties macro
Changes Made:
*Removed Filed Usage to use Nio Api

Issue #16155: use nio api in PropertiesMacro

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
config/pitest-suppressions/pitest-filters-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java

Issue: #14019 
Restored the revert of SuppressFilterElement done in https://github.com/checkstyle/checkstyle/pull/16944

Issue #14019: Covered pitest survivals for SuppressFilterElement by restoration 

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/pitest-suppressions/pitest-ant-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java

Issue #14084: Remove warning from nullness profile for CheckstyleAntTask

---

config/jsoref-spellchecker/whitelist.words
pom.xml

https://github.com/checkstyle/checkstyle/actions/runs/14811930403/job/41587663425#step:4:2178
```
----------- grep of linkcheck.html--BEGIN
--- .ci-temp/linkcheck-suppressions-sorted.txt	2025-05-03 14:53:29.592737023 +0000
+++ .ci-temp/linkcheck-errors-sorted.txt	2025-05-03 14:53:29.589737009 +0000
@@ -1,3 +1,6 @@
+<a class="externalLink" href="https://www.baeldung.com/java-double-brace-initialization">https://www.baeldung.com/java-double-brace-initialization</a>: 403 Forbidden
+<a class="externalLink" href="https://www.baeldung.com/java-double-brace-initialization">https://www.baeldung.com/java-double-brace-initialization</a>: 403 Forbidden
+<a class="externalLink" href="https://www.eclipse.org/legal/epl-v20.html">https://www.ecli …
```

minor: suppress some links for linkcheck validation

---

.ci/validation.sh
.circleci/config.yml
.semaphore/semaphore.yml

Issue #17001: migrate pgjdbc no-error execution to circleci

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputCatchParametersOnNewLine.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSingleSwitchStatementWithoutCurly.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCatchParametersOnNewLine.java

fixes #14654 
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/d55485b980e5c7ae9c883ba8f79dcbd6/raw/c824102d90368dbd060f41a1f6bda249cdcf0a5b/master_google_style.xml
Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/f9c7774ca78df1f48f34bf30799bd3952abd9e2a/list-of-projects.properties

Issue #14654: fix catch parameter wrong indentation

---

src/site/xdoc/extending.xml

minor words fixed to capitals for website.
https://checkstyle.sourceforge.io/extending.html

minor: Capitalize section titles in extending.xml for consistency

---

config/jsoref-spellchecker/whitelist.words
src/site/xdoc/index.xml.vm

Issue #6173: Update Vim editor plugin details and remove outdated entry

---

src/site/xdoc/filters/suppresswarningsfilter.xml
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswarningsfilter/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppresswarningsfilter/Example2.java

Issue: #16738
Update `SuppressWarningsFilterExamplesTest` to use `verifyFilterWithInlineConfigParser`

Issue #16738: Update SuppressWarningsFilterExamplesTest to use verifyFilterWithInlineConfigParser

---

.ci/bump-version.sh

Issue #16850: Use Maven Wrapper for version bumping in pom.xml

---

.ci/check-performance-regression.sh
mvnw

Issue #16850: use Maven Wrapper for packaging in performance regression script

---

.ci/idea-inspection.sh
.circleci/config.yml
mvnw

Issue #16850: Update Maven commands to use Maven Wrapper and improve cache descriptions

---

.ci/idea-inspection.sh
mvnw

Issue #16850: Replace Maven command with Maven Wrapper in idea-inspection.sh

---

.ci/no-exception-test.sh
mvnw

Issue #16850: Replace Maven commands with Maven Wrapper in no-exception-test.sh

---

.ci/idea-inspection.bat

Issue #16850: Use Maven Wrapper for compilation in idea-inspection.bat

---

.ci/releasenotes-gen.sh

Issue #16850: Use Maven Wrapper for building release notes in release notes-gen.sh

---

.ci/run-link-check-plugin.sh

Issue #16850: Use Maven Wrapper in run-link-check-plugin.sh for consistency

---

.ci/sonar.sh

Issue #16850: Use Maven Wrapper in sonar.sh for executing SonarQube analysis

---

.ci/util.sh

Issue #16850: Use Maven Wrapper in getMavenProperty function in util.sh

---

.ci/travis.sh

Issue #16850: Use Maven Wrapper in travis.sh for local repo initialization and deployment

---

.travis.yml

Issue #16850: Add Maven Wrapper cache directory and update build command in Travis CI configuration

---

.ci/release-upload-all-jar.sh

Issue #16850: Use Maven Wrapper in release-upload-all-jar.sh for packaging

---

.ci/release-maven-prepare.sh

Issue #16850: Use Maven Wrapper in release-maven-prepare.sh for version on bumping

---

.ci/release-update-github-page.sh

Issue #16850: Use Maven Wrapper in release-update-github-page.sh for building release notes

---

.ci/release-maven-perform.sh

Issue #16850: Use Maven Wrapper in release-maven-perform.sh for deployment

---

.ci/release-publish-releasenotes-twitter.sh

Issue #16850: Use Maven Wrapper in release-publish-releasenotes-twitter.sh

---

azure-pipelines.yml

Issue #16850: Use Maven Wrapper in Azure Pipelines configuration

---

config/pmd.xml

Pull #16961: include PMD `UnusedPrivateMethod`
- seems stable
- easy to revert
- #16962

Pull #16961: include PMD `UnusedPrivateMethod`

---

.cirrus.yml

Issue #16850: Add Maven Wrapper support in Cirrus CI configuration

---

.ci/validation.cmd

Issue #16850: Use Maven Wrapper in validation.cmd for consistency across commands

---

.ci/releasenotes-gen.sh

Issue #16850
Reference https://github.com/checkstyle/checkstyle/pull/17092#issuecomment-2885435696

Issue #16850: replace Maven Wrapper with direct Maven command in releasenotes-gen.sh

---

.ci/validation.sh

Issue #16850: Use Maven Wrapper in validation.sh for consistency across commands

---

.ci/validation.sh
config/checkstyle-non-main-files-checks.xml

Issue #16850
Reference https://github.com/checkstyle/checkstyle/pull/17070#issuecomment-2883562414 
and
https://github.com/checkstyle/checkstyle/issues/16850#issuecomment-2887196264

Issue #16850: Refine Maven Command Invocation in CI Validation and Broaden Regex Enforcement for Maven Wrapper Variants

---

src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
src/site/xdoc/cmdline.xml.vm
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java

Issue #17106: adjust indentation for suppress-xpath tag in XpathFileGeneratorAuditListener

---

config/suppressions.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagBlockComment.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagInterface.java

part of #11166 
Diff Regression config: https://gist.githubusercontent.com/Rohanraj123/f8548a1a76258afebf6c9ef15d09dd59/raw/3d05b3263103cb1ab091134458ce50af7081f3c0/gistfile1.txt

Issue #11166: Remove usage of getFileContents() from WriteTagCheck

---

src/site/xdoc/checks/header/index.xml

Add Multifileregexpheader check section into header index.html

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaChild.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaChildCorrect.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CaseHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchRuleHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambdaChild.java

fixes: #17120
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/937e10572dd412961b61c77577619dff/raw/7a47240f8793e7335adbd81c2806b375f0394815/google_checks_indentation.xml
Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/9ba8e4fb324e1daf589874c6992f2aa87b03079a/list-of-projects.properties

Issue #17120: fix false positive for Lambda child in indentation check

---

pom.xml

Issue #17142: add excluded link to avoid false positives from broken link check

---

.ci/validation.sh
.semaphore/semaphore.yml
config/jsoref-spellchecker/whitelist.words

Issue #9807: Removing no-violation-test-josm from CI

---

.ci/diff-report.sh

https://github.com/checkstyle/checkstyle/actions/runs/15511697557/job/43673488490
```
shell: /usr/bin/bash -e {0}
env:
AWS_REGION: us-east-2
AWS_BUCKET_NAME: checkstyle-diff-reports
USER_LOGIN: kkoutsilis
DEFAULT_PROJECTS_LINK: https://raw.githubusercontent.com/checkstyle/test-configs/main/extractor/src/main/resources/list-of-projects.yml
BASE_TEST_CONFIGS_URL: https://raw.githubusercontent.com/checkstyle/test-configs/main
EXTRACTOR_VERSION: 2024-10-08
DIFF_TOOL_VERSION: 1.0-2025-01-30
PATCH_DIFF_TOOL_VERSION: 0.1-SNAPSHOT
CACHE_KEY: regression-report-9017ae84cd019a0d3b84b15212d9c5c2f8edcaea-2953040004
GENERATED_CONFIGS_PATH: generated_configs
DIFF_CONFIG_LINK: https://raw.githubusercontent.com/checkstyle/test-configs/main/configs in PR description
/config.xml
PATCH_CONFIG_LINK: …
```

minor: Update diff-report.sh to print more in logs

---

src/site/xdoc/checks/annotation/suppresswarningsholder.xml
src/site/xdoc/checks/annotation/suppresswarningsholder.xml.template
src/site/xdoc/checks/coding/innerassignment.xml
src/site/xdoc/checks/coding/innerassignment.xml.template

#17186 
Added he separator in inner assignment and Suppresswarningsholder

Issue #17186: Adding Hr separator in inner assignment and Suppresswarningsholder

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressionsOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressionsTwo.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestSwitchExpressions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestSwitchExpressionsNewLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSwitchExpressionNoSingleLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchExpressionAlone.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchExpressionAloneOrSingleline.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchRuleAlone.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyCaseBlocksWithSwitchRuleAloneOrSingleline.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression7.java

Issue #17168: Moved Block Module Inputs to Compilable Folder

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSingleSwitchStatementsWithoutCurly.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionCorrect.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionDeclaration.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionDeclarationLCurlyNewLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionNewLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCodeBlocks2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambdaChild.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLineWrappedRecordDeclaration.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMultilineStatements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchExpressionWrappingIndentation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchOnStartOfLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTextBlock.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationYieldForceStrict.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationYieldStatement.java

Part of : https://github.com/checkstyle/checkstyle/issues/17168

Issue #17168: Moved Indentation Module Inputs to Compilable Folder

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthSwitchExps.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthIgnoringImportStatements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthIgnoringPackageStatements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCompactCtorsCountEmpty.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthTextBlocksCountEmpty.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberMax1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberMax20.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberPrivateModifierOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberPrivateModifierTwo.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTopLevel1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTopLevel2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTwo.java

Issue #17168: Moved Size Module Inputs to Compilable Folder

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullEnhancedInstanceof.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordsAndCompactCtors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough10.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough9.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughSwitchRules.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldClassNestedInRecord.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldEnhancedInstanceof.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldInnerRecordsImplicitlyStatic.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldRecordsImplicitlyStaticClassComparison.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocks.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocksQuotes.java

Issue #17168: Moved CodingOne  Module Inputs to Compilable Folder

---

config/checkstyle-resources-suppressions.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryNullCheckWithInstanceOfCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclarationRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberRecordsDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarynullcheckwithinstanceof/InputUnnecessaryNullCheckWithInstanceOfOne.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarynullcheckwithinstanceof/InputUnnecessaryNullCheckWithInstanceOfTwo.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckTextBlocks.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclarationRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclarationRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableRecords.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableSwitchExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceCheckSwitchExpressions.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceCheckSwitchExpressions2.java

Issue #17168: Moved CodingThree Module Inputs to Compilable Folder

---

.ci/pitest.sh

it will help in cases like this https://github.com/checkstyle/checkstyle/pull/17154#issuecomment-2962364609

minor: print pitest commands to let contributors see commands to reuse on local

---

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCovariantEqualsTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalIdentifierNameTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordComponentNameTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordComponentNumberTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordTypeParameterNameTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSealedShouldHavePermitsListTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionStaticVariableNameTest.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentname/InputXpathRecordComponentNameDefault.java
src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordtypeparametername/InputXpathRecordTypeParameterNameTypeDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/covariantequals/InputXpathCovariantEqualsInRecord.java
src/it/resources/org/checkstyle/suppressionxpathfilter/illegalidentifiername/InputXpathIllegalIdentifierNameOne.java
src/it/resources/org/checkstyle/suppressionxpathfilter/illegalidentifiername/InputXpathIllegalIdentifierNameTwo.java
src/it/resources/org/checkstyle/suppressionxpathfilter/recordcomponentname/InputXpathRecordComponentNameDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/recordcomponentname/InputXpathRecordComponentNameFormat.java
src/it/resources/org/checkstyle/suppressionxpathfilter/recordcomponentnumber/InputXpathRecordComponentNumberCustomMax.java
src/it/resources/org/checkstyle/suppressionxpathfilter/recordcomponentnumber/InputXpathRecordComponentNumberDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/recordtypeparametername/InputXpathRecordTypeParameterNameTypeDeclared.java
src/it/resources/org/checkstyle/suppressionxpathfilter/recordtypeparametername/InputXpathRecordTypeParameterNameTypeDefault.java
src/it/resources/org/checkstyle/suppressionxpathfilter/sealedshouldhavepermitslist/InputXpathSealedShouldHavePermitsListInner.java
src/it/resources/org/checkstyle/suppressionxpathfilter/sealedshouldhavepermitslist/InputXpathSealedShouldHavePermitsListTopLevel.java
src/it/resources/org/checkstyle/suppressionxpathfilter/staticvariablename/InputXpathStaticVariableNameInnerClassField.java

Issue #17168: Moved IT Module Inputs to Compilable Folder

---

src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport1.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport10.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport11.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport12.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport13.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport14.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport15.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport16.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport2.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport3.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport4.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport5.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport6.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport7.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport8.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserFullJavaIdentifierSupport9.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java
src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserTextBlocks.java
src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnCompactCtor.java
src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnRecord.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperTextBlock.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTextBlock.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTextBlockCrlf.java
src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTextBlockNewLine.java

Issue #17168: Moved Parser Module Inputs to Compilable Folder

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenEmptyStatement.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens7.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens8.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenLastTokenType.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenLastTokenType2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenMissingSwitchDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromCatch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally4.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally5.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenStringLiteralEquality.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenTestLimitedToken.java

Issue: #16807 
Arrange Properties for DescendantToken as order:
https://checkstyle.sourceforge.io/checks/misc/descendanttoken.html#DescendantToken
Added missing properties for DescendantToken in inline config

Issue #16807: Updating properties in Input files for module DescendantTokenCheck

---

.ci/run-link-check-plugin.sh
.circleci/config.yml

Issue #17168: Migrating LinkcheckPlugin to Jdk17

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchRuleHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambdaAndChildOnTheSameLine.java

Issue #17167: fp when switch is not wrapped

---

.semaphore/semaphore.yml

Issue #17168: Upgrading CI on semaphore to jdk17

---

.circleci/config.yml

Issue #17168: Upgrading Default CI image to Jdk17

---

config/import-control.xml
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
src/site/xdoc/checks/header/header.xml
src/site/xdoc/checks/header/header.xml.template
src/site/xdoc/checks/header/regexpheader.xml
src/site/xdoc/checks/header/regexpheader.xml.template
src/site/xdoc/checks/javadoc/javadocleadingasteriskalign.xml
src/site/xdoc/checks/javadoc/javadocmissingwhitespaceafterasterisk.xml
src/site/xdoc/checks/regexp/regexpsinglelinejava.xml
src/site/xdoc/checks/regexp/regexpsinglelinejava.xml.template
src/site/xdoc/checks/sizes/filelength.xml
src/site/xdoc/checks/sizes/filelength.xml.template

Issue: #17237  
Continuing on #16950

Issue #17237: Fix the problem when property of module has older version than the module's

---

.github/workflows/check-performance-regression.yml
.github/workflows/no-exception-workflow.yml
.github/workflows/pitest.yml

Issue #17168: Migrating Multiple CI to jdk17

---

.circleci/config.yml
config/jsoref-spellchecker/whitelist.words

part of : #17168
Image from https://github.com/checkstyle/contribution/pull/942

Issue #17168: Changing docker Image to jdk17 - circleci

---

.github/workflows/checker-framework.yml
config/checker-framework-suppressions/checker-index-suppressions.xml
config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
config/checker-framework-suppressions/checker-methods-resource-fenum-suppressions.xml
config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/checker-framework-suppressions/checker-purity-value-returns-suppressions.xml
config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
config/checker-framework-suppressions/checker-signature-gui-units-init-suppressions.xml

Issue #17168: Upgrading CheckerFramework to jdk17

---

.github/workflows/error-prone.yml
config/jsoref-spellchecker/whitelist.words

Issue #17168: Upgrade error-prone CI to Jdk17

---

.ci/google-java-format.sh
config/pitest-suppressions/pitest-indentation-suppressions.xml
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputAnnotationArrayInitMultiline.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputAnnotationArrayInitMultiline2.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputAnnotationArrayInitMultilineCorrect.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedAnnotationArrayInitMultiline.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedAnnotationArrayInitMultiline2.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnotationArray.java

#17122 
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/d55485b980e5c7ae9c883ba8f79dcbd6/raw/fff88288dced4eb5d4e9cbe021576fd92d62678d/master_google_style.xml
Diff Regression projects: https://gist.githubusercontent.com/mohitsatr/68b0817ac52ff7773d35585ee12fc1cc/raw/f9c7774ca78df1f48f34bf30799bd3952abd9e2a/list-of-projects.properties

Issue #17122: fix indentaion false-positive  for multiline annotation arrays

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java

#17225 
Continuing #17238
All version release dates are specified in the issue.

Issue #17225: Continue to extend 'Since version' javadoc marking implementation

---

azure-pipelines.yml

Issue #17168: Upgrade Azure CI to jdk17

---

.ci/validation.sh
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundArrow.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundArrow.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundArrowCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaChild.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaChildCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSingleSwitchStatementWithoutCurly.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSingleSwitchStatementWithoutCurlyCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchWrappingIndentation.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSwitchWrappingIndentationCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputRecordComponentName.java

Issue #17309: Add resources-noncompilable to the compilation

---

config/jsoref-spellchecker/whitelist.words
config/spotbugs-exclude.xml
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java

Part of : #17168
From comment : https://github.com/checkstyle/checkstyle/pull/17259#issuecomment-3019192404

Issue #17168: Fix inspection for private methods used from inner class

---

.ci/validation.sh
.circleci/config.yml

Issue #17168: Removing javac 11  job from CircleCI

---

azure-pipelines.yml
config/checker-framework-suppressions/checker-index-suppressions.xml
config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
config/checker-framework-suppressions/checker-methods-resource-fenum-suppressions.xml
config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/checker-framework-suppressions/checker-purity-value-returns-suppressions.xml
config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
config/checker-framework-suppressions/checker-signature-gui-units-init-suppressions.xml
config/intellij-idea-inspections.xml
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java

Issue #17168: Upgrade Pom Java version to 17

---

docs/BEGINNING_DEVELOPMENT.md
src/site/xdoc/beginning_development.xml

Issue #17321: Update Doc to Use jdk17 as minimial required

---

.ci/google-java-format.sh
.github/workflows/google-java-format.yml
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/ParameterNamesTest.java
src/it/java/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/LocalVariableNamesTest.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceAroundArrow.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundArrowCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedCatchParametersOnNewLine.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedLambdaAndChildOnTheSameLine.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedLambdaChild.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedSingleSwitchStatementWithoutCurly.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedSwitchOnStartOfTheLine.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedSwitchWrappingIndentation.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaAndChildOnTheSameLine.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLambdaChild.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputMultilineStatementsCorrect.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputSingleSwitchStatementWithoutCurly.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputFormattedRecordComponentName.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputFormattedPatternVariableNameEnhancedInstanceofTestDefault.java
src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputRecordTypeParameterName.java

resolves #17285 
- Added resources-noncompilable path to the google-java-format.sh
- Created missing `InputFormatted...java` inputs and tests

Issue #17285: Add non-compilable resources to google-java-format.sh

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/MissingDeprecatedCheck.xml
src/site/xdoc/checks/annotation/annotationonsameline.xml.template
src/site/xdoc/checks/annotation/annotationusestyle.xml
src/site/xdoc/checks/annotation/annotationusestyle.xml.template
src/site/xdoc/checks/annotation/missingdeprecated.xml
src/site/xdoc/checks/annotation/missingdeprecated.xml.template
src/site/xdoc/checks/annotation/missingoverride.xml
src/site/xdoc/checks/annotation/missingoverride.xml.template
src/site/xdoc/checks/annotation/packageannotation.xml
src/site/xdoc/checks/annotation/packageannotation.xml.template
src/site/xdoc/checks/annotation/suppresswarnings.xml
src/site/xdoc/checks/annotation/suppresswarnings.xml.template
src/site/xdoc/checks/annotation/suppresswarningsholder.xml
src/site/xdoc/checks/annotation/suppresswarningsholder.xml.template

Issue #17281: Extended Description Macro to annotation modules

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java

Issue #17251: Removed potential expected vs actual inconsistency in XdocsJavaDocsTest

---

src/site/xdoc/checks/imports/importcontrol.xml
src/site/xdoc/checks/imports/importcontrol.xml.template
src/site/xdoc/checks/imports/importorder.xml
src/site/xdoc/checks/imports/importorder.xml.template
src/site/xdoc/checks/imports/redundantimport.xml
src/site/xdoc/checks/imports/redundantimport.xml.template
src/site/xdoc/checks/imports/unusedimports.xml
src/site/xdoc/checks/imports/unusedimports.xml.template

Issue #17281: Extended Description Macro to imports modules

---

src/site/xdoc/checks/misc/arraytypestyle.xml
src/site/xdoc/checks/misc/arraytypestyle.xml.template
src/site/xdoc/checks/misc/avoidescapedunicodecharacters.xml
src/site/xdoc/checks/misc/avoidescapedunicodecharacters.xml.template
src/site/xdoc/checks/misc/commentsindentation.xml
src/site/xdoc/checks/misc/commentsindentation.xml.template
src/site/xdoc/checks/misc/descendanttoken.xml
src/site/xdoc/checks/misc/descendanttoken.xml.template
src/site/xdoc/checks/misc/finalparameters.xml
src/site/xdoc/checks/misc/finalparameters.xml.template
src/site/xdoc/checks/misc/indentation.xml
src/site/xdoc/checks/misc/indentation.xml.template
src/site/xdoc/checks/misc/nocodeinfile.xml
src/site/xdoc/checks/misc/nocodeinfile.xml.template
src/site/xdoc/checks/misc/orderedproperties.xml
src/site/xdoc/checks/misc/orderedproperties.xml.template
src/site/xdoc/checks/misc/outertypefilename.xml
src/site/xdoc/checks/misc/outertypefilename.xml.template
src/site/xdoc/checks/misc/trailingcomment.xml
src/site/xdoc/checks/misc/trailingcomment.xml.template
src/site/xdoc/checks/misc/uncommentedmain.xml
src/site/xdoc/checks/misc/uncommentedmain.xml.template
src/site/xdoc/checks/misc/uniqueproperties.xml
src/site/xdoc/checks/misc/uniqueproperties.xml.template
src/site/xdoc/checks/misc/upperell.xml
src/site/xdoc/checks/misc/upperell.xml.template

Issue #17281: Extended Description Macro to misc modules

---

src/site/xdoc/checks/regexp/regexp.xml
src/site/xdoc/checks/regexp/regexp.xml.template
src/site/xdoc/checks/regexp/regexpmultiline.xml
src/site/xdoc/checks/regexp/regexpmultiline.xml.template
src/site/xdoc/checks/regexp/regexponfilename.xml
src/site/xdoc/checks/regexp/regexponfilename.xml.template
src/site/xdoc/checks/regexp/regexpsingleline.xml
src/site/xdoc/checks/regexp/regexpsingleline.xml.template
src/site/xdoc/checks/regexp/regexpsinglelinejava.xml
src/site/xdoc/checks/regexp/regexpsinglelinejava.xml.template

Issue #17281: Extended Description Macro to regexp modules

---

src/site/xdoc/checks/sizes/anoninnerlength.xml
src/site/xdoc/checks/sizes/anoninnerlength.xml.template
src/site/xdoc/checks/sizes/executablestatementcount.xml
src/site/xdoc/checks/sizes/executablestatementcount.xml.template
src/site/xdoc/checks/sizes/filelength.xml
src/site/xdoc/checks/sizes/filelength.xml.template
src/site/xdoc/checks/sizes/lambdabodylength.xml.template
src/site/xdoc/checks/sizes/methodcount.xml
src/site/xdoc/checks/sizes/methodcount.xml.template
src/site/xdoc/checks/sizes/methodlength.xml
src/site/xdoc/checks/sizes/methodlength.xml.template
src/site/xdoc/checks/sizes/outertypenumber.xml
src/site/xdoc/checks/sizes/outertypenumber.xml.template
src/site/xdoc/checks/sizes/parameternumber.xml.template
src/site/xdoc/checks/sizes/recordcomponentnumber.xml
src/site/xdoc/checks/sizes/recordcomponentnumber.xml.template

Issue #17281: Extended Description Macro to sizes modules

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/NPathComplexityCheck.xml
src/site/xdoc/checks/metrics/npathcomplexity.xml
src/site/xdoc/checks/metrics/npathcomplexity.xml.template

Issue #17355: Wrapped <table> tags with <div>

---

.ci/google-java-format.sh
src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/WhereToBreakTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputFormattedIllegalLineBreakAroundLambda.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputIllegalLineBreakAroundLambda.java

supplemental: IT for 4.5.1 where-to-break for lambda arrow

---

.ci/validation.sh
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example10.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example11.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example12.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example2.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example3.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example4.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example5.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example6.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example7.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example8.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example9.java

Issue #17321: Migrate Xdocs Import file to jdk17

---

pom.xml
src/site/xdoc/checks/blocks/avoidnestedblocks.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesAllIgnored.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesCommonPackage.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesDirectPackages.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/Example2.java

dependency: bump net.sf.saxon:Saxon-HE from 12.5 to 12.8

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/NewlineAtEndOfFileCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/TranslationCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocBlockTagLocationCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocContentLocationCheck.xml
src/site/xdoc/checks/javadoc/javadocblocktaglocation.xml
src/site/xdoc/checks/javadoc/javadocblocktaglocation.xml.template
src/site/xdoc/checks/javadoc/javadoccontentlocation.xml
src/site/xdoc/checks/javadoc/javadoccontentlocation.xml.template
src/site/xdoc/checks/misc/newlineatendoffile.xml
src/site/xdoc/checks/misc/newlineatendoffile.xml.template
src/site/xdoc/checks/misc/translation.xml
src/site/xdoc/checks/misc/translation.xml.template

Issue #17281: Extended NotesMacro and DescriptionMacro to javadoc, misc modules

---

src/site/xdoc/checks/misc/todocomment.xml
src/site/xdoc/checks/misc/todocomment.xml.template

Issue #17281: Expanded DescriptionMacro to TodoComment

---

src/site/xdoc/filefilters/beforeexecutionexclusionfilefilter.xml
src/site/xdoc/filefilters/beforeexecutionexclusionfilefilter.xml.template

Issue #17281: Extended DescriptionMacro to firefilters

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/site/DescriptionMacro.java
src/main/java/com/puppycrawl/tools/checkstyle/site/NotesMacro.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/LineLengthCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/FileTabCharacterCheck.xml
src/site/xdoc/checks/sizes/linelength.xml
src/site/xdoc/checks/sizes/linelength.xml.template
src/site/xdoc/checks/whitespace/filetabcharacter.xml
src/site/xdoc/checks/whitespace/filetabcharacter.xml.template

Issue #17281: Extended NotesMacro and DescriptionMacro to sizes, whitespace modules

---

src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableTestWarningSeverity.java

closes https://github.com/checkstyle/checkstyle/issues/12980
followup  from https://github.com/checkstyle/checkstyle/pull/17392

minor: fix violation comment

---

src/site/xdoc/checks/coding/illegaltype.xml
src/site/xdoc/checks/coding/illegaltype.xml.template
src/site/xdoc/checks/misc/todocomment.xml
src/site/xdoc/checks/misc/todocomment.xml.template
src/site/xdoc/checks/sizes/linelength.xml
src/site/xdoc/checks/sizes/linelength.xml.template
src/site/xdoc/filters/suppressionfilter.xml
src/site/xdoc/filters/suppressionfilter.xml.template
src/site/xdoc/filters/suppresswithplaintextcommentfilter.xml
src/site/xdoc/filters/suppresswithplaintextcommentfilter.xml.template

Issue #17386: Moved all misplaced notes sections under description section

---

.semaphore/semaphore.yml

Issue #14086: Activaying CI Execution Back

---

config/intellij-idea-inspections.xml
src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java
src/main/java/com/puppycrawl/tools/checkstyle/ThreadModeSettings.java
src/main/java/com/puppycrawl/tools/checkstyle/api/CheckstyleException.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ListToTreeSelectionModelWrapper.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableCellRenderer.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableModelAdapter.java
src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGenerationException.java
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules/CheckstyleAntTaskStub.java

Issue #17301: Add @Serial annotation to serialVersionUID fields

---

src/site/xdoc/checks/imports/importcontrol.xml
src/site/xdoc/checks/imports/importcontrol.xml.template
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/filters/Example9.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/import-control9.xml

Issue #17400: Enabled examples macro for Example 9 in importcontrol.xml.template

---

src/site/xdoc/checks/imports/importcontrol.xml
src/site/xdoc/checks/imports/importcontrol.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/import-control11.xml
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/someImports/Example11.java

Issue #17400: Enabled examples macro for Example 11 in importcontrol.xml.template

---

src/it/java/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/SpecialEscapeSequencesTest.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequencesInTextBlockForOctalValues.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequencesInTextBlockForUnicodeValues.java
src/main/resources/google_checks.xml
src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java

part of #14291
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/2f62c8fabd1ea8fbc7ceaf6f8b4d19b5/raw/63a1cb1f6e525b99b6b05ee53721bb8308c5a042/master_illegaltext.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/f4bc1e92062712f41048c8282e8e283c/raw/efdfe42f1b6d4480c780693f5ea3f99b04b801b9/patch_illegaltext.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on-for-github-action.properties

Issue #14291: Add TEXT_BLOCK_CONTENT token in IllegalTokenText in google config

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions2.xml

Issue #17402: Enabled examples macro for Example 2 in suppressionxpathfilter.xml.template

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions3.xml

Issue #17402: Enabled examples macro for Example 3 in suppressionxpathfilter.xml.template

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example4.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions4.xml

Issue #17402: Enabled examples macro for Example 4 in suppressionxpathfilter.xml.template

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template

doc: Finished implementation of example separators in SuppressionXpathFilter website page

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example5.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions5.xml

Issue #17402: Enabled examples macro for Example 5 in suppressionxpathfilter.xml.template

---

config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/GeneralFormTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnCanonicalConstructorsWithAnnotation.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnCompactConstructorsWithAnnotation.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedJavadocPositionOnConstructorInRecord.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputFormattedRecordClassJavadocPosition.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCanonicalConstructorsWithAnnotation.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnCompactConstructorsWithAnnotation.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputJavadocPositionOnConstructorInRecord.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputRecordClassJavadocPosition.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPositionOnCompactConstructors.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPositionOnCompactConstructorsWithAnnotation.java

Issue #17158: fix invalid javadoc position for compact constructor

---

src/site/xdoc/google_style.xml

supplemental: Update old cached version with latest one(2025)

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example8.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions8.xml

Issue #17402: Enabled examples macro for Example 8 in suppressionxpathfilter.xml.template

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example6.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions6.xml

Issue #17402: Enabled examples macro for Example 6 in suppressionxpathfilter.xml.template

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/checker-framework-suppressions/checker-signature-gui-units-init-suppressions.xml
config/intellij-idea-inspections.xml
config/sevntu-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/filters/IntMatchFilterElement.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableCellRenderer.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/ImmutabilityTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsCategoryIndexTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

Issue #17302: Refactor instanceof checks to pattern variables

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSwitchExpressionAndLambda.java

Issue: #16807 
```
PS C:\Users\ACER\Desktop\checkstyle> mvn clean verify
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------< com.puppycrawl.tools:checkstyle >-------------------
.
.
.
C:\Users\ACER\Desktop\checkstyle\target\plexus-resources1655545072tmp
[INFO] Total time:  12:21 min
[INFO] Finished at: 2025-07-27T14:43:43+05:30 …
```

Issue #16807: Updated properties in Input files for NeedBracesCheck

---

config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/HorizontalWhitespaceTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeAnnotations.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedNoWhitespaceBeforeEllipsis.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeAnnotations.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeEllipsis.java
src/main/resources/google_checks.xml

part of #8205 
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/d55485b980e5c7ae9c883ba8f79dcbd6/raw/864566af406d2bc0e9f6046e909ff1c3519e3309/master_google_style.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/ebe8f2abe7765997e11a14604813627a/raw/c74be4dd11d23d4b46ee7321aee2029282a3f60e/nowhitespacebeforeellipsis.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on-for-github-action.properties

Issue #8205: No whitespace before ellipsis is allowed

---

src/site/xdoc/google_style.xml

supplemental: Add coverage gap for issue #17451 to coverage table

---

config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/HorizontalWhitespaceTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputFormattedWhitespaceInsideArrayInitializer.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceInsideArrayInitializer.java

supplemental: IT for whitespace inside array initializer

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example9.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions9.xml

Issue #17402: Enabled examples macro for Example 9 in suppressionxpathfilter.xml.template

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example11.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions11.xml

Issue #17402: Enabled examples macro for Example 11 in suppressionxpathfilter.xml.template

---

src/site/xdoc/google_style.xml

supplemental: Add blue-tick for Package Name rule for modules

---

src/site/xdoc/filters/suppressionxpathfilter.xml
src/site/xdoc/filters/suppressionxpathfilter.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/Example13.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/suppressions13.xml

Issue #17402: Enabled examples macro for Example 13 in suppressionxpathfilter.xml.template

---

src/main/java/com/puppycrawl/tools/checkstyle/site/DescriptionMacro.java
src/main/java/com/puppycrawl/tools/checkstyle/site/NotesMacro.java
src/main/java/com/puppycrawl/tools/checkstyle/site/PropertiesMacro.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java

Issue #17378 
Will attempt to split this method into two in separate pull.

Issue #17378: Renamed SiteUtil.getPropertiesJavadocs

---

src/site/xdoc/google_style.xml

supplemental: rename 5.2.1 'Package and module names'

---

src/site/xdoc/google_style.xml

supplemental: Rename 4.8.4.3 section

---

src/site/xdoc/google_style.xml

supplemental: Rename 4.8.5.2 'Class, package, and module annotations'

---

config/linkcheck-suppressions.txt
src/site/xdoc/google_style.xml

supplemental: Add section '4.8.6.2 TODO comments'

---

src/site/xdoc/google_style.xml

supplemental: Add red-ban for module directives in 4.8.7 'Modifier' 

---

src/site/xdoc/google_style.xml

supplemental: Rename section 4.8.4 'Switch statements and expressions'

---

config/intellij-idea-inspections.xml
src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/TreeTableTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java

Issue #17304: Convert concatenated strings to text blocks

---

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4862todocomments/TodoCommentTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4862todocomments/InputTodoCommentAllVariants.java

supplemental: IT for Todo comments

---

src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/defaultlogger/ExpectedDefaultLoggerOutputSingleError.txt

#16361
Few more tests updated.

Issue #16361: Update DefaultLoggerTest.java to verify with InlineConfig parser and logger, more updates

---

src/site/xdoc/cmdline.xml.vm

Issue #17506: doc fix for optional configuration file

---

config/checkstyle-report-1.0.0.xsd
pom.xml

fixes #5166
took xsd from https://github.com/checkstyle/checkstyle/issues/7517#issuecomment-3146397378 and modified it to match our test expected reports

Issue #5166: first version of xml report xsd

---

config/configuration-1-3.xsd
pom.xml

fixes #7517
`mvn xml:validate` to do validation xml against xsd

Issue #7517: place in repo xsd for configuration_1_3.dtd

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/indentation/CommentsIndentationCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/AbbreviationAsWordInNameCheck.xml
src/site/xdoc/checks/misc/commentsindentation.xml
src/site/xdoc/checks/naming/abbreviationaswordinname.xml
src/site/xdoc/checks/naming/classtypeparametername.xml
src/site/xdoc/checks/naming/classtypeparametername.xml.template
src/site/xdoc/google_style.xml
src/site/xdoc/index.xml.vm

supplemental: Update all old cached style-guide links to latest version

---

src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule3sourcefile/package-info.java
src/site/xdoc/google_style.xml

and Update the coverage table 
from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2234148498
part of #17541

supplemental: IT for 'Source file structure' for package-info.java

---

README.md

correction in wording to avoid confusion, feedback from Discord

minor: Update README.md for dev tools

---

src/site/xdoc/config.xml

Issue #14879: Continued adding link anchors to examples in config.xml

---

config/release-settings.xml
pom.xml

Issue #17559: change deploy plugin based on sonatype requirements

---

config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedLineBreakAfterLeftCurlyOfBlockInSwitch.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputLineBreakAfterLeftCurlyOfBlockInSwitch.java
src/site/xdoc/google_style.xml

from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2234153110 and #17565

supplemental: IT & table update for '4.8.4.1 Indentation'

---

config/jsoref-spellchecker/whitelist.words
src/it/java/com/google/checkstyle/test/chapter6programpractice/rule61overridealwaysused/OverrideAlwaysUsedTest.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule61overridealwaysused/InputOverrideAlwaysUsedForRecord.java
src/site/xdoc/google_style.xml

from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2234081128 and #17561

supplemental: 6.1 IT and coverage-table update

---

.github/workflows/regression-report.yml

Reverts checkstyle/checkstyle#17572
https://github.com/checkstyle/checkstyle/actions/runs/16782944852/job/47526229330#step:4:43

Revert "minor: trim whitespaces after regression report comment"

---

src/it/java/org/checkstyle/suppressionxpathfilter/metrics/XpathRegressionBooleanExpressionComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/metrics/XpathRegressionClassDataAbstractionCouplingTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/metrics/XpathRegressionClassFanOutComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/metrics/XpathRegressionCyclomaticComplexityTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/metrics/XpathRegressionJavaNCSSTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/metrics/XpathRegressionNPathComplexityTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/booleanexpressioncomplexity/InputXpathBooleanExpressionComplexityCatchBlock.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/booleanexpressioncomplexity/InputXpathBooleanExpressionComplexityClassFields.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/booleanexpressioncomplexity/InputXpathBooleanExpressionComplexityConditionals.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/classdataabstractioncoupling/InputXpathClassDataAbstractionCouplingClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/classdataabstractioncoupling/InputXpathClassDataAbstractionCouplingEnum.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/classdataabstractioncoupling/InputXpathClassDataAbstractionCouplingInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/classfanoutcomplexity/InputXpathClassFanOutComplexityClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/classfanoutcomplexity/InputXpathClassFanOutComplexityEnum.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/classfanoutcomplexity/InputXpathClassFanOutComplexityInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/cyclomaticcomplexity/InputXpathCyclomaticComplexityConditionals.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/cyclomaticcomplexity/InputXpathCyclomaticComplexitySwitchBlock.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/javancss/InputXpathJavaNCSSOne.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/javancss/InputXpathJavaNCSSThree.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/javancss/InputXpathJavaNCSSTwo.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/npathcomplexity/InputXpathNPathComplexityMethod.java
src/it/resources/org/checkstyle/suppressionxpathfilter/metrics/npathcomplexity/InputXpathNPathComplexityStaticBlock.java

Issue #14769: Implemented metrics package structure for IT Regression area

---

src/it/java/org/checkstyle/suppressionxpathfilter/modifier/XpathRegressionClassMemberImpliedModifierTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/modifier/XpathRegressionInterfaceMemberImpliedModifierTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/modifier/XpathRegressionModifierOrderTest.java
src/it/java/org/checkstyle/suppressionxpathfilter/modifier/XpathRegressionRedundantModifierTest.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/classmemberimpliedmodifier/InputXpathClassMemberImpliedModifierEnum.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/classmemberimpliedmodifier/InputXpathClassMemberImpliedModifierInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/interfacememberimpliedmodifier/InputXpathInterfaceMemberImpliedModifierField.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/interfacememberimpliedmodifier/InputXpathInterfaceMemberImpliedModifierInner.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/interfacememberimpliedmodifier/InputXpathInterfaceMemberImpliedModifierMethod.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/modifierorder/InputXpathModifierOrderAnnotation.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/modifierorder/InputXpathModifierOrderMethod.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/modifierorder/InputXpathModifierOrderVariable.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/redundantmodifier/InputXpathRedundantModifierClass.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/redundantmodifier/InputXpathRedundantModifierInterface.java
src/it/resources/org/checkstyle/suppressionxpathfilter/modifier/redundantmodifier/InputXpathRedundantModifierWithEnum.java

Issue #14769: Implemented modifier package structure for IT Regression area

---

.circleci/config.yml

Issue #17269: Changing Docker Script to latest groovy Image

---

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/WhereJavadocIsUsedTest.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputJavadocTypeOnRecord.java
src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputJavadocTypeOnRecord2.java

from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2125501633

supplemental: IT covering record for '7.3 Where Javadoc is used'

---

config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter4formatting/rule487modifiers/ModifiersTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputFormattedModifierOrderNonSealed.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputFormattedModifierOrderSealed.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputModifierOrderNonSealed.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule487modifiers/InputModifierOrderSealed.java

from: https://github.com/checkstyle/checkstyle/pull/17165#discussion_r2247795799

supplemental: IT for '4.8.7 Modifiers'

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/intellij-idea-inspections.xml
config/pitest-suppressions/pitest-common-suppressions.xml
config/pmd-main.xml
src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ClassDefHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java
src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java

Issue #17300: Convert switch statements to enhanced switch expressions

---

.ci/eclipse-compiler-javac.sh
.ci/validation.sh
.circleci/config.yml
pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesPatternMatchingForSwitchAllowSingleLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSwitchExpressionAndLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSwitchExpressionAndLambdaAllowSingleLine.java

Issue #17429: Relocate inputs to compilable path for block check

---

config/checkstyle-examples-checks.xml
src/site/xdoc/checks/annotation/packageannotation.xml
src/site/xdoc/checks/coding/missingswitchdefault.xml
src/site/xdoc/checks/coding/unusedcatchparametershouldbeunnamed.xml
src/site/xdoc/checks/coding/unusedlambdaparametershouldbeunnamed.xml
src/site/xdoc/checks/coding/unusedlocalvariable.xml
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/Example1.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/Example2.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/Example3.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/Example1.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlambdaparametershouldbeunnamed/Example1.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/Example1.java
src/xdocs-examples/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/Example2.java

Issue #13290 
https://checkstyle.org/checks/naming/typename.html#TypeName

Issue #13290: Used TypeName check to validate Example classes

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexityWhenExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexitySealedClasses.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexitySwitchBlocks6.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexityWhenExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexityWhenSwitchAsSinglePoint.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityDefault3.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityPatternMatchingForSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityWhenExpression.java

Issue #17429: Relocate inputs to compilable path for Metrics Module

---

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCaseDefaultColonCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceBeforeRecordHeader.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckRecordPattern.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadCheckRecordPattern2.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterUnnamedPattern.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/InputNoWhitespaceBeforeCaseDefaultColonEnumAndStrings.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/InputNoWhitespaceBeforeCaseDefaultColonPatternMatchingForSwitch.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperator.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapInstanceOfOperatorEndOfLine.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadCheckWhenExpression.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForRecordPattern.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForRecordPatternWithSpaceOption.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterLiteralWhen.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterSwitchStatements.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespaceafter/InputWhitespaceAfterUnnamedPattern.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAfterPermitsList.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundLiteralWhen.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundUnnamedPattern.java

Issue #17429: Relocate inputs to compilable path for WhiteSpace Module

---

src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierNoViolationRecords.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierRecords.java

From comment : https://github.com/checkstyle/checkstyle/pull/17602#issuecomment-3182076045

supplemental: Changing Comment to Non-compiled by eclipse

---

src/site/xdoc/google_style.xml

supplemental: Add Green tick to '4.2 Block indentation'

---

src/site/xdoc/checks/blocks/avoidnestedblocks.xml
src/site/xdoc/checks/blocks/avoidnestedblocks.xml.template
src/site/xdoc/checks/blocks/emptyblock.xml
src/site/xdoc/checks/blocks/emptyblock.xml.template
src/site/xdoc/checks/blocks/emptycatchblock.xml
src/site/xdoc/checks/blocks/emptycatchblock.xml.template
src/site/xdoc/checks/blocks/leftcurly.xml
src/site/xdoc/checks/blocks/leftcurly.xml.template
src/site/xdoc/checks/blocks/needbraces.xml
src/site/xdoc/checks/blocks/needbraces.xml.template
src/site/xdoc/checks/blocks/rightcurly.xml
src/site/xdoc/checks/blocks/rightcurly.xml.template

Issue #17531: Removed site log warnings for blocks modules

---

src/site/xdoc/checks/design/designforextension.xml
src/site/xdoc/checks/design/designforextension.xml.template
src/site/xdoc/checks/design/finalclass.xml
src/site/xdoc/checks/design/finalclass.xml.template
src/site/xdoc/checks/design/hideutilityclassconstructor.xml
src/site/xdoc/checks/design/hideutilityclassconstructor.xml.template
src/site/xdoc/checks/design/innertypelast.xml
src/site/xdoc/checks/design/innertypelast.xml.template
src/site/xdoc/checks/design/interfaceistype.xml
src/site/xdoc/checks/design/interfaceistype.xml.template
src/site/xdoc/checks/design/mutableexception.xml
src/site/xdoc/checks/design/mutableexception.xml.template
src/site/xdoc/checks/design/onetoplevelclass.xml
src/site/xdoc/checks/design/onetoplevelclass.xml.template
src/site/xdoc/checks/design/sealedshouldhavepermitslist.xml
src/site/xdoc/checks/design/sealedshouldhavepermitslist.xml.template
src/site/xdoc/checks/design/throwscount.xml
src/site/xdoc/checks/design/throwscount.xml.template
src/site/xdoc/checks/design/visibilitymodifier.xml
src/site/xdoc/checks/design/visibilitymodifier.xml.template

Issue #17531: Removed site log warnings for design modules

---

.ci/validation.sh
.circleci/config.yml
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionCaseDefault.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionPatternMatchingInSwitch.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionPatternsInFor.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionPatternsInIfStatement.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionPatternsInSwitch.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionPatternsInTernary.java
src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/antlr4/InputAntlr4AstRegressionPatternsInWhile.java

supplemental: Changing comment to jdk22

---

src/site/xdoc/checks/coding/missingnullcaseinswitch.xml.template
src/site/xdoc/checks/coding/missingswitchdefault.xml.template
src/site/xdoc/checks/coding/patternvariableassignment.xml.template
src/site/xdoc/checks/coding/unusedcatchparametershouldbeunnamed.xml.template
src/site/xdoc/checks/coding/unusedlambdaparametershouldbeunnamed.xml.template
src/site/xdoc/checks/coding/unusedlocalvariable.xml.template
src/site/xdoc/checks/coding/whenshouldbeused.xml.template
src/site/xdoc/checks/misc/finalparameters.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingNullCaseInSwitchCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/PatternVariableAssignmentCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLambdaParameterShouldBeUnnamedCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckExamplesTest.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/coding/WhenShouldBeUsedCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingnullcaseinswitch/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/patternvariableassignment/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlambdaparametershouldbeunnamed/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/coding/whenshouldbeused/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/Example4.java

Issue #17429: Relocate inputs to compilable path for Xdocs module

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4862todocomments/InputTodoCommentAllVariants.java
src/main/resources/google_checks.xml
src/site/xdoc/checks/misc/todocomment.xml
src/site/xdoc/checks/misc/todocomment.xml.template
src/site/xdoc/google_style.xml

resolves: #17501
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/f3d0e6d4aa5b6e25a9d3a6b9d5425972/raw/18a7ee9a1016eb7b314e7508a68618a89257170e/master_todo.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/b53a185be531c4ac11653a45b478e2a1/raw/9d92392250ec9bcb8b7191ea4d6b9ada0f854e7b/patch_todo.xml

Issue #17501: Add TodoComment Check to the google config

---

config/checkstyle-checks.xml
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequencesForEscapedS.java
src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule232specialescape/InputSpecialEscapeSequencesInTextBlockForUnicodeValues.java
src/main/resources/google_checks.xml

part of #17551
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/2f62c8fabd1ea8fbc7ceaf6f8b4d19b5/raw/bc72ae7f2a27f8eab15dbd13474be89eba348f7d/master_illegaltext.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/f4bc1e92062712f41048c8282e8e283c/raw/50c098d67286d281d864398d2b4c3a8ed4461003/patch_illegaltext.xml

Issue #17551: Violation on Unicode value of '\s'

---

azure-pipelines.yml

Issue #17429: Migrating Azure CI to jdk21

---

config/jsoref-spellchecker/whitelist.words
docs/TestingTechniques.md

Issue #17404: Created wiki page on TDD

---

.github/workflows/no-exception-workflow.yml

Issue #17429: Migrating no-exception-workflow CI to jdk21

---

appveyor.yml

Issue #17429: Migrating Appveyor CI to jdk21

---

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

Issue #17176: United filter and checks validations

---

.cirrus.yml
.github/workflows/check-performance-regression.yml
.github/workflows/checker-framework.yml
.github/workflows/pitest.yml
.github/workflows/run-checkstyle-ast-print.yml
.github/workflows/run-checkstyle.yml
config/checker-framework-suppressions/checker-index-suppressions.xml
config/checker-framework-suppressions/checker-lock-tainting-suppressions.xml
config/checker-framework-suppressions/checker-methods-resource-fenum-suppressions.xml
config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
config/checker-framework-suppressions/checker-purity-value-returns-suppressions.xml
config/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml
config/checker-framework-suppressions/checker-signature-gui-units-init-suppressions.xml

Issue #17429: Migrating Multiple CI to Jdk21

---

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml
src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java

Issue: #14084
**Suppression removed:**
```
<checkerFrameworkError unstable="false">
<fileName>src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java</fileName>
<specifier>return</specifier>
<message>incompatible types in return.</message>
<lineContent>return returnValue;</lineContent>
<details>
type of expression: @Initialized @Nullable DetailAST
method return type: @Initialized @NonNull DetailAST
</details>
</checkerFrameworkError>
```

Issue #14084: Resolved CheckerFramework violation

---

.circleci/config.yml
config/linkcheck-suppressions.txt
pom.xml

Issue #17429: Migrating CircleCI to JDK21

---

config/intellij-idea-inspections-misc.xml
src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java

Issue #17429: Migrating Ispection Idea to jdk21

---

config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/EmptyBlocksMayBeConciseTest.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputFormattedTryCatchIfElse.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputTryCatchIfElse.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByVariableName.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchEmptyComment.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputFormattedEmptyBlocksAndCatchBlocks.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputFormattedEmptyCatchEmptyComment.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputCatchParametersOnNewLine.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputFormattedCatchParametersOnNewLine.java
src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule62donotignoreexceptions/InputEmptyFinallyBlock.java
src/main/resources/google_checks.xml

part of : #17563 
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/e1438c3d37ea33baff8301aec7ec41b9/raw/49a29c43657baf6defd598ab9f78263345aaa346/master_emptycatchblock.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/5e2fed73f37698ca3ee316e5f42df083/raw/ce74c66e85578bb1628e918a9777eca7edf12135/patch_emptycatchblock.xml

Issue #17165: Remove exceptionVariableName property of EmptyCatchBlock

---

config/jsoref-spellchecker/whitelist.words
config/version-number-rules.xml
pom.xml
src/test/java/com/puppycrawl/tools/checkstyle/AbstractGuiTestSupport.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/MainTest.java
src/test/java/com/puppycrawl/tools/checkstyle/gui/TreeTableTest.java

Issue #17330: Upgrade caciocavallo to latest

---

src/main/java/com/puppycrawl/tools/checkstyle/Main.java
src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
src/main/java/com/puppycrawl/tools/checkstyle/ThreadModeSettings.java
src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocTag.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/TagInfo.java
src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java
src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputViolation.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules/MessageLevelPair.java
src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java

Issue #17299: Convert eligible classes to records One

---

config/jsoref-spellchecker/whitelist.words
src/site/xdoc/checks/imports/importorder.xml
src/site/xdoc/checks/imports/importorder.xml.template
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example10.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example11.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example12.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example2.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example3.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example4.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example5.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example6.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example7.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example8.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/Example9.java

Issue #17429: Relocate inputs to compilable path for Xdoc Module 2

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java

Issue #17673: Conversion to Enhance Switch for SuppressWarningCheck

---

.circleci/config.yml

Issue #17104: migrate IDEA inpection in CI to 2025.2

---

docs/BEGINNING_DEVELOPMENT.md
src/main/resources/sun_checks.xml

Issue #17429: Changing References to JDK21

---

.circleci/config.yml

Reverts checkstyle/checkstyle#17679

Revert "Issue #17104: migrate IDEA inpection in CI to 2025.2"

---

.ci/no-exception-test.sh

Issue  #17429: Replacing JDK Back to 17 In Gradle Build to Fix CI

---

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
src/main/resources/com/puppycrawl/tools/checkstyle/messages.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_de.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_es.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_fi.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_fr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_ja.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_pt.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_ru.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_tr.properties
src/main/resources/com/puppycrawl/tools/checkstyle/messages_zh.properties
src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java

Issue #3110: Remaining hardcoded english in Checker.java is translated in message files

---

.ci/error-prone-check.groovy
.github/workflows/error-prone.yml

Issue #17269: Remove Extra Installation of Groovy from Error Prone

---

config/checkstyle-non-main-files-suppressions.xml
config/google-java-format/excluded/compilable-input-paths.txt
src/it/java/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/ColumnLimit100Test.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputColumnLimitEdgeCase.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputFormattedColumnLimitEdgeCase.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputFormattedTextBlockColumnLimit.java
src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputTextBlockColumnLimit.java
src/main/resources/google_checks.xml
src/site/xdoc/filters/suppresswithplaintextcommentfilter.xml
src/site/xdoc/filters/suppresswithplaintextcommentfilter.xml.template
src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java

resolves #11867
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/2f62c8fabd1ea8fbc7ceaf6f8b4d19b5/raw/6281804ddac26777baac8e4fef9eef76aa076a82/master_linelength.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/f4bc1e92062712f41048c8282e8e283c/raw/1f9b1df02f6be4017d7b3909c41c70676a9bea3c/patch_linelength.xml

Issue #11867: Suppress Line-Length violations for text-block content

---

.ci/validation.sh
.circleci/config.yml
config/jsoref-spellchecker/whitelist.words
config/openrewrite-recipes-checkstyle.properties
pom.xml
rewrite.yml

Issue #17717: Added checkstyle-openrewrite-recipes

---

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceBeforeLeftCurlyOfEmptyBlock.java

supplemental: Add references to #17715

---

src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/modifier/ClassMemberImpliedModifierCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/modifier/InterfaceMemberImpliedModifierCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpMultilineCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpOnFilenameCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpSinglelineCheck.xml
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/regexp/RegexpSinglelineJavaCheck.xml

Issue #13626: Simplified modifier and regexp modules javadocs

---

config/jsoref-spellchecker/whitelist.words
pom.xml
src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
src/main/java/com/puppycrawl/tools/checkstyle/site/ModuleJavadocParsingUtil.java
src/main/java/com/puppycrawl/tools/checkstyle/site/SiteUtil.java

Issue #17487: Add `StreamRulesRecipes`

---

pom.xml

Issue #17487: Add `JavaRecipeBestPractices`

Issue #17487: Add `JavaRecipeBestPractices`

---

pom.xml

Issue #17487: Add: `org.openrewrite.maven.BestPractices`

---

src/it/java/com/google/checkstyle/test/chapter5naming/rule522classnames/ClassNamesTest.java
src/it/resources/com/google/checkstyle/test/chapter5naming/rule522classnames/InputClassNamesWithUnderscore.java
src/main/resources/google_checks.xml

part of #17507
Diff Regression config: https://gist.githubusercontent.com/mohitsatr/3a1330cde557521408301cb0d9c3cc26/raw/0b6f88fef0b0c0f7087c79d6851560517c3ca1dd/classname_master.xml
Diff Regression patch config: https://gist.githubusercontent.com/mohitsatr/b296c3e0c359337ce32033121be97a45/raw/0e76405632551df14e2921e9dd05d992d26a3d76/classname_patch.xml

Issue #17507: Add support for underscores in class name

---

src/test/java/com/puppycrawl/tools/checkstyle/IndentationTrailingCommentsVerticalAlignmentTest.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava1.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda1.java

#17128 
Updated InputFiles for the following:
InputIndentationCustomAnnotation.java
InputIndentationFromGuava1.java
InputIndentationLambda.java
InputIndentationLambda1.java

Issue #17128: Fix indentation comments in annotation input files

---

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedCatchParameterShouldBeUnnamedCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamed.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedInsideAnonClass.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedNested.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedcatchparametershouldbeunnamed/InputUnusedCatchParameterShouldBeUnnamedWithResourceAndFinally.java

Issue #15456
Defined violation messages for UnusedCatchParameterShouldBeUnnamedCheck

Issue #15456: Violation messages for UnusedCatchParameterShouldBeUnnamedCheck

---

src/site/xdoc/checks/sizes/lambdabodylength.xml
src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheckTest.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthDefault.java
src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthMax.java
src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthExamplesTest.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/Example1.java
src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/Example2.java

Issue #15456
Defined violation messages for LambdaBodyLengthCheck

Issue #15456: Defined violation messages for LambdaBodyLengthCheck
