checkstyle/checkstyle

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java, src/xdocs/config_annotation.xml
Fixed typo in property name <b>allowSamelineParameterizedAnnotation</b> instead of <b>allowSamelineParametrizedAnnotation</b>
Fixed in sources and xdoc config.
=> Annotation Location Check, fixed typo in property name, issue #585

checkstyle_checks.xml, import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/Utils.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java, src/main/resources/google_checks.xml, src/main/resources/sun_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/UtilsTest.java, src/xdocs/config.xml
Added <b>fileExtensions</b> property to Checker and TreeWalker, updated sun_checks.xml
```xml
<property name="fileExtensions" value="java, properties, xml"/>
...
<property name="fileExtensions" value="java"/>
...
```
Tested on pdf file:
```
$ java -jar checkstyle-6.3-SNAPSHOT-all.jar -c /sun_checks.xml Books/Spring\ in\ Action\,\ 3rd\ Edition.pdf 
Audit done.
```
=> Added file extensions property to Checker & TreeWalker, issue #25

src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/sun_style.xml
According to #549 
Here's report after my updates:
http://alexkravin.github.io/linkcheck/linkcheck.html
There're 25 errors, but as you can see all of them because of ping timeout - that's because I used vpn connection during building, seems to be it's not fast enough, these links are ok.
=> Resolving linkcheck plugin errors, issue #549

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages.properties, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/InputEmptyCatchBlockCheck.java, src/xdocs/config_blocks.xml, src/xdocs/google_style.xml
According to #571 
New Check was added, EmptyCatchBlockCheck is fully covered by UTs, EmptyBlockCheck was updated: removed references to checking catch blocks, updated UTs.
Updated docs.
What exactly have I do to update Coverage page (http://checkstyle.sourceforge.net/google_style.html) ?
Shouldn't it be updated automatically?
https://github.com/checkstyle/google-style-config-test will be updated asap
=> New Check: Empty Catch Block Check, issue #571

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
Thread-safety given by `StringBuffer` doesn't give any benefit when used within one method, so in such cases `StringBuilder` is safe and more efficient replacement.
=> Replace StringBuffer with StringBuilder to improve performance

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/metrics/InputBooleanExpressionComplexityNPE.java
According to #654 
Fixed NPE, added UT and input.
Npe occurred because multi-catch pipe operator wasn't in consideration of <b>binary or</b> operator possible usage.
Detailed exception's information is coming from TreeWalker and exception between 
Audit started...
and
Audit finished.
Is coming from Checker. But in Checker there's no catch block for such exceptions, that's why it looks like swallowing.
=> Boolean Expression Complexity Check, fixed NPE, issue #654

src/xdocs/google_style.xml
Fixed links for config, checked links for tests.
Removed extra table cell.
Removed [] in config/test column.
Fixed spacing of checkstyle checks with multiple config/tests.
Fixed small spelling mistake.
=> Update config links in Google Style, Issue #686

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/xdocs/config_coding.xml
According to #607 
Updated docs for <b>ignoreFormat</b> option.
Got rid of ambiguity about it.
=> Hidden Field Check, updated docs for 'ignoreFormat' option, issue #607

pom.xml
Both runtime library and Maven plugin have to be updated at the same time, so property with version was introduced.
=> Update antlr4 library from 4.3 to 4.5, issue #644

pom.xml
Bugs:
* [MJAR-135] - encoding problem with folder-names
* [MJAR-151] - Error assembling JAR on OS X
* [MJAR-179] - Adding empty files to jar failed with a ZipException : bad CRC checksum
* [MJAR-185] - Update version of plexus-archiver to 2.7.1
* [MJAR-188] - maven-jar-plugin is very slow on machines with slow Unix group lookups
* [MJAR-189] - Upgrade plexus-archiver dependency to v2.9
Improvements:
* [MJAR-178] - Change information on site
* [MJAR-180] - Upgrade to Maven 2.2.1 compatiblity
* [MJAR-181] - MavenProject/MavenSession Injection as a paremeter instead as a component.
* [MJAR-182] - Update version of plexus-archiver to 2.6.3
* [MJAR-184] - Update version of plexus-archiver to 2.7
* [MJAR-186] - Upgrade maven-plugins-testing-harness from 1.2 to 1.3
* [MJAR-187] - Upgrade …
=> Update Maven JAR Plugin to 2.6, issue #644

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
Extended acceptable tokens array as there was a bug which let user set only variables or/and parameters.
Now all supported tokens are acceptable and won't lead to error.
=> Final Local Variable Check, extended acceptable tokens

.travis.yml
Command taken from https://github.com/trautonen/coveralls-maven-plugin#jacoco.
As the next step, probably we can simplify `travis` profile. I'm not sure why we have there `surefire-report` plugin.
=> Fix command used to invoke Coveralls, issue #806

pom.xml
1. POM is cleaned up and reformatted
1. tidy-maven-plugin is introduced to enforce [POM Code Convention](http://maven.apache.org/developers/conventions/code.html#POM_Code_Convention) and fail the build on style violation.
=> Introduce tidy-maven-plugin to enforce POM canonical order, issue #809 

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/CheckStyleTask.java, src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/main/java/com/puppycrawl/tools/checkstyle/Utils.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/UtilsTest.java
>While it's not safe in the general case to ignore exceptions that are thrown when closing an I/O resource, it should generally be safe in the case of a resource that's being used only for reading, such as a Reader. Unlike with writable resources, there's no chance that a failure that occurs when closing the reader indicates a meaningful problem such as a failure to flush all bytes to the underlying resource.
`Reader` and `InputStream` instances are closed using `Closeables.closeQuietly()`, while `RandomAccessFile` is closed with `Closeables.close()` that throws `IOException` and needs to be handled.
From Javadoc:
>```java
public static void close(@Nullable
Closeable closeable,
boolean swallowIOException)
throws IOException
```
>Closes a Closeable, with control over whether an IOException …
=> Add logging to empty catch blocks to fix PMD violations, issue #744

config/findbugs-exclude.xml, pom.xml
Package `com.puppycrawl.tools.checkstyle.grammars` contains only autogenerated code, so it should be excluded from Findbugs analysis.
=> Disable Findbugs for 'grammars' package, issue  #778

README.md
Now the coveralls.io badge will have a consistent flat look like the other badges.
**Before:**
**After:**
=> Use SVG badge for coveralls.io.

src/xdocs/checks.xml
Previously `MissingDeprecated` and `MissingOverride` had truncated
descriptions.
=> Complete descriptions in checks index

pom.xml
In version 2.7 the new `cobertura-integration-test` report is generated by
default.
As Checkstyle doesn't have `integration-test` phase, just `cobertura`
report is enough and this needs to be set explicitly.
More information in #916.
=> Update cobertura-maven-plugin to 2.7, issue #916

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
In order to pass the test `equals` method must reference only final fields. Otherwise, if the value of this field changes, the same object may not be equal to itself at two different points in time.
=> Use EqualsVerifier to test SuppressWithNearbyCommentFilter. #1088

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/design/InputThrowsCount.java, src/xdocs/config_design.xml
Report: http://vladlis.github.io/
The option has suppressed 283 violations while running the Check on openjdk7 and spring.framework with default properties (from 3733 to 3450).
=> ThrowCountCheck should have option to skip private methods, #1136

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
100% test coverage for com.puppycrawl.tools.checkstyle.checks.sizes, issue #1024.
I made some fixes in visitToken() according to my assumptions https://github.com/checkstyle/checkstyle/issues/1167#issuecomment-109049527
and also I refactored the method.
cobertura report 
http://mezk.github.io/cobertura/
checkstyle-tester report befor changes in MethodCountCheck (method visitToken() )
http://mezk.github.io/site_before/index.html
checkstyle-tester report after changes in MethodCountCheck (method visitToken() )
http://mezk.github.io/site_after/index.html
git diff shows that reports before and after changes are equal.
=>  100% test coverage for com.puppycrawl.tools.checkstyle.checks.sizes,

pom.xml
Release Notes - Maven Assembly Plugin - Version 2.5.5
* Bug
* [MASSEMBLY-767] - Schema missing from the web site
* [MASSEMBLY-768] - JarInputStream unable to find  manifest
created by version 2.5.4
* [MASSEMBLY-769] - ZIP fileMode permissions not properly set with
dependencySet and unpackOptions
=> Update maven-assembly-plugin to 2.5.5

src/xdocs/config_imports.xml
Mentioning that static imports are allowed from java.lang and same package.
=> Updated description for RedundantImport

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractIllegalCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/Guard.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractTypeParameterNameCheck.java
Removing **assert** statements in a project because it is difficult to make them 100% covered by tests (they require executions with both asserts enabled and disabled). In addition, they are not really useful in production:
http://stackoverflow.com/questions/1957645/when-to-use-an-assertion-and-when-to-use-an-exception
http://docs.oracle.com/javase/6/docs/technotes/guides/language/assert.html
Also reduced branch coverage for AbstractTypeParameterNameCheck to make project compile (some branches were covered, so removing lines with them reduced total coverage for this class)
=> Removed all assert statements

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierTest.java
Reports were generated and compared due to refactoring of RedundantModifierCheck: http://rdiachenko.github.io/
Reports for Guava project before check's refactoring and after are identical.
=> 'RedundantModifierCheck' was refactored, UT coverage improved

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractTypeParameterNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeParameterNameTest.java
Reports for Guava and Hibernate projects before check's refactoring and after are identical: http://rdiachenko.github.io/
Reports were generated on all child checks of AbstractTypeParameterNameCheck:
```
<module name="ClassTypeParameterName"/>
<module name="InterfaceTypeParameterName"/>
<module name="MethodTypeParameterName"/>
```
=> Issue #1288: 'AbstractTypeParameterNameCheck' refactored, UT coverage improved

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/Utils.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/UtilsTest.java
In `JavadocUtils` any reflection-related exception would mean programmer's mistake with no recovery. In such cases checked exceptions are useless, so new method in utils is provided to wrap any checked exceptions into unchecked ones.
=> Remove non-testable reflection code from JavadocUtils. #1308

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputJavaDocTagContinuationIndentation.java, src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputJavaDocTagContinuationIndentationOffset3.java
=> Add test coverage to JavadocTagContinuationIndentation check. #1308

config/ant-phase-verify.xml, config/build.xml, config/checkstyle_checks.xml, config/java_regexp.header, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java, src/xdocs/config_header.xml
After fix Header does not rise any violation with [default config](https://github.com/checkstyle/checkstyle/commit/6fbce5c80b62931ad2f532819f15791a36cdb6ba#diff-6e886340e5a2ff9bd26e48165c70663dL58). In accordance with [manual](http://checkstyle.sourceforge.net/config_header.html#RegexpHeader) default value for property ```header``` is ```null```. 
[Reports](http://mezk.github.io/index.html).
=> Fix Header causing exception with default config, issue #1129.

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java
Reports are exactly the same over huge codebase:
```
--- target/checkstyle-result.xml
+++ target-6.8.1/checkstyle-result.xml
@@ -1,5 +1,5 @@
-<checkstyle version="6.9-SNAPSHOT">
+<checkstyle version="6.8.1">
```
=> Remove dead code from NewHandler in Indentation check. #1270

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/InputTypeParamsTags.java, src/xdocs/config_javadoc.xml
Checkstyle tester output - http://pbaranchikov.github.io/checkstyle/javadoc-type/checkstyle.html
=> JavadocType does not check parameters in inner classes, fixes  #1421

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/InputLeftCurlyEnums.java, src/xdocs/config_blocks.xml
Added setter for ```ignoreEnums```, updated javadoc/xdoc and provided tests for option.
=>  LeftCurlyCheck have hidden option, issue #975 

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/coding/InputIllegalType.java
Checkstyle reports: http://baratali.github.io/illegal_type/
**The reports are identical**
Details:
1) Removed useless getters
2) In getCanonicalName(importAst) method, check for STAR token is not necessary because this method receives only imports without 'stars': https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java#L252
=> Issue #1293: Refactoring of IllegalTypeCheck

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocUtils.java, src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputCorrectJavaDocParagraphCheck.java
Reports were generated for the following config before and after changes:
```xml
<module name="JavadocParagraph"/>
<module name="AtclauseOrder"/>
<module name="JavadocType">
<property name="authorFormat" value="\S"/>
</module>
<module name="JavadocMethod">
<property name="allowUndeclaredRTE" value="true"/>
<property name="allowThrowsTagsForSubclasses" value="true"/>
<property name="allowMissingPropertyJavadoc" value="true"/>
</module>
<module name="JavadocVariable"/>
<module name="JavadocStyle">
<property name="scope" value="public"/>
</module>
<module name="JavadocTagContinuationIndentation"/>
<module name="SingleLineJavadoc"/>
<module name="SummaryJavadoc"/>
<module name="NonEmptyAtclauseDescription"/>
```
Reports are identical:
```
diff pre/checkstyle-result.xml …
```
=> Add test case and refactor JavadocUtils. #1308

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputCustomTag.java, src/test/resources/com/puppycrawl/tools/checkstyle/javadoc/InputParsingErrors.java
Reports are identical:
```
diff pre/checkstyle-result.xml post/checkstyle-result.xml -s
Files pre/checkstyle-result.xml and post/checkstyle-result.xml are identical
```
The following config was used on 10,000 source files to generate reports:
```
<module name="JavadocParagraph"/>
<module name="AtclauseOrder"/>
<module name="JavadocTagContinuationIndentation"/>
<module name="SingleLineJavadoc"/>
<module name="SummaryJavadoc"/>
<module name="NonEmptyAtclauseDescription"/>
</module>
```
Fixes #1308.
=> Improve test coverage in AbstractJavadocCheck. #1308

src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
Fixes `ExceptionNameDoesntEndWithException` inspection violation in test code.
Description:
>Reports exception classes whose names don't end with 'Exception'.
=> Correct name of exception. #1555

src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java
Fixes `MethodCanBeVariableArityMethod` inspection violations in test code.
Description:
>Reports methods with which can be converted to be a variable arity/varargs method, available in Java 5 and newer.
This inspection only reports if the project or module is configured to use a language level of 5.0 or higher.
=> Use varargs in test code. #1555

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Fixes `StaticFieldReferenceOnSubclass` inspection violations.
Description:
>Reports static field accesses where the call is qualified by a subclass of the declaring class, rather than the declaring class itself. Java allows such qualification, but such accesses may be confusing, and may indicate a subtle confusion of inheritance and overriding.
=> Do not use static field referenced by subclass. #1555

pom.xml
Should fix plenty of violations, but I suppose I'll do second part for these checks
Newlines should follow each element:
Noncompliant Code Example
```<parent><child /></parent> ```
Compliant Solution
```
<parent>
<child />
</parent>
```
=> New line check for pom.xml. Issue #46

pom.xml
Proper indentation is a simple and effective way to improve the code's readability. Consistent indentation among the developers on a team also reduces the differences that are committed to source control systems, making code reviews easier.
By default this rule checks that each block of code is indented but not the size of this indent. The parameter "indentSize" allows the expected indent size to be defined. Only the first line of a badly indented section is reported.
I'm not sure about other violations. If anything left after #1882 I'll fix it next time
=> Indentation fix for pom.xml. Issue #46

pom.xml
Proper indentation is a simple and effective way to improve the code's readability. Consistent indentation among the developers on a team also reduces the differences that are committed to source control systems, making code reviews easier.
By default this rule checks that each block of code is indented but not the size of this indent. The parameter "indentSize" allows the expected indent size to be defined. Only the first line of a badly indented section is reported.
Should fix all violations in pom
=> Indentation fixes for pom.xml. Issue #46

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
@romani
According to [documentation](http://checkstyle.sourceforge.net/config_sizes.html#MethodCount), MethodCountCheck checks the number of **methods** declared in each type. That means that user should specify only one toke from configuration - METHOD_DEF. But currect set of acceptable tokens for the check is:
```java
TokenTypes.CLASS_DEF,
TokenTypes.ENUM_CONSTANT_DEF,
TokenTypes.ENUM_DEF,
TokenTypes.INTERFACE_DEF,
TokenTypes.METHOD_DEF
```
That means that user can use the following configuration for the check:
```xml
<module name="MethodCount">
<property name="tokens" value="ENUM_CONSTANT_DEF"/>
</module>    
```
With the configuration the check will throw NPE on file ```checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/sizes/MethodCountCheckInput.java``` :
```
SEVERE: …
```
=> Corrected acceptable, required and default token sets , issue #655

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Fix for:
- JavadocMethod ```Missing a Javadoc comment.```
- JavadocVariable ```Missing a Javadoc comment.```
=> Issue #1566: 'missing javadoc comment' violations fixed for JavadocTokenTypes

src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
The issue was stream not being closed at all or closed, but not in finally block.
Fixes some `IOResource` inspection violations.
Description:
>Reports any I/O resource which is not safely closed in a finally block. Such resources may be inadvertently leaked if an exception is thrown before the resource is closed. I/O resources checked by this inspection include java.io.InputStream, java.io.OutputStream, java.io.Reader, java.io.Writer and java.io.RandomAccessFile. I/O resources which are wrapped by other I/O resources are not reported, as the wrapped resource will be closed by the wrapping resource.
=> Issue #1555: Use try-with-resources to close streams in test code

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/PropertiesExpander.java
I found one more way of suppressing inspections thanks to the answer for my question: http://stackoverflow.com/questions/32363262/intellij-idea-suppresswarnings-for-inspection-with-name-of-tool/
Is it better?
Javadoc remains clear:
=> Issue #2065: Add suppression for IntelliJ IDEA inspection as comment

pom.xml
Looks like it was missed in pom.
=> Issue #1290: AbstractOptionCheck has been removed from list of checks to cover

config/intellij-idea-inspections.xml, src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java
ParameterNameDiffersFromOverriddenParameter does not require parameters to match names anymore if method is from external library and parameter may be wrongly named there.
=> Issue #1555: Tune down inspection for overridden parameter names

config/checkstyle_checks.xml, src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandsoacing/CustomImportOrderTest.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
Fixes some `SpellCheckingInspection` inspection violations.
Description:
>Spellchecker inspection helps locate typos and misspelling in your code, comments and literals.
=> Issue #2080: Fix typos in code

src/test/java/com/puppycrawl/tools/checkstyle/CommitValidationTest.java
Fixes `UseOfObsoleteAssert` inspection violations introduced in #1518.
Description:
>Reports any calls to methods from the junit.framework.Assert class. This class is obsolete and the calls can be replaced by calls to methods from the org.junit.Assert class.
=> Issue #1555: Remove usage of obsolete junit.framework.Assert class

src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java
Constructor of `FileInputStream` throws `FileNotFoundException`, but validation happens in native method:
```java
/**
* Opens the specified file for reading.
* @param name the name of the file
*/
private native void open0(String name) throws FileNotFoundException;
```
Error message is locale and system dependent, so it cannot be reliably checked in test. It's better to use manual file existence validation instead.
=> Issue #2137: Make test for FileTabCharacter locale and OS independent

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
Restricting the number of break and continue statements in a loop is done in the interest of good structured programming.
One break and continue statement is acceptable in a loop, since it facilitates optimal coding. If there is more than one, the code should be refactored to increase readability.
=> Issue #46: loops should not have more then one break or continue statement

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/doclets/InputTokenTypesDocletCorrect.java
This PR needs to be rebased on #2196 and modified a bit to avoid [extra output](https://travis-ci.org/checkstyle/checkstyle/jobs/80798099#L614-L617).
=> Issue #2126: Make coverage 100% for TokenTypesDoclet

pom.xml
Changelog: https://github.com/codehaus-plexus/plexus-compiler/compare/plexus-compiler-2.5...codehaus-plexus:plexus-compiler-2.6
=> Pull #2247: Update plexus-compiler-javac-errorprone to 2.6

pom.xml
Change log 1.6.3 (2015-10-02)
----------------------------
* Mock name in @Mock(name="abc") annotations are no longer ignored for the Mockito API extension
* Fixed NPE in withArguments() constructor (thanks to Tomoyuki Saito for pull request)
* Upgraded Javassist dependency to version 3.20.0-GA.
* Using soft reference in classloader cache
* MockClassloader now extends Javassist Loader classloader to implement findClass etc
* PowerMock now works better with ByteBuddy (issue 579)
* This allows creating mocks in the applyInterceptionPolicy method of MockPolicy, which in turn allows using MockPolicy together with PowerMockRule (issue 581).
* Upgraded the powermock-easymock extension to use EasyMock 3.4
=> Pull #2293: Update PowerMock to 1.6.3

src/xdocs/index.xml.vm
Both links are forwarding to bitbucket project which is being updated.
=> Issue #1238: Replaced outdated link for bamboo-checkstyle-plugin

src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/InputModifier.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/InputParameterNumberCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/InputSimple.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckInput.java
1 input copied. InputModifier lost the javadoc tag since this is the only place the file is for, which is not a modifier package.
=> Issue #2161: unify test input locations for sizes package

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputMissingJavadocTags.java
Fix for issue #2398 
* Added test data to expose the error.
* Added a check that regexp matching second line of a multiline tag actually finds anything.
=> Fix for issue #2398: Exception thrown for incomplete @return tag if next line is empty

config/ant-phase-verify.xml, config/suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/BaseFileSetCheckTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/DebugAuditAdapter.java, src/test/java/com/puppycrawl/tools/checkstyle/DebugChecker.java, src/test/java/com/puppycrawl/tools/checkstyle/DebugFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJava14LexerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CompareTreesWithComments.java
Can't test "GeneratedJava14LexerTest.testUnexpectedChar" since I'm windows.
Removed exclude in "ant-phase-verify". It's only parsing the "src" directory, so it shouldn't be an issue.
Added suppressions for "BaseCheckTestSupport" since it covers alot of things.
Added missing headers.
Split long/complex methods into 2.
Made "CompareTreesWithComments.expectedTree" private with a setter. If this isn't acceptable, the only other option I see here is a suppression.
=> Issue #2421: expanded checks on test directory

config/suppressions.xml, src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java, src/it/java/com/google/checkstyle/test/base/ConfigurationBuilder.java, src/it/java/com/google/checkstyle/test/base/IndentationConfigurationBuilder.java, src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandsoacing/CustomImportOrderTest.java, src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAroundTest.java, src/it/java/com/google/checkstyle/test/chapter5naming/rule521packagenames/PackageNameTest.java, src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/ClassMethodTypeParameterNameTest.java
Fixed AbstractClassName, DeclarationOrder, RightCurly, EmptyLineSeparator, Regexp, and VisibilityModifier.
MagicNumber was also already being suppressed.
Test has no abstract on BaseCheckTestSupport, so I made IT the same. This was related to AbstractClassName.
msgNonGroup in CustomImportOrderTest was not being used, so it was removed. This was related to VisibilityModifier.
=> Issue #2421: enabling checking on it folder

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_coding.xml, src/xdocs/config_design.xml, src/xdocs/config_filters.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_modifier.xml, src/xdocs/config_naming.xml, src/xdocs/config_regexp.xml, src/xdocs/config_sizes.xml, src/xdocs/config_whitespace.xml
preview of xdoc check validation. no fixes here, will be in separate commit. shouldn't be merged until then.
use reflection alot here.
**Added the following requirements:**
All sections shouldn't end with 'Check'.
All sections should be able to be instantiated.
All sub-sections should follow the order: Description, Properties (optional), Examples, Example of Usage, Package, Parent Module
Following sub-sections can be out of order and optional: Notes, Rule Description, Use Case
Package must be the check's package location.
Parent Module must be TreeWalker if it extends Check, otherwise must be Checker.
Properties is optional, but must exist if there is a bean to be documented, or its tokens should be documented. (default != acceptable != required)
**Still to implement:**
If tokens property …
=> Issue #2442: adding xdoc check validation

pom.xml
Release Notes - Apache Maven Shade Plugin  Version 2.4.2
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12317921&version=12333008
Bugs:
* [MSHADE-172] - "java.lang.ArithmeticException: / by zero" in MinijarFilter
* [MSHADE-190] - Shade does not relocate the contents of META-INF/services files
* [MSHADE-209] - [REGRESSION] "java.lang.ArithmeticException: / by zero" in MinijarFilter (reporter Jon McLean).
Improvements:
* [MSHADE-205] - Better use of ClazzpathUnit for improved jar minimization (contribution of Benoit Perrot).
* [MSHADE-207] - Replace wrong link to codehaus with correct location
* [MSHADE-210] - Upgrade maven-plugins parent to version 28.
* [MSHADE-211] - Keep Java 1.5
=> Pull #2464: Update Maven Shade Plugin to 2.4.2

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java
PackageNameCheck now extends Check.
Fields and setters copied from AbstractFormatCheck.
**Minor changes**:
Error property moved to MSG_KEY constant.
Fixed minor errors in javadoc.
=> Issue #2451: removed excess hierarchy from PackageNameCheck

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java
TrailingCommentCheck now extends Check.
Fields and setters copied from AbstractFormatCheck, with minor modifications.
setLegalComment's parameter had to change to avoid conflicts with the format field.
DEFAULT_FORMAT was removed since it was only used once.
=> Issue #2451: removed excess hierarchy from TrailingCommentCheck

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java
SuppressWarningsCheck now extends Check.
Fields and setters copied from AbstractFormatCheck, with minor modifications.
Fixed javadocs with class packages in them or needed in them.
=> Issue #2451: removed excess hierarchy from SuppressWarningsCheck

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/XDocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java
AbstractClassNameCheck now extends Check.
Removed DEFAULT_FORMAT as it was only used once.
Added test for missing coverage of 'setFormat'.
=> Issue #2451: removed excess hierarchy from AbstractClassNameCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java
NestedForDepthCheck now extends Check.
Copied methods/fields from abstract.
DEFAULT_MAX was merged with max.
Javadoc was changed to remove statements about abstract class.
=> Issue #2451: removed excess hierarchy from NestedForDepthCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheck.java
InterfaceTypeParameterNameCheck now extends AbstractNameCheck.
Copied methods over, and removed getLocation.
**Comment**:
There is no `InterfaceTypeParameterNameCheckTest`. The file `ClassTypeParameterNameCheckTest` holds tests for all 3 checks that extend `AbstractTypeParameterNameCheck`.
=> Issue #2451: removed excess hierarchy from InterfaceTypeParameterName

src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractOptionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
EmptyBlockCheck now extends Check.
Copied method from AbstractOptionCheck, changed field to option to match setter.
Added test for missing coverage.
=> Issue #2451: removed excess hierarchy from EmptyBlockCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java
EmptyForIteratorPadCheck now extends Check.
Copied methods and fields from abstract.
Added test for missing coverage.
=> Issue #2451: removed excess hierarchy from EmptyForIteratorPadCheck

src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java
This line should be a 'get' because regardless of the contents of `current` the next statements will do another put, replacing the original put contents. This is similar to assigning a value to a variable, and then re-assigning the same variable with the same or similar value.
=> minor: fixed improper put that should be get

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java, src/xdocs/config_javadoc.xml
This is a fix for a problem introduced with Checkstyle 6.10 with commit [#d56a2a3](https://github.com/checkstyle/checkstyle/commit/d56a2a366c6f9e3e8639d492d548ae562b75dc81#diff-6dbb31589372edafae8e79665300f05a), which prevents the *JavadocStyle* check from correctly evaluating the `tokens` property. Since `getRequiredTokens()` was set to return the result of `getAcceptableTokens()`, the `tokens` property was effectively disabled.
For example, the following configuration, which checks end-of-sentence format exclusively on methods, is no longer possible:
```xml
<module name="JavadocStyle">
<property name="severity" value="info"/>
<property name="tokens" value="METHOD_DEF"/>
<property name="scope" value="public"/>
<property name="checkFirstSentence" value="true"/>
<property …
```
=> Fix 'tokens' property in JavadocStyle check

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CaseHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IfHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/PrimordialHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SlistHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java
renamed suggestedChildLevel to getSuggestedChildLevel.
It is a getter and even some methods that call it, like getLevelImpl, are getters.
=> minor: renamed suggestedChildLevel to more natural name

config/suppressions.xml, src/it/java/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/SummaryJavadocTest.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
Requested by mkordas from #2616.
If a xdoc specifies google/sun, then it must appear in the google/sun configuration file.
I'm not happy about the new suppression, but I didn't want to pass the new list around as a parameter or recreate it ever new file/section.
`getCheckStyleChecksReferencedInConfig` throws was changed because of the requirements of ThrowsCountCheck on the method being changed to public.
I plan to make a new issue to re-organize the internal tests.
=> xdoc: added verification of google/sun checks in config

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/InputOverrideAnnotationNoNPE.java
Configuration:
````xml
<module name="ParameterNameCheck">
<property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
<property name="ignoreOverridden" value="true"/>
</module>
</module>
</module>
````
No NPE on the following projects:
[checkstyle](http://mezk.github.io/checkstyle/checkstyle.html)
sevntu checkstyle - 0 violations
guava - 0 violations
[hibernate](http://mezk.github.io/hibernate/checkstyle.html)
[HBase](http://mezk.github.io/HBase/checkstyle.html)
[openjdk](http://mezk.github.io/openjdk/checkstyle.html)
[spring](http://mezk.github.io/spring/checkstyle.html)
[Orekit](http://mezk.github.io/Orekit/checkstyle.html)
=> Issue #2678: Fix NPE in ParameterNameCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ArrayInitHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CaseHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ClassDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/DoWhileHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ForHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IfHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ImportHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LabelHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ObjectBlockHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/PackageDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/PrimordialHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SlistHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SynchronizedHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/WhileHandler.java
Fixed method names so they are more understandable and reflect what the method does. All these changes are contained to `AbstractExpressionHandler` and `LineWrappingHandler` and `BlockParentHandler`.
Improving javadocs of all indentation classes so it may be easier to others to follow what is going on.
**Actual Logic Changes:**
`AbstractExpressionHandler.findSubtreeLines` (now called `addAllSubtreeLines`) had a parameter `allowNesting` but its only use was to send to itself. The method is final, so no one can override the method and make use of the parameter, so I removed it.
=> minor: fixed indentation documentation and method names

config/checkstyle_sevntu_checks.xml, config/sevntu_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java
It is impossible to avoid wildcard as return type, because we don't know the actual type of the
returning object when we invoke the methods. That is why I suppressed some violations.
=> Issue #2661: Enforce ForbidWildcardAsReturnType of sevntu-checkstyle over Checkstyle source code

src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java, src/it/java/com/google/checkstyle/test/base/ConfigValidationTest.java, src/main/java/com/puppycrawl/tools/checkstyle/AuditEvemtFormatter.java, src/main/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatter.java, src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java, src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java, src/test/java/com/puppycrawl/tools/checkstyle/AuditEventUtFormatter.java, src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/BriefUtLogger.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/FileSetCheckLifecycleTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
New message looks like:
```
[WARNING] /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/InputMain.java:3:14: Name 'InputMain' must match pattern '^[a-z0-9]*$'. [TypeName]
[WARNING] /media/andreiselkin/TOURO/IDEA_Projects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/InputMain.java:5:7: Name 'InputMainInner' must match pattern '^[a-z0-9]*$'. [TypeName]
Audit done.
```
=> Issue #2666: Print name of the Check after printing violation message 

src/xdocs/index.xml.vm
I'm the author of sbt-checkstyle-plugin, an SBT plugin from running Checkstyle on Java files in an SBT project. I'd like to have it added to the list of related tools at http://checkstyle.sourceforge.net/index.html#Related_Tools.
I wasn't sure if this was the best way to go about adding it - let me know if there's something else I should do.
=> doc: Add sbt-checkstyle-plugin to list of active tools

pom.xml
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.apache.org/jira/browse/SUREFIRE-1185'>SUREFIRE-1185</a>]
-         single method test spews status of every single other test
</li>
<li>[<a href='https://issues.apache.org/jira/browse/SUREFIRE-1187'>SUREFIRE-1187</a>]
-         JUnit4 Provider created unnecessary Runner instance
</li>
<li>[<a href='https://issues.apache.org/jira/browse/SUREFIRE-1189'>SUREFIRE-1189</a>]
-         Prevent from I/O leakage. Thus close streams in finally block.
</li>
<li>[<a href='https://issues.apache.org/jira/browse/SUREFIRE-1192'>SUREFIRE-1192</a>]
-         Fixed Sonar and FindBug issues
</li>
<li>[<a href='https://issues.apache.org/jira/browse/SUREFIRE-1193'>SUREFIRE-1193</a>]
-         Surefire 2.19 hangs in the log4j build
</li>
<li>[<a …
=> minor: Update Maven Surefire and Failsafe plugin

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputJavadocPosition.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputJavadocPositionOnlyComments.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputJavadocPositionWithSinglelineComments.java
I generated checkstyle reports on all projects in project-to-test-on.txt by checkstyle-tester (there was only one Javadoc check, AtclauseOrderCheck, in config file). There is no any exceptions in reports.
=> Issue #325: Check placement of Javadoc comments in AbstractJavadocCheck

config/checkstyle_sevntu_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
According to     
https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html
https://docs.oracle.com/javase/7/docs/api/java/util/Vector.html
http://stackoverflow.com/a/1386288/1015848
>A more complete and consistent set of LIFO stack operations is provided by the Deque interface and its implementations, which should be used in preference to Stack class. 
>As of the Java 2 platform v1.2, Vector class was retrofitted to implement the List interface, making it a member of the Java Collections Framework. Unlike the new collection implementations, Vector is synchronized. If a thread-safe implementation is not needed, it is recommended to use ArrayList in place of Vector.
So, java.util.Vector and java.util.Stack should be prohibited in our code.
@romani 
I used ForbidInstantiation and …
=> Pull #2859: Disallow usage of java.util.Stack and java.util.Vector in code

src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/InputInnerAssignmentLambdaExpressions.java
I couldn't fix both lambdas.
If left as is, Eclipse gave the error `Local variable pressed defined in an enclosing scope must be final or effectively final`.
I was able to fix the second one, but the first one couldn't be fixed the same way as Eclipse gave the error `Syntax error on token(s), misplaced construct(s)`.
I couldn't leave the original `boolean pressed = ...` outside the lambda because Eclipse gae the error `Lambda expression's local variable pressed cannot redeclare another local variable defined in an enclosing scope.`.
Code coverage was not required for the first lambda.
=> Issue #2904: fixed bad code in InputInnerAssignmentLambdaExpressions

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/java.g
Issue #2973
I will do a separate PR for each unused grammar item. There will be 2 more, one is questionable.
This one is for FLOAT_SUFFIX.
It has remained unused for atleast 5 years.
=> Issue #2973: removed unused FLOAT_SUFFIX from java.g

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/java.g
Issue #2973
This one is for VOCAB.
It looks like it was unused since the creation of the grammar in 2001. https://github.com/checkstyle/checkstyle/blob/0fd69594a4c3e82f92f93f0371791da66938f8c3/src/checkstyle/com/puppycrawl/tools/checkstyle/java.g#L1101-L1106
I saw the comment above it, but there is no case to prove why it is needed and regression showed no errors with it gone.
=> Issue #2973: removed unused VOCAB from java.g

config/intellij-idea-inspections.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinter.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java
Issue #2973
The first for the hard to reach code coverages.
This doesn't reach 100% line coverage because the remaining 59 lines are actually unreachable code by normal means. For now, I am submitting these and increasing the coverage rate.
My plan to reach the other areas is to have the `LA` method return delayed values instead of static positioning, but for now I will work on the recognizer.
So I don't have to keep creating files for every small test, I split `parseFile` apart with the addition of `parseFileText`. I also added the method `verifyAstRaw` and the class `AssertGeneratedJavaLexer `.
Suppressions are needed because the ANTLR checks are very specific.
=> Issue #2973: added java lexer cases for coverage

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/InputAnnotationLocation3.java
Issue #3106
Tokens DOT, LITERAL_NEW, TYPE_ARGUMENT were causing a NPE becuase they could have modifiers for annotations but if they don't, we hide the node in the tree making their find return `null`.
=> Issue #3106: fixed annotation location check with no modifiers

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputTwoStatementsPerLine.java
Issue #2950. This comes before PR #2940.
This fixes indentation for lines with some type of multiple statements on it, and rewrites `LineWrappingHandler` to be more of a utility and not require the first node to be the first on the line. This allows us to use this in places where we don't know where the node is on the line, like `throws`.
Changes to `LineWrappingHandler`:
* It is now more a utility class. It only takes `IndentationCheck` on instance, so it is more connected to `IndentationCheck` and requires us to only make one instance, instead of an instance for every AST.
* Every call to `checkIndentation` now takes the nodes to examine as parameters instead of being stuck to the instance. We never called this method more than once on one instance, so I found the connection to the …
=> Issue #2950: rewrote LineWrappingHandler for nodes not on first line

src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidLabelWithWhileLoopIndent.java
count correction was causing the warnings in the input file and the test file to be out of sync. It made it seem like an input file had an extra violation when it didn't as seen in the one input file corrected. Also we were only using it in one place.
I removed count correction completely.
=> minor: removed unnecessary count correction in indentation test

src/xdocs/config_regexp.xml
Issue #3085 
I accidentally double escaped the examples for the check.
=> Issue #3085: fixed escaping in RegexpOnFilename examples

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4
Issue #1064
Description of fix is at: https://groups.google.com/d/msg/checkstyle-devel/Uyu-vO50eAQ/CdKYGSX-CAAJ
Basically, we are injecting code into the ANTLR to skip calling `adaptivePredict` which is causing the slowdown.
I implemented this change in my project's CS and saw no negative effects as is and when removing or changing javadocs to report violations.
I did see a drop in runtime from 70 seconds to 20 seconds.
I will run regression.
Issue is still waiting approval.
=> Issue #1064: fixed slow javadoc antlr parsing

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableNameLambda.java
Issue #3144 
Exception is because we are in an interface and `findFirstUpperNamedBlock` wasn't stopping at the interface definition.
Code fix has it now stopping at the field definition. This is because the code was original stopping at methods, and fields are on the same hierarchy, so I thought it was better to stop here.
=> Issue #3144: fixed NPE in FinalLocalVariable for lambda in field

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTag.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/InputUnusedImportWithValueTag.java
https://github.com/checkstyle/checkstyle/issues/3157
Javadoc `{@value}` tag references static constant and makes its value appear in the generated javadoc. Constant can be referenced either by fully qualified name `{@value java.util.Calendar#MONTH}` or by relative name `{@value Calendar#MONTH}` when corresponding import is present
`import java.util.Calendar;`.
This PR fixes an issue with `UnusedImports` check which considered imports used in `{@value}` to be unused.
=> Issue #3157: Javadoc value tag can reference import

config/checkstyle_sevntu_checks.xml, config/sevntu_suppressions.xml, pom.xml, src/it/java/com/google/checkstyle/test/base/BaseCheckTestSupport.java, src/it/java/com/google/checkstyle/test/base/BaseIndentationCheckSupport.java, src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java, src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/CheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParseTreeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/ParseTreeBuilder.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
Issue #3175 
expanded sevntu testing to all folders.
LineLengthExtended needed same ignore to package/import that we added to LineLength.
I was unsure about CauseParameterInException, ForbidCCommentsInMethods, IllegalCatchExtended violations so I just suppressed them for now.
Underscores added to numbers were placed in positions were commas would be separating thousands, etc.
=> Issue 3175

config/findbugs-exclude.xml, config/pmd.xml, config/sevntu_suppressions.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/api/ExternalResourceHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java, src/xdocs/writingchecks.xml, src/xdocs/writingfilters.xml, src/xdocs/writingjavadocchecks.xml.vm
#407 
**Solution to #407 issue. Part 1.**
Questions that should be discussed:
1) Where should we load external resources by their URIs to calculate SHA-1 cache sum? In PropertyCacheFile?
2) Where and how we should treat exceptions if it is not possible to create URI for resource. See failded tests.
3) What default implementation should we use for method 'getExternalResources'?
Suggestions:
```java
public List<URI> getExternalResources() {
return Collections.EMPTY_LIST;
}
```
or
```java
public Optional<List<URI>>getExternalResources() {
return Optional.absence();
}
```
Both first and second implementation require null check in Checker, because we do not know whether user will follow the rule and return non null reference.
4) How can we be sure that user will invoke …
=> Issue #407: Fix cache usage in presence of modules which use external resources for configuration

src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
Issue #3168
forbid whitespaces on the end of the commit message.
made sure there is atleast one commit to validate.
I can't confirm that the original issue is because of one of these 2, but i can confirm that space on the end after a period is accepted and makes it look like message ends with period.
https://travis-ci.org/rnveach/checkstyle/builds/130457690
https://github.com/rnveach/checkstyle/commit/51299ac6d961bde0efaa0eda72a6841f5e99ac79
`will have spaces on end. ` does have a space on the end as seen in the 2nd link if you highlight the message or download the commit
=> Issue #3168: forbid no commits and whitespace on end of commit message

config/checkstyle_checks.xml, config/checkstyle_sevntu_checks.xml, config/sevntu_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputSingleSpaceComments.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputSingleSpaceErrors.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputSingleSpaceNoErrors.java, src/xdocs/checks.xml, src/xdocs/config_whitespace.xml
Issue #3173
Start of new check from sevntu.
Made some minor modifications from sevntu.
* Removed references of `nodes` and replaced them with `whitespace` characters.
* Changed property `validateCommentNodes` to `validateComments`.
* Changed check's method definitions from `(DetailAST ast, String line)` to `(String line, int columnNo)`.
Questions:
(1)
````
+    public int[] getDefaultTokens() {
+        return CommonUtils.EMPTY_INT_ARRAY;
+    }
....
+    public void beginTree(DetailAST rootAST) {
+        visitEachToken(rootAST);
+    }
````
Can we just change `getDefaultTokens` to all tokens? I dislike parsing the entire tree twice (once by `TreeWalker` and then again by this check).
Should we use reflection to get all tokens, or should I hardcode the list and make a test to verify?
(2) …
=> Issue #3173: moved SingleSpaceSeparatorCheck from sevntu to checkstyle

src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java
Issue #3066
Turns out issue was with the test I had written. It split the input file by '\n' and didn't accept the possibility of '\r' or '\r\n'. ANTLR and sub-classes picked this up correctly and that's why they wanted 2 lines for the comment.
Update just removes the try/catch along with the fix.
=> Issue #3066: fixed line feeds in AstRegressionTest

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputEnumIsSealed.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputImmutable.java, src/xdocs/config_design.xml
#2971
@romani 
>
1) please fix CIs
2) please update xdoc files documentation, with config+code examples for new option. As options are very similar to each other, we need to help user to see a difference by examples.
3) Please generate html report with your option on opensource projects to make sure there are no exceptions and reported violations as ok.
Please use this tool - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester , please read README file.
4) Please generate diff-report of execution without your option and with you options to make sure there are no regression.
Please use this tool - https://github.com/checkstyle/contribution/tree/master/patch-diff-report-tool
5) To resolve Travis failures please rebase code over latest master, it is already resolved.
1) …
=> Issue #2971: Add allowPublicFinalFields option for VisibilityModifier

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ArrayInitHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidAnonymousClassIndent.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidForIndent.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidIfIndent.java
Issue #3116
Problem extended from `BlockParentHandler.shouldStartWithRCurly` which was saying the right curly should start the line. Since this method goes against not forcing users to split their lines, it was removed.
`|| areOnSameLine(rcurly, lcurly)` was removed as `|| !isOnStartOfLine(rcurly)` takes precedence and can't be hit for code coverage.
I did not remove the `ioffset` code incase we need it again, if that is all right.
Regression will be shortly.
=> Issue #3116: removed requirement right curlies must be first on line

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ImportHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/PackageDefHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/InputPackageDeclaration2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidImportIndent.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputPackageDeclaration3.java
Issue #2618
`checkLinesIndent` is only used by these 2 classes, and they seem like an attempt to mimic `LineWrappingHandler`. I removed them for in favor of `LineWrappingHandler`.
Regression will be shortly.
Unanswered question: https://github.com/checkstyle/checkstyle/issues/2618#issuecomment-213997415 This code uses `lineWrappingIndentation`.
=> Issue #2618: refactored indentation import and package logic

src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/xdocs/config_regexp.xml
Issue #3187 
Added default value validation except for strings and string arrays.
`RegExpCheck` changed default value to align with what the xdoc says, otherwise the xdoc has to be changed to `0`.
=> Issue 3187: validate default types

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/xdocs/config_annotation.xml, src/xdocs/config_javadoc.xml
Issue #3212
This is the last one for the string arrays.
Affected modules: SuppressWarningsHolder , AtclauseOrderCheck, SingleLineJavadocCheck
This PR basically changed only:
`````
void setProperty(String s) {
field = s.split(",");
}
````
into:
````
void setProperty(String... s) {
field = s;
}
````
**Breaking Compatibility:**
As stated in in other PR at https://github.com/checkstyle/checkstyle/pull/3189#issuecomment-220032301, old code didn't properly split comma delimited inputs from the configuration. Spaces were left in and these caused properties like `1, 2` to be seen as `1` and `<space>2`. This caused checks like `IllegalInstantiation` to not identify classes properly and hid what should have been violations.
=> Issue 3212: aligned setters to be arrays like properties for xdoc validation (breaking compatibility)

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputVisibilityModifierGenerics.java, src/xdocs/config_design.xml
#3142
@romani 
Added support of generic types for the Check. If allowPublicImmutableFields is set to true, the check will also check whether generic type parameters are immutable. If at least one parameter is mutable the check will rise violation. The changes work for both canonical and ordinary class names of type parameters.
Regression reports were generated against the following projects:
1) openjdk8
2) pmd
3) lombok
4) spring-framework
5) java-design-patterns
6) MaterialDesignLibrary
7) Hbase
8) Orekit
9) apache-ant
10) apache-jsecurity
11) android-launcher
13) infinispan
14) protonpack
15) jOOL
16) RxJava
17) checkstyle-with-excludes
18) sevntu-checkstyle-with-excludes
19) findbugs-with-excldues
20) hibernate-orm-with-excludes
21) guava-mvnstyle
with the following configuration: …
=> Issue #3142: Add proper support for generics in VisibilityModifierCheck

src/xdocs/checks.xml
The "Checks" page lists the available checks in alphabetical order and even says that it does. Therefore I corrected the order of some checks, because they have not been in the right place.
=> Pull #3263: corrected alphabetical order of the checks

src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyDoWhile.java
#3090
1) The problem was fixed.
2) Added new UT.
3) Added new IT.
Regression reports were generated against the following projects:
1) pmd
2) lombok
3) spring-framework
4) java-design-patterns
5) MaterialDesignLibrary
6) Hbase
7) apache-ant
8) apache-jsecurity
9) android-launcher
10) infinispan
11) protonpack
12) jOOL
13) RxJava
14) checkstyle-with-excludes
15) sevntu-checkstyle-with-excludes
16) findbugs-with-excldues
17) hibernate-orm-with-excludes
18) guava-mvnstyle
Configuration:
```xml
<property name="severity" value="warning"/>
<module …
```
=> Issue #3090: Fix wrong enforcement of same brace policy for LITERAL_DO in RightCurlyCheck

src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
This fixes the issue seen running pitest on CS in Windows.
The 3 tests that were causing the problem for me were, in the specific order:
*    com.puppycrawl.tools.checkstyle.MainTest.testDebugOption
*    com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest.testAllCheckSections
*    com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest.testAllXmlExamples
Which caused the following exception in Windows, but not on Linux:
`FINE : MINION : FAIL Description [testClass=com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest, name=testAllXmlExamples(com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest)] -> java.lang.OutOfMemoryError: Java heap space`
Basically our junit testing the debug option is bleeding into other tests, leaving logging on the highest. `XDocsPages` test run alot of …
=> minor: fixed debug option bleeding into other tests

src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/InputFinalParametersReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputHiddenFieldReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputParameterAssignmentReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputRequireThisReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/InputAbbreviationAsWordReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/InputParameterNameReceiver.java
Issue #3239 
Identified as an issue in https://github.com/checkstyle/checkstyle/pull/3259#issuecomment-225621597
Reason receiver parameters are ignored in these checks:
* Receiver parameters can't be `final`.
* Receiver parameters can't be renamed.
* Variables can't be named `this` to conflict with receiver parameters.
* `this` can't be re-assigned from a receiver parameter.
=> Issue #3239: fixed checks that fail on new receiver parameter

config/sevntu_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
#3259
There is no need in catching of InvalidPathException since it extends RuntimeException and we just wrap it in IllegalStateException which extends RuntimeException too without additional information.
=> Avoid catching of InvalidPathException and AccessDeniedException in PropertyCacheFile#persist

src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
#3177 
Removed validation of rw access for output file in Main#validateCli and as a result two UTs:
```
MainTest.testExistingFilePlainOutputToFileWithoutReadAndRwPermissions
MainTest.testExistingTargetFilePlainOutputToFileWithoutRwPermissions
```
were also deleted.
After merge of https://github.com/checkstyle/checkstyle/pull/3259 and this PR the issue #3177 will be resolved.
=> Issue #3177: Remove validation of rw access for output file in Main#validateCli

pom.xml
dsm-maven plugin was deactivated until https://github.com/sevntu-checkstyle/dsm-maven-plugin/issues/31 be resolved.
=> config: deactivate dsm-maven-plugin as it does not support Java 1.8

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/InputAnnotationLocation4.java, src/xdocs/config_annotation.xml
#3117 
@romani 
Fixed for foreach, for loops, catch, method, lambdas parameters.
I'm not able to generate regression reports against Apache-Apex, as I have got the following exceptions (before and after changes):
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project sample: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at …
```
=> Issue #3117: Add ability to differentiate annotation placement in foreach, for loops, parameter definition

wercker.yml
#3159 
@romani
1) All Travis CI's jobs were copied to Wercker CI except for generation of release notes and testing of PR format. nemo.sonarqube.com phase was commented out since I do not have permissions.
2) Cache was set up for Maven to avoid reloading of dependencies during execution.
3) I have to add ```rm -rf contribution``` for NoExceptionTests to avoid the following prblem:
4) We have to decide which phases will migrate to Wercker CI from Travis CI.
5) We have to design worckflow for Checkstyle at Wercker CI. See http://devcenter.wercker.com/docs/workflows/index.html
6) We have to create pipelines in order to execute jobs in parallel and use different containers (aka boxes) to test on different OS. The profiles can be found at https://hub.docker.com/ . Wercker CI offers free …
=> Issue #3159: Reduce the number of tasks performed by Travis CI

src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputVisibilityModifierGenerics.java
#3293 
Since now we use Java 1.8, it worth cutting down on Checkstyle's dependencies on Guava library:
1) Guava's Optional replaced with Java's native.
2) Guava's Predicate and Iterables should be replaced with Java's Predicate and streams. We cannot do this until we resolve or find workaround for Cobertura report generation problem on Java 1.8. (https://github.com/checkstyle/checkstyle/pull/3269#issuecomment-226986404, https://github.com/mojohaus/cobertura-maven-plugin/issues/21)
3) ...
P.S.
Teamcity's violations are not correct as java.util.Optional is not an unused import.
=> Cut down on Checkstyle's dependencies on Guava

src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
The JavaDoc contained invalid XML syntax. This commit fixes it.
=> doc: Fix JavaDoc comments

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputRequireThisBraceAlone.java
Issue #3334
`getBlockEndToken` can return `null` and there was no check to make sure it wasn't null before trying to use it.
=> Issue #3334: fixed RequireThis when can't find end block token

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/InputEclipseStaticImportsOrder.java, src/xdocs/config_imports.xml
#3101 
**Reports before and after**
Config before:
```xml
<property name="severity" value="warning"/>
<module name="ImportOrder"/>
</module>
</module>
```
Config after (useContainerOrderingForStatic = false):
```xml
<property name="severity" value="warning"/>
<module name="ImportOrder">
<property …
```
=> Issue #3101: Add new 'useContainerOrderingForStatic' option for ImportOrderCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableAssignedInsideAndOutsideSwitch.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableFalsePositives.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputFinalLocalVariableMultipleAndNestedConditions.java
#3074
@romani 
1) Fixed #3074.
2) Fixed #3186 too. UT 'testMultipleAndNestedConditions' was added to cover test cases taken from the issue (#3186).
3) Reports:
http://mezk.github.io/i3074-FinalLocalVariable/index.html
Projects:
pmd, lombok-ast, openjdk8, spring-framework, elasticsearch, java-design-patterns, MaterialDesignLibrary, Hbase, Orekit, apache-ant, apache-jsecurity, android-launcher, infinispan, protonpack, jOOL, RxJava, checkstyle-with-excludes, sevntu-checkstyle-with-excludes, findbugs, hibernate-orm-with-excludes, guava-mvnstyle, apache-struts.
Configuration:
```xml
<property name="severity" value="warning"/>
<module name="FinalLocalVariable">     
</module>
</module>
</module>
```
A …
=> Issue #3074: Fix FinalLocalVariable false positive when variable is assigned inside and outside switch-block

src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
Methods can be static
Exceptions not actually thrown
Unnecessary casts
No actual logic changed.
=> Minor Code Style Fixes Found By Eclipse

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
#3385 
I reviewed all Checkstyle UTs and found 15 hardcoded messages.
One more proof that Maven does not switch locale correctly before execution of Checkstyle's UTs. Similar problems must be detected after fix for (https://github.com/checkstyle/checkstyle/issues/3377).
=> minor: fix hardcoded messages in UTs

config/pmd.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
#3406
One more step to cut down on Checkstyle's dependencies on third-party libraries. The first one was made in https://github.com/checkstyle/checkstyle/pull/3293
Guava's Joiner was replaced with Java 8 native approach ([String#join](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.Iterable-)).
I do not replace usage of Joiner in [PackageObjectFactory](https://github.com/MEZk/checkstyle/blob/6b82f01378346226e0c999370c0e614cc6af878b/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java#L143) as it allows to skip nulls. If we use Java 8 approach in order to skip nulls it will require to do the following: http://www.leveluplunch.com/java/examples/stringjoiner-example/#join-list-skipping-null and as far as I know …
=> Pull 3406: Replace Guava's Joiner with Java 8 native approach

config/checkstyle_checks.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
Issue #2874.
FYI:
**without option**
FinalLocalVariableCheck#visitToken - CC = 21
VariableDeclarationUsage#calculateDistanceInSingleScope - CC = 17
**with option**
FinalLocalVariableCheck#visitToken - CC = 15
VariableDeclarationUsage#calculateDistanceInSingleScope - CC = 11
FinalLocalVariableCheck#visitToke and VariableDeclarationUsage#calculateDistanceInSingleScope  are just too complex themselves. And even when switchBlockAsSingleDecisionPoint is set to true they remain logically complex.
=> Issue #2874: Use CyclomaticComplexity.switchBlockAsSingleDecisionPoint in checkstyle_checks.xml

config/suppressions.xml
#2874 
Fixed https://travis-ci.org/checkstyle/checkstyle/jobs/158560120#L317.
The problem appeared after https://github.com/checkstyle/checkstyle/commit/de022d2434e58dd633fd50a7f9bb50565a8767b5 had been merged.
Our CIs did not trigger the problem in my PR (https://github.com/checkstyle/checkstyle/pull/3401) because the build for PR was triggered before the https://github.com/checkstyle/checkstyle/commit/de022d2434e58dd633fd50a7f9bb50565a8767b5 had been merged.
Sorry for causing the problem.
=> Issue #2874: Fix suppression line for CyclomaticComplexityCheck

config/checkstyle_sevntu_checks.xml, config/sevntu_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailNode.java
#3412
1) Usage of java.util.Stack and java.util.Vector was disallowed for the whole project.
2) Usage of classes from 'com.puppycrawl.tools.checkstyle.checks.*' package was disallowed for 'com.puppycrawl.tools.checkstyle.api' and 'com.puppycrawl.tools.checkstyle.utils' packages.
New violations appeared due to the second restriction. What should we do with them?
```
main/java/com/puppycrawl/tools/checkstyle/api/DetailNode.java
This import should not match '.+\.checks\..+' pattern, it is forbidden in com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocNodeImpl.	22
main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
This import should not match '.+\.checks\..+' pattern, it is forbidden in com.puppycrawl.tools.checkstyle.checks.javadoc.InvalidJavadocTag.	34
This import should …
```
=> Pull #3412: Fix ForbidCertainImports config

src/xdocs/index.xml.vm
Added text and link to CS backport on main index.
I put in some explanation why we can't support older JDKS and emphasized that backport is community/unofficially controlled.
Feel free to make any corrections/additions you see fit.
=> doc: added links to cs backport jre6

src/xdocs/index.xml.vm
Fixed missing slash in URL to backport documentation.
=> doc: added missing slash to backport documentation url

config/checkstyle_sevntu_checks.xml, config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputExtendAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputEmptyTypesAndCycles.java
#3433 
Got rid of and prohibited usage of:
1) com.google.common.annotations.GwtCompatible
2) com.google.common.annotations.GwtInCompatible
3) com.google.common.collect.TreeTraverser
4) com.google.common.io.Files
Immutable collections from Guava cannot be replaced with Java's Collections.unmodifiable... since unmodifiable collections provide only read-only view of modifiable collections. They are not thread-safe!
The list of the remaining dependencies on Guava: [checkstyle-dependencies](https://github.com/checkstyle/checkstyle/files/484682/checkstyle-dependencies.txt)
=> Issue #3433: Cut down on Checkstyle's dependencies on Guava (part 3)

config/findbugs-exclude.xml, config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTags.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPModel.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/JTreeTable.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
#3433 
I tried to get rid of the following dependencies:
1. com.google.common.collect.ImmutableList
2. com.google.common.collect.ImmutableSortedSet
3. com.google.common.collect.ImmutableSet
4. com.google.common.collect.ImmutableMap
**ImmutableCollection**
API which uses ImmutableCollection:
1) com.puppycrawl.tools.checkstyle.DefaultContext
2) com.puppycrawl.tools.checkstyle.api.AutomaticBean
3) com.puppycrawl.tools.checkstyle.api.Context
**ImmutableList**
API which uses ImmutableList:
1) com.puppycrawl.tools.checkstyle.DefaultContext
**ImmutableMap**
API which uses ImmutableMap
1) com.puppycrawl.tools.checkstyle.DefaultConfiguration
2) com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter
3) com.puppycrawl.tools.checkstyle.api.Configuration …
=> Issue #3433:  Cut down on Checkstyle's dependencies on Guava (part 4, collections)

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputEqualsHashCode.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputEqualsParameter.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputSemantic.java, src/xdocs/config_coding.xml
Issue #3308
Updated documentation. Changed some code to use our utility method, which checked for static that our old code didn't. Checking parameter for `Object` or `java.lang.Object`.
=> Issue #3308: fixed EqualsHashCode equals method parameter test

src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/api/InputClearDetailAstLazyLoadCache.java
Issue #3486
@romani This is the showcase of https://github.com/checkstyle/checkstyle/issues/3466#issuecomment-250868051 . I will make a issue and fix the code in this same PR.
Test works by testing actual child count versus cached child count. Both should always be equal. AST tree with comment fails this test.
=> Issue #3486: DetailAST cache and child counting with comments

config/pmd.xml
#3499
JUnit4TestShouldUseTestAnnotation is suppressed as it is a PMD bug: pmd treats test method from Predicate interface as UT and rises violation.
Since we use lambda instead of Predicate in PackageObjectFactory, we do not need to suppress JUnit4TestShouldUseTestAnnotation.
=> config: exclude JUnit4TestShouldUseTestAnnotation from pmd.xml

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
Issue #3489.
Fixes to the bug include making the config hash a field, putting the config hash back into the `details` in the clear method, and changing all `details.clear()` to use the `clear` method.
Other changes in the file include:
* Making `CONFIG_HASH_KEY` public.
* Adding `get` method to verify hash's value when it is not known.
=> Issue #3489: restore config hash on property cache clear

config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgControl.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_2.dtd, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgControlRegExpInPkgTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgControlRegExpTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgControlTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_pkg-re-in-both.xml, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_pkg-re-in-child.xml, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_pkg-re-in-parent.xml, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/import-control_two-re.xml, src/xdocs/config_imports.xml
This pull request fixes Issue #2999. Notes:
* I have added the possibility to define packages not only to the `subpackage` element but also to the root element `importcontrol`.
* The travis will continue to fail until the new DTD [import_control_1_2.dtd](https://github.com/vboerchers/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_2.dtd) is available as http://www.puppycrawl.com/dtds/import_control_1_2.dtd
=> Issue #2999: allow regex in importcontrol and subpackage element

config/checkstyle_checks.xml, config/pmd.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilterSet.java, src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filefilters/package-info.java, src/main/resources/checkstyle_packages.xml, src/site/site.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TestBeforeExecutionFileFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filefilters/ExclusionBeforeExecutionFileFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/BeforeExecutionFileFilterSetTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/xdocs/config.xml, src/xdocs/config_filefilters.xml, src/xdocs/writingfilefilters.xml
Issue #2866
Added pre-filters to be able to exclude files from being checked.
ExclusionPreFilter accepts regular expression to allow customizing which files are skipped.
Missing any XDoc documentation as there is some question if `PreFilter` is the word we want to use to describe this new set.
Currently prefilters is missing from `Checker.getExternalResourceLocations` as the only pre-filter doesn't use this and requirements in issue didn't want this.
If we still want pre-filters to have external resources, then I can just add a dummy class to fill in the code coverage.
=> Issue #2866: added prefilters and exclusion prefilter

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputMain.java, src/xdocs/config_javadoc.xml, src/xdocs/writingjavadocchecks.xml.vm
Issue #2427.
Added acceptable and required javadoc tokens. Code was mostly copied from `TreeWalker` which this class is mimicking.
All javadoc checks required `getRequiredJavadocTokens` to be added.
Questions:
1)
The issue made note of an [area that had documentation on this already but was removed](https://github.com/checkstyle/checkstyle/blob/fff24e89001ce2ad9c30d1f573639cd640183669/src/xdocs/config_javadoc.xml#L978).
Was that documentation valid that the 2 tokens are optional?
Are there any other optional tokens for the javadoc checks? I didn't see anything jump out when glancing over.
Some things to note:
1)
We needed some place to validate that the javadoc tokens set for the check are correct and require us to be able to throw a `CheckstyleException`. I did this in `init` and so had …
=> Issue #2427: added customizable javadoc tokens

src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputNoJavadocNeededInLambda.java
#1254
Diff reoports were generated against the following projects:
1. openjdk8
2. pmd
3. lombok-ast
4. spring-framework
5. elasticsearch
6. java-design-patterns
7. MaterialDesignLibrary
8. Hbase
9. Orekit
10. apache-ant
11. apache-jsecurity
12. android-launcher
13. apache-struts
14. infinispan
15. protonpack
16. jOOL
17. RxJava
18. checkstyle-with-excludes
19. sevntu-checkstyle-with-excludes
20. findbugs
21. hibernate-orm-with-excludes
22. guava-mvnstyle
http://mezk.github.io/i1254-JavadocVariable/index.html
=> Issue #1254: Fix JavadocVariableCheck when assigning a lambda as a field

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/CustomImportOrderTest.java, src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder1.java, src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder2.java, src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder3.java, src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderNoImports.java, src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderValid.java, src/main/resources/google_checks.xml
#941
1) Updated import ordering in google_checks.xml according to changes Google Style Guide
2) Updated ITs
3) CustomImportOrder still has issues with checking the exact number of blank lines between groups. In addition, it allows to have one or more blank lines even if separateLineBetweenGroups is set to false. However, Google Style Guide ([section 3.3.3](https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing)) says that `If there are both static and non-static imports, a single blank line separates the two blocks. There are no other blank lines between  import statements.` As a result of the issues we cannot provide the correct configuration.
3.1) Example of wrong behavior:
``` xml
<module name="CustomImportOrder">
<property …
```
=> Issue #941: Update import ordering in google_checks.xml according to changes in Google Style Guide

src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/ParameterNameTest.java, src/it/resources/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputParameterNameSimple.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/InputScope.java, src/xdocs/config_naming.xml
Issue: #3473 
Add scope and excludeScope properties to ParameterNameCheck
Issue #3381 should make the warnings at the following lines disappear:
- [63:24](https://github.com/checkstyle/checkstyle/pull/3480/files#diff-a0d5f5022546877d69441fab461bfd64R63)
- [77:44](https://github.com/checkstyle/checkstyle/pull/3480/files#diff-a0d5f5022546877d69441fab461bfd64R77)
=> Issue #3473: ParameterNameCheck: new scope and excludeScope properties

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/suppress_all.xml
Issue #3488
Since we can call `fireErrors` in `AbstractFileSetCheck` during `finishProcessing` (`TranslationCheck`), we have to add all files to the cache, and then remove them if errors get fired that are not suppressed.
=> Issue #3488: save files into cache with no un-suppressed violations

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelector.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPModel.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/JTreeTable.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPModelTest.java
Issue #3432 
Added DetailNode support for CodeSelector and CodeSelectorPModel classes. Code selection in GUI enabled.
Some javadoc nodes aren't selects correctly while Issue #3507 (and maybe some others) isn't solved.
Test for CodeSelectionPModel added.
=> Issue #3432: Added DetailNode support for CodeSelector, gui code selection and test.

config/ant-phase-verify.xml, config/build.xml, config/checkstyle_checks.xml, config/checkstyle_sevntu_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java
Issue #3487
Cache turned on for Checkstyle and sevntu.
* Changes in `XDocPagesTest` is because instantiating the examples caused our own cachefile to be corrupted.
* Sevntu cachefile couldn't be enabled in the pom, that I could figure out. `<cacheFile>${project.build.directory}/cachefile-sevntu</cacheFile>` caused no cache file to be created.
* Removed the delete cachefiles as we don't really need them and will defeat the purpose of the cache. CI will always be clean, so it will only matter locally. Cache is deleted on clean, and will reset for files/configs that change. Deleting the file will just put us back without cache each time we run verify.
=> Issue #3487: turned on checkstyle cache for developers

appveyor.yml
Fixing appveyor failure:
````
M2_HOME = "C:\maven\apache-maven-3.2.5" 
Please set the M2_HOME variable in your environment to match the 
location of the Maven installation 
Command exited with code 1
````
Maven was somehow installed into `C:\maven\maven`. Since we cache the directory, it stuck with future runs and we were skipping new install because of directory check.
This fixes verifying the install directory and that only it is cached.
=> config: fixed issue with appveyor and corrupted maven cache

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/xdocs/config_imports.xml
Issue #3450
For now, I just copied some unit tests to test loading URLs and resources with the `file` property.
However, in [SuppressionFilterTest](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java#L159), `CommonUtils#getUriByFilename(String filename)` is mocked with Mockito.
Should I change the tests to use mocking? If so, they would also have to be changed for testing regular files.
By the way, I have kept tests for `url` property until it will be removed.
=> Issue #3450: Support loading import control configuration from URLs and classpath

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/xdocs/config_imports.xml
Issue #3584 
I wasn't sure about how to mark the property as deprecated in xdocs, so I put it in the description.
I think it would be nice if we could put it in the title of the property table as well but this would require a change in XDocsPagesTest.
For example:
```html
<tr>
<td>url (deprecated)</td>
<td>
URL of the file containing the import control configuration.
This property is deprecated. Please use the file property to load configurations
from URLs.
</td>
<td><a href="property_types.html#string">string</a></td>
<td><code>null</code></td>
</tr>
```
Another option would be to give it a CSS class and use CSS to generate the `(deprecated)` after the property name.
If you like these ideas I can open an issue for this.
=> Issue #3584: Deprecate 'url' property of ImportControlCheck

wercker.yml
#3608 
Switched from launch.sh to launch.groovy.
=> infra: Use launch.groovy for 'NoException' testing (Wercker)

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractLoader.java
Issue #3605: enable certain SAXParserFactory features.
=> Issue #3605: enable certain SAXParserFactory features.

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/xdocs/config.xml
Issue #3611
Exception will now only stop 1 file from executing instead of all of them.
`catch (Exception ex) {`
We could make this catch `Throwable` instead so nothing gets by, but I wasn't sure if this was ok as the field name has `Exception` in it.
=> Issue #3611: added haltOnException to Checker

pom.xml, shippable.yml
Issue #3316.
Due to the fact that pitest works for a long time, and CI will perceive it as an timeout error, we need to split pitest testing packages on maven profiles. At first I added the sizes package of checks to separate maven profile and added pitest testing of this package in shippable CI.
=> Issue #3316: use pitest testing of checks.sizes package in shippable CI

src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/xdocs/config_coding.xml, src/xdocs/config_naming.xml, src/xdocs/google_style.xml
All checks should have their styles listed if they are in those configs.
All checks that are in style configs should be listed in their style xdocs. Note: Sun is disabled since Sun has no proper xdoc.
=> Fixed style listings for checks

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputEmptyLineSeparator.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/package-info/test1/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/package-info/test2/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/package-info/test3/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/package-info/test4/package-info.java
=> Issue #3426: remove warning on PACKAGE_DEF predicted by javadoc not separated by line

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputNoWhitespaceAfterSynchronized.java, src/xdocs/config_whitespace.xml
Issue #2803 
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/166/
````
<module name="NoWhitespaceAfterCheck">
<property name="tokens" value="LITERAL_SYNCHRONIZED"/>
</module>
````
I did not add this to google_config. As regression shows, every single `synchronized` written in guava and android have a space after it.
Even though google style doesn't specify this token specifically I believe the following text covers that it should have this space:
http://checkstyle.sourceforge.net/reports/google-java-style-20160712.html#s4.6.2-horizontal-whitespace
> a single ASCII space also appears in the following places
> Separating any reserved word ... from an open parenthesis (() that follows it on that line
If you still think I should ask them about this, please direct me to the …
=> Issue #2803: added synchronized to NoWhitespaceAfterCheck

src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/xdocs/config.xml
Issue #3622
`"TreeWalker.upChild"` is because bean utils thinks ***set**upChild* is a setter method.
`-        else if (AbstractFileSetCheck.class.isAssignableFrom(clss)) {` is because TreeWalker has a parent module as well as is a file set check.
=> Issue #3622: expanded and fixed documentation for checker and treewalker

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AbstractImportRule.java
Some left-over reference to `Guard` from before refactoring and also a typo.
=> minor: correct Javadoc for AbstractImportRule

circle.yml
#3676
@romani 
I was not able to add GROOVY_HOME into PATH variable, so I had to use an absolute path to Groovy bin directory and invoke Groovy from there.
I used the following guide to install and cache Groovy
https://circleci.com/docs/installing-custom-software/
I created the question at Circle CI forum but did not get useful answer
https://discuss.circleci.com/t/how-to-install-groovy/8511
Should be merged after https://github.com/checkstyle/contribution/pull/146
=> infra: Use launch.groovy for testing (Circle CI)

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XDocsPagesTest.java, src/xdocs/checks.xml
Issue #3664
Test was re-written from scratch. Original test scanned files and folders, new test uses the common utility that scans the classpath and checks class inheritance.
`getSimpleNames` was moved to utility class so multiple classes could make use of it.
New section is called `Non-Standard Checks`. 2 known non-standard checks were added to this section. One was already listed in standard section so it was just moved.
=> Issue #3664: verified all types of checks are on checks.xml

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
The [`AvoidEscapedUnicodeCharactersCheck`](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.html) incorrectly renders the example unicode escapes as their unicode characters, which is confusing.
I found [this question](http://stackoverflow.com/q/32020170) trying to fix this problem, but (as discussed) `\\` doesn't work and `\u005c` (escaped backslash) is confusing when reading the source.
However the HTML escape `&#92;` works, rendering as a backslash in the HTML while remaining (fairly) readable in the source. This change swaps the examples to use the HTML escape, and also corrects the first sentence of the docs which are truncated in the [package view](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkst …
=> doc: fix the escaping of AvoidEscapedUnicodeCharactersCheck's javadocs

src/xdocs/config_imports.xml
Small typo I spotted while adding documentation for the new attribute.
=> doc: Fix typo in config_imports.xml

config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/ConfigurationUtil.java
Issue #3720 
@romani 
Issue is not approved so code is more a demonstration. Since there was also some reservation about a UT of this kind, I didn't add all overrides.
Please approve issue if you want me to finish this.
The test uses our configuration loader to read and process the configuration file.
`TOKENS_IN_CONFIG_TO_IGNORE` will specify all tokens that we do not want defined directly in our config. `NoWhitespaceBefore` was added for demonstration but it's value is valid as we don't have those used in our config.
If we want, we can add this to all configurations (google and sun).
Eventually I think we should add more support to the configurations to allow writing these back to files for fully dynamic testing in PRs. Sevntu's CI has a perfect example of where that could be used.
=> Issue #3720: verify all tokens are used in checkstyle config

src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TestRootModuleChecker.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue #3530
`setClassLoader` is used by eclipse-cs.
`setClassLoader` - has weird javadoc that show some references to multifile validation that removed as problematic (we will come back to multifile mode later).  
`setClassLoader` had to be moved to root module as `ant` wanted to set it.
Originally `ant` used `contextualize` to set the class loaders but the root module didn't support that method either. So the choice was to add the `contextualize` method via also adding the interface `Contextualizable` or just add the setter. I figured setter would be better as the interface would require all root modules to implement a complex method like `contextualize`. `Main` also used the setter methods instead of `contextualize`.
Added a `reset` method to `TestRootModuleChecker` to ensure it is …
=> Issue #3530: allowed ant to override and swap checker

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CatchHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputInvalidTryIndent.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputValidTryIndent.java
Issue #3803 
The `true`/`false` change tells the method if indentation should be increased because of line wrapping.
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/190/
Only one difference in openjdk9, which I assume the reason it is there is because the `try` in not indented correct from the lambda.
=> Issue #3803: fixed catch indentation wrapping

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CheckUtil.java
The method returns token names, not text.
=> Pull #3820: Rename method in CheckUtil

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Issue #3749
Just updated reason. All examples already existed at https://github.com/checkstyle/checkstyle/blob/e307efd92b98c19c879db9b0ea3d20bc4460a532/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java#L314-L357
=> Issue #3749: updated reason for google's OperatorWrapCheck config

src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java
`AbstractTypeAwareCheck` looks like it could contain a bug when dealing with interfaces, especially nested interfaces.
[When we process `visitToken`, we call `processClass` for classes, interfaces, and enumerations](https://github.com/rnveach/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java#L145-L148).
[`processClass` manipulates `currentClassName` and calls `processTypeParams` to handle the type parameters.](https://github.com/rnveach/checkstyle/blob/b4a337a599e853cdc44b19a76da28fcfab2956cd/src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java#L337)
[When we process `leaveToken` for these tokens we do the same as `processClass` but reversing …
=> Fix AbstractTypeAwareCheck when dealing with nested interfaces

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputDesignForExtensionOverridableMethods.java
#3843 
1) Replaced Stream.of(...) with Arrays.stream(...) to avoid problem with cobertura.
2) Removed null-check (``` if (methodImplOpenBrace != null)```) from ```hasEmptyImplementation``` as ```methodImplOpenBrace``` can be null only if the method is native or abstract, or its signature is declared in interface. All the cases mentioned are checked by ```canBeOverriden``` which is more verbose that is why I decided to rely on it. Since I change the check logic a bit I decided to regenerate diff reports with default configuration.
3) Added test input to increase branch coverage rate up to 100%.
Diff reports:
http://mezk.github.io/i3843-coverage/diff
Cobertura report:
http://mezk.github.io/i3843-coverage/cobertura
@rnveach 
Feel free to review and share your thoughts.
This PR blocks …
=> Issue #3843: Fix coverage problem for DesignForExtension

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/InputWhitespaceAroundCatch.java, src/xdocs/config_whitespace.xml
It should be an option to disable checking whitespace around empty catch block because:
```java
try {
sth....
} catch (RuntimeException ex) {}
```
is a common pattern to explicitly suppress exceptions.
=> Pull #3841: add allowEmptyCatches parameter to WhitespaceAroundCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputDesignForExtensionIgnoredAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/InputDesignForExtensionMultipleAnnotations.java
#3830 
> @rnveach 
As shown in the debug output above, do you know why DesignForExtensionCheck.hasAnnotation has to examine the contents of the method? Won't this lead to false positives for this method?
@romani 
it should not review content of method. modificators and annotations is enough for decision.
Fixed. 
```findFirstTokenByPredicate``` was reimplemented. The idea was taken from DetailAST#findFirstToken .
There is no need in looping through all ignored annotations and invoking of  ```hasAnnotation``` inside ```hasIgnoredAnnotation```  each time, that is why I decided to check whether ignored annotations set contains any of method annotations.
Diff reports:
http://mezk.github.io/i3830-DesignForExtension/diff
As you can see from the reports there are both false positives and false …
=> Issue #3830: Fix bug in DesignForExtension when order of annotations changes violation

config/checkstyle_sevntu_checks.xml, config/import-control.xml, config/sevntu_suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
#3843 
I did not use ForbitCertainImports as it cannot exclude test classes where usage of java.util.stream should be allowed.
=> Issue #3843: Disallow import of interfaces from java.util.stream due to coverage problem

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
#3848 
Method can be defined only in class, interface, enum, annotation interface, annonymous class. For CLASS_DEF, INTERFACE_DEF, ENUM_DEF, ANNOTATION_DEF tokens we create new ClassFrame with type CLASS_FRAME. For annonymous class we create AnonymousClassFrame which extends ClassFrame and also has the type CLASS_FRAME. Thus, when we collect declarations in ```collectDeclarations```, METHOD_DEF token in always related to the frame with type CLASS_FRAME. It means that there is no need in checking the frame type.
Reports:
1) Diff http://mezk.github.io/i3848-RiquireThisCheck/diff
2) Coverage  http://mezk.github.io/i3848-RiquireThisCheck/cobertura/
=> Issue #3848: Remove unnecessary if-block to increase code coverage

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputRequireThisMetodReferences.java
#3848 
1) Added UT for method references.
2) Removed unnecessary null check as [method call](https://github.com/MEZk/checkstyle/blob/242cfe3ac366cb270fdbdd1425c96dff812f4bd0/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L259) always refers to specific frame. And it means that we do not need to check whether [the frame](https://github.com/checkstyle/checkstyle/compare/master...MEZk:i3848-RequireThichCheck-coverage?expand=1#diff-110729384f4c9d098bd29eafab295062R803) is null.
3) Coverage is 100%.
Diff report:
http://mezk.github.io/i3848-RiquireThisCheck/diff
=> Issue #3848: Increase code coverage of RequireThisCheck

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue #3731 
@romani 
I ran a GUI to show the AST of my example code successfully by following the [docs](http://checkstyle.sourceforge.net/writingchecks.html#The_Checkstyle_SDK_Gui) and write a example depends on what the tree shown by GUI window.
One thing I am confused is that the I didn't find the `DOUBLE_COLON ` type in the tree which shown by GUI, but there is a `@see #DOUBLE_COLON` in original code. Did I miss anything? Or there should be no `DOUBLE_COLON` actually?
=> Issue #3731: expand documentation on METHOD_REF token

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_coding.xml, src/xdocs/config_design.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_modifier.xml, src/xdocs/config_naming.xml, src/xdocs/config_regexp.xml, src/xdocs/config_sizes.xml, src/xdocs/config_whitespace.xml
All doc pages have the sentence "All messages can be customized if the default doesn't suite you," but it should be [suit](https://en.wiktionary.org/wiki/suit#Verb). Since the sentence is so often seen I present this PR to fix this minor spelling error.
=> Spelling: change 'suite' to 'suit'

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespaceAround.java
Issue #3900 : Modified TypecastParenPadCheckTest.java to accommodate for the change in the location of test-resources the corresponding tests depend upon. The test-resources for those tests now reside at src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPad. Also the corresponding test-resources had to be modified accordingly to overcome having duplicate classes
=> Issue #3900: Split and Organize Checkstyle inputs by Test for TypecastParenPad

src/xdocs/config_coding.xml
Issue: https://github.com/checkstyle/checkstyle/issues/3943
=> Issue #3943: Add examples for xdoc for ArrayTrailingComma

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
Fixes: #3648
**What I have done:**
=> Issue #3648: make code coverage for MainFrameModel 100%

src/xdocs/index.xml.vm
The problem was detected at https://app.codeship.com/projects/124310/builds/23433281 .
According to [redirectcheck.com](http://redirectcheck.com) the link to the BlueJ web site has been moved from http://www.bluej.org to https://www.bluej.org/ .
redirectcheck.com report:
```
www.bluej.org
HTTP/1.1 301 Moved Permanently
Date: Tue, 14 Mar 2017 20:31:54 GMT
Server: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f
Location: https://www.bluej.org/
Content-Length: 230
Content-Type: text/html; charset=iso-8859-1
https://www.bluej.org/
HTTP/1.1 200 OK
Date: Tue, 14 Mar 2017 20:31:55 GMT
Server: Apache/2.4.7 (Ubuntu) OpenSSL/1.0.1f
Last-Modified: Tue, 14 Mar 2017 16:28:56 GMT
ETag: "2085-54ab353066213"
Accept-Ranges: bytes
Content-Length: 8325
Vary: Accept-Encoding
Content-Type: text/html
```
```curl …
```
=> minor: fix link to bluej web site to avoid a violation from linkcheck

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPad.java
=> Issue #3976: Split and Organize Checkstyle inputs by Test for EmptyForIteratorPad

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlySingelineIfBlocks.java
#4044 
Fixed false negative in RightCurly while checking single line if blocks with brace policy ALONE. Some logic was extracted into shouldHaveLineBreakBefore to avoid CC check violations.
Diff reports are on the way ...
=> Issue #4044: Fix false negative in RightCurly while checking single line if blocks with brace policy ALONE

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
Issue #3962
This PR does fix the leaking file resource but I was unable to write a test to satisfy the coverage requirements. 
I am submitting this to show what I tried to do and request help on how to fix the drop in coverage.
Thanks!
Giorgos
=> Issue #3962: Use try-with-resources to fix leaking unclosed InputStream

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ObjectBlockHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputAnonymousClassInMethodCurlyOnNewLine.java
Issue #3612 (related PR #3613)
Diffs: https://soon-checkstyle-diffs.github.io/issue-3612/
~~Unfortunately, I'm unable to create regression diffs on all projects, because checkstyle fails with `OutOfMemory` error while generating report (it fails on master as well).~~
~~I've made reports for guava (https://soon-checkstyle-diffs.github.io/issue-3612/guava/) and jdk (https://soon-checkstyle-diffs.github.io/issue-3612/jdk/) using their checkstyle configs. Is it possible to set different checkstyle configs for different projects at once? Probably, in the properties file?~~
I'm also a little bit confused with the [line number 32 in the test case](https://github.com/checkstyle/checkstyle/pull/3973/files#diff-41124079fe0fabb5d72bbb58a1f17c8cR32). I'm not sure if it should raise a warning.
=> Issue #3612: Fixed left curly indentation

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/InputAbbreviationAsWordReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbrevationaswordinname/InputAbbreviationAsWordInNameAbstractMultisetSetCount.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbrevationaswordinname/InputAbbreviationAsWordInNameOverridableMethod.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbrevationaswordinname/InputAbbreviationAsWordInNameReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbrevationaswordinname/InputAbbreviationAsWordInNameType.java
=> Issue #4095: Split and Organize Checkstyle inputs by Test for AbbreviationAsWordInName

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputIllegalTypeMemberModifiers.java
When scanning Checkstyle's code for a failed check, I found the following places where we had a loop looking for something and assigning a variable if it was found or not. I noticed most of the loops were specifically not ending when a determination was found.
I changed spots involving loops and assigning variables true/false to end their execution sooner as the variable is modified.
Changes to `InputIllegalTypeMemberModifiers` were to keep code coverage at 100% for the check as we lost some on the `for` loop for the fixes.
appveyor required change to `JavadocMethodCheck` that it be changed to a for-each.
=> Pull #4102: changed loops to end execution early

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputClassCouplingExcludedPackagesAllIgnored.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputClassCouplingExcludedPackagesCommonPackage.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputClassCouplingExcludedPackagesDirectPackages.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputClassFanOutComplexityExcludedPackagesAllIgnored.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputClassFanOutComplexityExcludedPackagesCommonPackage.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/InputClassFanOutComplexityExcludedPackagesDirectPackages.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/inputs/a/aa/AAClass.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/inputs/a/ab/ABClass.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/inputs/b/BClass.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/inputs/c/CClass.java, src/xdocs/config_metrics.xml
Issue #3309 
This PR adds `excludedPackages` parameter to the `ClassDataAbstractionCouplingCheck` and `ClassFanOutComplexityCheck`.
The diff is pretty big, because of added support for retrieving package name of imported class. Previously the check excludes classes by the name only. Now it tracks package name (for direct class imports) and therefore also excludes all `java.lang` classes. Unfortunately, it does not support wildcard imports, like `import java.lang.*`, because I don't know how to track them.
I've looked though all diff reports and for each project the metric value either decreases (because of direct imports from `java.lang`) or remains the same.
Diff: https://soon-checkstyle-diffs.github.io/issue-3309/index.html
Now I'm going to run some performance tests. For now the module …
=> Issue #3309: Added excludedPackages to class coupling checks

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableName.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableNameInnerClass.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableNameOneCharInitVarName.java
This pull request covers to issue #4150 
What was modified:
1) Modified paths to test classes
2) Moved all necessary inputs into /localvariablename package
Results:
All unit tests passed.
the result of mvn clean verify -> Tests run: 103, Failures: 0, Errors: 0, Skipped: 0
=> Issue #4150: Split and Organize Checkstyle inputs by Test for LocalVariableName

src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
=> Issue #2186: Exception message extended to provide more information on incorrect parent

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/InputFileTabCharacterSimple.java
This pull request covers to issue #3959 
What was modified:
Modified paths to test classes
Moved all necessary inputs into /whitespace/filltabcharacter package
Results:
All unit tests passed.
the result of mvn clean verify also OK
=> Issue #3959: Split and Organize Checkstyle inputs by Test for FileTabCharacter

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputAllowLocalVars.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/InputValidateOnlyOverlappingFalse.java, src/xdocs/config_coding.xml
Issue #3423: Allow non-overlapping overshadowing local vars without any violations from RequireThisCheck. Added UT. Fixed related UT.
=> Issue #3423: RequireThis treats local variable as property

.gitignore
'.nondex/*' is covered by '.nondex'
=> minor: remove redundant line in .gitignore

pom.xml
#4176 
FYI: .gitignore: https://github.com/checkstyle/checkstyle/blob/master/.gitignore
```
.settings
.externalToolBuilders
.classpath
.project
.checkstyle
.pmd
.pmdruleset.xml
.fbExcludeFilterFile
nbactions.xml
nb-configuration.xml
target
bin
checkstyle.iml
.idea
*~
hs_err_pid*
replay_pid*
.DS_Store
.nondex
```
=> Issue #4176: Add suppression of .DS_Store for NewlineAtEndOfFile

src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodtypeparametername/InputMethodTypeParameterName.java
This PR solves issue #4168
The "InputTypeParameterName.java" test file was copied to the folder "methodtypeparametername" since this two files still use it:
- ClassTypeParameterNameCheckTest
- InterfaceTypeParameterNameCheckTest
=> Issue #4168: Split and Organize Checkstyle inputs by Test for MethodTypeParameterName

.gitignore, pom.xml
**Intellij IDEA** generates `checkstyle.ipr` and `checkstyle.iws` files which are not excluded from checkstyle list, that causes verification to be failed.
Files `checkstyle.ipr` and `checkstyle.iws` are not specified in **gitignore** file.
=> Adding IDEA project files to gitignore and excluding them from checkstyle list

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/InputAvoidNestedBlocksDefault.java
Issue #4220 
This PR moves all inputs of AvoidNestedBlocksCheckTest of the blocks package to a new subdirectory 'avoidnestedblocks'.
=> Issue #4220: Modified AvoidNestedBlocksCheckTest.java and moved its input files to the avoidnestedblocks subdirectory

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableBreak.java
#4082 
Diff report:
http://www.luolc.com/checkstyle-diff-report/issue4082/
=> Issue #4082: Take "break" into consideration in FinalLocalVariable

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputLeftCurlyAllInOneLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyCoverageIncrease.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefault.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefault3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyFirstLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnums.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyLineBreakAfter.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyMethod.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyMissingBraces.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyNewLineOptionWithLambda.java
Issue #4220
This PR moves all inputs of LeftCurlyCheckTest of the blocks package to a new subdirectory 'leftcurly'.
Since a few tests were being shared by different tests, two new files were created.
Also `InputLeftCurlyAllInOneLine.java` shows up as deleted and a new file `InputLeftCurlyFirstLine.java` is created. This happens because the change in the name of the class of the file is relatively large to the contents present in the file. This has been done previously as well in PR #3964 with the file `InputGh47.java` when it was changed to `InputGenericWhitespaceList.java`
=> Issue #4220: Modified LeftCurlyCheckTest.java and moved its input files to leftcurly subdirectory

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForWhitespace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLambda.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLambdaOnly.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLambdaOnlyWithSpace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLambdaWithSpace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLeftRightAndNoSpace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadWhitespace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadWithDisabledLambda.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadWithSpace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadWithSpaceAndDisabledLambda.java
Related to issue #4062 
What was done:
1) Moved all necessary classes to new package /parenpad
2) Renamed InputParenPad.java to InputParenPadLeftRightAndNoSpace.java
=> Issue #4062: Split and Organize Checkstyle inputs by Test for ParentPad

src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberEmptyInner.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberSimple.java
Pull request related to issue #4043 
What was done:
1) Moved all necessary classes to new package /outertypenumber
2) Renamed InputSimple to InputOuterTypeNumberSimple and InputOuterTypeNumber to InputOuterTypeNumberEmptyInner
=> Issue #4043: Split and Organize Checkstyle inputs by Test for OuterTypeNumber

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefault.java
Issue #4220
This PR moves all inputs of EmptyCatchBlockCheckTest of the blocks package to a new subdirectory 'emptycatchblock'.
=> Issue #4220: Modified EmptyCatchBlockCheckTest.java and moved its input files to the emptycatchblock subdirectory

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputEmptyDefault.java, src/xdocs/config_blocks.xml
Issue #4159 : LITERAL_DEFAULT is now processed by EmptyBlockCheck. Corresponding UTs added
=> Issue #4159: EmptyBlock should process LITERAL_DEFAULT

src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockAllowEmptyLoops.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault.java
Issue #4220
This PR moves all inputs of EmptyBlockCheckTest of the blocks package to a new subdirectory 'emptyblock'.
=> Issue #4220: Modified EmptyBlockCheckTest.java and moved its input files to the emptyblock subdirectory

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
#3496 
This one is for com.puppycrawl.tools.checkstyle.checks.javadoc.
Javadoc checks are slow, so I've made reports only on a few projects (no regression):
[JavadocParagraph](https://vladlis.github.io/3496/part3/1/index.html)
[JavadocTagContinuationIndentation](https://vladlis.github.io/3496/part3/2/index.html)
[JavadocVariable](https://vladlis.github.io/3496/part3/3/index.html)
Did not test JavadocMethodCheck as it is deprecated.
=> Issue #3496: Enforce ReturnCount max=1 (part 3)

config/checkstyle_checks.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/SeparatorWrapTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapMethodRef.java, src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestMethodRef.java, src/xdocs/config_whitespace.xml
#3951 
Firstly, we need to confirm the check logic. As the issue mentioned: `want '::' operator at end of previous line`, but it is not correct according to google style: http://checkstyle.sourceforge.net/reports/google-java-style-20170228.html#s4.5.1-line-wrapping-where-to-break
> When a line is broken at a non-assignment operator the break comes before the symbol.
> - This also applies to the following "operator-like" symbols:
>   - the two colons of a method reference (::)
Notice that the break should come before `::`. 
Configurations for Google style is updated as well.
~~Diff report is on the way.~~
Diff report:
http://www.luolc.com/checkstyle-diff-report/issue3951/
=> Issue #3951: SeparatorWrap: add support for method reference operator

src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractDeclarationCollector.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/MultilineDetector.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/AbstractParenPadCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
I created a check to see if variables could be moved inside if statements (ignoring loops).
Changes are the result of violations the check produced.
It did produce 3 other violations, 2 of which can't be moved and are a current limitation of the check. The variables are a save and the next statements change the values for which the variable is created for. So moving is not possible.
The last violation wasn't moved because other similar variables were around it and I didn't want to break the style.
````
[ERROR] checkstyle\src\main\java\com\puppycrawl\tools\checkstyle\checks\coding\FinalLocalVariableCheck.java:259:17: Variable 'prevScopeUnitializedVariableData' can be moved inside the block to restrict runtime creation. [VariablePlacement]
[ERROR] …
```
=> Pull #4328: moved variables inside if blocks to reduce execution time

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputCommentsIndentationSurroundingCode.java
Fixes for new check at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/565 .
Will rename commit to reference this PR.
=> Pull #4343: moved more variables inside if blocks to reduce execution

pom.xml
Issue #4341 
Used maven-resources-plugin to copy dtds schemes from resources folder to target/site/dtds.
Plugin goal doc:
https://maven.apache.org/plugins/maven-resources-plugin/copy-resources-mojo.html
Maven phases doc:
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
The plugin will automatically create dtds dir. 
@romani 
I think that pre-site phase is a good step to perform the copying.
=> Issue #4341: Copy dtds schemas from resources dir to target/site/dtds during pre-site phase

config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtility.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java
#4342 
The issue with InefficientEmptyStringCheck was caused by String.trim().isEmpty() which creates new String object. I added a method that checks whether String is empty or not without creating temporary String.
https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/strings.html#InefficientEmptyStringCheck
=> Issue #4342: Modified version of maven-pmd and fixed InefficientEmptyStringCheck

src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java
Issue #4101
Edit:
The new assertions in `CheckerTest` were because parts of the test wasn't failing with the changes made when they should have been.
=> Issue #4101: changed external resources in cache to have special prefix

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
Issue #4350
Expanded violation message to show full stack trace.
`XMLLogger` was changed to accommodate retaining newlines in stacktrace when put to XML file. Depending on parser, if new lines aren't converted then can be changed to single spaces which will distort the stacktrace.
I noticed some issues when deciding how to code this fix.
1)
[`BaseCheckTestSupport` counts lines based on the number of errors.](https://github.com/checkstyle/checkstyle/blob/2f3f4b76f04f0b5071abcaed54648a49a0db3160/src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java#L244) So test can only verify the first line of the exception, and not the full trace.
2)
[`AuditListener.addException` isn't called anywhere except in test code.](https://github.com/checkstyle/checkstyle/blob/b4a337a599e853cdc44 …
=> Issue #4350: expanded exception violation when haltOnException is off

pom.xml, shippable.yml
Issue: #4402 add pitest-checks-annotation profile
When I simply add com.puppycrawl.tools.checkstyle.checks.annotation.* build fails:
Failed to execute goal org.pitest:pitest-maven:1.2.0:mutationCoverage (default-cli) on project checkstyle: Execution default-cli of goal org.pitest:pitest-maven:1.2.0:mutationCoverage failed: 65535
So I've added classes manually
execution time: 04:10 min
threshold: 99
=> Issue #4402: Add pitest-checks-annotation profile

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
Issue #4400
increased mutation threshold for pitest-checkstyle-common by 2%
threshold: 84%
execution time: 04:28 min
threshold will increase slowly as profile is quite big
[pitest report before changes for class](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle/Checker.java.html)
[pitest report before changes for package](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle/index.html)
`testFinishLocalSetupFullyInitialized` kills the following mutations: [173](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle/Checker.java.html#org.pitest.mutationtest.report.html.SourceFile@58688a38_173), [415](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle/Checker.java.html#org.pitest.mutationtest.report.html.SourceFile@58688a38_415), …
=> Issue #4400: Increase coverage of pitest-checks-common profile to 85%

src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #4393 : ASTs to be generated and walked only when there are corresponding type of checks. No parsing if no checks are specified
=> Issue #4393: Walk and parse ASTs only when needed

src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderTypeAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/InputModifier2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderAnnotationDeclaration.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderDefaultMethods.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderIt.java
Issue #4431 
This PR moves all inputs of ModifierOrderCheckTest of the modifier package to a new subdirectory 'modifierorder'.
=> Issue #4431: Modified ModifierOrderCheckTest.java and moved its input files to the modifierorder subdirectory

config/catalog.xml, src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_1_xpath_experimental.dtd
https://github.com/checkstyle/checkstyle/issues/4364
=> Issue #4364: Design a new format of suppression dtd schema to support XPath queries

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportDefault.java
Issue #4437 
This PR moves all inputs of AvoidStarImportCheckTest of the imports package to a new subdirectory 'avoidstarimport'.
=> Issue #4437: Modified AvoidStarImportCheckTest.java and moved its input files to the avoidstarimport subdirectory

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilsTest.java
Issue #4395 
increased mutation threshold for pitest-checkstyle-common by 9%
threshold: 49%
execution time: 01:36 min
[pitest report before changes for class](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle.utils/ScopeUtils.java.html)
[pitest report before changes for package](https://nimfadora.github.io/issue4395.html)
=> Issue #4395: increase coverage of pitest-checkstyle-utils profile to 49%

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
Issue #4437
This PR moves all inputs of AvoidStaticImportCheckTest of the imports package to a new subdirectory 'avoidstaticimport'.
=> Issue #4437: Modified AvoidStaticImportCheckTest.java and moved its input files to the avoidstaticimport subdirectory

src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #4445: Verifying calls to private static method using powermock was causing CI failures due to apparent conflict with cobertura
=> Issue #4445: Unstable TreeWalkerTest due to an apparent powermock - cobertura conflict

src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/config-custom-simple-root-module.xml
Issue #4417
`testCustomSimpleRootModule` doesn't test a successful module load, just a failure message.
`TestRootModuleChecker` doesn't implement `AutomaticBean` to be able to be instantiated. If we did add this implementation, then `TestRootModuleChecker` gets picked up and wanted to be added to our configurations and such, because all tests see it as a real module. To be able to deduce if a module is in `main` or `test` we would need to settle on a naming convention and override the production `module finder` in the test folder to skip the test named modules.
=> Issue #4417: fixed failure to load custom root module

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/cache.tmp, src/test/resources/com/puppycrawl/tools/checkstyle/externalResourse.tmp
Issue #4400 
increased mutation threshold for pitest-checkstyle-common by 5%
threshold: 89%
execution time: 11:46 min
[pitest report before changes for PropertyCacheFile](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle/PropertyCacheFile.java.html)
[pitest report before changes for CheckstyleAntTast](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle.ant/CheckstyleAntTask.java.html)
[pitest report before changes for package](https://nimfadora.github.io/issue4400.html)
=> Issue #4400: increase coverage of pitest-checkstyle-common profile to 89%

config/pmd.xml, pom.xml
Issue: #4342 
pmd-maven-plugin version was bumped to 3.8
dependencies on pmd 5.7.0 were added to pmd-maven-plugin
all violations were suppressed for now
=> Issue #4342: bumped version of pmd-mvn-plugin to 3.8 and pmd to 5.7.0

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #4398
removed Main class (forgotten to be removed while splitting to profiles) from tree-walker profile
threshold without Main class : 77%
increased mutation threshold for pitest-checkstyle-tree-walker by 12%
current threshold: 89%
execution time: 9:43 min
[pitest report before changes for package](https://nimfadora.github.io/issue4398.html)
=> Issue #4398: increase coverage of pitest-checkstyle-tree-walker profile to 89%

config/intellij-idea-inspections.xml, config/suppressions.xml, pom.xml, shippable.yml, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/LineColumnTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/BeforeExecutionFileFilterSetTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/FilterSetTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/api/abstractcheck/InputAbstractCheckTestFileContence.java
Issue #4394
Profiles pitest-checkstyle-api and pitest-checkstyle-filters were united in order to increase coverage of api profile, as they have many common functionality. More then with any other profile. 
Coverage of api profile before union: 67% test coverage and 45% mutation coverage.
Coverage of api profile after union: 92% test coverage and 75% mutation coverage.
[pitest-checkstyle-api profile before changes](https://nimfadora.github.io/api.html)
[pitest-checkstyle-api-filters profile after union before coverage increasing changes](https://nimfadora.github.io/filters_union_api.html)
increased mutation threshold for pitest-checkstyle-api-filters profile by 4%
current threshold: 85%
execution time: 9:51 min
=> Issue #4394: united api and filters profiles, increased coverage to 85%

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/CloseAndFlushTestByteArrayOutputStream.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue #4400 
[pitest report before changes](https://nimfadora.github.io/issue4400.html)
increased mutation threshold for pitest-checkstyle-common profile by 2%
current threshold: 92%
execution time: 13:02 min
=> Issue #4400: increase coverage of pitest-checkstyle-common profile to 92%

config/pmd.xml
Issue #4342 
suppressed issues as the don't seem to be ones that should be fixed.
`AccessorMethodGeneration` as it stated [here](https://github.com/checkstyle/checkstyle/issues/4342#issuecomment-310384718)
`UnusedPrivateMethod` as it generates false-positives on private methods called within a file
[pmd report](https://nimfadora.github.io/pmd-pr/pmd4342.html)
=> Issue #4342: suppressed production code violations as they should not be fixed

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/BlockOption.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/xdocs/config_blocks.xml, src/xdocs/property_types.xml
Issue #4035 
Renamed `STMT` in BlockOption class to `STATEMENT`. Also made subsequent changes in the EmptyBlockCheck, EmptyBlockCheckTest, config_blocks.xml, property_types.xml and messages.properties.
=> Issue #4035: Rename STMT in BlockOption class to STATEMENT

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilityTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilsTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnClass.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnConstructor.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnEnum.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnEnumMember.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnField.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnInterface.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnMethod.java
Issue #4395 
[pitest report before changes](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle.utils/index.html)
increased mutation threshold for pitest-checkstyle-api-filters profile by 32%
current threshold: 99%
execution time: 02:38 min
=> Issue #4395: increase coverage of pitest-checkstyle-utils profile to 99%

config/findbugs-exclude.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
Issue #3666 
The method 'getFilename' has been removed as it was deprecated and the subsequent changes to FileContentsTest and findbugs-exclude.xml have been made.
=> Issue #3666: Remove deprecated method 'getFilename' from FileContents class

src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/xdocs/anttask.xml.vm
so that invalid URLs can be treated as resource paths. Fixes #4449.
=> Manually parse the Ant configUrl field into a URL

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config.xml, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_coding.xml, src/xdocs/config_design.xml, src/xdocs/config_filefilters.xml, src/xdocs/config_filters.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_modifier.xml, src/xdocs/config_naming.xml, src/xdocs/config_regexp.xml, src/xdocs/config_sizes.xml, src/xdocs/config_whitespace.xml
Issue #4475
Just adding version to properties in this PR. Next PR will do module version.
I will not add version to Javadoc as there is no way to cross check them without a specialized JUnit, and this seems like this will be done with https://groups.google.com/forum/?hl=en#!topic/checkstyle-devel/lsNF6Dj90lo .
I added a temporary junit method to verify version numbers from extract file matched what I wrote in the xdocs.
I manually confirmed versions 3.0 and 6.7 because of limitations of the extract utility and small issues in CS at those times.
No modules were before 3.0 as they were internal, didn't use a configuration, and used System properties to control their settings.
=> Issue #4475: added since version column to all module properties

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount4.java, src/xdocs/config_sizes.xml
Issue #4534
@rnveach , please review and merge if you agree.
regression could be provided later, we need to unblock wercker.
=> Issue #4534: add ANNOTATION_DEF to defaultTokens to fix NPE

src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationAfterAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentIsAtTheEndOfBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInEmptyBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInMultiblockStructures.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInSwitchBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationJavadoc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationNoNpe.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode.java
Issue #4538 
This PR moves all inputs of CommentsIndentationCheckTest of the imports package to a new subdirectory 'commentsindentation'.
=> Issue #4538: Modified CommentsIndentationCheckTest.java and moved its input files to the commentsindentation subdirectory

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount5.java
Issue #4540
The reason to drop all the class definitions for a 'not method definition' condition is so [the change inversely mirrors exactly what is in `visitToken`](https://github.com/checkstyle/checkstyle/blob/7956f0b8d846d8f8ded1e9871e4bb58bf351fbb1/src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java#L112-L118). We should be less likely to have issues again if we add more tokens this way.
I will provide regression for just this change, and run regression against commit before bad PR to see if I can verify no more bad results exist.
=> Issue #4540: fixed wrong MethodCount with new nested interface def

.travis.yml, pom.xml
Issue #4373
Spotbugs was added to the project. All checks that are excluded in findbugs are also excluded here.
Generating report has shown no bugs.
=> Issue #4373: add Spotbugs to the project

src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue #3110 
This PR modifies the UTs in DefaultLoggerTest and CheckstyleAntTaskTest to support the localized messages set in DefaultLogger.
=> Issue #3110: Modified UTs to support localized messages from DefaultLogger

config/pmd-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
Issue #4567 
subtask of #877 
fixed AccessorClassGeneration violations and JUnitTestsShouldIncludeAssert  in CheckstyleAntTask
=> Issue #4567: fix AccessorClassGeneration and JUnitTestsShouldIncludeAssert violations

.ci/travis/travis.sh
base on problems at #4573
it is non obvious for users how to resolve such problem, so we need to print parts of HTML report.
=> config: print missed coverage during a coverage check

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/ThreadModeSettings.java, src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultConfigurationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TestRootModuleChecker.java, src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/config-multi-thread-mode.xml
Issue https://github.com/checkstyle/checkstyle/issues/4370
This MR adds new hidden parameter `-M` allowing user to enable multithread mode. Also, this commit splits `Checker` and `TreeWalker` into `AbstractChecker`, `Checker`, `MultiThreadChecker` and `AbstractTreeWalker`, `TreeWalker`, `MultiThreadTreeWalker` respectively. Multithread class versions are empty, because actual implementation is a subject of another issue.
=> Issue #4370: Add multi thread mode to checkstyle launcher

src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCoupling.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesAllIgnored.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesCommonPackage.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesDirectPackages.java
Issue #4575
This PR moves all inputs of ClassDataAbstractionCouplingCheckTest of the metrics package to a new subdirectory 'classdataabstractioncoupling'.
=> Issue #4575: Modified ClassDataAbstractionCouplingCheckTest.java and moved its input files to the classdataabstractioncoupling subdirectory

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockAnnotationDefaultKeyword.java
Issue #4472 
---------
Diffs with `LITERAL_DEFAULT`: https://soon-checkstyle-diffs.github.io/issue-4472-npe/index.html
Diffs with default module properties: https://soon-checkstyle-diffs.github.io/issue-4472/index.html
=> Issue #4472: Fix EmptyBlockCheck NPE with annotation default keyword

wercker.yml
Issue #4582
This is the final PR.
=> Issue #4582: restored wercker xwiki

config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelector.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentationTest.java
Issue #3555 
What was made:
Replaced creating temporary list and then creating unmodifiable view with `Collections.unmodifiableList` with assigning `line2position` field to new ArrayList and then adding all elements from origin list to field with `addAll()` method. All tests passed correctly/ During manual test case I checked that modifications of element's in original collection will not modify elements in copy as was supposed.
=> Issue #3555: refactoring: CodeSelectorPModel do double copy of collection in c-tor

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
Issue #4394
[pitest-checkstyle-api-filters profile before changes](https://nimfadora.github.io/issue4394.html)
increased mutation threshold for pitest-checkstyle-api-filters profile by 6%
current threshold: 90%
execution time: 18:23 min
=> Issue #4394: increase coverage of pitest-checkstyle-api-filters profile to 90%

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/InputTreeWalkerHiddenComments.java
Issue #4398
increased mutation threshold for pitest-checkstyle-tree-walker by 5%
threshold: 94%
execution time: 10:31 min
[pitest report before changes for package](https://nimfadora.github.io/issue4398.html)
=> Issue #4398: increase coverage of pitest-checkstyle-tree-walker profile to 94%

src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #4398
Identified in https://github.com/checkstyle/checkstyle/pull/4623#discussion_r125784524 , there were no tests verifying that TreeWalker calls checks' destroy method. When they were removed, only thing failing was code coverage.
Before PR pitest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/1/com.puppycrawl.tools.checkstyle/TreeWalker.java.html
After PR pitest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/2/com.puppycrawl.tools.checkstyle/TreeWalker.java.html
Only thing missing is supporting the `super.destroy()`.
=> Issue #4398: added tests to verify TreeWalker calling checks' destroy

pom.xml
Issue #4399
Futher to out conversation with @romani, this pull request suppresses all mutations (that can be suppressed) for pitest-checkstyle-main profile, so that later fix and remove suppressions.
Now the situation with main profile is as follows: [report](https://nimfadora.github.io/issue4399.html)
problems: 
1) [here](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle/Main.java.html#org.pitest.mutationtest.report.html.SourceFile@15e7538c_213) 
Original:
errorCounter != 0 && !cliViolations
I have tried many variants: 
errorCounter == 0 && !cliViolations
errorCounter == 0 && cliViolations
errorCounter != 0 && cliViolations
!(errorCounter != 0 && !cliViolations)
!(errorCounter == 0 && !cliViolations)
!(errorCounter == 0 && cliViolations)
!(errorCounter != 0 && cliViolations) …
=> Issue #4399: increase coverage of pitest-checkstyle-main profile to 99%

pom.xml
Issue #4398
Futher to out conversation with @romani, this pull request suppresses all mutations (that can be suppressed) for pitest-checkstyle-tree-walker profile, so that later fix and remove suppressions.
Now the situation with tree-walker profile is as follows: [report](https://nimfadora.github.io/issue4398.html)
(some mutations are timed out and appear only when some other are excluded)
=> Issue #4398: increase coverage of pitest-checkstyle-tree-walker profile to 100%

src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/bothfiles/InputIgnored.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/bothfiles/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/bothfiles/package.html, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleHtmlComment.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleNoJavadoc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/bothfiles/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/annotation/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/invalidformat/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/invalidinherit/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/valid/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/pkginfo/invalidformat/package-info.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/pkginfo/invalidinherit/package-info.java
Issue #4586 :
1.Copied&Renamed `InputNojavadoc` to the javadocstyle subdirectory.Because it was used by the other check test.
2.Moved&Renamed the remianing resources for JavadocStyleCheck to the javadocstyle subdirectory.
=> Issue #4586: Moved resources for the JavadocStyle check test

src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/SeparatorWrapTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapArrayDeclarator.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputSeparatorWrapEllipsis.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForArrayDeclarator.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForEllipsis.java
Issue #3752 
According to https://github.com/checkstyle/checkstyle/issues/3752#issuecomment-310446430 ARRAY_DECLARATOR and ELLIPSIS updated to EOL in google style check config.
Tests updated. Links to issues opened on google style added to comments.
=> Issue #3752: Added tokens to SeparatorWrapCheck in google style

src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/SinglelineDetector.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java
https://github.com/checkstyle/checkstyle/issues/4641
=> Issue #4641: Avoid usage of getLines method from FileText

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportWithBlockMethodParameters.java
This fixes issue #4606. 
I understand that `UnusedImportsCheck` needs to be rewritten to parse javadoc correctly. However, this fix is small and there is an included test that can be used to verify the rewrite.
I created a new input test file and test method in `UnusedImportsCheckTest`. If you prefer, I can just add the problem `@see` tag into `InputUnusedImports.java`.
=> Issue #4606: Support parameter imports for block-level javadoc tags

src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/ant/checkstyleanttask/InputCheckstyleAntTaskFlawless.java
Issue #4686 
This PR moves the remaining input file from the 'flawless' subdirectory to 'checkstyleanttask' subdirectory.
=> Issue #4686: Moved input of 'flawless' subdirectory to 'checkstyleanttask' subdirectory of CheckstyleAntTaskTest

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
#4700 
The `BUNDLE_CACHE` is defined as follows:
private static final Map<String, ResourceBundle> BUNDLE_CACHE =
Collections.synchronizedMap(new HashMap<>());
Therefore, additional `synchronized` blocks are redundant as long as we're doing all work inside the same method (see `getBundle` changes).
=> Issue #4700: Remove redundant sync for synchronizedMap (Intelllij inspection violations)

src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java
Issue #4592 
This PR adds a new class `AbstractPathTestSupport` which contains two methods `getPath(String filename)` and `abstract getPackageLocation()`. `CheckstyleAntTaskTest` and `SuppressionsLoaderTest` no longer extends BaseCheckTestSupport but instead uses this abstract class. This removes the file from the hierarchy.
=> Issue #4592: Added AbstractPathTestSupport and CheckstyleAntTaskTest, SuppressionsLoaderTest now extends from it

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
Issue #4707
fixed all IDEA violations from [this report](https://nimfadora.github.io/idea/suppressed_abstraction.html)
except BooleanParameter which will be addressed in #4709
=> Issue #4707: fixed abstraction IDEA violations

config/suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporter.java, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
Issue #4394
[pitest-checkstyle-api profile before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.api/index.html)
increased mutation threshold for pitest-checkstyle-api-filters profile by 8%
current threshold: 96%
execution time: 9:51 min
=> Issue #4394: increase coverage of pitest-checkstyle-api profile to 96%

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java
Issue #4394
[pitest-checkstyle-api profile before changes](https://nimfadora.github.io/issue4394.html)
increased mutation threshold for pitest-checkstyle-api profile by 4%
execution time: 3:31 min
one mutation left: [I have no idea how to test it](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.api/FileText.java.html#org.pitest.mutationtest.report.html.SourceFile@76e17762_175)
=> Issue #4394: increase coverage of pitest-checkstyle-api profile to 100%

src/test/java/com/puppycrawl/tools/checkstyle/AbstractTreeTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParseTreeTest.java
Issue #4592
This PR adds a new class AbstractTreeTestSupport which contains methods necessary for processing UTs for Tree tests. JavadocParseTreeTest and AstTreeStringPrinterTest no longer extends BaseCheckTestSupport but instead uses this abstract class. This removes the file from the hierarchy.
=> Issue #4592: Added AbstractTreeTestSupport and JavadocParseTreeTest, AstTreeStringPrinterTest now extend from it

src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractTreeTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
This PR adds `final` to the `getPath()` method in AbstractPathTestSupport and `/` to the `getNonCompilablePath()` method and the resulting changes because of that.
=> minor: Added 'final' to getPath in AbstractPathTestSupport and '/' to getNonCompilablePath in AbstractTreeTestSupport

config/suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/InputSuppressByIdWithNearbyCommentFilter.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/InputSuppressionCommentFilter.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressions_with_id.xml
Issue #4396
increased mutation threshold for pitest-checkstyle-filters by 5%
execution time: 9:42 min
[pitest report before changes for package](https://nimfadora.github.io/issue4396.html)
=> Issue #4396: increase coverage of pitest-checkstyle-filters profile to 100

config/intellij-idea-inspections.xml
Issue #4725
enabled such inspections:
AssertMessageNotString
CheckStyle
CollectionAddAllCanBeReplacedWithConstructor
CssConvertColorToRgbInspection
CssUnusedSymbol
DanglingJavadoc
ExtendsThrowable
FieldAccessedSynchronizedAndUnsynchronized
FieldRepeatedlyAccessed
FunctionWithMultipleLoopsJS
Guava
GuavaFluentIterable
HtmlUnknownTarget
IgnoreDuplicateEntry
IgnoreRelativeEntry
IgnoreUnusedEntry
JSDeclarationsAtScopeStart
MethodNamesDifferOnlyByCase
MethodOnlyUsedFromInnerClass
PackageNamingConvention
PackageVisibleField
RedundantMethodOverride
ResultOfObjectAllocationIgnored
StaticNonFinalField
UnusedParameters
=> Issue #4725: add inspections passed without violations

.ci/travis/travis.sh, pom.xml
#4769
JavadocParserListener and JavadocParserVisitor are excluded from generation as they are not used at all.
=> Issue #4769: Control coverage of JavadocParser and JavadocLexer

src/test/java/com/puppycrawl/tools/checkstyle/AbstractTreeTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/filefilters/ExclusionBeforeExecutionFileFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/EmbeddedNullCharTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/GeneratedJava14LexerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/HexFloatsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/Java7DiamondTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/Java7MultiCatchTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/Java7NumericalLiteralsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/Java7StringSwitchTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/Java7TryWithResourcesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/Java9TryWithResourcesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/LineCommentAtTheEndOfFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/MultiDimensionalArraysInGenericsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/UnicodeEscapeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/VarargTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/AnnotationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/AnnotationsOnArrayTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/DefaultMethodsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/LambdaTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/MethodReferencesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/ReceiverParameterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/java8/TypeUseAnnotationsOnQualifiedTypesTest.java
Issue #4592
This PR extends the tests in filefilters, filters, grammars packages from `AbstractModuleTestSupport` and `AbstractTreeTestSupport`.
=> Issue #4592: Tests from filefilters, filters, grammars now extend AbstractModuleTestSupport and AbstractTreeTestSupport

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/Comment.java, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AbstractTypeAwareCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineSet.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/HtmlTag.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTag.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImplTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/CommentsTest.java
Issue #4724
I think it is not very good idea to rewrite toString, as in JavadocNodeImpl, for e.z. we have such fields as [children and parent](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImpl.java#L68), in HtmlTag toString method [performs some calculations](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/HtmlTag.java#L121). What should I do with such cases?
=> Issue #4724: fix FieldNotUsedInToString IDEA violations

config/checkstyle_checks.xml, config/checkstyle_sevntu_checks.xml, config/import-control.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalkerAuditEvent.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalkerFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/InputTreeWalkerSuppressionCommentFilter.java, src/xdocs/config_filters.xml, src/xdocs/config_misc.xml, wercker.yml
https://github.com/checkstyle/checkstyle/issues/4714
=> Issue #4714: Make SuppressionCommentFilter and SuppressWithNearbyCommentFilter children of TreeWalker

wercker.yml
In PR for [4714](https://github.com/checkstyle/checkstyle/issues/4714), `wercker.yml` was patched to pass checks. Project [chekstyle-tester](https://github.com/checkstyle/contribution/tree/master/checkstyle-tester) was updated recently, `SuppressionCommentFilter` and `SuppressWithNearbyCommentFilter` modules were moved to `TreeWalker` and there is no need to patch [checks-nonjavadoc-error.xml](https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/checks-nonjavadoc-error.xml) now. This PR removes redundant commands from `wecker.yml` responsible for patching `checks-nonjavadoc-error.xml`
=> config: remove gist patch for contribution/checkstyle-tester

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
Issue #4402
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.annotation/index.html)
increased coverage of pitest-checks-annotation by 1%
execution time: 01:39
=> Issue #4402: increase coverage of pitest-checks-annotation to 100

src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/xdocs/config_javadoc.xml
=> Issue #4717: Added JavadocParserErrorStrategy which extends BailErrorStrategy

.travis.yml
Update for travis to older distribution until fixed.
#4847 - show all problems that are happening with trusty.
#4848 - will upgrade to "trusty"
=> config: add distribution for travis

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExtendedMethod.java
Issue #4856
This is a simple NPE fix.
The method being searched for in issue, `getClass`, can't be found because it is declared in `Object` and we can only look at the declarations in the current file. There is nothing we can do for the method except to skip over it.
Code was slightly modified so call to `findFrame` wasn't always being executed, regardless of `validateOnlyOverlapping` definition.
=> Issue #4856: fixed NPE in RequireThisCheck for methods from base class

src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/internal/package-info.java
Identified at https://github.com/checkstyle/checkstyle/pull/4855#discussion_r130225340 ,
this PR restores `AllChecksTest.testAllModulesWithDefaultConfiguration` to its working, original condition.
Changes in `AbstractModuleTestSupport` were needed to support `TreeWalkerFilterModule`s. This is what prompted me to create Issue #4843 .
`package-info.java` was added to quiet error from `testAllModulesWithDefaultConfiguration` when `JavadocPackageCheck` was run.
=> minor: restored AllChecksTest.testAllModulesWithDefaultConfiguration

src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java
Adds links to new tests supports `AbstractPathTestSupport`, `AbstractModuleTestSupport` and `AbstractTreeTestSupport` in `BaseCheckTestSupport` as it no longer supported and has become deprecated.
=> minor: Added links to new test supports in BaseCheckTestSupport

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable2.java
Issue #4630
We skip over `FOR_EACH_CLAUSE` in `leaveToken` but we don't do the same when we reach `LITERAL_FOR` which is a parent of `FOR_EACH_CLAUSE`.
=> Issue #4630: fixed exception in ModifiedControlVariable for enhanced for

src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
Issue #4885
Problem went unnoticed because we didn't have a test failing with multiple packages defined.
I assume coverage didn't catch anything missing because we inlined work using `Collectors.joining`.
=> Issue #4885: fixed list of packages when module can't be found

config/pmd-test.xml, config/sevntu_suppressions.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
Issue #4563
Rewrote `setParent` to not do a recursive call but to use a loop instead.
`testManyComments` was written in a way to avoid putting a 300kb input file into our repository.
It added 9 seconds runtime on my local PC.
i assume we don't need regression.
=> Issue #4563: fixed stackoverflow with DetailAST.setParent

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocCorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect.java
Issue #4744
This will also cover https://github.com/checkstyle/checkstyle/issues/4800 .
Changed in inputs is moving correct case out of incorrect input file. All changes in test are from that, not from change in code.
Regression will come, but it will be slow because of javadoc parsing.
=> Issue #4744: ignore starting inheritDoc in SummaryJavadocCheck

src/it/java/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/SummaryJavadocTest.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
Issue #4798
`summary.first.sentence` was rewritten to specify only an ending period was missing, as a missing first sentence is part of `summary.javaDoc.missing`.
Logic was rewritten to not show violations on missing summary and forbidden fragement at the same time for default module.
Changes in Tests were because of this.
Inlining `firstSentence = firstSentence.substring(0, endOfSentence);` is because nested `if`s were getting too deep and caused a violation. I didn't want to move `log`s outside of main visit.
=> Issue #4798: refactored SummaryJavadoc messages and logic

config/import-control.xml
Taken from https://github.com/checkstyle/checkstyle/pull/4899#discussion_r131524446
=> Pull #4907: disallow java.util.Comparator in import-control

src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierAnnotationOnEnumConstructor.java
=> Issue #4846: ignore annotation in enum constructor for RedundantModifier

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatter.java, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java, src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java
#4607 
In XMLLogger, there would be an `id="..."` if the module id is set. (and no `source="..."`)
Log message would be `[SEVERITY LEVEL] filePath:lineNo:columnNo: message. [ModuleId]`, if module id is set.
I was stuck before for I didn't realize that I need to modify `compareTo` in LocalizedMessage.
=> Issue #4607: Added moduleId to violation messages

src/main/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDoclet.java, src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/doclets/InputTokenTypesDocletJavadocParseError.java
Issue #4805
here are the changes in TokenTypes which cause build to fail
=> Issue #4805: fix HtmlTagCanBeJavadocTag in TokenTypes

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java
Issue #4945
This PR makes JavadocPackageCheck thread-safe, by enabling concurrent access to the `directoriesChecked` field
=> Issue #4945: JavadocPackageCheck should be thread-safe

src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelCounter.java
Issue #4927
Using `counter++` is not thread-safe, therefore it replaced with `AtomicInteger` and `count.incrementAndGet`
=> Issue #4927: Use atomic counter to allow multi-thread access

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
Issue #4925
This PR wraps all thread-unsafe context into a `ThreadLocal` instance
=> Issue #4925: Remove thread-unsafe context from the `AbstractJavadocCheck` class

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/SinglelineDetector.java, src/test/java/com/puppycrawl/tools/checkstyle/TestLoggingReporter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
Issue #4988
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.regexp/index.html)
pitest-checks-regexp coverage was increased by 7%
current threshould: 100
=> Issue #4988: increased coverage of pitest-checks-regexp to 100%

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
Issue #4675
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks/index.html)
pitest-checks-misc coverage by 3%
current threshold: 96%
=> Issue #4675: increased coverage of pitest-checks-misc to 96%

src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Issue #4842 
MainTest.testCreateListenerWithLocationIllegalStateException tests method Main.createListener. This method opens output stream for specified output location and passes created output stream to appropriate audit listener constructor. When specified format of the audit listener is not appropriate  it closes the stream with CommonUtils.close and throws exception.
Test MainTest.testCreateListenerWithLocationIllegalStateException mocks CommonUtils.close and in the result the output stream is not closed after invocation of Main.createListener.
At the end of the test it tried to remove the output location for which the output stream was not closed.
In Windows the file cannot be deleted where there is stream opened for file. The attempt to do this leads to the following error:
``` …
```
=> Issue #4842: make test for creating listener with location clean temp file

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/TestUtils.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthComments.java
Issue #4993
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.sizes/index.html)
coverage of pitest-checks-sizes was increased by 6%
=> Issue #4993: increased coverage of pitest-checks-sizes to 100%

config/checkstyle_checks.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/annotation/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckOnDifferentTokens.java, src/xdocs/checks.xml, src/xdocs/config_annotation.xml
Issue #3440 
Added new check for verifying that annotation located on same line with its target.
=> Issue #3440: Added new check for verifying that annotation located on same line with its target

src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
Issue #4932
Made `fileStarted`, `fileFinished`, `addError` and `addException` thread-safe
=> Issue #4932: XMLLogger should be thread-safe

shippable.yml, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
Issue #5022 
Not sure if shippable build is unstable, but I am able to reproduce the failure locally and the root of the problem is the following line:
fileMessages.clear();
Called inside `auditFinished`
Fixed coverage by adding a test for this behavior
=> Issue #5022: Fixed pitest coverage

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilsTest.java
Issue #4395
original: `id > TOKEN_VALUE_TO_NAME.length - 1`
mutated: `id > TOKEN_VALUE_TO_NAME.length + 1`
fixed: `id >= TOKEN_VALUE_TO_NAME.length`
and added one more test on the lower bound of invalid token id
=> Issue #4395: kill last mutation in pitest-checkstyle-utils

src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
Identified at https://github.com/checkstyle/checkstyle/pull/5025#discussion_r136051605 ,
We don't support swapping writers during mid-execution of Checkstyle, so we should remove `setOutputStream` to prevent people from mistaking this. Identified PR was going to make it `public` by mistake.
I wanted to make 1 constructor call another but I ran into some issues preventing that.
One constructor is deprecated so I don't think the good constructor should be calling the deprecated one.
There is no conversion from boolean to `OutputStreamOptions` that I can do in one line as required by a constructor call in a constructor unless I make a new method in `OutputStreamOptions` which would only be used for this purpose.
Eventually deprecated constructor will be removed, so I think this way is ok. If …
=> Pull #5033: made XMLLogger writer final

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportCheckClearState.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportWithoutWarnings.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportCheckClearState.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportWithoutWarnings.java
Issue #5004
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.imports/index.html)
coverage of pitest-checks-imports was increased by 2%
current threshold: 96
=> Issue #5004: increase coverage of pitest-checks-imports to 96%

.ci/eclipse-compiler-javac.sh
Issue #2600
> Extra quotes have to be removed, see my last comment in PR.
Looks like, removed all of them
> there should be:
> ECJ_JAR="ecj-4.7.jar"
> ECJ_MAVEN_VERSION="R-4.7-201706120950"
done
> build is failed but no details are printed.
Done. But it was conflicting with `-e` flag. 
> Please do PR(not for merge) 
Will do, after this one is merged
=> Issue #2600: improved some items

src/xdocs/writingjavadocchecks.xml.vm
Issue #3810  is fixed, so reference from web documentation is not required.
=> doc: remove section about a resolved API issue

src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/InputXpathAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/InputXpathEnum.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperAst.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperEnum.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperInterface.java
Issue #3891 
No inputs in main directory. https://github.com/rnveach/checkstyle/tree/issue_3891_6/src/test/resources/com/puppycrawl/tools/checkstyle/xpath
All deleted files were renamed and had their package change.
@romani Please note import change in `RootNodeTest` and how our checks don't complain either way. Eclipse made the change when I re-organized imports.
=> Issue #3891: reorganized xpath package inputs

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsJavadocQualifiedName.java
Issue #3453: UnusedImportsCheck: handle qualified names in javadoc
=> Issue #3453: UnusedImportsCheck: handle qualified names in javadoc

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
Issue #4908
Moved all thread-unsafe `AbstractCheck` state to a thread-local state holder
=> Issue #4908: Remove thread-unsafe context from AbstractCheck

.ci/eclipse-compiler-javac.sh
As I am new to this file, if i executed it as is it printed out 2000+ errors about couldn't be able to find classes.
It turns out that this is a required parameter that is passed by maven. Some of our other scripts can be executed as is, so it was not clear that this couldn't be.
I only modified it slightly to fail if no parameters were passed.
It doesn't affect the maven process any.
=> minor: modified eclipse compiler to not execute without arguments

src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/ParenPadTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputParenPad.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadTryWithResources.java, src/xdocs/config_whitespace.xml
Issue #4294: ParenPad: handle trailing semi-colons in try-with-resources
=> Issue #4294: ParenPad: handle trailing semi-colons in try-with-resources

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTags.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/abstractjavadoc/InputAbstractJavadocNonTightHtmlTags2.java
Issue #3311 : Added method doesCheckAcceptJavadocWithUnclosedHtmlTag in AbstractJavadocCheck which can be overridden in extending checks which are not to process javadoc with unclosed HTML tags
**`<obsolete>`** _I have added another method called `isUnlcosedTag` in `DetailNode` class.
`hasUnclosedTag` would return true whenever the javadoc node or any of its successors at any level is an unclosed HTML tag. `isUnclosedTag` would only return true when the javadoc node itself is an unclosed html tag. This would help user to exactly identify and process a javadoc node which is an unclosed tag in the way he/she wants to. And if a user wants to skip an entire portion of the tree having unclosed tags with in it then he/she can just use `hasUnclosedTag` rather than `isUnclosedTag`._
_If it is …
=> Issue #3311: Boolean indicator in AbstractJavadocCheck for decision regarding processing javadoc with unclosed HTML tags

config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
Issue #4984
Fields in JavadocTokenTypes reordered to remove violations caused by DeclarationOrderCheck.
=> Issue #4984: Reorder fields in JavadocTokenTypes

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
Issue #5005
[report before changes](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.metrics/)
increased coverage of pitest-checks-metrics by 4%
current threshold 97%
=> Issue #5005: increase coverage of pitest-checks-metrics to 97%

config/import-control.xml, config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/FileStatefulCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/GlobalStatefulCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/StatelessCheck.java
Issue #4883 
This PR adds the following marker interfaces:
1. ~~`OneModuleInstancePerApplication` - for stateless and global-stateful checks~~
1. ~~`OneModuleInstancePerThread` - for file-stateful checks~~
1. `GlobalStatefulModule` - for global-stateful checks
1. `FileStatefulModule` - for file-stateful checks
1. `StatelessModule` - for stateless checks
This PR is a base PR for https://github.com/checkstyle/checkstyle/pull/4892 and https://github.com/checkstyle/checkstyle/pull/4882
=> Issue #4883: Add MT check markers

config/org.eclipse.jdt.core.prefs, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultConfigurationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/FilterUtilsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
Testing if eclipse can be configured to flag unused exceptions in tests.
=>  Pull #5113: enabled eclipse compiler to flag unused exceptions 

config/pmd-test.xml, config/suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/GeneratedJavadocTokenTypesTest.java
Issue #5186: Added 'GeneratedJavadocTokenTypesTest' to check that the numbers generated by ANTLR for elements in javadoc grammar do not change with the grammar
=> Issue #5186: Addded GeneratedJavadocTokenTypesTest.java

config/checkstyle_checks.xml, config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinter.java, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java, src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/doclets/TokenTypesDocletTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammars/AstRegressionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java
Issue #5023. Changes:
Prohibited the usage of hardcoded encoding in Checkstyle sources
Fixed existing hardcoded encodings to match new rule
Allowed import of java.nio.charset.StandardCharsets for packages where it needed
=> Issue #5023. Prohibited the usage of hardcoded encoding in Checkstyle sources.

config/checkstyle_sevntu_checks.xml, config/sevntu_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
Issue #929
There is also an (abandoned and closed) PR for this issue: #4076
I have tried to take both the discussion from the issue and the incomplete PR into consideration.
Changes:
- Using private final loggers instead of private static final, except in the Main.java class
- Added sventu check to prevent static Loggers in the future
- Added exception to above rule for the Main.java class (for reasons see discussion in #4076)
=> Issue #929: Use private final loggers instead of private static final in Checkstyle codebase

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorChildNodes.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorMinColumnNo.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorStartOfTheLine.java
Issue #5003
[report before changes](https://nimfadora.github.io/issue5003.html)
increase coverage of pitest-checks-whitespace by 1%
current threshold: 99%
[regression report](https://nimfadora.github.io/diff5003/index.html)
=> Issue #5003: increase coverage of pitest-checks-whitespace to 99%

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
Issue #5003 
remove calls to [processExpression](https://github.com/checkstyle/checkstyle/issues/5003#issuecomment-338330949), as pitest claims ([here](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.whitespace/ParenPadCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4f473a20_123) and [here](https://nimfadora.github.io/pr/com.puppycrawl.tools.checkstyle.checks.whitespace/ParenPadCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4f473a20_187)) that they are useless
[regression report](https://nimfadora.github.io/diff5003-paren-pad/index.html)
=> Issue #5003: remove ParenPad#processExpression call where it seems useless

src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractAccessControlNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtils.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitialization.java
Issue #5124
This is the first PR.
This removes 64 of the 91 uses of `branchContains`.
I focused on all variables that were using `modifiers`.
I ran into 1 issue with this in `DesignForExtensionCheck` where a comment wasn't found in the modifier. I just undid the change and will look into it more later.
I ran into another issue with `AbstractAccessControlNameCheck` where the method said it was receiving the modifiers AST but in fact ti was not. I fixed this in the method call to it.
=> Issue #5124: removed usage of branchContains for modifiers

src/test/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
Issue #5228
Removed unnecessary `create*Config` methods and replaced them with `createModuleConfig`.
=> Issue #5228: removed unnecessary create module config methods

src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
Issue #5228
We must only use acceptable types for property values so regression util can understand what that value is.
`getResourcePath` was added to abstract support as I feel this can be used elsewhere in the future and will be a recognizable method by the util.
=> Issue #5228: property values must be acceptable types

src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolverTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilityTest.java
Issue #5210 
Some try/catches were invalid as they were catching exceptions that weren't expected. These try/catch blocks were removed.
`ClassResolverTest` had an interesting case where it had a fail but more code after it which shouldn't be possible to execute.
=> Issue #5210: added junit failures if exception is not thrown

src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/xdocs/config_javadoc.xml
Issue #5094: delete javadoc.parse.error
=> Issue #5094: delete javadoc.parse.error

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheck.java
Issue #4581 
This PR reorganizes the token methods in `whitespace, sizes` and `naming` folders.
=> Issue #4581: Reorganize token methods in whitespace, sizes, naming folders

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
=> Removed maxLineLength property from javadoc, the property itself had been removed earlier

src/xdocs/config_imports.xml
Issue #4284 
I updated the documentation to make it clear that static members have to be explicitly allowed. Do we leave it at that or will we implement a workaround for this issue?
=> Issue #4284: clarify documentation about allowing static imports

src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtility.java
Issue #5124
This removes 13 out of the 27 uses of `branchContains` left.
This removes all cases where the item being looked for was in a standard location.
=> Issue #5124: removed usage of branchContains for simple cases

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
Issue #4581
This PR reorganizes the token methods in `blocks`, `design`, and `metrics` folders.
=> Issue #4581: Reorganize token methods in blocks, design, metrics folders

src/main/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java
Issue #4581
This PR reorganizes the token methods in `javadoc` and `modifier` folders and miscellaneous checks.
=> Issue #4581: Reorganize token methods in javadoc and modifier folders and miscellaneous checks

src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
Issue #5228
This fixes all violations found in test besides ones for https://github.com/checkstyle/checkstyle/issues/5157. I only had to suppress 4 cases.
=> Issue #5228: fixed violations for test makeup

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocpackage/noparentfile/package-info.java
=> Issue #5127: Fixed NPE in JavadocPackageCheck when relative path is used to run checkstyle CLI

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
Issue #5157
Custom `verify` methods will be supported, however they shouldn't be creating configurations of the module being tested as we may not examine them for their properties.
Custom `create` methods will not be supported just like very custom property settings as there is too much variable in how they can be defined.
This fixes all cases.
=> Issue #5157: removed custom create configuration methods

.github/ISSUE_TEMPLATE.md
Provided output is more readable if it's wrapped in markdown. If it's provided in the template it's more likely that users will use it.
=> added markdown to .github/ISSUE_TEMPLATE.md

config/checkstyle_sevntu_checks.xml
Issue #5228
This completes the issue.
`RequireFailForTryCatchInJunit` is also required for CI to pass.
=> added CheckstyleTestMakeupCheck and added RequireFailForTryCatchInJunit from sevntu

config/findbugs-exclude.xml, config/intellij-idea-inspections.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
I did a search on all issues in our source and looked for ones that were closed and waiting for some fix.
The command I used was: `grep -ohr  "https://github.com/checkstyle/checkstyle/issues/[0-9]*" ~/opensource/checkstyle --exclude="releasenotes.xml" --exclude="releasenotes_old.xml" | sort -u -f`
Inputs could also be skipped in the search.
=> minor: removed temporary issues that are closed

src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterTest.java
Identified at https://github.com/checkstyle/checkstyle/pull/5236#issuecomment-349042760 ,
The constructor takes all the same fields as SuppressElement, but [it also takes an optional `xpathQuery`](https://github.com/checkstyle/checkstyle/blob/f994512712c08a16def4a3c5a0426b7ab1590cc9/src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java#L85-L88).
For other elements, [it is considered matching if the optional parameter is `null`](https://github.com/checkstyle/checkstyle/blob/f994512712c08a16def4a3c5a0426b7ab1590cc9/src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java#L114).
However as of right now, [`xpathQuery` it is considered not a match if is not given](https://github.com/checkstyle/checkstyle/blob/f994512712c08a16def4a3c5a0426b7ab1590cc9/src/main/java/ …
=> Pull #5321: fixed bug on matching xpath when no xpath given

src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
This change is to lock down our main abstract test classes from overriding to make it clear it isn't allowed anymore. We should be using what we built, instead of re-inventing things. If something is wrong with these classes, then they should be fixed.
See conversation at https://github.com/checkstyle/checkstyle/pull/5213#discussion_r155634192 .
I am unable to lockdown 2 methods, one in test and the other in IT.
https://github.com/checkstyle/checkstyle/blob/acb8b7f8da7336eebb9eac6c25680cc83c65be5d/src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java#L208
This can't be swapped because `WriteTagCheck` prints violations as `info` and it messes up the audit count because we only count errors. I will continue looking into how to remedy this. …
=> minor: locked down abstract test classes from overriding

src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtils.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilsTest.java
Issue #4876
Used method name talked about in issue. If you can think of a better one, let me know.
=> Issue #4876: specified what checks is in ModuleReflectionUtils

src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
Issue #4675
@romani This is missing line coverage, not mutation coverage.
Shippable isn't picking this up because it uses a different class name.
You are searching for `survived` when this had a class of `uncovered`. Shippable needs to be updated. Please make the update since you are better with shell scripts.
https://github.com/checkstyle/checkstyle/blob/master/shippable.yml#L55
=> Issue #4675: increased pitest coverage for misc package

src/test/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilterTest.java
Fix for missing coverage in master that pitest caught.
35c607f167d79343258926919799dab9bce9d33b added a new method to the class and no new tests were added.
a3ea8636e224f854ce56450c65139a805a9fab6f forced violations if pitest had uncovered lines.
The 2 in the end conflicted with one another.
=> minor: fixed missing coverage in SeverityMatchFilter

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisCatchVariables.java
Identified at https://github.com/checkstyle/checkstyle/issues/5307#issuecomment-351240617
Catch variables are seen in the scope of the try block instead of the catch block.
Easy printout of frame tree with this changes: https://github.com/rnveach/checkstyle/commit/aad8b0382813c6abadf951b603b2e884bb4a0478#diff-6b1f89f1bde0470d4bd42580d1aa8bfb
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/143/
http://rveach.no-ip.org/checkstyle/regression/reports/143/spring-framework/index.html#A1
=> Pull #5351: fixed RequireThisCheck and catch variable handling

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumConstant.java
Identified at https://github.com/checkstyle/checkstyle/issues/5307#issuecomment-351240617
Enumerations don't see enumeration constants at all.
Easy printout of frame tree with this changes: https://github.com/rnveach/checkstyle/commit/b5840705bde5c53316717f265289d0b0af8aa045#diff-6b1f89f1bde0470d4bd42580d1aa8bfb
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/143/
Regression was done in parallel with https://github.com/checkstyle/checkstyle/pull/5351 and it only showed regression for the other PR, so there is no regression with this PR.
Most likely it is because users don't write non-static variables in this casing.
The following shows the issue without the enum constants using the input file with the released CS version:
````
$ cat TestClass.java
package …
```
=> Pull #5361: fixed RequireThisCheck and enum constants handling

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAnnotationInterface.java
Identified at https://github.com/checkstyle/checkstyle/issues/5307#issuecomment-352132626 .
We had specifics to annotation interfaces, but we never used or collected them.
I will post regression soon.
=> Pull #5363: added missing annotation token definition

.ci/idea_inspection.sh, src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/FileStatefulCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/GlobalStatefulCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtils.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtils.java
minor: fix typos
no changes in the code, except the names of local variables and private methods.
=> minor: fix typos

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java
Identified at https://github.com/checkstyle/checkstyle/issues/5307#issuecomment-352307935 .
We assign current on a visit, but we don't reset it when we leave a token. So check thinks we are still in the previous frame, when we are back in the parent.
Here is proof:
````
$ cat TestClass.java
class NestedFrames {
int a = 0;
public int oneReturnInMethod2() {
for (int i = 0; i < 10; i++) {
int a = 1;
if (a != 2 && true) {
if (true | false) {
if (a - a != 0) {
a += 1;
}
}
}
}
return a + a * a;
}
}
$ cat TestConfig.xml
<module name="RequireThisCheck"> …
```
=> Pull #5364: changed RequireThis kept track of the frame being examined

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFor.java
Identified at https://github.com/checkstyle/checkstyle/issues/5307#issuecomment-352784756 
For loop variables are seen in the wrong scope. They are thought to be in the base method definition when they are actually scoped inside the loop itself.
You can clearly see the scope change at https://github.com/rnveach/checkstyle/commit/85c10036687b19156b06110d02c6408eac028864#diff-6b1f89f1bde0470d4bd42580d1aa8bfb .
````
$ cat TestClass.java
public class TestClass {
int b = 0;
void method() {
for (int b = 0; b < 10; b++) {
}
return b + b * b;
}
}
$ cat TestConfig.xml
<module …
```
=> Pull #5392: fixed RequireThisCheck and for loop variable handling

pom.xml, shippable.yml, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
Issue #4675
fixed last mutation described [here](https://github.com/checkstyle/checkstyle/issues/4675#issuecomment-353892974) by removing line, as it will not lead to some false-positives or missing errors in output.
=> Issue #4675: fix last mutation

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
Issue #5405
Violations are not always on files. Sometimes they are on directories.
`SuppressWithPlainTextComment` was changed to ignore these violations and not to try to read them as a file.
=> Issue #5405: SuppressWithPlainTextComment should ignore directories

config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/Configuration.java, src/main/java/com/puppycrawl/tools/checkstyle/api/Context.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java, wercker.yml
Issue #3455
An additional wercker commit was added to disable sevntu to pass CI. It must be re-enabled after checkstyle is released with this change and sevntu is released after using the new checkstyle version.
@romani This issue might not be correctly identified in the import file.
This issue is titled only for `api` package and copies allowances from `api` package, but there are other areas in the import file with this same issue number that is not `api` related.
https://github.com/checkstyle/checkstyle/blob/5cdbb191a17c65c2956b35d71513e9b59b6d2166/config/import-control.xml#L51
https://github.com/checkstyle/checkstyle/blob/5cdbb191a17c65c2956b35d71513e9b59b6d2166/config/import-control.xml#L67
https://github.com/checkstyle/checkstyle/blob/5cdbb191a17c65c2956b35d71513e9b59b6d2166/config/i …
=> Issue #3455: removed guava from api code

pom.xml
See discussions at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/628 .
=> minor: sevntu must use appropriate checkstyle version

src/xdocs/config_whitespace.xml
Issue #5401 
replace the word 'ignored' to 'validated' under SingleSpaceSeparator-Properties-validateComments
=> Issue #5401: replace the word 'ignored' to 'validated'

src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java, src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/GenericWhitespaceTest.java, src/it/java/com/google/checkstyle/test/chapter5naming/rule53camelcase/AbbreviationAsWordInNameTest.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
Issue #5409 
I will generate regression on the changes in the Check.
The sheer amount of duplication in `AvoidEscapedUnicodeCharactersCheck` is very sad.
I will create another issue once this PR is merged to sort the unicodes and split them apart better so they are easier to read.
=> Issue #5409: fixed intellij 2017.3 violations part 1

src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java, src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyOption.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyOption.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java
Issue #5423
The {@code } inline tag has some limitations:
- it may not contains encoded html entities such a &amp;lt; - they will be displayed 'as is'
- it may not contains symbols "!?." since they are treated as the end-of-sentence marker by the javadoc tool
- it may not contains symbols "{}" for obvious reason
To mark such fragments as code, the {@code } inline tag must be replaced with the HTML &lt;code&gt; tag.
In addition, several typos have been fixed.
=> Issue #5423: Javadoc fixes

src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerException.xml, src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerException2.xml, src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerException3.xml, src/test/resources/com/puppycrawl/tools/checkstyle/xmllogger/ExpectedXMLLoggerExceptionNullFileName.xml
Issue #5419
Regression isn't affected as we don't use `addException` method. See https://github.com/checkstyle/checkstyle/issues/4377 .
=> Issue #5419: prevented XMLLogger from sanitizing exception tags

src/xdocs/anttask.xml.vm, src/xdocs/cmdline.xml.vm, src/xdocs/config.xml, src/xdocs/config_annotation.xml, src/xdocs/config_coding.xml, src/xdocs/config_design.xml, src/xdocs/config_filters.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_naming.xml, src/xdocs/config_regexp.xml, src/xdocs/config_sizes.xml, src/xdocs/config_whitespace.xml, src/xdocs/contributing.xml, src/xdocs/google_style.xml, src/xdocs/index.xml.vm, src/xdocs/releasenotes.xml, src/xdocs/releasenotes_old.xml, src/xdocs/report_issue.xml, src/xdocs/sponsoring.xml, src/xdocs/writingchecks.xml, src/xdocs/writingfilefilters.xml, src/xdocs/writingfilters.xml, src/xdocs/writingjavadocchecks.xml.vm, src/xdocs/writinglisteners.xml.vm
Issue #5291
I tried to format as best I could.
@romani 
How do we want to handle xdoc comments that are too long? Should I split comment into 2 so `Warning here` stays on line with warning?
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_filters.xml#L305
Or linux commands too long:
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/cmdline.xml.vm#L180
=> Issue #5291: fixed long xdoc lines of 130 characters or more

src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheckTest.java
Issue #5409
http://rveach.no-ip.org/checkstyle/regression/reports/issue5409.html
~Fixes all `Unsafe lazy initialization of 'static' field inspection   2 errors`.~
Fixes all `Overridable method called during object construction inspection   8 errors`
Fixes one instance of `Redundant throws clause inspection   25 errors`.
=> Issue #5409: fixed intellij 2017.3 violations part 2

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionOverridableMethods.java
Issue #5255: fixed DesignForExtensionCheck for methods with no modifiers
=> Issue #5255: fixed DesignForExtensionCheck for methods with no modifiers

src/xdocs/config_filters.xml
#5517 
Based on https://github.com/checkstyle/checkstyle/pull/5464#issuecomment-362374643 and https://github.com/checkstyle/checkstyle/pull/5464#issuecomment-363918259 I removed unsupported checks from SuppressionXpathFilter xdoc.
Till https://github.com/checkstyle/checkstyle/pull/5509
=> minor: remove unsupported checks from SuppressionXpathFilter xdoc

pom.xml
Those Maven plugin versions have been specified in the pluginManagement section already. In Eclipse there are even warnings that these are duplicated.
=> infra: remove duplicated maven versions

src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilsTest.java
Issue #5561
Fixes a test failure on JDK9 .
=> Issue #5561: IllegalStateException message text was changed in JDK9

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolverTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilsTest.java
Issue #5558
Note that we are still using the PowerMock 1.x release. To compile the Checkstyle with JDK9 use
```
export MAVEN_OPTS='--add-opens java.xml/jdk.xml.internal=ALL-UNNAMED'
mvn clean verify -Dpowermock.version=2.0.0-beta.5
```
=> Issue #5558: Switch to powermock-api-mockito2

src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationFromGuava.java
Issue #5582
Drop `javax.xml.bind.annotation.XmlElement` import and replace with an inner annotation.
=> Issue #5582: Remove usage of javax.xml.bind.XmlElement

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java, src/test/resources/org/powermock/extensions/configuration.properties
Issue #5584
We need the file `org/powermock/extensions/configuration.properties` in the resources.
So, the test `AllTestsTest` should be fixed.
Note that this is a temporary solution. Once the Powermock issue will be fixed, the file `org/powermock/extensions/configuration.properties` will not be required.
=> Issue #5584: Switch to Powermock 2.0

src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
Issue #5595 
This is related to #5592. I'm going to extract some classes to a dedicated profile, but the Pitest complains on missing coverage for some classes.
=> Issue #5595: 100% coverage for PackageObjectFactory

.ci/shippable.sh, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
Issue #5599
This is related to #5592. I'm going to extract some classes to a dedicated profile, but the Pitest complains on missing coverage for some classes.
=> Issue #5599: 100% coverage for Checker

src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java
Issue #5597
This is related to #5592. I'm going to extract some classes to a dedicated profile, but the Pitest complains on missing coverage for some classes.
=> Issue #5597: 100% coverage for XMLLogger

.ci/shippable.sh, pom.xml, shippable.yml
Issue #5592
The largest part of `pitest-checkstyle-common` is the ANT test. Extracting this test to a dedicated profile will give more resources to the rest of `pitest-checkstyle-common`
=> Issue #5592: Split pitest-checkstyle-common

src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
Issue #5613
Solves the Spotbugs error
```
[ERROR] Forbidden method invocation: java.awt.event.InputEvent#getModifiers() [Deprecated in Java 9]
[ERROR]   in com.puppycrawl.tools.checkstyle.gui.TreeTable$TreeTableCellEditor (TreeTable.java:287)
```
=> Issue #5613: Replace InputEvent#getModifiers with getModifiersEx

pom.xml
Related to #5603
After reverting cba0f56054b402311cba2b2acb1e26e0c1506b13 there are two entries for maven.pmd.plugin.version in the pom.xml
=> config: Remove duplicate entry for PMD plugin version

.ci/shippable.sh, src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/api/Comment.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolverTest.java
Issue #5633 
- `for` loop in `JavadocDetailNodeParser` replaced with `foreach` loop
- `ClassResolverTest::TestMess` split into three different tests
- The garbage in `Comment` ctor replaced with some code
- `MutableExceptionCheckTest::testWrongTokenType` checks the exception message
=> Issue #5633: Fix PMD6 violations (bestpractices)

.travis.yml, appveyor.yml
Issue #5663
OracleJDK8 is the default environment for the time being.
For the other (OpenJDK8/9, OracleJDK9) we need a build step to make sure that our code is not JDK depended.
=> Issue #5663: Add openjdk8/9 to Travis/AppVeyor

.ci/sonar.sh, config/default_sonar_profile.xml
=> spelling: checkstyle profile

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4
=> spelling: grammar

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
note that this conflicts with #5654 (because there are 2 lines in a row, one's a comment, one's code). It's trivially resolvable. My original commit sequence has this change built on top of that change, but for "independent" (conflicting) PRs, that progression can't be followed.
=> spelling: code

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputFastMatcher.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrect.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectClass.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectFieldAndParameter.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectForAndParameter.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectIfAndParameter.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectReturnAndParameter.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectWhileDoWhileAndParameter.java
=> spelling: block indentation

src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4, src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/GeneratedJavadocTokenTypesTest.java
=> spelling: grammar singleton

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCtorCall.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationMethodCallLineWrap.java
Issue #5655
When a method name is on the next line from the dot, like this
```
a.
method(
someArg);
```
the indentation is calculated  in the wrong way. This PS fixes it.
=> Issue #5655: Indentation: wrapped method name

config/pmd.xml
Issue #5603
Part 2.
All the rulesets that are completely absorbed by the category `errorprone` have been removed.
Rulesets that are partially moved to the category `errorprone` will be retained until they are completely absorbed.
For the transition time some rules will be are excluded twice: one for the old `ruleset`, another for the new `category`.
=> Issue #5603: Use category/java/errorprone in the PMD config

config/pmd.xml
Issue #5603
Part 3.
All the rulesets that are completely absorbed by the category bestpractices have been removed.
Rulesets that are partially moved to the category bestpractices will be retained until they are completely absorbed.
Absorbed by `bestpractices`:
- rulesets/java/unusedcode.xml
- rulesets/java/sunsecure.xml
New Rules:
- GuardLogStatement
This rule is not compatible with CS. It can be solved by renaming `AbstractViolationReporter::log` to something else. But this requires changing the API and it does not make sense.
=> Issue #5603: Use category/java/bestpractices in the PMD config

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
Issue #5706
I will run regression to see if there are any affected cases.
Most likely it will only happen with very similar package/class names like `com.company.A` and `com.A`.
=> Issue #5706: fixed FinalClassCheck extracting qualified names

config/pmd-main.xml, config/pmd-test.xml, config/pmd.xml
Issue #5603
Part 4.
All the rulesets that are completely absorbed by the category `design` have been removed.
Rulesets that are partially moved to the category `design` will be retained until they are completely absorbed.
Absorbed rulesets:
- rulesets/java/codesize.xml
- rulesets/java/coupling.xml
- rulesets/java/junit.xml
- rulesets/java/strictexception.xml
- rulesets/java/typeresolution.xml
=> Issue #5603: Use category/java/design in the PMD config

config/import-control.xml
A few places we allow the package (and it's sub) but then later disallow a portion of the package.
This could mean the disallow is being ignored as the first matching rule we find is used and all subsequent rules are ignored, even if they happen to match too.
I moved all the disallows first so there can't be any mistakes from new changes.
=> config: moved disallows to be first in import control

config/pmd-main.xml, config/pmd-test.xml, config/pmd.xml
Issue #5603
Part 5.
All the rulesets that are completely absorbed by the category `codestyle` have been removed.
Rulesets that are partially moved to the category `codestyle` will be retained until they are completely absorbed.
Absorbed rulesets:
- rulesets/java/braces.xml
- rulesets/java/imports.xml
- rulesets/java/naming.xml
- rulesets/java/unnecessary.xml
=> Issue #5603: Use category/java/codestyle in the PMD config

config/pmd.xml
Issue #5603
Part 6.
All the rulesets that are completely absorbed by the category `performance` have been removed.
Rulesets that are partially moved to the category `performance` will be retained until they are completely absorbed.
Absorbed rulesets:
- rulesets/java/strings.xml
- rulesets/java/optimizations.xml
- rulesets/java/migrating.xml
=> Issue #5603: Use category/java/performance in the PMD config

.ci/test-spelling-unknown-words.sh
#5719
I should explain that the hg locate fallback is for my personal use -- I manage github work using mercurial. It shouldn't impact the normal flow.
=> Issue #5719: Switch to git ls-files and exclude from contrib

config/pmd.xml
Issue #5603
Part 8.
All the rulesets that are completely absorbed by the category `documentation` have been removed.
Rulesets that are partially moved to the category `documentation` will be retained until they are completely absorbed.
Absorbed rulesets:
- rulesets/java/comments.xml
- rulesets/java/design.xml
=> Issue #5603: Use category/java/documentation in the PMD config

.ci/jsoref-spellchecker/whitelist.words, config/catalog.xml, config/import-control.xml, config/pmd.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AbstractImportControl.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/FileImportControl.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/MismatchStrategy.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControl.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_4.dtd, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/FileImportControlTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControlTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileName.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileName.xml, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileNameNoExtension, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileNameNoExtension.xml, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrolloader/InputImportControlLoaderComplete.xml, src/xdocs/checks.xml, src/xdocs/config_imports.xml
Issue #3492
ImportControl -> AbstractImportControl with original code for abstract methods being placed inside PkgImportControl.
ClassImportControl is similar to PkgImportControl except there are no children and it is based on the class name and not the package. It must be declared next to other package definitions and not be mixed in with the current allow/disallow list just like packages. Packages and classes have the same priority. If they both match, then whichever one written in the XML file first will be used.
Class name is based on the first class found in the file. Other class names in the same file will be ignored.
=> Issue #3492: add ability to control imports in certain classes

src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_0.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_1.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_2.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_3.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/checks/imports/import_control_1_4.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/configuration_1_0.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/configuration_1_1.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/configuration_1_2.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/configuration_1_3.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/packages_1_0.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_0.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_1.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_1_xpath_experimental.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_2.dtd, src/main/resources/com/puppycrawl/tools/checkstyle/suppressions_1_2_xpath_experimental.dtd, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrolloader/InputImportControlLoaderDtd_MODIFIED_FOR_UT.dtd
Issue #5721 
This PR removes the xml declaration tag -> `<?xml version="1.0" .... ?>` from all `.dtd` files.
=> Issue #5721: Remove xml declaration tag from all dtd files

config/checkstyle_checks.xml, src/it/java/com/google/checkstyle/test/base/AbstractModuleTestSupport.java
Identified by IntelliJ locally.
=> config: turned on throws validation for JavadocMethod

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderMultiline.java
Issue #5881 
When the `import` token and the imported package name are on different lines, the first line should be compared.
=> Issue #5881: False positive for multiline imports

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
Issue #5722 
identified at https://github.com/checkstyle/checkstyle/issues/5601#issuecomment-396120018
CI failures https://circleci.com/gh/checkstyle/checkstyle/5997 :
```
4:14:57 AM PIT >> INFO : MINION : ls.checkstyle.api.CheckstyleException: unable to read
file:/home/circleci/project/src/test/resources/com/puppycrawl/tools/checkstyle/
checks/imports/importcontrol/InputImportControlOneRegExp.xml
at com.puppycrawl.tools.checkstyle.checks.imports.ImportContr
4:14:57 AM PIT >> INFO : MINION : olLoader.load(ImportControlLoader.java:282)
at com.puppycrawl.tools.checkstyle.checks.imports.ImportControlLoader.load(ImportControlLoader.java:253)
at com.puppycrawl.tools.checkstyle.checks.imports.ImportControlCheck.setFile(ImportControlCheck.java:192)
4:14:57 AM PIT >> INFO : MINION : 
... 44 more …
```
=> Issue #5722: Update DTD public names (typo at ImportControlLoader)

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/xdocs/config_naming.xml
```
<module name="ParameterName">
<property name="format" value="^[a-z][a-zA-Z0-9]+$"/>
</module>
</module>
</module>
boolean foo() {
try {} catch (Exception e) {}
}
}
$ java -jar checkstyle-8.10.1-all.jar -c config.xml Test.java
Audit done.
```
=> doc: update xdoc for ParameterName to clarify how to check catch parameter

pom.xml
Issue #5916
I am not completely sure that this is right update, but it helps to resolve problem in Eclipse.
=> Issue #5916: fix Eclipse error Plugin execution not covered by lifecycle

config/ant-phase-verify.xml
Issue #5916
fix for https://github.com/checkstyle/checkstyle/issues/5916#issuecomment-397519413
I have no idea why it should be like this, but it works.
=> Issue #5916: fix strange eclipse error that config is not found

src/xdocs/config_blocks.xml, src/xdocs/property_types.xml
Issue #4058: Updated xdocs to denote that RightCurlyCheck does not process right curly brace of expression blocks.
=> Issue #4058: xdocs update for right curly check

src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
Issue #5971 
The variable `final ANTLRInputStream input` was removed to prevent the violation `ExcessiveImports`.
=> Issue #5971: Remove usages of ANTLRInputStream

.ci/check-only-javadoc-error.sh
in (batch) mode to reduce amount of download logs
right now it is printing following:
```
Downloaded: https://repo.maven.apache.org/maven2/commons-digester/commons-digester/1.8.1/commons-digester-1.8.1.jar (143 KB at 278.7 KB/sec)
182/182 KB   308/328 KB   132/145 KB   
182/182 KB   307/328 KB   132/145 KB   
182/182 KB   308/328 KB   136/145 KB   
182/182 KB   308/328 KB   140/145 KB   
182/182 KB   311/328 KB   140/145 KB   
182/182 KB   311/328 KB   144/145 KB   
182/182 KB   311/328 KB   145/145 KB   
182/182 KB   312/328 KB   145/145 KB   
182/182 KB   315/328 KB   145/145 KB   
182/182 KB   316/328 KB   145/145 KB   
182/182 KB   319/328 KB   145/145 KB   
182/182 KB   320/328 KB   145/145 KB   
182/182 KB   323/328 KB   145/145 KB   
182/182 KB   325/328 KB   145/145 KB   
182/182 …
```
=> config: update distelli execution to run maven in non-interactive mode

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorImports.java, src/xdocs/config_whitespace.xml
Issue #4625 
Do not distinguish between type import and static import for `EmptyLineSeparatorCheck`,
to properly support `ImportOrderCheck` with `option` = `inflow`
=> Issue #4625: Unite type/static import for EmptyLineSeparatorCheck

src/site/resources/js/anchors.js
Go to `http://checkstyle.sourceforge.net/config_annotation.html#AnnotationLocation` . Click on any anchor, AnnotationLocation for example, and the new URL becomes `http://checkstyle.sourceforge.net/config_annotation.html#AnnotationLocation#AnnotationLocation`.
This issue always messes me up when switching to other anchor tags as most browsers will take this double hashtag as nonsense and not take you to either anchor on a page refresh.
This fixes this bug so it is always using the page's raw location.
=> minor: fix bug with hashtag in url for anchors

pom.xml
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/709#issuecomment-408118508
Caused:
> checkstyle-regression
Unable to instantiate 'com.github.sevntu.checkstyle.checks.coding.EnumTrailingCommaAndSemicolonCheck' class
=> config: upgraded sevntu-checkstyle-maven-plugin to 1.30.0

.ci/jsoref-spellchecker/whitelist.words
Issue #6055 
missed patch for spelling whitelist
=> spelling: add xcode

config/pmd.xml, pom.xml
Issue #5790
Release 6.6 seems to be more stable than its 6.X predecessors.
=> Issue #5790: Upgrade to PMD 6.6.0

config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
Identified at https://github.com/checkstyle/checkstyle/pull/6101#issuecomment-418950942
=> minor: fixed inlined javadoc tag from being split between lines

src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports.java
Issue #6121 
Note that the whole FullIdent::append was changed to simple
```
if (detailAST == null) {
detailAST = ast;
}
```
this is because the deepest `IDENT` in the chain as always the top- and leftmost one.
=> Issue #6121: Update FullIdent to store DetailAST instead of line/column

.ci/jsoref-spellchecker/whitelist.words, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/xdocs/config_naming.xml
=> Issue #5832: Add javadoc and xdoc Example for AbbreviationAsWordInName

config/version-number-rules.xml
saxon update is suppressed till #6149
this PR is based on failure of #6144
=> config: bump saxon to 9.9.0-1

src/it/java/com/google/checkstyle/test/chapter5naming/rule53camelcase/AbbreviationAsWordInNameTest.java, src/it/resources/com/google/checkstyle/test/chapter5naming/rule53camelcase/InputAbbreviationAsWordInTypeNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
The goal of this PR is to fix Issue #6130: 
- Calls to `getAbbreviationIfIllegal(String str, int beginIndex, int endIndex)` are now with inclusive indexes, regardless of whether the abbreviation is at the end of the string.
- When checking if an abbreviation is allowed, the final character is not stripped when the abbreviation is at the end of the string.
Regression results: http://esilkensen.github.io/checkstyle-tester/6130
=> Issue #6130: AbbreviationAsWordInName false positive at end of the word

.ci/jsoref-spellchecker/whitelist.words, README.md, config/import-control.xml, config/pmd-main.xml, config/pmd.xml, config/spotbugs-exclude.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMain1.java, src/xdocs/cmdline.xml.vm, src/xdocs/writingchecks.xml
Issue #6068: migrate to picocli command line parser from Commons CLI
This PR replaces #6082.
Sorry it took so long. It was harder than I thought to get all the tests and checks to pass. :-)
=> Issue #6068: migrate to picocli command line parser from Commons CLI

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/xdocs/config_filters.xml
Issue #5758
This fixes all checks in the issue.
=> Issue #5758: converted other line/column checks to log ast

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeAllowedAnnotations.java, src/xdocs/config_javadoc.xml
Issue: #5608
Copied the example of javadocMethod. Moved code to util class to avoid duplication. Added tests.
=> Issue #5608: Adding support for allowedAnnotations in javadocTypeCheck

config/intellij-idea-inspections.xml
#6241 
it does not work for my local IDEA, if still be an issue on remote, I will open issue on IDEA and disable inspection.
the same problem is with violations like:
```
Modularization issues
Class independent of its module
AllTestsTest.java
Class 'AllTestsTest' has no dependencies or dependents in its module
```
=> Issue #6241: allow disablement of ClassWithTooManyDependents inspection

config/intellij-idea-inspections.xml
Issue #6241
reason - https://teamcity.jetbrains.com/viewLog.html?buildId=1798853&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsMaster
on merge: do comment at https://youtrack.jetbrains.com/issue/IDEA-203424 that one more inspection is affected, with link to PR. This PR have link to master (see above), in PR status will be link to PR CI results with disablement in action.
=> Issue #6241: disable ClassIndependentOfModule till IDEA-203424

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
Issue #6238
Part of #6238 It simply fixed one test:
```
when(classLoader.getURLs()).thenThrow(IOException.class);
```
is not a legal code, since `URLClassLoader.getURLs()` throws nothing.
=> Issue #6238: Upgrade Powermock2 to RC4

pom.xml
Annotation pitest couldn't scan entire package with wildcards because pitest was throwing an entire on some class. See https://github.com/hcoles/pitest/issues/302 . It turns out the issue was pitest was loading our input files and it failed on one of them.
The specific file in our case was `InputAnnotationLocationDeprecatedAndCustom$Annotation`.
I changed all pitest profiles to ignore input files when we use a wildcard in test area and to now scan the entire annotation package.
=> config: ignore input files for pitest

.ci/jsoref-spellchecker/whitelist.words, .ci/pitest.sh, .ci/travis/travis.sh, .travis.yml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
Issue #4684
Update includes fix for files with similar names (TreeWalker versus TreeWalkerAuditEvent).
Script should have future support for https://github.com/checkstyle/checkstyle/pull/6254 .
How should I handle SuppressWarningsHolder?
> Xmlstarlet have option to define xsd, I did this to parse pom.xml
I think when I was looking at this before, it requires to put `pom:` before every node making the query longer. Let me know if you still want this.
=> Issue #4684: added shell script to find missing pitest files

pom.xml
Found one line with a * on the end and it seemed weird it did it and none of the others did. Removing that star and running the pitest report for it showed that the nested class never had any mutations calculated. Without the *, pitest by default ignores nested classes when we specify the class name. This change is to add * to all class names so we don't have to worry about remembering this for future changes.
=> config: add wildcards for nested classes since pitest wont add them

.ci/jsoref-spellchecker/whitelist.words, pom.xml
This is in support of https://github.com/checkstyle/checkstyle/issues/6264 .
Defaults are not added by default when you start adding new mutators. Just adding the new one without the defaults results in only the new mutator running. This is what I used to generate the report in the first post of the issue.
=> config: expanded pitest mutators to defaults

.ci/pitest.sh
Issue #6275
Travis and wercker uses some sorting, but it is either just displaying the results or comparing it to another file it sorted itself. So this seems like the only area that needs it.
Travis will fail because issue isn't approved.
=> Issue #6275: enforce same sorting on all systems for pitest.sh

src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderValid.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeAllowedAnnotations.java
Issue #6252 
Part of #6228 
from the test input `/src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderValid.java` one line was removed:
`import com.sun.accessibility.internal.resources.*;`
The line is not important and can be removed without any effect.
=> Issue #6252: Move test inputs with deprecated packages to resources-noncompilable

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodJavadocInMethod.java
Issue #6273 
Like issue stated, I found this because there was a mutation surviving on it and this is the results I got when I ran regression. I will run a new regression for this PR.
Comments aren't required because the check's implementation actually looks at the Java's source, so it sees everything, including comments.
This issue is needed to finish mutations which is the only reason I bring it up for a check we consider deprecated.
=> Issue #6273: removed comment support from JavadocMethodCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_imports.xml
Issue #5750 
First commit to exclude internal classes from validation.
The hack with `depth` counting won't work since this check validates only comment bocks, so the method `leaveToken` will be called right after the first processed comment. Instead of, the inner types now are filtered out by the scope.
Second commit for `CustomImportOrderCheck`, third for `ImportOrderCheck`
=> Issue #5750: aligned javadoc/xdoc for (Custom)ImportOrder 

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java
Issue #6320
This finishes packagenameloader profile which just had 1 mutation surviving.
=> Issue #6320: added REMOVE_CONDITIONALS mutator for packagenameloader

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierPrivateMethodInPrivateClass.java
=> Issue #6320: added REMOVE_CONDITIONALS mutator for modifier

.ci/test-spelling-unknown-words.sh
I'm about to offer the Travis integration to another project that uses Travis, so I revisited the script and it seems like there are only two minor changes I wanted to make in order to make it easier to reuse with different paths.
=> minor: refactor paths for spellchecker script

.ci/jsoref-spellchecker/whitelist.words, .ci/test-spelling-unknown-words.sh
`cpio ... --to-stdout` is a gnu-ism which of course doesn't work on *bsd (esp macOS).
This doesn't matter much when one uses Travis on Linux, but I develop on macOS... so it's helpful for the script to work there.
I've looked at `pax` and `cpio` and `tar`, and none of them seem to support pipe-to-pipe extraction (which is really disappointing).
This approach seems to work "well enough" for this one rpm, and I suspect it's fairly close to correct based on https://www.mkssoftware.com/docs/man4/cpio.4.asp
namely, each row has a `0707` magic field at the start, and there's a `\0` delimiter.
(mks is wrong about the magic field, it's only 0707...)
=> minor: rewrite cpio handling to support bsd

src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRightCurlyTest.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAlone.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLine2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAnnotations.java, src/xdocs/config_blocks.xml
Issue #4022 
_Some Test cases borrowed from a comment in #3775_
**Behavioral Changes:**
1. [This](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneOrSingleline.java#L108), [This](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneOrSingleline.java#L141), and [This (column '9')](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneOrSingleline.java#L148) are now violations
2. [This](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/InputRightCurlyAloneOrSingleline.jav …
=> Issue #4022: Removed shouldStartLine property for RightCurly

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableReceiverParameter.java
The goal of this PR is to fix Issue #6375, where the FinalLocalVariable check throws a NullPointerException when it encounters "receiver" parameters.
Proposed fix is to exclude these from the check via `CheckUtil.isReceiverParameter` (these parameters are implicitly `final` and the compiler will not let them be modified).
Regression report: http://esilkensen.github.io/checkstyle-tester/6375
=> Issue #6375: FinalLocalVariable: NPE

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtil.java
Issue #6403
Fun little note, originally I changed `.*?` to `.*` and the execution time doubled. I find it weird how much the `?` help.
=> Issue #6403: fixed bad regular expression when only doing a find

README.md, src/xdocs/contributing.xml
Issue #6236
I will update checkstyle.org to have "Build" section after merge.
=> Issue #6236: add build instructions to website

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableEnhancedForLoopVariable.java
The goal of this PR is to fix Issue #6377, where the FinalLocalVariable check can throw an IllegalStateException when checking an enhanced for-loop.
Proposed solution is to push/pop a new `ScopeData` when entering/exiting a `LITERAL_FOR` token, and to mark `FinalVariableCandidate`'s for enhanced for-loop variables as `assigned` upon creation.
Regression report: http://esilkensen.github.io/checkstyle-tester/6377
Elasticsearch example from the Issue description: [#A119](http://esilkensen.github.io/checkstyle-tester/6377/elasticsearch/index.html#A119)
**Example of the exception:** (with my understanding of how it happens)
```
public void method() {
for (Object o : collection) {
// do nothing
}
Object o;
if (condition) {
o = new String("foo");
} else {
o = new String("bar");
}
}
```
With the …
=> Issue #6377: FinalLocalVariable: IllegalStateException

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
After examining issues at https://github.com/checkstyle/checkstyle/pull/6421#issuecomment-462543909 ,
I looked into this memory and noticed ImportOrderCheck was using like 8 gigs of memory and 25 minutes to complete pitest. When looking at the report only 1 line said memory error. I changed the code around this mutation and now it completes the 1 check under a minute with no excess memory usage. Test was removed because code changed was directly connected to it.
I don't know if this fixes random issue we have seen in CI. It could be related since probably not all CIs will have huge chunks of memory for usage.
As a side note, this also helps solve https://github.com/checkstyle/checkstyle/issues/3567 as that test was still waiting further review.
=> minor: solved pitest issues with ImportOrderCheck

src/xdocs/extending.xml
Now, on the sidebar, there are 5 sections under `Extending Checkstyle` . However, in [Extending Checkstyle](https://checkstyle.org/extending.html) page, there are only 4 of them and File filter section is missing.
Let's add the File FIlter section back to extending.xml.
=> doc: add File Filter section in extending.xml

src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
Identified at https://github.com/checkstyle/checkstyle/pull/6432#pullrequestreview-204617009 ,
PackageObjectFactory lists classes that are not modules and should be removed.
=> minor: removed non-modules from PackageObjectFactory

config/version-number-rules.xml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Issue #6397
@romani Do we have a suppression somewhere that prevented this library from being upgraded until the issue was resolved?
=> Issue #6397: upgraded picocli to 3.9.5

config/suppressions.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAroundTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundBasic.java, src/main/resources/google_checks.xml
Issue #6381
I have tried to removed the `TokenTypes.LAMBDA` from `getDefaultTokens()` method in `WhitespaceAroundCheck` [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java#L213). However, it seems that it does not work.
While investigating on the issue, I found that there is already a [test](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java#L415) that tests the same issue. See the test with its previous test and the [test file](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyL …
=> Issue #6381: Incorrect warning for empty lambda bodies with google_checks.xml

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4832nocstylearray/ArrayTypeStyleTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4832nocstylearray/InputArrayTypeStyle.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyle.java, src/xdocs/config_misc.xml
The goal of this PR is to address Issue #6301 by adding support for checking the [ArrayTypeStyle](https://checkstyle.org/config_misc.html#ArrayTypeStyle) of method definitions.
The following is valid Java syntax:
```
Object emptyArray()[] {
...
}
```
With this PR, method definitions with array return types like the above would be reported as violations regardless of the value of `javaStyle`. My initial thought was that since functions can't have an array return type in C, it could make sense for this check to always enforce "Java-style" method return types.
That said, I think it'd be an easy enough code change to only report these method return type violations when `javaStyle` is `true` - or similarly to add a new parameter (or `TokenTypes.METHOD_DEF` as an optional token?) to configure …
=> Issue #6301: ArrayTypeStyle support for method definitions

src/it/java/com/google/checkstyle/test/chapter4formatting/rule485annotations/AnnotationLocationTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule485annotations/InputAnnotationLocation.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationMultiple.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationParameterized.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationSingleParameterless.java
Issue #6440 
Regression report: https://pbludov.github.io/issue-6440/
=> Issue #6440: AnnotationLocation: named parameters must be considered parameters

src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java
Issue #4814
Benefit of this PR is that most `startsWith` was removed and we are doing full `equals` now.
=> Issue #4814: added try/catch to setting up TreeWalker children

config/ant-phase-verify.xml
The exclude makes it look like it is excluding a folder but it is actually just a file.
There are some other around the same area that look like they might be files and not folders, but I am not sure. This is the only one that is affecting me right now.
=> config: fixed exclude for .checkstyle from eclipse-cs

src/main/java/com/puppycrawl/tools/checkstyle/filters/CsvFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/IntMatchFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/IntRangeFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/CsvFilterElementTest.java
Issue #6496
All classes already have equals/hashCode. Mostly minor documentation changes except CsvFilterElement where a public method had to be made private as it modifies the field from the constructor. Tests were removed as they were just duplicates of others and pitest/code coverage should show this.
=> Issue #6496: made and documented all filter elements are immutable

src/xdocs/property_types.xml
=> Issue #6458: Correct typo in Lcruly property type description

config/checkstyle_checks.xml
=> Issue #6452: Use default value false for javaFiveCompatibility property of MissingOverride check in checkstyle_checks.xml

pom.xml
As far as I understood the `no-validations` and `assembly` Maven profiles, they are intended to skip all validation tasks (and the latter additionally the site generation).
When I executed a build with `no-validations` profile I observed that the JDepend tasks are nevertheless run.
This change correct this and excludes JDepend validation in said profiles.
=> Skip JDepend in no-validations and assembly profiles

.github/CONTRIBUTING.md, src/xdocs/writingjavadocchecks.xml.vm
=> Issue #6478: fix last urls that reference old web site and old dtd location

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_blocks.xml
Issue #6532 (part of #5750)
Second commit to ignore `@noinspection` tag in the javadoc.
=> Issue #6532: aligned javadoc/xdoc for LeftCurly

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/TreeWalkerPowerTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checker/InputCheckerTabCharacter.txt, src/xdocs/config.xml
Issue #6485
I moved the standard tab width to `CommonUtil` since everyone is using it now.
To be able to generate the column position in `AbstractFileSetCheck` I had to make a few changes and collect the `FileContents` and used this to pass it to TreeWalker.
`FileTabCharacter` is the only file set that had to be changed to give the correct column position. This is because the changes to the log statement already included the +1 which is an exact mirror of `AbstractCheck`'s log method.
=> Issue #6485: added tabWidth to Checker and populated it to all checks

src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java
=> Issue #6133: Disable XML External Entity load in XmlUtil.java in tests

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_annotation.xml
Second commit to allow checks without any properties.
=> Issue #6531: aligned javadoc/xdoc for PackageAnnotation

config/pmd.xml, config/version-number-rules.xml, pom.xml
Issue #6536 
`LinguisticNaming` and `UseUnderscoresInNumericLiterals` are excluded for a while.
`CommonUtil` whitelisted since it is no more fit to `classReportLevel` of `CyclomaticComplexity`.
The level itself is reduced to 75.
=> Issue #6536: upgrade to PMD 6.12

config/pmd.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
Issue #6578
`Deque<Boolean> isAfterValues` ->  `Deque<Boolean> afterValues`
`Method isSubclass` -> `Method method`
`Method isStarImport` -> `Method method`
=> Issue #6578: Enable PMD rule LinguisticNaming

config/pmd.xml
Issue #6579 
`acceptableDecimalLength=6` for `UseUnderscoresInNumericLiterals` is the same as `minDecimalSymbolLength=7` for `NumericLiteralNeedsUnderscoreCheck`
=> Issue #6579: Enable PMD rule UseUnderscoresInNumericLiterals

.ci/pitest.sh
When running pitest on Windows, the diff shows all lines changed when there are
ignores configured due to difference in line endings. With this change, -w is
used for the diff so whitespaces are ignored.
=> config: ignore whitespace for pitest ignorelist

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
From https://github.com/checkstyle/checkstyle/pull/6604/files#r268451734
Fixes #6604
`RequireThisCheck.CatchFrame` and `RequireThisCheck.ForFrame` should be private or documented.
The second option is questionable because all other frame classes are private.
=> minor: make RequireThisCheck.{Catch,For}Frame private

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
This removes uses of an ANTLR specific method and uses the DetailAST directly instead.
This is in support of issue #3817 .
Regression will be provided.
=> minor: remove usage of antlr specific method in RequireThisCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
This removes uses of ANTLR classes and uses DetailAST directly instead.
This is in support of issue #3817 .
=> minor: remove unnecessary antlr classes from main code

src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4861blockcommentstyle/InputCommentsIndentationCommentIsAtTheEndOfBlock.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_EclipseDefaultNegative.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_EclipseDefaultPositive.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeStaticImports.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentIsAtTheEndOfBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthComments.java
Issue #4845
This removes uses of DetailAST from all our inputs.
This is in support of issue #3817 .
No changes to production code, so no regression required.
=> Issue #4845: remove usage of DetailAST from input files

src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
Issue #4861
Removed FileContext and merged it with the check itself. We don't create and use old FileContexts so creating a new instance on every new file isn't necessary.
Besides merging the classes, parameters and fields have to be renamed to avoid naming conflicts, public methods made private, methods moved inside other inner class, and getters/setters removed to use the field directly.
=> Issue #4861: resolved escaping this from AbstractClassCouplingCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
Issue #6624
This removes uses of an ANTLR specific method and uses the DetailAST directly instead.
This is in support of issue #3817 .
Regression will be provided.
=>  Issue #6624: remove usage of antlr method in VariableDeclarationUsage

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLine2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java
Fixes #6345.
When I working with this pr, I found that this may be an intended behavior of checkstyle.
See [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java#L225), it allows empty body.
If it is not the intended behavior, I will just delete the line that allows empty body.
=> Issue #6345: RightCurly with option alone false negative for class, method and constructor

.ci/jsoref-spellchecker/whitelist.words, config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeInner.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadocOnInterface.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerClasses.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerInterfaces.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeTags.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeUnusedParamInJavadocForClass.java, src/xdocs/checks.xml, src/xdocs/config_javadoc.xml, src/xdocs/property_types.xml
Issue #5411
This is for MissingJavadocType. It was pretty much a copy/paste of the original check.
=> Issue #5411: split JavadocType for missing javadocs

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_coding.xml
Second commit to force a whitespace after period/comma/etc.
=> Issue #6586: aligned javadoc/xdoc for FallThrough

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_coding.xml
=> Issue #6586: aligned javadoc/xdoc for VariableDeclarationUsageDistance

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
Issue: #6540 
The example from original issue (@Anno(@Value)) was already in test class (line 71), but it was in the list of violations for both ALWAYS and NEVER rules therefore it was removed for NEVER-cases.
=> Issue #6540: correct false positive AnnotationUseStyle

.travis.yml
It seems that we do not need the package 'oracle-java8-installer'.
This is some kind of atavism. It is not needed for the build process, since the `jdk-switcher` does its job well.
=> config: remove oracle-java8-installer

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_coding.xml
=> Issue #6586: aligned javadoc/xdoc for ReturnCount

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_coding.xml
=> Issue #6586: aligned javadoc/xdoc for NestedForDepth

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java, src/xdocs/config_javadoc.xml
I looked over the PR before merging but didn't realize the version numbers were still outdated.
=> minor: fix version numbers for MissingJavadocMethodCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
Missed marking some properties as deprecated.
=> minor: add missing deprecated on JavadocMethod properties

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java, src/xdocs/config_naming.xml
=> Issue #5832: Add javadoc and xdoc Example for MemberName

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_whitespace.xml
=> Issue #6749: aligned javadoc/xdoc for ParenPad

src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
=> Issue #6764: fix some sonar warnings and small refactoring

config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationSingleParameterless.java, src/xdocs/config_annotation.xml
Splitting followup part 2 for #6530
Fixes #6463
Regression report: http://kautler.net/cs-regression-6463/
Draft because based on fix for #6462, will rebase and un-draft once #6653 was merged.
=>  Issue #6463: Only handle fields for VARIABLE_DEF in AnnotationLocation check, not local variables

src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/xdocs/config_misc.xml
This matches more the intention of the check and also works properly
if you for example have files with Linux line ending on
Windows systems as is common for cross-platform projects.
Fixes #4073 
Depends on #6509
=> Issue #4073: Use lf_cr_crlf as default for NewlineAtEndOfFile check

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/xdocs/config_whitespace.xml
Issue #6749 (sequel for #6763) 
Minor changes to keep in sync with `NoWhitespaceBefore`
=> Issue #6749: aligned javadoc/xdoc for NoWhitespaceAfter

pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/538908990#L2800
@rnveach , looks like we do not validate trailing spaces in xml files.
=> minor: bump maven checkstyle to 3.1.0

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_filters.xml
Issue #6800
This PR affects only `xdocs/config_filters.xml`, other xdocs are OK.
=> Xdoc 'properties' subsection shoud be just one table

src/main/resources/google_checks.xml
The google checkstyle url is immediately followed by a period, it appears to be a part of the url if don't pay much attention, so I suggest to remove it.
The commit in this PR follows the advice from the last closed PR #6815.
=> minor: remove trailing period to correct the url

.travis.yml
From https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038
> As of today, Oracle licensing has changed and the JDK cannot be downloaded from Oracle any longer without logging in.
This PR to make sure that everything is going fine with openjdk8.
=> config: switch travis to openjdk8

.travis.yml
* OracleJdk9 build removed;
* javac9 build switched to openjdk9.
=> config: remove oracle9 configuration from travis ci

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
Issue #5750
Minor change to force a space before dash:
`Covariant {@code equals()} - method that...`
as we did it for the `Properties` section:
`Property {@code elementStyle} - Define the...`
=> Issue 5750 mdash space

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesCaseDefaultNoSingleLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesEmptyDefault.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineStatements.java
https://github.com/checkstyle/checkstyle/issues/4764
1. Fixed false-positive violation for braces for case and default blocks. 
2. Test cases were updated with example from original issue + lambda test case added.
3.  Code was refactored:
- single line checks for `case` and `default` was merged into one
- original logic for violation detection in `visitTree` was refactored to avoid useless checks
- couple of utility methods were added
- `isInAnnotationField` method was removed because this check was applied only to `default` keyword and it is covered by `hasUnbracedStatements` method
=> Issue #4764: fix false-positive violation in NeedBracesCheck

.travis.yml
The Oracle JDK License has [changed](https://www.oracle.com/technetwork/java/javase/overview/oracle-jdk-faqs.html) for releases starting April 16, 2019.
Oracle now require users to log in to an Oracle account to download their JDK. It is also not possible to cache installers, as this falls within redistribution restrictions. The only choice we have is to stop running the build against Oracle JDK.
=> config: remove Oracle JDK from Travis CI

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
Issue #6854
Now we need to use reflection to access the `Tag` class.
=> Issue #6854: make SuppressWithNearbyCommentFilter.Tag private

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilterSuppressById.java
The goal of this PR is to fix #6879 by updating the `isMatch` method in `SuppressionCommentFilter.Tag` so that it takes into account `messageFormat` when matching on module ID.
Related PR that does the same to `SuppressWithNearbyCommentFilter.Tag`: #6876
=> Issue #6879: SuppressionCommentFilter ignores messageFormat

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java, src/xdocs/config_naming.xml
The document of [ConstantName](https://checkstyle.sourceforge.io/config_naming.html#ConstantName) misses a slash. And then I check the source, and find the source misses it too. So I create this PR to fix it.
=> doc: Add missing slash for constant name check doc

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterCustomMessageFormat.sql
This PR fixes #6887, updating the suppression `isMatch` logic to always check the message format (instead of only when the event source format matches). It adds a test case that would fail with the current master code.
Previous PR's applied the same logic to SuppressionCommentFilter (#6882) and SuppressWithNearbyCommentFilter (#6876).
=> Issue #6887: SuppressWithPlainTextCommentFilter ignores messageFormat

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
This is a minor refactoring PR that cleans up `isMessageMatch` in SuppressionCommentFilter and SuppressWithNearbyComment filter, identified in https://github.com/checkstyle/checkstyle/pull/6899#discussion_r303358544
=> minor: refactor isMessageMatch in comment filters

pom.xml
This PR updates the mutation threshold for the pitest-filters profile to 100 in `pom.xml` (forgot to do as part of PR #6889 for Issue #6659)
=> Issue #6659: Increase mutation threshold for pitest-filters profile

.ci/pitest.sh, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParentheses15Extensions.java
#5008
HiddenFieldCheck.java:278: Removed unused call. It was always called with LPAREN, the actual params are handled by visitToken with PARAMETER_DEF.
MultipleVariableDeclarationsCheck.java:124: Cleaned up method since the AST is sorted. 
RequireThisCheck.java:454: Removed check for method call since these has already been handled by parentType == METHOD_CALL in processIdent prior to handling field.
=> Issue #5008: Increased coding pitest coverage to 100%

pom.xml
Issue #6910
`sevntu-checkstyle-maven-plugin` was replaced with `sevntu-checks` dependency
=> Issue #6910: replace sevntu-checkstyle-maven-plugin with sevntu-checks

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullOnTheSameLine.java
Issue #5008. 
Removed the remaining pitest mutations by introducing a utility method for testing which node is first in the AST. 
The reason not to cover the mutations where they were located previously is that it requires two ast nodes with the exact same location, which in an ast build from a source file will only be the case if the compared nodes are the same node. And since the checks enforces that one of the nodes are a method invocation or field access and the other is a declaration it will never  happen that it is the same node that is being compared to it self. 
I further added a test that shows a false warning generated by current master in EqualsAvoidNullCheck, due to the pitest hack with minimumSymbolsBetween.
=> Issue #5008: Removed remaining coding pitest

pom.xml
Issue #6910 
Maven property name for sevntu-checks was reverted because other projects might already use it (e.g.: https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.ci/travis.sh#L86)
=> Issue #6910: revert maven property name for sevntu-checks

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
````
[Console output redirected to file:M:\output.txt]
Usage: checkstyle [-dEghjJtTV] [-c=<configurationFile>] [-C=<checkerThreadsNumber>] [-f=<format>]
[-o=<outputPath>] [-p=<propertiesFile>] [-s=<suppressionLineColumnNumber>]
[-w=<tabWidth>] [-W=<treeWalkerThreadsNumber>] [-e=<exclude>]...
[-x=<excludeRegex>]... <files>...
Checkstyle verifies that the specified source code files adhere to the specified rules. By default
errors are reported to standard out in plain format. Checkstyle requires a configuration XML file
that configures the checks to apply.
<files>...            One or more source files to verify
-c=<configurationFile>    Sets the check configuration file to use.
-C, --checker-threads-number=<checkerThreadsNumber>
(experimental) The number of Checker threads (must be greater …
```
=> config: upgrade picocli to 4.0.0

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Split from https://github.com/checkstyle/checkstyle/pull/6862
An improper message during development threw something other than IAE and there was no way to tell which file or message caused the error without placing a breakpoint.
This is simply to make the debugging process easier by catching all exceptions and printing the specifics of where the error occurred.
=> minor: catch all exceptions when checking check messages

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_filters.xml
This PR addresses issue #6883 - adding an `idFormat` property to SuppressionCommentFilter. 
Currently, when deciding if an audit event should be suppressed, this filter first matches the event source against the `checkFormat`. If that fails, it matches the event module ID against the `checkFormat`. With this PR, the filter instead matches the event module ID against the new `idFormat` property (additional details in issue description).
Initial questions/notes:
* Should `idFormat` be a string or regular expression? It's a regular expression in this PR, but I think either way could make sense to me and would be happy to change it to a string.
* I think we'll want a regression report for this change? I'll run one tomorrow...
=> Issue #6883: Add ID format property to SuppressionCommentFilter

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
Issue #6947: this seems like a bug in Eclipse, but as a workaround I think we can just move the `{@code}` block onto one line.
=> Issue #6947: eclipse violation over javadoc of AtclauseOrderCheck.java

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/xdocs/config_filters.xml
Issue #6884: This PR adds an `idFormat` property to SuppressWithNearbyCommentFilter. 
Currently, when deciding if an audit event should be suppressed, this filter first matches the event source against the `checkFormat`. If that fails, it matches the event module ID against the `checkFormat`. With this PR, the filter instead matches the event module ID against the new `idFormat` property (additional details in issue description).
Related PR that added an `idFormat` property to SuppressionCommentFilter: #6928 
I will provide regression reports following the same pattern as in that PR.
=> Issue #6884: Add ID format property to SuppressWithNearbyCommentFilter

.ci/jsoref-spellchecker/whitelist.words, config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationCorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationCustomTags.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationIncorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationMultilineCodeBlock.java, src/xdocs/checks.xml, src/xdocs/config_javadoc.xml
Issue #6929 
Regression report: https://pbludov.github.io/issue-6929/
Mostly parse errors. Some catches:
https://pbludov.github.io/issue-6929/Hbase/index.html#A163
https://pbludov.github.io/issue-6929/hibernate-orm/index.html#A82
https://pbludov.github.io/issue-6929/hibernate-orm/index.html#A96
https://pbludov.github.io/issue-6929/hibernate-orm/index.html#A125
To discuss: use this check in google/sun configs?
=> Issue #6929: add check JavadocBlockTagLocation

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_misc.xml
No changes in the code, but many changes in the comments.
=> Issue #6966: aligned javadoc/xdoc for AvoidEscapedUnicodeCharacters

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAnonInnerLengthTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/anoninnerlength/SuppressionXpathRegressionAnonInnerLength.java
This PR adds XPath regression test for suppression filter on [AnonInnerLength](https://checkstyle.org/config_sizes.html#AnonInnerLength) check, see #6207.
=> Issue #6207: Add xpath regression test for AnonInnerLength

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAbstractClassNameTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/abstractclassname/SuppressionXpathRegressionAbstractClassNameInner.java, src/it/resources/org/checkstyle/suppressionxpathfilter/abstractclassname/SuppressionXpathRegressionAbstractClassNameTop.java, src/it/resources/org/checkstyle/suppressionxpathfilter/abstractclassname/SuppressionXpathRegressionAbstractClassNoModifier.java
This PR adds XPath regression test for suppression filter on [AbstractClassName](https://checkstyle.org/config_naming.html#AbstractClassName) check, see #6207.
=> Issue #6207: Add xpath regression test for AbstractClassName

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnusedImportsTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/unusedimports/SuppressionXpathRegressionUnusedImportsOne.java, src/it/resources/org/checkstyle/suppressionxpathfilter/unusedimports/SuppressionXpathRegressionUnusedImportsTwo.java
This PR adds XPath regression test for suppression filter on [UnusedImports](https://checkstyle.org/config_imports.html#UnusedImports) check, see #6207.
=> Issue #6207: Add xpath regression test for UnusedImports

.ci/jsoref-spellchecker/whitelist.words, .ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Issue #6982
it will not work on Windows, but our pitests are so linux dependent, so I think it is ok.
creation of file that user does not have access , will result in pollution on users filesystem (as we will not be able to remove it), it is not good.
=> Issue #6982: kill mutation survival at Main.listFiles() over canRead()

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java, src/xdocs/config_filters.xml
Issue #6954: This PR adds an `idFormat` property to SuppressWithPlainTextCommentFilter.
Related PR's added an `idFormat` property to SuppressionCommentFilter (#6928) and SuppressWithNearbyCommentFilter (#6951)
I will provide regression reports following the same pattern as in those PR's.
=> Issue #6954: Add ID format property to SuppressWithPlainTextCommentFilter

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidInlineConditionalsTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/SuppressionXpathRegressionAvoidInlineConditionalsAssert.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/SuppressionXpathRegressionAvoidInlineConditionalsAssign.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidinlineconditionals/SuppressionXpathRegressionAvoidInlineConditionalsVariableDef.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_coding.xml
This PR adds XPath regression test for suppression filter on [AvoidInlineConditionals](https://checkstyle.org/config_coding.html#AvoidInlineConditionals) check, see #6207. Also, fix related code snippets in documents.
=> Issue #6207: Add xpath regression test for AvoidInlineConditionals 

src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java, src/xdocs/config_misc.xml
Almost empty PR since the check is new and already aware of `XdocsJavaDocsTest`.
=> Issue #6966: aligned javadoc/xdoc for OrderedProperties

src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_misc.xml
Minor changes to the `XdocsPagesTest` to treat an empty `int array` as `{}` for properties of the type `Set of Tokens`.
This is need to avoid "Default value is ."
=> Issue #6966: aligned javadoc/xdoc for DescendantToken

src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_misc.xml
Second commit to ignore fields from inner `private` types.
This check has inner type `ResourceBundle` which also has a field named `baseName`.
Such fields should be ignored as we already do it for setters.
=>  Issue #6966: aligned javadoc/xdoc for Translation

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidNestedBlocksTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/SuppressionXpathRegressionAvoidNestedBlocksEmpty.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/SuppressionXpathRegressionAvoidNestedBlocksSwitch1.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/SuppressionXpathRegressionAvoidNestedBlocksSwitch2.java, src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnestedblocks/SuppressionXpathRegressionAvoidNestedBlocksVariable.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_blocks.xml
This PR adds XPath regression test for suppression filter on [AvoidNestedBlocks](https://checkstyle.org/config_blocks.html#AvoidNestedBlocks) check, see #6207.
Also, it fixes a complication error in related code example in documentation.
```
AvoidNestedBlocks $ cat Demo1.java
public class Demo1 {
int a = 0;
{
int a = 1;
}
System.out.println("a=" + a);
}
}
```
```
AvoidNestedBlocks $ javac Demo1.java
Demo1.java:5: error: variable a is already defined in method main(String[])
int a = 1;
^
1 error
```
=> Issue #6207: Add xpath regression test for AvoidNestedBlocks

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config.xml, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_coding.xml, src/xdocs/config_design.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_modifier.xml, src/xdocs/config_naming.xml, src/xdocs/config_regexp.xml, src/xdocs/config_reporting.xml, src/xdocs/config_sizes.xml, src/xdocs/config_whitespace.xml, src/xdocs/writingchecks.xml, src/xdocs/writinglisteners.xml.vm
Issue #6771 , this is not a final fix, just fixes over `xdoc` folder.
please review https://github.com/checkstyle/checkstyle/issues/6771#issuecomment-524585694
most interesting changes are at the bottom of github change page.
=> Issue #6771: update xdoc files to use violation term instead of error

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
Issue #5124
This is just a simple rewrite. Fixing code to use a valid Javadoc will be handled at https://github.com/checkstyle/checkstyle/issues/5450 .
=> Issue #5124: remove usages of branchContains for DesignForExtensionCheck

src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
#7032 quick fix to skip test if `setReadable(false)` returns false.
=> Issue #7032: skip test if file cannot be set to not-readable

src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java, src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentationTest.java
Issue #6724 
Formatted all multi-line javadocs. Now summary begin with the second line.
=> Issue #6724: format sources to pass JavadocSummaryLocationCheck

.ci/wercker.sh
it is possible after https://github.com/jqno/equalsverifier/pull/245
after merge, we should delete forked repo.
=> config: use upstream equalsverifier for CI

.ci/jsoref-spellchecker/whitelist.words, .ci/travis/travis.sh
Identified at https://github.com/checkstyle/checkstyle/pull/7088
Needed stacktrace to see `Property 'allowMissingJavadoc' does not exist, please check the documentation`
Original error was only showing `Unable to create Root Module: config {/home/travis/build/checkstyle/checkstyle/.ci-temp/simple-binary-encoding/config/checkstyle/checkstyle.xml}, classpath {/home/travis/build/checkstyle/checkstyle/.ci-temp/simple-binary-encoding/sbe-benchmarks/build/classes/java/generated:/home/travis/build/checkstyle/checkstyle/.ci-temp/simple-binary-encoding/sbe-benchmarks/build/resources/generated}.`
=> config: add stack trace to gradle

.circleci/config.yml, .travis.yml, shippable.yml, wercker.yml
Issue #7023
Split from https://github.com/checkstyle/checkstyle/pull/7088 where the PR showed the small fixes worked and the CI was running for all commits involved.
=> Issue #7023: fix all commits CI check to go against origin's master

.ci/jsoref-spellchecker/whitelist.words, .ci/travis/travis.sh
Fix for PR age issue. I believe the issue is the number being returned is a string and not integer and so needs to be converted to an integer.
Minor changes to the displays for easier debugging.
=> config: fix string to number issue in pr age check

.ci/eclipse-compiler-javac.sh
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/779 ,
4.10 doesn't exist on the server anymore, 4.11 is the lowest version.
We need to identify why our CI didn't pick this up. I looked at some previous builds and eclipse analysis was being skipped in them.
My local fails the same as sevntu.
=> config: upgrade eclipse static analysis

.ci/appveyor.bat, .travis.yml, config/spotbugs-exclude.xml
#7040
Add exclusions to spotbugs-exclude.xml for Files.newInputStream which can be ignored
I don't know why this doesn't fail on CI, but it blocks usage of `mvn clean install` locally. The messages don't reveal any issues and can be ignored.
=> Issue #7040: spotbugs is not executed in build process

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNull.java
Issue #5124 
Rewritten without `branchContains` 
Regression report: https://pbludov.github.io/issue-5124-2/
Before this PR there was a bug causing a call to
```
frame.findField("((fieldName))")
```
which returns `null`.  Changes in the method `skipVariableAssign` fixes this.
=> Issue #5124: remove usages of branchContains for EqualsAvoidNullCheck

config/org.eclipse.jdt.core.prefs
Issue #5060
Added reasons why some eclipse preferences are suppressed.
The rest remaining could be enabled.
=> Issue #5060: put reason to why eclipse violations are disabled

.ci/travis/travis.sh, .travis.yml, src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java
Issue #7129
Fixed mistype in `.ci/travis.sh`
`LocalizedMessageTest` now fails if the specified language or country code are not valid.
=> Issue #7129: use ja-JP for Japanese locale, zh-CN for Chinese locale in travis.sh

src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java
Issue #7170 
Do not validate empty strings Iif user has no locale configured.
=> Issue #7170: fix LocalizedMessageTest for empty locale

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/xdocs/config_coding.xml
Examples for UnnecessaryParenthesesCheck added. Fix #5747
=> Issue #5747: Examples for UnnecessaryParenthesesCheck added

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_imports.xml
Second commit to change `<h4>` to `<p>` to avoid `header used out of sequence` error issued by the javadoc tool.
=> Issue #7144: aligned javadoc/xdoc for ImportControl

.ci/travis/travis.sh, .travis.yml
this is requirements to understand how to deal with #7033 .
it is refactoring and cleanup.
Main points:
1) we do not need jdk9 and jdk10, as jdk11 is available now and it will be our next JDK, we can use only latest jdk in non LTS jdk in travis to keep amount of builds limited.
2) `package -Passembly` do skip of tests as I use this only during release to generate "xxxxx-all.jar" 
3) `-Dlinkcheck.skip=true` it is execution of link check plugin that is running during `site` phase.
4) `\!` is bash is required only when it is used in command line directly, as we keep suppressions in special string constants it is not required. Escaping of it make regex be `\!` - so it simply does not work. I verified this by `-X` execution, and execution of `mvn -e package -Dtest=....` now actually executes …
=> config: fix Travis items to do more jdk11 and jdk12 builds

.ci/wercker.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodParamsTags.java
Added one regexp to check params without docs and test from issue #6743, fixed failed tests, removed unused code.
Checkstyle tester diff report for this branch available here
https://tirex.github.io/checkstyle/diff/
=> Issue #6743: fixed unused param not reported when missing description

.ci/travis/travis.sh, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/ImportControlLoaderPowerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
Issue #7033
sacrify some pitest coverage on generated binary code
Coverage when test is removed (not sure why we did reflection, we can cover it now without reflection):
Problems in pitests over try with resources:
We value execution on new JDK more that pitest coverage (it is pitest issue, pitest should ignore such mutations, coverage of it become too problematic).
```
java -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+32)
OpenJDK 64-Bit Server VM (build 12+32, mixed mode, sharing)
./.ci/pitest.sh pitest-utils
./.ci/pitest.sh pitest-imports
```
=> Issue #7033: update tests to pass openjdk12

src/site/resources/css/site.css
Issue: #7036 
Display release date in upper right corner of release node block:
=> fix release date display

.ci/wercker.sh
Fix for build problem
https://app.wercker.com/checkstyle/checkstyle/runs/build/5dd4cb4b8e18590008b09d9a?step=5dd4cb9ef947d10009282aa1
Root cause: https://github.com/hibernate/hibernate-search/commit/170491f69d89a723fc1c7a1c4744f2a026933f32 see changes at bottom
=> config: update wercker build of hibernate to skip elaticsearch

.ci/wercker.sh
This reverts commit c442c78f24af273ebc770bc31a2579a9d9831418.
Issue #7288
=> Revert "Issue #7288: fix xwiki build on wercker"

.travis.yml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java
Issue #7276
In JDK-13 there is one more call to `out.flush` from `implClose`:
```
-            else
-                out.close();
+            else {
+                try {
+                    out.flush();
+                } finally {
+                    out.close();
+                }
+            }
```
See https://bugs.openjdk.java.net/browse/JDK-8220477">JDK-8220477
=> Issue #7276: Fix OutputStream flush count on JDK 13

.ci/travis/travis.sh, .travis.yml, appveyor.yml
Issue #7299
JDK 9 and JDK 10 build removed.
Java 9 specific syntax verified with JDK 11 in `--release 9` mode
=> Issue #7299: remove build for old non-LTS releases

pom.xml
detected while adding new plugin to pom.xml
our pom is huge so I used collapse for all plugins tags in Sublime
=> minor: fix indentation in pom.xml for forbiddenapis plugin

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
Issue #7309
Fixed in code:
*    Redundant suppression (Errors) (8)
*    Misordered 'assertEquals()' arguments (Errors) (1)
*    Redundant Collection operation (1)
*    Redundant type cast (Errors) (7)
*    Unnecessarily escaped character (1)
Fixed in config:
*    Constant on the wrong side of comparison (Errors) (2247)
*    Duplicated code fragment (30)
=> Issue #7309: fix teamcity inspections issues

config/import-control-test.xml, config/intellij-idea-inspections.xml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheckTest.java
Issue #6916
Auto converted to Junit5 with IDEA inspections.
As a side effect, some imports replaced with static imports.
=> Issue #6916: migrate tests to junit5 for annotation package

.travis.yml
Reasons:
1) it is hard to predict that whiltelist should be extended,
2) it is so easy to make typo
=> infra: move spellchecker to one of first job in Travis to fail faster

pom.xml
Issue https://github.com/jacoco/jacoco/issues/660 is resolved.
Local run of
`mvn clean test jacoco:restore-instrumented-classes  jacoco:report@default-report jacoco:check@default-check`
shows 100% coverage on my PC.
=> minor: remove obsolete jacoco suppression

config/checkstyle_checks.xml, config/import-control-test.xml, config/intellij-idea-inspections.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheckTest.java
Issue #6916
Tests of the `checks` (misc) package are migrated to Junit5.
Changes in the config:
Junit5 annotations `BeforeAll, AfterAll, BeforeEach, AfterEach` added to `DesignForExtension`;
annotation `TempDir` to `VisibilityModifier`.
=> Issue #6916: migrate tests to junit5 for checks package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue #6916
Tests of the `ant` package are migrated to Junit5.
~~I don't understand why IDEA replaced with static import invocations of method `MatcherAssert.assertThat` from `Hamcrest` but decided to leave them static for consistency with other test methods.~~
UPD: actually, IDEA did opposite change: *some* static import of `assertThat` were replaced with `MatcherAssert.assertThat` and this change broke the build. I reverted it back to static import.
=> Issue #6916: migrate tests to junit5 for ant package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
Issue #6916
Tests of the `blocks` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for blocks package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
Issue #6916
Tests of the `modifier` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for modifier package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LambdaParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheckTest.java
Issue #6916
Tests of the `naming` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for naming package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java
Issue #6916
Tests of the `regexp` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for regexp package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java
Issue #6916
Tests of the `sizes` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for sizes package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/CsvFilterElementTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/IntMatchFilterElementTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/IntRangeFilterElementTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElementTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElementTest.java
Issue #6916
Tests of the 'filters' and 'filefilters` packages are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for packages filefilters, filters

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java
Issue #6916
Tests of the `design` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for design package

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheckTest.java
Issue #6916
Tests of the `header` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for header package

src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java, src/xdocs/config_annotation.xml, src/xdocs/config_javadoc.xml, src/xdocs/writingchecks.xml
Issue #7341
This PR fixes links to non-public members and links to methods with changed signatures.
=> Issue #7341: fix javadoc links to non-public members

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AccessResultTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ClassImportRuleTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/FileImportControlTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControlTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportRuleTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
Issue #6916
Tests of the `imports` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for imports package

config/checkstyle_checks.xml, pom.xml, src/xdocs/config.xml, src/xdocs/config_filters.xml, src/xdocs/config_imports.xml
Issue #7340
Solved by reordering reports to execute `linkcheck` last.
Validation of links to `project-reports.html` and `project-info.html` suppressed as they created after **all reports** are generated.
`forcesite` was added at https://github.com/checkstyle/checkstyle/commit/dc3111cb1a2720eb59770756e1afa8d8b9982d8a there is small discussion in commit about such files
=> Issue #7340: linkcheck reports that all dtd files are missing

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineSetTest.java
Issue #6916
Tests of the `indentation` package are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for indentation package

src/site/resources/css/site.css, src/xdocs/writingjavadocchecks.xml.vm
Issue #7301:
* Fix source display in firefox
how it was before:
according to @rnveach there should be some space between the text of the code snippet and its border. This already works in chrome (merged in https://github.com/checkstyle/checkstyle/pull/7302) and this pr fixes that for firefox.
=> Issue #7301: fix source display for firefox

src/xdocs/property_types.xml
Issue #7339
New property type `file`.
Also, the documentation for all types that were called properties for some reason, even though they are types, has been fixed. Discovered by @rnveach at https://github.com/checkstyle/checkstyle/pull/7046#discussion_r336712228
=> Issue #7339: document property type file

.ci/jsoref-spellchecker/whitelist.words, config/import-control-test.xml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolverTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocNodeImplTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfoTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtilTest.java
Issue #6916
Tests of the `javadoc` package are migrated to Junit5.
This PR introduces new dependency: https://github.com/itsallcode/junit5-system-extensions
This is replacement for [SystemRules ](https://github.com/stefanbirkner/system-rules)
See changes in AbstractJavadocCheckTest.java
=> Issue #6916: migrate tests to junit5 for javadoc package

.ci/jsoref-spellchecker/whitelist.words, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
Issue #6916 
Fix for broken pitest. The original [commit](https://github.com/checkstyle/checkstyle/pull/7360/commits/e923b01b20607f3f62aff073618e15d81ae19d45#diff-d6da3ccf0fd4b2a7f156b27130a0fbbdL48) has `SystemOutGuard` instead of `SystemErrGuard`. As a result, wrong output stream was asserted.
This PR fixes it.
=> Issue #6916: fix AbstractJavadocCheckTest

config/import-control-test.xml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsMobileWrapperTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java
Issue #6916
Tests of the `internal` package are migrated to Junit5, except of `powermock`
=> Issue #6916: migrate tests to junit5 for package internal

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultConfigurationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefinitionsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParserTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageNamesLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertiesExpanderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/PropertyCacheFilePowerTest.java
Issue #6916
Tests of the checkstyle package are migrated to Junit5, except `MainTest` and `JavadocPropertiesGeneratorTest` which will be submitted in separate PR.
=> Issue #6916: migrate tests to junit5 for package checkstyle

src/main/java/com/puppycrawl/tools/checkstyle/Main.java
Issue #7382 
Blocker for #6916
The '@ TempDir ' annotation from Junit5 works slightly differently than the `@TemporaryFolder` rule from Junit4. This creates a new subdirectory in the $TMP folder, and deletes it when the test completes.
This creates problems when running tests under Windows. If there are unclosed files in the temporary subdirectory, the directory cannot be deleted.
=> Issue #7382: Fix Appveyor junit5 tests

config/import-control-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Issue #6916
Tests of the ` {Main,JavadocPropertiesenerator}Test` are migrated to Junit5.
=> Issue #6916: migrate tests to junit5 for {Main,JavadocPropertiesenerator}Test

config/suppressions.xml, src/main/resources/google_checks.xml, src/main/resources/sun_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainViolationsForGoogle.java, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainViolationsForGoogleSuppressions.xml, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainViolationsForGoogleXpathSuppressions.xml, src/xdocs/config_filters.xml, src/xdocs/google_style.xml, src/xdocs/sun_style.xml
Issue #6946
Examples of execution by CLI:
```
java -Dorg.checkstyle.google.suppressionxpathfilter.config="/var/tmp/xpath-suppressions.xml" \
-jar /var/tmp/checkstyle-8.28-all.jar \
-c google_checks.xml \
Test.java
Audit done.
```
```
java -Dorg.checkstyle.google.suppressionfilter.config="/var/tmp/suppressions.xml" \
-jar /var/tmp/checkstyle-8.28-all.jar \
-c google_checks.xml \
Test.java
Audit done.
```
Tested at https://github.com/sevntu-checkstyle/checkstyle-samples/pull/23
=> Issue #6946: add suppression filters to google and sun configs

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAlone.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLine2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySame.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java
Fix for issue #7187.
This PR is blocker for PR #7039 .
RightCurlyCheck false positives fixed.  For various tokens like `CLASS_DEF`, `METHOD_DEF` etc.
Regression report: 
https://sd1998.github.io/checkstyle-regression/Fix-7187/index.html
Base Config:
https://sd1998.github.io/checkstyle-regression/Fix-7187/base_config.xml
Patch Config:
https://sd1998.github.io/checkstyle-regression/Fix-7187/patch_config.xml
Report repository:
https://github.com/sd1998/checkstyle-regression/tree/master/Fix-7187
=> Fix #7187: RightCurlyCheck false positives fixed. 

.ci/travis/travis.sh, .travis.yml
It is not very reliable approach(in case of multi commits in PR it will not help) but lets start with some ...
**Testing on my local**:
Tree with merge commit on my local :
```
$ git log --graph
*   commit 7b39f32ec55abfca0ea126d36b19d45dd2c20779
|\  Merge: 10fa74a 47b2c58
| | Author: Roman Ivanov <ivanov-jr@mail.ru>
| | Date:   Tue Dec 24 14:28:57 2019 -0800
| | 
| |     Merge branch 'config-validate-since-in-new-checks'
| |   
| * commit 47b2c58e550f97ee6f94ac788864066e075cde13
| | Author: sd1998 <shashvat51@gmail.com>
| | Date:   Sun Oct 27 12:33:20 2019 +0530
| | 
| |     Issue #6971: NoArrayTrailingCommaCheck added
| |   
| * commit cd2e1f538a5d37917028421070f3c1dc252ce470
|/  Author: Roman Ivanov <ivanov-jr@mail.ru>
|   Date:   Tue Dec 24 14:06:20 2019 -0800
|   
|       config: …
```
=> Config validate since javadoc tag in new modules

config/checkstyle_checks.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOtherAlone.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAlone.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySame.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java, src/xdocs/config_blocks.xml
ANNOTATION_DEF support added in RightCurlyCheck. Fix #7041.
Regression:
https://sd1998.github.io/checkstyle-regression/Fix-7041/
=> Issue #7041: ANNOTATION_DEF support added in RightCurlyCheck

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
Issue #7391
All tests now use `captureMuted()` method.
=> Issue #7391: mute System.{err,out} in tests

.ci/wercker.sh
after release activity for already closed #7329
upstream repositories are migrated to 8.28.
=> config: update wercker to use upstream orekit and xwiki (#7329)

.ci/travis/travis.sh
problem noticed while execution of
```
$ ./.ci/travis/travis.sh no-exception-test-guava-with-google-checks
.....
[INFO] Total time:  40.480 s
[INFO] Finished at: 2019-12-29T15:39:38-08:00
Running Checkstyle on src/main/java - finished
linking report to index.html
Removing non referenced xref files in report ...
[delete] Deleting directory /home/rivanov/java/github/checkstyle/checkstyle/contribution/checkstyle-tester/src/main/java/guava
[move] Moving 43 files to /home/rivanov/java/github/checkstyle/checkstyle/contribution/checkstyle-tester/reports/guava
✔ ~/java/github/checkstyle/checkstyle [master|✚ 1…2] 
$ git …
```
=> config: upgrade several travis builds to use .ci-temp folder to keep repository untouched

.ci/travis/travis.sh
Issue #7423
it executes only from master build, not PR.
for some reason I can not run it from local, as it is hanging at `[INFO] User cache: /home/rivanov/.sonar/cache`
probably this PR should be just merged.
On remote it passed in master https://travis-ci.org/checkstyle/checkstyle/jobs/631080595#L1215 looks like this line is instant action and sonarqube server info should be printed immediately.
=> Issue #7423: provide organization/projectKey name as checkstyle for sonar

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
Noticed this when searching for something.
=> minor: remove unnecessary optional mention from JavadocMethodCheck

.ci/bump-license-year-in-all-projects.sh, .ci/bump-license-year.sh
based on mess of today in CI with year bump ....
https://github.com/checkstyle/checkstyle/pull/7433
https://github.com/checkstyle/checkstyle/pull/7434
from https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release#before-starting
ones merged, wiki should be updated.
such file should be copied to all other repositories (or use some wrapper with wget/curl of such script and execution of it)
Probably updates like this are not required for review/CI so we cn make script that clone all dependent repositories and make changes in them and push. So some maintainer will launch one script and it will do all required updates.
=> config: add .ci/bump-license-year-in-all-projects.sh

.ci/jsoref-spellchecker/whitelist.words, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/ScopeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelTest.java
Issue #7436
Small step to run tests in parallel. We need to get rid of the global state change in the tests.
=> Issue #7436: avoid using Locale.setDefault in tests

config/intellij-idea-inspections.xml, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java, src/xdocs/config_filters.xml
Issue #7405 
Now all checks are split into three sets:
* incompatible with SuppressionXpathFilter (#5770, #5777)
* compatible with SuppressionXpathFilter, but missing XPath IT Regression Testing (#6207)
* compatible with SuppressionXpathFilter and with XPath IT Regression Testing
After adding a new check, it must have xpath regression tests, or if this is not possible, it must be included in the list of incompatible checks.
=> Issue #7405: all new checks should have XpathRegressionTest

config/checkstyle_checks.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyOtherAlone.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneNewTokens.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineNewTokens.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySame.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameNewTokens.java, src/xdocs/config_blocks.xml
ENUM_DEF support added in RightCurlyCheck. Fix #7161.
Regression Report: 
https://sd1998.github.io/checkstyle-regression/Fix-7161/index.html
Base config:
https://sd1998.github.io/checkstyle-regression/Fix-7161/base_config.xml
Patch config:
https://sd1998.github.io/checkstyle-regression/Fix-7161/patch_config.xml
Regression Repo:
https://github.com/sd1998/checkstyle-regression/tree/master/Fix-7161
=> Issue #7161: ENUM_DEF support added for RightCurlyCheck

src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsMobileWrapperTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java
Issue #7446
`Node.getAttributes().getNamedItem("name").getNodeValue()` extracted to an utility method.
Method `sanitizeXml` moved to the class `XmlUtil`.
=> Issue #7446: ensure all checks summaries in sync with checks.xml

src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethods.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/ClassWithChainedMethodsCorrect.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationChainedMethodWithBracketOnNewLine.java
Issue #6210
regression report: https://alinkov.github.io/full_report/reports/diff/index.html
When we set up different values for **lineWrappingIndentation** and **basicOffset** (these values are different in sun checks and google checks) in some cases we have error `'method call rparen' has incorrect indentation`
For example for code
```java
when(someService.someMethod(any(), any()))
.thenReturn(
new SearchResult("val1", "val2")
);
```
=> Issue #6210: Use lineWrappingIndentation in multiline method call

pom.xml
detected by https://travis-ci.org/checkstyle/checkstyle/jobs/637603836#L1140
and dependabot do not see such version bump ability, even I manually asked it to "Bump now" at https://app.dependabot.com/accounts/checkstyle
so our shell hack is still useful :)
=> config: bump sonar-maven-plugin to 3.7.0.1746

src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
Issue #5604
'reference' already holds the assigned value along all execution'
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AW9t2w3qYD2QG1pPXIUe&open=AW9t2w3qYD2QG1pPXIUe
history of how such code appear - https://github.com/checkstyle/checkstyle/commit/69a3d541b4888e5e0e6ab09aa675667155c65381 
diff looks big, but all I did is inverted condition and put adjacent ELSE_IF as nested.
=> Issue #5604: resolve Sonar violation 'Remove this useless assignment'

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
Issue #7458
we need to recheck PR validation on sonar to make sure violations gone.
=> Issue #7458: 'ThreadLocal' variables should be cleaned up when no longer used

src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileSetCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllSinglelineCommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
Issue #7472
final modifier was added to satisfy Check
```
[echo] Checkstyle started (checkstyle_checks.xml): 17/01/2020 11:59:45 AM
[checkstyle] Running Checkstyle  on 1105 files
[checkstyle] [ERROR] src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java:1481:9: Class 'DynamicalResourceHolderCheck' looks like designed for extension (can be subclassed), but the method 'setFirstExternalResourceLocation' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'DynamicalResourceHolderCheck' final or making the method 'setFirstExternalResourceLocation' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
[checkstyle] [ERROR] …
```
=> Issue #7472: disable instatiation of modules with private ctor

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java, src/xdocs/config_misc.xml
based on discussion at https://github.com/checkstyle/checkstyle/pull/7238#discussion_r360711145
It is not very concise doc, but good step forward to unblock #7238 .
I did simple `// violation` on purpose to not bother user with too much details like `// indent:8 ; expected: > 4; ok, because 8 > 4` extra time.
=> doc: extend Indentation Check explanation of line wrap

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperClonePlainAndSubclasses.java
Discovered [here](https://github.com/checkstyle/checkstyle/pull/7489#discussion_r368164607)
JFYI: the Pitest can not appy `BooleanFalseReturnValsMutator` to code like `return a > b`.
After extracting a local variable,
```java
final boolean result = a > b;
return result;
``` 
the mutator `BooleanFalseReturnValsMutator` is able to add the mutation and the missing coverage is detected.
This PR adds the missing case.
=> minor: add missing test case to SuperCloneCheckTest

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java
Issue #7468
fix is blind, I am not sure  how to test it, but it is recommended to disable it by default - https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#jaxb-unmarshaller .
See issue for details.
=> Issue #7468: disable 'external-parameter-entities' feature by default 

src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ClassDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MemberDefHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #7487 
First commit to add the method.
Second commit to switch `ast.getChildCount() > 0` to `ast.hasChildren()` and `ast.getChildCount() == 0` to `!ast.hasChildren()`
Some `if`'s are inverted for readablity. The method `isOnEnumConstant` is rewritten to eliminate multiple calls to `getPrevSiblingSkipComments`
[InvalidJavadocPosition, DesignForExtension, JavadocContentLocation, MissingJavadocPackage](https://pbludov.github.io/issue-7487-has-children-6/)
[AtclauseOrder, JavadocBlockTagLocation, JavadocParagraph, JavadocTagContinuationIndentation, MissingDeprecated, NonEmptyAtclauseDescription, SingleLineJavadoc, SummaryJavadoc](https://pbludov.github.io/issue-7487-has-children-5/)
[SummaryJavadoc only](https://pbludov.github.io/issue-7487-has-children-4/)
=> Issue 7487 add method hasChildren() to DetailAST

config/pmd-main.xml, config/pmd.xml
partially address #7509
still not resolved:
```
[WARNING] The rule CollapsibleIfStatements is referenced multiple times 
in "PMD ruleset for Checkstyle". Only the last rule configuration is used.
[WARNING] The rule CollapsibleIfStatements is referenced multiple times 
in "PMD ruleset for Checkstyle". Only the last rule configuration is used.
[WARNING] Use of deprecated attribute 'ClassOrInterfaceDeclaration/@Image'
in XPath query
```
but `CollapsibleIfStatements` is used only ones:
```
✔ ~/java/github/romani/checkstyle [7509-pmd L|✔] 
$ ag "CollapsibleIfStatements"
config/pmd-main.xml
14:    <rule ref="category/java/design.xml/CollapsibleIfStatements"/>
```
=> Issue #7509: resolve some pmd warnings

src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java
Issue #7512 
The method was used only in one check.
Regression (no difference):
https://pbludov.github.io/issue-7512-get-number-of-children/
=> Issue #7512: mark DetailAST::getNumberOfChildren deprecated

config/checkstyle_checks.xml, config/pmd.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
from https://github.com/checkstyle/checkstyle/pull/7485#discussion_r373470333
tested:
```
✔ ~/java/github/romani/checkstyle [minor-extra-regexp-check L|✚ 1] 
$ git diff
diff --git a/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java 
b/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
index 6eefd8e..15a5622 100644
--- a/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
+++ b/src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
@@ -374,7 +374,7 @@ public class ElementNode extends AbstractNode {
* Create an iterator over the "following" axis.
* @param start the initial context node.
*/
-        /* default */ FollowingEnumeration(NodeInfo start) {
+        /* default */ public FollowingEnumeration(NodeInfo start) { …
```
=> minor: add Check with id noDefaultCommentWithOtherVisibility

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java, src/xdocs/config_annotation.xml
lowercase is used for javadoc tag, but in example there is an annotation, it should be uppercase
=> doc: deprecated -> Deprecated

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java, src/xdocs/config_naming.xml
It is a bit unclear that [MemberName](https://checkstyle.org/config_naming.html#MemberName) is for **instance** members only.
This PR adds an example on non-instance member to make obvious.
=> doc: add example of non-instance member for MemberNameCheck

wercker.yml
problem at https://app.wercker.com/checkstyle/checkstyle/runs/build/5e5129ae7b63df001ae10266?step=5e5129f61ccc98000832416b
`[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-common-rules) @ hibernate-search-parent --- [WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message: Detected Maven Version: 3.5.2 is not in the allowed range 3.6.2.`
detected at https://github.com/checkstyle/checkstyle/pull/7577#issuecomment-589996135
=> infra: update wercker maven to 3.6.2 to pass build of hibernate-search

src/xdocs/config_coding.xml
=> doc: fix indentation of config example

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java, src/xdocs/config_whitespace.xml
Issue #7631: add code examples
```
<module name="WhitespaceAfter"/>
</module>
</module>
if (foo) {              // OK
//...
} else if(bar) {        // violation
//...
}
testMethod(foo, bar);   // OK
testMethod(foo,bar);    // violation
for (;;){}               // OK
for(;;){}                // violation, space after 'for' is required
}
}
$ java -jar /var/tmp/checkstyle-8.29-all.jar -c config.xml Test.java 
[ERROR] /var/tmp/Test.java:6:14: 'if' is not followed by …
```
=> fix-for-issue-7631

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java, src/xdocs/config_coding.xml
Fixes Issue: #7668 
<module name="MissingSwitchDefault"/>
</module>
</module>
switch (i) {
case 1:
break;
case 2:
break;
// violation
}
switch (i) {
case 1:
break;
default: // OK
break;
}
}
}
[ERROR] D:\OpenSource\TestCommit\Test.java:4: switch without "default" clause. [MissingSwitchDefault]
Audit done.
=> Issue #7668: Add examples for Missing Switch default

src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java, src/xdocs/config_misc.xml
Fixes Issue: #7591
<module name="TodoComment"/>
</module>
</module>
i++;   // TODO: do differently in future   // violation
i++;   // todo: do differently in future   // OK
}
}
[ERROR] D:\OpenSource\TestCommit\Test.java:4: Comment matches to-do format 'TODO:'. [TodoComment] 
Audit done.
Output of non-default example:
$ cat config2.xml …
=> Issue #7591: Update doc for TodoComment

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java, src/xdocs/config_whitespace.xml
Issue #7621: Update doc for GenericWhitespace
The relevant section has been modified. It now looks like this: 
There are no additional configurations, so there is only one set of example violations. Output:
```
<module name="GenericWhitespace"/>
</module>
</module>
D:\checkstyletest>type test\Test.java 
public<T> void foo() {} // violation, "<" not preceded with whitespace
public void test() {
List< String> l; // violation, "<" followed with whitespace
List a = new ArrayList <>(); // violation, "<" preceded with whitespace …
```
=> Issue #7621: Update doc for GenericWhitespace

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java, src/xdocs/config_imports.xml
Fixes Issue: #7684 
<module name="AvoidStarImport">
</module>
</module>
</module>
import java.util.Scanner;         // OK
import java.io.*;                 // violation
import static java.lang.Math.*;   // violation
[ERROR] D:\OpenSource\TestCommit\Test.java:2: Using the '.*' form of import should be avoided - java.io.*. [AvoidStarImport]
[ERROR] D:\OpenSource\TestCommit\Test.java:3: Using the '.*' form of import should be avoided - java.lang.Math.*. …
=> Issue #7684: update doc for AvoidStarImport

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/xdocs/config_javadoc.xml
"var" has already been added as an allowed tag: https://github.com/checkstyle/checkstyle/blob/12c6e69fe7de3d462f5ca117dc4a6f0ba51a1d7c/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L209-L218
I've tested it on the latest release:
```
<module name="JavadocStyle"/>
</module>
</module>
D:\checkstyletest>type test\Test.java 
/**
* First sentence.
* 
* <div>this is a valid tag</div>
* <var>this is also a valid tag</var>
* <foo>this is not a valid tag</foo>
* 
*/
public class Test {}
D:\checkstyletest>java -jar …
```
=> Issue #2410: JavadocStyleCheck: need to support VAR html tag

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java, src/xdocs/config_coding.xml
issue: #7645: Update doc for IllegalToken
```xml
<module name="IllegalToken"/>
</module>
```
```java
outer: // violation
for (int i = 0; i < 5; i++) {
if (i == 1) {
break outer;
}
}
}
}
```
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java
[ERROR] /Users/hgh/Downloads/my_file/IDEA_workspace/Leetcode_maven/engineering_ability/src/main/java/Test.java:4:14: Using 'outer:' is not …
=> issue #7645: Update doc for IllegalToken

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java, src/xdocs/config_coding.xml
Issue #7646: Update doc for IllegalTokenText
Output of configure to configure the check to forbid String literals containing "a href": 
```xml
<module name="IllegalTokenText">
<property name="tokens" value="STRING_LITERAL"/>
<property name="format" value="a href"/>
</module>
</module>
</module>
```
```java
String test = "a href"; // violation
}
}
```
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java …
=> Issue #7646: Update doc for IllegalTokenText

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java, src/xdocs/config_coding.xml
Fixes Issue #7642 
Output for default example:
```
<module name="IllegalCatch"/>
</module>
</module>
$ cat test.java 
class test{
public static void main(String[] args)
{
try {
// do stuff
} catch (Exception e) { // Violation
}
try {
// do stuff
} catch (ArithmeticException e) {
} catch (Exception e) { //Violation, one of the exception is declared to be illegal and order of multi-catch blocks doesn't matter
}
try {
// do stuff
} catch (ArithmeticException | Exception e) {  Violation, one of the exception is declared to be illegal
}
try {
// do stuff
} catch …
```
=> Issue #7642: Update doc for IllegalCatch

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule341onetoplevel/OneTopLevelClassTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOneTopLevelClassTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/onetoplevelclass/SuppressionXpathRegressionOneTopLevelClass.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassIndentation.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassSameLine.java, src/xdocs/config_filters.xml
Resolve #7754: Update AbstractChecks to log DetailAST - OneTopLevelClass
Diff report: https://wltan.github.io/checkstyle-reports/2020-03-08/onetoplevel/diff/
There is only one log call to fix: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java#L153
Notes:
1. I wasn't able to upload all of the "deeper" files due to the max file path length (on Windows). But I think all of the essential information should be there.
2. All of the discrepancies seem to be about the extra column number, which is expected as we now log the DetailAST node instead of just the line number.
3. Our unit tests only cover violations at column 1, but other projects can have violations at other columns as well (e.g. `apache-ant` has …
=> Issue #7754: Update AbstractChecks to log DetailAST - OneTopLevelClass

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java, src/xdocs/config_annotation.xml
Issue #7573: update doc for MissingOverride
```xml
<module name="MissingOverride"/>
</module>
</module>
```
```java
class Test extends SuperClass {
/** {@inheritDoc} */
@Override
public void test1() { // OK
}
/** {@inheritDoc} */
public void test2() { // violation, should be annotated with &#64;Override
}
/** {@inheritDoc} */
private void test3() { // violation, using the @inheritDoc tag on private method that is not valid
}
/** {@inheritDoc} */
public static void test4() { // violation, using the @inheritDoc tag on static method …
```
=> Issue #7573: update doc for MissingOverride

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder7.java
Issue #7522 
Add support for using SuppressWarningsHolder with @SuppressWarnings as an annotation property
Examples of a valid code now
@CustomAnnotation(@SuppressWarnings("unchecked")) 
@Getter(onMethod_ = @SuppressWarnings("unchecked"))
Report
https://amrdeveloper.github.io/checkstyle-reports/7522/
=> Issue #7522: fix @SuppressWarnings as an annotation property exception

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java, src/xdocs/config_annotation.xml
Issue : https://github.com/checkstyle/checkstyle/issues/7574
Configuration
```
<module name="PackageAnnotation" />
</module>
</module>
```
Output with violation in MyClass.java
```
$ cat MyClass.java
@Deprecated
package com.example.annotations.packageannotation;
$ java -jar checkstyle-8.29-all.jar -c config.xml MyClass.java
[ERROR] /home/dunu008/GSOC/CHECKSTYLE-PROJECT/tests/MyClass.java:2: Package annotations must be in the package-info.java info. [PackageAnnotation]
Audit done.
``` …
=> Issue #7574 : Update doc for PackageAnnotation

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
Fixes Issue #7801 
Adds an UT for fixing the issue mentioned in https://github.com/checkstyle/checkstyle/issues/7801#issuecomment-597193539:
> ## 4. Regression and Code Logic Analysis
> Although the results of the regression report wasn't useful, I have discovered an UT by analysing the code which tests a particular edge case of `if(exclude.endsWith(".*")) `. The reason the absence of the if statement didn't break the test codes:
> `if(exclude.endsWith(".*"))` is redundant, since even if this check wasn't there and let's assume the exclude was a random member, it would yield true for the second condition but not for the first condition in `if (classOrStaticMember.startsWith(excludeMinusDotStar)&& !classOrStaticMember.equals(excludeMinusDotStar))`. and hence not move forward.
> 
> But if a …
=> Issue #7801: Resolve Pitest Issues - AvoidStaticImportCheck

.ci/wercker.sh, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #7190: remove deprecated setClassLoader methods
=> Issue #7190: remove deprecated setClassLoader methods

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/xdocs/config_coding.xml
**Issue #7638**
EqualsHashCode Check Doc Updation.
**Output of Example:**
```
<module name="EqualsHashCode"/>
</module>
</module>
public static class Example1 {
public int hashCode() {
// code
}
public boolean equals(String o) { // violation, overloaded implementation of 'equals'
// code
}
}
public static class Example2 {
public boolean equals(Object o) { // violation, no 'hashCode'
// code
}
public boolean equals(String o) {
// code
}
}
public static class Example3 {
public int hashCode() …
```
=> Issue #7638: Update doc for EqualsHashCode

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_MultiplePatternMultipleImport.java
In https://github.com/checkstyle/checkstyle/issues/7802#issuecomment-597470793 it was found that the current unit tests are not well-designed to kill the mutations produced by pitest. Copied here for reference:
> We already have unit tests in `CustomImportOrderCheckTest.java` that covers the different cases of regex matching, but the problem is that the input file is currently designed such that even if the test were to "fail" with the mutation, the output (violations) does not change, and so the tests incorrectly pass.
This PR aims to address that problem by enhancing the existing unit tests.
Pitest report for this branch: https://wltan.github.io/checkstyle-reports/2020-03-12/202003121402/
Both lines 815 and 816 no longer cause issues under pitest. It appears that this PR can solve both …
=> Issue #7802: Resolve Pitest Issues - CustomImportOrderCheck (1)

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionArrayTrailingCommaTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/arraytrailingcomma/SuppressionXpathRegressionArrayTrailingCommaOne.java, src/it/resources/org/checkstyle/suppressionxpathfilter/arraytrailingcomma/SuppressionXpathRegressionArrayTrailingCommaTwo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingComma.java, src/xdocs/config_filters.xml
Resolve #7723 : Update AbstractChecks to log DetailAST - ArrayTrailingComma
Diff report links :
- violation reported on rcurly (old) : https://wilcoln.github.io/checkstyle-reports/7723/diff/index.html
- violation reported on last item : https://wilcoln.github.io/checkstyle-reports/7723v2/diff/index.html
As expected/wanted, the number of violations reported remains the same for all projects. The only difference between the two diff reports are the lines and cols on which the violations are being found. Which is also completely normal.
=> Issue #7723: Update AbstractChecks to log DetailAST - ArrayTrailingComma

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java, src/xdocs/config_whitespace.xml
```
<module name="SingleSpaceSeparator">
</module>
</module>
</module>
public class test {
int foo()   { // violation, 3 whitespaces
return  1; // violation, 2 whitespaces
}
int fun1() { // OK, 1 whitespace
return 3; // OK, 1 whitespace
}
void  fun2() {} // violation, 2 whitespaces
}
$ java -jar checkstyle-8.30-all.jar -c config.xml test.java
[ERROR] C:\Users\Shrey\Desktop\PR1\test.java:2:17: Use a single space to separate non-whitespace characters. [SingleSpaceSeparator]
[ERROR] C:\Users\Shrey\Desktop\PR1\test.java:3:17: Use a single space to separate …
```
=> Issue #7629: Update doc for SingleSpaceSeparator

config/checkstyle_resources_suppressions.xml, src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/OuterTypeFilenameTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOuterTypeFilenameTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/outertypefilename/SuppressionXpathRegressionOuterTypeFilename1.java, src/it/resources/org/checkstyle/suppressionxpathfilter/outertypefilename/SuppressionXpathRegressionOuterTypeFilename2.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Issue #7755: Update AbstractChecks to log DetailAST - OuterTypeFilename
https://github.com/checkstyle/checkstyle/blob/0823da3cf1820603a155b5c8f14d5dfa63fe92b5/src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java#L118
Diff report:
https://huganghui.github.io/7755-DetailAST-outerTypeFilename/reports/diff/
=> Issue #7755: Update AbstractChecks to log DetailAST - OuterTypeFilename

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java
Issue #7800: Resolve Pitest Issues - AvoidStaticImportCheck(2)
As described as in #7800:
**Pitest report**
Link: https://huganghui.github.io/7800-AvoidStarImportCheck(2)/before-pit-reports/202003131405/
Surviving mutations:
on line 188: removed conditional - replaced equality check with false → SURVIVED I am focusing on it.
on line 224: removed conditional - replaced equality check with true → SURVIVED referenced by #7799, wilcoln is focusing on it.
**Hardcoded mutation**
mutation cs branch: https://github.com/HuGanghui/checkstyle/commit/1578ac0229711f39a4a7c77457f430491918cd57
comment:
Looking at the pitest report, we can see that the surviving mutation is the one for which removed conditional - replaced equality check with false → SURVIVED, this is equivalent as simply removing the …
=> Issue #7800: Resolve Pitest Issues - AvoidStarImportCheck(2)

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthUnicodeChars.java
This PR fixes Issue #5089, namely, `LineLength() `will now count codepoints (unicode characters) instead of 2 byte characters, thus correcting existing issue where unicode characters are counted as two, 2 byte characters.  I have added some test cases, and the diff report can be found [here](https://nmancus1.github.io/diff_3_13_2020/index.html).
=> Issue #5089: LineLength measures Java characters, not Unicode characters

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/xdocs/config_blocks.xml
Resolves #7584 
```
$ cat configRightCurlyDefault.xml
<module name="RightCurly"/>
</module>
</module>
$ cat RightCurlyDefault.java
public void test() {
if (foo) {
bar();
}           // violation, right curly must be in the same line as the 'else' keyword
else {
bar();
}
if (foo) {
bar();
} else {     // OK
bar();
}
if (foo) { bar(); } int i = 0;  // violation
// ^^^ statement is not allowed on same line after curly right brace
if (foo) { bar(); }            // OK
int i = 0;
try {
bar();
}           // violation, rightCurly must be in the same line …
```
=> Issue: #7584 add RightCurly example

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java
Resolve #7799
Please see comments in #7799 for all the details.
=> Issue #7799: Resolve Pitest Issues - AvoidStarImportCheck (1)

src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java, src/xdocs/config_misc.xml
Issue #7590: Update doc for OuterTypeFilename
Output of configure the check: 
```xml
<module name="OuterTypeFilename"/>
</module>
</module>
```
```java
public class Test { // OK
}
```
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java
Audit done.
```java
class Foo { // violation
}
```
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java
Starting …
=> Issue #7590: Update doc for OuterTypeFilename

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java, src/xdocs/config_whitespace.xml
Fixes Issue #7625 
**Default Example**
```
<module name="NoWhitespaceBefore">         
</module>
</module>
</module>
class Test {
void defaultTest() {
int foo;
foo ++; // violation, whitespace before '++' is not allowed
foo++; // OK
for (int i = 0 ; i < 5; i++) {}  // violation
// ^ whitespace before ';' is not allowed
for (int i = 0; i < 5; i++) {} // OK
int[][] array = { { 1, 2 }
, { 3, 4 } }; // violation, whitespace before ',' is not allowed
int[][] array2 = { { 1, 2 },
{ 3, 4 } }; // OK
Lists.charactersOf("foo").listIterator() …
```
=> Issue #7625: Updated doc for NoWhiteSpaceBefore

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java, src/xdocs/config_coding.xml
fixes #7636 
**Output for default example**
````
<module name="DefaultComesLast">
</module>
</module>
</module>
void method(int i) {
switch (i) {
case 1:
break;
case 2:
break;
default: // OK
break; 
}
switch (i) {
case 1:
break;
case 2:
break; // OK, no default
}
switch (i) {
case 1:
break;
default: // violation, 'default' before 'case'
break;
case 2:
break;
}
switch (i) {
case 1:
default: // violation, 'default' before 'case'
break;
case 2:
break;
}
}
} …
```
=> Issue #7636: Update doc for DefaultComesLast

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavadocStyleTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/javadocstyle/SuppressionXpathRegression/package-info.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Issue #7740: Update AbstractChecks to log DetailAST - JavadocStyle
Diff report (finally here!): https://wltan.github.io/checkstyle-reports/2020-03-18/javadocstyle-detailast-regression/diff/
Discrepancies observed are due to logging column number where we previously did not.
Note that although there are seven calls to `log` as highlighted in https://github.com/checkstyle/checkstyle/issues/7740#issuecomment-599047248, this PR only fixes one of them as instructed in https://github.com/checkstyle/checkstyle/issues/7740#issuecomment-599061545. Please see the discussion on that thread for more details.
=> Issue #7740: Update AbstractChecks to log DetailAST - JavadocStyle

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionImportOrderTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/importorder/SuppressionXpathRegressionImportOrderFive.java, src/it/resources/org/checkstyle/suppressionxpathfilter/importorder/SuppressionXpathRegressionImportOrderFour.java, src/it/resources/org/checkstyle/suppressionxpathfilter/importorder/SuppressionXpathRegressionImportOrderOne.java, src/it/resources/org/checkstyle/suppressionxpathfilter/importorder/SuppressionXpathRegressionImportOrderThree.java, src/it/resources/org/checkstyle/suppressionxpathfilter/importorder/SuppressionXpathRegressionImportOrderTwo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Fixes issue #7733 
**Updates(total 5 log calls):**
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L666
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L673
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L676
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L738 …
=> Issue #7733: Update AbstractChecks to log DetailAST - ImportOrder

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
Resolves #7805 and #7803 
As mentioned in https://github.com/checkstyle/checkstyle/issues/7805#issuecomment-601250261 , there were no differences and no UTs were suggested in the diff report (https://github.com/checkstyle/checkstyle/issues/7805#issuecomment-600638693) and observed no other way to fix the issue.
Removing the condition was the only approach. The surviving mutation referred to by #7803 is also killed by this approach.
=> Issue #7805: Resolve Pitest Issues - CustomImportOrderCheck (4)

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheck.java, src/xdocs/config_design.xml
Issue #7612: Update doc for InterfaceIsType
```xml
<module name="InterfaceIsType"/>
</module>
</module>
```
```java
public interface Test1 { // violation
int a = 3;
}
interface Test2 { // OK
}
interface Test3 { // OK
int a = 3;
void test();
}
```
$ RUN_LOCALE="-Duser.language=en -Duser.country=US"
$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java
[ERROR] /var/tmp/Test.java:1: interfaces should describe a type and hence have methods. [InterfaceIsType]
Audit done.
Checkstyle …
=> Issue #7612: Update doc for InterfaceIsType

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java
Fixes issue #7920 
This mutation was surviving `removed conditional - replaced equality check with true → KILLED` at line no 120.
If `pkgName` is null it means this is an unnamed package and as an unnamed package cannot be imported we don't need to check if the `pkgName` is null as the second condition will return false.
=> Issue #7920: Resolve Pitest Issues - RedundantImportCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java, src/xdocs/config_annotation.xml
Issue : https://github.com/checkstyle/checkstyle/issues/7569
1. Default Configuration
```$ cat config.xml
<module name="AnnotationLocation" />
</module>
</module>
```
```
$ cat testone.java
public class testone{
@NotNull private boolean field1; //ok
@Override public int hashCode() { return 1; } // ok
@NotNull //ok
private boolean field2;
@Override //ok
public boolean equals(Object obj) { return true; }
@Mock DataLoader loader; // ok
@SuppressWarnings("deprecation") DataLoader loader; // violation
@SuppressWarnings("deprecation") public int foo() { …
```
=> Issue #7569: Update doc for AnnotationLocation to have config first and code sample after

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java, src/xdocs/config_whitespace.xml
Default examples:
```
<module name="NoLineWrap"/>
</module>
</module>
$ cat test.java 
package com.puppycrawl.tools.checkstyle. //violation
checks.whitespace;
import java.lang.Object; // OK
import java.lang. // violation
Integer;
import static java.math. // violation
BigInteger.TEN;
$ java -jar checkstyle-8.30-all.jar -c config.xml test.java 
[ERROR] /home/shrey/Desktop/CheckstyleJar/test.java:1: package statement should not be line-wrapped. [NoLineWrap]
[ERROR] /home/shrey/Desktop/CheckstyleJar/test.java:5: import statement should not be line-wrapped. [NoLineWrap]
[ERROR] …
```
=> Issue #7623: Update doc for NoLineWrap

src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java, src/xdocs/config_regexp.xml
This fixes #7697 
```
<module name="RegexpSingleline">
<property name="format" value="System.exit\("/>
<property name="minimum" value="0"/>
<property name="maximum" value="1"/>
</module>
</module>
$ cat MyClass.java
void myFunction() {
try{
doSomething();
} catch (Exception e) {
System.exit(1); // OK, as only there is only one occurrence.
} 
}
void doSomething() {};
}
$ java -jar checkstyle-8.29-all.jar -c config.xml MyClass.java
Audit done.
$ cat MyClass.java
void myFunction() {
try {
doSomething();
System.exit(0);
} catch (Exception e) { …
```
=> Issue: #7697 update doc for RegexpSingleline

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavadocContentLocationTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/javadoccontentlocation/SuppressionXpathRegressionJavadocContentLocationOne.java, src/it/resources/org/checkstyle/suppressionxpathfilter/javadoccontentlocation/SuppressionXpathRegressionJavadocContentLocationTwo.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Issue resolves #7738 .
(Default Config):
https://harsh-kukreja.github.io/diff%20report%20default%20config/diff/
(Config with location of first_line):
https://harsh-kukreja.github.io/diff%20report%20first_line%20config/diff/
Update AbstractChecks to log DetailAST - JavadocContentLocation
=> Issue: #7738 Update AbstractChecks to log DetailAST - JavadocContentLocation 

.ci/jsoref-spellchecker/whitelist.words, .ci/wercker.sh, wercker.yml
See https://github.com/pgjdbc/pgjdbc/pull/1726#issuecomment-594643435
when https://github.com/pgjdbc/pgjdbc/pull/1627 is merged this PR be ready for merge.
=> infra: pgjdbc, migrate Maven -> Gradle

src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java, src/xdocs/config_misc.xml
Fixes issue #7589 
Screenshot
1. Check with default config
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ cat conifg.xml
<module name="NewlineAtEndOfFile"/>
</module>gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ java -jar target/checkstyle-8.31-SNAPSHOT-all.jar -c conifg.xml Test.java
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:1: File does not end with a newline. [NewlineAtEndOfFile]
Audit done.
```
2. Check with lineSeparator config
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open …
```
=> Issue #7589: Update doc for NewlineAtEndOfFile

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAnnotationUseStyleTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleEight.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleFive.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleFour.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleOne.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleSeven.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleSix.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleThree.java, src/it/resources/org/checkstyle/suppressionxpathfilter/annotationusestyle/SuppressionXpathRegressionAnnotationUseStyleTwo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java, src/xdocs/config_filters.xml
Resolve #7722: Update AbstractChecks to log DetailAST - AnnotationUseStyle
Diff report : https://wilcoln.github.io/checkstyle-reports/7722/diff/index.html
I ran regression on all projects and the diff report was so huge (1.2Gb+)  that  `git add` was taking forever to run. Beside, i'm not sure that github will allow me to upload such a load. So I've decided to host detailed reports for only the 8 first projects.
The number of violations **has increased** as there are often multiple violations on same line.
For example in the **apache-struts** project, [this file](https://github.com/apache/struts/blob/master/core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultObjectTypeDeterminer.java) contains two violations on line [71](https://github.com/apache/struts/blob/9053c84d505dfbcca0 …
=> Issue #7722: Update AbstractChecks to log DetailAST - AnnotationUseStyle

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderContainerOrdering.java
Resolves Issue #7874: Resolve Pitest Issues - ImportOrderCheck (3)
PiTest Report, ran before changes, showing surviving mutation:
https://nmancus1.github.io/Issue-7874/com.puppycrawl.tools.checkstyle.checks.imports/ImportOrderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@7ea147e3_820
Surviving mutation: `removed conditional - replaced equality check with false → SURVIVED`
PiTest Report, ran after changes, to show mutation was killed (updated):
https://nmancus1.github.io/Issue-7874/pitest_3/202003292351/com.puppycrawl.tools.checkstyle.checks.imports/ImportOrderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@2a2271dc_820
=> Issue #7874: Resolve Pitest Issues - ImportOrderCheck (3)

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/xdocs/config_filters.xml
As for now Indentationcheck support for XpathSuppression is not supported till the [Issue #7734 ](https://github.com/checkstyle/checkstyle/issues/7734) is resolved.
PR is made in support of following comment https://github.com/checkstyle/checkstyle/issues/7734#issuecomment-602221021
Updated site screenshot :
=> doc: update IndentationCheck note for SuppressionXpathFilter

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java, src/xdocs/config_whitespace.xml
Fix for issue #7626 
Website changes
CLI Output:
```
Karunas-MacBook-Pro:checkstyle Harsh$ cat config.xml 
<module name="OperatorWrap"/>
</module>
</module>Karunas-MacBook-Pro:checkstyle Harsh$ cat Test.java
class Test {
String s = "Hello" +
"World"; // violation, '+' should be on new line
if (10 ==
20) { // violation, '==' should be on new line.
// body
}
if (10
==
20) { // ok
// body
}
int c = 10 /
5; // violation, '/' should be on new line.
int d = c
+ 10; // ok
}
}Karunas-MacBook-Pro:checkstyle Harsh$ java -jar …
```
=> Issue #7626: Update doc for OperatorWrap

.ci/jsoref-spellchecker/whitelist.words, .ci/pitest.sh, config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingWhitespaceAfterAsteriskCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingWhitespaceAfterAsteriskCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskInvalid.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskValid.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskValidWithTab.java, src/xdocs/checks.xml, src/xdocs/config_filters.xml, src/xdocs/config_javadoc.xml
Issue #7183
Contribution PR:
checkstyle/contribution#454
https://github.com/checkstyle/contribution/pull/454 (this link was added to satisfy `verify-no-exception-configs` build item)
https://0blivious.github.io/7183/index.html
Old regression report
https://0blivious.github.io/index.html
Sevntu-checkstyle PR (merged)
https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/806
Checkstyle PR
https://github.com/checkstyle/checkstyle/pull/7883
=> Issue #7183: add JavadocMissingWhitespaceAfterAsteriskCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java, src/xdocs/config_whitespace.xml
Update doc for WhitespaceAround.
Solves issue: #7632 
**CLI TEST RESULT:**
Default Config: 
```
Karunas-MacBook-Pro:checkstyle Harsh$ cat config.xml 
<module name="WhitespaceAround"/>
</module>
</module>
Karunas-MacBook-Pro:checkstyle Harsh$ cat Test.java 
class Test {
public Test(){} // 2 violations, '{' is not followed and preceded by whitespace.
if (foo) { // ok
// body
}
else{ // violation
// body
}
for (int i = 1; i > 1; i++) {} // violation, '{' is not followed by whitespace.
Runnable noop = () ->{}; // 2 violations,
// '{' is not followed …
```
=> Issue #7632: Update doc for WhitespaceAround

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/xdocs/config_javadoc.xml
Fixes issue #7599 
Screenshot:
1. Default check
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ cat config.xml
<module name="JavadocStyle">
</module>
</module>
</module>gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ java -jar target/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:7: First sentence should end with a period. [JavadocStyle]
Audit done.
```
2. Check for public scope
``` …
```
=> Issue #7599: update doc for JavadocStyle

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
Fixes #7982 
This mutation `replaced equality check with true` was surviving  on condition 
`if(message == null)` in method `RegexpCheck@setMessage()`.
Killed the mutation by removing the condition `message == null`
The member `message` is only used in one method `logMessage` and in that method, we are already null checking member `message` as shown below
```
if (message == null || message.isEmpty()) {
msg = format.pattern();
}
```
This makes our null check in `setMessage()` useless, hence removing this condition won't affect any functionality or test case and would kill the mutation.
=> Issue #7982: Resolve Pitest Issues - RegexpCheck (1)

appveyor.yml
Issue #7969 
JDK13 is no more supported, we are moving to jdk14.
AppVeyor image upgraded from Windows Server 2012 to Windows Server 2019.
We have no files with jdk13 specific syntax, so travis stage `javac13` can be replaced with `javac14` too.
=>  Issue #7969: upgrade AppVeyor build image to VS2019 

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java, src/xdocs/config_design.xml
Fixes #7610
```
$ cat config3.xml
<module name="HideUtilityClassConstructor">
</module>
</module>
</module>
$ cat Test3.java
class Test { // violation, class only has a static method and a constructor
public Test() {
}
public static void fun() {
}
}
class Foo { // OK
private Foo() {
}
static int n;
}
class Bar { // OK
protected Bar() {
// prevents calls from subclass
throw new UnsupportedOperationException();
}
}
class UtilityClass { // violation, class only has a static field
static float f;
}
$ java -jar checkstyle-8.30-all.jar -c config3.xml Test3.java
[ERROR] …
```
=> Issue #7610: Update doc for HideUtilityClassConstructor

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheck.java, src/xdocs/config_whitespace.xml
Fixes #7630
Default example:
```
<module name="TypecastParenPad">
</module>
</module>
</module>
class Foo {
float f1 = 3.14f;
int n = ( int ) f1; // violation, space after left parenthesis and before right parenthesis
double d = 1.234567;
float f2 = (float ) d; // violation, space before right parenthesis
float f3 = (float) d; // OK
float f4 = ( float) d; // violation, space after left parenthesis
}
$ java -jar checkstyle-8.30-all.jar -c config.xml Test.java
[ERROR] C:\Users\Shrey\Desktop\Checkstyle jar\Test.java:5:11: '(' is followed by whitespace. …
```
=> Issue #7630: Update doc for TypecastParenPad

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/xdocs/config_design.xml
Fixes #6745 
As mentioned in https://github.com/checkstyle/checkstyle/issues/6745#issuecomment-605467069 I would also like to reduce the amount of bold formatting used in this section. The site now looks like this:
=> Issue #6745: Improve VisibilityModifier documentation

.ci/appveyor.bat, .ci/travis/travis.sh, .travis.yml, appveyor.yml
Issue #7969
JDK13 is no more supported, we are moving to jdk14.
Except the OSX build, since an xcode image with jdk14 for OSX is not released yet.
We have no files with jdk13 specific syntax, so travis stage javac13 can be safely replaced with javac14.
=> Issue #7969: drop jdk13 build, add jdk14 build

.ci/jsoref-spellchecker/whitelist.words, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/xdocs/config_coding.xml
Fixes: #7647 
**default:**
```
<module name="IllegalType">
</module>
</module>
</module>
public class Test extends TreeSet { // violation
public <T extends java.util.HashSet> void method() { // violation
LinkedHashMap<Integer, String> lhmap = new LinkedHashMap<Integer, String>(); // violation
TreeMap<Integer, String> treemap = new TreeMap<Integer, String>(); // violation
Test t; // OK
HashMap<String, String> hmap; // violation
Queue<Integer> intqueue; // OK …
```
=> Issue #7647: Update doc for IllegalType

pom.xml
such violations become stable - https://app.codeship.com/projects/124310/builds/9e4691e7-7cc7-4797-8609-7df2a52cae60?line=fc257935-fc3d-490c-9a0b-ce08e96fbbfb&step=parallel_.ci%2Frun-link-check-plugin.sh
```
2020-04-12 10:14:35
system ------------ grep of linkcheck.html--BEGIN
2020-04-12 10:14:35
system <td><i><a class="externalLink" href="https://www.bountysource.com/">
https://www.bountysource.com/</a>: java.net.SocketTimeoutException : 
Read timed out</i></td></tr></table></td></tr>
2020-04-12 10:14:35
system <td><i><a class="externalLink" 
href="https://api.bountysource.com/badge/team?team_id=3568&amp;amp;style=bounties_posted">
https://api.bountysource.com/badge/team?team_id=3568&amp;amp;style=bounties_posted</a>: java.net.SocketTimeoutException : Read timed out</i></td></tr> …
```
=> Suppress few links to make codeship green

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMissingJavadocMethodTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadocmethod/SuppressionXpathRegressionMissingJavadocMethod1.java, src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadocmethod/SuppressionXpathRegressionMissingJavadocMethod2.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Resolves #7745 
Diff report: https://shashwat70.github.io/diff3/index.html
Diff is empty as the check was already logging DetailAST node.
=> Issue #7745: Integration tests added for MissingJavadocMethod

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderEmptyRule.java, src/xdocs/config_imports.xml
Fix #7128 
The documentation mistakenly shows the default value to be an empty set `{}` when it should be the empty string `""`. This led to some confusion in #7128 when the user thought that they could use `{}` as the default value.
This PR aims to fix the two points brought up in https://github.com/checkstyle/checkstyle/issues/7128#issuecomment-544254686:
1. Documentation is now updated to show `""` instead of `{}`
2. `setCustomImportOrderRules` now checks if `inputCustomImportOrder` is empty, and will not modify `customImportOrderRules` at all if it is the case.
Diff report: https://wltan.github.io/checkstyle-reports/2020-03-18/customimport-defaultrule-regression/diff/
=> Issue #7128: customImportOrderRules does not support the default value

src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromJavaLang.java
This is the only change required to compile Checkstyle with JDK15.
One test input should be updated since `java.lang.reflect.Modifier` ctor was removed in
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8230723
=> minor: update test inputs for JDK15

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheck.java, src/xdocs/checks.xml, src/xdocs/config_coding.xml
Fix for #7672 
Output of default example (invalid):
```
<module name="Checker" >
<module name="OverloadMethodsDeclarationOrder" />
</module>
</module>
$ cat MyClass.java 
public class MyClass{
public void foo(int i) {} //OK
public void foo(String s) {} //OK
public void notFoo() {} // violation. Have to be after foo(String s, int i)
public void foo(int i, String s) {}
public void foo(String s, int i) {}
}
$ java -jar checkstyle-8.30-all.jar -c config.xml MyClass.java
[ERROR] /Users/guneshi/github/test/MyClass.java:5: Overload methods should not be split. Previous overloaded …
```
=> Issue #7672:Updated doc for OverloadMethodsDeclarationOrder

src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java, src/xdocs/config_filters.xml
Fixes #7179 
Updated docs as per the respective parent module of each filter under the "Notes" section.
Example of filter which did not have a "Notes" section earlier: (contains a typo, which is fixed via commit)
Example of filter which had a "Notes" section earlier:
=> Issue #7179: Update docs of filters to indicate level in the tree

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java, src/xdocs/config_whitespace.xml
Fixes #7628
```
<module name="SeparatorWrap">
</module>
</module>
</module>
import java.io.
IOException; // OK
class Test {
String s;
public void foo(int a,
int b) { // OK
}
public void bar(int p
, int q) { // violation, separator comma on new line
if (s
.isEmpty()) { // violation, separator dot on new line
}
}
}
$ java -jar checkstyle-8.30-all.jar -c config.xml Test.java
[ERROR] C:\Users\Shrey\Desktop\Checkstyle jar\Test.java:13:21: ',' should be on the previous line. [SeparatorWrap]
[ERROR] C:\Users\Shrey\Desktop\Checkstyle …
```
=> Issue #7628: Update doc for SeparatorWrap

.ci/idea_inspection.bat, .ci/shippable.sh, .ci/sonar.sh, .ci/wercker.sh, .circleci/config.yml, .travis.yml, Jenkinsfile
Identified at https://github.com/checkstyle/checkstyle/pull/8099#issuecomment-613768780 ,
I made sure all maven commands print the stack trace so we can look at and identify any issues in any maven commands.
I ensured all maven commands were covered by running the regular expression `(mvn [^-])|(mvn \-[^e])` and ensure nothing besides `mvn --version` showed up.
=> config: ensured all maven commands print the stack  trace

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
**Fixes** #7922
**Reports:** https://github.com/checkstyle/checkstyle/issues/7922#issuecomment-604274485
The only property requiring the ```currentClassName``` variable is ```validateThrows```. As can be seen in the code:
https://github.com/checkstyle/checkstyle/blob/834b505b9938e93f6950dd20a13e39e295e5ac86/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L485
which further calls ```getThrows``` and ```getThrowed``` method both requiring the ```currentClassName``` variable.
However, once we get the ```classInfo``` by this ```currentClassName``` variable, it calls ```checkThrowsTags``` method:
https://github.com/checkstyle/checkstyle/blob/834b505b9938e93f6950dd20a13e39e295e5ac86/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodChe …
=> Issue #7922: Resolve Pitest Issues - JavadocMethodCheck (1)

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/xdocs/config_javadoc.xml
fixes #7600 
Website view:
Default config:
```
<module name="JavadocTagContinuationIndentation">
</module>
</module>
</module>
/**
* @tag comment..
*  Indentation spacing is 1 (violation)
*   Indentation spacing is 2 (violation)
*     Indentation spacing is 4 (OK)
*/
}
kaustubh@dxtk:~$ java -jar checkstyle-8.30-all.jar -c Test.xml Test.java
[ERROR] /home/kaustubh/Test.java:3: Line continuation have incorrect indentation level, expected level should be …
```
=> Issue #7600: Update doc for JavadocTagContinuationIndentation

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
Minor spelling fix `expectionInfo` -> `exceptionInfo`
From https://github.com/checkstyle/checkstyle/pull/7955#discussion_r409555197
=> minor: Fix typo in JavadocMethodCheck

src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNode.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
Resolves #6988 
Extending the work and implementing @rnveach's sort criteria discussed in PR #7485.
Example from: https://github.com/checkstyle/checkstyle/pull/7485#discussion_r373855071
```
public class test {
void method() {
}
}
```
Before:
```
$  java -jar checkstyle-8.29-all.jar -b "//CLASS_DEF/*" test.java 
|--IDENT -> test [1:13]
---------
---------
---------
```
After:
```
$ java -jar checkstyle-8.31-SNAPSHOT-all.jar -b "//CLASS_DEF/*" test.java
--------- …
```
=> Issue #6988: Sort XPath Results in Document Order

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnore.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreFinal.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreFinalKeepStaticFinal.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreNonStaticFinal.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreStatic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreStaticFinal.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreStaticKeepStaticFinal.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameNoIgnore.java, src/xdocs/config_naming.xml
Issue #6582: static final option for AbbreviationAsWordInName
Currently, we are able to ignore `static` fields and `final` fields separately, but have no way to ignore only variables that are both `static` and `final`, which are usually (but not necessarily) constants.
I have added a new property `ignoreStaticFinal` to the check. The default value is `true` so that anyone running the default configuration (i.e. `ignoreStatic` and `ignoreFinal` both true) will not notice any difference in violations as a result of this change.
Note however that a `static final` variable will only respect `ignoreStaticFinal` and not `ignoreStatic` or `ignoreFinal`. For example, if `ignoreStatic` is false but `ignoreStaticFinal` remains true, only `static` and non-`final` variables will be ignored.
An …
=> Issue #6582: static final option for AbbreviationAsWordInName

src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/before.FileText.java.html
After Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/optimal.FileText.java.html
Submited Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FileText.java.html
@romani 
I'll take this opportunity to suggest that some users might want constructors to be the first methods defined in class .Thus, it might be relevant to count penalty for every constructor defined below a non-constructor method.
Currently, there is no such criterion defined in the method-distance repo, this is why, in this case, …
=> minor: Optimize method distance in checkstyle.api.FileText

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPackageDeclarationTest.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packagedeclaration/SuppressionXpathRegression1.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packagedeclaration/SuppressionXpathRegression2.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_coding.xml, src/xdocs/config_filters.xml
fixes: #7758 
This check partially supports Xpath.
Two log calls:
https://github.com/checkstyle/checkstyle/blob/676dc23d4f239e1b3f57b5cdce043067d8c996e5/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java#L147
https://github.com/checkstyle/checkstyle/blob/676dc23d4f239e1b3f57b5cdce043067d8c996e5/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java#L163
Due to certain reason(https://github.com/checkstyle/checkstyle/issues/7758#issuecomment-604070675), I had to provide one more log call when AST is null.
Diff report: https://dxtkastb.github.io/checkstyle/reports/packed/diff2/index.html
**Changes in Documentation:**
Under Check documentation:
------------------------------------------------------------------------------- …
=> Issue #7758: Update AbstractChecks to log DetailAST - PackageDeclaration

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheck.java, src/xdocs/config_coding.xml
Fix #7811: upadate doc of AvoidDoubleBraceInitialization to make example compilable
- The old example was using raw type `List` for no apparent reason, so I updated it to a more 'standard' usage.
- Examples have been re-indented to +4 spaces per level. Previously there was an inconsistency in the second example some lines were +3 instead.
- The explanation comments were moved around or tweaked slightly due to the line length limit.
Note that import statements were added to make the input files compilable, but it is omitted in documentation for the site.
Example 1:
```
<property …
```
=> Issue #7811: Update doc of AvoidDoubleBraceInitialization

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
Mentioned at #8062
https://github.com/checkstyle/checkstyle/pull/8062#discussion_r410964302
=> minor: Incorrect javadoc for JavadocStyleCheck's message property keys

config/suppressions.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterBad.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAfterGood.java, src/main/resources/google_checks.xml, src/xdocs/config_whitespace.xml, src/xdocs/google_style.xml
Closes #5624: Google Style Should Enforce Spaces after Commas
Diff report: https://shashwat70.github.io/diff2/index.html
=> Issue #5624: Google Style Should Enforce Spaces after Commas

config/checkstyle_non_main_files_checks.xml, config/checkstyle_non_main_files_suppressions.xml
This resolves #7987 
use ```@Test``` occurrences in the test files in suppressionxpathfilter directory to validate the number of test cases written.
```
public class XpathRegressionAnonInnerLengthTest extends AbstractXpathTestSupport {
private final String checkName = AnonInnerLengthCheck.class.getSimpleName();
@Override
protected String getCheckName() {
return checkName;
}
@Test
public void testMaxLength() throws Exception {
final int maxLen = 5;
final File fileToProcess =
new File(getPath("SuppressionXpathRegressionAnonInnerLength.java"));
final DefaultConfiguration moduleConfig =
createModuleConfig(AnonInnerLengthCheck.class);
moduleConfig.addAttribute("max", String.valueOf(maxLen));
final String[] expectedViolation = {
"7:41: " + getCheckMessage(AnonInnerLengthCheck.class, …
```
=> Issue #7987: use RegexpSingleline Check to validate amount of tests in Xpath tests

src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java, src/xdocs/config_regexp.xml
Issue #7696: update doc for RegexpOnFilename
**For default configuration**
config.xml
```
<!DOCTYPE module PUBLIC 
<module name="RegexpOnFilename"/>
</module>
```
Results
```
F:\College\Checkstyle Jar>java -jar checkstyle-8.30-all.jar -c config.xml src/xdocs/"config regexp.xml"
[ERROR] F:\College\Checkstyle Jar\src\xdocs\config regexp.xml:1: File match folder pattern '' and file pattern '\s'. [RegexpOnFilename]
Audit done.
```
**For custom configurations**
config.xml
```
<?xml version="1.0"?>                                            …
```
=> Issue: #7696 update doc for RegexpOnFilename

config/checkstyle_non_main_files_suppressions.xml, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAnonInnerLengthTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/anoninnerlength/SuppressionXpathRegressionAnonInnerLengthDefault.java
Resolves issue #8151 
Added a defaul config test in `XpathRegressionAnonInnerLengthTest`.
=> Issue #8151: Update XpathRegressionAnonInnerLengthTest to have atleast 2 tests

src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAfterTest.java
I missed this at #7988
Realized this when I took another look at my recently merged PR.
Just a minor consistency issue.
=> minor: Empty string array replaced

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheck.java, src/xdocs/config_design.xml
Fixes #7611 
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ cat config.xml
<module name="InnerTypeLast"/>
</module>
</module>gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ java -jar target/checkstyle-8.32-SNAPSHOT-all.jar -c config.xml Test.java
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:4:5: Fields and methods should be before inner classes. [InnerTypeLast]
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:16:5: Fields and methods should be before inner classes. [InnerTypeLast] …
```
=> Issue #7611: Update doc for InnerTypeLast

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java, src/xdocs/config_whitespace.xml
Fixes #7627
```
$ cat config1.xml
<module name="ParenPad">
</module>
</module>
</module>
$ cat Test1.java
class Foo {
int n;
public void fun() {  // OK
bar( 1);  // violation, space after left parenthesis
}
public void bar(int k ) {  // violation, space before right parenthesis
while (k > 0) {  // OK
}
Test obj = new Test(k);  // OK
}
public void fun2() {  // OK
switch( n) {  // violation, space after left parenthesis
case 2:
bar(n);  // OK
default:
break;
}
}
}
$ java -jar ../checkstyle-8.30-all.jar -c config1.xml Test1.java
[ERROR] C:\Users\Shrey\Desktop\Checkstyle …
```
=> Issue #7627: Update doc for ParenPad

appveyor.yml, config/checkstyle_non_main_files_checks.xml
Issue #8118: Enforce -e for all maven commands
I add RegexpSingleline to finish this task and I change 
```java
(mvn [^-])|(mvn \-[^e])
```
to 
```java
(mvn [^-])|(mvn \-[^e\-v])
```
to avoid false positive on 
```java
mvn --version
mvn -version
```
=> Issue #8118: Enforce -e for all maven commands

config/checkstyle_non_main_files_checks.xml, config/checkstyle_resources_checks.xml, config/checkstyle_sevntu_checks.xml, pom.xml
Fixes #8168 
1. Removed `cacheFile` property from `config/checkstyle_sevntu_checks.xml`.
2. Removed false comments from other configurations, as discussed in this comment https://github.com/checkstyle/checkstyle/issues/8168#issuecomment-617875015 .
3. Modified configuration of plugin to have the name of config file as `cache_sevntu`
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ mvn clean install
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
..........
[INFO] …
```
=> Issue #8168: remove from configs hardcode caused by MCHECKSTYLE-33

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/xdocs/config_naming.xml
Fix #7566 
Although the title of the issue only asks for "default config example", there is one more property `ignoreOverriddenMethods` that was not covered by existing examples, so I've added that in as well.
The two examples added:
```
<property name="severity" value="error"/>
<module name="AbbreviationAsWordInName"/>
</module>
</module>
D:\checkstyletest>type test\*.java 
public class MyClass extends SuperClass { // OK, camel case
int CURRENT_COUNTER; // violation, at most 4 consecutive capital letters allowed
static int GLOBAL_COUNTER; // OK, static is …
```
=> Issue #7566: Add default config example for AbbreviationAsWordInName

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java, src/xdocs/config_javadoc.xml
Fixes #7603 
1. Check with default config
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ cat check.xml
<module name="MissingJavadocMethod"/>
</module>
</module>gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ java -jar target/checkstyle-8.32-SNAPSHOT-all.jar -c check.xml Test.java
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:2:3: Missing a Javadoc comment. [MissingJavadocMethod]
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:3:3: Missing a Javadoc comment. [MissingJavadocMethod]
Audit …
```
=> Issue #7603: Update doc for MissingJavadocMethod
