- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/427828508#L1162
> config: bump jgit to 5.0.3.201809091024-r

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for CatchParameterName

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
- src/xdocs/config_imports.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/config_modifier.xml
- src/xdocs/index.xml.vm
- src/xdocs/releasenotes_old.xml
- src/xdocs/sun_style.xml
- src/xdocs/writinglisteners.xml.vm
due to failres at https://app.codeship.com/projects/124310/builds/f594dafb-cbdf-4e01-b70e-77fc0bd497a8
as https://app.codeship.com/projects/124310/builds/72b0cf8d-ba0b-41ce-b5fd-dbc6b1e9e84b pass , should be ok to merge
> minor: change oracle.com links to use https

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L2915
> config: bump jgit to 5.1.2.201810061102-r

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L2941
> config: bump maven-shade-plugin to 3.2.0

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L2954
> config: bump sonar-maven-plugin to 3.5.0.1254

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L2980
> config: bump forbiddenapis to 2.6

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L2968
> config: bump pitest to 1.4.3

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L2993
> config: bump maven-failsafe-plugin to 2.22.1

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/442841783#L3006
> config: bump maven-surefire-plugin to 2.22.1

- config/pmd.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeExtendsImplements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeGenerics.java
- src/xdocs/config_coding.xml
Issue #6118 
This PR brings a violation for any attempt to extend a banned class/interface
```
pubic class Bar extends ForbiddenClass {} // violation
```
regression tests:
https://pbludov.github.io/issue-6118a/
> Issue #6118: IllegalType should check extends & implements

- src/xdocs/config_imports.xml
> Issue #5510: fixes ImportOrder example for IntelliJ IDEA

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/445829260#L2916
> config: bump jgit to 5.1.3.201810200350-r

- release.sh
…without looking to script file
I simply ignored rule of thumb - no comment in code and code should be read as text .
this update will help to understand output and clearly define in output what is running.
> minor: converting commments to code to make it clear what is running

- .ci/wercker.sh
- wercker.yml
> Issue #6167: Add equalsverifier project to wrecker ci

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/449014145#L2879
> config: bump equalsverifier to 3.0.2

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/449014145#L2891
> config: bump maven-pmd-plugin to 3.11.0

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/449014145#L2862
> config: bump guava to 27.0-jre

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeMemberModifiers.java
> Issue #6123: ignore parameters of methods with modifiers not in 'memberModifiers'

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/452041949#L2857
> config: bump spotbugs-maven-plugin to 3.1.8

- .ci/jsoref-spellchecker/whitelist.words
- config/version-number-rules.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XpathUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
https://github.com/checkstyle/checkstyle/issues/6149
> config: update to saxon 9.9

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/455142812#L2861
> config: bump maven-shade-plugin to 3.2.1

- .github/CONTRIBUTING.md
> Issue #5488: Created contributing.md

- pom.xml
> Issue #6213: warning during build of site with equalsverifier-3.0.2

- .ci/wercker.sh
Revert for Issue https://github.com/checkstyle/checkstyle/issues/6218
> Revert "config: fix wercker CI, see details at #6218"

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/458092683#L2848
> config: bump system-rules to 1.19.0

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/458092683#L2861
> config: bump guava to 27.0.1-jre

- .ci/test-spelling-unknown-words.sh
- config/ant-phase-verify.xml
- config/checkstyle_non_main_files_suppressions.xml
previous PR: https://github.com/checkstyle/checkstyle/pull/6227
it is not first time I have:
`[checkstyle] [ERROR] ....checkstyle/checkstyle/.ci/jsoref-spellchecker/english.words:1: File does not end with a newline. [NewlineAtEndOfFile]`
```
main:
execute:
[echo] Checkstyle started (checkstyle_checks.xml): 23/11/2018 06:55:40 AM
[checkstyle] Running Checkstyle  on 1012 files
[echo] Checkstyle finished (checkstyle_checks.xml) : 23/11/2018 06:55:41 AM
[echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 23/11/2018 06:55:40 AM
[checkstyle] Running Checkstyle  on 1641 files
[checkstyle] [ERROR] ....checkstyle/checkstyle/.ci/jsoref-spellchecker/english.words:1: File does not end with a newline. [NewlineAtEndOfFile]
```
> Minor skip file

- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
Issue #6096
continuation from: https://github.com/checkstyle/checkstyle/pull/6097
> Issue #6096: improve performance with not lazy usage of file.lastModified()

- config/intellij-idea-inspections.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
> Issue #6241: suppress CanBeFinal inspection on picocli options as it use reflection

- src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java
> Issue #6262: removed namespace aware from XmlLoader

- .ci/jsoref-spellchecker/whitelist.words
- .ci/pitest.sh
- .circleci/config.yml
- config/ant-phase-verify.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/XmlLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListener.java
- src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAuditListenerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserHiddenComments2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/xpathfilegeneratorastfilter/InputXpathFileGeneratorAstFilter.java
Issue #4684
SuppressWarningsHolder was not added since it is listed in pitest as a comment.
> Issue #4684: added missing classes to pitest

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/467147401#L2850
> config: bump picocli to 3.8.2

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/467147401#L2850
> config: bump jgit to 5.2.0.201812061821-r

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/467147401#L2850
> config: bump maven-jar-plugin to 3.1.1

- .ci/wercker.sh
continuation of https://github.com/checkstyle/checkstyle/pull/6266
> config: update xwiki to address issue of pull #6266

- src/xdocs/index.xml.vm
https://app.codeship.com/projects/67b814a0-8fee-0133-9b59-02a170289b8c/builds/f3d57918-f92a-44c6-a87c-8e972ba12cfc?line=0e134d18-42a9-44af-9815-a16d8a4493b0&step=parallel_.ci%2Frun-link-check-plugin.sh
> minor: fix issue linkcheck plugin

- pom.xml
> Issue #6098: revert of workaround as on 3.1.9 it works fine

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules/DebugAuditAdapter.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSynchronizedStatement.java
Issue #6289
The first of 2 PRs for this issue.
The issue isn't approved so CI will fail.
> Issue #6289: added new tests to kill CONSTRUCTOR_CALLS mutations

- .ci/pitest.sh
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder6.java
> Issue #3708: finalized pitest mutation for misc profile

- .ci/pitest.sh
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnums.java
> Issue #6293: finalized pitest mutation for blocks profile

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingFalse.java
Issue #6264
This is just the starting point for the PR. I will be providing talking points and regression for every change listed here.
~Not all changes in `pitest.sh` are remaining mutations as noted in the issue description at https://github.com/checkstyle/checkstyle/issues/6264#issuecomment-446314799 . I will make notes on which ones are true changes and try to review them and see if I still can't kill them.~
This PR will close the issue once merged.
> Issue #6264: added TRUE_RETURNS pitest mutator

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/NoWhitespaceBeforeTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoWhitespaceAfterTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoWhitespaceBeforeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespaceafter/SuppressionXpathRegressionNoWhitespaceAfter.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebefore/SuppressionXpathRegressionNoWhitespaceBefore.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterMethodRef.java
- src/xdocs/config_filters.xml
Issue #5759 NoWhitespace{After,Before}Check
regression report https://pbludov.github.io/issue-5759/nowhitespace/
> Issue #5759: Update NoWhitespace{After,Before}Check to log DetailAST

- .ci/pitest.sh
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/AbstractParenPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
Issue #6289 
This is just the starting point for the PR. I will be providing talking points and regression for every unique change listed here.
This PR will close the issue once merged.
> Issue #6289: added CONSTRUCTOR_CALLS pitest mutator

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
Issue #6289 
This PR will close the issue.
Discussion was at https://github.com/checkstyle/checkstyle/pull/6296#issuecomment-447990990 .
> Issue #6289: resolved final CONSTRUCTOR_CALLS mutation

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSingleSpaceSeparatorTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/singlespaceseparator/SuppressionXpathRegressionSingleSpaceSeparator.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
- src/xdocs/config_filters.xml
Issue #5759 SingleSpaceSeparatorCheck
regression report https://pbludov.github.io/issue-5759/sss/
> Issue #5759: Update SingleSpaceSeparatorCheck to log DetailAST

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/470168476#L2841
> config: bump antly to 4.7.2

- .ci/pitest.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistance.java
Issue #5008 
This issue will probably be split into 3 PRs.
> Issue #5008: added test cases to kill coding profile mutations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
> Issue #6303: prevented violations ImportOrder for duplicate imports

- src/xdocs/releasenotes.xml
issue was found during https://github.com/checkstyle/sonar-checkstyle/issues/156
issue title was already updated by me.
> minor: fix 8.12 release notes for ImportOrder (issue title already updated)

- .travis.yml
- appveyor.yml
> Issue #6228: Set up JDK 11 build

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/472422393#L2855
> config: bump equalsverifier to 3.1.2

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCount.java
> Issue #6320: added REMOVE_CONDITIONALS mutator for sizes

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableName.java
Issue #6320
Comments and regression to come.
> Issue #6320: added REMOVE_CONDITIONALS mutator for naming

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObject.java
Issue #6320
Regression and comments to come.
> Issue #6320: added REMOVE_CONDITIONALS mutator for annotation

- .ci/travis/travis.sh
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierPackageClassName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorAbstract.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClassRootClass2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableException.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierInner.java
Issue #6320
Comments and regression to come.
> Issue #6320: added REMOVE_CONDITIONALS mutator for design

- config/checkstyle_resources_suppressions.xml
- config/suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/LineSeparatorOption.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyle.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename1a.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameNoPublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/trailingcomment/InputTrailingComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain.java
Issue #6320
Comments and regression to come.
> Issue #6320: added REMOVE_CONDITIONALS mutator for misc

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnums.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBraces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineStatements.java
Issue #6320
Regression and comments to come.
> Issue #6320: added REMOVE_CONDITIONALS mutator for blocks

- .ci/pitest.sh
- config/checkstyle_resources_suppressions.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorImportSeparatedFromPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/packageinfo/test4/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadLeftRightAndNoSpace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorEmpty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllTokens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundBraces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundKeywordsAndOperators.java
Issue #6320 
Regression and comments to come.
> Issue #6320: added REMOVE_CONDITIONALS mutator for whitespace

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/477492200#L2856
> config: bump picocli to 3.9.0

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/477492200#L2875
> config: bump equalsverifier to 3.1.4

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/477492200#L2888
> config: bump powermock to 2.0.0

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/477492200#L2913
> config: bump maven-assembly-plugin to 3.1.1

- .ci/jsoref-spellchecker/whitelist.words
- .ci/test-spelling-unknown-words.sh
> Issue #6021: treat pipeline failures for spellchecker as fatal errors

- .ci/test-spelling-unknown-words.sh
> Spelling error handling

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullMisc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullNested.java
Issue #6373
Regression to come. No differences are expected but random issue could make it seem like there are.
Issue isn't approved so travis will fail.
> Issue #6373: fixed frame tracking for EqualsAvoidNull

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/480532825#L2871
> config: bump jgit to 5.2.1.201812262042-r

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ArrayInitHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentLevel.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LabelHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ObjectBlockHandler.java
> Issue #6308: made IndentLevel immutable

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- config/pmd-test.xml
- config/spotbugs-exclude.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilter.java
- src/xdocs/config_filters.xml
- src/xdocs/config_imports.xml
> Issue #5879: Suppression xpath single filter

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/489695919#L2915
> config: bump jacoco-maven-plugin to 0.8.3

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/489695919#L2889
> config: bump spotbugs-maven-plugin to 3.1.11

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/489695919#L2857
> config: bump saxon to saxon-9.9.1-1

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/489695919#L2872
> config: bump jacoco to 0.8.3

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/489695919#L2901
> config: bump pitest to 1.4.5

- .ci/pitest.sh
- pom.xml
> Issue #6320: add REMOVE_CONDITIONALS to xpath config

- .ci/pitest.sh
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessageTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationNoPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderForwardReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderVariableAccess.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNull.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeEqualsParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitialization.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableEnhancedForLoopVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldLambdas.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableBothForLoops.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplevariabledeclarations/InputMultipleVariableDeclarations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistance.java
Issue #6320
Since we added the mutator everywhere, I am dumping all the tests I had saved up for incomplete packages that I was still working on.
> Issue #6320: added new tests to kill mutations for multiple packages 

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for MethodName

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
> Issue #3567: fixed final ForbidAnnotationElementValueCheck violation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for InterfaceTypeParameterName

- src/xdocs/index.xml.vm
- src/xdocs/writingchecks.xml
> Issue #6083: Add Limitation in index.xml.vm

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for ConstantName

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/xdocs/cmdline.xml.vm
> Issue #6399: expanded exclude options to include files

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
- src/xdocs/config_annotation.xml
Issue #6416 
https://pbludov.github.io/issue-6416/ (zero impact, as expected)
> Issue #6416: AnnotationLocation: remove unhandled tokens

- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
> Issue #6297: removed files from cache when an exception occurs

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for LocalFinalVariableName

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java
Issue #4979
Part 1 of a possible 2 part PR.
> Issue #4979: synchronize suppress and xpath filter element

- config/catalog.xml
> Issue #4877: added reason for catalog.xml

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/TagParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleNeverEndingXmlComment.java
> Issue #4564: fixed exception on JavadocStyle's skip html comment

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/xdocs/config_coding.xml
> Issue #5900: renamed format property to illegalAbstractClassNameFormat

- src/xdocs/config_annotation.xml
> Issue #6451: Fixed typo in MissingDeprecated description

- src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
Add test created at https://github.com/checkstyle/checkstyle/pull/6435#issuecomment-464937668 but couldn't add because of powermock interference.
> minor: expanded PackageObjectFactory test for invalid classes

- src/main/java/com/puppycrawl/tools/checkstyle/api/FilterSet.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java
> Issue #6494: remove equals/hashcode from FilterSet

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java
> Issue #4734: remove equals/hashcode from SuppressionFilter

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/xdocs/config_blocks.xml
> Issue #6455: fixed property types for EmptyCatchBlockCheck

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java
Another minor thing I noticed.
> minor: removed unnecessary createChecker for verify method call

- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java
Just something I noticed when working on the other PR.
> minor: removed unnecessary multi-file verify with single file

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/package-info.java
> Issue #5769: added package-info to list of valid javadocs

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for LocalVariableName

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #5750: aligned javadoc/xdoc for MissingDeprecated

- src/main/resources/sun_checks.xml
- src/xdocs/config_coding.xml
> Issue #6470: Remove AvoidInlineConditionals check from sun_checks.xml

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
- src/xdocs/config_design.xml
> Issue #6468: Fix typo in rationale of VisibilityModifier check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
- src/xdocs/config_annotation.xml
> Issue #6453: Change default format regex of SuppressWarnings check to ^\s*+$

- src/site/resources/files/suppressions_none.xml
> Issue #6449: Fix doctype declaration of suppressions_none.xml

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
- src/xdocs/config_coding.xml
> Issue #6472: Clean up rationale of ExplicitInitialization check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_blocks.xml
> Issue #5750: aligned javadoc/xdoc for EmptyBlock

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #5750: aligned javadoc/xdoc for MissingOverride

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #5750: aligned javadoc/xdoc for AnnotationLocation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_blocks.xml
> Issue #6532: aligned javadoc/xdoc for EmptyCatchBlock

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_blocks.xml
> Issue #6532: aligned javadoc/xdoc for NeedBraces

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #6531: aligned javadoc/xdoc for AnnotationOnSameLine

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java
> Issue #6446: fixed AnnotationMemberValuePair in AnnotationUseStyleCheck

- src/main/resources/sun_checks.xml
> Issue #6420: fixed outdated links in sun_checks.xml

- config/pmd-test.xml
- config/pmd.xml
> Issue #6226: changed pmd's AbstractNaming to ClassNamingConventions

- config/checkstyle_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
> Issue #5506: disallowed StringBuffer

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #6531: aligned javadoc/xdoc for SuppressWarnings

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #6531: aligned javadoc/xdoc for AnnotationUseStyle

- .ci/travis/travis.sh
> updating simple-binary-encoding regression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_annotation.xml
> Issue #6531: aligned javadoc/xdoc for SuppressWarningsHolder

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_blocks.xml
> Issue #6532: aligned javadoc/xdoc for AvoidNestedBlocks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java
> Issue #6491: Fix wrong JavaDoc example for NestedForDepth check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_blocks.xml
> Issue #6532: aligned javadoc/xdoc for RightCurly

- .ci/wercker.sh
- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
Issue #2883
Attempt rety of https://github.com/checkstyle/checkstyle/pull/5323 .
> Issue #2883: removed cache from treewalker

- .ci/jsoref-spellchecker/whitelist.words
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/site/resources/css/site.css
- src/xdocs/beginning_development.xml
- src/xdocs/cmdline.xml.vm
- src/xdocs/config_imports.xml
- src/xdocs/config_metrics.xml
- src/xdocs/config_whitespace.xml
- src/xdocs/releasenotes.xml
- src/xdocs/writingchecks.xml
- src/xdocs/writingjavadocchecks.xml.vm
- re-enable maven-site-plugin validation as underlying problem was fixed in xml-maven-plugin 1.0.2
- fix invalid markup
Fixes #6563
> Issue #6563: Fix Invalid Doc

- src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java
> Issue #4632: override java parser report error to throw exception

- .ci/travis/travis.sh
- .travis.yml
Issue #5897
CI is expected to fail until https://github.com/checkstyle/contribution/pull/348 is merged .
> Issue #5897: verified all modules are in no exception configs

- config/pmd.xml
> Issue #5680: disable PMD rule UseProperClassLoader

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for CovariantEquals

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for ArrayTrailingComma

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for AvoidInlineConditionals

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for EqualsAvoidNull

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for DeclarationOrder

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for MagicNumber

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for EqualsHashCode

- config/suppressions.xml
- src/main/resources/google_checks.xml
- src/main/resources/sun_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config_filefilters.xml
> Issue #6570: Exclude module-info.java from Google and Sun configurations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for DefaultComesLast

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for MissingCtor

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for EmptyStatement

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for IllegalInstantiation

- src/xdocs/config.xml
Finalization of https://github.com/checkstyle/checkstyle/issues/6485
> doc: added documentation for global tabWidth

- src/xdocs/config_coding.xml
> Issue #6488: Fix documentation of InnerAssignment check

- .ci/pitest.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAlone.java
> Issue #6367: Improve pitest coverage for RightCurly

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for FinalLocalVariable

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for RequireThisCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for MissingSwitchDefault

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for UnnecessaryParentheses

- pom.xml
> upgrade to ASM 7.1
Ant support for testPlugin and failWhenNoMutations
Allow empty elements in maven configuration
> config: upgrade pitest to 1.4.6

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for StringLiteralEquality

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for IllegalTokenText

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for NoClone

- .ci/jsoref-spellchecker/exclude.pl
- .ci/jsoref-spellchecker/whitelist.words
- config/pmd-test.xml
- src/it/java/com/sun/checkstyle/test/chapter6declarations/rule61numberperline/MultipleVariableDeclarationsTest.java
- src/it/resources/com/sun/checkstyle/test/chapter6declarations/rule61numberperline/InputMultipleVariableDeclarations.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
- src/main/resources/sun_checks.xml
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConvTOC.doc.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc1.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc10.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc2.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc3.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc4.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc5.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc6.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc7.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc8.html
- src/site/resources/styleguides/sun-code-conventions-19990420/CodeConventions.doc9.html
- src/site/resources/styleguides/sun-code-conventions-19990420/Copyright.doc.html
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
- src/xdocs/index.xml.vm
- src/xdocs/sun_style.xml
> Issue #6490: Add MultipleVariableDeclarations check to Sun style config

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for InnerAssignment

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for PackageDeclaration

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
The CI will fail till #6651 (whitespace after comma issue)
> Issue #6586: aligned javadoc/xdoc for SimplifyBooleanExpression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for IllegalThrows

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for ExplicitInitialization

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for MultipleVariableDeclarations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for SimplifyBooleanReturn

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config_coding.xml
Second commit to turn `Default value is .` into `Default value is no tokens.`
> Issue #6586: aligned javadoc/xdoc for IllegalType

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for NestedIfDepth

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for IllegalCatch

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for SuperClone

- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/translation/ExpectedTranslationLog.xml
> Issue #5103: fixed multi-file reporting in TranslationCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySame.java
> Issue #6466: do not complain in same-mode about constructs that are not multi-part

- config/pmd-test.xml
- config/pmd.xml
Removed unnecessary PMD suppressions.
> minor: remove unnecessary pmd suppressions

- config/pmd.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheck.java
> Issue #6606: catch all exceptions during reflection in AbstractTyeAware

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for OneStatementPerLine

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for ParameterAssignment

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for SuperFinalize

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for MultipleStringLiterals

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for IllegalToken

- pom.xml
This is in support of https://github.com/checkstyle/checkstyle/issues/6687 and confirmed in https://github.com/checkstyle/checkstyle/pull/6681 .
> config: update maven-enforcer-plugin to 3.0.0-M2

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for NestedTryDepth

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for ModifiedControlVariable

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for OverloadMethodsDeclarationOrder

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for NoFinalizer

- .ci/travis/travis.sh
- .travis.yml
- appveyor.yml
Issue #6687
Confirming JDK12 build for https://github.com/checkstyle/checkstyle/pull/6664
Will create issue depending on CI results.
> Issue #6687: set up JDK12 build

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
> Issue #6586: aligned javadoc/xdoc for HiddenField

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorNoViolationOnEmptyLineBeforeComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments.java
Issue #5981 
Checking of comments before tokens has been added to EmptyLineSeparatorCheck with corresponding tests.
> Issue #5981: add validation of new lines before comments

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalType.java
> Issue #6612: do not complain about illegal types as parameters of methods with @Override annotation

- pom.xml
> config: upgrade powermock to 2.0.2

- .gitattributes
- config/checkstyle_non_main_files_suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefaultLF.java
> Issue #6513: Do not depend on system line separator in empty catch block check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for FinalClass

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for InnerTypeLast

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for DesignForExtension

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for MutableException

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for OneTopLevelClass

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for ThrowsCount

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for InterfaceIsType

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for HideUtilityClassConstructor

- .ci/jsoref-spellchecker/whitelist.words
- pom.xml
> Issue #6713: exclude icu4j from saxon

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_design.xml
> Issue #6725: aligned javadoc/xdoc for VisibilityModifier

- .github/ISSUE_TEMPLATE.md
Issue #6742
Continuation of https://github.com/checkstyle/checkstyle/pull/6716 .
> We probably will need to your feedback on PR description too :) - https://github.com/checkstyle/checkstyle/blob/master/.github/PULL_REQUEST_TEMPLATE.md 
Template already stated that CI must pass. The only thing I can think of adding is the command to run `mvn verify test` locally.
> Issue #6742: clarify in issue template to follow the rules

- config/checkstyle_checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationSingleParameterless.java
- src/xdocs/config_annotation.xml
Splitting followup part 1 for #6530
Fixes #6462
Regression report: http://kautler.net/cs-regression-6462/
> Issue #6462: Remove PARAMETER_DEF from AnnotationLocation

- src/xdocs/releasenotes.xml
> doc: fix my name in release notes

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for NoLineWrap

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for MethodParamPad

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for FileTabCharacter

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for EmptyForInitializerPad

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for TypecastParenPad

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for WhitespaceAfter

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for SingleSpaceSeparator

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for NoWhitespaceAfter

- .ci/travis/travis.sh
- .travis.yml
> Issue #6701: create osx related builds in travis.sh

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for GenericWhitespace

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTryWithResources.java
- src/xdocs/config_coding.xml
> Issue #6125: Ignore variable reference as resource statement

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for SeparatorWrap

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for EmptyForIteratorPad

- config/pmd-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
Issue #4900
Blocked by https://github.com/checkstyle/checkstyle/pull/6629
> Issue #4900: refactored DetailASTTest.testTreeStructure

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for NoWhitespaceBefore

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for WhitespaceAround

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for OperatorWrap

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableNameOneCharInitVarName.java
- src/xdocs/config_naming.xml
Issue: #6489 
Case for one-char loop variable is treated differently now, test case was updated.
Regression report will be soon.
> Issue #6489: correct one-char loop variable in LocalVariableNameCheck

- .ci/idea_inspection.sh
- .ci/jsoref-spellchecker/whitelist.words
- .ci/wercker.sh
Miscellaneous PR without issue: Inpection -> Inspection
> spelling: inpection

- .ci/jsoref-spellchecker/whitelist.words
- src/xdocs/writingjavadocchecks.xml.vm
Miscellaneous PR without issue: Identificator -> Identifier
> spelling: identificator

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
> Issue #6749: aligned javadoc/xdoc for EmptyLineSeparator

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for MethodTypeParameterName

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for PackageName

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/538908990#L2787
> config: bump pitest to 1.4.8

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/538908990#L2813
> config: bump maven-jar-plugin to 3.1.2

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/538908990#L2826
> config: bump jacoco-maven-plugin to 0.8.4

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/538908990#L2758
> config: bump equalsverifier to 3.1.9

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
#5124
Reg report (no differences) - https://strkkk.github.io/5124_one_statement/
> Issue #5124: remove branchContains for OneStatementPerLineCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
- src/xdocs/config_annotation.xml
- src/xdocs/property_types.xml
#3210
Reg. report: https://strkkk.github.io/3210/
> Issue #3210: fix compact_no_array in AnnotationUseStyleCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
#6818 also removes usage ob branchContains for #5124
Report - https://strkkk.github.io/5124_anno/
> Issue #6818: fix expanded style in AnnotationUseStyleCheck

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonintrywithresources/InputUnnecessarySemicolonInTryWithResourcesDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonintrywithresources/InputUnnecessarySemicolonInTryWithResourcesNoBraceAfterAllowed.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
#6774
Contribution repo PR  https://github.com/checkstyle/contribution/pull/378
Reg. report https://strkkk.github.io/6774/index.html
> Issue #6774: Add UnnecessarySemicolonInTryWithResourcesCheck

- config/intellij-idea-inspections.xml
Issue #6821
we should merge this PR if we come to agreement at #6823
> Issue #6821: disable SimplifiableJUnitAssertion inspection

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyOption.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyOption.java
> Issue #6821: remove IDEA suppressions fix for violation 'Redundant suppression'

- config/intellij-idea-inspections.xml
- src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java
- src/it/java/com/sun/checkstyle/test/base/AbstractSunModuleTestSupport.java
- src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionGenericWhitespaceTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoWhitespaceBeforeTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionParenPadTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSingleSpaceSeparatorTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionTypecastParenPadTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionWhitespaceAfterTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionWhitespaceAroundTest.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
> Issue #6821: idea violations java2

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SuppressionFilter

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/blank/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/blank/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/blockcomment/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/single/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/singleline/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/singleline/package-info.java
- src/xdocs/checks.xml
- src/xdocs/config_javadoc.xml
#6705
Contribution PR - https://github.com/checkstyle/contribution/pull/377
Reg report: https://strkkk.github.io/6705/index.html
> Issue #6705: Add MissingJavadocPackageCheck

- pom.xml
> Issue #6835: bump sevntu version

- README.md
- config/checkstyle_checks.xml
- config/suppressions.xml
- src/main/resources/sun_checks.xml
- src/xdocs/index.xml.vm
- src/xdocs/sponsoring.xml
- src/xdocs/sun_style.xml
#6804 
PR it does not fix issue but just do prestep.
bluej site is removed, as it is dead project, I do not want complicate regexp to keep it.
should be merged only when http://checkstyle.sourceforge.net/ become redirected to https
nothing works on sourceforge , waiting for conversion to http, support ticket is shared in issue.
> 6804 https sourceforge

- .ci/copy-site-to-sourceforge.sh
- .ci/jsoref-spellchecker/whitelist.words
> Issue #6804: redirect sourceforge.io dtds to checkstyle.org site

- .ci/travis/travis.sh
- config/checkstyle_sevntu_checks.xml
- pom.xml
Issue #6835
first fix attempt was at #6836
> Issue #6835: add Jsr305AnnotationsCheck to sevntu config

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InvalidJavadocPositionTest.java
- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InvalidJavadocPositionTest.java
- src/it/java/com/sun/checkstyle/test/chapter5comments/rule52documentationcomments/InvalidJavadocPositionTest.java
- src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputInvalidJavadocPosition.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPosition.java
- src/it/resources/com/sun/checkstyle/test/chapter5comments/rule52documentationcomments/InputInvalidJavadocPosition.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtil.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties
- src/main/resources/google_checks.xml
- src/main/resources/sun_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/package-info.java
- src/xdocs/checks.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/google_style.xml
- src/xdocs/sun_style.xml
Issue #6649
Contribution: https://github.com/checkstyle/contribution/pull/383
> Issue #6649: add InvalidJavadocPositionCheck

- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InvalidJavadocPositionTest.java
- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InvalidJavadocPositionTest.java
- src/it/java/com/sun/checkstyle/test/chapter5comments/rule52documentationcomments/InvalidJavadocPositionTest.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputInvalidJavadocPosition.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPosition.java
- src/it/resources/com/sun/checkstyle/test/chapter5comments/rule52documentationcomments/InputInvalidJavadocPosition.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java
> Issue #6857: fix javadoc check on local variables

- .ci/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberAnnotationElement.java
- src/xdocs/config_coding.xml
#4383
Reg report: https://strkkk.github.io/4383/
> Issue #4383: add ignoreAnnotationElementDefaults property in MagicNumber

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
Issue #6844 
Now we need to use reflection to access the Tag class.
> Issue #6844: Make SuppressionCommentFilter.Tag private

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
The `Notes` section now before `Properties`.
> Issue #6726: aligned javadoc/xdoc for SuppressionCommentFilter

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SuppressWithNearbyCommentFilter

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SuppressWithPlainTextCommentFilter

- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheckTest.java
> Issue #6858: Remove TreeWalker#validateDefaultTokens

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
Issue #6890
Now we need to use reflection to access the `Suppression` class.
> Issue #6890: make SuppressWithPlainTextCommentFilter.Suppression private

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineTryWithResourcesIgnore.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineMultiline.java
- src/xdocs/config_coding.xml
#6790
Report https://strkkk.github.io/6790/
> Issue #6790: add treatTryResourcesAsStatement property to OneStatementPerLine

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SuppressWarningsFilter

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SeverityMatchFilter

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElementTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterWithCustomOnComment.sql
The goal of this PR is to increase the mutation coverage for pitest-filters to 100% (#6659).
I will add PR comments explaining my reasoning for some of the changes, and will certainly be happy to iterate on them in response to any feedback.
> Issue #6659: increase mutation coverage for pitest-filters

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SuppressionXpathFilter

- .ci/appveyor.bat
- appveyor.yml
> Issue #6696: Create appveyor batch file

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_coding.xml
- src/xdocs/config_filters.xml
- src/xdocs/config_imports.xml
- src/xdocs/config_misc.xml
- src/xdocs/config_modifier.xml
- src/xdocs/config_naming.xml
- src/xdocs/config_whitespace.xml
- src/xdocs/releasenotes.xml
- src/xdocs/releasenotes_old.xml
- src/xdocs/writingchecks.xml
> Issue #6900: remove absolute checkstyle links, change javadoc routine

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- config/pmd.xml
- config/spotbugs-exclude.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressFilterElement.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionsinglefilter/InputSuppressionSingleFilter.java
- src/xdocs/config_filters.xml
> Issue #6402: add new SuppressionSingleFilter

- config/checkstyle_checks.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongLink.java
- src/xdocs/checks.xml
- src/xdocs/config_whitespace.xml
- src/xdocs/google_style.xml
- src/xdocs/writingchecks.xml
Issue #6902
Changes only in the config, comments and tests.
> Issue #6902: format xdoc/javadoc files to follow rule of LineLength

- .circleci/config.yml
- .travis.yml
- distelli-manifest.yml
- shippable.yml
- wercker.yml
> Issue #3383: Skip dry run build item for maven release commit

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
#6805
Reg report: https://strkkk.github.io/6805/
> Issue #6805: fix false-positive in while idiom for InnerAssingmentCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/CheckstyleException.java
> doc: Serialisation -> serialization

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filters.xml
> Issue #6726: aligned javadoc/xdoc for SuppressionXpathSingleFilter

- src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_filefilters.xml
> Issue #6726: aligned javadoc/xdoc for BeforeExecutionExclusionFileFilter

- pom.xml
This commit enables caching on PMD to speed up re-runs.
> config: enable PMD cache

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineLambda.java
- src/xdocs/config_blocks.xml
#3837
Fix + changes to resolve violations in checkstyle code.
Reg report https://strkkk.github.io/3837/
> Issue #3837: report lambda with no braces when contents span multiple lines

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
> Issue #6936: add short versions E and w for the CLI

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config_coding.xml
- src/xdocs/config_design.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/config_metrics.xml
Issue #6938 
First commit to format xdocs/javadoc.
Second commit to fix `XdocsPagesTest#getModulePropertyExpectedValue`
> Issue 6938: sort values for String Set properties 

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
Issue #6931 
Fixes for Javadoc only.
> Issue #6929: fix violations for JavadocBlockTagLocation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
Issue #6948: Fix is to escape `>` as `&gt;`
> Issue #6948: javadoc error in NeedBracesCheck.java

- src/xdocs/cmdline.xml.vm
> Issue #6933: Update link to latest version of CLI jar

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/569019879#L1160
> config: bump maven-javadoc-plugin to 3.1.1

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/569019879#L1175
> config: bump maven.site.plugin.version to 3.8.2

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/569019879#L1149
> config: bump maven.spotbugs.plugin.version to 3.1.12.1

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/569019879#L1131
> config: bump slf4j-simple to 1.7.27

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/569019879#L1115
> config: bump picocli to 4.0.1

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnnecessarySemicolonAfterTypeMemberDeclarationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessarysemicolonaftertypememberdeclaration/SuppressionXpathRegressionUnnecessarySemicolonAfterTypeMemberDeclaration.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclaration.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
#6847 
Old reg report: https://strkkk.github.io/6752/
Current reg report: https://strkkk.github.io/6752_2/
contrib PR - https://github.com/checkstyle/contribution/pull/392
> Issue #6847: Add UnnecessarySemicolonAfterTypeMemberDeclarationCheck

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
> Issue #6934: fix suppression generation with custom output location

- src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for FinalParameters

- src/main/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for ArrayTypeStyle

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for UncommentedMain

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/xdocs/cmdline.xml.vm
> Issue #6934: correct doc for suppression generation

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionArrayTypeStyleTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/arraytypestyle/SuppressionXpathRegressionArrayTypeStyleMethodDef.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/arraytypestyle/SuppressionXpathRegressionArrayTypeStyleVariable.java
This PR adds XPath regression test for suppression filter on [ArrayTypeStyle](https://checkstyle.org/config_misc.html#ArrayTypeStyle) check, see #6207.
> Issue #6207: Add xpath regression test for ArrayTypeStyle

- src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for OuterTypeFilename

- .ci/pitest.sh
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainConfig-TypeName-bad-value.xml
Issue #6974
As side effect of change, there will be no counter of errors print when CLI is stopped with exception.
> Issue #6974: move error count print of CLI to stderr

- .ci/pitest.sh
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
> Issue #6982:  Issue #6982: kill mutation in Main.java by always closing streams 

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
Some of the lines in `config_misc.xml` has been shortened to fit to the '100 character per line' limit.
> Issue #6966: aligned javadoc/xdoc for CommentsIndentation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for UniqueProperties

- src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for TrailingComment

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for UpperEll

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/575015020#L1160
> config: bump spotbugs to 3.1.12.2

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/575015020#L1147
> config: bump slf4j to 1.7.28

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/575015020#L1131
> config: bump picocli to 4.0.2

- pom.xml
all details at https://github.com/checkstyle/checkstyle/pull/6998
it was detected before PR from snyk at https://travis-ci.org/checkstyle/checkstyle/jobs/575015020#L1113
> config: bump commons-beanutils to 1.9.4

- config/pmd-main.xml
- config/pmd-test.xml
- config/pmd.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
Issue #6868
https://pmd.github.io/latest/pmd_rules_java_errorprone.html#closeresource
> Issue #6868: update pmd to 6.17.0 and resolve violations

- .ci/jsoref-spellchecker/whitelist.words
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
> Issue #6991: Make test on file that have no read access but has write acces

- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for NewlineAtEndOfFile

- src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
> Issue #6966: aligned javadoc/xdoc for TodoComment

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_misc.xml
Implementation details moved from javadoc comment to regular comment.
> Issue #6966: aligned javadoc/xdoc for Indentation

- .ci/shippable.sh
- .ci/travis/travis.sh
- .ci/wercker.sh
- config/checkstyle_checks.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/ant/checkstyleanttask/InputCheckstyleAntTaskTestChecks.xml
- src/xdocs/config_sizes.xml
> Issue #2116: turned LineLengthCheck into an FileSet check

- .ci/travis/travis.sh
- .travis.yml
- src/main/resources/sun_checks.xml
> Issue #2116: add sun_checks.xml regression

- .ci/wercker.sh
> Issue #2116: switch wercker to use forked equalsverifier

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/578022414#L1110
> config: bump picocli to 4.0.3

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/578022414#L1126
> config: bump jgit to 5.4.2

- src/main/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinter.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
separated first commit from #7025
> minor: refactoring of line endings

- src/it/resources/com/google/checkstyle/test/chapter2filebasic/rule231filetab/InputFileTabCharacter.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/InputLineLength.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhile.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlyDoWhileAlone.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule44columnlimit/InputLineLength.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundBasic.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocCheck.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputCorrectSummaryJavaDocCheck.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule72thesummaryfragment/InputIncorrectSummaryJavaDocCheck.java
> Issue #6771: use 'violation'/'problem' term in it/resources insteadof 'error'

- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinter.java
- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/XpathUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/asttreestringprinter/InputAstTreeStringPrinterPrintBranch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainXPath.java
> Issue #6660: add xpath evaluation to cli

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/583818724#L1192
> config: bump sonar to 3.6.1.1688

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/583818724#L1166
> config: bump ant to 1.10.7

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/583818724#L1134
> config: bump picocli to 4.0.4

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/583818724#L1118
> config: bump guava to 28.1-jre

- config/version-number-rules.xml
continuation of https://github.com/checkstyle/checkstyle/pull/7051
> config: suppress pitest new version detection

- .ci/travis/travis.sh
Issue #2116
This reverts commit 7a87bb5bf1e38f0f67a5d18b85fc4b2d933e385a.
> Revert "Issue #2116: use forked simple-binary-encoding with fix to pass CI build

- .ci/wercker.sh
- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/583818724#L1148
> config: bump saxon to 9.9.1-5

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for AnonInnerLength

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for OuterTypeNumber

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for LineLength

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for ParameterNumber

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for ExecutableStatementCount

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for MethodLength

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for FileLength

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_sizes.xml
> Issue #7060: aligned javadoc/xdoc for MethodCount

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/xdocs/config_imports.xml
> Issue #7080: fix CustomImportOrder documentation

- .circleci/config.yml
- .travis.yml
- shippable.yml
- wercker.yml
> Issue #7023: include all commits for CI checks between head and master

- appveyor.yml
> config: after fix of #6558 appveyor should test changes in .gitattributes file

- .ci/travis/travis.sh
- .travis.yml
> Issue #5496: fail CI if top master commit is too far back

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionNativeMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionOverridableMethods.java
> Issue #5450: add javadoc recognition to DesignForExtension

- .ci/wercker.sh
- wercker.yml
Issue #3279 
it was recently requested at https://github.com/checkstyle/checkstyle/pull/7078#issuecomment-533757737
but due to rash to resolve "git clone" issue, was postponed.
====
PR in contribution - https://github.com/checkstyle/contribution/pull/413
after its merge, this PR need to be updated to use master branch of contribution repo.
> Issue #3279: let wercker to test cloned checkstyle repo(master or PR branch

- .ci/wercker.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java
- src/xdocs/config_javadoc.xml
> Issue #7096: remove deprecated properties from JavadocMethodCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
> Issue #7100: remove deprecated constructor and methods from FileContents

- src/main/java/com/puppycrawl/tools/checkstyle/DetailAstImpl.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfoTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/XpathUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java
> Issue #6628: removed antlr specific methods from DetailAST

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineMultilineSupport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineMultilineSupport2.java
- src/xdocs/config_regexp.xml
> Issue #6717: add support to RegexpMultiline to match across lines

- src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/XMLLoggerTest.java
> Issue #7105: remove deprecated constructor from XMLLogger

- config/checkstyle_resources_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderNoPackage3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine.java
related to #6680 
continuation of https://github.com/checkstyle/checkstyle/pull/6830 (code provided by  @gmshake )
> minor: update in UTs for upcomming fix for #6680

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
- src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
> Issue #7107: remove deprecated constructors for DefaultLogger

- .ci/pitest.sh
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java
> Issue #6367: resolved pitest for blocks package

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/CovariantEqualsCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@9ed9769_147
> Issue #6320: resolve remove conditional for CovariantEqualsCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java
Issue #6320 
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/DefaultComesLastCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@73f93fb4_132
> Issue #6320: resolve remove conditional for DefaultComesLastCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/EqualsHashCodeCheck.java.html
> Issue #6320: resolve remove conditional for EqualsHashCodeCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/ExplicitInitializationCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4a1f8f59_184
> Issue #6320: resolve remove conditional for ExplicitInitializationCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/ArrayTrailingCommaCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@3e738d34_165
> Issue #6320: resolve remove conditional for ArrayTrailingCommaCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/FallThroughCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@34199d1c_276
I am not sure regression is needed. Let me know otherwise.
> Issue #6320: resolve remove conditional for FallThroughCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/IllegalCatchCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@77baac76_132
> Issue #6320: resolve remove conditional for IllegalCatchCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java
Issue #6320 
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/ReturnCountCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@1716bfb9_326
> Issue #6320: resolve remove conditional for ReturnCountCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentWithUnchecked.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/ParameterAssignmentCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@25925217_193
I don't think regression is needed. Let me know.
> Issue #6320: resolve remove conditional for ParameterAssignmentCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/IllegalThrowsCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4f4e6a99_149
> Issue #6320: resolve remove conditional for IllegalThrowsCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullMisc.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/EqualsAvoidNullCheck.java.html
> Issue #6320: resolve remove conditional for EqualsAvoidNullCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_imports.xml
> Issue #7144: aligned javadoc/xdoc for AvoidStarImport

- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/InputSimplifyBooleanReturn.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/SimplifyBooleanReturnCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@3fccc795_101
No regression needed.
> Issue #6320: resolve remove conditional for SimplifyBooleanReturnCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableBothForLoops.java
Issue #6320
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/37/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/ModifiedControlVariableCheck.java.html
> Issue #6320: resolve remove conditional for ModifiedControlVariableCheck

- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
Issue #7120
Fix violation of IntelliJ IDEA inspection `InconsistentResourceBundle`
> Issue #7120: Add localization for javadoc.write.tag

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_imports.xml
> Issue #7144: aligned javadoc/xdoc for AvoidStaticImport

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_imports.xml
> Issue #7144: aligned javadoc/xdoc for RedundantImport

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_metrics.xml
> Issue #7145: aligned javadoc/xdoc for BooleanExpressionComplexity

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_metrics.xml
> Issue #7145: aligned javadoc/xdoc for CyclomaticComplexity

- .ci/common.sh
- .circleci/config.yml
- .travis.yml
- shippable.yml
- wercker.yml
Issue identified at https://github.com/checkstyle/checkstyle/pull/7123#issue-322507527 ,
Fixing CI so we don't skip all master runs. Right now the PR commit count is making all master CI runs act like there are no commits and is always skipping CI.
See https://github.com/checkstyle/checkstyle/pull/7125#discussion_r329520373 for full description
This is also to try to provide us easier maintenance and some debugging as I am not sure I have fixed all cases.
> config: fix previous commits check to avoid confusion with master and rewrite main ci for easier maintenance

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_metrics.xml
> Issue #7145: aligned javadoc/xdoc for ClassFanOutComplexity

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_imports.xml
> Issue #7144: aligned javadoc/xdoc for UnusedImports

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_regexp.xml
> Issue #7163: aligned javadoc/xdoc for Regexp

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_metrics.xml
> Issue #7145: aligned javadoc/xdoc for ClassDataAbstractionCoupling

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_metrics.xml
> Issue #7145: aligned javadoc/xdoc for NPathComplexity

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_regexp.xml
> Issue #7163: aligned javadoc/xdoc for RegexpMultiline

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_regexp.xml
> Issue #7163: aligned javadoc/xdoc for RegexpSinglelineJava

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_imports.xml
> Issue #7144: aligned javadoc/xdoc for IllegalImport

- .ci/jsoref-spellchecker/whitelist.words
- config/org.eclipse.jdt.core.prefs
fixes #5060
Reason: https://github.com/checkstyle/checkstyle/issues/5060#issuecomment-538684043
Reason for second commit: https://github.com/checkstyle/checkstyle/pull/7169#issuecomment-538806309
> Issue #5060: keep nullanalysis disabled as we have no time to make it now

- .ci/jsoref-spellchecker/whitelist.words
- src/xdocs/index.xml.vm
> minor: reference jitpack as option to build artifacts

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/595782529#L1073
> config: bump equalsverifier to 3.1.10

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_metrics.xml
> Issue #7145: aligned javadoc/xdoc for JavaNCSSCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_regexp.xml
> Issue #7163: aligned javadoc/xdoc for RegexpSingleline

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_regexp.xml
> Issue #7163: aligned javadoc/xdoc for RegexpOnFilename

- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_header.xml
> Issue #7185: aligned javadoc/xdoc for Header

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_modifier.xml
> Issue #7186: aligned javadoc/xdoc for ModifierOrder

- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_header.xml
> Issue #7185: aligned javadoc/xdoc for RegexpHeader

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_modifier.xml
> Issue #7186: aligned javadoc/xdoc for RedundantModifier

- pom.xml
https://travis-ci.org/checkstyle/checkstyle/jobs/598822377#L1084
> config: bump jacoco to 0.8.5

- pom.xml
Redo of https://github.com/checkstyle/checkstyle/pull/7207
> config: bump jgit to 5.5.1.201910021850

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/xdocs/config_filters.xml
from https://github.com/checkstyle/sonar-checkstyle/pull/245#issuecomment-544212422
> doc: fix config sample for SuppressWithNearbyCommentFilter

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheck.java
- src/xdocs/config_coding.xml
> Issue #7077: correct docs for UnnecessarySemicolonAfterTypeMemberDeclaration

- .ci/travis/travis.sh
- config/pmd-main.xml
- src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
partially address #7033
address fully https://github.com/checkstyle/checkstyle/issues/7033#issuecomment-545264613
> Issue #7033: make FileText.fullText to be non final

- config/pmd.xml
- pom.xml
Issue #7225 (first part of update)
second Part (will be separate PR) to resolve WARNINGS.
As issue is misc it is ok to make fixes in few PRs (even in different releases).
> Issue #7225: bump pmd to 6.18.0

- .ci/wercker.sh
- config/pmd.xml
as it is covered by LocalVariableName (related to #7229)
> config: remove custom rule CheckstyleCustomShortVariable

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExpressions.java
#7066 
Report: https://strkkk.github.io/7066_2/index.html
> Issue #7066: correct RequireThis for expression cases

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for JavadocMethod

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for JavadocPackage

- config/pmd-test.xml
- config/pmd.xml
> Issue #7248: resolve PMD warning on deprecated MethodDeclarator

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for JavadocParagraph

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for JavadocStyle

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for NonEmptyAtclauseDescription

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for WriteTag

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for JavadocType

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for SummaryJavadoc

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for JavadocVariable

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/xdocs/config_javadoc.xml
#7267 
fix for https://travis-ci.org/checkstyle/checkstyle/jobs/612891700#L547
> Issue #7267: fix for eclipse and openjdk error in documentation caused by some previous commit

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_javadoc.xml
> Issue #7208: aligned javadoc/xdoc for SingleLineJavadoc

- .ci/jsoref-spellchecker/whitelist.words
- pom.xml
minor change to `pom.xml`
from https://github.com/checkstyle/checkstyle/pull/7265#issuecomment-554670610
> config: add myself to the developer list

- src/site/resources/css/site.css
> Issue #7270: change repeat of header to repeat-x

- .ci/wercker.sh
> Issue #7288: fix xwiki build on wercker

- .ci/copy-site-to-sourceforge.sh
> config: add more output to investigate #7268

- .ci/copy-site-to-sourceforge.sh
> Issue #7268: fix proper mod of files in archive at sourceforge

- .ci/appveyor.bat
- .ci/travis/travis.sh
- .travis.yml
- appveyor.yml
Issue #7281
Travis & Appveyor JAVA 13 builds
> Issue #7281: set up jdk-13 build, drop jdk-12

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/header/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/annotation/blockcomment/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/blank/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/blockcomment/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/detached/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/single/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/singleline/package-info.java
#7117
report #2 https://strkkk.github.io/checkstyle/7117_2/index.html
> Issue #7117: fix package info javadoc check

- .ci/travis/travis.sh
I really tiered to recheck Travis state when new Check is introduced ....
so here is extra hacking to ease this problem.
I do check any PR link as if it present it will be verified by human, so any link to contributions pools is ok for now. We can make validation more exact later on if required. 
tested on https://github.com/checkstyle/checkstyle/pull/7228
testing:
```
diff --git a/config/checkstyle_checks.xml b/config/checkstyle_checks.xml
index dac232b..3cf89b3 100644
--- a/config/checkstyle_checks.xml
+++ b/config/checkstyle_checks.xml
@@ -77,6 +77,7 @@
<module name="Translation">
<property name="requiredTranslations" value="de, fr, fi, es, pt, ja, tr, zh"/>
</module>
+  <module name="UniqueProperties111"/>
<module name="UniqueProperties"/>
<module name="OrderedProperties" /> …
```
> config: update 'verify-no-exception-configs' validation to not fail build if some contribution PR is referenced in description

- .ci/common.sh
- .circleci/config.yml
- .travis.yml
- shippable.yml
- wercker.yml
Looking into issue identified at https://github.com/checkstyle/checkstyle/pull/7125#issuecomment-538694543
> config: fix issue with shippable identifying commits

- src/site/resources/css/site.css
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsMobileWrapperTest.java
- src/xdocs/eclipse.xml
- src/xdocs/google_style.xml
- src/xdocs/idea.xml
- src/xdocs/netbeans.xml
- src/xdocs/property_types.xml
- src/xdocs/sponsoring.xml
- src/xdocs/sun_style.xml
- src/xdocs/writingchecks.xml
Issue: #7301
* fix check for wrapper (checked only config_*.xml files til now)
* add handling of small images
* fix display of source
> Issue #7301: fix handling of small images

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingFalse.java
#7306
Report https://strkkk.github.io/checkstyle/7306/index.html
Report for spring-integration https://strkkk.github.io/checkstyle/7306_2/index.html
> Issue #7306: fix RequireThis for method reference

- .ci/wercker.sh
- wercker.yml
> Issue #7322: add no-error-spring-integration to wercker

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
Issue #6916
Tests of the `metrics` package are migrated to Junit5.
> Issue #6916: migrate tests to junit5 for metrics package

- wercker.yml
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/745 is fixed.
> infra: activate wercker.sh no-error-checkstyles-sevntu

- .ci/wercker.sh
- wercker.yml
to verify https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/786
ATTENTION: ones sevntu PR is merged, I will remove `checkout` to branch
> infra: activate wercker no-error-sevntu-checks

- .ci/wercker.sh
- wercker.yml
missed steps from https://github.com/checkstyle/checkstyle/pull/5794
to actually activate Strata code no-error validation
their config: https://github.com/OpenGamma/OG-Tools/blob/master/build-config/src/main/resources/checkstyle/checkstyle-main-v8.26.xml
> infra: activate no-error-stata in wercker

- config/pmd-main.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
Issue https://github.com/hcoles/pitest/issues/377 seems to be resolved.
Local run of `pmd:check` succeeded on my PC.
> minor: remove obsolete pmd suppression

- .ci/appveyor.bat
- .ci/jsoref-spellchecker/whitelist.words
- appveyor.yml
#7330
testing of appveyor ability to fail build 
detected at https://github.com/checkstyle/checkstyle/pull/7193#issuecomment-541426258
> Issue #7330: Appveyor is not failing even build is failed 

- .ci/jsoref-spellchecker/whitelist.words
- .github/ISSUE_TEMPLATE.md
- src/xdocs/report_issue.xml
Each time I read issue, and I have to open documentation to make decision on approval.
It would help user to review documentation before reporting issue and for us to quickly read documentation.
> Issue template: request for link to Check

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
Issue #6916
Tests of the `whitespace` package are migrated to Junit5.
> Issue #6916: migrate tests to junit5 for whitespace package

- .ci/jsoref-spellchecker/whitelist.words
- .dependabot/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
- src/xdocs/contributing.xml
fixes #7224
releasenotes builder PR - https://github.com/checkstyle/contribution/pull/420
> Issue #7224: dependabot config to configure commit message

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java
Issue #6916
Tests of the `gui` package are migrated to Junit5.
> Issue #6916: migrate tests to junit5 for package gui

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/FilterUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/XpathUtilTest.java
Issue #6916
Tests of the `utils` package are migrated to Junit5.
> Issue #6916: migrate tests to junit5 for package utils

- config/pmd.xml
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderValid.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine2.java
Issue #6680 
Regression report: https://gmshake.github.io/checkstyle_contribution/checkstyle-tester/diff_pr_7197_3
https://romani.github.io/6680/diff/index.html
> Issue #6680: fix unexpected violation for extra empty line between package and import

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java
Issue #6916
Tests of the `xpath` package are migrated to Junit5.
> Issue #6916: migrate tests to junit5 for package xpath

- README.md
base on actions at  https://github.com/checkstyle/checkstyle/pull/7369
> config: add dependabot badge to README to ease access to it

- pom.xml
Issue #7372 
Tidy enabled and applied.
> Issue #7372: Re-enable Tidy

- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
- src/main/java/com/puppycrawl/tools/checkstyle/ThreadModeSettings.java
- src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelCounter.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
minor part of Issue #7380
part of https://github.com/checkstyle/checkstyle/pull/7193
> minor: fix violations for Issue #7380

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorBlockCommentSeparatedFromPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorBlockCommentUnderPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorClassDefinitionAndCommentNotSeparatedFromPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorModifierUnderPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleCommentSeparatedFromPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleCommentUnderPackage.java
- src/xdocs/config_whitespace.xml
#4763 
Old report [with regression false positive] https://strkkk.github.io/checkstyle/4763/index.html
New report [without false positive] https://strkkk.github.io/checkstyle/4763_2/index.html
> Issue #4763: fix empty statement for comment under package

- .ci/wercker.sh
> config: swith back to master of contribution (Issue #7329)

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/CustomImportOrderTest.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrder5.java
- src/it/resources/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/InputCustomImportOrderValid2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpanMultipleLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_OverlappingPatterns.java
Fix issue #7314 
Regression report: https://gmshake.github.io/checkstyle_contribution/checkstyle-tester/diff_pr_7365_4/
> Issue #7314: check empty line separator between import statements

- src/xdocs/cmdline.xml.vm
> doc: add info about -b cli option to documentation

- src/xdocs/cmdline.xml.vm
From https://github.com/checkstyle/checkstyle/pull/7397#discussion_r361214509
fix for a minor typo
> doc: fix treeWithJavadoc command line option

- config/suppressions.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Issue #6385
originally proposed in PR #7252
> Issue #6385: explicitly define default tokens in google_checks.xml

- src/it/java/com/google/checkstyle/test/chapter5naming/rule53camelcase/AbbreviationAsWordInNameTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAbbreviationAsWordInNameTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameAnnotation.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameAnnotationField.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameEnum.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameField.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameInterface.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameMethod.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameParameter.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/abbreviationaswordinname/SuppressionXpathRegressionAbbreviationAsWordInNameVariable.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
- src/xdocs/config_filters.xml
Issue #5777
The check `AbbreviationAsWordInName` updated to log DetailAST
> Issue #5777: Update AbbreviationAsWordInName to log DetailAST

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoArrayTrailingCommaTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/noarraytrailingcomma/SuppressionXpathRegressionNoArrayTrailingCommaOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/noarraytrailingcomma/SuppressionXpathRegressionNoArrayTrailingCommaTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noarraytrailingcomma/InputNoArrayTrailingComma.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
Fix for issue #6971.
Contribution PR: https://github.com/checkstyle/contribution/pull/436
https://sd1998.github.io/checkstyle-regression/Fix-6971/index.html
Base config:
https://sd1998.github.io/checkstyle-regression/Fix-6971/base_config.xml
Patch config:
https://sd1998.github.io/checkstyle-regression/Fix-6971/patch_config.xml
Report repo:
https://github.com/sd1998/checkstyle-regression/tree/master/Fix-6971
> Issue #6971: Added implementation for NoArrayTrailingCommaCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
Issue https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/166 is still open, but these suppressions are redundant since https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/777
> minor: remove obsolete suppressions

- .ci/travis/travis.sh
Issue #7411
with extra `echo`  just in case.
> Issue #7411: pipe cat after diff to avoid failure

- .ci/travis/travis.sh
Reverts checkstyle/checkstyle#7426
> Revert "Issue #7423: provide organization/projectKey name as checkstyle for sonar"

- .ci/travis/travis.sh
- README.md
Issue #7423 
new project page - https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle
> Issue #7423: new sonarqube project was created in checkstyle organization

- src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/comment/package-info.java
> Issue #7430: fix javadoc recognition on package with comment between

- .ci/jsoref-spellchecker/whitelist.words
- .ci/travis/travis.sh
- .ci/wercker.sh
- .travis.yml
- wercker.yml
small step for #5604 
it does not integrate Sonar to PR status in githubl, but should show statistics on sonarqube.io , I will investigate further how to make complete integration.
> Issue #5604: activation of sonar validation in PRs

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoEnumTrailingCommaTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/noenumtrailingcomma/SuppressionXpathRegressionNoEnumTrailingCommaOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/noenumtrailingcomma/SuppressionXpathRegressionNoEnumTrailingCommaTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingComma.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
Fix for issue #6972.
Contribution PR:
https://github.com/checkstyle/contribution/pull/432
https://sd1998.github.io/checkstyle-regression/Fix-6972/index.html
Old Regression Report: 
https://sd1998.github.io/checkstyle-regression/Fix-6972/old-report/index.html
Base config:
https://sd1998.github.io/checkstyle-regression/Fix-6972/base_config.xml
Patch config:
https://sd1998.github.io/checkstyle-regression/Fix-6972/patch_config.xml
Report repo:
https://github.com/sd1998/checkstyle-regression/tree/master/Fix-6972
> Issue #6972: Added implementation for NoEnumTrailingCommaCheck

- shippable.yml
> Issue #7450: match image version with image defined in 'Node Pools'

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheck.java
- src/xdocs/config_coding.xml
Issue identified at https://github.com/checkstyle/checkstyle/commit/f0af10863ff015bd4401878f73a70ced4baca46e#r36683492
> minor: fix example of module for NoArrayTrailingCommaCheck

- wercker.yml
related to #5604
skipping of build was detected at https://app.wercker.com/checkstyle/checkstyle/runs/build/5e18e7a57b63df001ac78ed9?step=5e18e7e71ccc980008300654
> config: enable sonar build on master and PRs

- src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java
Issue #5604
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AW9t2w2eYD2QG1pPXIUN&open=AW9t2w2eYD2QG1pPXIUN
> Issue #5604: resolve Sonar violation Replace this Map.get() with Map.computeIfAbsent

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
Issue #5604
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AW9t2w0PYD2QG1pPXITg&open=AW9t2w0PYD2QG1pPXITg
Should gone.
> Issue #5604: resolve Sonar violation 'Use the primitive boolean expression here'

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
Issue #5604
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AW9t2wyqYD2QG1pPXITF&open=AW9t2wyqYD2QG1pPXITF
solution taken from https://stackoverflow.com/a/23548085/1015848
> Issue #5604: resolve Sonar violation 'Use Arrays.copyOf, Arrays.asList… instead

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidNoArgumentSuperConstructorCallTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnoargumentsuperconstructorcall/SuppressionXpathRegressionAvoidNoArgumentSuperConstructorCall.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidnoargumentsuperconstructorcall/InputAvoidNoArgumentSuperConstructorCall.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
#7363
Contrib PR - https://github.com/checkstyle/contribution/pull/425
~Report https://strkkk.github.io/checkstyle/7363/index.html~
Updated report https://strkkk.github.io/checkstyle/7363_2/index.html
Report for spring integration https://strkkk.github.io/checkstyle/7363_3/index.html
> Issue #7363: add AvoidNoArgumentSuperConstructorCallCheck

- config/pmd-main.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidNoArgumentSuperConstructorCallTest.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheckTest.java
- src/xdocs/checks.xml
> fix for build

- pom.xml
> Issue #7492: enforce jdk 1.8 by maven enforcer plugin

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
Issue #7475 
we need to verify that Sonar does reports such cases as violation.
but at https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&pullRequest=7478 I see not issues at all, looks like Sonar filter out all issues that present in master, so I do not know how to make sure I actually did fix for violation.
> Issue #7475: resolve Cognitive Complexity cases above 20

- .ci/jsoref-spellchecker/whitelist.words
- release.sh
fixes #6333 
fixes #6186
taken from https://github.com/checkstyle/checkstyle/wiki/How-to-make-a-release
it finally worked well.
> updates for release.sh

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java
- src/xdocs/config_coding.xml
> doc: fix typo training -> trailing

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/xdocs/config_blocks.xml
> Issue #7174: update RightCurly doc on unsupported tokens

- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
- src/xdocs/config_misc.xml
#4074
Report https://strkkk.github.io/checkstyle/4074/index.html
Report v2 https://strkkk.github.io/checkstyle/4074_2/index.html
> Issue #4074: fix overlap between lf and crlf at file end

- src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java
- src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
https://github.com/checkstyle/checkstyle/issues/7486
> Issue #7486: Xpath implementation: relationship between getLocalPart and getStringValue

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: Add javadoc and xdoc Example for TypeName

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidDoubleBraceInitializationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoiddoublebraceinitialization/SuppressionXpathRegressionAvoidDoubleBraceInitialization.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoiddoublebraceinitialization/InputAvoidDoubleBraceInitialization.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
#6480 Added check
Report: https://strkkk.github.io/checkstyle/6480/index.html
Config PR: https://github.com/checkstyle/contribution/pull/443
> Issue #6480: Add AvoidDoubleBraceInitializationCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ElseHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IfHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodCallHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SlistHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
> Issue #7518: refactor line comparison

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: add javadoc and xdoc Example for StaticVariableName

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: add javadoc and xdoc Example for ParameterName

- src/xdocs/google_style.xml
- src/xdocs/sun_style.xml
> Issue #7505: add attention note to tables of style coverage

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java
- src/xdocs/config_whitespace.xml
#6104 
Report https://strkkk.github.io/checkstyle/6104/index.html
Report after update https://strkkk.github.io/checkstyle/6104_2/index.html
> Issue #6104: fix GenericWhitespaceCheck for ctor calls

- config/suppressions.xml
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputRightCurlyAloneOrEmptyNoViolations.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config_filters.xml
- src/xdocs/google_style.xml
Issue #6807
report: https://romani.github.io/6807-google-rightcurlyalone/diff/index.html
> Issue #6807: add suppression filter for RightCurlyAlone

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LambdaParameterNameCheck.java
- src/xdocs/config_naming.xml
> Issue #5832: add javadoc and xdoc example for LambdaParameterName

- .ci/wercker.sh
- wercker.yml
test javadoc regression on checkstyle project.
expecting wercker to fail because of issue with 1 check.
> config: added javadoc checkstyle regression

- .ci/jsoref-spellchecker/whitelist.words
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java
- src/xdocs/config_coding.xml
> Issue #7660: Add code example for StringLiteralEquality

- .ci/wercker.sh
- wercker.yml
> Issue #7705: add no error regression for contribution repo

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheck.java
- src/xdocs/config_coding.xml
```
<module name="NoClone"/>
</module>
</module>
public Object clone() {return null;} // violation, overrides the clone method
public Test clone() {return null;} // violation, overrides the clone method
public static clone(Object o) {return null;} // OK
public static clone(Test o) {return null;} // OK
}
[ERROR] /var/tmp/Test.java:3: Avoid using clone method. [NoClone]
[ERROR] /var/tmp/Test.java:5: Avoid using clone method. …
```
> Issue #7670: Update doc for NoClone

- .ci/wercker.sh
- wercker.yml
Issue #7705
Expecting similar errors from wercker as repo hasn't been updated to 8.30 and already confirmed it needs changes.
> Issue #7705: add no error regression for methods distance repo

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java
- src/xdocs/config_coding.xml
```
<module name="SimplifyBooleanReturn"/>
</module>
</module>
private boolean cond;
private Foo a;
private Foo b;
public boolean check1() {
if (cond) { // violation, can be simplified
return true;
}
else {
return false;
}
}
// Ok, simplified version of check1()
public boolean check2() {
return cond;
}
// violations, can be simplified
public boolean check3() {
if (cond == true) { // can be simplified to "if (cond)"
return false;
}
else {
return true; // can be simplified to "return !cond"
}
}
// Ok, …
```
> Issue #7659: Update doc for SimplifyBooleanReturn

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java
- src/xdocs/config_design.xml
Resolve #7614: Update doc for OneTopLevelClass
Output of default config: (there is only one config to test)
```
<module name="OneTopLevelClass"/>
</module>
</module>
D:\checkstyletest>type test\Foo.java 
public class Foo { // OK, first top-level class
// methods
}
class Foo2 { // violation, second top-level class
// methods
}
D:\checkstyletest>java -jar -Duser.language=en -Duser.country=US checkstyle-8.30-all.jar -c config.xml test\Foo.java 
[ERROR] D:\checkstyletest\test\Foo.java:5: Top-level class Foo2 has to reside in its …
```
> Issue #7614: Update doc for OneTopLevelClass

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/EmptyCatchBlockTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEmptyCatchBlockTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByComment.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyCatchBlockViolationsByVariableName.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/emptycatchblock/SuppressionXpathRegressionEmptyCatchBlock1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/emptycatchblock/SuppressionXpathRegressionEmptyCatchBlock2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7729
Updates : https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java#L238
Diff Report:
https://gaurabdg.github.io/checkstyle-tester-reports/EmptyCatchBlock/diff/index.html
> Issue #7729: Update AbstractChecks to log DetailAST - EmptyCatchBlock

- .ci/jsoref-spellchecker/whitelist.words
Testing master for word failures in other PRs.
> minor: remove words for failing master

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedAbovePackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedSingleComment.java
Issue #7534: fix NPE in MissingDeprecatedCheck
diff report here: https://www.nickmancuso.dev/hosting/diff/index.html
> Issue #7534: fix NPE in MissingDeprecatedCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
- src/xdocs/config_misc.xml
Fixes Issue: #7594 
$ cat config2.xml
<module name="UncommentedMain"/>
</module>
</module>
$ cat Test2.java
public class Game{
public static void main(String[] args){}  // violation
}
public class Main{
public static void main(String[] args){}  // violation
}
public class Launch{
//public static void main(String[] args){} // OK
}
$ java -jar checkstyle-8.29-all.jar -c config2.xml Test2.java
[ERROR] D:\OpenSource\TestCommit\Test2.java:2: Uncommented main method found. [UncommentedMain]
[ERROR] D:\OpenSource\TestCommit\Test2.java:6: …
> Issue #7594: Update doc for UncommentedMain

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java
- src/xdocs/config_metrics.xml
> Issue #7689: update doc for BooleanExpressionComplexity

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoCloneTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/noclone/SuppressionXpathRegressionNoCloneOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/noclone/SuppressionXpathRegressionNoCloneTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Resolve #7751 : Update AbstractChecks to log DetailAST - NoClone
Diff report link : https://wilcoln.github.io/checkstyle-reports/7751/diff/index.html
> Issue #7751: Update AbstractChecks to log DetailAST - NoClone

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java
- src/xdocs/config_coding.xml
```
<module name="SimplifyBooleanExpression"/>
</module>
</module>
public void bar() {
boolean a, b;
Foo c, d, e;
if (!false) {}; // violation, can be simplfied to true
if (a == true) {}; // violation, can be simplified to a
if (a == b) {}; // OK
if (a == false) {}; // violation, can be simplfied to !a
if (!(a != true)) {}; // violation, can be simplified to a
e = (a || b) ? c : d; // OK
e = (a || false) ? c : d; // violation, can be simplified to a
e = (a && b) ? c : d; // OK
}
}
$ java -jar …
```
> Issue #7658: Update doc for SimplifyBooleanExpression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
- src/xdocs/config_regexp.xml
Resolve #7698
> The default config does not match to anything, so there is no need for an example for it.
```xml
<module name="RegexpSinglelineJava">
<property name="format" value="System\.out\.println"/>
<property name="ignoreComments" value="true"/>
</module>
</module>
</module>
```
```java
public void main(){
System.out.println(""); // violation, the illegal pattern is matched on a single line
System.out.
println(""); // OK		
/* System.out.println */ // OK, comments are ignored
}
}
```
$ java …
> Issue #7698: Add code examples for RegexpSinglelineJava

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheck.java
- src/xdocs/config_coding.xml
```xml
<module name="SuperClone"/>
</module>
</module>
```
```java
class A {
public Object clone() { // OK
return super.clone();
}
}
class B {
private int b;
public B clone() { // violation, does not call super.clone()
B other = new B();
other.b = -1;
return other;
}
}
class C {
public C clone() {  // OK
return (C) super.clone();
}
}
```
```
[ERROR] /var/tmp/Test.java:11:11: Method 'clone' should call 'super.clone'. [SuperClone]
Audit done. …
```
> Issue #7661: Update doc for SuperClone

- src/it/java/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/NoFinalizerTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoFinalizerTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nofinalizer/SuppressionXpathRegressionNoFinalizer1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nofinalizer/SuppressionXpathRegressionNoFinalizer2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Fixes Issue #7752
Log Update:
https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java#L86
Diff report:
https://gaurabdg.github.io/checkstyle-tester-reports/NoFinalizer/diff/index.html
> Issue #7752: Update AbstractChecks to log DetailAST - NoFinalizer

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheck.java
- src/xdocs/config_coding.xml
Fixes Issue: #7653 
**Output of default Exmaple**
```
<module name="NestedTryDepth"/>
</module>
</module>
```
```
public static void defaultTest() {
try {
try {
try { // violation, current depth is 2, max default allowed depth is 1
} catch (Exception e) {
}
} catch (Exception e) {
}
} catch (Exception e) {
}
}
}
```
```
java -jar checkstyle-8.30-all.jar -c config.xml Test.java
[ERROR] /home/abhishek99/checkstyleTest/Test.java:5:17: Nested try depth is 2 (max allowed is 1). [NestedTryDepth]
Audit done.
Checkstyle ends with …
```
> Issue #7653: Updated doc for NestedTryDepth

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMissingOverrideTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingoverride/SuppressionXpathRegressionMissingOverrideAnonymous.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingoverride/SuppressionXpathRegressionMissingOverrideClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingoverride/SuppressionXpathRegressionMissingOverrideInheritDocInvalid1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingoverride/SuppressionXpathRegressionMissingOverrideInheritDocInvalid2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingoverride/SuppressionXpathRegressionMissingOverrideInterface.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7748: Update AbstractChecks to log DetailAST - MissingOverride
https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java#L150
https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheck.java#L170
Diff report:
default:
https://huganghui.github.io/7748-DetailAST-missing-over-ride/reports1/diff/
javaFiveCompatibility property:
https://huganghui.github.io/7748-DetailAST-missing-over-ride/reports2/diff/
> Issue #7748: Update AbstractChecks to log DetailAST - MissingOverride

- .circleci/config.yml
Fixes Issue #7832 
Please ignore, because I am testing the CI.
> Issue #7832: Publish pitest report as artifact at circleci

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule485annotations/AnnotationLocationTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAnnotationLocationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationAnnotation.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationCTOR.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationEnum.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationInterface.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationMethod.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/annotationlocation/SuppressionXpathRegressionAnnotationLocationVariable.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
This resolves #7768 
https://malintha1996.github.io/checkstyle-tester-reports/AnnotationLocation/diff/index.html
Update AbstractChecks to log DetailAST - AnnotationLocation
> Issue #7768: Update AbstractChecks to log DetailAST - AnnotationLocation

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPackageAnnotationTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packageannotation/SuppressionXpathRegressionPackageAnnotationOne.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packageannotation/SuppressionXpathRegressionPackageAnnotationTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/package-info.java
- src/xdocs/config_filters.xml
Resolve #7757 : Update AbstractChecks to log DetailAST - PackageAnnotation
Diff report link : https://wilcoln.github.io/checkstyle-reports/7757/diff/index.html
The diff output is ok, with no new violation reported for all the projects.
> Issue #7757: Update AbstractChecks to log DetailAST - PackageAnnotation

- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule332nolinewrap/NoLineWrapTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoLineWrapTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nolinewrap/SuppressionXpathRegressionNoLineWrap1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nolinewrap/SuppressionXpathRegressionNoLineWrap2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nolinewrap/SuppressionXpathRegressionNoLineWrap3.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
resolves Issue #7753 
[Diff Report](https://abhishek-kumar09.github.io/7753/reports/diff/index.html)
> Issue #7753: Update AbstractChecks to log DetailAST - NoLineWrap

- wercker.yml
from https://github.com/checkstyle/checkstyle/pull/7870#issuecomment-599868948
no validation, just printing status.
> infra: update wercker to print content of .ci-temp and git status

- src/main/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
> minor: fix missed space violation from JavadocMissingWhitespaceAfterAsteriskCheck

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidStaticImportTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstaticimport/SuppressionXpathRegressionAvoidStaticImport1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstaticimport/SuppressionXpathRegressionAvoidStaticImport2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault.java
- src/xdocs/config_filters.xml
Fixes Issue #7726 
Log Update:
https://github.com/checkstyle/checkstyle/blob/5ec8cfe4ded197c67f0f4bb8edfddde1d34d78c1/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java#L128
Diff Report: https://gaurabdg.github.io/checkstyle-tester-reports/regression/AvoidStaticImport/diff/index.html
> Issue #7726: Update AbstractChecks to log DetailAST - AvoidStaticImport

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMissingCtorTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingctor/SuppressionXpathRegressionMissingCtor1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingctor/SuppressionXpathRegressionMissingCtor2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtor2.java
- src/xdocs/config_filters.xml
Issue #7744: Update AbstractChecks to log DetailAST - MissingCtor
https://github.com/checkstyle/checkstyle/blob/5ec8cfe4ded197c67f0f4bb8edfddde1d34d78c1/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheck.java#L71
Diff report:
https://huganghui.github.io/7744-DetailAST-missing-ctor/reports/diff/
> Issue #7744: Update AbstractChecks to log DetailAST - MissingCtor

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionFinalClassTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finalclass/SuppressionXpathRegressionFinalClass1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/finalclass/SuppressionXpathRegressionFinalClass2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7731: Update AbstractChecks to log DetailAST - FinalClass
https://github.com/HuGanghui/checkstyle/blob/960d437846eb39ae1a52791528d73867c08982bf/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java#L137
diff report:
https://huganghui.github.io//7731-DetailAST-final-class/reports/reports/diff/
> Issue #7731: Update AbstractChecks to log DetailAST - FinalClass

- src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java
> Issue #7885: pitest problem with coverage in SuppressWarningsHolder

- src/it/java/com/google/checkstyle/test/chapter3filestructure/rule331nowildcard/AvoidStarImportTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidStarImportTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstarimport/SuppressionXpathRegressionAvoidStarImport1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidstarimport/SuppressionXpathRegressionAvoidStarImport2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Fixes Issue #7725 
Log update:
https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java#L240
diff report:
https://akki111singh.github.io/diff/index.html
> Issue #7725: Update AbstractChecks to log DetailAST - AvoidStarImport

- .ci/jsoref-spellchecker/whitelist.words
- .ci/travis/travis.sh
- .travis.yml
- wercker.yml
Resolves Issue  #7810 and #7534
> Issue #7534: Add pmd build item

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUncommentedMainTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/uncommentedmain/SuppressionXpathRegressionUncommentedMain.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/uncommentedmain/SuppressionXpathRegressionUncommentedMainTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7764 
Update AbstractChecks to log DetailAST - UncommentedMain
Report : https://amrdeveloper.github.io/checkstyle-reports/7764/
> Issue #7764: Update AbstractChecks to log DetailAST - UncommentedMain

- src/xdocs/config_whitespace.xml
doc: fix typo in config_whitespace.xml
> doc: fix typo in config_whitespace.xml

- .ci/wercker.sh
- wercker.yml
Fixes Issue #7914 
Add spoon to no exception in wercker.sh
> Issue #7914: add spoon project to no-exception testing

- .ci/pitest.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java
> Issue #7854: Resolve Pitest Issues - IllegalImportCheck (1)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java
- src/xdocs/config_metrics.xml
Updated docs for for JavaNCSS. 
Solves issue #7693 
**CLI TEST RESULT :**
1. Default config
```
Gauravs-MacBook-Pro:checkstyle gauravpunjabi$ cat config.xml 
<module name="JavaNCSS"/>
</module>
</module>Gauravs-MacBook-Pro:checkstyle gauravpunjabi$ java -jar target/checkstyle-8.31-SNAPSHOT-all.jar -c config.xml Test.java 
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:2:5: NCSS for this method is 51 (max allowed is 50). [JavaNCSS]
Audit done.
``` 
2. Check with 40 allowed uncommented lines
``` …
```
> Issue #7693: update doc for JavaNCSS

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/xdocs/config_coding.xml
Issue: #7648: add doc for magic number
Screenshot of the website
Screenshot of the default behavior:
Screenshot after adding the config:
> Issue: #7648: add doc for magic number

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/xdocs/config_coding.xml
Issue #7666: Add documentation examples for InnerAssignment check
Here is the website:
There is only a single (default) config on the site:
```
$ cat check.xml
<module name="InnerAssignment"/>
</module>
</module>
void foo() {
int a, b;
a = b = 5; // violation, assignment to each variable should be in a separate statement
a = b += 5; // violation
a = 5; // OK
b = 5; // OK
a = 5; b = 5; // OK
double myDouble;
double[] doubleArray = new double[] {myDouble = 4.5, 15.5}; // violation
String nameOne;
List<String> myList = new …
```
> Issue #7666: Add documentation examples for InnerAssignment check

- .ci/travis/travis.sh
minor: add "cd -" to removeFolderWithProtectedFiles, per discussion at https://github.com/checkstyle/checkstyle/pull/7816#discussion_r395072027
> minor: add "cd -" to removeFolderWithProtectedFiles

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda5.java
…lambda indentations
Fixes #5969 and closes #7675
I just hope to live a happy life of Minecraft modding. Thank you for this great checkstyle! https://github.com/FabricMC/fabric/pull/518/files#diff-23a850fe9b00699c6f6cd295e8ef341d
> Issue #5969: Respect and expect tab width in column number check for lambda indentations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
- src/xdocs/config_metrics.xml
Issue #7694: added code examples
---
```
<module name="NPathComplexity"/>
</module>
</module>
public abstract class Test {
final int a = 0;
int b = 0;
public void foo() { // OK, NPath complexity is less than default threshold
// function consists of one if-else block with an NPath Complexity of 3
if (a > 10) {
if (a > b) { // nested if-else decision tree adds 2 to the complexity count
buzz();
} else {
fizz();
}
} else { // last possible outcome of the main if-else block, adds 1 to complexity
buzz();
}
}
public void boo() { // …
```
> Issue #7694: update doc for NPathComplexity

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java
- src/xdocs/config_design.xml
Update doc for ThrowsCount
Solves issue: #7615 
**Cli Output**
Default Config:
```
Karunas-MacBook-Pro:checkstyle Harsh$ cat config.xml 
<module name="ThrowsCount"/>
</module>
</module>
Karunas-MacBook-Pro:checkstyle Harsh$ cat Test.java 
class Test {
public void failTest() throws CloneNotSupportedException,
ArrayIndexOutOfBoundsException,
StringIndexOutOfBoundsException,
IllegalStateException,
NullPointerException { // violation, max allowed is 4
// body
}
public void successTest() throws ArithmeticException,
NumberFormatException { // ok
//body
}
private void privateTest() throws …
```
> Issue #7615: Update doc for ThrowsCount

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
Fix for Issue #7855 
Pitest Report
https://harsh-kukreja.github.io/pitest-report-before/com.puppycrawl.tools.checkstyle.checks.imports/IllegalImportCheck.java.html
Diff Report:
https://harsh-kukreja.github.io/IllegalImportCheckDiffReport3/
As per the decision in comment:
https://github.com/checkstyle/checkstyle/issues/7855#issuecomment-604737052
> Issue #7855: Resolve Pitest Issues - IllegalImportCheck (2)

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnnecessarySemicolonAfterOuterTypeDeclarationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessarysemicolonafteroutertypedeclaration/SuppressionXpathRegressionUnnecessarySemicolonAfterOuterTypeDeclaration.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessarysemicolonafteroutertypedeclaration/SuppressionXpathRegressionUnnecessarySemicolonAfterOuterTypeDeclarationInnerTypes.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterOuterTypeDeclarationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclaration.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
Fixes Issue #7677 
Diff report: https://strkkk.github.io/7677/index.html 
Contrib repo PR: https://github.com/checkstyle/contribution/pull/464
> Issue #7677: add UnnecessarySemicolonAfterOuterTypeDeclarationCheck

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java
Resolve #7981
Please see comments in #7981 for all the details.
> Issue #7981: Resolve Pitest Issues - DetectorOptions

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheck.java
- src/xdocs/config_annotation.xml
Resolve #7846 
**New description :**
> Issue #7846: Update doc on description of package annotation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/xdocs/config_naming.xml
Closes #8005: config_naming has inconsistent tag usage
Generated site: https://shashwat70.github.io//site/config_naming.html
> Issue #8005: config_naming has inconsistent tag usage

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java
Fix #7812: OneTopLevelClass: Improve data structure efficiency
Even though this is not really important, I feel that I should at least tie up the loose end from https://github.com/checkstyle/checkstyle/pull/7790#discussion_r389439081. Right now using a `SortedMap` just to store a redundant line number is an awkward implementation, no matter how you look at it.
Regression: https://wltan.github.io/checkstyle-reports/2020-03-26/onetoplevel-detailast-regression/diff/
> Issue #7812: OneTopLevelClass: Improve data structure efficiency

- config/checkstyle_resources_checks.xml
> minor: update comments over suppression to clearly define until issue

- .ci/wercker.sh
Issue #7892: Improve clean up of .ci-temp directory
> Issue #7892: Improve clean up of .ci-temp directory

- .travis.yml
Issue #8014
https://docs.travis-ci.com/user/build-config-validation/
> Issue #8014: resolve travis config issues

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
> Issue #7978: Resolve Pitest Issues - JavadocMethodCheck (6)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheck.java
- src/xdocs/config_misc.xml
Fixes: #7596 
**output:**
```
<module name="UpperEll"/>
</module>
</module>
class Test {
long var1 = 508987; // OK
long var2 = 508987l; // violation
long var3 = 508987L; // OK
}
kaustubh@dxtk:~$ java -jar checkstyle-8.30-all.jar -c Test.xml Test.java
[ERROR] /home/kaustubh/Test.java:3:15: Should use uppercase 'L'. [UpperEll]
Audit done.
```
@timurt please review.
> Issue #7596: Update doc for UpperEll

- config/checkstyle_resources_checks.xml
- config/checkstyle_resources_suppressions.xml
- src/it/resources/org/checkstyle/suppressionxpathfilter/nolinewrap/SuppressionXpathRegressionNoLineWrap2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationGuavaFalsePositive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/grammar/InputRegressionJava8Class2.java
Resolves #8020: resolve Trailing whitespace violations in test resources
> Issue #8020: resolve Trailing whitespace violations in test resources

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMethodCountTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodcount/SuppressionXpathRegressionMethodCount1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodcount/SuppressionXpathRegressionMethodCount2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodcount/SuppressionXpathRegressionMethodCount3.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/methodcount/SuppressionXpathRegressionMethodCount4.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Closes #7743: Update AbstractChecks to log DetailAST - MethodCount
Diff report: https://shashwat70.github.io/diff1/
> Issue #7743: Update AbstractChecks to log DetailAST - MethodCount

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionInterfaceIsTypeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfaceistype/SuppressionXpathRegressionInterfaceIsType1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfaceistype/SuppressionXpathRegressionInterfaceIsType2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7735: Update AbstractChecks to log DetailAST - InterfaceIsType
diff report : 
https://huganghui.github.io/7735-DetailAST-InterfaceIsType/reports/
> Issue #7735: Update AbstractChecks to log DetailAST - InterfaceIsType

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
- src/xdocs/config_metrics.xml
Fixes #7692
```
<module name="CyclomaticComplexity">
</module>
</module>
</module>
Shrey@PREDATOR-PH315-51 MINGW64 ~/Desktop/Checkstyle jar
class CyclomaticComplexity {
// Cyclomatic Complexity = 11
int a, b, c, d, n;
public void foo() { // 1, function declaration
if (a == 1) { // 2, if
fun1();
} else if (a == b // 3, if
&& a == c) { // 4, && operator
if (c == 2) { // 5, if
fun2();
}
} else if (a == d) { // 6, if
try {
fun4();
} catch (Exception e) { // 7, catch
}
} else {
switch(n) {
case 1: // 8, case
fun1();
break;
case 2: // 9, case
fun2();
break;
case 3: …
```
> Issue #7692: Update doc for CyclomaticComplexity

- codeship-steps.yml
to address https://app.codeship.com/projects/124310/builds/541d9e46-3936-48e2-8c92-f5ecc9c772ce
```
2020-04-04 23:22:30 system build/pull started
2020-04-04 23:22:41 system build/pull finished successfully
2020-04-04 23:22:42 system ls: unrecognized option: 
2020-04-04 23:22:42 system 
2020-04-04 23:22:42 system BusyBox v1.27.2 (2018-01-29 15:48:57 GMT) multi-call binary.
2020-04-04 23:22:42 system 
2020-04-04 23:22:42 system Usage: ls [-1AaCxdLHRFplinshrSXvctu] [-w WIDTH] [FILE]...
2020-04-04 23:22:42 system 
2020-04-04 23:22:42 system List directory contents
2020-04-04 23:22:42 system 
2020-04-04 23:22:42 system   -1  One column output
2020-04-04 23:22:42 system   -a  Include entries which start with .
2020-04-04 23:22:42 system   -A  Like -a, but exclude . and ..
2020-04-04 23:22:42 …
```
> ci: fix failure in codeship to recognize multiline commands

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
> Issue #7767: Moved WriteTag to list of javadoc checks in SuppressionXpathFilter doc

- .ci/jsoref-spellchecker/whitelist.words
- .ci/semaphore.sh
- .ci/semaphore.yml
- README.md
> Issue #8051: set up semaphore CI

- src/xdocs/config_blocks.xml
Resolves #8011: Wrong tag usage in NeedBraces Check
Generated site: https://shashwat70.github.io//site/config_blocks.html
> Issue #8011: Wrong tag usage in NeedBraces Check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java
- src/xdocs/config_metrics.xml
Closes #7691 
Site: https://shashwat70.github.io/site/config_metrics.html#ClassFanOutComplexity
Default config (Good):
```
C:\Users\Shashwat\Documents>cat config.xml
<module name="ClassFanOutComplexity"/>
</module>
</module>
C:\Users\Shashwat\Documents>cat Test.java
public class InputClassComplexity {
Set set = new HashSet(); // Set, HashSet ignored due to default excludedClasses property
Map map = new HashMap(); // Map, HashMap ignored due to default excludedClasses property
public Date date = new Date(); // Counted, 1
public Time time = new Time(); // Counted, 2
public Place place = new …
```
> Issue #7691: ClassFanOutComplexity doc update

- src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderOption.java
Fixes the violations that are generated after solving issue #6722 
PR Link for Check: [MissingLeadingAsterisk](https://github.com/checkstyle/checkstyle/pull/8085)
> doc: add leading asterisks for javadoc

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavadocTypeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadoctype/SuppressionXpathRegressionJavadocTypeOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadoctype/SuppressionXpathRegressionJavadocTypeThree.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadoctype/SuppressionXpathRegressionJavadocTypeTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Resolve #7741: Update AbstractChecks to log DetailAST - JavadocType
Regression: http://wltan.github.io/checkstyle-reports/2020-04-09/javadoctype-detailast/index.html
> Issue #7741: Update AbstractChecks to log DetailAST - JavadocType

- src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/before.LocalizedMessage.java.html
After Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.LocalizedMessage.java.html
> minor: Optimize method distance in checkstyle.api.LocalizedMessage

- src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/before.AbstractCheck.java.html
After Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.AbstractCheck.java.html
> minor: Optimize method distance in checkstyle.api.AbstractCheck

- src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/before.FullIdent.java.html
After Optimization:
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FullIdent.java.html
> minor: Optimize method distance in checkstyle.api.FullIdent

- src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/before.FileContents.java.html
After Optimization: 
https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FileContents.java.html
> minor: Optimize method distance in checkstyle.api.FileContents

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Fixes: #7759 & #7760 
Website view:
@rnveach @romani Minor issue. please review
> Issue #7759: Regexp & RegexpSinglelineJava check does not support SuppressionXpathFilter.

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/NoWhitespaceBeforeTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeColonOfLabel.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeDefault.java
- src/xdocs/config_whitespace.xml
Resolve #8124 
Diff report : https://wilcoln.github.io/checkstyle-reports/8124/diff/index.html
NB: https://github.com/checkstyle/checkstyle/pull/8123 should be merged before this PR.
> Issue #8124: Add LABELED_STAT token support to NoWhitespaceBefore

- .ci/shippable.sh
- shippable.yml
Update for #7892: clean up after Shippable runs.
> Issue #7892: clean up after shippable

- src/main/java/com/puppycrawl/tools/checkstyle/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Resolves #8181 
Discussion at https://github.com/checkstyle/checkstyle/pull/8035#discussion_r414608281
@romani @rnveach Please review and merge this as the parent PR dependts on this and I cant push changes till then.
> Issue #8181: Remove cli options -C and -W

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionInterfaceMemberImpliedModifierTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfacememberimpliedmodifier/SuppressionXpathRegressionInterfaceMemberImpliedModifier1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfacememberimpliedmodifier/SuppressionXpathRegressionInterfaceMemberImpliedModifier2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/interfacememberimpliedmodifier/SuppressionXpathRegressionInterfaceMemberImpliedModifier3.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
> Issue #7736: Integration tests added for InterfaceMemberImpliedModifier

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnnecessarySemicolonAfterTypeMemberDeclarationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessarysemicolonaftertypememberdeclaration/SuppressionXpathRegressionUnnecessarySemicolonAfterTypeMemberDeclarationTokens.java
> Issue #8151: Update XpathRegressionUnnecessarySemicolonAfterTypeMembr to have atleast 2 tests

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSingleSpaceSeparatorTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/singlespaceseparator/SuppressionXpathRegressionSingleSpaceSeparatorValidateComments.java
> Issue #8151: Update XpathRegressionSingleWhiteSpace to have atleast 2 tests

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheck.java
- src/xdocs/config_coding.xml
Fixes #7664 
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ cat config.xml 
<module name="AvoidInlineConditionals"/>
</module>
</module>gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ java -jar target/checkstyle-8.32-SNAPSHOT-all.jar -c config.xml Test.java 
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:4:35: Avoid inline conditionals. [AvoidInlineConditionals]
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:5:43: Avoid inline conditionals. [AvoidInlineConditionals]
[ERROR] …
```
> Issue #7664: Update doc for AvoidInlineConditionals

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoWhitespaceBeforeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebefore/SuppressionXpathRegressionNoWhitespaceBeforeLineBreaks.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebefore/SuppressionXpathRegressionNoWhitespaceBeforeTokens.java
> Issue #8151: Update XpathRegressionNoWhitespaceBefore to have atleast 2 tests

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoWhitespaceAfterTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespaceafter/SuppressionXpathRegressionNoWhitespaceAfterLineBreaks.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespaceafter/SuppressionXpathRegressionNoWhitespaceAfterTokens.java
> Issue #8151: Update XpathRegressionNoWhitespaceAfter to have atleast 2 tests

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionOuterTypeNumberTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/outertypenumber/SuppressionXpathRegressionOuterTypeNumberDefault.java
> Issue #8151: Update XpathRegressionOuterTypeNumber to have atleast 2 tests

- .ci/jsoref-spellchecker/whitelist.words
- .github/CODE_OF_CONDUCT.md
> Issue #7833: Create code of conduct

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNestedIfDepthTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nestedifdepth/SuppressionXpathRegressionNestedIfDepthMax.java
> Issue #8151: Update XpathRegressionNestedIfDepthTest to have atleast 2 tests

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheck.java
- src/xdocs/config_coding.xml
Fixes #7667 
```
gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$ cat config.xml 
<module name="MissingCtor"/>
</module>
</module>gauravpunjabi@Gauravs-MacBook-Pro:~/Coding/Open Source/checkstyle$  java -jar target/checkstyle-8.33-SNAPSHOT-all.jar -c config.xml Test.java 
[ERROR] /Users/gauravpunjabi/Coding/Open Source/checkstyle/Test.java:8:1: Class should define a constructor. [MissingCtor]
Audit done.
```
> Issue #7667: Update doc for MissingCtor

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidDoubleBraceInitializationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoiddoublebraceinitialization/SuppressionXpathRegressionAvoidDoubleBraceInitializationTwo.java
Partially resolves issue #8151
> Issue #8151: Update XpathRegressionAvoidDoubleBraceInitializationTest to have atleast 2 tests

- src/xdocs/beginning_development.xml
> Issue #8198: Fixed beginning development instructions

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNestedForDepthTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nestedfordepth/SuppressionXpathRegressionNestedForDepthMax.java
> Issue #8151: Update XpathRegressionNestedForDepthTest to have atleast 2 tests.

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnnecessarySemicolonInEnumerationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessarysemicoloninenumeration/SuppressionXpathRegressionUnnecessarySemicolonInEnumerationAll.java
> Issue #8151: Update XpathRegressionUnnecessarySemicolonInEnumerationTest to have atleasts 2 tests

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAvoidNoArgumentSuperConstructorCallTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/avoidnoargumentsuperconstructorcall/SuppressionXpathRegressionAvoidNoArgumentSuperConstructorCallInnerClass.java
Partially resolves issue #8151
> Issue #8151: Update XpathRegressionAvoidNoArgumentSuperConstructorCallCheckTest to have at least 2 tests

- config/checkstyle_non_main_files_suppressions.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNestedTryDepthTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nestedtrydepth/SuppressionXpathRegressionNestedTryDepthMax.java
> Issue #8151: Update XpathRegressionNestedTryDepthTest to have atleat 2 tests.

- pom.xml
> Issue #8219: show grammar classe in reports and update minimum values

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/xdocs/config_javadoc.xml
https://app.codeship.com/projects/124310/builds/dc4242e3-d374-4c1e-96cb-275dd96d9518?line=029472bc-d43e-4876-b180-2562884ecffd&step=parallel_.ci%2Frun-link-check-plugin.sh
can be merged if codeship does not report problem with 'firstsentence' links, there might be some other problems, will be addressed in some next PR.
> minor: fix links (link-check-plugin)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
> minor: fix TC violations

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java
- src/xdocs/config_coding.xml
Issue #7671: added coding Example.
protected void finalize() throws Throwable { // violation
try {
System.out.println("overriding finalize()");
} catch (Throwable t) {
throw t;
} finally {
super.finalize();
}
}
}
$ java -jar checkstyle-8.31-all.jar -c /google_checks.xml Test.java
[WARN] /mnt/c/Users/Ipowe/Desktop/Test.java:3:5: Avoid using finalizer method. [NoFinalizer]
Audit done.
> Issue #7671: Update doc for NoFinalizer

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
fixes: #7873 
@rnveach @strkkk  Please review.
> Issue #7873: Resolve Pitest Issues - ImportOrderCheck (2)

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
> Issue #7804: Resolve Pitest Issues - CustomImportOrderCheck (3)

- .ci/jsoref-spellchecker/whitelist.words
- .ci/travis/travis.sh
- .travis.yml
Issue #3786
continuation of #8136
> Issue #3786: enable JOSM in Travis CI

- .ci/common.sh
- .ci/jsoref-spellchecker/whitelist.words
- .ci/shippable.sh
- .ci/travis/travis.sh
- .circleci/config.yml
- .travis.yml
- buddy.yml
- codeship-steps.yml
- config/checkstyle_checks.xml
- config/checkstyle_non_main_files_checks.xml
- config/checkstyle_non_main_files_suppressions.xml
- config/checkstyle_sevntu_checks.xml
- config/default_sonar_profile.xml
- config/import-control.xml
- config/intellij-idea-inspections.xml
- config/pmd-test.xml
- config/sevntu_suppressions.xml
- config/spotbugs-exclude.xml
- config/suppressions-xpath.xml
- config/suppressions.xml
- pom.xml
- shippable.yml
- src/test/resources/com/puppycrawl/tools/checkstyle/configurationloader/InputConfigurationLoaderMissingConfigParent.xml
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilter.xml
- src/xdocs/releasenotes_old.xml
Issue #8169: Making regex to validate missed space in comments in non main files
> Issue #8169: Making regex to validate missed space in comments in non files

- src/main/resources/sun_checks.xml
Fix two broken links in sun_checks.xml
> spelling: Fix broken links in sun_checks.xml

- config/ant-phase-verify.xml
> Issue #8256: convert ant's echo to info level

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheck.java
- src/xdocs/config_metrics.xml
Closes #7690  : update doc for ClassDataAbstractionCoupling
Site: https://shashwat70.github.io/site/config_metrics.html#ClassDataAbstractionCoupling
Default config (Good):
```
C:\Users\Shashwat\Documents>cat config.xml
<module name="ClassDataAbstractionCoupling"/>
</module>
</module>
C:\Users\Shashwat\Documents>cat Test.java
class InputClassCoupling {
Set set = new HashSet(); // HashSet ignored due to default excludedClasses property
Map map = new HashMap(); // HashMap ignored due to default excludedClasses property
Date date = new Date(); // Counted, 1
Time time = new Time(); // Counted, 2 …
```
> Issue #7690: ClassDataAbstractionCoupling doc update

- .travis.yml
Issue #8275
This build should fail until #8263 is fixed.
> Issue #8275: verify tests with spotbugs

- .travis.yml
minor: fix nonsense message in travis output
> minor: fix nonsense message in travis output

- .ci/wercker.sh
Issue #8279
I am not sure I can send PR to project to ignore certificate.
> Issue #8279: ignore certificate of sonarcloud

- .ci/jsoref-spellchecker/whitelist.words
- config/pmd-test.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
> Issue #7469: Use ArchUnit library to control source code

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionUnnecessaryParenthesesTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses2.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses3.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses4.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses5.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses6.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses7.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/unnecessaryparentheses/SuppressionXpathRegressionUnnecessaryParentheses8.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
> Issue #7765: XpathRegression tests added for UnnecessaryParentheses

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMissingJavadocTypeTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadoctype/SuppressionXpathRegressionMissingJavadocTypeAnnotation.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadoctype/SuppressionXpathRegressionMissingJavadocTypeClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadoctype/SuppressionXpathRegressionMissingJavadocTypeExcluded.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadoctype/SuppressionXpathRegressionMissingJavadocTypeScope.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/missingjavadoctype/SuppressionXpathRegressionMissingJavadocTypeToken.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7747: Update AbstractChecks to log DetailAST - MissingJavadocType
> Issue #7747: Update AbstractChecks to log DetailAST - MissingJavadocType

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionTodoCommentTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/todocomment/SuppressionXpathRegressionTodoCommentOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/todocomment/SuppressionXpathRegressionTodoCommentTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7762: Update AbstractChecks to log DetailAST - TodoComment
> Issue #7762: Update AbstractChecks to log DetailAST - TodoComment

- config/ant-phase-verify.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java14/InputJava14Records.java
Issue #8023: Add records input
Examples taken from:
https://blogs.oracle.com/javamagazine/records-come-to-java
https://alidg.me/blog/2020/2/9/java14-records-in-depth
https://openjdk.java.net/jeps/359
compilation is checked by:
https://github.com/checkstyle/checkstyle/blob/15ba4ccd6adfa2486658d5b36588831c1a1006d3/.travis.yml#L289-L293
> Issue #8023: Add input file for Java14 records 

- config/ant-phase-verify.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java14/InputJava14InstanceofWithPatternMatching.java
Issue #7290: Add input file for Java14 instanceof with pattern matching
Example code taken from:
https://jaxenter.com/pattern-matching-for-instanceof-in-java-14-169830.html
https://www.baeldung.com/java-pattern-matching-instanceof
https://openjdk.java.net/jeps/305
The last three code snippets were troublesome in testing grammar, so I included them even though they really aren't pattern matching examples.
> minor: Add input file for Java14 instanceof with pattern matching (#7290)

- src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g
Issue #8274: Update java.g to allow new tokens to be added
> Issue #8274: Update java.g to allow new tokens to be added

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavadocMethodTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadocmethod/SuppressionXpathRegressionJavadocMethodFive.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadocmethod/SuppressionXpathRegressionJavadocMethodFour.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadocmethod/SuppressionXpathRegressionJavadocMethodOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadocmethod/SuppressionXpathRegressionJavadocMethodThree.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/javadocmethod/SuppressionXpathRegressionJavadocMethodTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Issue #7739: Update AbstractChecks to log DetailAST - JavadocMethod
this PR is based on comments in Issue #7739 and PR #8214  
diff report: https://huganghui.github.io/7739-JavadocMethod//diff/
> Issue #7739: Update AbstractChecks to log DetailAST - JavadocMethod

- .ci/jsoref-spellchecker/whitelist.words
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- src/xdocs/report_issue.xml
Resolves #7834 
I've updated the issue template for this repository as the issue expects.
I've added two types namely, a bug report and a feature request. Moreover, I've also enabled the provision for a blank issue. Please let me know if this fine.
Looking at this might be helpful: https://github.com/nodejs/node/tree/master/.github/ISSUE_TEMPLATE
Updated doc look like:
https://shashwat70.github.io/site/report_issue.html
> Issue #7834: Issue template updated to new format

- wercker.yml
> Issue #8325: use maven 3.6.3-jdk-11 for wercker build

- pom.xml
from https://app.codeship.com/projects/124310/builds/a450593b-9563-4355-a204-ca613dbc1440?line=b20e85ed-69fc-493b-8d75-1c1e45dfe6a9&step=parallel_.ci%2Frun-link-check-plugin.sh
```
2020-06-21 08:54:24
system <td><i><a class="externalLink" href="https://opencollective.com/checkstyle/">https://opencollective.com/checkstyle/</a>: 403 Forbidden</i></td></tr>
2020-06-21 08:54:24
system <td><i><a class="externalLink" href="https://opencollective.com/checkstyle/backers/badge.svg">https://opencollective.com/checkstyle/backers/badge.svg</a>: 403 Forbidden</i></td></tr>
2020-06-21 08:54:24
system <td><i><a class="externalLink" href="https://opencollective.com/checkstyle/sponsors/badge.svg">https://opencollective.com/checkstyle/sponsors/badge.svg</a>: 403 Forbidden</i></td></tr></table></td></tr> …
```
> minor: exclude links to opencollective

- src/xdocs/cmdline.xml.vm
from https://github.com/checkstyle/checkstyle/pull/8247
> doc: add example of how to run GUI from snapshot jar

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
Resolves Issue #8336 
conflict: https://sonarcloud.io/project/issues?fileUuids=AW9t2waOYD2QG1pPXIEf&id=org.checkstyle%3Acheckstyle&open=AXLiCslKkpVZ0x1TON5t&resolved=false
> Issue #8336: resolve sonar violation caused due to PR #8038

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierTryWithResources.java
Resolves #8299 
Reg report (no diff): https://strkkk.github.io/checkstyle/8299/index.html
> Fix NPE in RedundantModifierCheck

- src/xdocs/releasenotes.xml
Change username  "nmancus1"  to "Nick Mancuso" in release notes.
> doc: change "nmancus1" to "Nick Mancuso" in release notes

- config/pmd-test.xml
Fixes PMD warning detected [here](https://github.com/checkstyle/checkstyle/pull/8349#issuecomment-651050383)
> minor: fix pmd warning of deprecated attribute

- .ci/jsoref-spellchecker/whitelist.words
- src/site/resources/css/site.css
fix #8264
rel: https://github.com/checkstyle/checkstyle/pull/8307
preview: [https://jo2.github.io/checkstyle-font-size/](https://jo2.github.io/checkstyle-font-size/)
> Issue #8264: Increase font size of website

- src/xdocs/property_types.xml
#8328 
Types added to `property_types.xml`:
-  byte, byte[]
- char, char[]
- float, float[]
- long, long[]
- short, short[]
> Issue #8328: Change name of checkstyle types to be close to real java types - other types

- src/xdocs/property_types.xml
> minor: sort the property types in xdoc

- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config_annotation.xml
- src/xdocs/config_blocks.xml
- src/xdocs/config_coding.xml
- src/xdocs/config_design.xml
- src/xdocs/config_filefilters.xml
- src/xdocs/config_filters.xml
- src/xdocs/config_imports.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/config_metrics.xml
- src/xdocs/config_misc.xml
- src/xdocs/config_naming.xml
- src/xdocs/config_regexp.xml
- src/xdocs/config_sizes.xml
- src/xdocs/writingfilefilters.xml
- src/xdocs/writingfilters.xml
#8328 
- Introuduced `Pattern` and `Pattern[]`
- Sorted the property types
> Issue #8328: Change name of checkstyle types to be close to real java types - regexp

- src/site/resources/css/site.css
Issue #8397
https://romani.github.io/8397-pixel2xl/site/index.html
> Issue #8397: update css to treat mobile devices in horizontal layout as mobile

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LambdaParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_naming.xml
#8306 
"ClassTypeParameterName",
"StaticVariableName",
"LocalVariableName",
"MethodTypeParameterName",
"AbbreviationAsWordInName",
"MethodName",
"ParameterName",
"MemberName",
"CatchParameterName",
"LambdaParameterName"
> Issue #8306: Javadoc Modification for Metadata Generation Support - 2

- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306 
"PackageName",
"EmptyCatchBlock",
"AvoidNestedBlocks",
"LeftCurly",
"NeedBraces",
"EmptyBlock",
"RightCurly",
"DescendantToken",
"UniqueProperties",
"UncommentedMain"
> Issue #8306: Javadoc Modification for Metadata Generation Support - 3

- src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306 
"Translation",
"NewlineAtEndOfFile",
"FinalParameters",
"TodoComment",
"AnonInnerLength",
"ParameterNumber",
"LineLength",
"OuterTypeNumber",
"FileLength",
"MethodCount"
> Issue #8306: Javadoc Modification for Metadata Generation Support - 4

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306
"IllegalTokenText",
"NestedForDepth",
"OneStatementPerLine",
"SuperFinalize",
"EmptyStatement",
"IllegalToken",
"IllegalThrows",
"NoFinalizer",
"VariableDeclarationUsageDistance",
"PackageDeclaration"
> Issue #8306: Javadoc Modification for Metadata Generation Support - 8

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/xdocs/config_whitespace.xml
#8306 
"FileTabCharacter",
"NoWhitespaceBefore",
"NoLineWrap",
"EmptyLineSeparator",
"OperatorWrap",
"ParenPad",
"NoWhitespaceAfter",
"EmptyForInitializerPad",
"WhitespaceAfter",
"SingleSpaceSeparator",
> Issue #8306: Javadoc Modification for Metadata Generation Support - 13

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingWhitespaceAfterAsteriskCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306
"SingleLineJavadoc",
"NonEmptyAtclauseDescription",
"JavadocMissingWhitespaceAfterAsterisk",
"JavadocPackage",
"MissingJavadocPackage",
"JavadocType",
"SummaryJavadoc",
"JavadocContentLocation",
"WriteTag",
"InvalidJavadocPosition",
> Issue #8306: Javadoc Modification for Metadata Generation Support - 15

- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SeverityMatchFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionSingleFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilter.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306
Modified Filter files. This is the final PR for Javadoc Modification.
> Issue #8306: Javadoc Modification for Metadata Generation Support - final

- .github/workflows/diff_report.yml
Improving diff_report.yml for these directions:
https://github.com/checkstyle/checkstyle/pull/8445#pullrequestreview-448125816
> minor: improve diff_report.yml file

- .github/workflows/diff_report.yml
> Issue #8446: changed to using action from contribution repo

- .github/workflows/diff_report.yml
> Issue #8459: PR trigger removed from report generation action

- .github/workflows/diff_report.yml
> Issue #8495: added trigger on editing comment for diff report generation

- .github/workflows/diff_report.yml
Some improving of diff_report.yml.
> minor: rename and swap of steps in diff_report.yml

- config/ant-phase-verify.xml
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java14/InputJava14SwitchExpression.java
minor: Input for Java 14 switch expression(#6615)
Input consists of code from #8185, in addition to lots of code from openjdk14's `langtools/` directory.
> minor: Input for Java 14 switch expression(#6615)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullEnhancedInstanceof.java
Issue #8362: Enhanced instanceof support for EqualsAvoidNullCheck
This PR adds support for PATTERN_VARIABLE_DEF tokens, and therefore enhanced instanceof, for EqualsAvoidNullCheck.
> Issue #8362: Enhanced instanceof support for EqualsAvoidNullCheck

- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameCheckEnhancedInstanceofAllowXmlLength1.java
From discussion at https://github.com/checkstyle/checkstyle/pull/8412#discussion_r452865287
> minor: update AbbreviationAsWordInNameCheckTest.java and inputs (#8412)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneMethodReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeMethodReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeVariations.java
Resolves #8399 
Reg report (no diff) https://strkkk.github.io/checkstyle/8399/index.html
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/strkkk/strkkk.github.io/master/checkstyle/check.xml
Diff Regression patch config: https://raw.githubusercontent.com/strkkk/strkkk.github.io/master/checkstyle/check.xml
> Issue #8399: fix NPE for SuperClone and SuperFinalize checks

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeEnhancedInstanceof.java
- src/xdocs/config_coding.xml
Issue #8365: enhanced instanceof check validation: IllegalTypeCheck
This PR will add support for PATTERN_VARIABLE_DEF tokens, and enhanced instanceof syntax,  to IllegalTypeCheck.
> Issue #8365: enhanced instanceof check validation: IllegalTypeCheck

- config/ant-phase-verify.xml
- config/checkstyle_checks.xml
- config/pmd.xml
- pom.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/ant/antlib.xml
Issue #8543 
The first commit fixes the indentation for some files (whitespace only changes).
The second commit turns on checking the format.
> Issue #8543 format xml sources

- .github/workflows/diff_report.yml
Closes #8539
Example of usages (fake config and 1 project is used, only for demo)
1. New module report https://github.com/strkkk/checkstyle/pull/5
2. Diff report https://github.com/strkkk/checkstyle/pull/4
3. Diff report with different patch config https://github.com/strkkk/checkstyle/pull/6
PR for doc update 
https://github.com/checkstyle/contribution/pull/497
> Issue #8539: change diff trigger

- pom.xml
Issue #8543 
all xml sources included
added goal `check-format`
> Issue #8543: check that all xml sources are well formed

- src/xdocs/config_annotation.xml
- src/xdocs/config_blocks.xml
- src/xdocs/config_design.xml
- src/xdocs/config_filefilters.xml
- src/xdocs/config_header.xml
- src/xdocs/config_imports.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/config_metrics.xml
- src/xdocs/config_misc.xml
- src/xdocs/config_naming.xml
- src/xdocs/config_regexp.xml
- src/xdocs/config_sizes.xml
Issue #8544
xdocs for all checks except coding, filters and whitespace
> Issue #8544: format xml sources (xdocs checks part one)

- config/intellij-idea-inspection-scope.xml
- config/intellij-idea-inspections.xml
- pom.xml
Issue #8544
Intellij IDEA congifs were formatted with two spaces indented.
The file `config/intellij-idea-inspections.xml` is not aligned on `=` vertically.
>  Issue #8544: format xml sources (intellij idea configs)

- pom.xml
- src/main/resources/google_checks.xml
- src/main/resources/sun_checks.xml
Issue #8544
Google & Sun configs are updated to use two spaces for indentation.
> Issue #8544: format xml sources (sun/google styles)
