.ci/wercker.sh, wercker.yml
Update for #7892: Add validation for empty .ci-temp folder after CI runs
=> Issue #7892: add empty .ci-temp validation

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheck.java, src/xdocs/config_annotation.xml
Fixes #7570
```
$ cat configAnnotation.xml
<module name="AnnotationOnSameLine">
</module>
</module>
</module>
$ cat annotation1.java
class Foo {
@SuppressWarnings("deprecation")  // violation, annotation should be on the same line
public Foo() {
}
public void fun1() {
}
@SuppressWarnings("unchecked") public void fun2() {  // OK
}
}
@SuppressWarnings("unchecked") class Bar extends Foo {  // OK
@Deprecated public Bar() {  // OK
}
@Override  // violation, annotation should be on the same line
public void fun1() {
}
@Before @Override public void fun2() {  // OK
}
@SuppressWarnings("deprecation") …
```
=> Issue #7570: Update doc for AnnotationOnSameLine

.github/ISSUE_TEMPLATE.md, src/xdocs/report_issue.xml
Resolve #2622: Update documentation for windows users
Notes:
- The example for linux was already patched so I couldn't replicate it. I used a different case, adapted from #5685.
- To accommodate both linux and windows report examples, I moved around some of the text a bit so it looks better (in my opinion).
- I also added the variation for Windows to the issue template, in #7926 the user had problems running the issue template commands due to Windows command line.
- I'm open to further improvements/suggestions for wording and formatting, so far this is just my take on what needs to be done.
New site looks like this:
=> Issue #2622: Update documentation for windows users

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java
Fix Issue #7979 
As per my knowledge we can see for each JavadocMethodCheck a new instance will be created so whenever this method is called a new object itself will be created of `currentTypeParams`
Pitest report: 
https://harsh-kukreja.github.io/JavadocMethodCheckPitestReport/com.puppycrawl.tools.checkstyle.checks.javadoc/JavadocMethodCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@18b9ce_383
Hardcoded commit: 
https://github.com/checkstyle/checkstyle/commit/d2b3b319b15aa9b5efa41fce812e9c533c826f5c
Diff report:
https://harsh-kukreja.github.io/issue-7979/index.html
=> Issue 7979  Resolve Pitest Issues - JavadocMethodCheck (7)

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodIgnoreThrows.java, src/xdocs/config_javadoc.xml
Issue #7473: JavadocMethod: false positive with validateThrows if catched inside the method
Logic has been tweaked as follows:
1. For every use of the `throws` literal, check the AST node's ancestors to see where it comes from
2. If we find that it is from a lambda or `try` block, we disregard that node. **Update**: Local and anonymous classes defined in the method will also be ignored.
3. `catch` and `finally` literals are considered children of the `try` literal. However they should not be ignored because exceptions can be thrown there that go uncaught. Hence if we encounter `catch` and `finally` on the way up then we need to 'skip' the next ancestor (the `try` literal).
Regression: https://wltan.github.io/checkstyle-reports/2020-04-20/javadocmethod-throws/index (updated)
=> Issue #7473: JavadocMethod: false positive with validateThrows

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java, src/xdocs/config_naming.xml
fixes: #7563 
**Website view:**
**Output:**
```
kaustubh@dxtkastb:~$ cat Test.java
public class MyTest {
try {
// ...
} catch (ArithmeticException e) { // OK
// ...
} catch (ArrayIndexOutOfBoundsException ex) { // OK
// ...
} catch (Throwable t) { // OK
// ...
} catch (IndexOutOfBoundsException e123) { // violation, digits
// not allowed
// ...
} catch (NullPointerException ab) { // violation, should have at least
// three characters if not e|t|ex
// ...
} catch (ArrayStoreException abc) { // OK
// ...
} catch (InterruptedException aBC) { // violation, first two characters
// should be in lowercase
// ...
} catch (RuntimeException abC) { // OK
// ...
} catch (Exception abCD) { // OK
// ...
}
}
}
kaustubh@dxtkastb:~$ cat Test.xml
<!DOCTYPE …
```
=> Issue #7563: Add default config example for CatchParameterName

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentation.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationDescription.java, src/xdocs/config_javadoc.xml
Fixes issue #2813 
Originally in this, we retrieved all the new line nodes (`\n`) in the Javadoc and considered their 2nd next sibling as our description. The problem with this technique was that it was failing to consider the first description in the example below .i.e `Description 1` because according to the AST `Description 1` is not 2nd next sibling of `\n`, hence it was not being violated as specified in the issue. 
```
/**
* @param s
* Description 1.
* Description 2.
*/
public void test(String s) {}
```
To solve this problem, I changed the traversing technique. Now we are retrieving all the `LEADING_ASTRISK` nodes, as from my observation each description is followed by a `LEADIN_ASTERISK`. The important change in this technique is that a `LEADING_ASTRISK` is always followed by …
=> Issue #2813: JavadocTagContinuationIndentation doesn't report some lines

config/pmd-main.xml, config/pmd-test.xml, config/pmd.xml
Fixes #8206 
Needed to replace `@Image` with `@SimpleName` as `@Image` is deprecated now.
=> Issue #8206: Resolve PMD warning deprecated attribute 'ClassOrInterfaceDeclaration/@Image

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java, src/main/resources/sun_checks.xml
Linkcheck fails with
```xml
<td><i>
<a class="externalLink" href="https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html">
https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html</a>:
301 Moved Permanently</i></td></tr></table></td></tr>
```
Updated location is:
```
GET /technetwork/java/javase/documentation/index-137868.html HTTP/1.1
HTTP/1.1 301 Moved Permanently
Server: Oracle-HTTP-Server
Location: https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html
Content-Length: 7551
```
(Another links for javadoc-tool not fixed in #8221)
=> doc: update link to moved javadoc-tool page

src/it/java/com/google/checkstyle/test/chapter3filestructure/rule333orderingandspacing/CustomImportOrderTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCustomImportOrderTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/SuppressionXpathRegressionCustomImportOrderFive.java, src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/SuppressionXpathRegressionCustomImportOrderFour.java, src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/SuppressionXpathRegressionCustomImportOrderOne.java, src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/SuppressionXpathRegressionCustomImportOrderSix.java, src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/SuppressionXpathRegressionCustomImportOrderThree.java, src/it/resources/org/checkstyle/suppressionxpathfilter/customimportorder/SuppressionXpathRegressionCustomImportOrderTwo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Issue: #7728 Update AbstractChecks to log DetailAST - CustomImportOrder
Diff report
https://developerhb.github.io/diff/index.html
Logs Modified - **6**
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L576
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L619
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L633
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L717 …
=> Issue: #7728 Update AbstractChecks to log DetailAST - CustomImportOrder

.ci/pitest.sh, config/checkstyle_resources_suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsSingleWordPackage.java
Issue #7921 
Description: 
We don't need the variable collect to check if we should start collecting or not because it will always true because every java fill will contain package keyword or class that will make collect = true
Reports:
Diff Report : https://amrdeveloper.github.io/checkstyle-reports/7921/diff/
pitest-after : https://amrdeveloper.github.io/checkstyle-reports/7921/pitest-after
pitest-before : https://amrdeveloper.github.io/checkstyle-reports/7921/pitest-before/
=> Issue #7921: Resolve Pitest Issues - UnusedImportsCheck

src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsUrlTest.java, src/xdocs/checks.xml
solve a typo which is mentioned in #7889 Broken link - AvoidDoubleBraceInitialization, and I add UT to validate URL is correct. 
And I find that there are three special cases:
CommentsIndentation:
java file in **src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation** but in checks.xml belongs to misc
https://github.com/checkstyle/checkstyle/blob/90ba1b8a82a20afcd45c89591dea49a7d0dc45bb/src/xdocs/checks.xml#L142
Indentation:
java file in **src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation** but in checks.xml belongs to misc
https://github.com/checkstyle/checkstyle/blob/90ba1b8a82a20afcd45c89591dea49a7d0dc45bb/src/xdocs/checks.xml#L350
SuppressWarningsHolder:
java file in **src/main/java/com/puppycrawl/tools/checkstyle/checks** but in checks.xml belongs to …
=> Issue #7889: add UT to validate URL is correct in config.xml and fix a typo

.ci/travis/travis.sh
detected during build failure for https://github.com/checkstyle/checkstyle/commit/eda60ea5b8579abe0babc42435b078b4bc2be67e in master branch.
=> minor: fix links to files in 'travis.sh verify-no-exception-configs'

.ci/test-spelling-unknown-words.sh, .ci/travis/travis.sh, .travis.yml
Update for #7892: Add validation for empty .ci-temp folder after CI runs
Travis cut logs if scripts finish execution abnormally:
https://travis-ci.community/t/log-are-truncated-when-my-script-exits-abnormally/5878/4 Note that the OP is stating that this happens when script exits normally or with error.
=> Issue #7892: add empty .ci-temp validation for travis

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheck.java, src/xdocs/config_naming.xml
#7565 
**Website Look**
**Non Default Config**
pk@pk:~/Desktop/check$ cat config.xml 
```
<module name = "AbstractClassName">
<property name = "format" value = "^Generator.+$"/>
</module>
</module>
</module>
```
pk@pk:~/Desktop/check$ cat Test.java
```
abstract class GeneratorFirstClass{}
abstract class SecondClass{}
class GeneratorThirdClass{}
class FourthClass{}
```
pk@pk:~/Desktop/check$ java -jar checkstyle-8.30-all.jar -c config.xml Test.java
[ERROR] /home/pk/Desktop/check/Test.java:2:1: Name 'SecondClass' must match pattern '^Generator.+$'. [AbstractClassName] …
=> Issue #7565: update doc for AbstractClassName

src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/NoWhitespaceBeforeTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeAnnotations.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Issue #6707: fix false violation report that does not allow spaces in front of ellipsis tokens for Google Style, specific information are in issue.
diff report:
https://huganghui.github.io/6707-ellipsis/diff/
=> Issue #6707: fix false violation report that does not allow spaces in front of ellipsis tokens for Google Style

.ci/travis/xtr_releasenotes-gen.sh
Issue #8268: Cleanup .ci-temp folder after release notes generation
=> Issue #8268: Cleanup .ci-temp folder after release notes generation

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderNonStaticWrongSequence.java
Issue #7876: Fix for ImportOrderChec(6)
=> Issue #7876: Fix for ImportOrderCheck(6)

config/checkstyle_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_coding.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_modifier.xml, src/xdocs/config_naming.xml, src/xdocs/config_sizes.xml, src/xdocs/config_whitespace.xml
Resolves #3946
Resolves #3934(duplicate).
1. All xdocs have been updated
source: https://github.com/checkstyle/checkstyle/pull/5484#issuecomment-367367563
2. An UT has been provided to enforce this formatting 
source: 
https://github.com/checkstyle/checkstyle/issues/3946#issue-212299810
```
TOKEN1,
TOKEN2,
TOKEN3.
```
to:
```
TOKEN1
,TOKEN2
,TOKEN3
.
```
Generated Site: https://gaurabdg.github.io/checkstyle-tester-reports/site/
=> Issue #3946: code cleanup: minimize future xdoc changes

config/spotbugs-exclude.xml
Issue #8262
`$jacocoData` is an instrumented field, not a real one.
=> Issue #8262: ignore jacoco internal field in spotbugs validation

pom.xml, src/it/resources/com/google/checkstyle/test/chapter6programpractice/rule64finalizers/InputNoFinalizeExtend.java, src/it/resources/org/checkstyle/suppressionxpathfilter/hiddenfield/SuppressionXpathRegressionHiddenFieldOne.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEquals.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeStarImports.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeVariations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierIsStarImport.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderCompareImports.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_NoSeparator.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_OverlappingPatterns.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupOrder.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupOrderBottom.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupOrderBottom_Negative.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupOrderBottom_Negative2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticOnDemandGroupOrder.java
Issue #8283 
* Fix import order inputs
* Rename test classes with deprecated methods to have Input prefix
* Classes `AllChecksTest` and `XdocsPagesTest` are explicitly ignored
=> Issue 8283 fix import tests

config/checkstyle_checks.xml, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule413emptyblocks/InputEmptyBlock.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAlone.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLine2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleLineBlocksWithSemi.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyAloneOrSingleline.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyLeft.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlySameBlocksWithSemi.java, src/xdocs/config_blocks.xml
Resolves #7175 
Diff report: 
- `alone_or_singleline` - https://gaurabdg.github.io/checkstyle-tester-reports/regression/rcurly/diff/
- `alone` -  https://gaurabdg.github.io/checkstyle-tester-reports/regression/rcurly-alone/diff/
=> Issue #7175: INTERFACE_DEF token support in RightCurlyCheck

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ArrayInitHandler.java
Resolves Issue #8270 
idea:
`getNextFirstNonBlankOnLineAfter(int,int)` return first non-blank column on the same line after the position of the second argument provided.
Its a private class and its scope is only `ArrayInitHandler.java` and thus it is used only at one place inside `getChildrenExpectedIndent()`
The pupose of use is to get first non-blank cloumn number after lcurly position. It should return -1 if there are only blank lines after lcurly.
Practically it is not possible to have any column after lcurly to be at 0th position(being on the same line for lcurly). Thus the contional mutation is survived on `>= 0` clause.
Modifying it to check condition for `!= -1` kills the mutation.
=> Issue #8270: Pitest Issue: Indentation - ArrayInitHandler

config/ant-phase-verify.xml
minor: add "until" comment for records input 
We need to add a link to issue #8023 to explain why this can't be parsed yet.
=> minor: add "until" comment for records input (#8023)

src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
Issue #4944: Extend Checkstyle GUI tool to work with Xpath - **Layout Changes**
*Actual implementation of functionality is still remainig.*
*This is just the layout.*
=> Issue #4944: Extend Checkstyle GUI tool to work with Xpath - Layout Changes

config/ant-phase-verify.xml, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java14/InputJava14TextBlocks.java
minor: add text blocks input 
In reference to #7103, this PR is for the input file to test the implementation of Java 14 text blocks.
Credit for most of the inputs goes to @strkkk, I also found a few more examples from https://www.baeldung.com/java-text-blocks and #7103.
=> minor: add text blocks input (#7103)

pom.xml
https://app.codeship.com/projects/124310/builds/70f426fe-f4ce-43c4-baba-c2c14e6caedb?line=c6567587-f064-4101-9934-5c987551d6f0&step=parallel_.ci%2Frun-link-check-plugin.sh
`2020-06-23 23:43:42
system <td><i><a class="externalLink" href="https://oss.sonatype.org/service/local/staging/deploy/maven2/">https://oss.sonatype.org/service/local/staging/deploy/maven2/</a>: 405 Not Allowed</i></td></tr></table></td></tr>`
```
✔ ~/java/github/romani/checkstyle [master|✔] 
$ ag -Q "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
✘-1 ~/java/github/romani/checkstyle [master|✔] 
$ cd target/site/
✔ ~/java/github/romani/checkstyle/target/site [master|✔] 
$ ag -Q "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
distribution-management.html
139:<h3><a …
```
=> minor: exclude from validation link to sonatype that demand authorization

src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g
Issue #8308: need to introduce "id" rule to solve keyword as identifier problem.
Per discussion at #8308, in order to solve the "keyword as identifier" problem, which is introduced by the inclusion of the "records" feature of Java 14, we need to add this rule to Checkstyle's grammar.  Please see Check and AST regression reports here: https://github.com/checkstyle/checkstyle/issues/8308#issuecomment-642053460
=> Issue #8308: need to introduce "id" rule (#8023)

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config.xml, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_filters.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_misc.xml, src/xdocs/config_whitespace.xml, src/xdocs/property_types.xml
#8328
Refactored - 
1. `ClosingParensOption`
2. `ElementStyleOption`
3. `TrailingArrayCommaOption`
All other enums already have `Option` suffix already and just required a bit of renaming in `property_types.html` related files
=> Issue #8328: Change name of checkstyle types to be close to real java types - enums

src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FullIdent.java, src/main/java/com/puppycrawl/tools/checkstyle/api/LocalizedMessage.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/NoCodeInFileCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/DetailAstSet.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNode.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/ElementNode.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/RootNode.java
I took the violations from #7932 and I put together a small script to fix them for me: https://github.com/josephmate/FixAtClauseError . It takes the output from a build, searches for the missing newline checkstyle errors and inserts them.
=> minor: fix violations from future EmptyLineBeforeAtClauseBlock (#6192)

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config.xml, src/xdocs/config_annotation.xml, src/xdocs/config_blocks.xml, src/xdocs/config_coding.xml, src/xdocs/config_design.xml, src/xdocs/config_filters.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_metrics.xml, src/xdocs/config_misc.xml, src/xdocs/config_modifier.xml, src/xdocs/config_naming.xml, src/xdocs/config_regexp.xml, src/xdocs/config_sizes.xml, src/xdocs/config_system_properties.xml, src/xdocs/config_whitespace.xml, src/xdocs/property_types.xml, src/xdocs/releasenotes_old.xml
#8328 
Refactored
1. `integer -> Integer`
2. `boolean -> Boolean`
3. `integerSet -> int[]`
4. create `Double` and `double[]`
5. `stringSet -> String[]`
=> Issue #8328: Change name of checkstyle types to be close to real java types - basic types

config/checkstyle_sevntu_checks.xml, config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java, src/xdocs/config.xml, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_naming.xml, src/xdocs/property_types.xml
#8328 
Types Refactored in first commit - 
1. Pattern
2. URI
3. File
4. Scope
5. AccessModifierOption[]
=> Issue #8328: Change name of checkstyle types to be close to real java types - misc

src/main/java/com/puppycrawl/tools/checkstyle/checks/NoCodeInFileCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_blocks.xml, src/xdocs/property_types.xml
#8306 
Added modified `XdocsJavadoc` UT.
- `NoCodeInFileCheck`
- `RightCurlyCheck`
- `BooleanExpressionComplexityCheck`
- `ClassFanOutComplexityCheck`
- `CyclomaticComplexityCheck`
- `JavaNCSSCheck`
- `NPathComplexityCheck`
- `ConstantNameCheck`
- `InterfaceTypeParamterNameCheck`
- `LocalFinalVariableNameCheck`
- `TypeNameCheck`
Javadoc of `RightCurlyCheck`
Before:
After:
=> Issue #8306: Javadoc Modification for Metadata Generation Support - 1

.ci/jsoref-spellchecker/whitelist.words, config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java
Issue #4944: Extend Checkstyle GUI tool to work with Xpath.
**This PR depends on PR https://github.com/checkstyle/checkstyle/pull/8247**
The first commit is not be reviewed. It is of PR https://github.com/checkstyle/checkstyle/pull/8247.
This PR adds the functionality of generating Xpath Query when a node is selected from tree.
=> Issue #4944: Extend Checkstyle GUI tool to work with Xpath - Generate Xpath Query

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameCheckEnhancedInstanceof.java, src/xdocs/config_naming.xml
Issue #8387: enhanced instanceof check validation for AbbreviationAsWordInNameCheck(#7290)
This PR will add support for Java 14 enhanced instanceof syntax to AbbreviationAsWordInNameCheck.
~~Reviewers, please note that the first commit is from the instanceof PR, #8401.~~
Commit has been dropped since #8401 was merged.
Check regression report: https://checkstyle-reports-java14.s3.amazonaws.com/reports/diff_instanceof-AbbreviationAsWordInNameCheck/index.html
=> Issue #8387: Add support for enhanced instanceof syntax for AbbreviationAsWordInNameCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/xdocs/config_header.xml, src/xdocs/config_imports.xml, src/xdocs/property_types.xml
#8306 
"ExecutableStatementCount",
"MethodLength",
"RegexpHeader",
"Header",
"ExplicitInitialization",
"InnerAssignment",
"UnnecessarySemicolonAfterTypeMemberDeclaration",
"UnnecessarySemicolonInTryWithResources",
"FinalLocalVariable",
"MissingSwitchDefault"
=> Issue #8306: Javadoc Modification for Metadata Generation Support - 5

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306 
Modifield Files:
"UnnecessaryParentheses",
"MultipleStringLiterals",
"MultipleVariableDeclarations",
"AvoidDoubleBraceInitialization",
"ReturnCount",
"CovariantEquals",
"EqualsAvoidNull",
"HiddenField",
"NoClone",
"IllegalInstantiation"
=> Issue #8306: Javadoc Modification for Metadata Generation Support - 6

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterOuterTypeDeclarationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306 
"ModifiedControlVariable",
"FallThrough",
"SuperClone",
"EqualsHashCode",
"StringLiteralEquality",
"NestedIfDepth",
"UnnecessarySemicolonAfterOuterTypeDeclaration",
"IllegalType",
"SimplifyBooleanReturn",
"DeclarationOrder"
=> Issue #8306: Javadoc Modification for Metadata Generation Support - 9

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8306
"ArrayTrailingComma",
"NoEnumTrailingComma",
"IllegalCatch",
"AvoidNoArgumentSuperConstructorCall",
"NoArrayTrailingComma",
"ImportOrder",
"CustomImportOrder",
"AvoidStaticImport",
"ImportControl",
"AvoidStarImport"
=> Issue #8306: Javadoc Modification for Metadata Generation Support - 10

.ci/jsoref-spellchecker/whitelist.words, .github/workflows/diff_report.yml
#7498
Adding .yml file, which generates diff report for every pull request.
Triggers on opening, reopening, editing and new commit of pull request and when someone write comment "report".
Also, the body of pull request should contain two lines:
Diff Regression projects: {{URI to file like projects-to-test-on.properties}}
Diff Regression config: {{URI to file like my_checks.xml}}
Result: new comment from github-actions bot with link on generated diff report
Requirements:
As it push reports to aws bucket you will need:
1) secrets.AWS_ACCESS_KEY_ID - access key for AWS S3 service user
2) secrets.AWS_SECRET_ACCESS_KEY - security access key for AWS S3 service user
3) secrets.GITHUB_TOKEN - to sent new comment by github-actions bot [built-in github token]
4) .yml file start working only when it …
=> Issue #7498: add github actions file to generate diff report

.github/workflows/diff_report.yml
Issue: #8447 
Update diff_report.yml file: added the ability to create report only for patch branch (for example, for new checks).
If issue comment is "diff report", then a basic difference report will be generated.
If issue comment is "single report", then a basic single report will be generated.
Example: https://github.com/OvchinnikovNV/checkstyle/pull/2
=> Issue #8447: add ability to create single report

.github/workflows/diff_report.yml
Issue #8496
If something goes wrong during report generation - bot sends comment with description and link to job.
Example: https://github.com/jack1515/checkstyle/pull/4
=> Issue #8496: failure comment added (for diff/single report generation)

.github/workflows/diff_report.yml
Issue #8448 
Added generation diff report with different (base and patch) configs.
The description of PR should contain one more line:
Diff Regression patch config: {{URI to patch config file}}
Something like this:
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/my_check.xml
Diff Regression patch config: https://raw.githubusercontent.com/kate2513/kate2513.github.io/master/patch_config.xml
=> Issue #8448: added using different configs to diff report generation pipeline

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
Issue #8345: Add TokenUtil.isTypeDeclaration method
~~Reviewers, I have added the records support commits to this so we can immediately add `TokenTypes.RECORD_DEF` to `TokenUtil.isTypeDeclaration()`.  I will rebase once we merge #8293.~~  The second commit is the refactoring of `ScopeUtil.java` to use `TokenUtil.isTypeDeclaration()`.
=> Issue #8345: Add TokenUtil.isTypeDeclaration method

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldEnhancedInstanceof.java, src/xdocs/config_coding.xml
Issue #8364: Add support for enhanced instanceof syntax to HiddenFieldCheck(#7290)
~~Reviewers, please note that the first commit is from the instanceof PR, #8401.~~
Commit has been dropped now that #8401 was merged.
Check regression report: https://checkstyle-reports-java14.s3.amazonaws.com/reports/diff_instanceof-HiddenFieldCheck/index.html
=> Issue #8364: Add support for enhanced instanceof syntax to HiddenFieldCheck(#7290)

pom.xml, src/xdocs/beginning_development.xml, src/xdocs/checks.xml, src/xdocs/cmdline.xml.vm, src/xdocs/config.xml, src/xdocs/contributing.xml, src/xdocs/index.xml.vm, src/xdocs/property_types.xml, src/xdocs/writingchecks.xml, src/xdocs/writingjavadocchecks.xml.vm
Issue #8544
Checkstyle all xdoc files (except the checks) were formatted with two spaces indented.
There is a questionable one: `property_types.xml`. We should discuss this.
To satisfy the rules, all `<b>}</b>` tags should be indented __more__ than the enclosing `<pre>` tag.
There is at least three options:
* remove `<b></b>` and keep only the comments
* add this file to the exception list (current)
* wrap long lines
Formatting for checks will be in in the next PR(s).
=> Issue #8544: format xml sources (xdocs non-checks)

.ci/jsoref-spellchecker/whitelist.words, config/checkstyle_checks.xml, pom.xml, src/it/java/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/PatternVariableNameTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPatternVariableNameTest.java, src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule527localvariablenames/InputPatternVariableNameEnhancedInstanceofTestDefault.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/SuppressionXpathRegressionPatternVariableName1.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/SuppressionXpathRegressionPatternVariableName2.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/SuppressionXpathRegressionPatternVariableName3.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/patternvariablename/SuppressionXpathRegressionPatternVariableName4.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PatternVariableNameCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PatternVariableNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/patternvariablename/InputPatternVariableNameEnhancedInstanceofNoSingleChar.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/patternvariablename/InputPatternVariableNameEnhancedInstanceofTestDefault.java, src/xdocs/checks.xml, src/xdocs/config_naming.xml, src/xdocs/google_style.xml
Issue #8407: new Check: PatternVariableName
We are introducing this check to ensure that pattern variable names conform to a predefined pattern.  Since I could not find mention of pattern variables in the sun or google style guides, I have omitted this check from those configurations.  I have added the check to `checkstyle_checks.xml`, using the default pattern `^[a-z][a-zA-Z0-9]*$`.
Check regression report : https://checkstyle-reports-java14.s3.amazonaws.com/reports/diff_check_patternvariablename/index.html
Contribution PR: https://github.com/checkstyle/contribution/pull/492
=> Issue #8407: new Check: PatternVariableName

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
minor: update PATTERN_VARIABLE_DEF with `since` tag
Per discussion with @romani, we will be adding the `since` tag to all token types documentation in TokenTypes.java.
=> minor: update PATTERN_VARIABLE_DEF with since tag

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameCheckRecords.java, src/xdocs/config_naming.xml
Issue #8511: Records Support check update for AbbreviationAsWordInNameCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/c7859b6315e09bd45bc70e88abacb33e/raw/f39a8180dda844af0706709481f02cc2433ac37a/AbbreviationAsWordInNameCheck.xml
=> Issue #8511: Records Support check update for AbbreviationAsWordInNameCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsRecordsAndCompactCtors.java
Issue #8488: Records Support Check update for UnusedImportsCheck
This PR updates UnusedImportsCheck to function as intended with Java 14 record definitions and compact constructors. 
Diff Regression projects: https://raw.githubusercontent.com/nmancus1/nmancus1.github.io/master/check-update-configs/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/nmancus1/nmancus1.github.io/master/check-update-configs/UnusedImports.xml
=>  Issue #8488: Records Support Check update for UnusedImportsCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameRecord.java, src/xdocs/config_misc.xml
Issue #8516: Records Support check update for OuterTypeFilenameCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/f52e3def2d2cee1831d1bf15b0258d86/raw/6820ccb5294a94cd5fa8b36eac8694639ac20c59/OuterTypeFilenameCheck.xml
=> Issue #8516: Records Support check update for OuterTypeFilenameCheck

.ci/jsoref-spellchecker/whitelist.words, pom.xml
Issue #6560
On platforms that had a default encoding different than UTF-8, some of the unit tests failed. This PR explicitly specifies the encoding for the unit tests so that they'll pass no matter what the platform's encoding is.
=> Issue #6560: Explicitly specify default encoding to make unit tests more robust

wercker.yml
https://app.wercker.com/checkstyle/checkstyle/runs/build/5f2abbebdac5630008ba5d27?step=5f2abc18052291000707439d
problems like:
```
> Task :spring-integration-core:compileJava
/pipeline/source/.ci-temp/spring-integration/spring-integration-core/src/main/java/org/springframework/integration/channel/FluxMessageChannel.java:28: error: cannot find symbol
import reactor.core.publisher.FluxIdentityProcessor;
^
symbol:   class FluxIdentityProcessor
location: package reactor.core.publisher
/pipeline/source/.ci-temp/spring-integration/spring-integration-core/src/main/java/org/springframework/integration/channel/FluxMessageChannel.java:30: error: cannot find symbol
import reactor.core.publisher.Processors;
^
symbol:   class Processors
```
=> ci: move spring integration project validation to stable version

pom.xml
Issue #8606
tested:
```
$ mvn verify
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------< com.puppycrawl.tools:checkstyle >-------------------
[INFO] Building checkstyle 8.36-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- tidy-maven-plugin:1.1.0:check (validate) @ checkstyle ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) @ checkstyle ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-versions) @ checkstyle ---
[INFO] 
[INFO] --- xml-maven-plugin:1.0.2:check-format (default) @ …
```
=> Issue #8606: add .ci-temp to exclude list for xml-maven-plugin:check-format

.ci/pitest.sh, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java, src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserTextBlocks.java
Issue #8604: fix master build failure due to leaked pitest coverage
The issue is that there were no tests included in `pitest-common-2` that exercised the text block lexer code within JavaParser.java.  I simply added a UT to check text block content, and now pitest is happy. Note that I have reverted the previous hack and restored coverage minimum back to 100%.
Five successful pitest-common-2 runs:
https://nmancus1.github.io/pitest-common-2/202008070835/
https://nmancus1.github.io/pitest-common-2/202008070836/
https://nmancus1.github.io/pitest-common-2/202008070838/
https://nmancus1.github.io/pitest-common-2/202008070839/
https://nmancus1.github.io/pitest-common-2/202008070841/
=> Issue #8604: fix master build failure due to leaked pitest coverage

src/xdocs/config_naming.xml
Per discussion at https://github.com/checkstyle/checkstyle/pull/8586#discussion_r464095811, indentation needs to be fixed in code examples for PatternVariableNameCheck. 
Site link: https://nmancus1.github.io/site_PatternVariableNameCheck
=> minor: fix PatternVariableNameCheck code example indentation

src/main/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8633 
```
<property name="fileExtensions" type="java.lang.String[]" default-value="all files">
<description><![CDATA[Specify file extensions that are accepted.]]></description>
</property>
```
`all files` is not good default value. We need to fix javadoc. It is what we mean and how it will be interpreted, but it is not a value
So, we need to replace it with `""`
=> Issue #8633: LineLengthCheck.fileExtensions default value and similar usages should be changed to empty string

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorRecordsAndCompactCtors.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorRecordsAndCompactCtorsNoEmptyLines.java, src/xdocs/config_whitespace.xml
Issue #8523: Records support check update for EmptyLineSeparatorCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/bdaeb2e6be6d30243edaeb6f04e44a87/raw/bc4eff061891f13d2ec1cf2beeab87fd96e4cc93/EmptyLineSeparatorCheck.xml
=> Issue #8523: Records support check update for EmptyLineSeparatorCheck

pom.xml
minor: remove already covered check PatternVariableName(#8407)
Identified at https://github.com/checkstyle/checkstyle/pull/8586#discussion_r467624665
This check already has pitest coverage by https://github.com/checkstyle/checkstyle/blob/ebee876080d594ed64dcaba6f56441d05d08643e/pom.xml#L2462 , so we can remove it from here.
=> minor: remove already covered check PatternVariableName(#8407)

.ci/jsoref-spellchecker/exclude.pl, .ci/jsoref-spellchecker/whitelist.words, .ci/travis/openjdk14-test/jdk14-test-excluded-files.list, .ci/travis/openjdk14-test/single-module-config.xml, .ci/travis/travis.sh, .travis.yml, config/ant-phase-verify.xml
Issue #8631: Proof of Java 14 syntax parsing by new CI build item
To prove that we can parse jdk14 syntax, we have taken the list of test files from https://download.java.net/openjdk/testresults/15/archives/24/langtools-24-summary.txt and created a Travis build item that builds the contributor's version of Checkstyle and executes Checkstyle on this list. 
The config used is a simple one so that we can execute this build quickly, just to show that we can parse all of these files.  The only module is `ClassTypeParameterName`. Also to speed things up, we will clone the openjdk14 repo with` --depth 1`.
I have added some comments to the list, to show future contributors where we can add more files as we find them.
Reviewers, please note that I have included the commits from …
=> Issue #8631: Proof of Java 14 syntax parsing by new CI build item

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckSwitchExpression.java
Issue #8660: UnnecessaryParentheses throws NPE on switch exprssion syntax
Diff Regression config: https://gist.githubusercontent.com/nmancus1/5de2b363978aeb1feb327d52e1247ef9/raw/ef539479d35662261a6672434d0ff4f724fbccb0/UnnecessaryParentheses.xml
=> Issue #8660: UnnecessaryParentheses throws NPE on switch expression syntax

config/ant-phase-verify.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchRuleHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpression.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionCorrect.java
Issue #8661: IndentationCheck throws a NPE on switch expression
Diff Regression config: https://gist.githubusercontent.com/nmancus1/68be3aca702f5825bfa909698e4dea74/raw/1c6320477615ddf0c35ef574994c95e3bffcaa7e/Indentation.xml
Please note that this PR only adds support for switch rules and fixes the NPE for #8661.  Support for yield statements will be handled separately at https://github.com/checkstyle/checkstyle/issues/8691
=> Issue #8661: IndentationCheck throws a NPE on switch expression

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyCheckSwitchExpressions.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyCheckSwitchExpressionsNewLine.java
Issue #8663: Switch expression syntax check update for LeftCurlyCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/573e0d598453915a39c69b599523b33a/raw/485809d9a16f82f6f92d575a394da687f1c84aa6/LeftCurly.xml
=> Issue #8663: Switch expression syntax check update for LeftCurlyCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressions.java
Issue #8672: Switch expression syntax check update for MissingSwitchDefault
Diff Regression config: https://gist.githubusercontent.com/nmancus1/dcf15792d9f08da0e573e5bbda2185d0/raw/556901973a29f95b25f3a41e61a466aef4780b2e/MissingSwitchDefault.xml
=> Issue #8672: Switch expression syntax check update for MissingSwitchDefault

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocks.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocksQuotes.java, src/xdocs/config_coding.xml
Issue #8576: Text Blocks syntax check update for IllegalTokenText
Diff Regression config: https://gist.githubusercontent.com/nmancus1/d90a520a3fb437338ebe3aa8a9d38658/raw/1255542f2554faccc82686fb31a200ce5a321237/IllegalTokenTextBase.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/f3228845e6fc39bef184da0c2e543017/raw/0ca5929b2da9a056286c5c8a21c0a9a5d4febb4f/IllegalTokenTextPatch.xml
=> Issue #8576: Text Blocks syntax check update for IllegalTokenText

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityCheckTextBlocks.java
Issue #8617: Text Blocks syntax check update for StringLiteralEquality
Diff Regression config: https://gist.githubusercontent.com/nmancus1/e04f556bfc30cd0a6d3a99552b9db694/raw/669aa65ecaa1cec614065c547494d357a8fa7655/StringLiteralEquality.xml
=> Issue #8617: Text Blocks syntax check update for StringLiteralEquality

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersTextBlocks.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersTextBlocksAllowByComment.java, src/xdocs/config_misc.xml
Issue #8613: Text Blocks syntax check update for AvoidEscapedUnicodeChars
Diff Regression config: https://gist.githubusercontent.com/nmancus1/89652bf785843ea1deaeaa31839bb001/raw/cfa7c13108a4b07b7954869925c99be3717ea009/AvoidEscapedUnicodeCharacters.xml
=> Issue #8613: Text Blocks syntax check update for AvoidEscapedUnicodeChars

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckTextBlocks.java, src/xdocs/config_coding.xml
Issue #8618: Text Blocks syntax check update for UnnecessaryParentheses
Diff Regression config: https://gist.githubusercontent.com/nmancus1/867268e2ebbb122e77e1640bee93b8b2/raw/6316c24398eea59d85f9601a3c35c62f362efb76/UnnecessaryParentheses.xml
=> Issue #8618: Text Blocks syntax check update for UnnecessaryParentheses

.ci/jsoref-spellchecker/whitelist.words, config/checkstyle_checks.xml, src/it/java/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/RequireEmptyLineBeforeBlockTagGroupTest.java, src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputCorrectRequireEmptyLineBeforeBlockTagGroupCheck.java, src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule712paragraphs/InputIncorrectRequireEmptyLineBeforeBlockTagGroupCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PatternVariableNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/requireemptylinebeforeblocktaggroup/InputRequireEmptyLineBeforeBlockTagGroupCorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/requireemptylinebeforeblocktaggroup/InputRequireEmptyLineBeforeBlockTagGroupIncorrect.java, src/xdocs/checks.xml, src/xdocs/config_filters.xml, src/xdocs/config_javadoc.xml, src/xdocs/google_style.xml
Resolves Issue #6192
Contribution PR: https://github.com/checkstyle/contribution/pull/478
Diff Regression projects: https://gist.githubusercontent.com/josephmate/a39a39b4c60aa11929aee4574aa90220/raw/6cff315508233d6056dc37debcb8737e4c031fd5/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/josephmate/a39a39b4c60aa11929aee4574aa90220/raw/6cff315508233d6056dc37debcb8737e4c031fd5/my_check_base.xml
Diff Regression patch config: https://gist.githubusercontent.com/josephmate/a39a39b4c60aa11929aee4574aa90220/raw/6cff315508233d6056dc37debcb8737e4c031fd5/my_check_patch.xml
**How the functional change works:**
1. only inspect nodes of type `JavadocTokenTypes.JAVADOC_TAG`
2. ignore if there is already an at-clause before the current at-clause. an empty line is …
=> Issue #6192: New module RequireEmptyLineBeforeBlockTagGroup to ensure there is an empty line before javadoc tag like @param

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheck.java
RequireEmptyLineBeforeBlockTagGroupCheck property javadoc didnt follow the template required for metadata generation.
=> doc: rectify RequireEmptyLineBeforeBlockTagGroupCheck javadoc

config/ant-phase-verify.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPosition.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderLotsOfRecords.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderRecords.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnCompactCtor.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/utils/blockcommentposition/InputBlockCommentPositionOnRecord.java, src/xdocs/config_javadoc.xml
Issue #8490: Full Records support check update for AtclauseOrderCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/d2967a1cd1ca512393fad295ceac21ae/raw/792d8e6cd3be4a27777c53d06fa7ae49b04ca930/AtclauseOrderBase.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/795d95a929b34d12ffefcaaaff3b02fe/raw/bfb376bdbbbd22d254871274b8931ba4f9ace8e4/AtclauseOrderPatch.xml
Please note that the first commit, https://github.com/checkstyle/checkstyle/commit/0cbac0f6af41b0eac5aa483a508d3a58236715b0 is not merged yet, and should not be reviewed here.
=> Issue #8490: Full Records support check update for AtclauseOrderCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/suppresswarnings/InputSuppressWarningsRecords.java, src/xdocs/config_annotation.xml
#8456: Full Records support check update for SuppressWarningsCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/539720a55feafa162cbecaa3175d7304/raw/237081cd7f8d93520e16563a387f1500894024be/SuppressWarnings.xml
Please note that commit https://github.com/checkstyle/checkstyle/pull/8752/commits/9794dca69cf8d8ab5645f6ec23c80191065ff6d6 is not under review here, but is needed for functionality of this check.
=> #8456: Full Records support check update for SuppressWarningsCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/overloadmethodsdeclarationorder/InputOverloadMethodsDeclarationOrderRecords.java
Issue #8471: Full Records check update for OverloadMethodsDeclarationOrder
Diff Regression config: https://gist.githubusercontent.com/nmancus1/8288e98333d2e8c8498918c82a1517de/raw/fe5ae98fd76c60a136073bbfd631fcd39bc93018/OverloadMethodsDeclarationOrder.xml
=> Issue #8471: Full Records check update for OverloadMethodsDeclarationOrder

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderTextBlocks.java
Issue #8619: Text Blocks syntax check update for SuppressWarningsHolder
Diff Regression config: https://gist.githubusercontent.com/nmancus1/33006852faa6fc91e8abccda0e2a98e5/raw/56dcb83c1cb3aecf93b549f39e7b9864d597375f/SuppressWarningsHolder.xml
=> Issue #8619: Text Blocks syntax check update for SuppressWarningsHolder

.ci/jsoref-spellchecker/whitelist.words, config/checkstyle_checks.xml, pom.xml, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordComponentNumberTest.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentnumber/SuppressionXpathRecordComponentNumber1.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentnumber/SuppressionXpathRecordComponentNumber2.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_zh.properties, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumber.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberMax1.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberMax20.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberPrivateModifier.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTopLevel1.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTopLevel2.java, src/xdocs/checks.xml, src/xdocs/config_sizes.xml
Issue #8748 : Create new check RecordComponentNumberCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/497dbdc31fe7a09cd960fc255972fb65/raw/c68be9ca06b61e1f279705c8b915386e701803c0/RecordComponentNumberCheckBase.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/e40c93aa8c632af54f63a8c3347821da/raw/2734393e077ea5f2deb69f3570e0200452ab31fe/RecordComponentNumberCheckPatch.xml
Contribution PR: https://github.com/checkstyle/contribution/pull/500
Link to site: https://nmancus1.github.io/site_recordcomponentnumber/
~~First check regression report, before modifying …
=> Issue #8748: Create new check RecordComponentNumberCheck

.ci/travis/travis.sh, .travis.yml, config/pmd-test.xml
Issue #8754: PMD shows WARN during build
This PR fixes the PMD warning produced during execution of the `ShortMethodName` rule while using the using the pmd-test.xml ruleset specified in pom.xml.
Proof of builds failed for PMD processing errors:
https://travis-ci.org/github/checkstyle/checkstyle/jobs/721051353
https://travis-ci.org/github/checkstyle/checkstyle/jobs/721051354
https://travis-ci.org/github/checkstyle/checkstyle/jobs/721051355
=> Issue #8754: PMD shows WARN during build

.ci/jsoref-spellchecker/whitelist.words, config/checkstyle_checks.xml, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIllegalIdentifierNameTest.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalidentifiername/SuppressionXpathRegressionIllegalIdentifierNameTestOne.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/illegalidentifiername/SuppressionXpathRegressionIllegalIdentifierNameTestTwo.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/YieldHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/IllegalIdentifierNameCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierName.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameOpenTransitive.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameParameterReceiver.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameUnderscore.java, src/xdocs/checks.xml, src/xdocs/config_naming.xml
Issue #8764: Create new check IllegalIdentifierName
Diff Regression config: https://gist.githubusercontent.com/nmancus1/a6d651fb8e00bf39244b85c05ac809b8/raw/25957bb9583e66aaa6d4849838ecfae77eac2070/Base.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/eb3dfff886148844a5b58523914109e3/raw/a20fbc07b5fd63f33c776fc20a1d2d725e86d735/IllegalIdentifierName.xml
Contribution PR: https://github.com/checkstyle/contribution/pull/503
Link to site: https://nmancus1.github.io/site_illegalidentifiername/config_naming.html#IllegalIdentifierName
=> Issue #8764: Create new check IllegalIdentifierName

src/xdocs/index.xml.vm
I maintain and operate stickler-ci and we offer hosted checkstyle integration with GitHub pull requests, with output being provided as check run annotations.
=> doc: Add stickler-ci to the active tool list

config/suppressions.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/WhitespaceAroundTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputWhitespaceAroundBasic.java, src/main/resources/google_checks.xml
Resolves partially #8122 
Fixes point 1 of https://github.com/checkstyle/checkstyle/issues/8122#issuecomment-617849138
Diff Regression projects: https://gist.githubusercontent.com/shashwatj07/61f92a65743199b114ade179f1d113b0/raw/5bf68867fe066cacc3b7743669217f2f6e7f1c27/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/shashwatj07/4b4387bc73a204c6d59dda2f7dc9fd2a/raw/7520658954923b30aeb1b157a6e5cf4dc7ccfc19/config.xml
=> Issue #8122: Google style should enforce space around enhanced for colon

.ci/pitest.sh, config/checkstyle_input_suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderSimilarGroupPattern.java
Resolves #7872 
Regression didn't find a case.
https://github.com/checkstyle/checkstyle/issues/7872#issuecomment-686426768
=> Issue #7872: fixes Resolve Pitest Issues - ImportOrderCheck (1)

src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/DescendantTokenCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTypeCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MagicNumberCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MultipleStringLiteralsCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/AtclauseOrderCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
#8785 
`AtclauseOrderCheck` is now working in Sonarqube plugin:
=> Issue #8785: Set tokenTypesSet as validationType for non base token properties

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressions.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressionsTwo.java, src/xdocs/config_coding.xml
Issue #8779: Fix false positive for switch expressions in MissingSwitchDefault
Diff Regression config: https://gist.githubusercontent.com/nmancus1/dcf15792d9f08da0e573e5bbda2185d0/raw/556901973a29f95b25f3a41e61a466aef4780b2e/MissingSwitchDefault.xml
=> Issue #8779: Fix false positive for switch expressions in MissingSwitchDefault

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheck.java, src/xdocs/config_coding.xml
Issue #7651
```
<module name="NestedForDepth"/>
</module>
</module>
class Test {
for(int i=0; i<10; i++) {
for(int j=0; j<i; j++) {
for(int k=0; k<j; k++) { // violation
}
}
}
for(int i=0; i<10; i++) {
for(int j=0; j<i; j++) { // ok
}
}
}
}
$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.33-all.jar -c config.xml Test.java
[ERROR] /var/tmp/Test.java:5:13: Nested for depth is 2 (max allowed is 1). [NestedForDepth]
Audit done.
<?xml version="1.0" …
```
=> Issue #7651: add examples for NestedForDepth

config/spotbugs-exclude.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/DescendantTokenCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTokenCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraperTest.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java, src/xdocs/config_coding.xml, src/xdocs/config_misc.xml
=> Issue #8801: Support for all Token Types as a Property Type for Module Metadata

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassConstructorInRecord.java
Issue #8811: FinalClass check crashes CheckStyle if there are multiple constructors in a record
Diff Regression config: https://gist.githubusercontent.com/nmancus1/92731df66f85c542f5f80c160273c981/raw/f9ea36e63bf9fde6f2193eca21fb06c755cc7f7a/FinalClass.xml
=> Issue #8811: FinalClass check crashes CheckStyle 

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRecords.java
Issue #8810: DesignForExtension check crashes CheckStyle if an undocumented non-final method is present in a record
Diff Regression config: https://gist.githubusercontent.com/nmancus1/fbfe0d682ec1ff833ad9ebdfa83a80b0/raw/9aec986e9fb822e214e4e7a462c3bb3fcc7b3b8c/DesignForExtension.xml
=> Issue #8810: DesignForExtension check crashes CheckStyle

.ci/wercker.sh
to not be affected by their build failures between releases
master build failure - https://app.wercker.com/checkstyle/checkstyle/runs/build/5f5a28d17e996800080b09e4?step=5f5a294a16cb6b0007e48909
=> infra: use stable version of pgjdbc 

.travis.yml
infra: disable josm build
Identified in multiple builds:
https://travis-ci.org/github/checkstyle/checkstyle/builds/727817467
https://travis-ci.org/github/checkstyle/checkstyle/builds/725705597
https://travis-ci.org/github/checkstyle/checkstyle/jobs/724495852
...
```
https://oss.sonatype.org/content/repositories/snapshots/org/jacoco/org.jacoco.ant/0.8.6-SNAPSHOT/org.jacoco.ant-0.8.6-SNAPSHOT-nodeps.jar
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 		:: org.jacoco#org.jacoco.ant;0.8.6-SNAPSHOT: not found
[ivy:resolve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR …
```
=> infra: disable josm build

.github/workflows/rebase.yml
Initial version to resolve #8842
Github action is triggered by additing (or editing) comment with content `GitHub, rebase`
There are 2 restrictions that I found during testing so far:
1. It wont work if patch branch name == 'master'
2. If there was changes in github workflows in target branch - `refusing to allow a GitHub App to create or update workflow without workflows permission`, it is a github restriction.
Second case is not very frequent since updates in workflows are not very frequent.
=> Issue #8842: Add rebase github action

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocTypeCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeRecordComponents.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeRecordComponents2.java, src/xdocs/checks.xml, src/xdocs/config_javadoc.xml
Issue #8808: false positive with JavadocTypeCheck @param tags for Records
Note that the changes in commit https://github.com/checkstyle/checkstyle/commit/df1ae95a1c114ecfd6402781668639cdd6593457 correspond to the following code:
```
/** @param x */
class Test {}
```
```
/**
* InputJavadocTypeUnusedParamInJavadocForClass.
*
* @param BAD This is bad.
* @param <BAD> This doesn't exist.
* @param
*/
public class InputJavadocTypeUnusedParamInJavadocForClass {
}
```
In both of these cases, the check was adding the angle brackets to the output, assuming that they were for type parameters.  Now that the `@param` tag is overloaded for use with record components, there is no way to know the intent of an unused `@param` tag, so it is best to remove these angle brackets.  In any event, the original …
=> Issue #8808: false positive with JavadocTypeCheck @param tags for Records

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractAccessControlNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNamePrivateMethodsInInterfaces.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNamePublicMethodsInInterfaces.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantName.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameInterfaceIgnorePublic.java
#8569
Fixed ConstantName check to correctly detect constants + MethodName check is extended with test case for private methods in interface
Diff Regression config: https://gist.githubusercontent.com/strkkk/a6e04b73158d1ef6f563dd5aab753361/raw/74f66fa883a25f37a0689fbe4ab293d66c236417/constant_name
=> Issue #8569: fix ConstantNameCheck and MethodNameCheck for interfaces

.ci/jsoref-spellchecker/whitelist.words, .ci/validation.cmd, .cirrus.yml
Issue #8855 Windows build at Cirrus CI
Notes:
* We need to use custom clone script due to `core.autocrlf` option;
* Maven and Chocolatey cache should be under the working directory;
* The command `refreshenv` does [not work](https://cirrus-ci.org/guide/windows/#environment-variables), we should set `PATH` variable manually;
* The tests `MainTest` and `PrepertiesGeneratorTest` fails since `picocli` is unable to figure out right ANSI mode. Interesting, that Appveyor is not affected by this bug. Solved with `NO_COLOR` environment variable;
* During the process I found a nice solution for connection reset problem that appears in all CI's.
=> Issue #8855: set up cirrus ci

config/spotbugs-exclude.xml
Since https://github.com/spotbugs/spotbugs/issues/259 is closed, some excludes have become redundant.
And it looks like some other false positives are gone too.
=> minor: remove redundant spotbugs excludes

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportRuleTest.java
Issue #6658 
**Mutation:**
```java
boolean pkgMatch;
if (isRegExp()) {          // removed conditional - replaced eqality check with true
pkgMatch = forImport.matches(pkgName + "\\..*");
if (pkgMatch && exactMatch) {
pkgMatch = !forImport.matches(pkgName + "\\..*\\..*");
}
}
else {
pkgMatch = forImport.startsWith(pkgName + ".");
if (pkgMatch && exactMatch) {
pkgMatch = forImport.indexOf('.',
pkgName.length() + 1) == -1;
}
}
 
return calculateResult(pkgMatch);
```
**Explanation:**
There should be a test where `regexp` is **false** but the `pkg name` is given in form of **regexp**.
**Solution:**
I added the following test.
```java
@Test
public void testPkgImportRuleNoRegexp() {
final PkgImportRule rule = new PkgImportRule(true, false, "(pkg|hallo)", false, false);
assertNotNull(rule, "Rule …
```
=> Issue #6658: Pitest increase mutation coverage for pitest-imports profile to 100% - PkgImportRule

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/FallThroughCheck.xml, src/xdocs/config_coding.xml
Issus #7640 
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Default config
```
cat config.xml
<module name="FallThrough"/>
</module>
</module>
cat Test.java 
public void foo() throws Exception {
int i = 0;
while (i >= 0) {
switch (i) {
case 1:
i++;
case 2: // violation, case 1 contains …
```
=> Issue #7640: add examples for FallThrough

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java, src/xdocs/config_imports.xml
Issue #7685
Output of example 1:
<!DOCTYPE 
module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
<module name="AvoidStaticImport"/>    
</module>
</module>
import static java.lang.Math.pow;          // violation
import static java.lang.System.out;        // violation
import java.io.*;                          // OK
import java.util.*;                        // OK
$ java -jar checkstyle-8.36.2-all.jar -c config.xml Test.java
[ERROR] D:\OpenSource\TestCommit\Test.java:1:29: Using a static member import should be avoided - java.lang.Math.pow. [AvoidStaticImport]
[ERROR] …
=> Issue #7685: Update doc for AvoidStaticImport

.ci/jsoref-spellchecker/whitelist.words, .ci/wercker.sh
Issue #6209
for googlecloudplatform/spring-cloud-gcp
based on advice at https://github.com/checkstyle/checkstyle/pull/8850#issuecomment-705151362
tested:
```
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.1:check (checkstyle-validation) @ spring-cloud-gcp-core ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Starting audit...
[ERROR] .ci-temp/spring-cloud-gcp/spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/Credentials.java:20: Wrong order for 'java.util.ArrayList' import. [ImportOrder]
[ERROR] .ci-temp/spring-cloud-gcp/spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/Credentials.java:30:29: '=' is not followed by whitespace. [WhitespaceAround]
[ERROR] …
```
=> Issue #6209: activate no-error-spring-cloud-gcp in wercker 

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/EqualsAvoidNullCheck.xml, src/xdocs/config_coding.xml
Issue #7637
Example 1:
```
cat config.xml
<module name="EqualsAvoidNull"/>
</module>
</module>
cat Test.java
package main;
String nullString = null;
nullString.equals("My_Sweet_String");            // violation
"My_Sweet_String".equals(nullString);            // OK
nullString.equalsIgnoreCase("My_Sweet_String");  // violation
"My_Sweet_String".equalsIgnoreCase(nullString);  // OK
}
}
java -jar checkstyle-8.36.2-all.jar -c config.xml Test.java
[ERROR] D:\OpenSource\TestCommit\Test.java:6:26: String …
```
=> Issue #7637: Update doc for EqualsAvoidNull

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescription.java
Closes #8889 
Diff Regression config: https://gist.githubusercontent.com/strkkk/a6e04b73158d1ef6f563dd5aab753361/raw/c89894fe9b9c5bd8a3ddc7c17023340806449941/constant_name
=> Issue #8889: fix NonEmptyAtclauseDescriptionCheck for empty descriptions

src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameTryResourcesJava9.java
Closes #8879 
Issue is in common method for local variable definition detection, thus several checks are affected.
Diff Regression config: https://gist.githubusercontent.com/strkkk/ac73db2366737f5a2d9ac0b3a39e81fa/raw/88d42f4621b0802ae77b8bc50e20d437afa5b763/8879.xml
Reg report (checks that invoke this method directly or via isClassDeclarationDef method)
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8879_local_variable_false_positive_2020151659/reports/diff/index.html
It shows that some other false positives have been fixed and also one NPE
=> Issue #8879: fix local variable detection in resource node

.github/workflows/site.yml
Closes #8876 
Triggered by adding comment `GitHub, generate web site` or `GitHub, generate site` to pull request, as other actions
Job takes ~4 minutes to run.
Example PR: https://github.com/strkkk/checkstyle/pull/10
=> Issue #8876: add github action to generate site

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheck.java, src/xdocs/config_naming.xml
Issue #7562
```
<module name="ClassTypeParameterName">
</module>
</module>
</module>
class MyClass1<T> {}   // OK
class MyClass2<t> {}   // violation
$ java -jar checkstyle-8.36.2-all.jar -c config.xml Test.java
[ERROR] D:\OpenSource\TestCommit\Test.java:2:16: Name 't' must match pattern '^[A-Z]$'. [ClassTypeParameterName]
Audit done.
```
=> Issue #7562: Add default config example for ClassTypeParameterName

.cirrus.yml
=> Issue #8918: update Cirrus CI to not print download progress in logs

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java
Fix #8895 
As described [here](https://github.com/checkstyle/checkstyle/issues/8895#issuecomment-711096332), adding `&& astTraverse.getType() != TokenTypes.COMPACT_CTOR_DEF` solves the problem.
Diff Regression config: https://gist.githubusercontent.com/anhminhtran235/c74908614e3465fade5de3c1d33fad5e/raw/ec75fe33dd75befe6b23185b9521c93cebb1c18b/check.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/cbc85ed26b809064dc260a246666743a/raw/a515faeb85836d1bb9987855cadc23fd3b63abfc/gistfile1.txt
=> Issue #8895: FinalLocalVariable: NPE in records

src/xdocs/index.xml.vm
Closes #8925
Subsections were missing their ids, so js code to take link name was returning undefined
=> Issue #8925: fix anchor links for front page subsections

.ci/wercker.sh
to pass on checkstyle snapshot version
reproduced in local even on master code.
failure - https://app.wercker.com/checkstyle/checkstyle/runs/build/5f9aca9c237ec900081ffd52?step=5f9acae1fddfc1000855aa55
detected at https://github.com/checkstyle/checkstyle/pull/8939#issuecomment-719579267
=> infra: update spring-cloud-gcp to use maven-checkstyle-plugin 3.1.1

src/xdocs/index.xml.vm
Remove bitbucket plugin from list of active tools.
Original link https://marketplace.atlassian.com/apps/1214095/checkstyles-for-bitbucket-server leads to 404 page, also there is no plugin in list of bitbucket apps.
=> minor: remove invalid bitbucket plugin from list of active tools

.ci/jsoref-spellchecker/whitelist.words, .semaphore/semaphore.yml
From https://github.com/checkstyle/checkstyle/pull/8920#discussion_r515509604
> one day this execution will fail in CI in PR, contributor might not be very experienced in CI to figureout how to reproduce it on local, so we will share with him link to single line in config for simple copy and paste in terminal, and it works.
=> config: make semaphore ci commands easy to run on local

config/checkstyle_checks.xml, config/suppressions.xml, src/xdocs/config_coding.xml, src/xdocs/config_filters.xml, src/xdocs/config_metrics.xml, src/xdocs/config_naming.xml, src/xdocs/config_sizes.xml
=> minor: fix indentation in config examples

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/AtclauseOrderCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocTagContinuationIndentationCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/NonEmptyAtclauseDescriptionCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SingleLineJavadocCheck.xml, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/javadoc/InputJavadocMetadataScraperAtclauseOrderCheck.java, src/xdocs/checks.xml, src/xdocs/config_javadoc.xml
from sourcecode and documentation
Issue #8552
what is left (we do not need to fix it):
```
✔ ~/java/github/romani/checkstyle [8552-at-clause L|✔] 
08:58 $ ag "at-clauses"
src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/javadoc/InputJavadocMetadataScraperAtclauseOrderCheck.java
41: * Note: Google used the term "at-clauses" for block tags in their guide till 2017-02-28.
src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
41: * Note: Google used the term "at-clauses" for block tags in their guide till 2017-02-28.
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/AtclauseOrderCheck.xml
13: Note: Google used the term "at-clauses" for block tags in their guide till 2017-02-28. …
```
=> Issue #8552: change all 'at-clause' terms to 'block tag'

src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
Issue: #8963 
Fixes nondeterministic logging of error messages in Translation Check.
=> Issue #8963: Make output of TranslationCheck deterministic

src/xdocs/writingchecks.xml
Issue: #8551.
Commit message should be: “Issue #8551: Consider relaxing the stated limitation about UTF-8” (sorry, just saw it when opening the PR).
The issue does not have the “approved” label, but I understood the comment there (asking to suggest better wording and referring to the source code of the website) as inviting me to introduce a PR. I hope this is okay.
=> Unambiguous limitation about ASCII

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheck.java, src/xdocs/config_javadoc.xml
Issue #7606: update doc for WriteTag
Output of first example:
```
<module name="WriteTag">
<property name="tag" value="@author"/>
<property name="tagFormat" value="\S"/>
</module>
</module>
</module>
```
`java -Djava.util.logging.config.file=log.properties -jar checkstyle-8.30-all.jar -c config.xml java_sandbox/src/com/codestyle/sandbox/Test.java`
```
[INFO] /Users/demezhanmarikov/IdeaProjects/java_sandbox/src/com/codestyle/sandbox/Test.java:4: Javadoc tag @author=Author [WriteTag]
[ERROR] /Users/demezhanmarikov/IdeaProjects/java_sandbox/src/com/codesty …
```
=> Issue #7606: updates docs for WriteTag

src/xdocs/config_blocks.xml
https://checkstyle.org/property_types.html%3ESeverityLevel
is result in 404 error
I am not sure why our link validator is not catching this, still open question
=> minor: fix link for LeftCurlyOption in LeftCurly

.ci/jsoref-spellchecker/whitelist.words, .ci/travis/travis.sh, src/it/java/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/MissingJavadocTypeTest.java, src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeCheck.java, src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule73wherejavadocrequired/InputMissingJavadocTypeCheckNoViolations.java, src/main/resources/google_checks.xml, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainViolationsForGoogle.java, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainViolationsForGoogleSuppressions.xml, src/xdocs/config_javadoc.xml, src/xdocs/google_style.xml
Issue #5148: Add MissingJavadocType to google_checks.xml
ATTENTION quotes from style guide:
> From https://google.github.io/styleguide/javaguide.html#s1.1-terminology:
"The term class is used inclusively to mean an "ordinary" class, enum class, interface or annotation type (`@interface`)."
> From https://google.github.io/styleguide/javaguide.html#s7.3-javadoc-where-required:
"At the minimum, Javadoc is present for every public class, and every public or protected member of such a class, with a few exceptions noted below."
This PR is a continuation of https://github.com/checkstyle/checkstyle/pull/8105.
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/32ddbff9e69986ac2fcbbeff7def2f80/raw/8480445657f1d215e683dbb6b14c1577bbd44e6b/projects-to-test-on.properties
Diff …
=> Issue #5148: Add MissingJavadocType to google_checks.xml

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordAsTopLevel.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java
Fix #8873 
This PR disables `requireThis` in COMPACT_CTOR_DEF, since `this` cannot be used in COMPACT_CTOR_DEF in Java 15 as mentioned [here](https://github.com/checkstyle/checkstyle/issues/8873#issuecomment-720129384).
As mentioned [here](https://github.com/checkstyle/checkstyle/issues/8873#issuecomment-723726379), not printing error message when `ast` is in `COMPACT_CTOR_DEF` solves the problem in #8873
Also, 4 violations in `testRecordsAsTopLevel()` are no longer violations, so I removed them.
Diff Regression config: https://gist.githubusercontent.com/anhminhtran235/bf0e177285c39256dd7e3217d8dae9e1/raw/55ff82d4be5a21d610e83da86dba7835eea2560d/config.xml
Diff Regression projects: https://gist.githubusercontent.com/anhminhtran235/2da94f96d35ab9471624c5b6c4421c66/raw/82b014453ca421085199b4 …
=> Issue #8873: RequireThis: Incorrectly triggers for record fields in compact constructor

.travis.yml
Issue #9046
One of markdownlint dependencies, chef-utils was recently [released](https://rubygems.org/gems/chef-utils) without support for older ruby versions, such as 2.5.3 that installed with ubuntu 16.04
As markdownlint is not dependent on new features from this release, we can continue to use old chef-utils version.
=> Issue #9046: use xenial compatible markdownlint

.ci/travis/travis.sh
token defined at https://cloud.drone.io/checkstyle/checkstyle/settings
pr number is from https://docs.drone.io/pipeline/environment/reference/drone-pull-request/
=> infra: update drone to have readonly token for verify-no-exception-configs valiation

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTypeCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_coding.xml
Closes #8933 
Default value is changed from null to empty list, setter is corrected to filter empty strings.
It seems that regression is not required.
=> Issue #8933: add handling of empty string in IllegalTypeCheck property

src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java
The issue https://github.com/junit-team/junit5/issues/1786 is still open, but it looks like `@TmpDir` is working as expected now.
We no longer need to do the obvious initialization/cleanup steps.
=> minor: remove junit5 workaround

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SwitchRuleHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionNewLine.java
Issue #9037: IndentationCheck throws NPE on line wrapped switch rule
Note that I have removed `TokenTypes.LAMBDA` from `SWITCH_RULE_CHILDREN[]`; there was already a redundancy between `SwitchRuleHandler` and `LambdaHandler`, so I decided to just let `LambdaHandler` do the work.
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/931b74d45ae7ff3b68f379898f9c816e/raw/c8d3c4f19440789c4eaaa17786ebc98d120dd22c/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/nmancus1/8277e4d4d979cd9745b86048999a20b5/raw/4064b88513abd5ac7f1af27616af47f168d0d1d4/Indentation.xml
=> Issue #9037: IndentationCheck throws NPE on line wrapped switch rule

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionTrailingCommentTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/trailingcomment/SuppressionXpathRegressionTrailingComment1.java, src/it/resources/org/checkstyle/suppressionxpathfilter/trailingcomment/SuppressionXpathRegressionTrailingComment2.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressionXpathFilter.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/xdocs/config_filters.xml
Issue #7763: Update AbstractChecks to log DetailAST - TrailingComment
from Roman: it is not implementation that I would like to have in this Check ideally, but let move refactoring to new issue.
https://github.com/checkstyle/checkstyle/issues/9009
https://github.com/checkstyle/checkstyle/issues/9010
Diff Regression projects: https://gist.githubusercontent.com/HuGanghui/709e0a8266eb1656488051b4cfc9161f/raw/5731ab3b42c995e5823e02a34a00c25241bcec1d/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/HuGanghui/d3b892a11fa52287ec1723246f12718f/raw/9576b09b677ea0cf838aa3ae451519597efd46ca/TrailingComment.xml
=> Issue #7763: Update AbstractChecks to log DetailAST - TrailingComment

.ci/jsoref-spellchecker/whitelist.words, .ci/validation.sh, .semaphore/semaphore.yml
Issue #9021
`validation.sh` installs `SNAPSHOT` version of the Checkstyle to the maven cache. But JOSM uses ANT, so it can't find the right jar file. To solve this problem, the `ivysettings.xml` file is patched to use the Checkstyle bundle from the `target` directory.
Before patching:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ivysettings>
<settings defaultResolver="josm-nexus"/>
<resolvers>
<ibiblio name="josm-nexus" m2compatible="true" root="https://josm.openstreetmap.de/nexus/content/repositories/public/"/>
<ibiblio name="jcenter" m2compatible="true" root="https://jcenter.bintray.com/"/>
</resolvers>
<modules>
<module organisation="ch.poole" name="OpeningHoursParser" resolver="jcenter"/>
</modules>
</ivysettings>
```
after patching
```xml
<?xml version="1.0" encoding="utf-8"?> …
```
=> Issue #9021: fix josm validation

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java
Resolves few items for #6295
Simply replacing lambda with `Function.identity()` solves mutation problem and make code prettier.
=> Issue #6295: resolve pitest issues for JavadocTagInfo

.github/workflows/diff_report.yml, .github/workflows/site.yml
Closes #9116 
Cache added for diff report generation and site generation.
Tests on local fork shows that site generation took 2,5 minutes vs 4 without cache, report took 4 minutes with cache vs 6,5 minutes without it (1 project, 1 check)
=> Issue #9116: add dependencies cache for maven in github actions

src/xdocs/index.xml.vm
https://app.codeship.com/projects/124310/builds/595d26c7-9546-4b84-968f-5d6cca11af2b?line=33703021-6716-42d9-92c2-4019201856ad&step=parallel_.ci%2Frun-link-check-plugin.sh
https://wheregoes.com/trace/
https://developer.github.com/v3/checks/runs/
redirect301 Redirect
https://docs.github.com/v3/checks/runs/
🍪
redirect301 Redirect
https://docs.github.com/v3/checks/runs
🍪
redirect301 Redirect
https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#runs
Trace Complete - Total Redirects:3
=> minor: fix link to redirected target that found by link-check-plugin

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters.java
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AXZvXAtca-Kxo9081VHK&open=AXZvXAtca-Kxo9081VHK
it is very questionable fix as all other regexp expressions are prone to the same problem, so fixing only one of them will not resolve problem. But we reduce reabability of code for sure, not that much but still. It might be good to keep all regexp in same format to keep code consistent in view.
-----
I marked as "wontfix" similar case https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AXZvXApaa-Kxo9081VHJ&open=AXZvXApaa-Kxo9081VHJ
```
context of this match is always small (names of identifiers or method names or class names).
Additional points:
- is that such change might change default values of some modules.
- we sometime print regexp to user …
```
=> Mark sonar violation 'Regular expressions should not overflow the stack' as false positive over AvoidEscapedUnicodeCharactersCheck

pom.xml
https://app.codeship.com/projects/124310/builds/30087815-da4a-4e15-8c18-0cf73ba3a00b?line=ee94ae31-1aef-48bf-8482-e20f3e2c4b34&step=parallel_.ci%2Frun-link-check-plugin.sh
```
2020-12-27 00:02:03
system ------------ grep of linkcheck.html--BEGIN
2020-12-27 00:02:03
system <td><i><a class="externalLink" href="https://liberapay.com/checkstyle/">
https://liberapay.com/checkstyle/</a>
: 503 Service Temporarily Unavailable</i></td></tr></table></td></tr>
2020-12-27 00:02:03
system ------------ grep of linkcheck.html--END
```
it is very stable failure for several builds and restart does not help
=> minor: exclude librepay.com from linkcheck plugin

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersEscapedS.java
Issue #9133: AvoidEscapedUnicodeCharacters should support '\s' escape symbol
and Issue #9159
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/931b74d45ae7ff3b68f379898f9c816e/raw/c8d3c4f19440789c4eaaa17786ebc98d120dd22c/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/nmancus1/895dff8ab31b89ef9623e98391767441/raw/4a83b19384168311d39053b43a06d640b0cdcd55/config.xml
In an effort to make `TEXT_BLOCK_LITERAL` content match that of an identical (after compilation) `STRING_LITERAL` content, I attempted to do the following:
```
String literal = ast.getText();
if (ast.getType() == TokenTypes.TEXT_BLOCK_CONTENT) {
literal = "\"" 
+ CheckUtil.stripIndentAndInitialNewLineFromTextBlock(ast.getText())
+ "\"";
}
```
However, pitest …
=> Issue #9133: AvoidEscapedUnicodeCharacters should support '\s' escape symbol

.ci/jsoref-spellchecker/whitelist.words, .ci/wercker.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AnnotationArrayInitHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnArrInit.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnArrInit2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationDifficultAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationZeroArrayInit.java
Fixes #9086 
Reverted to code point where we were not following forceStrictCondition for annotation array-elements.
Reverted to commit: https://github.com/Abhishek-kumar09/checkstyle/commit/543f240b13c90f7eec991824eb82ff1622d4e301 from Issue #5951 .
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/717190a7e2e06f4747b9c622692d4b99/raw/93fe7739cbdc52d7d17273a12d2b92328812c504/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/57961e5808a1495433051701ff921494/raw/e7a3d51cabe1f918782b547a40763a9152743691/gconfig.xml
=> Issue #9086: ForceStrictCondition should not affect individual array elements

.ci/wercker.sh
=> Issue #9176: Fix for no-error-pgjdbc is failing with "reference not a tree"

config/checkstyle_checks.xml
Issue #9137: Create MatchXpath instance to forbid usage of 'expected' element in Test annotation
```
➜  src cat config.xml 
<module name="MatchXpath">
<property name="query" value="//CLASS_DEF//OBJBLOCK//METHOD_DEF//MODIFIERS//
ANNOTATION[.//IDENT[@text='Test']]//ANNOTATION_MEMBER_VALUE_PAIR
[.//IDENT[@text='expected']]"/>
<message key="matchxpath.match" value="Avoid using ''expected'' in Test annotation."/>
</module>
</module>
</module>
➜  src cat XPathExpectedMatcher.java 
import org.junit.Test;
public class XPathExpectedMatcher {
@Test(expected = …
```
=> Issue #9137: Create MatchXpath instance to forbid usage of 'expected'

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsShadowed.java
Issue #4219
Instead of collecting types into the plain list, collect them for the current frame only.
Then remove all locally declared types and pull the rest up to the parent frame.
On the top level there will be plain list, but without any locally declared types.
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/32ddbff9e69986ac2fcbbeff7def2f80/raw/8480445657f1d215e683dbb6b14c1577bbd44e6b/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/pbludov/25180f2628587d294328749677a73c30/raw/2f786c594fd647f3eb42031eded04f1575a3aafd/unused-imports.xml
=> Issue #4219: UnusedImports doesn't recognize imports shadowed by inner types

.ci/validation.sh, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Issue #9003: nondex tool found issue in token ordering at Indentation
This PR hopefully resolves #9003.  I have included the nondex update to verify that using an ordered data structure (LinkedHashSet) vs. a non-ordered structure (HashSet) resolves the issue.
First CI run:
failure at https://checkstyle.semaphoreci.com/jobs/d793aa43-1d5e-4058-991f-432f75525a99
`AllChecksTest.testAllCheckTokensAreReferencedInGoogleConfigFile:394->validateAllCheckTokensAreReferencedInConfigFile:451->validateDefaultTokens:479 All default tokens should be used in config for Indentation`
` JavadocPropertiesGeneratorTest.testNonExistentArgument:111 Unexpected error log ==> expected: <Missing required options and parameters: '--destfile=<outputFile>', '<inputFile>'`
=> Issue #9003: nondex tool found issue in token ordering at Indentation

src/site/resources/js/anchors.js
Found during https://github.com/checkstyle/checkstyle/pull/9183
In generated pages, e.g. for project summary, anchors for subsection are broken. For example https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/fix_button_2021113707/summary.html
=> minor: fix anchors for generated pages

.ci/jsoref-spellchecker/whitelist.words, .ci/wercker.sh
Use pgjdbc original fork as the wercker repo for no-error-pgjdbc
=> infra: use pgjdbc original fork as the repo for wercker checks

.github/workflows/diff_report.yml
Closes #9177 
Adds label to report message, it is parsed from PR description line "Report label: "
If there is no such line, no label added to report.
Example PR https://github.com/strkkk/checkstyle/pull/16
PR with updated documentation https://github.com/checkstyle/contribution/pull/540
Results in
=> Issue #9177: add label for diff report from PR description

src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
Closes #8932
Also message for incorrect id was changes to be similar and clearer
=> Issue #8932: fix invalid token name or id messages

config/checkstyle_non_main_files_suppressions.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/design/DesignForExtensionCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRequiredJavadocPhrase.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRequiredJavadocPhraseMultiLine.java, src/xdocs/config_design.xml
Issue #4358: add requiredJavadocPhrase to DesignForExtensionCheck
I have simplified the logic quite a bit from the previous PR. The responsibility of implementing the `requiredJavadocPhrase` pattern (regex) should be on the user; we should not need to modify the text of the javadoc comment. We are only checking for a match anywhere within the javadoc, not an exact match of the entire contents of the javadoc.
Note that this new property's default value is to match anything; that is, the check will still have the original behavior unless the phrase is changed.  I am making a patch config with the recommended `This implementation`... to make sure this works as intended.  I can run this a few times if we need to.
Link to site: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/issue-43 …
=>  Issue #4358: add requiredJavadocPhrase to DesignForExtensionCheck

config/checkstyle_checks.xml, config/checkstyle_non_main_files_suppressions.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGenerationException.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocMissingLeadingAsteriskCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/invalid_metadata/InputJavadocMetadataScraperPropertyMisplacedDefaultValueCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/invalid_metadata/InputJavadocMetadataScraperPropertyMisplacedTypeCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/invalid_metadata/InputJavadocMetadataScraperPropertyMissingDefaultValueCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/invalid_metadata/InputJavadocMetadataScraperPropertyMissingTypeCheck.java, src/xdocs/config_design.xml
Closes #9204 
1. Metadata tool code is changed to fail in case default value or type is misssing/misplaced
2. Suppression mentioned in issue is fixed.
3. Added check to make sure that properties for metadata generation are on new javadoc line.
4. Fixed one issue with properties that was found after check addition.
=> Issue #9204: Change metadata generator to fail on invalid properties

src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
#9140 
related PR https://github.com/checkstyle/checkstyle/pull/9153
=> Issue #9140: fix regexp TOKEN_TEXT_PATTERN in JavadocMetadataScraper

.ci/jsoref-spellchecker/whitelist.words, src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java, src/xdocs/config_filefilters.xml
based on discussion from https://github.com/checkstyle/checkstyle/issues/3523#issuecomment-765615028
=> doc: udpate BeforeExecutionExclusionFileFilter to show example of negative lookahead

src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/commonutil/InputCommonUtilTestWithChecks.xml, src/xdocs/property_types.xml
Issue #9170: Checkstyle should support "classpath:" protocol
The logic in my changes maintain the order of searching for resources; the original PR at https://github.com/checkstyle/checkstyle/pull/8789/files forced `getUriByFilename()` to check the classpath first if `classpath:` protocol is specified.  Since I have refactored this method, it will be simple to add this logic in this PR or later if we decide to.
Also, it will now be simple to add support for `file:` protocol, however, `getUrl()` currently supports this.
=> Issue #9170: Checkstyle should support "classpath:" protocol

.ci/jsoref-spellchecker/whitelist.words, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/ChainedPropertyUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ChainedPropertyUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainPropertyChaining.properties, src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainPropertyChainingUndefinedProperty.properties, src/test/resources/com/puppycrawl/tools/checkstyle/utils/chainedpropertyutil/InputChainedPropertyUtil.properties, src/test/resources/com/puppycrawl/tools/checkstyle/utils/chainedpropertyutil/InputChainedPropertyUtilRecursiveUnresolvable.properties, src/test/resources/com/puppycrawl/tools/checkstyle/utils/chainedpropertyutil/InputChainedPropertyUtilUndefinedProperty.properties, src/xdocs/config_system_properties.xml
Issue #9173: Checkstyle should support property expansion within property definitions (property chaining)
Link to documentation: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/issue-9173_2021201706/config_system_properties.html
=> Issue #9173: Checkstyle should support property chaining

pom.xml
Closes: #9217 
$cat log pom.xml 
```
<plugin>
<groupId>nl.demon.shadowland.maven.plugins</groupId>
<artifactId>sonarqube-maven-report</artifactId>
<version>0.2.2</version>
</plugin>
```
Before change URL - `https://sonarcloud.io/project/index/com.puppycrawl.tools:checkstyle`
Current URL - `https://sonarcloud.io/dashboard?id=com.puppycrawl.tools%3Acheckstyle`
Desired URL - `https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle`   
I am not able to change `com.puppycrawl.tools` with `org.checkstyle`. Kindly comment on how to solve this.
=> Issue #9217: Sonar Dashboard link doesn't work

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/xdocs/config_coding.xml
Issue #7643: 
I closed the previous PR #9154 
Add code example
```
$ cat my_checks.xml
<module name="IllegalInstantiation">
</module>
</module>
</module>
$ cat MyTest.java
public class MyTest {
public class Boolean {
boolean a;
public Boolean (boolean a) { this.a = a; }
}
public void myTest (boolean a, int b) {
Boolean c = new Boolean(a); // OK
java.lang.Boolean d = new java.lang.Boolean(a); // OK
Integer e = new Integer(b); // OK
Integer f = Integer.valueOf(b); // OK
}
}
$ java -jar checkstyle-8.39-all.jar -c …
```
=> Issue #7643: Update doc for IllegalInstantiation

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.java, src/xdocs/config_coding.xml
Resolves #7635.
Website after update - 
`$ cat conifg.xml`
```xml
<module name="DeclarationOrder"/>
</module>
</module>
```
```java
public int a;
protected int b;
public int c;            // violation, variable access definition in wrong order
Test() {
this.a = 0;
this.b = 0;
this.c = 0;
this.name = "";
}
// This method does nothing
}
Test(int a, int b, int c, String name) {   // violation, constructor definition in wrong order
this.a = a;
this.b = b;
this.c = c;
this.name = name;
}
private String name;     // violation, instance variable declaration …
```
=> Issue #7635: Update doc for DeclarationOrder

src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
As identified in https://github.com/checkstyle/checkstyle/pull/9225#issuecomment-774683879 , this swaps the master list we use in `TreeWalker` to store tokens as integers instead of strings.
=> swap treewalker token master list to integer from string

.ci/jsoref-spellchecker/whitelist.words, config/sevntu_suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGenerationException.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/xmlmetareader/InputXmlMetaReaderCheckNoProps.xml, src/test/resources/com/puppycrawl/tools/checkstyle/meta/xmlmetareader/InputXmlMetaReaderCheckWithProps.xml, src/test/resources/com/puppycrawl/tools/checkstyle/meta/xmlmetareader/InputXmlMetaReaderFileFilter.xml, src/test/resources/com/puppycrawl/tools/checkstyle/meta/xmlmetareader/InputXmlMetaReaderFilter.xml
Relates to #8771
1. Some unnecessary null checks has been removed
2. Added tests for XmlMetaReader
3. Constructor with cause in MetadataGenerationException is removed + suppression added, since this ctor is not used anywhere and there is no need for it.
4. Coverage data is changed, exclude list is changed to have only specific classes instead of whole meta package
=> Improve metadata code and coverage

src/xdocs/google_style.xml
Detected at https://github.com/checkstyle/checkstyle/issues/5089#issuecomment-774998752
Limitation does not exist anymore
=> doc: remove outdated limitation from google style doc

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java, src/xdocs/config_coding.xml
Issue #7641: Adding code examples for HiddenField check
=> Issue #7641: Adding code examples for HiddenField check

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/xdocs/config_coding.xml
Resolves #7656 
Website after update - 
`$ cat check_config.xml`
```xml                 
<module name="RequireThis">
</module>
</module>
</module>
```
```java
private int a;
private int b;
private int c;
public Test(int a) {
// overlapping by constructor argument
this.a = a;       // OK, this keyword used
b = 0;            // OK, no overlap
foo(arg);         // OK, no overlap
}
public void foo(int c) {
// overlapping by method argument
c = c;            // violation, reference to instance variable "c" requires "this"
}
}
```
`$ java com.puppycrawl.tools.checkstyle.Main …
=> Issue #7656: Update doc for RequireThis

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInEnumerationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noenumtrailingcomma/InputNoEnumTrailingComma.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicoloninenumeration/InputUnnecessarySemicolonInEnumeration.java
Fixes for #8653
NoEnumTrailingCheck is rewritten to handle empty enums with only comma as well (there was no violation before since it inspected ENUM_CONSTANT_DEF token instead of ENUM_DEF).
UnnessaryEnumSemicolonCheck test inputs were extended with enum with only comma.
=> Correct NoEnumTrailingCheck and UnnessaryEnumSemicolonCheck to handle empty enums

.ci/validation.sh
All Checkstyle issues are resolved in JOSM. We can use stable version in the CI.
=> infra: use stable version of josm in ci

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java, src/xdocs/config_imports.xml
Closes: #7686
**Output of the default configuration:-**
```
<property name="tabWidth" value="7"/>
<module name="CustomImportOrder"/>
</module>
</module>
```
`$ cat Hello.java`
```
package com.company;
import org.apache.commons.io.fileutils; //OK
import static java.util.*; //OK
import java.time.*; //OK
import static java.io.*; //OK
import com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck; //OK
import com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck; //OK
```
```
$ java -jar checkstyle-8.39-all.jar -c config.xml Hello.java
Audit done.
``` …
=> Issue #7686: Update doc for CustomImportOrder

.circleci/config.yml
Issue #9115
https://app.circleci.com/pipelines/github/checkstyle/checkstyle/4862/workflows/900f96cd-378f-4209-b45b-89fd48fe6d30/jobs/74172
it is not easy to reproduce connection failure, but I think we can trust their documentation, in worse case we will reopen issue.
=> Issue #9115: try to downlaod artifacts one more time in circle ci

src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java, src/xdocs/config_misc.xml
I have added examples for the UniqueProperties Check, Closes #7595 . Request the admins to verify and point out any changes if required.
`$ cat cnf.xml `
```
<module name="UniqueProperties"/>
</module>
```
`$ cat app.properties`
```
key.one=44
key.two=32 
key.one=54
```
`$ java -jar checkstyle-8.40-all.jar -c cnf.xml app.properties`
```
[ERROR] /home/divesh/Desktop/app.properties:1: Duplicated property 'key.one' (2 occurrence(s)). [UniqueProperties]
Audit done.
```
`$ cat cnf.xml `
``` …
```
=> Issue #7595: Update doc for UniqueProperties

.ci/idea_inspection.sh, .ci/no_old_refs.sh, .ci/run-link-check-plugin.sh, .ci/sonar-wrapper.sh, .ci/sonar.sh, config/checkstyle_non_main_files_checks.xml, config/intellij-idea-inspections.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/CheckstyleAntTaskPowerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/testmodules/CheckstyleAntTaskLogStub.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/testmodules/CheckstyleAntTaskStub.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/testmodules/MessageLevelPair.java
Related to #9256 
I found one more pattern for to do issues, it is like `till #<issue number>`
1. This pattern is added to job for checking source code
2. Violations fixed for closed items
3. Second commit - found bug in checkstyle check for checking whitespaces after comments in sh files. Added a new check for it and fixed violations. May be new PR is needed for this change?
=> Add one more closed to do issue pattern and fix violations

pom.xml
Remove suppression [fixed](https://github.com/hcoles/pitest/pull/860) in 1.6.3.
=> minor: remove pitest suppression for loadUri

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Fixes #9285: The template is read from the first line, since the first line doesn't matchup with the github extensible template, it is failing to create an issue template.
=> minor: Fix github issue template not working

.ci/no_old_refs.sh, config/spotbugs-exclude.xml, pom.xml
Related to #9256 
1. Job is changed to detect closed issues in other repos as well
2. Violations are fixed (spotbugs and pitest)
=> Extend closed issues job to check issues in other repos

src/xdocs/report_issue.xml
1. Added `-n` flag to `cat` commands. This flag adds line numbers to file content, which very useful for detecting issues, especially when file is long. For example https://github.com/checkstyle/checkstyle/issues/8546
Unfortunately, I couldn't find similar thing for windows (sigh).
2. Jar version is changed to X.XX to be consistent across patterns.
=> doc: improve issue templates

config/spotbugs-exclude.xml, src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java
Fixes #9297 
Violations for `AbstractCheck` and `AbstractFileSetCheck` are suppressed. 
Methods `setFileContents` and `clearMessages` are part of the public API, so it's hard to change them.
The field `JavadocDetailNodeParser#errorListener` is a local variable now.
=> Issue #9297: solve spotbugs violations for java 11

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
Fixes #7877 
**Pitest Report before fix:** https://bossever.github.io/issue7877/pit-reports/202102122217/com.puppycrawl.tools.checkstyle.checks.imports/ImportOrderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@476dda8b_878
[Hardcoded mutation on line 878](https://github.com/bossever/checkstyle/commit/7e0c2b518fe06f41175f1106d1d3bb1e9b00ca32): `removed conditional - replaced equality check with true → SURVIVED`
**Pitest Report after fix:** https://bossever.github.io/issue7877/pit-reports/202102182308/com.puppycrawl.tools.checkstyle.checks.imports/index.html
I tried coming up with test cases where the mutation could be killed, but came to the conclusion that there exists no such test case, please read comment on issue - …
=> Issue #7877: Removed redundant conditional

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java
Fixes #5711, resolves #8183
Similar to #8002, the problem is with the logic behind how a violation is determined. Previously we only checked the `TEXT` node itself. If the `TEXT` is only a short whitespace (not enough indentation), we ignored it when in fact we need to check if there is a non-newline token (such as a `JAVADOC_INLINE_TAG `) immediately after it.
~~Regression: https://wltan.github.io/checkstyle-reports/2020-05-10/javadoctagcont-blocktag/
There are violations within Checkstyle itself which were not previously detected due to this issue. They can be found in the regression report as well. I've fixed those violations to use the correct indentation, in a separate commit so it's easier to tell from the main changes, and I'll squash it back into one commit if requested after …
=> Issue #5711: JavadocTagContinuationIndentation: no violation with block tag starting the line

.ci/no-exception-test.sh
infra: add checkout_from support to no-exception-test.sh
As mentioned at https://github.com/checkstyle/checkstyle/pull/9278/files#r576851236, I have separated the addition of the `checkout_from` bash function from the changes at #9278.
=> infra: add checkout_from support to no-exception-test.sh

.ci/eclipse-compiler-javac.sh, .ci/jsoref-spellchecker/whitelist.words, .ci/validation.sh, .semaphore/semaphore.yml, pom.xml, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packageannotation/SuppressionXpathRegressionPackageAnnotationOne.java, src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/packageannotation/SuppressionXpathRegressionPackageAnnotationTwo.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation2.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationLang.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameUnderscore.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeAllowedAnnotations.java
Fixes #9310
The import `sun.*` replaced with `sun.reflect.*`, `sun.applet.*` replaced with `sun.misc.*`, 
The annotation `javax.annotation.Generated` replaced with `java.lang.SuppressWarnings`.
Two new build configs for semaphore CI with `java.version=11`: one for OpenJdk11 javac, another for Eclipse compiler.
=> #Issue #9310: test inputs should be compilable with javac11

.ci/pitest.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
Fixes #9317
1) Pitest report: https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239317/pit-reports/202102231422/com.puppycrawl.tools.checkstyle.checks.header/RegexpHeaderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@73367fcc_249
2) Surviving mutation: removed conditional - replaced equality check with false → SURVIVED
3) Regression report: https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239317/diff/index.html
From https://github.com/checkstyle/checkstyle/pull/9305#issuecomment-781747766
=> Issue #9317: Resolve Pitest Issues - RegexpHeader

.ci/wercker.sh, .github/workflows/site.yml
Reason: long list of downloads makes in difficult to find useful information, e.g. for sonar: https://app.wercker.com/checkstyle/checkstyle/runs/build/60311065237ec900083b7685?step=60311852476e90000847aad5
and site generation.
`ntp` flag (stands for "no-transfer-progress") suppresses all entries like
```
Downloading from central: ...
Downloaded from central: ...
```
May be there are other places where it can be useful?
=> minor: add maven flag to omit download progress

.ci/travis/travis.sh
Issue #9268
Identified at https://github.com/checkstyle/checkstyle/pull/7418 that xwiki's CI regression isn't complete. These changes are also temporarily in the other PR to show that fixes work and resolve any regression issues when breaking changes are introduced.
In addition `--depth 1` prevent checking out a different branch if an override is needed.
=> Issue #9268: add checkout_from for travis.sh

config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyDoubleBrace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyEmptyOnSingleLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyEndOfFile.java
Closes: #9271 
Continutation of #9288
Interestingly according to GitHub  [renaming](https://github.com/github/renaming/) the PR should automatically get targeted on renaming branch. But didn't happen with this one. It might be targeting PR on this branch and not from this branch. 
Sorry for that. Fixed points as pointed in #9288 in recent commit.
Diff Regression config: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/Issue9217/Issue9271/config-Issue9271-20210224194247.xml
Diff Regression projects: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/Issue9217/Issue9271/projects-to-test-on.properties
=> Issue #9271: Remove detailAstImp from Rcurly

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters.java
AvoidEscapedUnicodeCharactersCheck pattern for escaped chars is a bit incorrect.
According to [JLS](https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.3) char 'u' can be repeated many times, and it is still valid escape.
Note: pattern for whitespace escapes was not updated - it is causing sonar violation that require big refactoring of regex and tests.
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/2031b8f52d40c522c5cd8c343ff2c8af476082d7/confg.xml
Diff Regression projects: https://gist.githubusercontent.com/strkkk/29c0f3a0ce06a681afdf8d3c417a4b30/raw/f2771cee1ba63f0236377c2b55b77a2fb1fe45e0/small_projects
Report label: only jdk9
=> Fix escaped char pattern in AvoidEscapedUnicodeCharactersCheck

config/suppressions.xml, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMatchXpathTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedAmpChar.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedAmpString.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedAposChar.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedAposString.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedCarriageString.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedGreaterChar.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedGreaterString.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedLessChar.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedLessString.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedNewLineString.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedQuotChar.java, src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathEncodedQuoteString.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGenerator.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTextBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeChar.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeChar.xml, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeString.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathfilter/InputSuppressionXpathFilterEscapeString.xml, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorEscapeCharacters.java
Closes: #6893  
```
class A {
String quoteChar = "\"escaped\"" +
"2";
String lessChar = "<escaped" +
"3";
String ampersandChar = "&escaped" +
"4";
String greaterChar = ">escaped" +
"5";
String newLineChar = "escaped\n" +
"6";
String specialChar = "escaped\r" +
"6";
String aposChar = "'escaped'" +
"7";
}
```
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="OperatorWrapCheck"/>
</module>
</module>
```
```
$ java -jar java -jar checkstyle-8.41-SNAPSHOT-all.jar -c .\config.xml .\Test.java
[ERROR] H:\CheckstyleCheck\.\Test.java:3:36: '+' should be on a new line. …
```
=> Issue #6893: Generate Xpath Suppresion on escape xml symbols

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java, src/xdocs/config_javadoc.xml
Fixes #7605
**config_1.xml**
```
<module name="SingleLineJavadoc"/>
</module>
</module>
```
**Test_1_Invalid.java**
```
class Test_1_Invalid
{
/** @return 42 */ // violation, javadoc should be multiline
public int foo() {
return 42;
}
}
```
```
java -jar ~/Downloads/checkstyle-8.40-all.jar -c config_1.xml Test_1_Invalid.java
[ERROR] /home/lucifer/IdeaProjects/testing/src/Test_1_Invalid.java:3: Single-line Javadoc comment should be multi-line. [SingleLineJavadoc]
Audit done.
```
**Test_1_Valid.java**
```
public class Test_1_Valid
{
/**
* @return …
```
=> Issue #7605: Update doc for SingleLineJavadoc

.github/workflows/diff_report.yml
Closes #9323 
Branch name is replaced with 7 chars commit sha, which protects link from any special chars that can be in branch name
=> Issue #9323: replace branch name with hash in diff report action

src/main/resources/google_checks.xml
See issue #9335 
This is a pretty straight forward fix. I found it researching the checks in the provided Google Checks document.
The references to issues <code>#258</code> and <code>#259</code> were flipped.
=> Issue: #9335 Fix Issue links in Google Checks

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9373
```
$ javac Test.java 
$ 
a=b;
}
}
$ java -jar checkstyle-8.38-all.jar -t Test.java …
```
=> Issue #9373: Added Example of AST for TokenTypes.ASSIGN

.ci/run-link-check-plugin.sh, .github/workflows/run_link_check.yml, README.md, codeship-steps.yml, config/checkstyle_non_main_files_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SingleLineJavadocCheck.xml, src/site/resources/styleguides/google-java-style-20180523/javaguide.html, src/xdocs/config_javadoc.xml, src/xdocs/index.xml.vm
Move run link job to github actions and fix violations
```
<td><i><a class="externalLink" href="http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBEFIF">http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBEFIF</a>: 301 Moved Permanently</i></td></tr></table></td></tr>
<td><i><a class="externalLink" href="http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBEFIF">http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDBEFIF</a>: 301 Moved Permanently</i></td></tr></table></td></tr>
<td><i><a class="externalLink" href="https://docs.oracle.com/javase/8/docs/api/java/awt/Window.AccessibleAWTWindow.html?is-external=true">https://docs.oracle.com/javase/8/d …
```
=> minor: move run link check job to github action and fixed violations

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9397 
```
void foo(int a,int b,int c) {
c = a & b;
}
}
$ java com.puppycrawl.tools.checkstyle.Main -t sun_checks.xml Test.java
|   |   |   `--IDENT …
```
=> Issue #9397: Added example of AST for TokenTypes.BAND

src/main/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGenerator.java
fix for #8548
Rewrite the regex field `JavadocPropertiesGenerator.END_OF_SENTENCE_PATTERN`, to fix [this SonarQube warning](https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AXN1aAJJvRinlJ3puDUg&open=AXN1aAJJvRinlJ3puDUg).
* `(.*?[.?!])(\s|$)` - the original regex
* `([^.?!]*+[.?!])(\s|$)` - what SonarQube suggested
* `(([^.?!]|[.?!](?!\s|$))*+[.?!])(\s|$)` - what I used in the end
The problem with Sonar's suggestion is that it matches different things than the original pattern. For the input "Get obj.field.", their suggestion matches "field.", while the original pattern and my solution match the whole string.
The regex is a bit complex now. An alternative solution could be to write some Java code for finding the first sentence.
edit: fixed 3rd regex
=> Issue #8548: reformulate regex to fix Sonar warning

src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java, src/it/java/com/sun/checkstyle/test/base/AbstractSunModuleTestSupport.java, src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java, src/main/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinter.java, src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java, src/main/java/com/puppycrawl/tools/checkstyle/api/FileText.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentation.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodRecordsAndCompactCtors.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodThrowsDetection.java
Fix #8117 
~~Regression: https://wltan.github.io/checkstyle-reports/2020-04-18/javadocmethod-traverse/~~
Diff Regression projects: https://raw.githubusercontent.com/wltan/checkstyle-reports/master/auto-generate/pr-8213/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/wltan/checkstyle-reports/master/auto-generate/pr-8213/my_check.xml
There are violations within Checkstyle's own code that were not detected previously. I have fixed those in a separate commit, so that it is easier to tell apart from the main bug fix.
=> Issue #8117: False negative with validateThrows in JavadocMethod

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9577 
```
**Test.java**
public strictfp class Test {}
**AST**
|   |--LITERAL_PUBLIC -> public [1:0]
|   `--STRICTFP -> strictfp [1:7]
|--LITERAL_CLASS -> class [1:16]
|--IDENT -> Test [1:22]
`--OBJBLOCK -> OBJBLOCK [1:27]
|--LCURLY -> { [1:27]
`--RCURLY -> } [1:28]
```
```
|   |--LITERAL_PUBLIC -> public
|   `--STRICTFP -> strictfp
|--LCURLY -> {
`--RCURLY -> }
```
=> Issue #9577: add code example of AST for TokenTypes.STRICTFP

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9544 
```
>cat Test.java
void foo(double a) {
a = 3.14d;
}
}
|   |       |   `--LITERAL_DOUBLE -> double [2:13]
|   |       `--IDENT -> a [2:20]
|   |--RPAREN …
```
=> Issue #9544: Added example of AST for TokenTypes.NUM_DOUBLE

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9545 
```
>cat Test.java
void foo(float a) {
a = 3.14f;
}
}
|   |       |   `--LITERAL_FLOAT -> float [2:13]
|   |       `--IDENT -> a [2:19]
|   |--RPAREN -> …
```
=> Issue #9545: Added example of AST for TokenTypes.NUM_FLOAT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9546 
```
C:\Users\Shashwat>cat Test.java
void foo(int a) {
a = 3;
}
}
|   |       |   `--LITERAL_INT -> int [2:13]
|   |       `--IDENT -> a …
```
=> Issue #9546: Added example of AST for TokenTypes.NUM_INT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9547 
```
C:\Users\Shashwat>cat Test.java
void foo(long a) {
a = 3l;
}
}
|   |       |   `--LITERAL_LONG -> long [2:13]
|   |       `--IDENT …
```
=> Issue #9547: Added example of AST for TokenTypes.NUM_LONG

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9556 
```
C:\Users\Shashwat>cat Test.java
void foo(long a) {
a++;
}
}
|   |       |   `--LITERAL_LONG -> long [2:13]
|   |       `--IDENT -> a …
```
=> Issue #9556: Added example of AST for TokenTypes.POST_INC

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9513
```
$ cat MyClass.java 
public static int square(int x)
{
return x*x;
}
}
$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -t MyClass.java 
|   |   `--LITERAL_INT -> int [2:18]
|   |--IDENT -> square [2:22]
|   |--LPAREN -> ( [2:28]
|   |--PARAMETERS -> PARAMETERS [2:29]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:29]
|   |       |--MODIFIERS -> MODIFIERS [2:29]
|   | …
```
=> Issue #9513: Update example of AST for TokenTypes.METHOD_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9371 
Created an example AST for TokenTypes.ABSTRACT:
```
public abstract class MyClass
{
}
```
Please see the screenshot for the detail:
=> Issue #9371: Add example of AST for TokenTypes.ABSTRACT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9594
```
C:\Users\Hiron\Downloads>more Test.java
void foo(int a , int b) {
a = + b;
}
}
C:\Users\Hiron\Downloads>java -jar checkstyle-8.41-all.jar -t Test.java
| …
```
=> Issue #9594: update example of AST for TokenTypes.UNARY_PLUS

config/checkstyle_input_suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderCorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderIncorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderIncorrectCustom.java
Issue #9533: update AtclauseOrderCheckTest to use unique Input file in each test method
Added a few minor commits to update existing input files and removed corresponding suppression (https://github.com/checkstyle/checkstyle/pull/9613/commits/a92ea914b23e8825d3aba5c49f03baa6f3e70e2f) and to reformat (fix whitespace) in existing UT properties(https://github.com/checkstyle/checkstyle/pull/9613/commits/3ada3145503bee04a4a788e2b85b9643a4b829f6).
Note that warn/violation comments in https://github.com/checkstyle/checkstyle/pull/9613/commits/3ada3145503bee04a4a788e2b85b9643a4b829f6 changed location to match the existing UT, as they were not consistent.
=> Issue #9533: update AtclauseOrderCheckTest to use unique Input file in each test method

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java, src/xdocs/config_javadoc.xml
Closes: #7602
`λ cat config.xml`
```
<module name="JavadocVariable"/>
</module>
</module>
```
```
private int a; // violation, missing javadoc for private member
/**
* Some description here
*/
private int b; // OK
protected int c; // violation, missing javadoc for protected member
public int d; // violation, missing javadoc for public member
/*package*/ int e; // violation, missing javadoc for package member
}
```
`λ set RUN_LOCALE="-Duser.language=en -Duser.country=US"`
`λ java %RUN_LOCALE% -jar checkstyle-8.41-all.jar -c …
=> Issue #7602: add code examples for JavadocVariable

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
closes #9549 
```
% java -jar checkstyle-8.41-all.jar -t MyClass.java | grep "1:"
PACKAGE_DEF -> package [1:0]
|--ANNOTATIONS -> ANNOTATIONS [1:39]
|--DOT -> . [1:39]
|   |--DOT -> . [1:28]
|   |   |--DOT -> . [1:22]
|   |   |   |--DOT -> . [1:11]
|   |   |   |   |--IDENT -> com [1:8]
|   |   |   |   `--IDENT -> puppycrawl [1:12]
|   |   |   `--IDENT -> tools [1:23]
|   |   `--IDENT -> checkstyle [1:29]
|   `--IDENT -> api [1:40]
`--SEMI -> ; [1:43]
```
expected update for javodoc is:
```
PACKAGE_DEF -> package
|--ANNOTATIONS -> ANNOTATIONS
|--DOT -> .
|   |--DOT -> .
|   |   |--DOT -> .
|   |   |   |--DOT -> .
|   |   |   |   |--IDENT -> com
|   |   |   |   `--IDENT -> puppycrawl
|   |   |   `--IDENT -> tools
|   |   `--IDENT -> checkstyle
|   `--IDENT -> api
`--SEMI -> ;
```
=> Issue #9549 : updated example of AST for TokenTypes.PACKAGE_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9427 
```
public static boolean my(int a, int b) {
return a == b;
}
}
|--IDENT -> Tester [2:13]
`--OBJBLOCK -> OBJBLOCK [2:20]
|--LCURLY -> { [2:20]
|   |   `--LITERAL_STATIC -> static [3:8]
|   |--TYPE -> TYPE [3:15]
|   |   `--LITERAL_BOOLEAN -> boolean [3:15]
|   |--IDENT -> my [3:23]
|   |--LPAREN -> ( [3:25]
|   |--PARAMETERS -> PARAMETERS [3:26]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [3:26]
|   |   |   |--MODIFIERS -> …
```
=> Issue #9427: Added Example of AST for TokenTypes.EQUAL

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9587 
```
**Test.java**
class Comparable<T extends Serializable & CharSequence> {}
**AST**
λ  java -jar checkstyle-8.41-all.jar -t Test.java
|--LITERAL_CLASS -> class [3:0]
|--IDENT -> Comparable [3:6]
|--TYPE_PARAMETERS -> TYPE_PARAMETERS [3:16]
|   |--GENERIC_START -> < [3:16]
|   |--TYPE_PARAMETER -> TYPE_PARAMETER [3:17]
|   |   |--IDENT -> T [3:17]
|   |   `--TYPE_UPPER_BOUNDS -> extends [3:19]
|   |       |--IDENT -> Serializable [3:27]
|   |       |--TYPE_EXTENSION_AND -> & [3:40]
|   | …
```
=> Issue #9587: update example of AST for TokenTypes.TYPE_EXTENSION_AND

.gitattributes, src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathQueryGeneratorTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperTextBlock.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTextBlockCrlf.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/xpath/xpathquerygenerator/InputXpathQueryGeneratorTextBlockNewLine.java
Closes #9359 
```
$ cat InputXpathQueryGeneratorTextBlock.java 
//non-compiled with javac: Compilable with Java14
package com.puppycrawl.tools.checkstyle.xpath.xpathquerygenerator;
public class InputXpathQueryGeneratorTextBlock {
String testOne = """
&1line
>2line
<3line
""";
}
$ cat config.xml                            
<module name="IllegalToken">
<property name="tokens" value="STRING_LITERAL"/>
<property name="tokens" value="TEXT_BLOCK_CONTENT"/>
</module>
</module>
</module>
$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -c config.xml InputXpathQueryGeneratorTextBlock.java 
Starting …
```
=> Issue #9359: Match content of textblock by xpath

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java, src/xdocs/config_annotation.xml
Closes : #7572
```
<module name="MissingDeprecated"/>
</module>
</module>
```
```
class Demo{
@Deprecated
public static final int MY_CONST=13; // ok
/** This javadoc is missing deprecated tag. */
@Deprecated
public static final int COUNTER = 10; // violation
/** @deprecated
* <p></p>
*/
@Deprecated
public static final int NUM = 123456; // ok
/**
* @deprecated
*  <p>
*/
@Deprecated
public static final int CONST=12; // ok
}
```
`$ java -jar checkstyle-8.39-all.jar -c config.xml Demo.java`
```
[ERROR] E:\New …
```
=> Issue #7572: update doc for MissingDeprecated

config/checkstyle_checks.xml
Fixes #9138 
This check will raise violation at each `@Issue` annotation used in a Java source file.
I have placed the check module in the "coding" sub-section of `checkstyle_checks.xml`, in alphabetical order. Let me know if I should make any changes.
```xml
<module name="MatchXpath">
<property name="query" value="//ANNOTATION[./IDENT[@text='Issue']]"/>
<message key="matchxpath.match" value="Avoid using @Issue annotation."/>
</module>
</module>
</module>
```
```java
import org.junit.jupiter.api.Test;
@Test …
```
=> Issue #9138: Create MatchXpath instance to forbid usage of "@Issue"

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9590 :
```
public class MyClass<A, B> {
}
```
```
anmolsharma@Anmols-MacBook-Pro GSOC % java -jar checkstyle-8.41-all.jar -t MyClass.java
|--TYPE_PARAMETERS -> TYPE_PARAMETERS [1:20]
|   |--GENERIC_START -> < [1:20]
|   |--TYPE_PARAMETER -> TYPE_PARAMETER [1:21]
|   |   `--IDENT -> A [1:21]
|   |--COMMA -> , [1:22]
|   |--TYPE_PARAMETER -> TYPE_PARAMETER [1:24]
|   |   `--IDENT -> B [1:24]
|   `--GENERIC_END -> > [1:25]
`--OBJBLOCK -> OBJBLOCK [1:27]
|--LCURLY -> { [1:27]
```
Expected Update for Javadoc:
```
|   `--LITERAL_PUBLIC …
```
=> Issue #9590: updated example of AST for TokenTypes.TYPE_PARAMETERS

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9407 
```
public static char test() {
return 'a';
}
}
|--IDENT -> Tester [1:13]
|   |   `--LITERAL_CHAR -> char [2:15]
|   |--IDENT -> test [2:20]
|   |--PARAMETERS -> PARAMETERS [2:25]
|   |--RPAREN -> ) [2:25]
|   `--SLIST -> { [2:27]
|       |--LITERAL_RETURN -> return [3:2]
| …
```
=> Issue #9407: Added Example of AST for TokenTypes.CHAR_LITERAL

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java, src/xdocs/config_design.xml
Resolves #9357: FinalClass now exempts private-only constructor classes that also have nested subclasses
Note:- This will still give a violation if used inside the default package. Its fix is simple but writing an input class without package name is not permitted by checkstlye even if you write in the non-compilable resources folder. Code coverage will not be met without that.
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/85355576c05c80e8b08752a62ba3a4076909d266/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/be2b54fe328d0024818fe8aa52def42eca798c34/my_checks.xml
=> Issue #9357: FinalClass now exempts private-only constructor classes that also have nested subclasses

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheck.java, src/xdocs/config_whitespace.xml
Closes: #7618
`$ cat config.xml
`
```
<module name="EmptyForIteratorPad"/>
</module>
</module>
```
`$ cat Hello.java`
```
import java.util.*;
class Hello
{
{
HashMap<Integer,Integer> mp=new HahMap<Integer,Integer>();
for (Iterator foo =mp.entrySet().iterator();  foo.hasNext(); ); // violation since whitespace
//after semicolon
for (Iterator foo =mp.entrySet().iterator();  foo.hasNext();); // ok                                     
}
}
```
`$ java -jar checkstyle-8.39-all.jar -c config.xml Hello.java
`
```
[ERROR] E:\New folder\Java …
```
=> Issue #7618: Update doc for EmptyForIteratorPad

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9560 : 
```
public record MyRecord(Comp x, Comp... comps) {
}
```
Generated AST:
```
RECORD_DEF -> RECORD_DEF [1:0]
|--LITERAL_RECORD -> record [1:7]
|--IDENT -> MyRecord [1:14]
|--LPAREN -> ( [1:22]
|--RECORD_COMPONENTS -> RECORD_COMPONENTS [1:23]
|   |--RECORD_COMPONENT_DEF -> RECORD_COMPONENT_DEF [1:23]
|   |   |--ANNOTATIONS -> ANNOTATIONS [1:23]
|   |   |--TYPE -> TYPE [1:23]
|   |   |   `--IDENT -> Comp [1:23]
|   |   `--IDENT -> x [1:28]
|   |--COMMA -> , [1:29]
|   `--RECORD_COMPONENT_DEF -> RECORD_COMPONENT_DEF [1:31]
|       |--ANNOTATIONS -> ANNOTATIONS [1:31]
|       |--TYPE -> TYPE [1:31]
|       |   `--IDENT -> Comp [1:31]
|       |--ELLIPSIS -> ... [1:35]
| …
```
=> Issue #9560: updated example of AST for TokenTypes.RECORD_COMPONENT_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9562 
Source used to generate AST : 
```
public record MyRecord() {
}
```
Generated AST :
```
RECORD_DEF -> RECORD_DEF [1:0]
|--LITERAL_RECORD -> record [1:7]
|--IDENT -> MyRecord [1:14]
|--LPAREN -> ( [1:22]
|--RECORD_COMPONENTS -> RECORD_COMPONENTS [1:23]
|--RPAREN -> ) [1:23]
`--OBJBLOCK -> OBJBLOCK [1:25]
|--LCURLY -> { [1:25]
```
Expected Update for Javadoc:
```
RECORD_DEF -> RECORD_DEF 
|   `--LITERAL_PUBLIC -> public 
|--LITERAL_RECORD -> record 
|--IDENT -> MyRecord 
|--LPAREN -> ( 
|--RECORD_COMPONENTS -> RECORD_COMPONENTS
|--RPAREN -> ) 
|--LCURLY -> { 
`--RCURLY -> }
```
=> Issue #9562: updated example of AST for TokenTypes.RECORD_DEF

.ci/pitest.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java
Closes #9722 
Pitest Solved :- 
`"AbstractJavadocCheck.java.html:<td class='covered'><pre><span class='survived'> Arrays.sort(acceptableJavadocTokens);</span></pre></td></tr>"`
Added test to check binarySearch done properly, or else throws exceptions.
=> Issue #9722: Resolve Pitest Issue in Abstract Javadoc Check

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9399 
```
void block_comment_begin(){
/* Comment content
*/
}
}
```
```
|   |--IDENT -> block_comment_begin [2:9]
|   |--LPAREN -> ( [2:28]
|   |--PARAMETERS -> PARAMETERS [2:29]
|   |--RPAREN -> ) [2:29]
|   `--SLIST -> { [2:30]
|       |--BLOCK_COMMENT_BEGIN -> /* [3:8]
|       |   |--COMMENT_CONTENT ->  Comment …
```
=> Issue #9399: Updated the example of AST for TokenTypes.BLOCK_COMMENT_BEGIN

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9595 
` $ cat Test.java`
```java
private int PI = 3.14;
}
```
```sh
$ java -jar checkstyle-8.40-SNAPSHOT-all.jar -t test.java
|--VARIABLE_DEF -> VARIABLE_DEF [3:2]
|   |--MODIFIERS -> MODIFIERS [3:2]
|   |   `--LITERAL_PRIVATE -> private [3:2]
|   |--TYPE -> TYPE [3:10]
|   |   `--LITERAL_INT -> int [3:10]
|   |--IDENT -> PI [3:14]
|   |--ASSIGN -> = [3:17]
|   |   `--EXPR -> EXPR [3:19]
|   |       `--NUM_FLOAT -> 3.14 [3:19]
|   `--SEMI -> ; [3:23]
#Relevant AST Nodes for VARIABLE_DEF
$ java -jar checkstyle-8.40-SNAPSHOT-all.jar -t …
```
=> Issue #9595: Update example of AST for TokenTypes.VARIABLE_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9490 :
```
public class MyClass{
public int x;
}
```
Generated AST:
```
CLASS_DEF -> CLASS_DEF [22:0]
|--MODIFIERS -> MODIFIERS [22:0]
|   `--LITERAL_PUBLIC -> public [22:0]
|--LITERAL_CLASS -> class [22:7]
|--IDENT -> MyClass [22:13]
`--OBJBLOCK -> OBJBLOCK [22:20]
|--LCURLY -> { [22:20]
|--VARIABLE_DEF -> VARIABLE_DEF [23:4]
|   |--MODIFIERS -> MODIFIERS [23:4]
|   |   `--LITERAL_PUBLIC -> public [23:4]
|   |--TYPE -> TYPE [23:11]
|   |   `--LITERAL_INT -> int [23:11]
|   |--IDENT -> x [23:15]
|   `--SEMI -> ; [23:16]
`--RCURLY -> } [24:0]
```
```
|   `--LITERAL_INT -> int
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9490: updated example of AST for TokenTypes.LITERAL_PUBLIC

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9443 : 
Java Code used to generate AST:
```
int[] values = new int[10];
for (int value : values) {
doSmth();
}
}
}
```
Generated AST:
```
|   |--PARAMETERS -> PARAMETERS [2:39]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:39]
|   | …
```
=> Issue #9443: Updated example of AST for TokenTypes.FOR_EACH_CLAUSE

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9568
Code used for Generating example: 
```
mahmoud:~/Desktop/checkstyle$ more Test.java 
// Comment Content
public class A {
}
```
```
mahmoud:~/Desktop/checkstyle$ java -jar checkstyle-8.41-all.jar -T Test.java 
|   |--SINGLE_LINE_COMMENT -> // [1:0]
|   |   `--COMMENT_CONTENT ->  Comment Content\n [1:2]
|--IDENT -> A [2:13]
`--OBJBLOCK -> OBJBLOCK [2:15]
|--LCURLY -> { [2:15]
```
Expected update for JavaDoc is:
```
SINGLE_LINE_COMMENT -> //
`--COMMENT_CONTENT ->  Comment Content\n
```
=> Issue #9568: update example of AST for TokenTypes.SINGLE_LINE_COMMENT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9456: 
```
public interface MyInterface {
}
```
Generated AST:
```
INTERFACE_DEF -> INTERFACE_DEF [1:0]
|--LITERAL_INTERFACE -> interface [1:7]
|--IDENT -> MyInterface [1:17]
`--OBJBLOCK -> OBJBLOCK [1:29]
|--LCURLY -> { [1:29]
```
```
INTERFACE_DEF -> INTERFACE_DEF
|--LITERAL_INTERFACE -> interface
|--IDENT -> MyInterface
|--LCURLY -> {
`--RCURLY -> }
```
=> Issue #9456: updated example of AST for TokenTypes.INTERFACE_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9483 :
```
public interface MyInterface {
}
```
Generated AST:
```
INTERFACE_DEF -> INTERFACE_DEF [1:0]
|--LITERAL_INTERFACE -> interface [1:7]
|--IDENT -> MyInterface [1:17]
`--OBJBLOCK -> OBJBLOCK [1:29]
|--LCURLY -> { [1:29]
```
```
INTERFACE_DEF -> INTERFACE_DEF
|--LITERAL_INTERFACE -> interface
|--IDENT -> MyInterface
|--LCURLY -> {
`--RCURLY -> }
```
=> Issue #9483: updated example of AST for TokenTypes.LITERAL_INTERFACE

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9504 
```
void literal_void(){}
}
```
```
|   |--IDENT -> literal_void [2:9]
|   |--LPAREN -> ( [2:21]
|   |--PARAMETERS -> PARAMETERS [2:22]
|   |--RPAREN -> ) [2:22]
|   `--SLIST -> { [2:23]
|       `--RCURLY -> } [2:24]
```
```
$ java -jar checkstyle-8.41-all.jar -T Test.java | grep "2:4\|2:9" …
```
=> Issue #9504: updated example of AST for TokenTypes.LITERAL_VOID

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9482 : 
```
public int x;
}
```
Generated AST:
```
|   |   `--LITERAL_INT -> int [2:11]
|   |--IDENT -> x [2:15]
```
```
|  `--LITERAL_PUBLIC -> public
|  `--LITERAL_INT -> int
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9482: updated example of AST for TokenTypes.LITERAL_INT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9484 : 
```
public long x;
}
```
Generated AST:
```
|   |   `--LITERAL_LONG -> long [2:11]
|   |--IDENT -> x [2:16]
|   `--SEMI -> ; [2:17]
```
```
--MODIFIERS -> MODIFIERS
`--LITERAL_PUBLIC -> public
--TYPE -> TYPE
`--LITERAL_LONG -> long
--IDENT -> x
`--SEMI -> ;
```
=> Issue #9484: updated example of AST for TokenTypes.LITERAL_LONG

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Close: #9552 
Generated javadoc:
Code sample:
```
$ javac --release 15 --enable-preview ~/Test9552.java
Note: /home/jianz/Test9552.java uses preview language features.
Note: Recompile with -Xlint:preview for details.
$ cat ~/Test9552.java
public class Test9552 {
public void checkInstance(Object obj) {
if (obj instanceof String str) {}
}
}
```
Relevant AST:
```
$ java -jar target/checkstyle-8.42-SNAPSHOT-all.jar -t ~/Test9552.java | grep "3:"
|       |--LITERAL_IF -> if [3:4]
|       |   |--LPAREN -> ( [3:7]
|       |   |--EXPR -> EXPR [3:12]
|       |   |   `--LITERAL_INSTANCEOF -> instanceof [3:12]
|       |   |       |--IDENT -> obj [3:8]
|       |   |       `--PATTERN_VARIABLE_DEF -> PATTERN_VARIABLE_DEF [3:23]
|       |   |           |--TYPE -> TYPE [3:23]
|       |   |           | …
```
=> Issue #9552: update example of AST for TokenTypes.PATTERN_VARIABLE_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue: #9489 
```
public class MyClass{
protected int x;
}
```
Generated AST:
```
|--VARIABLE_DEF -> VARIABLE_DEF [2:2]
|   |   `--LITERAL_PROTECTED -> protected [2:2]
|   |--TYPE -> TYPE [2:12]
|   |   `--LITERAL_INT -> int [2:12]
|   |--IDENT -> x [2:16]
|   `--SEMI -> ; [2:17]
```
```
|   `--LITERAL_PROTECTED -> protected
|   `--LITERAL_INT -> int
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9489: add example of AST for TokenTypes.LITERAL_PROTECTED

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9493 : 
```
public short x;
}
```
Generated AST:
```
|   |   `--LITERAL_SHORT -> short [2:11]
|   |--IDENT -> x [2:15]
```
```
|  `--LITERAL_PUBLIC -> public
|  `--LITERAL_SHORT -> short
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9493: updated example of AST for TokenTypes.LITERAL_SHORT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9477 : 
```
public float x;
}
```
Generated AST:
```
|   |   `--LITERAL_FLOAT -> float [2:11]
|   |--IDENT -> x [2:15]
```
```
|  `--LITERAL_PUBLIC -> public
|  `--LITERAL_FLOAT -> float
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9477: updated example of AST for TokenTypes.LITERAL_FLOAT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9494 
Source used to generated AST
```
public static int x;
}
```
Generated AST
```
|   |   `--LITERAL_INT -> int [2:18]
|   |--IDENT -> x [2:22]
|   `--SEMI -> ; [2:23]
```
```
$ java -jar checkstyle-8.41-all.jar -T Test.java | grep "2:"
| …
```
=> Issue #9494: updated example of AST for TokenTypes.LITERAL_STATIC

src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/IllegalIdentifierNameCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/IllegalIdentifierNameCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/illegalidentifiername/InputIllegalIdentifierNameLambda.java, src/xdocs/config_naming.xml
Issue #9756: IllegalIdentifierName doesn't check single no-parentheses lambda parameter
Diff Regression config: https://gist.githubusercontent.com/nmancus1/2267f758c41c127dfee6c6c73c655b0c/raw/c1a31b23cd28a0a476b094790fbf034c26757e01/base.xml
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/a89d2614131e8c0a44f3b31cb6775598/raw/c9476797246225ab23ce707662e1e6b9ce2caa4e/gistfile1.txt
=> Issue #9756: IllegalIdentifierName doesn't check single lambda parameter

.ci/jsoref-spellchecker/whitelist.words, .ci/travis/travis.sh, .ci/validation.sh, .ci/wercker.sh, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocMethodCheck.xml, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodPublicOnly.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodSurroundingAccessModifier.java, src/test/resources/com/puppycrawl/tools/checkstyle/utils/checkutil/InputCheckUtilTest.java, src/xdocs/config_javadoc.xml
Issue #7417: change scope to access modifier in JavadocMethodCheck
1. Need regression reports for JavadocMethodCheck, and RecordComponentNumberCheck.
Failing CI:
1. `./.ci/wercker.sh no-error-equalsverifier` - [uses scope property in config](https://app.wercker.com/checkstyle/checkstyle/runs/build/6054d9b9237ec90008473aa6?step=6054dfea476e900008b0f46c)
2.  `./.ci/travis/travis.sh no-error-xwiki` - [uses scope property in config](https://travis-ci.org/github/checkstyle/checkstyle/jobs/763584503)
3.  ` .ci/validation.sh no-error-pmd`  - [uses scope property in config](https://checkstyle.semaphoreci.com/jobs/d8ae46ab-f367-4a12-b17c-a7991ec296d7)
Link to specific check documentation: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/issue-7417_2021172805/config_javadoc.html#JavadocMet …
=> Issue #7417: change scope to access modifier in JavadocMethodCheck

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9491:
```
public record MyRecord () {
}
```
Generated AST:
```
RECORD_DEF -> RECORD_DEF [1:0]
|--LITERAL_RECORD -> record [1:7]
|--IDENT -> MyRecord [1:14]
|--LPAREN -> ( [1:23]
|--RECORD_COMPONENTS -> RECORD_COMPONENTS [1:24]
|--RPAREN -> ) [1:24]
`--OBJBLOCK -> OBJBLOCK [1:26]
|--LCURLY -> { [1:26]
```
```
RECORD_DEF -> RECORD_DEF
|--LITERAL_RECORD -> record
|--IDENT -> MyRecord
|--LPAREN -> (
|--RECORD_COMPONENTS -> RECORD_COMPONENTS
|--RPAREN -> )
|--LCURLY -> {
`--RCURLY -> }
```
=> Issue #9491: updated example of AST for TokenTypes.LITERAL_RECORD

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9488 : 
```
private int x;
}
```
Generated AST:
```
|   |   `--LITERAL_PRIVATE -> private [2:4]
|   |--TYPE -> TYPE [2:12]
|   |   `--LITERAL_INT -> int [2:12]
|   |--IDENT -> x [2:16]
|   `--SEMI -> ; [2:17]
```
```
|   `--LITERAL_PRIVATE -> private
|   `--LITERAL_INT -> int
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9488: updated example of AST for TokenTypes.LITERAL_PRIVATE

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9559 
```
void foo(){} 
} 
```
```
|   |--RPAREN -> ) [2:13]
|   `--SLIST -> { [2:14]
|       `--RCURLY -> } [2:15]
```
```
$ java -jar checkstyle-8.41-all.jar -T Test.java | grep "2:15"
|--METHOD_DEF -> METHOD_DEF …
```
=> Issue #9559: update example of AST for TokenTypes.RCURLY

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9514
**Test.java**
```
import java.util.*;
void test() {
Comparator<String> compare = String::compareToIgnoreCase;
}
}
```
**AST**
```
|   `--STAR -> * [1:17]
`--SEMI -> ; [1:18]
|--METHOD_DEF -> METHOD_DEF [4:1]
|   |--TYPE -> TYPE [4:1]
|   |   `--LITERAL_VOID -> void [4:1]
|   |--IDENT -> test [4:6] …
```
=> Issue #9514: update example of AST for TokenTypes.METHOD_REF

src/main/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilter.java, src/xdocs/config_filefilters.xml
fixes Issue #8269 :
added last example
=> Issue #8269:Update documentation for BeforeExecutionExclusionFileFilter

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue #9449
Java code use to generate AST :
<pre>
<code>
public static void main(String[] args)
{
int a=10,b=0; boolean c;
c=a>b;
System.out.println(c);
}
}
</code>
</pre>
Generated AST:
<pre>
<code>
|--IDENT -> MyClass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:14]
|--LCURLY -> { [1:14]
|   |   |--LITERAL_PUBLIC -> public [2:4]       
|   |   `--LITERAL_STATIC -> static [2:11]      
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:34]
|   |       |--MODIFIERS -> …
=> Issue #9449: Updated example of AST for TokenTypes.GT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9509
Java code used to generate AST :
<pre>
<code>
public static void main(String[] args)
{
boolean a = true , b = false;
if(a || b) {
System.out.println("Prints TRUE");
}
}
}
</code>
</pre>
Generated AST :
<pre>
<code>
|--IDENT -> MyClass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:14]
|--LCURLY -> { [1:14]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:34]
|   | …
=> Issue #9509: Updated example of AST for TokenTypes.LOR

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9501
**Test.java**
```
transient int a;
}
```
**AST**
```
|--VARIABLE_DEF -> VARIABLE_DEF [2:1]
|   |   `--LITERAL_TRANSIENT -> transient [2:1]
|   |   `--LITERAL_INT -> int [2:11]
|   |--IDENT -> a [2:15]
```
```
λ java -jar checkstyle-8.41-all.jar -t Test.java | grep "2:"
```
```
|--VARIABLE_DEF -> VARIABLE_DEF [2:1]
| …
```
=> Issue #9501: add example of AST for TokenTypes.LITERAL_TRANSIENT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Updated the TokenTypes.java file according to Issue #9550 
added example:
<pre>
<code>
public class ParametersDefine {
void foo(int firstParameter, int... secondParameter) {
}
}
</code>
</pre>
<pre>
C:\Users\Amr Bumadian\Downloads> java -jar checkstyle-8.41.1-all.jar -t ParametersDefine.java
|--IDENT -> ParametersDefine [1:13]
`--OBJBLOCK -> OBJBLOCK [1:30]
|--LCURLY -> { [1:30]
|   |--IDENT -> foo [2:6]
|   |--LPAREN -> ( [2:9]
|   |--PARAMETERS -> PARAMETERS [2:10]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [2:10]
|   |   | …
=> Issue #9550: updated example of AST for TokenTypes.PARAMETER_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9441 : 
```
public final int x= 0;
}
```
Generated AST:
```
|   |   `--FINAL -> final [2:11]
|   |--TYPE -> TYPE [2:17]
|   |   `--LITERAL_INT -> int [2:17]
|   |--IDENT -> x [2:21]
|   |--ASSIGN -> = [2:22]
|   |   `--EXPR -> EXPR [2:24]
|   |       `--NUM_INT -> 0 [2:24]
|   `--SEMI -> ; [2:25]
```
```
| …
```
=> Issue #9441: updated example of AST for TokenTypes.FINAL

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9487:
```
String s = null;
}
```
Generated AST:
```
|   |   `--IDENT -> String [2:4]
|   |--IDENT -> s [2:11]
|   |--ASSIGN -> = [2:13]
|   |   `--EXPR -> EXPR [2:15]
|   |       `--LITERAL_NULL -> null [2:15]
|   `--SEMI -> ; [2:19]
```
```
|   `--IDENT -> String
|--IDENT -> s
|--ASSIGN -> =
|   `--EXPR -> …
```
=> Issue #9487: updated example of AST for TokenTypes.LITERAL_NULL

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9451 : 
```
public class MyClass implements Collection {
}
```
Generated AST:
```
|--IMPLEMENTS_CLAUSE -> implements [1:21]
|   `--IDENT -> Collection [1:32]
`--OBJBLOCK -> OBJBLOCK [1:43]
|--LCURLY -> { [1:43]
```
```
|--IDENT -> MyClass
|--IMPLEMENTS_CLAUSE -> implements
|   `--IDENT -> Collection
|--LCURLY -> {
`--RCURLY -> }
```
=> Issue #9451: updated example of AST for TokenTypes.IMPLEMENTS_CLAUSE

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9519 :
```
public int x;
}
```
Generated AST:
```
|   |   `--LITERAL_INT -> int [2:11]
|   |--IDENT -> x [2:15]
```
```
|   `--LITERAL_INT -> int
|--IDENT -> x
`--SEMI -> ;
```
=> Issue #9519: updated example of AST for TokenTypes.MODIFIERS

.ci/jsoref-spellchecker/whitelist.words, .ci/no-exception-test.sh, .ci/shippable.sh, .ci/wercker.sh, .github/workflows/diff_report.yml
infra: move all launch.groovy usages in CI to diff.groovy
Right now this PR is just to test and make sure that all CI works as expected.  See https://github.com/checkstyle/contribution/pull/546 for details.
=> infra: move all launch.groovy usages in CI to diff.groovy

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9495
```
% javac Test.java
% 
% cat Test.java
class Test {
void sub() {
super.toString();
}
}
%
%  java -jar checkstyle-8.42-SNAPSHOT-all.jar -t Test.java
|   |--IDENT -> sub [2:6]
|   |--LPAREN -> ( [2:9]
|   |--PARAMETERS -> PARAMETERS [2:10]
|   |--RPAREN -> ) [2:10]
|   `--SLIST -> { [2:12]
|       |--EXPR -> EXPR [3:16]
|       |   `--METHOD_CALL -> ( [3:16]
|       |       |--DOT -> . [3:7]
|       |       |   |--LITERAL_SUPER -> super [3:2]
|       |       |   `--IDENT -> toString [3:8]
|       | …
```
=> Issue #9495: update example of AST for TokenTypes.LITERAL_SUPER

src/xdocs/cmdline.xml.vm
Removed `docs` since it doesn't exist and @romani confirmed this should reference our sun config rather than some 3rd party config.
=> doc: removes unknown docs folder for sun config

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Updated the TokenTypes.java file according to Issue #9481
added example:
<pre>
<code>
StringBuilder text = new StringBuilder();
boolean isBuilder = text instanceof StringBuilder;
</code>
</pre>
<pre>
D:\Work\GSOC>java -jar checkstyle-8.41.1-all.jar -t Test.java
`--OBJBLOCK -> OBJBLOCK 
|--LCURLY -> {
|--METHOD_DEF -> METHOD_DEF 
|   |--MODIFIERS -> MODIFIERS 
|   |   |--LITERAL_PUBLIC -> public 
|   |   `--LITERAL_STATIC -> static 
|   |--TYPE -> TYPE 
|   |   `--LITERAL_VOID -> void 
|   |--IDENT -> main 
|   |--LPAREN -> ( 
|   |--PARAMETERS -> PARAMETERS
|   |   `--PARAMETER_DEF -> PARAMETER_DEF 
|   |       |--MODIFIERS -> MODIFIERS 
|   |       |--TYPE -> TYPE 
|   |       | …
=> Issue #9481: updated example of AST for TokenTypes.LITERAL_INSTANCEOF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Updated the TokenTypes.java file according to Issue #9505
added example:
<pre>
<code>
class VolatileObject {
private volatile int variable;
}
</code>
</pre>
<pre>
C:\Users\Amr Bumadian\Downloads> java -jar checkstyle-8.41.1-all.jar -t VolatileObject.java
|--LITERAL_CLASS -> class [2:0]
|--IDENT -> VolatileObject [2:6]
`--OBJBLOCK -> OBJBLOCK [2:21]
|--LCURLY -> { [2:21]
|--VARIABLE_DEF -> VARIABLE_DEF [3:4]
|   |   |--LITERAL_PRIVATE -> private [3:4]
|   |   `--LITERAL_VOLATILE -> volatile [3:12]
|   |--TYPE -> TYPE [3:21]
|   |   `--LITERAL_INT -> int [3:21]
|   |--IDENT -> variable [3:25]
|   `--SEMI -> ; [3:33]
</pre>
expected update for java doc:
<pre>
VARIABLE_DEF -> …
=> Issue #9505: updated example of AST for TokenTypes.LITERAL_VOLATILE

src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/modifier/ModifierOrderCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealed.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealedNoViolation.java, src/xdocs/config_modifier.xml
Issue #9854: ModiferOrderCheck should support 'sealed' and 'non-sealed'
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/79c9d575d541725cd0b861497d2e7aa1/raw/38c5c2e22dc7809dcbd89c488bf37f39914b6e15/projects.properties
Diff Regression config: https://gist.githubusercontent.com/nmancus1/b111673a252cfdfa990b562361608e29/raw/344468c69278dbff8c8834a43db19f5c6a7b6eb5/config.xml
=> Issue #9854: ModiferOrderCheck should support 'sealed' and 'non-sealed'

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9473 
```
public double x;
}
```
```
|   |   `--LITERAL_DOUBLE -> double [2:11]
|   |--IDENT -> x [2:18]
|   `--SEMI -> ; [2:19]
`--RCURLY -> } [3:0] 
```
```
$ java -jar checkstyle-8.41-all.jar -T Test.java | grep "2:"
|   |   `--LITERAL_PUBLIC …
```
=> Issue #9473: updated example of AST for TokenTypes.LITERAL_DOUBLE

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9503 
```
void foo() {
try { } finally {}
}
}
```
```
|   |--RPAREN -> ) [2:13]
|   `--SLIST -> { [2:15]
|       |--LITERAL_TRY -> try [3:8]
|       |   |--SLIST -> { [3:12]
|       |   |   `--RCURLY -> } [3:14]
|       | …
```
=> Issue #9503: updated example of AST for TokenTypes.LITERAL_TRY

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9517 
```
void foo(int a, int b, int c) {
c = a % b;
}
}
```
```
|   |   |   |   `--LITERAL_INT -> int …
```
=> Issue #9517: updated example of AST for TokenTypes.MOD

.ci/travis/travis.sh
https://travis-ci.org/github/checkstyle/checkstyle/jobs/767598726#L3290
```
INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.xwiki.rendering:xwiki-rendering:13.4-SNAPSHOT: 
Could not find artifact org.xwiki.commons:xwiki-commons-pom:pom:13.4-SNAPSHOT in
sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) 
and 'parent.relativePath' points at no local POM @ line 23, column 11
```
=> infra: move xwiki validation to checkstyle org repo

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/StringLiteralEqualityCheck.xml, src/xdocs/config_coding.xml
failed master job
https://github.com/checkstyle/checkstyle/runs/2403748349?check_suite_focus=true
```
<td><i><a class="externalLink" href="http://www.thejavageek.com/2013/07/27/string-comparison-with-equals-and-assignment-operator/">http://www.thejavageek.com/2013/07/27/string-comparison-with-equals-and-assignment-operator/</a>: 404 Not Found</i></td></tr></table></td></tr>
<td><i><a class="externalLink" href="http://www.thejavageek.com/2013/07/27/string-comparison-with-equals-and-assignment-operator/">http://www.thejavageek.com/2013/07/27/string-comparison-with-equals-and-assignment-operator/</a>: 404 Not Found</i></td></tr></table></td></tr>
```
Link is replaced with stackoverflow question
=> minor: replace broken links with new ones

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9476 
```
void foo() {
try {} finally {}
}
}
```
```
|   |--RPAREN -> ) [2:13]
|   `--SLIST -> { [2:15]
|       |--LITERAL_TRY -> try [3:8]
|       |   |--SLIST -> { [3:12]
|       |   |   `--RCURLY -> } [3:13]
|       |   `--LITERAL_FINALLY -> finally [3:15]
|       |       `--SLIST …
```
=> Issue #9476: updated example of AST for TokenTypes.LITERAL_FINALLY

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9566 
**Rparen.java**
```
public class Rparen{
void check(){
//A right parenthesis is used in check(")"
}
}
```
**Cmd console:**
```
E:\GSoC>javac Rparen.java
E:\GSoC>java -jar checkstyle-8.41-all.jar -t Rparen.java
|--IDENT -> Rparen [1:13]
`--OBJBLOCK -> OBJBLOCK [1:19]
|--LCURLY -> { [1:19]
|   |--IDENT -> check [2:9]
|   |--LPAREN -> ( [2:14]
|   |--PARAMETERS -> PARAMETERS [2:15]
|   |--RPAREN -> ) [2:15]
|   `--SLIST -> { [2:16]
|       `--RCURLY -> } [4:4]
`--RCURLY -> } [5:0]
```
**Expected update for javodoc** …
=> Issue #9566: update example of AST for TokenTypes.RPAREN

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9469
Added comment lines to [TokenTypes.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java)
```
E:\GSoC>java -jar checkstyle-8.41-all.jar -t Test.java
|   |--IDENT -> check [2:9]
|   |--LPAREN -> ( [2:14]
|   |--PARAMETERS -> PARAMETERS [2:15]
|   |--RPAREN -> ) [2:15]
|   `--SLIST -> { [2:16]
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:8]
|       |   |--MODIFIERS -> …
```
=> Issue #9469: Update example of AST for TokenTypes.LITERAL_CLASS

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9475 
**Test.java**
```
boolean a = false;
}
```
**AST**
`$ java -jar checkstyle-8.42-all.jar -t Test.java`
```
|--VARIABLE_DEF -> VARIABLE_DEF [3:1]
|   |--TYPE -> TYPE [3:1]
|   |   `--LITERAL_BOOLEAN -> boolean [3:1]
|   |--IDENT -> a [3:9]
|   |--ASSIGN -> = [3:11]
|   |   `--EXPR -> EXPR [3:13]
|   |       `--LITERAL_FALSE -> false [3:13]
|   `--SEMI -> ; [3:18]
```
```
$ java -jar checkstyle-8.42-all.jar -t Test.java | grep "3:"
|--VARIABLE_DEF -> …
```
=> Issue #9475: add code example of AST for TokenTypes.LITERAL_FALSE

config/checkstyle_checks.xml, config/suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
closes #9936
New MatchXPath module before suppression:
```bash
[INFO] --- maven-antrun-plugin:3.0.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 28/04/2021 12:05:10 AM
[INFO] [checkstyle] Running Checkstyle  on 1408 files
[ERROR] [checkstyle] [ERROR] /home/nick/IdeaProjects/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java:281:24: Avoid using deprecated method DetailAst.branchContains(). [MatchXPathBranchContains]
[ERROR] [checkstyle] [ERROR] /home/nick/IdeaProjects/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java:282:25: Avoid using deprecated method DetailAst.branchContains(). [MatchXPathBranchContains]
[ERROR] [checkstyle] [ERROR] …
```
=> Issue #9936: Deprecate 'DetailAST.branchContains`

.ci/jsoref-spellchecker/whitelist.words, config/pmd.xml, config/sevntu_suppressions.xml, config/suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/SarifLogger.java, src/main/resources/com/puppycrawl/tools/checkstyle/sarif/ResultErrorOnly.template, src/main/resources/com/puppycrawl/tools/checkstyle/sarif/ResultFileOnly.template, src/main/resources/com/puppycrawl/tools/checkstyle/sarif/ResultLineColumn.template, src/main/resources/com/puppycrawl/tools/checkstyle/sarif/ResultLineOnly.template, src/main/resources/com/puppycrawl/tools/checkstyle/sarif/SarifReport.template, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleError.sarif, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerDoubleException.sarif, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerEmpty.sarif, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerLineOnly.sarif, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleError.sarif, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleException.sarif, src/test/resources/com/puppycrawl/tools/checkstyle/sariflogger/ExpectedSarifLoggerSingleWarning.sarif, src/xdocs/cmdline.xml.vm
Closes: #8905
by providing a basic version of [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html)
This PR does not include:
- Fully update the documentation with SARIF support.
- Populating `runs[0].tool.rules` for the actual checkstyle checks that are executed.
- Fully integrated relative path support since the basePath can only be set through `Checker` instead of `Main`.
Given that this PR is already a mammoth, I would prefer the rest to be implemented in follow-up PRs.
I have validated the output at https://sarifweb.azurewebsites.net/Validation
This [gist](https://gist.github.com/chao2zhang/8ebff385e0c6e1da4ebbb50024d873fe) is a sample SARIF output that I ran with `java -jar target/checkstyle-8.42-SNAPSHOT-all.jar -c src/main/resources/sun_checks.xml -f=sarif …
=> Issue #8905: Add basic SARIF support

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9468 
**Test.java**
```
char a = 'A';
}
```
**AST**
`$ java -jar checkstyle-8.42-all.jar -t Test.java`
```
|--VARIABLE_DEF -> VARIABLE_DEF [3:1]
|   |--TYPE -> TYPE [3:1]
|   |   `--LITERAL_CHAR -> char [3:1]
|   |--IDENT -> a [3:6]
|   |--ASSIGN -> = [3:8]
|   |   `--EXPR -> EXPR [3:10]
|   |       `--CHAR_LITERAL -> 'A' [3:10]
|   `--SEMI -> ; [3:13]
```
```
$ java -jar checkstyle-8.42-all.jar -t Test.java | grep "3:"
```
```
|--VARIABLE_DEF -> …
```
=> Issue #9468: add code example of AST for TokenTypes.LITERAL_CHAR

.ci/no-exception-test.sh
We must allow excludes on these projects in order to not cause failure in CI.
=> infra: restore CI jobs that require excludes in projects file

.ci/jsoref-spellchecker/whitelist.words, .ci/no-exception-test.sh, .ci/projects-for-no-exception-javadoc.properties
reason: it is very strange that we keep config for CI of checkstyle in another repo.
file projects-for-circle.properties was added at https://github.com/checkstyle/contribution/pull/52
and it is clearly have bad name now as location was changed.
We should keep configs for checkstyle CI in checkstyle repo.
=> infra: move config for no-exception execution of javadoc in repo

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/xdocs/cmdline.xml.vm, src/xdocs/config_design.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_naming.xml, src/xdocs/releasenotes.xml
Closes #9930 
Made changes in links in `src/xdocs` and `RightCurlyCheck.java`.
According to the [Linkcheck reports](https://checkstyle.org/linkcheck.html) as described in #9930 the following links were changes:-
1) For `config_design.html`
`property_types.html#pattern` => `property_types.html#Pattern`
2) For `config_javadoc.html`
`property_types.html#access_modifiers` => `property_types.html#AccessModifierOption.5B.5D`
3) For `apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.html`
`https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#METHOD_DEF` => `apidocs/com/puppycrawl/tools/checkstyle/api/TokenTypes.html#METHOD_DEF`
4) For `config_naming.html`
`property_types.html#regexp` => …
=> Issue #9930: Resolved issues with links detected by Linkcheck plugin

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties, src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SummaryJavadocCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocHtmlFormat.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineCorrect.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineDefault.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineForbidden.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocNoPeriod.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriod.java, src/xdocs/config_javadoc.xml
Closes : #7202 
Adds support for Inline @summary Javadoc Tag . Added support for summary within HTML format as INLINE_TAG
Diff Regression config: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/master/SummaryJavadoc/SummaryJavadocConfig.xml
Diff Regression projects: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/71feb5493e64467d24bf4bb73545cb1db8c0d4fb/Issue9010/projects-to-test-on.properties
Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/767e05a_2021020750/reports/diff/index.html Clean report
=> Issue #7202: Add Support for Summary Javadoc tag

src/xdocs/writingchecks.xml
Fixed typo under the section: Understanding The Visitor Pattern
=> doc: fix typo in writingchecks.xml

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: [#9459](https://github.com/checkstyle/checkstyle/issues/9459)
```
$ javac Test/src/Main.java  
$ cat Test/src/Main.java 
public class Main {
void foo(boolean a, boolean b) {
a = true;
b = true;
if(a && b) {}
}
}
$ java -jar checkstyle-8.42-all.jar -t Test/src/Main.java
|--IDENT -> Main [1:13]
|   |   |   |--MODIFIERS -> MODIFIERS …
```
=> Issue #9459: Added Example of AST for TokenTypes.LAND

wercker.yml
From https://github.com/checkstyle/checkstyle/pull/10019#discussion_r637354929:
Wercker is failing on `./.ci/wercker.sh no-error-hibernate-search`:
```bash
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.6.3 is not in the allowed range 3.8.1.
```
Appears to be related to https://github.com/hibernate/hibernate-search/commit/4e4918306334ee5ef2d984297efe2f4dc93c4deb
=> infra: upgrade wercker docker image

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9391 
Java Code used here:
<pre>
<code>
public @interface MyAnnotation {
int someValue();
}
}
</code>
</pre>
AST Format of the Java Doc:
<pre>
<code>
|--ANNOTATION_DEF -> ANNOTATION_DEF [2:2]
|   |   `--LITERAL_PUBLIC -> public [2:2]
|   |--AT -> @ [2:9]
|   |--LITERAL_INTERFACE -> interface [2:10]
|   |--IDENT -> MyAnnotation [2:20]
|   `--OBJBLOCK -> OBJBLOCK [2:33]
|       |--LCURLY -> { [2:33]
|       |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [3:4]
|       |   |--MODIFIERS -> MODIFIERS [3:4]
|       | …
=> Issue #9391: update example of AST for TokenTypes.ANNOTATIONS.DEF

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpanMultipleLines.java
Closes #10059 in support of https://github.com/checkstyle-antlr4/checkstyle-antlr4/issues/6
```bash
➜  checkstyle git:(issue-10059) grep -R antlr | grep -v "v4" | grep Input | grep -v "noncompilable"
src/test/java/com/puppycrawl/tools/checkstyle/grammar/AstRegressionTest.java:import antlr.ParserSharedInputState;
```
=> Issue #10059: Replace ANTLR2 dependencies in test inputs

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixex Issues #9392:
Java Code used:
<pre>
<code>
public @interface MyAnnotation {
String someField() default "Hello world";
}
}
</code>
</pre>
AST FORMAT OF JAVA CODE:
<pre>
<code>
|--ANNOTATION_DEF -> ANNOTATION_DEF [2:4]
|   |--AT -> @ [2:11]
|   |--LITERAL_INTERFACE -> interface [2:12]
|   |--IDENT -> MyAnnotation [2:22]
|   `--OBJBLOCK -> OBJBLOCK [2:35]
|       |--LCURLY -> { [2:35]
|       |--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [3:8]
|       |   |--MODIFIERS -> …
=> Issue #9392: update example of AST for TokenTypes.ANNOTATION_FIELD_DEF

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes Issue #9406
Java Code used here:
<pre>
<code>
int x=0;
switch (x) {
case 0:
case 1:
case 2:
x = 3;
break;
}
}
}
</code>
</pre>
AST Format of the Java Code:
<pre>
<code>
|   |   `--PARAMETER_DEF -> …
=> Issue #9406: update example of AST for TokenTypes.CASE_GROUP

.ci/wercker.sh, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderWithAnnotationsOutsideJavadoc.java
Resolves #9941: Fixing AtclauseOrder falsely ignoring method with annotation
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/eb228fa41edadc10eea264a914ea1411f0e52122/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/4e042b7368c2ab4a66635033e0cb338c81f1d7f8/my_checks.xml
=> Issue #9941: Fixing AtclauseOrder falsely ignoring method with annotation

src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersEscapedS.java
Resolves #9143
Diff Regression config: https://gist.githubusercontent.com/shashwatj07/62612965266474738d91ed8a1eda53fd/raw/06c9dc513f0fa2e8086aa1e1d76abd7491458a53/config1.xml
Diff Regression projects: https://gist.githubusercontent.com/shashwatj07/b3de11a5c370e5f6092e31776b9c3b91/raw/8f42d25090f9d1b10c9b5d56ba39b482ac0aa91f/projects.properties
=> Issue #9143:AvoidEscapedUnicodeCharacters does not identify line ending characters in multiline text blocks

.ci/eclipse-compiler-javac.sh, .ci/jsoref-spellchecker/whitelist.words, config/org.eclipse.jdt.core.prefs
Issue #10140
New compiler options: None
Removed compiler options:
* org.eclipse.jdt.core.compiler.annotation.inheritNullAnnotations
* org.eclipse.jdt.core.compiler.problem.unsafeTypeOperation
* org.eclipse.jdt.core.compiler.annotation.missingNonNullByDefaultAnnotation
* org.eclipse.jdt.core.compiler.annotation.nullanalysis
=> issue #10140: Validate ECJ options on ecj release

.github/workflows/no-exception-workflow.yml
From https://github.com/checkstyle/checkstyle/pull/10143#pullrequestreview-690624945:
> it would be better to split such big job (21 min) to multiple each execution separately, it will make it more quick by parallelism and easy to restart only single execution.
=> infra: parallelize no-exception javadoc github workflow

src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java
Supplemental to #8990 and just makes fixes to order of existing tags in javadocs.
=> supplemental: correct order of param tags in existing Javadocs(#8990)

.travis.yml
this RP is mostly to test PRs triggering for Travis.
and it works again - https://travis-ci.com/github/checkstyle/checkstyle/builds/230727986
for PRs and for master.
Lets keep travis ready for new tasks, no need to move items from actions back.
All my problems with migration from travis.org and travis.com are described at https://travis-ci.community/t/cant-find-a-repository-that-i-just-added-travis-yml-to/10909/18
=> infra: remove from travis all executions that we alrerady moved to github actions

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java, src/xdocs/config_imports.xml
fixes Issue #5982:
Output of  first example with no value parameters in command line:-
```
<property name="tabWidth" value="7"/>
<module name="ImportOrder">
<property name="staticGroups" value=""/>
<property name="sortStaticImportsAlphabetically" value="true"/>
</module>
</module>
</module>
```
```
import static java.io.File.listRoots;
import static javax.swing.WindowConstants.*; // OK
import static java.io.File.createTempFile; // violation should be before javax
import static com.puppycrawl.tools.checkstyle.checks.imports.avoidstaticimport.InputAvoidStaticImportNestedClass.Inne …
```
=> Issue #5982: Added example to ImportOrder about other groups

.ci/jsoref-spellchecker/whitelist.words, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCommentsIndentationTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEmptyLineSeparatorTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionInvalidJavadocPositionTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionJavadocContentLocationTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionSingleSpaceSeparatorTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionTodoCommentTest.java, src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionTrailingCommentTest.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/xpath/xpathmapper/InputXpathMapperSingleLineComment.java, src/xdocs/config_misc.xml
Closes #9009, #5819
```
int a; // SUPPRESS CHECKSTYLE
int b; // NOPMD
int c; // NOSONAR
int d; // violation, not suppressed
}
<module name="TrailingComment"/>
<module name="SuppressionXpathSingleFilter">
<property name="checks" value="TrailingCommentCheck"/>
<property name="query" value="//SINGLE_LINE_COMMENT
[./COMMENT_CONTENT[@text=' NOSONAR\n' or @text=' NOPMD\n'
or @text=' SUPPRESS CHECKSTYLE\n']]"/>
</module>
</module>
</module>
$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -c config.xml Test.java …
```
=> Issue #9009: Violations from TrailingComment should possible to suppress by xpath by content of comment

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathBlockComments.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathMultilineComments.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathSingleLineComments.java
Closes: #10107
```
public class TestClass {
void method() {
// test
}
}
$ cat config.xml   
<module name="MatchXpath">
<property name="query" value="//SINGLE_LINE_COMMENT" />
</module>
</module>
</module>
$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -c config.xml Test.java
[ERROR] /home/akmo/GitHub/Test/MatchXpath/Test.java:3:1: Illegal code structure detected. [MatchXpath]
Audit done.
```
=> Issue #10107: Support for comment in MatchXpath

.ci/validation.sh
From https://github.com/checkstyle/checkstyle/pull/10280/checks?check_run_id=3120338838:
`Error:      Non-resolvable parent POM for org.xwiki.platform:xwiki-platform:13.6-SNAPSHOT: Could not find artifact org.xwiki.commons:xwiki-commons-pom:pom:13.6-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 23, column 11 -> [Help 2]`
The `no-error-xwiki` task needs to have specific commit updated.
=> infra: update xwiki commit in no-error testing

config/checkstyle_checks.xml
From: https://github.com/checkstyle/checkstyle/pull/10368#discussion_r671740246
```
class Test{
int num1; //Violation Comment
int num2; // OK
bool isTrue; //Incorrect Comment
/*Incorrect Block Comment */
int num3;
/* Correct Block Comment */
int num4;
/**
*Incorrect Block Comment.
*/
int num5;
/*
*Incorrect Block Comment.
*/
int num6;      
/* Correct Block Comment
*/
int num7;
/*
* Correct Block Comment
*/
int num8;
/*Incorrect Block Comment.
* Correct Block Comment.
*/
int num9;
/* Correct Block Comment.
*Incorrect Block Comment.
*/
int num10;
}
}
<property …
```
=> supplemental: Convert from Todo check to better MatchXpath check

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9411 
```
vinayak@Gladiator:~/Documents$ cat test.java 
class test {
public static void main(String args[]){
//this is single line comment
/*
this is multiline comment
*/
}
}
vinayak@Gladiator:~/Documents/Opensource/checkstyle/target$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -T /home/vinayak/Documents/test.java 
|--IDENT -> test [1:6]
|   |--IDENT -> main [2:20]
|   |--PARAMETERS -> …
```
=> Issue #9411: update example of AST for TokenTypes.COMMENT_CONTENT

.ci/jsoref-spellchecker/whitelist.words, wercker.yml
I took a link from 
https://groovy.apache.org/download.html
=> infra: update link to groovy zip, as bintray is deprecated

appveyor.yml
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/40209511/job/urk18dde17mp582b
```
Running Install scripts
Add-Type -AssemblyName System.IO.Compression.FileSystem
if (!(Test-Path -Path "C:\maven\apache-maven-3.2.5" )) {
(new-object System.Net.WebClient).DownloadFile(
'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
'C:\maven-bin.zip'
)
[System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
}
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'www.us.apache.org'"
At line:3 char:3
+   (new-object System.Net.WebClient).DownloadFile(
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ …
```
=> infra: update url to maven, as it is not working any more

src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpressionDeclaration.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCaseLevel.java
Issue #8929 fix indent checks for case/default nodes by marking them as ignored in LineWrappingHandler.
Diff Regression config: https://gist.githubusercontent.com/sukolenvo/ee40ee2c7772e4f5cfb709d6c665a078/raw/a26e8cb549354f145f40ecf94b2463a31b2c98ca/checkstyle.xml
Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/384112a_2021141432/reports/diff/index.html
=> Issue #8929: fix indent checks in switch expressions

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocVariableCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleEnumCtorScopeIsPrivate.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocvariable/InputJavadocVariableInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodEnumCtorScopeIsPrivate.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountInterfaceMemberScopeIsPublic.java
Issue #9876 
The method `ScopeUtils.getScopeFromMods` always return `package` scope if no scope is explicitly set.
There is a local workaround for this bug in `MissingJavadocMethodCheck.calculateScope` and `MethodCountCheck.ctor`.
This PR removes these workarounds and fixes the broken method.
PR to fix xwiki: https://github.com/xwiki/xwiki-platform/pull/1652
Diff Regression config: https://gist.githubusercontent.com/pbludov/f91134ed24d58a1f210a2871829b4df0/raw/b00cf34d60e1a232b83a89e078a72ae6b46e9d2b/issue-9876-config.xml
Affected checks
============
* DeclarationOrder
* DesignForExtension
* JavadocStyle
* JavadocType
* JavadocVariable
* MethodCount
* MissingJavadocMethod
* MissingJavadocType
Not affected checks
===============
* RequireThis uses this method only to …
=> Issue #9876: Fix default scope for enum/interface/annotation members

.ci/validation.cmd, appveyor.yml
Resolves #10513 
We used to only see downloads when the cached content is not used as in the case of https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/40209636/job/9gdq17n6xvaqy4n7. 
Now, we do not see the downloads as in https://ci.appveyor.com/project/AkMo3/checkstyle-appveyor/builds/40223247 in whatsoever case
=> Issue #10513: Update maven to 3.8.1 and use ntp option in Appveyor

.github/workflows/pitest.yml
Noticed at https://github.com/checkstyle/checkstyle/pull/10574 :
pitest naming scheme should be consistent in github CI.
=> infra: rename JavaAstVisitor pitest

.ci/openjdk16-excluded.files
`BeforeExecutionExclusionFileFilter` got added back into #10603 upon rebase: https://github.com/checkstyle/checkstyle/pull/10603/files . This PR removes it.
=> minor: remove BeforeExecutionExclusionFileFilter

.ci/openjdk16-excluded.files, src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java
Closes #8291.
Note that no functional changes to existing code have been made; I have only included the test case from the issue and removed the associated file filters.
=> Issue #8291: Checkstyle freezes on deeply nested lambdas

src/main/resources/sun_checks.xml
https://checkstyle.org/config_modifiers.html is a broken link, the intended URL appears to be https://checkstyle.org/config_modifier.html.
This change updates the broken link to the good one.
=> minor: fix broken link within sun_checks.xml

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_1.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_4.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_5.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_6.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_7.java
=> Issue #10548: Migrate to Inline Config Parser in MagicNumberCheckTest

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl10.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl11.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl12.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl13.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl14.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl15.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl16.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl162.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl163.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl17.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl19.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl21.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl22.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl23.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl24.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl4.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl5.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl6.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl9.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlDisallowClassOfAllowPackage.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileName.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl_Blacklist.java
Resolves #10725 
Resolves #10671 
>Shashwat
Today at 6:45 AM
(file) gives C:\Users\checkstyle\ABCD.xml
(file)(resource) gives /com/puppycrawl/tools/...ABCD.xml
=> Issue #10725: Add support for file path in Inline Config Parser

config/pmd.xml, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java, src/test/java/com/puppycrawl/tools/checkstyle/bdd/ModuleInputConfiguration.java, src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
#10745
This PR adds a new class TestInputConfiguration to hold list of child modules and list of violations. However, the functionality for multiple child modules will be implemented in next PRs.
=> Issue #10745: Added new TestInputConfiguration to hold child modules and violations

src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
=> Issue #10745: Added functionality for module parent

src/test/java/com/puppycrawl/tools/checkstyle/grammar/GeneratedJavaTokenTypesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammar/javadoc/GeneratedJavadocTokenTypesTest.java
Identified when working on the backport.
Comment was originally designed to warn users to not just update the count for no reason to pass the test. The new tokens need to be added as well as updating the count. The comment should stick to the count and the wording was made a bit clearer to help that.
Javadoc had no similar counting system for things to be added when new changes are made. This was added. To me, it looks like the counts are still valid as the numbers seemed to match up.
=> minor: fixes comment and token type counting in tests

src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
Resolves #10756: JavadocMetadataScraper now correctly identifies check name
=> Issue #10756: JavadocMetadataScraper now correctly identifies check name

config/version-number-rules.xml
=> config: remove old antrl reference from version plugin config

config/version-number-rules.xml
Fixes #10781 
Spotbugs version 4.3.0  reports too many false positives about exposing internal state of a mutable object.
Untill https://github.com/spotbugs/spotbugs/issues/1601 is fixed, this dependency should be excluded from version checking.
=> Issue #10781: temporary disable spotbugs version update

config/suppressions.xml, src/it/java/com/google/checkstyle/test/base/AbstractIndentationTestSupport.java, src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java, src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractPathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java
Closes #6336 
Added javadoc for these files that were causing violations:
1. `AbstractIndentationTestSupport.java`
2. `AbstractXpathTestSupport.java`
3. `AbstractModuleTestSupport.java`
4. `AbstractPathTestSupport.java`
5. `AbstractXmlTestSupport.java`
Also removed the suppressions from `config/suppressions.xml`
=> Issue #6336: added javadoc for Test Support classes

.ci/drone-io.sh
failed master build, looks like there is some issue with unpacking tar archive and checkstyle tried to run checks on tar archive. 
It makes no sense to check archives, so exclude them from processing
https://cloud.drone.io/checkstyle/checkstyle/5487/1/3
>`	[ERROR] [checkstyle] [ERROR] /drone/src/cache.tar:18: Line should not be longer than 100 symbols [lineLength]`
=> minor: fix drone build by excluding archives from line length check

.ci/eclipse-compiler-javac.sh
It is possible to figure out the latest Eclipse Compiler version in two http requests.
This PR replaces the hard-coded version with a web request.
=> infra: use last ecj compiler in ci

.ci/validation.sh
Fixes failing `no-error-xwiki` CI item, noticed at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/8952/workflows/87d98f45-0a8d-4f75-8343-b2d0d24caf1c/jobs/100876
=> infra: update xwiki commit

pom.xml
Issue #10815 
Turn on `failOnWarnings` and exclude all generated code.
=> Issue #10815: make build fail on javadoc warnings

src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java
Identified at https://github.com/checkstyle/checkstyle/pull/10805 where it was noticed the class had no messages, but the test wasn't failing or documenting it.
Slightly redid the tests and util method to clarify when to scan super classes and when not to. Originally, the test was thinking `JavadocMetadataScraper` had messages from `AbstractJavadocCheck` which shouldn't be considered since those are parsing messages and not related to the check. The point of the test is to ensure all checks are logging some message and we are identifying it.
=> minor: restructures message testing to clarify messages come from

.ci/jsoref-spellchecker/whitelist.words, src/xdocs/index.xml.vm
Closes #10057 
I think it is better to make a new section instead of extending "tools" list, since these projects are not tools, but extensions to core functionality.
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/43cdfc1_2021105638/index.html#Additional_Checks
=> Issue #10057: add section with additional checks to main page

crowdin.yml
Issue #6191 
Added config for crowdin integration.
It takes as original all messages.properties files, output will be added to same location with country code suffix, as it is now.
=> Issue #6191: add config file for crowdin integration

src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodDefaultAccessModifier.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodEnum.java
Resolves #10835: JavadocMethod accessModifiers incorrectly interpreted for interface class 
Diff Reports-
All related variations of JavadocMethod: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5d631da_2021155102/reports/diff/index.html
All related variations of ParameterName: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5d631da_2021061820/reports/diff/index.html
All related variations of RecordComponentNumber: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5d631da_2021065848/reports/diff/index.html
=> Issue #10835: Fixing default access modifier for CheckUtil

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeWithEmoji.java
closes #10920 .
Diff Regression config: https://gist.githubusercontent.com/nmancus1/c505009a3aa0485a4293d193c00c807b/raw/9645b8608afd7b0dbd57df4baa2fb23cfe1802d0/config.xml
=> Issue #10920:  NoWhitespaceBefore error on semicolon or comma after string with emoji

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
<h3>Fixes Issue: #9393</h3> 
<br>
This PR changes all "+-" to "`-" , as mentioned in the issue. 
<br>
Here is the rendered javadoc file generated using `mvn javadoc:javadoc` :
<br><br>
**TEST.java :**
```java
@MyAnnotation package blah;
````
**Command :**
```
java -jar checkstyle-9.1-all.jar -t TEST.java
COMPILATION_UNIT -> COMPILATION_UNIT [1:14]
`--PACKAGE_DEF -> package [1:14]
|--ANNOTATIONS -> ANNOTATIONS [1:0]
|   `--ANNOTATION -> ANNOTATION [1:0]
|       |--AT -> @ [1:0]
|       `--IDENT -> MyAnnotation [1:1]
|--IDENT -> blah [1:22]
```
**Code changes :**
```java
* <pre>
* `--PACKAGE_DEF -> package
*     |--ANNOTATIONS -> ANNOTATIONS
*     |   `--ANNOTATION -> ANNOTATION
*     |       |--AT -> @
*     |       `--IDENT -> MyAnnotation
*     |--IDENT -> blah
* …
```
=> minor: correct the wrong format of AST

src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
Fixes issue #10749: Currently moduleFolders names are hardcoded `checks`, `filters`, `filefilters`. It is not necessary for all folders to exist, if all three folders doesn't exist, util will stop. Instead the folders can be taken as inputs.
=> Issue #10749: Add support to take list of moduleFolders as input

.travis.yml
fixes #10778
master build is already on free tier, looks like green. So no more unexpected stops for Travis CI, no more email to support for extra credits.
actual migration to new arch:
https://github.com/checkstyle/checkstyle/commit/2567947c88a67521e2ec5b51c9c2ea52a5bbf0a6
https://github.com/checkstyle/checkstyle/commit/f565da197f26212b1cedaa742384c98e91428a1d
all old builds/PRs will continue to use credits, so please rebase.
=> #10778 activate hibernate

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue #9421 
```
cat Test.java  
public void myShape(int... dimension) {
}
}
% java -jar checkstyle-9.1-all.jar -t Test.java
|   |   `--LITERAL_PUBLIC -> public [3:4]
|   |--TYPE -> TYPE [3:11]
|   |   `--LITERAL_VOID -> void [3:11]
|   |--IDENT -> myShape [3:16]
|   |--LPAREN -> ( [3:23]
|   |--PARAMETERS -> PARAMETERS [3:24]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:24]
|   |       |--MODIFIERS -> MODIFIERS [3:24]
|   |       |--TYPE -> TYPE …
```
=> Issue #9421: create example of AST for TokenTypes.ELLIPSIS

src/xdocs/config_system_properties.xml
Issue https://github.com/checkstyle/checkstyle/issues/9072
Changes
1. Removed mention of properties `checkstyle.locale.language`, `checkstyle.locale.country`, `checkstyle.cache.file` and `checkstyle.basedir`. All these properties have no usage in code.
2. Localisation -> Localization
3. Changed block about localization, added note that checkstyle uses default property `user.language`
Current version https://checkstyle.org/config_system_properties.html
Updated version https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ab13c36_2021154747/config_system_properties.html
=> Issue #9072: cleanup of system properties docs page

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes #9464 : update example of AST for TokenTypes.LITERAL_BREAK
=> Issue #9464: updated example of AST for TokenTypes.LITERAL_BREAK

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9463
```
**Test.java**
public class Test { 
public boolean flag;
}
**AST**
java -jar checkstyle-9.0.1-all.jar -t Test.java
`--CLASS_DEF -> CLASS_DEF [4:0]
|--MODIFIERS -> MODIFIERS [4:0]
|   `--LITERAL_PUBLIC -> public [4:0]
|--LITERAL_CLASS -> class [4:7]
|--IDENT -> Test [4:13]
`--OBJBLOCK -> OBJBLOCK [4:18]
|--LCURLY -> { [4:18]
|--VARIABLE_DEF -> VARIABLE_DEF [5:2]
|   |--MODIFIERS -> MODIFIERS [5:2]
|   |   `--LITERAL_PUBLIC -> public [5:2]
|   |--TYPE -> TYPE [5:9]
|   |   `--LITERAL_BOOLEAN -> boolean [5:9]
|   |--IDENT -> flag [5:17]
|   `--SEMI -> ; [5:21]
`--RCURLY -> } [6:0]
java -jar checkstyle-9.0.1-all.jar -t Test.java | grep 5:
|--VARIABLE_DEF -> VARIABLE_DEF [5:2]
|   |--MODIFIERS -> MODIFIERS [5:2]
|   |   `--LITERAL_PUBLIC -> public [5:2]
|   |--TYPE -> TYPE …
```
=> Issue #9463: update example of AST for TokenTypes.LITERAL_BOOLEAN

src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputViolation.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullEnhancedInstanceof.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordsAndCompactCtors.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNull.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullIgnoreCase.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullMisc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullNested.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullOnTheSameLine.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplementsAndNestedCount.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityMultiCatchBitwiseOr.java
Resolves #10943: Message validation in our Inputs should not have trailing and leading '.*'
=> Issue #10943: Message validation in our Inputs should not have trailing and leading '.*'

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes #9412 : update example of AST for TokenTypes.CTOR_CALL
=> Issue #9412: updated example of AST for TokenTypes.CTOR_CALL

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes #9400 : updated example of AST for TokenTypes.BLOCK_COMMENT_END
```
PS C:\Users\abhin\Desktop> cat Test.java
class A {
/*comment*/
}
PS C:\Users\abhin\Desktop> java -jar checkstyle-9.1-all.jar -T Test.java
|--IDENT -> A [1:6]
`--OBJBLOCK -> OBJBLOCK [1:8]
|--LCURLY -> { [1:8]
|--BLOCK_COMMENT_BEGIN -> /* [2:2]
|   |--COMMENT_CONTENT -> comment [2:4]
|   `--BLOCK_COMMENT_END -> */ [2:10]
```
expected update for javodoc is:
```
BLOCK_COMMENT_BEGIN -> /*
|--COMMENT_CONTENT -> comment
`--BLOCK_COMMENT_END -> */
```
=> Issue #9400: updated example of AST for TokenTypes.BLOCK_COMMENT_END

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9422
**Test.java**
`$ cat Test.java`   
```
class Test{
public static void main(String []args){
while(true);
}
}
```
`$ java -jar checkstyle-9.0.1-all.jar -t Test.java`
```
|   |--PARAMETERS -> PARAMETERS [2:28]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:28]
|   |       |--MODIFIERS -> MODIFIERS [2:28]
|   |       |--TYPE -> TYPE [2:28]
| …
```
=> Issue #9422: create example of AST for TokenTypes.EMPTY_STAT

src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes #9455: update example of AST for TokenTypes.INSTANCE_INIT
Test.java file:
```
private int foo;
{foo = 10;}
}
```
AST printed through CLI:
```
|   |   `--LITERAL_PRIVATE -> private [2:4]
|   |--TYPE -> TYPE [2:12]
|   |   `--LITERAL_INT -> int [2:12]
|   |--IDENT -> foo [2:16]
|   `--SEMI -> ; [2:19]
|--INSTANCE_INIT -> INSTANCE_INIT [3:4]
|   `--SLIST -> { [3:4]
|       |--EXPR -> EXPR [3:9]
|       |   `--ASSIGN -> = [3:9]
|       | …
```
=> Issue #9455: updated example of AST for TokenTypes.INSTANCE_INIT

.github/workflows/diff_report.yml
Related to discussion at https://github.com/checkstyle/contribution/pull/527#issuecomment-969376283 , allowing file exclusions in diff report generation will permit us to run check regression on newer openjdk's.
I do not think that github actions will use the proposed changes in this PR to execute a diff report created by a comment in this PR, so we will need to merge this, then try https://github.com/checkstyle/checkstyle/pull/10911 again to show that exclusions work. I will also update #10911 to use openjdk16.
=> infra: allow file exclusions in diff report generation

.github/workflows/diff_report.yml
As we do for other `diff.groovy` usages such as `no-exception-test` CI tasks, we should specify a larger heap size for checkstyle execution while generating check behavior regression reports.
Examples:
https://github.com/checkstyle/checkstyle/blob/003704a000881455349bd42bf9b16b91f2724ab9/.ci/no-exception-test.sh#L86
https://github.com/checkstyle/checkstyle/blob/003704a000881455349bd42bf9b16b91f2724ab9/.ci/no-exception-test.sh#L106
https://github.com/checkstyle/checkstyle/blob/003704a000881455349bd42bf9b16b91f2724ab9/.ci/no-exception-test.sh#L127
https://github.com/checkstyle/checkstyle/blob/003704a000881455349bd42bf9b16b91f2724ab9/.ci/no-exception-test.sh#L148
This should allow us to use openjdk16 project in https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects- …
=> infra: specify heap size for diff report generation

.github/workflows/diff_report.yml
This fixes the `diff_report.yml` workflow, which is currently not working properly:
https://github.com/checkstyle/checkstyle/runs/4446596762?check_suite_focus=true#step:2:12
The repo settings for actions permission have been changed to:
>Read repository contents permission
>Workflows have read permissions in the repository for the contents scope only. 
The `diff_report.yml` workflow needs the `pull-requests: write` permission so it can react and reply to PR comments. This PR sets the required permissions to fix the issue.
It's still worth taking even if you undo the repo settings change; it limits the permissions for this workflow to the minimum required.
=> infra: Set permissions required by the workflow

.github/workflows/diff_report.yml
https://github.com/checkstyle/checkstyle/runs/4453342391?check_suite_focus=true#step:9:36
```
Error: git repository ../../checkstyle does not have a branch with name 'origin/"issue-11001"'!
Error: origin/"issue-11001" is not an exiting git branch!
Caught: java.lang.IllegalArgumentException: Error: invalid command line arguments!
```
The `diff_report.yml` workflow was failing because the `REF` environment variable was getting set in the form `origin/"branchname"` (extra doublequotes around the branch name)
The extra quotes were coming from the jq command, which outputs strings in json format (that is, doublequoted). This PR uses jq's --raw-output option:
>With this option, if the filter's result is a string then it will be written directly to standard output rather than being formatted as …
=> infra: Fix branch name (remove quotes)

src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/TrailingCommentCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/trailingcomment/InputTrailingComment2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/trailingcomment/InputTrailingCommentWithNoPrecedingWhitespace.java, src/xdocs/config_misc.xml
Closes #10997.
Link to new docs: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/27d4f52_2021135942/config_misc.html#TrailingComment
Diff Regression config: https://gist.githubusercontent.com/nmancus1/fadf235ea645a5f13bab96df8158792c/raw/75b61a9420213e2f3ac89d9732cdd256a6442361/config.xml
I suspected that others may be using the same trailing comment for Eclipse internationalization for non-localized strings, so I included the config from #10997 in check regression report configs(as TC2) to show that we are now ignoring these comments if `legalComment` property is set accordingly. These are the only differences. The default config shows no differences(TC1).
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/27d4f52_2021143110/reports/diff/index.html
=> Issue #10997: TrailingCommentsCheck ignores first comment character

.github/workflows/site.yml
Similar to https://github.com/checkstyle/checkstyle/pull/11014#issue-1073832545, hopefully this fixes site generation issue.
Example of failure: https://github.com/checkstyle/checkstyle/actions/runs/1559956127
Failure seems to be related to writing rocket emoji to comment where `Github, generate site` is placed.
Even if this does not fix failure, it is a good idea to update permissions.
From https://github.com/checkstyle/checkstyle/pull/11014#issue-1073832545:
> It's still worth taking [this PR] even if you undo the repo settings change; it limits the permissions for this workflow to the minimum required.
=> infra: add permissions for site workflow

.github/workflows/rebase.yml
Similar to #11014 (comment), this should fix rebase issue.
Failure seems to be related to writing rocket emoji to comment where Github, generate site is placed.
Even if this does not fix failure, it is a good idea to update permissions.
From #11014 (comment):
> It's still worth taking [this PR] even if you undo the repo settings change; it limits the permissions for this workflow to the minimum required.
=> infra: add permissions for rebase workflow

.github/workflows/rebase.yml
Hopefully fixes failure of `Github, rebase` workflow.
It was tough to find exact documentation that details which permission is necessary for this action, [this](https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request) is somewhat related. Repo for [cirrus actions rebase ](https://github.com/cirrus-actions/rebase) does not specify exact permissions required for it's workflow, but there is an issue at https://github.com/cirrus-actions/rebase/issues/84#issuecomment-984248665 that states that the changes in this PR are required.
=> infra: update permissions for rebase workflow

azure-pipelines.yml
Noticed failing build at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=6440&view=logs&j=eb841e9f-6e1e-5c29-3ad5-74ec2c658069
Related to https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/ and https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-196-update
=> infra: update macOS image

.github/workflows/codeql-analysis.yml
The CodeQL workflow currently works on PRs but not on pushes to `master`:
https://github.com/checkstyle/checkstyle/runs/4489527012?check_suite_focus=true#step:4:10
This PR sets the permissions required for it to work on push.
```
request: {
method: 'PUT',
url: 'https://api.github.com/repos/
checkstyle/checkstyle/code-scanning/analysis/status',
```
=> infra: Update permissions for codeql workflow

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheck.java, src/xdocs/config_imports.xml
Fixes #7688
**Default examples:**
```
<module name="RedundantImport"/>
</module>
</module>
$ cat MyClass.java
package Test;
import static Test.MyClass.*; // OK, static import
import static java.lang.Integer.MAX_VALUE; // OK, static import
import Test.MyClass; // violation, imported from the same package as the current package
import java.lang.String; // violation, the class imported is from the 'java.lang' package
import java.util.Scanner; // OK
import java.util.Scanner; // violation, it is a duplicate of another import
public class MyClass{ };
$ java -jar …
```
=> Issue #7688: update doc for RedundantImport

src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java
Issue #11054
Local pitest confirmed that duplicating the code is acceptable, though I don't think this is really desirable.
=> Issue #11054: rewrote RightCurlyCheck avoid a possible exception

.ci/validation.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/SimplifyBooleanExpressionCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java, src/xdocs/config_coding.xml
Resolves #11015: SimplifyBooleanExpression: A false negative about ternary operator
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/f2165f24391044b23b73a312a7d05179ed70b188/my_checks.xml
Final report (clean) - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8b38dbc_2021055812/reports/diff/index.html
Website - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6db4c58_2021130029/config_coding.html#SimplifyBooleanExpression
=> Issue #11015: Fixed false negative about ternary operator in SimplifyBooleanExpressionCheck

pom.xml
=> Issue #11067: Remove powermock workaround for JDK16

.cirrus.yml
Issue #10905 
Java16 build removed. Java16 is no more supported by the vendor.
Java17 (LTS) build added.
=> Issue #10905: setup Java17 build

.ci/jsoref-spellchecker/whitelist.words, .ci/validation.sh, .semaphore/semaphore.yml, wercker.yml
stable failure of semaphoreci on pmd validation
https://checkstyle.semaphoreci.com/jobs/25bf624f-4f4c-4380-8de4-2ee08fe6d4b8
`[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile (kotlin-compile) on project pmd-lang-test: Execution kotlin-compile of goal org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile failed: A required class was missing while executing org.jetbrains.kotlin:kotlin-maven-plugin:1.4.10:compile: kotlin/reflect/full/KClasses 02:02`
commands is taken from https://github.com/pmd/pmd/blob/master/.ci/build.sh#L93
=> infra: update pmd CI execution to not use forked repository

src/xdocs/index.xml.vm
Identified at https://github.com/checkstyle/checkstyle/issues/10886 , added a new section on the main page to display the list of JREs checkstyle is currently supported on so it is clear to users.
=> adds section for list of supported JREs

src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefinitionsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/SuppressionsStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/JavadocTokenTypesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/BlockTagUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/TestUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ChainedPropertyUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/FilterUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/JavadocUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ModuleReflectionUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ParserUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/XpathUtilTest.java
Fixes #11107
We no longer need to pass `false` for this value. Therefore, we can simply remove this parameter.
=> Issue #11107: remove checkConstructorIsPrivate parameter

config/suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PropertyCacheFileTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XmlLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/XpathFileGeneratorAstFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControlTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java
=> Issue #9142: resolve Assertions.assertNull

src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllBlockCommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammar/comments/AllSinglelineCommentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Fixes #11131
This is leftover of #10932 
There were some `if` in the tests due to the  incompatibility of Powermock with `assumeXXX`.
Detected by @rnveach at https://github.com/checkstyle/checkstyle/issues/10932#issuecomment-1001087308
=> Issue #11131: replace 'if' with assumeTrue/False in tests

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityConcatenatedTextBlocks.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityConcatenatedString.java
Resolves #11031: StringLiteralEquality FN about String literal expression
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/62103529e941c23abb7b23b61df366427b0fbf02/my_checks.xml
Final Report (clean): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8479596_2021003141/reports/diff/index.html
=> Issue #11031: Fixed false negative about concatenated strings in StringLiteralEqualityCheck

config/import-control.xml, config/pmd-test.xml, config/suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/PropertyType.java, src/main/java/com/puppycrawl/tools/checkstyle/XdocsPropertyType.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilter.java, src/test/java/com/puppycrawl/tools/checkstyle/XdocsPropertyTypeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
Issue #10744
New annotation: `XdocsPropertyType`. This annotation should be accessible with checks and filters,
Method `getModulePropertyExpectedValue` refactored to satisfy size checks.
Method `getModulePropertyExpectedTypeName` removed.
=> Issue #10744: use annotation to specify the property type

pom.xml
Fixes #11120 
fb-contrib works with Spotbugs, but with some exceptions thrown at runtime:
```
Exception analyzing...using detector com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod
[java] java.lang.RuntimeException: Incompatible bcel version, apparently bcel has been upgraded to not use 'Unknown' for 'BootstrapMethods', but uses: BootstrapMethods
```
This is due to fb-contrib shoud be used only with Findbugs. For Spotbugs there is a dedicated build named sb-contrib.
=> Issue #11120: switch from fb-contrib to sb-contrib

config/import-control-test.xml, config/suppressions.xml, src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java, src/it/java/org/checkstyle/suppressionxpathfilter/AbstractXpathTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
Closes #9142
Doing a search on `org.junit.jupiter.api.Assertions` only provides the following results:
````
M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\ant\CheckstyleAntTaskTest.java (1 hit)
Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\header\HeaderCheckTest.java (1 hit)
Line 25: import static org.junit.jupiter.api.Assertions.assertThrows;
M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\imports\ImportControlLoaderTest.java (1 hit)
Line 23: import static org.junit.jupiter.api.Assertions.assertThrows;
M:\checkstyleWorkspace\checkstyle\src\test\java\com\puppycrawl\tools\checkstyle\checks\javadoc\AbstractJavad …
```
=> Issue #9142: finalize

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AbstractSuperCheck.java
Issue #6320
Identified at https://github.com/checkstyle/checkstyle/pull/11157 .
http://rveach.no-ip.org/checkstyle/pitest/40/pitest-coding/com.puppycrawl.tools.checkstyle.checks.coding/AbstractSuperCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@4c20892b_101
We limit this check to very specific tokens. METHOD_DEF and LITERAL_SUPER.
The area in question in this code relies directly on the tokens brought forward to the visit check. So we can't show super is needed, regression showed nothing anyways. METHOD_DEF is not an issue and cannot be contributed to show such because we already have a specific section in the visit for METHOD_DEF and any that get to this section, we enough checks in `isSameNameMethod` that it basically has to be the super literal because we are looking …
=> Issue #6320: resolution for AbstractSuperCheck

.ci/pitest.sh
Outputs:
```bash
$ .ci/pitest.sh --list
Supported profiles:
pitest-annotation
pitest-ant
pitest-api
pitest-blocks
pitest-coding
pitest-common
pitest-design
pitest-filters
pitest-gui
pitest-header
pitest-imports
pitest-indentation
pitest-javadoc
pitest-main
pitest-metrics
pitest-misc
pitest-modifier
pitest-naming
pitest-packagenamesloader
pitest-regexp
pitest-sizes
pitest-utils
pitest-whitespace
pitest-xpath
$ .ci/pitest.sh nosuchoption
Unexpected argument: nosuchoption
Usage .ci/pitest.sh <profile>
To see the full list of supported profiles run '.ci/pitest.sh --list'
```
=> infra: add `--list` to .ci/pitest.sh

config/spotbugs-exclude.xml
Issue #11140
`[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.PackageObjectFactory defines static field "com.puppycrawl.tools.checkstyle.PackageObjectFactory.NAME_TO_FULL_MODULE_NAME" which appears to allow memory bloat [com.puppycrawl.tools.checkstyle.PackageObjectFactory] In PackageObjectFactory.java PMB_POSSIBLE_MEMORY_BLOAT`
`[ERROR] Medium: Class com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder defines static field "com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.CHECK_ALIAS_MAP" which appears to allow memory bloat [com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder] In SuppressWarningsHolder.java PMB_POSSIBLE_MEMORY_BLOAT`
http://fb-contrib.sourceforge.net/bugdescriptions.html
>PMB_POSSIBLE_MEMORY_BLOAT
This class defines static fields …
=> Issue #11140: resolve PMB_POSSIBLE_MEMORY_BLOAT

src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationNoPackage.java
Issue #6320
Identified at #11157 .
This needs a very specific case to kill the mutation. We need an input file with no package definition, and we need the class we are forbidding to match the current package plus the dot and the name of the class to forbid. Since the package doesn't exist, it is an empty string. This makes the class we need to forbid be `.<ClassName>` hence this test case. I went with `BadExample` to specially denote it. With the mutation in place, this causes an NPE to kill it.
Latest run at https://github.com/checkstyle/checkstyle/runs/4734268330 shows mutations gone with this.
=> Issue #6320: added test case for IllegalInstantiationCheck

.ci/validation.sh
Noticed at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/555202878, gcp core checkstyle execution is failing with 87 violations
Passing build at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/555207079
=> infra: use stable commit for gcp

config/spotbugs-exclude.xml
Issue #11140
`[ERROR] Medium: Method com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.finishTree(DetailAST) is implemented with an exact copy of its superclass' method [com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck] At AbstractJavadocCheck.java:[line 293] COM_COPIED_OVERRIDDEN_METHOD`
>COM_COPIED_OVERRIDDEN_METHOD This method is implemented using an exact copy of its superclass method's implementation, which usually means that this method can just be removed.
=> Issue #11140: resolve COM_COPIED_OVERRIDDEN_METHOD

.ci/jsoref-spellchecker/whitelist.words, .github/workflows/bump_license_year.yml
Resolves #11194: Automate bumping license year
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
After merge:
manually run it from the actions tab to see it in action.
=> Issue #11194: Automate bumping license year

.ci/jsoref-spellchecker/whitelist.words, config/spotbugs-exclude.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Fixes #11172 
`Runtime.getRuntime().exit(int)` used to report the exit code.
All tests for the `Main` class now call a helper method `invokeMain(int, String...)` that mocks `Runtime.getRuntime().exit(int)` to avoid the VM termination. `ExitHelper` class removed.
=> Issue #11172: replace System.exit with Runtime.exit

.ci/bump-license-year.sh
=> Issue #11203: Update bump-license-year.sh to use g4 file extension

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters5.java
Issue #10924: Updated `AvoidEscapedUnicodeCharactersCheck` to use code point.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/4323d26bee52faf59d8ebab0e9f94dab/raw/2fe5691757afea0390518650016752c76508ca1f/config.xml
=> Issue #10924: Update UnicodeCharactersCheck to use code points

src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordsAndCompactCtors.java
Issue #6320
Identified at #11157 .
Field needs to come at end of record definition instead of before.
Latest run at https://github.com/checkstyle/checkstyle/runs/4733793364 shows mutations gone with this.
=> Issue #6320: added test case for EqualsAvoidNullCheck

config/checkstyle_resources_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnnecessaryParenthesesCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement2.java, src/xdocs/config_coding.xml
Resolves #11061:  UnnecessaryParentheses: false negative
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/5b2e5d76bc8d10c8f0e3619697156e49d80ab85f/my_checks.xml
Final Report(clean) - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/cd3cb0c_2021122340/reports/diff/index.html
=> Issue #11061: False negative around TokenTypes.LOR in UnnecessaryParenthesesCheck

.ci/openjdk16-excluded.files
Resolves #11215: add file filters for non-compilable files in openjdk16
=> Issue #11215: add file filters for non-compilable files in openjdk16

.travis.yml
Reactivates `no-error-checkstyles-sevntu` CI task now that https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/858 is merged
=> infra: reactivate no-error-checkstyles-sevntu after sevntu#858

.circleci/config.yml
noticed at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/11304/workflows/de04ced3-7f8c-4b13-9f08-c47d6cd3f641/jobs/111882
`Caused by: java.lang.IllegalArgumentException: invalid target release: 11`
Successful run: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/11305/workflows/fde9c587-dc2b-4a6c-8899-b194fb8cb779/jobs/111887
=> infra: update docker image for no-error-xwiki

.github/workflows/site.yml
Closes #11228
Javadocs are generated successfully:
```bash
➜  checkstyle git:(issue-11228) mvn -e --no-transfer-progress clean site -Pno-validations -Dmaven.javadoc.skip=false
...
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.7:report (default-report) @ checkstyle ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] Total time:  01:16 min
[INFO] Finished at: 2022-01-22T18:37:35-05:00
```
=> Issue #11228: Let 'site' Github action to generate javadoc

.ci/validation.sh
usual update of xwiki-platform commit
noticed at https://circleci.com/gh/checkstyle/checkstyle/112471?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> infra: update xwiki-platform commit

.ci/validation.sh
Not sure if I should reference https://github.com/checkstyle/checkstyle/issues/10885 or not, only time will tell if this will be a permanent fix.
Failure noted at https://circleci.com/gh/checkstyle/checkstyle/112560?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> infra: use master branch for no-error-xwiki execution

.ci/openjdk17-excluded.files, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapGuardedPatterns.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapTryWithResources.java
Closes #11187
Diff Regression config: https://gist.githubusercontent.com/nmancus1/284f66dbf5a076b43708b7685ee9bd53/raw/c595fc26ae622509dadcd25ca6fe02b3db5ffaac/config.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/e34312d61da0b073f31339cfbf385f289b721fed/checkstyle-tester/projects-to-test-on-for-github-action.properties
Final report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/586d278_2022024156/reports/diff/index.html
No diffs now that #10848 is closed.
=> Issue # 11187: OperatorWrapCheck throws NPE on guarded patterns

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MissingSwitchDefaultCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCaseLabelElements.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java, src/xdocs/config_coding.xml
Closes #11220 
Report label: all projects
Diff Regression config: https://gist.githubusercontent.com/nmancus1/3db3e23a5063857160d7d92cbdfa1bfe/raw/b8fc9b284c6604bf0862f237f030794bfb0a7800/config.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/e34312d61da0b073f31339cfbf385f289b721fed/checkstyle-tester/projects-to-test-on-for-github-action.properties
Final report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/f5590ec_2022232703/reports/diff/index.html
Only diffs are in openjdk17, in noncompilable files. I am not sure if we should add files filters for these files, though, since they are how I confirmed logic of check update. I think that they might be valuable in the future for similar reasons.
Blocked until …
=> Issue #11220: False positive in MissingSwitchDefault with pattern in switch label

config/checkstyle_resources_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableWithoutPackageStatement.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unusedlocalvariable/InputUnusedLocalVariableNestedClasses2.java
Part of #6320: Kill surviving mutations for REMOVE_CONDITIONALS in UnusedLocalVariableCheck
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/432e52446da09d37b6c0def38f08c6a5ca6446a5/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/ef336038bce0e1a7af42b9032aa41cd1266a2d89/my_checks.xml
---
pit-report (see active mutators at the end): https://vyom-yadav.github.io/DiffReport/pit-reports/202201221220/com.puppycrawl.tools.checkstyle.checks.coding/UnusedLocalVariableCheck.java.html
Diff report: https://vyom-yadav.github.io/DiffReport/diffUnusedKillMutations/index.html
=> Issue #6320: Kill surviving mutations for REMOVE_CONDITIONALS in UnusedLocalVariableCheck

src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
Discovered while working in #9146 
`message.startsWith(message)` is always true. It's strange that no tool reports this.
=> minor: fix mistype in ImportControlCheckTest

.ci/jsoref-spellchecker/whitelist.words, .ci/validation.sh
Hibernate Search changed the name of its Maven property controlling the version of checkstyle, so the previous commands did not actually override the version of checkstyle.
Fortunately we upgrade checkstyle regularly in Hibernate Search (e.g. https://github.com/hibernate/hibernate-search/pull/2874), so we know it still works.
=> infra: Update commands used for validation with Hibernate Search

src/xdocs/beginning_development.xml, src/xdocs/index.xml.vm
Missed in #9146 
We need to update Index.html and beginning_development.html to specify the minimum JDK version.
=> doc: update requirements to jdk 11

src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModel.java
Fixes #11294 
`File#getParentFile` is actually `new File(file.getParent())` with null check.
=> Issue #11294: fix NPE in gui.MainFrameModel#getLastDirectory

config/checkstyle_checks.xml, src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/api/Configuration.java, src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
Issue #11289
Java 9 introduces two attributes for `@Deprecated` annotation: `since` and `forRemoval`.
The first one should be mandatory. New XPath check added to validate this.
=> Issue #11289: add since and forRemoval properties to Deprecated annotation

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnusedLocalVariableCheck.java
This field was removed in 0f3d9d4709f929d57310ff5505bbcfa4f93f1037 but I forgot to remove the comment related to it.
=> minor: Remove outdated comment from UnusedLocalVariable

.ci/validation.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorEnumMembers.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorInterfaceFields.java
Closes #11241 
for some reason, check was not aware that enums can have fields
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/332b1574376419f7ea927be6902398aedec8e3bf/confg.xml
=> Issue #11241: fix empty line separator for enum and interface fields

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/AvoidStarImportCheck.xml, src/xdocs/config_imports.xml
I found it confusing that the `excludes` property only mentioned packages, yet when I specified a package, starred static member imports within that package were not excluded. This change clarifies that the `excludes` property uses packages for starred class imports and class names for starred static member imports.
https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html is a class
https://checkstyle.org/config_imports.html#AvoidStarImport we already have example where `exclude` uses not only package (2nd example).
---
Edit: the requested CLI demonstration of the existing behavior that is merely being documented in this PR:
```
tniessen@ubuntuserver:~/dev/checkstyle$ javac Test.java 
tniessen@ubuntuserver:~/dev/checkstyle$ cat Test.java 
import static java.lang.Math.*; // okay, …
```
=> doc: mention that excludes can be class names

src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.java, src/xdocs/config_imports.xml
Issue #11352
Example 1
```
amrdeveloper@machine:~/Downloads$ cat config.xml
<module name="AvoidStarImport">
<property name="allowClassImports" value="true"/>
<property name="excludes" value="java.io,java.net"/>
</module>
</module>
</module>
amrdeveloper@machine:~/Downloads$ cat Test.java
import java.util.Scanner;         // OK
import java.io.*;                 // OK
import static java.lang.Math.*;   // violation
import java.util.*;               // OK
import java.net.*;                // OK
amrdeveloper@machine:~/Downloads$ java -jar checkstyle.jar -c config.xml Test.java
Starting …
```
=> Issue #11352: Update AvoidStarImport documentation with example for mix of properties

config/import-control.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/MetadataGeneratorLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraperTest.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
Continuing #10805 
Resolves #10747: MetadataGeneratorUtil now reports errors back to the users
Summary-
The previous PR #10805 added the support of logging a violation in `JavadocMetadataScraper` when the module doesn't contain javadoc description. As `JavadocMetadataScraper` is not a part of checkstyle_checks and we need metadata beforehand we execute it with the help of `MetadataGeneraotrUtilTest`. In this PR support was added to show the violations we logged in `JavadocMetadataScraper`.
A separate logger has been created to get rid of `Audit starting...` messages which are printed by the `DefaultLogger`. Inside the test, we capture the output silently and then compare it with the expected violations.
=> Issue #10747: MetadataGeneratorUtil now reports errors back to the users

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
Issue number: #11214
In DeclarationOrderCheck all violation messages are specified correctly and testing passed correctly so and should be remove from the InlineConfigParser list
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder
=> Issue #11214: Remove DeclarationOrderCheck from InlineConfigParser

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckSwitchExpression.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckTextBlocks.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesLambdas.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesOperatorsAndCasts.java
Specified violation messages in input files for **one** of the checks - `UnnecessaryParenthesesCheck` - in Issue #11214 .
=> Issue #11214: Specify violation messages for UnnecessaryParenthesesCheck

config/signatures.txt, pom.xml
Closes #10933 .
Example of error message:
```
[ERROR] Forbidden method invocation: com.puppycrawl.tools.checkstyle.api.AbstractCheck#log(int,java.lang.String,java.lang.Object[]) [Use of this log method is forbidden, please use AbstractCheck#log(DetailAST ast, String key, Object... args)]
```
=> Issue #10933: Checkstyle should force logging of AST in checks that require it

src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
The comment said "each each" instead of just "each"
=> spelling: Fix double word in TreeWalker

src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderForwardReference.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/InputNoWhitespaceBeforeCaseDefaultColon.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperAbstractSuperCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperAnnotationUseStyleCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperAtclauseOrderCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperRightCurlyCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/InputJavadocMetadataScraperWriteTagCheck.java
Issue #4845
Targetted TokenTypes and switch them to Calendar which also has public static integer fields.
=> Issue #4845: removed usage of TokenTypes from inputs

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterWithEmoji.java
Issue #10924: Updated NoWhitespaceAfterCheck to use codepoints
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/ee7bdfb2a7f3238291d8fd09eb24a752/raw/21d54b97bef2a9883661ab84140125af7f877c27/config.xml
```
src % cat config.xml Test.java 
<property name="severity" value="warning"/>
<property name="fileExtensions" value="java, properties, xml"/>
<module name="NoWhitespaceAfter"/>
</module>
</module>
/* a🎄🎄a*/ char  []c2= "🤩🎄".toCharArray(); // violation but not reported
/* trees*/ char  []c3= …
```
=> Issue #10924: Update NoWhitespaceAfterCheck to use codepoints

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
Issue #10924: `WhitespaceAroundCheck` already uses `codepoint`. Updated this check to use `CodePointUtil` methods.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/d4bef73243734249b18a2f5fa01ef190/raw/ecbfc3ab7e81187983b6f8ae78547254421f9e1d/config.xml
=> Issue #10924: Update WhitespaceAroundCheck

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
Issue #11214: Remove DefaultComesLastCheck from unspecified violation message suppression
In DefaultComesLastCheck all violation messages are specified correctly and testing passed correctly so we should be remove from the InlineConfigParser list
https://github.com/checkstyle/checkstyle/tree/master/src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast
=> Issue #11214: Remove DefaultComesLastCheck from unspecified violation message suppression

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/AbstractParenPadCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
Issue #10924: AbstractParenPadCheck already uses code points. Updated this check to use CodePointUtil methods.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/327da1e283758cd4593c483c91f7ff76/raw/a4ce66842137ae5e853df3e40d28ddc7f6833840/config.xml
```
checkstyle % git grep "extends AbstractParenPadCheck" 
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java:public class ParenPadCheck extends AbstractParenPadCheck {
src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheck.java:public class TypecastParenPadCheck extends AbstractParenPadCheck {
```
=> Issue #10924: Refactored AbstractParenPadCheck to use CodePointUtil methods.

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesCheckSwitchExpression.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesReturnValue.java
Fixes #11357. Had to fix some tests, also in the SwitchExpression test
Diff Regression config: https://gist.githubusercontent.com/OttoKaaij/363ce8a2a1007b4a3856cda24bb4e1c6/raw/4e6e0ec1c7b56bc728034e36ec498527c7aa2f8d/my_checks.xml
Regression report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/cdec517_2022140934/reports/diff/index.html
=> Issue #11357: Report correct violation in lambda return

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
No need to use `getLineCodePoints` as we check if line is blank or after removing whitespace line starts `//` or `/*`.
Since, we require only particular line so there is no need to get all lines from files
=> minor: Removed usages of getLines in EmptyLineSeparatorCheck

src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
For some reason, the modifiers in `ScopeUtil` are compared by text.
Maybe it comes from very ancient code.
Diff Regression config: https://gist.githubusercontent.com/pbludov/3a8be5da26a64e2be80b26217d052eb6/raw/343dd6f3ef6e8c8d3ae5c06821cc4a4f59fb4101/config.xml
=> minor: compare tokens by type in ScopeUtil

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SummaryJavadocCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineReturn.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineReturnForbidden.java, src/xdocs/config_javadoc.xml
This fixes #10776.
Diff Regression config: https://gist.githubusercontent.com/octylFractal/4fd8d417bc3c14e0e2567f512e3769c2/raw/9fb50b87f3a6afc102e846a707693d91e08a2c8a/config.xml
=> Add support for inline return tag in SummaryJavadoc

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java, src/xdocs/config_coding.xml
Issue https://github.com/checkstyle/checkstyle/issues/7650: add code samples
```
C:\Users\ExApricity\Desktop>type config.xml
<module name="MultipleStringLiterals">
</module>
</module>
</module>
C:\Users\ExApricity\Desktop>type Test.java
String a = "StringContents";
String a1 = "unchecked";
@SuppressWarnings("unchecked") // OK, duplicate strings are ignored in annotations
String a2 = "StringContents"; // violation, "StringContents" occurs twice
String a3 = "DoubleString" + "DoubleString"; // violation, "DoubleString" …
```
=> issue #7650:add code samples

src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/trailingcomment/InputTrailingCommentWithEmoji.java
Issue #10924: Updated TrailingCommentCheck to use code points
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/338aa5815422d64fc1e119861cac1336/raw/ef19e01810ccc472e359e17175cb8dd5885d983c/config.xml
Proof that check requires update: https://github.com/checkstyle/checkstyle/pull/11422#issuecomment-1069099315
=>  Issue #10924: Update TrailingCommentCheck to use code points

.ci/eclipse-compiler-javac.sh
Issue #9146
The default Java version used by Eclipse compiler in CI should be 11.
=> Issue #9146: set default Java release to 11 for Eclipse compiler

src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
It is strange that the hotkey for Open file dialog is `Alt+S`. It looks like a mistype.
Should be `Alt+O`.
Maybe it was "Select file" originally, but later the label was changed.
=> minor: fix mnemonic for open file button

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
Issue #10924: Updated NoWhitespaceBeforeCheck.
This check already uses code points, refactored to use methods in `CodePointUtil`.
Diff Regression config: https://gist.githubusercontent.com/MUzairS15/12920ff345227511c6d2b7321cb6e344/raw/8a547b379e405964c2fb4a1ec8e719c7a20d0366/config.xml
=> Issue #10924: Update NoWhitespaceBeforeCheck 

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CodePointUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapWithEmoji.java
Issue #10924: Updated SeparatorWrapCheck to use code points
```
src % cat config.xml
<module name="SeparatorWrap">
<property name="option" value="NL"/>
</module>
</module>
</module>
src % cat src/main/java/Test.java 
void test() {
String s = "sda";
/* 🎄🎄 */ s.
isEmpty(); // violation but not reported
/* sda */ s.
isEmpty(); // violation and reported
}
}      
src % java -jar checkstyle-10.0-all.jar -c config.xml src/main/java/Test.java
[ERROR] Test.java:6:28: '.' should be on a new line. [SeparatorWrap]
Audit done.
``` …
=> Issue #10924: Update SeparatorWrapCheck to use code points

config/version-number-rules.xml
Patterns  **EI_EXPOSE_REP, EI_EXPOSE_REP2** were suppressed in 5e618459068dbd6d64a8f3518e4fce38b26b5a6f
And we have already updated spotbugs-maven-plugin to the latest version. There is no longer any reason for this suppression.
=> Minor: remove suppression for spotbugs-maven-plugin version check

src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/MethodLengthCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCompactCtorsCountEmpty.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthTextBlocksCountEmpty.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptySmallSize.java, src/xdocs/config_sizes.xml
Issue #11166 
Remove usage of getFileContents for method length check.
Note - count is changed because now check ignores block comments as well.
Report - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/80b7f57_2022070929/reports/diff/index.html
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/4d8840dce7f80febf98199fab58575402d503fec/confg.xml
=> 11166 remove get file contents method length

.ci/jsoref-spellchecker/whitelist.words, .ci/no_old_refs.sh, .github/workflows/no_old_refs.yml
Resolves #11442
Tested at - https://github.com/Vyom-Yadav/actions-test/pull/39
https://github.com/Vyom-Yadav/actions-test/pull/40
Direct push to master - https://github.com/Vyom-Yadav/actions-test/runs/5655841079?check_suite_focus=true
Push to PR (not from fork) - https://github.com/Vyom-Yadav/actions-test/runs/5655783382?check_suite_focus=true
Push to PR (from fork) - https://github.com/Vyom-Yadav/actions-test/runs/5655810498?check_suite_focus=true
---
What this PR does-
1. **Improved reporting:-** A clickable link is now given to the user which redirects it to the line where the closed issue is referenced. 
2. **Runs on a PR:-** The job now runs on a PR too.
3. **Issues linked to PR are mentioned:-** If the developer has linked some issue to the PR and that issue is referenced somewhere …
=> Issue #11442: Check no closed issue references workflow is now triggered on pull requests

.ci/jsoref-spellchecker/whitelist.words, .ci/travis.sh, .travis.yml
Master build is failing 
They migrated https://github.com/hibernate/hibernate-search/commit/81a280863aab3e42a8f9eb52d3c277b5c7731373
=> config: bump hibernate search to jdk 17

.ci/jsoref-spellchecker/whitelist.words, src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheck.java, src/xdocs/config_naming.xml
Issue #10889 Updated Documentation regarding how `AbbreviationAsWordInNameCheck` checks for abbreviation.
=> Issue #10889 : Updated Documentation regarding how AbbreviationAsWordInNameCheck checks for abbreviation.

src/xdocs/writingchecks.xml
While reading through this document to get started on more substantial contributions, I decided to attempt to fix some grammatical errors present in the document. The content of the text was very helpful, so big thanks there to the writers!
=> Doc: improve grammar in writingchecks.xml

src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
This PR proposed to use a naive implementation for `TokenUtil.isOfType`, as discussed in #11370. This yields a significant speedup of Checkstyle run-time.
=> Issue #11370: use naive implementation for isOfType

src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/header/AbstractHeaderCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagInfo.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTags.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/XpathUtil.java
1. Replace some usages, where static factory method can be used
2. Simplify some places, where new java11 Collectors methods can be used
Note: some static fields sets where mutable, but now they are immutable.
=> minor: replace Collections.unmodifiable* with static factory methods

src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java
These tests are useless. If the **user.language** property is set to anything else but English, 200+ tests will fail.
So we need a dedicated test suite to validate all supported languages.
=> minor: remove testLocaleIsSupported tests

config/spotbugs-exclude.xml
Issue #11140
http://fb-contrib.sourceforge.net/bugdescriptions.html
>SLS_SUSPICIOUS_LOOP_SEARCH This method continues with a loop, and does not break out of it, after finding and setting a variable in an if condition based on equality. Since continuing on in the loop would seem to be unlikely to find the item again, breaking at this point would seem to be the proper action. Example: int age = 0; for (Person p : people) { if (p.getName().equals("Dave")) { age = p.getAge(); } }   It is likely you wanted a break after getting the age for "Dave".
=> Issue #11140: resolve SLS_SUSPICIOUS_LOOP_SEARCH

src/main/java/com/puppycrawl/tools/checkstyle/api/FileContents.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/InputMissingJavadocPackageNotPackageInfo-package-info.java
Fixed the issue #11531 by checking if the file name is equal to "package-info.java".
=> Issue #11531: Fixed methods for package-info file check

config/intellij-idea-inspections.properties, src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/SarifLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FallThroughCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThroughStringSwitch.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentNotInLoopContext.java
Issue #11566 
* syntax error in `.config` files
* ~~'if' statement can be replaced with conditional or boolean expression~~
* null check can be replaced with method
* call to set.removeAll may work slowly
* redundant string operation
* synchronized method
Two new test inputs added: for an assignment not within a loop and for "fallthru" outside of a comment.
=> Resolve IDEA violations from Teamcity 2022.04 part 2

config/import-control.xml, src/main/java/com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.java
`ReverseListIterator` is basically a utility class. It shouldn't have anything specific to checkstyle similar to `ReverseDescendantIterator` and the others...
=> minor: removes checkstyle specific class in ReverseListIterator

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_8.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumber_9.java
Issue #10043
The bug in line 12 is caused by the following line [lastColumn = nextAST.getColumnNo() - 1;](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L338)
It will lead to the 8 of the method2() be out of the range of the SuppressWarnings and will not be suppressed. The end position of the SuppressWarnings will be located to the ";" at the end of the code line. If it minus one, it will not cover the "8", which is just before the ";" .
=> Issue #10043: Fixed SuppressWarnings not working on local variables

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPad2.java
Went through the test tier to see why certain methods are still protected and not final. Found some instances were the methods were used in complex ways that weren't needed. Like manually creating the Checker when the verify method will do this for us, etc...
=> minor: removes complicated uses of test tier that are not needed

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java
Discovered in #11621
The method `getTypeArgsClassNames` is a `do-while` loop written as `while` loop.
Diff Regression config: https://gist.githubusercontent.com/pbludov/3a8be5da26a64e2be80b26217d052eb6/raw/a4f71fbe46c69ee580723a11be2690478433b987/config.xml
=> minor: do-while loop in VisibilityModifierCheck

config/sevntu_suppressions.xml
As title suggests. Identified through https://github.com/rnveach/checkstyle/tree/suppression_splitter .
=> minor: remove unnecessary sevntu suppressions

src/it/java/com/google/checkstyle/test/base/AbstractGoogleModuleTestSupport.java, src/it/java/com/sun/checkstyle/test/base/AbstractSunModuleTestSupport.java, src/it/java/org/checkstyle/base/AbstractCheckstyleModuleTestSupport.java, src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
#11604
First commit is a simple synchronize between Test and IT where similar code is.
Second commit is the bigger change. I reworked how we build the Checker tree so it is more streamlined and not passing around the enumeration. `createChecker` will now handle the current given module and identify if it needs a TreeWalker or other similar intermediary between it and the module. It also removed random config names and more closely used the ones they represent.
I could not make similar changes to the IT side as the IT side has some weird complexities that need to be dealt with. We pass the name of the check and not the full class. We have to pull things from an existing config, and we only do partial pulls, still rebuild the missing pieces. There are also some tests that pull in more …
=> Some reworking for test structures

.ci/jsoref-spellchecker/whitelist.words, pom.xml
Resolves #11662 
Related documentation: https://docs.oracle.com/en/java/javase/11/tools/javac.html#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9
>always - Generates a package-info.class file for every package-info.java file. This option may be useful if you use a build system such as Ant, which checks that each .java file has a corresponding .class file.
=> Issue #11662: Fixed NoSuchFileException during maven-compiler-plugin:3.10.1:testCompile

.ci/checkchmod.sh, .ci/no_old_refs.sh, .github/workflows/no_old_refs.yml, .shellcheckrc
Resolves: `SC2236` https://github.com/checkstyle/checkstyle/issues/11637
`SC2236: Use -n instead of ! -z` (https://github.com/koalaman/shellcheck/wiki/SC2236)
=> Issue #11637: Used Shellcheck to resolve SC2236 in Shell Script

src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElementTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilterAllNullConfiguration.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilterDecideByCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilterDecideById.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilterDecideByIdAndExpression.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionxpathsinglefilter/InputSuppressionXpathSingleFilterDefaultFileProperty.java
Issue #11460 SuppressionXpathSingleFilter suppresses all violations when used with the default configuration
This problem is caused by XpathFilterElement.accept(TreeWalkerAuditEvent event) returning false when all the properties set to null. This is fixed by adding a function judging if all the properties are set to null.
=> Issue #11460 Fixed the default behavior of SuppressoinXpathSingleFilter

pom.xml
Identified at https://github.com/rnveach/checkstyle-extras/issues/3
Very minor. Only thing found.
=> minor: fixes off pom indentation

pom.xml
Added tidy skip to no validation profile.
Identified at https://github.com/checkstyle/checkstyle/pull/11686 and https://github.com/rnveach/checkstyle-backport-jre8/commit/7032abdb5ec9d48e9e61079625bd8c7f547f4dd5 .
=> minor: includes skipping tidy on no-validations profile

pom.xml
Identified at https://github.com/checkstyle/checkstyle/pull/11686 and it's issue.
This removes inputs and expecteds from the test jar to reduce its size.
> -rw-r--r--  1 www-data www-data 10299902 May 31 21:54 checkstyle-10.4-SNAPSHOT-tests.jar
On Windows, new file size is: 3,576,922. Reduced by ~6.7 megs.
=> minor: removes inputs and expecteds from test jar to reduce size

.ci/jsoref-spellchecker/whitelist.words, .travis.yml
Attempt to fix failure to find `JAVA_HOME` env varible noted at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/572463219 and elsewhere
Upon starting container, openjdk is already installed:
```
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-11-hotspot-ppc64el
```
But later, travis ci tries to install coretto, which fails to download:
```
install_jdk
Installing openjdk11
--2022-06-06 03:58:06--  https://apt.corretto.aws/corretto.key
Resolving apt.corretto.aws (apt.corretto.aws)... 65.8.214.8, 65.8.214.107, 65.8.214.114, ...
Connecting to apt.corretto.aws (apt.corretto.aws)|65.8.214.8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1695 (1.7K) [binary/octet-stream]
Saving to: ‘STDOUT’
0K . …
```
=> infra: set JAVA_HOME in travis ci

.travis.yml
We forgot to link to explanation of manual JAVA_HOME assignment in travis.yml config, this PR adds quick explanation and link to investigation.
=> minor: add comment with explanation of manual setting of JAVA_HOME in travis.yml

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
Noticed during work on https://github.com/checkstyle/checkstyle/pull/11691, it is better to fix a simple violation like this, than to put a comment on it and let it live in the code base.
=> minor: make filters field final

.ci/pitest.sh, .github/workflows/pitest.yml, pom.xml
Resolves #11528 
No Checks are left for migration.
One check was left in the initial commit, semaphore failed - https://checkstyle.semaphoreci.com/jobs/7b20f037-132b-4ddd-ab3b-089fa7a1c702
Bash script mentioned below governs it.
https://github.com/checkstyle/checkstyle/blob/cffefba904f8d47f7bf9a9d9b053f5d33ea2afff/.ci/validation.sh#L39
---
`pitest-coding-1` -> `6 minutes`
`pitest-coding-2` -> `4 minutes`
`pitest-require-this-check` -> `18 minutes`
There is a separate instance for `RequireThis` as it consumes a lot of time. 
---
ATTENTION: Update https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-pitest-report after merging this PR.
=> Issue #11528: Split pitest coding into 3 to improve execution time

src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
Noticed during work on https://github.com/checkstyle/checkstyle/pull/11691, it is better to fix a simple violation like this, than to put a comment on it and let it live in the code base.
Diff Regression config: https://gist.githubusercontent.com/nick-mancuso/e46a3d11fe985fac1c4468c6b0f7fa4e/raw/98085c1a02a72fdf3419e35c5cbfe23cd9aa111c/config.xml
=> minor: use iterator instead of enumeration

.ci/pitest.sh
Resolves #11730 
Result:-
```
Supported profiles:
pitest-annotation
pitest-ant
pitest-api
pitest-blocks
pitest-coding-1
pitest-coding-2
pitest-coding-require-this-check
pitest-common
pitest-common-2
pitest-design
pitest-filters
pitest-gui
pitest-header
pitest-imports
pitest-indentation
pitest-java-ast-visitor
pitest-javadoc
pitest-main
pitest-metrics
pitest-misc
pitest-modifier
pitest-naming
pitest-packagenamesloader
pitest-regexp
pitest-sizes
pitest-tree-walker
pitest-utils
pitest-whitespace
pitest-xpath
```
=> Issue #11730: ci/pitest.sh --list doesn't show all pitest profiles

pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/MissingDeprecatedCheck.xml, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/modifier/RedundantModifierCheck.xml, src/xdocs/config_annotation.xml, src/xdocs/config_javadoc.xml, src/xdocs/config_modifier.xml, src/xdocs/index.xml.vm
Noticed at https://github.com/checkstyle/checkstyle/runs/6930711012?check_suite_focus=true
Two remaining "broken" links:
One (mojohaus) has been suppressed, since the plugin needs to update the link on their end.
I can't figure out what is going on with the other, I have no problem accessing the site:
```
➜  checkstyle git:(fix-broken-links) curl https://checkstyle.sourceforge.io/version/6.18/ -I 
HTTP/2 200 
date: Fri, 17 Jun 2022 15:43:47 GMT
```
Remaining "broken" links:
```
<td><i><a class="externalLink" href="https://checkstyle.sourceforge.io/version/6.18/">https://checkstyle.sourceforge.io/version/6.18/</a>: 403 Forbidden</i></td></tr></table></td></tr>
<td><i><a class="externalLink" …
```
=> minor: fix broken links

.ci/StarterRuleSet-AllRulesByCategory.groovy.txt, .ci/codenarc.groovy, .ci/codenarc.sh, .ci/jsoref-spellchecker/whitelist.words, .github/workflows/codenarc-analysis.yml
Resolves #11734
Failing CodeNarc analysis (Proof of working): https://github.com/checkstyle/checkstyle/runs/7021070841?check_suite_focus=true
=> Issue #11734: Add codenarc to CI for groovy files 

src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java, src/xdocs/config_misc.xml
Issue #7592: Update examples for TrailingComment
[Link to official doc if you need to compare](https://checkstyle.org/config_misc.html#TrailingComment_Examples)
* Added example for first and second configuration.
* Switched third example with third configuration since the proper order is `first configuration -> then example`.
* Added indentation to third and fourth configuration and third example.
* Fixed wrong configuration(I explain down below why I think it is wrong).
```console
stoyank@zenbook:~/Desktop/checkstyle$ cat configuration.xml 
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="TrailingComment" />
</module> …
```
=> Issue #7592: Update doc for TrailingComment

.ci/pitest.sh, .github/workflows/pitest.yml
From discussion at https://github.com/checkstyle/checkstyle/pull/11731#discussion_r903910867 and https://github.com/checkstyle/checkstyle/issues/11720#issuecomment-1164365831:
Extract maven execution from `pitest.sh` script.
Failed pitest run (for proof): https://github.com/checkstyle/checkstyle/actions/runs/2555422670
=> minor: extract maven execution from pitest

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassName.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameCustom.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameFormerFalsePositive.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameType.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameVariants.java
Addresses issue #11214
Specifies the violation messages for `AbstractClassNameCheck` in all relevant `Input..` files.
* Specified violation messages for `AbstractClassNameCheck` in 5 files
* Escaped RegEx special characters in the message. For instance, 
`^Abstract.+$` -> `\^Abstract\.\+\$`
* I got `Line should not be longer than 100 symbols [lineLength]` when  	running `mvn clean verify` so I moved the problematic `// violation '..'` 	comments above the violation line and changed them to `// violation below '..'`. This is what I noticed other people did.
* Changed the row numbers in `expected` variables in `AbstractClassNameCheckTest` due to the moved `// violation` comments.
* Removed the check from the suppresion list in `InlineConfigParser`.
The biggest outlier is in the …
=> Issue #11214: Specify violation messages for AbstractClassNameCheck

.ci/pitest-suppressions/pitest-javadoc-suppressions.xml, .ci/pitest-survival-check-html.sh, pom.xml
#7797 
Kill 2 surviving mutations in `pitest-javadoc`.
Both the mutations were removing the call to `beginJavadocTree(..)` and `finishJavadocTree(..)`, both these methods-
https://github.com/checkstyle/checkstyle/blob/da2237a0f86d6590673dafefb6d5995c60b5eb89/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java#L234-L248
Have no implementation by default. Only `JavadocMetadataScraper` overrides these methods.
Adding its test to the profile resulted in the mutations being killed. I didn't follow SOP as this case is different.
=> Issue #7797: Kill two surviving mutations in pitest-javadoc

.ci/tweet-releasenotes.sh
Resolves #11725
Generating Twitter Credential: https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api
=> Issue #11725: Automate twitter posts to use single shell command

.ci/jsoref-spellchecker/whitelist.words, .ci/prepare-settings.sh, .ci/release-settings.xml
=> Issue #11726: Automate creation of settings.xml file for release

.ci/validation.sh
Build failure in xwiki-commons: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/13681/workflows/f8556257-7af1-4c75-9cbe-34e53c647980/jobs/149782
Link to passing xwiki build: https://circleci.com/gh/checkstyle/checkstyle/149839?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> infra: checkout stable commit from xwiki-commons

.ci/validation.sh
Noticed at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/574884599 and elsewhere, gradle daemon has been disappearing and build has timed out.
Link to passing pgjdbc build: https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/574900564
=> infra: update pgjdbc commit

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11771
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d1202e8_2022093015/reports/diff/index.html
Without the condition `if (toVisit == null)`, `curNode = curNode.getParent();` will be executed even when `toVisit != null`, if `toVisit != null`, we will break from the loop
`while (curNode != null && toVisit == null)` and on the very next line after while loop, `curNode` gets updated `curNode = toVisit;`, so the previous assignment of
`curNode = curNode.getParent();`does not make a difference.
=> Issue #11720: Kill surviving mutation in RequireThisCheck

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11781
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a13586b_2022121954/reports/diff/index.html
- validateOnlyOverlappingFalseWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a13586b_2022042830/reports/diff/index.html
`validateOnlyOverlapping = false` report was not generated with OpenJDK (Out of memory in GitHub actions), though it is very unlikely that it will show any difference, still, if it is required, ping me, and I will generate it locally.
The next sibling is used at
`final Set<DetailAST> exprIdents = getAllTokensOfType(sibling, TokenTypes.IDENT);`
The method `getAllTokensOfType(..)` already …
=> Issue #11720: Kill surviving mutation in RequireThisCheck related to checking overlapping by local variable

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11776
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dc3d699_2022053018/reports/diff/index.html
- validateOnlyOverlappingFalseWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/dc3d699_2022072839/reports/diff/index.html
`validateOnlyOverlapping = false` report was not generated with OpenJDK (Out of memory in GitHub actions), though it is very unlikely that it will show any difference, still, if it is required, ping me, and I will generate it locally.
The condition `definitionToken.getType() == TokenTypes.STATIC_INIT` is same as the condition 
`codeBlockDefinition.getType() == TokenTypes.STATIC_INIT`. A …
=> Issue #11720: Kill surviving mutation in RequireThisCheck related to static blocks

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAnonymousEmpty.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11779
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/96fc21a_2022110234/reports/diff/index.html
- Find a case that kills the mutation via diff report, add new test in existing PR
=> Issue #11720: Kill surviving mutation in RequireThisCheck related to anonymous inner class

src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/api/CheckstyleException.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/DetectorOptions.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/grammar/javadoc/JavadocParseTreeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/testmodules/TestFileSetCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CloseAndFlushTestByteArrayOutputStream.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XdocUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XpathIteratorUtil.java
Adds noinspection tag for ChainOfInstanceofChecks, CheckedExceptionClass, ReturnOfInnerClass, AssignmentOrReturnOfFieldWithMutableType, ClassOnlyUsedInOnePackage, part of #11277
=> Issue #11277: update code base to have javadoc tag to explain noinspection content

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationRecordsAndCompactCtors.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationAfterAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationBlockCommentBeforePackage.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCheckWithEmoji.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentIsAtTheEndOfBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentsAfterMethodCall.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInEmptyBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInMultiblockStructures.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInSwitchBlock.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationJavadoc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationWithInMethodCallWithSameIndent.java
Addresses #11214  
and #11446 
* Updates all `CommentsIndentationCheckTest` methods to use `verifyWithInlineConfigParser()`.
* Adds violation messages to all related `InputCommentsIndentation*.java` files.
=> Issue #11446: Update CommentsIndentationCheckTest to use verifyWithInlineConfigParser

src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorRecordsAndCompactCtors.java
Addresses #11446
Updates 1 test in `EmptyLineSeparatorCheckTest` to use `verifyWithInlineConfigParser()`.
=> Issue #11446: Update EmptyLineSeparatorCheckTest to use verifyWithInlineConfigParser

pom.xml
Bug identified at https://github.com/rnveach/checkstyle-backport-jre8/issues/8#issuecomment-1172031439
Details of why this is an issue and how it screwed the backport release process at https://github.com/rnveach/checkstyle-backport-jre8/issues/8#issuecomment-1172386376
Extra file is created in repo:
```
mvn package -Passembly
....
[INFO] --- maven-shade-plugin:3.3.0:shade (default) @ checkstyle ---
[INFO] Including info.picocli:picocli:jar:4.6.3 in the shaded jar.
......
[INFO] Including org.xmlresolver:xmlresolver:jar:data:4.2.0 in the shaded jar.
[INFO] Dependency-reduced POM written at:
/home/rivanov/java/github/checkstyle/checkstyle/dependency-reduced-pom.xml
[WARNING] Saxon-HE-11.3.jar, antlr4-runtime-4.10.1.jar, checker-qual-3.12.0.jar, 
checkstyle-10.4-SNAPSHOT.jar, …
```
=> infra: turns off create dependency reduced pom for shade plugin

config/spotbugs-exclude.xml, src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java, src/main/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParser.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTags.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilter.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelector.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentation.java, src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java, src/main/java/com/puppycrawl/tools/checkstyle/xpath/iterators/ReverseListIterator.java
Part of #11140 
[Description](http://fb-contrib.sourceforge.net/bugdescriptions.html#OCP_OVERLY_CONCRETE_PARAMETER)
> This method uses concrete classes for parameters when only methods defined in an implemented interface or superclass are used. Consider increasing the abstraction of the interface to make low impact changes easier to accomplish in the future.
In general, this makes sense. But sometimes it requires additional imports from foreign packages.
Code:
```java
private static void addLastSibling(DetailAstImpl self, DetailAstImpl sibling) {
```
Report:
```
[ERROR] Medium: com.puppycrawl.tools.checkstyle.JavaAstVisitor.addLastSibling(DetailAstImpl, DetailAstImpl):
2nd parameter 'sibling' could be declared as com.puppycrawl.tools.checkstyle.api.DetailAST instead …
```
=> Issue #11140: solve OCP_OVERLY_CONCRETE_PARAMETER

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExtendedMethod.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11801
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/524f25d_2022054435/reports/diff/index.html
- validateOnlyOverlappingFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2094829_2022200724/reports/diff/index.html
The logic was analyzed and a test case was developed.
=> Issue #11720: Kill surviving mutation in RequireThisCheck in isAstSimilar

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11778
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b264150_2022061102/reports/diff/index.html
- validateOnlyOverlappingFalseWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/156cf72_2022113923/reports/diff/index.html
Instead of `addIdent(..)` when visiting the `LITERAL_CATCH` token, we just add `catchFrame` to the `frameStack` and when we visit `PARAMETER_DEF` in the visitor pattern, we add that token, it will be added to `catchFrame` as it was the last frame added to the stack.
---
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/5dc88b466a50335 …
=> Issue #11720: Kill surviving mutation in RequireThisCheck in collectDeclarations

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11780
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/4d8bbaa_2022114649/reports/diff/index.html
- validateOnlyOverlappingFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/4d8bbaa_2022152354/reports/diff/index.html
The condition is redundant, the only case in which the result might not be what is expected is when the frame is `FrameType.CTOR_FRAME` in which the earlier method returned `false` but the current method will result `true`. Shouldn't be a problem, fields with `FrameType.CTOR_FRAME` are ctor parameters and variable declarations are not checked, only usages are checked- …
=> Issue #11720: Kill surviving mutation in RequireThisCheck in isInsideConstructorFrame

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLambdaParameters.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11802
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2f8428b_2022054812/reports/diff/index.html
- validateOnlyOverlappingFalseWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2f8428b_2022100531/reports/diff/index.html
- Find a case that kills the mutation via diff report, add new test in existing PR
=> Issue #11720: Kill surviving mutation in RequireThisCheck in isAnonymousClassDef

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisLocalClassesInsideLambdas.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11787
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/afd61f5_2022053245/reports/diff/index.html
- validateOnlyOverlappingFalseWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/afd61f5_2022072739/reports/diff/index.html
This method is only used at: https://github.com/checkstyle/checkstyle/blob/c8c2d8c7edaa05ce457b5babd6be27daff299528/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L870-L876
Where we check `codeBlockDefinition` for having a `static` modifier that can't be used with constructors. The rationale for adding this at that time could be to save a few iterations. …
=> Issue #11720: Kill surviving mutation in RequireThisCheck related to getting block-definition for the code

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11810
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ed54487_2022191546/reports/diff/index.html
- treatTryResourcesAsStatementTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ed54487_2022202733/reports/diff/index.html
- treatTryResourcesAsStatementTrueDefaultProjects: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ed54487_2022132649/reports/diff/index.html
- Nothing was found in the reports, the logic of the check was analyzed, and this test case was developed. (Now my brain works 10% more :) )
=> Issue #11720: Kill surviving mutation in OneStatementPerLineCheck leaveToken

.ci/tweet-releasenotes.sh
tested:
```
$ source ~/.m2/export-cs-release-vars.sh
✔ ~/java/github/romani/checkstyle [Rahulkhinchi03/setting-2 L|✚ 1] 
$ export CS_RELEASE_VERSION="10.3.1" && ./.ci/tweet-releasenotes.sh
fatal: destination path 'contribution' already exists and is not an empty directory.
^C
✘-INT ~/java/github/romani/checkstyle [Rahulkhinchi03/setting-2 L|✚ 1] 
$ rm -rf .ci-temp/
✔ ~/java/github/romani/checkstyle [Rahulkhinchi03/setting-2 L|✚ 1] 
$ export CS_RELEASE_VERSION="10.3.1" && ./.ci/tweet-releasenotes.sh
....
CS_RELEASE_VERSION=10.4-SNAPSHOT
LATEST_RELEASE_TAG="checkstyle-10.3.1"
[WARN] Issue .....
Execution succeeded!
```
=> infra: check GITHUB_READ_ONLY_TOKEN in tweet-releasenotes.sh

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionConstantNameTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/constantname/SuppressionXpathRegressionConstantNameCamelCase.java, src/it/resources/org/checkstyle/suppressionxpathfilter/constantname/SuppressionXpathRegressionConstantNameLowercase.java, src/it/resources/org/checkstyle/suppressionxpathfilter/constantname/SuppressionXpathRegressionConstantNameWithBeginningUnderscore.java, src/it/resources/org/checkstyle/suppressionxpathfilter/constantname/SuppressionXpathRegressionConstantNameWithTwoUnderscores.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Addresses #6207
Adds 4 regression tests for `ConstantName` check.
=> Issue #6207: Add XPath regression tests for ConstantName

pom.xml
References issue #11846 as requested in https://github.com/checkstyle/checkstyle/pull/11793#issuecomment-1172971759.
=> config: reference issue #11846 for EmptyLineSeparatorCheckTest

config/suppressions.xml, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/xdocs/config_annotation.xml, src/xdocs/config_filters.xml, src/xdocs/google_style.xml
=> Issue #11655: allow suppressing Google style warnings with annotations and comments

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFalsePositive.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11837
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2197fa9_2022062425/reports/diff/index.html
- validateEnhancedForLoopVariableTrueWithParameterDefWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2197fa9_2022082305/reports/diff/index.html
- validateEnhancedForLoopVariableTrueWithParameterDefWithOnlyOpenJDK: https://vyom-yadav.github.io/openJdkReports/killSurvivingMutationInFinalLocalVariableCheck-1/reports/diff/index.html
Just the condition `ast.getParent().getType() == TokenTypes.SWITCH_RULE` is sufficient, the other condition `ast.getParent().getParent().findFirstToken(TokenTypes.SWITCH_RULE) == ast.getParent()` results in a false negative, the …
=> Issue #11720: Kill surviving mutation in FinalLocalVariableCheck related to SWITCH_RULE

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldLambdas2.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11833
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ec40b73_2022185735/reports/diff/index.html
- setterCanReturnItsClassAndIgnoreSetter: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ec40b73_2022035007/reports/diff/index.html
- Missing test case was added from the diff report.
---
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/a116179eb9e7b14ffc38b86575e8cb2796489dde/my_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/bd2c453cc3ac1e892a11225639415edd1b027900/projects-to-test-on.properties
Report label: DefaultConfig
These are the default …
=> Issue #11720: Kill surviving mutation in HiddenFieldCheck related to setter method

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableSwitchStatement.java
https://github.com/checkstyle/checkstyle/issues/11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11841
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8a3ffff_2022191625/reports/diff/index.html
- validateEnhancedForLoopVariableTrueWithParameterDefWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8a3ffff_2022130102/reports/diff/index.html
The logic was analyzed and a test case was developed.
=> Issue #11720: Kill surviving mutation in FinalLocalVariableCheck related to switch statement

.ci/validation.sh
Fixes damaged build from xwiki-platform noted at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/13922/workflows/c3c97a12-592e-41d1-90d2-7ce5da3c9d13/jobs/154090, search by "ClassFanoutComplexity"
Link to xwiki build: https://circleci.com/gh/checkstyle/checkstyle/154296?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> infra: specify xwiki-platform commit

src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtil.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodAllowedAnnotations.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeMultipleQualifiedAnnotation.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeQualifiedAnnotation1.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeQualifiedAnnotation2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeQualifiedAnnotation3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeQualifiedAnnotation4.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeQualifiedAnnotation5.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeQualifiedAnnotationWithParameters.java
Addresses #11736
Adds support for qualified annotation names in `MissingJavadocTypeCheck`.
Diff Regression config: https://gist.githubusercontent.com/stoyanK7/37de7a689373daea1df3ec5f4e16efbb/raw/4f28948a768d7cf7fb3a59f6f1faf9e6152d28fa/config.xml
=> Issue #11736: Support qualified annotation names for MissingJavadocTypeCheck

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldClassNestedInRecord.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11830
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7a12e30_2022144013/reports/diff/index.html
- setterCanReturnItsClassAndIgnoreSetter: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7a12e30_2022033855/reports/diff/index.html
The logic was analyzed and a test case was developed. Though this violation looks like a false positive to me.
=> Issue #11720: Kill surviving mutation in HiddenFieldCheck in visitOtherTokens

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11840
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/ebad84d_2022065725/reports/diff/index.html
- validateEnhancedForLoopVariableTrueWithParameterDefWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/d873a2b_2022082232/reports/diff/index.html
Only `LITERAL_IF` can have last child as `LITERAL_ELSE`. `else` statements can be only used with `if` statemennts.
---
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/b6cf9595bf1c29d308be0677128ed9f1e760d07b/my_checks.xml
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/c7d0fc6900b7c10681be2f69147ea604 …
=> Issue #11720: Kill surviving mutation in FinalLocalVariableCheck related to if statement

.ci/jsoref-spellchecker/exclude.pl, .ci/jsoref-spellchecker/whitelist.words, cdg-pitest-licence.txt, config/checkstyle_non_main_files_suppressions.xml, pom.xml
Resolves #11727 
---
```diff
+ decreased execution time
- increased execution time
```
---
Compared with https://github.com/checkstyle/checkstyle/pull/11866
Run with accelerator: https://github.com/checkstyle/checkstyle/actions/runs/2640881429
Run without accelerator (#11866): https://github.com/checkstyle/checkstyle/actions/runs/2636912598
Run without licence: https://github.com/checkstyle/checkstyle/actions/runs/2641406919
```diff
@@ Profile                           New time               Previous time @@
+  pitest-annotation                 1m 44s                 2m 13s 
+  pitest-ant                        1m 42s                 1m 51s 
+  pitest-api                        2m 50s                 4m 30s 
+  pitest-blocks                     1m 54s                 3m 35s 
+ …
```
=> Issue #11727: Include CDG Accelerator Plugin to boost pitest performance

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
#11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#HiddenField
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11832
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1d0786f_2022212117/reports/diff/index.html
- setterCanReturnItsClassAndIgnoreSetter: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1d0786f_2022123815/reports/diff/index.html
Only 4 tokens at present can reach this method. `VARIABLE_DEF`, `PARAMETER_DEF`, `PATTERN_VARIABLE_DEF` and `RECORD_COMPONENT_DEF`. This condition is redundant as the upcoming conditions make sure that it can be only `PARAMETER_DEF` that can change the result of the method.
The upcoming conditions-
```java
final DetailAST parametersAST = ast.getParent();
final …
```
=> Issue #11720: Kill surviving mutation in HiddenFieldCheck in isIgnoredSetterParam

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
#11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#OneStatementPerLine
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b2477f8_2022213233/reports/diff/index.html
- treatTryResourcesAsStatementTrueDefaultProjects: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/9574ed2_2022131711/reports/diff/index.html
The condition removed is `!TokenUtil.areOnSameLine(prevSibling, ast)`, this condition helped in governing whether we would change `currentStatement` to
`currentStatement = ast.getPreviousSibling();`. If this was true i.e. `prevSibling` and `currentStatement` aren't on same line, we would do the above mentioned change.
Now this change occurs even if `prevSibling` and `currentStatement` are on the same line, in that case, …
=> Issue #11720: Kill surviving mutations in OneStatementPerLineCheck

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
#11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#HiddenField
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11831
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1aacc82_2022220212/reports/diff/index.html
- setterCanReturnItsClassAndIgnoreSetter: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/5702a2e_2022200904/reports/diff/index.html
Lambdas are of 3 types-
```java
foo1 obj = () -> {};  
foo2 obj2 = a -> {};  
foo2 obj3 = (a) -> {};
```
Related respective ASTs:
```
--LAMBDA -> ->
|--LPAREN -> (
|--PARAMETERS -> PARAMETERS
|--RPAREN -> )
`--SLIST -> { 
`--RCURLY -> }
```
```
--LAMBDA -> ->
|--IDENT -> a
`--SLIST -> {
`--RCURLY -> }
```
```
--LAMBDA -> ->
|--LPAREN -> (
|--PARAMETERS -> …
```
=> Issue #11720: Kill surviving mutation in HiddenFieldCheck related to lambda expressions

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
#11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#FinalLocalVariable
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11842
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/7fb6edf_2022111841/reports/diff/index.html
- validateEnhancedForLoopVariableTrueWithParameterDefWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/edbdae3_2022210449/reports/diff/index.html
The reason behind this change is due to the fact that this method was always called when it is guaranteed that the `childType` will always be of type `TokenTypes.CASE_GROUP`.
Usages of this method:
- First usage
https://github.com/checkstyle/checkstyle/blob/a6dec5beda11fd54734e2c5ae655ca09448e48a0/src/main/java/com/puppycrawl/t …
=> Issue #11720: Kill surviving mutation in FinalLocalVariableCheck related to case group

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, .ci/pitest-survival-check-html.sh, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
#11720
Check Documentation: https://checkstyle.sourceforge.io/config_coding.html#FinalLocalVariable
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11839
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/bbf9c34_2022205708/reports/diff/index.html
- validateEnhancedForLoopVariableTrueWithParameterDefWithoutOpenJDK: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/bbf9c34_2022122035/reports/diff/index.html
The only case we should be concerned is when `loop1 != null` is `false` i.e. `loop1 == null`.
Now there can be a case when `loop1 == null` and `loop2 == null` which will make this method return `true` as `loop1 == loop2` when it earlier returned `false`. 
The method `isInTheSameLoop(..)` will return `true` in that condition …
=> Issue #11720: Kill surviving mutation in FinalLocalVariableCheck related to loops

.ci/validation.sh, .drone.yml
"Fixes" (really allows us to bypass) failure noted at: https://cloud.drone.io/checkstyle/checkstyle/11222/4/2
I am guessing that this is the same issue mentioned by @romani regarding dropbox last week in discord:
```
Dropbox.
Hi Roman,
This email is an automated notification from Dropbox letting you know that your Public links have been temporarily suspended for generating excessive traffic.
```
The file we are actually downloading now:
```
➜  checkstyle git:(fix-infra-2) ✗ curl -o .ci-temp/cache.tar -SsL \
https://www.dropbox.com/s/"sh1g8o4h16p4n""x6"/cache.tar\?dl\=0
➜  checkstyle git:(fix-infra-2) cat .ci-temp/cache.tar 
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dropbox - 404</title>
<link …
```
=> infra: remove cache from drone execution

.cirrus.yml
This is just an experiment for now to see what fails if we do not install this package.
This build has been failing frequently lately from bad install of xmlstarlet: https://github.com/checkstyle/checkstyle/runs/7314089466
```
Added C:\ProgramData\chocolatey\bin\xsltproc.exe shim pointed to '..\lib\xsltproc\tools\xsltproc.bat'.
ShimGen has successfully created a shim for iconv.exe
ShimGen has successfully created a shim for xmlcatalog.exe
ShimGen has successfully created a shim for xmllint.exe
The install of xsltproc was successful.
Software installed to 'C:\ProgramData\chocolatey\lib\xsltproc\tools\..\dist'
Chocolatey installed 1/1 packages. 
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 0 …
```
=> infra: disable xmlstarlet install

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/MissingJavadocTypeCheck.xml, src/xdocs/config_javadoc.xml
Addresses [#11736](https://github.com/checkstyle/checkstyle/issues/11736#issuecomment-1181167741)
Updates documentation and provides one more example.
https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType
=> Issue #11736: Update doc for MissingJavadocTypeCheck

src/xdocs/config_system_properties.xml
taken from https://github.com/checkstyle/checkstyle/issues/10356#issuecomment-1176777269
error message modified a bit to match limit of 100 symbols, "Name" word is removed, I think it will be not noticable.
=> doc: put example of enableExternalDtdLoad to xdoc

.ci/pitest-suppressions/pitest-ant-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
#11720 
Checkstyle Ant Task documentation: https://checkstyle.sourceforge.io/anttask.html
N/A
`antTask.execute()` uses `System.currentTimeMillis()` to calculate the time elapsed, if we note the time before and after the execution of the method, that will be more than or equal to the time calculated inside the method.
Now the order of execution of instructions can change in a multithreaded program as the scheduler controls the threads, but all the related methods run on a single thread only.
=> Issue #11720: Kill surviving mutation in CheckstyleAntTask related to logging

.ci/pitest-suppressions/pitest-ant-suppressions.xml, .ci/pitest-survival-check-html.sh, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
https://github.com/checkstyle/checkstyle/issues/11720
Checkstyle Ant Task documentation: https://checkstyle.sourceforge.io/anttask.html
N/A
These mutations were getting killed without any new test case when I `replaced equality check with true`. But the mutations were surviving in the `mutationCoverage` report due to branch optimization.
https://github.com/checkstyle/checkstyle/blob/40b3384a7f22ef41e434cbe747f0a803d2b2d7a2/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L698-L706
After branch optimization changed to-
```java
if (toFile != null && useFile) {                                                   
final OutputStream infoStream = Files.newOutputStream(toFile.toPath());        
defaultLogger = …
```
=> Issue #11720: Kill surviving mutation in CheckstyleAntTask related to creating logger

pom.xml
caused by latest version bump in exec-maven-plugin
https://github.com/checkstyle/checkstyle/runs/7373432546?check_suite_focus=true#step:3:2207
```
<td><i><a class="externalLink" href="https://www.mojohaus.org/exec-maven-plugin">https://www.mojohaus.org/exec-maven-plugin</a>: 301 Moved Permanently</i></td></tr></table></td></tr>
<td><i><a class="externalLink" href="https://www.mojohaus.org/exec-maven-plugin">https://www.mojohaus.org/exec-maven-plugin</a>: 301 Moved Permanently</i></td></tr></table></td></tr>
```
```
$ mvn site -Pno-validations
....
[INFO] Total time:  59.816 s
[INFO] Finished at: …
```
=> minor: fix linkcheck violation on trailing slash in new version of exec-maven-plugin

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11907
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2036331_2022184302/reports/diff/index.html
Lambdas are of 3 types-
```java
foo1 obj = () -> {};  
foo2 obj2 = a -> {};  
foo2 obj3 = (a) -> {};
```
Related respective ASTs:
```
--LAMBDA -> ->
|--LPAREN -> (
|--PARAMETERS -> PARAMETERS
|--RPAREN -> )
`--SLIST -> { 
`--RCURLY -> }
```
```
--LAMBDA -> ->
|--IDENT -> a
`--SLIST -> {
`--RCURLY -> }
```
```
--LAMBDA -> ->
|--LPAREN -> (
|--PARAMETERS -> PARAMETERS
|   `--PARAMETER_DEF -> PARAMETER_DEF
|       |--MODIFIERS -> MODIFIERS
|       |--TYPE -> TYPE
|       `--IDENT -> a …
```
=> Issue #11720: Kill surviving mutation in UnnecessaryParenthesesCheck in isLambdaSingleParameterSurrounded

config/spotbugs-exclude.xml
Part of #11140 
Same message(`Checks and filters are treated differently`) was above both methods.
>ITC_INHERITANCE_TYPE_CHECKING
This method uses the instanceof operator in a series of if/else statements to differentiate blocks of code based on type. If these types are related by inheritance, it is cleaner to just define a method in the base class, and use overridden methods in these classes.
=> Issue #11140: Solve ITC_INHERITANCE_TYPE_CHECKING

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11910
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/e1420ec_2022144656/reports/diff/index.html
```java
@MyAnnotation1(name = "ABC")
```
parses as:
```
ANNOTATION -> ANNOTATION 
|--AT -> @ 
|--IDENT -> MyAnnotation1 
|--LPAREN -> ( 
|--ANNOTATION_MEMBER_VALUE_PAIR -> ANNOTATION_MEMBER_VALUE_PAIR
|   |--IDENT -> name 
|   |--ASSIGN -> = 
|   `--EXPR -> EXPR 
|       `--STRING_LITERAL -> "ABC" 
`--RPAREN -> ) 
```
It has `IDENT`, `ASSIGN` and `EXPR` as its children, removing the condition  
`type != TokenTypes.ASSIGN` will also prevent `IDENT` and `EXPR` from going inside the block. …
=> Issue #11720: Kill surviving mutation in UnnecessaryParenthesesCheck in visitToken

.ci/pitest-suppressions/pitest-java-ast-visitor-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-java-ast-visitor`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-java-ast-visitor/index.html
=> Issue #11719: Activate all group for pitest-java-ast-visitor

.ci/validation.sh
Fixes failing no-error-xwiki build noted at https://circleci.com/gh/checkstyle/checkstyle/tree/master
no-error-xwiki build: https://circleci.com/gh/checkstyle/checkstyle/161144?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> infra: remove specific commits from no-error-xwiki build

.ci/pitest-suppressions/pitest-blocks-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-blocks`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-blocks/index.html
=> Issue #11719: Activate all group for pitest-blocks

.ci/pitest-suppressions/pitest-misc-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-misc`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-misc/index.html
=> Issue #11719: Activate all group for pitest-misc

.ci/pitest-suppressions/pitest-header-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-header`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-header/index.html
=> Issue #11719: Activate all group for pitest-header

.ci/pitest-suppressions/pitest-filters-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-filters`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-filters/index.html
=> Issue #11719: Activate all group for pitest-filters

.ci/pitest-suppressions/pitest-design-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-design`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-design/index.html
=> Issue #11719: Activate all group for pitest-design

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral2.java
#11720
Hardcoded mutation tested at: https://github.com/checkstyle/checkstyle/pull/11933
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8bed554_2022145753/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8bed554_2022100114/reports/diff/index.html
- Diff was found in report https://github.com/checkstyle/checkstyle/pull/11933#issuecomment-1190394605
This violation looks like a false positive to me, I created #11968 for it.
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck related to try-catch blocks

.ci/pitest-suppressions/pitest-annotation-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-annotation`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-annotation/index.html
=> Issue #11719: Activate all group for pitest-annotation

.ci/pitest-suppressions/pitest-imports-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-imports`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-imports/index.html
=> Issue #11719: Activate all group for pitest-imports

.ci/pitest-suppressions/pitest-coding-2-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-coding-2`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-coding-2/index.html
=> Issue #11719: Activate all group for pitest-coding-2

.ci/pitest-suppressions/pitest-metrics-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-metrics`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-metrics/index.html
=> Issue #11719: Activate all group for pitest-metrics

.ci/pitest-suppressions/pitest-xpath-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-xpath`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-xpath/index.html
=> Issue #11719: Activate all group for pitest-xpath

.ci/pitest-suppressions/pitest-main-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-main`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-main/index.html
=> Issue #11719: Activate all group for pitest-main

.ci/pitest-suppressions/pitest-whitespace-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-whitespace`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-whitespace/index.html
=> Issue #11719: Activate all group for pitest-whitespace

.ci/pitest-suppressions/pitest-utils-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-utils`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-utils/index.html
=> Issue #11719: Activate all group for pitest-utils

.ci/pitest-suppressions/pitest-naming-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-naming`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-naming/index.html
=> Issue #11719: Activate all group for pitest-naming

.ci/pitest-suppressions/pitest-modifier-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-modifier`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-modifier/index.html
=> Issue #11719: Activate all group for pitest-modifier

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11911
Check documentation: https://checkstyle.sourceforge.io/config_coding.html#UnnecessaryParentheses
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/26624b9_2022085405/reports/diff/index.html
Only `LAMBDA` can satisfy the condition https://github.com/checkstyle/checkstyle/blob/c5934093281c83126d7f34365501404f87fb46b8/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java#L635-L646
```java
foo2 obj3 = (a) -> {};
```
AST:
```
--LAMBDA -> ->
|--LPAREN -> (
|--PARAMETERS -> PARAMETERS
|   `--PARAMETER_DEF -> PARAMETER_DEF
|       |--MODIFIERS -> MODIFIERS
|       |--TYPE -> TYPE
|       `--IDENT -> a
|--RPAREN -> )
`--SLIST -> {
`--RCURLY -> } …
```
=> Issue #11720: Kill surviving mutation in UnnecessaryParenthesesCheck related to lambdas

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11938
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/be19a27_2022172028/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/be19a27_2022181609/reports/diff/index.html
In any variable declaration block, we wish to stop when the block ends, but this is already covered by the condition `currentAst != null`, an example will make things clearer-
```java
void method() {                 
int a = 12;                 
for (int i = 0; i != 0; ) { 
}                           
{                           
// Empty …
```
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in calculateDistanceInSingleScope

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11931
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/409dd3b_2022065548/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/409dd3b_2022181524/reports/diff/index.html
Redundant condition, the following condition 
`if (elseBlock.getType() == TokenTypes.LITERAL_ELSE) {` makes sure that only `if` statements enter the main logic block. Also, NPE is not possible as only `LITERAL_FOR`, `LITERAL_WHILE`, `LITERAL_DO`, `LITERAL_IF`, `LITERAL_SWITCH`, enter the method `isVariableInOperatorExpr` and each of these …
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in isVariableInOperatorExpr

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11936
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/92cf19e_2022101845/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/92cf19e_2022183001/reports/diff/index.html
When we remove the condition 
```java
if (currentNodeType == TokenTypes.SLIST) {
firstNodeInsideBlock = currentNode.getFirstChild();
}
```
and if the current node is of type `SLIST`, then the method `getFirstNodeInsideForWhileDoWhileBlocks` will return `SLIST` instead of its first child. This won't make a difference because in the caller …
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in getFirstNodeInsideForWhileDoWhileBlocks

.ci/pitest-suppressions/pitest-tree-walker-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-tree-walker`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-tree-walker/index.html
=> Issue #11719: Activate all group for pitest-tree-walker

.ci/pitest-suppressions/pitest-imports-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java
#6658
**Check Documentation:** https://checkstyle.sourceforge.io/config_imports.html#ImportControl
N/A
https://github.com/checkstyle/checkstyle/blob/7b88df3043a92eb8c821ea9370d0f286c3f1207d/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoader.java#L190-L193
is redundant as only `allow` and `disallow` can reach that branch, all other branches are covered before.
=> Issue #6658: Kill Surviving mutation in ImportControlLoader

.ci/pitest-suppressions/pitest-ant-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-ant`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-ant/index.html
=> Issue #11719: Activate all group for pitest-ant

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-coding-1`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-coding-1/index.html
=> Issue #11719: Activate all group for pitest-coding-1

.ci/validation.sh, .shellcheckrc
Part of #11637 
>  SC2269 # (info): This variable is assigned to itself, so the assignment does nothing.
=> Issue #11637: Resolve shellcheck SC2269

.ci/pitest-suppressions/pitest-api-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-api`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-api/index.html
=> Issue #11719: Activate all group for pitest-api

.ci/pitest-suppressions/pitest-packagenamesloader-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-packagenamesloader`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-packagenamesloader/index.html
=> Issue #11719: Activate all group for pitest-packagenamesloader

.ci/pitest-suppressions/pitest-common-2-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-common-2`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-common-2/index.html
=> Issue #11719: Activate all group for pitest-common-2

.ci/pitest-suppressions/pitest-sizes-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-sizes`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-sizes/index.html
=> Issue #11719: Activate all group for pitest-sizes

.ci/pitest-suppressions/pitest-regexp-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-regexp`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-regexp/index.html
=> Issue #11719: Activate all group for pitest-regexp

.ci/pitest-suppressions/pitest-common-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-common`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-common/index.html
=> Issue #11719: Activate all group for pitest-common

.ci/pitest-suppressions/pitest-coding-require-this-check-suppressions.xml, pom.xml
#11719
Activating `ALL` group for `pitest-coding-require-this-check`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-coding-require-this-check/index.html
=> Issue #11719: Activate all group for pitest-coding-require-this-check

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11937
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1931469_2022164752/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/1931469_2022181908/reports/diff/index.html
If variable wasn't used after its declaration then `variableUsageAst` will be null, this method returns 
`Entry<DetailAST, Integer>` , `new SimpleEntry<>(variableUsageAst, dist)` this method
(`calculateDistanceInSingleScope`) is only called at-
https://github.com/checkstyle/checkstyle/blob/32cfeee3a3b85eb26015dc515211c6db97a470f6/src/main/j …
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck related to usage distance

src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderWithAndWithoutCheckSuffixDifferentCases.java, src/xdocs/config_annotation.xml
Resolves #11885 
Allows `SuppressWarningHolder` to suppress violations with NameCheck i.e `@SuppressWarnings("checkstyle:constantnamecheck")` or `@SuppressWarnings("checkstyle:ConstantNameCheck") `
---
Diff Regression config: https://gist.githubusercontent.com/stoyanK7/73d7efde0efd9c6496ba95f0816ccb86/raw/0e0179ee0b4e193cb5faa8b5fcfa74a6bc1a46f0/config.xml
=> Issue #11885: Allow SuppressWarningHolder to suppress the violation with NameCheck

.ci/pitest-suppressions/pitest-javadoc-suppressions.xml, pom.xml
minor: Modify pitest mutators for `pitest-javadoc`
- Report with `ALL` group except `INLINE_CONSTS`: https://vyom-yadav.github.io/pitest-all-latest/pitest-javadoc/index.html
=> minor: Modify pitest mutators for pitest-javadoc

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
#11720
Hardcoded mutation tested at https://github.com/checkstyle/checkstyle/pull/11930
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8454c0e_2022065932/reports/diff/index.html
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8454c0e_2022181205/reports/diff/index.html
In any variable declaration block, we wish to stop when the block ends, but this is already covered by the condition `currentStatementAst != null`
There cannot be more statements in the branch after reaching `RCURLY` as it is the last child (if present). So the condition `currentStatementAst != null` is enough in every use case.
---
Diff …
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in searchVariableUsageExpressions

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java
Issue #11140
>OCP_OVERLY_CONCRETE_PARAMETER
This method uses concrete classes for parameters when only methods defined in an implemented interface or superclass are used. Consider increasing the abstraction of the interface to make low impact changes easier to accomplish in the future.
Take the following example:
private void appendToList(ArrayList<String> list) { if (list.size() < 100) { list.add("Foo"); } } 
The parameter list is currently defined as an ArrayList, which is a concrete implementation of the List interface. Specifying ArrayList is unnecessary here, because we aren't using any ArrayList-specific methods (like ensureCapacity() or trimToSize()). Instead of using the concrete definition, it is better to do something like:
private void appendToList(List<String> list) { ... 
If …
=> Issue #11140: solve more OCP_OVERLY_CONCRETE_PARAMETER

.ci/pitest-suppressions/pitest-api-suppressions.xml, pom.xml
#12017 
Mutations were present in the `log(..)` method, check tests, Xpath regression tests were added.
=> Issue #12017: Kill surviving mutations in AbstractCheck

.ci/pitest-suppressions/pitest-api-suppressions.xml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressByIdJavadocCheck.java
#12017 
- Logic was analyzed to develop the test case
=> Issue #12017: Kill surviving mutations in AbstractCheck and AbstractFileSetCheck

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmethod/InputJavadocMethodCustomMessage.java
#12017 
- Logic was analyzed to develop the test case.
This was not just a single mutation, this showcases the limitation of the pitest report checking model + the `mutations.xml` report provided by pitest. The problem of uniquely identifying mutations when `sourceFile`, `mutatedClass`, `mutatedMethod`, `mutator`, `description`, and `lineContent` is the same.
=> Issue #12017: Kill surviving mutations in AbstractCheck related to custom message keys

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractCheck.java
#12017 
No need to specifically initialize `tabWidth` to a default value, the default value is inherited from the parent module. Only the root modules need to explicitly instantiate `tabWidth` with a default value (Only `Checker` needs to instantiate the field)
https://github.com/checkstyle/checkstyle/blob/a54849afccd9cdc371c6040398d27225947debe0/src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java#L256-L265
=> Issue #12017: Kill surviving mutations in AbstractCheck for tabWidth

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
#12017 
- Logic was analyzed and the test case was modified.
=> Issue #12017: Kill surviving mutations in AutomaticBean related to String.format

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
#12017 
`RelaxedAccessModifierArrayConverter` is only used for `AccessModifierOption[].class`.
No need to invoke `trim()` here, they are trimmed at:
https://github.com/checkstyle/checkstyle/blob/74d8802acfb8833cd34538447d0852baa58e6c5b/src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption.java#L65-L67
=> Issue #12017: Kill surviving mutations in AutomaticBean related to trimming strings

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/api/AutomaticBean.java
#12017 
No need to trim strings here, they are trimmed further down in the method:
```java
while (tokenizer.hasMoreTokens()) {
final String token = tokenizer.nextToken();
result.add(token.trim());
}
```
=> Issue #12017: Kill surviving mutations in AutomaticBean related to trimming strings in RelaxedStringArrayConverter

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java
#12017
- Logic was analyzed to develop the test case.
=> Issue #12017: Kill surviving mutations in AbstractFileSetCheck related to fileExtensions

.ci/pitest-survival-check-xml.groovy
The problem was with the `setDifference(..)` method, both `setOne` and `setTwo` it received were sorted, but as result was a `HashSet`, and the sorting had no effect.
The correct order of elements is displayed now, moreover instead of sorting elements earlier, we sort them while calculating `setDifference(..)`, `setOne` and `setTwo` are of type `HashSet` instead of `TreeSet`, this also executes `setTwo.contains(mutation)` in `O(1)` (on an avg.)
=> minor: Fix sorting issue in pitest survival checking script

.ci/pitest-suppressions/pitest-annotation-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
#12036
The logic was analyzed to develop the test case.
=> Issue #12036: Kill surviving mutation in AnnotationUseStyleCheck related to trimming strings

.ci/common.sh, .ci/eclipse-compiler-javac.sh, .ci/releasenotes-gen.sh, .ci/travis.sh, .ci/validation.sh, .shellcheckrc, release.sh
Part of #11637
> SC2046 # (warning): Quote this to prevent word splitting.
---
Taken from [this stackexchange answer](https://unix.stackexchange.com/a/443990):
> You need to use `"$(somecmd "$file")"`.
=> Issue #11637: Resolve shellcheck SC2046

config/ant-phase-verify.xml, config/checkstyle_non_main_files_suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java, src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/ant/checkstyleanttask/ExpectedCheckstyleAntTaskSarifOutput.sarif, src/xdocs/anttask.xml.vm
#11985
1. created an uber jar using `mvn -P assembly package`
2. used the resultant jar along with the code in ant project - https://github.com/jknair0/AntCheckStyleTest/tree/pr/checkstyle-sarif-test
3. ran `ant checkstyle`
4. It generates a valid 'sarif' report.
=> Issue #11985: sarif formatter option added to ant task

.ci/pitest-suppressions/pitest-api-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
#12017
The logic was analyzed and the missing test case was added.
=> Issue #12017: Kill surviving mutations in AbstractCheck related to tokens

.ci/jsoref-spellchecker/exclude.pl, config/ant-phase-verify.xml
Excluded as TeamCity config is generated and contains embedded CDATA
=> minor: Exclude .teamcity dir from ant-phase-verify.xml and spellchecker

.ci/pitest-suppressions/pitest-annotation-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
#12036 
Link to check documentation: https://checkstyle.sourceforge.io/config_annotation.html#AnnotationUseStyle
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/cab090f_2022112136/reports/diff/index.html
- closingParensAlways: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/3a1700c_2022155641/reports/diff/index.html
The default value `ClosingParensOption.NEVER` was never used in the comparison, moreover the order of `if` statements guaranteed that the default value when replaced with `null` does not affect the logic.
The logic was modified a bit to use `ClosingParensOption.NEVER`.
---
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/8b937c2d78d340904640249dd597e382380dc6ea/my_checks.xml
Report …
=> Issue #12036: Kill surviving mutation in AnnotationUseStyleCheck related to closingParens

.ci/pitest-suppressions/pitest-annotation-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
#12036 
Link to check documentation: https://checkstyle.sourceforge.io/config_annotation.html#AnnotationUseStyle
- DefaultConfig: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b9302d2_2022111833/reports/diff/index.html
- trailingArrayCommaAlways: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6c1c4ca_2022160315/reports/diff/index.html
The default value `TrailingArrayCommaOption.NEVER` was never used in the comparison, moreover the order of `if` statements guaranteed that the default value when replaced with `null` does not affect the logic.
The logic was modified a bit to use `TrailingArrayCommaOption.NEVER`.
The value of `trailingArrayCommaOption` inside `logCommaViolation(..)` won't be `TrailingArrayCommaOption.IGNORE`, following code guarantees it: …
=> Issue #12036: Kill surviving mutation in AnnotationUseStyleCheck related to trailingArrayComma

.ci/bump-version.sh, .github/workflows/bump-version-and-update-milestone.yml
=> Issue #12058: Enhancements for bump version action

.ci/tweet-releasenotes.sh
=> Issue #12011: tweet-releasenotes.sh should be able to work on start and finish release names.

.ci/jsoref-spellchecker/whitelist.words, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java, src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
https://github.com/checkstyle/checkstyle/runs/7934338572?check_suite_focus=true#step:3:2454
```
<td><i><a class="externalLink" href="https://www.ietf.org/rfc/rfc4627.txt">https://www.ietf.org/rfc/rfc4627.txt</a>: 403 Forbidden</i></td></tr></table></td></tr>
<td><i><a class="externalLink" href="http://cvs.apache.org/viewcvs/jakarta-ant/src/main/org/apache/tools/ant/ProjectHelper.java">http://cvs.apache.org/viewcvs/jakarta-ant/src/main/org/apache/tools/ant/ProjectHelper.java</a>: 404 Not Found</i></td></tr></table></td></tr>
<td><i><a class="externalLink" href="http://pmd.sourceforge.net/pmd-5.3.1/pmd-java/rules/java/optimizations.html#SimplifyStartsWith">http://pmd.sourceforge.net/pmd-5.3.1/pmd-java/rules/java/optimizations.html#SimplifyStartsWith …
```
=> minor: correct links detected by linkcheck plugin

.ci/pitest-suppressions/pitest-coding-1-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceIfStatements.java
Closes #11720
- validateBetweenScopesFalse: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/78d2c37_2022195745/reports/diff/index.html
- validateBetweenScopesTrue: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/3fe931a_2022125544/reports/diff/index.html
There is no need to loop and check all the statements in the `if-else` chain at once, just check the current statement, the next statement (if present), and the outer method i.e. `calculateDistanceBetweenScopes` will iterate over the remaining branches, we just add the head of the remaining branches to `variableUsageExpressions` for it to be analyzed in the next iteration.
Also support for `if` statements …
=> Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in getFirstNodeInsideIfBlock

.ci/StarterRuleSet-AllRulesByCategory.groovy.txt, .ci/error-prone-check.groovy, .ci/error-prone-suppressions/compile-phase-suppressions.xml, .ci/error-prone-suppressions/test-compile-phase-suppressions.xml, .ci/jsoref-spellchecker/whitelist.words, .github/workflows/error-prone.yml, .mvn/jvm.config, config/checkstyle_non_main_files_suppressions.xml, pom.xml
Resolves #2160
Enabling error-prone for the project, all `.*[\\/]resources[\\/].*` are excluded from error-prone evaluation.
https://errorprone.info/docs/flags
---
**Proof of Working:**
- `New surviving error(s) found:` https://github.com/checkstyle/checkstyle/runs/7965373088?check_suite_focus=true
- `Unnecessary suppressed error(s) found and should be removed:` https://github.com/checkstyle/checkstyle/runs/7965413923?check_suite_focus=true
- Both `New surviving error(s) found:` and `Unnecessary suppressed error(s) found and should be removed:` https://github.com/checkstyle/checkstyle/runs/7965481307?check_suite_focus=true
---
`--add-exports` and `--add-opens` is required on JDK 16 and newer due to [JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396)
=> Issue #2160: Activate error-prone

.github/workflows/publish_releasenotes_for_twitter.yml
Fixes #12082 
To use Twitter variables as secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
=> Issue #12082: Github action Publish release notes Twitter 

.ci/jsoref-spellchecker/whitelist.words, config/intellij-idea-inspections.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitTest.java
#12099
1. A rule stating that classes in the API package are not dependent on classes in the utils package.
2. Suppression list containing classes that don't follow this rule.
=> Issue #12099: Add ArchUnit test to ensure classes in api package are not dependent on classes present in utils package

config/pmd-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/ArchUnitSuperClassTest.java
=> Issue #12099: Add ArchUnit test enforcing the rule that checks only extend AbstractCheck or AbstractFileSetCheck or AbstractJavadocCheck

config/pmd-test.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/ImmutabilityTest.java
#12099 
- There are 4 `ArchRules`, ArchUnit is just like English, so the rules are easy to understand.
- `fieldsInUtilClassesShouldBeImmutable`
- `fieldsInStatelessChecksShouldBeImmutable`
- `classesWithImmutableFieldsShouldBeStateless`
- `classesWithMutableFieldsShouldBeStateful`
-  Suppression list was added and populated.
=> Issue #12099: Add ArchUnit test to ensure fields in modules and utils are immutable, and modules are correctly annotated

azure-pipelines.yml
Noticed at https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=11277&view=results, azure is retiring 10.5 images and having rolling brownouts now.
=> Update macos image

.ci/StarterRuleSet-AllRulesByCategory.groovy.txt, .ci/pitest-survival-check-xml.groovy
=> Issue #12132: Fix ArrayIndexOutOfBoundsException in pitest-survival-check-xml.groovy

.ci/no-exception-test.sh, .ci/validation.sh
Appears to be left over when integrating `launch.groovy` into `diff.groovy` at https://github.com/checkstyle/checkstyle/commit/f0eb2638866e2718983b7f580d1b77de6496a105#diff-c0ec6ae84b678dd1c2f581efe7cf8ec0255cc01f4e1b4c9fc66069907ed0a0b9L18
`diff.groovy` right now always checks the Git's POM to get the version.
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L222
And passes through to the maven command.
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L632
So it appears this parameter is not necessary and possible could cause conflicts.
=> minor: remove unnecessary checkstyle versions to diff.groovy

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalInstantiationCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalInstantiationCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalinstantiation/InputIllegalInstantiationLang3.java, src/xdocs/config_coding.xml
Issue #3955
it is breaking compatibility .... will need review from all.
=> Issue #3955: corrected tokens so all are required

.ci/checker-framework-suppressions/checker-framework-formatter-suppressions.xml, .ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml, .ci/checker-framework-suppressions/checker-framework-regex-property-key-compiler-message-suppressions.xml, .ci/checker-framework-suppressions/checker-framework-signature-gui-units-init-suppressions.xml, .ci/pitest-suppressions/pitest-common-suppressions.xml, config/import-control.xml, config/suppressions.xml, pom.xml, src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/LocalizedMessage.java, src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/LocalizedMessageTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java
Identified at https://github.com/hcoles/pitest/issues/1081#issuecomment-1226105481
while looking at https://github.com/checkstyle/checkstyle/pull/12053
`java.util.ResourceBundle.getBundle` has its own cache. It's cache is in the form `CacheKey(baseName, locale, module, callerModule)`. So extra cache in our code for this looks like not required.
The double cache has been there since 2002. The commit, 7e083cf6cbbe2b1590b92bf3feae547e5f58d6ac, says it is a 8% performance improvement.
While looking into this, bug was identified and posted at https://github.com/checkstyle/checkstyle/issues/12101 .
`Utf8Control` was made public in 7c2f448ad61f66224168d197dfc6195e7b8d9409 for no reason than for tests and not production code.
`DefaultLoggerTest#testCountryIsValid` and …
=> Remove custom cache in Violation.java. It was extra cache for resource bundle cache for messages.

src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressWarningsFilter.xml, src/xdocs/config_filters.xml
Fixes typo in https://checkstyle.org/config_filters.html#SuppressWarningsFilter
`{@code SuppressWarnings}` -> `@SuppressWarnings`.
=> doc: fix formatting mistake in SuppressWarningsFilter

.ci/pitest-suppressions/pitest-whitespace-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadToCheckTrimFunctionInOptionProperty.java
Issue #12251: Resolve Pitest suppression for AbstractParenPadCheck
=> Issue #12251: Resolve Pitest suppression for AbstractParenPadCheck

.ci/pitest-suppressions/pitest-whitespace-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPadToCheckTrimFunctionInOptionProperty.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPadToCheckUppercaseFunctionInOptionProperty.java
Issue #12261: Resolve Pitest suppression for EmptyForIteratorPadCheck
killed two surviving mutation
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L44
and 
https://github.com/checkstyle/checkstyle/blob/ba8efc21659a66600a25ed662b62d1b1cb7611ea/.ci/pitest-suppressions/pitest-whitespace-suppressions.xml#L53
=> Issue #12261: Resolve Pitest suppression for EmptyForIteratorPadCheck

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleCompact.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleCompactNoArray.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleExpanded.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoParens.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithParens.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingCommaIgnore.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingCommaNever.java
This is with reference to #11214 
I have made the respective changes but is unable to wrap the violation text to the next line. It keeps showing error when ever I wrap the long violation line to the next line. 
```
[ERROR] testStyleCompactNoArray  Time elapsed: 0.008 s  <<< ERROR!
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Violation message should be specified on line 20 in C:\Users\shubh\OneDrive\Desktop\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\annotation\annotationusestyle\InputAnnotationUseStyleCompactNoArray.java
at com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheckTest.testStyleCompactNoArray(AnnotationUseStyleCheckTest.java:210)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Violation message …
```
=> Issue #11214: specified violation message for AnnotationUseStyleCheck

.ci/checker-framework-suppressions/checker-framework-index-suppressions.xml, .ci/checker-framework-suppressions/checker-framework-nullness-optional-interning-suppressions.xml, .ci/checker-framework-suppressions/checker-framework-signature-gui-units-init-suppressions.xml, .ci/pitest-suppressions/pitest-misc-suppressions.xml, .ci/pitest-suppressions/pitest-tree-walker-suppressions.xml, config/import-control.xml, config/pmd.xml, src/main/java/com/puppycrawl/tools/checkstyle/Checker.java, src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java, src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java, src/main/java/com/puppycrawl/tools/checkstyle/LocalizedMessage.java, src/main/java/com/puppycrawl/tools/checkstyle/Main.java, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/CheckerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java, src/test/java/com/puppycrawl/tools/checkstyle/LocalizedMessageTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java, src/test/java/com/puppycrawl/tools/checkstyle/api/ViolationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
Issue #12101
The issue is our exceptions use LocalizedMessage though it does not have access to the global locale. It is expecting to be supplied the locale, but we never provide it the overridden locale from the config.
As the class name implies, LocalizedMessage should **currently** be the central place for the locale storage. (This does not resolve #12104 but does proceed to better management). The locale does not need to be provided to `LocalizedMessage` in the constructor anymore as anyone using should use the global locale, **currently**.
The second commit converts a bunch of `Violation` uses to `LocalizedMessage`. The areas being used are not actual violations but just being used for locale messages. Violation and LocalizedMessage both use the global locale, so this is really a no …
=> Issue #12101: move global locale to localized message 

.ci/pitest-suppressions/pitest-whitespace-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java
Issue #12275: Resolve Pitest suppression for EmptyForInitializerPad-2
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/a85bd5c1897e158b6495850ba792bf4b/raw/37385b138ced4f80b43ccf865900a812500f4f42/config.xml
=> Issue #12275: Resolve Pitest suppression for EmptyForInitializerPad-2

.github/dependabot.yml
For example, saxon is listed as 10.1 but we are on 10.6 .
This file hasn't changed since it was added, so dependabot must be handling the ignores itself.
=> minor: remove outdated ignores from dependabot

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java, src/xdocs/config_whitespace.xml
This is with reference to the Issue: #7619 .
I have updated examples given in the following files:
1. src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
2. src/xdocs/config_whitespace.xml
After making the necessary changes, mvn clean verify passed without test failures.
=> Issue #7619: Updated doc for EmptyLineSeperator

.ci/StarterRuleSet-AllRulesByCategory.groovy.txt, .ci/checker-framework.groovy
Contents of this PR:
- Removed custom hashcode and equals method, now both of those methods are generated using `@EqualsAndHashCode`
- Resolved a few IDEA violations generated locally.
=> Pull #12312: Remove custom equals and hashCode method and correct compareTo method in checker-framework.groovy

.ci/pitest-suppressions/pitest-whitespace-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadForSynchronized.java
Issue #12282: Resolve Pitest suppression for ParenPad
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/e206f8b15b0d8c04e1d6b1fbded90dbe/raw/6b6a30c0a864caad500abed316e2e7a51d99c59b/config.xml
=> Issue #12282: Resolve Pitest suppression for ParenPad

.ci/checker-framework-suppressions/checker-formatter-suppressions.xml, .ci/checker-framework-suppressions/checker-index-suppressions.xml, .ci/checker-framework-suppressions/checker-lock-tainting-suppressions.xml, .ci/checker-framework-suppressions/checker-methods-resource-fenum-suppressions.xml, .ci/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml, .ci/checker-framework-suppressions/checker-purity-value-returns-suppressions.xml, .ci/checker-framework-suppressions/checker-regex-property-key-compiler-message-suppressions.xml, .ci/checker-framework-suppressions/checker-signature-gui-units-init-suppressions.xml, .ci/checker-framework.groovy
=> Issue #12311: checker-framework.groovy depends too much on name of repo

src/xdocs/config.xml, src/xdocs/writinglisteners.xml.vm
=> Issue #12228: Changes in the overview section applied

.ci/util.sh
identified from https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.ci/validation.sh#L20 when trying to run locally and running into issues,
````
sevntu.checkstyle/.ci-temp/eclipse-cs/ $ git status
HEAD detached at 10.0.0
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:  docs/partials/releases/5.0.0final/release_notes.html
modified:  docs/sitemap.xml
no changes added to commit (use "git add" and/or "git commit -a")
````
Even our checkout would not reset the repo and we assume we are getting a clean state of the repo we retrieve.
=> minor: ensure external repos are also cleaned and reset from previous

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheck.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPadDefaultConfig.java
Closes #12291 
Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/ebedd8493b5744621e68e25d3c3f5398958eeaf1/config_single.xml
Report (clean): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a33ccb6_2022154627/reports/diff/index.html
=> Issue #12291: fix bound condition in EmptyForInitializerPadCheck

src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java
Resolves false RedundantSuppression noticed at https://github.com/checkstyle/checkstyle/pull/12354.
=> minor: suppress false RedundantSupression

.circleci/config.yml
Requested at https://github.com/checkstyle/checkstyle/pull/12354#issuecomment-1298624070
>IDEA_VERSION
JAVA_VERSION
MAVEN_VERSION
Done
>print sha of the downloaded file
Downloaded file is not in the final image, and in fact it is piped directly to `tar`. In order to keep the size of the image as small as possible, we do not store this.
=> infra: add "Print versions" to 'run-inspections' job

.ci/pitest-suppressions/pitest-blocks-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyEnumConstantDef.java
Part of #12330 
mutation covered from #12330 is https://github.com/checkstyle/checkstyle/blob/aad6891485ab1ea6b5ecaedbb5bd5cc03539f2b0/.ci/pitest-suppressions/pitest-blocks-suppressions.xml#L12-L19
=> Issue #12330: Resolve Pitest for Block Profile-2

.ci/update-github-page.sh
Resolves #12181 
---
From curl docs:
> [--fail-with-body](https://curl.se/docs/manpage.html#--fail-with-body)
(HTTP) Return an error on server errors where the HTTP response code is 400 or greater). In normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This flag will still allow curl to output and save that content but also to return error 22. 
---
Failed run: https://github.com/stoyanK7/checkstyle/actions/runs/3444671922/jobs/5747521215
```
curl: (22) The requested URL returned error: 404
{
"message": "Not Found",
"documentation_url": "https://docs.github.com/rest/reference/repos#update-a-release"
}
Error: Process completed with exit code 22.
```
=> Issue #12181: Fail 'Publish GitHub page' when curl fails

.ci/jsoref-spellchecker/whitelist.words, .ci/travis.sh, .travis.yml
After thinking about random things late at night, and then seeing sevntu has a 2 gig cache file. Checkstyle seems to be around 600 megs.
https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/caches
https://app.travis-ci.com/github/checkstyle/checkstyle/caches
Command from https://www.howtogeek.com/howto/ubuntu/delete-files-older-than-x-days-on-linux .
This won't be perfect as we could removing dependencies that are still used but have not updated in this timeframe.
=> infra: added quarterly cache clean up (travis)

.ci/validation.sh, .semaphore/semaphore.yml, codeship-steps.yml, pom.xml
https://github.com/TestingResearchIllinois/NonDex/issues/175
https://github.com/TestingResearchIllinois/NonDex/compare/nondex-1.1.2...master (note, no tag for 2.1)
nondex 2.1 was released and should support Java 11.
=> infra: re-enable nondex and upgrade to 2.1

.ci/run-link-check-plugin.sh, config/checkstyle_non_main_files_suppressions.xml
fixes failure and adds suppression for https://github.com/checkstyle/checkstyle/actions/runs/3453488392/jobs/5764121711
Failure occurred in master after merge since link check runs only there.
=> infra: remove 'fail-with-body' option from link check

src/xdocs/cmdline.xml.vm
Fix to Issue #12393 : The closing anchor tag for the hyperlink was missing.
=> Issue#12393 : Added closing anchor tag

.circleci/config.yml
releasenotes-gen job is failing without github token, we have a PR to re-enable this job in another CI at https://github.com/checkstyle/checkstyle/pull/12401, but that PR may take some time. Better to disable this since it will constantly fail anyway in repo branches (master, dependabot, etc., not from forked PRs).
=> infra: remove releasenotes-gen from circleci

.ci/jsoref-spellchecker/whitelist.words, .ci/sonar_break_build.sh, .ci/validation.sh, .circleci/config.yml, .github/workflows/sonarqube.yml
For security reasons, we will migrate sonar to github actions. Also, I have copied the script from https://github.com/viesure/blog-sonar-build-breaker to our own repo, for several reasons:
1. External script could be modified by maintainer of https://github.com/viesure/blog-sonar-build-breaker to print our environment variables
2. External script does not use `set -e`, and thus will not fail build upon failure in script. 
Example: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/16061/workflows/95872086-a4e9-4812-9a41-0900ae1bdfcb/jobs/197395
It is better for us to maintain control over scripts running in our CI.
We need to add our sonar token to github env variables.
---------------------
update: looks like sonar script has been failing for a long time, while not failing …
=> infra: migrate sonar to github actions

.ci/releasenotes-gen.sh, .ci/sonar-wrapper.sh, .ci/sonar.sh, .ci/test-spelling-unknown-words.sh, .ci/travis.sh, .ci/util.sh, .ci/validation.sh, .travis.yml
Identified at https://github.com/checkstyle/checkstyle/pull/12391#issuecomment-1312514908,
Moves all sleep commands to travis so we don't have to add sleep to everything and everyone gets a chance for output.
I left sleep commands near "exit"s as I wasn't sure if travis would still execute the rest.
I also organized all sleep commands so they were similar in pattern to do a search and find.
=> minor: move sleep to main travis so all commands get chance to output

codeship-steps.yml
We do not need redundancy in nondex, build is failing in codeship on master branch now: https://app.codeship.com/projects/67b814a0-8fee-0133-9b59-02a170289b8c/builds/41483c48-ab4c-46ea-a410-46a750e6a5d0?component=step_parallel_.%2F.ci%2Fvalidation.sh_nondex
=> infra: remove nondex from codeship

src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileNameNoExtension
In test Input Files, Checks Modules and Properties are passed in comments at the top file and all these modules are added as child of TreeWalker.
But There is no way to configure the property of TreeWalker from Input Files Comments. So I added the function which will set the property of treeWalker.
For ref, #12386
=> Update Test Configuration To Support Adding TreeWalker Property

.ci/jsoref-spellchecker/exclude.pl, codeship-services.yml, codeship-steps.yml, codeship.encrypted, config/checkstyle_non_main_files_suppressions.xml
As releasenotes-gen only runs on master, we can migrate this task to codeship. Currently, this job is failing in CircleCi due to missing github token: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/16059/workflows/82c3e207-5f67-4958-84a0-c4428ea215c8/jobs/197310
=> infra: migrate releasenotes-gen to codeship

.ci/releasenotes-gen.sh, codeship-steps.yml
codeship does not like `if` command in yaml file, this PR moves it to release notes script (it should be there anyway to check for existence of token before proceeding). See https://app.codeship.com/projects/67b814a0-8fee-0133-9b59-02a170289b8c/builds/d1f69a08-b1da-46aa-a7f7-6780a76fc829?component=step_parallel_.%2F.ci%2Freleasenotes-gen.sh
=> infra: move token check into releasenotes-gen.sh

codeship-services.yml
Noticed at https://app.codeship.com/projects/67b814a0-8fee-0133-9b59-02a170289b8c/builds/6cdaaf52-f4fc-428d-b94e-0bfd445160bf?component=step_parallel_.%2F.ci%2Freleasenotes-gen.sh&log=8c83cc9d-c27e-4bf8-9808-411b9bb6274e_8, it looks like job is failing since image specified is based on jdk8
=> infra: update codeship image to latest jdk-11-groovy-git-mvn

codeship-services.yml, codeship-steps.yml, codeship.encrypted, config/checkstyle_non_main_files_suppressions.xml
Codeship is painful to deal with for a number of reasons (bad UI, etc.). We have moved release notes generation to github action at https://github.com/checkstyle/checkstyle/pull/12421, so we should clean up and remove it and related changes from codeship. We will keep `ls -la` running to make sure we keep resources available if we need them.
=> infra: mostly disable codeship

.ci/update-github-page.sh, .github/workflows/publish_releasenotes_outside.yml
Resolves #12182
---
`.ci/update-github-page.sh` makes this `PATCH` request:
https://github.com/checkstyle/checkstyle/blob/c2e84c5bd0a5ac9169df7c056be9f13233efd651/.ci/update-github-page.sh#L92
This corresponds to [Update a release - `PATCH /repos/{owner}/{repo}/releases/{release_id}`](https://docs.github.com/en/rest/releases/releases#update-a-release)
Checking the [Permissions required for GitHub Apps for `Releases`](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#releases), this one in particular requires `write` access for `contents`. Supported by this [StackOverflow answer](https://stackoverflow.com/a/69941765/9553927):
Without `permissions`: https://github.com/stoyanK7/checkstyle/actions/runs/3461934840/jobs/5780172729#step:3:179
With `permissions`: …
=> Issue #12182: Investigate why GITHUB token has no access to issues

.github/workflows/releasenotes-gen.yml, README.md
Moving release note generation to github actions, as codeship UI is not great and codeship requires a bunch of extra steps to check repo out, etc.
BUT main problem is that codeship UI isnot mobile browser friendly that make it impossible to use, but unfortunately for this job we need good support to let us read printed content.
This PR is on a repo branch so that we can test it before merging.
------------------------
Results of testing: https://github.com/checkstyle/checkstyle/actions/workflows/releasenotes-gen.yml
We can see that runs 4 and 5 failed from PRs/issues that did not have a label (as expected), and run 6 succeeded after I added the labels.
=> infra: move release note generation to github action

README.md
Leftovers from https://github.com/checkstyle/checkstyle/commit/87cdbdc8aa3743ae61eab68ccf96aa2495635a4b and other drone migration related tasks
Also:
```
➜  checkstyle git:(master) ✗ ag -Q "drone"
src/xdocs/releasenotes.xml
1868:            minor: fix drone build by excluding archives from line length check.
1892:            Use cache for maven dependencies to speed up drone io builds.
4246:            Test more project on drone.io.
README.md
14:[![][drone img]][drone]
182:[drone]:https://cloud.drone.io/checkstyle/checkstyle
183:[drone img]:https://cloud.drone.io/api/badges/checkstyle/checkstyle/status.svg
```
```
➜  checkstyle git:(remove-badge) ✗ ag -Q "drone"               
src/xdocs/releasenotes.xml
1868:            minor: fix drone build by excluding archives from line length check. …
```
=> minor: remove drone badge

.ci/sonar_break_build.sh, .ci/validation.sh, .circleci/config.yml
#12431 
Proof that analysis is uploading correctly: https://sonarcloud.io/summary/new_code?id=org.checkstyle%3Acheckstyle&pullRequest=12433
[Proof of failed build](https://app.circleci.com/pipelines/github/checkstyle/checkstyle/16220/workflows/776a6978-076a-4ee7-8ea0-3d45c271d3cb/jobs/203283) from commit https://github.com/checkstyle/checkstyle/pull/12433/commits/119a99d4ea83c13dce4f47e6d7290e10fcfd03db
Link to dashboard of failed build: https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=12433
=> Issue #12431: Re-enable sonar

src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
See https://sonarcloud.io/organizations/checkstyle/rules?open=java%3AS5778&rule_key=java%3AS5778 for details.
>When verifying that code raises a runtime exception, a good practice is to avoid having multiple method calls inside the tested code, to be explicit about which method call is expected to raise the exception.
=> minor: extract Set declaration

.ci/pitest-suppressions/pitest-whitespace-suppressions.xml, config/checkstyle_resources_suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestTrailingWhitespace.java
Issue #12430: Resolve Pitest suppression for SeparatorWrapCheck
Diff Regression config: https://gist.githubusercontent.com/arinmodi/6b46ea3817e1e421ee98eb01f1bed89d/raw/1185fc6ae40afee5804c8ef069c74c06a63cbaba/config.xml
=> Issue #12430: Resolve Pitest suppression for SeparatorWrapCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
See https://sonarcloud.io/project/issues?issues=AYFDh7epvqZP8r4qP3BS&open=AYFDh7epvqZP8r4qP3BS&id=org.checkstyle%3Acheckstyle for more details.
>The java.util.function package provides a large array of functional interface definitions for use in lambda expressions and method references. In general it is recommended to use the more specialised form to avoid auto-boxing. For instance IntFunction<Foo> should be preferred over Function<Integer, Foo>.
=> minor: refactor to use 'ToIntFunction' interface

.ci/pitest-suppressions/pitest-naming-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameWhitespaceInAccessModifierProperty.java
Referencing from #12326 
also related to #12341
=> Issue #12326: Resolve Pitest suppression for AccessModifierOption

.ci/jsoref-spellchecker/whitelist.words, .ci/update-github-page.sh
Resolves #12169 and in particular https://github.com/checkstyle/checkstyle/issues/12169#issuecomment-1239374997
---
[The JSON](https://github.com/checkstyle/checkstyle/actions/runs/3007875786/jobs/4830931730#step:3:193) had unescaped `"` characters:
We just swap them with single-quote `'` like with backticks.
=> Issue #12169: Fix failure to publish github release notes ' R: Publish GitHub Page'

.ci/copy-site-to-sourceforge.sh, .ci/jsoref-spellchecker/whitelist.words, .github/workflows/copy_site_to_sourceforge.yml
Resolves #12081
---
The job: https://github.com/stoyanK7/checkstyle/actions/runs/3488545560/jobs/5837520525
Even though it failed, the files got uploaded and are accessible at https://stoyank-checkstyle.sourceforge.io.
The job failed on the archiving part since (I suspect) there is some internal folder structure that I need to set up manually once before running the script for the first time. `htdocs-version`, `htdocs/version` folders and so on..
We introduce two new secrets:
- `SF_USER` - SourceForge username for login
- `SSH_KEY`(Probably better to name it `SF_SSH_KEY`) - Private SSH key to access SourceForge. Public one has to be placed here https://sourceforge.net/auth/shell_services
=> Issue #12081: Add Github action 'Copy site to sourceforge'

.ci/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestAssignment.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestDefault.java
Closes #12345
Diff Regression config: https://gist.githubusercontent.com/strkkk/26466254f89c32d8f1a6bd53b6f5b251/raw/e31682f867c2d357b605523c1a80cee50fab9c18/config_single.xml
=> Issue #12345: fix NoWhitespaceAfterCheck false positive

.ci/pr-description.sh, config/checkstyle_non_main_files_suppressions.xml
Noticed at https://github.com/checkstyle/checkstyle/actions/runs/3531403281/jobs/5924533074, check of PR description was silently failing.
```
0s
Run ./.ci/pr-description.sh
curl: option --fail-with-body: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Commit messages from github: ...
Issue number: 
PR validation succeeded.
```
=> infra: remove --fail-with-body from pr-description.sh

.ci/close-create-milestone.sh, .ci/creation-of-issue-in-other-repos.sh, .ci/releasenotes-gen-xdoc-push.sh, .ci/tweet-releasenotes.sh, .ci/update-github-milestone.sh, .ci/update-github-page.sh, .ci/upload-all-jar.sh, .ci/validation.sh, config/checkstyle_non_main_files_suppressions.xml
Resolves #12456 
---
I have left `sonar`, `drone-io`, `travis` and `release` untouched:
=> Issue #12456: Remove new curl parameter from all GitHub actions for release

config/pitest-suppressions/pitest-blocks-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestIfElseAlone.java
Issue #12441: Resolve Pitest suppression for RightCurlyCheck
Diff Regression config: https://gist.githubusercontent.com/arinmodi/3cf085f17de7e31a5089c43182f45eec/raw/37bb6fa0f32abfc98f35ebad85ec603fb89e665e/config2.xml
=> Issue #12441: Resolve Pitest suppression for RightCurlyCheck

config/checkstyle_non_main_files_checks.xml
Issue #12463
Copied a file over to CI and ran this on my local:
````
[INFO] --- maven-antrun-plugin:3.1.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 28/11/2022 09:36:15 PM
[INFO] [checkstyle] Running Checkstyle  on 1496 files
[INFO]      [echo] Checkstyle finished (checkstyle_checks.xml) : 28/11/2022 09:36:18 PM
[INFO]      [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 28/11/2022 09:36:15 PM
[INFO] [checkstyle] Running Checkstyle  on 3500 files
[ERROR] [checkstyle] [ERROR] M:\checkstyleWorkspaceEclipse\checkstyle\.ci\catalog.xml:1: CI folder should only contain executables files [RegexpOnFilename]
````
=> Issue #12463: adds enforcement of executables in ci folder

release.sh
(CI should be green to start release)
during release it is too late to run tests or any other validation.
=> infra: disable test during release phases to speed up execution 

.github/workflows/update_sources.yml
Resolves #12464
---
Without env variable: https://github.com/stoyanK7/checkstyle/actions/runs/3577041042/jobs/6015570073#step:4:7
With env variable: https://github.com/stoyanK7/checkstyle/actions/runs/3577075268/jobs/6015645427#step:4:8
=> Issue #12464: Fix 'R: Push Release Notes' failing

.github/workflows/update_sources.yml
Resolves #12479 
---
Without permissions: https://github.com/stoyanK7/checkstyle/actions/runs/3586321134/jobs/6035377211#step:5:11
With permissions: https://github.com/stoyanK7/checkstyle/actions/runs/3586454916/jobs/6035663797#step:5:1
=> Issue #12479: 'R: Push Release Notes' failing on push

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordsWithCheckFields.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordsWithCheckFieldsOverlap.java
=> Issue #11807: fixes exception on records and fields in RequireThis

.travis.yml
Similar to https://github.com/checkstyle/contribution/pull/700#event-7956954470, avoidance of travis package management will hopefully help to stabilize travis build
=> infra: avoid travis package management

src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/NoWhitespaceAfterCheck.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterSynchronized.java, src/xdocs/config_whitespace.xml
Closes #12486 
Diff Regression config: https://gist.githubusercontent.com/nrmancuso/8875948c95d7ad62310b0ecd72c527ff/raw/df0c55c7670d01c7db1ba09bc8219c96c67b85c9/config.xml
=> Issue #12486: NoWhitespaceAfter shouldn't check synchronized method

.ci/checker-framework.groovy
Resolves #12524 
Tested locally on windows as Checker Framework does not currently support windows properly, see https://github.com/checkstyle/checkstyle/pull/12366#issuecomment-1304441297 and the following comments.
=> Issue #12524: Replace backward slash with forward slash while creating CheckerFrameworkError object in checker-framework.groovy

.github/workflows/site.yml
Noticed at https://github.com/checkstyle/checkstyle/actions/runs/3794382250, site generation is failing from commands in `run` continuation block prefaced with `run:` (bad copy/paste on my part).
This was not caught since github actions do not use yml from the PR branch to run (forgot about this when "testing")
=> infra: fix site generation

config/import-control-test.xml
Issue https://github.com/checkstyle/checkstyle/issues/12100
Part of https://github.com/checkstyle/checkstyle/pull/12098
All usages of `@BeforeAll` were removed but forbidding the usage was pending, this PR completes that task.
=> supplemental: Forbid usage of @BeforeAll in tests

.github/workflows/bump_license_year.yml
Resolves #12572 
Source: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
Proof of working: https://github.com/Vyom-Yadav/actions-test/commit/8ae3f4490e16f3bbba5f252f96b03e15198e8122
=> Issue #12572: fix bump_license_year.yml not adding year to commit message

.github/workflows/releasenotes-gen.yml
Release Notes action was skipped on commit of version bump 
https://github.com/checkstyle/checkstyle/actions/workflows/releasenotes-gen.yml
same as: https://github.com/checkstyle/contribution/commit/6c1e4973f94f63fbd70c4fd749dcbe19e3b08cd1#diff-3352b8e68cb99ef1d26fdb226a4caf7e9e5b524dee8dda727210453eec3d9b0dR10
=> infra: allow trigger action manually after version bump

.ci/sonar_break_build.sh
Noticed at https://github.com/checkstyle/checkstyle/pull/12548#issuecomment-1368192527, how to diagnose sonar build failure is not obvious.
New failure message: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/16821/workflows/4e9432ae-aef9-4286-aa5f-9ebc0d522bde/jobs/225458/parallel-runs/0/steps/0-103
```
Verification of sonar gate status
Quality gate failed.
See sonar dashboard at 'https://sonarcloud.io/dashboard?id=org.checkstyle%3Acheckstyle&pullRequest=12566' for failures.
```
=> Improve sonar failure message

.ci/checker-framework.groovy
=> Issue #12522: Empty ErrorStream in checker-framework.groovy to prevent buffer exhaustion and external processes from blocking

.ci/travis.sh, .ci/validation.sh, .circleci/config.yml, .semaphore/semaphore.yml, .travis.yml, azure-pipelines.yml
Migrates most travis jobs to semaphore, travis has been failing for quite awhile now. We will keep "test and deploy" and snapshot deployment in travis on master branch until at least https://github.com/checkstyle/checkstyle/issues/12620
=> infra: migrate travis jobs to semaphore

.github/workflows/diff_report.yml
We have a failure to generate diff report when we use more than one parameter. See examples below.
Ok, we need to merge this to see results from `echo`.
My guess is that we are appending to GITHUB_OUTPUT in such a way as to cause issues when we later retrieve this information.
Diff Regression config: https://gist.githubusercontent.com/nrmancuso/51b18335d59bc81bb09370564e258f51/raw/5dbbab498fceb4b15f5395cebcf133f2d7a02ba4/config.xml
=> infra: fix indentation and add echo of output

.github/workflows/diff_report.yml
GITHUB_OUTPUT is a file, we need to `cat` it: https://github.com/checkstyle/checkstyle/actions/runs/3951129217/jobs/6764584414#:~:text=/home/runner/work,Set%20branch
=> minor: cat github output file in diff report generation

src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java
Issue #12667
As discussed at https://github.com/checkstyle/checkstyle/issues/12667#issuecomment-1397649608 .
I confirmed that test pass now in Git Bash on Windows.
=> Issue #12667: disables picocli's colors for tests

src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavaParserTest.java, src/test/java/com/puppycrawl/tools/checkstyle/JavadocPropertiesGeneratorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java, src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheckTest.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/utils/InlineTagUtilTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElementTest.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/MainFrameModelTest.java, src/test/java/com/puppycrawl/tools/checkstyle/gui/ParseTreeTablePresentationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsMobileWrapperTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsUrlTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/ElementNodeTest.java, src/test/java/com/puppycrawl/tools/checkstyle/xpath/RootNodeTest.java
The `isTrue` were starting to annoy me.
The same cannot be done with `isFalse`. For example there is no `doesNotStartWith`.
=> minor: replaces unncessary isTrue assertions with better ones

.ci/upload-all-jar.sh, .ci/validation.sh, .semaphore/semaphore.yml, pom.xml, release.sh, src/xdocs/cmdline.xml.vm
Supplemental for https://github.com/checkstyle/contribution/pull/747#discussion_r1064284794
> let's combine no-validation and assembly.
> 
> But assembly should skip tests jaring and assembly plugin. So all 2 parameters should be part of assembly profile.
test jars assemble required only during release process. -Passembly was purely a profile to make "-all" jar that is not maven concept of jars.
=> supplemental: changes to assembly profile for contribution#747

.ci/test-spelling-unknown-words.sh, .gitignore
All temp files should be moved to `.ci-temp` as that is our temporary working directory when doing CI commands. It makes it easier to manage these files if they are separated from long term files managed by the git repository.
=> minor: moves files generated by spellchecker to temp directory

.github/workflows/diff_report.yml
Noticed at https://github.com/checkstyle/checkstyle/actions/runs/4012370020:
`The workflow is not valid. .github/workflows/diff_report.yml (Line: 31, Col: 14): Concurrency group name cannot be empty`
diff report generation is now completely broken.
=> infra: fix concurrency block in diff report workflow

.ci/close-create-milestone.sh, .ci/upload-all-jar.sh, .github/workflows/new-milestone-and-issue-in-other-repo.yml, config/jsoref-spellchecker/whitelist.words
Resolves #12570
[Actions job](https://github.com/stoyanK7/checkstyle/actions/runs/4019211159/jobs/6905766728)
`Test milestone` was closed and `10.7.0` was created.
The asset was uploaded.
Issues were created.
=> Issue #12570: action 'R: Close/Create Milestone' is not working

.ci/close-create-milestone.sh, .ci/update-github-milestone.sh, .ci/upload-all-jar.sh
Resolves #12694
---
Adds `GITHUB_TOKEN` authorization header where it was missing. I checked all actions jobs and the `.sh` files they are calling.
---
The reason for [the main issue was different](https://github.com/checkstyle/checkstyle/issues/12694#issuecomment-1410750115) but I am adding the headers anyways to keep things consistent.
=> Issue #12694: Push 'all' jar action is not working and not failing execution

.semaphore/semaphore.yml
=> Issue 12705: remove .m2 for codenarc execution to make it more stable on download

pom.xml
Missed from https://github.com/checkstyle/checkstyle/pull/12710 as it seems versions-maven-plugin does not look to bump itself. Edit: It seems this is only reported by `display-plugin-updates`.
https://mvnrepository.com/artifact/org.codehaus.mojo/versions-maven-plugin
2.14.2 released on 12/24. *(Missed)*
2.14.0 released on 12/14. *(Missed)*
2.13.0 released on 10/23.
=> dependency: bump versions-maven-plugin to 2.14.2

config/pmd-main.xml, config/pmd-test.xml, config/pmd.xml, pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsUrlTest.java
Identified after noticing https://github.com/checkstyle/checkstyle/pull/12707#discussion_r1094701977 and running `mvn versions:display-dependency-updates`.
4-5 dependencies are out of date.
Based on below evidence, it looks like we stopped getting some updates around 10/25/2022 - 10/29/2022 .
`versions-maven-plugin` got an update around the same time.
https://mvnrepository.com/artifact/org.codehaus.mojo/versions-maven-plugin
2.13.0 release on 10/23.
It's latest release is 2.14.2 which was released on 12/24.
@romani ping
=> Multiple dependency bumps

.ci/validation.sh, .circleci/config.yml, pom.xml
Closes #12625
Link to example of failed run: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/16973/workflows/1abde372-b58a-4607-9bb5-a51560e8edf2/jobs/231413/parallel-runs/0/steps/0-102 
```
Append asterisks to the following pitest target classes in pom.xml:
com.puppycrawl.tools.checkstyle.AuditEventFormatter
com.puppycrawl.tools.checkstyle.XdocsPropertyType
com.puppycrawl.tools.checkstyle.PropertyType
com.puppycrawl.tools.checkstyle.FileStatefulCheck
com.puppycrawl.tools.checkstyle.ModuleFactory
com.puppycrawl.tools.checkstyle.PropertyResolver
com.puppycrawl.tools.checkstyle.StatelessCheck
com.puppycrawl.tools.checkstyle.TreeWalkerFilter
com.puppycrawl.tools.checkstyle.GlobalStatefulCheck
com.puppycrawl.tools.checkstyle.grammar.CommentListener
Exited with code exit status …
```
=> Issue #12625: validate wildcards on target classes

.ci/maven-release-perform.sh, .github/workflows/maven_release_perform.yml, config/jsoref-spellchecker/whitelist.words
Resolves #12079 
---
I cannot wrap my head around how any of this realease/deploy works and I am stuck. This is my progress until now. I feel like I'm a just doing trial and error hoping something works at this point.
Running
```
./.ci/maven-release-perform.sh 10.5.1
```
yields
```
[INFO] BUILD FAILURE
[INFO] Total time:  01:39 min
[INFO] Finished at: 2022-12-16T19:13:34+01:00
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy
(injected-nexus-deploy) on project checkstyle: Failed to deploy artifacts: Could not …
```
=> Issue #12079: Github action "Release perform"

.ci/checker-framework.groovy
=> Issue #12379: Checker false violation removals on other failures

.ci/pitest.sh
Resolves #12647
Proof of working: https://github.com/checkstyle/checkstyle/actions/runs/4036216927/jobs/6938663693
Log:
```
...
Enhanced functionality available at https://www.arcmutate.com/
[INFO] BUILD FAILURE
[INFO] Total time:  16:57 min
[INFO] Finished at: 2023-01-29T10:24:23Z
Error:  Failed to execute goal org.pitest:pitest-maven:1.9.9:mutationCoverage (default-cli) on project checkstyle: Mutation score of 96 is below threshold of 100 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal …
```
=> Issue #12647: ensure groovy script runs when pitest fails 

.github/workflows/bump-version-and-update-milestone.yml, .github/workflows/maven-prepare.yml, .github/workflows/maven-release-perform.yml, .github/workflows/new-milestone-and-issue-in-other-repo.yml, .github/workflows/publish-releasenotes-for-twitter.yml, .github/workflows/publish-releasenotes-outside.yml, .github/workflows/update-github-io.yml, .github/workflows/update-sources.yml, .github/workflows/upload-all-jar.yml
Part of #12720 
From https://github.com/checkstyle/checkstyle/pull/12741#discussion_r1106565550
> Is it possible to move such update on input usage in Separate PR, to let me merge it sooner and test in manual execution of each action in next release.
> It is huge milestone for us that release is fully in CI even there are few actions to run.
> 
> PR with workflow will take a bit more time to accept. I want it to has less changes to let me focus more details on actual workflow changes.
---
Reasoning: `inputs` context is accessible from both `workflow_dispatch` and `workflow_call`. We are going to use `workflow_call` to make the workflow reusable.
From: https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/
> 
> Workflows triggered by …
=> Issue #12720: Use input context instead of event context

config/checkstyle_checks.xml, config/checkstyle_resources_checks.xml
Changes all occurrences of `regexp.filepath.mismatch` to `regexp.filename.mismatch` on `RegexpOnFileNameCheck` checks.
Proof:
https://github.com/checkstyle/checkstyle/blob/e662258faf13c3abf343563c4daeb7edec96bc9d/src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java#L274
Before change:
```
[ERROR][checkstyle] [ERROR] .../src/main/java/com/puppycrawl/tools/checkstyle/test.xml:1: File not match folder pattern '[\\/]src[\\/]\w+[\\/]java[\\/]' and file pattern '\.java$'. [javaFileLocation]
```
After change:
```
[ERROR] [checkstyle] [ERROR] .../src/main/java/com/puppycrawl/tools/checkstyle/test.xml:1: Only java files should be located in the 'src/*/java' folders. [javaFileLocation]
```
~I'm pretty sure I noticed this typo in other repositories as well. I will …
=> Pull #12748: Fix RegexpOnFileNameCheck message keys

src/main/java/com/puppycrawl/tools/checkstyle/api/AuditEvent.java, src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java, src/test/java/com/puppycrawl/tools/checkstyle/api/AuditEventTest.java
Issue #12681 
We have comments for this class that even say we do no serialize it.
=> Issue #12681: removes serializable from violation and audit event

.ci/maven-release-perform.sh, .ci/prepare-settings.sh, config/jsoref-spellchecker/whitelist.words, pom.xml
Part of #12726 
---
Moves `maven-gpg-plugin` configuration to its own profile as requested in: https://github.com/checkstyle/checkstyle/issues/12762#issuecomment-1439393566
> My upgrade to 2.x will be not easy. Can we activate this plugin config by extra profile? To use it in environment with 2.x version, and work as before if not defined.
By default, the mode is used because GitHub runners use gpg v2.1+, but maintainer can remove it if they do release from local since not everybody can upgrade from v1.4 to v2.1 easily.
Job using new profile: https://github.com/stoyanK7/checkstyle/actions/runs/4246243945/jobs/7382806834
Expected fail without new profile: https://github.com/stoyanK7/checkstyle/actions/runs/4246287057/jobs/7382904938#step:6:1802
```
[INFO] --- maven-gpg-plugin:1.1:sign …
```
=> Issue #12726: Create new profile for gpg version 2 

.ci/util.sh
From https://github.com/checkstyle/checkstyle/issues/12762#issuecomment-1439990111
> new problem is [here](https://github.com/checkstyle/checkstyle/actions/runs/4242897227/jobs/7374970451#step:6:1806):
Turns out that GitHub secrets are not set and environment variables are created with empty string as value but `checkForVariable` does not catch that:
https://github.com/checkstyle/checkstyle/actions/runs/4242897227/jobs/7374970451#step:5:4
```
 stoyan @  zenbook:  ~/open-source/checkstyle                                                                                                                                       master
$ ./.ci/creation-of-issue-in-other-repos.sh …
```
=> Issue #12762: Assert variable is not empty in checkForVariable

.github/workflows/copy-site-to-sourceforge.yml
Part of #12720
The purpose of this PR is to divide #12741 into smaller chunks
All workflows use 
```yml
on:
workflow_dispatch:
inputs:
version:
```
apart from the file in this PR.
=> Issue #12720: Keep workflows inputs version consistent

src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
Resolves #12765
I identified only 2 types release commit messages:
- `[maven-release-plugin] prepare for next development iteration`
- `[maven-release-plugin] prepare release checkstyle-10.8.0`
Proof that it works. First I checkout to faulty commit and run test so it fails. Then I apply this commit on top and run test again:
[Screencast from 23-02-23 22:18:54.webm](https://user-images.githubusercontent.com/23459549/221034936-20b3995a-f985-45d6-8975-c9648deba270.webm)
=> Issue #12765: CommitValidationTest should ignore the release process

.ci/update-github-page.sh, config/jsoref-spellchecker/whitelist.words
Part of #12720 
The purpose of this PR is to divide #12741 into smaller chunks
---
> Please explain why this shell script is required.
I was under impression that we did not miss any steps from release process.
Answer(same as https://github.com/checkstyle/checkstyle/pull/12741#discussion_r1116005992): 
The purpose of this script is to create the release on GitHub. Nowhere in the release process are we doing that:
After it is created, `R: Close/Create Milestone, Upload '-all' jar, Create issues` and `R: Publish GitHub Page` search for that release by tag `checkstyle-<release target version>`
https://github.com/checkstyle/checkstyle/blob/fb9ff40ef7679342afcc6dc62cd059255c673dbb/.ci/update-github-page.sh#L36-L42
https://github.com/checkstyle/checkstyle/blob/fb9ff40ef7679342afcc6dc62cd059255c6 …
=> Issue #12720: Create release in update github page script 

.github/workflows/bump-version-and-update-milestone.yml, .github/workflows/copy-site-to-sourceforge.yml
All descriptions use `Target Version without (-SNAPSHOT)` except those two files.
=> Pull #12776: Keep workflow input descriptions consistent

.github/workflows/release.yml
`new-milestone-and-issue-in-other-repo` uses `secrets` context. When called from caller workflow, it needs to inherit that context. We do that with most other jobs in `release.yml` but I forgot this one. My bad.
https://github.com/checkstyle/checkstyle/blob/e00da2f769452ca4d01e05b94d162210e9d854a0/.github/workflows/new-milestone-and-issue-in-other-repo.yml#L60-L64
Noticed in:
https://github.com/stoyanK7/checkstyle/actions/runs/4326216948/jobs/7553449274#step:6:5
```
./.ci/creation-of-issue-in-other-repos.sh 10.8.1
shell: /usr/bin/bash -e {0}
env:
GITHUB_TOKEN: 
Error: Set not empty value to GITHUB_TOKEN environment variable
Error: Process completed with exit code 1.
```
Success run with applied fix:
https://github.com/stoyanK7/checkstyle/actions/runs/4326378052/jobs/7553782567#step:6:5 …
=> Pull #12796: Add forgotten secret inherit in release

pom.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderNonConstant.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderTextBlocks.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder4.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder5.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder6.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder7.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderWithAndWithoutCheckSuffixDifferentCases.java
Issue #11446
SuppressWarningsHolder is Annotation check. [documentation](https://checkstyle.org/config_annotation.html#SuppressWarningsHolder)
I don't know how to replace the configs in methods `testAll()`, `testSuppressWarningsTextBlocks()`, `testWithAndWithoutCheckSuffixDifferentCases()` with inlined comment configs. Thanks.
=> Issue #11446: Updated SuppressWarningsHolderTest to use verifyWithInlineConfigParser method

pom.xml
Bumps Error Prone from 2.15.0 to 2.18.0.
Suggested commit message:
```
dependency: bump Error Prone 2.15.0 -> 2.18.0
See:
- https://github.com/google/error-prone/releases/tag/v2.16
- https://github.com/google/error-prone/releases/tag/v2.17.0
- https://github.com/google/error-prone/releases/tag/v2.18.0
- https://github.com/google/error-prone/compare/v2.15.0...v2.18.0
```
I'm not sure why Dependabot didn't open PRs for this dependency, but it would be nice to upgrade Error Prone.
=> dependency: bump Error Prone 2.15.0 -> 2.18.0

.github/workflows/new-milestone-and-issue-in-other-repo.yml
Removes execution of `upload-all-jar.sh` from `new-milestone-and-issue-in-other-repo.yml`. The workflow was doing too much and the upload of `-jar` is an important part of the release process. We already have a separate workflow for uploading all jar:
https://github.com/checkstyle/checkstyle/blob/master/.github/workflows/upload-all-jar.yml
After merging PR, https://github.com/checkstyle/checkstyle/wiki/Semi-automated-release has to be updated.
=> Pull #12793: Remove execution of upload -all jar from new-milestone-and-issue-in-other-repo

.github/workflows/set-milestone-on-referenced-issue.yml
Switches to `PAT` secret in `.github/workflows/set-milestone-on-referenced-issue.yml`.
From https://github.com/checkstyle/checkstyle/issues/12497#issuecomment-1455018698:
`GITHUB_TOKEN` does not receive write permissions for some reason.
Switching to `PAT` as suggested in https://github.com/checkstyle/checkstyle/issues/12497#issuecomment-1455130026
> as we have special logic in action `${{ github.event.pull_request.merged == true }}` that limits execution a lot, and content is trusty in this case. We should use PAT.
=> Pull #12799: Switch to PAT secret in set-milestone workflow

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java, src/xdocs/config_annotation.xml
Closes #7571
**The default value properties**
Web Page:
CLI:
```
naotokuwayama@NaotonoMacBook-Air test % cat config.xml
<module name="AnnotationUseStyle"/>
</module>
</module>
naotokuwayama@NaotonoMacBook-Air test % cat Test.java 
@SuppressWarnings("unchecked") // OK
@Deprecated // OK
@SomeArrays({"unchecked","unused"}) // OK
public class TestOne
{
}
@SuppressWarnings(value={"unchecked"}) // Violation - parameter 'value' shouldn't be used
@Deprecated() // Violation - cannot have a closing parenthesis
@SomeArrays(value={"unchecked","unused",}) // Violation - cannot have a trailing array …
```
=> Issue #7571: Update doc for AnnotationUseStyle

src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java, src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTypeCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeRecordComponents2.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeRecords.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeBadTag.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeInterfaceMemberScopeIsPublic.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeJavadoc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeJavadoc_1.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeJavadoc_2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeJavadoc_3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeNoJavadoc.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeNoJavadoc_1.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeNoJavadoc_2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeScopeInnerClasses.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTestTrimProperty.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTypeParamsTags.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTypeParamsTags_1.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeUnusedParamInJavadocForClass.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeWhitespace.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeWhitespace_1.java
Issue: #11214
I finished adding violation messages except for 2 parts.
The first part I have a trouble is this file.
`src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeJavadoc_2.java
`
In this file, I need to put `\$Revision.*\$` as a version format and I could not figure out how to do the escaping for special regex characters. I tried below patterns, but it did not work. Could you guide me how to fix it?
Things I tried
```
\\$Revision.*\\$
\\$Revision\.*\\$
\\$Revision.\*\\$
\\$Revision\.\*\\$
```
The second part I have a trouble is **25th** line of this file. 
`src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctype/InputJavadocTypeTypeParamsTags_1.java`
`public class InputJavadocTypeTypeParamsTags_1<A,B1,C456 extends …
=> Issue #11214: Add violation messages in JavadocTypeCheck

src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java, src/xdocs/config_annotation.xml
Issue: #7575 
Add two code examples  to the doc of SuppressWarnings.
`mvn clean verify` passed.
Web Page:
CLI:
First Example:
```xml
$ type config.xml
<module name="SuppressWarnings"/>
</module>
</module>
$ type Test.java
@SuppressWarnings("") // violation, empty strings or all whitespace are not allowed
class Test{
@SuppressWarnings(" ") // violation
private int num = 9;
@SuppressWarnings("unused") // ok
void foo1(){
}
@SuppressWarnings(true?"unused":"") // violation, does not consider conditionals
void foo2(){
}
}
$ java -jar checkstyle-10.8.0-all.jar -c config.xml Test.java
Starting …
```
=> Issue #7575: update doc for SuppressWarnings

.ci/set-milestone-on-referenced-issue.sh
Resolves https://github.com/checkstyle/checkstyle/issues/12497#issuecomment-1462092794
> This still seems to be broken.
https://github.com/checkstyle/checkstyle/actions/runs/4369202639/jobs/7642723623#step:3:46
> Please review and confirm.
Success job run: https://github.com/stoyanK7/checkstyle/actions/runs/4393492340/jobs/7693921915
=> Pull #12821: Make grep always return exit code 0 in set-milestone

.github/workflows/checker-framework.yml, .github/workflows/error-prone.yml, .github/workflows/no-exception-workflow.yml, .github/workflows/no-old-refs.yml, .github/workflows/pitest.yml, .github/workflows/releasenotes-gen.yml, .github/workflows/run-link-check.yml, .github/workflows/set-milestone-on-referenced-issue.yml, .github/workflows/shellcheck.yml
Resolves #12824
From [Example: Only run job for specific repository](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository)
codeql workflow already had such condition too:
https://github.com/checkstyle/checkstyle/blob/fd31119f2acdf8072e4205b6dd2abf5f118d4dd6/.github/workflows/codeql-analysis.yml#L23
Success commit with all skipped jobs: https://github.com/stoyanK7/checkstyle/commit/ff7b592585a695e20a693471e06a7b309e4bc6a9
=> Issue #12824: Add conditional to run on:push workflows only in checkstyle repository

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml, src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java, src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java, src/test/java/com/puppycrawl/tools/checkstyle/JavaAstVisitorTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java
Consider the Javadoc of `Collectors#toSet`:
> Returns a Collector that accumulates the input elements into a new Set. There are no guarantees on the type, mutability, serializability, or thread-safety of the Set returned; if more control over the returned Set is required, use `toCollection(Supplier)`. 
The occurrences that do need a guarantee on mutability are updated to use the `toCollection(Supplier)` collector. There is also a similar `toList` occurrence that is fixed.
Our custom Error Prone check, [CollectorMutability](https://error-prone.picnic.tech/bugpatterns/CollectorMutability/), that we have in [Error Prone Support](https://github.com/picnicSupermarket/error-prone-support/) identified these occurrences.
=> Pull #12777: emphasize mutability of collectors

src/test/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolderTest.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolderAlias2.java
supplemental: test cases added
While working on https://github.com/checkstyle/checkstyle/issues/11641 I noticed that I don't found test cases which use alias list property
=> supplemental: test cases added

.ci/idea-inspection.sh
Related to https://github.com/checkstyle/checkstyle/pull/12835#issuecomment-1468275604, we need to make failure message and location of results more obvious.
Link to failure: https://app.circleci.com/pipelines/github/checkstyle/checkstyle/17709/workflows/0cdbc001-5bf5-4dd3-886a-5d7eb39f4933/jobs/259008?invite=true#step-103-100
=> minor: make inspections failure results more obvious

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionModifierOrderTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/modifierorder/SuppressionXpathRegressionModifierOrderAnnotation.java, src/it/resources/org/checkstyle/suppressionxpathfilter/modifierorder/SuppressionXpathRegressionModifierOrderMethod.java, src/it/resources/org/checkstyle/suppressionxpathfilter/modifierorder/SuppressionXpathRegressionModifierOrderVariable.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue #6207
Add three XPath regression tests for `ModifierOrder` check.
Documentation：`https://checkstyle.sourceforge.io/config_modifier.html#ModifierOrder`.
=> Issue #6207: Add xpath regression test for ModifierOrder

.ci/releasenotes-gen.sh, .ci/validation.sh, .shellcheckrc
Related to #11637.
Doc link: https://www.shellcheck.net/wiki/SC2016
Also important: https://www.shellcheck.net/wiki/SC2154
=> Issue #11637: Resolve shellcheck SC2016

config/checker-framework-suppressions/checker-nullness-optional-interning-suppressions.xml, config/checkstyle-checks.xml, src/it/java/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/RightCurlyTest.java, src/it/resources/com/google/checkstyle/test/chapter4formatting/rule412nonemptyblocks/InputRightCurlySwitchCase.java, src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheck.java, src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/RightCurlyCheck.xml, src/main/resources/google_checks.xml, src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyCheckTest.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression2.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression3.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression4.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression5.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression6.java, src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchExpression7.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchCase.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchCase2.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchCase3.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchCase4.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestSwitchCase5.java, src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly/InputRightCurlyTestWithComment.java, src/xdocs/config_blocks.xml
Issue #9994: LITERAL_SWITCH token support in RightCurlyCheck
Diff Regression config: https://gist.githubusercontent.com/Kevin222004/75ac442a047d7fe25bedb544f9acd754/raw/52982ec6530ca6a4bfb5d24054bf816649cbe4fd/config.xml 
Diff Regression patch config: https://gist.githubusercontent.com/Kevin222004/7049aace77660fb0f0ac515ee7996c83/raw/1ef1a12723d35019f756bb0b11ed855e1d86ca92/patch_config.xml
=> Issue #9994: LITERAL_SWITCH token support in RightCurlyCheck

.shellcheckrc
Related to #11637.
https://www.shellcheck.net/wiki/SC2002
Additional info found at https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat
=> Issue #11637: Resolve shellcheck SC2002

.github/workflows/release-publish-releasenotes-twitter.yml
We keep `run` key always at last spot. For example,
https://github.com/checkstyle/checkstyle/blob/665f58f178e282e5565b5782ab1b33237d32f547/.github/workflows/release-maven-perform.yml#L38-L54
https://github.com/checkstyle/checkstyle/blob/665f58f178e282e5565b5782ab1b33237d32f547/.github/workflows/release-update-github-page.yml#L41-L45
=> minor: move run key at last spot

.ci/no-old-refs.sh, .ci/pr-description.sh, .ci/release-close-create-milestone.sh, .ci/release-create-issues-in-other-repos.sh, .ci/release-publish-releasenotes-twitter.sh, .ci/release-update-github-page.sh, .ci/release-upload-all-jar.sh, .ci/releasenotes-gen-xdoc-push.sh, .ci/run-link-check-plugin.sh, .ci/set-milestone-on-referenced-issue.sh, .ci/test-spelling-unknown-words.sh, .ci/update-github-milestone.sh, .github/workflows/check-pr-description.yml, .github/workflows/no-old-refs.yml, .github/workflows/release-new-milestone-and-issues-in-other-repos.yml, .github/workflows/release-publish-releasenotes-twitter.yml, .github/workflows/release-update-github-page.yml, .github/workflows/release-upload-all-jar.yml, .github/workflows/releasenotes-gen.yml, .github/workflows/run-link-check.yml, .github/workflows/set-milestone-on-referenced-issue.yml, azure-pipelines.yml, config/checkstyle-non-main-files-suppressions.xml
Resolves #12451
---
Proof that `--fail-with-body` is now supported. It was released in `7.76.0`:
- Run: https://github.com/stoyanK7/checkstyle/actions/runs/4449397732/jobs/7813529479#step:3:6
```
curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) ...
```
- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#installed-apt-packages
=> Issue #12451: Restore curl --fail-with-body

.github/workflows/release.yml
Resolves twitter failure in release run: https://github.com/checkstyle/checkstyle/actions/runs/4438465653
Twitter job: https://github.com/checkstyle/checkstyle/actions/runs/4438465653/jobs/7790124616#step:4:124
```
TARGET_RELEASE_INDEX=
PREVIOUS_RELEASE_INDEX=1
```
Release on my fork: https://github.com/stoyanK7/checkstyle/actions/runs/4449215620
Twitter job : https://github.com/stoyanK7/checkstyle/actions/runs/4449215620/jobs/7813174923#step:4:125
```
TARGET_RELEASE_INDEX=0
PREVIOUS_RELEASE_INDEX=1
```
Twitter releasenotes job should be dependent on `update-github-page` because it expects the release to be there
https://github.com/checkstyle/checkstyle/blob/b2e5cb20d2f1b3aa0273579b05651404aa0234de/.ci/release-publish-releasenotes-twitter.sh#L32-L40
---
What happened in the fail run was …
=> Pull #12857: Make twitter-releasenotes job depend on update-github-page

src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java, src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java/JavaLanguageParser.g4
Closes #12809 
-------------------------
Reports:
AST regression test report:
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/antlr-report/index.html
- Difference is in stack trace of non-compilable files only
Check regression reports:
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part2-report/index.html
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part4-report/index.html
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/sevntu-check-regression_part_1-report/index.html
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part6-report/index.html
https://nrmancuso.github.io/reports/issue-12809/2023-03-18-T-00-03-28/part3-report/index.html …
=> Issue #12809: Improve performance of lambda processing

.github/workflows/release-new-milestone-and-issues-in-other-repos.yml
Resolves failure in release `10.9.2` https://github.com/checkstyle/checkstyle/actions/runs/4456286742/jobs/7826685717
`new-milestone-and-issues-in-other-repos` [failed by trying to create milestone `10.9.2`](https://github.com/checkstyle/checkstyle/actions/runs/4456286742/jobs/7826685717#step:5:112):
```
"resource": "Milestone",
"code": "already_exists",
"field": "title"
```
It is supposed to get the new release number from pom. `10.9.3` in this case:
https://github.com/checkstyle/checkstyle/blob/c5e0f6fda7a48e38b9fbf45aa72f26a0b61b4cec/.ci/release-close-create-milestone.sh#L19-L22
The problem comes from `actions/checkout`. [It did not checkout to latest commit but rather to commit before release happened so the action pulled `10.9.2` from pom instead of …
=> Pull #12866: Ensure new-milestone-and-issues-in-other-repos always pulls latest commit

config/pitest-suppressions/pitest-api-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilterSetTest.java
Related to #12877.
Surviving mutation has been killed.
=> Issue #12878: Resolve pitest suppression for BeforeExecutionFileFilterSet

config/pitest-suppressions/pitest-api-suppressions.xml, src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java
Related to #12887 
Surviving mutation has been killed. 
Pure JUnit test used here. reason mentioned in the testing suite.
=> Issue #12887: Kill surviving mutation in FilterSet.java

src/xdocs/cmdline.xml.vm
issue detected while helping at https://github.com/checkstyle/checkstyle/pull/12870
existing doc is incorrect as after `\` should be nothing, as it is line end wrapper symbol in linux.
=> doc: describe in cli doc that folder can be used

.ci/release-close-create-milestone.sh, .ci/release-create-issues-in-other-repos.sh, .ci/release-maven-perform.sh, .ci/release-publish-releasenotes-twitter.sh, .ci/release-update-github-page.sh, .ci/release-upload-all-jar.sh, .github/workflows/release-maven-perform.yml, .github/workflows/release-new-milestone-and-issues-in-other-repos.yml, .github/workflows/release-publish-releasenotes-twitter.yml, .github/workflows/release-update-github-io.yml, .github/workflows/release-update-github-page.yml, .github/workflows/release-upload-all-jar.yml
Resolves #12840 
---
Workflow run: https://github.com/stoyanK7/checkstyle/actions/runs/4520382682
The run fails, but that is because I do not have Twitter credentials. I had to manually point to my Sourceforge project, but that is not tied with GitHub so nothing can be done there.
What I noticed is that we can maybe make `release-maven-perform` have a different profile (https://github.com/stoyanK7/checkstyle/commit/08f79b22ba7c8f381be22b968ca01b3409ba272b) to deploy to local if `$REPOSITORY_OWNER` is not `checkstyle`. That way anyone can run/debug the whole release process on their fork. This is a separate issue from this one though.
=> Issue #12840: Add repository owner environment variable in release process

.ci/set-milestone-on-referenced-issue.sh, README.md
`set-milestone-on-referenced-issue` "failed" silently because there was no milestone created during release and it does not check for that. The milestone for `10.9.3` was missing for a few days.
https://github.com/checkstyle/checkstyle/actions/runs/4507589937/jobs/7935502024#step:3:53
```
Fetching latest milestone.
MILESTONE_NUMBER=null
MILESTONE_TITLE=null
Setting milestone null to issue #12898.
```
---
This PR adds a check to ensure failure if no milestone is found and also introduces a badge in the README. This way somebody can notice if milestone is missing.
=> Pull #12909: Fail set-milestone if no milestone is found

src/main/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheck.java, src/xdocs/config_design.xml
[x] Updated doc starts with default config and example, followed by properties and their examples
[x] Passed that command `mvn clean verify` pass without violations
[x] Screenshots of how website looks like are attached below
[x] CLI results of different examples are attached below
```terminal
(base) a9527@9527deMacBook-Pro java % javac Foo.java
(base) a9527@9527deMacBook-Pro java % cat config.xml
<module name="DesignForExtension"/>
</module>
</module>
(base) a9527@9527deMacBook-Pro java % cat Foo.java  
public abstract class Foo {
private int bar;
public int method1() {return 2;}
public …
```
=> Issue #7608: Update doc for DesignForExtension

.ci/generate-extra-site-links.sh, .github/workflows/site.yml, config/jsoref-spellchecker/whitelist.words
Resolves #12853
Actions job: https://github.com/stoyanK7/checkstyle/actions/runs/4552768971/jobs/8028554421#step:3:19
Comment: https://github.com/stoyanK7/checkstyle/pull/62#issuecomment-1488315182
---
The script is flexible enough to detect that multiple xdoc files were changed.
The script picks the earliest line that has been changed in the xdoc file. Let's say that lines 25 to 30 have been changed and lines 89 to 100. The script would pick line 25 and  start from it up (24, 23, 22, 21...) until it finds a row with an `id=".*"`(a (sub)section). Then it extracts the id and creates the link based on the name of the changed xdoc and the id.
Cases covered:
- New xdoc created (it would generate a link with `#` at the end which is valid)
- First line changed (there is no id above it so it …
=> Issue #12853: Generate site workflow should provide more specific links

src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionParameterNameTest.java, src/it/resources/org/checkstyle/suppressionxpathfilter/parametername/SuppressionXpathRegressionParameterNameAccessModifier.java, src/it/resources/org/checkstyle/suppressionxpathfilter/parametername/SuppressionXpathRegressionParameterNameDefaultPattern.java, src/it/resources/org/checkstyle/suppressionxpathfilter/parametername/SuppressionXpathRegressionParameterNameDifferentPattern.java, src/it/resources/org/checkstyle/suppressionxpathfilter/parametername/SuppressionXpathRegressionParameterNameIgnoreOverridden.java, src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Issue: https://github.com/checkstyle/checkstyle/issues/6207
This PR adds XPath regression test for suppression filter on [ParameterName](https://checkstyle.org/config_naming.html#ParameterName) check.
=> Issue #6207: Add xpath regression test for ParameterName

.github/workflows/site.yml
Resolves https://github.com/checkstyle/checkstyle/issues/12853#issuecomment-1490493226
> The workflow uses this group
>`group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}`
>
>But this workflow context does not have `github.event.pull_request.number`, rather `github.event.issue.number` so it falls back to `github.ref`.
Print of new concurrency group:
https://github.com/stoyanK7/checkstyle/actions/runs/4578224927/jobs/8084568564#step:4:8
```
Site-62
```
Old one was `Site-refs/heads/master`.
=> Pull #12942: Fix concurrency group for site action

.ci/generate-extra-site-links.sh
Resolves issues found in https://github.com/checkstyle/checkstyle/pull/12937#issuecomment-1490596614
Adds 3 to variable `EARLIEST_CHANGE_LINE_NUMBER` to compensate for the diff context:
We expect `http://checkstyle-docs.org/asda123/sun_style.html#Sun_Suppressions`
Local run:
```
__________________________________________________________________________________________________________________________________________________
 stoyan @  zenbook:  ~/open-source/checkstyle                                                                       pull/12940-fix-extra-links
$ git log -1
commit c8e96ab989a5e2e57ebccfba266c09b6d02ca3af (HEAD -> pull/12940-fix-extra-links, origin/pull/12940-fix-extra-links)
Author: stoyanK7 <stoyank127@gmail.com>
Date:   Fri Mar 31 19:43:56 2023 +0200
Pull #12940: …
```
=> Pull #12940: Add 3 to earliest change variable to compensate for diff context

.github/workflows/actionlint.yml, .github/workflows/release-new-milestone-and-issues-in-other-repos.yml, .github/workflows/release-publish-releasenotes-twitter.yml, .github/workflows/release-update-github-io.yml, .github/workflows/release-update-github-page.yml, .github/workflows/release-upload-all-jar.yml, .github/workflows/release.yml, .github/workflows/site.yml
Resolves #12678
https://github.com/checkstyle/checkstyle/issues/12678#issuecomment-1488545090
---
The following errors were present:
https://github.com/stoyanK7/checkstyle/actions/runs/4553573127/jobs/8030294702#step:4:6
```
.github/workflows/release-new-milestone-and-issues-in-other-repos.yml:27:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-publish-releasenotes-twitter.yml:23:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-update-github-io.yml:23:92: property "concurrency-group" is not defined in object type {version: any} [expression]
.github/workflows/release-update-github-page.yml:23:92: property "concurrency-group" is not defined in object type …
```
=> Issue #12678: Re-enable action lint

.github/workflows/diff-report.yml
Resolves #12794
Multiline strings should be handled differently. Taken from GitHub actions documentation: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string. We already applied the same solution in `site` workflow.
Before:
https://github.com/stoyanK7/checkstyle/pull/62#issuecomment-1493068289
Now:
https://github.com/stoyanK7/checkstyle/pull/62#issuecomment-1493073677
=> Issue #12794: Diff-Report action does not post link to report in GitHub comment
