- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundRecordsAllowEmptyTypes.java
Issue #8528: Records Support Check update for WhitespaceAroundCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/f7ecd2a87a5640d64af226ed3ae9ee7d/raw/4e5b8db7d29e9cab21ce0d3781182fe57d962654/whitespacearound.xml
> Issue #8528: Records Support Check update for WhitespaceAroundCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsRecords.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
Issue #8462:  Records Support Check update for CovariantEqualsCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/cf669c00a1f79c51c7c02f3d67b3faae/raw/0a4e8939e2ca5b6ff648e3be5a0979ffd1182607/covariantequals.xml
> Issue #8462:  Records Support Check update for CovariantEqualsCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityRecords.java
Issue #8506: Records Support check update for NPathComplexityCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/7fa5a2abc278d744263c7011b3ff9826/raw/45d12d3398a05aff0046d170c14c3a8d4ac5a4ef/NPathComplexityCheck.xml
> Issue #8506: Records Support check update for NPathComplexityCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberIgnoreFieldDeclarationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/magicnumber/InputMagicNumberRecordsDefault.java
- src/xdocs/config_coding.xml
#8469: Records Support Check update for MagicNumberCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/3f0f3a5861e24078f5841af67df17d7d/raw/bcac82e66915786c33820d0043aa9595ece7eb04/MagicNumberCheck.xml
> Issue #8469: Records Support Check update for MagicNumberCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java
- src/xdocs/config_whitespace.xml
Issue #8525: Records Support Check update for MethodParamPadCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/4d8b08c174a597b6173a8ef08205fc53/raw/2b6d9f2983905715d4ec0f9cc8363ab6d99aa319/methodparampad.xml
> Issue #8525: Records Support Check update for MethodParamPadCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordAsTopLevel.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordDefault.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordsAndCompactCtors.java
- src/xdocs/config_coding.xml
Issue #8473: Records Support check update for RequireThisCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/c68d6dc8f36ee2668649b7ce629a6fdb/raw/208d9609dc79c8532f27ba03444cd3f73379e7b7/RequireThisCheck.xml
> Issue #8473: Records Support check update for RequireThisCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordsAndCompactCtors.java
Issue #8464: Records Support Check update for EqualsAvoidNullCheck
Diff Regression projects: https://raw.githubusercontent.com/nmancus1/nmancus1.github.io/master/check-update-configs/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/nmancus1/nmancus1.github.io/master/check-update-configs/EqualsAvoidNull.xml
> Issue #8464: Records Support Check update for EqualsAvoidNullCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainRecords.java
- src/xdocs/config_misc.xml
Issue #8522: Records Support check update for UncommentedMainCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/d5bf0363588dd8ea815a68c47c1d59de/raw/5b94adea37ce596ff6d4174188b15b1e323225ce/UncommentedMainCheck.xml
> Issue #8522: Records Support check update for UncommentedMainCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadCheckRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadCheckRecordsSpace.java
- src/xdocs/config_whitespace.xml
Issue #8527: Records support check update for ParenPadCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/a6f1587f9fc197f015d524702028682b/raw/0d1ecc614164ae7c533e7e9e4e782be710dbbf13/ParenPadCheckBase.xml
> Issue #8527: Records support check update for ParenPadCheck

- .ci/pitest.sh
- pom.xml
minor: master build failure due to leaked pitest coverage(#8604)
> minor: master build failure due to leaked pitest coverage(#8604)

- config/ant-phase-verify.xml
minor: remove exclude for records input(#8023)
After merging support for records, we forgot to remove this exclude.
> minor: remove exclude for records input(#8023)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberRecords.java
Issue #8520: Records Support check update for OuterTypeNumberCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/97e0e0b4ab44974b743a891439bc5a54/raw/13a700f73d44d11190b84bf48ac3826727d0d265/OuterTypeNumberCheck.xml
> Issue #8520: Records Support check update for OuterTypeNumberCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountRecords.java
- src/xdocs/config_sizes.xml
Issue #8518: Records support check update for MethodCountCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/c3db490c3255a96a6c18e55727631f54/raw/d7f46e4b1ec131bbd81e32e289c26d592f8aa8e9/MethodCountCheck.xml
> Issue #8518: Records support check update for MethodCountCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountRecords.java
- src/xdocs/config_sizes.xml
Issue #8517: Records support check update for ExecutableStatementCountCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/97ac4dfcac2c99ccac09af59a7edbf53/raw/c8155e44bfb94053b3b4650e61bd1f0716ff5bea/ExecutableStatementCount.xml
> Issue #8517: Records support check update for ExecutableStatementCount

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexityRecords.java
Issue #8504: Records support check update for CyclomaticComplexityCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/dc0a2fb76fe65de2426be1bb0549c3f7/raw/1b7f21d8b6a4908596177cd279b5ca5aa67512d0/CyclomaticComplexity.xml
> Issue #8504: Records support check update for CyclomaticComplexityCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexityRecordsAndCompactCtors.java
Issue #8501: Records support check update for BooleanExpressionComplexityCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/4b2c936ce7126095e94192bd20b74f20/raw/48cf09835dfbac3b67aa7414b084dc8f2a5e3594/BooleanExpressionComplexityCheck.xml
> Issue #8501: Records support check update for BooleanExpressionComplexity

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapRecordsAndCompactCtors.java
- src/xdocs/config_whitespace.xml
Issue #8526: Records support check update for NoLineWrapCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/c6d77daf759ca9862d798540d001bb4b/raw/efb206b5041a69f10d7e6217b48263d34a83a76b/NoLineWrapCheck.xml
> Issue #8526: Records support check update for NoLineWrapCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthRecordsAndCompactCtors.java
- src/xdocs/config_sizes.xml
Issue #8519: Records support check update for MethodLengthCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/d60f07a8d81a6c21ba2057ede8dc273e/raw/97a2b0dfe57f7b4f848c357141358a74e0ddfc59/MethodLengthCheckBase.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/4d14b80af490c08a47ffa5d53dd3fb78/raw/71a32d00f44869bb72cc81d779747b3cac76620f/MethodLengthCheckPatch.xml
> Issue #8519: Records support check update for MethodLengthCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/xdocs/config_blocks.xml
> minor: move module config javadoc to examples section

- src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/TokenUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/TokenUtilTest.java
> Issue #8048: Extract logic for token type checking to separate method

- src/it/java/com/google/checkstyle/test/chapter5naming/rule53camelcase/AbbreviationAsWordInNameTest.java
- src/it/resources/com/google/checkstyle/test/chapter5naming/rule53camelcase/InputAbbreviationAsWordInTypeNameCheck.java
- src/main/resources/google_checks.xml
Resolves #3812 
Diff report: https://shashwatj07.github.io/diff4/index.html
> Issue #3812: Fixed google_checks.xml to disallow abbreviations in identifier names

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java
- src/xdocs/config_annotation.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - annotation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/xdocs/config_coding.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - coding

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/xdocs/config_sizes.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - sizes

- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/RegexpHeaderCheck.java
- src/xdocs/config_header.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - header

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LambdaParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MemberNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/PatternVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheck.java
- src/xdocs/config_naming.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - naming

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/metrics/messages_zh.properties
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSSRecordsAndCompactCtors.java
- src/xdocs/config_metrics.xml
Issue #8505: Records Support check update for JavaNCSSCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/ffc09aff638f88f32ef97514432b0a8b/raw/f66215404c0ae82f14dd1ed304282258f4d1ad36/javaancssbase.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/8ed0d8354f0f97bd94dd6a8956b3af80/raw/4f176909a2e38f3bdaad51bbe44be721fc869001/javancss.xml
> Issue #8505: Records Support check update for JavaNCSSCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheck.java
- src/xdocs/config_misc.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - misc

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpOnFilenameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheck.java
- src/xdocs/config_regexp.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - regexp

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/RecordTypeParameterNameTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordTypeParameterNameTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule528typevariablenames/InputRecordTypeParameterName.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordtypeparametername/SuppressionXpathRegressionRecordTypeParameterName1.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordtypeparametername/SuppressionXpathRegressionRecordTypeParameterName2.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordTypeParameterNameCheck.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordTypeParameterNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordtypeparametername/InputRecordTypeParameterName.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordtypeparametername/InputRecordTypeParameterNameFoo.java
- src/xdocs/checks.xml
- src/xdocs/config_naming.xml
- src/xdocs/google_style.xml
Issue #8513: New check RecordTypeParameterNameCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/fe2c1055db690af06582ed78d9f52dd5/raw/149357483340a42b902ed1715e005cafb90c3a69/RecordTypeParameterNameCheckBase.xml
Diff Regression patch config: https://gist.githubusercontent.com/nmancus1/ed1d63e8e53dff56fd53642c43a66c76/raw/81408cd27482b5ea8a9e7746d5e7e0eb98c96016/RecordTypeParameterNameCheckPatch.xml
Contribution PR: https://github.com/checkstyle/contribution/pull/499
Link to site: https://nmancus1.github.io/site_RecordTypeParameterName
_updated 8/3 per …
> Issue #8513: New check RecordTypeParameterNameCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheck.java
- src/xdocs/config_whitespace.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - whitespace

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheck.java
- src/xdocs/config_modifier.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - modifier

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/xdocs/config_javadoc.xml
> Issue #8657: Modification of javadoc example markers to support metadata generation - javadoc

- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
Issue #4944: Extend Checkstyle GUI tool to work with Xpath
This PR is to Find Node by Xpath. 
**Correct Xpath Query:**
**Before**
**After**
**Incorrect Xpath Query:**
**Before:**
**After:**
> Issue #4944: Extend Checkstyle GUI tool to work with Xpath

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldSwitchExpression.java
Issue #8659: HiddenFieldCheck throws a NPE on switch expression
Diff Regression config: https://gist.githubusercontent.com/nmancus1/ddaa2dc0a3c7185e2400e001e9809907/raw/6b50c4280d997d19dbe689b4fd046ee11edc1cfb/HiddenField.xml
> Issue #8659: HiddenFieldCheck throws a NPE on switch expression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityCheckSwitchExpression.java
Issue #8681: Switch expression check update for NPathComplexityCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/47a829149ed6bb9dd27dd9ee832b6190/raw/586445eb5d49c19649ac07cfdc07758667dd51ba/NPathComplexity.xml
> Issue #8681: Switch expression check update for NPathComplexityCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSwitchExpressions.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSwitchExpressionsSkipIfLast.java
- src/xdocs/config_coding.xml
Issue #8665: Switch expression syntax check update for DefaultComesLast
Diff Regression config: https://gist.githubusercontent.com/nmancus1/059ef586fdd6e4ab146decd450d5bdc0/raw/5dcd861b1b94b2e92195e6e1b2eb06f62e3bb7f2/DefaultComesLast.txt
> Issue #8665: Switch expression syntax check update for DefaultComesLast

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesCheckSwitchExpression.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesCheckSwitchExpressionNoSingleLine.java
Issue #8664: NeedBraces throws a NPE when parsing switch expression syntax
Diff Regression config: https://gist.githubusercontent.com/nmancus1/9856763c94e3283016546a6dcd709208/raw/7e2b5b9c4f472f935ea48d958dbdd926e215aa2a/NeedBraces.xml
> Issue #8664: NeedBraces throws a NPE when parsing switch expression syntax

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java
Issue #8614: Text Blocks syntax check update for EqualsAvoidNullCheck
Diff Regression config: https://gist.githubusercontent.com/nmancus1/777c681aff07f2107556071b89f79275/raw/21e7cb5be685151d20c6210fc3e7478a60c24c4d/EqualsAvoidNull.xml
> Issue #8614: Text Blocks syntax check update for EqualsAvoidNullCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ScopeUtilTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierNoViolationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierRecords.java
- src/xdocs/checks.xml
- src/xdocs/config_modifier.xml
Issue #8577: Records Support check update for ClassMemberImpliedModifier
Diff Regression config: https://gist.githubusercontent.com/nmancus1/862ab46a87aa3d4ffc29309420eac624/raw/8447a3976cfa3cadc15636fcd0d9e257e946796d/ClassMemberImpliedModifierBase.xml
> Issue #8577: Records Support check update for ClassMemberImpliedModifier

- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/xdocs/config_blocks.xml
- src/xdocs/config_coding.xml
- src/xdocs/config_imports.xml
- src/xdocs/config_javadoc.xml
- src/xdocs/config_misc.xml
- src/xdocs/config_regexp.xml
- src/xdocs/config_sizes.xml
Fix #8726 
Fixes default values of properties detected in https://github.com/checkstyle/metadata-gen/issues/54
> Issue #8726: Mofication of module property default values to reflect actual working data

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.java
- src/xdocs/config_naming.xml
> Issue #8732: Removal of examples from property description

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceCheckSwitchExpressions.java
Issue #8676: VariableDeclarationUsageDistance throws a NPE on switch expressions
Diff Regression config: https://gist.githubusercontent.com/nmancus1/e3a7aff4509ae0c30831033a980d7a33/raw/d44596e998890689d76261872137429fc985c4d8/VariableDeclarationUsageDistance.xml
> Issue #8676: VariableDeclarationUsageDistance throws a NPE on switch expressions

- .ci/wercker.sh
required for https://github.com/checkstyle/checkstyle/pull/8743
as we will do patch for xwiki as next step
> minor: update xwiki to latest commit

- config/checkstyle_input_suppressions.xml
Issue #8738: Remove BlockCommentPosition test input files from input suppressions
> Issue #8738: Remove BlockCommentPosition test input files from input suppressions

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/YieldHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCheckSwitchExpression.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationYieldStatement.java
Issue #8691: Switch expression syntax check update for Indentation
Diff Regression config: https://gist.githubusercontent.com/nmancus1/5ce6db326d41df89b5d4f97f7cdb606d/raw/ae0494c000bb7848b75ca7078cb8eab0a767e030/Indentation.xml
> Issue #8691: Switch expression syntax check update for Indentation

- .ci/jsoref-spellchecker/whitelist.words
- .ci/wercker.sh
- config/suppressions-xpath.xml
- pom.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/annotation/SuppressWarningsCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/AtclauseOrderCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PackageObjectFactoryTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGenerator.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/ModuleDetails.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/ModulePropertyDetails.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/ModuleType.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java
> Issue #8742: Metadata-gen code migration

- .ci/jsoref-spellchecker/whitelist.words
- .ci/pitest.sh
- .ci/travis/travis.sh
- .circleci/config.yml
- config/import-control.xml
- config/spotbugs-exclude.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGenerator.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/ModuleDetails.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/ModulePropertyDetails.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/ModuleType.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/package-info.java
> Issue #8761: Move metadata generation code to main from test folder

- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java
> Issue #8768: resolve Sonar violation 

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTypeCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
> minor: fix validationType for memberModifiers in IllegalType

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.java
- src/xdocs/config_coding.xml
Issue #7639: update doc for ExplicitInitialization
```
<module name="ExplicitInitialization"/>
</module>
</module>
```
```
private int a_int = 0; // violation
private int b_int = 1;
private int c_int;
private char a_char = '\0'; // violation
private char b_char = 'b';
private char c_char;
private boolean a_bool = false; // violation
private boolean b_bool = true;
private boolean c_bool;
private Obj a_O = null; // violation
private Obj b_O = new Obj();
private Obj c_O;
private int ar1[] = null; // violation …
```
> Issue #7639: updates docs for ExplicitInitialization

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheck.java
- src/xdocs/config_coding.xml
Issue #7644
```
<module name="TreeWalker" >
<module name="IllegalThrows"/>
</module>
</module>
public void func1() throws RuntimeException {} // violation
public void func2() throws Exception {}  // ok
public void func3() throws Error {}  // violation
public void func4() throws Throwable {} // violation
public void func5() throws NullPointerException {} // ok
@Override
public void toString() throws Error {} // ok
}$ java $RUN_LOCALE -jar /var/tmp/checkstyle-8.33-all.jar -c config.xml Test.java
[ERROR] …
```
> Issue #7644: Update doc for IllegalThrows

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_input_checks.xml
- config/checkstyle_input_suppressions.xml
- config/checkstyle_non_main_files_checks.xml
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraperTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/InputJavadocMetadataScraperNoCodeInFileCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/annotation/InputJavadocMetadataScraperAnnotationUseStyleCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/blocks/InputJavadocMetadataScraperRightCurlyCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/custom/InputJavadocMetadataScraperPropertyWithNoCodeTagCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/javadoc/InputJavadocMetadataScraperAtclauseOrderCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/javadoc/InputJavadocMetadataScraperSummaryJavadocCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/checks/javadoc/InputJavadocMetadataScraperWriteTagCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/filefilters/InputJavadocMetadataScraperBeforeExecutionExclusionFileFilter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/meta/javadocmetadatascraper/filters/InputJavadocMetadataScraperSuppressWarningsFilter.java
#8771 
- PR to setup UT backbone
- Improved branch cov from 0.84 to 0.88
> Issue #8771: Improve code coverage for metadata generator classes - 1

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/SlistHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationRecordsAndCompactCtors.java
Issue #8806: false positive with nested records' methods
Diff Regression config: https://gist.githubusercontent.com/nmancus1/8277e4d4d979cd9745b86048999a20b5/raw/4064b88513abd5ac7f1af27616af47f168d0d1d4/Indentation.xml
> Issue #8806: IndentationCheck false positive with nested records' methods

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
> Issue #8823: fix sonar violation on null from getParent

- .ci/jsoref-spellchecker/whitelist.words
- src/xdocs/index.xml.vm
Add checkstyle github actions to related tools.
> doc: add checkstyle github action to related tools

- .github/workflows/diff_report.yml
Closes #8827 
Preview: https://abhishek-kumar09.github.io/github-actions-report-fetch/
Commit in my repo: https://github.com/Abhishek-kumar09/checkstyle/commit/0b14959611d0fb1f89fe7ae3308b9efeafa87f72
My repo's diff.yaml file: https://github.com/Abhishek-kumar09/checkstyle/blob/0b14959611d0fb1f89fe7ae3308b9efeafa87f72/.github/workflows/diff_report.yml
github-actions Run: https://github.com/Abhishek-kumar09/checkstyle/actions/runs/252306649
> Issue #8827: Diff Report should be generated against main checkstyle's branch

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheck.java
Diff Regression config: https://gist.githubusercontent.com/developerhb/2ec7d4b5183dfeddd266be7a62aa3542/raw/e6d79a0407122a2798da3a0515fca3782b62e995/my_check.xml
Diff Regression projects: https://gist.githubusercontent.com/developerhb/2ec7d4b5183dfeddd266be7a62aa3542/raw/e6d79a0407122a2798da3a0515fca3782b62e995/projects-to-test-on.properties
> Issue #6658: increase mutation coverage for pitest-imports profile to 100% - IllegalImportCheck

- .ci/eclipse-compiler-javac.sh
- .ci/jsoref-spellchecker/whitelist.words
- config/org.eclipse.jdt.core.prefs
Issue #8839 
~~All options are sorted (no more dedicated ignore section).
This makes it easier to find out which options have been added.~~
> Issue #8839: update eclipse compiler to R17

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIndentationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/indentation/SuppressionXpathRegressionIndentationLambdaTest1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/indentation/SuppressionXpathRegressionIndentationLambdaTest2.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCtorCall.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLambda8.java
Closes #3342,
Covers all the cases described in the discussion thread under #3342,
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/717190a7e2e06f4747b9c622692d4b99/raw/e14c56fbb6ca5f77b5bd20da1c9e51f0a99284ee/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/59f7adaffb4eefc379dd29c23227091b/raw/d156d4bc542f4a342be8fe4cccb1dd0e138a4f61/config.xml
> Issue #3342: Indentation: Lambda re-implementation

- .cirrus.yml
- README.md
Issue #8855
* Fix for master build
* The tests are the same as for Appveyor.
Appveyor itself will be updated in next PR.
> Issue #8855: fix master build on cirrus ci

- src/main/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheck.java
I found a code fragment applicable to`TokenUtil#forEachChild` in `FinalParametersCheck.java`, so I modified
> minor: applying TokeUtil#forEachChild

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/EmptyStatementCheck.xml
- src/xdocs/config_coding.xml
Issue #7665 
```
cat config.xml
"-//Puppy Crawl//DTD Check Configuration 1.3//EN"      
<module name="EmptyStatement" />
</module>
</module>
cat Test.java
int i = 5;
if (i > 3); // violation, semicolon ";" right after if statement
i++;
for (i = 0; i < 5; i++); // violation
i++;
while (i < 10) // OK
i++;
}
}
java -jar .\checkstyle-8.36.1-all.jar -c config.xml Test.java
[ERROR] E:\checkstyle-playground\Test.java:4:15: Empty statement. [EmptyStatement]
[ERROR] E:\checkstyle-playground\Test.java:6:32: Empty statement. [EmptyStatement]
Audit done.
Checkstyle ends with 2 …
```
> Issue #7665: add examples for EmptyStatement

- .ci/validation.sh
- .semaphore/semaphore.yml
Issue #8859: Add SpongePowered/Configurate Checkstyle run to CI
> Issue #8859: Add SpongePowered/Configurate Checkstyle run to CI

- src/xdocs/releasenotes.xml
problem was found at https://github.com/checkstyle/sonar-checkstyle/pull/338/files#r499291408
> minor: fix releasenotes 8.36 to clearly mention new check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationBraceAdjustment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidClassDefIndent.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationStrictCondition.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationSwitchCasesAndEnums.java
- src/test/resources/com/puppycrawl/tools/checkstyle/main/InputMainComplexityOverflow.java
Fixes Issue #3899 and Issue #6392.
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/Abhishek-kumar09/Configurate/master/etc/checkstyle/checkstyle.xml
> Issue #3899: Modify braceAdjustment for support to google-java-format and switch-block-indentation

- .semaphore/semaphore.yml
not for merge ... 
testing what is wrong with this validation item
> infra: activate josm again

- .ci/wercker.sh
- wercker.yml
> Issue #6209: activate no-error-spring-cloud-gcp in wercker

- pom.xml
https://travis-ci.org/github/checkstyle/checkstyle/jobs/733779138#L1065
> config: bump ant to 1.10.9

- config/checkstyle_checks.xml
- config/checkstyle_non_main_files_checks.xml
- config/checkstyle_non_main_files_suppressions.xml
- config/checkstyle_resources_checks.xml
- config/checkstyle_resources_suppressions.xml
- config/suppressions.xml
> Issue #8790: All Regexp Checks that has few instances should have id property

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionIndentationTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/indentation/SuppressionXpathRegressionIndentationElseWithoutCurly.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/indentation/SuppressionXpathRegressionIndentationIfWithoutCurly.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AbstractExpressionHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/DoWhileHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationDoWhile.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationForWithoutCurly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationIfElseWithNoCurly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidIfIndent.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationWhileNoCurly.java
Resolves Issue #3135
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/717190a7e2e06f4747b9c622692d4b99/raw/93fe7739cbdc52d7d17273a12d2b92328812c504/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/d52f23ee4f0db3d0b685d036c4321333a8e66ca5/my_check.xml
> Issue #3135: Indentation support for non-list child of block elements(if/else/for/while/switch/case)

- src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/Main.java
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtilTest.java
Fix of violations from https://github.com/checkstyle/checkstyle/pull/8896
Change lambdas to be not more than 10 lines
> minor: refactor long lambdas

- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/DescendantTokenCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsJavaDocsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/CheckUtil.java
- src/xdocs/config_coding.xml
> Issue #8916: use empty string for empty array values of token property

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionLambdaBodyLengthTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/lambdabodylength/SuppressionXpathRegressionLambdaBodyLength1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/lambdabodylength/SuppressionXpathRegressionLambdaBodyLength2.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes/messages_zh.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/LambdaBodyLengthCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthSwitchExps.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthMax.java
- src/xdocs/checks.xml
- src/xdocs/config_sizes.xml
Closes #8341 
~~Depends on https://github.com/checkstyle/checkstyle/pull/8897~~
it is new module, so all mentors need to review.
Contrib PR: https://github.com/checkstyle/contribution/pull/512
New module config: https://gist.githubusercontent.com/strkkk/bf10f326cacdf50f8cb67f0023cd972b/raw/c9710499bd4d853d8d56b71aa55c10f8ab33a56e/lambda_body.xml
> Issue #8341: add LambdaBodyLengthCheck

- .ci/jsoref-spellchecker/whitelist.words
- src/xdocs/index.xml.vm
> doc: Add Mega-Linter to active tools list

- .ci/README.md
- .ci/jsoref-spellchecker/whitelist.words
- .ci/travis/travis.sh
- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .mdlrc
- .travis.yml
- README.md
- config/markdownlint.rb
- pom.xml
Issue #8909
Almost no changes in the existing .md files.
The one significant change is that now we have a top level header in the each file:
* [md041](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md041---first-line-in-file-should-be-a-top-level-header)
~~I vote to suppress this rule.~~
> Issue 8909 markdownlint

- .github/workflows/diff_report.yml
> Issue #8938: put user content to env variable at workflows/diff_report.yml

- SECURITY.md
from https://github.com/checkstyle/checkstyle/issues/8936
> doc: add security policy page

- pom.xml
https://snyk.io/test/github/checkstyle/checkstyle?targetFile=pom.xml
we do not use affected method at all, but lets update version.
> config: bump guava version to 30.0 to fix security alert

- .ci/jsoref-spellchecker/whitelist.words
- .github/workflows/codeql-analysis.yml
suggestion from https://github.com/checkstyle/checkstyle/security
I just removed javascript language and removed some comments.
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code
https://github.com/checkstyle/checkstyle/security/code-scanning - 0 alerts found.
> config: codeql-analysis.yml is generated by Github

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordTypeParameterNameCheck.java
> minor: fix check name in javadoc

- .ci/openjdk14-excluded.files
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java
Fix #8934 
Turns out, assigning to `switch` is not the problem. In fact, wrapping `switch` inside a function `foo()` makes the problem disappear.
```
$ cat ExpressionSwitchBugs.java
public class ExpressionSwitchBugs {
private static final int staticValue = 2;
private void foo() {
final int someVariable = switch (staticValue) {
case 0 -> -1;
case 2 -> 2;
default -> 3;
};
}
}
java -jar .\checkstyle-8.37-all.jar -c config.xml ExpressionSwitchBugs.java
Audit done.
```
Here's what went wrong in #8934:
The NPE occurs at line 482, when checkstyle is reading `case 0 -> -1;`
https://github.com/checkstyle/checkstyle/blob/3fc9dd98ad6ed963e2cfcd2e630f7031ec5b0c1e/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheck.java#L481-L482
Basically, when …
> Issue #8934: FinalLocalVariable throws a NPE on Switch expression in assignment 

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheck.java
- src/xdocs/config_whitespace.xml
> Issue #3601: MethodParamPad example added

- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/xdocs/config_annotation.xml
just update for default example
> Issue #7571: Update doc AnnotationUseStyle

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
- src/xdocs/config_javadoc.xml
just update for default config
> Doc: Update doc AtclauseOrderCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheck.java
- src/xdocs/config_blocks.xml
Issue #7580 : update doc for EmptyBlock
> Issue #7580: Updated docs of EmptyBlock

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java
- src/xdocs/config_javadoc.xml
> Issue #7604: Update doc NonEmptyAtclauseDescriptionCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheck.java
- src/xdocs/config_coding.xml
Fixes #7669
```
PS H:\CheckstyleCheck> cat .\config.xml
<module name="MultipleVariableDeclarations">
</module>
</module>
</module>
PS H:\CheckstyleCheck> cat .\Test.java
int mid;
int high;
// ...
int lower, higher; // violation
// ...
int value,
index;  // violation
// ...
int place = mid, number = high; // violation
}
}
PS H:\CheckstyleCheck> java -jar H:\GitHub\checkstyle\target\checkstyle-8.38-SNAPSHOT-all.jar -c .\config.xml .\Test.java
[ERROR] H:\CheckstyleCheck\.\Test.java:7:5: Each variable declaration must be in its own statement. …
```
> Issue #7669: Updated docs for MultipleVaribleDeclaration

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorSingleTypeVariables.java
- src/xdocs/config_whitespace.xml
Closes #8957
Diff Regression projects: https://gist.githubusercontent.com/strkkk/5eb3b0069ecd438af73bf045c24a855c/raw/d568ee6c30a91e3f721c37b4883ef3264b6203b7/all-projects
Diff Regression config: https://gist.githubusercontent.com/strkkk/bf10f326cacdf50f8cb67f0023cd972b/raw/0dffdf53db3b7cfd7f57c88618fe871f4f779adf/lambda_body.xml
> Fix EmptyLineSeparator for multiple single type variables on line

- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalCatchCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalThrowsCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTypeCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/design/VisibilityModifierCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocBlockTagLocationCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/ClassDataAbstractionCouplingCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/metrics/ClassFanOutComplexityCheck.xml
Closes #8941 
As you see in diff, there were other similar issues for other checks
> Issue #8941: fix metadata generation for wrapped default values

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule42blockindentation/InputIndentationCorrectIfAndParameter.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrect.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectClass.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectFieldAndParameter.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectIfAndParameter.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectNewChildren.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectReturnAndParameter.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectWhileDoWhileAndParameter.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlLoaderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnonymousClassInMethodCurlyOnNewLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCorrectIfAndParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidMethodIndent.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNew.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationValidNewChildren.java
Fixes #5362 
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/7e9f169832e45c826fb99e72b3ff08f32765243a/my_check.xml
> Issue #5362: Fix new keyword and their children not checked correctly.

- src/main/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheck.java
- src/xdocs/config_design.xml
Issue #7609
Updated doc for FinalClass #8996
> Issue #7609: Update doc for FinalClass #8996

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/InnerAssignmentCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
- src/xdocs/config_coding.xml
fixes: #6915 
Diff Regression config: https://gist.github.com/romani/7deac41fe5c1e70af01438d32aabc7eb/raw/57a44c0470584de669575484b20677641ae50bfd/my_check-pr8190.xml
Diff Regression projects: https://gist.githubusercontent.com/romani/7deac41fe5c1e70af01438d32aabc7eb/raw/7c7cfa59aef6edc05c91b7f1848881d9afc9cbc9/projects-to-test-on-pr-8190.properties
> Issue #6915: InnerAssignment: false positives on for and do-while loops

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFinalInstanceVariable.java
Add input as discussed in #8973
> Issue #8973: RequireThis: Add input for final instance variable

- .ci/jsoref-spellchecker/whitelist.words
- wercker.yml
> Issue #9019: Docker limits is reached in wercker

- .semaphore/semaphore.yml
> infra: disable josm project validation in semaphore ci

- .semaphore/semaphore.yml
https://ci.appveyor.com/project/Checkstyle/checkstyle/builds/36487365/job/h4cka47fvgojsu3e#L251
If is impossible to comment out code in yml file without complains from checkstyle :)
> minor: fix checkstyle violation on yml file

- README.md
> Issue #7045: add azure badge

- README.md
> Issue #2460: add drone badge

- .drone.yml
Issue #2460
image from https://hub.docker.com/_/maven
> Issue #2460: copy two commands from Travis

- .ci/jsoref-spellchecker/whitelist.words
- .drone.yml
Issue #2460
based on https://docs.drone.io/pipeline/kubernetes/examples/language/golang/
> Issue #2460: copy to drone.io 2 more commands from Travis

- .drone.yml
- .travis.yml
> Issue #2460: move more items from Travis to drone

- .drone.yml
- .travis.yml
> Issue #2460: move more jobs from Travis to drone

- .ci/travis/travis.sh
- .drone.yml
- .travis.yml
> Issue #2460: move more to Travis to drone

- .travis.yml
- azure-pipelines.yml
> Isuse #7045: azure to use matrix

- .travis.yml
- azure-pipelines.yml
> Issue #7045: move move jobs from Travis to azure

- .ci/travis/travis.sh
- .travis.yml
- azure-pipelines.yml
> Issue #7045: move more item from Travis to azure

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/messages_zh.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/JavadocMissingLeadingAsteriskCheck.xml
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressionXpathFilter.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingleadingasterisk/InputJavadocMissingLeadingAsteriskCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingleadingasterisk/InputJavadocMissingLeadingAsteriskIncorrect.java
- src/xdocs/checks.xml
- src/xdocs/config_filters.xml
- src/xdocs/config_javadoc.xml
Issue #6722
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/32ddbff9e69986ac2fcbbeff7def2f80/raw/8480445657f1d215e683dbb6b14c1577bbd44e6b/projects-to-test-on.properties
New module config: https://gist.githubusercontent.com/pbludov/3a8be5da26a64e2be80b26217d052eb6/raw/fa0bef2587280c80bfa87e18493afe52ca1a5eba/config.xml
Contrib repo PR: https://github.com/checkstyle/contribution/pull/526
> Issue #6722: new check JavadocMissingLeadingAsteriskCheck

- .travis.yml
- azure-pipelines.yml
> Issue #7045: move version validation to azure

- azure-pipelines.yml
> Issue #7045: enable builds on master

- azure-pipelines.yml
> Issue #7045: skip install of xmlstarlet

- .travis.yml
- azure-pipelines.yml
> Issue #7045: move mdl to azure

- .travis.yml
- azure-pipelines.yml
> Issue #7045: move pr-age to azure

- .ci/travis/xtr_releasenotes-gen.sh
- .drone.yml
fix regexp to work with empty value (not a PR)
https://cloud.drone.io/checkstyle/checkstyle/140/3/3
> infra: make release notes script to be CI agnostic; 

- .drone.yml
https://docs.drone.io/secret/repository/
> infra: bind step with drone secret

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheck.java
- src/xdocs/config_naming.xml
Issue #7567: Adding code examples for default configuration of MethodNameCheck
> Issue #7567: Adding code examples for default configuration of MethodNameCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheck.java
- src/xdocs/config_naming.xml
Resolves #7564 Add Default config example for ConstantName.
> Issue #7564: Added example for default config

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheck.java
- src/xdocs/config_coding.xml
Issue #7652: Updated doc for NestedIfDepth
> Issue #7652: Updating doc for NestedIfDepth

- .ci/travis/travis.sh
> Issue #9066: Update wording of verify-no-exception-configs validation to mention what is expected

- azure-pipelines.yml
detected at
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=208&view=logs&j=b79bfe0d-a4e8-5dea-7085-eab0d7b5dc1f&t=e0670b16-7f21-5bf2-0c17-6e3ed0a3471f
> infra: skip azure cache only if explicitly defined

- .travis.yml
> Issue #8908: Do clean in all Travis maven commands

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- config/import-control.xml
- config/spotbugs-exclude.xml
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionMatchXpathTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/matchxpath/SuppressionXpathRegressionMatchXpathTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_de.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fi.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_fr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_ja.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_pt.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_tr.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/coding/messages_zh.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MatchXpathCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathAvoidInstanceCreationWithoutVar.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpath.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathDoubleBrace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathExecutableStatementCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathForbidParameterizedConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathForbidPrintStackTrace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathIllegalThrows.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathMethodOrder.java
- src/xdocs/checks.xml
- src/xdocs/config_coding.xml
https://github.com/checkstyle/checkstyle/issues/6481
Contribution update: https://github.com/checkstyle/contribution/pull/528
> Issue #6481: Generic XPath check

- .ci/pitest.sh
- .ci/wercker.sh
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule4841indentation/IndentationTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule4841indentation/InputIndentationCorrectAnnotationArrayInit.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AnnotationArrayInitHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/BlockParentHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/powermock/PropertyCacheFilePowerTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnArrInit.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnArrInit2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnotationArrayInitGood.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnotationScopeIndentationCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationDifficultAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidArrayInitIndent.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationOddLineWrappingAndArrayInit.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationZeroArrayInit.java
Fixes Issue #5951, #8980  
https://github.com/pmd/pmd/pull/2925 - merged
https://github.com/pgjdbc/pgjdbc/pull/1961
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/7994fb09f0b5d073f1937e62faecdd5cb3908e64/project-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/2143ba7f21dcafb998019a1ca2c0ee3f1c510646/my_check.xml
> Issue #5951: Add indentation Support for Annotation Array Initialisation

- .ci/pitest.sh
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_DotPackageName.java
> Issue #7875: resolve pitest issue for ImportOrderCheck

- .github/workflows/site.yml
> Issue #9117: add new trigger phrase for site generation action

- src/main/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterElement.java
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&open=AXZvXAyUa-Kxo9081VHM&resolved=false&severities=MINOR
> minor: resolve sonar violation 'Replace this lambda with method refererence

- src/xdocs/checks.xml
- src/xdocs/config_annotation.xml
> Issue #9130: add space in documentation between words

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/OperatorWrapTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapEol.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapNl.java
Issue #8018
Text-based approach replaced with AST-based. 
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/32ddbff9e69986ac2fcbbeff7def2f80/raw/8480445657f1d215e683dbb6b14c1577bbd44e6b/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/pbludov/81b21835641d4f9f61ce70954a29dfcb/raw/a703de479422ac1bcd12e5a69b653217b3513a73/Issue-8018-operator-wrap-config.xml
Diff Regression config (NL): https://gist.githubusercontent.com/pbludov/cb09980e6eef2a89b2298ed10c087fbc/raw/a141f53d13c3907349217758bea066fac3b49c63/Issue-8018-operator-wrap-config-nl.xml
Diff Regression config (EOL): https://gist.githubusercontent.com/pbludov/a233b467c6c3b1ddfd06041fde6577a5/raw/37ba5305aaa37aa1d8623d84804b0a5ed1dad6b0/Issue-8018-operator-wrap-config-eol.xml
* …
> Issue #8018: AST based operatorwrap

- src/main/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraper.java
https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&issues=AXZvXAw5a-Kxo9081VHL&open=AXZvXAw5a-Kxo9081VHL
> minor: fix sonar violation 'Refactor this repetition that can lead to a stack overflow for large inputs.'

- config/checkstyle_checks.xml
- src/it/java/org/checkstyle/base/AbstractItModuleTestSupport.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LambdaHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/MetadataGeneratorUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/ModuleType.java
Closes #8710 
Warnings corrected as well.
> Issue #8710: add check for private method javadoc to config

- .travis.yml
detected at https://travis-ci.org/github/checkstyle/checkstyle/jobs/752997381
> infra:  print first 300 lines of diff

- .ci/no-exception-test.sh
Issue #8960: Use diff.groovy in openjdk14-with-checks-nonjavadoc-error
Now that we have removed JXR from Checkstyle-Tester, we can also remove usage of `extraMvnOptions` in this CI run.
~~I am initially using this PR to show that https://github.com/checkstyle/contribution/pull/538 works as intended; after sharing those results I will update this PR.~~
> Issue #8960: Use diff.groovy in openjdk14-with-checks-nonjavadoc-error

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/LineWrappingHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/NewHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationChainedMethodCalls.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationCustomAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewWithForceStrictCondition.java
---
---
New Keyword was being checked at multiple times, one inside its own handler and one by the lineWrappingHandler.
Changed code to give all the powers to only newHandler.
Fixes #9071 
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/717190a7e2e06f4747b9c622692d4b99/raw/ce18e37ba0f30ce85d3f929a5821fa4178557232/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/2143ba7f21dcafb998019a1ca2c0ee3f1c510646/my_check.xml
> Issue #9071: New keyword throwing unresolvable indentation errors

- .ci/wercker.sh
commits are moved from contributor fork to our fork
https://github.com/Abhishek-kumar09/pgjdbc/commits/master
this PR blocks https://github.com/checkstyle/checkstyle/pull/8177
> infra: use checkstyle's fork for pgjdbc fixes

- src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
This PR is split from #8177.
There are internal Checkstyle violations that were previously not detected due to issue #5711. This PR aims to fix those violations.
> minor: fix internal Checkstyle violations

- .github/workflows/diff_report.yml
- .github/workflows/rebase.yml
- .github/workflows/site.yml
Closes: #9187 
Since I think this works only in master branch, can`t directly test on this repository. Here at some screenshot in one of my own Test Repository. I had made changes just on Rebase Action as I would first like to confirm that it works.
> Issue #9187: Github actions should react with thump up

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ArrayInitHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationInvalidArrayInitIndentTwoDimensional.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationValidArrayInitIndentTwo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationValidArrayInitIndentTwoDimensional.java
Fixes Issue #8979 
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/7994fb09f0b5d073f1937e62faecdd5cb3908e64/project-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/7e9f169832e45c826fb99e72b3ff08f32765243a/my_check.xml
> Issue #8979: fix for 'array initialization rcurly' has incorrect indentation

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/blocks/AvoidNestedBlocksCheck.xml
- src/xdocs/config_blocks.xml
Issue #7579: Added code examples for AvoidNestedBlocks
Moved the example for allowInSwitchCase property from the Description sub-section to Examples. 
Output of default config examples:
`$ cat custom_config.xml`
```
<module name="AvoidNestedBlocks"/>
</module>
</module>
```
```
int myInteger = 0;
{
myInteger = 2;    //NOT OK, violation : Avoid nested blocks.
}
System.out.println("myInteger = " + myInteger);
switch (a) {
case 1:
{
System.out.println("Case 1");   //NOT OK, violation : Avoid nested blocks.
break;
}
case 2:
System.out.println("Case 2");     //OK
break;
}
}
``` …
> Issue #7579: Update doc for AvoidNestedBlocks

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/com/google/checkstyle/test/chapter5naming/rule526parameternames/RecordComponentNameTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionRecordComponentNameTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter5naming/rule526parameternames/InputRecordComponentName.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentname/SuppressionXpathRecordComponentName1.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/recordcomponentname/SuppressionXpathRecordComponentName2.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordComponentNameCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/naming/RecordComponentNameCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordComponentNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordcomponentname/InputRecordComponentNameDefault.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordcomponentname/InputRecordComponentNameLowercase.java
- src/xdocs/checks.xml
- src/xdocs/config_naming.xml
- src/xdocs/google_style.xml
Closes #8765
Contrib repo PR: https://github.com/checkstyle/contribution/pull/537
Diff Regression projects: https://gist.githubusercontent.com/strkkk/5eb3b0069ecd438af73bf045c24a855c/raw/d568ee6c30a91e3f721c37b4883ef3264b6203b7/all-projects
New module config: https://gist.githubusercontent.com/strkkk/bf10f326cacdf50f8cb67f0023cd972b/raw/1d80f17c7fb7157e313b393dce0270da2ab01453/lambda_body.xml
> Issue #8765: add RecordComponentNameCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheck.java
- src/xdocs/config_whitespace.xml
Solves issue #7620: Update doc for FileTabCharacter
Website after Javadoc update:
Output of default config examples:
Config file:
`$ cat custom_checks.xml`
```
<module name="FileTabCharacter"/>
</module>
```
Source code:
`$ cat test.java`
```
public class test {
int a;                          // violation : indented using tab, no further checks
public void foo (int arg) {
a = arg;
}
}
```
Output:
`$ java -jar checkstyle-8.40-SNAPSHOT-all.jar -c custom_checks.xml test.java `
```
[ERROR] /home/ayushman/Desktop/CheckstyleExperiments/FileTabCharacter/test.java:2:1: File contains tab characters (this is the first …
```
> Issue #7620: Update doc for FileTabCharacter check

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/xdocs/report_issue.xml
> Issue #9114: Update github issue templates to use cli

- .github/workflows/codeql-analysis.yml
> Issue #9203: Github action CodeQL should use maven cache

- .ci/jsoref-spellchecker/whitelist.words
- pom.xml
1. Add myself to list of developers
2. Mark inactive developers as former
> config: update developers list

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/imports/ImportOrderCheck.xml
- src/xdocs/config_imports.xml
Issue #7687: Adding code examples for ImportOrder check
minor: fix incorrect property reference (#7687)
> Issue #7687: Adding code examples for ImportOrder check

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/VariableDeclarationUsageDistanceCheck.xml
- src/xdocs/config_coding.xml
Solves #7663. Update doc for VariableDeclarationUsageDistance.
Website after update:
`$ cat custom_checks.xml`
```xml
<module name="VariableDeclarationUsageDistance"/>
</module>
</module>
```
Source code:
```java
public void foo1() {
int num;        // violation, distance = 4
final int PI;   // OK, final variables not checked
System.out.println("Statement 1");
System.out.println("Statement 2");
System.out.println("Statement 3");
num = 1;
PI = 3.14;
}
public void foo2() {
int a;          // OK, used in different scope
int b = 1;      // OK, used in different scope
int …
```
> Issue #7663: Update doc for VariableDeclarationUsageDistance

- pom.xml
Closes: #9240 
Minor: update Sonar Maven Plugin to 3.8.0.2131
> minor: Update sonar-maven-plugin

- .github/workflows/diff_report.yml
Closes #9255 
Test PR with no projects link: https://github.com/strkkk/checkstyle/pull/18
Related PRs
PR for uncommented projects https://github.com/checkstyle/contribution/pull/543
PR with doc update https://github.com/checkstyle/contribution/pull/544
> Issue #9255: add default projects file for diff github action

- .ci/jsoref-spellchecker/whitelist.words
- .ci/travis/travis.sh
- .ci/wercker.sh
- .travis.yml
- wercker.yml
#9242 
Add XWiki project (xwiki-commons, xwiki-rendering, xwiki-platform) validation to the Travis job.
> Issue #9242: Build also xwiki-rendering and xwiki-platform in the no regression travis job

- .ci/openjdk14-excluded.files
- src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/suppresswarningsholder/InputSuppressWarningsHolder7.java
Closes #9260 
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/c329ce8d8c156983950ae9f6ec43da4f92efb3a3/confg.xml
Diff Regression projects: https://raw.githubusercontent.com/strkkk/contribution/uncomment_projects/checkstyle-tester/projects-to-test-on.properties
> Issue #9260: fix SuppressionWarningsHolder for annotation default values and array inits

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
Issue #7878
1) Pitest report
https://aryaniiit002.github.io/Issue-7878/pit-reports/202102041842/com.puppycrawl.tools.checkstyle.checks.imports/ImportOrderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@63eaed7a_732
2) Surviving mutation:
`removed conditional - replaced equality check with true → SURVIVED
`
3)  Regression report:
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/PatchBranch_2021151721/reports/diff/index.html
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/f4157cc7f398779c0f348e600885e7ae71ab828f/my_check.xml
Diff Regression projects: https://gist.githubusercontent.com/aryaniiit002/97577199a93846562de23a0d6304e496/raw/1e822753136da53287c702a879090c63061936f2/projects-to-test-on.propertie …
> Issue #7878: Resolve Pitest Issues ImportOrderCheck (7)

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/xdocs/config_coding.xml
Issue #8930: Example to show how to target Check to fields only
> Issue #8930: IllegalType: update examples to show how to target Check to fields only

- src/main/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheck.java
- src/xdocs/config_regexp.xml
Issue #7695: Updated xml and javadoc for RegexMultiline #9148
> Issue #7695: Update doc for RegexpMultiline #9148

- .ci/travis/travis.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationNewHandler.java
Resolves #9236 
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/a0cbb3d537560f88f699e778b41ffd3c8e1c9338/gistfile1.txt
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/a0cbb3d537560f88f699e778b41ffd3c8e1c9338/my_check.xml
> Issue #9236: Resolve 'new' suggesting wrong indentation for try handler

- .ci/jsoref-spellchecker/whitelist.words
- .ci/no_old_refs.sh
- .ci/openjdk14-excluded.files
- .travis.yml
- config/checkstyle_checks.xml
- config/import-control.xml
- config/intellij-idea-inspections.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionXpathFilter.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/filters/SuppressionXpathFilter.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsPagesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/xdocs/config_filters.xml
Related to #9256
Travis failure (without commit with fixes) is because there is unfixed issues, all violations are valid.
https://travis-ci.org/github/checkstyle/checkstyle/jobs/758375259
Cleanup of some mentioned issues that have been closed.
> Issue #9256: add job for checking mentioned closed todo issues

- .github/workflows/diff_report.yml
Depends on https://github.com/checkstyle/contribution/pull/543
Link is changed to point to a new file
> minor: change link to file in diff report action

- src/main/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheck.java
- src/xdocs/config_misc.xml
Resloves #9131: Adding example for AvoidEscapedUnicodeCharacters
> Issue #9131: Adding example for AvoidEscapedUnicodeCharacters

- config/markdownlint.rb
Issue #9292
Prerequisite for #9285
> Issue #9292: disable markdownlint rule md041

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/ClassDefHandler.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/HandlerFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/MethodDefHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationLineWrappedRecordDeclaration.java
Issue #9152: Record implementing interfaces, indentation faulty
Diff Regression projects: https://gist.githubusercontent.com/nmancus1/ca61df3ebd259f03b7a6d4fd866520e1/raw/fca8f93b99256f34d3b12a667b6a3c384e0087fc/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/nmancus1/ad8818e33f0f1e6f26621b19e411fd31/raw/259d81194cd6a81ca3fbeae7215d93fa4f4fda23/config.xml
Diff report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/issue-9152_2021150829/reports/diff/index.html
> Issue #9152: Record implementing interfaces, indentation faulty

- .ci/jsoref-spellchecker/whitelist.words
- .ci/no_old_refs.sh
- .github/FUNDING.yml
- .github/workflows/diff_report.yml
- .github/workflows/no_old_refs.yml
- .github/workflows/rebase.yml
- .github/workflows/site.yml
- .travis.yml
- README.md
- config/checkstyle_non_main_files_checks.xml
Action will be triggered after push to master
Example https://github.com/strkkk/checkstyle/actions/workflows/no_old_refs.yml 
Added badge to display status
Second commit - fix check for yaml comment whitespace, it reports false-positive when hash sign is used inside bash expression
> minor: job for closed issues moved to github actions and add badge

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java
Fixes https://github.com/checkstyle/checkstyle/issues/9304
1. Pitest report: https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239304/pit-reports/202102171623/com.puppycrawl.tools.checkstyle.checks.header/HeaderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@79513efe_186
2. Surviving mutation: `removed conditional - replaced equality check with false → SURVIVED`
3. Regression report: https://aryaniiit002.github.io/Checkstyle-reports/Issue-%239304/diff/index.html
> Issue #9304: Resolve Pitest Issues - HeaderCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheck.java
- src/xdocs/config_coding.xml
Closes: #7655 
Since PR #9013 was abandoned and minimal changes were required in that PR to complete, this PR completes those changes. 
Please comment if it is allowed to make this PR while on is opened and abandoned?
```
int method(int parameter) {
if (parameter <= 0 ) {
throw new IllegalArgumentException("A positive value is expected");
}
parameter -= 2;  // violation
return parameter;
}
}
int method(int parameter) {
if (parameter <= 0 ) {
throw new IllegalArgumentException("A positive value is expected");
}
parameter -= 2;  // violation
return parameter;
}
}
```
``` …
```
> Issue #7655: Update doc for ParameterAssignment

- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
- src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
- src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/treewalker/InputTreeWalkerMultiCheckOrder.java
Issue #9251
This ensures all checks are executed deterministically.
Example taken from https://nmancus1.github.io/diff_reports_9122/diff_config5/infinispan/index.html#A1
> Issue #9251: create deterministic order of check execution

- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinter.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavaParser.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/ParserUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ParserUtilTest.java
Issue #9272: Create parser util class that will host util methods for parser that creates AST
> Issue #9272: Create parser utility class

- .github/workflows/diff_report.yml
- .github/workflows/site.yml
Extracted variables to env properties
> minor: extract env variables in github actions

- .ci/travis/travis.sh
- .drone.yml
Fixes #9343 
Maven flag to omit download progress is added to drone.io builds
> Issue #9343: remove download progress in drone.io builds

- src/it/java/com/google/checkstyle/test/chapter7javadoc/rule711generalform/SingleLineJavadocTest.java
- src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule711generalform/InputSingleLineJavadocCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/javadoc/SingleLineJavadocCheck.xml
- src/main/resources/google_checks.xml
- src/xdocs/config_javadoc.xml
> Issue #4052: update config of SingleLineJavadoc in google_checks.xml

- .ci/idea_inspection.sh
- .ci/no-exception-test.sh
- .ci/run-link-check-plugin.sh
- .ci/shippable.sh
- .ci/sonar.sh
- .ci/travis/travis.sh
- .ci/travis/xtr_releasenotes-gen.sh
- .ci/validation.sh
- .ci/wercker.sh
- .drone.yml
- .semaphore/semaphore.yml
- .travis.yml
- azure-pipelines.yml
- config/checkstyle_non_main_files_checks.xml
- config/checkstyle_non_main_files_suppressions.xml
- release.sh
- wercker.yml
There was an idea in https://github.com/checkstyle/checkstyle/pull/9345 to enforce usage of `--no-transfer-progress` flag to all maven commands.
> minor: add --no-transfer-progress flag to maven commands in sh and yml files

- .ci/jsoref-spellchecker/whitelist.words
- .ci/run-link-check-plugin.sh
- config/checkstyle_non_main_files_suppressions.xml
Remove flag and add suppression since codeship image does not support proper maven version yet
> minor: remove --no-transfer-progress flag for codeship

- config/import-control.xml
- src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
- src/main/java/com/puppycrawl/tools/checkstyle/TreeWalker.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaWriter.java
Closes #9342 
Besides problems from issue, also these minor violations were fixed https://sonarcloud.io/project/issues?id=org.checkstyle%3Acheckstyle&resolved=false&severities=MINOR&types=CODE_SMELL
> Issue #9342: fix sonar violations

- .ci/no-exception-test.sh
- .ci/shippable.sh
- .ci/travis/travis.sh
- .ci/util.sh
- .ci/validation.sh
- .ci/wercker.sh
> Issue #9348: Extract common bash CI functions into util.sh

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9395 
```
void foo() {
int[] y =
{
1,
2,
};
}
}
$ java com.puppycrawl.tools.checkstyle.Main -t sun_checks.xml Test.java
|   |--RPAREN -> ) [2:13]
|   `--SLIST -> { [2:15]
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:10]
|       |   |--MODIFIERS -> MODIFIERS [3:10]
|       |   |--TYPE -> TYPE [3:10]
|       |   | …
```
> Issue #9395: updated example of AST for TokenTypes.ARRAY_INIT

- src/test/java/com/puppycrawl/tools/checkstyle/internal/CommitValidationTest.java
- src/xdocs/contributing.xml
Closes #8928 
Combined with [#547](https://github.com/checkstyle/contribution/pull/547) in contribution repository.
>  Issue #8928: Add supplemental prefix support 

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9403 
```
|   |   |--COMMA -> , [2:18]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:20]
|   | …
```
> Issue #9403: Added example of AST for TokenTypes.BOR_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9401 
```
>cat Test.java
void foo(int a) {
a=~a;
}
}
|   |       |   `--LITERAL_INT -> int [2:13]
|   |       `--IDENT -> a [2:17]
|   |--RPAREN -> ) [2:18]
| …
```
> Issue #9401: Added example of AST for TokenTypes.BNOT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9415 
```
public static void my(int a) {
a = 4 / 2;
}
}
|--IDENT -> Tester [2:13]
`--OBJBLOCK -> OBJBLOCK [2:20]
|--LCURLY -> { [2:20]
|   |   `--LITERAL_STATIC -> static [3:8]
|   |--TYPE -> TYPE [3:15]
|   |   `--LITERAL_VOID -> void [3:15]
|   |--IDENT -> my [3:20]
|   |--LPAREN -> ( [3:22]
|   |--PARAMETERS -> PARAMETERS [3:23]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:23]
|   |       |--MODIFIERS -> MODIFIERS [3:23]
|   | …
```
> Issue #9415: Added Example of AST for TokenTypes.DIV

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9402 
```
>cat Test.java
a=a|b;
}
}
|   |   |--COMMA -> …
```
> Issue #9402: Added example of AST for TokenTypes.BOR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes : #9373 
```
$ javac Test.java 
$ 
a=b;
}
}
$ java -jar checkstyle-8.38-all.jar -t Test.java
|   |   |   `--IDENT -> a …
```
> Issue #9373: updated example of AST for TokenTypes.ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9414 
```
public static void my(int a) {
--a;
}
}
|--IDENT -> Tester [2:13]
`--OBJBLOCK -> OBJBLOCK [2:20]
|--LCURLY -> { [2:20]
|   |   `--LITERAL_STATIC -> static [3:8]
|   |--TYPE -> TYPE [3:15]
|   |   `--LITERAL_VOID -> void [3:15]
|   |--IDENT -> my [3:20]
|   |--LPAREN -> ( [3:22]
|   |--PARAMETERS -> PARAMETERS [3:23]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:23]
|   |       |--MODIFIERS -> MODIFIERS [3:23]
|   | …
```
> Issue #9414: Added Example of AST for TokenTypes.DEC

- src/main/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheck.java
- src/xdocs/config_blocks.xml
Closes: #7581
`$ cat Hello.java`
```
class Hello {
try {
}
catch(Exception e) { // violation since catch block is empty
}
}
}
```
```
<module name="EmptyCatchBlock"/>
</module>
</module>
```
Output:
```
$ java -jar checkstyle-8.39-all.jar -c config.xml Hello.java
[ERROR] E:\New folder\Java Dev\src\com\company\Hello.java:10:9: Empty catch block. [EmptyCatchBlock]
Audit done.
```
> Issue #7581: Add default config and code examples for EmptyCatchBlock

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/ModifiedControlVariableCheck.xml
- src/xdocs/config_coding.xml
Closes: #7649
```
<property name="tabWidth" value="7"/>
<module name="ModifiedControlVariable"/>
</module>
</module>
```
```
class Demo {
{
for(int i=0;i<8;i++)
{
i++; // violation
}
}
}
```
Output:-
```
$ java -jar checkstyle-8.39-all.jar -c config.xml Demo.java
[ERROR] E:\New folder\Java Dev\src\com\company\Demo.java:8:14: Control variable 'i' is modified. [ModifiedControlVariable]
Audit done.
```
```
"-//Checkstyle//DTD Checkstyle …
```
> Issue #7649: Update doc for ModifiedControlVariable

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9591
```
**Test.java**
List<? extends Number> list;
}
**AST**
|--VARIABLE_DEF -> VARIABLE_DEF [2:1]
|   |   |--IDENT -> List [2:1]
|   |   `--TYPE_ARGUMENTS -> TYPE_ARGUMENTS [2:5]
|   |       |--GENERIC_START -> < [2:5]
|   |       |--TYPE_ARGUMENT -> TYPE_ARGUMENT [2:6]
|   |       |   |--WILDCARD_TYPE -> ? [2:6]
|   |       |   `--TYPE_UPPER_BOUNDS -> extends [2:8]
|   |       |       `--IDENT -> Number [2:16]
|   | …
```
> Issue #9591: add example of AST for TokenType.TYPE_UPPER_BOUNDS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9572 
```
>cat Test.java
a>>=b;
}
}
|   |   |--COMMA -> …
```
> Issue #9572: Added example of AST for TokenTypes.SR_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9578
```
**Test.java**
void Test() {
String str = "StringLiteral";
}
}
**AST**
|   |--IDENT -> Test [2:6]
|       |   |--MODIFIERS -> MODIFIERS [3:2]
|       |   |--TYPE -> TYPE [3:2]
| …
```
> Issue #9578: add example of AST for TokenTypes.STRING_LITERAL

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9555 
```
>cat Test.java
a+=b;
}
} …
```
> Issue #9555: Added example of AST for TokenTypes.PLUS_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9416 
```
>cat Test.java
a/=b;
}
} …
```
> Issue #9416: Added example of AST for TokenTypes.DIV_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9405 
```
>cat Test.java
a>>>=b;
}
}
|   |   |--COMMA -> …
```
> Issue #9405: Added example of AST for TokenTypes.BSR_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9398 
```
>cat Test.java
a&=b;
}
} …
```
> Issue #9398: Added example of AST for TokenTypes.BAND_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9569 
```
>cat Test.java
a=a<<b;
}
}
| …
```
> Issue #9569: Added example of AST for TokenTypes.SL

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9571 
```
>cat Test.java
a=a>>b;
}
}
|   |   |--COMMA -> …
```
> Issue #9571: Added example of AST for TokenTypes.SR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9574 
```
>cat Test.java
a*=b;
}
} …
```
> Issue #9574: Added example of AST for TokenTypes.STAR_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9516 
```
>cat Test.java
a-=b;
}
} …
```
> Issue #9516: Added example of AST for TokenTypes.MINUS_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9554 
```
C:\Users\Shashwat>cat Test.java
void foo(long a) {
a--;
}
}
|   |       |   `--LITERAL_LONG -> long [2:13]
|   |       `--IDENT -> a …
```
> Issue #9554: Added example of AST for TokenTypes.POST_DEC

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9588
```
**Test.java**
import java.util.List;
List<? super Integer> list;
}
**AST**
|   `--IDENT -> List [1:17]
`--SEMI -> ; [1:21]
|--VARIABLE_DEF -> VARIABLE_DEF [4:1]
|   |--TYPE -> TYPE [4:1]
|   |   |--IDENT -> List [4:1]
|   |   `--TYPE_ARGUMENTS -> TYPE_ARGUMENTS [4:5]
|   |       |--GENERIC_START …
```
> Issue #9588: add code example of AST for TokenTypes.TYPE_LOWER_BOUNDS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9518 
```
**Test.java**
void test() {
int a = 5;
a %= 2;
}
}
**AST**
|       |   |--MODIFIERS -> MODIFIERS [3:2]
|       |   |--TYPE -> TYPE [3:2]
| …
```
> Issue #9518: add code example of AST for TokenTypes.MOD_ASSIGN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9394 
Expected update example of AST for TokenTypes.ARRAY_DECLARATOR
> Issue #9394: update example of AST for TokenTypes.ARRAY_DECLARATOR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9512
```
**Test.java**
void test() {
Integer.parseInt("123");
}
}
**AST**
|       |--EXPR -> EXPR [3:18]
|       |   `--METHOD_CALL -> ( [3:18]
|       |       |--DOT -> . [3:9]
|       |       |   |--IDENT -> Integer …
```
> Issue #9512: update code example of AST for TokenTypes.METHOD_CALL

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9573
```
$ javac Star.java
$ cat Star.java
class Star {
void foo(int a, int f, int m) {
f = m * a;
}
}
$ java -jar checkstyle-8.41-all.jar -t Star.java 
|--IDENT -> Star [1:6]
|   |   |--COMMA -> , [2:18]
|   | …
```
> Issue #9573: Added Example of AST for TokenTypes.STAR

- src/main/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/TrailingCommentCheck.xml
- src/xdocs/checks.xml
- src/xdocs/config_misc.xml
> Issue #9643: fix summary description for TrailingComment

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9543 
```
public static boolean my(int a, int b) {
return a != b;
}
}
|--IDENT -> Tester [2:13]
`--OBJBLOCK -> OBJBLOCK [2:20]
|--LCURLY -> { [2:20]
|   |   `--LITERAL_STATIC -> static [3:8]
|   |--TYPE -> TYPE [3:15]
|   |   `--IDENT -> Boolean [3:15]
|   |--IDENT -> test [3:23]
|   |--LPAREN -> ( [3:27]
|   |--PARAMETERS -> PARAMETERS [3:28]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [3:28]
|   |   |   |--MODIFIERS -> MODIFIERS …
```
> Issue #9543: Added Example of AST for TokenTypes.NOT_EQUAL

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java
> Issue #9678: fix build problem in IDEA with sun package

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9497 :
```
anmolsharma@Anmols-MacBook-Pro GSOC % java -jar checkstyle-8.41-all.jar -t MyClass.java
|--IDENT -> Myclass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:13]
|--LCURLY -> { [1:13]
|   |   |--LITERAL_PUBLIC -> public [2:4]    |   |   `--LITERAL_STATIC -> static [2:11]
|   |--PARAMETERS -> PARAMETERS [2:39]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:39]
|   |       |--MODIFIERS -> MODIFIERS [2:39]
|   |       |--TYPE -> TYPE [2:39]
|   |       |   `--ARRAY_DECLARATOR -> [ [2:39]
|   |       | …
```
> Issue #9497: updated example of AST for TokenTypes.LITERAL_SYNCHRONIZED

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9452 
```
anmolsharma@Anmols-MacBook-Pro GSOC % java -jar checkstyle-8.41-all.jar -t MyClass.java
|   `--IDENT -> IOException [1:15]
|--LITERAL_CLASS -> class [2:0]
|--IDENT -> Myclass [2:6]
`--OBJBLOCK -> OBJBLOCK [2:13]
|--LCURLY -> { [2:13]
|   |   |--LITERAL_PUBLIC -> public [3:4]
|   |   `--LITERAL_STATIC -> static [3:11]
|   |--TYPE -> TYPE [3:18]
|   |   `--LITERAL_VOID -> void [3:18]
|   |--IDENT -> main [3:23]
|   |--LPAREN -> ( [3:27]
|   |--PARAMETERS -> PARAMETERS [3:39]
|   |   `--PARAMETER_DEF -> …
```
> Issue #9452: updated example of AST for TokenTypes.IMPORT

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/TryHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTryBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationTryBlockWithResources.java
Fixes #9341 
*This is an extension to the solution of https://github.com/checkstyle/checkstyle/issues/9236*
Diff Regression projects: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/29775c9e897e152f5cda2bdcc8cadfe57690d1a7/project-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/29775c9e897e152f5cda2bdcc8cadfe57690d1a7/my_check.xml
Report label: Default Indentation profile with force Strict
> Issue #9341: Fix Try child suggesting wrong indentation level

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9584
```
class Demo{
{
boolean var=true;
}
}
```
`$ java -jar checkstyle-8.39-all.jar -t Demo.java`
```
|--IDENT -> Demo [1:6]
|--METHOD_DEF -> METHOD_DEF [2:0]
|   |--MODIFIERS -> MODIFIERS [2:0]
|   |   |--LITERAL_PUBLIC -> public [2:0]
|   |   `--LITERAL_STATIC -> static [2:7]
|   |--TYPE -> TYPE [2:14]
|   |   `--LITERAL_VOID -> void [2:14]
|   |--IDENT -> main [2:19]
|   |--LPAREN -> ( [2:23]
|   |--PARAMETERS -> PARAMETERS [2:35]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:35]
|   |       |--MODIFIERS -> MODIFIERS [2:35]
|   |       |--TYPE -> TYPE [2:35]
|   |       | …
```
> Issue #9584: update example of AST for TokenTypes.TYPE

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9404 
```
public static void test(int a, int b) {
a >>> b;
}
}
|--IDENT -> Tester [1:13]
|   |--IDENT -> test [2:20]
|   |--PARAMETERS -> PARAMETERS [2:25]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [2:25]
|   |   |   |--MODIFIERS -> MODIFIERS …
```
> Issue #9404: Added Example of AST for TokenTypes.BSR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9561 
```
anmolsharma@Anmols-MacBook-Pro GSOC % java -jar checkstyle-8.41-all.jar -t MyClass.java | grep "2:"
|--RECORD_DEF -> RECORD_DEF [2:4]
|   |--LITERAL_RECORD -> record [2:11]
|   |--IDENT -> myRecord [2:18]
|   |--RECORD_COMPONENTS -> RECORD_COMPONENTS [2:28]
|   |   |--RECORD_COMPONENT_DEF -> RECORD_COMPONENT_DEF [2:28]
|   |   |   |--ANNOTATIONS -> ANNOTATIONS [2:28]
|   |   |   |--TYPE -> TYPE [2:28]
|   |   |   |   `--IDENT -> Comp [2:28]
|   |   |   `--IDENT -> x [2:33]
|   |   |--COMMA -> , [2:34]
|   |   `--RECORD_COMPONENT_DEF -> RECORD_COMPONENT_DEF [2:36]
|   |       |--ANNOTATIONS -> ANNOTATIONS [2:36]
|   |       |--TYPE -> TYPE [2:36]
|   |       |   `--IDENT …
```
> Issue #9561: updated example of AST for TokenTypes.RECORD_COMPONENTS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9417 
```
public static void test(int a) {
do {
} while (a > 0);
}
}
|--IDENT -> Tester [1:13]
|   |--IDENT -> test [2:20]
|   |--PARAMETERS -> PARAMETERS [2:25]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:25]
|   |       |--MODIFIERS -> MODIFIERS …
```
> Issue #9417: Added Example of AST for TokenTypes.DO_WHILE

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9589 
```
anmolsharma@Anmols-MacBook-Pro GSOC % java -jar checkstyle-8.41-all.jar -t MyClass.java
|   `--IDENT -> IOException [1:15]
IMPORT -> import [2:0]
|--DOT -> . [2:16]
|   |--DOT -> . [2:11]
|   |   |--IDENT -> java [2:7]
|   |   `--IDENT -> util [2:12]
|   `--IDENT -> Collection [2:17]
`--SEMI -> ; [2:27]
|--LITERAL_CLASS -> class [3:0]
|--IDENT -> Myclass [3:6]
`--OBJBLOCK -> OBJBLOCK [3:13]
|--LCURLY -> { [3:13]
|--METHOD_DEF -> METHOD_DEF [4:4]
|   |--MODIFIERS -> MODIFIERS [4:4]
|   |   |--LITERAL_PUBLIC -> public [4:4]
|   |   `--LITERAL_STATIC -> static [4:11]
| …
```
> Issue #9589: updated example of AST for TokenTypes.TYPE_PARAMETER

- src/it/java/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/OperatorWrapTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputOperatorWrap.java
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllChecksTest.java
Fixes #4122 
PR description moved to https://github.com/checkstyle/checkstyle/issues/4122#issuecomment-801119194
> Issue #4122: Reevaluate tokens for OperatorWrapCheck in Google config

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes #9480 : 
```
String message = "";
boolean optimistic = true;
if(optimistic) {
message = "half full";
}
else {
message = "half empty";
}
}
}
```
Generated AST:
```
CLASS_DEF -> CLASS_DEF [9:0]
|--MODIFIERS -> MODIFIERS [9:0]
|   `--LITERAL_PUBLIC -> public [9:0]
|--LITERAL_CLASS -> class [9:7]
|--IDENT -> MyClass [9:13]
`--OBJBLOCK -> OBJBLOCK [9:21]
|--LCURLY -> { [9:21]
|--METHOD_DEF -> METHOD_DEF [10:4]
|   |--MODIFIERS -> MODIFIERS [10:4]
|   |   |--LITERAL_PUBLIC -> public [10:4]
|   |   `--LITERAL_STATIC -> static [10:11]
|   |--TYPE -> TYPE [10:18]
|   |   `--LITERAL_VOID -> void [10:18]
|   |--IDENT -> main [10:23]
|   |--LPAREN -> ( [10:27]
|   |--PARAMETERS -> PARAMETERS [10:39]
| …
```
> Issue #9480: updated example of AST for TokenTypes.LITERAL_IF

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9581 
```
String example = """
Hello, World!
""";
}
java -jar checkstyle-8.41-all.jar -t Test.java
|--IDENT -> MyClass [3:13]
`--OBJBLOCK -> OBJBLOCK [3:21]
|--LCURLY -> { [3:21]
|--VARIABLE_DEF -> VARIABLE_DEF [4:4]
|   |--MODIFIERS -> MODIFIERS [4:4]
|   |--TYPE -> TYPE [4:4]
|   |   `--IDENT -> String [4:4]
|   |--IDENT -> example [4:11]
|   |--ASSIGN -> = [4:19]
|   |   `--EXPR -> EXPR [4:21]
|   |       `--TEXT_BLOCK_LITERAL_BEGIN -> """ [4:21]
|   |           |--TEXT_BLOCK_CONTENT -> \n            Hello, World!\n             [4:24]
|   |           `--TEXT_BLOCK_LITERAL_END -> """ [6:12]
|   `--SEMI -> ; [6:15]
`--RCURLY …
```
> Issue #9581: updated example of AST for TokenTypes.TEXT_BLOCK_CONTENT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9575 
```java
import static java.io.IOException;
}
```
```sh
$ java -jar checkstyle-8.40-SNAPSHOT-all.jar -t Test.java            
STATIC_IMPORT -> import [1:0]
|--LITERAL_STATIC -> static [1:7]
|--DOT -> . [1:21]
|   |--DOT -> . [1:18]
|   |   |--IDENT -> java [1:14]
|   |   `--IDENT -> io [1:19]
|   `--IDENT -> IOException [1:22]
`--SEMI -> ; [1:33]
`--RCURLY -> } [3:19]
#Relevant AST Nodes for STATIC_IMPORT
$ java -jar checkstyle-8.40-SNAPSHOT-all.jar -T Test.java | grep 1:  
STATIC_IMPORT -> import [1:0]
|--LITERAL_STATIC -> static …
```
> Issue #9575: Update example of AST for TokenTypes.STATIC_IMPORT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9418 
```
class Person {
String name;
}
public String getName(Person person) {
return person.name;
}
}
|--IDENT -> Tester [1:13]
|--CLASS_DEF -> CLASS_DEF [3:1]
|   |--LITERAL_CLASS -> class [3:1]
|   |--IDENT -> Person [3:7]
|   `--OBJBLOCK -> OBJBLOCK [3:14]
|       |--LCURLY -> { [3:14]
|       |--VARIABLE_DEF -> VARIABLE_DEF [4:2]
|       |   |--MODIFIERS -> MODIFIERS [4:2]
|       |   |--TYPE -> TYPE [4:2]
|       |   |   `--IDENT -> String [4:2]
| …
```
> Issue #9418: Added Example of AST for TokenTypes.DOT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9567
```
class Demo
{
{
for(;;);
}
}
```
`$ java -jar checkstyle-8.39-all.jar -t Demo.java`
```
|--IDENT -> Demo [1:6]
`--OBJBLOCK -> OBJBLOCK [2:0]
|--LCURLY -> { [2:0]
|   |   |--LITERAL_PUBLIC -> public [3:4]
|   |   `--LITERAL_STATIC -> static [3:11]
|   |--TYPE -> TYPE [3:18]
|   |   `--LITERAL_VOID -> void [3:18]
|   |--IDENT -> main [3:23]
|   |--LPAREN -> ( [3:27]
|   |--PARAMETERS -> PARAMETERS [3:39]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:39]
|   |       |--MODIFIERS -> MODIFIERS [3:39]
|   |       |--TYPE -> TYPE [3:39]
|   |       | …
```
> Issue #9567: update example of AST for TokenTypes.SEMI

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9570
`$ cat Demo.java
`
```
class Demo{
{
int c=1;
if (c == 1) {
c = 0;
}
}
}
```
`$ java -jar checkstyle-8.39-all.jar -t Demo.java`
```
|--IDENT -> Hello [1:6]
`--OBJBLOCK -> OBJBLOCK [2:0]
|--LCURLY -> { [2:0]
|   |   |--LITERAL_PUBLIC -> public [3:4]
|   |   `--LITERAL_STATIC -> static [3:11]
|   |--TYPE -> TYPE [3:18]
|   |   `--LITERAL_VOID -> void [3:18]
|   |--IDENT -> main [3:23]
|   |--LPAREN -> ( [3:27]
|   |--PARAMETERS -> PARAMETERS [3:39]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [3:39]
|   |       |--MODIFIERS -> MODIFIERS [3:39]
|   |       |--TYPE -> TYPE [3:39]
| …
```
> Issue #9570: update example of AST for TokenTypes.SLIST

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/singlelinejavadoc/InputSingleLineJavadocIgnoredTags.java
> Issue #9532: Updated SingleLineJavadocCheckTest to use unique Input file in each test method

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue #9515: update example of AST for TokenTypes.MINUS
> Issue #9515

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9576 
```java
static int num;
static {
num = 10;
// Inside Static Initialisation Block
}
}
```
`$ java -jar checkstyle-8.40-SNAPSHOT-all.jar -T Test.java`
```sh
|--VARIABLE_DEF -> VARIABLE_DEF [3:2]
|   |--MODIFIERS -> MODIFIERS [3:2]
|   |   `--LITERAL_STATIC -> static [3:2]
|   |--TYPE -> TYPE [3:9]
|   |   `--LITERAL_INT -> int [3:9]
|   |--IDENT -> num [3:13]
|   `--SEMI -> ; [3:16]
|--STATIC_INIT -> STATIC_INIT [5:2]
|   `--SLIST -> { [5:9]
|       |--EXPR -> EXPR [6:8]
|       |   `--ASSIGN -> = [6:8]
|       |       |--IDENT -> num …
```
> Issue #9576: Update example of AST for TokenTypes.STATIC_INIT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9506 : 
```
int i = 0;
while (i < 5) {
i++;
}
}
}
```
Generated AST:
```
|   |--PARAMETERS -> PARAMETERS [2:39]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:39]
|   |       |--MODIFIERS -> MODIFIERS [2:39]
|   | …
```
> Issue #9506: updated example of AST for TokenTypes.LITERAL_WHILE

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Close: #9410 
Generated javadoc:
Code sample:
```
$ javac ~/Test9410.java
$ cat ~/Test9410.java
public class Test9410 {
public static void doSomething() {
int a, b;
}
}
```
Relevant AST:
```
$ java -jar target/checkstyle-8.42-SNAPSHOT-all.jar -t ~/Test9410.java | grep "3:"
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:4]
|       |   |--MODIFIERS -> MODIFIERS [3:4]
|       |   |--TYPE -> TYPE [3:4]
|       |   |   `--LITERAL_INT -> int [3:4]
|       |   `--IDENT -> a [3:8]
|       |--COMMA -> , [3:9]
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:4]
|       |   |--MODIFIERS -> MODIFIERS [3:4]
|       |   |--TYPE -> TYPE [3:4]
|       |   |   `--LITERAL_INT -> int [3:4]
|       |   `--IDENT -> b [3:11]
|       |--SEMI -> ; [3:12]
```
Expected javadoc update:
```
|--VARIABLE_DEF -> VARIABLE_DEF
| …
```
> Issue #9410: create example of AST for TokenTypes.COMMA

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9548 
**Test.java**
```
class Test {}
```
**AST**
```
`--RCURLY -> } [1:12]
```
```
|--LCURLY -> {
`--RCURLY -> }
```
> Issue #9548: add code example of AST for TokenTypes.OBJBLOCK

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowStaticMember.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportExcludes.java
> Issue #9741: update AvoidStarImportCheckTest to use unique Input file in each test method

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9413 
Preview of Page after update
File used to generate AST:
```
$ cat Test.java                    
public class Test { 
public SpecialEntry(int value, String text)
{
this.value = value;
this.text = text;
}
}
```
Generated AST:
```
$ java -jar checkstyle-8.42-SNAPSHOT-all.jar -T Test.java
CLASS_DEF -> CLASS_DEF [1:1]
|--MODIFIERS -> MODIFIERS [1:1]
|   `--LITERAL_PUBLIC -> public [1:1]
|--LITERAL_CLASS -> class [1:8]
|--IDENT -> Test [1:14]
`--OBJBLOCK -> OBJBLOCK [1:19]
|--LCURLY -> { [1:19]
|--CTOR_DEF -> CTOR_DEF [2:2]
|   |   `--LITERAL_PUBLIC -> public [2:2]
|   |--IDENT -> SpecialEntry [2:9]
|   |--LPAREN -> ( [2:21]
|   |--PARAMETERS -> PARAMETERS [2:22]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [2:22]
|   |   |   |--MODIFIERS -> …
```
> Issue #9413: Update Example of AST for TokenTypes.CTOR_DEF

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9563
Code used for test: 
```
mahmoud:~/Desktop/checkstyle$ more Test.java 
public class A {
public void b {
try (Foo foo = new Foo(); Bar bar = new Bar()) { }
} 
}
```
Generated AST:
```
mahmoud:~/Desktop/checkstyle$ java -jar checkstyle-8.41-all.jar -T Test.java 
|--IDENT -> A [2:13]
`--OBJBLOCK -> OBJBLOCK [2:15]
|--LCURLY -> { [2:15]
|--VARIABLE_DEF -> VARIABLE_DEF [3:4]
|   |   `--LITERAL_PUBLIC -> public [3:4]
|   |--TYPE -> TYPE [3:11]
|   |   `--LITERAL_VOID -> void [3:11]
|   `--IDENT -> b [3:16]
|--INSTANCE_INIT -> INSTANCE_INIT [3:18]
|   `--SLIST -> { [3:18]
|       |--LITERAL_TRY -> try [4:5]
|       | …
```
> Issue #9563: update example of AST for TokenTypes.RESOURCE

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckOnDifferentTokens.java
> Issue #9522: Update AnnotationOnSameLineCheckTest to use unique input files

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9580
Generated javadoc:
Code sample:
```
$ javac ~/Test.java
$ cat ~/Test.java
public static String test(Day day) {
return switch (day) {
case SAT, SUN -> "Weekend";
default -> "Working day";
};
}
enum Day {
SAT,
SUN,
OTHER
}
}
```
Relevant AST:
```
|       |--LITERAL_RETURN -> return [4:4]
|       |   |--EXPR -> EXPR [4:11]
|       |   |   `--LITERAL_SWITCH -> switch [4:11]
|       |   |       |--LPAREN -> ( [4:18]
|       |   |       |--EXPR -> EXPR [4:19]
|       |   |       |   `--IDENT -> day [4:19]
|       |   |       |--RPAREN -> ) [4:22]
|       |   |       |--LCURLY -> { [4:24]
|       |   |       |--SWITCH_RULE -> SWITCH_RULE [5:6]
|       |   |       |   |--LITERAL_CASE -> case [5:6]
|       |   |       |   |   |--EXPR -> EXPR [5:11]
|       |   | …
```
> Issue #9580: update example of AST for TokenTypes.SWITCH_RULE

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountCtorDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountDefaultConfig.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountInstanceInit.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountMaxZero.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountMethodDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountStaticInit.java
> Issue #9736: update ExecutableStatementCountCheckTest to use unique Input file in each test method

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9553
```
>cat Test.java
void foo(int a, int b, int c) {
c=a+b;
}
}
|   | …
```
> Issue #9553: update example of AST for TokenTypes.PLUS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9470
Code used for generating example:
```
mahmoud:/data/checkstyle/checkstyle test$ more Test.java 
public class A {
public void b {
for (int i = 0; i < 5; i++) {
continue;
}
}
}
```
Output:
```
mahmoud:/data/checkstyle/checkstyle test$ java -jar checkstyle-8.41-all.jar -t Test.java 
|--IDENT -> A [1:13]
`--OBJBLOCK -> OBJBLOCK [1:15]
|--LCURLY -> { [1:15]
|   |   `--LITERAL_VOID -> void [2:11]
|   `--IDENT -> b [2:16]
|--INSTANCE_INIT -> INSTANCE_INIT [2:18]
|   `--SLIST -> { [2:18]
|       |--LITERAL_FOR -> …
```
> Issue #9470: update example of AST for TokenTypes.LITERAL_CONTINUE

- src/test/java/com/puppycrawl/tools/checkstyle/xpath/AttributeNodeTest.java
Closes #9784
Sevntu PR: https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/834
contribution PR: https://github.com/checkstyle/contribution/pull/552
> Issue #9784: Prefer method reference above lambda expressions

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue: #9586
```
➜ src cat Test.java                                       
import java.util.Collection;
public Collection<?> a;
}
➜ src java -jar checkstyle-8.41-all.jar -t Test.java 
|   `--IDENT -> Collection [1:17]
`--SEMI -> ; [1:27]
|--VARIABLE_DEF -> VARIABLE_DEF [4:4]
|   |--MODIFIERS -> MODIFIERS [4:4]
|   |   `--LITERAL_PUBLIC -> public [4:4]
|   |--TYPE -> TYPE [4:11]
|   |   |--IDENT -> Collection [4:11]
|   | …
```
> Issue #9586: update example of AST for TokenTypes.TYPE_ARGUMENTS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9502
Code used for generating example:
```
mahmoud:/data/checkstyle/checkstyle test$ more Test.java 
public class A {
public void b {
boolean a = true;
}
}
```
Output:
```
mahmoud:/data/checkstyle/checkstyle test$ java -jar checkstyle-8.41-all.jar -t Test.java 
|--IDENT -> A [2:13]
`--OBJBLOCK -> OBJBLOCK [2:15]
|--LCURLY -> { [2:15]
|--VARIABLE_DEF -> VARIABLE_DEF [3:4]
|   |   `--LITERAL_PUBLIC -> public [3:4]
|   |--TYPE -> TYPE [3:11]
|   |   `--LITERAL_VOID -> void [3:11]
|   `--IDENT -> b [3:16]
|--INSTANCE_INIT -> INSTANCE_INIT [3:18]
|   `--SLIST -> { [3:18]
|       |--VARIABLE_DEF -> VARIABLE_DEF [4:5]
| …
```
> Issue #9502: update example of AST for TokenTypes.LITERAL_TRUE

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9565
**Test.java**
```
public void test() throws IOException {
try (FileReader fr = new FileReader("config.xml")) {
} finally {}
}
}
```
**AST**
```
|--METHOD_DEF -> METHOD_DEF [4:1]
|   |   `--LITERAL_PUBLIC -> public [4:1]
|   |--TYPE -> …
```
> Issue #9565: add example of AST for TokenTypes.RESOURCES

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameCustom.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameFormerFalsePositive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameType.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameVariants.java
fixes Issue #9746:
update some basic changes make unique input files for each and every class method of AbstractClassNameCheckTest.java
> Issue #9746: update AbstractClassNameCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9390 
**Test.java**
```
@interface Annotation {
int[] value() default {3, 4, 5};
}
@Annotation({1, 2})
public class Test {}
```
**AST**
```
ANNOTATION_DEF -> ANNOTATION_DEF [1:0]
|--AT -> @ [1:0]
|--LITERAL_INTERFACE -> interface [1:1]
|--IDENT -> Annotation [1:11]
`--OBJBLOCK -> OBJBLOCK [1:22]
|--LCURLY -> { [1:22]
|--ANNOTATION_FIELD_DEF -> ANNOTATION_FIELD_DEF [2:3]
|   |--MODIFIERS -> MODIFIERS [2:3]
|   |--TYPE -> TYPE [2:3]
|   |   `--ARRAY_DECLARATOR -> [ [2:3]
|   |       |--LITERAL_INT -> int [2:0]
|   |       `--RBRACK -> ] [2:4]
|   |--IDENT -> value [2:6]
|   |--LPAREN -> ( [2:11]
|   |--RPAREN -> ) [2:12]
|   |--LITERAL_DEFAULT -> default …
```
> Issue #9390: update example of AST for TokenTypes.ANNOTATION_ARRAY_INIT

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespaceAround.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespaceTestSpace.java
> Issue #9814: update TypecastParenPadCheckTest.java to use unique input files

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9511
**Test.java**
```
void test() {
int a = 5, b = 10;
boolean c;
c = a < b;
}
}
```
**AST**
```
|       |   |--MODIFIERS -> MODIFIERS [3:2]
| …
```
> Issue #9511: add code example of AST for TokenTypes.LT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Issue: #9471:
```
public class MyClass{
void foo(){
int type=3,x=0;
switch(type)
{
case 1:
x = 1;
break;
default:
x = 2;
}
}
}
```
Generated AST:
```
|   `--SLIST -> { [2:12]
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:4]
|       |   |--MODIFIERS -> MODIFIERS [3:4]
|       |   |--TYPE -> TYPE [3:4]
|       | …
```
> Issue #9471: update example of  TokenTypes.LITERAL_DEFAULT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9558
```
class Demo
{
{
int a[];
}
} 
```
`$ java -jar checkstyle-8.41-all.jar -t Demo.java
`
```
|--LITERAL_CLASS -> class [2:0]
|--IDENT -> Demo [2:6]
`--OBJBLOCK -> OBJBLOCK [3:0]
|--LCURLY -> { [3:0]
|--METHOD_DEF -> METHOD_DEF [4:4]
|   |--MODIFIERS -> MODIFIERS [4:4]
|   |   |--LITERAL_PUBLIC -> public [4:4]
|   |   `--LITERAL_STATIC -> static [4:11]
|   |--TYPE -> TYPE [4:18]
|   |   `--LITERAL_VOID -> void [4:18]
|   |--IDENT -> main [4:23]
|   |--LPAREN -> ( [4:27]
|   |--PARAMETERS -> PARAMETERS [4:39]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [4:39]
|   |       |--MODIFIERS -> MODIFIERS [4:39]
|   |       |--TYPE -> TYPE [4:39]
|   |       | …
```
> Issue #9558: update example of AST for TokenTypes.RBRACK

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9508
Java code used to generate AST :
<pre>
<code>
public static void main(String[] args)
{
boolean a, b = false;
a = ! b;
System.out.println(a);
}
}
</pre>
</code>
Java code used to generate AST :
<pre>
<code>
CLASS_DEF -> CLASS_DEF [1:0]   
|--IDENT -> MyClass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:14]
|--LCURLY -> { [1:14]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:34]
|   |       |--MODIFIERS …
> Issue #9508: Updated example of AST for TokenTypes.LNOT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
I have updated the TokenTypes.java file according to Issue #9596 
I used that code to generate AST : 
**123.java :** 
```
class Test{
public static void main(String[] args){
List<String> list = new ArrayList<>();
}
}
```
**Command :** 
```
java -jar checkstyle-8.41.1-all.jar -t 123.java
|   |   `--PARAMETER_DEF -> …
```
> Issue #9596: Added Example of AST for TokenTypes.WILDCARD

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9461 
Java code used to generate AST:
<pre>
public static void main (String[] args)
{
int a = 5 , b = 10;  boolean c;
c = a <= b;
System.out.println(c);
}
}
</pre>
Generated AST:
<pre>
|--IDENT -> MyClass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:13]
|--LCURLY -> { [1:13]
|   |--LPAREN -> ( [2:28]
|   |--PARAMETERS -> PARAMETERS [2:35]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:35]
|   |       |--MODIFIERS -> MODIFIERS [2:35]
|   | …
> Issue #9461: Updated example of AST for TokenTypes.LE

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9585
```
>cat Test.java
import java.util.List;
List<? super List> list;
}
> java -jar checkstyle-8.41-all.jar -t Test.java
|   `--IDENT -> List [1:17]
`--SEMI -> ; [1:21]
|--VARIABLE_DEF -> VARIABLE_DEF [4:1]
|   |--TYPE -> TYPE [4:1]
|   |   |--IDENT -> List [4:1]
|   |   `--TYPE_ARGUMENTS -> TYPE_ARGUMENTS [4:5]
|   |       |--GENERIC_START -> < [4:5]
|   |       |--TYPE_ARGUMENT -> …
```
> Issue #9585: update example of AST for TokenTypes.TYPE_ARGUMENT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9510
```
void foo(){
Integer val = new Integer();
while (false) {
val += (-3);
}
}
}
```
```
$ java -jar checkstyle-8.40-all.jar -t Test.java  
|   |--TYPE -> TYPE [3:4]
|   |   `--LITERAL_VOID -> void [3:4]
|   |--IDENT -> foo [3:9]
|   |--LPAREN -> ( [3:12]
|   |--PARAMETERS -> PARAMETERS [3:13]
|   |--RPAREN -> ) [3:13]
|   `--SLIST -> { [3:15]
|       |--VARIABLE_DEF -> VARIABLE_DEF [4:8]
|       |   |--MODIFIERS -> MODIFIERS [4:8]
|       |   |--TYPE -> TYPE [4:8]
| …
```
> Issue #9510: update example of AST for TokenTypes.LPAREN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9442
**Test.java**
```
void test() {
int[] arr = {1, 2, 3};
for (int i = 0; i < arr.length; i++) {}
}
}
```
**AST**
```
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:5]
|       |   |--MODIFIERS …
```
> Issue #9442: add code example of AST for TokenTypes.FOR_CONDITION

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9444 
**Test.java**
```
void test() {
int[] arr = {1, 2, 3};
for (int i = 0; i < arr.length; i++) {}
}
}
```
**AST**
```
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:5]
|       | …
```
> Issue #9444: add code example of AST for TokenTypes.FOR_INIT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9479
**Test.java**
```
void test() {
int[] arr = {1, 2, 3};
for (int i = 0; i < arr.length; i++) {}
}
}
```
**AST**
```
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:5]
|       |   |--MODIFIERS …
```
> Issue #9479: update example of AST for TokenTypes.LITERAL_FOR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9445
**Test.java**
```
void test() {
int[] arr = {1, 2, 3};
for (int i = 0; i < arr.length; i++) {}
}
}
```
**AST**
```
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:5]
|       |   |--MODIFIERS …
```
> Issue #9445: add code example of AST for TokenTypes.FOR_ITERATOR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes : #9557 
$ javac test.java
public class test {
public static void main() {
int quantity=0;
String variable=(quantity==1)?"true":"false";
}
}
$ java -jar checkstyle-8.41-all.jar -T test.java
|--IDENT -> test [1:13]
|--METHOD_DEF -> METHOD_DEF [2:0]
|   |--MODIFIERS -> MODIFIERS [2:0]
|   |   |--LITERAL_PUBLIC -> public [2:0]
|   |   `--LITERAL_STATIC -> static [2:7]
|   |--TYPE -> TYPE [2:14]
|   |   `--LITERAL_VOID -> void [2:14]
|   |--IDENT -> main [2:19]
|   |--LPAREN -> ( [2:23]
|   |--PARAMETERS -> PARAMETERS [2:24]
|   |--RPAREN -> ) [2:24]
|   `--SLIST -> { [2:25]
| …
> updated example of AST for TokenTypes.QUESTION

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
This PR fixes failing master build from https://github.com/checkstyle/checkstyle/commit/6fe80257a5368a435b2bdea4fb21c2fb4d0f4364
> minor: fix '->' in QUESTION token Javadoc

- .ci/no-exception-test.sh
- .ci/wercker.sh
Noticed at https://github.com/checkstyle/checkstyle/pull/9728#discussion_r612384004, we need to change the repo to the patch branch (PR branch).
> infra: fix branch in no-exception tests

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/whitespacearound/InputWhitespaceAroundAllowEmptyCompactCtors.java
- src/xdocs/config_whitespace.xml
Resolves #8237: fixing no whitespace violation in empty constructors
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/85355576c05c80e8b08752a62ba3a4076909d266/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/896bb68507934031a5ab4b785e093b7a31e684a8/my_checks.xml
Diff Regression patch config: https://gist.githubusercontent.com/Vyom-Yadav/273327b9c6cd6963b7dade792bc2c9c2/raw/88c882407bd3891076de4461f058b6ccc7fa8630/patch_config.xml
Report label: Final report.
> Issue #8237: fixing no whitespace violation in empty constructors

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9429
**Test.java**
```
public class Test extends ArrayList {
}
```
**AST**
```
|   `--IDENT -> ArrayList [1:17]
|--EXTENDS_CLAUSE -> extends [3:18]
|   `--IDENT -> ArrayList [3:26]
`--OBJBLOCK -> OBJBLOCK [3:36]
|--LCURLY -> { [3:36]
`--RCURLY -> } [3:37]
```
```
λ java -jar checkstyle-8.41.1-all.jar -t Test.java | grep "3:"
```
``` …
```
> Issue #9429: update code example of AST for TokenTypes.EXTENDS_CLAUSE

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9408
**Test.java**
```
}
```
**AST**
```
`--RCURLY -> } [1:19]
```
```
|--LCURLY -> {
`--RCURLY -> }
```
> Issue #9408: update code example of AST for TokenTypes.CLASS_DEF

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
closes #9564
```
> cat Test.java
void method1() {
try (Foo foo = new Foo(); Bar bar = new Bar()) {
}
}
String method2() throws Exception {
String path = "some path";
try (BufferedReader br = new BufferedReader(new FileReader(path))) {
return br.readLine();
}
}
private class Foo implements AutoCloseable {
public void close() {
}
}
private class Bar implements AutoCloseable{
public void close() {
}
}
}
> java -jar checkstyle-8.41.1-all.jar -t Test.java …
```
> Issue #9564: update example of AST for TokenTypes.RESOURCE_SPECIFICATION

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9428
**Test.java**
```
void test() {
int x = 4 + 2 * (5 % 3) + (1 << 3) - 4 * 5;
}
}
```
**AST**
```
|       |   |--MODIFIERS -> MODIFIERS …
```
> Issue #9428: update code example of AST for TokenTypes.EXPR

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9457
**Test.java**
```
void test() {
int i = 0;
outer:
while (i < 10) {
if (i == 5)
continue outer;
i++;
}
}
}
```
**AST**
```
|       | …
```
> Issue #9457: update code example of AST for TokenTypes.LABELED_STAT

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/MatchXpathCheck.xml
- src/xdocs/config_coding.xml
Closes #9873 
```
$ curl -Is https://www.saxonica.com/html/documentation10/expressions/ | head -n 1 
HTTP/1.1 200 OK
$ curl -Is https://www.saxonica.com/html/documentation10/functions/fn/ | head -n 1
HTTP/1.1 200 OK
```
> Issue #9873: Update link to saxon documentation

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9593
**Test.java**
```
void test() {
int a = 10, b = 5;
a = -b;
}
}
```
**AST**
```
|       |   |--MODIFIERS -> MODIFIERS [3:2]
|       | …
```
> Issue #9593: add code example of AST for TokenTypes.UNARY_MINUS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9454
**Sucessfully Compiled**
**Test.java**
```
void test() {
int [] arr = {1, 2, 3, 4};
arr[0] = 10;
}
}
```
**AST**
```
|       |--VARIABLE_DEF -> VARIABLE_DEF [3:6]
|       |   |--MODIFIERS -> MODIFIERS [3:6]
| …
```
> Issue #9454: update code example of AST for TokenTypes.INDEX_OP

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes #9492 
```
public int foo(int i) {
return i+1;
}
}
```
```
|   |   `--LITERAL_INT -> int [2:11]
|   |--IDENT -> foo [2:15]
|   |--LPAREN -> ( [2:18]
|   |--PARAMETERS -> PARAMETERS [2:19]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:19]
|   |       |--MODIFIERS -> MODIFIERS [2:19]
|   |       |--TYPE -> TYPE [2:19]
|   | …
```
> Issue #9492: updated example of AST for TokenTypes.LITERAL_RETURN

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9469
**Test.java**
```
class Test {
}
```
**AST**
```
`--RCURLY -> } [2:0]
```
```
λ java -jar checkstyle-8.41.1-all.jar -t Test.java
```
```
`--RCURLY -> } [2:0]
```
```
|--LCURLY -> {
`--RCURLY -> }
```
> Issue #9469: update code example of AST for TokenTypes.LITERAL_CLASS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9500
**Test.java**
```
void test() throws FileNotFoundException, EOFException {
}
}
```
**AST**
```
|--METHOD_DEF -> METHOD_DEF [4:1]
|   |--TYPE -> TYPE [4:1]
|   |   `--LITERAL_VOID -> void [4:1]
|   |--IDENT -> test [4:6]
|   |--LPAREN -> …
```
> Issue #9500: add code example of AST for TokenTypes.LITERAL_THROWS

- .ci/validation.sh
related to https://github.com/checkstyle/checkstyle/issues/7417
> infra: move pmd build-tools repo to checkstyle org repo

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault7.java
Closes: #9896
Made some changes in existing unit test, added unique input file for each test method in IllegalImportCheckTest.java
> update IllegalImportCheckTest.java to use unique Input file

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9498
**Test.java**
```
class TestClass {
private int id;
private String name;
public TestClass() {
this(1, "NULL");
}
public TestClass(int id, String name) {
this.id = id;
this.name = name;
}
}
```
**AST**
```
|--IDENT -> TestClass [1:6]
`--OBJBLOCK -> OBJBLOCK [1:16]
|--LCURLY -> { [1:16]
|--VARIABLE_DEF -> VARIABLE_DEF [3:1]
|   |   `--LITERAL_PRIVATE -> private [3:1]
|   |--TYPE -> TYPE [3:9]
|   |   `--LITERAL_INT -> int [3:9]
|   |--IDENT -> id [3:13]
|   `--SEMI -> ; [3:15]
|--VARIABLE_DEF -> VARIABLE_DEF [4:1]
|   | …
```
> Issue #9498: add code example of AST for TokenTypes.LITERAL_THIS

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9496
**Test.java**
```
import java.awt.*;
void test() {
int type = 3;
Color background;
switch (type) {
case 0:
background = Color.red;
break;
case 1:
background = Color.blue;
break;
default:
background = Color.green;
}
}
}
```
**AST**
```
|--DOT -> . [1:15]
|   |   `--IDENT -> awt [1:12]
|   `--STAR -> * [1:16]
`--SEMI -> ; [1:17]
|--METHOD_DEF -> METHOD_DEF [4:1]
|   |--MODIFIERS -> …
```
> Issue #9496: update code example of AST for TokenTypes.LITERAL_SWITCH

- pom.xml
Similar upgrade to sevntu ( https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/840 )
> config: upgrade sevntu-checkstyle-check to 8.40

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9474 
**Test.java**
```
void test() {
boolean flag = true;
if (flag) {
} else {
}
}
}
```
**AST**
`$ jjava -jar checkstyle-8.42-all.jar -t Test.java`
```
|   |--TYPE -> TYPE [3:1]
|   |   `--LITERAL_VOID -> void [3:1]
|   |--IDENT -> test [3:6]
|   |--LPAREN -> ( [3:10]
|   |--PARAMETERS -> PARAMETERS [3:11]
|   |--RPAREN -> ) [3:11]
|   `--SLIST -> { [3:13]
|       |--VARIABLE_DEF -> VARIABLE_DEF [4:2]
|       |   |--MODIFIERS -> MODIFIERS …
```
> Issue #9474: add code example of AST for TokenTypes.LITERAL_ELSE

- .cirrus.yml
- pom.xml
Solves #9907 
* Replace Java15 build with Java16 build in Cirrus CI
* ~~Add javac16 stage to Drone CI~~
> Issue #9907: set up Java16 build

- .ci/travis/travis.sh
- .ci/wercker.sh
> 9967 xwiki

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9472 
**Test.java**
```
import java.util.Random;
void test() {
Random rand = new Random();
int x;
do {
x = rand.nextInt();
} while (x < 5);
}
}
```
**AST**
`$ java -jar checkstyle-8.42-all.jar -t Test.java`
```
|   `--IDENT -> Random [1:17]
`--SEMI -> ; [1:23]
|--METHOD_DEF -> METHOD_DEF [5:1]
|   |--MODIFIERS -> MODIFIERS [5:1]
|   |--TYPE -> TYPE [5:1]
|   |   `--LITERAL_VOID -> void …
```
> Issue #9472: update code example of AST for TokenTypes.LITERAL_DO

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9467 
**Test.java**
```
void test() {
try {
FileReader fr = new FileReader("Test.txt");
} catch (FileNotFoundException e) {
}
}
}
```
**AST**
`$ java -jar checkstyle-8.42-all.jar -t Test.java`
```
|--METHOD_DEF -> METHOD_DEF [5:1]
|   |--MODIFIERS -> MODIFIERS [5:1]
|   |--TYPE -> TYPE [5:1]
|   |   `--LITERAL_VOID -> void [5:1] …
```
> Issue #9467: add code example of AST for TokenTypes.LITERAL_CATCH

- config/version-number-rules.xml
- pom.xml
based on https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=3120&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=598
> Config versions

- .ci/no-exception-test.sh
- .travis.yml
Noticed at https://github.com/checkstyle/checkstyle/pull/9974
> infra: general CI cleanup

- .ci/travis/travis.sh
Resolves #9967 
PR to fix violation has been merged https://github.com/xwiki/xwiki-platform/pull/1622
> Issue #9967: Travis is failing on xwiki-platform validation

- .ci/travis/travis.sh
- .github/workflows/check-pr-description.yml
- .travis.yml
> infra: move PR description to action to reuse github token

- .travis.yml
> infra: disable verify-no-exception-configs until #9984

- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/sizes/ExecutableStatementCountCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountLambdas.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountMaxZero.java
- src/xdocs/config_sizes.xml
Resolves #8971
Diff Regression config: https://gist.githubusercontent.com/shashwatj07/7605ebd47967668adc4aae822a183e64/raw/dc6f71de078beb67fcfff924deb983316cbabef6/config3.xml
Diff Regression patch config: https://gist.githubusercontent.com/shashwatj07/33d71f5ad09426ee578811a025427ee9/raw/462091664b9bcaf04de215108288d71699434b53/config2.xml
Diff Regression projects: https://gist.githubusercontent.com/shashwatj07/b3de11a5c370e5f6092e31776b9c3b91/raw/8f42d25090f9d1b10c9b5d56ba39b482ac0aa91f/projects.properties
> Issue #8971: ExecutableStatementCount should allow LAMBDA token

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionCovariantEqualsTest.java
- src/it/resources-noncompilable/org/checkstyle/suppressionxpathfilter/covariantequals/SuppressionXpathRegressionCovariantEqualsInRecord.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/covariantequals/SuppressionXpathRegressionCovariantEqualsInClass.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/covariantequals/SuppressionXpathRegressionCovariantEqualsInEnum.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partial for Issue: #6207
Add xpath regression test for CovariantEquals
> Issue #6207: Add xpath regression test for CovariantEquals

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/UnnecessaryParenthesesCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessaryparentheses/InputUnnecessaryParenthesesIfStatement.java
- src/xdocs/config_coding.xml
Resolves #9957: UnnecessaryParentheses false positives in 8.42
Diff Regression projects: https://gist.githubusercontent.com/Vyom-Yadav/91807e6244cff60698d9e33e32ba2d51/raw/eb228fa41edadc10eea264a914ea1411f0e52122/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/518edf2da1dd8da7ff8f5570c2ebb89671fcfcfb/my_checks.xml
> Issue #9957: Fixing Unnecessary Parentheses false positives

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java
> Issue #9142: Migrate to Truth in AtclauseOrderCheckTest

- .ci/validation.sh
- .semaphore/semaphore.yml
- config/checkstyle_checks.xml
> Issue #8886: Validate sure that all Regexp modules has id property

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
fixes #9486 
Generated Java Doc
> Code used for generating example:
<pre>
<code>
new ArrayList<>(50);
}
}
</code>
</pre>
> Output in AST Format:
<pre>
<code>
|   `--IDENT -> ArrayList [1:17]
|--IDENT -> MyClass [2:13]
`--OBJBLOCK -> OBJBLOCK [2:21]
|--LCURLY -> { [2:21]
|--METHOD_DEF -> METHOD_DEF [3:5]
|   |--MODIFIERS -> MODIFIERS [3:5]       
|   |   |--LITERAL_PUBLIC -> public [3:5] 
|   |   `--LITERAL_STATIC -> static …
> Issue #9486: updated AST for TokenTypes.LITERAL_NEW

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9453 
```
aasthachauhan@Aasthas-MacBook-Pro documents % cat Test.java
class Test
{
{
int a=0;
++a;
}
}                                                                                                                                                                                                          aasthachauhan@Aasthas-MacBook-Pro documents % javac Test.java
aasthachauhan@Aasthas-MacBook-Pro documents % java -jar checkstyle-8.42-all.jar -T Test.java
`--OBJBLOCK -> OBJBLOCK [2:0]
|--LCURLY -> { [2:0]
|   | …
```
> Issue #9453: update example of AST for TokenTypes.INC

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractTreeTestSupport.java
> Issue #9142: Migrate to Truth in AbstractTreeTestSupport

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java
> Issue #9142: Migrate to Truth in AbstractXmlTestSupport

- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java
As a supplement to #9174, this PR improves the implementation of some methods.
Regression reports are not required as none of the projects use the summary tag.
Diff Regression config: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/master/SummaryJavadoc/SummaryJavadocConfig.xml
Diff Regression projects: https://raw.githubusercontent.com/AkMo3/akmo3.github.io/master/SummaryJavadoc/openjdk10.properties
Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/0ef2523_2021045510/reports/diff/index.html (Report is Clean)
> minor: Improve summary javadoc check method implementation

- config/sevntu_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java
> Issue #9142: Migrate to Truth in MutableExceptionCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessaryParenthesesCheck.java
TC in master branch is complaining about method
https://teamcity.jetbrains.com/viewLog.html?buildId=3506668&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsMaster
UnnecessaryParenthesesCheck#checkAroundOperators
Method is refactored
Diff report (no diff) https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/088d4f8_2021102117/reports/diff/index.html
> minor: refactor boolean expression to fix TC build

- config/checkstyle_input_checks.xml
> Issue #10094: Refactor check for config comment in inputs

- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotationJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObject.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObjectJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOther.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOtherJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverride.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideFromObject.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideFromObjectJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideFromOther.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideFromOtherJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideGoodOverrideJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideNotOverride.java
> Issue #10082: Update inputs for MissingOverrideCheckTest

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControl.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControlTest.java
> Issue #10072: Resolve Pitest Issues - pitest-imports (1)

- config/checkstyle_non_main_files_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheckOnDifferentTokens.java
> Issue #10083: Update inputs for AnnotationOnSameLineCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
This resolves Issue #9465 : update example of AST for TokenTypes.LITERAL_BYTE
> Issue #9465: Update example of AST for TokenTypes.LITERAL_BYTE

- config/sevntu_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTaskTest.java
> Issue #9142: Migrate to Truth in CheckstyleAntTaskTest

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentIsAtTheEndOfBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentsAfterMethodCall.java
Closes: #9105
Closes: #9945
Diff Regression config: https://gist.githubusercontent.com/SGanguly1999/e442ac6cb963ab43477a4fe2d9ec065e/raw/4c35c1fa2b5378920e29e39997ab0626a4ec87a2/basic2.xml
**REPORT LINK:** 
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b1f2f84_2021140625/reports/diff/index.html
> Issue #9105: False Positive Comments Indentaion method end, multiline comments

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/PkgImportControl.java
Leftover from #10073
See https://github.com/checkstyle/checkstyle/pull/10073#issuecomment-858387865
> minor: fixed TeamCity build violation

- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedAbovePackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadDeprecated.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedGood.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedSingleComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedSpecialCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/package-info.java
> Issue #10113: Update inputs for MissingDeprecatedCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/InputPackageAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/packageannotation/package-info.java
> Issue #10114: Update inputs for PackageAnnotationCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyle.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleCompact.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleCompactNoArray.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleEverythingMixed.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleExpanded.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoParens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingCommaNever.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleParams.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithParens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingCommaIgnore.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingCommaNever.java
> Issue #10112: Update inputs for AnnotationUseStyleCheckTest

- config/sevntu_suppressions.xml
- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractViolationReporterTest.java
> Issue #9142: Migrate to Truth in AbstractViolationReporterTest

- .ci/jsoref-spellchecker/whitelist.words
- config/pmd.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InputConfiguration.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
> Issue #10077: Parse and extract check name and check properties from input file

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/CommentTest.java
> Issue #9142: Migrate to Truth in CommentTest

- .ci/jsoref-spellchecker/whitelist.words
- .ci/wercker.sh
> spelling: fix mistype in wercker.sh

- config/checkstyle_checks.xml
- config/import-control-test.xml
> Issue #10074: Cover it folder by import control

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileContentsTest.java
> Issue #9142: Migrate to Truth in FileContentsTest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/BeforeExecutionFileFilterSetTest.java
> Issue #9142: Migrate to Truth in BeforeExecutionFileFilterSetTest

- config/sevntu_suppressions.xml
- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheckTest.java
> Issue #9142: Migrate to Truth in AbstractFileSetCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
Issue #9142
No Violations Expected:
```
Files with expected violations and actual violations differ.
value of: keySet()
expected to be empty
but was : [C:\Users\Shashwat\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\annotation\missingoverride\InputMissingOverrideBadOverrideFromObject.java]
```
Violations don't match:
```
Violations for C:\Users\Shashwat\checkstyle\src\test\resources\com\puppycrawl\tools\checkstyle\checks\annotation\missingoverride\InputMissingOverrideBadOverrideFromObject.java differ.
unexpected (1): 53:5: Must include @java.lang.Override annotation when {@inheritDoc} Javadoc tag exists.
---
expected      : [15:5: Must include @java.lang.Override annotation when {@inheritDoc} Javadoc tag exists., 35:9: Must include @java.lang.Override annotation …
```
> Issue #9142: Migrate to Truth in AbstractModuleTestSupport

- .ci/validation.sh
- .github/workflows/no-exception-workflow.yml
We need to temporarily move these CI jobs to a github workflow until we restore travis.
> infra: switch travis jobs to github workflow

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault7.java
> Issue #10148: Updated inputs for IllegalImportCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodInterfacePrivateMethod.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodRecordsAndCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodRecordsAndCtorsMinLineCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodAllowedAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodExtendAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodIgnoreNameRegex.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodIgnoreNameRegex2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodJavadocInMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodMissingJavadocTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodNoJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodNoJavadoc2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodNoJavadoc3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodPublicMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodPublicOnly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodPublicOnly2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodPublicOnly3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodReceiverParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodScopeAnonInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodScopeAnonInner2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodScopeInnerInterfaces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodSetterGetter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodSetterGetter2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodSmallMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethod_01.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethod_02.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocmethod/InputMissingJavadocMethodsNotSkipWritten.java
> Issue #10147: Updated inputs for MissingJavadocMethodCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/api/AbstractCheckTest.java
> Issue #9142: Migrate to Truth in AbstractCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameAccessModifier.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameCatchOnly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameOverrideAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameOverrideAnnotationNoNPE.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameOverrideAnnotationOne.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/parametername/InputParameterNameReceiver.java
> Issue #10145: Updated inputs for ParameterNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/avoidnestedblocks/InputAvoidNestedBlocksAllowInSwitchCase.java
> Issue #10155: Updated inputs for AvoidNestedBlocksCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/NeedBracesCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSwitchExpressionNoSingleLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesEmptySingleLineDefaultStmt.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesLoopBodyFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesLoopBodyTrue.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesSingleLineStatements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestCaseDefaultNoSingleLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestConditions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestCycles.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestIt.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestItWithAllowsOn.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestNotAllowSingleLineLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSingleLineCaseDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSingleLineCaseDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/needbraces/InputNeedBracesTestSingleLineLambda.java
> Issue #10160: Updated inputs for NeedBracesCheckTest

- config/checkstyle_input_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneMethodReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeMethodReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClassCtorsInitBlocks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameInterfaceIgnorePublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPackageImportClassInOneLine.java
https://github.com/checkstyle/checkstyle/pull/10120#discussion_r655415089
> minor: fixed ConfigCommentOnTopInputs config

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/AuditEventTest.java
> Issue #9142: Migrate to Truth in AuditEventTest

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InputConfiguration.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
> Issue #10141: Parse and extract check properties from input file

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
https://teamcity.jetbrains.com/viewLog.html?buildId=3524344&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsMaster
> minor: fixed TeamCity violation

- .circleci/config.yml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
testing of Teamcity PR validation
violations:
```
src/test/java/com/puppycrawl/tools/checkstyle/bdd
InlineConfigParser.java (1)
83: setCheckName() Prohibited exception IndexOutOfBoundsException caught 
src/test/java/com/puppycrawl/tools/checkstyle/bdd
InlineConfigParser.java (1)
95: setCheckProperties() Value of pre-increment expression ++lineNo is used 
```
> minor: remove old files from circleci config

- src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyle.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleOff.java
> Issue #10175: Updated inputs for ArrayTypeStyleCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationCustomAnnotationsDeclared.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationDeprecatedAndCustom.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationEmpty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationEnum.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationMultiple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationParameterized.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationSingleParameterless.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationWithoutAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/inputs/package-info.java
> Issue #10174: Updated inputs for AnnotationLocationCheckTest

- config/sevntu_suppressions.xml
- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java
> Issue #9142: Migrate to Truth in AutomaticBeanTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderLotsOfRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderIncorrectCustom.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderMethodReturningArrayType.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderNewArrayDeclaratorStructure.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/InputAtclauseOrderWithAnnotationsOutsideJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/atclauseorder/package-info.java
> Issue #10176: Updated inputs for AtclauseOrderCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOtherJava5.java
> Issue #10078: Parse and extract violations

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidnoargumentsuperconstructorcall/InputAvoidNoArgumentSuperConstructorCall.java
> Issue #10196: Updated inputs for AvoidNoArgumentSuperConstructorCallCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/emptystatement/InputEmptyStatement.java
> Issue #10198: Updated inputs for EmptyStatementCheckTest

- .travis.yml
- wercker.yml
> Issue #10178: move all "No Error" execution from wercker to travis

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileSetCheckTest.java
> Issue #9142: Migrate to truth in FileSetCheckTest

- config/pmd.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
> Issue #10225: Rename InputConifguration to TestInputConfigation

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FileTextTest.java
> Issue #9142: Migrate to truth in FileTextTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrder.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderAvoidDuplicatesInStaticFinalFields.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderForwardReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderOnlyConstructors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderOnlyModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderVariableAccess.java
> Issue #10210: Update inputs for DeclarationOrderCheckTest

- .ci/jsoref-spellchecker/whitelist.words
- config/checkstyle_checks.xml
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/NoWhitespaceBeforeCaseDefaultColonTest.java
- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionNoWhitespaceBeforeCaseDefaultColonTest.java
- src/it/resources/com/google/checkstyle/test/chapter4formatting/rule462horizontalwhitespace/InputNoWhitespaceBeforeCaseDefaultColon.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebeforecasedefaultcolon/SuppressionXpathRegressionNoWhitespaceBeforeCaseDefaultColonFour.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebeforecasedefaultcolon/SuppressionXpathRegressionNoWhitespaceBeforeCaseDefaultColonOne.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebeforecasedefaultcolon/SuppressionXpathRegressionNoWhitespaceBeforeCaseDefaultColonThree.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/nowhitespacebeforecasedefaultcolon/SuppressionXpathRegressionNoWhitespaceBeforeCaseDefaultColonTwo.java
- src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCaseDefaultColonCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/whitespace/NoWhitespaceBeforeCaseDefaultColonCheck.xml
- src/main/resources/google_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCaseDefaultColonCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/InputNoWhitespaceBeforeCaseDefaultColonEnumAndStrings.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebeforecasedefaultcolon/InputNoWhitespaceBeforeCaseDefaultColon.java
- src/xdocs/checks.xml
- src/xdocs/config_whitespace.xml
- src/xdocs/google_style.xml
Closes #8186
- New Check NoWhiteSpaceBeforeCaseDefaultColonCheck
- This is continutation of PR #8187 by @wilcoln.
- Contribution PR : checkstyle/contribution#548
New module config: https://github.com/AkMo3/akmo3.github.io/raw/master/ColonCheck/WhiteSpaceBeforeColon.xml
New Report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/8cce311_2021034422/reports/diff/index.html
___
Old Report: https://akmo3.github.io/NoWhiteSpace/reports/diff/index.html
> Issue #8186: add new check NoWhiteSpaceBeforeCaseDefaultColonCheck

- src/test/java/com/puppycrawl/tools/checkstyle/api/SeverityLevelCounterTest.java
> Issue #9142: Migrate to Truth in SeverityLevelCounterTest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/LineColumnTest.java
> Issue #9142: Migrate to Truth in LineColumnTest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCode.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeEqualsParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeNoEquals.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeSemantic.java
> Issue #10213: Update inputs for EqualsHashCodeCheckTest

- config/checkstyle_input_checks.xml
- config/checkstyle_non_main_files_checks.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputViolation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObject.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObjectJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOther.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideNotOverride.java
> Issue #10079: Add support for violation messages in parser

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noarraytrailingcomma/InputNoArrayTrailingComma.java
> Issue #10241: Update inputs for NoArrayTrailingCommaCheckTest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/api/FilterSetTest.java
> Issue #9142: Migrate to truth in FilterSetTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSwitchExpressions.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSwitchExpressionsSkipIfLast.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLast.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastDefaultMethodsInInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/defaultcomeslast/InputDefaultComesLastSkipIfLastAndSharedWithCase.java
> Issue #10211: Update inputs for DefaultComesLastCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/noclone/InputNoClone.java
> Issue #10242: Update inputs for NoCloneCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedifdepth/InputNestedIfDepthDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedifdepth/InputNestedIfDepthMax.java
> Issue #10239: Update inputs for NestedIfDepthCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleVariableDeclarationsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplevariabledeclarations/InputMultipleVariableDeclarations.java
> Issue #10237: Update inputs for MultipleVariableDeclarationsCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtor2.java
> Issue #10235: Update inputs for MissingCtorCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignmentLambdaExpressions.java
> Issue #10234: Update inputs for InnerAssignmentCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedtrydepth/InputNestedTryDepthMax.java
> Issue #10240: Update inputs for NestedTryDepthCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressions.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefaultCheckSwitchExpressionsTwo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingswitchdefault/InputMissingSwitchDefault.java
> Issue #10236: Update inputs for MissingSwitchDefaultCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/overloadmethodsdeclarationorder/InputOverloadMethodsDeclarationOrderRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/overloadmethodsdeclarationorder/InputOverloadMethodsDeclarationOrder.java
> Issue #10259: Update inputs for OverloadMethodsDeclarationOrderCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityCheckTextBlocks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEquality.java
> Issue #10263: Update inputs for StringLiteralEqualityCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java
> Issue #10261: Update inputs for SimplifyBooleanExpressionCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerFallThrough.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerFallThrough.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nofinalizer/InputNoFinalizerHasFinalizer.java
> Issue #10257: Update inputs for NoFinalizerCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptyIsFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthModifier.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthSimple.java
> Issue #10146: Updated inputs for MethodLengthCheckTest

- .ci/jsoref-spellchecker/whitelist.words
- src/it/java/com/google/checkstyle/test/chapter4formatting/rule43onestatement/OneStatementPerLineTest.java
- src/it/resources-noncompilable/com/google/checkstyle/test/chapter4formatting/rule43onestatement/InputOneStatementPerLine.java
> Issue #10277: Google test uses check input for OneStatementPerLineTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeMethodReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superfinalize/InputSuperFinalizeVariations.java
> Issue #10265: Update inputs for InputSuperFinalizeMethodReference

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanreturn/InputSimplifyBooleanReturn.java
> Issue #10262: Update inputs for SimplifyBooleanReturnCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentReceiver.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentWithUnchecked.java
> Issue #10260: Update inputs for ParameterAssignmentCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyBlockCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSwitchExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockAnnotationDefaultKeyword.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockCase2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2Statement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemantic2Text.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticInvalid.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock/InputEmptyBlockSemanticText.java
> Issue #10156: Updated inputs for EmptyBlockCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoidinlineconditionals/InputAvoidInlineConditionals.java
> Issue #10195: Updated inputs for AvoidInlineConditionalsCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclarationRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclaration.java
> Issue #10268: Update inputs for UnnecessarySemicolonAfterTypeMemberDeclarationCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonintrywithresources/InputUnnecessarySemicolonInTryWithResourcesDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonintrywithresources/InputUnnecessarySemicolonInTryWithResourcesNoBraceAfterAllowed.java
> Issue #10270: Update inputs for UnnecessarySemicolonInTryWithResourcesCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/nestedfordepth/InputNestedForDepth1.java
> Issue #10238: Update inputs for NestedForDepthCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleNestedGenerics.java
Closes #10215.
Diff Regression config: https://gist.githubusercontent.com/nmancus1/626d012b6ca38bf04844224307036e08/raw/755163b21059b241d6709cd60c1a8b733e248ac1/config.xml
Final report: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2cb7d1c_2021183046/reports/diff/index.html 
All lost violations were false positives.
> Issue #10215: ArrayTypeStyle false positives in nested generics

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEqualsRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/covariantequals/InputCovariantEquals.java
> Issue #10197: Updated inputs for CovariantEqualsCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneInnerAndWithArguments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneMethodReference.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperClonePlainAndSubclasses.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/superclone/InputSuperCloneWithoutWarnings.java
> Issue #10264: Update inputs for SuperCloneCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInEnumerationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicoloninenumeration/InputUnnecessarySemicolonInEnumeration.java
> Issue #10269: Update inputs for UnnecessarySemicolonInEnumerationCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/emptycatchblock/InputEmptyCatchBlockDefault2.java
> Issue #10157: Updated inputs for EmptyCatchBlockCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingCommaAlwaysDemandTrailingComma.java
> Issue #10193: Updated inputs for ArrayTrailingCommaCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclarationRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonafteroutertypedeclaration/InputUnnecessarySemicolonAfterOuterTypeDeclaration.java
> Issue #10267: Update inputs for UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoiddoublebraceinitialization/InputAvoidDoubleBraceInitialization.java
> Issue #10194: Updated inputs for AvoidDoubleBraceInitializationCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
From: https://teamcity.jetbrains.com/viewLog.html?buildId=3546025&tab=Inspection&buildTypeId=Checkstyle_IdeaInspectionsPullRequest
> minor: Fix Teamcity build

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InterfaceIsTypeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/interfaceistype/InputInterfaceIsTypeAllowMarker.java
> Issue #10295: Update inputs for InterfaceIsTypeCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/CatchParameterNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterName2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterName3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/catchparametername/InputCatchParameterNameSimple.java
> Issue #10297: Update inputs for CatchParameterNameCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestSwitchExpressions.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestSwitchExpressionsNewLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefaultTestNl.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyDefaultTestNlow.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnumsOptFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyIgnoreEnumsOptTrue.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyMethodTestNewLine2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestCoverageIncrease.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefaultLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestDefaultWithAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestEolSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestFirstLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestInvalidOption.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestLineBreakAfter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestMissingBraces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNewLine3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNewLineOptionWithLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlWithAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlowSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly/InputLeftCurlyTestNlowWithAnnotations.java
> Issue #10158: Update inputs for LeftCurlyCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ClassTypeParameterNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/classtypeparametername/InputClassTypeParameterName1.java
> Issue #10298: Update inputs for ClassTypeParameterNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/packagename/InputPackageNameSimple1.java
> Issue #10304: Update inputs for PackageNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/InterfaceTypeParameterNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/interfacetypeparametername/InputInterfaceTypeParameterName1.java
> Issue #10299: Update inputs for InterfaceTypeParameterNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalVariableNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableNameInnerClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localvariablename/InputLocalVariableNameOneCharInitVarName.java
> Issue #10302: Update inputs for LocalVariableNameCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportAllowStaticMember.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstarimport/InputAvoidStarImportExcludes.java
> Issue #10296: Update inputs for AvoidStarImportCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LambdaParameterNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/lambdaparametername/InputLambdaParameterNameSwitchExpression.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/lambdaparametername/InputLambdaParameterName.java
> Issue #10300: Update inputs for LambdaParameterNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodTypeParameterNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodtypeparametername/InputMethodTypeParameterName1.java
> Issue #10303: Update inputs for MethodTypeParameterNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForInitializerPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPad.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforinitializerpad/InputEmptyForInitializerPad2.java
> Issue #10319: Update inputs for EmptyForInitializerPadCheckTest

- config/checkstyle_input_suppressions.xml
- config/checkstyle_resources_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/FileTabCharacterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/filetabcharacter/InputFileTabCharacterSimple1.java
> Issue #10321: Update inputs for FileTabCharacterCheckTest

- config/checkstyle_input_suppressions.xml
- config/checkstyle_resources_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoLineWrapCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapBad2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nolinewrap/InputNoLineWrapGood.java
> Issue #10322: Update inputs for NoLineWrapCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/upperell/InputUpperEllSemantic.java
> Issue #10334: Update inputs for UpperEllCheckTest

- config/checkstyle_input_suppressions.xml
> config: Introduced empty lines in checkstyle_input_suppressions

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyForIteratorPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPad1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptyforiteratorpad/InputEmptyForIteratorPad2.java
> Issue #10320: Update inputs for EmptyForIteratorPadCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TodoCommentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/InputTodoCommentSimple.java
> Issue #10332: Update inputs for TodoCommentCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/UncommentedMainCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMainRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/uncommentedmain/InputUncommentedMain6.java
> Issue #10333: Update inputs for UncommentedMainCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/LocalFinalVariableNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameTryResourcesJava9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableName1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameInnerClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/localfinalvariablename/InputLocalFinalVariableNameTryResources.java
> Issue 10301: Update inputs for LocalFinalVariableNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/InvalidJavadocPositionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/InputInvalidJavadocPosition.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/comment/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/invalidjavadocposition/package-info.java
> Issue #10340: Update inputs for InvalidJavadocPositionCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocBlockTagLocationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationCustomTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocblocktaglocation/InputJavadocBlockTagLocationMultilineCodeBlock.java
> Issue #10341: Update inputs for JavadocBlockTagLocationCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingLeadingAsteriskCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingleadingasterisk/InputJavadocMissingLeadingAsteriskCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingleadingasterisk/InputJavadocMissingLeadingAsteriskIncorrect.java
> Issue #10344: Update inputs for JavadocMissingLeadingAsteriskCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMissingWhitespaceAfterAsteriskCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskInvalid.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskValid.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocmissingwhitespaceafterasterisk/InputJavadocMissingWhitespaceAfterAsteriskValidWithTab.java
> Issue #10345: Update inputs for JavadocMissingWhitespaceAfterAsteriskCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationFirstLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/InputJavadocContentLocationTrailingSpace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoccontentlocation/package-info.java
> Issue #10342: Update inputs for JavadocContentLocationCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleHtmlComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleNeverEndingXmlComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleNoJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/bothfiles/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/invalidformat/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/invalidinherit/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/valid/package-info.java
> Issue #10358: Update inputs for JavadocStyleCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/blank/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/header/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/annotation/blockcomment/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/annotation/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/blank/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/blockcomment/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/detached/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/single/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/nojavadoc/singleline/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadocpackage/singleline/package-info.java
> Issue #10362: Update inputs for MissingJavadocPackageCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescription.java
> Issue #10363: Update inputs for NonEmptyAtclauseDescriptionCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocTagContinuationIndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationBlockTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationDescription.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationGuavaFalsePositive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadoctagcontinuationindentation/InputJavadocTagContinuationIndentationOffset3.java
> Issue #10359: Update inputs for JavadocTagContinuationIndentationCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/singlelinejavadoc/InputSingleLineJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/singlelinejavadoc/InputSingleLineJavadocIgnoredTags.java
> Issue #10365: Update inputs for SingleLineJavadocCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/requireemptylinebeforeblocktaggroup/InputRequireEmptyLineBeforeBlockTagGroupCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/requireemptylinebeforeblocktaggroup/InputRequireEmptyLineBeforeBlockTagGroupIncorrect.java
> Issue #10364: Update inputs for RequireEmptyLineBeforeBlockTagGroupCheckTest

- .ci/pitest.sh
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractJavadocCheck.java
> Issue #10126: Resolved Pitest Issues - AbstractJavadocCheck

- .ci/jsoref-spellchecker/whitelist.words
- config/import-control.xml
- config/suppressions.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultLogger.java
- src/test/java/com/puppycrawl/tools/checkstyle/DefaultLoggerTest.java
> Issue #9794: Loggers should use class for printing to output that does only Localization

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9409 
```
vinayak@Gladiator:~/Documents/Opensource/checkstyle/target$ cat /home/vinayak/Documents/Test.java 
class Test{
public static void main(String args[]){
int num;
boolean isValid = true;
num = isValid ? 1 : 0;
}
}
vinayak@Gladiator:~/Documents/Opensource/checkstyle/target$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -T /home/vinayak/Documents/Test.java 
|   |--IDENT -> main [2:20]
| …
```
> Issue #9409: create example of AST for TokenTypes.COLON

- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagDoubleTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEmptyTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagEnumsAndAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagExpressionError.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagIgnore.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagIncomplete.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMissingFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagMissingTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagNoJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagRegularExpression.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/writetag/InputWriteTagSeverity.java
> Issue #10366: Update inputs for WriteTagCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/VisibilityModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierPackageClassName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierAnnotated2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierAnnotated3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierAnnotatedSameTypeName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierGenerics.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierGregorianCalendar.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutable2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutable3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutable4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutable5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableSameTypeName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableSameTypeName2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableStarImport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierImmutableStarImport2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierInner1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierIsStarImport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierLocalAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierPublicOnly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifierSimple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifiersNullModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifiersPublicImmutable2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/InputVisibilityModifiersPublicImmutable3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/visibilitymodifier/inputs/InetSocketAddress.java
> Issue #10382: Update inputs for VisibilityModifierCheckTest

- config/checkstyle_non_main_files_suppressions.xml
- config/signatures.txt
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
> Issue #10392: Forbid usage of deprecated API

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/OneTopLevelClassCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassAnnotation2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassClone.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassDeclarationOrder2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassEnum.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassEnum2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassIndentation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassInterface2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassInterface3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassNoPublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/onetoplevelclass/InputOneTopLevelClassSameLine.java
> Issue #10384: Update inputs for OneTopLevelClassCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCount2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCount3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/throwscount/InputThrowsCountMethodWithAnnotation.java
> Issue #10383: Update inputs for ThrowsCountCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/InnerTypeLastCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastArray.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClassCtorsInitBlocks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClassRootClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/innertypelast/InputInnerTypeLastClassRootClass2.java
> Issue #10386: Update inputs for InnerTypeLastCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorAbstract.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorAbstractSerializable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorDesignForExtension.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorInnerStaticClasses.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorNonUtilityClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorPrivate.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorPublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorRegression.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorSerializable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/hideutilityclassconstructor/InputHideUtilityClassConstructorSerializableInnerStatic.java
> Issue #10387: Update inputs for HideUtilityClassConstructorCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/MutableExceptionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableException2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableException3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableExceptionClassExtendsGenericClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/mutableexception/InputMutableExceptionMultipleInputs.java
> Issue #10385: Update inputs for MutableExceptionCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassClassWithPrivateCtorWithNestedExtendingClass.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassClassWithPrivateCtorWithNestedExtendingClassWithoutPackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClassConstructorInRecord.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/finalclass/InputFinalClass.java
> Issue #10388: Update inputs for FinalClassCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportNestedClass.java
> Issue #10408: Update inputs for AvoidStaticImportCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImport_UnnamedPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportBug.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportCheckClearState.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportWithChecker.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/redundantimport/InputRedundantImportWithoutWarnings.java
> Issue #10411: Update inputs for RedundantImportCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexityRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexity2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexityNPE.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexitySmall.java
> Issue #10425: Update inputs for BooleanExpressionComplexityCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCoupling2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCoupling3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCoupling4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesAllIgnored.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingExcludedPackagesDirectPackages.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/inputs/a/aa/AAClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/inputs/a/ab/ABClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/inputs/b/BClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/inputs/c/CClass.java
> Issue #10426: Update inputs for ClassDataAbstractionCouplingCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityVar.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity15Extensions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityExcludedPackagesAllIgnored.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityExcludedPackagesCommonPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityExcludedPackagesDirectPackages.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityExtends.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityMultiDimensionalArray.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityPackageName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityRemoveIncorrectAnnotationToken.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityRemoveIncorrectTypeParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityRemoveMultiCatchBitwiseOr.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/inputs/a/aa/AAClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/inputs/a/ab/ABClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/inputs/b/BClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/inputs/c/CClass.java
> Issue #10427: Update inputs for ClassFanOutComplexityCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/CyclomaticComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexityRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexity.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexitySwitchBlocks2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexitySwitchBlocks3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/cyclomaticcomplexity/InputCyclomaticComplexitySwitchBlocks4.java
> Issue #10428: Update inputs for CyclomaticComplexityCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/JavaNCSSCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSSRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSS2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/javancss/InputJavaNCSS3.java
> Issue #10429: Update inputs for JavaNCSSCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityCheckSwitchExpression.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityDefault2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexity.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/npathcomplexity/InputNPathComplexityOverflow.java
> Issue #10430: Update inputs for NPathComplexityCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtension.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionIgnoredAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionMultipleAnnotations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionNativeMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionOverridableMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRequiredJavadocPhrase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRequiredJavadocPhraseMultiLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionsLocalAnnotations.java
> Issue #10389: Update inputs for DesignForExtensionCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierNoViolationRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierOnClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierOnClassNoViolations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierOnClassSetEnumFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierOnClassSetInterfaceFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/classmemberimpliedmodifier/InputClassMemberImpliedModifierOnInterface.java
> Issue #10444: Update inputs for ClassMemberImpliedModifierCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierPrivateMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnClassNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnInterface2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnInterface3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnInterface4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnInterfaceNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnClassNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnInterface2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnInterface3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnInterface4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnInterfaceNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierPackageScopeInterface.java
> Issue #10445: Update inputs for InterfaceMemberImpliedModifierCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealed.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderSealedAndNonSealedNoViolation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderAnnotationDeclaration.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderDefaultMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderIt.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderTypeAnnotations.java
> Issue #10446: Update inputs for ModifierOrderCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierTryWithResources.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierAnnotationOnEnumConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierClassesInsideOfInterfaces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierConstructorModifier.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInAbstractMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInAnonymousClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInEnumMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInEnumStaticMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInTryWithResource.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierIt.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierNestedClassInPublicInterfaceRedundantModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierPrivateMethodInPrivateClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierPublicModifierInNotPublicClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierStaticInInnerTypeOfInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierStaticMethodInInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierStaticModifierInNestedEnum.java
> Issue #10447: Update inputs for RedundantModifierCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameCheckEnhancedInstanceof.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameCheckEnhancedInstanceofAllowXmlLength1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameCheckRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameAbstractMultisetSetCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnore.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreFinalKeepStaticFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreNonStaticFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreStatic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreStaticFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameIgnoreStaticKeepStaticFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameNoIgnore.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameOverridableMethod2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameReceiver.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType6.java
> Issue #10448: Update inputs for AbbreviationAsWordInNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ConstantNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameInterfaceIgnorePublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameMemberExtended.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameSimple1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameSimple2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/constantname/InputConstantNameStaticModifierInInterface.java
> Issue #10449: Update inputs for ConstantNameCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbbreviationAsWordInNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameOverridableMethod2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abbreviationaswordinname/InputAbbreviationAsWordInNameType6.java
Leftover from https://github.com/checkstyle/checkstyle/pull/10458
> minor: Fixed Checkstyle violations and AbbreviationAsWordInNameCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
#9507
Before:
After:
CLI:
```
->src cat Test.java
class Test {
public int method(String mode) {
int yield = 0;
return switch (mode) {
case "a", "b":
yield 1;
default:
yield - 1;
};
}
}
->src javac Test.java
->java -jar checkstyle-8.44-all.jar -t Test.java
|   |   `--LITERAL_PUBLIC -> public [2:2]
|   |--TYPE -> TYPE [2:9]
|   |   `--LITERAL_INT -> int [2:9]
|   |--IDENT -> method [2:13]
|   |--LPAREN -> ( [2:19]
|   |--PARAMETERS -> PARAMETERS [2:20]
|   |   `--PARAMETER_DEF -> PARAMETER_DEF [2:20]
|   |       |--MODIFIERS -> MODIFIERS [2:20]
|   | …
```
> Issue #9507: update example of AST for TokenTypes.LITERAL_YIELD

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9466 
```
vinayak@Gladiator:~/Documents$ cat test.java 
class test {
public static void main(String args[]){
int num = 1;
switch (num) {
case 0:
num = 1;
}
switch (num) {
case 1 -> num = -1;
}
}
}
vinayak@Gladiator:~/Documents/Opensource/checkstyle/target$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -T /home/vinayak/Documents/test.java 
|--IDENT -> test [1:6]
|   |--IDENT -> main [2:20]
| …
```
> Issue #9466: update example of AST for TokenTypes.LITERAL_CASE

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/staticvariablename/InputStaticVariableName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/staticvariablename/InputStaticVariableName2.java
> Issue #10451: Update inputs for StaticVariableNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/TypeNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeNameRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/typename/InputTypeName6.java
> Issue #10452: Update inputs for TypeNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/MethodParamPadCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPad4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadWhitespaceAround.java
> Issue #10471: Update inputs for MethodParamPadCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeTextBlocksTabIndent.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeAtStartOfTheLine2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeDot.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeDotAllowLineBreaks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeEmptyForLoop.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespacebefore/InputNoWhitespaceBeforeMethodRef.java
> Issue #10475: Update inputs for NoWhitespaceBeforeCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceAfterCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarations3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterArrayDeclarationsAndAnno.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterNewGenericTypeArgument.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterNewTypeStructure.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestAllTokens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestAllowLineBreaks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestArrayDeclarator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestMethodRef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestMethodRefAfter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestNpe.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestSynchronized.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/nowhitespaceafter/InputNoWhitespaceAfterTestTypecast.java
> Issue #10473: Update inputs for NoWhitespaceAfterCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SeparatorWrapCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForArrayDeclarator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForEllipsis.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForInvalidOption.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestDot.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/separatorwrap/InputSeparatorWrapForTestMethodRef.java
> Issue #10478: Update inputs for SeparatorWrapCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrap6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapEol.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapNl.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapSeparatorAndInterfaces.java
> Issue #10476: Update inputs for OperatorWrapCheckTest

- config/checkstyle_input_suppressions.xml
- config/checkstyle_resources_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorChildNodes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorComments2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorEmpty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorErrors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorMinColumnNo.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorNoErrors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorNoStackoverflowError.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/singlespaceseparator/InputSingleSpaceSeparatorStartOfTheLine.java
> Issue #10479: Update inputs for SingleSpaceSeparatorCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/TypecastParenPadCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespaceAround.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/typecastparenpad/InputTypecastParenPadWhitespaceTestSpace.java
> Issue #10480: Update inputs for TypecastParenPadCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsAnnotations.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFileInUnnamedPackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsSingleWordPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports15Extensions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImports2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsBug.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsCheckClearState.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsFromJavaLang.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsJavadocQualifiedName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsShadowed.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithBlockMethodParameters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithNewlinesInsideTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithValueTag.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/unusedimports/InputUnusedImportsWithoutWarnings.java
> Issue #10412: Update inputs for UnusedImportsCheckTest

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves Issue #9460
mvn javadoc result
Program AST
> Issue #9460: Update example of AST for TokenTypes.LCURLY

- config/checkstyle_non_main_files_suppressions.xml
- config/signatures-test.txt
- pom.xml
> Issue #10391: Violate original verify method and suppress errors

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationAfterAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationBlockCommentBeforePackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentIsAtTheEndOfBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationCommentsAfterMethodCall.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInEmptyBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInMultiblockStructures.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationInSwitchBlock.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationNoNpe.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationSurroundingCode3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/commentsindentation/InputCommentsIndentationWithInMethodCallWithSameIndent.java
> Issue #10474: Update inputs for CommentsIndentationCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/FinalLocalVariableCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckRecords.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchAssignment.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableCheckSwitchExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariable2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAnonymousClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAssignedInsideAndOutsideSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableAssignedMultipleTimes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableBreak.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableEnhancedForLoopVariable2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFalsePositive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableFalsePositives.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableLeavingSlistToken.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableMultiCatch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableMultipleAndNestedConditions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameLambda.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNameShadowing.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableNativeMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/finallocalvariable/InputFinalLocalVariableReceiverParameter.java
> Issue #10498: Update inputs for FinalLocalVariableCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocks.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTextBlocksQuotes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens5.java
> Issue #10504: Update inputs for IllegalTokenTextCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypePackageClassName.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestEnhancedInstanceof.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeArrays.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeEmptyStringMemberModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeNewArrayStructure.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSameFileNameFalsePositive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeSimilarClassName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestAbstractClassNamesFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestAbstractClassNamesTrue.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestDefaults.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestExtendsImplements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestGenerics.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestIgnoreMethodNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestLegalAbstractClassNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestMemberModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestPlainAndArraysTypes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestSameFileNameGeneral.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestStarImports.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestStaticImports.java
> Issue #10505: Update inputs for IllegalTypeCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch4.java
> Issue #10500: Update inputs for IllegalCatchCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsIgnoreMethodNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsIgnoreOverriddenMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsNotIgnoreOverriddenMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestClassNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestIllegalClassNames.java
> Issue #10502: Update inputs for IllegalThrowsCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens7.java
> Issue #10503: Update inputs for IllegalTokenCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableBothForLoops.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable3.java
> Issue #10508: Update inputs for ModifiedControlVariableCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiteralsTextBlocks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiteralsNoWarnings.java
> Issue #10509: Update inputs for MultipleStringLiteralsCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectory.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectory2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtParent.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtParent2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtSubpackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationDiffDirectoryAtSubpackage2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationNoPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationNoPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationPlain.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/packagedeclaration/InputPackageDeclarationWithCommentOnly.java
> Issue #10510: Update inputs for PackageDeclarationCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ReturnCountCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountLambda4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountSwitches2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/returncount/InputReturnCountVoid.java
> Issue #10512: Update inputs for ReturnCountCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordAsTopLevel.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordDefault.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThis15Extensions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLambdaParameters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAllowLocalVars.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAnnotationInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisAnonymousEmpty.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisBraceAlone.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisCaseGroup.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisCatchVariables.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumConstant.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisEnumInnerClassesAndBugs3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExpressions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisExtendedMethod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFinalInstanceVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisFor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisMethodReferences.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisReceiver.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisSimple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisStatic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/requirethis/InputRequireThisValidateOnlyOverlappingTrue.java
> Issue #10511: Update inputs for RequireThisCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeInterfaceMemberScopeIsPublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadocOnInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerClasses1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerClasses2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerInterfaces1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerInterfaces2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeTags.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeUnusedParamInJavadocForClass.java
> Issue #10478: Update inputs for MissingJavadocTypeCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/AbstractClassNameCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameCustom.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameFormerFalsePositive.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameType.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/abstractclassname/InputAbstractClassNameVariants.java
> Issue #10539: Update inputs for AbstractClassNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/MethodNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNamePrivateMethodsInInterfaces.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNamePublicMethodsInInterfaces.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameEqualClassName2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameEqualClassName3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameExtra.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameOverriddenMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/naming/methodname/InputMethodNameSimple.java
> Issue #10541: Update inputs for MethodNameCheckTest

- config/checkstyle_checks.xml
From: https://github.com/checkstyle/contribution/pull/562#issuecomment-891895132
> supplemental: Convert from Todo check to better MatchXpath check(#10107)

- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordComponentNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordcomponentname/InputRecordComponentNameDefault.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordcomponentname/InputRecordComponentNameLowercase.java
> Issue #10543: Update inputs for RecordComponentNameCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordTypeParameterNameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordtypeparametername/InputRecordTypeParameterName.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/naming/recordtypeparametername/InputRecordTypeParameterNameFoo.java
> Issue #10544: Update inputs for RecordTypeParameterNameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenEmptyStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenLastTokenType2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenMissingSwitchDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromCatch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenStringLiteralEquality.java
> Issue #10558: Update inputs for DescendantTokenCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameRecord.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameRecordMethodRecordDef.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/outertypefilename/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename15Extensions.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename1a.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilename5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameCheckPublic.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameIllegalTokens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/outertypefilename/InputOuterTypeFilenameNoPublic.java
> Issue #10562: Update inputs for OuterTypeFilenameCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersReceiver.java
> Issue #10559: Update inputs for FinalParametersCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObject.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromObjectJava5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadOverrideFromOther.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideNotOverride.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/arraytrailingcomma/InputArrayTrailingCommaAlwaysDemandTrailingComma.java
> Issue #10548: Migrate to Inline Config Parser in ArrayTrailingCommaCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheckTest.java
> Issue #10548: Migrate to Inline Config Parser in AvoidInlineConditionalsCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsingleline/InputRegexpSinglelineSemantic8.java
> Issue #10116: Update inputs for RegexpSinglelineCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheckTest.java
> Issue #10548: Migrate to Inline Config Parser in EmptyStatementCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DetailAstImplTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/NoCodeInFileCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/InputNoCodeInFile3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/InputNoCodeInFile4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/nocodeinfile/InputNoCodeInFile5.java
> Issue #10561: Update inputs for NoCodeInFileCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpCheckStopEarly.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic12.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic13.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic14.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpSemantic9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpStartingWithEmptyLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexp/InputRegexpTrailingComment9.java
> Issue #10560: Update inputs for RegexpCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/anoninnerlength/InputAnonInnerLength2.java
> Issue #10584: Update inputs for AnonInnerLengthCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength4.java
> Issue #10586: Update inputs for FileLengthCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongPackageStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongImportStatements.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongLink.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthSimple1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthUnicodeChars.java
> Issue #10588: Update inputs for LineLengthCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCountInterfaceMemberScopeIsPublic.java
> Issue #10590: Update inputs for MethodCountCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberEmptyInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberSimple1.java
> Issue #10592: Update inputs for OuterTypeNumberCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/avoiddoublebraceinitialization/InputAvoidDoubleBraceInitialization.java
> Issue #10548: Migrate to Inline Config Parser in AvoidDoubleBraceInitializationCheckTest

- config/checkstyle_resources_suppressions.xml
Fixes master build, related to https://github.com/checkstyle/checkstyle/commit/ac60b9c07ea008be409a5d6c768cf78e5b3cd5e8
> minor: add suppression for InputLineLengthSimple1.java

- src/xdocs/index.xml.vm
Fixes broken link in master build: https://github.com/checkstyle/checkstyle/actions/runs/1118539346
> doc: fix broken scm manager install link

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportControlCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl12.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl13.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl14.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl15.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl16.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl17.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl18.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl19.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl20.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl21.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl22.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl23.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl24.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlDisallowClassOfAllowPackage.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControlFileNameNoExtension
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importcontrol/InputImportControl_Blacklist.java
> Issue #10596: Update inputs for ImportControlCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumber2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple4.java
> Issue #10594: Update inputs for ParameterNumberCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceAtStartOfTheLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceEndsTheLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceInnerClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceList.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceMethodRef1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceMethodRef2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/genericwhitespace/InputGenericWhitespaceNested.java
> Issue #10470: Update inputs for GenericWhitespaceCheckTest

- .ci/openjdk16-excluded.files
Fixes ci failure noted in https://github.com/checkstyle/checkstyle/issues/10424#issuecomment-897528706
> minor: remove BeforeExecutionExclusionFileFilter

- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/AnnotationArrayInitHandler.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/indentation/InputIndentationAnnotationArrayInitOldStyle.java
Fixes #10020 
Diff Regression projects: https://gist.githubusercontent.com/aryaniiit002/97577199a93846562de23a0d6304e496/raw/eb4a3a70f46a644ce06914ac5ba8fd1b0e3c940b/projects-to-test-on.properties
Diff Regression config: https://gist.githubusercontent.com/Abhishek-kumar09/0745ecf11934e0214b9187f9d4896e4a/raw/2143ba7f21dcafb998019a1ca2c0ee3f1c510646/my_check.xml
Report label: Default Indentation profile
> Issue #10020: Fix Annotation array initalization issue with curlies  on seperate line

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalThrowsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalthrows/InputIllegalThrowsTestIllegalClassNames.java
> Issue #10548: Migrate to Inline Config Parser in IllegalThrowsCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltoken/InputIllegalTokens6.java
> Issue #10548: Migrate to Inline Config Parser in IllegalTokenCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegalcatch/InputIllegalCatch4.java
> Issue #10548: Migrate to Inline Config Parser in IllegalCatchCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingCtorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/missingctor/InputMissingCtor2.java
> Issue #10548: Migrate to Inline Config Parser in MissingCtorCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MissingSwitchDefaultCheckTest.java
> Issue #10548: Migrate to Inline Config Parser in MissingSwitchDefaultCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputViolation.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullEnhancedInstanceof.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNull.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullIgnoreCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullMisc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullOnTheSameLine.java
> Issue #10548: Migrate to Inline Config Parser in EqualsAvoidNullCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputViolation.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsHashCodeCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeEqualsParameter.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeNoEquals.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalshashcode/InputEqualsHashCodeSemantic.java
> Issue #10548: Migrate to Inline Config Parser in EqualsHashCodeCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ModifiedControlVariableCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableBothForLoops.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/modifiedcontrolvariable/InputModifiedControlVariableEnhancedForLoopVariable2.java
> Issue #10548: Migrate to Inline Config Parser in ModifiedControlVariableCheckTest

- config/checkstyle_non_main_files_checks.xml
- config/checkstyle_non_main_files_suppressions.xml
> Issue #10624: Enforce line limit 100 on all Input files

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java
> Issue #10378: Added support for violation comment on adjacent lines

- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/multiplestringliterals/InputMultipleStringLiterals6.java
> Issue #10548: Migrate to Inline Config Parser in MultipleStringLiteralsCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedForDepthCheckTest.java
> Issue #10548: Migrate to Inline Config Parser in NestedForDepthCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedIfDepthCheckTest.java
> Issue #10548: Migrate to Inline Config Parser in NestedIfDepthCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NestedTryDepthCheckTest.java
> Issue #10548: Migrate to Inline Config Parser in NestedTryDepthCheckTest

- config/checkstyle_input_checks.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitialization.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/explicitinitialization/InputExplicitInitializationOnlyObjectReference.java
Resolves #10190 
Issue #10548: Migrate to Inline Config Parser in ExplicitInitializationCheckTest
> Issue #10190: Add support for multiple violations on same line

- src/xdocs/writingchecks.xml
Update documentation to reflect comments at https://github.com/checkstyle/checkstyle/issues/8050#issuecomment-898897547.
Exact link to docs: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/26458c6_2021135057/writingchecks.html#Limitations
> doc: fix writingchecks.xml docs

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoArrayTrailingCommaCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoCloneCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoEnumTrailingCommaCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/NoFinalizerCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OneStatementPerLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/OverloadMethodsDeclarationOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanExpressionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/StringLiteralEqualityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperCloneCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/SuperFinalizeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterOuterTypeDeclarationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonAfterTypeMemberDeclarationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInEnumerationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/UnnecessarySemicolonInTryWithResourcesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLine.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/stringliteralequality/InputStringLiteralEqualityCheckTextBlocks.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/unnecessarysemicolonaftertypememberdeclaration/InputUnnecessarySemicolonAfterTypeMemberDeclarationRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/onestatementperline/InputOneStatementPerLineSingleLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/simplifybooleanexpression/InputSimplifyBooleanExpression.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceFinal.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceGeneral.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceRegExp.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/variabledeclarationusagedistance/InputVariableDeclarationUsageDistanceScopes.java
> Issue #10548: Migrate to Inline Config Parser in Tests

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTokenTextCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltokentext/InputIllegalTokenTextTokens5.java
> Issue #10527: Added support for null in inline config

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/innerassignment/InputInnerAssignment.java
> Issue #10548: Migrate to Inline Config Parser in InnerAssignmentCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestEnhancedInstanceof.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeEmptyStringMemberModifiers.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestGenerics.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestIgnoreMethodNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestLegalAbstractClassNames.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeTestPlainAndArraysTypes.java
> Issue #10548: Migrate to Inline Config Parser in IllegalTypeCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/HiddenFieldCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldEnhancedInstanceof.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenField7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldLambdas.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldReorder.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/hiddenfield/InputHiddenFieldStaticVisibility.java
> Issue #10548: Migrate to Inline Config Parser in HiddenFieldCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationonsameline/InputAnnotationOnSameLineCheck2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadDeprecated.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedBadJavadoc.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/InputMissingDeprecatedSpecialCase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingdeprecated/package-info.java
> Issue #10649: Migrate to Inline Config Parser in Annotation Check Tests

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/AvoidDoubleBraceInitializationCheck.xml
- src/xdocs/config_coding.xml
fixes 301 for updated jooq link noticed at https://github.com/checkstyle/checkstyle/runs/3373233114
> doc: update jooq link

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationAnnotation.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationCustomAnnotationsDeclared.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationDeprecatedAndCustom.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationIncorrect3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationParameterized.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/InputAnnotationLocationSingleParameterless.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationlocation/inputs/package-info.java
> Issue #10649: Migrate to Inline Config Parser in AnnotationLocationCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationUseStyleCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleDifferentStyles.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleNoTrailingComma.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithParens.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/InputAnnotationUseStyleWithTrailingCommaNever.java
> Issue #10649: Migrate to Inline Config Parser in AnnotationUseStyleCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/TestInputConfiguration.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathDoubleBrace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathExecutableStatementCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathForbidParameterizedConstructor.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathForbidPrintStackTrace.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathIllegalThrows.java
> Issue #10545: Add support for messages in inlined config

- config/checkstyle_input_suppressions.xml
> Issue #10652: Permanent suppression section at checkstyle_input_suppressions.xml

- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
> Issue #10665: Add support for multiple violations on adjacent lines in Input Parser

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/DesignForExtensionCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/FinalClassCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/design/HideUtilityClassConstructorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionNativeMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionOverridableMethods.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRequiredJavadocPhrase.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/design/designforextension/InputDesignForExtensionRequiredJavadocPhraseMultiLine.java
> Issue #10667: Migrate to Inline Config Parser in Design Check Tests

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/BooleanExpressionComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassDataAbstractionCouplingCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCouplingRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/booleanexpressioncomplexity/InputBooleanExpressionComplexity2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classdataabstractioncoupling/InputClassDataAbstractionCoupling.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexity.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityRemoveIncorrectAnnotationToken.java
> Issue #10672: Migrate to Inline Config Parser in Metric Check Tests

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ClassMemberImpliedModifierCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/InterfaceMemberImpliedModifierCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/ModifierOrderCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierFieldsOnInterface4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnClassNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierMethodsOnInterfaceNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnClassNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierNestedOnInterfaceNested.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/interfacememberimpliedmodifier/InputInterfaceMemberImpliedModifierPackageScopeInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/modifierorder/InputModifierOrderIt.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierIt.java
> Issue #10675: Migrate to Inline Config Parser in Modifier Check Tests

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/AnonInnerLengthCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/FileLengthCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodLengthCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/OuterTypeNumberCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ParameterNumberCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/RecordComponentNumberCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthRecordsAndCompactCtors.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumber.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberMax1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberMax20.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberPrivateModifier.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTopLevel1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/recordcomponentnumber/InputRecordComponentNumberTopLevel2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/filelength/InputFileLength.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodcount/InputMethodCount2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthCountEmptyIsFalse.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthModifier.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/methodlength/InputMethodLengthSimple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberSimple.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/outertypenumber/InputOuterTypeNumberSimple1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumber2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/parameternumber/InputParameterNumberSimple4.java
> Issue #10676: Migrate to Inline Config Parser in Sizes Check Tests

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthLongLink.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/linelength/InputLineLengthSimple1.java
> Issue #10676: Migrate to Inline Config Parser in LineLengthCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/LambdaBodyLengthCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthSwitchExps.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/lambdabodylength/InputLambdaBodyLengthMax.java
> Issue #10676: Migrate to Inline Config Parser in LambdaBodyLengthCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/IllegalImportCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/illegalimport/InputIllegalImportDefault1.java
> Issue #10671: Migrate to Inline Config Parser in IllegalImportCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefaultPackage.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderEclipseDefaultPositive.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderNoPackage3.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderThirdPartyAndSpecial2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderViolationsSameLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/avoidstaticimport/InputAvoidStaticImportDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderDefault4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderEmptyRule.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSingleLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderSpanMultipleLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrder_OverlappingPatterns.java
> Issue #10671: Migrate to Inline Config Parser in Imports Check Tests

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder3.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderEclipseStatic1.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderEclipseStatic2.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderEclipseStatic3.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsNegative.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupsTop.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_MultiplePatternMatches2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticGroupOrderBottom3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrderStaticOnDemandGroupOrderBottom3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_Above.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_Bottom.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_DotPackageName.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_InFlow.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_Top2.java
> Issue #10671: Migrate to Inline Config Parser in ImportOrderCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/RedundantImportCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/UnusedImportsCheckTest.java
> Issue #10671: Migrate to Inline Config Parser in Import Check Tests

- .github/workflows/pitest.yml
Resolves: #10684
Please see artifacts being produced after merge: https://github.com/AkMo3/checkstyle/actions/runs/1154147702
> Issue #10684: Pitests to produce artifact on all runs at master

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/FinalParametersCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyle.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleNestedGenerics.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/arraytypestyle/InputArrayTypeStyleOff.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenEmptyStatement.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenIllegalTokens7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenLastTokenType.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenLastTokenType2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromCatch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenReturnFromFinally6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/descendanttoken/InputDescendantTokenStringLiteralEquality.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParametersPrimitiveTypes2.java
> Issue #10693: Migrate to Inline Config Parser in Miscellaneous Check Tests

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/AvoidEscapedUnicodeCharactersCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersEscapedS.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersTextBlocks.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharactersTextBlocksAllowByComment.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters4.java
> Issue #10693: Migrate to Inline Config Parser in AvoidEscapedUnicodeCharactersCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/sizes/ExecutableStatementCountCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountCtorDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountDefaultConfig.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountInstanceInit.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountLambdas.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountMaxZero.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountMethodDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/sizes/executablestatementcount/InputExecutableStatementCountStaticInit.java
> Issue #10676: Migrate to Inline Config Parser in ExecutableStatementCountCheckTest

- pom.xml
> minor: fixed issue mismatch

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeRecords.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeInner.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadoc1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeNoJavadocOnInterface.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypePublicOnly1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerInterfaces1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeScopeInnerInterfaces2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeSkipAnnotations4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/missingjavadoctype/InputMissingJavadocTypeTags.java
> Issue #10692: Migrate to Inline Config Parser in Javadoc Check Tests

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocParagraphCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocparagraph/InputJavadocParagraphIncorrect2.java
> Issue #10692: Migrate to Inline Config Parser in JavadocParagraphCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocHtmlFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocIncorrect2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineCorrect.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineDefault.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocInlineForbidden.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocNoPeriod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriod.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/InputSummaryJavadocPeriodAtEnd.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/inputs/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/summaryjavadoc/package-info.java
> Issue #10692: Migrate to Inline Config Parser in SummaryJavadocCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/MatchXpathCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpath.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpath2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpath4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathBlockComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/matchxpath/InputMatchXpathMultilineComments.java
> Issue #10548: Migrate to Inline Config Parser in MatchXpathCheckTest

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyleRecordsAndCompactCtors.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/InputJavadocStyle9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/bothfiles/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/invalidformat/package-info.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/javadocstyle/pkginfo/invalidinherit/package-info.java
> Issue #10692: Migrate to Inline Config Parser in JavadocStyleCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/trailingcomment/InputTrailingComment2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/trailingcomment/InputTrailingComment3.java
> Issue #10564: Update inputs for TrailingCommentCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineMultilineSupport.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineMultilineSupport2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/InputRegexpMultilineSemantic9.java
> Issue #10716: Update inputs for RegexpMultilineCheckTest

- config/checkstyle_input_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaSemantic7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpsinglelinejava/InputRegexpSinglelineJavaTrailingComment9.java
> Issue #10714: Update inputs for RegexpSinglelineJavaCheckTest

- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparator2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLines.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorMultipleEmptyLinesInside.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorNewMethodDef.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorNoViolationOnEmptyLineBeforeComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPackageImportClassInOneLine.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPostFixCornerCases.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorPreviousLineEmptiness.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/emptylineseparator/InputEmptyLineSeparatorWithComments2.java
> Issue #10689: Migrate to Inline Config Parser in EmptyLineSeparatorCheckTest

- .ci/validation.sh
Fixes master build failure noticed at https://app.circleci.com/pipelines/github/checkstyle/checkstyle/8756/workflows/1f1b8545-13ad-42a9-8d68-c6e312a41acd/jobs/99903
Link to passing build in this PR: https://circleci.com/gh/checkstyle/checkstyle/99906?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> infra: update xwiki commit

- config/pmd.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AbstractModuleTestSupport.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/ModuleInputConfiguration.java
> Issue #10745: Renamed TestInputConfiguration to ModuleInputConfiguration

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/PackageDeclarationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/AllTestsTest.java
Resolves #10751 
Resolves #10732
> Issue #10751: Add ability to suppress forbidden API by annotation

- .github/workflows/pitest.yml
> infra: disable pitest pitest-report-java-ast-visitor until #10755

- config/checkstyle_input_suppressions.xml
> minor: fixed issue reference

- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilterTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/filefilters/beforeexecutionexclusionfilefilter/InputBeforeExecutionExclusionFileFilterIncorrectClass.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filefilters/beforeexecutionexclusionfilefilter/InputBeforeExecutionExclusionFileFilter.java
> Issue #10737: Migrate to Inline Config Parser for BeforeExecutionExclusionFileFilterTest

- src/test/java/com/puppycrawl/tools/checkstyle/JavaAstVisitorTest.java
Recognized by @rnveach in Java 6 backport.
> minor: refactor JavaAstVisitorTest

- .ci/drone-io.sh
- .drone.yml
> Issue #10065: cache for Drone ci maven dependencies

- .drone.yml
Detected at https://github.com/checkstyle/checkstyle/pull/10679#discussion_r702440577
> infra: remove extra volume block from drone.yml

- .travis.yml
Issue #10778
To make CI green again.
> Issue #10778: disabled problem travis items until fixed

- .ci/wercker.sh
https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/537716352#L643
```
* What went wrong:
Error resolving plugin [id: 'com.github.autostyle', version: '3.1']
> Could not resolve all dependencies for configuration 'detachedConfiguration2'.
> Could not determine artifacts for com.github.autostyle:com.github.autostyle.gradle.plugin:3.1
> Could not get resource 'https://plugins.gradle.org/m2/com/github/autostyle/com.github.autostyle.gradle.plugin/3.1/com.github.autostyle.gradle.plugin-3.1.jar'.
> Could not HEAD 'https://jcenter.bintray.com/com/github/autostyle/com.github.autostyle.gradle.plugin/3.1/com.github.autostyle.gradle.plugin-3.1.jar'.
> Read timed out
```
> Fix pjdbc build

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/DefaultConfiguration.java
- src/main/java/com/puppycrawl/tools/checkstyle/JavaAstVisitor.java
- src/main/java/com/puppycrawl/tools/checkstyle/ThreadModeSettings.java
- src/main/java/com/puppycrawl/tools/checkstyle/api/Violation.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/UniquePropertiesCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/SuppressWarningsCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/SimplifyBooleanReturnCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/indentation/CommentsIndentationCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/naming/AccessModifierOption.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/sizes/MethodCountCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/GenericWhitespaceCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/SingleSpaceSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoader.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/ListToTreeSelectionModelWrapper.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/MainFrame.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTable.java
- src/main/java/com/puppycrawl/tools/checkstyle/gui/TreeTableModelAdapter.java
Issue #10818 
Three commits with fixes and one to set javadoc level to `private`
> Issue #10818: add/fix javadoc for private types and members

- config/checkstyle_checks.xml
Followup for #10818 
Detected at https://github.com/checkstyle/checkstyle/pull/10819#discussion_r715090428
> config: forbid undocumented private getters (#10818)

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEmptyStatementTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/emptystatement/SuppressionXpathRegressionEmptyStatement1.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/emptystatement/SuppressionXpathRegressionEmptyStatement2.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partial for Issue: #6207 
Add xpath regression test for EmptyStatement
> Issue #6207: Add xpath regression test for EmptyStatement

- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/meta/ModuleDetails.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java
Attempt to increase code coverage.
> minor: increase code coverage for meta data packages

- src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionEmptyBlockTest.java
- src/it/resources/org/checkstyle/suppressionxpathfilter/emptyblock/SuppressionXpathRegressionEmptyBlockEmpty.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
Partial for Issue: #6207
Add xpath regression test for EmptyBlock
> Issue #6207: Add Xpath Regression Test for EmptyBlock

- .ci/jsoref-spellchecker/whitelist.words
- pom.xml
- src/main/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReader.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/XmlMetaReaderTest.java
Issue #10773
Tested with eclipse-cs test area and it solved the issue.
> Issue #10773: suppress false scanner exception in xml meta reader

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Resolves #9396
```
vinayak@Gladiator:~/Documents$ cat Test.java
class Test{
public static void main(String args[]){
Derived d1 = new Derived();
d1.set(1);
}
}
class Base {
protected int num;
public void set() {}
}
class Derived extends Base {
@Override
public void set(int n) {
this.num = n;
}
}
vinayak@Gladiator:~/Documents/Opensource/checkstyle/target$ java -jar checkstyle-8.45-SNAPSHOT-all.jar -T /home/vinayak/Documents/Test.java
|   | …
```
> Issue #9396: Add example of AST for TokenTypes.AT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes Issue #9419:
Java Code Used:
<pre>
<code>
import java.util.function.Function;
public static double square(double num) {
return Math.pow(num, 2);
}
Function&lt;Double, Double&gt; square = MyClass::square;
double ans = square.apply(23d);
}
</code>
</pre>
AST  FORMAT OF Java code:
<pre>
<code>
|--IMPORT -> import [1:0]
|   |--DOT -> . [1:25]
|   |   |--DOT -> . [1:16]
|   |   |   |--DOT -> . [1:11]
|   |   |   |   |--IDENT -> java [1:7]
|   |   |   |   `--IDENT -> util [1:12]
|   |   |   `--IDENT -> function [1:17]
|   |   `--IDENT -> Function [1:26]
|   `--SEMI -> ; [1:34]
`--CLASS_DEF -> CLASS_DEF [3:0] …
> Issue #9419: created example of AST for TokenTypes.DOUBLE_COLON

- pom.xml
From azure master build
https://dev.azure.com/romanivanovjr/romanivanovjr/_build/results?buildId=5807&view=logs&j=1a6076f9-5826-5ba0-19ba-deaff2e35eea&t=5f46bc98-6f46-512e-6656-5fbfb1d03e4d&l=602
> config: bump reflection version to 0.10.2

- .ci/jsoref-spellchecker/whitelist.words
- .travis.yml
Issue #10778
sounds like unlimited parallelism:
It might be awesome benefits of this arch in Travis
> Issue #10778: switch to ppc64le arch to avoid usage of paid credits

- .ci/jsoref-spellchecker/whitelist.words
- .travis.yml
Reverts checkstyle/checkstyle#10918
> Revert "Issue #10778: switch to ppc64le arch to avoid usage of paid credits"

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter10.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter11.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter5.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter6.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter7.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter8.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilter9.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilterSuppressById2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilterSuppressById3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilterSuppressById4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressioncommentfilter/InputSuppressionCommentFilterSuppressById5.java
> Issue #10737: Migrate to Inline Config Parser for SuppressionCommentFilterTest

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes Issue #9458:
Java Code Used:
<pre>
<code>
ArrayList<Integer> numbers = new ArrayList<>();
numbers.add(1);
numbers.forEach((n) -> System.out.println(n));
}
}
</code>
</pre>
AST  FORMAT OF Java code:
<pre>
<code>
|--IMPORT -> import [1:0]
|   |--DOT -> . [1:16]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> java [1:7]
|   |   |   `--IDENT -> util [1:12]
|   |   `--IDENT -> ArrayList [1:17]
|   `--SEMI -> ; [1:26]
`--CLASS_DEF -> CLASS_DEF [3:0]
|--IDENT -> MyClass [3:13]
`--OBJBLOCK -> OBJBLOCK [3:21]
|--LCURLY -> { [3:21]
|--METHOD_DEF -> …
> Issue #9458: updated example of AST for TokenTypes.LAMBDA

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9551
```
**Test.java**
public class Test { 
void foo(int firstParameter, int... secondParameter) {}
}
**AST**
java -jar checkstyle-9.0.1-all.jar -t Test.java
`--CLASS_DEF -> CLASS_DEF [4:0]
|--MODIFIERS -> MODIFIERS [4:0]
|   `--LITERAL_PUBLIC -> public [4:0]
|--LITERAL_CLASS -> class [4:7]
|--IDENT -> Test [4:13]
`--OBJBLOCK -> OBJBLOCK [4:18]
|--LCURLY -> { [4:18]
|--METHOD_DEF -> METHOD_DEF [5:2]
|   |--MODIFIERS -> MODIFIERS [5:2]
|   |--TYPE -> TYPE [5:2]
|   |   `--LITERAL_VOID -> void [5:2]
|   |--IDENT -> foo [5:7]
|   |--LPAREN -> ( [5:10]
|   |--PARAMETERS -> PARAMETERS [5:11]
|   |   |--PARAMETER_DEF -> PARAMETER_DEF [5:11]
|   |   |   |--MODIFIERS -> MODIFIERS [5:11]
|   |   |   |--TYPE -> TYPE [5:11]
|   |   |   |   `--LITERAL_INT -> int [5:11]
|   |   |   `--IDENT …
```
> update example of AST for TokenTypes.PARAMETERS

- .ci/travis/travis.sh
- .travis.yml
partial for #10778
addressing https://github.com/checkstyle/checkstyle/issues/10778#issuecomment-962530901
final fix will be activation of arch.
> 10778 ppc arch

- config/checkstyle_checks.xml
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/AbstractClassCouplingCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CheckUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/metrics/ClassFanOutComplexityCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CheckUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityImplementsAndNestedCount.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/metrics/classfanoutcomplexity/InputClassFanOutComplexityMultiCatchBitwiseOr.java
Closes #10144
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/f555bc03ede3366afdd92cfe337d12565591b96a/confg.xml
TODO items
> Issue #10144: fix classes count on multicatch and implements clause

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes Issue #9485 example of AST for TokenTypes.LITERAL_NATIVE
> Issue #9485: updated example of AST for TokenTypes.LITERAL_NATIVE

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/metrics/NPathComplexityCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/EmptyLineSeparatorCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheck.java
> minor: refactor few if statements to simplify them

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullSuperClass.java
Closes #10962 
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/9b153902a204a5e9b1a7b0445cfa6b7715499e30/confg.xml
Report (clean) https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/a921658_2021160443/reports/diff/index.html
> Issue #10962: fix NPE in EqualsAvoidNullCheck

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/OperatorWrapCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapArrayAssign.java
Closes #10945, fixed wrapping for assign of annotation array
Diff Regression config: https://gist.githubusercontent.com/strkkk/31749e0743553a606f69fdfc6670d780/raw/2d7b9780d1fee9def8b7671b8a96e2490021575f/confg.xml
> Issue #10945: fix wrap check for annotation array

- crowdin.yml
change escape policy to disable auto escape
> config: change escape single quotes policy for crowdin

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
> Issue #9450: update example of AST for TokenTypes.IDENT

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Fixes #9387 : update example of AST for TokenTypes.ANNOTATION
Test.java file:
```
@MyAnnotation(someField1 = "Hello",
someField2 = @SomeOtherAnnotation)
public class Test {}
```
AST printed through CLI:
```
|   |--ANNOTATION -> ANNOTATION [1:0]
|   |   |--AT -> @ [1:0]
|   |   |--IDENT -> MyAnnotation [1:1]
|   |   |--LPAREN -> ( [1:13]
|   |   |--ANNOTATION_MEMBER_VALUE_PAIR -> ANNOTATION_MEMBER_VALUE_PAIR [1:14]
|   |   |   |--IDENT -> someField1 [1:14]
|   |   |   |--ASSIGN -> = [1:25]
|   |   |   `--EXPR -> EXPR [1:27]
|   |   |       `--STRING_LITERAL -> "Hello" [1:27]
|   |   |--COMMA -> , [1:34]
|   |   |--ANNOTATION_MEMBER_VALUE_PAIR -> ANNOTATION_MEMBER_VALUE_PAIR [2:20]
| …
```
> Issue #9387: updated example of AST for TokenTypes.ANNOTATION

- src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/customimportorder/InputCustomImportOrderEclipseDefaultPositive.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_EclipseDefaultNegative.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/imports/importorder/InputImportOrder_EclipseDefaultPositive.java
Issue #10932 
Small commit to remove dependency on powermock from test inputs.
> Issue #10932: replace Powermock imports in test inputs

- config/checkstyle_non_main_files_suppressions.xml
> Issue #10625: Removed InputEqualsAvoidNullEnhancedInstanceof.java from linelength suppression

- .github/workflows/site.yml
Similar to https://github.com/checkstyle/checkstyle/pull/11010
> infra: extract variables for site generation action to improve security

- config/suppressions.xml
- pom.xml
- src/test/java/com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/nonemptyatclausedescription/InputNonEmptyAtclauseDescription.java
Resolves #10752: Added support for violation N lines above/below in Inline Config Parser
Issue #10692: Migrate to Inline Config Parser in Javadoc Check Tests
> Issue #10752: Added support for violation N lines above/below in Inline Config Parser

- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/AbstractParenPadCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/checks/whitespace/NoWhitespaceBeforeCheck.java
- src/main/java/com/puppycrawl/tools/checkstyle/utils/CommonUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/ParenPadCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/CommonUtilTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/whitespace/parenpad/InputParenPadCheckEmoji.java
Closes #11001 .
Diff Regression config: https://gist.githubusercontent.com/nmancus1/8eb01d0872a0abb22f818b802750a470/raw/c1474267ec16c4e3e9d7b035f112ed2952737f79/config.xml
Diff report(Clean): https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/6032fab_2021155411/reports/diff/index.html
> Issue #11001: False positive for Whitespace Before Paren After String with emojis

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
- src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/IllegalTypeCheck.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersDefault.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersFinal.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersPrivateFinal.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/illegaltype/InputIllegalTypeRecordsWithMemberModifiersPublicProtectedStatic.java
- src/xdocs/config_coding.xml
Fixes #10817
Diff Regression config: https://gist.githubusercontent.com/Rahulkhinchi03/7b19d57cd13d1d2904ab523a61f7f300/raw/5784d380be13aec65a30e5042a18ddb25b20308a/config.xml
> Issue #10817: Fix IllegalTypeCheck on Record with configured member modifiers

- src/main/java/com/puppycrawl/tools/checkstyle/api/TokenTypes.java
Closes: #9420 
**Test.java file:**
```
new ArrayList<>(50);
}
}
```
AST printed through CLI:
```
|--IMPORT -> import [1:0]
|   |--DOT -> . [1:16]
|   |   |--DOT -> . [1:11]
|   |   |   |--IDENT -> java [1:7]
|   |   |   `--IDENT -> util [1:12]
|   |   `--IDENT -> ArrayList [1:17]
|   `--SEMI -> ; [1:26]
`--CLASS_DEF -> CLASS_DEF [2:0]
|--IDENT -> Test [2:13]
`--OBJBLOCK -> OBJBLOCK [2:18]
|--LCURLY -> { [2:18]
|--METHOD_DEF -> METHOD_DEF [3:5]
|   |--MODIFIERS -> MODIFIERS [3:5]
|   |   |--LITERAL_PUBLIC -> public [3:5]
|   |   `--LITERAL_STATIC -> static …
```
> Issue #9420: create example of AST for TokenTypes.ELIST

- src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_es.properties
- src/main/resources/com/puppycrawl/tools/checkstyle/checks/blocks/messages_fi.properties
Related to crowdin integration. Adds missing quotes to translations.
> minor: add missing quotes in translation

- .ci/travis/travis.sh
- .travis.yml
> Issue #11027: make all commands in travis.yml as single command

- config/checkstyle_non_main_files_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/equalsavoidnull/InputEqualsAvoidNullTextBlocks.java
> Issue #10625: Fixed InputEqualsAvoidNullTextBlocks.java and removed it from linelength suppression

- config/checkstyle_non_main_files_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideBadAnnotation.java
> Issue #10625: Fixed InputMissingOverrideBadAnnotation.java file and removed it from linelength suppression

- config/checkstyle_non_main_files_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingOverrideCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/annotation/missingoverride/InputMissingOverrideNotOverride.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/avoidescapedunicodecharacters/InputAvoidEscapedUnicodeCharacters1.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/declarationorder/InputDeclarationOrderInterfaceMemberScopeIsPublic.java
> Issue #10625: Fixed three input files and removed them from line length suppression

- src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheck.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ParameterAssignmentCheckTest.java
- src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentWithEnhancedSwitch.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/coding/parameterassignment/InputParameterAssignmentWithUnchecked.java
- src/xdocs/config_coding.xml
Resolves #11038: ParameterAssignment does not detect problem for Lambda parameters
Diff Regression config: https://gist.githubusercontent.com/Vyom-Yadav/98dceb63a79f4833e85fff9b2e1464a6/raw/d1ab97a1c9993af82ee2bbc444dc16382427bf43/my_checks.xml
Final Report (clean) - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/b2b6388_2021204140/reports/diff/index.html
> Issue #11038: ParameterAssignment now detects problems for Lambda parameters

- pom.xml
> Issue #7368: remove junit4 dependencies

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/DefinitionsTest.java
> Issue #9142: resolve DefinitionsTest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/AuditEventDefaultFormatterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/JavadocDetailNodeParserTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/FullIdentTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OrderedPropertiesCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/OuterTypeFilenameCheckTest.java
> Issue 9142 2

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/TrailingCommentCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationOnSameLineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/annotation/PackageAnnotationCheckTest.java
> Issue 9142 3

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidNoArgumentSuperConstructorCallCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/CovariantEqualsCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/DefaultComesLastCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EmptyStatementCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheckTest.java
> Issue 9142 5

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/AvoidNestedBlocksCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/blocks/EmptyCatchBlockCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/ArrayTrailingCommaCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidDoubleBraceInitializationCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/coding/AvoidInlineConditionalsCheckTest.java
> Issue 9142 4

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/gui/CodeSelectorPresentationTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/utils/XmlUtil.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/BlockCommentPositionTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
> Issue 9142 6

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/StaticVariableNameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpSinglelineJavaCheckTest.java
> Issue 9142 7

- src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithPlainTextCommentFilterTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilter.js
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterCustomMessageFormat.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById2.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById3.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById4.java
- src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppresswithplaintextcommentfilter/InputSuppressWithPlainTextCommentFilterSuppressById5.java
> Issue #10737: Migrate to Inline Config Parser for SuppressWithPlainTextCommentFilterTest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/PropertiesExpanderTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/api/TokenTypesTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/ArrayTypeStyleCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java
> Issue 9142 8

- config/import-control-test.xml
- src/test/java/com/puppycrawl/tools/checkstyle/xpath/XpathMapperTest.java
Issue #9142
As I understand this issue, hamcrest shouldn't be allowed either.
> Issue #9142: forbid hamcrest

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filefilters/BeforeExecutionExclusionFileFilterTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/CsvFilterElementTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/IntMatchFilterElementTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/filters/IntRangeFilterElementTest.java
> Issue 9142 10

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PackageNameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/PatternVariableNameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordComponentNameCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/naming/RecordTypeParameterNameCheckTest.java
> Issue 9142 11

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XdocsMobileWrapperTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/meta/JavadocMetadataScraperTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/FilterUtilTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/utils/ParserUtilTest.java
> Issue 9142 9

- config/suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocPackageCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocTypeCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/RequireEmptyLineBeforeBlockTagGroupCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SingleLineJavadocCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheckTest.java
- src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/WriteTagCheckTest.java
> Issue 9142 12

- pom.xml
> config: move mockito to test dependecies (#11065)

- config/checkstyle_non_main_files_suppressions.xml
- src/test/java/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheckTest.java
- src/test/resources/com/puppycrawl/tools/checkstyle/checks/modifier/redundantmodifier/InputRedundantModifierFinalInTryWithResource.java
> Issue #10625: Fixed InputRedundantModifierFinalInTryWithResource.java git push origin my-new-check
